### ISSUE TITLE
privotal greenplum command center Error"Query details cannot be displayed"

### ISSUE THREAD

**Issue by ketra21** [greenplum-db/gpdb#10004]
### Greenplum version or build
Greenplum Database 5.11.1
### OS version and uname -a
x86_64-pc-linux-gnu, compiled by GCC gcc (GCC) 6.2.0, 64-bit
### Expected behavior
We usuaIIy see the query detail ,but now it's don't displayed,I restart it but not work.
![image](https://user-images.githubusercontent.com/38323732/80332216-c58e9700-887c-11ea-8f3b-4674b75d7631.png)

### Actual behavior

Error"Query details cannot be displayed"

![image](https://user-images.githubusercontent.com/38323732/80331790-9a577800-887b-11ea-87ac-38beaeae68fb.png)

**Comment by Eulerizeit** [comment]
GPCC is a closed source component and not contained in this repo. 

Please contact support for this issue.
