### ISSUE TITLE
gp_enable_global_deadlock_detector GUC should not be repurposed

### ISSUE THREAD

**Issue by asimrp** [greenplum-db/gpdb#10030]
### Greenplum version or build
Master and 6X

### Expected behavior
The GUC `gp_enable_global_deadlock_detector` should only be used to enable GDD and nothing else, as the name suggests.

### Actual behavior
The GUC is not only used on QD to start GDD but also used to determine the lock mode on QD as well as QEs and a few other things.

All uses of this GUC other than to start GDD should be replaced with an interface such as `IsGlobalDeadlockDetectorRunning()` that should return true on QD if GDD process is found running.  On QE, whether GDD is running or not should be included as a dispatch parameter, so that `IsGlobalDeadlockDetectorRunning()` can work on QEs.

Context: https://github.com/greenplum-db/gpdb/pull/9992#pullrequestreview-402364938

**Comment by hlinnaka** [comment]
Hmm. So is there some other GUC to actually enable/disable global deadlock detection?

**Comment by asimrp** [comment]
This GUC is the one used to enable global deadlock detector, but it's repurposed for some additional decisions on QE.

**Comment by kainwen** [comment]
Fixed by

*  https://github.com/greenplum-db/gpdb/pull/10408 on 6X 
*  https://github.com/greenplum-db/gpdb/pull/10401 on master 

------------------------------------------

Now, the GUC `gp_enable_global_deadlock_detector ` is only used in master node.
