### ISSUE TITLE
Set SO_REUSEPORT to avoid too many ports taken up by TCP interconnect

### ISSUE THREAD

**Issue by hidva** [greenplum-db/gpdb#10048]
Currently, a QE will take up about `n * m` ports during a query execution when gp_interconnect_type is TCP, and `n` is the number of slices, `m` is the number of primary segments. 

We can reduce the number of ports used to 2 with the usage of `SO_REUSEPORT`. More specifically, we can bind all send sockets in QE to the same local address by using SO_REUSEPORT, just like:

```python
import socket
sendsocket1 = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
sendsocket2 = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
sendsocket1.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEPORT, 1)
sendsocket2.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEPORT, 1)
sendsocket1.bind(('', 33333)) # 33333 is a port chose randomly.
sendsocket2.bind(('', 33333)) # also bound at 33333
sendsocket1.connect(('hidva.com', 33330))  # hidva.com:33330 is a receiver QE
sendsocket2.connect(('hidva.com', 33331))  # hidva.com:33331 is another receiver QE
```

Here, we use the same local port to connect two QEs. And `lsof -nPp` shows that all send sockets have bound at the same local address

```
Python zhanyi IPv4 TCP 30.225.140.26:33333->180.76.167.43:33330 (ESTABLISHED)
Python zhanyi IPv4 TCP 30.225.140.26:33333->180.76.167.43:33331 (ESTABLISHED)
```

So we can make the following changes to `setupOutgoingConnection()` in ic_tcp.c to reduce the number of ports used by send sockets.

```diff
diff --git a/src/backend/cdb/motion/ic_tcp.c b/src/backend/cdb/motion/ic_tcp.c
index 9875d7562c..a6ef971cd1 100644
--- a/src/backend/cdb/motion/ic_tcp.c
+++ b/src/backend/cdb/motion/ic_tcp.c
@@ -674,6 +674,29 @@ setupOutgoingConnection(ChunkTransportState *transportStates, ChunkTransportStat
        {                                                       /* connect() EINTR retry loop */
                ML_CHECK_FOR_INTERRUPTS(transportStates->teardownActive);
 
+               int one = 1;
+               if ((setsockopt(conn->sockfd, SOL_SOCKET, SO_REUSEPORT, (char *) &one, sizeof(one))) == -1)
+                       _exit(2);  // just for DEBUG
+               struct sockaddr_in sndaddr;
+               memset(&sndaddr, 0, sizeof(sndaddr));
+               sndaddr.sin_family = AF_INET;
+               sndaddr.sin_addr.s_addr = htonl(INADDR_ANY);  
+               sndaddr.sin_port = g_sendport;  
+               // g_sendport is a static variable, its initial value is htons(0).
+               // In the first call of setupOutgoingConnection, the bind() will choose an unused port randomly, 
+               // and we will get the port via getsockname(), and assign it to g_sendport,
+               // it means that the following call of setupOutgoingConnection() will use the same port.
+               if (bind(conn->sockfd, &sndaddr, sizeof(sndaddr)) < 0)
+                       _exit(3);  // just for DEBUG
+               if (g_sendport == 0) {
+                       struct sockaddr local_addr;
+                       socklen_t len = sizeof(sockaddr);
+                       if (getsockname(conn->sockfd, &local_addr, &len) != 0)
+                               _exit(4);
+                       struct sockaddr_in *laddr = (struct sockaddr_in*)&local_addr;
+                       g_sendport = laddr->sin_port;                   
+               }
+
                n = connect(conn->sockfd, addrs->ai_addr, addrs->ai_addrlen);
 
                /* Non-blocking socket never connects immediately, but check anyway. */
```

**Comment by hidva** [comment]
@pivotal-ning-yu

**Comment by zhangh43** [comment]
Hi @hidva 
TCP interconnect do has port number issue. icproxy interconnect is used to fix this problem by introducing a proxy background worker for each postmaster. Remote traffic among segments will only go through proxy. Local traffic between backend and proxy is implemented by domain socket.

As for your proposal to use SO_REUSEPORT, in my understanding, SO_REUSEPORT's use case is to support multiple thread listens on the same host&port and kernel will distribute (load balancer) the traffic to each thread to improve the performance. But in greenplum, each QE(motion receiver) will handle it's specific incoming traffic. How does kernel knows how to dispatch a packet to the right motion receiver? Please correct me if my understanding is wrong.

**Comment by hidva** [comment]
@zhangh43 Through SO_REUSEPORT, we can make **different connections use the same local port** as follow:

```python
# SenderQE1 use 33333 as the local port to connect one receiver QE ReceiverQE1
# netstat: SenderQE1:33333-> ReceiverQE1 (ESTABLISHED)
sendsocket1 = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
sendsocket1.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEPORT, 1)
sendsocket1.bind(('', 33333)) # 33333 is a port chose randomly.
sendsocket1.connect(ReceiverQE1)  
```

```python
# SenderQE1 still use 33333 as the local port to connect another receiver QE ReceiverQE2
# netstat: SenderQE1:33333-> ReceiverQE2 (ESTABLISHED)
sendsocket2 = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
sendsocket2.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEPORT, 1)
sendsocket2.bind(('', 33333)) # also bound at 33333
sendsocket2.connect(ReceiverQE2)  
``` 

Suppose we have a query which has 4 slices and the query is running on a cluster which has 3 primary segments.

|  PrimarySegment1   | PrimarySegment2  | PrimarySegment3  | |
|  ----  | ----  | ----  | ----  | 
| QE_slice3content1  | QE_slice3content2 | QE_slice3content3 | slice3 |
| QE_slice2content1  | QE_slice2content2 | QE_slice2content3 | slice2 |
| QE_slice1content1  | QE_slice1content2 | QE_slice1content3 | slice1 |
| QE_slice0content1  | QE_slice0content2 | QE_slice0content3 | slice0 |

Without SO_REUSEPORT, every QE will use 1 (used as `tcp_listener`) + NumberOfPrimarySegments(used for connect QEs in parent slice) local ports:

```
QE_slice2content1 use port1 as the tcp_listener.
QE_slice2content1 use port2 to connect QE_slice1content1
QE_slice2content1 use port3 to connect QE_slice1content2
QE_slice2content1 use port4 to connect QE_slice1content3
```

But with SO_REUSEPORT,  every QE will use only 2 local ports, one for listening, one for connecting:

```
QE_slice2content1 use port1 as the tcp_listener.
QE_slice2content1 use port2 to connect QE_slice1content1
QE_slice2content1 use port2 to connect QE_slice1content2
QE_slice2content1 use port2 to connect QE_slice1content3
```

**Comment by zhangh43** [comment]
It sounds reasonable to me with the help of your explanation.
Would you like submit a patch and we could test the behavior and especially the performance impact of your proposal.

**Comment by hidva** [comment]
Ok, I will submit a PR today,

**Comment by hidva** [comment]
@zhangh43 PTAL https://github.com/greenplum-db/gpdb/pull/10782

**Comment by hidva** [comment]
Close this issue as discussed in #10782
