### ISSUE TITLE
Error with expand

### ISSUE THREAD

**Issue by T0125** [greenplum-db/gpdb#1004]
When I expanded segments with gpexpand command , it told me “ 'ERROR:  relation pg_catalog.gp_verification_history" does not exist ”,and exit.
After checking in pg_catalog catalog,and gp_toolkit catalog,the relation does not exist.

**Comment by kaknikhil** [comment]
Hi T0125 ,

Thanks for reporting the issue ,  commit https://github.com/greenplum-db/gpdb/commit/46c61428e8bcbe619021bee18c4ad0ef71370bdf should have fixed this issue. Are you using the latest source code ?

**Comment by T0125** [comment]
@kaknikhil 
Thanks a lot !
With your help, I solved the problem successfully.
By the way , I used the lastest code from github.
