### ISSUE TITLE
Failed to compile redis_fdw due to lack of ExecStoreTuple

### ISSUE THREAD

**Issue by yydzero** [greenplum-db/gpdb#10044]
Greenplum changed ExecStoreTuple to ExecStoreHeapTuple, while some FDW implementations such as redis are using this function.

PostgreSQL 12 uses ExecStoreHeapTuple instead of ExecStoreTuple, so this won't be a problem for Greenplum 7, and only an issue for Greenplum 6.

**Comment by adam8157** [comment]
Fixed by #10045
