### ISSUE TITLE
Too many distributed transactions for snapshot (procarray.c:1900)

### ISSUE THREAD

**Issue by nicholascp** [greenplum-db/gpdb#10057]
### Step to reproduce the behavior

PostgreSQL 9.4.24 (Greenplum Database 6.3.0 build commit:77aa1b6e4486adbaede9f5f2864a04fc3a512e93) on x86_64-unknown-linux-gnu, compiled
 by gcc (GCC) 6.4.0, 64-bit compiled on Jan 13 2020 22:04:43
(1 row)

postgres=# select count(*) from pg_stat_activity ;

"ERROR","XX000","Too many distributed transactions for snapshot (procarray.c:1900)"

**Comment by ashwinstar** [comment]
@nicholascp with what's provided here we can't act on it. So, please provide details like repro, how many concurrent sessions are running and such info to investigate the issue else unfortunately the issue cannot go any further.

**Comment by paul-guo-** [comment]
I previously encountered this issue also. Now seeing this issue with the test in my backport PR https://github.com/greenplum-db/gpdb/pull/10496. Will fix this in a separate PR. This should be relevant of max_prepared_xacts

**Comment by paul-guo-** [comment]
Pushed the code change. Closing the issue.
