### ISSUE TITLE
devtoolset-6-toolchain is removed

### ISSUE THREAD

**Issue by wlooong** [greenplum-db/gpdb#10069]
According to https://github.com/greenplum-db/gpdb/blob/master/README.linux.md, centos can install devtoolset-6-toolchain.
However 'devtoolset-6-toolchain' is removed from epel-release. There is no 'devtoolset-6-toolchain' anymore.
How deal with that? Or should you update the page 'https://github.com/greenplum-db/gpdb/blob/master/README.linux.md'?

**Comment by tylarb** [comment]
Devtoolset-7 works to compile master. I'll update the documentation accordingly. 

Thanks for pointing this out!

**Comment by tylarb** [comment]
@wlooong can you confirm that the updated steps in https://github.com/greenplum-db/gpdb/pull/10458 address your issues?

**Comment by wlooong** [comment]
Nice!
