### ISSUE TITLE
Why I set work_mem to 2048MB, when I execute gpconfig -s work_mem, it is still 32MB

### ISSUE THREAD

**Issue by GuoLiuFang** [greenplum-db/gpdb#1009]
I have restart Greenplum. the value of work mem do not changes. But postgresql.conf have changed.
Can anybody explain this?And how to set work_mem successfully?

**Comment by cjcjameson** [comment]
Hi there! Just wanted to let you know that a new flag to gpconfig got merged, thanks to @Chibin and @skahler-pivotal -- thanks for your feedback.
