### ISSUE TITLE
wrong plan

### ISSUE THREAD

**Issue by yydzero** [greenplum-db/gpdb#10131]
```
greenplum 6:

create table t1 (a int, b int, c int, d int);
create table t2 (a int, b int, c int, d int);
insert into t1 values (1, 2), (3, 4);
insert into t2 values (4, 4);

select * from t1 where exists (select sum(a) from t2  where t1.a = t2.a);
 a | b | c | d
---+---+---+---
 3 | 4 |   |
 1 | 2 |   |
(2 rows)

explain select * from t1 where exists (select sum(a) from t2  where t1.a = t2.a);
                                 QUERY PLAN
-----------------------------------------------------------------------------
 Gather Motion 2:1  (slice1; segments: 2)  (cost=0.00..2.02 rows=2 width=16)
   ->  Seq Scan on t1  (cost=0.00..2.02 rows=1 width=16)
 Optimizer: Postgres query optimizer
(3 rows)
```

**Comment by yydzero** [comment]
@kainwen @gaos1

**Comment by kainwen** [comment]
Postgres 12 will generate the plan:

```sql
zlv=# explain select * from t1 where exists (select sum(a) from t2  where t1.a = t2.a);
                           QUERY PLAN
-----------------------------------------------------------------
 Seq Scan on t1  (cost=0.00..61369.87 rows=925 width=16)
   Filter: (SubPlan 1)
   SubPlan 1
     ->  Aggregate  (cost=33.15..33.16 rows=1 width=8)
           ->  Seq Scan on t2  (cost=0.00..33.12 rows=9 width=4)
                 Filter: (t1.a = a)
(6 rows)

zlv=# select * from t1 where exists (select sum(a) from t2  where t1.a = t2.a);
 a | b | c | d
---+---+---+---
 1 | 2 |   |
 3 | 4 |   |
(2 rows)

zlv=# select version();
                                                       version
---------------------------------------------------------------------------------------------------------------------
 PostgreSQL 12devel on x86_64-apple-darwin18.2.0, compiled by Apple LLVM version 10.0.0 (clang-1000.11.45.5), 64-bit
(1 row)
```

On gpdb6, both ORCA and planner generate the same plan:

```sql
gpadmin=# explain select * from t1 where exists (select sum(a) from t2  where t1.a = t2.a);
                                  QUERY PLAN
-------------------------------------------------------------------------------
 Gather Motion 3:1  (slice1; segments: 3)  (cost=0.00..431.00 rows=2 width=16)
   ->  Seq Scan on t1  (cost=0.00..431.00 rows=1 width=16)
 Optimizer: Pivotal Optimizer (GPORCA)
(3 rows)

gpadmin=# set optimizer = off;
SET
gpadmin=# explain select * from t1 where exists (select sum(a) from t2  where t1.a = t2.a);
                                 QUERY PLAN
-----------------------------------------------------------------------------
 Gather Motion 3:1  (slice1; segments: 3)  (cost=0.00..2.02 rows=2 width=16)
   ->  Seq Scan on t1  (cost=0.00..2.02 rows=1 width=16)
 Optimizer: Postgres query optimizer
(3 rows)
```

------------------

The where condition is gone in Greenplum. However, IMO, this kind of optimization seems reasonable.
A subquery without any group clause and contains an agg in the projection it will produce at least one tuple even the table scan output no data. So in the case of this issue, we can deduce that the qual on t1 will always be true.

If the agg in subquery contains group by, things get different:

```sql
gpadmin=# explain select * from t1 where exists (select max(a) from t2  where t1.a = t2.a group by b);
                                 QUERY PLAN
-----------------------------------------------------------------------------
 Gather Motion 3:1  (slice1; segments: 3)  (cost=1.02..3.08 rows=4 width=16)
   ->  Hash Semi Join  (cost=1.02..3.08 rows=2 width=16)
         Hash Cond: (t1.a = t2.a)
         ->  Seq Scan on t1  (cost=0.00..2.02 rows=1 width=16)
         ->  Hash  (cost=1.01..1.01 rows=1 width=4)
               ->  Seq Scan on t2  (cost=0.00..1.01 rows=1 width=4)
 Optimizer: Postgres query optimizer
(7 rows)

gpadmin=# set optimizer = on;
SET
gpadmin=# explain select * from t1 where exists (select max(a) from t2  where t1.a = t2.a group by b);
                                    QUERY PLAN
----------------------------------------------------------------------------------
 Gather Motion 3:1  (slice1; segments: 3)  (cost=0.00..862.00 rows=1 width=16)
   ->  Hash Semi Join  (cost=0.00..862.00 rows=1 width=16)
         Hash Cond: (t1.a = t2.a)
         ->  Seq Scan on t1  (cost=0.00..431.00 rows=1 width=16)
         ->  Hash  (cost=431.00..431.00 rows=1 width=4)
               ->  GroupAggregate  (cost=0.00..431.00 rows=1 width=4)
                     Group Key: t2.a, t2.b
                     ->  Sort  (cost=0.00..431.00 rows=1 width=8)
                           Sort Key: t2.a, t2.b
                           ->  Seq Scan on t2  (cost=0.00..431.00 rows=1 width=8)
 Optimizer: Pivotal Optimizer (GPORCA)
(11 rows)
```

Actually, I have come to the dummy plan of agg before when doing optimization on tpcds. In gpdb6, we have dumpy_plan test but does not handle agg.

**Comment by d** [comment]
Thank you @yydzero for creating this issue.

> ```
> greenplum 6:
> 
> create table t1 (a int, b int, c int, d int);
> create table t2 (a int, b int, c int, d int);
> insert into t1 values (1, 2), (3, 4);
> insert into t2 values (4, 4);
> 
> select * from t1 where exists (select sum(a) from t2  where t1.a = t2.a);
>  a | b | c | d
> ---+---+---+---
>  3 | 4 |   |
>  1 | 2 |   |
> (2 rows)
> 
> explain select * from t1 where exists (select sum(a) from t2  where t1.a = t2.a);
>                                  QUERY PLAN
> -----------------------------------------------------------------------------
>  Gather Motion 2:1  (slice1; segments: 2)  (cost=0.00..2.02 rows=2 width=16)
>    ->  Seq Scan on t1  (cost=0.00..2.02 rows=1 width=16)
>  Optimizer: Postgres query optimizer
> (3 rows)
> ```

Quick feedback when creating an issue: it might help readers understand what outcome you'd expect, so as to form a good comparison with the actual behavior. Your post contains a series of SQL statements, which seems to suggest is a repro of an issue, which is good. But words describing why things are "wrong" might help.

**Comment by d** [comment]
> We need to confirm the implementation of this optimization in gpdb and take a look at the SQL standard to see what is the semantics for agg on empty table, and then come back to this.

An aggregated relation without a `GROUP BY` clause always contains one row ("tuple") that is the aggregation of all the input rows formed into one group. An existential qualified subquery in this case can be entirely eliminated.

Similarly, one side of the following join can be eliminated (i.e. we don't need a scan over `bar`, nor a `JOIN` at all:

```sql
CREATE TEMP TABLE foo (a int, b int);
CREATE TEMP TABLE bar (c int PRIMARY KEY, d int);

SELECT foo.b
FROM foo LEFT JOIN bar ON a = c;
```

**Comment by yydzero** [comment]
> A subquery without any group clause and contains an agg in the projection it will produce at least one tuple even the table scan output no data. So in the case of this issue, we can deduce that the qual on t1 will always be true.
What will return for those subquery if table scan output no data?

**Comment by d** [comment]
> > What will return for those subquery if table scan output no data?

A sum of zero.

**Comment by yydzero** [comment]
@d thanks for the reminder, I had expected the result will be empty.

**Comment by yydzero** [comment]
> > > What will return for those subquery if table scan output no data?
> 
> A sum of zero.

This new to me. Not sure whether other databases like Oracle does the same. 

Anyway close this issue. Thanks for your  help.
