### ISSUE TITLE
"ERROR","XX000","Distributed transaction 1588841929-0065770451 not found (cdbtm.c:2224)

### ISSUE THREAD

**Issue by tcyang11** [greenplum-db/gpdb#10151]
### Greenplum version or build
6.1.0
### OS version and uname -a
CentOS Linux release 7.3.1611 (Core) 
### Actual behavior
"ERROR","XX000","Distributed transaction 1588841929-0065770451 not found (cdbtm.c:2224)",,,,,,,0,,"cdbtm.c",2224,"Stack trace:
1    0x9f24fc postgres errstart (elog.c:558)
2    0x9f56a8 postgres elog_finish (elog.c:1715)
3    0xad3da0 postgres performDtxProtocolCommand (cdbtm.c:2099)
4    0x88c4d6 postgres PostgresMain (postgres.c:1514)
5    0x4cbe0b postgres <symbol not found> (postmaster.c:4464)
6    0x815256 postgres PostmasterMain (postmaster.c:1520)
7    0x4ce641 postgres main (main.c:205)
8    0x7f44d9816505 libc.so.6 __libc_start_main + 0xf5
9    0x4cec1c postgres <symbol not found> + 0x4cec1c
### Step to reproduce the behavior
update xx.xxxxx SET tenant_id=t.tenant_id, fallocated_num=t.fallocated_num, fmanual_lock_num=t.fmanual_lock_num, fadd_time=t.fadd_time, factive_num=t.factive_num, fentity_id=t.fentity_id, freal_num=t.freal_num, fstock_sysno=t.fstock_sysno, fstatus=t.fstatus, fcredit_sale_num=t.fcredit_sale_num, flast_update_time=t.flast_update_time, ftransfer_num_update_time=t.ftransfer_num_update_time, finventory_sysno=t.finventory_sysno, fmanual_lock_num_update_time=t.fmanual_lock_num_update_time, fvirtual_num=t.fvirtual_num, fowner_sysno=t.fowner_sysno, fpurchase_num=t.fpurchase_num, fglobal_distribution_way=t.fglobal_distribution_way, ftransfer_online_num=t.ftransfer_online_num, fglobal_custom=t.fglobal_custom, fbatch_info=t.fbatch_info, fproduct_sysno=t.fproduct_sysno, ferp_product=t.ferp_product, fproperty=t.fproperty, factive_num_update_time=t.factive_num_update_time, update_etl_date=t.update_etl_date, ftransfer_num=t.ftransfer_num, fentity_num=t.fentity_num, fstore_reserve_num=t.fstore_reserve_num,

**Comment by asimrp** [comment]
@tcyang11 can you post all the commands necessary to reproduce this issue?  Just the update statement, without the table definition and data doesn't help much.

**Comment by tcyang11** [comment]
The problem is not occur on a regular basis，May be related to data。

**Comment by tcyang11** [comment]
or database bug.

**Comment by paul-guo-** [comment]
6.1.0 is a bit old. You might want to upgrade at first.

**Comment by asimrp** [comment]
@tcyang11 please try the latest 6X release and reopen this issue with more detailed reproduction steps if you see the error again.  I'm closing this issue now as there is not enough information to act on.
