### ISSUE TITLE
how to make greenplum database enter read_only mode?

### ISSUE THREAD

**Issue by student194** [greenplum-db/gpdb#10161]
### Greenplum version or build
6.1.0

I have a question that how to make greenplum database enter read_only mode? I know that I can set option default_transaction_read_only to achieve my aim.But ,I can commit some transaction after  executing  instruction “begin transaction read write”.Is there a stricter read_only mode?Thank for your help!!

**Comment by hlinnaka** [comment]
There is no stricter read-only mode. One workaround is to create a new role and only grant read-only permissions to that role. You can still e.g. create temporary tables, though.
