### ISSUE TITLE
How to keep only the latest error log of external table?

### ISSUE THREAD

**Issue by constzl** [greenplum-db/gpdb#10175]
### Greenplum version or build
6.x and later
### OS version and uname -a
CentOS7
### autoconf options used ( config.status --config )
no matter
### Installation information ( pg_config )
no matter
### Expected behavior
Keep only the latest error log of external table.
### Actual behavior
Append mode logging error log and the size of error log keeps increasing if not truncate.
### Step to reproduce the behavior
![image](https://user-images.githubusercontent.com/32921993/82646333-0349ca00-9c47-11ea-9e9b-38c75155d615.png)

**Comment by hlinnaka** [comment]
This is a feature request, to truncate the error log implicitly after each COPY or SELECT from an external table. There are no plans for such a feature, you need to truncate the table first by calling `gp_truncate_error_log()`.
