### ISSUE TITLE
pg_exttable view incorrect column information parsing

### ISSUE THREAD

**Issue by kyeap-pivotal** [greenplum-db/gpdb#10172]
### Greenplum version or build
7.0.0-alpha.0+dev.6932.gc038b824a7 build dev

### OS version and uname -a
macOS Darwin 17.7.0

### autoconf options used ( config.status --config )
./configure --disable-orca --with-perl --with-python --disable-gpfdist --without-zstd --with-libxml

### Expected behavior
The pg_exttable view is not showing information in the correct columns. I am unable to confirm, but the underlying UDF the view uses might not be parsing the information of pg_foreign_table's ftoptions correctly.

### Actual behavior
options attribute of an external table is appended into the formatopts attribute when querying the view.

### Step to reproduce the behavior
Create external table
```
CREATE READABLE EXTERNAL TABLE public.ext_table(i int)
LOCATION ('file://tmp/myfile.txt')
FORMAT 'TEXT'
OPTIONS (foo 'bar')
LOG ERRORS
SEGMENT REJECT LIMIT 10 PERCENT
```
Query pg_exttable for the external table;
```
test=# select * from pg_exttable WHERE urilocation='{file://tmp/myfile.txt}';
-[ RECORD 1 ]---+-------------------------------------------------
reloid          | 16391
urilocation     | {file://tmp/myfile.txt}
execlocation    | {ALL_SEGMENTS}
fmttype         | t
fmtopts         | delimiter '     ' null '\N' escape '\' foo 'bar'
options         | 
command         |
rejectlimit     | 10
rejectlimittype | p
logerrors       | t
encoding        | 6
writable        | f
```

Expected Record to show
```
test=# select * from pg_exttable WHERE urilocation='{file://tmp/myfile.txt}';
-[ RECORD 1 ]---+-------------------------------------------------
reloid          | 16391
urilocation     | {file://tmp/myfile.txt}
execlocation    | {ALL_SEGMENTS}
fmttype         | t
fmtopts         | delimiter '     ' null '\N' escape '\'
options         | {foo=bar}
command         |
rejectlimit     | 10
rejectlimittype | p
logerrors       | t
encoding        | 6
writable        | f
```

**Comment by Eulerizeit** [comment]
Given that pg_exttab catalog was removed in PR #10015 should we expect this
to work?

Rob

**Comment by jimmyyih** [comment]
Yes, because in the same PR there is https://github.com/greenplum-db/gpdb/pull/10015/commits/eddd3a6e08e81c19b4588a3718cf1cb7197cfaf9 for backwards compatibility.

**Comment by jimmyyih** [comment]
```
/*
 * options. Since our document not contains the OPTION caluse, so we
 * assume no external table options in used for now.  Except
 * gpextprotocol.c.
 */
```

@adam8157 @JunfengYang So the assumption here is that because OPTIONS was never documented (unsupported in production) we are okay with the pg_exttable view always having the options column as blank?  If so, I kinda agree with that and nothing needs to be done for this Github issue.

**Comment by adam8157** [comment]
@jimmyyih Yes. Built-in external tables don't use custom options, custom protocol external tables have all options in the `fmtopts`, so we think it's safe to make that assumption.

We encourage not using the new `pg_exttable` view if possible, parsing the `pg_foreign_table` instead. Please leave a comment if anyone has a better idea.

**Comment by kyeap-pivotal** [comment]
Closing due to pg_exttab options clause not documented and supported. Recommendation is to parse pg_foreign_table.
