### ISSUE TITLE
: 未知的名称或服务015002 gpinitsystem:mdw:gpadmin-[FATAL]:-Unknown host mdw

### ISSUE THREAD

**Issue by witchang** [greenplum-db/gpdb#10176]
### OS version centos7.4 64

we install for single machine，but gpinitsystem produce error

: 未知的名称或服务015002 gpinitsystem:mdw:gpadmin-[FATAL]:-Unknown host mdw
: 未知的名称或服务 Script Exiting!

**Comment by JunfengYang** [comment]
Can you ping the mdw host?

**Comment by witchang** [comment]
yes,ssh is ok too,we change mdw to ip,is ok to start

**Comment by adam8157** [comment]
Since it works now and it was probably a network configuration issue, close this.
