### ISSUE TITLE
Is there any way to not specific the User in expect output file?

### ISSUE THREAD

**Issue by bzhaoopenstack** [greenplum-db/gpdb#10198]
### Greenplum version or build
Master 
### OS version and uname -a
ubuntu 1804

https://logs.openlabtesting.org/logs/fb/fba77702ceac9ec360914243c8f3cee139b67313/periodic-12/gpdb-installcheck-world-tests-on-arm64/6402f3c/test_results/

Hi guys,
When we build the periodic task towards gpdb master branch. We find a test failure during execuing installworld-check.

```
--- /home/zuul/gpdb/src/test/regress/expected/matview_ao.out	2020-05-28 14:35:55.133309617 +0800
+++ /home/zuul/gpdb/src/test/regress/results/matview_ao.out	2020-05-28 14:35:55.137309700 +0800
@@ -106,23 +106,23 @@
 (3 rows)
 
 \dm m_heap
-               List of relations
- Schema |  Name  |       Type        |  Owner  
---------+--------+-------------------+---------
- public | m_heap | materialized view | gpadmin
+              List of relations
+ Schema |  Name  |       Type        | Owner 
+--------+--------+-------------------+-------
+ public | m_heap | materialized view | zuul
 (1 row)
 
 \dm m_ao
-              List of relations
- Schema | Name |       Type        |  Owner  
---------+------+-------------------+---------
- public | m_ao | materialized view | gpadmin
+             List of relations
+ Schema | Name |       Type        | Owner 
+--------+------+-------------------+-------
+ public | m_ao | materialized view | zuul
 (1 row)
 
 \dm m_aocs
-               List of relations
- Schema |  Name  |       Type        |  Owner  
---------+--------+-------------------+---------
- public | m_aocs | materialized view | gpadmin
+              List of relations
+ Schema |  Name  |       Type        | Owner 
+--------+--------+-------------------+-------
+ public | m_aocs | materialized view | zuul
 (1 row)
```
 
The expected output file specifics the Owner name. I list all the expected output files in the master repo, seems on one like this. Is there any way to forbid this? Thanks very much

https://github.com/greenplum-db/gpdb/pull/10163 introduce this change.
@baobao0206 hi, could you please to look at this one? Thanks

**Comment by paul-guo-** [comment]
Yes this is an issue. you can use init_file rule to mask the difference.
Refer src/test/regress/init_file

But please put the rule in the test only since this rule is not common for
other tests.

Thanks.

**Comment by bzhaoopenstack** [comment]
Thanks @paul-guo- .
But when I look carefully about the diff file again, https://logs.openlabtesting.org/logs/fb/fba77702ceac9ec360914243c8f3cee139b67313/periodic-12/gpdb-installcheck-world-tests-on-arm64/6402f3c/test_results/regress_regression.diffs

Seems this is not easy to be mask. Sorry I give u just part of the difference. So the differences are:
1. The different blanks before the title "List of relations"
2. The different blanks beside the colume name "Owner"
3. The specified Owner Name to "gpadmin".

And I also retest it on a docker aarch64. Same behavior, for the Issue #1 and #2 are randomly blanks, sometimes there will be more 1 blank, or less 1 blank.

**Comment by bzhaoopenstack** [comment]
So even I add mask like this:
#m/public \| (m_heap|m_ao|m_aocs) \| materialized view \| .*/
#s/public \| (m_heap|m_ao|m_aocs) \| materialized view \| .*/public \| .* \| materialized view \| gpadmin/
#s/public \| \((m_heap|m_ao|m_aocs)\)\1 \| materialized view \| .*/public \| $1 \| materialized view \| gpadmin/
m/\s+public \| m_heap \| materialized view \| .*/
s/\s+public \| m_heap \| materialized view \| .*/ public \| m_heap \| materialized view \| gpadmin/
m/\s+public \| m_ao \| materialized view \| .*/
s/\s+public \| m_ao \| materialized view \| .*/ public \| m_ao \| materialized view \| gpadmin/
m/\s+public \| m_aocs \| materialized view \| .*/
s/\s+public \| m_aocs \| materialized view \| .*/ public \| m_aocs \| materialized view \| gpadmin/

The diff shows :
`--- /home/greenplum/src/gpdb/src/test/regress/expected/matview_ao.out   2020-05-29 07:33:16.071525958 +0000
+++ /home/greenplum/src/gpdb/src/test/regress/results/matview_ao.out    2020-05-29 07:33:16.075526014 +0000
@@ -106,23 +106,23 @@
 (3 rows)

 \dm m_heap
-               List of relations
- Schema |  Name  |       Type        |  Owner
---------+--------+-------------------+---------
+                List of relations
+ Schema |  Name  |       Type        |   Owner
+--------+--------+-------------------+-----------
  public | m_heap | materialized view | gpadmin
 (1 row)

 \dm m_ao
-              List of relations
- Schema | Name |       Type        |  Owner
---------+------+-------------------+---------
+               List of relations
+ Schema | Name |       Type        |   Owner
+--------+------+-------------------+-----------
  public | m_ao | materialized view | gpadmin
 (1 row)

 \dm m_aocs
-               List of relations
- Schema |  Name  |       Type        |  Owner
---------+--------+-------------------+---------
+                List of relations
+ Schema |  Name  |       Type        |   Owner
+--------+--------+-------------------+-----------
  public | m_aocs | materialized view | gpadmin
 (1 row)


======================================================================
`

**Comment by paul-guo-** [comment]
That is due to the length difference of various users.

Perhaps instead of using the mask rule, you could use role in the  test., e.g.

At the beginning of the test
```
create role matview_ao_role;
set role matview_ao_role;
```

drop the role in the end.
```
drop role matview_ao_role;
```

And then the test result is deterministic.

**Comment by bzhaoopenstack** [comment]
Thanks, I try to post a PR for this.

**Comment by bzhaoopenstack** [comment]
Thanks you guys help, I close this issue.
