### ISSUE TITLE
Docker image repository

### ISSUE THREAD

**Issue by jeusdi** [greenplum-db/gpdb#10191]
We're trying to find a ready-to-use docker image into a docker image repository.

We don't quite figure out which image to pick in order to run and play.

* Is there any docker image ready to use into a repository?
* If it's not available, how should we proceed in order to build it? Is there any official way to do that?

I'd appreciate your comments!

**Comment by tylarb** [comment]
@jeusdi we don't have a ready-to-use image for Greenplum currently.

You can follow the guide here - https://github.com/greenplum-db/gpdb/blob/master/README.docker.md, which is mostly focused on creating a developer environment.

For a better testing environment, I recommend installing a Greenplum RPM from our releases page - https://github.com/greenplum-db/gpdb/releases 

Note that your container(s) will need ssh running, so it's a good idea to get a container with systemd enabled - I think most of the base centos images support systemd currently.
