### ISSUE TITLE
CREATE EXTENSION postgres_fdw 

### ISSUE THREAD

**Issue by Grigoriev-S** [greenplum-db/gpdb#10201]
### Actual behavior
test=# CREATE EXTENSION postgres_fdw;
ERROR:  could not open extension control file "/usr/local/gpdb/share/postgresql/extension/postgres_fdw.control": No such file or director

**Comment by Grigoriev-S** [comment]
Hello.
How to add extension postgres_fdw?

**Comment by fanfuxiaoran** [comment]
By default, the postgres_fdw is not installed, you can run "make install" in the directory: contrib/postgres_fdw to install it.
