### ISSUE TITLE
how to reduce the time "sort" and "group by" operation takes?

### ISSUE THREAD

**Issue by GuoLiuFang** [greenplum-db/gpdb#1021]
this my `explain analyze `
I find sort and "group by" take almost all the time..and How to avoid Workfile spillling?
any idea is welcome.
![Markdown](http://i2.piimg.com/1949/5f659c90f675c844s.png)

**Comment by GuoLiuFang** [comment]
@yydzero 
@ivannovick 
@danielgustafsson 
Anyone can help me ?

**Comment by Eulerizeit** [comment]
Daniel is on leave right now. It will be a while before he returns.

**Comment by ascherbaum-pivotal** [comment]
Is this issue still open?

@GuoLiuFang Did the hint from @Eulerizeit help you?

**Comment by vraghavan78** [comment]
Closing the issue, @GuoLiuFang please re-open it if @Eulerizeit hint did not help you.
