### ISSUE TITLE
gp6.6.0-AOCOtable-orderby failure

### ISSUE THREAD

**Issue by tusamuel** [greenplum-db/gpdb#10231]
### Greenplum version or build
6.6.0
### OS version and uname -a
CentOS Linux release 7.5.1804 (Core)
Linux internal 3.10.0-862.3.2.el7.x86_64 #1 SMP Mon May 21 23:36:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

### Expected behavior
select d_id,count(0) from xxx where  date=20200602 group by d_id order by d_id;
 d_id |  count   
--------+----------
      2 | 10710211
      6 | 24076702
     13 | 29074913
     15 |   718752
     19 |   208700
     20 |   901843
     21 |    79330
     23 |  1549587
     27 |   409788
     28 |  1948571
     30 |   728790
     35 |   771663
     38 |    58848
     39 |    87166

### Actual behavior
 d_id |  count   
--------+----------
     15 |   282041
      2 |  3916903
     27 |   222610
     30 |   246005
     20 |   313292
     39 |    17165
     35 |   174049
     28 |   481914
     21 |    25579
     19 |    67964
     38 |     8942
     13 | 15438645
     23 |   502923
      6 | 12563665

#### table ddl：
Distributed randomly
Partition by: (date)
Options: appendonly=true, orientation=column, compresstype=zstd, compresslevel=3, blocksize=8192

#### column ddl：
date integer
d_id integer

#### orderby failure case
select d_id,count(0) from xxx where  date=20200602 group by d_id order by d_id;
select d_id,count(0) from xxx where  date in(20200602) group by d_id order by d_id;

#### orderby success case
select d_id,count(0) from xxx where  date>=20200602 and date<=20200602 group by d_id order by d_id;

**Comment by gaos1** [comment]
minirepo from Miao:
drop table if exists test_order;
create table test_order(
  a int,
  b int,
  c int,
  d int
)distributed randomly;
insert into test_order select generate_series(1,10),generate_series(1,11),generate_series(1,12),generate_series(1,13);

select a,count(*) from test_order where (b <= 10 and b = 10) group by a order by a;

--wrong
select b,count(*) from test_order where (a <= 10 and a = 10) group by b order by b;--缺少sort
select c,count(*) from test_order where (a <= 10 and a = 10) group by c order by c;--缺少sort
select d,count(*) from test_order where (a <= 10 and a = 10) group by d order by d;--缺少sort

--correct
select c,count(*) from test_order where (b <= 10 and b = 10) group by c order by c;
select d,count(*) from test_order where (b <= 10 and b = 10) group by d order by d;
select d,count(*) from test_order where (c <= 10 and c = 10) group by d order by d;
