### ISSUE TITLE
`numNonExtendedDispatcherState` is not always reset right

### ISSUE THREAD

**Issue by adam8157** [greenplum-db/gpdb#10241]
### Greenplum version or build
6X, maybe the master also.

### Expected behavior
Report error
```
ERROR:  failed to load the mysql query:
libmysqlclient.so: cannot open shared object file: No such file or directory
HINT:  export LD_LIBRARY_PATH to locate the library
```

### Actual behavior
Report error
```
ERROR: query plan with multiple segworker groups is not supported
HINT: likely caused by a function that reads or modifies data in a distributed table
```

### Step to reproduce the behavior
Checkout and install 489a5c318e493c6d5c552368ff55b229984ecf00 of https://github.com/adam8157/mysql_fdw_greenplum
`CREATE EXTENSION mysql_fdw;`

### RCA
`numNonExtendedDispatcherState` is not reset right when this error happens, the error that the library `libmysqlclient.so`, which is depended by the FDW module `mysql_fdw.so`, is not in the `LD_LIBRARY_PATH`

**Comment by kainwen** [comment]
Fixed by https://github.com/greenplum-db/gpdb/commit/58628039c5369a520fc65adb87f0d29fd1203fd7 in master
and in 6x https://github.com/greenplum-db/gpdb/commit/4d185c05c8406cd38659a3aee952150c4cecb2b2

See commit message for details.
