### ISSUE TITLE
Vagrant's configurations are not up to date

### ISSUE THREAD

**Issue by nacyolsa** [greenplum-db/gpdb#10256]
For Debian `docker-engine` is installed in deprecated way what cause errors. After fixing this there are next problems with building. I stopped investigating after that.

For Centos `git` version is installed too old what cause errors in next steps. After fixing this there are next problems with building. I stopped investigating after that.

**Comment by tylarb** [comment]
For the centos issue, which documentation or readme are you following ?

**Comment by nacyolsa** [comment]
I was using readme `src/tools/vagrant/README.md`. It was a month ago and I switched to docker which works correctly.

**Comment by tylarb** [comment]
I've asked around for details on this. Unfortunately, I don't see that the vagrant files are being maintained at the moment. I'll make a note to look into removing or updating them. For now, I'll close this issue.
