### ISSUE TITLE
Error hints are not displayed on psql

### ISSUE THREAD

**Issue by frankgh** [greenplum-db/gpdb#10255]
### Greenplum version or build
Greenplum 5

### OS version and uname -a
all OSs

### Expected behavior

```sql
SELECT *  FROM foo;
ERROR:  some error
HINT:  some hint.
DETAIL:  External table foo, file some_file
```

### Actual behavior

```sql
SELECT *  FROM foo;
ERROR:  some error
DETAIL:  External table foo, file some_file
```

### Step to reproduce the behavior

When an `ereport` has an `errhint`, the hint is not displayed to the end user on Greenplum 5. Greenplum 6+ is working correctly.

```
ereport(ERROR,
	(errcode(ERRCODE_CONNECTION_EXCEPTION),
	errmsg("%s", err.data),
	errhint("%s", hint.data)));
```

**Comment by lij55** [comment]
closing this GP5-only issue which is fixed on GP6 and later now.
