### ISSUE TITLE
Can we use GPSS with Greenplum OSS and without Pivotal license restrictions?

### ISSUE THREAD

**Issue by yvaa** [greenplum-db/gpdb#10254]
Hello! Thank you for the great database!

I read in [Greenplum 6.8 release notes](https://gpdb.docs.pivotal.io/6-8/relnotes/gpdb-68-release-notes.html):
> Greenplum Streaming Server (GPSS) version 1.3.6 is included, which introduces many new and changed features and bug fixes since the last GPSS version installed in Greenplum 6.x (1.3.1). Refer to the [GPSS Release Notes](https://greenplum.docs.pivotal.io/streaming-server/1-3-6/gpss-v13-release-notes.html) for more information on release content and to access the GPSS documentation. 

And anywhere on the page I see Pivotal Greenplum, Pivotal GPSS, Pivotal, Pivotal, Pivotal. I understand that Pivotal is the main contributor. But every time I read the documentation I don't understand which features are in "OSS Greenplum" and which are under "Pivotal Greenplum" as a licensed and supported fee product.

In the "OSS Greenplum" documentation you make links to the Pivotal Network software where we see Pivotal license restricted software. It looks messy.

For GPSS could you please answer, does the line "(GPSS) version 1.3.6 is included" in the release notes mean that I can use GPSS in Open Source Greenplum version without any restrictions or agreements with Pivotal licenses? For example if I want to test streaming from Kafka to OSS Greenplum.

Thanks!

**Comment by ivannovick** [comment]
GPSS is a VMware (ex Pivotal) licensed product and not open source.

**Comment by ivannovick** [comment]
If you see any links in OSS docs to Pivotal that is a bug, and appreciate you to share it for fixing

**Comment by dyozie** [comment]
Thanks @ivannovick  and @yvaa  

We try to minimize all proprietary content that shows up in the OSS docs, but sometimes it's unavoidable. Anything proprietary (including links to pivotal sites) should already be conditionalized to not appear in the open source docs at docs.greenplum.org.  But if something does appear there, please log a github issue so it can be properly conditionalized.

**Comment by yvaa** [comment]
@ivannovick @dyozie thank you for the response! Where I can find the release notice or changelog for OSS Greenplum 6.8 which has been released a couple of days ago?
