### ISSUE TITLE
CLUSTER (and all other DDL operations that result in table rewrite) on AO table loses MVCC 

### ISSUE THREAD

**Issue by hlinnaka** [greenplum-db/gpdb#10262]
### Greenplum version or build
master, (CLUSTER on AO tables is not supported on GPDB 6 and below)

### Step to reproduce the behavior
The CLUSTER on AO tables code uses a new snapshot to scan the table. That fails to copy over any old row versions that might still be visible to running transactions. The corresponding heap code goes to great lengths to preserve old tuple versions and their xmin/xmax values, to make it MVCC-safe.

**Comment by hlinnaka** [comment]
This is demonstrated with the attached "isolationtester" case:

[cluster.spec.txt](https://github.com/greenplum-db/gpdb/files/4745029/cluster.spec.txt)
[cluster.out.txt](https://github.com/greenplum-db/gpdb/files/4745030/cluster.out.txt)

Copy `cluster.spec.txt` to `src/test/isolation/specs/cluster.spec`, and `cluster.out.txt` to `src/test/isolation/specs/cluster.spec`. Run the test with `./pg_isolation_regress cluster`. As it is, it uses a heap table, and works. If you modify it to create an AO table, it fails. All the SELECTs with an old snapshot see an empty table.

**Comment by d** [comment]
@hlinnaka interesting, do you think this happens to `VACUUM` on AO tables as well? Specifically, will the following produce any isolation anomaly?

1. T1 starts with "repeatable read", reads a bunch of tables except for AO relation `R`
2. T2 begins, deletes, updates, then inserts a bunch of tuples into `R`. commits
3. T3 vacuums relation R (AO table), commits
4. T1 opens `R`

**Comment by ashwinstar** [comment]
@d Vacuum on AO doesn't delete the old file in presence of "repeatable read" transaction in system. It will leave it behind in delete-pending state for the case you mentioned above.

**Comment by asimrp** [comment]
@baobao0206 you have picked this one up and seem to have some ideas on how to solve it, would you like to share your thoughts here?

**Comment by baobao0206** [comment]
Heap table retains the original xmin and xmax in each tuple on cluster command, but AO table inserts a EOF tuple with new xmin. So we will get nothing when we scan the AO table in a transaction started before the cluster command. 
The Heap table contains xmin and xmax in each tuple, but AO table just have one EOF tuple. So it is impossible for us to achieve fine-grained visibility control on the sorted data. Use “heap swap” is not a good choice.
I think we should keep the old data segments on "AWAITING_DROP" state and insert the sorted data to an empty segment just like vacuum.

**Comment by baobao0206** [comment]
Another choice: 
Considering that the cluster command got AccessExclusiveLock, we only need to give the sorted data a small enough xmin to make them always visible to other transactions. This can also meet the isolation of repeated read.

**Comment by baobao0206** [comment]
I find that both choices I mentioned are not correct after looking into the AO codes. We can not keep the old data in  segments with "AWAITING_DROP" state and put the sorted data into empty segments. Because the "empty segments" may not exist.
Use "froze xid" in the relation may not match the isolation of repeated read. Because we should use the same snapshot in the transaction.

**Comment by x4m** [comment]
Maybe just document that CLUSTER against AO table is not MVCC safe? PostgreSQL already have not MVCC-safe truncate and table rewrite. CLUSTER operation is not supposed to be usual maintenance routine.

**Comment by asimrp** [comment]
@gaos1 asked whether other alter operations on append optimized tables have this problem.  And indeed, the alter table operations that rewrite AO table suffer from this problem.  I verified that by replacing `CLUSTER` with `ALTER TABLE ... ADD COLUMN` operation in Heikki's isolation test above and got the same failure.  The reason is explained by Jinbao above  - we do not use catalog snapshot for scanning AO auxiliary tables.

**Comment by x4m** [comment]
Documentation PR is merged. Probably, this issue can be closed?
