### ISSUE TITLE
External table location hostname translates to empty when selecting from exttable

### ISSUE THREAD

**Issue by sokolval** [greenplum-db/gpdb#10278]
### Greenplum version or build
6.7.1
### OS version and uname -a
Ubuntu 16.04 LTS
Linux gp-oss 4.4.114-50 #1 SMP Fri Feb 2 10:53:13 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
### autoconf options used ( config.status --config )
'--build=x86_64-linux-gnu' '--prefix=/usr' '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' '--sysconfdir=/etc' '--localstatedir=/var' '--disable-silent-rules' '--libdir=${prefix}/lib/x86_64-linux-gnu' '--libexecdir=${prefix}/lib/x86_64-linux-gnu' '--disable-maintainer-mode' '--disable-dependency-tracking' '--with-perl' '--with-python' '--without-gssapi' '--disable-gpcloud' '--with-libxml' '--with-system-tzdata=/usr/share/zoneinfo' '--prefix=/usr/local/gpdb' 'build_alias=x86_64-linux-gnu' 'CFLAGS=-g -O2 -fstack-protector-strong -Wformat -Werror=format-security' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'CXXFLAGS=-g -O2 -fstack-protector-strong -Wformat -Werror=format-security'
### Installation information ( pg_config )
BINDIR = /usr/local/gpdb/bin
DOCDIR = /usr/local/gpdb/share/doc/postgresql
HTMLDIR = /usr/local/gpdb/share/doc/postgresql
INCLUDEDIR = /usr/local/gpdb/include
PKGINCLUDEDIR = /usr/local/gpdb/include/postgresql
INCLUDEDIR-SERVER = /usr/local/gpdb/include/postgresql/server
LIBDIR = /usr/local/gpdb/lib/x86_64-linux-gnu
PKGLIBDIR = /usr/local/gpdb/lib/x86_64-linux-gnu/postgresql
LOCALEDIR = /usr/local/gpdb/share/locale
MANDIR = /usr/local/gpdb/share/man
SHAREDIR = /usr/local/gpdb/share/postgresql
SYSCONFDIR = /etc/postgresql
PGXS = /usr/local/gpdb/lib/x86_64-linux-gnu/postgresql/pgxs/src/makefiles/pgxs.mk
CONFIGURE = '--build=x86_64-linux-gnu' '--prefix=/usr' '--includedir=/usr/local/gpdb/include' '--mandir=/usr/local/gpdb/share/man' '--infodir=/usr/local/gpdb/share/info' '--sysconfdir=/etc' '--localstatedir=/var' '--disable-silent-rules' '--libdir=/usr/local/gpdb/lib/x86_64-linux-gnu' '--libexecdir=/usr/local/gpdb/lib/x86_64-linux-gnu' '--disable-maintainer-mode' '--disable-dependency-tracking' '--with-perl' '--with-python' '--without-gssapi' '--disable-gpcloud' '--with-libxml' '--with-system-tzdata=/usr/share/zoneinfo' '--prefix=/usr/local/gpdb' 'build_alias=x86_64-linux-gnu' 'CFLAGS=-g -O2 -fstack-protector-strong -Wformat -Werror=format-security' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'CXXFLAGS=-g -O2 -fstack-protector-strong -Wformat -Werror=format-security'
CC = gcc
CPPFLAGS = -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2 -I/usr/local/gpdb/include
CFLAGS = -Wall -Wmissing-prototypes -Wpointer-arith -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fno-aggressive-loop-optimizations -Wno-unused-but-set-variable -Wno-address -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -std=gnu99 -Werror=uninitialized -Werror=implicit-function-declaration -I/usr/local/gpdb/include
CFLAGS_SL = -fPIC
LDFLAGS = -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,--as-needed -Wl,-rpath,'/usr/local/gpdb/lib/x86_64-linux-gnu',--enable-new-dtags -L/usr/local/gpdb/lib/x86_64-linux-gnu
LDFLAGS_EX = 
LDFLAGS_SL = 
LIBS = -lpgcommon -lpgport -lxerces-c -lxml2 -lrt -lzstd -lrt -lcrypt -ldl -lm -L/usr/local/gpdb/lib/x86_64-linux-gnu
VERSION = PostgreSQL 9.4.24
### Expected behavior
template1=# select * from ext_t3;
 c1 | c2 |    c3    
----+----+----------
  1 |  0 | oops
  3 |  4 | tequilla
  7 |  2 | Hello!
(3 rows)
### Actual behavior
template1=# select * from ext_t2;
ERROR:  connection with gpfdist failed for "gpfdist://gp-oss:8100/tbl.txt", effective url: "http://:8100/tbl.txt": ;  (seg0 slice1 2:6:c:2:0:4:c:0:0 pid=294712)

### Step to reproduce the behavior
start gpfdist following below steps:
`source /usr/local/gpdb/greenplum_path.sh`
`nohup gpfdist -p 8100 > /dev/null 2>&1 &`
create file in the gpfdist workdir 

`vi tbl.txt`
1|0|oops
3|4|tequilla
7|2|Hello!
run `psql -d template1`

`create external table ext_t2 (c1 int, c2 int, c3 varchar(100)) location ('gpfdist://gp-oss:8100/tbl.txt') format 'TEXT' (delimiter '|');`
`create external table ext_t3 (c1 int, c2 int, c3 varchar(100)) location ('gpfdist://localhost:8100/tbl.txt') format 'TEXT' (delimiter '|');`
`select * from ext_t2;`
`select * from ext_t3;`

**Comment by avamingli** [comment]
> Actual behavior
template1=# select * from ext_t2;
ERROR: connection with gpfdist failed for "gpfdist://gp-oss:8100/tbl.txt", effective url: "http://:8100/tbl.txt": ; (seg0 slice1 2:6:c:2:0:4:c:0:0 pid=294712)

Is there a `err code` message before the message ` (seg0 slice1 2:6:c:2:0:4:c:0:0 pid=294712)`

**Comment by huiliang-liu** [comment]
Could you run ping & ping6 gp-oss and curl -v http://gp-oss:8100, then paste the results?
And seg0 slice1 seems a invalid IPv6 address and port. what is your network configuration of GPDB?

**Comment by sokolval** [comment]
For the IP address - I masked it, in fact. it gives out proper address, with 4 hex digits per part.
ping gp-oss reports Unknown host
`ping6 gp-oss PING gp-oss(gp-oss) 56 data bytes`
`64 bytes from gp-oss: icmp_seq=1 ttl=64 time=0.014 ms`
`64 bytes from gp-oss: icmp_seq=2 ttl=64 time=0.052 ms`
`64 bytes from gp-oss: icmp_seq=3 ttl=64 time=0.056 ms`
`64 bytes from gp-oss: icmp_seq=4 ttl=64 time=0.046 ms`
`^C`
`--- gp-oss ping statistics ---`
`4 packets transmitted, 4 received, 0% packet loss, time 4011ms`
`rtt min/avg/max/mdev = 0.014/0.043/0.056/0.014 ms`

`skl@gp-oss:~$ curl -v http://gp-oss:8100`
`*   Trying [masked IPv6 addr]...`
`* Connected to gp-oss ([masked IPv6 addr]) port 8100 (#0)`
`> GET / HTTP/1.1`
`> Host: gp-oss:8100`
`> User-Agent: curl/7.70.0-DEV`
`> Accept: */*`
`> `
`* Mark bundle as not supporting multiuse`
`* HTTP 1.0, assume close after body`
`< HTTP/1.0 400 invalid request (unable to set path)`
`< Content-length: 0`
`< Expires: 0`
`< X-GPFDIST-VERSION: 6.7.1 build 0`
`< Cache-Control: no-cache`
`< Connection: close`
`< `
`* Closing connection 0`

In fact I navigated through code till this error and saw that it refers to using curl. What I did try on my side: I built gpdb with different versions of curl under, but nothing helped. it is still loosing hostname from effective_url somehow

**Comment by sokolval** [comment]
> > Actual behavior
> > template1=# select * from ext_t2;
> > ERROR: connection with gpfdist failed for "gpfdist://gp-oss:8100/tbl.txt", effective url: "http://:8100/tbl.txt": ; (seg0 slice1 2:6:c:2:0:4:c:0:0 pid=294712)
> 
> Is there a `err code` message before the message ` (seg0 slice1 2:6:c:2:0:4:c:0:0 pid=294712)`

there is no additional err code before the segment in brackets.

**Comment by sokolval** [comment]
I did another attempts to connect to gpfdist using matching in /etc/hosts
When I put hosts IPv6 address there, still the output from select query was the same: 
`ERROR: connection with gpfdist failed for "gpfdist://gp-oss:8100/tbl.txt", effective url: "http://:8100/tbl.txt"`
What I did next - I put 127.0.0.1 there as the matching for host (as both gpfdist and segments live on the same host) and voila: the select returned what I expected from him. 
So it is more clear now that the issue is somewhere with IPv6.

**Comment by avamingli** [comment]
Thanks, sokolval.
You are rigjht, we found a IPV6 issue and the pr #10331 has been created for that.

**Comment by avamingli** [comment]
> Hello, Avamingli and Huiliang-liu!
> 
> Thank you for your quick action on this issue!
> I've rebuilt gpdb 6.8.1 and applied pr #10331 onto it, but still the issue remains for me.
> Could it be possible that few more updates to code are required?
> 
> Thank you in advance!

thanks sokolval, we will check for it.

**Comment by huiliang-liu** [comment]
Hi sokolval,
     For GPDB 6.x, you also need this patch: https://github.com/greenplum-db/gpdb/commit/48a962091bf029616ccff45ae37b44d280d29a4c#diff-fca92858627544f38c68116e65fdfc0f
    We will cherry-pick it to 6.x with pr 10331 later
