### ISSUE TITLE
Wonderful new test from upstream, wrong result

### ISSUE THREAD

**Issue by fengttt** [greenplum-db/gpdb#1030]
The following test is added in upstream PG95.  Greenplum returns wrong result.   We should either fix it, or disable this feature (subquery in the offset clause). 

select (select n from (select n from generate_series(1,10) as n order by n limit 1 offset s - 1) as y) as z from generate_series(1,10) as s;

**Comment by vraghavan78** [comment]
Thank you reporting this. I ran this in PG9.3, GPDB with Orca and GPDB with Planner and they report the same result. 

`vraghavan=# select (select n from (select n from generate_series(1,10) as n order by n limit 1 offset s - 1) as y) as z from generate_series(1,10) as s;
LOG:  statement: select (select n from (select n from generate_series(1,10) as n order by n limit 1 offset s - 1) as y) as z from generate_series(1,10) as s;
 z
----
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10
(10 rows)

vraghavan=# set optimizer = on;
LOG:  statement: set optimizer = on;
SET
vraghavan=# select (select n from (select n from generate_series(1,10) as n order by n limit 1 offset s - 1) as y) as z from generate_series(1,10) as s;
LOG:  statement: select (select n from (select n from generate_series(1,10) as n order by n limit 1 offset s - 1) as y) as z from generate_series(1,10) as s;
 z
----
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10
(10 rows)`

We will take a look at PG95 and figure out what needs to be ported. Thanks again for reporting this.

**Comment by hlinnaka** [comment]
I'm also seeing the same result, on PostgreSQL master, and GPDB master. @fengttt didn't mention what result he saw that was wrong, but it seems to work now. Closing.
