### ISSUE TITLE
Greenplum Database Documentation have a wrong

### ISSUE THREAD

**Issue by Yuvanjar** [greenplum-db/gpdb#10333]
### Greenplum 's documents have some wrong
When I learn how to loading data to database,I use the way like the document's introduce.The link is
_http://docs.greenplum.org/6-8/admin_guide/load/topics/transforming-xml-data.html#topic75_

then I found it has a wrong on the fifth block,it should be 

> **java \
>     -jar joost.jar \
>     -nodecl \
>     $1 \
>     input_transform.stx \
>  | awk 'NF>0'**
> 

but not

>  **java \
>     -jar joost.jar \
>     -nodecl \
>     $1 \
>     input_transform.stx \
>  | awk 'NF>0**

**Comment by mkiyama** [comment]
Thanks for pointing this out.
The docs team will look into it.

**Comment by hlinnaka** [comment]
Fixed in commit ba88fa41736c7852fb3ec7e28dab917a1cd95e88.Thanks!
