### ISSUE TITLE
Build failed when fault injection is disabled

### ISSUE THREAD

**Issue by fangzheng** [greenplum-db/gpdb#10341]
### Greenplum version or build
master

### OS version and uname -a
mac

When commenting out the definition of `FAULT_INJECTOR` macro, build fails with the following error:

````
Undefined symbols for architecture x86_64:
  "_FaultInjector_InjectFaultIfSet", referenced from:
      gpdb::InjectFaultInOptTasks(char const*) in gpdbwrappers.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
````

It is because the definition of `FaultInjector_InjectFaultIfSet()` in `faultinjector.c` is only present when `FAULT_INJECTOR` is defined.

If the issue is confirmed, I can submit a PR. Thanks.

**Comment by gfphoenix78** [comment]
@fangzheng Where do you commenting out the definition of FAULT_INJECTOR macro?

**Comment by fangzheng** [comment]
> @fangzheng Where do you commenting out the definition of FAULT_INJECTOR macro?

Hi, I comment it out from  src/include/pg_config_manual.h.

**Comment by gfphoenix78** [comment]
@fangzheng Although we prefer to use the macros like SIMPLE_FAULT_INJECTOR, there are still some places to use the function directly.
For your case, you could find the file `gpdbwrappers.cpp`, and put the line 
`        return FaultInjector_InjectFaultIfSet(fault_name, DDLNotSpecified, "", "");` in the block
```c
#ifdef FAULT_INJECTOR
return FaultInjector_InjectFaultIfSet(fault_name, DDLNotSpecified, "", "");
#else
GPOS_RAISE(gpdxl::ExmaGPDB, gpdxl::ExmiGPDBError,	
		   GPOS_WSZ_LIT("InjectFaultInOptTasks can only be called when fault injector is enabled"));
#endif
```

**Comment by fangzheng** [comment]
@gfphoenix78 Thanks for the correction. Since you have already come up with the fix, perhaps you can commit it to the master branch? Thanks.

**Comment by gfphoenix78** [comment]
Sure, thank you for your remind. Does it fix your problem?

**Comment by fangzheng** [comment]
Yes.
