### ISSUE TITLE
DISCARD doesn't discard

### ISSUE THREAD

**Issue by hlinnaka** [greenplum-db/gpdb#1036]
```
postgres=# create temporary table foo42 (id int4);
NOTICE:  Table doesn't have 'DISTRIBUTED BY' clause -- Using column named 'id' as the Greenplum Database data distribution key for this table.
HINT:  The 'DISTRIBUTED BY' clause determines the distribution of data. Make sure column(s) chosen are the optimal data distribution key to minimize skew.
CREATE TABLE
postgres=# discard temp;
DISCARD TEMP
postgres=# create temporary table foo42 (id int4);
NOTICE:  Table doesn't have 'DISTRIBUTED BY' clause -- Using column named 'id' as the Greenplum Database data distribution key for this table.
HINT:  The 'DISTRIBUTED BY' clause determines the distribution of data. Make sure column(s) chosen are the optimal data distribution key to minimize skew.
ERROR:  relation "foo42" already exists  (seg0 127.0.0.1:40000 pid=974) (cdbdisp_query.c:502)
```

DISCARD TEMP is supposed to drop all temporary tables, but apparently it doesn't.

**Comment by d** [comment]
Does that mean it's removed from `pg_class` but the segments still have the table?

**Comment by hlinnaka** [comment]
On 08/24/2016 08:32 AM, Jesse Zhang wrote:
> Does that mean it's removed from `pg_class` but the segments still have the table?

Yeah, I think so.

- Heikki

**Comment by asimrp** [comment]
Hey Heikki, the code to dispatch `DiscardStmt` is missing.  I tried adding it, which made `discard temp;` working.  However, `discard all;` started failing on segments because it cannot be run from within a transaction block.  This is where I'm stuck, thinking for a possible solution.

**Comment by asimrp** [comment]
@ashwinstar had an interesting suggestion: continue to not dispatch `DiscardStmt` and simply destroy the sessions between master and segments, on the lines of `disconnectAndDestroyAllGangs(false)`.  This is better than attempting to dispatch actions such as dropping temp tables but not performing two phase commit.

**Comment by hlinnaka** [comment]
Opened PR #6744 to fix this.

> @ashwinstar had an interesting suggestion: continue to not dispatch `DiscardStmt` and simply destroy the sessions between master and segments, on the lines of `disconnectAndDestroyAllGangs(false)`. This is better than attempting to dispatch actions such as dropping temp tables but not performing two phase commit.

Interesting idea. I like that, because it ensures that any other state that the QD->QE connections might hold is also cleaned up. However, I couldn't make that work easily. When I called `DisconnectAndDestroyAllGangs(false)`, the temporary tables still didn't get dropped in the segments. Temp tables are not automatically dropped in QEs when the QD->QE connection is disconnected, you need to explicitly dispatch a command to drop them. I think `DisconnectAndDestroyAllGangs(false)` would do the trick, but that gave a warning: "Any temporary tables for this session have been dropped because the gang was disconnected (session id = %d)". I supppose we could modify it to not emit that warning in this case. But looking at the implementation of DisconnectAndDestroyGangs(), it works by resetting the temp namespace OID. On the next statement, a new temp namespace will be allocated. I think that leaves behind the old temp schema and tables, to be cleaned up by something later, rather than dropping them immediately. That's fine for error handling, but doesn't seem appropriate for DISCARD ALL.

So I went back to the approach of simply dispatching the DISCARD statement, like we dispatch most utility statements.

> Hey Heikki, the code to dispatch DiscardStmt is missing. I tried adding it, which made discard temp; working. However, discard all; started failing on segments because it cannot be run from within a transaction block. This is where I'm stuck, thinking for a possible solution.

I solved that by not using two-phase commit for DISCARD ALL. I believe that's ok because DISCARD ALL is not allowed in a transaction block.

**Comment by Eulerizeit** [comment]
@hlinnaka did you just submit a PR that fixed this?  Or maybe a duplicate issue?
