### ISSUE TITLE
psql out of memory

### ISSUE THREAD

**Issue by ChaosEternal** [greenplum-db/gpdb#1038]
on version 4.3.9.0 
the sql is like 

select col1, * from some_big_table order by col1 desc

the some_big_table contains more than 500G data and trillions of rows of data 
the sql is submitted using psql and output is redirected to a file, the filesystem is big enough.
after a while, the psql process ended with an error "Out of memory" 

evidences that the message is not server side:
1. master logs do not contain the error message
2. when explain analyze the sql, it finishes sucessfully
3. when insert the output to an table, the sql finishes successfully

Other findings:
the RSS of the psql process grows rapidly but the output file does not change.

**Comment by ascherbaum-pivotal** [comment]
This is expected. Not desired, but expected. psql uses libpq under the hood, and that will fetch the entire result set to the client before start sending it to the output file.

You can work around that problem by using the COPY command.

https://www.postgresql.org/docs/8.3/static/sql-copy.html

Something like the following should work (untested):

```
psql -A -q -t -c "COPY (select col1, * from some_big_table order by col1 desc) TO STDOUT" -o oufput_file.csv
```
