### ISSUE TITLE
Feature Request: Allow Specifying SSH Key Name in Command-Line Utilities (gpseginstall, gpssh-exkeys)

### ISSUE THREAD

**Issue by Xangis** [greenplum-db/gpdb#104]
I have a set of servers I'd like to provision. The master-to-be can ssh into the segments-to-be without a password because mykey.pem is specified in the ~/.ssh/config file (with the line IdentityFile /home/me/.ssh/mykey.pem)

Because gpseginstall and gpssh-exkeys skip the SSH config, they prompt for a password in order to exchange keys and/or log in.

It would make things easier if there was a command-line argument to specify the key file to use when running gpseginstall, gpssh-exkeys, and the like (perhaps -i).

**Comment by ivannovick** [comment]
closing this out because its old and stale, but if you want to discuss further lets chat on the Greenplum email list
