### ISSUE TITLE
Assertion failure when creating partitioned table in utility mode

### ISSUE THREAD

**Issue by guofengrichard** [greenplum-db/gpdb#10410]
### Greenplum version or build

6X, master, (may also include 5X)

### Step to reproduce the behavior

In utility mode:

```
CREATE TABLE pt_lt_tab
(
  col1 int,
  col2 decimal
)
distributed by (col1)
partition by list(col2)
(
  partition part1 values(1)
);
```

**Comment by ashwinstar** [comment]
Given we keep partition catalog information only on master for these
affected versions, how much do we really care about this? (I understand
asserting is not nice in general.)

**Comment by guofengrichard** [comment]
> Given we keep partition catalog information only on master for these affected versions, how much do we really care about this? (I understand asserting is not nice in general.)

You consideration makes sense.  How about we just change the assertion condition to avoid this crash in utility mode?

**Comment by kainwen** [comment]
I do not think this issue has any value. Close it.
