### ISSUE TITLE
"cursor_tuple_fraction" appears twice in unsync_guc_name.h

### ISSUE THREAD

**Issue by fangzheng** [greenplum-db/gpdb#10437]
### Greenplum version or build
master

The GUC variable "cursor_tuple_fraction" appears twice in unsync_guc_name.h:

https://github.com/greenplum-db/gpdb/blob/master/src/include/utils/unsync_guc_name.h#L46

**Comment by fangzheng** [comment]
"gp_enable_minmax_optimization" is also duplicated:

https://github.com/greenplum-db/gpdb/blob/master/src/include/utils/unsync_guc_name.h#L176

**Comment by ashwinstar** [comment]
Sure @fangzheng would like to open PR to fix those?

**Comment by fangzheng** [comment]
@ashwinstar Thanks for confirmation. I will submit a PR soon.
