### ISSUE TITLE
Incorrect result with correlated subquery

### ISSUE THREAD

**Issue by zellerh** [greenplum-db/gpdb#10452]
### Greenplum version or build

5.28

### OS version and uname -a

MacOS

### autoconf options used ( config.status --config )

--config-cache --without-zstd --disable-gpcloud --enable-debug --enable-depend --enable-orca --with-python --with-quicklz

### Expected behavior

return 1 row (1,99)

### Actual behavior

returns 0 rows

### Step to reproduce the behavior

```
drop table if exists tcorr1, tcorr2;

create table tcorr1(a int, b int);
create table tcorr2(a int, b int);

insert into tcorr1 values (1,99);
insert into tcorr2 values (1,1);

set optimizer = off;

select *
from tcorr1 out
where out.b in (select coalesce(tcorr2.a, 99)
                from tcorr1 left outer join tcorr2 on tcorr1.a=tcorr2.a+out.a);
```

Note that right now, Orca produces the same wrong answer. Upstream Postgres has the correct result (I tried this on sqlfiddle.com, using PostgreSQL 9.6). I am working on a fix for Orca.

**Comment by guofengrichard** [comment]
And on 6X, it would generate an incorrect plan which passes a param through motion. So running this query on 6X would end up with error: `ERROR:  illegal rescan of motion node: invalid plan`.

**Comment by lij55** [comment]
closing this GP5 issue and keep https://github.com/greenplum-db/gpdb/issues/10791 to tracking the status of GP6.
