### ISSUE TITLE
gp_primarymirros

### ISSUE THREAD

**Issue by T0125** [greenplum-db/gpdb#1045]
Can anyone tell me about the usage of gp_primarymirros command,including the format of the input file ,which is used by -i parameters

**Comment by asimrp** [comment]
Hi @T0125, `gp_primarymirror` is an internal utility, not intended to be used directly by a user.  Can you please share what are you trying to achieve?

**Comment by ashwinstar** [comment]
@T0125  just a general recommendation/tip might be better to drop mail (and subscribe) to greenplum developers mailing list (gpdb-dev@greenplum.org) for such queries instead of opening it as issue.

**Comment by T0125** [comment]
@asimrp 
Thanks for your reply ! It is just in the process of gpmovemirrors , I found this command ,but there is no description of it . There was nothing wrong , just curious.
Sorry to trouble you , thanks again

**Comment by asimrp** [comment]
No worries, as Ashwin mentioned, please feel free to use the mailing list!
