### ISSUE TITLE
Madlib compilation error

### ISSUE THREAD

**Issue by zhongyibill** [greenplum-db/gpdb#10461]
### Greenplum version or build
`PostgreSQL 9.6beta4 (Greenplum Database 7.0.0-alpha.0 build dev) `
### madlib version
`madlib 1.16`

### Error behavior
```
/home/z14231/git_lijx_9.6/0703/SeaSQL-mpp-v2_build/madlib/madlib-1.16/methods/kmeans/src/pg_gp/kmeans.c: In function 'compute_metric':
/home/z14231/git_lijx_9.6/0703/SeaSQL-mpp-v2_build/madlib/madlib-1.16/methods/kmeans/src/pg_gp/kmeans.c:89:20: error: 'struct MemoryContextData' has no member named 'allBytesAlloc'
     if(inMemContext->allBytesAlloc - inMemContext->allBytesFreed > 50000)
                    ^~
/home/z14231/git_lijx_9.6/0703/SeaSQL-mpp-v2_build/madlib/madlib-1.16/methods/kmeans/src/pg_gp/kmeans.c:89:50: error: 'struct MemoryContextData' has no member named 'allBytesFreed'
     if(inMemContext->allBytesAlloc - inMemContext->allBytesFreed > 50000)

```

**Comment by lij55** [comment]
Hi @zhongyibill ,

the information that you provided is very limited. could you please upload the entire output of the cmake for madlib?
I don't think Madlib 1.6 could support GP7. did you changed anything for madlib?

**Comment by kainwen** [comment]
The version `PostgreSQL 9.6beta4 (Greenplum Database 7.0.0-alpha.0 build dev)` is long before. And madlib never support this.
