### ISSUE TITLE
Documentation: wrong description for pg_appendonly.compresstype.

### ISSUE THREAD

**Issue by egorklimov** [greenplum-db/gpdb#10476]
Hi!

I noticed, that pg_appendonly.compresstype has this description:

> Type of compression used to compress append-optimized tables. 
Valid values are:
zlib (gzip compression)
zstd (Zstandard compression)
quicklz1

Whereas on the page **Choosing the Table Storage Model** is said that:
compresstype | Type of compression. | zstd: Zstandard algorithmzlib: deflate algorithm<br>  quicklz: fast compression<br>  RLE_TYPE: run-length encoding<br>  none: no compression
-- | -- | --

Seems that "rle_type" and "none" are also valid types for compresstype.

Sorry if I missed smth and this is not really a mistake.
  
Related links:
* https://gpdb.docs.pivotal.io/6-9/ref_guide/system_catalogs/pg_appendonly.html, not only in 6.9, it seems like this error goes through all versions.
* https://gpdb.docs.pivotal.io/6-9/admin_guide/ddl/ddl-storage.html

**Comment by egorklimov** [comment]
Also in `CREATE TABLE` statement documentation is said: 
>  WITH ( storage_option=value )
The WITH clause can be used to set storage options for the table or its indexes. Note that you can also set storage parameters on a particular partition or subpartition by declaring the WITH clause in the partition specification. The lowest-level settings have priority.
The defaults for some of the table storage options can be specified with the server configuration parameter gp_default_storage_options. For information about setting default storage options, see Notes.
The following storage options are available:
APPENDONLY — Set to TRUE to create the table as an append-optimized table. If FALSE or not declared, the table will be created as a regular heap-storage table.
BLOCKSIZE — Set to the size, in bytes for each block in a table. The BLOCKSIZE must be between 8192 and 2097152 bytes, and be a multiple of 8192. The default is 32768.
ORIENTATION — Set to column for column-oriented storage, or row (the default) for row-oriented storage. This option is only valid if APPENDONLY=TRUE. Heap-storage tables can only be row-oriented.

In fact, all these settings are valid only if APPENDONLY = true, whereas it is not said for `blocksize`

Sorry, if it is not a mistake, I'm just starting to work with greenplum.

https://gpdb.docs.pivotal.io/510/ref_guide/sql_commands/CREATE_TABLE.html#topic1__section5 (in 6.* naming differs, but blocksize is also used only if appendonly=true)

**Comment by mkiyama** [comment]
Thanks for pointing these doc issues out.
We will look into them and update the docs.

**Comment by egorklimov** [comment]
For heaven's sake, add some info about `pg_get_partition_def` to the documentation, I spent a day generating ddl based on system catalogs and, at the end of the day, I absolutely accidentally found out this function :rofl:

**Comment by kainwen** [comment]
@mkiyama 
What is the state of this? Thanks!

**Comment by lisakowen** [comment]
@kainwen - mel is no longer writing for greenplum.  someone from the docs team will look into this.

**Comment by kainwen** [comment]
Fixed by https://github.com/greenplum-db/gpdb/pull/12601 .
