### ISSUE TITLE
Recovery support of different tablespace location value for the same primary-mirror pair 

### ISSUE THREAD

**Issue by phan-pivotal** [greenplum-db/gpdb#10473]
### Greenplum version or build
GP V6.*
### OS version and uname -a
CentOS 7.6
### Expected behavior
Support of different tablespace location value for the same primary-mirror pair 
### Actual behavior
the tablespace location value for the same primary-mirror pair(content) has to be the same.

### Step to reproduce the behavior
create tablespace tbsp_new location '/data/primary/tablespace01' WITH ( 
   content0 = '/data/primary/tablespace01', 
   content2 = '/data/primary/tablespace01', 
   content4 = '/data/primary/tablespace01', 
   content6 = '/data/primary/tablespace01', 

   content1 = '/data/primary/tablespace02', 
   content3 = '/data/primary/tablespace02', 
   content5 = '/data/primary/tablespace02', 
   content7 = '/data/primary/tablespace02');

Different tablespace location value supporting for the same primary-mirror pair 

is necessary for performance reason.

Justification:

1.Keep "each RAID group with a primary-mirror pair list have a symmetrical RAID group with the same primary-mirror list", would be idle for generating a symmetrical external storage flush task queue, which result in better SAS disk performance.

2.However this mean that for some contents, corresponding primary and mirror may be located in different path.
For example: the primary of content27 is located in "/data1", while the mirror of content27 has to be located in "/data2" in the accessory show case.
[topology .pdf](https://github.com/greenplum-db/gpdb/files/4924117/topology.pdf)

3.GP V6 still supporting customized mirror topology injection while initializing. And different design for tablespace feature would be a barrier for consistent UE, as well as a potential performance downgrade factor.

Relating ticket:
https://github.com/greenplum-db/gpdb/issues/8903

**Comment by phan-pivotal** [comment]
4. Tablespace creation in GP other versions other than V6, support "customized topology injection", and most customers under V5 and V4 may have to face this UE change during migration. UE changes are usually challenges or even barrier for our version migration companion, according our prior experience from V4->V5.

Feature Design Advice:
1. Interface proposal:
 create tablespace tbsp_new location '/data/default/tablespace' WITH (
dbid0 = '/data/primary/tablespace01',
dbid1 = '/data/primary/tablespace01',
dbid2 = '/data/primary/tablespace01',
dbid3 = '/data/primary/tablespace01',

dbid4 = '/data/primary/tablespace02',
dbid5 = '/data/primary/tablespace02',
dbid6 = '/data/primary/tablespace02',
dbid7 = '/data/primary/tablespace02',
...
);

**Comment by kun-teng** [comment]
The following are the topology of GP V6.7.1, still lack of "dbid level table space customerized topology injection" feature.

![image](https://user-images.githubusercontent.com/18341650/91300336-b5a8a480-e7d5-11ea-9de6-9f22f0df9dce.png)
![image](https://user-images.githubusercontent.com/18341650/91300354-bb9e8580-e7d5-11ea-876a-b6313fe08e4d.png)

**Comment by asimrp** [comment]
> Keep "each RAID group with a primary-mirror pair list have a symmetrical RAID group with the same primary-mirror list", would be idle for generating a symmetrical external storage flush task queue, which result in better SAS disk performance.

Does that mean Greenplum primary and mirror segments are initialized on a shared storage underneath, e.g. SAN?  The topology and the problem you are trying to describe is not clear to me.

**Comment by kun-teng** [comment]
An example of "each RAID group with a primary-mirror pair list have a symmetrical RAID group with the same primary-mirror list" 

                                           Host1
                         ------------|--------------------
RAID Group1.1                                             RAID Group1.2
-------------|------------                   -----------|-----------------
primary1, primary2, primary3              primary4, primary5, primary6
mirror10, mirror11, mirro12                  mirror7, mirror8, mirror9

                                           Host2
                         ------------|--------------------
RAID Group2.1                                             RAID Group2.2
-------------|------------                   -----------|-----------------
primary7 primary8 primary9              primary10, primary11, primary12
mirror4, mirror5, mirror6                    mirror1,      mirror2,   mirror 3

**Comment by ashwinstar** [comment]
I acknowledge that tablespace feature was changed for Greenplum 6 and forward. Previous versions of Greenplum allows specifying location for primary and mirror tablespace separately. That's something we discontinued as intentional decision in product. We discussed and debated a lot while making the change, but what we have in Greenplum 6 is what we went with and most likely will remain for future versions.
Reason for doing it this way are, to align with PostgreSQL codebase better and also to simplify the management aspect of the same within database. Design in which primary needs to store information about mirrors filepath location just didn't feel right to continue forward. Plus, it also restricted design to be able to support multiple mirrors (Greenplum still supports only one mirror but we didn't wish to continue designing new features limiting us from that aspect). Considering all that tablespace creation only allows specifying path for CONTENT (primary-mirror pair together) and not DBID.

We think modifying the way mount-points are named and configured, its fairly easy to get the same result as is possible for Greenplum 5. Understand exact same setup as is will not work. Though I think its one-time change to make and simplifies overall complexity from database code.

@skahler-vmware in-case you have any tip-tricks to share on this front

**Comment by phan-pivotal** [comment]
**Why the place storing "different primary and mirror file paths of the default tablespace", not suitable for storing 'different primary and mirror file paths of the user-defined tablespace"?**

Multiple mirrors - Good.
Initializing GPV6 with primary and mirror in different path -- Still work.
Primary doesn't store mirrors' default tablespace's filepath location -- Maybe good or not. But there are still a place  storing different primary and mirror file paths of the default tablespace.

**Comment by cobolbaby** [comment]
Any Progress?

**Comment by asimrp** [comment]
@cobolbaby is it not possible to adjust mount points and use symbolic links to achieve the desired layout?  What if you were deploying native PostgreSQL, wouldn't you face the same problem?

**Comment by ashwinstar** [comment]
We have no plans to make change on this front, hence closing this issue.
