### ISSUE TITLE
Multi-level partition table uses gpload merge mode to cause primary key conflicts

### ISSUE THREAD

**Issue by Danpilz** [greenplum-db/gpdb#10501]
Greenplum version 6.3
Centos 7  Linux master 3.10.0-1127.8.2.el7.x86_64 

### **_ddl:_**
![3](https://user-images.githubusercontent.com/35871541/88049785-4b726380-cb88-11ea-8641-b3b74f22e52f.png)

### **_gpload control files:_**
![1](https://user-images.githubusercontent.com/35871541/88049768-41e8fb80-cb88-11ea-83be-7b82656636d5.png)

### **_error messages:_**
![2](https://user-images.githubusercontent.com/35871541/88049774-457c8280-cb88-11ea-91d2-82181e1d9135.png)

### **_gpload.py:_**
![4](https://user-images.githubusercontent.com/35871541/88049794-4f9e8100-cb88-11ea-86e5-89dbfc061041.png)

**Comment by asimrp** [comment]
Thank you @Danpilz for reporting the problem and finding a workaround.  Would you mind posting `git diff -- gpMgmt/bin/gpload.py` output to show how `gpload.py` is changed?  Looking at screenshots is a bit cumbersome.

**Comment by asimrp** [comment]
@linwen would you like to take a look at this problem and the proposed solution?

**Comment by Danpilz** [comment]
@asimrp sure.
```
diff --git a/gpMgmt/bin/gpload.py b/gpMgmt/bin/gpload.py
index d18f76b5cd..1cecabe4a7 100755
--- a/gpMgmt/bin/gpload.py
+++ b/gpMgmt/bin/gpload.py
@@ -2754,7 +2754,7 @@ class gpload:
         sql += 'FROM %s) AS from_table ' % self.staging_table_name
         sql += 'LEFT OUTER JOIN %s into_table ' % self.get_qualified_tablename()
         sql += 'ON %s '%' AND '.join(match)
-        where = self.map_stuff('gpload:output:match_columns',lambda x,y:'into_table.%s IS NULL'%x,0)
+        where = self.map_stuff('gpload:output:match_columns',lambda x,y:'(into_table.{0} IS NULL or cast(into_table.{0} as varchar) = \'\')'.format(x),0)
         sql += 'WHERE %s ' % ' AND '.join(where)
         sql += 'AND gpload_row_number=1)'
```

**Comment by lij55** [comment]
Thanks for reporting the issue, @Danpilz .
We will look into this as soon as possible. Besides, a SQL of DDL and a yaml of config would be much more appreciated because it would help us to reproduce this issue more easily.

**Comment by Danpilz** [comment]
@lij55 Sorry, I can't provide DDL for the production environment, so I changed the field name.
[test.zip](https://github.com/greenplum-db/gpdb/files/4963379/test.zip)

**Comment by lij55** [comment]
It really helps.
Thanks! @Danpilz

**Comment by Danpilz** [comment]
> It really helps.
> Thanks! @Danpilz

So, how did you finally fix this problem? Add = "" in the where condition?

**Comment by lij55** [comment]
could you please do a quick test? disabe the orca and try it again?

**Comment by vraghavan78** [comment]
@Danpilz Orca errors out when it sees a non-deterministic DML behavior. This is stricter than Planner since the operation is not deterministic (I think need to double check). Rather than disabling orca, I would suggest disabling queries on multi-level partitioning support with Orca. This can be done via, `optimizer_multilevel_partitioning to off`.

**Comment by vraghavan78** [comment]
Not planning to change the behavior.
