### ISSUE TITLE
Change/Update the psql verion of the gpdb.

### ISSUE THREAD

**Issue by Wathsara** [greenplum-db/gpdb#10521]
### Greenplum version or build
6.8.1
### OS version
Ubuntu 18.04

 I have installed the above version of gpdb in ubuntu. What I realize is it is running with the psql version 9.4.1. Is there any way to use a newer version of psql than the 9.4.1.?

or

Is there any way to manage unique key violation when inserting bulk to gpdb using the python psycopg2 package. Because If the psql version is higher than the 9.5 I can directly use the ON CONFLICT.

**Comment by kainwen** [comment]
> ### Greenplum version or build
> 6.8.1
> 
> ### OS version
> Ubuntu 18.04
> 
> I have installed the above version of gpdb in ubuntu. What I realize is it is running with the psql version 9.4.1. Is there any way to use a newer version of psql than the 9.4.1.?
> 
> or
> 
> Is there any way to manage unique key violation when inserting bulk to gpdb using the python psycopg2 package. Because If the psql version is higher than the 9.5 I can directly use the ON CONFLICT.

The kernel version of gpdb6X is Postgres9.4. So it can not support upsert(insert on conflict).

It is not related to client version. This is kernel feature.
