### ISSUE TITLE
gp6.6 sql语法问题

### ISSUE THREAD

**Issue by liuzhliang** [greenplum-db/gpdb#10520]
同样的sql在gp4上跑没问题 在gp6上跑报错
[XX000]: ERROR: Context should be init first
sql如下 ：
select
substr(claim.ORG_CD,1,3)
from test_basic claim
inner join test_policy_fact registpolicy
on claim.CLAIM_NOTIF_NO=registpolicy.REGIST_NO and claim.POLICY_NO=registpolicy.POLICY_NO
left join dw_test_basic regist
on claim.CLAIM_NOTIF_NO=regist.CLAIM_NOTIF_NO
left join dw_test_fact claimhis
on claim.CASE_NO=claimhis.CASE_NO
and claimhis.OPEROR_TYPE='0'
and claimhis.THIS_ESTI_DATE<=timestamp '2015-03-01 23:59:59'
and claimhis.NEXT_ESTI_DATE >timestamp '2015-03-01 23:59:59'
left join test_paper_basic compensate
on claim.CASE_NO=compensate.CASE_NO
and compensate.ISRECASE_FLAG='0'
left join test_paper_fact compensate_fact
on compensate.COMPENSATE_NO=compensate_fact.COMPENSATE_NO

**Comment by kainwen** [comment]
> 同样的sql在gp4上跑没问题 在gp6上跑报错
> [XX000]: ERROR: Context should be init first
> sql如下 ：
> select
> substr(claim.ORG_CD,1,3)
> from test_basic claim
> inner join test_policy_fact registpolicy
> on claim.CLAIM_NOTIF_NO=registpolicy.REGIST_NO and claim.POLICY_NO=registpolicy.POLICY_NO
> left join dw_test_basic regist
> on claim.CLAIM_NOTIF_NO=regist.CLAIM_NOTIF_NO
> left join dw_test_fact claimhis
> on claim.CASE_NO=claimhis.CASE_NO
> and claimhis.OPEROR_TYPE='0'
> and claimhis.THIS_ESTI_DATE<=timestamp '2015-03-01 23:59:59'
> and claimhis.NEXT_ESTI_DATE >timestamp '2015-03-01 23:59:59'
> left join test_paper_basic compensate
> on claim.CASE_NO=compensate.CASE_NO
> and compensate.ISRECASE_FLAG='0'
> left join test_paper_fact compensate_fact
> on compensate.COMPENSATE_NO=compensate_fact.COMPENSATE_NO

Can you provide the table's schema?

**Comment by liuzhliang** [comment]
> > 同样的sql在gp4上跑没问题 在gp6上跑报错
> > [XX000]: ERROR: Context should be init first
> > sql如下 ：
> > select
> > substr(claim.ORG_CD,1,3)
> > from test_basic claim
> > inner join test_policy_fact registpolicy
> > on claim.CLAIM_NOTIF_NO=registpolicy.REGIST_NO and claim.POLICY_NO=registpolicy.POLICY_NO
> > left join dw_test_basic regist
> > on claim.CLAIM_NOTIF_NO=regist.CLAIM_NOTIF_NO
> > left join dw_test_fact claimhis
> > on claim.CASE_NO=claimhis.CASE_NO
> > and claimhis.OPEROR_TYPE='0'
> > and claimhis.THIS_ESTI_DATE<=timestamp '2015-03-01 23:59:59'
> > and claimhis.NEXT_ESTI_DATE >timestamp '2015-03-01 23:59:59'
> > left join test_paper_basic compensate
> > on claim.CASE_NO=compensate.CASE_NO
> > and compensate.ISRECASE_FLAG='0'
> > left join test_paper_fact compensate_fact
> > on compensate.COMPENSATE_NO=compensate_fact.COMPENSATE_NO
> 
> Can you provide the table's schema?

**Comment by adam8157** [comment]
@liuzhliang Could you please give a reproducer? The tables' DDLs and queries to trigger this issue in a clean database.

Thanks.

**Comment by kainwen** [comment]
Long time no response.

Feel free to reopen this if you still have more issues. @liuzhliang
