### ISSUE TITLE
COPY FROM AO table cause empty segfile to be created in master's data directory

### ISSUE THREAD

**Issue by fangzheng** [greenplum-db/gpdb#10551]
### Greenplum version or build
6X_STABLE

### Step to reproduce the behavior
Create an AO table a and execute `COPY a FROM '/tmp/file'`. As a result, an empty segfile is created under master's data directory. I am wondering if this is expected.

1. Run the following SQL from psql: 
````
psql (9.4.24)
Type "help" for help.

postgres=# CREATE TABLE a (a INT) WITH (appendonly=true, orientation=row);
NOTICE:  Table doesn't have 'DISTRIBUTED BY' clause -- Using column named 'a' as the Greenplum Database data distribution key for this table.
HINT:  The 'DISTRIBUTED BY' clause determines the distribution of data. Make sure column(s) chosen are the optimal data distribution key to minimize skew.
CREATE TABLE
postgres=# copy a from '/tmp/file';
COPY 1
postgres=# select * from a;
 a 
---
 1
(1 row)
````

2. Find an empty segfile in master's data directory:
````
ls -s datadirs/qddir/demoDataDir-1/base/12812/16384.1
0 datadirs/qddir/demoDataDir-1/base/12812/16384.1
````

**Comment by fangzheng** [comment]
Looks that in the COPY FROM case, QD on master would go through the call chain of CopyFrom() --> appendonly_insert_init() --> SetCurrentFileSegForWrite() --> SetCurrentFileSegForWrite() --> AppendOnlyStorageWrite_OpenFile(). 

It might be reasonable to check for Gp_role and skip file creation on QD side.

**Comment by adam8157** [comment]
Thanks for reporting, would you like to submit a PR?

**Comment by fangzheng** [comment]
@adam8157 Sorry for late reply and thanks for confirmation. I will submit a PR soon.

**Comment by ashwinstar** [comment]
PR https://github.com/greenplum-db/gpdb/pull/10850 was closed with "the code change seems to cause more risks than gains." Hence closing this issue as Won't Fix.
