### ISSUE TITLE
psql help copyright is outdated

### ISSUE THREAD

**Issue by ascherbaum-pivotal** [greenplum-db/gpdb#1056]
The copyright in psql is last updated 2011, and still states EMC.

https://github.com/greenplum-db/gpdb/blob/master/src/bin/psql/help.c#L460

**Comment by ascherbaum-pivotal** [comment]
@ivannovick Can you please provide a new copyright statement?

**Comment by ivannovick** [comment]
@andreasscherbaum can you update it?

**Comment by ivannovick** [comment]
I am not coding :)

**Comment by andreasscherbaum** [comment]
@ivannovick If you say the new copyright line is ok, I'm happy to go ahead and update it.

**Comment by ivannovick** [comment]
@andreasscherbaum can you do a PR?

**Comment by ivannovick** [comment]
We need to update the year for sure, and removing EMC and putting Pivotal sounds good

**Comment by Eulerizeit** [comment]
According to David Schachner

"To avoid having to continually adjust, you can also use the following format on the © notice:

Copyright (c) YYYY - Present Pivotal Software, Inc. 

...where YYYY is the year of first creation/publication."

**Comment by andreasscherbaum** [comment]
@ivannovick Already there: https://github.com/greenplum-db/gpdb/pull/1193

**Comment by ivannovick** [comment]
looks good to merge

**Comment by ascherbaum-pivotal** [comment]
Merged
