### ISSUE TITLE
Changing datatype of distribution key fails with bad message

### ISSUE THREAD

**Issue by hlinnaka** [greenplum-db/gpdb#10561]
### Greenplum version or build
6X_STABLE, 5X_STABLE

### Actual behavior

```
postgres=# create table foo (i int4 primary key, j int);
CREATE TABLE
postgres=# alter table foo alter i type numeric;
psql: ERROR:  relation "foo_pkey" already exists  (seg0 127.0.0.1:40000 pid=330)
```

### Expected behavior

I would've expected that to either work without error, or give a more appropriate error message.

**Comment by JunfengYang** [comment]
The checks in
https://github.com/greenplum-db/gpdb/blob/22308d6ab296d3a7cbf0cd4c3dd99c8bfb779136/src/backend/commands/tablecmds.c#L11543-L11560
is not working because `foo` is empty.

```
if (Gp_role == GP_ROLE_DISPATCH &&
		GpPolicyIsPartitioned(rel->rd_cdbpolicy) &&
		tab->dist_opfamily_changed)
	{
		relContainsTuples = cdbRelMaxSegSize(rel) > 0;
	}
```
The `relContainsTuples` is `false`.

After inserting several rows into `foo`, it works.
```
demo=# insert into foo select * from generate_series(1, 100);
INSERT 0 100
alter table foo alter i type numeric;
ERROR:  changing the type of a column that is used in a UNIQUE or PRIMARY KEY constraint is not allowed
```
Is it ok to remove this check https://github.com/greenplum-db/gpdb-postgres-merge/commit/963783630fae596802e1f0a8855495bc8554b82a?


So if the `foo` is empty, we should delete the old index, and recreate a new one.
But it seems the old index is not deleted on segments.

**Comment by JunfengYang** [comment]
For a normal indexed column, we required the user to drop the index before changing the column type even the table is empty:
```
demo=# create index j_idx on foo using btree (j);
demo=# alter table foo alter j type numeric;
ERROR:  cannot alter indexed column
HINT:  DROP the index first, and recreate it after the ALTER
```

**Comment by JunfengYang** [comment]
For the constraints, after altering the type, we execute `performDeletion` under `ATPostAlterTypeCleanup` only on master, this cause the error.
Any thoughts?

Shall we let the user drop the constraints before changing the column type like the normal index or dispatch the deletion on each segment under `ATPostAlterTypeCleanup`?

**Comment by JunfengYang** [comment]
@hlinnaka the title seems not right.

```
demo=# create table foo (i int4, j int) distributed by (i);
CREATE TABLE
demo=# \d foo
      Table "public.foo"
 Column |  Type   | Modifiers
--------+---------+-----------
 i      | integer |
 j      | integer |
Distributed by: (i)

demo=# alter table foo alter i type numeric;
ALTER TABLE
```

If the distribution key column doesn't contain any constraint, the alter will succeed.

**Comment by JunfengYang** [comment]
Raise a reasonable error message as the fix.
Merged in master https://github.com/greenplum-db/gpdb/commit/32446a321d492226d3f26d91f3b0deeabce90fd4 and 6X https://github.com/greenplum-db/gpdb/commit/0515db0ad894cc82865a7247a65da560021eee7e.
