### ISSUE TITLE
Greenplum gets only 1000 objects from s3 bucket

### ISSUE THREAD

**Issue by avkashin** [greenplum-db/gpdb#10563]
### Greenplum version or build
PostgreSQL 9.4.24 (Greenplum Database 6.8.1 build OSS) on x86_64-unknown-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39), 64-bit compiled
on Jul 30 2020 11:19:50
### OS version and uname -a
CentOS Linux release 7.8.2003 (Core)
Linux mdw1.ru-central1.internal 3.10.0-1127.13.1.el7.x86_64 #1 SMP Tue Jun 23 15:46:38 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
### autoconf options used ( config.status --config )
'--with-perl' '--with-python' '--with-libxml' '--with-gssapi' '--prefix=/usr/local/greenplum-db-6.8.1' '--enable-gpperfmon' '--enable-pxf' '--enable-orca' '--with-ldap' '--with-openssl' '--with-pam' '--with-zstd'
### Installation information ( pg_config )
BINDIR = /usr/local/greenplum-db-6.8.1/bin
DOCDIR = /usr/local/greenplum-db-6.8.1/share/doc/postgresql
HTMLDIR = /usr/local/greenplum-db-6.8.1/share/doc/postgresql
INCLUDEDIR = /usr/local/greenplum-db-6.8.1/include
PKGINCLUDEDIR = /usr/local/greenplum-db-6.8.1/include/postgresql
INCLUDEDIR-SERVER = /usr/local/greenplum-db-6.8.1/include/postgresql/server
LIBDIR = /usr/local/greenplum-db-6.8.1/lib
PKGLIBDIR = /usr/local/greenplum-db-6.8.1/lib/postgresql
LOCALEDIR = /usr/local/greenplum-db-6.8.1/share/locale
MANDIR = /usr/local/greenplum-db-6.8.1/share/man
SHAREDIR = /usr/local/greenplum-db-6.8.1/share/postgresql
SYSCONFDIR = /usr/local/greenplum-db-6.8.1/etc/postgresql
PGXS = /usr/local/greenplum-db-6.8.1/lib/postgresql/pgxs/src/makefiles/pgxs.mk
CONFIGURE = '--with-perl' '--with-python' '--with-libxml' '--with-gssapi' '--prefix=/usr/local/greenplum-db-6.8.1' '--enable-gpperfmon' '--enable-pxf' '--enable-orca' '--with-ldap' '--with-openssl' '--with-pam' '--with-zstd'
CC = gcc
CPPFLAGS = -D_GNU_SOURCE -I/usr/include/libxml2 -I/usr/local/greenplum-db-6.8.1/include
CFLAGS = -Wall -Wmissing-prototypes -Wpointer-arith -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fno-aggressive-loop-optimizations -Wno-unused-but-set-variable -Wno-address -O3 -std=gnu99 -Werror=uninitialized -Werror=implicit-function-declaration -I/usr/local/greenplum-db-6.8.1/include
CFLAGS_SL = -fPIC
LDFLAGS = -Wl,--as-needed -Wl,-rpath,'/usr/local/greenplum-db-6.8.1/lib',--enable-new-dtags -L/usr/local/greenplum-db-6.8.1/lib
LDFLAGS_EX =
LDFLAGS_SL =
LIBS = -lpgcommon -lpgport -lxerces-c -lxml2 -lpam -lrt -lgssapi_krb5 -lzstd -lrt -lcrypt -ldl -lm -L/usr/local/greenplum-db-6.8.1/lib
VERSION = PostgreSQL 9.4.24
### Expected behavior
Greenplum gets all objects from s3 bucket
### Actual behavior
Greenplum gets only 1000 objects from s3 bucket
### Step to reproduce the behavior
I've bucket - gpt3st - in Yandex S3 Object Storage - https://cloud.yandex.com/docs/storage/
In my bucket more than 1000 objects and Yandex like an AWS using pagination for output. I can get a list of 1000 objects per request.
When I trying to read my data from s3 bucket from greenplum I receive only 1000 objects and no more.
For example:
`gpcheckcloud -c 's3://storage.yandexcloud.net/gpt3st config=/home/gpadmin/yandex.conf region=us-east-1' | wc -l
`
`
Your configuration works well.`
`1000`

The same situation when I trying to read data from external table using s3 protocol.
 Here is part of xml from `tpcdump` which greenplum received from s3 provider
`<?xml version="1.0" encoding="UTF-8"?>`
`<ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/">`
`<Name>gpt3st</Name>`
`<Prefix></Prefix>`
`<MaxKeys>1000</MaxKeys>`
`<IsTruncated>true</IsTruncated>`
`<Contents>`
`<Key>blah-1.csv.gz</Key>`
`<LastModified>2020-07-31T11:44:21.231Z</LastModified>`
`<ETag>&#34;6d4911974e3c985bfb2b43dcf182afcf&#34;</ETag>`
`<Size>938475</Size>`
`<StorageClass>STANDARD</StorageClass>`
`</Contents>`
`...cuttin 1000 of content tags`
`<Marker></Marker>`
`</ListBucketResult>`

Why greenplum gets only 1000 objects and no more? I thought when parameter `IsTruncated` present in response in xml from s3, greenplum should send few requests to s3 until he gets all objects.

Thanks a lot.

**Comment by adam8157** [comment]
https://github.com/greenplum-db/gpdb/blob/0b17968e808a34dacf7de0c65eb6a5989009385e/gpcontrib/gpcloud/src/s3interface.cpp#L286-L321

`IsTruncated` and `Marker` are already handled actually. What do the keys look like? I suppose `blah-1.csv.gz` is not the real name.

**Comment by avkashin** [comment]
Hi,
@adam8157 thank you for your answer.
`blah-<Num>.csv.gz` is the real name of keys. `<Num>` is from 1 to 1200. This bucket was created just for testing purposes. I attach http stream between GP and s3 server - [gpt3st_http_gp.txt](https://github.com/greenplum-db/gpdb/files/5149130/gpt3st_http_gp.txt)

If the name of the keys is matter, I can repeat the test with another names.

**Comment by adam8157** [comment]
I was thinking it might be an encoding issue, probably not based on your latest info.

gpcloud has a test for this `ListBucketWithBucketWithMoreThan1000Keys`, I have no other ideas, will leave this issue to the maintaining team.

**Comment by avkashin** [comment]
@adam8157 thanks a lot!

**Comment by lij55** [comment]
Could you please try PXF for the same bucket? We would suggest PXF if it can work

**Comment by avkashin** [comment]
Was fixed in https://github.com/greenplum-db/gpdb/pull/12442.
