### ISSUE TITLE
"database ""gpadmin2"" does not exist",,,,,,,0,,"postinit.c",957

### ISSUE THREAD

**Issue by luowencai** [greenplum-db/gpdb#10648]
### Greenplum version or build

select version();
                                                                                               version                                                                      
                          
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
--------------------------
 PostgreSQL 9.4.24 (Greenplum Database 6.7.1 build commit:a21de286045072d8d1df64fa48752b7dfac8c1b7) on x86_64-unknown-linux-gnu, compiled by gcc (GCC) 6.4.0, 64-bit compile
d on Apr 30 2020 00:11:21
(1 row)

### Actual behavior
```
2020-08-15 22:34:37.721147 CST,"gpadmin2","gpadmin2",p28207,th-1585416128,"127.0.0.1","26584",2020-08-15 22:34:37 CST,0,con2327073,,seg-1,,,,sx1,"FATAL","3D000","database ""gpadmin2"" does not exist",,,,,,,0,,"postinit.c",957,
```

```
=> \l
                                     List of databases
   Name    |  Owner   | Encoding |  Collate   |   Ctype    |       Access privileges        
-----------+----------+----------+------------+------------+--------------------------------
 gpperfmon | gpadmin2 | UTF8     | en_US.utf8 | en_US.utf8 | gpadmin2=CTc/gpadmin2         +
           |          |          |            |            | =c/gpadmin2
 ibxdata   | gpadmin2 | UTF8     | en_US.utf8 | en_US.utf8 | =Tc/gpadmin2                  +
           |          |          |            |            | gpadmin2=CTc/gpadmin2         +
           |          |          |            |            | ibndata_job_owner=CTc/gpadmin2
 postgres  | gpadmin2 | UTF8     | en_US.utf8 | en_US.utf8 | 
 template0 | gpadmin2 | UTF8     | en_US.utf8 | en_US.utf8 | =c/gpadmin2                   +
           |          |          |            |            | gpadmin2=CTc/gpadmin2
 template1 | gpadmin2 | UTF8     | en_US.utf8 | en_US.utf8 | =c/gpadmin2                   +
           |          |          |            |            | gpadmin2=CTc/gpadmin2


```
What does this fatal mean?We don't have a database which name the admin user name,It's very strange.

**Comment by paul-guo-** [comment]
Do not know how did you access the database, but for psql if there is no database related env variable, option, etc is specified, it uses the current OS user name as database name. I'm closing this issue unless there is more evidence that shows this is a bug.

```
[pguo@host67@6:/data2]$ echo $PGDATABASE
postgres
[pguo@host67@6:/data2]$ unset PGDATABASE
[pguo@host67@6:/data2]$ psql
psql: FATAL:  database "pguo" does not exist
```
