### ISSUE TITLE
TupleSplit method of DISTINCT aggregation is wrong with FILTERs

### ISSUE THREAD

**Issue by hlinnaka** [greenplum-db/gpdb#10645]
### Greenplum version or build
master

### Step to reproduce the behavior

Consider this:
```
postgres=# create table foo (i int, j int);
psql: NOTICE:  Table doesn't have 'DISTRIBUTED BY' clause -- Using column named 'i' as the Greenplum Database data distribution key for this table.
HINT:  The 'DISTRIBUTED BY' clause determines the distribution of data. Make sure column(s) chosen are the optimal data distribution key to minimize skew.
CREATE TABLE
postgres=# insert into foo select g, g from generate_series (1, 1000) g;
INSERT 0 1000
postgres=# select sum(distinct i) FILTER (WHERE j > 0), sum(distinct j) FILTER (WHERE j > 0) from foo;
postgres=# select sum(distinct i) FILTER (WHERE i > 0), sum(distinct j) FILTER (WHERE i > 0) from foo;
  sum   | sum 
--------+-----
 500500 |    
(1 row)

```
The first sum is correct, but the second one is wrong, it should be the same as the first sum. The plan is:
```
postgres=# explain verbose select sum(distinct i) FILTER (WHERE i > 0), sum(distinct j) FILTER (WHERE i > 0) from foo;
                                                      QUERY PLAN                                                      
----------------------------------------------------------------------------------------------------------------------
 Finalize Aggregate  (cost=20.66..20.67 rows=1 width=16)
   Output: sum(DISTINCT i) FILTER (WHERE (i > 0)), sum(DISTINCT j) FILTER (WHERE (i > 0))
   ->  Gather Motion 3:1  (slice1; segments: 3)  (cost=20.62..20.65 rows=1 width=16)
         Output: (PARTIAL sum(DISTINCT i) FILTER (WHERE (i > 0))), (PARTIAL sum(DISTINCT j) FILTER (WHERE (i > 0)))
         ->  Partial Aggregate  (cost=20.62..20.63 rows=1 width=16)
               Output: PARTIAL sum(DISTINCT i) FILTER (WHERE (i > 0)), PARTIAL sum(DISTINCT j) FILTER (WHERE (i > 0))
               ->  Redistribute Motion 3:3  (slice2; segments: 3)  (cost=20.50..20.59 rows=1 width=8)
                     Output: i, j, (AggExprId)
                     Hash Key: i, j, (AggExprId)
                     ->  Streaming HashAggregate  (cost=20.50..20.53 rows=1 width=8)
                           Output: i, j, (AggExprId)
                           Group Key: AggExprId, foo.i, foo.j
                           ->  TupleSplit  (cost=13.00..15.50 rows=667 width=8)
                                 Output: i, j, AggExprId
                                 Split by Col: (foo.i), (foo.j)
                                 ->  Seq Scan on public.foo  (cost=0.00..13.00 rows=334 width=8)
                                       Output: i, j
 Optimizer: Postgres query optimizer
 Settings: optimizer=off
(19 rows)
```

The TupleSplit divides rows based on the DISTINCT. For example, if an input row is (1, 1), it is divided into two rows: (1, NULL) and (NULL, 1). The first row is fed into the first aggregate, `SUM(DISTINCT i) FILTER (WHERE i > 0)`. The second row is fed to `SUM(DISTINCT j) FILTER (WHERE j > 0)`. The second one is problematic, because in the row the 'j' has been turned into NULL, so it doesn't pass the FILTER, even though the original row did.

**Comment by weinan003** [comment]
The filter can push down to TupleSplit to fix this issue, I'll give a PR later

**Comment by weinan003** [comment]
Fix by a PR.
After this PR. I'm thinking about how to implement normal Agg with multi-DQA MPP query plan. For normal Aggs which without filter, we can assign one tuple from TupleSplit with the same AggExprId. But if normal Agg has a filter, we also need to push down the filter to TupleSplit, since if the filter is a subquery which may have a motion in it. 

For instance
`SELECT DQA_1(expr1) filter (subquery 1), DQA_2(expr2), Agg(expr3) filter(subquery1),Agg(expr4) filter(subquery1),...`
The query only has two DQA but several normal AGG with filter. For this kind of query, our previous sharedinputscan method cost should win.

So, after merge, maybe we need to think if support both kinds of DQA MPP plan? @gaos1
