### ISSUE TITLE
configure script giving a number of errors

### ISSUE THREAD

**Issue by arunmarathe** [greenplum-db/gpdb#10667]
### OS version and uname -a
Linux vm-arunm 3.10.0-1127.13.1.el7.x86_64 #1 SMP Tue Jun 23 15:46:38 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

### Step to reproduce the behavior
 ./configure --with-perl --with-python --with-libxml --with-gssapi --prefix=/usr/local/gpdb

I have made a few changes to "configure" script locally, as indicated below, but it keeps on failing for different reasons. Maybe there is something obviously missing or wrong?

```
[root@vm-arunm gpdb_src]# git diff --color configure
diff --git a/configure b/configure
index 824099f..6a02b3f 100755
--- a/configure
+++ b/configure
@@ -4077,7 +4077,8 @@ See \`config.log' for more details" "$LINENO" 5; }
 $as_echo "$as_me:${as_lineno-$LINENO}: checking for C compiler version" >&5
 set X $ac_compile
 ac_compiler=$2
-for ac_option in --version -v -V -qversion; do
+# for ac_option in --version -v -V -qversion; do
+for ac_option in --version -v; do
   { { ac_try="$ac_compiler $ac_option >&5"
 case "(($ac_try" in
   *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
@@ -4679,7 +4680,8 @@ fi
 $as_echo "$as_me:${as_lineno-$LINENO}: checking for C++ compiler version" >&5
 set X $ac_compile
 ac_compiler=$2
-for ac_option in --version -v -V -qversion; do
+# for ac_option in --version -v -V -qversion; do
+for ac_option in --version -v; do
   { { ac_try="$ac_compiler $ac_option >&5"
 case "(($ac_try" in
   *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;

```

Basically it did not like -V and -qversion options of the gcc compiler, the current error is that it cannot compile the sample programs.

```
[root@vm-arunm gpdb_src]# gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/opt/rh/devtoolset-7/root/usr/libexec/gcc/x86_64-redhat-linux/7/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,fortran,lto --prefix=/opt/rh/devtoolset-7/root/usr --mandir=/opt/rh/devtoolset-7/root/usr/share/man --infodir=/opt/rh/devtoolset-7/root/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --enable-plugin --with-linker-hash-style=gnu --enable-initfini-array --with-default-libstdcxx-abi=gcc4-compatible --with-isl=/builddir/build/BUILD/gcc-7.3.1-20180303/obj-x86_64-redhat-linux/isl-install --enable-libmpx --enable-gnu-indirect-function --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 7.3.1 20180303 (Red Hat 7.3.1-5) (GCC)

```

Can you please help?

Thanks,
Arun

**Comment by hlinnaka** [comment]
Hi! Modifying 'configure' really shouldn't be necessary. What was the error you got with unmodified 'configure'? Are there any clues in 'config.log'?

**Comment by arunmarathe** [comment]
Hi, Thanks for your response.

Here is the output from unmodified configure (last few lines on console).

```
checking whether g++ supports C++14 features with +std=c++14... no
checking whether g++ supports C++14 features with -h std=c++14... no
checking whether g++ supports C++14 features with -std=c++1y... no
checking whether g++ supports C++14 features with +std=c++1y... no
checking whether g++ supports C++14 features with -h std=c++1y... no
configure: error: *** A compiler with support for C++14 language features is required.
```

Inside the log file, the error is:

```
configure:4097: $? = 0
configure:4086: gcc -v >&5
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-39) (GCC)
configure:4097: $? = 0
configure:4086: gcc -V >&5
gcc: error: unrecognized command line option '-V'
gcc: fatal error: no input files
compilation terminated.
configure:4097: $? = 4
configure:4086: gcc -qversion >&5
gcc: error: unrecognized command line option '-qversion'
gcc: fatal error: no input files
compilation terminated.
```

It does not like the -V and -qversion compiler options. When I took out those two options from a couple of places, I got the error that I posted in my original bug report.

**Comment by arunmarathe** [comment]
Hi, Can anyone please look into this issue? I can provide more information if needed (various versions etc.).
If configure does not work, installation does not work. Thanks.

**Comment by asimrp** [comment]
The original configure error indicates that the compiler is too old.  Support for C++14 language standard seems to be available in gcc 5 onward, according to https://gcc.gnu.org/projects/cxx-status.html#cxx14
Can you try to upgrade your gcc to version and try again?

**Comment by arunmarathe** [comment]
Hi Asim, My compiler is up-to-date.

```
[root@vm-arunm arunm]# scl enable devtoolset-7 bash
[root@vm-arunm arunm]# which gcc
/opt/rh/devtoolset-7/root/usr/bin/gcc
[root@vm-arunm arunm]# gcc --version
gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

```

And verified that as non-root the same gcc is in effect. Thanks.

**Comment by hlinnaka** [comment]
The excerpt from your log said:
```
configure:4086: gcc -v >&5
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-39) (GCC)
```
Configure is picking up gcc version 4.8.5 from somewhere. I don't know what's going, but there is something funny with your gcc versions.

**Comment by arunmarathe** [comment]
> The excerpt from your log said:
> 
> ```
> configure:4086: gcc -v >&5
> Using built-in specs.
> COLLECT_GCC=gcc
> COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
> Target: x86_64-redhat-linux
> Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
> Thread model: posix
> gcc version 4.8.5 20150623 (Red Hat 4.8.5-39) (GCC)
> ```
> 
> Configure is picking up gcc version 4.8.5 from somewhere. I don't know what's going, but there is something funny with your gcc versions.


Thanks hlinnaka!
That was indeed part of the issue.
I have resolved it, and now the correct compiler version is referenced.
Still the error appears to be the same.



```
configure:4097: $? = 0
configure:4086: gcc -v >&5
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/opt/rh/devtoolset-7/root/usr/libexec/gcc/x86_64-redhat-linux/7/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,fortran,lto --prefix=/opt/rh/devtoolset-7/root/usr --mandir=/opt/rh/devtoolset-7/root/usr/share/man --infodir=/opt/rh/devtoolset-7/root/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --enable-plugin --with-linker-hash-style=gnu --enable-initfini-array --with-default-libstdcxx-abi=gcc4-compatible --with-isl=/builddir/build/BUILD/gcc-7.3.1-20180303/obj-x86_64-redhat-linux/isl-install --enable-libmpx --enable-gnu-indirect-function --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 7.3.1 20180303 (Red Hat 7.3.1-5) (GCC)
configure:4097: $? = 0
configure:4086: gcc -V >&5
gcc: error: unrecognized command line option '-V'
gcc: fatal error: no input files
compilation terminated.
configure:4097: $? = 1
configure:4086: gcc -qversion >&5
gcc: error: unrecognized command line option '-qversion'; did you mean '--version'?
gcc: fatal error: no input files
compilation terminated.

```

**Comment by arunmarathe** [comment]
This is still an open issue. Can someone from the product team please take a look?

Thanks,
Arun

**Comment by hlinnaka** [comment]
What is the error message from configure you're seeing? The same as before, i.e. `configure: error: *** A compiler with support for C++14 language features is required.` ? That message suggests that your compiler doesn't support C++14 features needed by GPDB. I'm not sure what exactly the requirements are. Do you have a C++ compiler installed at all? If you try to compile a test program with `g++ -std=c++14`

**Comment by arunmarathe** [comment]
> What is the error message from configure you're seeing? The same as before, i.e. `configure: error: *** A compiler with support for C++14 language features is required.` ? That message suggests that your compiler doesn't support C++14 features needed by GPDB. I'm not sure what exactly the requirements are. Do you have a C++ compiler installed at all? If you try to compile a test program with `g++ -std=c++14`, what happens?


The error in the config.log file is this:
```
gcc version 7.3.1 20180303 (Red Hat 7.3.1-5) (GCC)
configure:4701: $? = 0
configure:4705: checking whether we are using the GNU C++ compiler
configure:4724: g++ -c   conftest.cpp >&5
configure:4724: $? = 0
configure:4733: result: yes
configure:4742: checking whether g++ accepts -g
configure:4762: g++ -c -g  conftest.cpp >&5
configure:4762: $? = 0
configure:4803: result: yes
configure:4844: gcc -c -g -O2  conftest.c >&5
conftest.c: In function 'main':
conftest.c:23:1: error: unknown type name 'choke'
 choke me
 ^~~~~
configure:4844: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "Greenplum Database"
| #define PACKAGE_TARNAME "greenplum-database"
| #define PACKAGE_VERSION "7.0.0-alpha.0"
| #define PACKAGE_STRING "Greenplum Database 7.0.0-alpha.0"
| #define PACKAGE_BUGREPORT "support@greenplum.org"
| #define PACKAGE_URL ""

```

On the command line where I invoke "./configure", the error is this:

```
checking whether to build with OpenSSL support... no
checking whether to build with SELinux support... no
checking whether to build with systemd support... no
configure: error: libxml is required by gpcloud

```

**Comment by hlinnaka** [comment]
> First of all, I had to delete '-V' and '-qversion' options in two places because I was getting the above-mentioned error.

That really shouldn't be necessary. Note that it is normal for `config.log` to contain error messages. `configure` tries probes compiler options by trying to use them in a test program. If the compiling the test program fails, it concludes that the option is not supported by the compiler. All the different things it tries are recorded in the log, some of which error out and some work.

So the key here is the libxml error. Clearly you don't have libxml or its header files installed. I can't help you with that, I'm not familiar with the distribution you're using.

**Comment by arunmarathe** [comment]
> > First of all, I had to delete '-V' and '-qversion' options in two places because I was getting the above-mentioned error.
> 
> That really shouldn't be necessary. Note that it is normal for `config.log` to contain error messages. `configure` tries probes compiler options by trying to use them in a test program. If the compiling the test program fails, it concludes that the option is not supported by the compiler. All the different things it tries are recorded in the log, some of which error out and some work.
> 
> So the key here is the libxml error. Clearly you don't have libxml or its header files installed. I can't help you with that, I'm not familiar with the distribution you're using.

Thanks Heikki.
I have CentOS 7.8 release, and have libxml2 package. That release does not seem to have libxml package.

```
[root@vm-arunm arunm]# cat /etc/centos-release
CentOS Linux release 7.8.2003 (Core)

```

**Comment by adam8157** [comment]
Check out the `README.CentOS.bash` in the source tree, what you need is `libxml2-devel`.

Feel free to reopen if you still have compiling issues after running `README.CentOS.bash`.
