### ISSUE TITLE
metaData.isNullable(i) always return 2

### ISSUE THREAD

**Issue by jerryliu306** [greenplum-db/gpdb#10671]
**I'm submitting a ...**

test table:
drop table if exists test.sys_user1;
create table test.sys_user1(id serial not null) distributed by(id);

when i use metaData.isNullable(i) always return 2.

**Describe the issue**
Class.forName("org.postgresql.Driver");
            String url = "jdbc:postgresql://gpmaster:5432/testdb";
            String username = "gptest";
            String password = "000000";
            Connection conn = DriverManager.getConnection(url, username, password);
            Statement stm = conn.createStatement();
            String sql = "SELECT * FROM test.sys_user1 LIMIT 0";
            ResultSet rs = stm.executeQuery(sql);
            ResultSetMetaData metaData = rs.getMetaData();
            int count = metaData.getColumnCount();
            for(int i = 1; i <= count; i++) {
                String columnName = metaData.getColumnName(i);
                String columnTypeName = metaData.getColumnTypeName(i);
                int nullAble = metaData.isNullable(i);
                System.out.printf("%s, %s, %d\n", columnName, columnTypeName, nullAble);
            }

**Driver Version?** 
42.2.14
**Java Version?**
1.8
**OS Version?**
Linux hostname 3.10.0-862.el7.x86_64 #1 SMP Fri Apr 20 16:44:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
**PostgreSQL Version?**
9.4.24

print:
id, int4, 2

test in postgreSQL:
print:
id, serial, 0

----------------------------
when i use sql query metadata:
SELECT a.attnum AS ordinal_position,
         a.attname AS column_name,
         t.typname AS data_type,
         a.attlen AS character_maximum_length,
         a.atttypmod AS modifier,
         a.attnotnull AS notnull,
         a.atthasdef AS hasdefault
    FROM pg_class c,
         pg_attribute a,
         pg_type t
   WHERE c.relname = 'sys_user1'
     AND a.attnum > 0
     AND a.attrelid = c.oid
     AND a.atttypid = t.oid
ORDER BY a.attnum;

 ordinal_position | column_name | data_type | character_maximum_length | modifier | notnull | hasdefault
------------------+-------------+-----------+--------------------------+----------+---------+------------
                1 | id          | int4      |                        4 |       -1 | t       | t
(1 row)

**Comment by hlinnaka** [comment]
I cannot reproduce this. I'm getting the same result on GPDB 6 as on PostgreSQL:
```
$ psql postgres -c "select version()"
                                                                                  version                                                                                   
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 PostgreSQL 9.4.24 (Greenplum Database 6.0.0-beta.1 build dev) on x86_64-unknown-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit compiled on Aug 10 2020 19:58:05
(1 row)

$ java  -cp /tmp/postgresql-42.2.14.jar:. issue10671
id, serial, 0
```

**Comment by frankgh** [comment]
Same here, I'm unable to repro using the same posgresql driver, and a build version of Greenplum
```
testdb=# select version();
                                                                                                               version
-----------------------------------------------------------------------------------------------------------------------------
 PostgreSQL 9.4.24 (Greenplum Database 6.7.1+dev.105.g26c483b2057 build dev) on x86_64-apple-darwin18.7.0, compiled by Apple
(1 row)
```

![Screen Shot 2020-08-19 at 9 21 00 AM](https://user-images.githubusercontent.com/6936241/90662655-7ab6d780-e1fd-11ea-9f90-ae46ab38dc44.png)

As shown in the screenshot above, `nullable` is 0 for me.

**Comment by jerryliu306** [comment]
> Same here, I'm unable to repro using the same posgresql driver, and a build version of Greenplum
> 
> ```
> testdb=# select version();
>                                                                                                                version
> -----------------------------------------------------------------------------------------------------------------------------
>  PostgreSQL 9.4.24 (Greenplum Database 6.7.1+dev.105.g26c483b2057 build dev) on x86_64-apple-darwin18.7.0, compiled by Apple
> (1 row)
> ```
> 
> ![Screen Shot 2020-08-19 at 9 21 00 AM](https://user-images.githubusercontent.com/6936241/90662655-7ab6d780-e1fd-11ea-9f90-ae46ab38dc44.png)
> 
> As shown in the screenshot above, `nullable` is 0 for me. Maybe you have ORCA enabled? Can you try this code:
> 
> ```java
>         Class.forName("org.postgresql.Driver");
>         String url = "jdbc:postgresql://localhost:6000/testdb";
>         Connection conn = DriverManager.getConnection(url);
>         Statement stm = conn.createStatement();
>         String sql = "SELECT * FROM sys_user1 LIMIT 0";
>         stm.execute("set optimizer = off;");
>         ResultSet rs = stm.executeQuery(sql);
>         ResultSetMetaData metaData = rs.getMetaData();
>         int count = metaData.getColumnCount();
>         for (int i = 1; i <= count; i++) {
>             String columnName = metaData.getColumnName(i);
>             String columnTypeName = metaData.getColumnTypeName(i);
>             int nullAble = metaData.isNullable(i);
>             System.out.printf("%s, %s, %d\n", columnName, columnTypeName, nullAble);
>         }
> ```

thank you, add stm.execute("set optimizer = off;"); resolved.

**Comment by jerryliu306** [comment]
thank you @frankgh , add stm.execute("set optimizer = off;"); resolved.
