### ISSUE TITLE
Nested queries return error server closed the connection unexpectedly using GROUP BY GROUPING SETS

### ISSUE THREAD

**Issue by ryonchen** [greenplum-db/gpdb#10692]
### Greenplum version or build & OS version and uname -a
PostgreSQL 9.4.24 (Greenplum Database 6.10.1 build commit:efba04ce26ebb29b535a255a5e95d1f5ebfde94e) on x86_64-unknown-linux-gnu, compiled by gcc (GCC) 6.4.0, 64-bit compiled on Aug 13 2020 02:56:29

### Expected behavior
When executing two-tier nested SQL, the innermost query uses group by, and the outermost query uses group by grouping set, for example ：
select id , theme_name,sum(cnt) from (
select id, theme_name,cnt from (
    select id, theme_name, count(1) as cnt 
    from test.test_tbl
    group by id , theme_name
) t
) t 
GROUP BY GROUPING SETS ( ( "id" ), ( "id", "theme_name" ) ) 

I hope get the result ,but it returned error:
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.

**Comment by hlinnaka** [comment]
I can reproduce this on 6.10.1, but not on the head of 6X_STABLE branch. This was fixed in commit f913cba22f2cc6b08a843439eef1fe1286bf53a9 (https://github.com/greenplum-db/gpdb/issues/10491). Closing.

**Comment by ryonchen** [comment]
Thanks a lot!!!When will the official version be released?

**Comment by ryonchen** [comment]
> I can reproduce this on 6.10.1, but not on the head of 6X_STABLE branch. This was fixed in commit [f913cba](https://github.com/greenplum-db/gpdb/commit/f913cba22f2cc6b08a843439eef1fe1286bf53a9) (#10491). Closing.

Thanks a lot!!!When will the official version be released?
