### ISSUE TITLE
gpinitsystem --help throws an error about missing value

### ISSUE THREAD

**Issue by andreasscherbaum** [greenplum-db/gpdb#1071]
```
[gpadmin@localhost ~]$ gpinitsystem --help
20160825:18:13:30:022761 gpinitsystem:localhost:gpadmin-[FATAL]:-Missing value for option help
```

**Comment by Chibin** [comment]
Confirmed that the reported issue happens.

Looking at the code, it looks like there are no options for ```--help``` ... we only have ```-?``` as the argument for calling help.

**Comment by andreasscherbaum** [comment]
Then it should throw an error about an unknown option, and not an unknown value for --help, right?

**Comment by Chibin** [comment]
Yes, the output message is misleading and needs to be clearer.

**Comment by skahler-pivotal** [comment]
Fixed in
https://github.com/greenplum-db/gpdb/pull/1077
