### ISSUE TITLE
View gp_bloat_expected_pages is not updated after run VACUUM FULL or execute redistribution for a heap table

### ISSUE THREAD

**Issue by soulfere** [greenplum-db/gpdb#10732]
### Greenplum version or build
5.0 6.3
### OS version and uname -a
CentOS 7
### Expected behavior
In order to handle the heap table bloat. I execute VACUUM FULL for a table and report success.
After that, I run the ANALYZE command to refresh the analyze information.
I think after this, the data of view gp_bloat_expected_pages is updated ,the btdrelpages and btdexppages will be updated by a reasonable value.
### Actual behavior
Data in gp_bloat_expected_pages is not update, both btdrelpages and btdexppages value of the table are exactly as before.
That make me think that the bloat of the heap table is not effected even running the VACUUM FULL or force redistribution for the heap table.

Is there anyting wrong in my steps of handle the table bloat? 
Or am I misunderstand the meaning of the gp_bloat_expected_pages view?
If not, this could be a bug.
![image](https://user-images.githubusercontent.com/2850312/91650356-29d29900-eab1-11ea-9237-ee88443eb45d.png)

**Comment by kmjs233** [comment]
any conclusion?
