### ISSUE TITLE
Which one is the official production release?

### ISSUE THREAD

**Issue by kwoot** [greenplum-db/gpdb#10736]
### Greenplum version or build
6.10

### OS version and uname -a
Ubuntu 18.04

### Expected behavior
One clear package and package location

### Actual behavior
So, there is a release file on github called greenplum-db-6.10.1-ubuntu18.04-amd64.deb that installs in /usr/local/.
And there is one on launchpad called greenplum-db-6_6.10.1-1_amd64.deb that installs in /opt.

### Step to reproduce the behavior

Which one is the official production release?

**Comment by kmacoskey** [comment]
Howdy @kwoot 

> Which one is the official production release?

They are both official, production releases. That is, Greenplum R&D is actively maintaining both. 

> One clear package and package location

There are historical reasons why the packages on launchpad default to `/opt` and everything else defaults to `/usr/local`. Changing these defaults is as disruptive to the package users as it is to R&D to have consensus on a default. Currently, we don't plan on making any changes until a Major version boundary (Greenplum 7).

Is there a particular issue this is creating for you? Every new release is available in both locations, so either can be used. Using both the DEB packages in Github and Launchpad would be an issue but I'm not sure why anyone might want to do that.

**Comment by kwoot** [comment]
Hi!

Thank you so much for replying!

I am evaluating GP for a client of mine.

I am trying to install gp from the github packages on a standard ubuntu 18.04 test system.
I am really stuck in installation:
I run "/usr/local/greenplum-db-6.10.1/bin/gpinitsystem  -a -c gpconfigs/gpinitsystem_config  -h hostfile_gpinitsystem"
and it always fails at: initdb: "en_US.utf8" is not a valid server encoding nam.
But the locale is present (locale -a) and I even installed it anyway.

I get no replies on my questions in slack.

And I can not subscribe to any of the mailing lists because there are spaces in the mailing list names on the gp.org website and I did not find it when i searched for them.

Please help.

**Comment by kmacoskey** [comment]
Following up on this. The original issue has been answered. The second issue mentioned was resolved in the Open Source Greenplum Slack: https://greenplum.slack.com/archives/C7BA61BEU/p1598877405003000
