### ISSUE TITLE
About priority of RESOURCE QUEUE

### ISSUE THREAD

**Issue by LJoNe** [greenplum-db/gpdb#1075]
When i execute a simple query such as 'select \* from t', I find that 'increment_command_count' will run a second time after 'PortalSetBackoffWeight' .Then BackoffBackendSharedEntry->statementId will be different from currentStatementId{gp_session_id, gp_command_count},so that  'BackoffBackendTick' will return before running to 'BackoffBackend'. In the end the priority of statement will not be valid. Is there somthing wrong?

**Comment by ivannovick** [comment]
@gaos1 any action item on this?

**Comment by gaos1** [comment]
@ivannovick at this moment we want to focus on design and implementation of percentage-based cpu schedule. after that we will spike potential improvement for priority based cpu schedule or we might deprecate priority based cpu schedule if percentage based works well for all scenarios.

**Comment by gaos1** [comment]
we have clear percentage based cpu allocation in resource group. please try it and let us know if you have any new requirement on it. Thanks.
