### ISSUE TITLE
Assert failure when init system

### ISSUE THREAD

**Issue by dreamedcheng** [greenplum-db/gpdb#10765]
### Greenplum version or build
6.7.1

### OS version and uname -a
centos 7

### Installation information ( pg_config )
./configure --with-perl --with-python --with-libxml --with-gssapi --enable-debug --enable-cassert  --prefix=/data/basedir_gpdb/

### Step to reproduce the behavior
make crate-demo-cluster

Program terminated with signal 11, Segmentation fault.
#0  0x0000000000f356b1 in gpos::CMemoryPoolTracker::DeleteImpl (ptr=0x9558ce8, eat=gpos::CMemoryPool::EatSingleton) at CMemoryPoolTracker.cpp:141
141		GPOS_RTL_ASSERT(eat == EatUnknown || *alloc_type == eat);
(gdb) bt
#0  0x0000000000f356b1 in gpos::CMemoryPoolTracker::DeleteImpl (ptr=0x9558ce8, eat=gpos::CMemoryPool::EatSingleton) at CMemoryPoolTracker.cpp:141
#1  0x0000000000f32a50 in gpos::CMemoryPoolManager::DeleteImpl (this=0x9558ce8, ptr=0x9558ce8, eat=gpos::CMemoryPool::EatSingleton) at CMemoryPoolManager.cpp:161
#2  0x0000000000f32188 in gpos::CMemoryPool::DeleteImpl (ptr=0x9558ce8, eat=gpos::CMemoryPool::EatSingleton) at CMemoryPool.cpp:43
#3  0x0000000000f34740 in gpos::delete_detail::CDeleter<gpos::CMemoryPoolManager>::Delete (object=0x9558ce8) at ../../../../../../src/backend/gporca/libgpos/include/gpos/memory/CMemoryPool.h:243
#4  0x0000000000f33c97 in GPOS_DELETE<gpos::CMemoryPoolManager> (object=0x9558ce8) at ../../../../../../src/backend/gporca/libgpos/include/gpos/memory/CMemoryPool.h:330
#5  0x0000000000f33041 in gpos::CMemoryPoolManager::Shutdown (this=0x9558ce8) at CMemoryPoolManager.cpp:286
#6  0x0000000000f4054c in gpos_terminate () at _api.cpp:295
#7  0x00000000012a60ef in CGPOptimizer::TerminateGPOPT () at CGPOptimizer.cpp:192
#8  0x00000000012a6219 in TerminateGPOPT () at CGPOptimizer.cpp:275
#9  0x0000000000e2483b in ShutdownPostgres (code=0, arg=0) at postinit.c:1351
#10 0x0000000000c687cf in shmem_exit (code=0) at ipc.c:257
#11 0x0000000000c686c3 in proc_exit_prepare (code=0) at ipc.c:214
#12 0x0000000000c685c1 in proc_exit (code=0) at ipc.c:104
#13 0x00000000008db593 in BootstrapModeMain () at bootstrap.c:516
#14 0x00000000008db45c in AuxiliaryProcessMain (argc=4, argv=0x9520b88) at bootstrap.c:427
#15 0x0000000000b00697 in main (argc=5, argv=0x9520b80) at main.c:237

**Comment by chrishajas** [comment]
This looks identical to the issue fixed in https://github.com/greenplum-db/gpdb/commit/086a41c21eed219ed91ba3fc00ba3039b12600e4. Can you check whether you still see this issue in v6.10.0 or later?

**Comment by dreamedcheng** [comment]
> This looks identical to the issue fixed in [086a41c](https://github.com/greenplum-db/gpdb/commit/086a41c21eed219ed91ba3fc00ba3039b12600e4). Can you check whether you still see this issue in v6.10.0 or later?

Thanks. I'll try it.
