### ISSUE TITLE
confusing cloumn  of view gp_toolkit.gp_stats_missing

### ISSUE THREAD

**Issue by LittleWuCoding** [greenplum-db/gpdb#10777]
### Greenplum version or build
greenplum 6.4

View gp_toolkit.gp_stats_missing is likes below:
 smischema |              smitable               | smisize | smicols | smirecs 
-----------+-------------------------------------+---------+---------+---------
 public    | test1                       | f       |       4 |       0
 public    | test2                       | f       |       8 |       8
 public    | test3                       | f       |       5 |       0

the last column 'smirecs' is very confusing.
In manual:

![xxx](https://user-images.githubusercontent.com/31984989/92387317-dfec5180-f147-11ea-98dc-a6b4502fc158.png)

smirecs is for 'Number of rows in the table'
But when I review the source SQL of  gp_toolkit.gp_stats_missing in GP/src/backend/catalog/gp_toolkit.sql
,I found that it stands for  number of rows of table smitable in pg_statistics,which means how many cloumns who 's statistic got accounted.
So.if smirecs really stand for 'Number of rows in the table', it should be reltuples from table pg_class, which maybe not accurate，instead of count(*) from  pg_statistics
Or，the meaning indicated in manual is out of date or wrong.
 
Please tell me the real meaning of it~

**Comment by lij55** [comment]
hi @dyozie , 

this is a doc mis-match issue.
The value of `smirecs` is calculated by `COALESCE(stacnt, 0) AS smirecs` and `stacnt` is from:
```sql
SELECT starelid, count(*) AS stacnt
            FROM pg_catalog.pg_statistic
            GROUP BY starelid
```
It means the total columns of the table that has statistic.  code is here: https://github.com/greenplum-db/gpdb/blob/ba601fc54c069c8b555c6063cc8635a40bd0ec91/src/backend/catalog/gp_toolkit.sql#L856

Please consider this according to the backlog. Thanks!
