### ISSUE TITLE
Init standy master fail

### ISSUE THREAD

**Issue by zeromax007** [greenplum-db/gpdb#1079]
git clone Aug 26 repository.

> 
20160828:01:39:48:104933 gpinitstandby:greenplum-001:gpadmin-[INFO]:-Validating environment and parameters for standby initialization...
20160828:01:39:48:104933 gpinitstandby:greenplum-001:gpadmin-[INFO]:-Checking for filespace directory /data/master/gpseg-1 on greenplum-006
20160828:01:39:48:104933 gpinitstandby:greenplum-001:gpadmin-[INFO]:------------------------------------------------------
20160828:01:39:48:104933 gpinitstandby:greenplum-001:gpadmin-[INFO]:-Greenplum standby master initialization parameters
20160828:01:39:48:104933 gpinitstandby:greenplum-001:gpadmin-[INFO]:------------------------------------------------------
20160828:01:39:48:104933 gpinitstandby:greenplum-001:gpadmin-[INFO]:-Greenplum master hostname               = greenplum-001
20160828:01:39:48:104933 gpinitstandby:greenplum-001:gpadmin-[INFO]:-Greenplum master data directory         = /data/master/gpseg-1
20160828:01:39:48:104933 gpinitstandby:greenplum-001:gpadmin-[INFO]:-Greenplum master port                   = 5432
20160828:01:39:48:104933 gpinitstandby:greenplum-001:gpadmin-[INFO]:-Greenplum standby master hostname       = greenplum-006
20160828:01:39:48:104933 gpinitstandby:greenplum-001:gpadmin-[INFO]:-Greenplum standby master port           = 5432
20160828:01:39:48:104933 gpinitstandby:greenplum-001:gpadmin-[INFO]:-Greenplum standby master data directory = /data/master/gpseg-1
20160828:01:39:48:104933 gpinitstandby:greenplum-001:gpadmin-[INFO]:-Greenplum update system catalog         = On
20160828:01:39:48:104933 gpinitstandby:greenplum-001:gpadmin-[INFO]:------------------------------------------------------
20160828:01:39:48:104933 gpinitstandby:greenplum-001:gpadmin-[INFO]:- Filespace locations
20160828:01:39:48:104933 gpinitstandby:greenplum-001:gpadmin-[INFO]:------------------------------------------------------
20160828:01:39:48:104933 gpinitstandby:greenplum-001:gpadmin-[INFO]:-pg_system -> /data/master/gpseg-1
Do you want to continue with standby master initialization? Yy|Nn (default=N):
> y
20160828:01:39:50:104933 gpinitstandby:greenplum-001:gpadmin-[INFO]:-Syncing Greenplum Database extensions to standby
20160828:01:39:50:104933 gpinitstandby:greenplum-001:gpadmin-[INFO]:-The packages on greenplum-006 are consistent.
20160828:01:39:50:104933 gpinitstandby:greenplum-001:gpadmin-[INFO]:-Adding standby master to catalog...
20160828:01:39:50:104933 gpinitstandby:greenplum-001:gpadmin-[ERROR]:-Failed to add standby to master catalog.
20160828:01:39:50:104933 gpinitstandby:greenplum-001:gpadmin-[ERROR]:-Failed to create standby
20160828:01:39:50:104933 gpinitstandby:greenplum-001:gpadmin-[WARNING]:-Trying to rollback changes that have been made...
20160828:01:39:50:104933 gpinitstandby:greenplum-001:gpadmin-[INFO]:-Rolling back catalog change...
20160828:01:39:50:104933 gpinitstandby:greenplum-001:gpadmin-[INFO]:-Removing standby master from catalog...
20160828:01:39:50:104933 gpinitstandby:greenplum-001:gpadmin-[ERROR]:-Failed to remove standby from master catalog.
20160828:01:39:50:104933 gpinitstandby:greenplum-001:gpadmin-[ERROR]:-Error initializing standby master: error 'ERROR:  system contains 0 filespaces but filespace map contains only 1 filespaces (segadmin.c:228)
' in 'select gp_add_master_standby('greenplum-006', 'greenplum-006', '{{"pg_system","/data/master/gpseg-1"}}')'

**Comment by volkovandr** [comment]
I'm experiencing the same problems.

**Comment by deepesh1081** [comment]
could you rerun gpinitstandby with -D option and provide the following logs:

1. db logs from /data/master/gpseg-1/pg_log from greenplum-006 and greenplum-001 
2. cat /etc/hosts from both master and standby 
3. ~gpadmin/gpAdminLogs from master and standby
4. gpstate -e 
5. psql -c "SELECT * from pg_filespace;" template1
6. psql -c "SELECT * from pg_filespace_entry ;" template1

**Comment by asimrp** [comment]
@zeromax007 @volkovandr, please try again.  In case you encounter failures, feel free to create a new issue.  Thank you for the report.
