### ISSUE TITLE
Upgrade cluster with index marked invalid

### ISSUE THREAD

**Issue by dgkimura** [greenplum-db/gpdb#10805]
### Greenplum version or build
GPDB master

### Step to reproduce the behavior

Create a table with invalid marked index...

```sql
CREATE TABLE t (a int);
CREATE INDEX i on t(a);

SET allow_system_table_mods=on;
UPDATE pg_index SET indisvalid=false WHERE indrelid='t'::regclass;
RESET allow_system_table_mods;
```

Then run upgrade script..

```
bash test_gpdb.sh -b ~/gpdb/greenplum-db-devel/bin/ -o ~/gpdb/gpAux/gpdemo/datadirs
```

And it fails during upgrade...
```
Performing Upgrade
------------------
Analyzing all rows in the new cluster                       ok
...
Freezing all rows in new master after pg_restore            ok
Copying user relation files
No match found in new cluster for old relation with OID 24583 in database "test": "public.i" which is an index on "public.t"

Failed to match up old and new tables in database "test"
```

As Heikki noted https://github.com/greenplum-db/gpdb/pull/10788#discussion_r485355489, this is a valid state.  And indeed, Postgres handles upgrading these objects just fine, however Greenplum has issue.

**Comment by jchampio** [comment]
@bhuvnesh2703 Is this related to [this conversation](https://github.com/greenplum-db/gpdb/pull/9843#discussion_r401928150)?

**Comment by dpandhi-git** [comment]
Gpupgrade has a consistency check for Invalid indexes, that can be run before starting upgrade. To avoid above error. Details of check

Invalid indexes
The source cluster contains invalid indexes. This can occur with the CREATE INDEX CONCURRENTLY statement, which is not supported in Greenplum.

Resolution: Reindex or drop the indexes specified in invalid_indexes.txt.
