### ISSUE TITLE
tpcds.sh  error  failed to acquire resources on one or more segments counld not connect  to server 

### ISSUE THREAD

**Issue by wsh-sun** [greenplum-db/gpdb#10811]
### Greenplum version or build
9.4.24
### OS version and uname -a
centos 7.3.1611(core)

### Actual behavior
when i bash tpcds.sh to test the performance of gp，but always throw a error  on master node ‘failed to acquire resources on one or more segments counld not connect  to server ： connection timed out’，but！！！the server is health and not switch。（run different sql throw the same error）
### segment log
could not unlink file xxxx （but always throw the error ，even if not run tpcds）

**Comment by asimrp** [comment]
@wsh-sun Please provide detailed snippets from master as well as segment logs for us to be able to help solve your problem.

**Comment by kainwen** [comment]
Long time no response and this is not a gpdb's issue just other's tpcds tool' issue.
