### ISSUE TITLE
PANIC","XX000","Register file to a non-active workfile_set/per-query summary is illegal (workfi le_mgr.c:239

### ISSUE THREAD

**Issue by liuzhliang** [greenplum-db/gpdb#10855]
greenplum 6.11.1

master log 
  "ERROR","58M01","Error on receive from seg34 172.17.5.61:6004 pid=10700: server closed the connection unexp
ectedly
        This probably means the server terminated abnormally
        before or while processing the request.",,,,,"SQL statement ""
segment log 
PANIC","XX000","Register file to a non-active workfile_set/per-query summary is illegal (workfi
le_mgr.c:239

**Comment by JunfengYang** [comment]
Hi, thanks for the report! Can you provide the core dump? Or the reproduce steps for the issue?
You can find stack trace from logs, it also helps.

**Comment by liuzhliang** [comment]
> Hi, thanks for the report! Can you provide the core dump? Or the reproduce steps for the issue?
> You can find stack trace from logs, it also helps.

1    0xbe9d7c postgres errstart + 0x26c
2    0xc5e137 postgres RegisterFileWithSet + 0x147
3    0xa552d8 postgres BufFileCreateTempInSet + 0xa8
4    0x8de4ff postgres ExecHashJoin + 0xc3f
5    0x8bc7f8 postgres ExecProcNode + 0x318
6    0x8eae00 postgres ExecSort + 0x1e0
7    0x8bc7d8 postgres ExecProcNode + 0x2f8
8    0x8e152b postgres ExecMaterial + 0xcb
9    0x8bc7e8 postgres ExecProcNode + 0x308
10   0x8e3170 postgres ExecMergeJoin + 0x8c0
11   0x8bc808 postgres ExecProcNode + 0x328
12   0x8e78c1 postgres ExecNestLoop + 0x131
13   0x8bc818 postgres ExecProcNode + 0x338
14   0x8ddd79 postgres ExecHashJoin + 0x4b9
15   0x8bc7f8 postgres ExecProcNode + 0x318
16   0x8e78c1 postgres ExecNestLoop + 0x131
17   0x8bc818 postgres ExecProcNode + 0x338
18   0x8ddd79 postgres ExecHashJoin + 0x4b9
19   0x8bc7f8 postgres ExecProcNode + 0x318
20   0x8fb7c0 postgres ExecMotion + 0x70
21   0x8bc758 postgres ExecProcNode + 0x278
22   0x8b3b79 postgres <symbol not found> + 0x8b3b79
23   0x8b48a4 postgres standard_ExecutorRun + 0x384
24   0xa88571 postgres <symbol not found> + 0xa88571
25   0xa88a73 postgres <symbol not found> + 0xa88a73
26   0xa8a1c7 postgres PortalRun + 0x207
27   0xa8271e postgres <symbol not found> + 0xa8271e
28   0xa87258 postgres PostgresMain + 0x1fa8
29   0x6b9e85 postgres <symbol not found> + 0x6b9e85
30   0xa0cf52 postgres PostmasterMain + 0x10b2

**Comment by liuzhliang** [comment]
1    0xbe9d7c postgres errstart (elog.c:557)
2    0xc5e137 postgres RegisterFileWithSet (workfile_mgr.c:238)
3    0xa552d8 postgres BufFileCreateTempInSet (buffile.c:213)
4    0x8de4ff postgres ExecHashJoin (nodeHashjoin.c:1114)
5    0x8bc7f8 postgres ExecProcNode (execProcnode.c:1078)
6    0x8eae00 postgres ExecSort (tuptable.h:159)
7    0x8bc7d8 postgres ExecProcNode (execProcnode.c:1089)
8    0x8e152b postgres ExecMaterial (tuptable.h:159)
9    0x8bc7e8 postgres ExecProcNode (execProcnode.c:1085)
10   0x8e3170 postgres ExecMergeJoin (nodeMergejoin.c:678)
11   0x8bc808 postgres ExecProcNode (execProcnode.c:1074)
12   0x8e78c1 postgres ExecNestLoop (tuptable.h:159)
13   0x8bc818 postgres ExecProcNode (execProcnode.c:1070)
14   0x8ddd79 postgres ExecHashJoin (tuptable.h:159)
15   0x8bc7f8 postgres ExecProcNode (execProcnode.c:1078)
16   0x8e78c1 postgres ExecNestLoop (tuptable.h:159)
17   0x8bc818 postgres ExecProcNode (execProcnode.c:1070)
18   0x8ddd79 postgres ExecHashJoin (tuptable.h:159)
19   0x8bc7f8 postgres ExecProcNode (execProcnode.c:1078)
20   0x8fb7c0 postgres ExecMotion (tuptable.h:159)
21   0x8bc758 postgres ExecProcNode (execProcnode.c:1121)
22   0x8b3b79 postgres <symbol not found> (tuptable.h:159)
23   0x8b48a4 postgres standard_ExecutorRun (execMain.c:2962)
24   0xa88571 postgres <symbol not found> (pquery.c:290)
25   0xa88a73 postgres <symbol not found> (pquery.c:1487)
26   0xa8a1c7 postgres PortalRun (pquery.c:1022)
27   0xa8271e postgres <symbol not found> (postgres.c:1378)
28   0xa87258 postgres PostgresMain (postgres.c:5392)
29   0x6b9e85 postgres <symbol not found> (postmaster.c:0)
30   0xa0cf52 postgres PostmasterMain (postmaster.c:1523)

**Comment by JunfengYang** [comment]
Is it possible to upload the core dump?
What's the query you are running?

**Comment by liuzhliang** [comment]
> Is it possible to upload the core dump?
> What's the query you are running?

core文件没有生成  
系统日志里 有
Sep 21 05:57:24 sdw2-1 abrtd: Directory 'ccpp-2020-09-21-05:57:10-18813' creation detected
Sep 21 05:57:24 sdw2-1 abrtd: Package 'greenplum-db-6' isn't signed with proper key
Sep 21 05:57:24 sdw2-1 abrtd: 'post-create' on '/var/spool/abrt/ccpp-2020-09-21-05:57:10-18813' exited with 1
Sep 21 05:57:24 sdw2-1 abrtd: Deleting problem directory '/var/spool/abrt/ccpp-2020-09-21-05:57:10-18813'
Sep 21 05:59:32 sdw2-1 abrt[24155]: Saved core dump of pid 22192 (/usr/local/greenplum-db-6.11.1/bin/postgres) to /var/spool/abrt/cc
pp-2020-09-21-05:59:26-22192 (756109312 bytes)
Sep 21 05:59:32 sdw2-1 abrtd: Directory 'ccpp-2020-09-21-05:59:26-22192' creation detected
Sep 21 05:59:32 sdw2-1 abrtd: Package 'greenplum-db-6' isn't signed with proper key
Sep 21 05:59:32 sdw2-1 abrtd: 'post-create' on '/var/spool/abrt/ccpp-2020-09-21-05:59:26-22192' exited with 1
Sep 21 05:59:32 sdw2-1 abrtd: Deleting problem directory '/var/spool/abrt/ccpp-2020-09-21-05:59:26-22192'
但是我到该目录一下 并没有找到相应的core文件

**Comment by JunfengYang** [comment]
Fix the issue with commit 5b147fbe05efb2275f54fe0cfd63a239389f83be on master and c507eed7acaf140f5a8911d19e2b19944e62376a on 6X branch.
So close it.
