### ISSUE TITLE
Should we still want the cost figures displayed in Query plan of regression test?

### ISSUE THREAD

**Issue by bzhaoopenstack** [greenplum-db/gpdb#10867]
### Greenplum version or build
Master branch
ARCH:  aarch64

### OS version and uname -a
ubuntu 1804

Hi, I'm the "zuul regression ARM test" maintainer on Openlab. 
We found there are several days that the master build had failed with the same issue.
Please see:
https://logs.openlabtesting.org/logs/periodic-12/github.com/greenplum-db/gpdb/master/gpdb-installcheck-world-tests-on-arm64/c88a6d8/test_results/regress_regression.diffs

Looks the difference is the cost figures. As for my understanding, the `cost` figure is about the `cost estimate` means that pgsql expects to spend any calculation unit of `the value` to find these records/values. So we are not sure whether community want to test some specific `cost` figures in regression tests? Can we keep "cost off" while displaying the cost plans?

Thank you very much.

**Comment by bzhaoopenstack** [comment]
@hlinnaka Hi, Heikki, could you please take a look about this? Thanks.

**Comment by hlinnaka** [comment]
Yeah. And usually the cost differences are masked out by gpdiff, so that they don't cause a test failure. This looks like a similar case to that fixed in 0a94dcfbb9b3b9dd08c239047cad53ca60a25939.

**Comment by hlinnaka** [comment]
`costs off` is indeed another way of fixing that. Most GPDB tests don't use it because most tests were written before `costs off` option was invented.

**Comment by bzhaoopenstack** [comment]
Oh, I see there is a very big commit. And can not repro this issue on master branch anymore.

**Comment by bzhaoopenstack** [comment]
https://logs.openlabtesting.org/logs/a8/a8eb84a23a48be871db517b9bd7b503664955ee2/periodic-12/gpdb-installcheck-world-tests-on-arm64/f0b03d5/test_results/

**Comment by ashwinstar** [comment]
I am closing this one due to non-activity and not sure about current state. Please feel free to open fresh issue with latest status on this aspect and we can continue the conversation with fresh perspective.
