### ISSUE TITLE
Replace palloc0() with palloc() in buildGpQueryString()

### ISSUE THREAD

**Issue by fangzheng** [greenplum-db/gpdb#10874]
### Greenplum version or build
master, 6X_STABLE

The `buildGpQueryString()` function in cdbdisp_query.c calls `palloc0()` to allocate a memory buffer for holding the serialized query string to be dispatched to QEs 

https://github.com/greenplum-db/gpdb/blob/master/src/backend/cdb/dispatcher/cdbdisp_query.c#L913

Since this buffer would then be filled in full by the serialized query string, it would be more efficient to allocate the buffer with `palloc()` instead of `palloc0()`. This way, we can avoid the unnecessary cost of setting all bytes in the buffer to zero.

**Comment by xiong-gang** [comment]
yes, nice catch

**Comment by gfphoenix78** [comment]
@fangzheng Thank you for your effort. I have opened a PR to backport the patch for 6X(https://github.com/greenplum-db/gpdb/pull/10996).
