### ISSUE TITLE
Do not dispatch original query string to QE when log_statement is set to LOGSTMT_NONE

### ISSUE THREAD

**Issue by fangzheng** [greenplum-db/gpdb#10887]
### Greenplum version or build
master, 6X_STABLE

When QD calls `buildGpQueryString()` to serialize a query for dispatch and `quertree` or `plantree` is set, the original query string is not important for QEs, and QD would include a truncated version of it in the serialized query. QEs only use the query string to print log messages. (see https://github.com/greenplum-db/gpdb/blob/master/src/backend/cdb/dispatcher/cdbdisp_query.c#L876)

In case `log_statement` GUC variable is set to `LOGSTMT_NONE`, QEs would not use the query string at all. Therefore, `buildGpQueryString()` can further skip truncating it, and just include an empty query string in the dispatched query.

**Comment by xiong-gang** [comment]
nice catch, thanks.

**Comment by lij55** [comment]
closing this issue as this behavior is needed for debug purpose for some cases.
