### ISSUE TITLE
Improve efficiency of SerializeResGroupInfo()

### ISSUE THREAD

**Issue by fangzheng** [greenplum-db/gpdb#10886]
### Greenplum version or build
master, 6X_STABLE

When QD calls `buildGpQueryString()` to serialize a query string for dispatch, it executes the following code to serialize resource group information (see https://github.com/greenplum-db/gpdb/blob/master/src/backend/cdb/dispatcher/cdbdisp_query.c#L890):

````
	initStringInfo(&resgroupInfo);
	if (IsResGroupActivated())
		SerializeResGroupInfo(&resgroupInfo);
````

The code above is inefficient because: 
1) `initStringInfo()` allocates 1024 Bytes of memory even if resource group is not activated.
2) In case resource group is indeed activated, the resulting serialized data may be much smaller than 1024 Bytes.
3) The allocated memory for StringInfo is not `pfree()`-ed after use.

We may change the code so that it 1) only allocates memory for `StringInfo` when resource group is activated, 2) allocates the exact amount of memory for the serialized data, and 3) recycles the memory for `StringInfo` after use.

**Comment by xiong-gang** [comment]
nice catch, thanks.

**Comment by kainwen** [comment]
One pr is merged. The other needs more work. It should not be an issue here, the PR is a good record.
