### ISSUE TITLE
Hasura support or compatibility

### ISSUE THREAD

**Issue by rrjanbiah** [greenplum-db/gpdb#10909]
FWIW, already posted to Hasura https://github.com/hasura/graphql-engine/issues/4307 and https://github.com/MaterializeInc/materialize/issues/3496

Not sure who has to implement. But, seems to have great potential as Hasura on plain PostgreSQL is not suitable for all cases.

**Comment by adam8157** [comment]
It's probably on the other side. Anyway, it's interesting, Hasura looks great, PM will consider.

Closing this.
