### ISSUE TITLE
bgworker sweeper crash for Floating point Exception

### ISSUE THREAD

**Issue by wangcarven** [greenplum-db/gpdb#10902]
### Dont know what caused , I got crash info from linux message file 

traps: postgres[170678] trap divide error ip:81a36f sp:7ffcd1426870 error:0 in postgres[400000+9e3000]

traps: postgres[170691] trap divide error ip:81a36f sp:7ffeab6895f0 error:0 in postgres[400000+9e3000]

traps: postgres[170648] trap divide error ip:81a36f sp:7fffc09c77f0 error:0 in postgres[400000+9e3000]

Track the source is backend/postmaster/backoff.c:885 ,  but I didn't found any reason may  obviously caused the crash.

but surely there is some floating var in the codes, so maybe there is some bug.

**Comment by hlinnaka** [comment]
Which version exactly are you running? A few issues like this have been fixed in the past, see https://github.com/greenplum-db/gpdb/pull/9298 and https://github.com/greenplum-db/gpdb/issues/10381.

**Comment by wangcarven** [comment]
My Version is 6.0.0 and #9298 seems something like but not the same.  I got Floating point Exception instead of internal error, I got sinal 8 in database log file instead of Internal Error report in log file.  the position of code file is line 885 but #9298 not. maybe there is some bugs in deep.

**Comment by hlinnaka** [comment]
Ok. Definitely try upgrading to the latest 6.X version first. If the problem doesn't go away with the upgrade, then we need to dig deeper.

**Comment by ggbq** [comment]
@wangcarven  

Macro code **Assert()** does nothing if your GP compiled **without** `--enable-cassert`.

So that, backoff.c:885  `activeWeight -= (se->weight / gl->numFollowersActive)`, #9298 has already fixed it.
