### ISSUE TITLE
[BUG] server coredump

### ISSUE THREAD

**Issue by funnyxj** [greenplum-db/gpdb#1091]
When I run following sql, then kill -9 'psql' client, the server will coredump。

```
$psql postgres  -p35432

  begin;
  CREATE TABLE test1(id int);
  INSERT INTO test1 values(1);
  select * from test1 order by id;
```

```
$ps -ef|grep psql
65440    125569  65481  0 14:46 pts/16   00:00:00 psql postgres -p35432
```

```
kill -9 125569
```

 then I use kill -9 to kill psql，server will crash!

**Comment by asimrp** [comment]
@funnyxj can you please share the logs and stack trace from the core dump?

**Comment by funnyxj** [comment]
it happen on master， I had found a bug on GP.  I had fix this bug on my local code. The main problem is ShutdownPostgres must do before pgstat_beshutdown_hook. So PG add before_shmem_exit hook.

**Comment by gaos1** [comment]
@funnyxj could you please create a pull request for your fix? Thanks.

**Comment by gaos1** [comment]
@funnyxj i cannot reproduce it with the latest master code. if you still see it, please help to comment. thanks.
