### ISSUE TITLE
Master error after vacuum

### ISSUE THREAD

**Issue by ra3orblade** [greenplum-db/gpdb#10933]
### Greenplum version or build

PostgreSQL 9.4.24 (Greenplum Database 6.7.1+dev.80.g6fbca67 build dev) on x86_64-unknown-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36), 64-bit compiled on May 30 2020 13:59:40

### OS version and uname -a

Centos 3.10.0-693.17.1.el7.x86_64

### Step to reproduce the behavior

During pg_class table full vacuum it seems like it intersected with another process and master crashed. After crash our engineer set relfrozenxid to Zero. Now we are getting this stacktrace while trying to launch master:

`2020-10-01 03:31:05.415725 MSK,"report","d2d",p297197,th324307072,"10.58.197.12","44754",2020-10-01 03:30:55 MSK,0,con217,,seg-1,,,,sx1,"FATAL","XX000","cache lookup failed for relation 1259 (relcache.c:3612)",,,,,,,0,,"relcache.c",3612,
"Stack trace:
1   0xbd538c postgres errstart (elog.c:557)
2   0xbd7e63 postgres elog_finish (elog.c:1729)
3   0xbb5f59 postgres RelationCacheInitializePhase3 (relcache.c:3640)
4   0xbea52d postgres InitPostgres (postinit.c:1101)
5   0xa765b2 postgres PostgresMain (postgres.c:4840)
6   0x6be130 postgres <symbol not found> (postmaster.c:4462)
7   0xa00659 postgres PostmasterMain (postmaster.c:1513)
8   0x6c2edb postgres main (discriminator 1)
9   0x7f6f10cca3d5 libc.so.6 __libc_start_main + 0xf5
10  0x6cef3f postgres <symbol not found> + 0x6cef3f`

**Comment by asimrp** [comment]
@ra3orblade more details about the crash (before any modifications to relfrozenxid) will be needed to analyze your problem.  Can you share stack trace from master / segment logs that was emitted during the crash?  Did the crash result in a core dump?  Do you know anything about this other process that was concurrently running with the `vacuum full` process?

**Comment by ra3orblade** [comment]
We have found out later that day that this issue was fixed in:

https://gpdb.docs.pivotal.io/6-11/relnotes/gpdb-611-release-notes.html
30877 - VACUUM
In some cases, running VACUUM returns ERROR: found xmin <xid> from before relfrozenxid <frozen_xid>. The error was caused when a previously run VACUUM FULL was interrupted and aborted on a query executor (QE) and corrupted catalog frozen XID information. This issue is resolved.

**Comment by asimrp** [comment]
Thank you for the update.
