### ISSUE TITLE
CreateDistributedSnapshot passes invalid globalXminDistributedSnapshots to QE

### ISSUE THREAD

**Issue by flashk1021** [greenplum-db/gpdb#10930]
### Greenplum version or build
GP  7.0
### OS version and uname -a
Darwin US-185278-MP.local 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64
### Expected behavior
isolation2/uao_crash_compaction_column

-- This VACUUM removes the previous drop pending state for segment file 1 which
-- will make it available for future inserts.
1:VACUUM crash_before_cleanup_phase;
VACUUM
1:SELECT segno,column_num,physical_segno,tupcount,modcount,state FROM gp_toolkit.__gp_aocsseg('crash_before_cleanup_phase');
 segno | column_num | physical_segno | tupcount | modcount | state 
-------+------------+----------------+----------+----------+-------
 1     | 0          | 1              | 0        | 2        | 1     
 1     | 0          | 1              | 0        | 2        | 1     
 1     | 0          | 1              | 0        | 3        | 1     
 1     | 1          | 129            | 0        | 2        | 1     
 1     | 1          | 129            | 0        | 2        | 1     
 1     | 1          | 129            | 0        | 3        | 1     
 1     | 2          | 257            | 0        | 2        | 1     
 1     | 2          | 257            | 0        | 2        | 1     
 1     | 2          | 257            | 0        | 3        | 1     
 2     | 0          | 2              | 1        | 2        | 1     
 2     | 0          | 2              | 3        | 1        | 1     
 2     | 0          | 2              | 5        | 1        | 1     
 2     | 1          | 130            | 1        | 2        | 1     
 2     | 1          | 130            | 3        | 1        | 1     
 2     | 1          | 130            | 5        | 1        | 1     
 2     | 2          | 258            | 1        | 2        | 1     
 2     | 2          | 258            | 3        | 1        | 1     
 2     | 2          | 258            | 5        | 1        | 1     
(18 rows)
### Actual behavior
after VACUUM crash_before_cleanup_phase, the segment 1's state are still 2
### Step to reproduce the behavior

I think the root cause was introduced by the commit 72828c277e3c09730d1d9897099412b708fcd76d which swap the timing of globalXminDistributedSnapshots assignment inside function of CreateDistributedSnapshot. Before the change, when gxid is 0, the logic will skip the current entry and will not assign the invalid value of gxact_candidate->xminDistributedSnapshot to  globalXminDistributedSnapshots, but now the assignment happens first without checking if the entry is valid or not. The value of globalXminDistributedSnapshots will carry away to ds->xminAllDistributedSnapshots and eventually to QE, causing visible_to_all to false in the AppendOnlyRecycleDeadSegments and fail to drop the AOSEG_STATE_AWAITING_DROP segment marked during the first VACUUM command. This is the content of gxact_candidate, when bad value of xminDistributedSnapshot is assigned to globalXminDistributedSnapshots, but since gxid is 0, we should skip this entry. 

(TMGXACT) $8 = {
  gid = ""
  gxid = 0
  state = DTX_STATE_NONE
  sessionId = 19
  explicitBeginRemembered = '\0' 0 '\0'
  isOnePhaseCommit = '\0' 0 '\0'
  xminDistributedSnapshot = 41
  badPrepareGangs = '\0' 0 '\0'
  writerGangLost = '\0' 0 '\0'
  twophaseSegmentsMap = 0x0000000000000000
  twophaseSegments = 0x0000000000000000
}

**Comment by hlinnaka** [comment]
@xiong-gang, can you take a look at this, please?

**Comment by flashk1021** [comment]
> @xiong-gang, can you take a look at this, please?

@hlinnaka I rollbacked the changes in CreateDistributedSnapshot introduced by 72828c2, then it failed the isolation2/vacuum_self_function_row with the following result. Basically, the first vacuum ao dropped the awaiting_to_drop segment 1 on QE, because  visible_to_all inside AppendOnlyRecycleDeadSegments didn't catch the xid locked by myfunc(). I confused by the changes in CreateDistributedSnapshot, and is gxact_candidate->xminDistributedSnapshot valid even if gxact_candidate->gxid is InvalidDistributedTransactionId? But apparently before the commit above, it is invalid when gxact_candidate->gxid is InvalidDistributedTransactionId but it failed with your isolation2 new testcase for 5778f31124d5737e18d76f8d06f07f96c31c8be7. 

2: VACUUM ao;
VACUUM
2: SELECT segno, tupcount, state FROM gp_ao_or_aocs_seg('ao');
 segno | tupcount | state 
-------+----------+-------
 1     | 0        | 1     <-- expecting 2
 2     | 20       | 1     
 1     | 0        | 1     <-- expecting 2
 2     | 11       | 1     
 1     | 0        | 1     <-- expecting 2
 2     | 19       | 1     
(6 rows)

**Comment by flashk1021** [comment]
Closed this issue because not able to create it again.
