### ISSUE TITLE
Is the parameter passing logic from QD to QE in need of refactor?

### ISSUE THREAD

**Issue by asimrp** [greenplum-db/gpdb#10931]
### Greenplum version or build
6X (not master).

The PR #10773 fixed a crash in parameter passing logic from QD to QE.  The discussion on that PR indicates more investigation in that area of code.  Let's track it in this issue.  If a more experienced set of eyes determine the code to be alright, this issue can be closed.

**Comment by ashwinstar** [comment]
Given the issue doesn't exist on master branch. No plans to do any major refactoring for 6X_STABLE (bug fixes only). Hence, closing this issue.
