### ISSUE TITLE
ERROR:  relation with OID xxxxxx does not exist

### ISSUE THREAD

**Issue by eurekaka** [greenplum-db/gpdb#1094]
Reproduction steps:
```
create table foo(id int);
-- manually kill -9 a segment QE process to simulate SIGSEGV, and force postmaster reset on that segment
select * from foo; -- expected to fail because one QE of the using gang has exited
select * from foo; -- expected to succeed but it fails with error message like title above
```

Here is the output on my machine:
> test=# create table foo(id int);
NOTICE:  Table doesn't have 'DISTRIBUTED BY' clause -- Using column named 'id' as the Greenplum Database data distribution key for this table.
HINT:  The 'DISTRIBUTED BY' clause determines the distribution of data. Make sure column(s) chosen are the optimal data distribution key to minimize skew.
CREATE TABLE
test=# select * from foo;
ERROR:  Error on receive from seg0 slice1 10.153.101.105:25432 pid=25281: server closed the connection unexpectedly (cdbdisp.c:220)
DETAIL:
       	This probably means the server terminated abnormally
       	before or while processing the request.
test=# select * from foo;
ERROR:  relation with OID 692388 does not exist  (seg0 slice1 10.153.101.105:25432 pid=25338) (cdbdisp.c:220)
test=# select * from foo;
ERROR:  relation with OID 692388 does not exist  (seg0 slice1 10.153.101.105:25432 pid=25338) (cdbdisp.c:220)

I did a brief debug and found that after postmaster reset on segment, for the second SELECT query, a new QE was started, this QE would call ExecCheckRTEPerms => pg_class_aclmask to check the permission of the table by querying pg_class, and then QE would do an index scan for pg_class, and found the physical tuple for the created table foo in pg_class, however, it failed in the check of HeapTupleSatisfiesNow, so QE believed there was no entry for the table and reported error "relation with OID xxx does not exist". I tried the reproduction steps several times and found that in function HeapTupleSatisfiesNow, the code path varied from time to time, so I wondered if the tuple data of that entry in pg_class was corrupted.

Note that, if we restart a new session and do "select * from foo", it succeeds.

@ashwinstar , @asimrp , since it seems like a storage related issue, could you please spare a moment to take a look at it? thanks.

**Comment by ashwinstar** [comment]
@eurekaka Sure taking a look...

**Comment by ashwinstar** [comment]
Its basically failing in this check 
TransactionIdPrecedes(ShmemVariableCache->latestCompletedXid, xid) in TransactionIdIsInProgress. This is new code from merge, yet to debug in full but high-level  ShmemVariableCache->latestCompletedXid is not setting to really latestCompletedXid after restart / recovery. And once the cache gets populated with negative entry all subsequent calls fail as well. So, its not pg_class tuple corruption but incorrect value of variable latestCompletedXid driving incorrect visibility after postmaster reset on segment.

We removed the easy debugging info logging around tuple visibility to trace down such issues. It would have been matter of secs to know the issue took almost half-day. Will continue to look further and fix the same.

**Comment by ashwinstar** [comment]
Cause for the issue is ShmemVariableCache->latestCompletedXid was set as part of postgres merge to 8.3 after pass1 which only replays xlog records for persistent tables. Pass3 is where all the xlog records are replayed. So, latestCompletedXid needs to be set after all xlog records have been replayed to correctly point to real latestCompletedXid else it points to stale value from checkpoint and all in-flight transactions completed as part of recovery are treated as still in-progress after recovery, yielding incorrect visibility.

**Comment by eurekaka** [comment]
Cool, close this issue since we have a fix.
