### ISSUE TITLE
Misleading error message when distribution key column is concurrently updated

### ISSUE THREAD

**Issue by asimrp** [greenplum-db/gpdb#10942]
### Greenplum version or build
master (7) after PR #10919 is merged
### Expected behavior
When two DML statements that update distribution key columns run concurrently, e.g.
```SQL
update foo set c1 = c1 + 1 where c1 = 1;
```
one of them is expected to fail.  However, the error message displayed makes no sense.  A more meaningful error is needed.
### Actual behavior
The concurrent update fails with the following error message:
```
 ERROR:  EvalPlanQual can not handle subPlan with Motion node
```

### Step to reproduce the behavior
Turn on GDD (`gp_enable_global_deadlock_detector = on`).
Run the following isolation2 spec:
```SQL
1: create table foo (c1 int, c2 int) distributed by(c1);
1: insert into foo values(1,1);
1: select * from foo;

1: begin;
1: update foo set c1 = c1 + 1 where c1 = 1;
2&: update foo set c1 = c1 + 1 where c1 = 1;
1: end;
2<:
```

**Comment by asimrp** [comment]
FYI, @kainwen

**Comment by kainwen** [comment]
Actually, from my perspective, the error message makes sense.

split-update is DML with motion plan node and does not support eval-planqual on QEs. I do not think we have plan to change 
 this.
