### ISSUE TITLE
GPSD is busted after Postgres 12 merge

### ISSUE THREAD

**Issue by d** [greenplum-db/gpdb#10941]
### Greenplum version or build
7.0 alpha (master branch commit 61c386632335ce7e as of writing)

### Expected behavior
GPSD dumps the DDL and stats, which can then be restored.

### Actual behavior
```
/bin/gpsd", line 70
    print setStmt.format(',\n'.join(map(lambda t: '\t%s = %s::%s' %
          ^
SyntaxError: invalid syntax
```
### Step to reproduce the behavior
```
createdb pivotal
gpsd pivotal
```

**Comment by ashwinstar** [comment]
I think this might be due to python3 changes and not PostgreSQL 12 merge. Components like this and minirepro which don’t have tests in CI will keep getting broken this way.

**Comment by hlinnaka** [comment]
I wish we had a more robust way of dumping and restoring statistics. The `INSERT INTO pg_statistic` statements that gpsd constructs might not work across versions if the pg_statistic changes. I'm thinking of dumping them in a json file or something, and having a SQL-callable function to load the json file back in. A json file would be easier to also edit by hand if necessary.

gpsd also needs to be updated to dump the "extended statistics" that were introduced in v10 (`CREATE STATISTICS`).
