### ISSUE TITLE
Resgroup's CPU usage limitation didn't take effect.

### ISSUE THREAD

**Issue by dreamedcheng** [greenplum-db/gpdb#10990]
### Greenplum version or build
GP 6.3

### OS version and uname -a
centos 7

### Actual behavior
When executing a query, the resource group's control file (/sys/fs/cgroup/cpu/gpdb/53379/cgroup.procs) should contain the 
backend's pid, however, it doesn't contain any. So the CPU usage of the query didn't limited by the resource group.

Here is my resource group's configuration:
`postgres=> select * from gp_toolkit.gp_resgroup_config ;
 groupid |   groupname   | concurrency | cpu_rate_limit | memory_limit | memory_shared_quota | memory_spill_ratio | memory_auditor | cpuset
---------+---------------+-------------+----------------+--------------+---------------------+--------------------+----------------+--------
    6437 | default_group | 20          | 30             | 0            | 80                  | 0                  | vmtracker      | -1
    6438 | admin_group   | 10          | 10             | 10           | 80                  | 0                  | vmtracker      | -1
   53379 | group1        | 1           | 5              | 0            | 80                  | 0                  | vmtracker      | -1
(3 rows)`
![image](https://user-images.githubusercontent.com/7367189/96240976-213c1080-0fd4-11eb-825b-748f6b6d8f3c.png)

I debugged this problem, and found that when adding a pid to cgroup.procs file of cpuset subsystem in function ResGroupOps_AssignGroup, it will choose the default group (DEFAULT_CPUSET_GROUP_ID) . This will cause that a pid is controlled by two different cgroup of the same level! To prevent this, the cgroup system will just keep the pid in cgroup last written. So the backend was not controlled by the cgroup it belonged to.
![image](https://user-images.githubusercontent.com/7367189/96241674-16ce4680-0fd5-11eb-98ad-fd5ecea4b37c.png)

So I wonder if this problem can be fixed by removing the code
`writeInt64(DEFAULT_CPUSET_GROUP_ID, BASETYPE_GPDB,
					   RESGROUP_COMP_TYPE_CPUSET, "cgroup.procs", pid);`.

**Comment by xiong-gang** [comment]
Thanks for reporting, in your case the pid should be written to both `/sys/fs/cgroup/cpu/gpdb/53379/cgroup.procs` and `/sys/fs/cgroup/cpuset/gpdb/1/cgroup.procs`, and the code snippet you attached is writing the later one. Do you mean you cannot find the pid in `/sys/fs/cgroup/cpu/gpdb/53379/cgroup.procs`?

**Comment by dreamedcheng** [comment]
> Thanks for reporting, in your case the pid should be written to both `/sys/fs/cgroup/cpu/gpdb/53379/cgroup.procs` and `/sys/fs/cgroup/cpuset/gpdb/1/cgroup.procs`, and the code snippet you attached is writing the later one. Do you mean you cannot find the pid in `/sys/fs/cgroup/cpu/gpdb/53379/cgroup.procs`?

When writing pid to /sys/fs/cgroup/cpuset/gpdb/1/cgroup.procs, the same pid written in /sys/fs/cgroup/cpu/gpdb/53379/cgroup.procs before was erased. I wonder if this is because a pid cannot appear in two different cgroup.

**Comment by xiong-gang** [comment]
> > Thanks for reporting, in your case the pid should be written to both `/sys/fs/cgroup/cpu/gpdb/53379/cgroup.procs` and `/sys/fs/cgroup/cpuset/gpdb/1/cgroup.procs`, and the code snippet you attached is writing the later one. Do you mean you cannot find the pid in `/sys/fs/cgroup/cpu/gpdb/53379/cgroup.procs`?
> 
> When writing pid to /sys/fs/cgroup/cpuset/gpdb/1/cgroup.procs, the same pid written in /sys/fs/cgroup/cpu/gpdb/53379/cgroup.procs before was erased. I wonder if this is because a pid cannot appear in two different cgroup.

pid can appear in both `gpdb/cpuset/1` and `gpdb/cpu/group_id`
see the comments in `resgroup-ops.h`:
```
/*
 * Default cpuset group is a group manages the cpu cores which not belong to
 * any other cpuset group. All the processes which not belong to any cpuset
 * group will be run on cores in default cpuset group. It is a virtual group,
 * can't be seen in gpdb.
 */
#define DEFAULT_CPUSET_GROUP_ID 1
```

**Comment by dreamedcheng** [comment]
I debugged this, in my test instance, when writing pid to  `gpdb/cpuset/1`, the pid written in `/sys/fs/cgroup/cpu/gpdb/53379/cgroup.procs ` disappeared. And I use gdb to change the value of `curViaCpuset` so that the pid can be written to `gpdb/cpuset/53379`, in this way, everything is OK.

**Comment by xiong-gang** [comment]
could you cat the file `cpuset.cpus` `cpuset.mems` and `cpuset.cpu_exclusive` under `/sys/fs/cgroup/cpuset/gpdb`, `/sys/fs/cgroup/cpuset/gpdb/1` and `/sys/fs/cgroup/cpuset/gpdb/53379 `

**Comment by dreamedcheng** [comment]
Here is the result:
![image](https://user-images.githubusercontent.com/7367189/97404385-fbe2c700-1930-11eb-9ff1-50224227a99d.png)
![image](https://user-images.githubusercontent.com/7367189/97404456-19179580-1931-11eb-9d23-3278a6a25c05.png)
![image](https://user-images.githubusercontent.com/7367189/97404506-2f255600-1931-11eb-9cb3-1deaa6eda4c5.png)

And the following screenshot are the result when I debugging, when writing pid 25851 to cpuset, it was removed from cpu at the same time:
![image](https://user-images.githubusercontent.com/7367189/97404186-a4dcf200-1930-11eb-80dd-58f291efd482.png)
![image](https://user-images.githubusercontent.com/7367189/97404098-81b24280-1930-11eb-9fcd-cab078f6d4fd.png)

**Comment by dreamedcheng** [comment]
@xiong-gang Do you think the above screenshots are the expected behavior?

**Comment by xiong-gang** [comment]
I did the same steps and it behaves differently. Did you manually change any configurations?

**Comment by dreamedcheng** [comment]
I referred some cgroup documents and found that
`A single task may be in multiple cgroups, as long as each of those cgroups is in a different hierarchy. As soon as a task becomes a member of a second cgroup in the same hierarchy, it is removed from the first cgroup in that hierarchy. At no time is a task ever in two different cgroups in the same hierarchy.`

So I use `lssubsys -am` to list where the hierarchy they are attached to is mounted.  Surprisingly, `cpu` and `cpuset` are attached to the same hierarchy!
```
$lssubsys -am
cpuset,cpu,cpuacct /sys/fs/cgroup/cpuset,cpu,cpuacct
blkio /sys/fs/cgroup/blkio
memory /sys/fs/cgroup/memory
devices /sys/fs/cgroup/devices
```

I'll try to mount cpu and cpuset to different hierarchy later to see if the problem still exists.

**Comment by xiong-gang** [comment]
> I referred some cgroup documents and found that
> `A single task may be in multiple cgroups, as long as each of those cgroups is in a different hierarchy. As soon as a task becomes a member of a second cgroup in the same hierarchy, it is removed from the first cgroup in that hierarchy. At no time is a task ever in two different cgroups in the same hierarchy.`
> 
> So I use `lssubsys -am` to list where the hierarchy they are attached to is mounted. Surprisingly, `cpu` and `cpuset` are attached to the same hierarchy!
> 
> ```
> $lssubsys -am
> cpuset,cpu,cpuacct /sys/fs/cgroup/cpuset,cpu,cpuacct
> blkio /sys/fs/cgroup/blkio
> memory /sys/fs/cgroup/memory
> devices /sys/fs/cgroup/devices
> ```
> 
> I'll try to mount cpu and cpuset to different hierarchy later to see if the problem still exists.

Hmmm... I think that's the problem, it doesn't seem right to mount cpuset and cpu together.

**Comment by dreamedcheng** [comment]
@xiong-gang Yes, I verified this. And I think we may need a check here to see if `cpu` and `cpuset` are mounted at the same hierarchy, and throw an error in advance if it is. BTW, I open a PR for this, please take a look.

**Comment by xiong-gang** [comment]
Thank you,  it looks good in general, I will review and merge it.

**Comment by kainwen** [comment]
Fixed by 

* 6x (https://github.com/greenplum-db/gpdb/pull/11265)
* master (https://github.com/greenplum-db/gpdb/pull/11200)
