### ISSUE TITLE
gprecoverseg -r fails when password authentification enabled for gpadmin

### ISSUE THREAD

**Issue by avkashin** [greenplum-db/gpdb#10991]
### Greenplum version or build
PostgreSQL 9.4.24 (Greenplum Database 6.11.1 build dev-oss) on x86_64-pc-linux-gnu, compiled by gcc-6 (Ubuntu 6.5.0-2ubuntu1~18.04) 6.5.0 20181026, 64-bit co
mpiled on Sep 30 2020 11:51:36
### OS version and uname -a
Linux greenplum-test01i.db.example.net 4.19.114-29 #1 SMP Tue Apr 7 08:08:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
### autoconf options used ( config.status --config )
'--with-perl' '--with-python' '--with-libxml' '--with-gssapi' '--prefix=/opt/greenplum-db-6' '--enable-gpperfmon' '--disable-pxf' '--enable-orca' '--with-ldap' '--with-openssl' '--with-pam' '--with-zstd'
### Installation information ( pg_config )
BINDIR = /opt/greenplum-db-6/bin
DOCDIR = /opt/greenplum-db-6/share/doc/postgresql
HTMLDIR = /opt/greenplum-db-6/share/doc/postgresql
INCLUDEDIR = /opt/greenplum-db-6/include
PKGINCLUDEDIR = /opt/greenplum-db-6/include/postgresql
INCLUDEDIR-SERVER = /opt/greenplum-db-6/include/postgresql/server
LIBDIR = /opt/greenplum-db-6/lib
PKGLIBDIR = /opt/greenplum-db-6/lib/postgresql
LOCALEDIR = /opt/greenplum-db-6/share/locale
MANDIR = /opt/greenplum-db-6/share/man
SHAREDIR = /opt/greenplum-db-6/share/postgresql
SYSCONFDIR = /opt/greenplum-db-6/etc/postgresql
PGXS = /opt/greenplum-db-6/lib/postgresql/pgxs/src/makefiles/pgxs.mk
CONFIGURE = '--with-perl' '--with-python' '--with-libxml' '--enable-mapreduce' '--with-gssapi' '--with-extra-version=-oss' '--with-libs=/home/robot-pgaas-ci/workspace/greenplum-db-6-bionic-deb/gpdb/debian/build/lib' '--with-includes=/home/robot-pgaas-ci/workspace/greenplum-db-6-bionic-deb/gpdb/debian/build/include' '--prefix=/home/robot-pgaas-ci/workspace/greenplum-db-6-bionic-deb/gpdb/debian/build' '--with-ldap' '--enable-gpperfmon' '--with-pam' '--with-openssl' '--disable-pxf' '--with-zstd' 'CC=/usr/bin/gcc-6' 'CFLAGS=-g -O2 -fdebug-prefix-map=/home/robot-pgaas-ci/workspace/greenplum-db-6-bionic-deb/gpdb=. -fstack-protector-strong -Wformat -Werror=format-security' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'CXX=/usr/bin/g++-6' 'CXXFLAGS=-g -O2 -fdebug-prefix-map=/home/robot-pgaas-ci/workspace/greenplum-db-6-bionic-deb/gpdb=. -fstack-protector-strong -Wformat -Werror=format-security'
CC = /usr/bin/gcc-6
CPPFLAGS = -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2 -I/home/robot-pgaas-ci/workspace/greenplum-db-6-bionic-deb/gpdb/debian/build/include -I/opt/greenplum-db-6/include
CFLAGS = -Wall -Wmissing-prototypes -Wpointer-arith -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fno-aggressive-loop-optimizations -Wno-unused-but-set-variable -Wno-address -g -O2 -fdebug-prefix-map=/home/robot-pgaas-ci/workspace/greenplum-db-6-bionic-deb/gpdb=. -fstack-protector-strong -Wformat -Werror=format-security -std=gnu99 -Werror=uninitialized -Werror=implicit-function-declaration -I/opt/greenplum-db-6/include
CFLAGS_SL = -fPIC
LDFLAGS = -Wl,-Bsymbolic-functions -Wl,-z,relro -L/home/robot-pgaas-ci/workspace/greenplum-db-6-bionic-deb/gpdb/debian/build/lib -Wl,--as-needed -Wl,-rpath,'/home/robot-pgaas-ci/workspace/greenplum-db-6-bionic-deb/gpdb/debian/build/lib',--enable-new-dtags -L/opt/greenplum-db-6/lib
LDFLAGS_EX =
LDFLAGS_SL =
LIBS = -lpgcommon -lpgport -lxerces-c -lxml2 -lpam -lrt -lyaml -lgssapi_krb5 -lzstd -lrt -lcrypt -ldl -lm -L/opt/greenplum-db-6/lib
VERSION = PostgreSQL 9.4.24
### Expected behavior
`grecoverseg -r` executed successfully
### Actual behavior
```
gpadmin@greenplum-test01i:~$ gprecoverseg -ar
20201016:14:44:04:018503 gprecoverseg:greenplum-test01i:gpadmin-[INFO]:-Starting gprecoverseg with args: -ar
20201016:14:44:04:018503 gprecoverseg:greenplum-test01i:gpadmin-[INFO]:-local Greenplum Version: 'postgres (Greenplum Database) 6.11.1 build dev-oss'
20201016:14:44:04:018503 gprecoverseg:greenplum-test01i:gpadmin-[INFO]:-master Greenplum Version: 'PostgreSQL 9.4.24 (Greenplum Database 6.11.1 build dev-oss) on x86_64-pc-linux-gnu, compiled by gcc-6 (Ubuntu 6.5.0-2ubuntu1~18.04) 6.5.0 20181026, 64-bit compiled on Sep 30 2020 11:51:36'
20201016:14:44:04:018503 gprecoverseg:greenplum-test01i:gpadmin-[INFO]:-Obtaining Segment details from master...
20201016:14:44:04:018503 gprecoverseg:greenplum-test01i:gpadmin-[INFO]:-Greenplum instance recovery parameters
20201016:14:44:04:018503 gprecoverseg:greenplum-test01i:gpadmin-[INFO]:----------------------------------------------------------
20201016:14:44:04:018503 gprecoverseg:greenplum-test01i:gpadmin-[INFO]:-Recovery type              = Rebalance
20201016:14:44:04:018503 gprecoverseg:greenplum-test01i:gpadmin-[INFO]:----------------------------------------------------------
20201016:14:44:04:018503 gprecoverseg:greenplum-test01i:gpadmin-[INFO]:-Unbalanced segment 1 of 2
20201016:14:44:04:018503 gprecoverseg:greenplum-test01i:gpadmin-[INFO]:----------------------------------------------------------
20201016:14:44:04:018503 gprecoverseg:greenplum-test01i:gpadmin-[INFO]:-   Unbalanced instance host        = greenplum-test03i.db.example.net
20201016:14:44:04:018503 gprecoverseg:greenplum-test01i:gpadmin-[INFO]:-   Unbalanced instance address     = greenplum-test03i.db.example.net
20201016:14:44:04:018503 gprecoverseg:greenplum-test01i:gpadmin-[INFO]:-   Unbalanced instance directory   = /data1/mirror/gpseg3
20201016:14:44:04:018503 gprecoverseg:greenplum-test01i:gpadmin-[INFO]:-   Unbalanced instance port        = 7001
20201016:14:44:04:018503 gprecoverseg:greenplum-test01i:gpadmin-[INFO]:-   Balanced role                   = Mirror
20201016:14:44:04:018503 gprecoverseg:greenplum-test01i:gpadmin-[INFO]:-   Current role                    = Primary
20201016:14:44:04:018503 gprecoverseg:greenplum-test01i:gpadmin-[INFO]:----------------------------------------------------------
20201016:14:44:04:018503 gprecoverseg:greenplum-test01i:gpadmin-[INFO]:-Unbalanced segment 2 of 2
20201016:14:44:04:018503 gprecoverseg:greenplum-test01i:gpadmin-[INFO]:----------------------------------------------------------
20201016:14:44:04:018503 gprecoverseg:greenplum-test01i:gpadmin-[INFO]:-   Unbalanced instance host        = greenplum-test04i.db.example.net
20201016:14:44:04:018503 gprecoverseg:greenplum-test01i:gpadmin-[INFO]:-   Unbalanced instance address     = greenplum-test04i.db.example.net
20201016:14:44:04:018503 gprecoverseg:greenplum-test01i:gpadmin-[INFO]:-   Unbalanced instance directory   = /data1/primary/gpseg3
20201016:14:44:04:018503 gprecoverseg:greenplum-test01i:gpadmin-[INFO]:-   Unbalanced instance port        = 6001
20201016:14:44:04:018503 gprecoverseg:greenplum-test01i:gpadmin-[INFO]:-   Balanced role                   = Primary
20201016:14:44:04:018503 gprecoverseg:greenplum-test01i:gpadmin-[INFO]:-   Current role                    = Mirror
20201016:14:44:04:018503 gprecoverseg:greenplum-test01i:gpadmin-[INFO]:----------------------------------------------------------
20201016:14:44:04:018503 gprecoverseg:greenplum-test01i:gpadmin-[INFO]:-Getting unbalanced segments
20201016:14:44:04:018503 gprecoverseg:greenplum-test01i:gpadmin-[INFO]:-Stopping unbalanced primary segments...
20201016:14:44:04:018503 gprecoverseg:greenplum-test01i:gpadmin-[INFO]:-Triggering segment reconfiguration
20201016:14:44:04:018503 gprecoverseg:greenplum-test01i:gpadmin-[CRITICAL]:-gprecoverseg failed. (Reason='FATAL:  no pg_hba.conf entry for host "10.0.0.1", user "Gp4dmin_sup3Rpwd", database "test", SSL off
') exiting...
```
### Step to reproduce the behavior

1. Accept connections from localhost to GP only with `md5` method
```
local    all         gpadmin                                    ident
host     all         gpadmin         127.0.0.1/28       md5
host     all         gpadmin         10.10.0.1/32       md5
host     all         gpadmin         ::1/128                md5
```
2. Reload GP
`gpstop -u`
3. set variable `PGPASSWORD` - `export PGPASSWORD='Gp4dmin_sup3Rpwd'`
or insert password to `/home/gpadmin/.pgpass`. 
```
# hostname:port:database:username:password
*:*:*:gpadmin:Gp4dmin_sup3Rpwd
```
4. Run `gprecoverseg -r` and get error
```
20201016:14:44:04:018503 gprecoverseg:greenplum-test01i:gpadmin-[CRITICAL]:-gprecoverseg failed. (Reason='FATAL:  no pg_hba.conf entry for host "10.0.0.1", user "Gp4dmin_sup3Rpwd", database "test", SSL off
```
As you can see from the above error - `user` contains gpadmin password but no username `gpadmin`.

This patch made `gprecoverseg -r` works
```
--- /opt/greenplum-db-6/lib/python/gppylib/operations/segment_reconfigurer.py   2020-10-16 15:18:22.661197865 +0300
+++ /var/tmp/segment_reconfigurer.py.patched    2020-10-16 15:05:24.244906823 +0300
@@ -14,12 +14,12 @@
         self.timeout = timeout

     def _trigger_fts_probe(self, dburl):
-        conn = pygresql.pg.connect(dburl.pgdb,
-                dburl.pghost,
-                dburl.pgport,
-                None,
-                dburl.pguser,
-                dburl.pgpass,
+        conn = pygresql.pg.connect(dbname=dburl.pgdb,
+                host=dburl.pghost,
+                port=dburl.pgport,
+                opt=None,
+                user=dburl.pguser,
+                passwd=dburl.pgpass,
                 )
         conn.query(FTS_PROBE_QUERY)
         conn.close()
```

**Comment by ashwinstar** [comment]
Ouch!! that's bad pass____ displayed for username. Do you wish to open PR @avkashin to fix the issue? If not we can take it forward and fix.

Also, need to check in code if some other places exhibit similar problems in management utility code @kalensk

**Comment by kalensk** [comment]
I created a bug in our backlog to see if other utilities need to be updated and ensure gprecovseg gets fixed. Due to our limited resources and huge list of priorities, it will be awhile before we get to it unless it is pressing.

**Comment by avkashin** [comment]
Thanks for your fast response. [PR](https://github.com/greenplum-db/gpdb/pull/10995)

**Comment by avkashin** [comment]
PRs merged into master and 6X_STABLE.
