### ISSUE TITLE
gp_segment_configuration can't probe standy master down

### ISSUE THREAD

**Issue by lambgong** [greenplum-db/gpdb#11013]
### Greenplum version or build
gp 6.5

### OS version and uname -a
centos 7

### Step to reproduce the behavior
Kill standy master process，then check gp_segment_configuration，all the status are 'u'.
If you run gpstate -s, you can get the 'Standby host DOWN' correctly.

**Comment by xiong-gang** [comment]
FTS doesn't check the healthy and update gp_segment_configuration for standby coordinator, we are currently working on the coordinator auto-failover, please check the discussion on gpdb-dev mailing list.

**Comment by asimrp** [comment]
@laixiong on a related note, we are in the process of fixing the problem that master/standby status is tracked by master.  It should be tracked by a third-party other the master/standby.  https://groups.google.com/a/greenplum.org/g/gpdb-dev/c/402fIfVZ9SI/m/Pmljgy-_AgAJ
