### ISSUE TITLE
How to convert field type int2vector to array

### ISSUE THREAD

**Issue by cobolbaby** [greenplum-db/gpdb#11025]
When I execute the `select * from gp_distribution_policy`, I can get the `distkey` information. But the field in the GP6.x version is of the `int2vector` type, neither `smallint[]`.

I need to convert int2vector to an array type to make pgAdmin4 compatible with GP6. How can I do this?

**Comment by hlinnaka** [comment]
You can cast it:
```
postgres=# select '1 2 3'::int2vector::smallint[];
     int2      
---------------
 [0:2]={1,2,3}
(1 row)

```
The resulting array is a bit unusual, because it starts from index 0, rather than 1 like arrays in Postgres usually do. If that bothers you, you can do:
```
postgres=# select ('1 2 3'::int2vector::smallint[])[0:100];
  int2   
---------
 {1,2,3}
(1 row)
```
