### ISSUE TITLE
Some tools have weak authority management

### ISSUE THREAD

**Issue by sanjiaomaohhh** [greenplum-db/gpdb#11038]
### Greenplum version or build
6.10
### Description
The official tool versions provided by GP, such as gpkafka and gpcopy, do not provide open source code and can only download compiled artifacts. These tools are relatively weak in terms of rights management. For example, gpcopy requires users to use trust mode when connecting, but cannot use password authentication.

**Comment by lij55** [comment]
Open source Greenplum doesn't rely on any commercial components. It should be the issue of gpcopy or gpKafka (or any other commercial product from any company) that it doesn't work with open source Greenplum
Please go to the Offical Support team for all issues related to all closed source components.
