### ISSUE TITLE
Some security features do not meet the current general requirements of security protection

### ISSUE THREAD

**Issue by sanjiaomaohhh** [greenplum-db/gpdb#11035]
### Greenplum version or build
6.10
### Description
Postgres client login database server authentication using MD5 and other insecure encryption algorithm, does not meet the general requirements of security protection.

**Comment by hlinnaka** [comment]
GPDB 7 introduces SCRAM authentication as an alternative to the historical md5 authentication. In older versions, TLS with client certificate authentication is one option.
