### ISSUE TITLE
System table/view stores clear-text passwords

### ISSUE THREAD

**Issue by sanjiaomaohhh** [greenplum-db/gpdb#11033]
### Greenplum version or build
6.10
### Description
System table _pg_user_mapping_ stores the user name and **clear-text password** information of the external database, which is used to remotely connect to the external database from the local database and access the tables on the external database.

**Comment by hlinnaka** [comment]
That is by design. See similar question on pgsql-bugs list: https://www.postgresql.org/message-id/flat/16682-89078b97ed03d74b%40postgresql.org
