### ISSUE TITLE
/usr/local/greenplum-db-oss/bin/psql: not found

### ISSUE THREAD

**Issue by spcxtesla** [greenplum-db/gpdb#11048]
### Greenplum version or build
-local Greenplum Version: 'postgres (Greenplum Database) 6.11.2 build commit:d611e78af2c5a6561ccbbaf2b4652138410f9aeb Open Source'

### OS version and uname -a
Linux  hostname 4.15.0-122-generic #124-Ubuntu SMP Thu Oct 15 13:03:05 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

### autoconf options used ( config.status --config )
I use `apt install greenplum-db-6`

### Installation information ( pg_config )
BINDIR = /opt/greenplum-db-6-6.11.2/bin
DOCDIR = /opt/greenplum-db-6-6.11.2/share/doc/postgresql
HTMLDIR = /opt/greenplum-db-6-6.11.2/share/doc/postgresql
INCLUDEDIR = /opt/greenplum-db-6-6.11.2/include
PKGINCLUDEDIR = /opt/greenplum-db-6-6.11.2/include/postgresql
INCLUDEDIR-SERVER = /opt/greenplum-db-6-6.11.2/include/postgresql/server
LIBDIR = /opt/greenplum-db-6-6.11.2/lib
PKGLIBDIR = /opt/greenplum-db-6-6.11.2/lib/postgresql
LOCALEDIR = /opt/greenplum-db-6-6.11.2/share/locale
MANDIR = /opt/greenplum-db-6-6.11.2/man
SHAREDIR = /opt/greenplum-db-6-6.11.2/share/postgresql
SYSCONFDIR = /opt/greenplum-db-6-6.11.2/etc/postgresql
PGXS = /opt/greenplum-db-6-6.11.2/lib/postgresql/pgxs/src/makefiles/pgxs.mk
CONFIGURE = '--disable-debug-extensions' '--disable-tap-tests' '--enable-orca' '--with-zstd' '--with-gssapi' '--with-libxml' '--with-perl' '--with-python' '--with-openssl' '--with-pam' '--with-ldap' '--with-extra-version= Open Source' '--prefix=/usr/local/greenplum-db-oss' '--mandir=/usr/local/greenplum-db-oss/man' 'CC=gcc' 'CFLAGS=-O3 -fargument-noalias-global -fno-omit-frame-pointer -g'
CC = gcc
CPPFLAGS = -D_GNU_SOURCE -I/usr/include/libxml2 -I/opt/greenplum-db-6-6.11.2/include
CFLAGS = -Wall -Wmissing-prototypes -Wpointer-arith -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fno-aggressive-loop-optimizations -Wno-unused-but-set-variable -Wno-address -Werror=implicit-fallthrough=3 -Wno-format-truncation -O3 -fargument-noalias-global -fno-omit-frame-pointer -g -std=gnu99 -Werror=uninitialized -Werror=implicit-function-declaration -I/opt/greenplum-db-6-6.11.2/include
CFLAGS_SL = -fPIC
LDFLAGS = -Wl,--as-needed -Wl,-rpath,'/usr/local/greenplum-db-oss/lib',--enable-new-dtags -L/opt/greenplum-db-6-6.11.2/lib
LDFLAGS_EX = 
LDFLAGS_SL = 
LIBS = -lpgcommon -lpgport -lxerces-c -lxml2 -lpam -lrt -lgssapi_krb5 -lzstd -lrt -lcrypt -ldl -lm -L/opt/greenplum-db-6-6.11.2/lib
VERSION = PostgreSQL 9.4.24

### Expected behavior
> /opt/greenplum-db-6-6.11.2/lib/postgresql/pgxs/src/makefiles/../../src/test/regress/pg_regress --inputdir=./ --psqldir='/opt/greenplum-db-6-6.11.2/bin'    --dbname=contrib_regression xxx
(using postmaster on Unix socket, default port)
============== dropping database "contrib_regression" ==============
DROP DATABASE
============== creating database "contrib_regression" ==============
CREATE DATABASE
ALTER DATABASE
============== checking optimizer status              ==============
Optimizer enabled. Using optimizer answer files whenever possible
============== checking gp_resource_manager status    ==============
Resource group disabled. Using default answer files
============== running regression test queries        ==============
test xxx ... ok
=====================
 All 1 tests passed. 
=====================

### Actual behavior
> /opt/greenplum-db-6-6.11.2/lib/postgresql/pgxs/src/makefiles/../../src/test/regress/pg_regress --inputdir=./ --psqldir='/opt/greenplum-db-6-6.11.2/bin'    --dbname=contrib_regression xxx
(using postmaster on Unix socket, default port)
sh: 1: /usr/local/greenplum-db-oss/bin/psql: not found
pg_regress: cannot read the result
/opt/greenplum-db-6-6.11.2/lib/postgresql/pgxs/src/makefiles/pgxs.mk:303: recipe for target 'installcheck' failed
make: *** [installcheck] Error 2

### Step to reproduce the behavior
```make installcheck```

A solution:
```bash
sudo mkdir -p /usr/local/greenplum-db-oss/bin
ln -s ${GPHOME}/bin/psql /usr/local/greenplum-db-oss/bin/
```

**Comment by adam8157** [comment]
@bradfordb-vmware Hi, is this a known issue?

**Comment by bradfordb-vmware** [comment]
I don't believe this is a known issue but I also don't know that this is a supported use case (building an extension against pre-packaged OSS GPDB).

**Comment by kmacoskey** [comment]
@spcxtesla  It is currently not supported. By that I mean it's a bug.

The pre-built debian packages are relocated to install at `/opt/greenplum-db-[version]` while the compilation originally occurs at `/usr/local/greenplum-db-oss/`. The way with which **pgxs** is handling paths from compilation to execution it seems does not work with that relocation.  I believe this may not be an issue for the pre-built centos packages but I haven't checked.

The creation of the pre-built Greenplum packages for each releases is split across a few open source repositories. We will look into this issue to find a fix.

**Comment by kmacoskey** [comment]
Howdy @spcxtesla,

A change was made to resolve this issue. The change occurred in a different repository because some of the code that maintains the pre-built package distributions for every release is not located in this repository.  Please reference https://github.com/greenplum-db/greenplum-database-release/pull/98

In future releases of the Greenplum Database 6, pre-built packages made available on Launchpad, `pg_regress` should be looking in the correct directory.

Please open another issue if there are still problems or reach out to us in [Slack](https://greenplum.slack.com/). 

Thank you! - Greenplum Release Engineering team
