### ISSUE TITLE
ssh_utils.py

### ISSUE THREAD

**Issue by Viocalpan** [greenplum-db/gpdb#11079]
def escapeLine(self, line):
        '''Escape occurrences of \ and $ as needed and package the line as an "eval" shell command'''
        line = line.strip()
        if line == 'EOF' or line == 'exit' or line == 'quit':
            self.close(). #Add by Viocal pan 
            raise self.SessionCmdExit()
        line = line.split('\\')
        line = '\\\\'.join(line)
        line = line.split('"')
        line = '\\"'.join(line)
        line = line.split('$')
        line = '\\$'.join(line)
        line = 'eval "' + line + '" < /dev/null'
        return line

**Comment by adam8157** [comment]
Hi, why do you want to close the session? What is the issue?

**Comment by Viocalpan** [comment]
fix bug in ssh_utils.py

**Comment by Viocalpan** [comment]
ssh_utils.py 

def escapeLine(self, line):
    '''Escape occurrences of \ and $ as needed and package the line as an "eval" shell command'''
    line = line.strip()
    if line == 'EOF' or line == 'exit' or line == 'quit':
        _**self.close()  #fix it**_
        raise self.SessionCmdExit()
    line = line.split('\\')
    line = '\\\\'.join(line)
    line = line.split('"')
    line = '\\"'.join(line)
    line = line.split('$')
    line = '\\$'.join(line)
    line = 'eval "' + line + '" < /dev/null'
    return line
