### ISSUE TITLE
alter table REORGANIZE=true, should it reshuffle if dist key is the same

### ISSUE THREAD

**Issue by skahler-pivotal** [greenplum-db/gpdb#1109]
One of the things we talk about is using the ALTER TABLE REORGANIZE=true in order to reshuffle data. If it is a hash distributed table, I believe the reorganization is skipped altogether and no validation is done to ensure the data is actually hashed across the nodes correctly. Is this what we think the behavior should be?

**Comment by deepesh1081** [comment]
i feel that alter table reorganize=true/false, should be made simple as the user wants to re-distribute the data. 
it should always redistribute the data, irrespective of current distribution key. 
What would be a valid use case to say 'alter table reorganize=false' , irrespective of what columns they are going to be redistributed?

**Comment by skahler-pivotal** [comment]
The only use case I could see for need a reorganize=false would be going from a distributed table to a random and not wanting things to be reshuffled, so maybe you want to specify that it doesn't. I would think those are rare cases.

**Comment by Eulerizeit** [comment]
As @ashwin pointed out off thread:

> Currently, it seems (REORGANIZE=true) is having intelligence if nothing needs to be done why re-write. Seems documentation have it mentioned as if REORGANIZE is specified it must always rewrite the table. So, currently REORGANIZE is only useful for DISTRIBUTED RANDOMLY.

> It sounds correct from perspective having the option for it means it should perform what's asked to do, adding intelligence to it for this case doesn't seem useful.

It seems to me that we ought to be a little less smart and when we say redistribute we ought to redistribute.

**Comment by ashwinstar** [comment]
Also, for records there is no use case for reorganize=false. Altering distributed table to a random, anyways currently doesn't rewrite the data by default.

**Comment by lij55** [comment]
With the help of "copy from on segment", user would run quite easily into such situation that need redistribute immediately. 'reorganize=true' should be able to solve this as it is expected.

**Comment by ashwinstar** [comment]
This was fixed by https://github.com/greenplum-db/gpdb/pull/3189 and https://github.com/greenplum-db/gpdb/commit/31fd953d6a86520f193dc20e685f980a5d366c20
