### ISSUE TITLE
configure: error: header file <Python.h> is required for Python

### ISSUE THREAD

**Issue by jellyfig** [greenplum-db/gpdb#11091]
### Greenplum version or build
Docker container with GPDB for development/testing
2020-11-01  git clone gpdb-master

### OS version and uname -a
docker pull pivotaldata/gpdb-dev:centos7

### Actual behavior
configure: error: header file <Python.h> is required for Python

### Step to reproduce the behavior

docker run -w /home/build/gpdb -v ${PWD}:/home/build/gpdb:cached -it pivotaldata/gpdb-dev:centos7 /bin/bash

./configure --enable-debug --with-perl --with-python --with-libxml --disable-orca --prefix=/usr/local/gpdb

**Comment by ashwinstar** [comment]
Use `centos7-gpdb7` instead of `centos7`. That has Python3 which is required now to build GPDB master branch.

**Comment by adam8157** [comment]
FYI, https://github.com/greenplum-db/gpdb/issues/12431 and https://github.com/greenplum-db/gpdb/blob/master/README.CentOS.bash

Closing
