### ISSUE TITLE
Incomplete implementation of distributed version of pg_stat* views on master branch

### ISSUE THREAD

**Issue by maksm90** [greenplum-db/gpdb#11099]
The commit e6f93033289 have made the `pg_stat_all_tables` and `pg_stat_all_indexes` views as distributed that return aggregated statistic values for user defined objects over segments and raw statistics for system objects over master node. But there are at least two other related system views left unchanged (only with local execution) - `pg_statio_tables` and `pg_statio_indexes`. There is not any problem to make them as distributed similar to this was done for the `pg_stat_all_*` views. But I'm confused that proposed distributed version of these views doesn't allow to see statistic counters by segments - the more granular output . AFAICS this would require to add `gp_segment_id` column (via issuing `gp_execution_segment()` call) to the result row type of those views. Therefore I propose to:
- change definition of `pg_stat_all_*_internal` views prepending to target list the `gp_segment_id` column
- remove aggregates from the definition of `pg_stat_*` views
- make `pg_statio_*` views similar to `pg_stat_*` ones.

Any thoughts and objections?

**Comment by maksm90** [comment]
Any interest to this issue?
I plan to make some [addons](https://github.com/arenadata/gpdb/pull/122) to pg_stat_* views that will be based on possible fixes from current issue. Please don't ignore it.

**Comment by ashwinstar** [comment]
@maksm90 sorry for getting late to this one. I :+1: on the approach you have proposed and providing granular results as well as for sure, for these kind of things segment level visibility is really and more important than aggregated values.

**Comment by maksm90** [comment]
Hi @ashwinstar ! Thanks for your comment.

Now I have revised my point of view on this issue and propose to leave unchanged the definition of `pg_stat_all_tables` and `pg_stat_all_indexes` views as they give cluster-wide representation of system statistics for tables and indexes without interface modification compared with those one in PostgreSQL. But to allow granular segment-wide representation of these views I propose to inject `gp_execution_segment()` column in `pg_stat_*_internal` view and explicitly request `gp_dist_random('pg_stat_*_internal')` by users. Also as I previously mentioned I want to carry all changes to `pg_statio_*` views to make their similar to `pg_stat_*` ones.

What do you think about this?

**Comment by ashwinstar** [comment]
I am closing this as PR https://github.com/greenplum-db/gpdb/pull/15239 has been merged to main branch which provides the discussed functionality.
