### ISSUE TITLE
Canceling query because of high VMEM usage. 

### ISSUE THREAD

**Issue by zhongyibill** [greenplum-db/gpdb#11095]
### Greenplum version or build
Greenplum Database 7.0.0-alpha.0    commit:26fbf68751ab3bfbab63714bacee24693c1ce610

I use tpcds test greenplum. The test data volume is 10T，then get error result
`
Canceling query because of high VMEM usage. Used: 7373MB, available 819MB, red zone: 7372MB (runaway_cleaner.c:202)",,,,,,"select  *
from (select i_category
            ,i_class
            ,i_brand
            ,i_product_name
            ,d_year
            ,d_qoy
            ,d_moy
            ,s_store_id
            ,sumsales
            ,rank() over (partition by i_category order by sumsales desc) rk
      from (select i_category
                  ,i_class
                  ,i_brand
                  ,i_product_name
                  ,d_year
                  ,d_qoy
                  ,d_moy
                  ,s_store_id
                  ,sum(coalesce(ss_sales_price*ss_quantity,0)) sumsales
            from store_sales
                ,date_dim
                ,store
                ,item
       where  ss_sold_date_sk=d_date_sk
          and ss_item_sk=i_item_sk
          and ss_store_sk = s_store_sk
          and d_month_seq between 1201 and 1201+11
       group by  rollup(i_category, i_class, i_brand, i_product_name, d_year, d_qoy, d_moy,s_store_id))dw1) dw2
where rk <= 100
order by i_category
        ,i_class
        ,i_b",0,,"runaway_cleaner.c",202
`
pg_log has some error info:
`
2020-10-30 11:20:48.170404 HKT,,,p14919,th1619134592,,,,0,,,seg10,,,,,"LOG","00000","3rd party error log:
TopMemoryContext: 285312 total in 9 blocks; 33256 free (32 chunks); 252056 used
",,,,,,,,"SysLoggerMain","syslogger.c",691,

2020-10-30 11:20:48.170602 HKT,,,p14919,th1619134592,,,,0,,,seg10,,,,,"LOG","00000","3rd party error log:
  TupSerMemCtxt: 8192 total in 1 blocks; 8152 free (0 chunks); 40 used
  Interconnect Context: 8192 total in 1 blocks; 8152 free (0 chunks); 40 used
  MessageContext: 8192 total in 1 blocks; 7112 free (0 chunks); 1080 used
  Oid dispatch context: 0 total in 0 blocks; 0 free (0 chunks); 0 used
  UdpInterconnectMemContext: 8192 total in 1 blocks; 6056 free (41 chunks); 2136 used
  Local Stat Portal Hash: 8192 total in 1 blocks; 2696 free (0 chunks); 5496 used
  Operator class cache: 8192 total in 1 blocks; 776 free (0 chunks); 7416 used
  smgr relation table: 24576 total in 2 blocks; 13008 free (4 chunks); 11568 used
  TransactionAbortContext: 32768 total in 1 blocks; 32728 free (0 chunks); 40 used
  Portal hash: 8192 total in 1 blocks; 776 free (0 chunks); 7416 used
  PortalMemory: 8192 total in 1 blocks; 8152 free (1 chunks); 40 used
  Relcache by OID: 24576 total in 2 blocks; 12960 free (4 chunks); 11616 used
  CacheMemoryContext: 548976 total in 8 blocks; 169712 free (0 chunks); 379264 used
    pg_db_role_setting_databaseid_rol_index: 1024 total in 1 blocks; 312 free (0 chunks); 712 used
    pg_opclass_am_name_nsp_index: 1024 total in 1 blocks; 16 free (0 chunks); 1008 used
    pg_foreign_data_wrapper_name_index: 1024 total in 1 blocks; 448 free (0 chunks); 576 used
    pg_enum_oid_index: 1024 total in 1 blocks; 448 free (0 chunks); 576 used
    pg_class_relname_nsp_index: 1024 total in 1 blocks; 312 free (0 chunks); 712 used
    pg_foreign_server_oid_index: 1024 total in 1 blocks; 448 free (0 chunks); 576 used
    pg_statistic_relid_att_inh_index: 1024 total in 1 blocks; 16 free (0 chunks); 1008 used
    pg_cast_source_target_index: 1024 total in 1 blocks; 312 free (0 chunks); 712 used
    pg_language_lanname_index: 1024 total in 1 blocks; 448 free (0 chunks); 576 used
    pg_transform_oid_index: 1024 total in 1 blocks; 448 free (0 chunks); 576 used
    pg_partition_rule_oid_index: 1024 total in 1 blocks; 448 free (0 chunks); 576 used
    pg_partition_oid_index: 1024 total in 1 blocks; 448 free (0 chunks); 576 used
    pg_collation_oid_index: 1024 total in 1 blocks; 448 free (0 chunks); 576 used
    pg_amop_fam_strat_index: 1024 total in 1 blocks; 16 free (0 chunks); 1008 used
    pg_index_indexrelid_index: 1024 total in 1 blocks; 400 free (0 chunks); 624 used
    pg_ts_template_tmplname_index: 1024 total in 1 blocks; 312 free (0 chunks); 712 used
    pg_ts_config_map_index: 1024 total in 1 blocks; 16 free (0 chunks); 1008 used
    gp_policy_localoid_index: 1024 total in 1 blocks; 448 free (0 chunks); 576 used
    pg_opclass_oid_index: 1024 total in 1 blocks; 400 free (0 chunks); 624 used
    pg_foreign_data_wrapper_oid_index: 1024 total in 1 blocks; 448 free (0 chunks); 576 used
    pg_event_trigger_evtname_index: 1024 total in 1 blocks; 448 free (0 chunks); 576 used
    pg_ts_dict_oid_index: 1024 total in 1 blocks; 448 free (0 chunks); 576 used
    pg_event_trigger_oid_index: 1024 total in 1 blocks; 448 free (0 chunks); 576 used
    pg_conversion_default_index: 1024 total in 1 blocks; 16 free (0 chunks); 1008 used
    pg_operator_oprname_l_r_n_index: 1024 total in 1 blocks; 16 free (0 chunks); 1008 used
    pg_trigger_tgrelid_tgname_index: 1024 total in 1 blocks; 312 free (0 chunks); 712 used
    pg_extprotocol_ptcname_index: 1024 total in 1 blocks; 448 free (0 chunks); 576 used
    pg_enum_typid_label_index: 1024 total in 1 blocks; 312 free (0 chunks); 712 used
",,,,,,,,"SysLoggerMain","syslogger.c",691,

2020-10-30 11:20:48.171125 HKT,,,p14919,th1619134592,,,,0,,,seg10,,,,,"LOG","00000","3rd party error log:
    pg_ts_config_oid_index: 1024 total in 1 blocks; 448 free (0 chunks); 576 used
    pg_user_mapping_oid_index: 1024 total in 1 blocks; 448 free (0 chunks); 576 used
    pg_opfamily_am_name_nsp_index: 1024 total in 1 blocks; 16 free (0 chunks); 1008 used
    pg_foreign_table_relid_index: 1024 total in 1 blocks; 448 free (0 chunks); 576 used
    pg_type_oid_index: 1024 total in 1 blocks; 400 free (0 chunks); 624 used
    pg_aggregate_fnoid_index: 1024 total in 1 blocks; 448 free (0 chunks); 576 used
    pg_constraint_oid_index: 1024 total in 1 blocks; 448 free (0 chunks); 576 used
    pg_rewrite_rel_rulename_index: 1024 total in 1 blocks; 312 free (0 chunks); 712 used
    pg_ts_parser_prsname_index: 1024 total in 1 blocks; 312 free (0 chunks); 712 used
    pg_ts_config_cfgname_index: 1024 total in 1 blocks; 312 free (0 chunks); 712 used
    pg_ts_parser_oid_index: 1024 total in 1 blocks; 448 free (0 chunks); 576 used
    pg_operator_oid_index: 1024 total in 1 blocks; 400 free (0 chunks); 624 used
    pg_namespace_nspname_index: 1024 total in 1 blocks; 448 free (0 chunks); 576 used
    pg_ts_template_oid_index: 1024 total in 1 blocks; 448 free (0 chunks); 576 used
    pg_amop_opr_fam_index: 3072 total in 2 blocks; 1976 free (0 chunks); 1096 used
    pg_default_acl_role_nsp_obj_index: 1024 total in 1 blocks; 16 free (0 chunks); 1008 used
    pg_collation_name_enc_nsp_index: 1024 total in 1 blocks; 16 free (0 chunks); 1008 used
    pg_range_rngtypid_index: 1024 total in 1 blocks; 448 free (0 chunks); 576 used
    pg_ts_dict_dictname_index: 1024 total in 1 blocks; 312 free (0 chunks); 712 used
    pg_type_typname_nsp_index: 1024 total in 1 blocks; 312 free (0 chunks); 712 used
    pg_opfamily_oid_index: 1024 total in 1 blocks; 448 free (0 chunks); 576 used
    pg_class_oid_index: 1024 total in 1 blocks; 400 free (0 chunks); 624 used
    pg_proc_proname_args_nsp_index: 1024 total in 1 blocks; 16 free (0 chunks); 1008 used
    pg_transform_type_lang_index: 1024 total in 1 blocks; 312 free (0 chunks); 712 used
    pg_attribute_relid_attnum_index: 1024 total in 1 blocks; 264 free (0 chunks); 760 used
    pg_proc_oid_index: 1024 total in 1 blocks; 448 free (0 chunks); 576 used
    pg_language_oid_index: 1024 total in 1 blocks; 448 free (0 chunks); 576 used
    pg_namespace_oid_index: 1024 total in 1 blocks; 448 free (0 chunks); 576 used
    pg_amproc_fam_proc_index: 3072 total in 2 blocks; 1976 free (0 chunks); 1096 used
    pg_foreign_server_name_index: 1024 total in 1 blocks; 448 free (0 chunks); 576 used
    pg_attribute_relid_attnam_index: 1024 total in 1 blocks; 312 free (0 chunks); 712 used
    pg_conversion_oid_index: 1024 total in 1 blocks; 448 free (0 chunks); 576 used
    pg_user_mapping_user_server_index: 1024 total in 1 blocks; 312 free (0 chunks); 712 used
    pg_extprotocol_oid_index: 1024 total in 1 blocks; 448 free (0 chunks); 576 used
    pg_conversion_name_nsp_index: 1024 total in 1 blocks; 312 free (0 chunks); 712 used
    pg_authid_oid_index: 1024 total in 1 blocks; 400 free (0 chunks); 624 used
    pg_auth_members_member_role_index: 1024 total in 1 blocks; 312 free (0 chunks); 712 used
    pg_tablespace_oid_index: 1024 total in 1 blocks; 448 free (0 chunks); 576 used
    pg_shseclabel_object_index: 1024 total in 1 blocks; 16 free (0 chunks); 1008 used
    pg_resgroup_rsgname_index: 1024 total in 1 blocks; 448 free (0 chunks); 576 used
    pg_replication_origin_roname_index: 1024 total in 1 blocks; 448 free (0 chunks); 576 used
    pg_database_datname_index: 1024 total in 1 blocks; 400 free (0 chunks); 624 used
    pg_replication_origin_roiident_index: 1024 total in 1 blocks; 448 free (0 chunks); 576 used
    pg_auth_members_role_member_index: 1024 total in 1 blocks; 312 free (0 chunks); 712 used
",,,,,,,,"SysLoggerMain","syslogger.c",691,
2020-10-30 11:20:48.171610 HKT,,,p14919,th1619134592,,,,0,,,seg10,,,,,"LOG","00000","3rd party error log:
    pg_database_oid_index: 1024 total in 1 blocks; 400 free (0 chunks); 624 used
    pg_authid_rolname_index: 1024 total in 1 blocks; 400 free (0 chunks); 624 used
    pg_resgroup_oid_index: 1024 total in 1 blocks; 448 free (0 chunks); 576 used
    pg_auth_time_constraint_authid_index: 1024 total in 1 blocks; 448 free (0 chunks); 576 used
  WAL record construction: 172608 total in 2 blocks; 6584 free (0 chunks); 166024 used
  GPORCA Top-level Memory Context: 0 total in 0 blocks; 0 free (0 chunks); 0 used
    GPORCA memory pool: 1040384 total in 7 blocks; 452736 free (8 chunks); 587648 used
    GPORCA memory pool: 8192 total in 1 blocks; 6712 free (0 chunks); 1480 used
    GPORCA memory pool: 8192 total in 1 blocks; 3400 free (0 chunks); 4792 used
    GPORCA memory pool: 0 total in 0 blocks; 0 free (0 chunks); 0 used
    GPORCA memory pool: 8192 total in 1 blocks; 8128 free (0 chunks); 64 used
    GPORCA memory pool: 106560 total in 2 blocks; 3816 free (0 chunks); 102744 used
    GPORCA memory pool: 32832 total in 2 blocks; 8008 free (0 chunks); 24824 used
    GPORCA memory pool: 0 total in 0 blocks; 0 free (0 chunks); 0 used
    GPORCA memory pool: 32832 total in 2 blocks; 7432 free (0 chunks); 25400 used
  PrivateRefCount: 8192 total in 1 blocks; 2840 free (0 chunks); 5352 used
  MdSmgr: 8192 total in 1 blocks; 8120 free (0 chunks); 72 used
",,,,,,,,"SysLoggerMain","syslogger.c",691,
2020-10-30 11:20:48.171813 HKT,,,p14919,th1619134592,,,,0,,,seg10,,,,,"LOG","00000","3rd party error log:
  LOCALLOCK hash: 8192 total in 1 blocks; 776 free (0 chunks); 7416 used
  Timezones: 104120 total in 2 blocks; 2840 free (0 chunks); 101280 used
  ErrorContext: 8192 total in 1 blocks; 8152 free (0 chunks); 40 used
Grand total: 2610344 bytes in 132 blocks; 852504 free (90 chunks); 1757840 used
",,,,,,,,"SysLoggerMain","syslogger.c",691,
`

**Comment by JunfengYang** [comment]
Adjust `gp_vmem_protect_limit` may helps, please refer to https://gpdb.docs.pivotal.io/6-12/best_practices/sysconfig.html#topic_dt3_fkv_r4__segment_mem_config.

The usage logs show the usage after the error, which already done the cleanup, so we can not know which part uses the most memory.

**Comment by zhongyibill** [comment]
I Adjust gp_vmem_protect_limit bigger will cause OS OOM error

**Comment by ashwinstar** [comment]
Not much to RCA based on what we have or know so far. This also seems to be run on very early cycle of gpdb7. Please try latest 6X_STABLE or master branch and if still facing similar issue report via fresh issue and we can try to knock it down.
