### ISSUE TITLE
gpactivatestandby promotion failed when old master host can not be connected

### ISSUE THREAD

**Issue by haitaoy** [greenplum-db/gpdb#11105]
### Greenplum version or build
6X_STABLE

### OS version and uname -a
4.9.168 x86_64 x86_64 GNU/Linux

tcp configuration:
net.ipv4.tcp_syn_retries = 6

Reproduce ：
At begining, one normal master and standby：
![image](https://user-images.githubusercontent.com/7891389/97979304-e0ccf700-1e09-11eb-9a9a-dd863b406015.png)

then shutdown the master host(shutdown -h now), and run gpactivatestandby at standby host:
![image](https://user-images.githubusercontent.com/7891389/97981798-cbf26280-1e0d-11eb-980b-afc391248aa9.png)

I try to find the cause, and recognize that after master host's shutdown the standby will launch new 'wal receiver process' about every 120 seconds(net.ipv4.tcp_syn_retries = 6), each process would be blocked for 120s and exit with error '(XX000) could not connect to the primary server: could not connect to server: Connection timed out' , the call stack:
![image](https://user-images.githubusercontent.com/7891389/97980412-b54b0c00-1e0b-11eb-9cbb-28899d438f1b.png)
in this state, the process will not response to SIGTERM signal.

In gpactivatestandby source codes:

> logger.debug('Waiting for connection...')
    for i in xrange(50):
        try:
            dburl = dbconn.DbURL()
            with dbconn.connect(dburl, utility=True, logConn=False) as conn:
                # When the new master is available for connections, we should
                # run a CHECKPOINT to force the new TimeLineID to be written to
                # the pg_control file.
                dbconn.execSQL(conn, 'CHECKPOINT')
            logger.info('Standby master is promoted')
            return True
        except pygresql.InternalError, e:
            pass
        time.sleep(1)
    return False

gpactivatestandby script revokes promotion and only waits about 50 seconds, it has probability of timeout to wait the walreceiver to exit, and fail with above error message.

**Comment by haitaoy** [comment]
May be we can decrease net.ipv4.tcp_syn_retries to 3, but the default waiting time in gpactivatestandby should be reconsidered.

**Comment by ashwinstar** [comment]
@pobbatihari would be good to look into and add to queue to fix

**Comment by pobbatihari** [comment]
> @pobbatihari would be good to look into and add to queue to fix

Sure @ashwinstar, Created a story for the same.

**Comment by Annu149** [comment]
Hi @haitaoy, 
the gpactivatestandby utility activates a backup, standby master host and brings it into operation as the active master instance for a Greenplum Database system. The activated standby master effectively becomes the Greenplum Database master, accepting client connections on the master port.

Since master and standby are running on different ports (59000,59001) in the above setup, when we run gpactivatestandby on standby host, it is expecting standby running with port as same as master port 59000. Hence utility is failing with above error. 

We can set the PGPORT to 59001 on the standby host, then we can run gpactivatestandby on standby host which can run successfully.

**Comment by ashwinstar** [comment]
I think the main aspect user is complaining about here is the timeout script waits for activation of the standby (not much about PORT or not able to activate the standby)

> gpactivatestandby script revokes promotion and only waits about 50 seconds, it has probability of timeout to wait the walreceiver to exit, and fail with above error message.

Seems given the behavior explained where walreceiver process can take longer to shut-down, promotion can take longer than 50 secs. Hence, the user is asking if we can have the timeout greater than at least 120s which seems to the time walreceiver can be blocked for before acting on promotion request. (We also on the server side need to check why walreceiver takes this long time and possibly reduce that, though having higher timeout doesn't seem to do any harm for the script)

**Comment by ashwinstar** [comment]
@Annu149 as we had discussed please make the timeout value for standby promotion aligned with `MIRROR_PROMOTION_TIMEOUT` value. Done this on master branch via my refactor commit 1fe901d4bb9b141fd6931977eb93515982ac6edd. Please make the timeout value change for 6X_STABLE and that way we can bring closure to this issue.

**Comment by dpandhi-git** [comment]
Closing as 6x PR is merged
