### ISSUE TITLE
Vacuum analyse throw 'relation xxxx page 131022 is uninitialized --- fixing'

### ISSUE THREAD

**Issue by cobolbaby** [greenplum-db/gpdb#11119]
### Greenplum version or build

- GP 5.28.1

### OS version and uname -a

- Docker Container: Centos7
- Docker Host: Linux mdw 4.15.0-117-generic #118-Ubuntu SMP Fri Sep 4 20:02:41 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

### Expected behavior

When I executed this command last time, I encountered the exception that I had never seen before, as shown below. 
What is the possible root cause of the following abnormality?

```
WARNING:  relation "xxxx" page 131022 is uninitialized --- fixing  (seg7 10.12.0.32:40003 pid=48123)
WARNING:  relation "xxxx" page 131023 is uninitialized --- fixing  (seg7 10.12.0.32:40003 pid=48123)
...
```

**Comment by ashwinstar** [comment]
Based on this [upstream thread](https://www.postgresql.org/message-id/flat/47EF6161.7030201%40kaltenbrunner.cc#655bfa2ed98130065cf446f5599c49a4) its clear there are situations where this can happen and its not a problematic situation. Tom Lane in detail explains the scenarios this can happen. Nothing to fix and worry for this. Closing the issue.
