### ISSUE TITLE
No gp_toolkit.* in template0

### ISSUE THREAD

**Issue by phoccer** [greenplum-db/gpdb#1112]
It's possible that someone could muck up their template1 database. It can happen to the best, https://wiki.postgresql.org/wiki/Adventures_in_PostgreSQL,_Episode_1. That article mentions how you can go about recreating a pristine template1 from template0. That solution doesn't work in Greenplum.

You cannot make template0 connectable 

If I try to follow the instructions in the wiki article above I receive this error message when using Greenplum, gpadmin@mdw:5432 <X>UPDATE pg_database SET datallowconn = TRUE WHERE datname = 'template0';
ERROR:  permission denied: "pg_database" is a system catalog

If you muck up template1, you cannot use template0 as your TEMPLATE because gp_toolkit.\* is missing in template0. The name is there but there’s nothing in the schema.

If I try to create a database using template0, you can see that gp_tookit.\* is empty. I've included creating a database using template1 to show the difference.
gpadmin@mdw:5432 <X>CREATE DATABASE testdbtrm WITH TEMPLATE = template0 ENCODING = 'UTF8';
CREATE DATABASE
Time: 16128.218 ms

gpadmin@mdw:5432 <X>\connect testdbtrm
SSL connection (cipher: DHE-RSA-AES256-SHA, bits: 256)
You are now connected to database "testdbtrm" as user "gpadmin".

gpadmin@mdw:5432 <X>\dn
       List of schemas
        Name        |  Owner  
--------------------+---------
 gp_toolkit         | gpadmin
 information_schema | gpadmin
 pg_aoseg           | gpadmin
 pg_bitmapindex     | gpadmin
 pg_catalog         | gpadmin
 pg_toast           | gpadmin
 public             | gpadmin
(7 rows)

gpadmin@mdw:5432 <X>\d gp_toolkit.*
Did not find any relation named "gp_toolkit.*".

gpadmin@mdw:5432 <X>CREATE DATABASE testdb2trm WITH TEMPLATE = template1 ENCODING = 'UTF8';
CREATE DATABASE
Time: 14721.905 ms

gpadmin@mdw:5432 <X>\connect testdb2trm
SSL connection (cipher: DHE-RSA-AES256-SHA, bits: 256)
You are now connected to database "testdb2trm" as user "gpadmin".

gpadmin@mdw:5432 <X>\dn
       List of schemas
        Name        |  Owner  
--------------------+---------
 gp_toolkit         | gpadmin
 information_schema | gpadmin
 pg_aoseg           | gpadmin
 pg_bitmapindex     | gpadmin
 pg_catalog         | gpadmin
 pg_toast           | gpadmin
 public             | gpadmin
(7 rows)

gpadmin@mdw:5432 <X>\d gp_toolkit.*
Composite type "gp_toolkit.__gp_aovisimap_hidden_t"
 Column |  Type  
--------+---------
 seg    | integer
 hidden | bigint
 total  | bigint

View "gp_toolkit.__gp_fullname"
  Column   | Type | Modifiers 
-----------+------+-----------
 fnoid     | oid  | 
 fnnspname | name | 
 fnrelname | name | 
View definition:
 SELECT pgc.oid AS fnoid, pgn.nspname AS fnnspname, pgc.relname AS fnrelname
   FROM pg_class pgc, pg_namespace pgn
  WHERE pgc.relnamespace = pgn.oid;

View "gp_toolkit.__gp_is_append_only"
 Column  |  Type   | Modifiers 
---------+---------+-----------
 iaooid  | oid     | 
 iaotype | boolean | 
View definition:
 SELECT pgc.oid AS iaooid, 
        CASE
            WHEN pgao.relid IS NULL THEN false
            ELSE true
        END AS iaotype
   FROM pg_class pgc
   LEFT JOIN pg_appendonly pgao ON pgc.oid = pgao.relid;

External table "gp_toolkit.__gp_localid"
 Column  |  Type   | Modifiers 
---------+---------+-----------
 localid | integer | 
Type: readable
Encoding: UTF8
Format type: text
Format options: delimiter ' ' null '\N' escape '\'
Command: echo $GP_SEGMENT_ID
Execute on: all segments
…

**Comment by deepesh1081** [comment]
you should be able to recreate the gptoolkit objects using this file sql 👍 https://github.com/greenplum-db/gpdb/blob/2ba36ba6cae0dd0205cd38ec3ca393fcf6577b49/src/test/regress/sql/gp_toolkit.sql

**Comment by phoccer** [comment]
That doesn't recreate gp_toolkit.* objects. I'm referring to a situation where you need to use template0 or maybe you've completely messed up template1 and can't access gp_toolkit objects. You'll notice in that file line 28 selects from gp_toolkit.__gp_is_append_only but I'm looking at a situation where you don't have those gp_toolkit.* objects in template1. That file assumes gp_toolkit and it's objects already exist.

**Comment by phoccer** [comment]
What I've done for now is to keep a dump of the gp_toolkit schema in a local git repo just in case it should ever need to be recreated.

**Comment by asimrp** [comment]
@phoccer the correct path to gp_toolkit.sql is `src/backend/catalog/gp_toolkit.sql`.

**Comment by jimmyyih** [comment]
You can also find it in your installation:
`find $GPHOME -name gp_toolkit.sql`

**Comment by phoccer** [comment]
Awesome! Thank you @asimrp and @jimmyyih . So now I, and everyone, know where to find that. I guess I still have my original question of whether this should be loaded into template0 by default. I guess I'm simply looking at it in terms of how PostgreSQL handles things but maybe I shouldn't look at the situation that way.

**Comment by hlinnaka** [comment]
gp_toolkit *is* installed in template0. At least in current git master. Perhaps you were testing with an earlier version?

I'll mark this as closed...
