### ISSUE TITLE
Orca: broken estimation for selectivity of selection with equality predicate on date type key with scalar outside MCV

### ISSUE THREAD

**Issue by maksm90** [greenplum-db/gpdb#11169]
Hello everyone!

The commit 9b427611 had introduced the change in calculating of frequency value for singleton bucket derived from some not singleton one:
```C
@@ -434,12 +446,16 @@ CBucket::MakeBucketSingleton
     GPOS_ASSERT(point_singleton);
     GPOS_ASSERT(this->Contains(point_singleton));
 
-    // assume that this point is one of the ndistinct values
-    // in the bucket
-    CDouble distinct_ratio = CDouble(1.0) / this->m_distinct;
+    CDouble frequency_new = m_frequency;
+    CDouble distinct_new = m_distinct;
 
-    CDouble frequency_new = std::min(DOUBLE(1.0), (this->m_frequency * distinct_ratio).Get());
-    CDouble distinct_new = CDouble(1.0);
+    // if the bucket is not already singleton, scale accordingly
+    if (!this->IsSingleton())
+    {
+        CDouble ratio = CDouble(1.0) / m_bucket_upper_bound->Width(m_bucket_lower_bound, m_is_lower_closed,  m_is_upper_closed);
+        frequency_new = std::min(DOUBLE(1.0), (this->m_frequency * ratio).Get());;
+        distinct_new = CDouble(1.0);
+    }
```
In particular, instead of division of parent bucket frequency on NDV (multiply on distinct_ratio) the current implementation divides the first one by width of parent bucket. This width value for types that map to double floats might be very large as well as very small. For date type whose values are represented in the X axis of histogram as the number of **microseconds** starting from `2000-01-01` such width calculation between adjacent values (with 1 day interval) would lead to enormous value `86.4 * 10^9`. As result we get very small frequency for singleton bucket of single equality histogram and hence very small selectivity of equality condition that forces to assigns one row to selection node.

I propose to revert calculating of frequency to old formula via NDV value. But I afraid that this could break the main commit about union commutativity of histograms. @ashuka24 @zellerh could you take a look at this issue and approve or deny my proposition or suggest smth else?

### Greenplum version or build

master and 6X

### Step to reproduce the behavior

```sql
# create simple table with date type
create table test(d date);

# fill in some data so that cardinality of column would be small: 10^3 NDVs from 10^6 total amount of rows
insert into test select '2018-01-01'::date + make_interval(days := (i%1000)) from generate_series(0, 1000000) i;

# reduce statistics target to not clutter output from pg_stats
set default_statistics_target to 10;

# analyze to gather statistics
analyze test;

# check MCV in pg_statistics
select * from pg_stats where tablename = 'test' and attname = 'd' \gx
-[ RECORD 1 ]----------+---------------------------------------------------------------------------------------------------------------------------
schemaname             | public
tablename              | test
attname                | d
inherited              | f
null_frac              | 0
avg_width              | 4
n_distinct             | 984
most_common_vals       | {2019-05-08,2019-07-28,2020-05-01,2018-04-22,2018-07-26,2018-09-06,2018-10-25,2019-02-03,2019-07-01,2019-09-03}
most_common_freqs      | {0.00333333,0.003,0.003,0.00266667,0.00266667,0.00266667,0.00266667,0.00266667,0.00266667,0.00266667}
histogram_bounds       | {2018-01-01,2018-04-19,2018-07-29,2018-11-14,2019-02-20,2019-06-03,2019-09-12,2019-12-09,2020-03-14,2020-06-17,2020-09-26}
correlation            | -0.0115569
most_common_elems      | (null)
most_common_elem_freqs | (null)
elem_count_histogram   | (null)

# check the number of rows for scalar from MCV in equality predicate; real returned number is 10^3
explain select * from test where d = '2019-05-08';
                                   QUERY PLAN                                    
---------------------------------------------------------------------------------
 Gather Motion 1:1  (slice1; segments: 1)  (cost=0.00..482.72 rows=3334 width=4)
   ->  Seq Scan on test  (cost=0.00..482.62 rows=3334 width=4)
         Filter: (d = '2019-05-08'::date)

# check the number of rows for scalar outside MCV;  real returned number is 10^3
explain select * from test where d = '2019-05-09';
                                  QUERY PLAN                                  
------------------------------------------------------------------------------
 Gather Motion 1:1  (slice1; segments: 1)  (cost=0.00..482.60 rows=1 width=4)
   ->  Seq Scan on test  (cost=0.00..482.60 rows=**1** width=4)
         Filter: (d = '2019-05-09'::date)
```

### Expected behavior

The number of returned rows from Seq Scan on test after applying filter has to be smth around 1000

### Actual behavior

Real number is 1 - the [minimal dummy value](https://github.com/greenplum-db/gpdb/blob/6.12.0/src/backend/gporca/libnaucrates/src/statistics/CFilterStatsProcessor.cpp#L237).

P.S. while debugging of backend execution I struggled to output to log the internal representation of gporca objects (like CHistogram, CBucket, etc.) via `DbgPrint()` call. Could anybody direct me how to see in main log of server the debug output from `DbgPrint()` call or it should be expected somewhere else?

**Comment by zellerh** [comment]
Hi Maksim,

Thanks for bringing up this issue. I agree with you that we should improve how we handle the simple test case you provided.

As far as I remember, there are several underlying questions here that we might want to think about:


  *   What’s the difference in width between the intervals [a, b] and [a, b) when the boundaries map to doubles?
  *   How should we assign frequencies and NDVs when we split interval [a, b] into two intervals [a, b) and [b, b]?
  *   Is it realistic to have asserts in the code that check whether frequencies of buckets add up to 1.0 after splitting and combining some of them?
  *   Should we map a ‘date’ value to a double or would it be better to map it to an integer number of days?

As far as I can see, there is no clear and really satisfying answer to the first three questions. This makes me wish that we could avoid these three issues altogether and map dates to an integer count of days. Others may have more background, as far I’ve been told people have tried this before and probably rejected the idea for some good reason.

Your approach seems like a good solution if we want to stick with double mappings, but it might require looking into some asserts. I frequently also run into these asserts when I use minirepros. Not sure whether that’s a problem with the way the minirepro is collected.

Thanks,

Hans

**Comment by chrishajas** [comment]
>As far as I can see, there is no clear and really satisfying answer to the first three questions. This makes me wish that we could avoid these three issues altogether and map dates to an integer count of days. Others may have more background, as far I’ve been told people have tried this before and probably rejected the idea for some good reason.

Did a bit of archeology, pre-2014 it was stored as a LINT. However, postgres has a built in conversion for timestamp to double (convert_timevalue_to_scalar). This possibly was done since time has similar precision issues as a double, but that's speculation.

>P.S. while debugging of backend execution I struggled to output to log the internal representation of gporca objects (like CHistogram, CBucket, etc.) via DbgPrint() call. Could anybody direct me how to see in main log of server the debug output from DbgPrint() call or it should be expected somewhere else?

While DbgPrint works in a debugger if you're running an mdp within Orca, it doesn't work if you connect to the database backend currently. @d is hacking on a PR to enable this I believe https://github.com/greenplum-db/gpdb/pull/11102.

**Comment by maksm90** [comment]
@zellerh , @chrishajas thanks for so fast replies.

>   *   What’s the difference in width between the intervals [a, b] and [a, b) when the boundaries map to doubles?
>  *   How should we assign frequencies and NDVs when we split interval [a, b] into two intervals [a, b) and [b, b]?

I could assume that for double range its width have to be calculated as the number of discrete unique values inside that range but such calculation is tricky to perform. Then the frequencies and NDVs of singleton bucket [b, b] and adjacent range [a, b) would be calculated as:
```
point_ndv = initial_range_ndv / width
point_freq = initial_range_freq / width
other_range_ndv = initial_range_ndv - point_ndv
other_range_freq = initial_range_freq - point_freq
```
By now I see inconsistency in computing of NDV and frequency for singleton bucket:
*  for double type values the width of range bucket is defined as [difference between range bounds](https://github.com/greenplum-db/gpdb/blob/6.12.1/src/backend/gporca/libnaucrates/src/base/IDatum.cpp#L158-L162), as result we could get point the frequency value of which is larger than that one at range inclosing this point if width of inclosing bucket (as arithmetic difference between bounds) is less than one. IMO this is absurd result 
* the NDV for singleton bucket [is assigned to 1.0](https://github.com/greenplum-db/gpdb/blob/6.12.1/src/backend/gporca/libnaucrates/src/statistics/CBucket.cpp#L424) that is assumed that the point value of this singleton bucket have to appear in some record of incoming relation. But the formula for frequency of singleton bucket (division frequency of a whole inclosing bucket by bucket width) implies that the point value is some random one inside the range of bucket - it could correspond to some distinct value of attribute in relation or not. I think in this case the correct formula for NDV of singleton bucket is NDV of bucket divided by width of bucket (in terms of the distinct values defined by type inside the bucket range). This formula in fact computes the probability that the point of singleton bucket is in the set of distinct values of target attribute appearing in relation.

What's your thoughts about the notes above?

Vanilla PostgreSQL calculates single point frequency with assumption that the value appears in relation as:
```
selectivity = (1 - sum(mvf) - null_freq)/(num_distinct - num_mcv)
```
Based on same assumption the frequencies and NDVs of [a, b) and [b,b] intervals would be following:
```
point_ndv = 1.0
point_freq = initial_range_freq / initial_range_ndv
other_range_ndv = initial_range_ndv - 1
other_range_freq = initial_range_freq - point_freq
```
I cannot conclude which variant of NDV and frequency calculation is better for the ORCA case where there are several transformations for histogram buckets (merging, union, intersection, point assignment as singleton bucket, etc.)

> As far as I can see, there is no clear and really satisfying answer to the first three questions. This makes me wish that we could avoid these three issues altogether and map dates to an integer count of days. Others may have more background, as far I’ve been told people have tried this before and probably rejected the idea for some good reason.

AFAIC the most appropriate and least problematic solution here is to specify exceptional logic for date value to map it to intrinsic representation as the number of days starting from 2000-01-01. But I'm confused how much it could break comparison of date type attribute with other time related type values?

> While DbgPrint works in a debugger if you're running an mdp within Orca, it doesn't work if you connect to the database backend currently. @d is hacking on a PR to enable this I believe #11102.

Thanks a lot for the note. By now I get message emitted from `DbgPrint()` call via breakpoint setup inside some internal place of `CAutoTrace` destructor.

**Comment by zellerh** [comment]
Hi Maksim,


I could assume that for double range its width have to be calculated as the number of discrete unique values inside that range but such calculation is tricky to perform. Then the frequencies and NDVs of singleton bucket [b, b] and adjacent range [a, b) would be calculated as:

point_ndv = initial_range_ndv / width



point_freq = initial_range_freq / width



other_range_ndv = initial_range_ndv - point_ndv



other_range_freq = initial_range_freq - point_freq

That might be a good solution if width >> 1, but what happens if that’s not the case? It won’t work for width < 1, correct?

Based on same assumption the frequencies and NDVs of [a, b) and [b,b] intervals would be following:

point_ndv = 1.0



point_freq = initial_range_freq / initial_range_ndv



other_range_ndv = initial_range_ndv - 1



other_range_freq = initial_range_freq - point_freq

This formula should be ok for initial_range_ndv >> 1, but again we could get into trouble when that’s not the case. Still, I prefer it over the formula above, since the width is a very arbitrary thing while NDVs are not. It reminds me of a similar assumption made for join cardinalities, see this comment in the code:

     // Based on Ramakrishnan and Gehrke, "Database Management Systems, Third Ed", page 484
     // the cardinality of an equality join is the product of the base table cardinalities
     // divided by the MAX of the number of distinct values in each of the inputs

The shared idea in both of these is that when a particular value v appears in one table of a join, it is likely that the same value v also appears in the other table of the join.

As you said, there is no way to make this perfect, but I would hope that your proposal (second set of formulas above) would be worth a try. We probably also agree that mapping dates to LINTs should improve things, but that might take some more investigation.

Thanks,

Hans

**Comment by maksm90** [comment]
Hi, @zellerh , thanks for your response. Sorry for so delayed answer of me, I prepared patch for mapping dates to LINTs.

>> I could assume that for double range its width have to be calculated as the number of discrete unique values inside that range but such calculation is tricky to perform. Then the frequencies and NDVs of singleton bucket [b, b] and adjacent range [a, b) would be calculated as: point_ndv = initial_range_ndv / width point_freq = initial_range_freq / width other_range_ndv = initial_range_ndv - point_ndv other_range_freq = initial_range_freq - point_freq

> That might be a good solution if width >> 1, but what happens if that’s not the case? It won’t work for width < 1, correct?

By `number of discrete unique values inside that range` I mean the number of all points inside double range the counting of which requires decomposition of range bounds into mantissa and exponential part. In fact, this assumes extrapolation of doubles to integers where calculation of width has no any problem. Therefore, width would never be less than 1. But this method of calculation also cannot be satisfying for types that map its values to some small subset of doubles as it's done for date type and other time related types that are represented as microseconds without fractional part.


>> Based on same assumption the frequencies and NDVs of [a, b) and [b,b] intervals would be following: point_ndv = 1.0 point_freq = initial_range_freq / initial_range_ndv other_range_ndv = initial_range_ndv - 1 other_range_freq = initial_range_freq - point_freq 

> This formula should be ok for initial_range_ndv >> 1, but again we could get into trouble when that’s not the case.

Yeah, this kind of computation might lead to not consistent in common sense results. For example, frequency and NDV for the point might be more than for the range enclosing this point in some bucket if `range_width / enclosing_bucket_width < 1 / enclosing_bucket_ndv`.

> We probably also agree that mapping dates to LINTs should improve things, but that might take some more investigation.

I had checked the case of equality between date type attribute with other time related type argument in WHERE and JOIN predicate and found out that GPORCA doesn’t support estimation statistics for arguments with different time-related types marking their as [not comparable](https://github.com/greenplum-db/gpdb/blob/6.12.1/src/backend/gporca/libnaucrates/src/base/IDatum.cpp#L205-L214) (CStatsPredUtils::GetPredStats → IMDType::StatsAreComparable → IDatum::StatsAreComparable sequence of calls). Instead it assigns to such predicates the [dummy selectivity value](https://github.com/greenplum-db/gpdb/blob/6.12.1/src/backend/gporca/libnaucrates/src/statistics/CStatsPredUnsupported.cpp#L32) (40%). This opportunity was incorporated in commit https://github.com/greenplum-db/gpdb/commit/8383593168abb9084ee9c1da07ab5fb6a40ce639.  As a consequence, any cardinality estimations for nodes in which similar equality predicates take place (in where or join condition) doesn’t depend on distribution of participating in there attribute values. And our change in internal representation of date values (from double value of number of microseconds to integer one of number of days) doesn't sacrifice accuracy of selectivity estimation for predicates with date type attribute and other time-related argument.

But PostgreSQL optimizer in its turn fluently compares arguments with different time-related types at planner stage. The `convert_timevalue_to_scalar` routine is intended to unify values of these types and to compare their in the context of histograms manipulations. Therefore, IMO the restriction in comparison of time related types inside ORCA is temporary and it might be eliminated in future. But in this case mapping dates to the numbers of days from 2000-01-01 would distinguish the date type and leave it not comparable with other time related types.

**Comment by ashwinstar** [comment]
@maksm90 please can you confirm and yes please feel free to close this issue,  if this was fixed fully via PR https://github.com/greenplum-db/gpdb/pull/11349 (for master and 6X_STABLE via https://github.com/greenplum-db/gpdb/pull/11515

**Comment by maksm90** [comment]
> @maksm90 please can you confirm and yes please feel free to close this issue, if this was fixed fully via PR https://github.com/greenplum-db/gpdb/pull/11349 (for master and 6X_STABLE via https://github.com/greenplum-db/gpdb/pull/11515

The issue was fully resolved. Close it
