### ISSUE TITLE
external table json type can not load  \" key

### ISSUE THREAD

**Issue by chenbaggio** [greenplum-db/gpdb#11179]
### Greenplum version or build

6.x.stabled 

### OS version and uname -a

Linux vagrant.hashdata.vm 3.10.0-327.el7.x86_64 #1 SMP Thu Nov 19 22:10:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

### Expected behavior

after create external table with json type column ,then load the file content like : `{"\"customer\"": "\"Lily Bush\""}`, as expected, it should be loaded in , but in factor,  it can not load and report error 

```
DETAIL:  Token "customer" is invalid.
CONTEXT:  JSON data, line 1: {""customer...
```

### Actual behavior

report error

```
DETAIL:  Token "customer" is invalid.
CONTEXT:  JSON data, line 1: {""customer...
```

### Step to reproduce the behavior

1. create external table 

```
create external table test_ext (a json) LOCATION ('file://vagrant.hashdata.vm/tmp/test_ext.dat') FORMAT 'TEXT'(ESCAPE '\');

```
2. write file `file://vagrant.hashdata.vm/tmp/test_ext.dat`

write the content `{"\"customer\"": "\"Lily Bush\""}`

3. select * from test_ext;

tips: insert is ok

```
CREATE TABLE orders (
id serial NOT NULL PRIMARY KEY,
info json NOT NULL
);

INSERT INTO orders (info) values('{"\"customer\"": "Lily Bush"}');

```

not report any error, and json column can be parsed correctly

**Comment by chenbaggio** [comment]
Any body could answer the issue? it is urgently, thank you!!!

**Comment by asimrp** [comment]
@chenbaggio I don't think you need to escape the quotes.  I was able to successfully select from the external table by changing `test_ext.dat` to the following:
```
{"customer": "Lily Bush"}
```
With that, the select succeeded:
```SQL
select * from test_ext;
             a
---------------------------
 {"customer": "Lily Bush"}
(1 row)
```

**Comment by asimrp** [comment]
And if you want the quotes, use two `\`s to escape.  Change the `test_ext.dat` to:
```
{"\\"customer\\"": "\\"Lily Bush\\""}
```
And you get:
```SQL
select * from test_ext;
                 a
-----------------------------------
 {"\"customer\"": "\"Lily Bush\""}
(1 row)
```
