### ISSUE TITLE
ERROR: type "xxx" already exists

### ISSUE THREAD

**Issue by eric0225** [greenplum-db/gpdb#11188]
GPDB 版本:6.4.0
GPCC 版本:6.1.0
xxx表是分区表，并且有xxx_id_seq为自增序列
将xxx表重命名为xxx1
alter table xxx rename to xxx1;
重建xxx表
create table xxx(id int4,name text) distributed by (id);
提示报错
ERROR: type "xxx" already exists
HINT: A relation has an associated type of the same name, so you must use a name that doesn't conflict with any existing type.
查询了所有
select * from pg_class where relname = 'xxx';
select * from pg_tables where tablename = 'xxx';
select * from pg_type where typname = 'xxx';
都不存记录，直接查询select * from xxx ;提示表不存在
但是直接drop type xxx；提示
ERROR: cannot drop type xxx1 because table xxx1 requires it
HINT: You can drop table xxx1 instead.
并且目前drop表也报错
drop table xxx1
ERROR: cache lookup failed for type 9081508 (format_type.c:135)

**Comment by kainwen** [comment]
This issue is not well formed. Also, per some offline discussion, the reason might be pg_type's index is not shown in `\d+ pg_type`, which is duplicated to the issue https://github.com/greenplum-db/gpdb/issues/11207

So close this.
