### ISSUE TITLE
initdb failed doesn't show detailed error messages

### ISSUE THREAD

**Issue by dreamedcheng** [greenplum-db/gpdb#11201]
### Greenplum version or build
master branch

### OS version and uname -a
centos 7

### Actual behavior
When installing a demo cluster with some errors, the gpinitsystem.log didn't show detailed messages as 6X does, which makes us hard to find the cause of the failure.

The first screen shot is output of master branch when installing a demo cluster, while the second comes from 6X.
![image](https://user-images.githubusercontent.com/7367189/99959613-49cedb80-2dc6-11eb-9e70-50390d9766be.png)

![image](https://user-images.githubusercontent.com/7367189/99959730-7c78d400-2dc6-11eb-8a78-9c8e49a3ecb5.png)

**Comment by dreamedcheng** [comment]
I noticed that commit [f37acd85111acd21e4bbb1e1c01317ddacd0261b](https://github.com/greenplum-db/gpdb/commit/f37acd85111acd21e4bbb1e1c01317ddacd0261b) remove the backend output redirection for safety problems. 

I think detailed error messages is very useful for us to locate the cause of the problem. To avoid the safety issues, maybe we can replace the original backend_output parameter with a fixed value `$pg_data.initdb`. Correct me if I am wrong, thanks!

**Comment by ashwinstar** [comment]
@dreamedcheng seems right, I agree its useful functionality to have. Possibly lets start with proposing the same to PostgreSQL list and then can be absorbed in Greenplum once makes to PostgreSQL.

**Comment by dreamedcheng** [comment]
Sounds good! BTW, does PostgreSQL have a plan for this?

**Comment by ashwinstar** [comment]
> Sounds good! BTW, does PostgreSQL have a plan for this?

We will know once you submit the proposal to PostgreSQL :-)
