### ISSUE TITLE
pg_type return anomalous

### ISSUE THREAD

**Issue by eric0225** [greenplum-db/gpdb#11218]
GPDB version:6.4.0
GPCC version:6.1.0
when I query the type “ods_sc_twitter_people_incre” from pg_type，but it return the other one ；
just like this: 
alter table ods_sc_twitter_people_incre rename to ods_sc_twitter_people_incre _y;

![image](https://user-images.githubusercontent.com/71756944/100297366-7d2d8800-2fc9-11eb-9ee2-8ae08bd7298c.png)

but when I changed then environment variable ,it can't be queried；
 set enable_indexscan = off;
set enable_bitmapscan = off;
![image](https://user-images.githubusercontent.com/71756944/100297604-00e77480-2fca-11eb-95f1-e8bf54ce9425.png)

Why is there such a situation?

**Comment by asimrp** [comment]
@eric0225 that is an indication of some problem with catalog.  Do you want to try running `gpcheckcat` on `postgres` database?
```
gpcheckcat --help
gpcheckcat postgres
```
The `amcheck` extension would be helpful to determine btree index problem.

```SQL
create extension amcheck;
select * from bt_index_check('pg_type_typname_nsp_index'::regclass);
select * from bt_index_parent_check('pg_type_typname_nsp_index'::regclass);
```

**Comment by ashwinstar** [comment]
No further information provided on the error to help, hence closing this issue.
