### ISSUE TITLE
Launch S3 file accessing QE gang with random IDs to avoid compute skew among hosts

### ISSUE THREAD

**Issue by phan-pivotal** [greenplum-db/gpdb#11216]
### Greenplum version or build
V6.12.0
### OS version and uname -a
V7.8
### Expected behavior
Launch a S3 file accessing QE gang with random IDs
### Actual behavior
Launch a S3 file accessing QE gang with ranked IDs from 0 to N
### Step to reproduce the behavior
1. deploy a  GP cluster with 4 QE across 2 hosts (host1 and host2), with 2 QE on each host.

2. deploy a minio S3 in docker on IP 192.168.0.1 with port 9000.
docker pull minio/minio

3. upload two csv files to minio path "/gp_ext/t1"

4. 
CREATE READABLE EXTERNAL TABLE public.gp_ext_t1 (name vachar(64),description text)
LOCATION ('s3://192.168.0.1:9000/gp_ext/t1') 
FORMAT 'csv';

5、 explain analyze select * from public.gp_ext_t1;

6、 execute "netstat -anlp|grep minioIP" with gpssh

We will find that all minio access connections launched from host1, while host2 is idle in the S3 file access slice.
No matter with "set optimizer = on / off".

**Comment by phan-pivotal** [comment]
A CLI screen snapshot in a 4 hosts environment.

![image](https://user-images.githubusercontent.com/8972547/100190754-e362ce00-2f29-11eb-9e7f-7ce0e34f84d3.png)

**Comment by adam8157** [comment]
s02 is not idle as I see from the screenshot, the first two QEs work because there are only two CSV files with the prefix "/gp_ext/t1".
