### ISSUE TITLE
Data is written on wrong segment in partitoned tables with different partition distribution

### ISSUE THREAD

**Issue by kapustor** [greenplum-db/gpdb#11222]
### Greenplum version or build
6.11.2 
### OS version and uname -a
NA
### autoconf options used ( config.status --config )
NA
### Installation information ( pg_config )
NA
### Expected behavior
When changing distribution of one of partitions in partitioned table to randomly, data that corresponds to this partition must be written with random distribution
### Actual behavior
When changing distribution of one of partitions in partitioned table to randomly, data that corresponds to this partition is written according to global table distribution

### Step to reproduce the behavior

Making one of partitions distributed randomly is very useful functionality, especially when we have nulls in distribution key:

**CREATE TABLE tab1 (id int, year int)
DISTRIBUTED BY (id)
PARTITION BY range (id)
(start (0) end (10000000) every (10000000),
default partition nulls);**

	NOTICE:  CREATE TABLE will create partition "tab1_1_prt_nulls" for table "tab1"
	NOTICE:  CREATE TABLE will create partition "tab1_1_prt_2" for table "tab1"
	CREATE TABLE

**alter table tab1 alter partition nulls set distributed randomly;**

	NOTICE:  altering table "tab1_1_prt_nulls" (partition "nulls" of relation "tab1")
	ALTER TABLE

**insert into tab1 select gen,gen from generate_series(1,1000) gen;**

	INSERT 0 1000

**select gp_segment_id,count(1) from tab1 group by gp_segment_id;**

	gp_segment_id | count
	---------------+-------
				2 |   252
				0 |   257
				1 |   251
				3 |   240
	(4 rows)

**truncate tab1;**

	TRUNCATE TABLE
	
**insert into tab1 select null,gen from generate_series(1,1000) gen;**

	INSERT 0 1000
	
**select gp_segment_id,count(1) from tab1 group by gp_segment_id;**

	 gp_segment_id | count
	---------------+-------
				 0 |  1000
	(1 row)

**alter table tab1 set with (reorganize=true);**

	ALTER TABLE
	
**select gp_segment_id,count(1) from tab1 group by gp_segment_id;**

	 gp_segment_id | count
	---------------+-------
				 2 |   220
				 0 |   266
				 1 |   275
				 3 |   239
	(4 rows)

**Comment by JunfengYang** [comment]
Actually, we don't allow the leaf partition table to have a different distribution policy from the root one.

```
demo=# CREATE TABLE tab1 (id int, year int)                                                                                                                                                                                           DISTRIBUTED BY (id)                                                                                                                                                                                                                   PARTITION BY range (id)                                                                                                                                                                                                               (start (0) end (10000000) every (10000000),                                                                                                                                                                                           default partition nulls);
NOTICE:  CREATE TABLE will create partition "tab1_1_prt_nulls" for table "tab1"
NOTICE:  CREATE TABLE will create partition "tab1_1_prt_2" for table "tab1"
CREATE TABLE
demo=# \d+ tab1
                         Table "public.tab1"
 Column |  Type   | Modifiers | Storage | Stats target | Description
--------+---------+-----------+---------+--------------+-------------
 id     | integer |           | plain   |              |
 year   | integer |           | plain   |              |
Child tables: tab1_1_prt_2,
              tab1_1_prt_nulls
Distributed by: (id)
Partition by: (id)

demo=# create table x (a int, b int) distributed randomly;
CREATE TABLE
demo=# alter table tab1 exchange partition for (1) with table x;
ERROR:  relation "x" must have the same column names and column order as "tab1"
```

And on the master branch, we already forbid to alter the leaf partition table's distribution policy.
```
demo=# CREATE TABLE tab1 (id int, year int)
demo-# DISTRIBUTED BY (id)
demo-# PARTITION BY range (id)
demo-# (start (0) end (10000000) every (10000000),
demo(# default partition nulls);
CREATE TABLE
demo=# alter table tab1 alter partition nulls set distributed randomly;
psql: ERROR:  can't set the distribution policy of "tab1_1_prt_nulls"
HINT:  Distribution policy can be set for an entire partitioned table, not for one of its leaf parts or an interior branch.
```
See the related issue: https://github.com/greenplum-db/gpdb/issues/6475.

Seems the fix not backport to 6X. @gaos1 Do we need to backport the fix to 6X?

**Comment by kainwen** [comment]
@wuj21

**Comment by ashwinstar** [comment]
well "wrong segment" word usage seems too heavy for this github issue :-) Inserts via root partition will be redirected using root's distribution policy and not really look into individual children (it doesn't matter if the child is randomly distributed or not). If really wish to control the behavior to randomly distribute for a child, then the only option is to directly perform inserts to the child table. In general, it's discouraged to have different distribution policies between root and child (like apart from a child being randomly no other option is allowed). Hence, don't see this as something we are planning to change in the near term future and hence closing this github issue.
