### ISSUE TITLE
Could not execute a simple test program.

### ISSUE THREAD

**Issue by darionyaphet** [greenplum-db/gpdb#11220]
### Greenplum version or build
gpdb-6.12.1

### OS version and uname -a

Linux 3.10.0-1127.19.1.el7.x86_64

### Actual behavior

```
checking for rl_filename_completion_function... yes
checking for rl_reset_screen_size... yes
checking for append_history... yes
checking for history_truncate_file... yes
checking test program... failed
configure: error:
Could not execute a simple test program.  This may be a problem
related to locating shared libraries.  Check the file 'config.log'
```

### Step to reproduce the behavior

```
./configure --with-perl --with-python --with-libxml --with-gssapi --prefix=/home/user/bin/gpdb
```

**Comment by kainwen** [comment]
You should check `config.log` to see the detailed error message and find out how to solve it.

I do not think this is an issue of Greenplum. So close it.

Feel free to comments here if not resolved.

**Comment by Simon-Wong** [comment]
So,anybody get this again?
