### ISSUE TITLE
cast type get error results

### ISSUE THREAD

**Issue by dxscjx123** [greenplum-db/gpdb#11249]
### Greenplum version or build
master branch, the latest commit is 460780eb7cb20515db5974eab067b07459e5b9ba

select version() result
 PostgreSQL 12beta2 (Greenplum Database 7.0.0-alpha.0+dev.14038.g460780e build dev) on x86_64-pc-linux-gnu, compiled by gcc (GCC) 11.0.0 202011
04 (experimental), 64-bit compiled on Nov 25 2020 06:35:16 (with assert checking)
(1 row)

### OS version and uname -a
Linux  3.10.0-327 x86_64

### Installation information ( pg_config )
CONFIGURE = '--with-perl' '--with-python' '--with-libxml' '--enable-debug' '--disable-gpcloud' '--disable-gpfdist' '--without-zstd' '--prefix=/home/postgres/work/gpdb_dir' 'CFLGS=-O0 -g3 -ggdb3 -Wno-error' 'CXXFLAGS=-O0 -g3 -ggdb3 -Wno-error' 'LLVM_CONFIG=/opt/rh/llvm-toolset-7/root/usr/bin/llvm-config' 'CLANG=/opt/rh/llvm-toolset-7/root/usr/bin/clang' 'PKG_CONFIG_PATH=:/usr/lib/pkgconfig'
CC = gcc

### Actual behavior
I found the subselect sql get a wrong result in executor.
sql ：
```sql
create table test (col1 numeric(2,0), col2 numeric(2,0));
insert into test values (11, 11);
insert into test values (12, 12);
create table test2(c1 numeric(2,0), c2 varchar(10), c3 text);
insert into test2 values (11, '11', '11');
CREATE CAST (varchar AS numeric) WITH INOUT AS IMPLICIT;
```

execute sql: 
```sql
SELECT col1 FROM test where col1 in (select c2 from test2) ;
```
execute it and get a core file.

the plan is ：
```
postgres=# explain SELECT col1 FROM test where col1 in (select c2 from test2) ;
                                            QUERY PLAN
---------------------------------------------------------------------------------------------------
 Gather Motion 3:1  (slice1; segments: 3)  (cost=0.00..862.00 rows=1 width=5)
   ->  Hash Semi Join  (cost=0.00..862.00 rows=1 width=5)
         Hash Cond: (test.col1 = (test2.c2)::numeric)
         ->  Seq Scan on test  (cost=0.00..431.00 rows=1 width=5)
         ->  Hash  (cost=431.00..431.00 rows=1 width=3)
               ->  Broadcast Motion 3:3  (slice2; segments: 3)  (cost=0.00..431.00 rows=1 width=3)
                     ->  Seq Scan on test2  (cost=0.00..431.00 rows=1 width=3)
 Optimizer: Pivotal Optimizer (GPORCA)
(8 rows)
```

but when I execute it, it get result:
postgres=# SELECT col1 FROM test where col1 in (select c2 from test2) ;
psql: ERROR:  Error on receive from seg0 slice1 172.0.0.1:7532 pid=46446: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.

the reason why get the error meseage is 
In CMDAccessorUtils::FCmpOrCastedCmpExists will deal with the cast function. Finally execute Pmdcast->GetImdObj->GetMDObjDXLStr->RetrieveObject->RetrieveCast->CMDCastGPDB
when enable_cassert ,  CMDCastGPDB will get a GPOS_ASSERT_IMP(!is_binary_coercible, m_mdid_cast_func->IsValid()); so it can not get a GPORCA plan. But if it is not in cassert , it will get a GPORCA plan above.
But when execute, it get a core file
![image](https://user-images.githubusercontent.com/17701710/101358081-52023d00-38d5-11eb-99a8-ecb2879c3ef0.png)

**Comment by danhoffman699** [comment]
Issue is non-reproducible on `master` and `6X_STABLE`. https://github.com/greenplum-db/gpdb/commit/7a71720eb7b653b281917bd4ef718ca3085ab740 fixed it.

Closing this PR
