### ISSUE TITLE
Enabling CDB_MOTION_DEBUG preprocessor flag causes SEGV

### ISSUE THREAD

**Issue by asimrp** [greenplum-db/gpdb#11242]
### Greenplum version or build
6X_STABLE, did not try on Greenplum 7

### Installation information ( pg_config )
Note the CPPFLAGS in the end:
```
./config.status --config
'--prefix=/home/apraveen/workspace/gpdb6/gpAux/greenplum-db-devel' '--enable-cassert' '--enable-debug' '--enable-tap-tests' '--enable-depend' '--disable-orca' '--disable-gpcloud' '--disable-gpfdist' '--with-python' '--with-perl' 'CFLAGS=-O0' 'CXXFLAGS=-O0' 'CC=ccache gcc' 'CXX=ccache g++' 'CPPFLAGS=-DCDB_MOTION_DEBUG'
```
### Expected behavior
Simply query against a distributed table should result in motion nodes emitting details of each tuple serialized and deserialised in CSV logs.
Setup:
```SQL
set log_min_messages = debug3;
create table foo (a int, b int);
insert into foo select i,i from generate_series(1,20)i;
```
The insert statement should emit tuple serialization and deserialization information in QD and QE log files.

### Actual behavior
QE crashes with a SEGV.

**Comment by JunfengYang** [comment]
Merged.
