### ISSUE TITLE
2pc存在数据丢失现象

### ISSUE THREAD

**Issue by hanguanmiao** [greenplum-db/gpdb#11269]
### 1 版本号和配置
```
PostgreSQL 9.4.24 (Greenplum Database 6.0.0-beta.1 build dev)
```
一台master,2台segment,都在同一台机器上
### 2 测试2pc
2.1 insert distributed table
![enter image description here](https://raw.githubusercontent.com/hanguanmiao/for-greenplum/main/Screenshot%20from%202020-12-11%2014-52-15.png)
查询pid,插入数据。
在插入数据之前用gdb调式

2.2 gdb勾住master
![enter image description here](https://raw.githubusercontent.com/hanguanmiao/for-greenplum/main/Screenshot%20from%202020-12-11%2014-53-08.png)
用gdb调式，attach master_pid, 在DTX_PROTOCOL_COMMAND_COMMIT_PREPARED暂停

2.3 确认 prepared xact存在
![enter image description here](https://raw.githubusercontent.com/hanguanmiao/for-greenplum/main/Screenshot%20from%202020-12-11%2014-53-51.png)

2.4 发送DTX_PROTOCOL_COMMAND_COMMIT_PREPARED
![enter image description here](https://raw.githubusercontent.com/hanguanmiao/for-greenplum/main/Screenshot%20from%202020-12-11%2014-54-31.png)
只往其中一台发送DTX_PROTOCOL_COMMAND_COMMIT_PREPARED，另外一台还未得到DTX_PROTOCOL_COMMAND_COMMIT_PREPARED

2.5 杀死segment并继续运行
![enter image description here](https://raw.githubusercontent.com/hanguanmiao/for-greenplum/main/Screenshot%20from%202020-12-11%2014-56-51.png)
杀死segment进程后，master会发送一个DTX_PROTOCOL_COMMAND_RETRY_COMMIT_PREPARED.

2.6 数据插入非原子性
![enter image description here](https://raw.githubusercontent.com/hanguanmiao/for-greenplum/main/Screenshot%20from%202020-12-11%2014-57-49.png)
数据1消失了。
![enter image description here](https://raw.githubusercontent.com/hanguanmiao/for-greenplum/main/Screenshot%20from%202020-12-11%2014-58-19.png)
事务确实已提交

### 3 说明
如果没有出现这个现象，请在2.5中多杀死几次segment进程，这个现象就必然发生。
我所举的例子是数据部分成功，还有一种是在DTX_PROTOCOL_COMMAND_COMMIT_PREPARED前杀死segment进程的话，那所有的数据都会丢失

**Comment by paul-guo-** [comment]
Could you please try on latest gpdb 6? beta.1 is old. Also in step 2.5, you mean kill one segment. I assume you mean "kill -9" the QE backend, right?

**Comment by hanguanmiao** [comment]
> Could you please try on latest gpdb 6? beta.1 is old. Also in step 2.5, you mean kill one segment. I assume you mean "kill -9" the QE backend, right?

I have tested on gpdb clusters of version-6-12.1, it doesn't have the problem any more. Your suggestion is correct. Now you can close the issue and thanks for your reply.
