### ISSUE TITLE
ORCA: generate plan missing sort node, leading result out of order

### ISSUE THREAD

**Issue by qiuyuhang** [greenplum-db/gpdb#11267]
### Greenplum version or build
master branch

### SQL
```SQL
CREATE TABLE tenk1 (
	unique1		int4,
	unique2		int4,
	two			int4,
	four		int4,
	ten			int4,
	twenty		int4,
	hundred		int4,
	thousand	int4,
	twothousand	int4,
	fivethous	int4,
	tenthous	int4,
	odd			int4,
	even		int4,
	stringu1	name,
	stringu2	name,
	string4		name
);

COPY tenk1 FROM '@GPDB_SRC@/src/test/regress/data/tenk.data';

-- Here we got array_agg out of order, actually you can replace array_agg to other functions like concat
explain select array_agg(unique1) from (select unique1 from tenk1 where unique1 < 15 order by unique1) ss;
select array_agg(unique1) from (select unique1 from tenk1 where unique1 < 15 order by unique1) ss;

-- These works fine
explain select unique1 from tenk1 where unique1 < 15 order by unique1;
select unique1 from tenk1 where unique1 < 15 order by unique1;
```
### Expected behavior
```
                                   QUERY PLAN                                    
---------------------------------------------------------------------------------
 Aggregate  (cost=0.00..6.01 rows=1 width=8)
   Gather Motion 3:1  (slice1; segments: 3)  (cost=0.00..6.01 rows=16 width=4)
     Merge Key: unique1
     ->  Index Scan using tenk1_unique1 on tenk1  (cost=0.00..6.01 rows=6 width=4)
           Index Cond: (unique1 < 15)
 Optimizer: Pivotal Optimizer (GPORCA)
(5 rows)

              array_agg               
--------------------------------------
 {1,2,3,4,5,6,7,8,9,10,11,12,13,14}
(1 row)
```

### Actual behavior
```
                                      QUERY PLAN                                       
---------------------------------------------------------------------------------------
 Aggregate  (cost=0.00..6.01 rows=1 width=8)
   ->  Gather Motion 3:1  (slice1; segments: 3)  (cost=0.00..6.01 rows=16 width=4)
         ->  Index Scan using tenk1_unique1 on tenk1  (cost=0.00..6.01 rows=6 width=4)
               Index Cond: (unique1 < 15)
 Optimizer: Pivotal Optimizer (GPORCA)
(5 rows)

              array_agg               
--------------------------------------
 {2,3,4,7,8,0,1,12,5,6,9,10,11,13,14}
(1 row)
```

**Comment by kainwen** [comment]
You can specify the order in `array_agg`:

```sql
explain select array_agg(unique1 ORDER BY unique1) from (select unique1 from tenk1 where unique1 < 15 order by unique1) ss;
```

But this will lead to fallback to planner, planner will add sort node and use merge gather no matter `order by` provided or not.

So I think if `array_agg` can have options for order, we should use order by syntax when we want to get a sorted result.

**Comment by qiuyuhang** [comment]
But I think it's a bug, that ORCA pruning the sort node incorrectly.
Here is GP with ORCA off:
```
set optimizer=off;
                                          QUERY PLAN                                        
  
----------------------------------------------------------------------------------------------
 Aggregate  (cost=18.47..18.48 rows=1 width=32)
   ->  Gather Motion 3:1  (slice1; segments: 3)  (cost=18.17..18.43 rows=15 width=4)
         Merge Key: tenk1.unique1
         ->  Sort  (cost=18.17..18.18 rows=5 width=4)
               Sort Key: tenk1.unique1
               ->  Bitmap Heap Scan on tenk1  (cost=4.27..18.11 rows=5 width=4)
                     Recheck Cond: (unique1 < 15)
                     ->  Bitmap Index Scan on tenk1_unique1  (cost=0.00..4.27 rows=5 width=0)
                           Index Cond: (unique1 < 15)
 Optimizer: Postgres query optimizer
(10 rows)

              array_agg               
--------------------------------------
 {0,1,2,3,4,5,6,7,8,9,10,11,12,13,14}
(1 row)
```

Here is the pg13 output:
```
                             QUERY PLAN                             
--------------------------------------------------------------------
 Aggregate  (cost=470.52..470.53 rows=1 width=32)
   ->  Sort  (cost=470.29..470.33 rows=15 width=4)
         Sort Key: tenk1.unique1
         ->  Seq Scan on tenk1  (cost=0.00..470.00 rows=15 width=4)
               Filter: (unique1 < 15)
(5 rows)
              array_agg               
--------------------------------------
 {0,1,2,3,4,5,6,7,8,9,10,11,12,13,14}
(1 row)
```

**Comment by kainwen** [comment]
> But I think it's a bug, that ORCA pruning the sort node incorrectly

Orca uses index scan in your case. Index scan (using btree) will guarantee the output tuple of it is in order. Your pg13 case uses seqscan, that is why it has sort plannode to implement the `order by`.

The core issue is: ***does the semantic of array_agg require order?***

This may not be a problem in Postgres's single process model, but for MPP database, this impacts if we should use merge gather.

I do not think that Postgres requires that `array_agg` must guarantee the order even user does not specify it using `order by` syntax.

So to me, ORCA's plan is correct. It does not prune the sort node. It just uses normal gather because it thinks that `array_agg` without  order by clause does not need to keep order.

**Comment by d** [comment]
> But I think it's a bug, that ORCA pruning the sort node incorrectly.

Your expectation is wrong. Aggregates in SQL do _not_ mandate order. In fact, `ORDER BY` in a subquery is invalid SQL (Please look at the section specifying *query expression*). As an extension in PostgreSQL, `ORDER BY` in a subquery is syntactically permitted, but semantically ignored. As a legacy behavior (less sophisticated sublink pull up), older versions of PostgreSQL used to (and still _might_, but with no guarantee) produce plans that happen to sort the subquery before proceeding to plan thing further up the query tree. PostgreSQL provides a further extension in its aggregate function call syntax to specify input order of an aggregate reference, if that's what a user really wants, please use that if your query _has to_ work with a specific ordering, although in general I'd recommend you rewrite your query.
