### ISSUE TITLE
ORCA tests: loss of log entries emitted from statistics comparison routine

### ISSUE THREAD

**Issue by maksm90** [greenplum-db/gpdb#11281]
## Problem description

While running and debugging ORCA tests I have noticed that trace logs gotten from [CTestUtils::EresCompare](https://github.com/greenplum-db/gpdb/blob/6.12.1/src/backend/gporca/server/src/unittest/CTestUtils.cpp#L2866-L2898) method that compares serialized statistics objects are ignored on all caller sides and doesn't fall into trace output in screen [[1](https://github.com/greenplum-db/gpdb/blob/6.12.1/src/backend/gporca/server/src/unittest/CTestUtils.cpp#L2776-L2852), [2](https://github.com/greenplum-db/gpdb/blob/6.12.1/src/backend/gporca/server/src/unittest/dxl/statistics/CFilterCardinalityTest.cpp#L1076-L1134), [3](https://github.com/greenplum-db/gpdb/blob/6.12.1/src/backend/gporca/server/src/unittest/dxl/statistics/CMCVTest.cpp#L130-L140), [4](/https://github.com/greenplum-db/gpdb/blob/6.12.1/src/backend/gporca/server/src/unittest/dxl/statistics/CMCVTest.cpp#L130-L140)]. As result, if some test fails inside this method it's impossible to determine the reason of fail by trace output and need to involve debugging.
I think this is flaw and propose to wrap `CTestUtils::EresCompare` call the following fragment or smth similar:
```C
CWStringDynamic str(mp);
COstreamString oss(&str);
GPOS_RESULT eres = CTestUtils::EresCompare(oss, ...);
GPOS_TRACE(str->GetBuffer());
```
removing printing of the same that are printed inside `CTestUtils::EresCompare` objects from callers.

Any objections? 

### Greenplum version or build

master and below

**Comment by hardikar** [comment]
As you pointed out in the many examples, `GPOS_TRACE()` is used inside the tests to print the messages. I don't fully understand the problem. Are we missing `GPOS_TRACE` calls that should be there in side? In which case your suggestion would help streamline things.

**Comment by maksm90** [comment]
> So, I don't fully understand the problem. Are we missing GPOS_TRACE calls that should be there in side? In which case your suggestion would help streamline things.

The problem is in absence of `GPOS_TRACE()` call in printing logs gathered by OStream object that income to `CTestUtils::EresCompare()` function. As example, you could trace lifetime of OStream object `oss` and string variable `str` assigned to it inside [CFilterCardinalityTest::EresUnittest_CStatisticsCompare()](https://github.com/greenplum-db/gpdb/blob/6.12.1/src/backend/gporca/server/src/unittest/dxl/statistics/CFilterCardinalityTest.cpp#L1076-L1134) function:
```C
GPOS_RESULT
CFilterCardinalityTest::EresUnittest_CStatisticsCompare(
	CMemoryPool *mp, CMDAccessor *md_accessor,
	CStatisticsArray *pdrgpstatBefore, CStatsPred *pred_stats,
	const CHAR *szDXLOutput, BOOL fApplyTwice)
{
        /* Init trace string and assign to it OStream object */
	CWStringDynamic str(mp);
	COstreamString oss(&str);
        ...
        /* The first header string that doesn't make into log */
        oss << "Serializing Input Statistics Objects (Before Filter)" << std::endl;
	CWStringDynamic *pstrInput = CDXLUtils::SerializeStatistics(
        ...
        /* The second header string that doesn't make into log */
        oss << "Serializing Output Statistics Objects (After Filter)" << std::endl;
	CWStringDynamic *pstrOutput = CDXLUtils::SerializeStatistics(
        ...
        /* The first call of CTestUtils::EresCompare() that puts to oss results of serialized statistics equality */
        GPOS_RESULT eres = CTestUtils::EresCompare(
		oss, pstrOutput, &dstrExpected, false /* ignore mismatch */
	);
        ...
        if (fApplyTwice && GPOS_OK == eres)
	{
           ...
           /* The first call of CTestUtils::EresCompare() with incoming oss */
           eres = CTestUtils::EresCompare(
			oss, pstrOutput2, &dstrExpected, false /* ignore mismatch */
		);
           ...
       }
       ...
       /* The trace string 'str' is released without printing via GPOS_TRACE() */
}
```
In the work in current issue I want to attain that the trace text put to `oss` inside `CTestUtils::EresCompare()` is eventually printed out to the user visible log via `GPOS_TRACE()` call.

**Comment by lij55** [comment]
https://github.com/greenplum-db/gpdb/pull/11567 fixed it so closing
