### ISSUE TITLE
Readme suggestions

### ISSUE THREAD

**Issue by michaeljkent** [greenplum-db/gpdb#1128]
The Amazon Linux readme seems to be missing some dependencies.

We need the paramiko package, which we had to install by doing the following:

`sudo yum install python-devel openssl-devel libffi-devel`

and then:
```
sudo pip install --upgrade setuptools
sudo pip install --upgrade wheel
sudo pip install --upgrade paramiko pip
```

Instructions for these packages are included for debian machines in README.debian, but are missing for the CentOS 6 instructions in README.amazon_linux.

It might also be useful to include information about which ports need to be open in the Amazon security policy. To make our cluster work, we had to add rules to allow inbound TCP connections on our master/standby/segment ports, and UDP connections for port range 1025-65535.

**Comment by asimrp** [comment]
Why is `sudo pip install --upgrade wheel` needed?

**Comment by disambiguator** [comment]
We could be wrong, but we were getting the error "bdist_wheel not found" and were able to solve it by installing wheel. We tried that after reading [this SO article](http://stackoverflow.com/questions/26664102/why-can-i-not-create-a-wheel-in-python).

**Comment by ivannovick** [comment]
Updated the Amazon README to be more detailed and rich since you guys are actually using it.  I verified again.  Be sure to use Amazon linux and not CentOS for steps to match more exactly
