### ISSUE TITLE
### GreenPlum Cluster size gets larger and deletion performance gets lower

### ISSUE THREAD

**Issue by BooleanWu** [greenplum-db/gpdb#11297]
### Greenplum version or build
6.7.1
### OS version and uname -a
cat /etc/redhat-release 
CentOS Linux release 7.3.1611 (Core)

uname -a
Linux node1 2.6.32-431.el6.x86_64 #1 SMP Fri Nov 22 03:15:09 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux

free -g
             total       used       free     shared    buffers     cached
Mem:           251        230         21          0          0        141
-/+ buffers/cache:         89        162
Swap:           31          0         31

ethtool eth1
Settings for eth1:
Speed: 1000Mb/s
	Duplex: Full
	Port: Twisted Pair
	PHYAD: 1
	Transceiver: internal
	Auto-negotiation: on
	MDI-X: Unknown
	Supports Wake-on: pumbg
	Wake-on: d
	Current message level: 0x00000007 (7)
			       drv probe link
	Link detected: yes

### autoconf options used ( config.status --config )
```shell
kernel.core_pattern = /home/core/core-%e-%p
vm.max_map_count = 655360
vm.zone_reclaim_mode = 0
vm.swappiness = 0
kernel.msgmnb = 65536
kernel.msgmax = 65536
kernel.shmmax = 68719476736
kernel.shmall = 4294967296
kernel.sem = 1024 1048576 200 1024
net.ipv4.tcp_max_syn_backlog = 4096
net.core.netdev_max_backlog = 10000
net.ipv4.conf.all.arp_filter = 1
vm.overcommit_ratio = 95
vm.overcommit_memory = 2
vm.min_free_kbytes = 15000000
```
#### Master
```shell
gp_enable_global_deadlock_detector=on
statement_mem=3072MB
work_mem=8GB
maintenance_work_mem=16GB
shared_buffers=3072MB
gp_vmem_protect_limit=30720
effective_cache_size=64GB
#log_statement=mod
log_min_duration_statement=300000
max_connections=1000
log_statement=none
max_prepared_transactions=1500
log_filename='gpdb-%Y-%m-%d_%H.csv'
log_rotation_size=200MB
log_truncate_on_rotation=on
```
#### Segment
```shell
gp_enable_global_deadlock_detector=on
statement_mem=3072MB
work_mem=8GB
maintenance_work_mem=16GB
shared_buffers=3072MB
gp_vmem_protect_limit=30720
effective_cache_size=64GB
#log_statement=none
log_min_duration_statement=300000
max_connections=1500
log_statement=none
max_prepared_transactions=1500
log_rotation_size=200MB
log_truncate_on_rotation=on
```
#### 集群规模配置一
```shell
1、[3台服务器构成的集群]：每一台Slave从机上运行8个Segment实例（4个Primary实例 + 4个Mirror实例），鼓集群主机上额外运行一个GP的Mater节点
2、每一台的服务器都是上述Linux服务器的配置
```
#### 集群规模配置二
```shell
1、[1台GP的Master主机 + 1台GP的Master-Standby备机]，这两台服务器上都没有跑其他的Segment数据节点
2、[3台GP的Slave从机]：每一台Slave从机上运行8个Segment实例（4个Primary实例 + 4个Mirror实例）
3、每一台的服务器都是上述Linux服务器的配置
```

某一张表存在50个字段，每一个字段类型均为text，在id字段上建索引
相同的数据规模，根据 `一批id`过滤执行delete语句，在配置一中耗时3秒。期望在配置二中会更加的快

### Actual behavior
相同的数据规模，根据 `一批id`过滤执行delete语句，在配置一中耗时3秒。在配置二中耗时60秒

### Step to reproduce the behavior
按照上述服务器配置，搭建greenplum集群，执行上述删除语句必现

**Comment by kainwen** [comment]
Please provide the following info for each case:

1. `select * from gp_segment_configuration;`  
2. the delete statement
3. the table schema
4. explain the delete statement
5. explain analyze the delete statement

**Comment by BooleanWu** [comment]
多线程执行缩表导致，实际时间应该需要除以线程数量
