### ISSUE TITLE
Query Catalog Table occur error when use generate_series function and query plain use Index Scan

### ISSUE THREAD

**Issue by water32** [greenplum-db/gpdb#11307]
### Greenplum version or build
6.13
### OS version and uname -a
RHEL7
### Expected behavior
Success Execute SQL
### Actual behavior
Occur Error
### Step to reproduce the behavior
set enable_indexscan to on;
set enable_seqscan to off;
select proargtypes typs,generate_series(0,array_upper(proargtypes,1)) idx from pg_proc
where proname='gp_skew_details' and pronamespace=(select oid from pg_namespace where nspname='gp_toolkit');

ERROR:  set-valued function called in context that cannot accept a set
********** 错误 **********

ERROR: set-valued function called in context that cannot accept a set
SQL 状态: 0A000

**Comment by kainwen** [comment]
GPDB6 (and Postgres 9.4) generate a plan like:

```sql
gpadmin=# explain select  proargtypes typs,generate_series(0,array_upper(proargtypes,1)) idx from pg_proc where pronamespace = 11 and proname = 'charlt';
                                              QUERY PLAN
-------------------------------------------------------------------------------------------------------
 Index Only Scan using pg_proc_proname_args_nsp_index on pg_proc  (cost=0.28..9.30 rows=1000 width=31)
   Index Cond: ((proname = 'charlt'::name) AND (pronamespace = 11::oid))
(2 rows)
```

postgres9.4 can return the correct result, and Greenplum will throw out the error mentioned in the issue.

------------------------------------------------------------

Later version Postgres (or GPDB's master branch) generate the plan like:

```sql
gpadmin=# explain select  proargtypes typs,generate_series(0,array_upper(proargtypes,1)) idx from pg_proc where pronamespace = 11 and proname = 'charlt';
                                                QUERY PLAN
----------------------------------------------------------------------------------------------------------
 ProjectSet  (cost=0.28..9.54 rows=1046 width=35)
   ->  Index Only Scan using pg_proc_proname_args_nsp_index on pg_proc  (cost=0.28..4.30 rows=1 width=31)
         Index Cond: ((proname = 'charlt'::name) AND (pronamespace = '11'::oid))
 Optimizer: Postgres query optimizer
(4 rows)
```

It has a `ProjectSet` plannode in the top of the plan and it works well.
