### ISSUE TITLE
MyTmGxactLocal->waitGxids should not be pfree()-ed

### ISSUE THREAD

**Issue by fangzheng** [greenplum-db/gpdb#11309]
### Greenplum version or build
6X_STABLE, master

`MyTmGxactLocal->waitGxids` is a `List` of gxids, but it's currently destructed with `pfree()`. This should be changed to `list_free()`.

https://github.com/greenplum-db/gpdb/blob/master/src/backend/cdb/cdbtm.c#L1311

https://github.com/greenplum-db/gpdb/blob/master/src/backend/cdb/cdbtm.c#L1420

**Comment by kainwen** [comment]
@fangzheng 
It seems 6x has not been fixed yet.

**Comment by fangzheng** [comment]
> @fangzheng
> It seems 6x has not been fixed yet.

Thanks for the reminder. Here is the backport PR: https://github.com/greenplum-db/gpdb/pull/11311
