### ISSUE TITLE
About supported systems

### ISSUE THREAD

**Issue by zhijia3278** [greenplum-db/gpdb#11305]
Our unit is a bank. We intend to adopt Greenplum scheme in the near future, and we are preparing to test the cluster.

First of all, we need to prepare the host. The first problem is that our company's host system can only use **SUSE Linux**. Do we want to make sure that this distribution can support it normally? Can't we select rpm for the installation package? Can we only select the source code package of tar and compile it myself?

**Comment by adam8157** [comment]
It's not officially supported, but you could always contact our sales. Closing.
