### ISSUE TITLE
How to set application name in a Postgresql JDBC url

### ISSUE THREAD

**Issue by cobolbaby** [greenplum-db/gpdb#11330]
### Greenplum version or build

- GP 5.28.3

### OS version and uname -a

- Docker Container: Centos7
- Docker Host: Linux mdw 4.15.0-117-generic #118-Ubuntu SMP Fri Sep 4 20:02:41 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

### Expected behavior

I hope to get the client information by querying the system view pg_stat_activity, so I added the ApplicationName field to the JDBC connection.

```
jdbc:postgresql://localhost:5435/MyDB?ApplicationName=MyApp
```

or

```
jdbc:postgresql://localhost:5435/MyDB?application_name=MyApp
```

JDBC Driver

```
        <!-- https://mvnrepository.com/artifact/org.postgresql/postgresql -->
        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <version>42.2.5</version>
            <exclusions>  
                <exclusion>  
                    <groupId>*</groupId>  
                    <artifactId>*</artifactId>  
                </exclusion>  
            </exclusions> 
        </dependency>
```

### Actual behavior

But then I found out that this method does not work.  How to set application name in a Postgresql JDBC url?

**Comment by asimrp** [comment]
PostgreSQL [JDBC driver documentation](https://github.com/pgjdbc/pgjdbc/blob/master/README.md) indicates that ApplicationName property in connection string requires PostgreSQL 9.0 or newer server.  Greenplum 5 is based on PostgreSQL 8.3.  Please consider upgrading to Greenplum 6, which is based on PostgreSQL 9.4 where ApplicationName should be supported.
