### ISSUE TITLE
GPLoad reuse table CSV quote is ignored

### ISSUE THREAD

**Issue by bgunics-talend** [greenplum-db/gpdb#11348]
### Greenplum version or build
6.11

### Expected behavior
When we change the quote character in the yaml file, we expect the external table to be dropped and recreated when the following settings are used:

  OUTPUT:
    - TABLE: '"public"."test1"'
    - MODE: insert
  PRELOAD:
    - REUSE_TABLES: true
    - STAGING_TABLE: '"gp_load_test1"'

(Even if I don't specify a staging table the behavior is the same.)

### Actual behavior

External table is not dropped hence load is not correct.

### Step to reproduce the behavior

Change the Quote character in the YAML file, trigger gpload it again.

**Comment by lij55** [comment]
if `REUSE_TABLES` is set to true, it is expected to keep both external table and staging table. it is expected behavior.
