### ISSUE TITLE
Some notes after installing a Greenplum Demo Cluster

### ISSUE THREAD

**Issue by kuraga** [greenplum-db/gpdb#11374]
I've built and installed Greenplum 6.13 using Docker.
There are some notes.
I've done it for testing not production use so I'm not willing to fill these notes fundamentally.
But I'll write it by one issue.

**Comment by kuraga** [comment]
## First

We have several documents with Docker instructions:
  1. https://github.com/greenplum-db/gpdb/blob/6.13.0/README.docker.md
  2. https://github.com/greenplum-db/gpdb/blob/6.13.0/src/tools/docker/README.md
  3. https://github.com/greenplum-db/gpdb/tree/6.13.0/src/tools/docker/ubuntu16_ppa-persistent
  4. https://github.com/greenplum-db/gpdb/blob/6.13.0/src/tools/docker/ubuntu16_ppa/README.md
  5. several lines at https://github.com/greenplum-db/gpdb/tree/6.13.0#development-with-docker which contains a broken file path...
  6. https://engineering.pivotal.io/post/docker-gpdb/

Which of them should user use? In which sequence?.. They are contradictory...

BTW, is it a rule to not push builds to Docker?

**Comment by kuraga** [comment]
## Second

`USAGE` call is incorrect in now: [on `-?`](https://github.com/greenplum-db/gpdb/blob/6.13.0/gpAux/gpdemo/demo_cluster.sh#L153) script doesn't exit.

See patch for details:
```diff
diff --git a/gpAux/gpdemo/demo_cluster.sh b/gpAux/gpdemo/demo_cluster.sh
index 2954f0f3e28..0ac100e70be 100755
--- a/gpAux/gpdemo/demo_cluster.sh
+++ b/gpAux/gpdemo/demo_cluster.sh
@@ -147,10 +147,12 @@ cleanDemo(){
 # Main Section
 #*****************************************************************************
 
-while getopts ":cdK'?'" opt
+while getopts ":cdK'?'uh" opt
 do
 	case $opt in 
-		'?' ) USAGE ;;
+        '?'|u|h) USAGE
+           exit 0
+           ;;
         c) checkDemoConfig
            RETVAL=$?
            if [ $RETVAL -ne 0 ]; then
```

BTW, which key is used for Usage now?
Help [prints](https://github.com/greenplum-db/gpdb/blob/6.13.0/gpAux/gpdemo/demo_cluster.sh#L153) `-u` but script [checks](https://github.com/greenplum-db/gpdb/blob/6.13.0/gpAux/gpdemo/demo_cluster.sh#L103) `-?`.

**Comment by kuraga** [comment]
## Third

The main instruction to install was https://github.com/greenplum-db/gpdb/blob/6.13.0/README.docker.md for me.
But I had to add some steps to get it work.

Install the dependencies:
```sh
yum install -y epel-release  # for some packages below
yum install -y net-tools  # it warned me lack of `ifconfig`, etc.
yum install -y openssh-server  # `setup_gpadmin_user.bash` assumes sshd
yum install -y python2-devel python2-pip  # `pip` is called in instructions
pip install --upgrade pip  # `pip install --user psutil` requires some newer version of `pip` than standard
```
```sh
yum install -y xerces-c xerces-c-devel  # if you try to compile with ORCA
```

Also IMHO it's good to
```sh
pip install --user wheel
```

Instruction
```
Assuming that gpdemo-env.sh has been sourced, modify the pg_hba.conf file located in $MASTER_DATA_DIRECTORY to include the following:
host all gpadmin 0.0.0.0 trust
```
I've done with code:
```sh
echo 'host all gpadmin 0.0.0.0 trust' >> $MASTER_DATA_DIRECTORY/pg_hba.conf
```

Also it's simple to remove instruction about `[container name]` by just adding `docker run`'s `--name` option.

Sections I didn't try: `Set up rsync (optional)`, `Configure cgroups for GPDB (optional)`.

**Comment by kuraga** [comment]
## Fourth

Document [here](https://github.com/greenplum-db/gpdb/blob/6.13.0/README.docker.md), please: Stopping and Starting the Cluster.

Well we have `Starting a gpdemo Cluster` section but what does it do instead?
  1. Drop old cluster.
  2. (optionally) Erase all data.
  3. Construct a new cluster.
  4. Start the cluster.

It would be good to have instructions to just stop (without dropping anything) the cluster and then just start it (after restarting the container) exactly as a section of this document.

**Comment by kuraga** [comment]
## Fifth

https://github.com/greenplum-db/gpdb/blob/6.13.0/gpAux/gpdemo/demo_cluster.sh#L191-L200

These lines are incorrect in case of `WITH_MIRRORS=false`, `WITH_SANDBY=false`. Right?

**Comment by kuraga** [comment]
## Sixth

When compile with ORCA enabled I got
```
/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version CXXABI_1.3.9' not found
```
(or something like) on start.
Is this a known issue? Or will I create a new one?

**Comment by kuraga** [comment]
Thanks!
Feel free to ask me anything.

**Comment by kuraga** [comment]
## Seventh

I have three tables with equal structure.
```sql
INSERT INTO T3
  SELECT * FROM T1
  UNION ALL
  SELECT * FROM T2;
```
tooks:
1. 1,5 minutes if tables are `DISTRIBUTED BY` an `INTEGER` column;
2. 42 hours if tables are `DISTRIBUTED BY` an `TIMESTAMP WITH ZONE` low-cardinality column.

Is this difference normal. Could it be a bug?

**Comment by adam8157** [comment]
> ## Sixth
> When compile with ORCA enabled I got
> 
> ```
> /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version CXXABI_1.3.9' not found
> ```
> 
> (or something like) on start.
> Is this a known issue? Or will I create a new one?

ORCA needs a compiler that supports C++ higher standard (14?), so you probably installed a later version toolchain somewhere.

Binary built with that toolchain needs `LD_LIBRARY_PATH` set for running, like:
```
export LD_LIBRARY_PATH=/opt/gcc-X.Y.Z/lib64:${LD_LIBRARY_PATH:-}
```

**Comment by adam8157** [comment]
> ## Seventh
> I have three tables with equal structure.
> 
> ```sql
> INSERT INTO T3
>   SELECT * FROM T1
>   UNION ALL
>   SELECT * FROM T2;
> ```
> 
> tooks:
> 
> 1. 1,5 minutes if tables are `DISTRIBUTED BY` an `INTEGER` column;
> 2. 42 hours if tables are `DISTRIBUTED BY` an `TIMESTAMP WITH ZONE` low-cardinality column.
> 
> Is this difference normal. Could it be a bug?

Calculating the hash of `TIMESTAMP WITH ZONE` would be slow, but it looks bad taking 42 hours. Could you please provide a reproducer (how to create tables and load data)?

**Comment by adam8157** [comment]
And thanks for the notes!

Would you mind submitting pull requests for the scripts and docs you were mentioning?

**Comment by kuraga** [comment]
> > ## Seventh
> 
> ORCA needs a compiler that supports C++ higher standard (14?), so you probably installed a later version toolchain somewhere.

@adam8157, But where? Docker image installs them by itself.

**Comment by kuraga** [comment]
> > ## Seventh
> 
> Calculating the hash of `TIMESTAMP WITH ZONE` would be slow, but it looks bad taking 42 hours. Could you please provide a reproducer (how to create tables and load data)?

@adam8157 , ok, later (if it will be reproduced on syntatic data).

**Comment by kuraga** [comment]
> And thanks for the notes!

Thank YOU! After three month I didn't have a hope.

> Would you mind submitting pull requests for the scripts and docs you were mentioning?

No, sorry, Greenplum was just an experiment for me. But IMHO I've already described all issues.

**Comment by adam8157** [comment]
> > > ## Sixth
> > 
> > 
> > ORCA needs a compiler that supports C++ higher standard (14?), so you probably installed a later version toolchain somewhere.
> 
> @adam8157, But where? Docker image installs them by itself.

You might skipped something in the doc (https://github.com/greenplum-db/gpdb/blob/6.13.0/README.docker.md):
```
cat >> ~/.bash_profile <<EOF
...
source /opt/gcc_env.sh
...
EOF
```

**Comment by adam8157** [comment]
> @adam8157
> 
> > And thanks for the notes!
> 
> Thank YOU! After three month I didn't have a hope.
> 
> > Would you mind submitting pull requests for the scripts and docs you were mentioning?
> 
> No, sorry, Greenplum was just an experiment for me. But IMHO I've already described all issues.

I'm sorry about that, will discuss these notes in-house.

They are very valuable for us making Greenplum more user/developer friendly, thanks.

**Comment by kuraga** [comment]
> > > > ## Sixth
> 
> You might skipped something in the doc (https://github.com/greenplum-db/gpdb/blob/6.13.0/README.docker.md):
> 
> ```
> cat >> ~/.bash_profile <<EOF
> ...
> source /opt/gcc_env.sh
> ...
> EOF
> ```

Ok, I can't except this as I tried compile (obviously) first so I've not had understanding at that time.
But if you would re-compile by (maybe updated) docs then try compile with ORCA, too :)

**Comment by kuraga** [comment]
> > > > ## Sixth
> 
> You might skipped something in the doc (https://github.com/greenplum-db/gpdb/blob/6.13.0/README.docker.md):
> 
> ```
> cat >> ~/.bash_profile <<EOF
> ...
> source /opt/gcc_env.sh
> ...
> EOF
> ```

@adam8157 Yes, confirm. I repeated steps and everything is OK. ORCA is compiled. Sorry!

**Comment by kuraga** [comment]
> > ## Seventh
> > I have three tables with equal structure.
> > ```sql
> > INSERT INTO T3
> >   SELECT * FROM T1
> >   UNION ALL
> >   SELECT * FROM T2;
> > ```
> > 
> > 
> > tooks:
> > 
> > 1. 1,5 minutes if tables are `DISTRIBUTED BY` an `INTEGER` column;
> > 2. 42 hours if tables are `DISTRIBUTED BY` an `TIMESTAMP WITH ZONE` low-cardinality column.
> > 
> > Is this difference normal. Could it be a bug?
> 
> Calculating the hash of `TIMESTAMP WITH ZONE` would be slow, but it looks bad taking 42 hours. Could you please provide a reproducer (how to create tables and load data)?

@adam8157 , hm... on clean installation `UNION ALL` took 2 minutes. I don't know the cause. Sorry.

**Comment by kuraga** [comment]
@adam8157 one more question, please. So:
1. After cluster making, `gpdemo/datadirs` is 9Gb.
2. After some operations in `the_db` database it is 400Gb.
3. After `DROP DATABASE the_db` and `gpstop -a` is 72Gb.

Is it correct? I except ~9Gb instead... Thanks.

**Comment by adam8157** [comment]
What files occupied the disk? `pg_log`, `pg_xlog` or `archive`? It could be correct in some situations.

**Comment by kuraga** [comment]
> What files occupied the disk? `pg_log`, `pg_xlog` or `archive`? It could be correct in some situations.

@adam8157 , `pg_xlog` (1.1Gb per node).

**Comment by adam8157** [comment]
That's fine, `pg_xlog` stores WAL, which PostgreSQL won't aggressively remove, it won't go very huge, PostgreSQL will decide whether to delete the file.

**Comment by adam8157** [comment]
@chlos the images in docker hub pivotaldata have bundled higher version GCC and the `/opt/gcc_env.sh`.

**Comment by chlos** [comment]
> @chlos the images in docker hub pivotaldata have bundled higher version GCC and the `/opt/gcc_env.sh`.
Problem is that there are no images found. Both [pivotaldata/gpdb6-centos7-build](https://hub.docker.com/r/pivotaldata/gpdb6-centos7-build) and [gpdb7-centos7-test](https://hub.docker.com/r/pivotaldata/gpdb7-centos7-test) just shows an 404 error.

**Comment by adam8157** [comment]
Oops, recently we switched to gcr.io/data-gpdb-public-images, these files need to be updated, thanks.

filed a new issue https://github.com/greenplum-db/gpdb/issues/12431
