### ISSUE TITLE
I wanted to know the source file  which contain the entry point function main() for main process

### ISSUE THREAD

**Issue by BKnight73** [greenplum-db/gpdb#11380]
I am new to Greenplum development...
I am trying to understand system at code level and searching entry point function for main process . i.e. main().

There are many main methods that might be base on different modules. I wanted to know the source file where main() resides which will be for MAIN process. I guess that will be **Master Host**
@tanzeeb @rvs @professor @schubert @foobar

**Comment by asimrp** [comment]
@BKnight73 welcome to Greenplum!  What you are looking for is https://github.com/greenplum-db/gpdb/blob/ec38af2ac01294e43c77d3898912563d027b4596/src/backend/main/main.c#L61

Note that the same code runs on coordinator, standby, primary and mirror segments.  `Gp_role` and `GpIdentity` are used to distinguish the responsibilities.  See `IS_QUERY_DISPATCHER` macro for more detains.

Please note that we have decided to adopt a change in terminology - "master" is renamed to "coordinator".  The code changes are in progress. 

Questions like this may be easily discussed on [Greenplum #dev](https://greenplum.slack.com/archives/CFW9A98HL) slack channel rather that an issue.  I'm closing this one, please feel free to discuss further on slack.

**Comment by BKnight73** [comment]
Hello,

Thank you very much for your reply.

Can you please add me to the Greenplum -Dev Slack workspace?

Thank you;
Rajesh Kemkar;

**Comment by BKnight73** [comment]
Hello,

Also it will be of great help If you can share a design document with me.
I can go through SDD and can understand code better...

Thank you;
Rajesh Kemkar;

**Comment by asimrp** [comment]
@BKnight73 , you can sign yourself up to Greenlpum slack link above.

Several README files source repository are a good resource to start with, e.g. 
[executor/README](https://github.com/greenplum-db/gpdb/blob/master/src/backend/executor/README)
[executor/README.tuples](https://github.com/greenplum-db/gpdb/blob/master/src/backend/executor/README.tuples)
[resowner/README](https://github.com/greenplum-db/gpdb/blob/master/src/backend/utils/resowner/README)
[fts/README](https://github.com/greenplum-db/gpdb/blob/master/src/backend/fts/README)

Greenplum product documentation is a good resource as well: http://docs.greenplum.org/6-12/common/gpdb-features.html
