### ISSUE TITLE
ICG `constraints` failed due to inconsistent behavior

### ISSUE THREAD

**Issue by xinzweb** [greenplum-db/gpdb#1139]
The Postgres planner will bail when given `UPDATE` statements on distribution column.

GPORCA can produce a query plan supporting such updates. However, on GPDB, we observed different behaviors on different platforms.

On Darwin (OSX 10.11), the test passed, however on Linux the test failed. We got repro on following configuration and platform:
- Image: CentOs6
- Configuration flags are:

```
./configure --enable-orca --enable-mapreduce --with-perl --with-libxml --with-python --enable-gpfdist
```

**Comment by ivannovick** [comment]
@xinzweb is this resolved?

**Comment by d** [comment]
No not yet :(

**Comment by ashwinstar** [comment]
I no more see those tests in disabled form in the `constraints.source`. Does the issue still really exists? Any such kind of issues where greenery was achieved by disabling the test should be fixed on priority.

**Comment by ashwinstar** [comment]
@d do you know what this issue was, where did we disable the test and is it something still relevant or we can close this issue ?

**Comment by BaiShaoqi** [comment]
@xinzweb @melanieplageman and I are looking at this. We are not sure about the platform-specific flakiness of the constraints test, but, given the changes to split update now, this should probably be resolved either way.
@Eulerizeit

**Comment by ashwinstar** [comment]
@Eulerizeit @melanieplageman  We should bring back the sql statements removed as part of this commit https://github.com/greenplum-db/gpdb/commit/46e5a84da7f6af3b230d6fe6f61e3665498ae561 then if this issue is being closed/resolved to restore the test coverage back which was disabled before.

**Comment by Eulerizeit** [comment]
Thanks @ashwinstar I missed that commit.

**Comment by Eulerizeit** [comment]
@xinzweb could you revert 46e5a84da7f6 and see if this is resolved please?

**Comment by xinzweb** [comment]
@Eulerizeit thanks for the reminder. Ping @vraghavan78 to see if he can handle it from here. Thanks.

**Comment by melanieplageman** [comment]
@danielgustafsson does the re-adding of the tests mean we can close this issue?

**Comment by danielgustafsson** [comment]
No, as I mentioned in the linked PR we shouldn't bother with these tests as we have ample coverage of that codepath elsewhere (added well after this was worked on), I simply missed to close the issue when closing the PR so will do that now.
