### ISSUE TITLE
Greenplum7 Alpha+PostGIS3.0.2:Failed to create extension postgis,why and how to do?

### ISSUE THREAD

**Issue by geostar123** [greenplum-db/gpdb#11390]
### Greenplum version or build
postgres (Greenplum Database) 7.0.0-alpha.0+dev.14163.g327f60a build dev
PostGIS3.0.2

### OS version and uname -a
Linux pgdb-master 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

### Installation information ( pg_config )
BINDIR = /usr/local/gpdb/bin
DOCDIR = /usr/local/gpdb/share/doc/postgresql
HTMLDIR = /usr/local/gpdb/share/doc/postgresql
INCLUDEDIR = /usr/local/gpdb/include
PKGINCLUDEDIR = /usr/local/gpdb/include/postgresql
INCLUDEDIR-SERVER = /usr/local/gpdb/include/postgresql/server
LIBDIR = /usr/local/gpdb/lib
PKGLIBDIR = /usr/local/gpdb/lib/postgresql
LOCALEDIR = /usr/local/gpdb/share/locale
MANDIR = /usr/local/gpdb/share/man
SHAREDIR = /usr/local/gpdb/share/postgresql
SYSCONFDIR = /usr/local/gpdb/etc/postgresql
PGXS = /usr/local/gpdb/lib/postgresql/pgxs/src/makefiles/pgxs.mk
CONFIGURE = '--with-perl' '--with-python' '--with-libxml' '--with-gssapi' '--prefi                                                                                                           x=/usr/local/gpdb'
CC = gcc
CPPFLAGS = -D_GNU_SOURCE -I/usr/include/libxml2
CFLAGS = -Wall -Wmissing-prototypes -Wpointer-arith -Werror=vla -Wendif-labels -Wm                                                                                                           issing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-pr                                                                                                           ecision=standard -Wno-unused-but-set-variable -Werror=implicit-fallthrough=3 -Wno-                                                                                                           format-truncation -O3  -Werror=uninitialized -Werror=implicit-function-declaration
CFLAGS_SL = -fPIC
LDFLAGS = -Wl,--as-needed -Wl,-rpath,'/usr/local/gpdb/lib',--enable-new-dtags
LDFLAGS_EX =
LDFLAGS_SL =
LIBS = -lpgcommon -lpgport -lpthread -lxerces-c -lbz2 -lxml2 -lrt -lgssapi_krb5 -l                                                                                                           zstd -lz -lreadline -lrt -lcrypt -ldl -lm  -lcurl
VERSION = PostgreSQL 12beta2
### Expected behavior
create extension postgis;
CREATE EXTENSION
### Actual behavior
create extension postgis;
psql: ERROR:  query plan with multiple segworker groups is not supported
HINT:  likely caused by a function that reads or modifies data in a distributed table
### Step to reproduce the behavior

Greenplum cluster has one master and one segment.I have compiled and installed postgis3.0.2 on master and segment host. 
Any help will be appericated.Thanks.

**Comment by kainwen** [comment]
Same as https://github.com/greenplum-db/gpdb/issues/11304

I believe they are the same issues. 

We should take a look at these two soon.

**Comment by zhangh43** [comment]
Greenplum doesn't support PostGIS3.x, Please check the official documentation for the supported version. https://gpdb.docs.pivotal.io/6-13/analytics/postGIS.html

@fmcquillan99 Any comment on this issue?

**Comment by geostar123** [comment]
I think I could fixed this issue.To activate postgis after compilation and installation,you may execute the below sqls,not "create extension postgis".
 >$ psql -d postgres -f ${GPHOME}/share/postgresql/contrib/postgis-3.0/postgis.sql
  >$ psql -d postgres -f ${GPHOME}/share/postgresql/contrib/postgis-3.0/postgis_comments.sql
  >$ psql -d postgres -f ${GPHOME}/share/postgresql/contrib/postgis-3.0/rtpostgis.sql
  >$ psql -d postgres -f ${GPHOME}/share/postgresql/contrib/postgis-3.0/raster_comments.sql
  >$ psql -d postgres -f ${GPHOME}/share/postgresql/contrib/postgis-3.0/spatial_ref_sys.sql

After doing the above,I succeeded to  create a spatial table :

 CREATE TABLE gp_t1(id int not null,ch varchar(255) not null,de numeric(38,15) not null,ti smallint not null,mi int not null,s smallint not null,tc text not null,c text not null,l bigint not null,f numeric(38,15) not null, d double precision not null,y VARCHAR(4) not null,tm time not null,dt timestamp without time zone not null,t date not null,ts1 timestamp with time zone not null,ts2 timestamp without time zone not null,bl text not null,tibl text not null,mibl text not null,g GEOMETRY not null,PRIMARY KEY(id));

 CREATE INDEX gp_t1_idx ON gp_t1  USING GIST (g);

**Comment by geostar123** [comment]
postgres=# select postgis_version();
            postgis_version
---------------------------------------
 3.0 USE_GEOS=1 USE_PROJ=1 USE_STATS=1
(1 row)

**Comment by geostar123** [comment]
postgres=# select ST_GeomFromText('POINT(0 0)');
              st_geomfromtext
--------------------------------------------
 010100000000000000000000000000000000000000
(1 row)

Time: 1320.920 ms (00:01.321)

Thanks to all.
