### ISSUE TITLE
About performance of copy command for greenplum

### ISSUE THREAD

**Issue by qihuagao** [greenplum-db/gpdb#11420]
I am not sure whether this is good place to ask question. I would like to move this somewhere otherwise.

Since the latency of network(from master to  segment host),  how the copy command are degraded because of this.

are there some guys who have benchmarked this?  thanks a lot.

**Comment by lij55** [comment]
COPY is not intent for big amount of data. If you have huge data to loading, gpfdist is strongly suggested. For copy, it will parse and generate 'tuple' on master and distribute this tuple to related segment according to the hash/distribution key.
The bottle neck of COPY is convert text content to tuple so network latency would be high.

Besides, there are several mail list (https://greenplum.org/mailing-lists/) and you may ask similar question in the mail list. You can also ask such question in https://cn.greenplum.org/askgp/ if you are in China.

**Comment by qihuagao** [comment]
> COPY is not intent for big amount of data. If you have huge data to loading, gpfdist is strongly suggested. For copy, it will parse and generate 'tuple' on master and distribute this tuple to related segment according to the hash/distribution key.
> The bottle neck of COPY is convert text content to tuple so network latency would be high.
> 
> Besides, there are several mail list (https://greenplum.org/mailing-lists/) and you may ask similar question in the mail list. You can also ask such question in https://cn.greenplum.org/askgp/ if you are in China.
ok, appreciate your help.

**Comment by qihuagao** [comment]
> COPY is not intent for big amount of data. If you have huge data to loading, gpfdist is strongly suggested. For copy, it will parse and generate 'tuple' on master and distribute this tuple to related segment according to the hash/distribution key.
> The bottle neck of COPY is convert text content to tuple so network latency would be high.
> 
> Besides, there are several mail list (https://greenplum.org/mailing-lists/) and you may ask similar question in the mail list. You can also ask such question in https://cn.greenplum.org/askgp/ if you are in China.

ok, appreciate your help.
