### ISSUE TITLE
gpstate error message is misleading

### ISSUE THREAD

**Issue by Eulerizeit** [greenplum-db/gpdb#1143]
If you run gpstate with the cluster off the error message is odd. It asks if you are running locally and if the TCP port is open. 

At the least it ought to suggest the cluster is off. I'm unclear as to why it would suggest local host.  Also, Is the Post in this error message gotten from the configuration settings? 

[gpadmin@mdw pg_log]$ gpstate
20160920:21:16:09:002778 gpstate:mdw:gpadmin-[INFO]:-Starting gpstate with args:
20160920:21:16:09:002778 gpstate:mdw:gpadmin-[INFO]:-local Greenplum Version: 'postgres (Greenplum Database) 4.3.9.1 build commit:095e92e4ecbbbb6764897ca98b1cb7705ad0c805'
20160920:21:16:09:002778 gpstate:mdw:gpadmin-[CRITICAL]:-gpstate failed. (Reason='could not connect to server: Connection refused
        Is the server running on host "localhost" (127.0.0.1) and accepting
        TCP/IP connections on port 5432?
') exiting...

**Comment by oakbarrett** [comment]
Story created for enhancement to messaging

**Comment by chhitesh** [comment]
any update on this ?

**Comment by ivannovick** [comment]
closing it out, but feel free to submit a PR enhancement
