### ISSUE TITLE
Add unit test for GDD.

### ISSUE THREAD

**Issue by fangzheng** [greenplum-db/gpdb#11449]
### Greenplum version or build
master

Hi folks,
I have been reading the GDD code recently and think it's very nice work (salute you, GP hackers). 

Currently GDD is tested via the isolation2 framework. The tests there are well constructed, but are relatively small in terms of number of transactions and segments involved. One thing that might be nice to add is unit tests for GDD, which allow testing GDD algorithm with wait graphs of arbitrary scales and complexities. Such scenarios may not be easy to realize by using isolation2 framework.

I have implemented some unit tests using the standard cmockery mechanism. Here is the PR: https://github.com/greenplum-db/gpdb/pull/11448. 

Hope this could be of some value, and feedbacks are highly welcome. Thanks.

**Comment by ashwinstar** [comment]
@fangzheng Thanks for the contribution. Highly appreciate looking into GDD and enhancing test coverage for it.

For greenplum we don't need github issue for each PR. If opening PR can just do that and capture the context in it, no need for corresponding github issue for it. It adds unnecessary work for booking also context spreads in multiple places. Github issue is needed only if reporting some issue and not submitting code fix for it. I will keep this one open till PR #11448 makes in.

**Comment by fangzheng** [comment]
> @fangzheng Thanks for the contribution. Highly appreciate looking into GDD and enhancing test coverage for it.
> 
> For greenplum we don't need github issue for each PR. If opening PR can just do that and capture the context in it, no need for corresponding github issue for it. It adds unnecessary work for booking also context spreads in multiple places. Github issue is needed only if reporting some issue and not submitting code fix for it. I will keep this one open till PR #11448 makes in.

Hi Ashwin,
Thanks for the instructions and feedbacks. I'll follow the practice in the future.

**Comment by ashwinstar** [comment]
This was merged via https://github.com/greenplum-db/gpdb/commit/fda1e439c84c1a54fbc3530652f49ab121766406
