### ISSUE TITLE
gpdeletesystem requires the same variable to be set twice.

### ISSUE THREAD

**Issue by Eulerizeit** [greenplum-db/gpdb#1145]
Why does the same variable need to be set twice? This seems suboptimal. 

[gpadmin@mdw ~]$ gpdeletesystem
20160921:15:50:33:012935 gpdeletesystem:mdw:gpadmin-[CRITICAL]:-Required option --master-data-directory is missing.
[gpadmin@mdw ~]$ gpdeletesystem --master-data-directory /gp5data/master/gpseg-1/
20160921:15:50:39:012938 gpdeletesystem:mdw:gpadmin-[CRITICAL]:-MASTER_DATA_DIRECTORY environment variable not set.

**Comment by ashwinstar** [comment]
Agree its not good behavior. @oakbarrett please can you bring this in team's backlog and schedule to fix it.

**Comment by Chibin** [comment]
I've noted this with @oakbarrett already, same with issue 1143. 
Will follow up.

**Comment by oakbarrett** [comment]
I can create a story, but not sure when it will land...   
quick test, and it appears gpdeletesystem does a check against the ENV and command line parameter checking for consistency...  agree it may not be optimal, but curious if there is a reason for it...

```
[gpadmin@gpdb-sandbox ~]$ echo $MASTER_DATA_DIRECTORY
/gpmaster/seg-1
[gpadmin@gpdb-sandbox ~]$ gpdeletesystem -d /gpmaster/seg-2
20160927:16:08:37:002622 gpdeletesystem:gpdb-sandbox:gpadmin-[CRITICAL]:-Current setting of MASTER_DATA_DIRECTORY not same as -d parameter.
[gpadmin@gpdb-sandbox ~]$
```

**Comment by shubh8689** [comment]
Hi, @oakbarrett / @ashwinstar, I can take this up. 

Looking at gpdeletesystem, we are tracking two issues here-

1 - "--master-data-directory" being an undocumented option.
 - Looking at the below snippet --master-data-directory is the long/expanded form of "-d"
```
optgrp.add_option('-d', '--master-data-directory', dest='master_data_dir', 
                      type='string', help='Master data directory.')
```

But when we check, if this required argument is present, we chose to print the expanded form. Please refer the below snippet

```
 # check we got the -d option
    if not options.master_data_dir:
        logger.fatal('Required option --master-data-directory is missing.')
        parser.exit(2, None)
```
To fix this we can change this message to "Required option -d or --master-data-directory is missing." and add "--master-data-directory" to both help and documentation.

2 - We also check for master data directory using two different methods -
    a - Value of command line argument -d 
    b - Environment variable MASTER_DATA_DIRECTORY

```
# check that there isn't a conflict between -d option and MASTER_DATA_DIRECTORY env
    env_master_data_dir = os.getenv('MASTER_DATA_DIRECTORY', None)
    if not env_master_data_dir:
        logger.fatal('MASTER_DATA_DIRECTORY environment variable not set.')
        parser.exit(2, None)
        
    if os.path.normpath(env_master_data_dir) != options.master_data_dir:
        logger.fatal('Current setting of MASTER_DATA_DIRECTORY not same as -d parameter.')
        parser.exit(2, None)
```
In my opinion, since "-d" is a required option and anyhow we have to pass it through command line. Referring to environment variable MASTER_DATA_DIRECTORY and checking equality of environment vs commandline parameter can be skipped.

As to why the utility compares both environment variable and command line parameter to be the same, I couldn't find any convincing explanation. Let me know how this approach looks and I can start making the changes.

**Comment by ashwinstar** [comment]
On Mon, Nov 21, 2016 at 9:49 PM, Shubham Sharma <notifications@github.com>
wrote:

> Hi, @oakbarrett <https://github.com/oakbarrett> / @ashwinstar
> <https://github.com/ashwinstar>, I can take this up.
>
> Looking at gpdeletesystem, we are tracking two issues here-
>
> 1 - "--master-data-directory" being an undocumented option.
>
>    - Looking at the below snippet --master-data-directory is the
>    long/expanded form of "-d"
>
> optgrp.add_option('-d', '--master-data-directory', dest='master_data_dir',
>                       type='string', help='Master data directory.')
>
> But when we check, if this required argument is present, we chose to print
> the expanded form. Please refer the below snippet
>
>  # check we got the -d option
>     if not options.master_data_dir:
>         logger.fatal('Required option --master-data-directory is missing.')
>         parser.exit(2, None)
>
> To fix this we can change this message to "Required option -d or
> --master-data-directory is missing." and add "--master-data-directory" to
> both help and documentation.
>
Sure that sounds good.


> 2 - We also check for master data directory using two different methods -
> a - Value of command line argument -d
> b - Environment variable MASTER_DATA_DIRECTORY
>
> # check that there isn't a conflict between -d option and MASTER_DATA_DIRECTORY env
>     env_master_data_dir = os.getenv('MASTER_DATA_DIRECTORY', None)
>     if not env_master_data_dir:
>         logger.fatal('MASTER_DATA_DIRECTORY environment variable not set.')
>         parser.exit(2, None)
>
>     if os.path.normpath(env_master_data_dir) != options.master_data_dir:
>         logger.fatal('Current setting of MASTER_DATA_DIRECTORY not same as -d parameter.')
>         parser.exit(2, None)
>
> In my opinion, since "-d" is a required option and anyhow we have to pass
> it through command line. Referring to environment variable
> MASTER_DATA_DIRECTORY and checking equality of environment vs commandline
> parameter can be skipped.
>
> As to why the utility compares both environment variable and command line
> parameter to be the same, I couldn't find any convincing explanation.
>
Lets try to make it consistent with the behavior of other utilities,
@oakbarrett <https://github.com/oakbarrett> and team would be able to
provide guidance on it. From my personal opinion, -d should not be
mandatory option. Only if MASTER_DATA_DIRECTORY is not set it should be
asked to set it or provide -d option. But if MASTER_DATA_DIRECTORY is set
and -d is also provided, I believe -d should take precedence.

> Let me know how this approach looks and I can start making the changes.
>
Great to see you hacking on code and more so initiating discussion before
code change, welcome!

**Comment by ivannovick** [comment]
Is this resolved now?  @skahler-pivotal @oakbarrett @Chibin ?

**Comment by shubh8689** [comment]
Last time I didn't have the merge rights and Daniel helped me. I was recently added to GPDB org. I can give it a try. Are we following https://github.com/greenplum-db/greenplum-db.github.io/wiki/Merging-Pull-Requests to maintain a linear commit history ?

**Comment by danielgustafsson** [comment]
Yes, see answer to same question on another issue today.

**Comment by cjcjameson** [comment]
@skahler-pivotal Closing this issue as the PR has been pushed.

**Comment by Eulerizeit** [comment]
Thank you
