### ISSUE TITLE
cbdgang.c:1637  这种报错有见过吗？

### ISSUE THREAD

**Issue by shiliquan** [greenplum-db/gpdb#11475]
问题一：cbdgang.c:1637  这种报错有见过吗？
![image](https://user-images.githubusercontent.com/42087586/106842159-71072a80-66de-11eb-9be0-03a401658ea5.png)

问题二：发现gp数据库中的僵死进程无法kill掉，有没有什么其他好的解决办法？
![image](https://user-images.githubusercontent.com/42087586/106842265-aad83100-66de-11eb-8d00-c792d75ee56c.png)
上面两个通过select删除进程的，kill不掉。后面一个通过系统层面kill的话，会出问题吧，求教有没有什么好的解决方法？

**Comment by JunfengYang** [comment]
1. Please provide more info, like what's the query and the error trace in logs. 麻烦你提供更多信息，例如查询语句和出错时候的log。
2. If `pg_terminate_backend` can not stop the process, you should use `gdb` or `pstack` to check whether the process stuck at someplace. 如果`pg_terminate_backend`不生效，可以尝试使用`gdb`或者`pstack`看下进程卡在什么位置。

**Comment by adam8157** [comment]
2, and you could try upgrading, we resolved a similar issue back in October.

Closing this because of no information, feel free to reopen with more details.
