### ISSUE TITLE
make cluster fails due to ssh key

### ISSUE THREAD

**Issue by amilkh** [greenplum-db/gpdb#1149]
On a fresh El Capitan iMac, while following the instructions in the [README](https://github.com/greenplum-db/gpdb/blob/master/README.md) (with exception to using a different configure command), config and compilation completed just fine.

However, when running `make cluster`, I ran into the below issues:

```
20160922:17:02:03:038101 gpinitsystem:office-5-56:company-[INFO]:-Waiting for parallel processes batch [1], please wait...
..
20160922:17:02:05:038101 gpinitsystem:office-5-56:company-[INFO]:------------------------------------------------
20160922:17:02:05:038101 gpinitsystem:office-5-56:company-[INFO]:-Parallel process exit status
20160922:17:02:05:038101 gpinitsystem:office-5-56:company-[INFO]:------------------------------------------------
20160922:17:02:05:038101 gpinitsystem:office-5-56:company-[INFO]:-Total processes marked as completed           = 0
20160922:17:02:05:038101 gpinitsystem:office-5-56:company-[INFO]:-Total processes marked as killed              = 0
20160922:17:02:05:038101 gpinitsystem:office-5-56:company-[WARN]:-Total processes marked as failed              = 3 <<<<<
20160922:17:02:05:038101 gpinitsystem:office-5-56:company-[INFO]:------------------------------------------------
20160922:17:02:05:038101 gpinitsystem:office-5-56:company-[FATAL]:-Errors generated from parallel processes
20160922:17:02:05:038101 gpinitsystem:office-5-56:company-[INFO]:-Dumped contents of status file to the log file
20160922:17:02:05:038101 gpinitsystem:office-5-56:company-[INFO]:-Building composite backout file
20160922:17:02:05:gpinitsystem:office-5-56:company-[FATAL]:-Failures detected, see log file /Users/company/workspace/gpdb/gpAux/gpdemo/datadirs/gpAdminLogs/\
gpinitsystem_20160922.log for more detail Script Exiting!
```

**Contents of gpinitsystem log**

```
20160922:17:02:04:052603 gpcreateseg.sh:office-5-56:pivotal-[INFO]:-Commencing remote /Users/me/workspace/gpdb/gpAux/gpdemo/lalshell office-5-56.pa.company.io export GPHOME=/Users/me/workspace/gpdb/gpAux/greenplum-db-devel; . /Users/me/workspace/gpdb/gpAux/greenplum-db-devel/greenplum_path.sh; /Users/me/workspace/gpdb/gpAux/greenplum-db-devel/bin/lib/pysync.py -x pg_log -x postgresql.conf -x postmaster.pid /Users/me/workspace/gpdb/gpAux/gpdemo/datadirs/dbfast3/demoDataDir2 \[office-5-56.pa.company.io\]:/Users/me/workspace/gpdb/gpAux/gpdemo/datadirs/dbfast_mirror3/demoDataDir2
Permission denied (publickey,keyboard-interactive).^M
```

Upon digging into the `gpdb/gpAux/greenplum-db-devel/bin/lib/pysync.py`, I found that I could reproduce the issue simply by typing the below:

```
office-5-56:gpdemo me$ ssh -o BatchMode=yes office-5-56.pa.company.io
Permission denied (publickey,keyboard-interactive).
```

I was finally able to solve this by doing the below steps:

```
ssh-keygen #press enter 3 times
cat id_rsa.pub > authorized_keys
chmod u+w authorized_keys
```

---

I suggest we add these steps to the README.md. Any ideas?

**Comment by jimmyyih** [comment]
It's somewhat already mentioned in the README.md under Requirements -> http://gpdb.docs.pivotal.io/4360/prep_os-overview.html#topic1.

**Comment by amilkh** [comment]
Thanks @jimmyyih.
The only thing I found about ssh was the gpssh stuff below, but it doesn't seem to solve the issue.
http://gpdb.docs.pivotal.io/4360/prep_os-install-hosts.html#topic8

**Comment by amilkh** [comment]
@jimmyyih Is it alright to suggest the below to Docs team?

---
Could you please add the below to the [Mac OS X System Settings?](http://gpdb.docs.pivotal.io/4390/prep_os-system-params.html#topic6):

> - While logged in as the user that will run GPDB (gpadmin), run the below commands:
> ```
> ssh-keygen
> # press enter 3 times
> cat ~/.ssh/id_rsa.pub > ~/.ssh/authorized_keys
> chmod u+w ~/.ssh/authorized_keys
> ```

**Comment by amilkh** [comment]
@deepesh1081 @ivannovick any thoughts?

**Comment by danielgustafsson** [comment]
If adding this then please make sure to use an appending pipe to avoid overwriting existing authorized keys:
```bash
cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
```

**Comment by amilkh** [comment]
It may be better to just mentioned [gpssh-exkeys](http://gpdb.docs.pivotal.io/4390/install_guide/refs/gpssh-exkeys.html).

**Comment by ivannovick** [comment]
Assigning to @dyozie for docs updates

**Comment by Chibin** [comment]
You can do the following so you don't have to press enter 3 times. Generates a key with an empty pass phrase:
`ssh-keygen -N '' -f $HOME/id_rsa`

**Comment by ivannovick** [comment]
@mkiyama @dyozie did you guys get this one?

**Comment by mkiyama** [comment]
The Mac section was pulled from the GPDB InstallGuide.

**Comment by amilkh** [comment]
As @mkiyama mentioned, I no longer see a Mac OS X System Settings section in [Setting the Greenplum Recommended OS Parameters](http://gpdb.docs.pivotal.io/latest/prep_os-system-params.html), thus my suggested Docs update is not applicable.

Would still be nice to have this documented somewhere, but let's let this GitHub issue be the spot.
