### ISSUE TITLE
Hi guys, do we have planned release date of 7BETA or what is the status of 7ALPHA? 

### ISSUE THREAD

**Issue by qihuagao** [greenplum-db/gpdb#11518]
How's the features of upsert, partition and sequence by generating default which are support after postgres9.4 in 7ALPHA? 
Thanks in advance.

**Comment by wuj21** [comment]
The Postgresql 12 merging work has completed. Upsert, partition, etc are in master branch. So you can have a try with them. 
Release date of 7 BETA is not finalized.
