### ISSUE TITLE
How can I find the corresponding version of the code？

### ISSUE THREAD

**Issue by eejoin** [greenplum-db/gpdb#1152]
Gpdb hasn't tags on github, How can I find the corresponding version of the code?  for example, i want get the code of this version(PostgreSQL 8.2.15 (Greenplum Database 4.3.6.1 build 2)), is there  a corresponding source package on somewhere? please tell me the way, thanks

**Comment by danielgustafsson** [comment]
At the time of open sourcing the history was collapsed into a single origin commit, tags corresponding earlier non-open source versions (like 4.3.6.1) are thus not possible.

**Comment by ivannovick** [comment]
Hi, after our first open source release, Greenplum 5.0.0 we will have versions/tags in github.  As for now, we don't have them yet in open source.
