### ISSUE TITLE
About postgres 9.4.24

### ISSUE THREAD

**Issue by qihuagao** [greenplum-db/gpdb#11529]
### Greenplum version or build
PostgreSQL 9.4.24 (Greenplum Database 6.14.0 build commit:62d24f4a455276cab4bf2ca4538e96dcf58db8ba) on x86_64-unknown-linux-gnu, compiled by gcc (GCC) 6.4.0, 64-bit compiled on Feb  3 2021 19:35:00

We just installed latest released version of greenplum, and noticed default bind version of postgresql is 9.4.24,  is there some easy way of changing it to 9.6 when install.   Thank you.

**Comment by paul-guo-** [comment]
No, Greemplum 6 is based on Postgres 9.4 and we won't upgrade the Postgres version in Greenplum 6. If you want some features in Postgres 9.6 you could try the master branch (dev branch based on Postgres 12).

**Comment by qihuagao** [comment]
> No, Greemplum 6 is based on Postgres 9.4 and we won't upgrade the Postgres version in Greenplum 6. If you want some features in Postgres 9.6 you could try the master branch (dev branch based on Postgres 12).

Thank you very much for quick reply,   do you know what's stability of master release?  we need to put it on product environment.

**Comment by paul-guo-** [comment]
> > No, Greemplum 6 is based on Postgres 9.4 and we won't upgrade the Postgres version in Greenplum 6. If you want some features in Postgres 9.6 you could try the master branch (dev branch based on Postgres 12).
> 
> Thank you very much for quick reply, do you know what's stability of master release? we need to put it on product environment.

The master branch is a dev branch so please do not expect it that stable.

**Comment by qihuagao** [comment]
get it, thx a lot.
