### ISSUE TITLE
Test uao/compaction_utility_column from isolation2 suite may be flaky

### ISSUE THREAD

**Issue by asimrp** [greenplum-db/gpdb#11525]
### Greenplum version or build
PR #11490
### Step to reproduce the behavior
This failure is not reproducible.  The test failed once in PR pipeline: https://github.com/greenplum-db/gpdb/pull/11490#issuecomment-780319805

**Comment by wuj21** [comment]
close this issue since PR was merged.

**Comment by asimrp** [comment]
@wuj21 this issue is to track an unrelated test failure seen in the PR pipeline of the linked PR.  The linked PR does not fix this problem.

**Comment by QingMa-gp** [comment]
Test uao/compaction_utility_column did not fail in the most recent build. Close this issue.
