### ISSUE TITLE
gpstate causes an error message in the logs: "relation ""gpexpand.status"" does not exist"

### ISSUE THREAD

**Issue by volkovandr** [greenplum-db/gpdb#11554]
### Greenplum version or build
6.14.0

### OS version and uname -a
Ubuntu 18.04
Linux scarab1 4.15.0-124-generic #127-Ubuntu SMP Fri Nov 6 10:54:43 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

### Expected behavior
I execute gpstate, get the infos and see no errors anywhere

### Actual behavior
I execute gpstate, get the infos to the console. This part is fine.
But in the logs on the master server i see such messages:
`2021-02-23 10:39:36.214388 CET,"gpadmin","postgres",p3163,th423060672,"::1","28223",2021-02-23 10:39:36 CET,0,con1283,cmd12,seg-1,,dx9443,,sx1,"ERROR","42P01","relation ""gpexpand.status"" does not exist",,,,,,"`

### Step to reproduce the behavior
log_min_error_statement should be at least ERROR 
Just execute gpstate and check the logs.

I did some search, the issue seems to come from here:
https://github.com/greenplum-db/gpdb/blob/806fc86bc12d181b3f870da9e393296bc4e01030/gpMgmt/bin/gppylib/commands/gp.py#L1226
If no expansion is in progress, there is no gpexpand.status file and there is no gpexpand.status table. But the query is still executed in a try block. Logically it is fine, but it has this annoying side effect. I would suggest first checking whether the table is there, and only then querying it.

**Comment by ashwinstar** [comment]
Thanks for reporting @volkovandr. Interested to open Pull Request to fix the same?
