### ISSUE TITLE
初始化一直卡住“Completed restart of Greenplum instance in production mode”，psql postgres 命令也一直卡住

### ISSUE THREAD

**Issue by linyouyi** [greenplum-db/gpdb#11576]
[gpadmin@master ~]$ gpinitsystem -c gpconfigs/gpinitsystem_config -h gpconfigs/gpinitsystem_hostfile 
20210302:09:48:54:017684 gpinitsystem:master:gpadmin-[INFO]:-Checking configuration parameters, please wait...
20210302:09:48:54:017684 gpinitsystem:master:gpadmin-[INFO]:-Reading Greenplum configuration file gpconfigs/gpinitsystem_config
20210302:09:48:54:017684 gpinitsystem:master:gpadmin-[INFO]:-Locale has not been set in gpconfigs/gpinitsystem_config, will set to default value
20210302:09:48:55:017684 gpinitsystem:master:gpadmin-[INFO]:-Locale set to en_US.utf8
20210302:09:48:55:017684 gpinitsystem:master:gpadmin-[INFO]:-No DATABASE_NAME set, will exit following template1 updates
20210302:09:48:55:017684 gpinitsystem:master:gpadmin-[INFO]:-MASTER_MAX_CONNECT not set, will set to default value 250
20210302:09:48:55:017684 gpinitsystem:master:gpadmin-[INFO]:-Checking configuration parameters, Completed
20210302:09:48:55:017684 gpinitsystem:master:gpadmin-[INFO]:-Commencing multi-home checks, please wait...
...
20210302:09:48:57:017684 gpinitsystem:master:gpadmin-[INFO]:-Configuring build for standard array
20210302:09:48:57:017684 gpinitsystem:master:gpadmin-[INFO]:-Commencing multi-home checks, Completed
20210302:09:48:57:017684 gpinitsystem:master:gpadmin-[INFO]:-Building primary segment instance array, please wait...
...
20210302:09:49:03:017684 gpinitsystem:master:gpadmin-[INFO]:-Building group mirror array type , please wait...
...
20210302:09:49:08:017684 gpinitsystem:master:gpadmin-[INFO]:-Checking Master host
20210302:09:49:08:017684 gpinitsystem:master:gpadmin-[INFO]:-Checking new segment hosts, please wait...
......
20210302:09:49:31:017684 gpinitsystem:master:gpadmin-[INFO]:-Checking new segment hosts, Completed
20210302:09:49:31:017684 gpinitsystem:master:gpadmin-[INFO]:-Greenplum Database Creation Parameters
20210302:09:49:31:017684 gpinitsystem:master:gpadmin-[INFO]:---------------------------------------
20210302:09:49:31:017684 gpinitsystem:master:gpadmin-[INFO]:-Master Configuration
20210302:09:49:31:017684 gpinitsystem:master:gpadmin-[INFO]:---------------------------------------
20210302:09:49:31:017684 gpinitsystem:master:gpadmin-[INFO]:-Master instance name       = Greenplum
20210302:09:49:31:017684 gpinitsystem:master:gpadmin-[INFO]:-Master hostname            = master
20210302:09:49:31:017684 gpinitsystem:master:gpadmin-[INFO]:-Master port                = 5432
20210302:09:49:31:017684 gpinitsystem:master:gpadmin-[INFO]:-Master instance dir        = /home/gpadmin/data/master/gpseg-1
20210302:09:49:31:017684 gpinitsystem:master:gpadmin-[INFO]:-Master LOCALE              = en_US.utf8
20210302:09:49:31:017684 gpinitsystem:master:gpadmin-[INFO]:-Greenplum segment prefix   = gpseg
20210302:09:49:31:017684 gpinitsystem:master:gpadmin-[INFO]:-Master Database            = 
20210302:09:49:31:017684 gpinitsystem:master:gpadmin-[INFO]:-Master connections         = 250
20210302:09:49:31:017684 gpinitsystem:master:gpadmin-[INFO]:-Master buffers             = 128000kB
20210302:09:49:31:017684 gpinitsystem:master:gpadmin-[INFO]:-Segment connections        = 750
20210302:09:49:31:017684 gpinitsystem:master:gpadmin-[INFO]:-Segment buffers            = 128000kB
20210302:09:49:31:017684 gpinitsystem:master:gpadmin-[INFO]:-Checkpoint segments        = 8
20210302:09:49:31:017684 gpinitsystem:master:gpadmin-[INFO]:-Encoding                   = UNICODE
20210302:09:49:31:017684 gpinitsystem:master:gpadmin-[INFO]:-Postgres param file        = Off
20210302:09:49:31:017684 gpinitsystem:master:gpadmin-[INFO]:-Initdb to be used          = /usr/local/greenplum-db-6.14.1/bin/initdb
20210302:09:49:31:017684 gpinitsystem:master:gpadmin-[INFO]:-GP_LIBRARY_PATH is         = /usr/local/greenplum-db-6.14.1/lib
20210302:09:49:31:017684 gpinitsystem:master:gpadmin-[INFO]:-HEAP_CHECKSUM is           = on
20210302:09:49:31:017684 gpinitsystem:master:gpadmin-[INFO]:-HBA_HOSTNAMES is           = 0
20210302:09:49:31:017684 gpinitsystem:master:gpadmin-[INFO]:-Ulimit check               = Passed
20210302:09:49:31:017684 gpinitsystem:master:gpadmin-[INFO]:-Array host connect type    = Single hostname per node
20210302:09:49:31:017684 gpinitsystem:master:gpadmin-[INFO]:-Master IP address [1]      = ::1
20210302:09:49:31:017684 gpinitsystem:master:gpadmin-[INFO]:-Master IP address [2]      = 192.168.81.152
20210302:09:49:31:017684 gpinitsystem:master:gpadmin-[INFO]:-Master IP address [3]      = fe80::7e0f:3af0:1491:e770
20210302:09:49:31:017684 gpinitsystem:master:gpadmin-[INFO]:-Standby Master             = Not Configured
20210302:09:49:31:017684 gpinitsystem:master:gpadmin-[INFO]:-Number of primary segments = 1
20210302:09:49:31:017684 gpinitsystem:master:gpadmin-[INFO]:-Total Database segments    = 3
20210302:09:49:31:017684 gpinitsystem:master:gpadmin-[INFO]:-Trusted shell              = /usr/bin/ssh
20210302:09:49:31:017684 gpinitsystem:master:gpadmin-[INFO]:-Number segment hosts       = 3
20210302:09:49:31:017684 gpinitsystem:master:gpadmin-[INFO]:-Mirror port base           = 44000
20210302:09:49:31:017684 gpinitsystem:master:gpadmin-[INFO]:-Number of mirror segments  = 1
20210302:09:49:31:017684 gpinitsystem:master:gpadmin-[INFO]:-Mirroring config           = ON
20210302:09:49:31:017684 gpinitsystem:master:gpadmin-[INFO]:-Mirroring type             = Group
20210302:09:49:31:017684 gpinitsystem:master:gpadmin-[INFO]:----------------------------------------
20210302:09:49:31:017684 gpinitsystem:master:gpadmin-[INFO]:-Greenplum Primary Segment Configuration
20210302:09:49:31:017684 gpinitsystem:master:gpadmin-[INFO]:----------------------------------------
20210302:09:49:31:017684 gpinitsystem:master:gpadmin-[INFO]:-gp_segment_1 	33000 	gp_segment_1 	/home/gpadmin/data/primary/gpseg0 	2
20210302:09:49:31:017684 gpinitsystem:master:gpadmin-[INFO]:-gp_segment_2 	33000 	gp_segment_2 	/home/gpadmin/data/primary/gpseg1 	3
20210302:09:49:31:017684 gpinitsystem:master:gpadmin-[INFO]:-gp_segment_3 	33000 	gp_segment_3 	/home/gpadmin/data/primary/gpseg2 	4
20210302:09:49:32:017684 gpinitsystem:master:gpadmin-[INFO]:---------------------------------------
20210302:09:49:32:017684 gpinitsystem:master:gpadmin-[INFO]:-Greenplum Mirror Segment Configuration
20210302:09:49:32:017684 gpinitsystem:master:gpadmin-[INFO]:---------------------------------------
20210302:09:49:32:017684 gpinitsystem:master:gpadmin-[INFO]:-gp_segment_2 	44000 	gp_segment_2 	/home/gpadmin/data/mirror/gpseg0 	5
20210302:09:49:32:017684 gpinitsystem:master:gpadmin-[INFO]:-gp_segment_3 	44000 	gp_segment_3 	/home/gpadmin/data/mirror/gpseg1 	6
20210302:09:49:32:017684 gpinitsystem:master:gpadmin-[INFO]:-gp_segment_1 	44000 	gp_segment_1 	/home/gpadmin/data/mirror/gpseg2 	7

Continue with Greenplum creation Yy|Nn (default=N):
> y
20210302:10:01:17:017684 gpinitsystem:master:gpadmin-[INFO]:-Building the Master instance database, please wait...
20210302:10:01:25:017684 gpinitsystem:master:gpadmin-[INFO]:-Starting the Master in admin mode
20210302:10:01:29:017684 gpinitsystem:master:gpadmin-[INFO]:-Commencing parallel build of primary segment instances
20210302:10:01:29:017684 gpinitsystem:master:gpadmin-[INFO]:-Spawning parallel processes    batch [1], please wait...
...
20210302:10:01:29:017684 gpinitsystem:master:gpadmin-[INFO]:-Waiting for parallel processes batch [1], please wait...
................................
20210302:10:02:01:017684 gpinitsystem:master:gpadmin-[INFO]:------------------------------------------------
20210302:10:02:01:017684 gpinitsystem:master:gpadmin-[INFO]:-Parallel process exit status
20210302:10:02:01:017684 gpinitsystem:master:gpadmin-[INFO]:------------------------------------------------
20210302:10:02:01:017684 gpinitsystem:master:gpadmin-[INFO]:-Total processes marked as completed           = 3
20210302:10:02:01:017684 gpinitsystem:master:gpadmin-[INFO]:-Total processes marked as killed              = 0
20210302:10:02:01:017684 gpinitsystem:master:gpadmin-[INFO]:-Total processes marked as failed              = 0
20210302:10:02:01:017684 gpinitsystem:master:gpadmin-[INFO]:------------------------------------------------
20210302:10:02:01:017684 gpinitsystem:master:gpadmin-[INFO]:-Deleting distributed backout files
20210302:10:02:01:017684 gpinitsystem:master:gpadmin-[INFO]:-Removing back out file
20210302:10:02:01:017684 gpinitsystem:master:gpadmin-[INFO]:-No errors generated from parallel processes
20210302:10:02:01:017684 gpinitsystem:master:gpadmin-[INFO]:-Restarting the Greenplum instance in production mode
20210302:10:02:02:020369 gpstop:master:gpadmin-[INFO]:-Starting gpstop with args: -a -l /home/gpadmin/gpAdminLogs -m -d /home/gpadmin/data/master/gpseg-1
20210302:10:02:02:020369 gpstop:master:gpadmin-[INFO]:-Gathering information and validating the environment...
20210302:10:02:02:020369 gpstop:master:gpadmin-[INFO]:-Obtaining Greenplum Master catalog information
20210302:10:02:02:020369 gpstop:master:gpadmin-[INFO]:-Obtaining Segment details from master...
20210302:10:02:02:020369 gpstop:master:gpadmin-[INFO]:-Greenplum Version: 'postgres (Greenplum Database) 6.14.1 build commit:5ef30dd4c9878abadc0124e0761e4b988455a4bd Open Source'
20210302:10:02:02:020369 gpstop:master:gpadmin-[INFO]:-Commencing Master instance shutdown with mode='smart'
20210302:10:02:02:020369 gpstop:master:gpadmin-[INFO]:-Master segment instance directory=/home/gpadmin/data/master/gpseg-1
20210302:10:02:02:020369 gpstop:master:gpadmin-[INFO]:-Stopping master segment and waiting for user connections to finish ...
server shutting down
20210302:10:02:03:020369 gpstop:master:gpadmin-[INFO]:-Attempting forceful termination of any leftover master process
20210302:10:02:03:020369 gpstop:master:gpadmin-[INFO]:-Terminating processes for segment /home/gpadmin/data/master/gpseg-1
20210302:10:02:03:020369 gpstop:master:gpadmin-[ERROR]:-Failed to kill processes for segment /home/gpadmin/data/master/gpseg-1: ([Errno 3] No such process)
20210302:10:02:04:020392 gpstart:master:gpadmin-[INFO]:-Starting gpstart with args: -a -l /home/gpadmin/gpAdminLogs -d /home/gpadmin/data/master/gpseg-1
20210302:10:02:04:020392 gpstart:master:gpadmin-[INFO]:-Gathering information and validating the environment...
20210302:10:02:04:020392 gpstart:master:gpadmin-[INFO]:-Greenplum Binary Version: 'postgres (Greenplum Database) 6.14.1 build commit:5ef30dd4c9878abadc0124e0761e4b988455a4bd Open Source'
20210302:10:02:04:020392 gpstart:master:gpadmin-[INFO]:-Greenplum Catalog Version: '301908232'
20210302:10:02:04:020392 gpstart:master:gpadmin-[INFO]:-Starting Master instance in admin mode
20210302:10:02:04:020392 gpstart:master:gpadmin-[INFO]:-Obtaining Greenplum Master catalog information
20210302:10:02:04:020392 gpstart:master:gpadmin-[INFO]:-Obtaining Segment details from master...
20210302:10:02:04:020392 gpstart:master:gpadmin-[INFO]:-Setting new master era
20210302:10:02:04:020392 gpstart:master:gpadmin-[INFO]:-Master Started...
20210302:10:02:05:020392 gpstart:master:gpadmin-[INFO]:-Shutting down master
20210302:10:02:06:020392 gpstart:master:gpadmin-[INFO]:-Commencing parallel segment instance startup, please wait...
.
20210302:10:02:08:020392 gpstart:master:gpadmin-[INFO]:-Process results...
20210302:10:02:08:020392 gpstart:master:gpadmin-[INFO]:-----------------------------------------------------
20210302:10:02:08:020392 gpstart:master:gpadmin-[INFO]:-   Successful segment starts                                            = 3
20210302:10:02:08:020392 gpstart:master:gpadmin-[INFO]:-   Failed segment starts                                                = 0
20210302:10:02:08:020392 gpstart:master:gpadmin-[INFO]:-   Skipped segment starts (segments are marked down in configuration)   = 0
20210302:10:02:08:020392 gpstart:master:gpadmin-[INFO]:-----------------------------------------------------
20210302:10:02:08:020392 gpstart:master:gpadmin-[INFO]:-Successfully started 3 of 3 segment instances 
20210302:10:02:08:020392 gpstart:master:gpadmin-[INFO]:-----------------------------------------------------
20210302:10:02:08:020392 gpstart:master:gpadmin-[INFO]:-Starting Master instance master directory /home/gpadmin/data/master/gpseg-1 
20210302:10:02:08:020392 gpstart:master:gpadmin-[INFO]:-Command pg_ctl reports Master master instance active
20210302:10:02:08:020392 gpstart:master:gpadmin-[INFO]:-Connecting to dbname='template1' connect_timeout=15
20210302:10:02:23:020392 gpstart:master:gpadmin-[WARNING]:-Timeout expired connecting to template1, attempt 1/4
20210302:10:02:38:020392 gpstart:master:gpadmin-[WARNING]:-Timeout expired connecting to template1, attempt 2/4
20210302:10:02:53:020392 gpstart:master:gpadmin-[WARNING]:-Timeout expired connecting to template1, attempt 3/4
20210302:10:03:08:020392 gpstart:master:gpadmin-[WARNING]:-Timeout expired connecting to template1, attempt 4/4
20210302:10:03:08:020392 gpstart:master:gpadmin-[WARNING]:-Failed to connect to template1
20210302:10:03:08:020392 gpstart:master:gpadmin-[INFO]:-No standby master configured.  skipping...
20210302:10:03:08:020392 gpstart:master:gpadmin-[INFO]:-Check status of database with gpstate utility
20210302:10:03:09:017684 gpinitsystem:master:gpadmin-[INFO]:-Completed restart of Greenplum instance in production mode

**Comment by ShengtianM** [comment]
我和你一样的问题，最后发现是segment节点的防火墙未关闭，关闭segment节点防火墙后问题解决
