### ISSUE TITLE
Gpperfmon_Install Command Missing??

### ISSUE THREAD

**Issue by VinnyPembe** [greenplum-db/gpdb#11600]
### Greenplum version or build
6.14.1 (open-source-greenplum-db-6.14.1-rhel7-x86_64.rpm)

### OS version and uname -a
CentOS 7.9

###
Hello, I hope I'm posting this in the correct place; Apologies if I am not.

I've recently dealt with a 6.12.1 instance and noticed that the 'GPPERFMON_INSTALL' command file was missing from ${GPHOME}/bin. I found this odd, and assumed someone had just deleted it or something. However, I've just built a brand new 6.14.1 instance from scratch, and noticed again that the gpperfmon_install command file is missing.

Doing "find /* | grep gpperfmon" on my instance shows that there is a gpperfmon directory under ${MASTER_DATA_DIRECTORY}, and a gpperfmon_install_guide file under cli_help - Which talks about the aforementioned gpperfmon_install. So I can only assume it's meant to be there, or there is some way to get it.

I've searched online for over an hour and come up with absolutely nothing. Can anyone help with this? Or perhaps this is an actual issue undiscovered (though I doubt that).

Thanks in advance,
Vinny

**Comment by zhangh43** [comment]
gpperfmon is not recommend in GPDB6, metric_collector is the replacement of it. In GPDB master branch, gpperfmon is retired totally.
If you still want to use it, compile GPDB with option `--enable-gpperfmon`(default is false). It will require some additional package, please refer to `gpAux/gpperfmon/README.md` for details.

**Comment by VinnyPembe** [comment]
Well now I feel like a fool... haha. I still use GPCC on Licensed Greenplum, so I did not realise Gpperfmon was retired.

If Gpperfmon is indeed retired, then that is essentially okay; but is there any chance you can point me at how to install this 'metric_collector'. Such a vague name returns zero results in my search.

As my initial issue is effectively solved (thank you, Zhangh) I will close this issue.
