### ISSUE TITLE
gpstart may fail when command run through ssh doesn't execute /usr/local/bin/python3

### ISSUE THREAD

**Issue by zellerh** [greenplum-db/gpdb#11611]
Found this issue after upgrading to MacOS BigSur, where two python3 executables are present. One comes with MacOS in /usr/bin (version 3.8.2 in my case) and the other is installed by Homebrew in /usr/local/bin (version 3.9.2 in my case).

### Greenplum version or build
master (82b5d65c27)

### OS version and uname -a

MacOS BigSur 11.2.2
`Darwin xxxx.com 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64`

### autoconf options used ( config.status --config )

`CFLAGS=-O0 -g3 ./configure --prefix=/usr/local/gpdb --config-cache --without-zstd --disable-gpcloud --enable-debug --enable-depend --enable-orca --with-python --with-quicklz --enable-orafce --disable-gpfdist --enable-cassert`

### Expected behavior

Able to start GPDB with `gpstart`

### Actual behavior

Errors during gpstart

Symptoms: 

- `Error: unable to import module: No module named '_pg'`
- or `dlopen(/usr/local/gpdb/lib/python/_pg.so, 2): Symbol not found: _PyExc_StandardError` or
- or `Error: unable to import module: dlopen(/usr/local/gpdb/lib/python/psutil/_psutil_osx.so, 2): Symbol not found: __Py_ZeroStruct Referenced from: /usr/local/gpdb/lib/python/psutil/_psutil_osx.so Expected in: flat namespace in /usr/local/gpdb/lib/python/psutil/_psutil_osx.so`

The command that is run by gpstart looks like this: `ssh -o StrictHostKeyChecking=no -o ServerAliveInterval=60 my_local_host ". /usr/local/gpdb/greenplum_path.sh; $GPHOME/sbin/gpsegstart.py ..."`

Solution:

Make sure we use the python3 executable installed by Homebrew instead of the one provided with MacOS when we run an ssh command. The command `ssh localhost which python3` should return `/usr/local/bin/python3` and not `/usr/bin/python3`. I fixed this by adding `/usr/local/bin` to the front of the path in `~/.bashrc`.

### Step to reproduce the behavior

May depend on setup. In my case the issue happened on MacOS 11 (BigSur) when I didn't add `/usr/local/bin` in front of the path in .bashrc.

**Comment by ashwinstar** [comment]
I don't have Mac handy (and didn't use it recently, so this is more a guess.....). I doubt issue has to do with gpstart (or Greenplum) can work with Homebrew provided Python and not with MacOS provided one. Seems MacOS provided Python version is missing the PygreSQL corresponding to it while Homebrew has it which is causing the success vs failure.

**Comment by asimrp** [comment]
> Make sure we use the python3 executable installed by Homebrew instead of the one provided with MacOS when we run an ssh command.

That doesn't sound like a good solution to me.  Is it possible to check if all the required Python modules exist at build time?  May be through `./configure` or via some makefile under `gpMgmt`?

**Comment by zellerh** [comment]
Yes, @asimrp, thinking about this more I suspect that the real issue is that I built GPDB with Python 3.9.2 and then gpstart tried to run the gpsegstart.py program (via ssh) with Python 3.8.2. Looks like that isn't supported by Python?

**Comment by bradfordb-vmware** [comment]
w/ @ashuka24: We looked into this (or a very similar) issue on maOS Catalina (10.15.7) this morning. We should not be pip installing pygresql because the gpMgmt/bin/Makefile builds it against Greenplum's headers during installation. We did observe a compilation error when trying to build pygresql against GPDB

```console
In file included from pgmodule.c:181:
./pgconn.c:383:29: warning: implicit conversion changes signedness: 'ExecStatusType' to 'int' [-Wsign-conversion]
    if (result && (status = PQresultStatus(result)) != PGRES_TUPLES_OK)
                          ~ ^~~~~~~~~~~~~~~~~~~~~~
./pgconn.c:782:22: error: variable 'slen' is used uninitialized whenever 'if' condition is false [-Werror,-Wsometimes-uninitialized]
            else if (PyUnicode_Check(obj)) {
                     ^~~~~~~~~~~~~~~~~~~~
/usr/local/Cellar/python@3.9/3.9.2_1/Frameworks/Python.framework/Versions/3.9/include/python3.9/unicodeobject.h:115:18: note: expanded from macro 'PyUnicode_Check'
                 PyType_FastSubclass(Py_TYPE(op), Py_TPFLAGS_UNICODE_SUBCLASS)
```

which we worked around by setting a specific CFLAG when compiling pygresql:

```diff
- cd $(PYLIB_SRC_EXT)/$(PYGRESQL_DIR)/ && PATH=$(bindir):$$PATH LDFLAGS='$(LDFLAGS) $(PYGRESQL_LDFLAGS)' python3 setup.py build
+ cd $(PYLIB_SRC_EXT)/$(PYGRESQL_DIR)/ && PATH=$(bindir):$$PATH LDFLAGS='$(LDFLAGS) $(PYGRESQL_LDFLAGS)' CFLAGS='$(CFLAGS) -Wno-error=sometimes-uninitialized' python3 setup.py build
```

**Comment by adam8157** [comment]
For not releasing purpose, and we don't release for macOS, `pip3 install pygresql` is fine I suppose.

That uninitialized error is probably because of the differences between GCC and clang, we could consider bumping the bundled PyGreSQL if it fixed with a later version.

**Comment by lij55** [comment]
I managed to build GPDB with pygresql and python 3.9.10 on Ubuntu 22.04 with following command:
```
wget https://files.pythonhosted.org/packages/f3/cb/57020f422f088f5da83cf9897f7d7e100080e313e7e62092bc3bebd46e2a/PyGreSQL-5.2.3.tar.gz
tar xzf PyGreSQL-5.2.3.tar.gz
cd PyGreSQL-5.2.3
python3 setup.py install
```

`pip3 install pygresql` doesn't work indeed.

**Comment by fanfuxiaoran** [comment]
If you have python3 and python2 on your laptop at the same time, you can install pygresql as below
```
python3 -m pip install pygresql
```

**Comment by adam8157** [comment]
Closing.

Feel free to reopen this if `pygresql` is installed and `python3`, `pip3`, `ssh localhost python3` refer to the same Python.
