### ISSUE TITLE
No Binary keyword support in the copy command

### ISSUE THREAD

**Issue by Eulerizeit** [greenplum-db/gpdb#1162]
The Binary keyword is not supported in the COPY command. ( This was tested with 4.3.9.1).    But, the documentation implies that binary data can be loaded with COPY.  Has this been fixed in 5.0?

http://gpdb.docs.pivotal.io/4320/ref_guide/sql_commands/COPY.html

**Comment by hlinnaka** [comment]
No:

postgres=# copy foo from '/tmp/aaa'  with binary;
ERROR:  BINARY is not supported

**Comment by alldefector** [comment]
Comparing https://github.com/greenplum-db/gpdb/blob/ef42590d2e5f9d01ee5839d93b1d6b36fd2b1e9e/src/backend/commands/copy.c with https://github.com/postgres/postgres/blob/REL8_2_STABLE/src/backend/commands/copy.c (search for `->binary`), binary COPY was deliberately disabled in gpdb.

Would appreciate if someone could explain the rationale behind that and what's a good way to re-enable it.

**Comment by Eulerizeit** [comment]
The reason given was a performance improvement:
"This greatly simplifies the logic in COPY (and some external table) data processing, reduces complexity, removes many conditionals and allows the compiler to do a better job optimizing the code for faster execution. I don't have numbers but COPY (FROM file/STDIN) should get a good performance boost from reducing the CPU bottleneck on the QD a bit, and also external tables may benefit a little."

I'd like us to readdress whether we should add this functionality back.

**Comment by danielgustafsson** [comment]
Pushed in #1558, closing.
