### ISSUE TITLE
SELECT '' ,''  FROM table GROUP BY ROLLUP(1,2) ;SESSION CRASH

### ISSUE THREAD

**Issue by 1Makers1** [greenplum-db/gpdb#11646]
### Greenplum version or build
6.13
### OS version and uname -a
Linux 3.10.0-1062.9.1.el7.x86_64 #1 SMP Fri Dec 6 15:49:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
### Expected behavior
create table test_table  (a int , b int);
insert into test_table values (generate_series(1,10000),generate_series(1,10000)) ;
SELECT '' ,''  ,count(1) from  test_table  group by rollup(1,2) ;   
session dont crash
### Actual behavior
session crash 
postgres=#  SELECT '' ,''  ,count(1) from  test_table  group by rollup(1,2) ;           
ERROR:  Error on receive from seg0 slice1 : server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
### Step to reproduce the behavior
create table test_table  (a int , b int);
insert into test_table values (generate_series(1,10000),generate_series(1,10000)) ;
SELECT '' ,''  ,count(1) from  test_table  group by rollup(1,2) ;   

stack
1    0xbdf273 postgres StandardHandlerForSigillSigsegvSigbus_OnMainThread + 0x173
2    0x7fe2a3d655f0 libpthread.so.0 <symbol not found> + 0xa3d655f0
3    0x6dd542 postgres memtuple_getattr + 0x92
4    0xc3d355 postgres tupsort_prepare + 0x45
5    0xc3f71d postgres mk_qsort_impl + 0x43d
6    0xc3c8f8 postgres tuplesort_performsort_mk + 0x418
7    0x8eb3b5 postgres ExecSort + 0x385
8    0x8bcf48 postgres ExecProcNode + 0x2c8
9    0x8d6232 postgres ExecAgg + 0xf52
10   0x8bcf38 postgres ExecProcNode + 0x2b8
11   0x8ee4a4 postgres <symbol not found> + 0x8ee4a4
12   0x8bcff8 postgres ExecProcNode + 0x378
13   0x8d6232 postgres ExecAgg + 0xf52
14   0x8bcf38 postgres ExecProcNode + 0x2b8
15   0x8ee4a4 postgres <symbol not found> + 0x8ee4a4
16   0x8bcff8 postgres ExecProcNode + 0x378
17   0x8d6232 postgres ExecAgg + 0xf52
18   0x8bcf38 postgres ExecProcNode + 0x2b8
19   0x8fadcc postgres ExecMotion + 0x5c
20   0x8bcec8 postgres ExecProcNode + 0x248
21   0x8b48d5 postgres <symbol not found> + 0x8b48d5
22   0x8b5512 postgres standard_ExecutorRun + 0x3e2
23   0xa7f028 postgres <symbol not found> + 0xa7f028
24   0xa80c6f postgres PortalRun + 0x26f
25   0xa79338 postgres <symbol not found> + 0xa79338
26   0xa7e40d postgres PostgresMain + 0x222d
27   0x6c0f91 postgres <symbol not found> + 0x6c0f91
28   0xa05909 postgres PostmasterMain + 0x1099
29   0x6c5e8b postgres main + 0x1db
30   0x7fe2a310b505 libc.so.6 __libc_start_main + 0xf5
31   0x6d203f postgres <symbol not found> + 0x6d203f

**Comment by kainwen** [comment]
I believe this is the same issue as https://github.com/greenplum-db/gpdb/issues/10814

**Comment by kainwen** [comment]
Master branch does not have this bug because grouping sets part is refactored in master branch.

**Comment by kainwen** [comment]
Fixed by https://github.com/greenplum-db/gpdb/commit/367b80e76baf541a39c0baf44cb461fde18e9342
on 6X.
