### ISSUE TITLE
gserialized_estimate.c:911:8: error: too many arguments to function 'get_attstatsslot'         NULL, NULL, NULL, &floatptr, &nvalues);

### ISSUE THREAD

**Issue by bloodwolf2020** [greenplum-db/gpdb#11684]
![image](https://user-images.githubusercontent.com/46953147/111968274-f2523980-8b33-11eb-8f54-7325cf828ede.png)
an error occurred when i install postgis2.5.5

**Comment by wuj21** [comment]
Please providing the reproducing steps

**Comment by dpandhi-git** [comment]
Closing as no repro steps provided.
