### ISSUE TITLE
Can greenplum have not only 1 query point of master node?

### ISSUE THREAD

**Issue by gloCalHelp** [greenplum-db/gpdb#1171]
Dear Pioneer,

     greenplum seems really have a great performance of inserting and loading plenty other data sources , but  can greenplum have not only 1 query point of master node?  because only 1 query point of a server has a connection bottleneck.

     And in greenplum 4.3.8,  I have try PgBouncer with the  configuration of  not setting the master IP in a user-defined-database, but it seems not able to connect to datanode server and query to work.

**Comment by deepesh1081** [comment]
@gloCalHelp in Greenplum Master node( also known as Query Dispatcher) is the only server where clients can connect and query the cluster. Pgbouncer and other tool will also connect to the Master node and query the data.

**Comment by ivannovick** [comment]
This issue does not seem actionable.

**Comment by gloCalHelp** [comment]
@deepesh1081 
Dear Sir deepesh1081, 
 
      Thanks for your reply,  I know the solution to solve GPDB's connection bottleneck of only 1 master connection point now by contacting segments. Some GPDB commands can directly operate segments data but not necessarily contacting master, aren't they?
