### ISSUE TITLE
cache lookup failed for type XXX (format_type.c:135) when doing vacuum full analyze

### ISSUE THREAD

**Issue by soulfere** [greenplum-db/gpdb#11716]
### Greenplum version or build
Greenplum 6.3.0
### OS version and uname -a
CentOS 7.3
### Step to reproduce the behavior
When doing vacuum full analyze, SQL returns error: cache lookup failed for type 39530830 (format_type.c:135)  and vacumm full cannot continue.

**Comment by kainwen** [comment]
6.3 is quite old version. Would you please first try to upgrade your gpdb to latest version of gpdb6.X and then try?

**Comment by wuj21** [comment]
Greenplum 6.3.0 is pretty old. Try the latest 6.x Close this issue for now. Feel free to reopen when you see this issue in the latest 6.x.
