### ISSUE TITLE
如果嵌套的子查询里有指定字段，在外层进行rollup就会出问题(整个集群primary崩溃，自动切换到mirror)

### ISSUE THREAD

**Issue by ynqjwsm** [greenplum-db/gpdb#11712]
### Greenplum version or build
greenplum-db-6.12.1
### OS version and uname -a
Linux localhost 3.10.0-1160.6.1.el7.x86_64 #1 SMP Tue Nov 17 13:59:11 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

如果嵌套的子查询里有指定字段，在外层进行rollup就会出问题(整个集群primary崩溃，自动切换到mirror)。必须要先把子查询建成表。

2021-03-25 16:07:30.773427 CST,,,p3762,th0,,,2021-03-25 16:07:30 CST,0,con66502,cmd2,seg0,slice2,,,,"PANIC","XX000","Unexpected internal error: Segment process recei                                       ved signal SIGSEGV",,,,,,,0,,,,"1    0x7fe300c3d630 libpthread.so.0 <symbol not found> + 0xc3d630
2    0xc574a5 postgres tupsort_prepare (tuplesort_mk.c:3390)
3    0xc59c75 postgres mk_qsort_impl (tuplesort_mk_details.h:74)
4    0xc56997 postgres tuplesort_performsort_mk (tuplesort_mk_details.h:333)
5    0x8ede65 postgres ExecSort (tuplesort.h:417)
6    0x8bf4d8 postgres ExecProcNode (execProcnode.c:1089)
7    0x8d8a5a postgres ExecAgg (tuptable.h:159)
8    0x8bf4c8 postgres ExecProcNode (execProcnode.c:1093)
9    0x8f1248 postgres <symbol not found> (tuptable.h:159)
10   0x8bf588 postgres ExecProcNode (execProcnode.c:1039)
11   0x8d8a5a postgres ExecAgg (tuptable.h:159)
12   0x8bf4c8 postgres ExecProcNode (execProcnode.c:1093)
13   0x8f1248 postgres <symbol not found> (tuptable.h:159)
14   0x8bf588 postgres ExecProcNode (execProcnode.c:1039)
15   0x8d8a5a postgres ExecAgg (tuptable.h:159)
16   0x8bf4c8 postgres ExecProcNode (execProcnode.c:1093)
17   0x8f1248 postgres <symbol not found> (tuptable.h:159)
18   0x8bf588 postgres ExecProcNode (execProcnode.c:1039)
19   0x8d8a5a postgres ExecAgg (tuptable.h:159)
20   0x8bf4c8 postgres ExecProcNode (execProcnode.c:1093)
21   0x8f1248 postgres <symbol not found> (tuptable.h:159)
22   0x8bf588 postgres ExecProcNode (execProcnode.c:1039)
23   0x8d8a5a postgres ExecAgg (tuptable.h:159)
24   0x8bf4c8 postgres ExecProcNode (execProcnode.c:1093)
25   0x8f1248 postgres <symbol not found> (tuptable.h:159)
26   0x8bf588 postgres ExecProcNode (execProcnode.c:1039)
27   0x8d8a5a postgres ExecAgg (tuptable.h:159)
28   0x8bf4c8 postgres ExecProcNode (execProcnode.c:1093)
29   0x8f1248 postgres <symbol not found> (tuptable.h:159)
30   0x8bf588 postgres ExecProcNode (execProcnode.c:1039)
31   0x8d8a5a postgres ExecAgg (tuptable.h:159)
32   0x8bf4c8 postgres ExecProcNode (execProcnode.c:1093)
33   0x8d6484 postgres ExecAppend (tuptable.h:159)
34   0x8bf658 postgres ExecProcNode (execProcnode.c:978)
35   0x8fe670 postgres ExecMotion (tuptable.h:159)
36   0x8bf458 postgres ExecProcNode (execProcnode.c:1121)
37   0x8b6879 postgres <symbol not found> (tuptable.h:159)
38   0x8b75a4 postgres standard_ExecutorRun (execMain.c:2962)
39   0xa8b6b1 postgres <symbol not found> (pquery.c:290)
40   0xa8bbb3 postgres <symbol not found> (pquery.c:1487)
41   0xa8d307 postgres PortalRun (pquery.c:1022)
42   0xa85829 postgres <symbol not found> (postgres.c:1374)
43   0xa8a46c postgres PostgresMain (postgres.c:5388)
"
2021-03-25 16:07:30.773869 CST,,,p13721,th56862848,,,,0,,,seg0,,,,,"LOG","00000","server process (PID 3762) was terminated by signal 11: Segmentation fault","Failed                                        process was running: CREATE TABLE temp.TABLE_NAME AS
       select cast('201912' as varchar(10)) month_no
             ,nvl(b.branch_code2,'-1')     branch_code2
             ,nvl(b.branch_code3,'-1')     branch_code3
             ,nvl(b.branch_code4,'-1')     branch_code4
             ,nvl(b.branch_code5,'-1')     branch_code5
             ,nvl(a.class_type,'??????+??????') class_type
             ,nvl(a.type_name,'??????' )     type_name
             ,sum(a.month_amount_real)     own_mon_rl
         from (
               select a.*
                     ,'??????' class_type
                 from chnl_list.rpt_chl_own_rec_m a
                where a.month_no = '201912'
            ) a
        inner join exp_cfg.dim_zd_org_branch_tree_2020 b
           on a.branch_code5 =  b.branch_code
        group by rollup( b.branch_code2,b.branch_code3,b.branch_code4,b.branch_code5),rollup(a.class_type,a.type_name)
        DISTRIBUTED BY (branch_code5)
       ",,,,,,0,,"postmaster.c",3970,
2021-03-25 16:07:30.774035 CST,,,p13721,th56862848,,,,0,,,seg0,,,,,"LOG","00000","terminating any other active server processes",,,,,,,0,,"postmaster.c",3687,
2021-03-25 16:07:30.774053 CST,,,p42779,th56862848,,,,0,,,seg0,,,,,"WARNING","01000","ic-proxy-server: received signal 3",,,,,,,0,,"ic_proxy_main.c",379,
2021-03-25 16:07:30.774069 CST,,,p13721,th56862848,,,,0,,,seg0,,,,,"LOG","00000","worker process: ic proxy process (PID 42779) exited with exit code 1",,,,,,,0,,"pos                                       tmaster.c",3948,

**Comment by guofengrichard** [comment]
Could you please provide the query as well as the explain output for that query?

From the backtrace, it seems to be the issue being fixed by PR #11769

**Comment by adam8157** [comment]
Please try the latest, it's supposed to be fixed already. Closing. Feel free to reopen with more info if it's still a problem.
