### ISSUE TITLE
最新代码编译失败 “multiple definition of `max_packet_size'”

### ISSUE THREAD

**Issue by zhihuiFan** [greenplum-db/gpdb#11741]
### Greenplum version or build

当前的最新分支
commit db91ee4f3bd98737aab7cde35030a83d73354e03 (HEAD -> master, origin/master, origin/HEAD)
Author: zhaorui <zhaoru@vmware.com>
Date:   Wed Mar 31 10:20:39 2021 +0800

    Fix cases in gpfdist for dual stack solution. (#11728)

    If /proc/sys/net/ipv6/bindv6only is set to 0:
    In one case that if process A is already listening on ipv4 8080 port,
    the gpfdist cannot start successfully. But if process A is listening on
    ipv6 8080 port, the gpfdist can start successfully and will listen on
    ipv4 8080 port. But in this situation if one client tries to connect to
    gpfdist using ipv6 8080 port, it will connect to proccess A. Then the outcome
    is not what we want.

    If /proc/sys/net/ipv6/bindv6only is set to 1:
    In one case that if either process A or process B is already listening on
    either ipv4 8080 port or ipv6 8080 port, the gpfdist can still start
    successfully. In this situation if one client tries to connect to
    gpfdist using the port which process A or B is listening on, the outcome
    is not what we want.

    So in an environment which support both ipv4 or ipv6, this commit tries to make
    sure that only if gpfdist is listening on both ipv4 and ipv6 ports successfully,
    it will continue to run and try to handle clients requests. But there are some
    special environments that support only ipv4, in this env we have to make gpfdist
    starting successfully and listening on only ipv4 port.

### OS version and uname -a

Linux e18c07352.et15sqa 3.10.0-327.ali2008.alios7.x86_64 #1 SMP Tue Nov 29 17:56:13 CST 2016 x86_64 x86_64 x86_64 GNU/Linux

### autoconf options used ( config.status --config )

yizhi.fzh@e18c07352 /u/y/g/gpdb> ./configure --with-perl --with-python --with-libxml --with-gssapi --prefix=/usr/local/gpdb --without-zstd
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking which template to use... linux
checking for default port number... 5432
checking for block size... 32kB
checking for segment size... 1GB
checking for WAL block size... 32kB
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether /u01/yizhi/bin/llvm11.1.0/usr/local/bin/clang accepts -g... yes
checking for /u01/yizhi/bin/llvm11.1.0/usr/local/bin/clang option to accept ISO C89... none needed
checking for /u01/yizhi/bin/llvm11.1.0/usr/local/bin/clang option to accept ISO C99... none needed
checking whether we are using the GNU C++ compiler... yes
checking whether /u01/yizhi/bin/llvm11.1.0/usr/local/bin/clang++ accepts -g... yes
checking for gawk... gawk
checking whether /u01/yizhi/bin/llvm11.1.0/usr/local/bin/clang supports -Werror=vla, for CFLAGS... yes
checking whether /u01/yizhi/bin/llvm11.1.0/usr/local/bin/clang supports -Wendif-labels, for CFLAGS... yes
checking whether /u01/yizhi/bin/llvm11.1.0/usr/local/bin/clang++ supports -Wendif-labels, for CXXFLAGS... yes
checking whether /u01/yizhi/bin/llvm11.1.0/usr/local/bin/clang supports -Wmissing-format-attribute, for CFLAGS... yes
checking whether /u01/yizhi/bin/llvm11.1.0/usr/local/bin/clang++ supports -Wmissing-format-attribute, for CXXFLAGS... yes
checking whether /u01/yizhi/bin/llvm11.1.0/usr/local/bin/clang supports -Wformat-security, for CFLAGS... yes
checking whether /u01/yizhi/bin/llvm11.1.0/usr/local/bin/clang++ supports -Wformat-security, for CXXFLAGS... yes
checking whether /u01/yizhi/bin/llvm11.1.0/usr/local/bin/clang supports -fno-strict-aliasing, for CFLAGS... yes
checking whether /u01/yizhi/bin/llvm11.1.0/usr/local/bin/clang++ supports -fno-strict-aliasing, for CXXFLAGS... yes
checking whether /u01/yizhi/bin/llvm11.1.0/usr/local/bin/clang supports -fwrapv, for CFLAGS... yes
checking whether /u01/yizhi/bin/llvm11.1.0/usr/local/bin/clang++ supports -fwrapv, for CXXFLAGS... yes
checking whether /u01/yizhi/bin/llvm11.1.0/usr/local/bin/clang supports -fexcess-precision=standard, for CFLAGS... no
checking whether /u01/yizhi/bin/llvm11.1.0/usr/local/bin/clang++ supports -fexcess-precision=standard... no
checking whether /u01/yizhi/bin/llvm11.1.0/usr/local/bin/clang supports -Wno-unused-but-set-variable, for CFLAGS... no
checking whether /u01/yizhi/bin/llvm11.1.0/usr/local/bin/clang supports -Werror=implicit-fallthrough=3, for CFLAGS... no
checking whether /u01/yizhi/bin/llvm11.1.0/usr/local/bin/clang++ supports -fexcess-precision=standard, for CXXFLAGS... no
checking whether /u01/yizhi/bin/llvm11.1.0/usr/local/bin/clang supports -funroll-loops, for CFLAGS_VECTOR... yes
checking whether /u01/yizhi/bin/llvm11.1.0/usr/local/bin/clang supports -ftree-vectorize, for CFLAGS_VECTOR... yes
checking whether /u01/yizhi/bin/llvm11.1.0/usr/local/bin/clang supports -Wunused-command-line-argument, for NOT_THE_CFLAGS... yes
checking whether /u01/yizhi/bin/llvm11.1.0/usr/local/bin/clang supports -Wformat-truncation, for NOT_THE_CFLAGS... no
checking whether /u01/yizhi/bin/llvm11.1.0/usr/local/bin/clang supports -Wstringop-truncation, for NOT_THE_CFLAGS... no
checking whether /u01/yizhi/bin/llvm11.1.0/usr/local/bin/clang++ supports -Wdeprecated-register... yes
checking whether the C compiler still works... yes
checking how to run the C preprocessor... /u01/yizhi/bin/llvm11.1.0/usr/local/bin/clang -E
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking whether to build with ORCA... yes
checking whether to build with Greenplum Mapreduce... no
checking whether to build with gpcloud... no
checking whether /u01/yizhi/bin/llvm11.1.0/usr/local/bin/clang++ supports C++14 features with -std=c++14... yes
checking allow thread-safe client libraries... yes
checking whether to build with ICU support... no
checking whether to build with Tcl... no
checking whether to build Perl modules... yes
checking whether to build Python modules... yes
checking whether to build with GSSAPI support... yes
checking whether to build with PAM support... no
checking whether to build with BSD Authentication support... no
checking whether to build with LDAP support... no
checking whether to build with Bonjour support... no
checking whether to build with OpenSSL support... no
checking whether to build with SELinux support... no
checking whether to build with systemd support... no
checking for xml2-config... /usr/bin/xml2-config
checking whether to build with ZSTD support... no
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
configure: using CPPFLAGS= -D_GNU_SOURCE -I/usr/include/libxml2
configure: using LDFLAGS=
checking for ld used by GCC... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for ranlib... ranlib
checking for strip... strip
checking whether it is possible to strip libraries... yes
checking for ar... ar
checking for a BSD-compatible install... /usr/bin/install -c
checking for tar... /usr/bin/tar
checking whether ln -s works... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for bison... /usr/local/bin/bison
configure: using bison (GNU Bison) 3.6
checking for flex... /usr/bin/flex
configure: using flex 2.5.37
checking for perl... /usr/bin/perl
configure: using perl 5.16.3
checking for Perl archlibexp... /usr/lib64/perl5
checking for Perl privlibexp... /usr/share/perl5
checking for Perl useshrplib... true
checking for CFLAGS recommended by Perl... -D_REENTRANT -D_GNU_SOURCE -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64
checking for CFLAGS to compile embedded Perl...
checking for flags to link embedded Perl...   -fstack-protector  -L/usr/lib64/perl5/CORE -lperl -lresolv -lnsl -ldl -lm -lcrypt -lutil -lpthread -lc
checking for python3... /usr/local/bin/python3
configure: using python 3.7.2 (default, Jan  7 2019, 14:23:54)
checking for Python distutils module... yes
checking Python configuration directory... /home/tops/lib/python3.7/config-3.7m-x86_64-linux-gnu
checking Python include directories... -I/home/tops/include/python3.7m
checking how to link an embedded Python application... -L/home/tops/lib -lpython3.7m -lpthread -ldl  -lutil -lm
checking for a sed that does not truncate output... /usr/bin/sed
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking whether /u01/yizhi/bin/llvm11.1.0/usr/local/bin/clang is Clang... yes
checking whether Clang needs flag to prevent "argument unused" warning when linking with -pthread... no
checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
checking whether more special flags are required for pthreads... no
checking for PTHREAD_PRIO_INHERIT... yes
checking pthread.h usability... yes
checking pthread.h presence... yes
checking for pthread.h... yes
checking for strerror_r... yes
checking for getpwuid_r... yes
checking for gethostbyname_r... yes
checking whether strerror_r returns int... no
checking for main in -lm... yes
checking for library containing setproctitle... no
checking for library containing dlopen... -ldl
checking for library containing socket... none required
checking for library containing shl_load... no
checking for library containing getopt_long... none required
checking for library containing crypt... -lcrypt
checking for library containing shm_open... -lrt
checking for library containing shm_unlink... none required
checking for library containing clock_gettime... none required
checking for library containing fdatasync... none required
checking for library containing sched_yield... none required
checking for library containing gethostbyname_r... none required
checking for library containing shmget... none required
checking for library containing backtrace_symbols... none required
checking for library containing readline... -lreadline
checking for inflate in -lz... yes
checking for library containing gss_init_sec_context... -lgssapi_krb5
checking for apr-1-config... /usr/bin/apr-1-config
configure: using apr-1-config 1.4.8
checking for library containing apr_getopt_long... none required
checking for library containing event_add... -levent
checking for library containing yaml_parser_initialize... no
configure: WARNING: libyaml is not found. disabling transformations for gpfdist.
checking for clock_gettime in -lrt... yes
checking for xmlSaveToBuffer in -lxml2... yes
checking for curl-config... /usr/bin/curl-config
checking for curl >= 7.19.0... yes
checking CURL_CFLAGS...
checking CURL_LIBS... -lcurl
checking for BZ2_bzDecompress in -lbz2... yes
checking for strnicmp in -lxerces-c... yes
checking for Xerces-C... checking for stdbool.h that conforms to C99... yes
checking for _Bool... yes
checking atomic.h usability... no
checking atomic.h presence... no
checking for atomic.h... no
checking copyfile.h usability... no
checking copyfile.h presence... no
checking for copyfile.h... no
checking crypt.h usability... yes
checking crypt.h presence... yes
checking for crypt.h... yes
checking fp_class.h usability... no
checking fp_class.h presence... no
checking for fp_class.h... no
checking getopt.h usability... yes
checking getopt.h presence... yes
checking for getopt.h... yes
checking ieeefp.h usability... no
checking ieeefp.h presence... no
checking for ieeefp.h... no
checking ifaddrs.h usability... yes
checking ifaddrs.h presence... yes
checking for ifaddrs.h... yes
checking langinfo.h usability... yes
checking langinfo.h presence... yes
checking for langinfo.h... yes
checking mbarrier.h usability... no
checking mbarrier.h presence... no
checking for mbarrier.h... no
checking poll.h usability... yes
checking poll.h presence... yes
checking for poll.h... yes
checking sys/epoll.h usability... yes
checking sys/epoll.h presence... yes
checking for sys/epoll.h... yes
checking sys/ipc.h usability... yes
checking sys/ipc.h presence... yes
checking for sys/ipc.h... yes
checking sys/prctl.h usability... yes
checking sys/prctl.h presence... yes
checking for sys/prctl.h... yes
checking sys/procctl.h usability... no
checking sys/procctl.h presence... no
checking for sys/procctl.h... no
checking sys/pstat.h usability... no
checking sys/pstat.h presence... no
checking for sys/pstat.h... no
checking sys/resource.h usability... yes
checking sys/resource.h presence... yes
checking for sys/resource.h... yes
checking sys/select.h usability... yes
checking sys/select.h presence... yes
checking for sys/select.h... yes
checking sys/sem.h usability... yes
checking sys/sem.h presence... yes
checking for sys/sem.h... yes
checking sys/shm.h usability... yes
checking sys/shm.h presence... yes
checking for sys/shm.h... yes
checking sys/sockio.h usability... no
checking sys/sockio.h presence... no
checking for sys/sockio.h... no
checking sys/tas.h usability... no
checking sys/tas.h presence... no
checking for sys/tas.h... no
checking sys/un.h usability... yes
checking sys/un.h presence... yes
checking for sys/un.h... yes
checking termios.h usability... yes
checking termios.h presence... yes
checking for termios.h... yes
checking ucred.h usability... no
checking ucred.h presence... no
checking for ucred.h... no
checking utime.h usability... yes
checking utime.h presence... yes
checking for utime.h... yes
checking wchar.h usability... yes
checking wchar.h presence... yes
checking for wchar.h... yes
checking wctype.h usability... yes
checking wctype.h presence... yes
checking for wctype.h... yes
checking execinfo.h usability... yes
checking execinfo.h presence... yes
checking for execinfo.h... yes
checking for net/if.h... yes
checking for sys/ucred.h... no
checking for netinet/tcp.h... yes
checking readline/readline.h usability... yes
checking readline/readline.h presence... yes
checking for readline/readline.h... yes
checking readline/history.h usability... yes
checking readline/history.h presence... yes
checking for readline/history.h... yes
checking yaml.h usability... no
checking yaml.h presence... no
checking for yaml.h... no
configure: WARNING: header file <yaml.h> is not found. disabling transformations for gpfdist.
checking event.h usability... yes
checking event.h presence... yes
checking for event.h... yes
checking apr_getopt.h usability... yes
checking apr_getopt.h presence... yes
checking for apr_getopt.h... yes
checking zlib.h usability... yes
checking zlib.h presence... yes
checking for zlib.h... yes
checking bzlib.h usability... yes
checking bzlib.h presence... yes
checking for bzlib.h... yes
checking gssapi/gssapi.h usability... yes
checking gssapi/gssapi.h presence... yes
checking for gssapi/gssapi.h... yes
checking libxml/parser.h usability... yes
checking libxml/parser.h presence... yes
checking for libxml/parser.h... yes
checking for numa_available in -lnuma... no
checking numa.h usability... no
checking numa.h presence... no
checking for numa.h... no
checking time.h usability... yes
checking time.h presence... yes
checking for time.h... yes
checking whether byte ordering is bigendian... no
checking for inline... inline
checking for printf format archetype... printf
checking for flexible array members... yes
checking for signed types... yes
checking for __func__... yes
checking for _Static_assert... yes
checking for typeof... typeof
checking for __builtin_types_compatible_p... yes
checking for __builtin_constant_p... yes
checking for __builtin_unreachable... yes
checking for computed goto support... yes
checking for __builtin_frame_address... yes
checking whether struct tm is in sys/time.h or time.h... time.h
checking for struct tm.tm_zone... yes
checking for tzname... yes
checking for union semun... no
checking for struct sockaddr_un... yes
checking for struct sockaddr_storage... yes
checking for struct sockaddr_storage.ss_family... yes
checking for struct sockaddr_storage.__ss_family... no
checking for struct sockaddr_storage.ss_len... no
checking for struct sockaddr_storage.__ss_len... no
checking for struct sockaddr.sa_len... no
checking for struct addrinfo... yes
checking for intptr_t... yes
checking for uintptr_t... yes
checking for unsigned long long int... yes
checking for long long int... yes
checking for locale_t... yes
checking for C/C++ restrict keyword... __restrict
checking for struct cmsgcred... no
checking for struct option... yes
checking for z_streamp... yes
checking whether assembler supports x86_64 popcntq... yes
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
checking size of off_t... 8
checking size of bool... 1
checking for int timezone... yes
checking types of arguments for accept()... int, int, struct sockaddr *, socklen_t *
checking whether gettimeofday takes only one argument... no
checking for wcstombs_l declaration... no
checking for backtrace_symbols... yes
checking for cbrt... yes
checking for clock_gettime... yes
checking for copyfile... no
checking for fdatasync... yes
checking for getifaddrs... yes
checking for getpeerucred... no
checking for getrlimit... yes
checking for mbstowcs_l... no
checking for memmove... yes
checking for poll... yes
checking for posix_fallocate... yes
checking for ppoll... yes
checking for pstat... no
checking for pthread_is_threaded_np... no
checking for readlink... yes
checking for setproctitle... no
checking for setproctitle_fast... no
checking for setsid... yes
checking for shm_open... yes
checking for strchrnul... yes
checking for strsignal... yes
checking for symlink... yes
checking for sync_file_range... yes
checking for uselocale... yes
checking for utime... yes
checking for utimes... yes
checking for wcstombs_l... no
checking for getifaddrs... (cached) yes
checking for inet_ntop... yes
checking for __builtin_bswap16... yes
checking for __builtin_bswap32... yes
checking for __builtin_bswap64... yes
checking for __builtin_clz... yes
checking for __builtin_ctz... yes
checking for __builtin_popcount... yes
checking for fseeko... yes
checking for _LARGEFILE_SOURCE value needed for large files... no
checking how /u01/yizhi/bin/llvm11.1.0/usr/local/bin/clang reports undeclared, standard C functions... warning
checking for posix_fadvise... yes
checking whether posix_fadvise is declared... yes
checking whether fdatasync is declared... yes
checking whether strlcat is declared... no
checking whether strlcpy is declared... no
checking whether strnlen is declared... yes
checking whether F_FULLFSYNC is declared... no
checking whether RTLD_GLOBAL is declared... yes
checking whether RTLD_NOW is declared... yes
checking for struct sockaddr_in6...  yes
checking for PS_STRINGS... no
checking for isinf...  yes
checking for crypt... yes
checking for dlopen...  yes
checking for fls...  no
checking for getopt...  yes
checking for getrusage... yes
checking for inet_aton... yes
checking for mkdtemp... yes
checking for pread... yes
checking for pwrite... yes
checking for random... yes
checking for rint... yes
checking for srandom... yes
checking for strlcat... no
checking for strlcpy... no
checking for strnlen... yes
checking for strtof... yes
checking for unsetenv... yes
checking for getpeereid... no
checking for getaddrinfo... yes
checking for getopt_long... yes
checking for syslog... yes
checking syslog.h usability... yes
checking syslog.h presence... yes
checking for syslog.h... yes
checking for opterr... yes
checking for optreset... no
checking for strtoll... yes
checking for strtoull... yes
checking whether strtoll is declared... yes
checking whether strtoull is declared... yes
checking for builtin locking functions... yes
checking for rl_completion_append_character... yes
checking for rl_completion_matches... yes
checking for rl_filename_completion_function... yes
checking for rl_reset_screen_size... yes
checking for append_history... yes
checking for history_truncate_file... yes
checking test program... ok
checking whether long int is 64 bits... yes
checking for __builtin_mul_overflow... yes
checking size of void *... 8
checking size of size_t... 8
checking size of long... 8
checking alignment of short... 2
checking alignment of int... 4
checking alignment of long... 8
checking alignment of double... 8
checking for int8... no
checking for uint8... no
checking for int64... no
checking for uint64... no
checking for __int128... yes
checking for __int128 alignment bug... ok
checking alignment of PG_INT128_TYPE... 16
checking for builtin __sync char locking functions... yes
checking for builtin __sync int32 locking functions... yes
checking for builtin __sync int32 atomic operations... yes
checking for builtin __sync int64 atomic operations... yes
checking for builtin __atomic int32 atomic operations... yes
checking for builtin __atomic int64 atomic operations... yes
checking for __get_cpuid... yes
checking for __cpuid... no
checking for _mm_crc32_u8 and _mm_crc32_u32 with CFLAGS=... no
checking for _mm_crc32_u8 and _mm_crc32_u32 with CFLAGS=-msse4.2... yes
checking for __crc32cb, __crc32ch, __crc32cw, and __crc32cd with CFLAGS=... no
checking for __crc32cb, __crc32ch, __crc32cw, and __crc32cd with CFLAGS=-march=armv8-a+crc... no
checking which CRC-32C implementation to use... SSE 4.2 with runtime check
checking for special C compiler options needed for large files... (cached) no
checking for _FILE_OFFSET_BITS value needed for large files... (cached) no
checking size of off_t... (cached) 8
checking for library containing sem_init... -lpthread
checking which semaphore API to use... unnamed POSIX
checking for /dev/urandom... yes
checking which random number source to use... /dev/urandom
checking for perl.h... yes
checking for libperl... yes
checking Python.h usability... yes
checking Python.h presence... yes
checking for Python.h... yes
checking for xmllint... no
checking for xsltproc... /usr/bin/xsltproc
checking for fop... no
checking for dbtoepub... no
checking thread safety of required library functions... yes
checking whether /u01/yizhi/bin/llvm11.1.0/usr/local/bin/clang supports -Wl,--as-needed... yes
checking whether /u01/yizhi/bin/llvm11.1.0/usr/local/bin/clang supports -Werror=uninitialized, for CFLAGS... yes
checking whether /u01/yizhi/bin/llvm11.1.0/usr/local/bin/clang supports -Werror=implicit-function-declaration, for CFLAGS... yes
configure: using compiler=clang version 11.1.0 (https://github.com/llvm/llvm-project.git 1fdec59bffc11ae37eb51a1b9869f0696bfd5312)
configure: using CXX=/u01/yizhi/bin/llvm11.1.0/usr/local/bin/clang++ -std=c++14
configure: using CFLAGS=-Wall -Wmissing-prototypes -Wpointer-arith -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -Wno-unused-command-line-argument -Wno-misleading-indentation  -Werror=uninitialized -Werror=implicit-function-declaration
configure: using CXXFLAGS=-Wall -Wpointer-arith -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -Wno-deprecated-register -O3
configure: using CPPFLAGS= -D_GNU_SOURCE -I/usr/include/libxml2
configure: using LDFLAGS=  -Wl,--as-needed
configure: creating ./config.status
config.status: creating GNUmakefile
config.status: creating src/Makefile.global
config.status: creating src/include/pg_config.h
config.status: src/include/pg_config.h is unchanged
config.status: creating src/include/pg_config_ext.h
config.status: src/include/pg_config_ext.h is unchanged
config.status: creating src/interfaces/ecpg/include/ecpg_config.h
config.status: src/interfaces/ecpg/include/ecpg_config.h is unchanged
config.status: linking src/backend/port/tas/dummy.s to src/backend/port/tas.s
config.status: linking src/backend/port/posix_sema.c to src/backend/port/pg_sema.c
config.status: linking src/backend/port/sysv_shmem.c to src/backend/port/pg_shmem.c
config.status: linking src/include/port/linux.h to src/include/pg_config_os.h
config.status: linking src/makefiles/Makefile.linux to src/Makefile.port

# make

### Expected behavior

期望编译成功

### Actual behavior
Join2CrossProduct.o gporca/libgpopt/src/xforms/CXformLeftSemiJoin2HashJoin.o gporca/libgpopt/src/xforms/CXformLeftSemiJoin2InnerJoin.o gporca/libgpopt/src/xforms/CXformLeftSemiJoin2InnerJoinUnderGb.o gporca/libgpopt/src/xforms/CXformLeftSemiJoin2NLJoin.o gporca/libgpopt/src/xforms/CXformMaxOneRow2Assert.o gporca/libgpopt/src/xforms/CXformProject2Apply.o gporca/libgpopt/src/xforms/CXformProject2ComputeScalar.o gporca/libgpopt/src/xforms/CXformPushDownLeftOuterJoin.o gporca/libgpopt/src/xforms/CXformPushGbBelowJoin.o gporca/libgpopt/src/xforms/CXformPushGbDedupBelowJoin.o gporca/libgpopt/src/xforms/CXformPushGbWithHavingBelowJoin.o gporca/libgpopt/src/xforms/CXformRemoveSubqDistinct.o gporca/libgpopt/src/xforms/CXformResult.o gporca/libgpopt/src/xforms/CXformRightOuterJoin2HashJoin.o gporca/libgpopt/src/xforms/CXformSelect2Apply.o gporca/libgpopt/src/xforms/CXformSelect2BitmapBoolOp.o gporca/libgpopt/src/xforms/CXformSelect2DynamicIndexGet.o gporca/libgpopt/src/xforms/CXformSelect2Filter.o gporca/libgpopt/src/xforms/CXformSelect2IndexGet.o gporca/libgpopt/src/xforms/CXformSequenceProject2Apply.o gporca/libgpopt/src/xforms/CXformSimplifyGbAgg.o gporca/libgpopt/src/xforms/CXformSimplifyLeftOuterJoin.o gporca/libgpopt/src/xforms/CXformSimplifySubquery.o gporca/libgpopt/src/xforms/CXformSplitDQA.o gporca/libgpopt/src/xforms/CXformSplitGbAgg.o gporca/libgpopt/src/xforms/CXformSplitGbAggDedup.o gporca/libgpopt/src/xforms/CXformSplitLimit.o gporca/libgpopt/src/xforms/CXformSubqJoin2Apply.o gporca/libgpopt/src/xforms/CXformSubqueryUnnest.o gporca/libgpopt/src/xforms/CXformUnion2UnionAll.o gporca/libgpopt/src/xforms/CXformUnnestTVF.o gporca/libgpopt/src/xforms/CXformUpdate2DML.o gporca/libgpopt/src/xforms/CXformUtils.o gporca/libgpopt/src/xforms/CxformSelect2DynamicBitmapBoolOp.o gporca/libgpopt/src/exception.o gporca/libgpopt/src/init.o gpopt/config/CConfigParamMapping.o gpopt/translate/CMappingColIdVar.o gpopt/translate/CMappingVarColId.o gpopt/translate/CMappingElementColIdParamId.o gpopt/translate/CMappingColIdVarPlStmt.o gpopt/translate/CDXLTranslateContextBaseTable.o gpopt/translate/CCTEListEntry.o gpopt/translate/CContextDXLToPlStmt.o gpopt/translate/CDXLTranslateContext.o gpopt/translate/CQueryMutators.o gpopt/translate/CTranslatorScalarToDXL.o gpopt/translate/CTranslatorDXLToScalar.o gpopt/translate/CTranslatorUtils.o gpopt/translate/CTranslatorRelcacheToDXL.o gpopt/translate/CContextQueryToDXL.o gpopt/translate/CTranslatorQueryToDXL.o gpopt/translate/CTranslatorDXLToPlStmt.o gpopt/relcache/CMDProviderRelcache.o gpopt/utils/COptTasks.o gpopt/utils/CConstExprEvaluatorProxy.o gpopt/utils/CMemoryPoolPalloc.o gpopt/utils/CMemoryPoolPallocManager.o gpopt/utils/funcs.o gpopt/utils/RelationWrapper.o gpopt/CGPOptimizer.o gpopt/gpdbwrappers.o ../../src/port/libpgport_srv.a ../../src/common/libpgcommon_srv.a -L../../src/port -L../../src/common   -Wl,--as-needed -Wl,-rpath,'/usr/local/gpdb/lib',--enable-new-dtags  -Wl,-E -lpthread -lxerces-c -lbz2 -lxml2 -lrt -lgssapi_krb5 -lz -lrt -lcrypt -ldl -lm -lcurl -lpthread -o postgres
libpq/fe-secure-gssapi.o:(.bss+0x4010): multiple definition of `max_packet_size'
libpq/be-secure-gssapi.o:(.bss+0x4010): first defined here
clang-11: error: linker command failed with exit code 1 (use -v to see invocation)

### Step to reproduce the behavior
1. git clone 最新的代码
2. ./configure --with-perl --with-python --with-libxml --with-gssapi --prefix=/usr/local/gpdb --without-zstd
3. make

**Comment by JunfengYang** [comment]
This issue should same with https://github.com/greenplum-db/gpdb/issues/11772.
