### ISSUE TITLE
Error reading AO table file after VACUUM

### ISSUE THREAD

**Issue by oSkrobuk** [greenplum-db/gpdb#11785]
### Greenplum version or build
PostgreSQL 9.4.24 (Greenplum Database 6.12.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609, 64-bit compiled on Dec  2 2020 10:28:03

### OS version and uname -a
Linux hostname 4.19.62-13 #1 SMP Mon Jul 29 17:22:59 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

### Actual behavior
`ERROR: read beyond eof in table "table_1_prt_2021" file "base/12345/123456789.2", read position 0 (small offset 0), actual read length 0 (large read length 65536) (cdbbufferedread.c:211)  (seg90 slice1 IPv6:4002 pid=47175) (cdbbufferedread.c:211)`

```sql
SELECT * FROM table WHERE ...
```

### Step to reproduce the behavior
On 16:18:13 started `transaction 1`
On 16:20:11 started `transaction 2` and run query ```VACUUM ANALYZE table_1_prt_2021;``` and ```ANALYZE ROOTPARTITION table;```
On 16:23:00 `transaction 1` finished with error: `read beyond eof in table "table_1_prt_2021" file...```

It seems this should have been fixed in #790 but still exists in 6.12.1

Table DDL:
```sql
CREATE TABLE table (
    id character varying,
...
    created_dttm timestamp without time zone
)
WITH (appendonly='true', orientation='row', compresstype=zlib, compresslevel='2')
 DISTRIBUTED BY (id) PARTITION BY RANGE(created_dttm)
          (
          PARTITION "2019" START ('2019-01-01 00:00:00'::timestamp without time zone) END ('2020-01-01 00:00:00'::timestamp without time zone) WITH (appendonly='true', orientation='row', compresstype=zlib, compresslevel='2' ),

          PARTITION "2020" START ('2020-01-01 00:00:00'::timestamp without time zone) END ('2021-01-01 00:00:00'::timestamp without time zone) WITH (appendonly='true', orientation='row', compresstype=zlib, compresslevel='2' ),

          PARTITION "2021" START ('2021-01-01 00:00:00'::timestamp without time zone) END ('2022-01-01 00:00:00'::timestamp without time zone) WITH (appendonly='true', orientation='row', compresstype=zlib, compresslevel='2' ),

          PARTITION "2022" START ('2022-01-01 00:00:00'::timestamp without time zone) END ('2023-01-01 00:00:00'::timestamp without time zone) WITH (appendonly='true', orientation='row', compresstype=zlib, compresslevel='2' )
          );
```

**Comment by kainwen** [comment]
What does your transaction 1 do? Can you provide the SQL? Thanks.

**Comment by asimrp** [comment]
@oSkrobuk are you able to reproduce this issue?  Can you please share the SQL commands from transaction1 and transaction2, so that we can try to reproduce it?

**Comment by oSkrobuk** [comment]
Couldn't repeat the mistake. Here is the log of how it was: https://drive.google.com/file/d/1_hnbOpWghrwn6jgnc5J8o1UDZgvv4bGT/view?usp=sharing

The `ctl.loader_replace_by_key` function reads all dates of the `partition_column_name` column (it name is `created_dttm`) from `result_table` and deletes the data for the `partition_column_name` column in `target_table_name`

**Comment by dpandhi-git** [comment]
Closing as not reproducible
