### ISSUE TITLE
greenplum error, what's the reason for this error?please help

### ISSUE THREAD

**Issue by skimmilk6877** [greenplum-db/gpdb#1178]
select count(1) from xx.xxxx where hour_key=2016100416 limit 1;

ERROR:  VarBlock  is not valid. Valid block check error 10, detail 'offset 17973 at index 0 is bad -- must equal 8 (bytes_0_3 0x81007ea0, bytes_4_7 0x0000002f)' (appendonlyam.c:812)  (seg26 slice1 MPP09:40002 pid=13244) (cdbdisp.c:1526)
DETAIL:  
     Append-Only storage Small Content header: smallcontent_bytes_0_3 0x1900BC0F, smallcontent_bytes_4_7 0xE0C02279, headerKind = 1, executorBlockKind = 1, rowCount = 47, usingChecksums = false, header checksum 0x0, block checksum 0x0, dataLength 32518, compressedLength 8825, overallBlockLen 8840
     Scan of Append-Only Row-Oriented relation 'xxxx_1_prt_p_1h_2016100416'. Append-Only segment file 'base/17088/865925.1', block header offset in file = 108279384, bufferCount 12887

**Comment by asimrp** [comment]
@skimmilk6877 can you please provide steps to reproduce this?

**Comment by skimmilk6877** [comment]
@asimrp is this means the physical file broken？because this system is the production system，so I already     recover this problem. But I don't know what trigger this problem。I trancate the partition “xxxx_1_prt_p_1h_2016100416”，and the error is gone.


Actually,what I concerned most is  when this error appear,what can i do to skip or delete error line instead of truncate the whole partition ? Fortunately,I have partition ,but if I don not have , I have to truncate the whole table ..that is tragedy.

**Comment by ashwinstar** [comment]
Currently based on structure and layout of AO/CO tables just skipping a tuple will not allow to suppress the issue. Its more conveying problem with block which stores many tuples. Without further knowledge on the issue like reporting and scenario we won't be bale to take this forward. So, for now closing the issue. Please feel free to report agin if issue is seen and we can take it forward from there.
