### ISSUE TITLE
count(*) and count(*) over () performance difference

### ISSUE THREAD

**Issue by ryonchen** [greenplum-db/gpdb#11789]
I want to query the detail data and the total number of detail data. In general, this requires two sentences of SQL. For example, one is "select col1, col2, col3 from tb limit 50 offset 0", another one is "select count(*) from tb".In order to reduce the number of queries, I use "select col1, col2, col3, count(*) over () totol_count from tb" instead.
But I find that the latter(select col1, col2, col3, count(*) over () totol_count from tb limit 50 offset 0) is sometimes much slower than the former.Why???
What is the performance difference between the two methods？？？

**Comment by kainwen** [comment]
Can you please paste the result of

explain analyze of your both queries?

**Comment by ryonchen** [comment]
> Can you please paste the result of
> 
> explain analyze of your both queries?

This is an example：
**1、select col1, col2, col3 from tb limit 50 offset 0**
Limit  (cost=743828.93..747114.71 rows=200 width=287) (actual time=2290.254..2390.969 rows=200 loops=1)
  ->  Gather Motion 20:1  (slice3; segments: 20)  (cost=743828.93..747114.71 rows=200 width=287) (actual time=2290.248..2390.933 rows=200 loops=1)
        ->  Limit  (cost=743828.93..747110.71 rows=10 width=287) (actual time=2285.350..2385.507 rows=200 loops=1)
              ->  Hash Left Join  (cost=743828.93..307108249.22 rows=933531 width=287) (actual time=2285.318..2286.775 rows=200 loops=1)
                    Hash Cond: (a.admin_user_id = b.admin_id)
                    Extra Text: (seg14)  Hash chain length 1.1 avg, 3 max, using 14905 of 131072 buckets.Initial batch 0:

                    ->  Hash Right Join  (cost=738510.68..301329531.68 rows=933531 width=180) (actual time=2240.563..2241.582 rows=200 loops=1)
                          Hash Cond: (ui.user_id = a.live_student_id)
                          Extra Text: (seg14)  Initial batch 0:
(seg14)    Wrote 102629K bytes to inner workfile.
(seg14)    Wrote 15K bytes to outer workfile.
(seg14)  Hash chain length 5.4 avg, 43 max, using 86330 of 131072 buckets.  Skipped 1 empty batches.
                          ->  Broadcast Motion 20:20  (slice1; segments: 20)  (cost=0.00..854604.24 rows=3844192 width=16) (actual time=0.060..0.299 rows=1062 loops=1)
                                ->  Seq Scan on fact_user_info ui  (cost=0.00..47323.92 rows=192210 width=16) (actual time=11.569..29.433 rows=13780 loops=1)
                          ->  Hash  (cost=391171.08..391171.08 rows=933531 width=172) (actual time=2239.412..2239.412 rows=941454 loops=1)
                                ->  Seq Scan on adl_attend_record_student a  (cost=0.00..391171.08 rows=933531 width=172) (actual time=0.035..992.503 rows=941454 loops=1)
                    ->  Hash  (cost=2676.69..2676.69 rows=10567 width=111) (actual time=44.274..44.274 rows=15796 loops=1)
                          ->  Broadcast Motion 20:20  (slice2; segments: 20)  (cost=0.00..2676.69 rows=10567 width=111) (actual time=0.154..37.514 rows=15796 loops=1)
                                ->  Seq Scan on dim_auth_admin_user b  (cost=0.00..457.77 rows=529 width=111) (actual time=0.741..2.557 rows=826 loops=1)
                                      Filter: (data_status = 1)
Planning time: 1.744 ms
  (slice0)    Executor memory: 585K bytes.
  (slice1)    Executor memory: 60K bytes avg x 20 workers, 60K bytes max (seg0).
  (slice2)    Executor memory: 79K bytes avg x 20 workers, 79K bytes max (seg0).
* (slice3)    Executor memory: 137688K bytes avg x 20 workers, 137704K bytes max (seg14).  Work_mem: 107660K bytes max, 210243K bytes wanted.
Memory used:  262144kB
Memory wanted:  421484kB
Optimizer: Postgres query optimizer
Execution time: 43100.536 ms

**2、select count(*) from tb**
Aggregate  (cost=6123212.33..6123212.34 rows=1 width=8) (actual time=2339.615..2339.616 rows=1 loops=1)
  ->  Gather Motion 20:1  (slice2; segments: 20)  (cost=6123212.10..6123212.32 rows=1 width=8) (actual time=635.672..2339.433 rows=20 loops=1)
        ->  Aggregate  (cost=6123212.10..6123212.11 rows=1 width=8) (actual time=633.879..633.879 rows=1 loops=1)
              ->  Hash Left Join  (cost=5318.25..6076535.58 rows=933531 width=0) (actual time=10.343..2122.798 rows=941454 loops=1)
                    Hash Cond: (a.admin_user_id = b.admin_id)
                    Extra Text: (seg14)  Hash chain length 1.0 avg, 2 max, using 15689 of 1048576 buckets.
                    ->  Seq Scan on adl_attend_record_student a  (cost=0.00..391171.08 rows=933531 width=12) (actual time=0.045..413.148 rows=941454 loops=1)
                    ->  Hash  (cost=2676.69..2676.69 rows=10567 width=4) (actual time=4.963..4.963 rows=15796 loops=1)
                          ->  Broadcast Motion 20:20  (slice1; segments: 20)  (cost=0.00..2676.69 rows=10567 width=4) (actual time=0.086..1.963 rows=15796 loops=1)
                                ->  Seq Scan on dim_auth_admin_user b  (cost=0.00..457.77 rows=529 width=4) (actual time=0.054..0.970 rows=826 loops=1)
                                      Filter: (data_status = 1)
Planning time: 3.970 ms
  (slice0)    Executor memory: 156K bytes.
  (slice1)    Executor memory: 58K bytes avg x 20 workers, 58K bytes max (seg0).
  (slice2)    Executor memory: 9400K bytes avg x 20 workers, 9400K bytes max (seg0).  Work_mem: 371K bytes max.
Memory used:  262144kB
Optimizer: Postgres query optimizer
Execution time: 2380.302 ms

**3、select col1, col2, col3, count(*) over () totol_count from tb limit 50 offset 0**
Limit  (cost=743828.93..747113.21 rows=200 width=287) (actual time=57787.942..57788.339 rows=200 loops=1)
  ->  WindowAgg  (cost=743828.93..307341631.82 rows=18670608 width=287) (actual time=57787.936..57788.310 rows=200 loops=1)
        ->  Gather Motion 20:1  (slice3; segments: 20)  (cost=743828.93..307014896.18 rows=18670608 width=287) (actual time=1514.368..32796.802 rows=18735134 loops=1)
              ->  Hash Left Join  (cost=743828.93..307014896.18 rows=933531 width=287) (actual time=3037.492..24087.528 rows=941454 loops=1)
                    Hash Cond: (a.admin_user_id = b.admin_id)
                    Extra Text: (seg14)  Hash chain length 1.1 avg, 4 max, using 14068 of 65536 buckets.Initial batch 0:

                    ->  Hash Right Join  (cost=738510.68..301329531.68 rows=933531 width=180) (actual time=3025.370..21584.755 rows=941454 loops=1)
                          Hash Cond: (ui.user_id = a.live_student_id)
                          Extra Text: (seg14)  Initial batch 0:
(seg14)    Wrote 153542K bytes to inner workfile.
(seg14)    Wrote 76317K bytes to outer workfile.
(seg14)  Initial batches 1..3:
(seg14)    Read 153542K bytes from inner workfile: 51181K avg x 3 nonempty batches, 51445K max.
(seg14)    Read 76317K bytes from outer workfile: 25439K avg x 3 nonempty batches, 25470K max.
(seg14)  Hash chain length 4.3 avg, 42 max, using 218407 of 524288 buckets.
                          ->  Broadcast Motion 20:20  (slice1; segments: 20)  (cost=0.00..854604.24 rows=3844192 width=16) (actual time=0.038..13052.180 rows=3854245 loops=1)
                                ->  Seq Scan on fact_user_info ui  (cost=0.00..47323.92 rows=192210 width=16) (actual time=15.760..60.182 rows=193067 loops=1)
                          ->  Hash  (cost=391171.08..391171.08 rows=933531 width=172) (actual time=3024.259..3024.259 rows=941454 loops=1)
                                ->  Seq Scan on adl_attend_record_student a  (cost=0.00..391171.08 rows=933531 width=172) (actual time=0.024..1746.079 rows=941454 loops=1)
                    ->  Hash  (cost=2676.69..2676.69 rows=10567 width=111) (actual time=10.072..10.072 rows=15796 loops=1)
                          ->  Broadcast Motion 20:20  (slice2; segments: 20)  (cost=0.00..2676.69 rows=10567 width=111) (actual time=0.076..4.958 rows=15796 loops=1)
                                ->  Seq Scan on dim_auth_admin_user b  (cost=0.00..457.77 rows=529 width=111) (actual time=0.065..0.816 rows=826 loops=1)
                                      Filter: (data_status = 1)
Planning time: 3.735 ms
  (slice0)    Executor memory: 532307K bytes.
  (slice1)    Executor memory: 60K bytes avg x 20 workers, 60K bytes max (seg0).
  (slice2)    Executor memory: 79K bytes avg x 20 workers, 79K bytes max (seg0).
* (slice3)    Executor memory: 71632K bytes avg x 20 workers, 71632K bytes max (seg0).  Work_mem: 54358K bytes max, 215772K bytes wanted.
Memory used:  262144kB
Memory wanted:  648215kB
Optimizer: Postgres query optimizer
Execution time: 59277.469 ms

**Comment by kainwen** [comment]
I do not think this is an issue. The SQL 3 is a window agg. It is different from SQL 2.

Feel free to reopen this or comment here if you have more questions.

**Comment by kainwen** [comment]
I do not think this is an issue. The SQL 3 is a window agg. It is different from SQL 2.

Feel free to reopen this or comment here if you have more questions.
