### ISSUE TITLE
Delta Lake Read Support

### ISSUE THREAD

**Issue by ashishmgofficial** [greenplum-db/gpdb#11792]
### Greenplum version or build
5.x and above

Does Greenplum support Delta Lake tables from object stores like S3 ( like PrestoDB etc ) ? . If not, is there any plan for the same in near future ?

### Context

My Client has been using Greenplum for a long time as there Data Warehouse. We are writing a lot of dataset as Delta table in S3 , from where the client intends to create external tables for GreenPlum to read the delta records.

**Comment by wuj21** [comment]
Can you describe Delta Lake and Delta table?

**Comment by ashishmgofficial** [comment]
Delta lake is a data lake solution by Databricks which is basically a library on top of apache Spark. It provides ACID functionalities, time travel etc on data lakes

**Comment by hejatibor** [comment]
Check this:
https://gpdb.docs.pivotal.io/pxf/6-0/using/access_objstore.html

**Comment by ashishmgofficial** [comment]
> Check this:
> https://gpdb.docs.pivotal.io/pxf/6-0/using/access_objstore.html

This will read the entire parquet files in the s3 location right ? Since delta stores multiple versions of parquet for time travel, wouldn't current solution read duplicates ?

Also I guess current GP external tables don't support reading partitions

**Comment by johnnyflute** [comment]
how to join this ^_^

**Comment by lij55** [comment]
> Does this feature work in process, How to make a contribute

thanks for the contribution, @johnnyflute 
You can use this group to discuss the proposal: https://groups.google.com/a/greenplum.org/g/gpdb-dev, then feel free to raise the PR for review when the work is done.

Greenplum has s3 external table which can only read the entire file in a batch. we don't have presto experience. could you share us some doc about how PrestoDB does with the Delta Lake? it would help us to understand the use case. thanks in advance.

**Comment by lij55** [comment]
closing this issue as it is in the scope of PXF which locates in its own repo.
