### ISSUE TITLE
YAML variable support for gpload

### ISSUE THREAD

**Issue by CC-Hsu** [greenplum-db/gpdb#11796]
Hi, Team,

Will GPDB project consider variable substitution support for gpload YAML files?
https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html
https://stackoverflow.com/questions/41620674/use-placeholders-in-yaml
https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch
https://github.com/mybuilder/kongfig/issues/96
https://docs.greatexpectations.io/en/0.11.6/how_to_guides/configuring_data_contexts/how_to_use_a_yaml_file_or_environment_variables_to_populate_credentials.html

For example, users can pass value into gpload to substitute for variables and it might be useful for `MAPPING` expressions or some other configurations (`PORT`, `FILE`, etc.).

Thanks.

**Comment by wuj21** [comment]
@lij55 it is requirement for gpload

**Comment by lij55** [comment]
Hi @CC-Hsu 
gpss supports similar yaml config format and has more features. gpss has `property` parameter just for the same purpose. please consider gpss for such use case. closing this gpload issue. thanks.
