### ISSUE TITLE
GCC 10.0 compiling failure due to multiple definition in libpg

### ISSUE THREAD

**Issue by HaozhouWang** [greenplum-db/gpdb#11801]
### Greenplum version or build
master
### autoconf options used ( config.status --config )
--with-gssapi
### Installation information ( pg_config )

ld error
### Step to reproduce the behavior

When using GCC 10.0+, the compiler will give an error said
```
/usr/bin/ld: libpq/fe-secure-gssapi.o:/home/gpadmin/workspace/gpdb/src/backend/libpq/fe-secure-gssapi.c:68: multiple definition of `max_packet_size'; libpq/be-secure-gssapi.o:/home/gpadmin/workspace/gpdb/src/backend/libpq/be-secure-gssapi.c:68: first defined here
```

This might be both 
```
https://github.com/greenplum-db/gpdb/blob/6f7ab8ada5fafc921d63243706a22db7162b2964/src/backend/libpq/be-secure-gssapi.c#L68
```
And
```
https://github.com/greenplum-db/gpdb/blob/6f7ab8ada5fafc921d63243706a22db7162b2964/src/backend/libpq/be-secure-gssapi.c#L68
```
contains the same variable without static keywords
```
uint32		max_packet_size;
```
PG 12 does not have this issue.

It seems `max_packet_size` is used in local, could we add `static` or backport the PG 12 changes into these two files

**Comment by paul-guo-** [comment]
I think there have been a dup github issue of this.

**Comment by HaozhouWang** [comment]
Thanks @paul-guo- , could you please help me to point out the dup issue, and I will close this one.

**Comment by paul-guo-** [comment]
https://github.com/greenplum-db/gpdb/issues/11772

**Comment by HaozhouWang** [comment]
Thanks @paul-guo- , closed
