### ISSUE TITLE
Vacuum on catalog tables does not make space reused, causing catalog grow extremely

### ISSUE THREAD

**Issue by sokolval** [greenplum-db/gpdb#11825]
### autoconf options used 
'--build=x86_64-linux-gnu' '--prefix=/usr' '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' '--sysconfdir=/etc' '--localstatedir=/var' '--disable-silent-rules' '--libdir=${prefix}/lib/x86_64-linux-gnu' '--libexecdir=${prefix}/lib/x86_64-linux-gnu' '--disable-maintainer-mode' '--disable-dependency-tracking' '--with-perl' '--with-python' '--without-gssapi' '--disable-gpcloud' '--with-libxml' '--with-system-tzdata=/usr/share/zoneinfo' '--prefix=/usr/local/gpdb' 'build_alias=x86_64-linux-gnu' 'CFLAGS=-g -O2 -fstack-protector-strong -Wformat -Werror=format-security' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'CXXFLAGS=-g -O2 -fstack-protector-strong -Wformat -Werror=format-security'

### Installation information ( pg_config )
BINDIR = /usr/local/gpdb/bin
DOCDIR = /usr/local/gpdb/share/doc/postgresql
HTMLDIR = /usr/local/gpdb/share/doc/postgresql
INCLUDEDIR = /usr/local/gpdb/include
PKGINCLUDEDIR = /usr/local/gpdb/include/postgresql
INCLUDEDIR-SERVER = /usr/local/gpdb/include/postgresql/server
LIBDIR = /usr/local/gpdb/lib/x86_64-linux-gnu
PKGLIBDIR = /usr/local/gpdb/lib/x86_64-linux-gnu/postgresql
LOCALEDIR = /usr/local/gpdb/share/locale
MANDIR = /usr/local/gpdb/share/man
SHAREDIR = /usr/local/gpdb/share/postgresql
SYSCONFDIR = /etc/postgresql
PGXS = /usr/local/gpdb/lib/x86_64-linux-gnu/postgresql/pgxs/src/makefiles/pgxs.mk
CONFIGURE = '--build=x86_64-linux-gnu' '--prefix=/usr' '--includedir=/usr/local/gpdb/include' '--mandir=/usr/local/gpdb/share/man' '--infodir=/usr/local/gpdb/share/info' '--sysconfdir=/etc' '--localstatedir=/var' '--disable-silent-rules' '--libdir=/usr/local/gpdb/lib/x86_64-linux-gnu' '--libexecdir=/usr/local/gpdb/lib/x86_64-linux-gnu' '--disable-maintainer-mode' '--disable-dependency-tracking' '--with-perl' '--with-python' '--without-gssapi' '--disable-gpcloud' '--with-libxml' '--with-system-tzdata=/usr/share/zoneinfo' '--prefix=/usr/local/gpdb' 'build_alias=x86_64-linux-gnu' 'CFLAGS=-g -O2 -fstack-protector-strong -Wformat -Werror=format-security' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'CXXFLAGS=-g -O2 -fstack-protector-strong -Wformat -Werror=format-security'
CC = gcc
CPPFLAGS = -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2 -I/usr/local/gpdb/include
CFLAGS = -Wall -Wmissing-prototypes -Wpointer-arith -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fno-aggressive-loop-optimizations -Wno-unused-but-set-variable -Wno-address -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -std=gnu99 -Werror=uninitialized -Werror=implicit-function-declaration -I/usr/local/gpdb/include
CFLAGS_SL = -fPIC
LDFLAGS = -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,--as-needed -Wl,-rpath,'/usr/local/gpdb/lib/x86_64-linux-gnu',--enable-new-dtags -L/usr/local/gpdb/lib/x86_64-linux-gnu
LDFLAGS_EX = 
LDFLAGS_SL = 
LIBS = -lpgcommon -lpgport -lxerces-c -lxml2 -lrt -lzstd -lrt -lcrypt -ldl -lm -L/usr/local/gpdb/lib/x86_64-linux-gnu
VERSION = PostgreSQL 9.4.24

### Expected behavior
After running vacuum on catalog tables, tuples are released and new tuples are created in the freed space

### Actual behavior
New space is occupied each time even after vacuum executed regularly once every hour

### Step to reproduce the behavior
1. measure size as:
  select pg_total_relation_size('pg_class')+pg_total_relation_size('pg_namespace')+pg_total_relation_size('pg_attribute')+pg_total_relation_size('pg_depend')+pg_total_relation_size('pg_shdepend')+pg_total_relation_size('pg_statistic')+pg_total_relation_size('pg_attribute_relid_attnam_index')+pg_total_relation_size('pg_attribute_relid_attnum_index')+pg_total_relation_size('pg_stat_last_operation')+pg_total_relation_size('pg_type')+pg_total_relation_size('pg_constraint')+pg_total_relation_size('pg_depend_depender_index')+pg_total_relation_size('pg_attribute_encoding')+pg_total_relation_size('pg_depend_reference_index')+pg_total_relation_size('pg_class_relname_nsp_index')+pg_total_relation_size('pg_partition_rule') as size
2. Perform temporary objects creation and drop 
3. Perform vacuum as per regular maintenenance: 
   SYSTABLES="' pg_catalog.' || relname || ';' from pg_class a, pg_namespace b where a.relnamespace=b.oid and b.nspname='pg_catalog' and a.relkind='r'"
4.   psql -tc "SELECT 'VACUUM' || $SYSTABLES" ${DB} | psql -a ${DB} >> $LOGFILE 
5. Perform temporary objects creation and drop 
6. measure size as in point 1.

Size of catalog is getting increased, though vacuum of catalog is expected to allow filling empty pages in datafile of the catalog.

**Comment by sokolval** [comment]
<img width="1295" alt="image" src="https://user-images.githubusercontent.com/43939614/115015346-2b27c900-9ebc-11eb-8d84-4e6af6583ec9.png">

Vacuum is performed hourly. 
Cleaning of orphaned schemas is performed daily 10:30 PM

**Comment by adam8157** [comment]
Which specific catalog table bloats? Or each of the 16 tables you monitor do bloat?

**Comment by asimrp** [comment]
Please note that `vacuum full` is expected to reclaim space, any other forms of `vacuum` are not expected to reclaim space.  What form of vacuum is run in your environment, @sokolval ?

**Comment by sokolval** [comment]
> Which specific catalog table bloats? Or each of the 16 tables you monitor do bloat?
Graphics shows sum for several objects. Most contributing are: pg_attribute, pg_statistic, pg_depend, pg_attribute_encoding, pg_stat_last_operation, pg_class, pg_constraint.

> Please note that `vacuum full` is expected to reclaim space, any other forms of `vacuum` are not expected to reclaim space. What form of vacuum is run in your environment, @sokolval ?

I agree that vacuum full is expected to reclaim disk space and once it is run, disk space is returned and datafiles get shrunk.
My expectation is that since temporary objects are created and then dropped and created again, and also temporary schemas are dropped on a regular basis, so once objects are dropped and **vacuum** run (without full), the space is not returned to OS. However I expect that blocks inside file are marked as unused and once new row created in table it occupy that released empty space in block occupied in datafile. Is my expectation wrong here?

**Comment by sokolval** [comment]
<img width="1247" alt="image" src="https://user-images.githubusercontent.com/43939614/115863927-d7c6f500-a43e-11eb-9840-0b2c7897f22d.png">
As you may notice on Mar 11, 24, Apr 13 there was vacuum full run, however despite vacuum (simple) run hourly it is obvious that space is not reused.

**Comment by JunfengYang** [comment]
The VACUUM(without FULL) simply reclaims space and makes it available for re-use, extra space is not returned to the operating system (in most cases). So you can see from 04/02 - 04/13, the increase is slow.
This catalog size incremental actually depends on your workload, during a normal vacuum, it holds ShareUpdateExclusiveLock, so if other transactions access the same table, the vacuum will skip the page it can not acquire a lock on. So no space to reuse.
Or your workload creates lots of relations in a short time without any dead tuples to reclaims, it'll of course increase sharply.

**Comment by JunfengYang** [comment]
Close this issue for now, feel free to reopen it if you can provide more info.
