### ISSUE TITLE
Atomicity is broken in COPY statement

### ISSUE THREAD

**Issue by smmsmm1988** [greenplum-db/gpdb#11830]
### Greenplum version or build
PostgreSQL 9.4.24 (Greenplum Database 6.15.0+dev.72.gb85c008c07 build dev) on x86_64-unknown-linux-gnu, compiled by gcc (GCC) 8.3.1 20190604, 64-bit compiled on Apr 19 2021 17:21:23

### Actual behavior

![image](https://user-images.githubusercontent.com/7722001/115214025-b4e1cb80-a134-11eb-9f71-319818a4611c.png)

In COPY statement, when more than one segment are involved, two-phase commit MUST be used. However,  gpdb sometimes uses two-phase commit, sometimes uses one-phase commit. Under one-phase commit, the atomicity across multiple segments CANNOT be achieved. 

I debugged the code and found that ExecutorDidWriteXLog returns FALSE which causes DTX_STATE_ONE_PHASE_COMMIT is set. This problem also exists in GP7.

### Step to reproduce the behavior

1. set test_print_direct_dispatch_info = on;
2. create table test (a int, b int) distributed by (a);
3. copy test from 'xxxxxx' delimiter ',' (involving multiple segments)

**Comment by dreamedcheng** [comment]
This problem can be also reproduced in master branch. The root cause (for master branch) is that `cdbCopyEndInternal` didn't call `processResults` to process the results from the segments. So `TopXactexecutorDidWriteXLog` wasn't set properly.

So to fix it, maybe `processResults` is required for `cdbCopyEndInternal` .

**Comment by kainwen** [comment]
> This problem can be also reproduced in master branch. The root cause (for master branch) is that `cdbCopyEndInternal` didn't call `processResults` to process the results from the segments. So `TopXactexecutorDidWriteXLog` wasn't set properly.
> 
> So to fix it, maybe `processResults` is required for `cdbCopyEndInternal` .

Would you please open a pr for this? Thanks.

**Comment by dreamedcheng** [comment]
> > This problem can be also reproduced in master branch. The root cause (for master branch) is that `cdbCopyEndInternal` didn't call `processResults` to process the results from the segments. So `TopXactexecutorDidWriteXLog` wasn't set properly.
> > So to fix it, maybe `processResults` is required for `cdbCopyEndInternal` .
> 
> Would you please open a pr for this? Thanks.

OK

**Comment by adam8157** [comment]
We do process the results in `cdbCopyEndInternal()`, but we don't do this:
```
for (seg = 0; seg < gp->size; seg++)
{
	SegmentDatabaseDescriptor *q = gp->db_descriptors[seg]
...
	if (q->conn->wrote_xlog)
		MarkTopTransactionWriteXLogOnExecutor();
...
```
Is it the cure?

**Comment by dreamedcheng** [comment]
> We do process the results in `cdbCopyEndInternal()`, but we don't do this:
> 
> ```
> for (seg = 0; seg < gp->size; seg++)
> {
> 	SegmentDatabaseDescriptor *q = gp->db_descriptors[seg]
> ...
> 	if (q->conn->wrote_xlog)
> 		MarkTopTransactionWriteXLogOnExecutor();
> ...
> ```
> 
> Is it the cure?

@adam8157 yes.
@kainwen I opened a PR to fix this issue, please take a look, thanks.
