### ISSUE TITLE
Does GP use S3 SELECT API to load external tables stored in oss?

### ISSUE THREAD

**Issue by cobolbaby** [greenplum-db/gpdb#11861]
Does GP use S3 SELECT API to load external tables when executing the query sql?

```sql
CREATE WRITABLE EXTERNAL TABLE bsi_old.tbl_pinresult_archive_w (LIKE bsi_old.tbl_pinresult)
   LOCATION('s3://xxxx/xxxx/gpdb-archive/ config=~/s3.conf')
   FORMAT 'csv';

insert into bsi_old.tbl_pinresult_archive_w select * from bsi_old.tbl_pinresult

-- INSERT 0 695282638

-- Query returned successfully in 16 min 32 secs.

CREATE READABLE EXTERNAL TABLE bsi_old.tbl_pinresult_archive_r (LIKE bsi_old.tbl_pinresult_archive_w)
   LOCATION('s3://xxxx/xxxx/gpdb-archive/ config=~/s3.conf')
   FORMAT 'csv';
   
select * from bsi_old.tbl_pinresult_archive_r limit 100
```

### GP Version

- Greenplum version or build: 5.28.3
- OS version and uname -a: Centos7

**Comment by adam8157** [comment]
It uses Amazon S3 RESTful API.

**Comment by cobolbaby** [comment]
@adam8157 Is it the regular S3 interface or the S3 SELECT API?

**Comment by adam8157** [comment]
Were you referring https://docs.aws.amazon.com/AmazonS3/latest/API/API_SelectObjectContent.html? No, we are not using it in `s3://`.

I'm not sure if PXF S3 uses it.

**Comment by cobolbaby** [comment]
Does GP need to pull back all the gzip-compressed data files before it can perform some operations?

**Comment by cobolbaby** [comment]
> I'm not sure if PXF S3 uses it.

PXF provides support.

Refer to https://gpdb.docs.pivotal.io/pxf/5-16/using/access_s3.html
