### ISSUE TITLE
OOM when using PostGIS type columns

### ISSUE THREAD

**Issue by oSkrobuk** [greenplum-db/gpdb#11860]
### Greenplum version or build
PostgreSQL 9.4.24 (Greenplum Database 6.12.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609, 64-bit compiled on Dec 2 2020 10:28:03

PostGIS version 2.1.5

### OS version and uname -a
Linux hostname 4.19.62-13 #1 SMP Mon Jul 29 17:22:59 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

### autoconf options used ( config.status --config )
'--build=x86_64-linux-gnu' '--prefix=/usr' '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' '--sysconfdir=/etc' '--localstatedir=/var' '--disable-silent-rules' '--libdir=${prefix}/lib/x86_64-linux-gnu' '--libexecdir=${prefix}/lib/x86_64-linux-gnu' '--disable-maintainer-mode' '--disable-dependency-tracking' '--with-perl' '--with-python' '--without-gssapi' '--disable-gpcloud' '--with-libxml' '--with-system-tzdata=/usr/share/zoneinfo' '--prefix=/usr/local/gpdb' 'build_alias=x86_64-linux-gnu' 'CFLAGS=-g -O2 -fstack-protector-strong -Wformat -Werror=format-security' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'CXXFLAGS=-g -O2 -fstack-protector-strong -Wformat -Werror=format-security'

### Installation information ( pg_config )
BINDIR = /usr/local/gpdb/bin
DOCDIR = /usr/local/gpdb/share/doc/postgresql
HTMLDIR = /usr/local/gpdb/share/doc/postgresql
INCLUDEDIR = /usr/local/gpdb/include
PKGINCLUDEDIR = /usr/local/gpdb/include/postgresql
INCLUDEDIR-SERVER = /usr/local/gpdb/include/postgresql/server
LIBDIR = /usr/local/gpdb/lib/x86_64-linux-gnu
PKGLIBDIR = /usr/local/gpdb/lib/x86_64-linux-gnu/postgresql
LOCALEDIR = /usr/local/gpdb/share/locale
MANDIR = /usr/local/gpdb/share/man
SHAREDIR = /usr/local/gpdb/share/postgresql
SYSCONFDIR = /etc/postgresql
PGXS = /usr/local/gpdb/lib/x86_64-linux-gnu/postgresql/pgxs/src/makefiles/pgxs.mk
CONFIGURE = '--build=x86_64-linux-gnu' '--prefix=/usr' '--includedir=/usr/local/gpdb/include' '--mandir=/usr/local/gpdb/share/man' '--infodir=/usr/local/gpdb/share/info' '--sysconfdir=/etc' '--localstatedir=/var' '--disable-silent-rules' '--libdir=/usr/local/gpdb/lib/x86_64-linux-gnu' '--libexecdir=/usr/local/gpdb/lib/x86_64-linux-gnu' '--disable-maintainer-mode' '--disable-dependency-tracking' '--with-perl' '--with-python' '--without-gssapi' '--disable-gpcloud' '--with-libxml' '--with-system-tzdata=/usr/share/zoneinfo' '--prefix=/usr/local/gpdb' 'build_alias=x86_64-linux-gnu' 'CFLAGS=-g -O2 -fstack-protector-strong -Wformat -Werror=format-security' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'CXXFLAGS=-g -O2 -fstack-protector-strong -Wformat -Werror=format-security'
CC = gcc
CPPFLAGS = -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2 -I/usr/local/gpdb/include
CFLAGS = -Wall -Wmissing-prototypes -Wpointer-arith -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fno-aggressive-loop-optimizations -Wno-unused-but-set-variable -Wno-address -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -std=gnu99 -Werror=uninitialized -Werror=implicit-function-declaration -I/usr/local/gpdb/include
CFLAGS_SL = -fPIC
LDFLAGS = -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,--as-needed -Wl,-rpath,'/usr/local/gpdb/lib/x86_64-linux-gnu',--enable-new-dtags -L/usr/local/gpdb/lib/x86_64-linux-gnu
LDFLAGS_EX =
LDFLAGS_SL =
LIBS = -lpgcommon -lpgport -lxerces-c -lxml2 -lrt -lzstd -lrt -lcrypt -ldl -lm -L/usr/local/gpdb/lib/x86_64-linux-gnu
VERSION = PostgreSQL 9.4.24

### Actual behavior
Table DLL:
```sql
CREATE TABLE schema.table (
    polygon public.geography
)
 DISTRIBUTED RANDOMLY;
```

```sql
ANALYZE schema.table
--[53500] ERROR: Out of memory
--Detail: Resource group memory limit reached
SHOW STATEMENT_MEM;
--1200MB
```
Log: https://drive.google.com/file/d/11_t4ABoUJkkKigaQtrl28xIIJ188-xwV/view?usp=sharing
Error only on the master
The error repeats regardless of the settings `MEMORY_SHARED_QUOTA`, `MEMORY_SPILL_RATIO` and `CONCURRENCY` resource group

I noticed that the query works until all memory from SHARED has been utilization. This is true for all queries using PostGIS datatypes that fail with OOM error. The error is reproducible in any optimizer

These queries work without errors
```sql
SELECT count(*) FROM schema.table;
--2562022
SELECT sum(length(ST_AsBinary(polygon))) FROM schema.table;
--1569146702
CREATE TEMPORARY TABLE tmp AS
SELECT ST_AsText(polygon) FROM schema.table;
--All functions work from this list https://postgis.net/workshops/postgis-intro/geography.html#using-geography
VACUUM FULL schema.table;
VACUUM schema.table;
```

With OOM error:
```sql
ANALYZE schema.table;
CREATE TEMPORARY TABLE tmp AS
SELECT polygon FROM schema.table;
```

But this query completes without error:
```sql
EXPLAIN ANALYZE CREATE TEMPORARY TABLE tmp AS
SELECT polygon FROM schema.table;
/*
Result  (cost=0.00..0.00 rows=0 width=0) (actual time=0.060..29.462 rows=20299 loops=1)
  ->  Redistribute Motion 128:128  (slice1; segments: 128)  (cost=0.00..431.00 rows=1 width=8) (actual time=0.059..26.745 rows=20299 loops=1)
        ->  Result  (cost=0.00..431.00 rows=1 width=12) (actual time=0.047..22.220 rows=20382 loops=1)
              ->  Seq Scan on table (cost=0.00..431.00 rows=1 width=8) (actual time=0.047..18.052 rows=20382 loops=1)
Planning time: 5.563 ms
"  (slice0)    Executor memory: 204K bytes avg x 128 workers, 212K bytes max (seg7)."
"  (slice1)    Executor memory: 58K bytes avg x 128 workers, 58K bytes max (seg0)."
Memory used:  1179648kB
Optimizer: Pivotal Optimizer (GPORCA)
Execution time: 101.517 ms
*/
```

If set the limit, then the query is executed without error, but utilizes about 25GB of SHARED memory from resource group:
```sql
CREATE TEMPORARY TABLE tmp AS
SELECT polygon FROM schema.table
LIMIT 50000;
```

This problem did not exist before restarting the cluster. The GPDB and PostGIS has not been updated. There were no OS and library updates. GPDB configs have not changed. No errors on another cluster with the same versions and settings of GPDB, PostGIS and OS.

What and where can we look in our cluster at to localize the error?

**Comment by oSkrobuk** [comment]
```sql
SELECT typanalyze
FROM pg_type
WHERE typname LIKE 'geography';
-- -
```
On another cluster
```sql
SELECT typanalyze
FROM pg_type
WHERE typname LIKE 'geography';
--geography_analyze
```

**Comment by oSkrobuk** [comment]
```sql
SELECT oid, xmin, xmax
FROM pg_proc
WHERE proname = 'geography_analyze';
--896980,39770874,0

```

**Comment by oSkrobuk** [comment]
Found a query:
```sql
CREATE OR REPLACE FUNCTION geography_analyze(internal)
        RETURNS bool
        AS '$libdir/postgis-2.1','gserialized_analyze_nd'
        LANGUAGE 'c' VOLATILE STRICT
```
But that was after the problem appeared. There were no other queries to recreate the function

**Comment by oSkrobuk** [comment]
```sql
SET allow_system_table_mods = on;
UPDATE pg_type
SET typanalyze = 896980
WHERE oid = 18913;
UPDATE pg_type
SET typanalyze = 896992
WHERE oid = 18910;
SET allow_system_table_mods = off;
```
I executed these queries. The problem is resolved. But what caused this?

**Comment by kainwen** [comment]
We do not analyze the RCA, keep this open.

**Comment by kainwen** [comment]
> ```sql
> SET allow_system_table_mods = on;
> UPDATE pg_type
> SET typanalyze = 896980
> WHERE oid = 18913;
> UPDATE pg_type
> SET typanalyze = 896992
> WHERE oid = 18910;
> SET allow_system_table_mods = off;
> ```
> 
> I executed these queries. The problem is resolved. But what caused this?

Sorry we do not response for a long time. @oSkrobuk 
Can you share why you run such SQLs?

**Comment by dpandhi-git** [comment]
Closing as no further update
