### ISSUE TITLE
FDW in "all segments"-mode duplicates data many times 

### ISSUE THREAD

**Issue by dimkas78** [greenplum-db/gpdb#11865]
### Greenplum version or build
postgresql 9.4.24 (greenplum database 6.14.1 build commit:5ef30dd4c9878abadc0124e0761e4b988455a4bd) on x86_64-unknown-linux-gnu, compiled by gcc (gcc) 6.4.0, 64-bit compiled on feb 22 2021 18:27:08

### OS version and uname -a

CentOS 7.2

I try to copy data from Postgres 11 to Greenplum 6.14 by Foreign Data Wrapper.
With default options I receive N rows and all data comes through master node.
So I decide to change options to mpp_execute "all segment",
but in this case I receive 24*N rows, because my cluster has 24 segments nodes.

I think this is well known issue, but unfortunately can't find solution.

### Step to reproduce the behavior

-- On Postgres server
create table x(id int, value float8);
insert into x select r, r * random() from generate_series(1,1000) r;
select count(*) from x;

1000
(1 row)

-- On Greenplum server
CREATE EXTENSION postgres_fdw;
create server foreign_server_x FOREIGN DATA WRAPPER postgres_fdw
OPTIONS(host '172.16.128.135', port '5432', dbname 'postgres');

-- user mapping
CREATE USER MAPPING FOR current_user
SERVER foreign_server_x OPTIONS (user 'admin', password 'admin');

-- foreign table foreign_x
CREATE FOREIGN TABLE foreign_x
(id int, value float8) SERVER foreign_server_x OPTIONS (schema_name 'public', table_name 'x');

select count(*) from foreign_x;

1000
(1 row)

-- mpp_execute = all segments
alter foreign table foreign_x options (add mpp_execute 'all segments');

-- foreign_x (24 segments)
select count(*) from foreign_x;

24000
(1 row)

**Comment by adam8157** [comment]
It's not an issue, please don't use `all segments` for general foreign data wrappers, unless that FDW tells you to.

I'm considering warning the users unless the FDW having an API that indicates it could do that.

**Comment by dimkas78** [comment]
@adam8157 
Thank you for info!
