### ISSUE TITLE
GPDB Expression type: Query Parameter not supported in DXL

### ISSUE THREAD

**Issue by LeoLiang666** [greenplum-db/gpdb#11938]
### autoconf options used ( config.status --config )
master Greenplum Version: 'PostgreSQL 9.4.24 (Greenplum Database 6.16.0 build 
### Step to reproduce the behavior
2021-05-07 23:10:46.765651 CST,"gpadmin","gac_gpdb",p9689,th21917696,"10.1.1.161","37804",2021-05-07 23:10:43 CST,27907,con82,cmd14,seg-1,,dx57,x27908,sx2,"LOG","00000","2021-05-07 23:10:46:765587 CST,THD000,ERROR,""GPDB Expression type: Query Parameter not supported in DXL"",

Hi, 
there is a question about this:
insert into public.dm_driver_service_score_risk_rate_model
  select '20210801'::date
         , count(order_id)
         , 0
         , 0
  from public.view_risk_order 
  where create_date::date between '20191103'::date - interval '13 day'  and '20191103'::date - interval '2 day'
;  
when I perform this SQL，it's hang, 

  select '20210801'::date
         , count(order_id)
         , 0
         , 0
  from public.view_risk_order 
  where create_date::date between '20191103'::date - interval '13 day'  and '20191103'::date - interval '2 day'
;  
but perform select  sql is so quickly.

**Comment by LeoLiang666** [comment]
Linux OS is 
[root@gpmaster01 ~]# cat /etc/redhat-release 
CentOS Linux release 7.9.2009 (Core)

please help! many thanks!

**Comment by LeoLiang666** [comment]
Linux OS is 
[root@gpmaster01 ~]# cat /etc/redhat-release 
CentOS Linux release 7.9.2009 (Core)

please help! many thanks!

**Comment by JunfengYang** [comment]
Can you provide the table definition, some sample data, and the `EXPLAIN` output for the query?
The error "Query Parameter not supported in DXL" is from gporca, I don't think this related to your hung issue.

**Comment by kainwen** [comment]
We have asked for detailed information but no response for a long time. Feel free to re-open this if needed.
