### ISSUE TITLE
 Require image for ARM64 architecture

### ISSUE THREAD

**Issue by odidev** [greenplum-db/gpdb#11950]
Hi Team,

I am trying to build a **pivotaldata/gpdb-pxf-dev** image on ARM64 architecture but it is using **pivotaldata/gpdb-dev:centos6** as the [base image](https://github.com/greenplum-db/gpdb/tree/master/src/tools/docker/centos7) which is not available for arm64. 

I have successfully built the **gpdb-dev** image using the command docker build -t image_name . on the arm64 platform without making any changes in the Dockerfile.

I have used **Github actions** to build and push the image for both the platforms.

**Commit Link** - https://github.com/odidev/gpdb/commit/2a794121b128b6fcadf363ff74b582b1396de35b

**Github actions link** - https://github.com/odidev/gpdb/runs/2543677480?check_suite_focus=true

**Docker Hub Link** - https://hub.docker.com/repository/registry-1.docker.io/odidev/gpdb-dev/tags?page=1&ordering=last_updated

Do you have any plans on releasing arm64 images?

It will be very helpful if arm64 image is available. If interested, I will raise a PR.

**Comment by kmacoskey** [comment]
Hello @odidev . There's no current plans to release an arm64 image. We've mostly moved away from the old images in pivotaldata dockerhub as well. A PR to add an image is good.
