### ISSUE TITLE
Is there a compatibility check which tells what modules are required 

### ISSUE THREAD

**Issue by deepesh1081** [greenplum-db/gpdb#1197]
During my attempt to build gpdb-master on the sandbox i ran into many compatibility issues, and it is a very iterative process.   
My ask:  is there a script which looks at the environment to, and identify dependencies and suggest a yum command to install those, If such functionality does not exists, i feel it would be greatly helpful.
   
Following were the yum install command i had to use for configure to complete successfully:
Config command: "./configure --without-readline --without-zlib"
Dependencies: 
------------------------------------------------------------
yum install perl-ExtUtils-CBuilder perl-ExtUtils-MakeMaker perl-ExtUtils-Embed
yum -y install arp apr-devel apr-util apr-util-devel pcre pcre-devel
yum -y install libevent
yum install libevent-devel
yum install  libyaml-devel
yum install  flex
yum install  bison
yum install curl curl-devel
yum install bzip2-devel

**Comment by Eulerizeit** [comment]
Look at the README for AmazonLinux

**Comment by deepesh1081** [comment]
agreed, the file has the details, I am more looking for a verification step, which configure can execute what dependencies needs to be resolved beforehand, rather one running configure and resolving dependencies as you see them.

**Comment by hlinnaka** [comment]
No, I'm afraid there isn't. We rely on configure to do the checks, and unfortunately it bails out at the first error.
