### ISSUE TITLE
greenplum 6.10.1 gpinitsystem  `CXXABI_1.3.9' not found

### ISSUE THREAD

**Issue by gj-zhang** [greenplum-db/gpdb#11978]
### Greenplum version or build
6.10.1-2
### OS version and uname -a
CentOS Linux release 7.6.1810 (Core)
Linux xxx 4.14.141-1.el7.x86_64 #1 SMP Wed Sep 4 21:29:48 CST 2019 x86_64 x86_64 x86_64 GNU/Linux

###problem

```shell
gpinitsystem -c gpconfig/gpinitsystem_config -h gpconfig/hostfile_gpssh_segonly -s gp-001 -S -O gpconfig/gpconfig_template
```
##log
/opt/greenplum/greenplum-db-6.10.1/bin/postgres: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /opt/greenplum/greenplum-db-6.10.1/bin/postgres)

**Comment by adam8157** [comment]
Please provide the details of where you downloaded the package, and its filename, thanks.

**Comment by gj-zhang** [comment]
> Please provide the details of where you downloaded the package, and its filename, thanks.
https://github.com/greenplum-db/gpdb/releases?after=6.12.1

![image](https://user-images.githubusercontent.com/21170229/118085579-36a3dc80-b3f5-11eb-9200-88892ffb777e.png)

**Comment by gj-zhang** [comment]
> Please provide the details of where you downloaded the package, and its filename, thanks.

and i try 6.16 the problem still exist

https://network.pivotal.io/products/vmware-tanzu-greenplum#/releases/872702/file_groups/3529

![image](https://user-images.githubusercontent.com/21170229/118086352-67d0dc80-b3f6-11eb-82e0-c34efb7157a3.png)

Could you please tell me the difference between the two linked greenplum ? Which version should I choose for my production environment?  thank you

**Comment by gj-zhang** [comment]
> Please provide the details of where you downloaded the package, and its filename, thanks.

problem resolved，system environment variables are overwritten. thank you.

Could you please tell me the difference between the two linked greenplum ? Which version should I choose for my production environment? thank you

**Comment by adam8157** [comment]
Tanzu Greenplum is the enterprise version with some extra extensions. Opensource Greenplum is free of charge, but no warranty.
