### ISSUE TITLE
CREATE MATERIALIZED VIEW ... WITH NO DATA executing cursor query

### ISSUE THREAD

**Issue by ashwinstar** [greenplum-db/gpdb#11999]
### Greenplum version or build
GPDB6

### Expected behavior
- `CREATE MATERIALIZED VIEW sro_mv AS SELECT mv_action_select() WITH NO DATA;` -- passing
- `REFRESH MATERIALIZED VIEW sro_mv;` -- failing `ERROR:  division by zero`

### Actual behavior
- `CREATE MATERIALIZED VIEW sro_mv AS SELECT mv_action_select() WITH NO DATA;` -- fails `ERROR:  division by zero`

### Step to reproduce the behavior
```sql
DROP MATERIALIZED VIEW IF EXISTS sro_mv;
CREATE or REPLACE FUNCTION mv_action_select() RETURNS bool LANGUAGE sql AS
'DECLARE c CURSOR FOR select 1/0; SELECT true';
CREATE MATERIALIZED VIEW sro_mv AS SELECT mv_action_select() WITH NO DATA;
```

In PostgerSQL, `CREATE MATERIALIZED` doesn't run `PerformCursorOpen()` for this when `WITH NO DATA` is specified. GPDB though is running it even when `WITH NO DATA` is specified causing the difference in expectation.

**Comment by kainwen** [comment]
This line of code:

```
425     if (into->skipData && !is_matview)
 426     {
 427         /*
 428          * If WITH NO DATA was specified, do not go through the rewriter,
 429          * planner and executor.  Just define the relation using a code path
 430          * similar to CREATE VIEW.  This avoids dump/restore problems stemming
 431          * from running the planner before all dependencies are set up.
 432          */
 433         (void) create_ctas_nodata(query->targetList, into, queryDesc);
 434     }
 435     else
 436     {
 437         queryDesc->plannedstmt->query_mem = ResourceManagerGetQueryMemoryLimit(queryDesc->plannedstmt);
```

make the nodata field does not work for matview. The code comes in as the commit we introduce matview. In my memory, it seems to fix a pipeline’s work around. Will continue to look into it.

**Comment by kainwen** [comment]
Find the issue, `skipData` will not dispatch (in the above patch), lead to inconsistent catalog.

**Comment by kainwen** [comment]
Now I come up with 3 different fix method, either can fix this issue, I want to hear more voice on which is the best:

1. document and force CTAS with no data to have a random policy
2. skip check for policy in gpcheckcat
3. dispatch the policy to QD for CTAS with no data

**Comment by chenbaggio** [comment]
thanks! get it!
