### ISSUE TITLE
Support max_slot_wal_keep_size GUC in Greenplum 7

### ISSUE THREAD

**Issue by asimrp** [greenplum-db/gpdb#12007]
This is a request for a feature that is already present in Greenplum 6: https://github.com/greenplum-db/gpdb/pull/11908.  It was pulled in from PostgreSQL 13.  Let's use this issue to track its development in Greenplum 7.

There should be a way to limit the WAL retained by a primary segment when its mirror falls behind or disconnects.

**Comment by asimrp** [comment]
@paul-guo- FYI

**Comment by dpandhi-git** [comment]
@l-wang has started work on same
