### ISSUE TITLE
can not create replicated table on segment by CTAS

### ISSUE THREAD

**Issue by chenbaggio** [greenplum-db/gpdb#12021]
### Greenplum version or build

6x_stabled

### OS version and uname -a

Linux 192.168.10.200vagrant.hashdata.vm 3.10.0-327.el7.x86_64 #1 SMP Thu Nov 19 22:10:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

### Expected behavior

create replicated table on master and segments 

### Actual behavior

only create replicated table on master

### Step to reproduce the behavior

1.  `create table t1 (a int, b int) distributed by (a);`
2. `create table t2 as select * from t1 with no data distributed replicated;`
3.  conenct master , `select * from gp_distributed_policy` , can find the table t2
4.  connect anyone segment  as utility role, `select * from gp_distributed_policy` , can not find the table t2

**Comment by kainwen** [comment]
I believe this PR  https://github.com/greenplum-db/gpdb/pull/12018 (when backporting to 6X) can fix your issue.

In fact, it is the policy not dispatch to segments, the relation is created everywhere.

**Comment by chenbaggio** [comment]
another question , the tablespace option seems can not work,

has set the tablespace 

```
create table t1 tablespace ts as select * from t2 

```

but after created, the tablespace oid is still 0 (default)

the coding seems not correct:


```

static Oid
create_ctas_internal(List *attrList, IntoClause *into, QueryDesc *queryDesc, bool dispatch)
{

    if (queryDesc->ddesc)
		create->tablespacename = queryDesc->ddesc->intoTableSpaceName;
	else
		create->tablespacename = into->tableSpaceName;
}
```
and maybe should like 

```
static Oid
create_ctas_internal(List *attrList, IntoClause *into, QueryDesc *queryDesc, bool dispatch)
{

    if (queryDesc->ddesc && queryDesc->ddesc->intoTableSpaceName)
		create->tablespacename = queryDesc->ddesc->intoTableSpaceName;
	else
		create->tablespacename = into->tableSpaceName;
}

```

**Comment by kainwen** [comment]
> another question , the tablespace option seems can not work,
> 
> has set the tablespace
> 
> ```
> create table t1 tablespace ts as select * from t2 
> ```
> 
> but after created, the tablespace oid is still 0 (default)
> 
> the coding seems not correct:
> 
> ```
> 
> static Oid
> create_ctas_internal(List *attrList, IntoClause *into, QueryDesc *queryDesc, bool dispatch)
> {
> 
>     if (queryDesc->ddesc)
> 		create->tablespacename = queryDesc->ddesc->intoTableSpaceName;
> 	else
> 		create->tablespacename = into->tableSpaceName;
> }
> ```
> 
> and maybe should like
> 
> ```
> static Oid
> create_ctas_internal(List *attrList, IntoClause *into, QueryDesc *queryDesc, bool dispatch)
> {
> 
>     if (queryDesc->ddesc && queryDesc->ddesc->intoTableSpaceName)
> 		create->tablespacename = queryDesc->ddesc->intoTableSpaceName;
> 	else
> 		create->tablespacename = into->tableSpaceName;
> }
> ```

The main issue is fixed on master and 6X, for the tablespace issue, would you please open a PR to gpdb?
Thanks a lot.

**Comment by kainwen** [comment]
@chenbaggio 

```sql
gpadmin=# create tablespace ts location '/home/gpadmin/test';
CREATE TABLESPACE
gpadmin=# create table t tablespace ts as select i from generate_series(1, 100)i;
NOTICE:  Table doesn't have 'DISTRIBUTED BY' clause -- Using column(s) named 'i' as the Greenplum Database data distribution key for this table.
HINT:  The 'DISTRIBUTED BY' clause determines the distribution of data. Make sure column(s) chosen are the optimal data distribution key to minimize skew.
SELECT 100

gpadmin=# select reltablespace from pg_class where relname = 't';
 reltablespace
---------------
         16385
(1 row)

gpadmin=# select reltablespace from gp_dist_random('pg_class') where relname = 't';
 reltablespace
---------------
         16385
         16385
         16385
(3 rows)
```

Can you elaborate a bit on your previously-mentioned tablespace issue? Please open it as a new issue and paste the detailed reproduce steps. Thanks a lot.

**Comment by kainwen** [comment]
Fixed by https://github.com/greenplum-db/gpdb/pull/12018 (master) and https://github.com/greenplum-db/gpdb/pull/12044 (6x)
