### ISSUE TITLE
Coverity: memory leak in xlog_desc

### ISSUE THREAD

**Issue by zhangh43** [greenplum-db/gpdb#12052]
### Greenplum version or build
gpdb 6X_STABLE

Memory leak reported by Coverity in xlogdesc.c
We should firstly store `relpathperm()`'s result in variable path and then free path later.

```
BkpBlock   *bkp = (BkpBlock *) rec;

10. Resource "GetRelationPath(bkp->node.dbNode, bkp->node.spcNode, bkp->node.relNode, -1, bkp->fork)" is not freed or pointed-to in "appendStringInfo".
11. Failing to save or free storage allocated by "GetRelationPath(bkp->node.dbNode, bkp->node.spcNode, bkp->node.relNode, -1, bkp->fork)" leaks it.
9. Storage is returned from allocation function "GetRelationPath".

		appendStringInfo(buf, "full-page image: %s block %u",
						 relpathperm(bkp->node, bkp->fork),
```

**Comment by JunfengYang** [comment]
@zhangh43 I check the code, seems the function only used in pg_xlogdump, and Postgres doesn't care about the memory leak in it.

**Comment by ashwinstar** [comment]
yes, pg_xlogdump is short lived process. This is upstream code and doesn't care about fixing the same. Hence, closing as no fix needs to be made for it.
