### ISSUE TITLE
Error on update when from clause return multi tuple.

### ISSUE THREAD

**Issue by baobao0206** [greenplum-db/gpdb#12079]
### Greenplum version or build
Master(Orca)

### Actual behavior
create table testsort (i1 int, i2 int, i3 int, i4 int);
insert into testsort select i, i % 1000, i % 100000, i % 75 from generate_series(0,1000000) i;
analyze testsort;

create table foo (c int, d int);
insert into foo values (1, 1);

update foo set d = i1 from (select i1,i2 from testsort order by i2) x;
ERROR:  multiple updates to a row by the same query is not allowed

**Comment by kainwen** [comment]
See the thread: https://groups.google.com/a/greenplum.org/g/gpdb-dev/c/uOkafmel3YU/m/pDNFqOglBwAJ

This is gpdb specific behavior, especially for split-update case.
