### ISSUE TITLE
Failed to complete obtain psql count Master gp_segment_configuration  Script Exiting!

### ISSUE THREAD

**Issue by Saseke** [greenplum-db/gpdb#12096]
### Greenplum version or build
Greenplum version is 6.16.1
### autoconf options used ( config.status --config )
OS: ubuntu 18.04
Linux master 4.15.0-144-generic 148-Ubuntu SMP Sat May 8 02:33:43 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
### Installation information ( pg_config )
`20210603:13:32:16:002691 gpinitsystem:master:gpadmin-[INFO]:-Configuring build for standard array
20210603:13:32:16:002691 gpinitsystem:master:gpadmin-[INFO]:-Commencing multi-home checks, Completed
20210603:13:32:16:002691 gpinitsystem:master:gpadmin-[INFO]:-Building primary segment instance array, please wait...
..
20210603:13:32:23:002691 gpinitsystem:master:gpadmin-[INFO]:-Building group mirror array type , please wait...
..
20210603:13:32:25:002691 gpinitsystem:master:gpadmin-[INFO]:-Checking Master host
20210603:13:32:25:002691 gpinitsystem:master:gpadmin-[INFO]:-Checking new segment hosts, please wait...
....
20210603:13:32:40:002691 gpinitsystem:master:gpadmin-[INFO]:-Checking new segment hosts, Completed
20210603:13:32:40:002691 gpinitsystem:master:gpadmin-[INFO]:-Greenplum Database Creation Parameters
20210603:13:32:40:002691 gpinitsystem:master:gpadmin-[INFO]:---------------------------------------
20210603:13:32:40:002691 gpinitsystem:master:gpadmin-[INFO]:-Master Configuration
20210603:13:32:40:002691 gpinitsystem:master:gpadmin-[INFO]:---------------------------------------
20210603:13:32:40:002691 gpinitsystem:master:gpadmin-[INFO]:-Master instance name       = Greenplum
20210603:13:32:40:002691 gpinitsystem:master:gpadmin-[INFO]:-Master hostname            = master
20210603:13:32:40:002691 gpinitsystem:master:gpadmin-[INFO]:-Master port                = 5432
20210603:13:32:40:002691 gpinitsystem:master:gpadmin-[INFO]:-Master instance dir        = /home/gpadmin/data/master/gpseg-1
20210603:13:32:40:002691 gpinitsystem:master:gpadmin-[INFO]:-Master LOCALE              = en_US.utf8
20210603:13:32:40:002691 gpinitsystem:master:gpadmin-[INFO]:-Greenplum segment prefix   = gpseg
20210603:13:32:40:002691 gpinitsystem:master:gpadmin-[INFO]:-Master Database            = 
20210603:13:32:40:002691 gpinitsystem:master:gpadmin-[INFO]:-Master connections         = 250
20210603:13:32:40:002691 gpinitsystem:master:gpadmin-[INFO]:-Master buffers             = 128000kB
20210603:13:32:40:002691 gpinitsystem:master:gpadmin-[INFO]:-Segment connections        = 750
20210603:13:32:40:002691 gpinitsystem:master:gpadmin-[INFO]:-Segment buffers            = 128000kB
20210603:13:32:40:002691 gpinitsystem:master:gpadmin-[INFO]:-Checkpoint segments        = 8
20210603:13:32:40:002691 gpinitsystem:master:gpadmin-[INFO]:-Encoding                   = UNICODE
20210603:13:32:40:002691 gpinitsystem:master:gpadmin-[INFO]:-Postgres param file        = Off
20210603:13:32:40:002691 gpinitsystem:master:gpadmin-[INFO]:-Initdb to be used          = /opt/greenplum-db-6-6.16.1/bin/initdb
20210603:13:32:40:002691 gpinitsystem:master:gpadmin-[INFO]:-GP_LIBRARY_PATH is         = /opt/greenplum-db-6-6.16.1/lib
20210603:13:32:40:002691 gpinitsystem:master:gpadmin-[INFO]:-HEAP_CHECKSUM is           = on
20210603:13:32:40:002691 gpinitsystem:master:gpadmin-[INFO]:-HBA_HOSTNAMES is           = 0
20210603:13:32:40:002691 gpinitsystem:master:gpadmin-[INFO]:-Ulimit check               = Passed
20210603:13:32:40:002691 gpinitsystem:master:gpadmin-[INFO]:-Array host connect type    = Single hostname per node
20210603:13:32:40:002691 gpinitsystem:master:gpadmin-[INFO]:-Master IP address [1]      = ::1
20210603:13:32:40:002691 gpinitsystem:master:gpadmin-[INFO]:-Master IP address [2]      = 172.17.0.1
20210603:13:32:40:002691 gpinitsystem:master:gpadmin-[INFO]:-Master IP address [3]      = 192.168.139.144
20210603:13:32:40:002691 gpinitsystem:master:gpadmin-[INFO]:-Master IP address [4]      = fe80::250:56ff:fe2a:f781
20210603:13:32:40:002691 gpinitsystem:master:gpadmin-[INFO]:-Standby Master             = Not Configured
20210603:13:32:40:002691 gpinitsystem:master:gpadmin-[INFO]:-Number of primary segments = 1
20210603:13:32:40:002691 gpinitsystem:master:gpadmin-[INFO]:-Total Database segments    = 2
20210603:13:32:40:002691 gpinitsystem:master:gpadmin-[INFO]:-Trusted shell              = /usr/bin/ssh
20210603:13:32:40:002691 gpinitsystem:master:gpadmin-[INFO]:-Number segment hosts       = 2
20210603:13:32:40:002691 gpinitsystem:master:gpadmin-[INFO]:-Mirror port base           = 44000
20210603:13:32:40:002691 gpinitsystem:master:gpadmin-[INFO]:-Number of mirror segments  = 1
20210603:13:32:40:002691 gpinitsystem:master:gpadmin-[INFO]:-Mirroring config           = ON
20210603:13:32:40:002691 gpinitsystem:master:gpadmin-[INFO]:-Mirroring type             = Group
20210603:13:32:40:002691 gpinitsystem:master:gpadmin-[INFO]:----------------------------------------
20210603:13:32:40:002691 gpinitsystem:master:gpadmin-[INFO]:-Greenplum Primary Segment Configuration
20210603:13:32:40:002691 gpinitsystem:master:gpadmin-[INFO]:----------------------------------------
20210603:13:32:40:002691 gpinitsystem:master:gpadmin-[INFO]:-master 	33000 	master 	/home/gpadmin/data/primary/gpseg0 	2
20210603:13:32:40:002691 gpinitsystem:master:gpadmin-[INFO]:-worker1 	33000 	worker1 	/home/gpadmin/data/primary/gpseg1 	3
20210603:13:32:40:002691 gpinitsystem:master:gpadmin-[INFO]:---------------------------------------
20210603:13:32:40:002691 gpinitsystem:master:gpadmin-[INFO]:-Greenplum Mirror Segment Configuration
20210603:13:32:40:002691 gpinitsystem:master:gpadmin-[INFO]:---------------------------------------
20210603:13:32:40:002691 gpinitsystem:master:gpadmin-[INFO]:-worker1 	44000 	worker1 	/home/gpadmin/data/mirror/gpseg0 	4
20210603:13:32:40:002691 gpinitsystem:master:gpadmin-[INFO]:-master 	44000 	master 	/home/gpadmin/data/mirror/gpseg1 	5

Continue with Greenplum creation Yy|Nn (default=N):
> y
20210603:13:32:49:002691 gpinitsystem:master:gpadmin-[INFO]:-Building the Master instance database, please wait...
20210603:13:33:19:002691 gpinitsystem:master:gpadmin-[INFO]:-Starting the Master in admin mode
20210603:13:33:20:002691 gpinitsystem:master:gpadmin-[FATAL]:-Failed to complete obtain psql count Master gp_segment_configuration  Script Exiting!
20210603:13:33:20:002691 gpinitsystem:master:gpadmin-[WARN]:-Script has left Greenplum Database in an incomplete state
20210603:13:33:20:002691 gpinitsystem:master:gpadmin-[WARN]:-Run command bash /home/gpadmin/gpAdminLogs/backout_gpinitsystem_gpadmin_20210603_133214 to remove these changes
20210603:13:33:20:002691 gpinitsystem:master:gpadmin-[INFO]:-Start Function BACKOUT_COMMAND
20210603:13:33:20:002691 gpinitsystem:master:gpadmin-[INFO]:-End Function BACKOUT_COMMAND
`

**Comment by asimrp** [comment]
Hi @Saseke can you please share the contents of .csv files in coordinator data directory: `/home/gpadmin/data/master/gpseg-1/pg_log`?

**Comment by Saseke** [comment]
[gpdb-2021-06-03_133319.zip](https://github.com/greenplum-db/gpdb/files/6596850/gpdb-2021-06-03_133319.zip)

**Comment by asimrp** [comment]
Thank you for sharing the log file.  The following snippet looks relevant:
```
2021-06-03 13:33:19.604681 UTC,,,p5299,th1466217664,,,,0,,,seg-1,,,,,"LOG","00000","database system is ready to accept connections","PostgreSQL 9.4.24 (Greenplum Database 6.16.1 build commit:10171814c15886ff864fad19b89b3a7c224e0a97 Open Source) on x86_64-unknown-linux-gnu, compiled by gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0, 64-bit compiled on May 21 2021 19:49:59",,,,,,0,,"postmaster.c",3277,
2021-06-03 13:33:19.709324 UTC,"testDB","postgres",p5310,th1466217664,"[local]",,2021-06-03 13:33:19 UTC,0,,,seg-1,,,,sx1,"FATAL","28000","no pg_hba.conf entry for host ""[local]"", user ""testDB"", database ""postgres"", SSL off",,,,,,,0,,"auth.c",620,
2021-06-03 13:33:20.050214 UTC,"testDB","template1",p5389,th1466217664,"[local]",,2021-06-03 13:33:20 UTC,0,,,seg-1,,,,sx1,"FATAL","28000","no pg_hba.conf entry for host ""[local]"", user ""testDB"", database ""template1"", SSL off",,,,,,,0,,"auth.c",620,
```
The command used by `gpinitsystem` to start coordinator is
```
    export PGPORT=$GP_PORT;$PG_CTL -w -l $GP_DIR/pg_log/startup.log -D $GP_DIR -o "-i -p $GP_PORT -c gp_role=utility -m" start >> ${LOG_FILE} 2>&1
```
Can you please also check the contents of `/home/gpadmin/data/master/gpseg-1/pg_log/startup.log`?

**Comment by Saseke** [comment]
Thank you very much. I changed the configuration and it started successfully

**Comment by Mr-Diaolvyu** [comment]
> 非常感谢你。我更改了配置并成功启动

Hello, I met the same problem. How did you modify the configuration to solve it
