### ISSUE TITLE
Unexpected internal error (cdbgang.c:1622)

### ISSUE THREAD

**Issue by mimimiracle** [greenplum-db/gpdb#12123]
### Greenplum version
Greenplum4.3.8

### OS version and uname -a
Centos 7
Linux gpmaster 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

can connect to greenplum
can open database
can open schema
can read table struct

all primary node is going well
network is well, hardisk is well,

problem Is  **can not select from any table**
error information :**Unexpected internal error (cdbgang.c:1622)**

**Comment by kainwen** [comment]
gpdb4.3.8 is end-of-life. We are not going to spend time on this.
