### ISSUE TITLE
GPORCA Bug related with type cast

### ISSUE THREAD

**Issue by xlxie** [greenplum-db/gpdb#12133]
### Greenplum version or build
 PostgreSQL 9.4.24 (Greenplum Database 6.15.0 build dev) on x86_64-unknown-linux-gnu, compiled by gcc (GCC) 9.3.1 20200408 (Red Hat 9.3.1-2), 64-bit compiled on Jun 10 2021 10:08:23

### OS version and uname -a
Linux h68c05462.sqa.eu95 3.10.0-327.ali2010.alios7.x86_64 #1 SMP Mon Mar 20 19:58:02 CST 2017 x86_64 x86_64 x86_64 GNU/

### autoconf options used ( config.status --config )
./configure --enable-orca --with-perl --with-python --with-libxml --prefix=*****

### Installation information ( pg_config )
NaN

### Expected behavior
The optimizer generates a cast function to cast INTEGER to TEXT

### Actual behavior
Segment fault.

## DDL:
create table test_varchar(
data character varying
) distributed by (data);

insert into test_varchar values('test');

create table test_int(
id integer
) distributed by (id);

insert into test_int values(1);

CREATE CAST (integer AS text) WITH INOUT AS IMPLICIT;

## SQL:
select data from test_varchar where data > any(select id from test_int);

## Explanation:
As id is INTEGER type, the optimizer is supposed to generate a CAST function. However, the ORCA does not do that. Below is the plan.

<img width="835" alt="截屏2021-06-10 上午10 15 58" src="https://user-images.githubusercontent.com/6791107/121454153-e3fa1800-c9d4-11eb-86d5-4c0aad87f90e.png">

 At the execution stage, the execution engine treats the INTEGER as a TEXT variable. Thus, a segment fault is incurred. Below is the stack of the core dump file.

<img width="944" alt="截屏2021-06-10 上午10 26 44" src="https://user-images.githubusercontent.com/6791107/121455094-7f3fbd00-c9d6-11eb-855c-d7ff9b587bbe.png">

However, the PG optimizer works correctly in this case.

![20210610101810](https://user-images.githubusercontent.com/6791107/121454337-30ddee80-c9d5-11eb-8ae9-2c2006001732.jpg)

**Comment by chrishajas** [comment]
Fixed on master in https://github.com/greenplum-db/gpdb/commit/7a71720eb7b653b281917bd4ef718ca3085ab740 and 6X in https://github.com/greenplum-db/gpdb/commit/69c09fc0f586d581f2bdfd3ea93311da986763aa. Thanks for the report and repro!
