### ISSUE TITLE
gprecoverseg should start mirrors as soon as possible

### ISSUE THREAD

**Issue by asimrp** [greenplum-db/gpdb#12139]
The problem described in this issue applies to full recovery, but I have not checked incremental recovery.

### Greenplum version or build
6X and master

### Expected behavior
When performing full recovery of multiple segments, `gprecoverseg` should start a mirror as soon as the `pg_basebackup` reports success.
### Actual behavior
`gprecoverseg` waits until `pg_basebackup` processes for all the segments have finished and then starts the mirrors.
### Step to reproduce the behavior
This was seen in production where full recovery was performed on 8 failed segments.  Data directories of six segments occupied 400GB on disk whereas the remaining two segments occupied 2.1TB on disk.  The `pg_basebackup` finished in 5 hours for the smaller six segments.  They remained unstarted for 15 more hours until `pg_basebackup` finished for the larger two segments.

This is undesirable, especially in presence of ongoing workload.  One reason being the primary segments of the smaller 6 mirrors continued to accumulate WAL for several hours unnecessarily.
 
Let's fix this issue by starting a mirror as soon as `pg_basebackup` for it is finished.

**Comment by niralis13** [comment]
@asimrp Do we have any customer requesting this? or related JIRA?

**Comment by kaknikhil** [comment]
Fixed as part of https://github.com/greenplum-db/gpdb/pull/13133 and https://github.com/greenplum-db/gpdb/pull/13171. Closing this issue
