### ISSUE TITLE
gprecoverseg error:could not load pg_hba.conf

### ISSUE THREAD

**Issue by bloodwolf2020** [greenplum-db/gpdb#12149]
I have two physical server, gp_master and gp_standby;

After the gp_standby server restart, an error occured when i use gprecoverseg -F to start the segment on gp_standby;

![image](https://user-images.githubusercontent.com/46953147/121649688-65cc6d00-cacb-11eb-8fa4-1e04cbe8ba89.png)

![image](https://user-images.githubusercontent.com/46953147/121647281-d3c36500-cac8-11eb-803f-07af59e61b83.png)

This error is occur on the version 6.15.0 and 6.16.2, but does not occur on then version 6.6;

After use command gprecoverseg -F, pg_hba.conf file is like this int version 6.6:
![image](https://user-images.githubusercontent.com/46953147/121647778-62d07d00-cac9-11eb-8204-39ef34e3897d.png)

but on the version 6.15.0 or 6.16.2 like this

![image](https://user-images.githubusercontent.com/46953147/121649890-93b1b180-cacb-11eb-95f5-0d96b2d8f6f3.png)

update_pg_hba_conf.py
update the function config_primaries_for_replication like this
![image](https://user-images.githubusercontent.com/46953147/121654974-d4f89000-cad0-11eb-835b-21b2f37ec637.png)

**Comment by bloodwolf2020** [comment]
add function 
![image](https://user-images.githubusercontent.com/46953147/122152619-27043180-ce94-11eb-89ef-48dd4e139108.png)

change the append
![image](https://user-images.githubusercontent.com/46953147/122152713-456a2d00-ce94-11eb-9450-909f72856d1d.png)

![image](https://user-images.githubusercontent.com/46953147/122152783-5d41b100-ce94-11eb-85b2-f4c3d5847f86.png)

Can I make such changes as this one, which can be heavy and solve the above problems?

**Comment by shivzone** [comment]
@bloodwolf2020 there is an ongoing PR https://github.com/greenplum-db/gpdb/pull/12129/files to fix with pg_hba updates. @orhankislal please check if the PR addresses this as well

**Comment by orhankislal** [comment]
@shivzone is correct. The linked PR fixes whitespaces and filters duplicate lines.

**Comment by bloodwolf2020** [comment]
@orhankislal  thank you very much, but the gpexpand command exists then same problem!
