### ISSUE TITLE
 ERROR:  relation 15620498 deleted while still in use (relcache.c:2304)

### ISSUE THREAD

**Issue by eric0225** [greenplum-db/gpdb#12170]
GPDB version:6.4.0
GPCC version:6.1.0
A few days ago ，our server shut down abnormally，when execute some query I found some errors .One of the error is “ERROR:  invalid page in block 0 of relation base/12816/5696993  (seg40 slice1 172.16.3.31:6004 pid=24574)”.So I change the parameter， “SET zero_damaged_pages = on;”，execute vaccum command,but it dosen't work，still return error
![image](https://user-images.githubusercontent.com/71756944/122187321-8462a780-cec1-11eb-8646-4dd5c6e605f2.png)

 until today ，when I execute create table or truncate table return a error，just like this

CREATE TABLE "mid"."mid_01_candidate_posts_rel_lihkg" (
  "id" int4,
  "post_id" text COLLATE "pg_catalog"."default",
  "platform_type" text COLLATE "pg_catalog"."default",
  "post_type" text COLLATE "pg_catalog"."default",
  "post_content" text COLLATE "pg_catalog"."default",
  "comment_count" text COLLATE "pg_catalog"."default",
  "is_original" text COLLATE "pg_catalog"."default"
)distributed by (post_id)
;
> ERROR:  relation 15620498 deleted while still in use (relcache.c:2304)

truncate table mid.mid_01_candidate_posts_rel_twitter
> ERROR:  relation 12961698 deleted while still in use (relcache.c:2304)  (seg14 172.16.3.16:6002 pid=26916) (relcache.c:2304)

How to solve this problem ？
only change the parameters I can query this data
set gp_select_invisible to on;
![image](https://user-images.githubusercontent.com/71756944/122166156-c97bdf00-ceab-11eb-9505-89a4efb2348b.png)

**Comment by asimrp** [comment]
@eric0225 have your tried running `gpcheckcat` on your system?  It may be too late now but running `gpcheckcat` is strongly recommended after major events such as upgrade or cluster expansion or in the event of suspicious errors such as `invalid page ...`.

**Comment by asimrp** [comment]
Is there a backup you can restore the database from?  If so, consider restoring from past backup as an option.

Note that `gp_select_invisible` GUC is solely for debugging.  You are at risk of wrong results if this GUC remains on by mistake.

**Comment by kainwen** [comment]
I believe this issue is done.
