### ISSUE TITLE
Failed to complete obtain psql count Master gp_segment_configuration  Script Exiting!

### ISSUE THREAD

**Issue by Mr-Diaolvyu** [greenplum-db/gpdb#12177]
### Greenplum version or build
6.16.2

### OS version and uname -a
Linux DDB1 3.10.0-1160.25.1.el7.x86_64 #1 SMP Wed Apr 28 21:49:45 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

I checked the.csv log file in pg_log and received the following error.But I am using the command "gpinitsystem-c config/ gpinitsystem_config-h all_hosts -s DDB2" executed by gpadmin.Why use user postgres to connect to the database？

` 2021-06-17 18:03:34.470235 CST,"postgres","postgres",p7597,th-347494272,"[local]",,2021-06-17 18:03:34 CST,0,,,seg-1,,,,sx1,"FATAL","
28000","no pg_hba.conf entry for host ""[local]"", user ""postgres"", database ""postgres""",,,,,,,0,,"auth.c",627,
2021-06-17 18:03:34.686223 CST,"postgres","template1",p7678,th-347494272,"[local]",,2021-06-17 18:03:34 CST,0,,,seg-1,,,,sx1,"FATAL",
"28000","no pg_hba.conf entry for host ""[local]"", user ""postgres"", database ""template1""",,,,,,,0,,"auth.c",627, `

**Comment by wuj21** [comment]
Can you tell us how to reproduce this error?

**Comment by lij55** [comment]
Hi @Mr-Diaolvyu ,

do you still have this issue? could you please check you environment by `env | grep PG` when you hit this issue next time?
Besides, do you happen to set something environment in your bashrc or bash_profile?

**Comment by lij55** [comment]
closing issue as not enough information and response.
