### ISSUE TITLE
query finish request to process 156425

### ISSUE THREAD

**Issue by bloodwolf2020** [greenplum-db/gpdb#12196]
![image](https://user-images.githubusercontent.com/46953147/122880319-7783ff00-d36c-11eb-8d4a-21c291ac5f73.png)

all segment print this log, and no result to client.

**Comment by wuj21** [comment]
Please provide more information for this issue, including

1. Greenplum version
2. OS version
3. Expected  behavior
4. Actual behavior
5. Reproduce stes

**Comment by lij55** [comment]
closing because of lack of further information
