### ISSUE TITLE
ImportError: /usr/local/gpdb/lib/python/_posixsubprocess.so: undefined symbol: Py_InitModule4_64

### ISSUE THREAD

**Issue by fatCatGm** [greenplum-db/gpdb#12205]
when l user pip list in anaconda after l compile gp6.0 in arm64 computer
and  I got a mistake

ImportError: /usr/local/gpdb/lib/python/_posixsubprocess.so: undefined symbol: Py_InitModule4_64

**Comment by wuj21** [comment]
When you "source greenplum_path.sh", the python path is switched to the python combined with Greenplum. This is why you see this error.

**Comment by curry30000** [comment]
sorry did you solve the queation？
