### ISSUE TITLE
FailedAssertion("!(cdbpathlocus_is_valid(*_locus))", File: "indxpath.c", Line: 436)

### ISSUE THREAD

**Issue by ashwinstar** [greenplum-db/gpdb#12221]
### Greenplum version or build
5X_STABLE

### Expected behavior
No assertion failure

### Actual behavior
```
FailedAssertion("!(cdbpathlocus_is_valid(*_locus))", File: "indxpath.c", Line: 436)
```

### Step to reproduce the behavior
```sql
DROP TABLE clstr_tst_inh, clstr_tst, clstr_tst_s;
CREATE TABLE clstr_tst_s (rf_a SERIAL PRIMARY KEY, b INT) DISTRIBUTED BY (rf_a);
CREATE TABLE clstr_tst (a SERIAL PRIMARY KEY, b INT, c TEXT, d TEXT,
	CONSTRAINT clstr_tst_con FOREIGN KEY (b) REFERENCES clstr_tst_s)
	DISTRIBUTED BY (a);
CREATE INDEX clstr_tst_b ON clstr_tst (b);
CREATE TABLE clstr_tst_inh () INHERITS (clstr_tst);
SELECT a,b,c,substring(d for 30), length(d) from clstr_tst ORDER BY 1,2,3,4;
```

**Comment by kainwen** [comment]
The direct reason is when `building_index_pathkeys` later commits from upstream change behavior not to create EC if not found.

This makes the function `build_index_pathkeys` might return a NULL pointer, but later code does not consider this leads to this issue.

Need more time to dig into to see how to fix.

**Comment by seryozhasmirnov** [comment]
I am working on this issue and have crated the patch - soon it will be released when tests are ready.
https://github.com/arenadata/gpdb/pull/206

**Comment by seryozhasmirnov** [comment]
Hello, I have created new PR https://github.com/greenplum-db/gpdb/pull/12375
Please take a look.

Also the following comment in  [find_usable_indexes](https://github.com/greenplum-db/gpdb/blob/5X_STABLE/src/backend/optimizer/path/indxpath.c#L408-L412) function probably adds more confusion then clarification. 

```
	/*
	 * CDB: For appendrel child, pathkeys contain Var nodes in terms
	 * of the child's baserel.  Transform the pathkey list to refer to
	 * columns of the appendrel.
	 */
```
Can anyone give more information regarding it? Also parent relation reloptkind can be RELOPT_OTHER_MEMBER_REL so comment is not exactly correct.

**Comment by kainwen** [comment]
Fixed by https://github.com/greenplum-db/gpdb/pull/12375
