### ISSUE TITLE
Bitmapset is unsuitable for OID record

### ISSUE THREAD

**Issue by weinan003** [greenplum-db/gpdb#12270]
### Greenplum version or build
master branch

OID type is an unsigned int, but bitmapset requires a singed int as its value. So if the OID is bigger than signed INT_MAX. The overflow issue will crash in bitmapset function.

For example, as follow, in `pg_stat`, gpdb holds a bunch of bitmapsets as template buffer for OID records. Imagine that, if we create a table, the relation OID is bigger enough, gpdb will always receive an error for any operation for that relation (e.g. INSERT, TRUNCATE, etc.)

https://github.com/greenplum-db/gpdb/blob/6ec5206e453a3a466483f8700aee2d70fd2a20bc/src/backend/postmaster/pgstat.c#L4707-L4729

**Comment by kainwen** [comment]
Correct. Also bitmapset should be be used for huge integers.  They are suitable for relids. We have met this issue when developing gpexpand.

Would you please open a pr to resolve this? @weinan003

**Comment by weinan003** [comment]
I'm thinking about how to fix this? Using a hashtable to retire it? or maybe simply give an unsigned version bitmap set interface. How about you guys give a proposal first?

**Comment by kainwen** [comment]
> I'm thinking about how to fix this. Using a hashtable to retire it? or maybe simply give an unsigned version bitmap set interface. How about you guys give a proposal first?

The first idea is just use pg_list to mimic set. @JunfengYang

**Comment by JunfengYang** [comment]
Good catch!
Since the Oid numbers for each statement appear here should be small, a simple list could work well.
A hash table could also work.

**Comment by weinan003** [comment]
Cool, I'll fix it.

**Comment by ashwinstar** [comment]
Would be great to come up with failing test first. I know it might be difficult though maybe using fault injector or something creating the test before the fix would be expected.

**Comment by kainwen** [comment]
> Would be great to come up with failing test first. I know it might be difficult though maybe using fault injector or something creating the test before the fix would be expected.

This is not the first time to see the mis-use of bitmapset.

I remember previously we meet this:  https://github.com/greenplum-db/gpdb/issues/6888

Just when the OID is large enough, the overflow error will be found.

**Comment by ashwinstar** [comment]
That means its more critical to come up with test and fix the issue.

**Comment by kainwen** [comment]
Fixed by https://github.com/greenplum-db/gpdb/pull/12277

And I have commented there why I think without-case for this fix is acceptable.
