### ISSUE TITLE
gpcheck utility is not found

### ISSUE THREAD

**Issue by zhangyuvip** [greenplum-db/gpdb#1231]
gpcheck utility is not found

**Comment by danielgustafsson** [comment]
gpcheck was deprecated in previous closed source releases of Greenplum and has been removed. Created #1238 to remove leftover files from the deprecation.

**Comment by ivannovick** [comment]
thx @danielgustafsson and thx for associated PR

**Comment by ivannovick** [comment]
can we close this?

**Comment by Eulerizeit** [comment]
I'd keep it open until the documents have been changed.

**Comment by ivannovick** [comment]
I have added a docs todo item for 5.0
