### ISSUE TITLE
How to specify the address for coordinator/master when creating the demo cluster?

### ISSUE THREAD

**Issue by gfphoenix78** [greenplum-db/gpdb#12314]
When creating the demo cluster for Greenplum, the script `gpAux/gpdemo/demo_cluster.sh` is used. We could set `COORDINATOR_HOSTNAME=XXX` in GPDB 7X or `MASTER_HOSTNAME` in GPDB 6X, the result is that the `hostname` and `address` are the same values in gp_segment_configuration.

A simple example for my requirement is that I want to set the address to an IP address of the system, instead of the hostname.

The demo cluster uses the following command to create the cluster.
```
$GPPATH/gpinitsystem -a -c $CLUSTER_CONFIG -l $DATADIRS/gpAdminLogs ${STANDBY_INIT_OPTS} "$@"
```

We may easily specify the `hostname` and `address` in the `input configuration file`(via -I) explicitly, but sees no options in the configuration file(via -c) for this purpose.

**Comment by lij55** [comment]
hostname config is enough for demo cluster testing. it is easy to work around by changing the hostname to ip address in gp_segment_configuration through utility mode. closing this issue because it is not a common case.
