### ISSUE TITLE
Installation guide improvement on enabling core dump for GPDB

### ISSUE THREAD

**Issue by CC-Hsu** [greenplum-db/gpdb#12329]
### Greenplum version or build
GPDB 6.* installation guide
https://greenplum.docs.pivotal.io/6-17/install_guide/prep_os.html

### Expected behavior
Follow the page above, users should properly install a GPDB cluster with core dump feature enabled.

### Actual behavior
Following steps in the above link, core dump feature is still not enabled.
And I find that another part of setting for enabling core dump appears at the following page.
https://greenplum.docs.pivotal.io/6-17/best_practices/sysconfig.html

Maybe this part should be improved.

Best Regards.

**Comment by kainwen** [comment]
Fixed by https://github.com/greenplum-db/gpdb/pull/12598 (master) and 14d7ae0cd55be
