### ISSUE TITLE
Unable to detoast

### ISSUE THREAD

**Issue by fengttt** [greenplum-db/gpdb#1234]
create table a (i int, t text);
insert into a select i, i::text from generate_series(1, 10) i;
create table b as select i + 1 as i, t from a;
create table c as select i + 2 as i, t from a;

Now run the following query,
select *
from a inner join b on coalesce(a.t, '0') = coalesce(b.t, '0')
where not exists 
    ( select 1 from c
        where coalesce(c.t, '0') = coalesce(b.t, '0')
        and coalesce(b.t, '1') = coalesce(a.t, '1')
        and coalesce(a.t, '2') = coalesce(c.t, '2')
    )
;

psql:bug2.sql:9: ERROR:  Unable to detoast datum (tuptoaster.c:181)  (seg0 slice3 127.0.0.1:34321 pid=30683) (cdbdisp.c:220)

**Comment by fengttt** [comment]
This is latest head, using planner, not orca.

**Comment by ivannovick** [comment]
@fengttt can you help us try it on ORCA as well?  Do you have explain?

**Comment by asimrp** [comment]
Did a bit of initial investigation.  `ExecEvalScalarVar()` is returning a NULL datum without `isNull` argument set to true.  This datum is passed to `varattrib_untoast_ptr_len()` which does not tolerate a NULL datum and fails with the reported error.

Stack trace:
```
2016-10-20 00:54:45.400533 PDT,"apraveen","postgres",p77615,th2131047184,"127.0.0.1","62073",2016-10-20 00:54:45 PDT,32844,con6,cmd81,seg0,slice3,dx41,x32844,sx1,"ERROR","XX000","Unable to detoast datum (tuptoaster.c:181)",,,,,,"\
select *
from a inner join b on coalesce(a.t, '0') = coalesce(b.t, '0')
where not exists
( select 1 from c
where coalesce(c.t, '0') = coalesce(b.t, '0')
and coalesce(b.t, '1') = coalesce(a.t, '1')
and coalesce(a.t, '2') = coalesce(c.t, '2')
)
;",0,,"tuptoaster.c",181,"Stack trace:
1    0x10688214d postgres errstart + 0x5dd
2    0x1061c30f9 postgres varattrib_untoast_ptr_len + 0x59
3    0x1069c11c1 postgres hashDatum + 0x6c1
4    0x1069c0aed postgres cdbhash + 0x2d
5    0x1064cc476 postgres evalHashKey + 0xe6
6    0x1064cc0c0 postgres doSendTuple + 0x220
7    0x1064c9a1e postgres execMotionSender + 0x19e
8    0x1064c8a13 postgres ExecMotion + 0x1d3
9    0x10647a89e postgres ExecProcNode + 0x49e
10   0x10646cf93 postgres ExecutePlan + 0x193
11   0x10646cb7d postgres ExecutorRun + 0x43d
12   0x1066f8492 postgres PortalRunSelect + 0x152
13   0x1066f7fe3 postgres PortalRun + 0x303
14   0x1066f2031 postgres exec_mpp_query + 0x1061
15   0x1066ef921 postgres PostgresMain + 0x1671
16   0x106665022 postgres BackendRun + 0x2e2
17   0x10666441b postgres BackendStartup + 0x18b
18   0x10665f973 postgres ServerLoop + 0x543
19   0x10665db56 postgres PostmasterMain + 0x14a6
20   0x106535c26 postgres main + 0x346
```

**Comment by fengttt** [comment]
I am pretty sure ORCA plan will work fine.    

Guts feeling is that this bug is deeply inside cdbsubplan/cdbdisp and postgres init plan in general.   It is tough.

**Comment by gaos1** [comment]
added a tracker story to triage it.

**Comment by Eulerizeit** [comment]
@danielgustafsson does  this effect the work you're doing with pg_upgrade?

**Comment by hlinnaka** [comment]
This seems to be the essentially same bug as was fixed in PR #1400, but for NOT EXISTS rather than EXISTS. @dhanashreek89, @vraghavan78, @xinzweb, can you fix the issue more completely, please? This code seriously needs to be refactored.

**Comment by hsyuan** [comment]
Fixed in PR https://github.com/greenplum-db/gpdb/pull/1477

**Comment by hsyuan** [comment]
Closing this issue, since it was resolved in commit: https://github.com/greenplum-db/gpdb/commit/cbf16d51bd4f0dcd9a359df8d1dc1f9d9194fcfc
