### ISSUE TITLE
7X: pg_ctl start -w doesn't wait for walreceiver to be up

### ISSUE THREAD

**Issue by divyeshddv** [greenplum-db/gpdb#12363]
### Greenplum version or build
7.x 
3abc21ca888af1655c9141b0184958f2a15eb890

### OS version and uname -a
MacOS Catalina

### Installation information ( pg_config )
'--prefix=/usr/local/gpdb7' '-disable-orca' '--enable-depend' '--enable-debug' '--enable-cassert' '--disable-pxf' '--disable-gpcloud' '--without-perl' '--with-python' '--with-gssapi' '--without-zstd' '--disable-gpfdist'

### Expected behavior
pg_ctl -w start should wait until the recovering segment has `gp_segment_configuration.status = up`. 
segment is marked as `up` in `gp_segment_configuration` when the walreceiver starts up.
pg_ctl -w should wait for this process to start, so that after FTS probe is triggered, the segment gets marked `up` in `gp_segment_configuration`

### Actual behavior
pg_ctl -w start completes without waiting

```
[worker0] finished cmd: Starting seg at dir /Users/vanjared/gpdb7/gpAux/gpdemo/datadirs/dbfast2/demoDataDir1 cmdStr='env GPSESSID=0000000000 GPERA=797e9b775a8010af_210720143526 $GPHOME/bin/pg_ctl -D /Users/vanjared/gpdb7/gpAux/gpdemo/datadirs/dbfast2/demoDataDir1 -l /Users/vanjared/gpdb7/gpAux/gpdemo/datadirs/dbfast2/demoDataDir1/log/startup.log -w -t 600 -o " -p 7003 -c gp_role=execute " start 2>&1'  had result: cmd had rc=0 completed=True halted=False
  stdout='waiting for server to start.... done
server started
```
But the segment is down in gp_segment_configuration even after FTS probe

### Step to reproduce the behavior:

make a cluster
```
make create-demo-cluster
 ```
get a segment unreachable
```
psql
> set allow_system_table_mods = 1; 
> update gp_segment_configuration set hostname = 'unreaachable', address='unreachable' where dbid = 3;
```
add a large table
```
> create table t1 as select * from generate_series(1,100000000) as a;
```
make the segment reachable again
```
> update gp_segment_configuration set hostname = '<appropriate_hostname>', address='<appropriate_address>' where dbid = 3;
```
recover segment using gprecoverseg  (which internally will run pg_rewind and pg_ctl start -w)
```
gprecoverseg -av
```
check segment configuration as soon as gprecoverseg ends
```
> select * from  gp_segment_configuration;
```

### Comments/ Impact:
This is a regression from 6X. 
This would break the gprecoverseg contract, which requires segments to be up as when it completes successfully.
This can also lead to flaky tests, (eg: behave tests which check if segments are up after gprecoverseg completes successfully - same as repro)
Other calls (if any) to `pg_ctl start -w`

**Comment by ashwinstar** [comment]
Lets me clarify the expectation:
`pg_ctl -w start` for mirror should wait until the walreceiver process is spawned.

Context: Mirror is marked as up in gp_segment_configuration via FTS probe, when primary detects mirror connection to it. This happens when the walreceiver starts up and connects to Primary. `pg_ctl -w` working correctly for mirror is must and  important to meet the `gprecoverseg` contract that at end of `gprecoverseg` all recovered mirrors should be in `UP` state in gp_segment_configuration.
