### ISSUE TITLE
CURRENT_USER/SESSION_USER can not be used as an owner in ALTER TABLE ... OWNER TO

### ISSUE THREAD

**Issue by gfphoenix78** [greenplum-db/gpdb#12384]
### Greenplum version or build
GPDB 6X, upstream(PG 9.4) has this issue.

GPDB 7X and upstream with a higher version don't have this issue.

### Expected behavior
No error
### Actual behavior
Report syntax error
### Step to reproduce the behavior

```
gpadmin=# SELECT SESSION_USER, CURRENT_USER;
 session_user | current_user
--------------+--------------
 gpadmin      | gpadmin
(1 row)

gpadmin=# ALTER TABLE  ONLY t1 OWNER TO u1;
ALTER TABLE
gpadmin=# ALTER TABLE  ONLY t1 OWNER TO CURRENT_USER;
ERROR:  syntax error at or near "CURRENT_USER"
LINE 1: ALTER TABLE  ONLY t1 OWNER TO CURRENT_USER;
                                      ^
gpadmin=# ALTER TABLE  ONLY t1 OWNER TO SESSION_USER;
ERROR:  syntax error at or near "SESSION_USER"
LINE 1: ALTER TABLE  ONLY t1 OWNER TO SESSION_USER;
                                      ^
```

We may need to backport the patch from upstream.

**Comment by gfphoenix78** [comment]
The patch is https://github.com/postgres/postgres/commit/31eae6028eca4365e7165f5f33fee1ed0486aee0

**Comment by dpandhi-git** [comment]
closing as 7x does not have this issue. not fixing for 6x
