### ISSUE TITLE
[6X]: ERROR: unlogged sequences are not supported

### ISSUE THREAD

**Issue by gfphoenix78** [greenplum-db/gpdb#12383]
### Greenplum version or build
GPDB 6X
7X don't have this issue.

### Expected behavior
The referenced sequence should be logged, and the creation should succeed.
### Actual behavior
`ERROR: unlogged sequences are not supported`
### Step to reproduce the behavior
```
gpadmin=# CREATE UNLOGGED TABLE t2(b0 int, c0 serial UNIQUE PRIMARY KEY, c1 REAL );
ERROR:  unlogged sequences are not supported
```

The above will create an unlogged table, and the type of c0 is `serial` which result in creating a new sequence type. The persistence type of the sequence inherits from table t2, which is unlogged.
In upstream or GPDB 7X, the persistence type of the sequence is still `RELPERSISTENCE_PERMANENT`, so it will successfully create an unlogged table.

This issue may be of low priority or even be ignored, which depends on how useful it is in production.

**Comment by dpandhi-git** [comment]
Main (7X) does not have this issue.
In future if we run sqlancer we will take this requirement by then
