### ISSUE TITLE
gprecoverseg -i recover_config_file. directory permission error 700

### ISSUE THREAD

**Issue by gj-zhang** [greenplum-db/gpdb#12391]
### Greenplum version or build
PostgreSQL 9.4.24 (Greenplum Database 6.17.1 build commit:3633e368b674f35eb9609717eed42569ab138858) on x86_64-unknown-linux-gnu, compiled by gcc (GCC) 6.4.0, 64-bit compiled on Jul 20 2021 19:2
1:12
### OS version and uname -a
4.14.141-1.el7.x86_64 #1 SMP Wed Sep 4 21:29:48 CST 2019 x86_64 x86_64 x86_64 GNU/Linux

### Expected behavior
gprecoverseg -i recover_config   success

### Actual behavior
gprecoverseg -i recover_config   error
```shell
2021-07-23 17:06:25.701883 CST,,,p1459286,th-322299776,,,,0,,,seg0,,,,,"FATAL","55000","data directory ""/data/mirror1/gpseg0"" has group or world access","Permissions should be u=rwx (0700).",,,,,,,"checkDataDir","postmaster.c",1696,

```
### Step to reproduce the behavior

https://github.com/greenplum-db/gpdb/issues/12367#issuecomment-885512615

**Comment by gj-zhang** [comment]
Can someone take a look?

**Comment by kaknikhil** [comment]
@gj-zhang 

I replied to your comment in the other issue #12367. We can probably close this issue and track it using the original issue

**Comment by gj-zhang** [comment]
OK
