### ISSUE TITLE
file gpos/base.h is missing.

### ISSUE THREAD

**Issue by bh99** [greenplum-db/gpdb#124]
when  building with --enable-orca :

In file included from CConfigParamMapping.cpp:19:0:
../../../../src/include/gpopt/config/CConfigParamMapping.h:18:23: fatal error: gpos/base.h: No such file or directory
 #include "gpos/base.h"

**Comment by addisonhuddy** [comment]
Hi @bh99, we are really close to releasing both gpos and orca. Exciting stuff just around the corner.
