### ISSUE TITLE
The Assert in _mdfd_openseg is not applicable to AO table

### ISSUE THREAD

**Issue by hidva** [greenplum-db/gpdb#12408]
https://github.com/greenplum-db/gpdb/blob/0ef47d0543180234ccfd3007405afe2c81bc8a5d/src/backend/storage/smgr/md.c#L1898

The `_mdfd_openseg()` may be invoked for AO tables, and `_mdnblocks(reln, forknum, v) <= ((BlockNumber) RELSEG_SIZE)` may be false here.

![image](https://user-images.githubusercontent.com/17427025/127469791-01e6044b-8dfe-4a62-aaae-c6d2788052a6.png)

**Comment by JunfengYang** [comment]
Thanks for reporting!

**Comment by geekbosszhang** [comment]
What's the GP version are you using? Could you please paste the reproduction steps?

**Comment by kainwen** [comment]
fixed by https://github.com/greenplum-db/gpdb/pull/12557
