### ISSUE TITLE
VACUUM FULL error with catalog error in relfrozenxid

### ISSUE THREAD

**Issue by soulfere** [greenplum-db/gpdb#12400]
### Greenplum version or build
6.3.0
### OS version and uname -a
CentOS 7.3

Get error message when I do VACUUM FULL on pg_attribute table.
VACUUM FULL ANALYZE pg_attribute;

found xmin 19129071 from before relfrozenxid 19520614

I did found the release note for GP6.11 which solved this problem.
Like this issue mentioned https://github.com/greenplum-db/gpdb/issues/10933.

I read the source code, I think this fix the issue when do vacuum.
But if the catalog corrupt of relfrozenxid has already happened, can I solve the problem I met now by upgreading 6.11?

If not ,is there any other way to fix the catalog corruption?

**Comment by wuj21** [comment]
As my understanding, the question is whether upgrading to 6.11 can fix catalog corruption or not, right? The answer is no. For catalog corruption, please use gpcheckcat to check whether it is corrupted or not.

**Comment by ashwinstar** [comment]
> If not ,is there any other way to fix the catalog corruption?

This specific `relfrozenxid` incorrect value, if really wish can be manually fixed but updating the `pg_class` table (yes with extreme caution). Easiest would be find the lowest `datfrozenxid` value across all databases in system and use that value to update the `relfrozenxid`. You will have to use the GUC `allow_system_table_mods` to edit the catalog tables. Again reiterating needs to be done with extreme caution they kind of catalog fixes.
