### ISSUE TITLE
[6X] Support non-standby mode in recovery.conf

### ISSUE THREAD

**Issue by usernamedt** [greenplum-db/gpdb#12419]
### Greenplum version or build
Greenplum 6.16 

Hi! We want to support Greenplum physical backups in [WAL-G.](https://github.com/wal-g/wal-g) Thanks to the [Andrey's PR](https://github.com/greenplum-db/gpdb/pull/12076), Greenplum now has PITR backported to the 6X and working `pg_start_backup/pg_stop_backup` API. However, when I am trying to start the Greenplum master restored from a physical backup, I get the following error: 
```
"FATAL","22023","recovery command file ""recovery.conf"" request for standby mode not specified",,,,,,,0,,"xlog.c",5465
```

This happens because the non-standby mode in recovery.conf is disabled in Greenplum 6X. Source code: https://github.com/greenplum-db/gpdb/blob/1c70f219d2dfe14eb308100cc9de945e4f3804b5/src/backend/access/transam/xlog.c#L5462

Is there a possibility to restore the original functionality and allow the non-standby mode in recovery.conf? I did not find any specific reason why it has been disabled.

Thanks!

**Comment by soumyadeep2007** [comment]
PR (https://github.com/greenplum-db/gpdb/pull/12424) merged which closes this issue
