### ISSUE TITLE
ERROR:  invalid memory alloc request size 1073741824 (context 'AggContext')

### ISSUE THREAD

**Issue by zhangjianlongdba** [greenplum-db/gpdb#12423]
### Greenplum version or build
I have tried on 6.16.0, 6.16.3 and 6.17.1. This problem exists
### OS version and uname -a
Linux host27 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
### Installation information ( pg_config )
1 master 3 segments
### Actual behavior
This error occurs when the sql 4 of TPCH is executed under 1T capacity

**Comment by zhangjianlongdba** [comment]
I have tried on 6.16.0, 6.16.3 and 6.17.1. This problem exists
Linux host27 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
This error occurs when the sql4 of TPCH is executed under 1T capacity

ERROR:  invalid memory alloc request size 1073741824 (context 'AggContext') (mcxt.c:1378) (mcxt.c:568)  (seg2 slice1 192.168.4.31:7000 pid=53263) (mcxt.c:568)

**Comment by kainwen** [comment]
@zhangjianlongdba 
Sorry forget this for a long time. Do you still hit this issue?

Can you please tell us how you run TPCH?

1. what is the cluster config?
2. what is your table definition?

If possible can you please paste the errored out segment log and the plan here?

**Comment by kainwen** [comment]
We have internal TPC-H benchmark running every week. Long time no response also in the issue we have little information (plan, log...).

Close it. Feel free to re-open it if needed.
