### ISSUE TITLE
pg_ctl does not start successfully

### ISSUE THREAD

**Issue by mishima340** [greenplum-db/gpdb#12440]
### Greenplum version or build
7.0.0-alpha.0

### OS version and uname 
ubuntu 18.04
mishima

### autoconf options used ( config.status --config )
none

### Expected behavior

if we execute pg_ctl, gpdb starts successfully.

### Actual behavior

mishima@ubuntu:~/db$ /usr/local/gpdb/bin/pg_ctl -D testdb start
waiting for server to start....2021-08-11 14:13:48.584475 JST,,,p453945,th-188368512,,,,0,,,seg-10000,,,,,"FATAL","22023","dbid (from -b option) is not specified or is invalid.  This value must be >= 0, or >= -1 in utility mode.  The dbid value to pass can be determined from this server's entry in the segment configuration; it may be -1 if running in utility mode.",,,,,,,,"PostmasterMain","postmaster.c",1086,
 stopped waiting
pg_ctl: could not start server
Examine the log output.
mishima@ubuntu:~/db$

**Comment by ashwinstar** [comment]
Don't see any incorrect behavior. It reported why can't start, missing dbid.

Based on information shared no way to guess why dbid is missing on this system, so you will have to debug little more or help us with repro to help.

**Comment by gfphoenix78** [comment]
@mishima340 Could you describe your issue in more detail?

**Comment by mishima340** [comment]
Thank you for your response.

 Our company is searching OSS HTAP software. Therefore, we are interested in Greenplum.
We want to conduct some experiments.

My environment is as follows:
hardware: MacBook Pro
virtualization: VMware Fusion
OS: Ubuntu 20.04

I downloaded the source code of gpdb version 7.0.0-alpha.0 from GitHub.
Then, I executed as follows:
% ./configure
% make
% make install

I confirmed executable files have been created successfully.
Then, I executed as follows:

% initdb testdb
% pg_ctl -D testdb start

The processes of gpdb have not started successfully and an error message is as follows:

mishima@ubuntu:/db$ /usr/local/gpdb/bin/pg_ctl -D testdb start
waiting for server to start....2021-08-11 14:13:48.584475 JST,,,p453945,th-188368512,,,,0,,,seg-10000,,,,,"FATAL","22023","dbid (from -b option) is not specified or is invalid. This value must be >= 0, or >= -1 in utility mode. The dbid value to pass can be determined from this server's entry in the segment configuration; it may be -1 if running in utility mode.",,,,,,,,"PostmasterMain","postmaster.c",1086,
stopped waiting
pg_ctl: could not start server
Examine the log output.
mishima@ubuntu:/db$

Please help us.

Thanks

**Comment by ashwinstar** [comment]
> Our company is searching OSS HTAP software. Therefore, we are interested in Greenplum.

Thank you for your interest and playing with Greenplum. The paper would be interesting to you if not already looked into [ Greenplum: A Hybrid Database for Transactional and Analytical Workloads](https://arxiv.org/pdf/2103.11080.pdf)

> % initdb testdb
> % pg_ctl -D testdb start

Well that's PostgreSQL single node command to initialize and start. Greenplum is MPP (distributed PostgreSQL) system. Means it runs many PostgreSQL instances to provide the parallelism. Hence, for initializing Greenplum, please refer to `gpinitsystem` utility. And to start `gpstart`. These are mostly utilities as wrapper on top of PostgreSQL commands like initdb, pg_ctl though able to provide cluster of PostgreSQL nodes which can be deployed across different hosts and act a single database. Refer to [Greenplum Install Guide](https://gpdb.docs.pivotal.io/6-17/install_guide/install_guide.html) and [Greenplum Admin Guide](https://gpdb.docs.pivotal.io/6-17/admin_guide/admin_guide.html)

**Comment by mishima340** [comment]
Thank you for your information.
I will check it.

**Comment by mishima340** [comment]
Hi,
I am reading the documents that you told me.
This page
https://gpdb.docs.pivotal.io/6-17/admin_guide/managing/startstop.html
says that if I want to start gpdb, gpstart utility.
But before using gpstart, I have to initialize database such as initdb of the original PostgreSQL.
This page also says that we have to use gpinitsystem utility but I cannot find how to use gpinitsystem.
What page should I read for gpinitsystem?

Thanks.

**Comment by ashwinstar** [comment]
I provided pointer to Install Guide as well. That has all the details for Greenplum installation. Specifically, for `gpinitsystem` https://gpdb.docs.pivotal.io/6-17/utility_guide/ref/gpinitsystem.html. If you do goggle searches should be able to easily find the documents for Greenplum.

**Comment by ashwinstar** [comment]
Closing this issue as no further action on it.
