### ISSUE TITLE
CONNECTION LIMIT doesn't work as expected

### ISSUE THREAD

**Issue by cobolbaby** [greenplum-db/gpdb#12471]
### Greenplum version or build

- GP: 6.16.0

### OS version and uname -a

- Docker Container: Centos7
- Docker Host: Linux mdw 4.15.0-117-generic # 118-Ubuntu SMP Fri Sep 4 20:02:41 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

### Expected behavior

After I set the `CONNECTION LIMIT 200` for the role `sparkuser`, I could see `sorry, too many clients already` in the pg_log, but the real connections still exceed the limit.

### Actual behavior

<img width="1127" alt="屏幕快照 2021-08-21 下午5 13 53" src="https://user-images.githubusercontent.com/11460848/130317233-de48e331-3f97-4358-838f-e859fbfcf24b.png">

<img width="1090" alt="屏幕快照 2021-08-21 下午5 14 32" src="https://user-images.githubusercontent.com/11460848/130317227-c9f814d8-0b47-4f7b-b142-734dc733b496.png">

[pg_stat_activity.csv](https://github.com/greenplum-db/gpdb/files/7025254/data-1629538515415.csv)

**Comment by ashwinstar** [comment]
I am not able to repro the problem. I created a user with 2 as connection limit and on third connection I got the error `FATAL:  too many connections for role`.

**Comment by cobolbaby** [comment]
@ashwinstar,  whether the superuser will be limited by the `CONNECTION LIMIT`.

```
CREATE ROLE sparkuser WITH
  LOGIN
  SUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION
  CONNECTION LIMIT 200
  PASSWORD 'xxxxx';
```

**Comment by ashwinstar** [comment]
> @ashwinstar,  whether the superuser will be limited by the `CONNECTION LIMIT`.
> 
> 
> 
> ```
> 
> CREATE ROLE sparkuser WITH
> 
>   LOGIN
> 
>   SUPERUSER
> 
>   INHERIT
> 
>   NOCREATEDB
> 
>   NOCREATEROLE
> 
>   NOREPLICATION
> 
>   CONNECTION LIMIT 200
> 
>   PASSWORD 'xxxxx';
> 
> ```

![image](https://user-images.githubusercontent.com/11396815/131771224-8961b87e-6507-4e9d-8dad-f7987ec28861.jpeg) :) no once Superuser you already have too many powers

**Comment by cobolbaby** [comment]
Finally confirm that the superuser will ignore this restriction?
