### ISSUE TITLE
compile error while enable LOCK_DEBUG

### ISSUE THREAD

**Issue by LittleWuCoding** [greenplum-db/gpdb#12484]
### Greenplum version or build
master branch 
On file src/backend/storage/lmgr/lwlock.c  function LWLockTryLockWaiting(PGPROC *proc, volatile LWLock *l) use macro T_ID to get the lockid but the macro _ID was deleted by early commit.

https://github.com/greenplum-db/gpdb/blob/master/src/backend/storage/lmgr/lwlock.c#L593
https://github.com/greenplum-db/gpdb/blob/master/src/backend/storage/lmgr/lwlock.c#L599

Other place used the macro T_ID(lock) 
```
printf( "%d",  T_ID(lock);
```
 just replace it with :
```
printf( "%p",  lock);
```
for example: 
https://github.com/greenplum-db/gpdb/blob/master/src/backend/storage/lmgr/lwlock.c#L223
I think this is a incomplete modification of early commit, please correct it~

**Comment by kainwen** [comment]
Fixed by https://github.com/greenplum-db/gpdb/pull/12522
