### ISSUE TITLE
join key support is not distinct from

### ISSUE THREAD

**Issue by jingwen-ywb** [greenplum-db/gpdb#12507]

**Comment by lij55** [comment]
Hi @jingwen-ywb ,

thanks for reporting the issue. It is related with ORCA, right?
could you please update with more details about following information? it would be helpful for us to identify your found. 
1. Greenplum version
2. the DDL (table) of t1 and t2
Thanks!

**Comment by dpandhi-git** [comment]
closing with no further information received
