### ISSUE TITLE
Can't create MATERIALIZED VIEW after drop it

### ISSUE THREAD

**Issue by jinmojing** [greenplum-db/gpdb#12508]
### Greenplum version or build
gpdb6.8
### OS version and uname -a
ubuntu 18.04
### Expected behavior
1. drop MATERIALIZED VIEW glp_tmall_sku_view;    successfully drop this view
2. create MATERIALIZED VIEW glp_tmall_sku_view xxx;   can create view with new data
### Actual behavior
1. drop MATERIALIZED VIEW glp_tmall_sku_view;    successfully drop this view
2. create MATERIALIZED VIEW glp_tmall_sku_view xxx;   an error happened
NOTICE:  Table doesn't have 'DISTRIBUTED BY' clause. Creating a NULL policy entry.
ERROR:  type "glp_tmall_sku_view" already exists
HINT:  A relation has an associated type of the same name, so you must use a name that doesn't conflict with any existing type.

I checked pg_class and pg_namespace , not found "glp_tmall_sku_view"
demo=#     SELECT relname  FROM pg_catalog.pg_class c
   JOIN   pg_catalog.pg_namespace n ON n.oid = c.relnamespace
   WHERE  n.nspname = 'public'
   AND    c.relkind = 'm' ;
          relname
---------------------------
 mengniu_sku_view
 item2_view_422822
 item2_view_110107
 item2_view_120101
 item2_view_440104
 item2_view_110115
 item2_view_110112
 item2_view_320623
 item2_view_110116
 item2_view_110118
 item2_view_110101
 item2_view_110106
 item2_view_440111
 item2_view_640121
 item2_view_441523
 item2_view_441521
 item2_view_110109
 item2_view_441501
 item2_view_441581
 item2_view_510107
 item2_view_110114
 item2_view_500103
 item2_view_500120
 item2_view_360704
 item2_view_210124
 item2_view_350921
 item2_view_330182
 item2_view_411481
 item2_view_110102
 item2_view_500236
 item2_city_list_view_2019
 item2_city_list_view_2020
 item2_city_list_view_2021
 item2_view_110113
 item2_view_110111
 item2_view_110108
(36 rows)

**Comment by adam8157** [comment]
Not reproduced with the master branch or 6.17.0, closing.

Free free to reopen it with a repro, if it's still a problem with the latest version, thanks.
