### ISSUE TITLE
gpinitsystem error

### ISSUE THREAD

**Issue by mishima340** [greenplum-db/gpdb#12530]
### Greenplum version or build
6.17.1
### OS version and uname -a
ubuntu 18.04
Linux gpmaster 5.4.0-1055-aws #58~18.04.1-Ubuntu SMP Wed Jul 28 03:04:50 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Actual behavior

ubuntu@gpmaster:/usr/local/greenplum-db$ gpinitsystem -c gpinitsystem_config -h hostfile_gpinitsystem
20210902:05:32:10:003472 gpinitsystem:gpmaster:ubuntu-[INFO]:-Checking configuration parameters, please wait...
20210902:05:32:10:003472 gpinitsystem:gpmaster:ubuntu-[INFO]:-Reading Greenplum configuration file gpinitsystem_config
20210902:05:32:10:003472 gpinitsystem:gpmaster:ubuntu-[INFO]:-Locale has not been set in gpinitsystem_config, will set to default value
20210902:05:32:10:003472 gpinitsystem:gpmaster:ubuntu-[INFO]:-Locale set to en_US.utf8
20210902:05:32:10:003472 gpinitsystem:gpmaster:ubuntu-[INFO]:-No DATABASE_NAME set, will exit following template1 updates
20210902:05:32:10:003472 gpinitsystem:gpmaster:ubuntu-[INFO]:-MASTER_MAX_CONNECT not set, will set to default value 250
20210902:05:32:10:003472 gpinitsystem:gpmaster:ubuntu-[WARN]:-Master open file limit is 1024 should be >= 65535
20210902:05:32:10:003472 gpinitsystem:gpmaster:ubuntu-[INFO]:-Checking configuration parameters, Completed
20210902:05:32:10:003472 gpinitsystem:gpmaster:ubuntu-[INFO]:-Commencing multi-home checks, please wait...
..
20210902:05:32:11:003472 gpinitsystem:gpmaster:ubuntu-[INFO]:-Configuring build for standard array
20210902:05:32:11:003472 gpinitsystem:gpmaster:ubuntu-[INFO]:-Commencing multi-home checks, Completed
20210902:05:32:11:003472 gpinitsystem:gpmaster:ubuntu-[INFO]:-Building primary segment instance array, please wait...
............
20210902:05:32:26:003472 gpinitsystem:gpmaster:ubuntu-[INFO]:-Checking Master host
20210902:05:32:26:003472 gpinitsystem:gpmaster:ubuntu-[INFO]:-Checking new segment hosts, please wait...
Warning: the RSA host key for 'gpmaster' differs from the key for the IP address '172.31.27.156'
Offending key for IP in /home/ubuntu/.ssh/known_hosts:2
Matching host key in /home/ubuntu/.ssh/known_hosts:6
Are you sure you want to continue connecting (yes/no)? yes
20210902:05:32:30:003472 gpinitsystem:gpmaster:ubuntu-[WARN]:-Host gpmaster open files limit is 1024 should be >= 65535
Warning: the RSA host key for 'gpmaster' differs from the key for the IP address '172.31.27.156'
Offending key for IP in /home/ubuntu/.ssh/known_hosts:2
Matching host key in /home/ubuntu/.ssh/known_hosts:6
Are you sure you want to continue connecting (yes/no)? yes
Warning: the RSA host key for 'gpmaster' differs from the key for the IP address '172.31.27.156'
Offending key for IP in /home/ubuntu/.ssh/known_hosts:2
Matching host key in /home/ubuntu/.ssh/known_hosts:6
Are you sure you want to continue connecting (yes/no)? yes
20210902:05:32:36:003472 gpinitsystem:gpmaster:ubuntu-[WARN]:-Host gpmaster open files limit is 1024 should be >= 65535
Warning: the RSA host key for 'gpmaster' differs from the key for the IP address '172.31.27.156'
Offending key for IP in /home/ubuntu/.ssh/known_hosts:2
Matching host key in /home/ubuntu/.ssh/known_hosts:6
Are you sure you want to continue connecting (yes/no)? yes
............
20210902:05:33:09:003472 gpinitsystem:gpmaster:ubuntu-[INFO]:-Checking new segment hosts, Completed
20210902:05:33:09:003472 gpinitsystem:gpmaster:ubuntu-[INFO]:-Greenplum Database Creation Parameters
20210902:05:33:09:003472 gpinitsystem:gpmaster:ubuntu-[INFO]:---------------------------------------
20210902:05:33:09:003472 gpinitsystem:gpmaster:ubuntu-[INFO]:-Master Configuration
20210902:05:33:09:003472 gpinitsystem:gpmaster:ubuntu-[INFO]:---------------------------------------
20210902:05:33:09:003472 gpinitsystem:gpmaster:ubuntu-[INFO]:-Master instance name       = Greenplum Data Platform
20210902:05:33:09:003472 gpinitsystem:gpmaster:ubuntu-[INFO]:-Master hostname            = gpmaster
20210902:05:33:09:003472 gpinitsystem:gpmaster:ubuntu-[INFO]:-Master port                = 5432
20210902:05:33:09:003472 gpinitsystem:gpmaster:ubuntu-[INFO]:-Master instance dir        = /data/master/gpseg-1
20210902:05:33:09:003472 gpinitsystem:gpmaster:ubuntu-[INFO]:-Master LOCALE              = en_US.utf8
20210902:05:33:09:003472 gpinitsystem:gpmaster:ubuntu-[INFO]:-Greenplum segment prefix   = gpseg
20210902:05:33:09:003472 gpinitsystem:gpmaster:ubuntu-[INFO]:-Master Database            = 
20210902:05:33:09:003472 gpinitsystem:gpmaster:ubuntu-[INFO]:-Master connections         = 250
20210902:05:33:09:003472 gpinitsystem:gpmaster:ubuntu-[INFO]:-Master buffers             = 128000kB
20210902:05:33:09:003472 gpinitsystem:gpmaster:ubuntu-[INFO]:-Segment connections        = 750
20210902:05:33:09:003472 gpinitsystem:gpmaster:ubuntu-[INFO]:-Segment buffers            = 128000kB
20210902:05:33:09:003472 gpinitsystem:gpmaster:ubuntu-[INFO]:-Checkpoint segments        = 8
20210902:05:33:09:003472 gpinitsystem:gpmaster:ubuntu-[INFO]:-Encoding                   = UNICODE
20210902:05:33:09:003472 gpinitsystem:gpmaster:ubuntu-[INFO]:-Postgres param file        = Off
20210902:05:33:09:003472 gpinitsystem:gpmaster:ubuntu-[INFO]:-Initdb to be used          = /usr/local/greenplum-db-6.17.1/bin/initdb
20210902:05:33:09:003472 gpinitsystem:gpmaster:ubuntu-[INFO]:-GP_LIBRARY_PATH is         = /usr/local/greenplum-db-6.17.1/lib
20210902:05:33:09:003472 gpinitsystem:gpmaster:ubuntu-[INFO]:-HEAP_CHECKSUM is           = on
20210902:05:33:09:003472 gpinitsystem:gpmaster:ubuntu-[INFO]:-HBA_HOSTNAMES is           = 0
20210902:05:33:09:003472 gpinitsystem:gpmaster:ubuntu-[WARN]:-Ulimit check               = Warnings generated, see log file <<<<<
20210902:05:33:09:003472 gpinitsystem:gpmaster:ubuntu-[INFO]:-Array host connect type    = Single hostname per node
20210902:05:33:09:003472 gpinitsystem:gpmaster:ubuntu-[INFO]:-Master IP address [1]      = 172.31.27.156
20210902:05:33:09:003472 gpinitsystem:gpmaster:ubuntu-[INFO]:-Master IP address [2]      = ::1
20210902:05:33:09:003472 gpinitsystem:gpmaster:ubuntu-[INFO]:-Master IP address [3]      = fe80::da:65ff:fee2:a529
20210902:05:33:09:003472 gpinitsystem:gpmaster:ubuntu-[INFO]:-Standby Master             = Not Configured
20210902:05:33:09:003472 gpinitsystem:gpmaster:ubuntu-[INFO]:-Number of primary segments = 6
20210902:05:33:09:003472 gpinitsystem:gpmaster:ubuntu-[INFO]:-Total Database segments    = 12
20210902:05:33:09:003472 gpinitsystem:gpmaster:ubuntu-[INFO]:-Trusted shell              = ssh
20210902:05:33:09:003472 gpinitsystem:gpmaster:ubuntu-[INFO]:-Number segment hosts       = 2
20210902:05:33:09:003472 gpinitsystem:gpmaster:ubuntu-[INFO]:-Mirroring config           = OFF

20210902:05:33:09:003472 gpinitsystem:gpmaster:ubuntu-[INFO]:-gpsegment0 	6000 	gpsegment0 	/data0/primary/gpseg0 	2
20210902:05:33:09:003472 gpinitsystem:gpmaster:ubuntu-[INFO]:-gpsegment0 	6001 	gpsegment0 	/data0/primary/gpseg1 	3
20210902:05:33:09:003472 gpinitsystem:gpmaster:ubuntu-[INFO]:-gpsegment0 	6002 	gpsegment0 	/data0/primary/gpseg2 	4
20210902:05:33:09:003472 gpinitsystem:gpmaster:ubuntu-[INFO]:-gpsegment0 	6003 	gpsegment0 	/data1/primary/gpseg3 	5
20210902:05:33:09:003472 gpinitsystem:gpmaster:ubuntu-[INFO]:-gpsegment0 	6004 	gpsegment0 	/data1/primary/gpseg4 	6
20210902:05:33:09:003472 gpinitsystem:gpmaster:ubuntu-[INFO]:-gpsegment0 	6005 	gpsegment0 	/data1/primary/gpseg5 	7
20210902:05:33:09:003472 gpinitsystem:gpmaster:ubuntu-[INFO]:-gpsegment1 	6000 	gpsegment1 	/data0/primary/gpseg6 	8
20210902:05:33:09:003472 gpinitsystem:gpmaster:ubuntu-[INFO]:-gpsegment1 	6001 	gpsegment1 	/data0/primary/gpseg7 	9
20210902:05:33:09:003472 gpinitsystem:gpmaster:ubuntu-[INFO]:-gpsegment1 	6002 	gpsegment1 	/data0/primary/gpseg8 	10
20210902:05:33:09:003472 gpinitsystem:gpmaster:ubuntu-[INFO]:-gpsegment1 	6003 	gpsegment1 	/data1/primary/gpseg9 	11
20210902:05:33:09:003472 gpinitsystem:gpmaster:ubuntu-[INFO]:-gpsegment1 	6004 	gpsegment1 	/data1/primary/gpseg10 	12
20210902:05:33:09:003472 gpinitsystem:gpmaster:ubuntu-[INFO]:-gpsegment1 	6005 	gpsegment1 	/data1/primary/gpseg11 	13

Continue with Greenplum creation Yy|Nn (default=N):
> y
20210902:05:33:21:003472 gpinitsystem:gpmaster:ubuntu-[INFO]:-Building the Master instance database, please wait...
20210902:05:33:26:003472 gpinitsystem:gpmaster:ubuntu-[INFO]:-Starting the Master in admin mode
20210902:05:33:28:003472 gpinitsystem:gpmaster:ubuntu-[INFO]:-Commencing parallel build of primary segment instances
20210902:05:33:28:003472 gpinitsystem:gpmaster:ubuntu-[INFO]:-Spawning parallel processes    batch [1], please wait...
............
20210902:05:33:29:003472 gpinitsystem:gpmaster:ubuntu-[INFO]:-Waiting for parallel processes batch [1], please wait...
.....................................................
20210902:05:34:22:003472 gpinitsystem:gpmaster:ubuntu-[INFO]:------------------------------------------------
20210902:05:34:22:003472 gpinitsystem:gpmaster:ubuntu-[INFO]:-Parallel process exit status
20210902:05:34:22:003472 gpinitsystem:gpmaster:ubuntu-[INFO]:------------------------------------------------
20210902:05:34:22:003472 gpinitsystem:gpmaster:ubuntu-[INFO]:-Total processes marked as completed           = 5
20210902:05:34:22:003472 gpinitsystem:gpmaster:ubuntu-[INFO]:-Total processes marked as killed              = 0
20210902:05:34:22:003472 gpinitsystem:gpmaster:ubuntu-[WARN]:-Total processes marked as failed              = 7 <<<<<
20210902:05:34:22:003472 gpinitsystem:gpmaster:ubuntu-[INFO]:------------------------------------------------
20210902:05:34:22:003472 gpinitsystem:gpmaster:ubuntu-[FATAL]:-Errors generated from parallel processes
20210902:05:34:22:003472 gpinitsystem:gpmaster:ubuntu-[INFO]:-Dumped contents of status file to the log file
20210902:05:34:22:003472 gpinitsystem:gpmaster:ubuntu-[INFO]:-Building composite backout file
20210902:05:34:22:003472 gpinitsystem:gpmaster:ubuntu-[FATAL]:-Failures detected, see log file /home/ubuntu/gpAdminLogs/gpinitsystem_20210902.log for more detail Script Exiting!
20210902:05:34:22:003472 gpinitsystem:gpmaster:ubuntu-[WARN]:-Script has left Greenplum Database in an incomplete state
20210902:05:34:22:003472 gpinitsystem:gpmaster:ubuntu-[WARN]:-Run command bash /home/ubuntu/gpAdminLogs/backout_gpinitsystem_ubuntu_20210902_053210 to remove these changes
20210902:05:34:22:003472 gpinitsystem:gpmaster:ubuntu-[INFO]:-Start Function BACKOUT_COMMAND
20210902:05:34:22:003472 gpinitsystem:gpmaster:ubuntu-[INFO]:-End Function BACKOUT_COMMAND
ubuntu@gpmaster:/usr/local/greenplum-db$ 

### Step to reproduce the behavior

What should I do to avoid the fatal error?

Thanks.

**Comment by mishima340** [comment]
Hi,

I read the log file and found the following error message:

creating directory /data1/primary/gpseg11 ... ok
creating subdirectories ... ok
selecting default max_connections ... initdb: error 35072 from: "/usr/local/greenplum-db-6.17.1/bin/postgres" --boot -x0 -F -c max_connections=750 -c shared_buffers=4000 -c dynamic_shared_memory_type=none < "/dev/null" > "/data0/primary/gpseg7.initdb" 2>&1
initdb: removing data directory "/data0/primary/gpseg7"
initdb: error 35072 from: "/usr/local/greenplum-db-6.17.1/bin/postgres" --boot -x0 -F -c max_connections=750 -c shared_buffers=4000 -c dynamic_shared_memory_type=none < "/dev/null" > "/data0/primary/gpseg2.initdb" 2>&1
initdb: removing data directory "/data0/primary/gpseg2"
initdb: error 35072 from: "/usr/local/greenplum-db-6.17.1/bin/postgres" --boot -x0 -F -c max_connections=750 -c shared_buffers=4000 -c dynamic_shared_memory_type=none < "/dev/null" > "/data0/primary/gpseg1.initdb" 2>&1
initdb: removing data directory "/data0/primary/gpseg1"
initdb: error 35072 from: "/usr/local/greenplum-db-6.17.1/bin/postgres" --boot -x0 -F -c max_connections=750 -c shared_buffers=4000 -c dynamic_shared_memory_type=none < "/dev/null" > "/data0/primary/gpseg6.initdb" 2>&1
initdb: removing data directory "/data0/primary/gpseg6"
750
selecting default shared_buffers ... 125MB

What should I do?

Thanks.

**Comment by adam8157** [comment]
You need to adjust your sysctl and limits configurations, check out the mentioned PR.

**Comment by mishima340** [comment]
Thank you for your comment.
I adjusted limit.conf and solved this error.
Thank you.
Unfortunately, I encountered another error.
Please see #12544 "gpstart error" and answer some comments.
Thank you for your help.
