### ISSUE TITLE
gpstart failed

### ISSUE THREAD

**Issue by mishima340** [greenplum-db/gpdb#12554]
### Greenplum version or build
6.17.3
### OS version and uname -a
ubuntu 18.04
### Actual behavior

I started gpdb using gpinitsysm and it outputs the following error message.

20210908:04:53:00:012414 gpstart:gpmaster1:gpadmin-[INFO]:-Process results...
20210908:04:53:00:012414 gpstart:gpmaster1:gpadmin-[CRITICAL]:-gpstart failed. (Reason='') exiting...
20210908:04:53:00:006796 gpinitsystem:gpmaster1:gpadmin-[WARN]:
20210908:04:53:00:006796 gpinitsystem:gpmaster1:gpadmin-[WARN]:-Failed to start Greenplum instance; review gpstart output to
20210908:04:53:00:006796 gpinitsystem:gpmaster1:gpadmin-[WARN]:- determine why gpstart failed and reinitialize cluster after resolving
20210908:04:53:00:006796 gpinitsystem:gpmaster1:gpadmin-[WARN]:- issues.  Not all initialization tasks have completed so the cluster
20210908:04:53:00:006796 gpinitsystem:gpmaster1:gpadmin-[WARN]:- should not be used.
20210908:04:53:00:006796 gpinitsystem:gpmaster1:gpadmin-[WARN]:-gpinitsystem will now try to stop the cluster
20210908:04:53:00:006796 gpinitsystem:gpmaster1:gpadmin-[WARN]:
20210908:04:53:00:012504 gpstop:gpmaster1:gpadmin-[INFO]:-Starting gpstop with args: -a -l /home/gpadmin/gpAdminLogs -i -d /data/master/gpseg-1
20210908:04:53:00:012504 gpstop:gpmaster1:gpadmin-[INFO]:-Gathering information and validating the environment...
20210908:04:53:00:012504 gpstop:gpmaster1:gpadmin-[ERROR]:-gpstop error: postmaster.pid file does not exist.  is Greenplum instance already stopped?
20210908:04:53:00:006796 gpinitsystem:gpmaster1:gpadmin-[WARN]:-Failed to stop new Greenplum instance Script Exiting!
gpadmin@gpmaster1:/usr/local/greenplum-db$ 

"Reason" is not shown, I don't know how to fix the error.

The "startup.log" is as follows:

2021-09-08 04:52:22.267913 UTC,,,p8777,th686681024,,,,0,,,seg-1,,,,,"LOG","00000","registering background worker ""sweeper process""",,,,,,,,"RegisterBackgroundWorker","bgworker.c",774,
2021-09-08 04:52:22.373770 UTC,,,p8777,th686681024,,,,0,,,seg-1,,,,,"LOG","00000","redirecting log output to logging collector process",,"Future log output will appear in directory ""pg_log"".",,,,,,"SysLogger_Start","syslogger.c",989,
2021-09-08 04:52:58.518267 UTC,,,p12425,th-1248556096,,,,0,,,seg-1,,,,,"LOG","00000","registering background worker ""sweeper process""",,,,,,,,"RegisterBackgroundWorker","bgworker.c",774,
2021-09-08 04:52:58.626699 UTC,,,p12425,th-1248556096,,,,0,,,seg-1,,,,,"LOG","00000","redirecting log output to logging collector process",,"Future log output will appear in directory ""pg_log"".",,,,,,"SysLogger_Start","syslogger.c",989,

The last message of the "gpdb-2021-09-08_045258.csv" is as follows:

2021-09-08 04:52:59.300158 UTC,"gpadmin","template1",p12457,th-1248556096,"127.0.0.1","54386",2021-09-08 04:52:59 UTC,0,,cmd13,seg-1,,,,sx1,"LOG","00000","statement: SELECT typname, typlen FROM pg_type WHERE oid=21",,,,,,"SELECT typname, typlen FROM pg_type WHERE oid=21",0,,"postgres.c",1650,
2021-09-08 04:52:59.300324 UTC,"gpadmin","template1",p12457,th-1248556096,"127.0.0.1","54386",2021-09-08 04:52:59 UTC,0,,cmd15,seg-1,,,,sx1,"LOG","00000","statement: SELECT typname, typlen FROM pg_type WHERE oid=18",,,,,,"SELECT typname, typlen FROM pg_type WHERE oid=18",0,,"postgres.c",1650,
2021-09-08 04:52:59.300470 UTC,"gpadmin","template1",p12457,th-1248556096,"127.0.0.1","54386",2021-09-08 04:52:59 UTC,0,,cmd17,seg-1,,,,sx1,"LOG","00000","statement: SELECT typname, typlen FROM pg_type WHERE oid=23",,,,,,"SELECT typname, typlen FROM pg_type WHERE oid=23",0,,"postgres.c",1650,
2021-09-08 04:52:59.316914 UTC,,,p12425,th-1248556096,,,,0,,,seg-1,,,,,"LOG","00000","received fast shutdown request",,,,,,,0,,"postmaster.c",3073,
2021-09-08 04:52:59.316942 UTC,,,p12425,th-1248556096,,,,0,,,seg-1,,,,,"LOG","00000","aborting any active transactions",,,,,,,0,,"postmaster.c",3099,
2021-09-08 04:52:59.317014 UTC,,,p12433,th-1248556096,,,,0,,,seg-1,,,,,"FATAL","57P01","terminating background worker ""sweeper process"" due to administrator command",,,,,,,0,,"bgworker.c",565,
2021-09-08 04:52:59.318276 UTC,,,p12425,th-1248556096,,,,0,,,seg-1,,,,,"LOG","00000","worker process: sweeper process (PID 12433) exited with exit code 1",,,,,,,0,,"postmaster.c",3948,
2021-09-08 04:52:59.318425 UTC,,,p12429,th-1248556096,,,,0,,,seg-1,,,,,"LOG","00000","shutting down",,,,,,,0,,"xlog.c",8434,
2021-09-08 04:52:59.329161 UTC,,,p12429,th-1248556096,,,,0,,,seg-1,,,,,"LOG","00000","database system is shut down",,,,,,,0,,"xlog.c",8469,

How can I fix the error?
Thank you for your any help.

**Comment by adam8157** [comment]
Check out the gpstart logs in `~/gpAdminLogs` and try `gpstart -v`

**Comment by mishima340** [comment]
Thank you for your comment.
I tried gpstart -v and the following error occurred.
Please tell me the detail of "No module named site".
What is the "site"?
I executed "apt-cache search site" but many many items were listed; so I could not find the "site" module.
Thank you for your help.

--------------------------------------------------

  stderr='sh: 1: /usr/local/greenplum-db-6.17.3/greenplum_path.sh: Bad substitution
ImportError: No module named site
'
20210908:06:43:05:014731 gpstart:gpmaster1:gpadmin-[DEBUG]:-[worker2] finished cmd: remote segment starts on host 'gpsegment0' cmdStr='ssh -o StrictHostKeyChecking=no -o ServerAliveInterval=60 gpsegment0 ". /usr/local/greenplum-db-6.17.3/greenplum_path.sh; $GPHOME/sbin/gpsegstart.py -M mirrorless -V 'postgres (Greenplum Database) 6.17.3 build commit:d2912fee614b350ea5781581b23a6697150935cc Open Source' -n 12 --era a3d8d954ed1d4b7a_210908064301 -t 600 --master-checksum-version 1 -v -D '2|0|p|p|n|u|gpsegment0|gpsegment0|6000|/data0/primary/gpseg0' -D '3|1|p|p|n|u|gpsegment0|gpsegment0|6001|/data0/primary/gpseg1' -D '4|2|p|p|n|u|gpsegment0|gpsegment0|6002|/data0/primary/gpseg2' -D '5|3|p|p|n|u|gpsegment0|gpsegment0|6003|/data1/primary/gpseg3' -D '6|4|p|p|n|u|gpsegment0|gpsegment0|6004|/data1/primary/gpseg4' -D '7|5|p|p|n|u|gpsegment0|gpsegment0|6005|/data1/primary/gpseg5' -b 64"'  had result: cmd had rc=1 completed=True halted=False
  stdout=''
  stderr='sh: 1: /usr/local/greenplum-db-6.17.3/greenplum_path.sh: Bad substitution
ImportError: No module named site
'
20210908:06:43:05:014731 gpstart:gpmaster1:gpadmin-[INFO]:-Process results...
20210908:06:43:05:014731 gpstart:gpmaster1:gpadmin-[ERROR]:-gpstart failed.  exiting...
Traceback (most recent call last):
  File "/usr/local/greenplum-db-6.17.3/lib/python/gppylib/mainUtils.py", line 342, in simple_main_locked
    exitCode = commandObject.run()
  File "/usr/local/greenplum-db-6.17.3/bin/gpstart", line 157, in run
    success = self._start(segmentsToStart, invalidSegments)
  File "/usr/local/greenplum-db-6.17.3/bin/gpstart", line 453, in _start
    segmentStartResult = segmentStartOp.startSegments(self.gparray, segmentsToStart, startMode, self.era)
  File "/usr/local/greenplum-db-6.17.3/lib/python/gppylib/operations/startSegments.py", line 150, in startSegments
    assert totalToAttempt == len(result.getFailedSegmentObjs()) + len(result.getSuccessfulSegments())
AssertionError
20210908:06:43:05:014731 gpstart:gpmaster1:gpadmin-[DEBUG]:-WorkerPool haltWork()
20210908:06:43:05:014731 gpstart:gpmaster1:gpadmin-[DEBUG]:-[worker0] haltWork
20210908:06:43:05:014731 gpstart:gpmaster1:gpadmin-[DEBUG]:-[worker1] haltWork
20210908:06:43:05:014731 gpstart:gpmaster1:gpadmin-[DEBUG]:-[worker4] got a halt cmd
20210908:06:43:05:014731 gpstart:gpmaster1:gpadmin-[DEBUG]:-[worker5] got a halt cmd
20210908:06:43:05:014731 gpstart:gpmaster1:gpadmin-[DEBUG]:-[worker2] haltWork
20210908:06:43:05:014731 gpstart:gpmaster1:gpadmin-[DEBUG]:-[worker3] haltWork
20210908:06:43:05:014731 gpstart:gpmaster1:gpadmin-[DEBUG]:-[worker6] got a halt cmd
20210908:06:43:05:014731 gpstart:gpmaster1:gpadmin-[DEBUG]:-[worker7] got a halt cmd
20210908:06:43:05:014731 gpstart:gpmaster1:gpadmin-[DEBUG]:-[worker4] haltWork
20210908:06:43:05:014731 gpstart:gpmaster1:gpadmin-[DEBUG]:-[worker5] haltWork
20210908:06:43:05:014731 gpstart:gpmaster1:gpadmin-[DEBUG]:-[worker8] got a halt cmd
20210908:06:43:05:014731 gpstart:gpmaster1:gpadmin-[DEBUG]:-[worker9] got a halt cmd
20210908:06:43:05:014731 gpstart:gpmaster1:gpadmin-[DEBUG]:-[worker6] haltWork
20210908:06:43:05:014731 gpstart:gpmaster1:gpadmin-[DEBUG]:-[worker7] haltWork
20210908:06:43:05:014731 gpstart:gpmaster1:gpadmin-[DEBUG]:-[worker10] got a halt cmd
20210908:06:43:05:014731 gpstart:gpmaster1:gpadmin-[DEBUG]:-[worker8] haltWork
20210908:06:43:05:014731 gpstart:gpmaster1:gpadmin-[DEBUG]:-[worker11] got a halt cmd
20210908:06:43:05:014731 gpstart:gpmaster1:gpadmin-[DEBUG]:-[worker9] haltWork
20210908:06:43:05:014731 gpstart:gpmaster1:gpadmin-[DEBUG]:-[worker12] got a halt cmd
20210908:06:43:05:014731 gpstart:gpmaster1:gpadmin-[DEBUG]:-[worker10] haltWork
20210908:06:43:05:014731 gpstart:gpmaster1:gpadmin-[DEBUG]:-[worker0] got a halt cmd
20210908:06:43:05:014731 gpstart:gpmaster1:gpadmin-[DEBUG]:-[worker1] got a halt cmd
20210908:06:43:05:014731 gpstart:gpmaster1:gpadmin-[DEBUG]:-[worker11] haltWork
20210908:06:43:05:014731 gpstart:gpmaster1:gpadmin-[DEBUG]:-[worker12] haltWork
20210908:06:43:05:014731 gpstart:gpmaster1:gpadmin-[DEBUG]:-[worker3] got a halt cmd
20210908:06:43:05:014731 gpstart:gpmaster1:gpadmin-[DEBUG]:-[worker2] got a halt cmd
gpadmin@gpmaster1:/usr/local/greenplum-db$

**Comment by JunfengYang** [comment]
It's a python module, you should use pip to install it.

**Comment by mishima340** [comment]
Thank you for your quick response.
I executed as follows:
---------------------------------------------
# ubuntu@gpmaster1:~$ pip install site
Collecting site
  Could not find a version that satisfies the requirement site (from versions: )
No matching distribution found for site
ubuntu@gpmaster1:~$ 
---------------------------------------------
and then
---------------------------------------------
ubuntu@gpmaster1:~$ pip install site -vvv
Collecting site
  1 location(s) to search for versions of site:
  * https://pypi.python.org/simple/site/
  Getting page https://pypi.python.org/simple/site/
  Looking up "https://pypi.python.org/simple/site/" in the cache
  Returning cached "301 Moved Permanently" response (ignoring date and etag information)
  Looking up "https://pypi.org/simple/site/" in the cache
  No cache entry available
  Starting new HTTPS connection (1): pypi.org
  https://pypi.org:443 "GET /simple/site/ HTTP/1.1" 404 13
  Status code 404 not in [200, 203, 300, 301]
  Could not fetch URL https://pypi.python.org/simple/site/: 404 Client Error: Not Found for url: https://pypi.org/simple/site/ - skipping
  Could not find a version that satisfies the requirement site (from versions: )
Cleaning up...
No matching distribution found for site
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 353, in run
    wb.build(autobuilding=True)
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 554, in _prepare_file
    require_hashes
  File "/usr/lib/python2.7/dist-packages/pip/req/req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 514, in find_requirement
    'No matching distribution found for %s' % req
DistributionNotFound: No matching distribution found for site
ubuntu@gpmaster1:~$ 

---------------------------------------------------
I searched some web pages about the package of "site" but I could not solve this problem.
I am very sorry that I want you to solve this problem.
Thank you for your help.

**Comment by SmartKeyerror** [comment]
https://stackoverflow.com/questions/21874407/python-ipython-importerror-no-module-named-site/21874450, maybe it can help you.

**Comment by mishima340** [comment]
Thank you for your information. But I could not the problem.
I did as follows:

ubuntu@gpmaster1:~$ unset PYTHONHOME
ubuntu@gpmaster1:~$ unset PYTHONPATH
ubuntu@gpmaster1:~$ pip install site

and 

ubuntu@gpmaster1:~$ export PYTHONHOME=/usr/lib/python
python2.7/ python3/   python3.6/ python3.7/ python3.8/ 
ubuntu@gpmaster1:~$ export PYTHONHOME=/usr/lib/python
python2.7/ python3/   python3.6/ python3.7/ python3.8/ 
ubuntu@gpmaster1:~$ export PYTHONHOME=/usr/lib/python2.7
ubuntu@gpmaster1:~$ pip install site
ImportError: No module named site
ubuntu@gpmaster1:~$ export PYTHONHOME=/usr/lib/python3
ubuntu@gpmaster1:~$ pip install site
ImportError: No module named site
ubuntu@gpmaster1:~$ export PYTHONHOME=/usr/lib/python3.6
ubuntu@gpmaster1:~$ pip install site
ImportError: No module named site
ubuntu@gpmaster1:~$ export PYTHONHOME=/usr/lib/python3.7
ubuntu@gpmaster1:~$ export PYTHONHOME=/usr/lib/python3.8
ubuntu@gpmaster1:~$ pip install sit
ImportError: No module named site
ubuntu@gpmaster1:~$ pip install site
ImportError: No module named site
ubuntu@gpmaster1:~$ sudo apt-get install python-matplotlib


Please give me additional information.
Thank you for any help.

**Comment by SmartKeyerror** [comment]
Module `site` is automatically imported during initialization, so you can't use pip to install it. And do you append module search paths for third-party packages to sys.path ?

**Comment by mishima340** [comment]
I executed only 
% source greenplum_path.sh
So, my search path is
PYTHONHOME=/usr/local/greenplum-db-6.17.3/ext/python
PYTHONPATH=/usr/local/greenplum-db-6.17.3/lib/python

I found site.pyc

gpadmin@gpmaster1:/usr/local/greenplum-db$ ls /usr/local/greenplum-db-6.17.3/ext/python/lib/python2.7/site*
/usr/local/greenplum-db-6.17.3/ext/python/lib/python2.7/site.py  /usr/local/greenplum-db-6.17.3/ext/python/lib/python2.7/site.pyc

/usr/local/greenplum-db-6.17.3/ext/python/lib/python2.7/site-packages:
README

so, I modified as follows:

PYTHONPATH=/usr/local/greenplum-db-6.17.3/lib/python:/usr/local/greenplum-db-6.17.3/ext/python

but failed.

Please give me more advice.
Thanks.

**Comment by JunfengYang** [comment]
If you have multiple python versions, please make sure the pip matching the current python version you are using.
You can check with `which` and be careful of the symbolic link.
Then you should also make sure the python you are using through `ssh` is the correct one by `ssh host 'which python'`.

**Comment by mishima340** [comment]
Is this incorrect?

gpadmin@gpmaster1:/usr/local/greenplum-db-6.17.3$ ssh gpsegment0 'which python'
/usr/bin/python
gpadmin@gpmaster1:/usr/local/greenplum-db-6.17.3$

**Comment by mishima340** [comment]
In my environment, I have one master called "gpmaster1" and two segments called "gpsegment0" and "gpsegment1" on AWS.

**Comment by mishima340** [comment]
I was trying to fix the environment of gpmaster1 but this error message says

20210909:12:33:41:012012 gpstart:gpmaster1:gpadmin-[DEBUG]:-[worker2] finished cmd: remote segment starts on host 'gpsegment0' cmdStr='ssh -o StrictHostKeyChecking=no -o ServerAliveInterval=60 gpsegment0 ". /usr/local/greenplum-db-6.17.3/greenplum_path.sh; $GPHOME/sbin/gpsegstart.py -M mirrorless -V 'postgres (Greenplum Database) 6.17.3 build commit:d2912fee614b350ea5781581b23a6697150935cc Open Source' -n 12 --era a3d8d954ed1d4b7a_210909123336 -t 600 --master-checksum-version 1 -v -D '2|0|p|p|n|u|gpsegment0|gpsegment0|6000|/data0/primary/gpseg0' -D '3|1|p|p|n|u|gpsegment0|gpsegment0|6001|/data0/primary/gpseg1' -D '4|2|p|p|n|u|gpsegment0|gpsegment0|6002|/data0/primary/gpseg2' -D '5|3|p|p|n|u|gpsegment0|gpsegment0|6003|/data1/primary/gpseg3' -D '6|4|p|p|n|u|gpsegment0|gpsegment0|6004|/data1/primary/gpseg4' -D '7|5|p|p|n|u|gpsegment0|gpsegment0|6005|/data1/primary/gpseg5' -b 64"'  had result: cmd had rc=1 completed=True halted=False
  stdout=''
  stderr='sh: 1: /usr/local/greenplum-db-6.17.3/greenplum_path.sh: Bad substitution
ImportError: No module named site

segment server called gpsegment0 encounters an error of the module 'site'.

Please give me additional information to fix this error.

Thanks

**Comment by mishima340** [comment]
I changed gpsegment0's greenplum_path.sh as follows:

#PYTHONHOME="${GPHOME}/ext/python"                                                                                                                    
#PYTHONPATH="${GPHOME}/lib/python" 

Therefore, I did not encounter the 'site' error.
Instead, I encountered the following ImportError.

20210909:14:16:54:002074 gpstart:gpmaster1:gpadmin-[DEBUG]:-[worker3] finished cmd: remote segment starts on host 'gpsegment1' cmdStr='ssh -o StrictHostKeyChecking=no -o ServerAliveInterval=60 gpsegment1 ". /usr/local/greenplum-db-6.17.3/greenplum_path.sh; $GPHOME/sbin/gpsegstart.py -M mirrorless -V 'postgres (Greenplum Database) 6.17.3 build commit:d2912fee614b350ea5781581b23a6697150935cc Open Source' -n 12 --era a3d8d954ed1d4b7a_210909141651 -t 600 --master-checksum-version 1 -v -D '8|6|p|p|n|u|gpsegment1|gpsegment1|6000|/data0/primary/gpseg6' -D '9|7|p|p|n|u|gpsegment1|gpsegment1|6001|/data0/primary/gpseg7' -D '10|8|p|p|n|u|gpsegment1|gpsegment1|6002|/data0/primary/gpseg8' -D '11|9|p|p|n|u|gpsegment1|gpsegment1|6003|/data1/primary/gpseg9' -D '12|10|p|p|n|u|gpsegment1|gpsegment1|6004|/data1/primary/gpseg10' -D '13|11|p|p|n|u|gpsegment1|gpsegment1|6005|/data1/primary/gpseg11' -b 64"'  had result: cmd had rc=1 completed=True halted=False
  stdout=''
  stderr='sh: 1: /usr/local/greenplum-db-6.17.3/greenplum_path.sh: Bad substitution
Traceback (most recent call last):
  File "/usr/local/greenplum-db-6.17.3/sbin/gpsegstart.py", line 13, in <module>
    from gppylib.mainUtils import simple_main, addStandardLoggingAndHelpOptions
ImportError: No module named gppylib.mainUtils

So, I think I have to change  #PYTHONHOME or #PYTHONPATH.
Do you have any idea to fix this?
Thank you for your any advice.
Thanks.

**Comment by SmartKeyerror** [comment]
That's really weird, can you give me the result of `which python`、`which python3`、`ssh host which python` and `ssh host which python3` ?

**Comment by mishima340** [comment]
Thank you  for your response. gpmaster1 is the host name of the master, and gpsegment0 is the host name of the segment.

gpadmin@gpmaster1:~$ which python
/usr/bin/python
gpadmin@gpmaster1:~$ source /usr/local/greenplum-db-6.17.3/greenplum_path.sh 
gpadmin@gpmaster1:~$ which python
/usr/local/greenplum-db-6.17.3/ext/python/bin/python
gpadmin@gpmaster1:~$ which python3
/usr/bin/python3
gpadmin@gpmaster1:~$ 

gpadmin@gpmaster1:~$ ssh gpsegment0 which python
/usr/bin/python
gpadmin@gpmaster1:~$ ssh gpsegment0 which python3
/usr/bin/python3
gpadmin@gpmaster1:~$ 

I am wondering that if I execute "ssh gpsegment0 which python", 
the path must output "/usr/local/greenplum-db-6.17.3/ext/python/bin/python" ?
I am very sorry how to change the path.

Please let me know how to solve this problem.
Thank you for your any help.

**Comment by SmartKeyerror** [comment]
Did you add `GPHOME` to PYTHONPATH?

**Comment by mishima340** [comment]
Please see below.
Of course, the greenplum_path.sh of the segment has GPHOME as follows.
But when I execute "which python" by the segment, the path is not GreenPlum's python; is this a problem?
How can I solve it?

gpadmin@gpmaster1:/usr/local/greenplum-db-6.17.3$ ssh gpsegment0 'cat /usr/local/greenplum-db-6.17.3/greenplum_path.sh'
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
if [ ! -L "${SCRIPT_DIR}" ]; then
	GPDB_DIR=$(basename "${SCRIPT_DIR}")
else
	GPDB_DIR=$(basename "$(readlink "${SCRIPT_DIR}")")
fi
GPHOME=$(dirname "${SCRIPT_DIR}")/"${GPDB_DIR}"
#PYTHONHOME="${GPHOME}/ext/python"
export PYTHONHOME

PATH="${PYTHONHOME}/bin:${PATH}"
LD_LIBRARY_PATH="${PYTHONHOME}/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
#PYTHONPATH="${GPHOME}/lib/python"
PATH="${GPHOME}/bin:${PATH}"
LD_LIBRARY_PATH="${GPHOME}/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"

if [ -e "${GPHOME}/etc/openssl.cnf" ]; then
	OPENSSL_CONF="${GPHOME}/etc/openssl.cnf"
fi

export GPHOME
export PATH
export PYTHONPATH
export LD_LIBRARY_PATH
export OPENSSL_CONF
gpadmin@gpmaster1:/usr/local/greenplum-db-6.17.3$ ssh gpsegment0 'which python'
/usr/bin/python
gpadmin@gpmaster1:/usr/local/greenplum-db-6.17.3$ 


Thanks for your advice.

**Comment by higuoxing** [comment]
> Please see below.
> Of course, the greenplum_path.sh of the segment has GPHOME as follows.
> But when I execute "which python" by the segment, the path is not GreenPlum's python; is this a problem?
> How can I solve it?
> 
> ```
> gpadmin@gpmaster1:/usr/local/greenplum-db-6.17.3$ ssh gpsegment0 'cat /usr/local/greenplum-db-6.17.3/greenplum_path.sh'
> SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
> if [ ! -L "${SCRIPT_DIR}" ]; then
> GPDB_DIR=$(basename "${SCRIPT_DIR}")
> else
> GPDB_DIR=$(basename "$(readlink "${SCRIPT_DIR}")")
> fi
> GPHOME=$(dirname "${SCRIPT_DIR}")/"${GPDB_DIR}"
> #PYTHONHOME="${GPHOME}/ext/python"
> ^^^^^^^^^^^^^
> export PYTHONHOME
> 
> PATH="${PYTHONHOME}/bin:${PATH}"
> LD_LIBRARY_PATH="${PYTHONHOME}/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
> #PYTHONPATH="${GPHOME}/lib/python"
> ^^^^^^^^^^^^^ 
> PATH="${GPHOME}/bin:${PATH}"
> LD_LIBRARY_PATH="${GPHOME}/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
> 
> if [ -e "${GPHOME}/etc/openssl.cnf" ]; then
> OPENSSL_CONF="${GPHOME}/etc/openssl.cnf"
> fi
> 
> export GPHOME
> export PATH
> export PYTHONPATH
> export LD_LIBRARY_PATH
> export OPENSSL_CONF
> gpadmin@gpmaster1:/usr/local/greenplum-db-6.17.3$ ssh gpsegment0 'which python'
> /usr/bin/python
> gpadmin@gpmaster1:/usr/local/greenplum-db-6.17.3$
> ```
> Thanks for your advice.

It looks that the environment variable `PYTHONHOME` and `PYTHONPATH` is commented out? That's why your Python interpreter cannot find libraries.

**Comment by mishima340** [comment]
Thank you for your advice.
I fixed the path and confirmed my Greenplum had started successfully.
Thanks all !
