### ISSUE TITLE
GP Client Tools

### ISSUE THREAD

**Issue by VinnyPem** [greenplum-db/gpdb#1255]
Hello,

I've installed Greenplum from the GPDB Software available from Pivotal directly previously, with a Master server and an ETL server to catch files for loading. On the ETL server we had just the GP Client Tools package installed to allow the use of GPFDIST, PSQL, etc.

I've now installed a server using GitHub GPDB open source software successfully, but in trying to create a test ETL server, I don't seem to see any Client Tools as such? Have I missed something or is there currently no way to do this specifically via GitHub's open source?

I temporarily cheated by simply installing the GPDB software onto the ETL, which of course comes with the commands we require, but it also comes with stuff we would rather not have on there as well.

Thank you in advance for any help.

Regards,
Vinny.

**Comment by ivannovick** [comment]
Hi Vinny I think you are right their is no custom packaging for stripping out the server components.  As an easy step, you can just remove the postgres binary which will make the install only good for non-server use cases.  There are a few efforts to provide packaging for open source Greenplum and it would most likely by up to those packaging efforts to select the right output from the build for a client install.
