### ISSUE TITLE
Serial and bigserial type columns work extremely slowly when inserting millions of rows on many segments cluster

### ISSUE THREAD

**Issue by sokolval** [greenplum-db/gpdb#12583]
### Greenplum version or build
PostgreSQL 9.4.24 (Greenplum Database 6.17.3 build dev) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609, 64-bit compiled on Sep  8 2021 17:27:53
### OS version and uname -a
Linux hostname 4.19.62-13 #1 SMP Mon Jul 29 17:22:59 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
### autoconf options used ( config.status --config )
./config.status --config
'--with-perl' '--with-python' '--without-gssapi' '--enable-gpcloud' '--with-libxml' '--with-system-tzdata=/usr/share/zoneinfo' '--prefix=/usr/local/gpdb'
### Installation information ( pg_config )
BINDIR = /usr/local/gpdb/bin
DOCDIR = /usr/local/gpdb/share/doc/postgresql
HTMLDIR = /usr/local/gpdb/share/doc/postgresql
INCLUDEDIR = /usr/local/gpdb/include
PKGINCLUDEDIR = /usr/local/gpdb/include/postgresql
INCLUDEDIR-SERVER = /usr/local/gpdb/include/postgresql/server
LIBDIR = /usr/local/gpdb/lib/x86_64-linux-gnu
PKGLIBDIR = /usr/local/gpdb/lib/x86_64-linux-gnu/postgresql
LOCALEDIR = /usr/local/gpdb/share/locale
MANDIR = /usr/local/gpdb/share/man
SHAREDIR = /usr/local/gpdb/share/postgresql
SYSCONFDIR = /etc/postgresql
PGXS = /usr/local/gpdb/lib/x86_64-linux-gnu/postgresql/pgxs/src/makefiles/pgxs.mk
CONFIGURE = '--build=x86_64-linux-gnu' '--prefix=/usr' '--includedir=/usr/local/gpdb/include' '--mandir=/usr/local/gpdb/share/man' '--infodir=/usr/local/gpdb/share/info' '--sysconfdir=/etc' '--localstatedir=/var' '--disable-silent-rules' '--libdir=/usr/local/gpdb/lib/x86_64-linux-gnu' '--libexecdir=/usr/local/gpdb/lib/x86_64-linux-gnu' '--disable-maintainer-mode' '--disable-dependency-tracking' '--with-perl' '--with-python' '--without-gssapi' '--disable-gpcloud' '--with-libxml' '--with-system-tzdata=/usr/share/zoneinfo' '--prefix=/usr/local/gpdb' '--enable-ic-proxy' 'build_alias=x86_64-linux-gnu' 'CFLAGS=-g -O2 -fstack-protector-strong -Wformat -Werror=format-security' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'CXXFLAGS=-g -O2 -fstack-protector-strong -Wformat -Werror=format-security'
CC = gcc
CPPFLAGS = -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2 -I/usr/local/gpdb/include
CFLAGS = -Wall -Wmissing-prototypes -Wpointer-arith -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fno-aggressive-loop-optimizations -Wno-unused-but-set-variable -Wno-address -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -std=gnu99 -Werror=uninitialized -Werror=implicit-function-declaration -I/usr/local/gpdb/include
CFLAGS_SL = -fPIC
LDFLAGS = -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,--as-needed -Wl,-rpath,'/usr/local/gpdb/lib/x86_64-linux-gnu',--enable-new-dtags -L/usr/local/gpdb/lib/x86_64-linux-gnu
LDFLAGS_EX = 
LDFLAGS_SL = 
LIBS = -lpgcommon -lpgport -lxerces-c -lxml2 -lrt -luv -lzstd -lrt -lcrypt -ldl -lm -L/usr/local/gpdb/lib/x86_64-linux-gnu
VERSION = PostgreSQL 9.4.24

### Expected behavior
Fast  inserts into table with serial/bigserial field

### Actual behavior
Slow working on amounts 100000+ rows in 1 transaction and many segments (64/128)

### Step to reproduce the behavior
```
CREATE TABLE test_bigserial
(
    id      BIGSERIAL,
    n_id INT
)
DISTRIBUTED BY (id);

INSERT INTO test_bigserial (n_id)
SELECT generate_series(1, 1000000);
```
Above insert query would work extremely slow  (>72 hours) on cluster with 128 nodes. It can not be killed afterwards, only cluster restart helps to stop such session. On cluster with 64 nodes ETA is around 12 hours.

This was never observed on 6.12.1 - just we started seeing it on 6.17.1

**Comment by sokolval** [comment]
~$ time psql -d db -c "INSERT INTO test_bigserial (n_id)
> SELECT generate_series(1, 10000);"
INSERT 0 **10000**

real    **0m0.912s**
user    0m0.000s
sys     0m0.002s
---------------------
~$ time psql -d db -c "INSERT INTO test_bigserial (n_id)
SELECT generate_series(1, 100000);"
INSERT 0 **100000**

real    **0m35.328s**
user    0m0.002s
sys     0m0.000s
~$ time psql -d db -c "INSERT INTO test_serial (x)   
SELECT generate_series(1, 10000);"
INSERT 0 **10000**

real    **0m0.722s**
user    0m0.003s
sys     0m0.000s
~$ time psql -d db -c "INSERT INTO test_serial (x)
SELECT generate_series(1, 100000);"
INSERT 0 **100000**

real    **0m37.290s**
user    0m0.000s
sys     0m0.003s
~$ time psql -d db -c "INSERT INTO test_serial (x)
SELECT generate_series(1, 500000);"
INSERT 0 **500000**

real    **21m21.788s**
user    0m0.002s
sys     0m0.000s

=# \d test_serial
                         Table "public.test_serial"
 Column |  Type   |                        Modifiers                         
--------+---------+----------------------------------------------------------
 id     | integer | not null default nextval('test_serial_id_seq'::regclass)
 x      | integer | 
Distributed by: (id)

=# \d test_bigserial
                         Table "public.test_bigserial"
 Column |  Type   |                          Modifiers                          
--------+---------+-------------------------------------------------------------
 id     | bigint  | not null default nextval('test_bigserial_id_seq'::regclass)
 n_id   | integer | 
Distributed by: (id)

**Comment by InnerLife0** [comment]
I confirm. We faced this problem too  a day ago.
The reason is this [PR](https://github.com/greenplum-db/gpdb/pull/12029) and [this](https://github.com/arenadata/gpdb/commit/9ed94bca9faa0dc11db9138bd0695c26f560c3a8) commit (for 6x in our case).
The amount of [this](https://github.com/arenadata/gpdb/blob/9ed94bca9faa0dc11db9138bd0695c26f560c3a8/src/backend/utils/hash/dynahash.c#L883) loop iterations dramatically increased, because [match](https://github.com/arenadata/gpdb/blob/9ed94bca9faa0dc11db9138bd0695c26f560c3a8/src/backend/utils/hash/dynahash.c#L886) fucntion doesn't return 0 now.
For now, we are searching for a fix by ourselves, but it's possibly better to mention @dgkimura here.

At this time all sequences and serials affected. The workaround is to set sequence's cache value to something high.
```
postgres=# SELECT pg_get_serial_sequence('t_test', 'id_test');
         pg_get_serial_sequence          
-----------------------------------------
 public.t_test_id_test_seq
(1 row)

postgres=# alter sequence public.t_test_id_test_seq cache 10000;
ALTER SEQUENCE
```

**Comment by InnerLife0** [comment]
Why [match](https://github.com/arenadata/gpdb/blob/9ed94bca9faa0dc11db9138bd0695c26f560c3a8/src/backend/utils/hash/dynahash.c#L886) fucntion return non-zero value?
Before mentioned commit we used OId (not SeqTableKey) to pass to [hash_search](https://github.com/arenadata/gpdb/blob/9ed94bca9faa0dc11db9138bd0695c26f560c3a8/src/backend/commands/sequence.c).
This value [copied](https://github.com/arenadata/gpdb/blob/9ed94bca9faa0dc11db9138bd0695c26f560c3a8/src/backend/utils/hash/dynahash.c#L977) and [returned](https://github.com/arenadata/gpdb/blob/9ed94bca9faa0dc11db9138bd0695c26f560c3a8/src/backend/utils/hash/dynahash.c#L986) and then [treated](https://github.com/arenadata/gpdb/blob/9ed94bca9faa0dc11db9138bd0695c26f560c3a8/src/backend/commands/sequence.c#L1213) as [SeqTable](https://github.com/arenadata/gpdb/blob/9ed94bca9faa0dc11db9138bd0695c26f560c3a8/src/backend/commands/sequence.c#L79). [Copying](https://github.com/arenadata/gpdb/blob/9ed94bca9faa0dc11db9138bd0695c26f560c3a8/src/backend/commands/sequence.c#L1213) value to `elm->filenode` just overwrites the memory of `relid.called_from_dispatcher`. 
So, in our case, match function works with corrupted data provoking buckets count to grow higher and higher.

The following ugly fix solves the problem
```
diff --git a/src/backend/commands/sequence.c b/src/backend/commands/sequence.c
index 76a272aa31..85ab09841c 100644
--- a/src/backend/commands/sequence.c
+++ b/src/backend/commands/sequence.c
@@ -79,6 +79,7 @@ typedef struct sequence_magic
 typedef struct SeqTableData
 {
        Oid                     relid;                  /* pg_class OID of this sequence (hash key) */
+       bool called_from_dispatcher;
        Oid                     filenode;               /* last seen relfilenode of this sequence */
        LocalTransactionId lxid;        /* xact in which we last did a seq op */
        bool            last_valid;             /* do we have a valid "last" value? */
@@ -98,9 +99,6 @@ typedef struct SeqTableKey
        Oid relid;
        bool called_from_dispatcher;
 }
-#if defined(pg_attribute_packed)
-                       pg_attribute_packed()
-#endif
 SeqTableKey;
```

**Comment by dgkimura** [comment]
@sokolval - Thank you for creating this issue!

@InnerLife0 - Thank you for the spot on analysis!  I agree.  At the moment, I can't think of a better alternative to the solution you propose.  Would you like to create a pull-request on master that can then be backported to 6X?

**Comment by InnerLife0** [comment]
@dgkimura I'll create PR to master branch with modified version of fix today.

**Comment by dgkimura** [comment]
Fix has been merged into 6X_STABLE.  Thanks for the contributions!
