### ISSUE TITLE
bug "FATAL","XX000","shared_relation flag for ""pg_auth_time_constraint"" does not match IsSharedRelation(6070) (relcache.c:2833)"

### ISSUE THREAD

**Issue by digoal** [greenplum-db/gpdb#126]
commit c9a0fa4dd71336668303d694404b842a34cb64ea
Merge: 11c6425 5a2a527
Author: Heikki Linnakangas <hlinnakangas@pivotal.io>
Date:   Thu Nov 26 19:13:48 2015 +0200

    Merge commit '5a2a527bb500a7665f4aba26574f2494c5fc0469'
    
    Noth much interesting here, but I wanted to stop before the next upstream
    commit, which is a mechanical Copyright year bump.
    
    Conflicts:
        contrib/btree_gist/btree_gist.sql.in
        doc/FAQ
        doc/FAQ_DEV
        doc/FAQ_japanese
        doc/bug.template
        doc/src/FAQ/FAQ.html
        doc/src/FAQ/FAQ_DEV.html
        doc/src/FAQ/FAQ_japanese.html
        doc/src/sgml/ref/pg_ctl-ref.sgml
        doc/src/sgml/ref/postgres-ref.sgml
        doc/src/sgml/ref/reindex.sgml
        doc/src/sgml/release.sgml
        src/backend/access/gin/ginvacuum.c
        src/backend/access/heap/tuptoaster.c
        src/backend/main/main.c
        src/backend/postmaster/postmaster.c
        src/backend/tcop/postgres.c
        src/backend/utils/adt/float.c
        src/backend/utils/adt/regexp.c
        src/bin/pg_ctl/pg_ctl.c
        src/bin/pg_dump/dumputils.c
        src/include/catalog/pg_type.h
        src/include/pg_config.h.win32
        src/include/utils/builtins.h
        src/interfaces/ecpg/compatlib/Makefile
        src/interfaces/ecpg/ecpglib/Makefile
        src/interfaces/ecpg/pgtypeslib/Makefile
        src/interfaces/ecpg/preproc/Makefile
        src/interfaces/libpq/Makefile
        src/interfaces/libpq/libpq.rc.in
        src/port/win32ver.rc
        src/test/regress/pg_regress.c
        src/tools/RELEASE_CHANGES
        src/tools/copyright
        src/tools/msvc/Project.pm

when i use gpinitsystem init a greenplum database cluster, it's error:
```
20151127:09:27:36:033798 gpinitsystem:digoal:gp-[INFO]:----------------------------------------
20151127:09:27:36:033798 gpinitsystem:digoal:gp-[INFO]:-Greenplum Primary Segment Configuration
20151127:09:27:36:033798 gpinitsystem:digoal:gp-[INFO]:----------------------------------------
20151127:09:27:36:033798 gpinitsystem:digoal:gp-[INFO]:-digoal  /data01/gpdata/gpseg0   40000   2       0
20151127:09:27:36:033798 gpinitsystem:digoal:gp-[INFO]:-digoal  /data01/gpdata/gpseg1   40001   3       1
20151127:09:27:36:033798 gpinitsystem:digoal:gp-[INFO]:-digoal  /data01/gpdata/gpseg2   40002   4       2
20151127:09:27:37:033798 gpinitsystem:digoal:gp-[INFO]:-End Function DISPLAY_CONFIG
20151127:09:27:37:033798 gpinitsystem:digoal:gp-[INFO]:-Start Function ARRAY_REORDER
20151127:09:27:37:033798 gpinitsystem:digoal:gp-[INFO]:-End Function ARRAY_REORDER
20151127:09:27:37:033798 gpinitsystem:digoal:gp-[INFO]:-Start Function CREATE_QD_DB
20151127:09:27:37:033798 gpinitsystem:digoal:gp-[INFO]:-Building the Master instance database, please wait...
20151127:09:27:37:033798 gpinitsystem:digoal:gp-[INFO]:-Initializing Master Postgres instance /data01/gpdata/gpseg-1
20151127:09:27:37:033798 gpinitsystem:digoal:gp-[INFO]:-Commencing local /opt/gpdb/bin/initdb -E UTF8 -D /data01/gpdata/gpseg-1 --locale=C        --max_connections=48 --shared_buffers=256MB --is_filerep_mirrored=no --backend_output=/data01/gpdata/gpseg-1.initdb
The files belonging to this database system will be owned by user "gp".
This user must also own the server process.

The database cluster will be initialized with locale C.

creating directory /data01/gpdata/gpseg-1 ... ok
creating subdirectories ... ok
selecting default max_connections ... 48
selecting default shared_buffers/max_fsm_pages ... 256MB/409600
creating configuration files ... ok
creating template1 database in /data01/gpdata/gpseg-1/base/1 ... 2015-11-27 14:27:37.822588 GMT,,,p38488,th1225431104,,,,0,,,seg-1,,,,,"WARNING","01000","""fsync"": can not be set by the user and will be ignored.",,,,,,,,"set_config_option","guc.c",4325,
2015-11-27 09:27:38.536971 EST,,,p38488,th1225431104,,,,0,con1,,seg-1,,,x1,sx1,"FATAL","XX000","shared_relation flag for ""pg_auth_time_constraint"" does not match IsSharedRelation(6070) (relcache.c:2833)",,,,,,,,"RelationBuildLocalRelation","relcache.c",2833,1    0x8bd8a8 postgres errstart (??:?)
2    0x8bf64b postgres elog_finish (??:?)
3    0x89de0f postgres RelationBuildLocalRelation (??:?)
4    0x549fe7 postgres heap_create (??:?)
5    0x54b70f postgres heap_create_with_catalog (??:?)
6    0x53a67d postgres boot_yyparse (??:?)
7    0x53bf6e postgres AuxiliaryProcessMain (??:?)
8    0x485e52 postgres main (??:?)
9    0x7f6d47b53af5 libc.so.6 __libc_start_main (??:0)
10   0x485f19 postgres <symbol not found> (??:?)

child process exited with exit code 1
initdb: removing data directory "/data01/gpdata/gpseg-1"
2015-11-27 14:27:37.509257 GMT,,,p38487,th1885685824,,,,0,,,seg-1,,,,,"WARNING","01000","""fsync"": can not be set by the user and will be ignored.",,,,,,,,"set_config_option","guc.c",4325,
20151127:09:27:38:033798 gpinitsystem:digoal:gp-[INFO]:-Start Function ERROR_EXIT
20151127:09:27:38:gpinitsystem:digoal:gp-[FATAL]:- Command /opt/gpdb/bin/initdb -E UTF8 -D /data01/gpdata/gpseg-1 --locale=C        --max_connections=48 --shared_buffers=256MB --is_filerep_mirrored=no --backend_output=/data01/gpdata/gpseg-1.initdb failed with error status 1, see log file /home/gp/gpAdminLogs/gpinitsystem_20151127.log for more detail Script Exiting!
```

**Comment by hlinnaka** [comment]
On 27/11/15 16:31, Digoal.zhou wrote:
> creating template1 database in /data01/gpdata/gpseg-1/base/1 ... 2015-11-27 14:27:37.822588 GMT,,,p38488,th1225431104,,,,0,,,seg-1,,,,,"WARNING","01000","""fsync"": can not be set by the user and will be ignored.",,,,,,,,"set_config_option","guc.c",4325,
> 2015-11-27 09:27:38.536971 EST,,,p38488,th1225431104,,,,0,con1,,seg-1,,,x1,sx1,"FATAL","XX000","shared_relation flag for ""pg_auth_time_constraint"" does not match IsSharedRelation(6070) (relcache.c:2833)",,,,,,,,"RelationBuildLocalRelation","relcache.c",2833,1    0x8bd8a8 postgres errstart (??:?)
> 2    0x8bf64b postgres elog_finish (??:?)
> 3    0x89de0f postgres RelationBuildLocalRelation (??:?)
> 4    0x549fe7 postgres heap_create (??:?)
> 5    0x54b70f postgres heap_create_with_catalog (??:?)
> 6    0x53a67d postgres boot_yyparse (??:?)
> 7    0x53bf6e postgres AuxiliaryProcessMain (??:?)
> 8    0x485e52 postgres main (??:?)
> 9    0x7f6d47b53af5 libc.so.6 __libc_start_main (??:0)
> 10   0x485f19 postgres <symbol not found> (??:?)

Hmm, that's strange, it works for me and the buildfarm is happy. Did you 
try "make clean" before building?

- Heikki

**Comment by asimrp** [comment]
Hi @digoal, are you still facing this issue?

**Comment by ashwinstar** [comment]
Closing as didn't hear back from reporter. If still facing the issue please feel free to re-open.
