### ISSUE TITLE
Canceling `vacuum full` because of high VMEM usage

### ISSUE THREAD

**Issue by cobolbaby** [greenplum-db/gpdb#12633]
## Bug Report

When a table is significantly bloated, it is better to run VACUUM FULL. However, there are bugs related to improper memory usage in version 6.16.0.

### Greenplum version or build

- GP: 6.16.0

### OS version and uname -a

- Docker Container: Centos7
- Docker Host: Linux mdw 4.15.0-117-generic # 118-Ubuntu SMP Fri Sep 4 20:02:41 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

### Expected behavior

Even for the significantly bloated tables, there should not be such a problem as insufficient memory.

### Actual behavior

```
vacuum full dw.ship_mds_sno_parts;

ERROR:  Canceling query because of high VMEM usage. Used: 12353MB, available 1544MB, red zone: 13950MB (runaway_cleaner.c:202)  (seg2 10.13.0.59:40002 pid=1410032) (runaway_cleaner.c:202)
SQL state: XX000
```

**Comment by kainwen** [comment]
@cobolbaby Can you share a bit information on `dw.ship_mds_sno_parts`?

**Comment by cobolbaby** [comment]
![2021-09-27 10-54-42屏幕截图](https://user-images.githubusercontent.com/11460848/134891832-68a644ce-c0ef-4afa-b2ad-0baac75f592f.png)

**Comment by cobolbaby** [comment]
- dw.ship_mds_sno_parts 
  - Type: Heap
  - Size: 126.32 GB
  - Bloat Space: 125.22 GB

**Comment by haolinw** [comment]
It's hard to say that is a real bug without analyzing the detail information such as configuration and log.
The design of runaway detector does report error when the memory usage meets its criteria.
The basic knowledge is the accumulating requested memory size per segment should not exceed the red zone size: gp_vmem_protect_limit *
runaway_detector_activation_percent / 100.0, otherwise, the error message as you can see will be reported.

Could you please provide the following configuration as well as pg_log if there is a reoccurrence of this issue ?

gp_vmem_protect_limit
runaway_detector_activation_percent
gp_vmem_limit_per_query

Or you may want to use the system view session_state.session_level_memory_consumption to monitor the vmem usage status to help to understand the theory.

To enable that needs to make install gpcontrib/gp_internal_tools and follow https://github.com/greenplum-db/gpdb/blob/6X_STABLE/gpcontrib/gp_internal_tools/sql/gp_session_state_memory.sql to install the extension.
Then, run the following SQL on QD:
```
select m.segid,t.sum_vmem_mb,m.runaway_vmem_mb,m.is_runaway,m.sess_id,m.query from
    (select segid, sum(vmem_mb) as sum_vmem_mb from session_state.session_level_memory_consumption
    group by segid) t join session_state.session_level_memory_consumption m on m.segid = t.segid and
    m.query not like '%session_state.session_level_memory_consumption%' order by t.sum_vmem_mb desc;
\watch 1
```
As an example, paste my local test output here:
```
 segid | sum_vmem_mb | runaway_vmem_mb | is_runaway | sess_id |                                query
-------+-------------+-----------------+------------+---------+----------------------------------------------------------------------
     1 |          24 |               0 | f          |     242 | insert into t1 select generate_series(1,1000), repeat('a', 1000000);
     0 |          24 |               0 | f          |     242 | insert into t1 select generate_series(1,1000), repeat('a', 1000000);
     2 |          24 |               0 | f          |     242 | insert into t1 select generate_series(1,1000), repeat('a', 1000000);
    -1 |          22 |               0 | f          |     242 | insert into t1 select generate_series(1,1000), repeat('a', 1000000);
(4 rows)

                                               Watch every 1s   Tue Jan 18 07:37:51 2022

 segid | sum_vmem_mb | runaway_vmem_mb | is_runaway | sess_id |                                 query
-------+-------------+-----------------+------------+---------+-----------------------------------------------------------------------
    -1 |         118 |             104 | t          |     242 | insert into t1 select generate_series(1,100), repeat('a', 100000000);
     0 |          24 |               0 | f          |     242 | insert into t1 select generate_series(1,100), repeat('a', 100000000);
     2 |          24 |               0 | f          |     242 | insert into t1 select generate_series(1,100), repeat('a', 100000000);
     1 |          24 |               0 | f          |     242 | insert into t1 select generate_series(1,100), repeat('a', 100000000);
(4 rows)

                                               Watch every 1s   Tue Jan 18 07:37:52 2022

 segid | sum_vmem_mb | runaway_vmem_mb | is_runaway | sess_id |                                 query
-------+-------------+-----------------+------------+---------+-----------------------------------------------------------------------
     1 |          24 |               0 | f          |     242 | insert into t1 select generate_series(1,100), repeat('a', 100000000);
     0 |          24 |               0 | f          |     242 | insert into t1 select generate_series(1,100), repeat('a', 100000000);
     2 |          24 |               0 | f          |     242 | insert into t1 select generate_series(1,100), repeat('a', 100000000);
    -1 |          22 |               0 | f          |     242 | insert into t1 select generate_series(1,100), repeat('a', 100000000);
(4 rows)
```
The error message:
```
testdb=# insert into t1 select generate_series(1,100), repeat('a', 100000000);
ERROR:  Canceling query because of high VMEM usage. Used: 104MB, available 8079MB, red zone: 81MB (runaway_cleaner.c:202)
testdb=#
```
"sum_vmem_mb" represents the sum of requested memory of all sessions per segment, the value(118MB) on QD (segid = -1) exceeded the red zone size (81MB), so "is_runaway" is true and thus reported above error.
"Used: 104MB" represents the max size of memory used by a session, usually is same as "runaway_vmem_mb".
"available 8079MB" usually represents gp_vmem_protect_limit - red-zone-size.

**Comment by haolinw** [comment]
@cobolbaby If the above answer works for you, is that OK to close the issue ?

**Comment by ashwinstar** [comment]
I would like to flip the question and ask (just out of curiosity) if we know
- is the `vacuum full` memory requirements dependent on bloat on the table?
- is the `vacuum full` memory requirements dependent on size of the table?
- is the `vacuum full` memory requirements dependent on index and number of indexes present on the table?

Knowing these will help to answer first what amount of memory requirements does `vacuum full` have. Or is it required to be redesigned (I know it mostly might be upstream think then) `vacuum full` to be independent of these things to not be affected and able to work in constrained memory situation as well?

**Comment by cobolbaby** [comment]
IMO, database maintenance operations such as `vacuum` or `vacuum full` should not report such problems. After all, it is a maintenance task running in the background, and the resource consumption of memory should be relatively low.

**Comment by haolinw** [comment]
Any other question about this issue ? Or can we close it ? @cobolbaby

**Comment by cobolbaby** [comment]
No more, thanks.

**Comment by ashwinstar** [comment]
Shouldn't be using memory any higher than `maintenance_work_mem` for maintenance operations. In this case it was heap table, though in-general not sure AO table's respect that limit in GPDB for maintenance tasks.

**Comment by haolinw** [comment]
That's a little tricky, remembered had a discussion with team about that (@Aegeaner, @yaowangm), from code, seems memory usage should be under `maintenance_work_mem`, but seems still found OOM in some real case, haven't got a chance to dig.
