### ISSUE TITLE
Greenplum - count distinct queries - Extremely Slow

### ISSUE THREAD

**Issue by pusarya** [greenplum-db/gpdb#12641]
Dear Team

We request your support on below issue faced by us on OSS Greenplum.

### **Problem Statement :-** 
“Greenplum count(distinct) queries not able to respond in decent response time on underlying well distributed data and with performant cluster”

**Background on Infra:-**
a)	Cluster of 8 Data Nodes
b)	16 vcpu on each Node            
c)	32 GB RAM on each node
d)	8 Segments Per Node
e)	Cluster IOPS – Read - ~4 GB/s

**Background on Data:-**
1)	Fully Distributed Table of 120 Million record – on 64 Segments
2)	Each Segment contains – 2million record

**Background on Requirement & Problem Faced:-**
1)	20+ Independent attributes to be probed for distinct values for Dynamic Time Inputs. 
( Important Point to note -> These attributes are independent in nature, so cannot combine them together via group by clauses, and distinct is required) 

2)	Count(distinct) - We need within 10 sec interactive query response to process these counts for Dashboard. ( But Getting 180+ sec response time)

**Our Analysis:-**
1)	As per Explain plan , GPORCA is not even invoked for these queries and Postgres query optimizer is preparing Execution plan
2)	We tried to create Append-Optimized, Row/Columnar tables, to try bumping response time, but no improvements visible as such.
3)	Switched Off – ‘optimizer_force_multistage_agg’ – No effects yielded.- Response time - 192 sec
4)	Switched Off – ‘enable_groupagg’ - No effects yielded - Response time - 192 sec
5)	Switched On – ‘enable_hashagg’ – Response time - 120 sec

**Based on above facts, we want to know**
_1)	Why the GPORCA optimizer not getting enabled
2)	Why count(distinct) queries taking 15X more time than count(*) queries. Is parallelization not being utilized.
3)	How we can optimize these queries.
4)	Is there any other alternative to meet this requirement._

**### Query**
set client_min_messages=log

explain analyze
select 
fct.state_name  AS STATE_NAME,
count( distinct enrolled) as Enrolled_All, 
count( distinct enrolled_over30) as Enrolled_30,    
count( distinct cbac_completed) as cbac_completed,
count( distinct screened_full) + count( distinct screened_partial) as Total_Screened_First_Time,
count( distinct screened_full) as Screened_Full,
count( distinct screened_partial) as Screened_Partial,
count( distinct anm_rescreened)  as ReScreened,               
count( distinct phc_referred_by_asha) + count( distinct phc_referred_by_anm) + count( distinct anm_via_screening_cervical) as Referred_to_PHC, 
count( distinct phc_referred_by_asha) + count( distinct phc_referred_by_anm_without_cervical) + count( distinct anm_via_screening_cervical) as Referred_to_PHC_Without_CS,
count( distinct phc_referred_by_anm_without_cervical) as Referred_by_Cervical_Screening,
count( distinct phc_referred_by_asha) as Referred_by_Early_Detection,
count( distinct phc_referred_by_anm) as Referred_by_Screening,
count( distinct anm_via_screening_cervical) as Referred_for_VIA_Screening,
count( distinct secondary_referred) as Referred_to_Secondary,  
count( distinct th_referred) as Referred_to_Tertiary,     
count( distinct examined) as Examined,  
count( distinct examined_without_via) as Examined_Without_Via,
count( distinct phc_examined_cervical_via) as Examined_Via,
(count( distinct phc_referred_by_asha) + count( distinct phc_referred_by_anm) + count( distinct anm_via_screening_cervical) + count( distinct secondary_referred)+count( distinct th_referred)) as Tot_Referred ,
count( distinct diagnosed) as Diagnosed,                 
count( distinct under_treatment) as Under_Treatment
from 
goi_dwh."MV_NCD_+_Disease_AO" fct
where 
fct.time_id between 20180101 and 20210926
group by 
fct.state_name 
order by 
fct.state_name 

**### QUERY PLAN** 

```
                                                                                                                                                              |
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
Gather Motion 64:1  (slice2; segments: 64)  (cost=55660074.34..65839860.43 rows=23 width=286) (actual time=320381.431..320381.478 rows=29 loops=1)                       |
  Merge Key: state_name                                                                                                                                                  |
  ->  GroupAggregate  (cost=55660074.34..65839860.43 rows=1 width=286) (actual time=144636.238..192111.120 rows=3 loops=1)                                               |
        Group Key: state_name                                                                                                                                            |
        ->  Sort  (cost=55660074.34..55978192.63 rows=1988240 width=141) (actual time=115436.419..149594.034 rows=40217955 loops=1)                                      |
              Sort Key: state_name                                                                                                                                       |
              Sort Method:  quicksort  Memory: 354662kB                                                                                                                  |
              Sort Method:  external sort  Disk: 3622304kB                                                                                                               |
              Sort Method:  external merge  Disk: 493280kB                                                                                                               |
              ->  Redistribute Motion 64:64  (slice1; segments: 64)  (cost=0.00..4932450.62 rows=1988240 width=141) (actual time=11.983..40584.803 rows=40217955 loops=1)|
                    Hash Key: state_name                                                                                                                                 |
                    ->  Seq Scan on "MV_NCD_+_Disease_AO" fct  (cost=0.00..2387504.28 rows=1988240 width=141) (actual time=1.268..9955.026 rows=2046801 loops=1)         |
                          Filter: ((time_id >= 20180101) AND (time_id <= 20210926))                                                                                      |
Planning time: 11.129 ms                                                                                                                                                 |
  (slice0)    Executor memory: 359K bytes.                                                                                                                               |
  (slice1)    Executor memory: 258K bytes avg x 64 workers, 258K bytes max (seg0).                                                                                       |
* (slice2)    Executor memory: 57526K bytes avg x 64 workers, 731701K bytes max (seg38).  Work_mem: 96458K bytes max, 3647976K bytes wanted.                             |
Memory used:  128000kB                                                                                                                                                   |
Memory wanted:  7296251kB                                                                                                                                                |
Optimizer: Postgres query optimizer                                                                                                                                      |
Execution time: 320661.622 ms             

```                                                                                                                               |

**Comment by kainwen** [comment]
@pusarya The issue description is so good.

By turning on the GUC, `optimizer_trace_fallback`, you can know from the errmsg why ORCA fallback to planner.

**Comment by kainwen** [comment]
It seems ORCA does not support DQA:

```
gpadmin=# set optimizer_trace_fallback = on;
SET
gpadmin=# explain select a, count(distinct b), count(distinct c), count(distinct d) from t group by a;
INFO:  GPORCA failed to produce a plan, falling back to planner
DETAIL:  Feature not supported: Multiple Distinct Qualified Aggregates are disabled in the optimizer
                                      QUERY PLAN
--------------------------------------------------------------------------------------
 Gather Motion 3:1  (slice1; segments: 3)  (cost=5985.02..6812.52 rows=1000 width=28)
   ->  GroupAggregate  (cost=5985.02..6812.52 rows=334 width=28)
         Group Key: a
         ->  Sort  (cost=5985.02..6148.52 rows=21800 width=16)
               Sort Key: a
               ->  Seq Scan on t  (cost=0.00..754.00 rows=21800 width=16)
 Optimizer: Postgres query optimizer
(7 rows)
```

So we have to optimize this query and plan under legacy planner.

1. Can you paste the plan with best speed? (with GUC tuning)
2. Can you try to enlarge `statement_mem`

**Comment by pusarya** [comment]
@kainwen - As suggested, I tried to bump work_mem & statement_mem GUC parameters, but looks this is best plan, which is no better than what send earlier.

Also, we dont see any alternative to this query logic as for all the required attributes in Query, a different Timestamp is considered as base for aggregation as they are time based events, 
This requirement mandatorily need Run time distinct counts across Time periods if GPORCA is not supporting this query, I am afraid what alternative we have then.

Also from documentation, I found that set optimizer_enable_multiple_distinct_aggs can forcefully enable GPORCA optimizer, but that actually produce a far less efficient plan than Postgres Optimizer.

~$ **gpconfig -s work_mem**
Values on all segments are consistent
GUC          : work_mem
Master  value: 256MB
Segment value: 256MB

~$gpstop -M fast
~$gpstart

**SET statement_mem TO '200 MB';**
set client_min_messages=log;
set optimizer_trace_fallback = on;

QUERY PLAN                                                                                                                                                              |
------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
Gather Motion 64:1  (slice2; segments: 64)  (cost=55660074.34..65839860.43 rows=23 width=286) (actual time=318520.123..318520.166 rows=29 loops=1)
  Merge Key: state_name
  ->  GroupAggregate  (cost=55660074.34..65839860.43 rows=1 width=286) (actual time=142940.092..192417.705 rows=3 loops=1)
        Group Key: state_name
        ->  Sort  (cost=55660074.34..55978192.63 rows=1988240 width=141) (actual time=112410.601..146979.055 rows=40217955 loops=1)
              Sort Key: state_name
              Sort Method:  quicksort  Memory: 354662kB
              Sort Method:  external sort  Disk: 3622304kB
              Sort Method:  external merge  Disk: 493280kB
              ->  Redistribute Motion 64:64  (slice1; segments: 64)  (cost=0.00..4932450.62 rows=1988240 width=141) (actual time=5.534..39512.092 rows=40217955 loops=1)
                    Hash Key: state_name
                    ->  Seq Scan on "MV_NCD_+_Disease_AO" fct  (cost=0.00..2387504.28 rows=1988240 width=141) (actual time=0.480..10970.042 rows=2046801 loops=1)
                          Filter: ((time_id >= 20180101) AND (time_id <= 20210926))
Planning time: 4.775 ms
  (slice0)    Executor memory: 359K bytes.
  (slice1)    Executor memory: 258K bytes avg x 64 workers, 258K bytes max (seg0).
* (slice2)    Executor memory: 57526K bytes avg x 64 workers, 731701K bytes max (seg38).  Work_mem: 96458K bytes max, 3647976K bytes wanted.
Memory used:  128000kB
Memory wanted:  7296251kB
Optimizer: Postgres query optimizer
Execution time: 318775.524 ms                                                                                                                                      |

**Comment by vraghavan78** [comment]
@pusarya GPORCA currently does efficiently support Multiple DQA that is why it falls back to planner. Let me think if there is a re-write available

**Comment by kainwen** [comment]
@pusarya We do not use `work_mem` in gpdb, we use `statement_mem`.

Set `statement_mem` can lead to memory-consume node (sort, hashjoin, ....) to use more memory instead of spilling much to disck so that can improve the speed. `statement_mem` does not impact the plan.

Can you please share the table def? Thanks.

**Comment by vraghavan78** [comment]
@pusarya here is a potential re-write that will be supported by Orca.

```sql
explain analyze
WITH drvd_table as (SELECT * from goi_dwh."MV_NCD_+_Disease_AO" fct where fct.time_id between 20180101 and 20210926)

select x.STATE_NAME, x,Enrolled_All, y.Enrolled_30
from
(select state_name AS STATE_NAME, count( distinct enrolled) as Enrolled_All,
from drvd_table  group by fct.state_name) x,
(select  y.state_name AS STATE_NAME, count( distinct enrolled_over30) as Enrolled_30,
from drvd_table group by fct.state_name) y
where x.STATE_NAME = y.STATE_NAME
order by x.STATE_NAME
```
What I have tried to do is two of the distinct qualified aggregates into its own derived table execution. I am not sure if the generated plan is indeed better. Please note that since I did not have the DDL, i could not get the syntax correctness. Please fix the minor syntax errors if there are any.

**Comment by pusarya** [comment]
@vraghavan78 - I adjusted your query and tried with 2 distinct attributes, but time remains 74 sec in both the case (Original groupby Vs this query)
So if we expand to 20 attributes , it will take same 200+ sec.

**Also Query plan is still Postgres optimizer. Results below**

@kainwen - DDL is attached
[Table DDL.zip](https://github.com/greenplum-db/gpdb/files/7256239/Table.DDL.zip)


### **Query** 
explain analyze
WITH drvd_table as (SELECT * from goi_dwh."MV_NCD_+_Disease_AO" fct where fct.time_id between 20180101 and 20210926)
select x.STATE_NAME, x,Enrolled_All, y.Enrolled_30
from
(select state_name AS STATE_NAME, count( distinct enrolled) as Enrolled_All
from drvd_table  group by state_name) x,
(select  state_name AS STATE_NAME, count( distinct enrolled_over30) as Enrolled_30
from drvd_table group by state_name) y
where x.STATE_NAME = y.STATE_NAME
order by x.STATE_NAME

**### Query Plan**
> Gather Motion 64:1  (slice3; segments: 64)  (cost=7123842.25..7123844.75 rows=1000 width=284) (actual time=189237.479..189237.523 rows=29 loops=1)
  Merge Key: x.state_name
  ->  Sort  (cost=7123842.25..7123844.75 rows=16 width=284) (actual time=159678.336..159678.341 rows=3 loops=1)
        Sort Key: x.state_name
        Sort Method:  quicksort  Memory: 2112kB
        ->  Hash Join  (cost=7123634.92..7123792.42 rows=16 width=284) (actual time=159677.875..159678.010 rows=3 loops=1)
              Hash Cond: ((x.state_name)::text = (y.state_name)::text)
              Extra Text: (seg16)  Hash chain length 1.0 avg, 1 max, using 1 of 32768 buckets.Hash chain length 1.0 avg, 1 max, using 1 of 256 buckets; total 0 expansions.

              Extra Text: (seg55)  Hash chain length 1.0 avg, 1 max, using 3 of 32768 buckets.Hash chain length 1.0 avg, 1 max, using 1 of 32768 buckets.Hash chain length 1.0 avg, 1 max, using 1 of 256 buckets; total 0 expansions.

              ->  Subquery Scan on x  (cost=3561801.21..3561821.21 rows=16 width=276) (actual time=84777.628..84777.640 rows=3 loops=1)
                    ->  HashAggregate  (cost=3561801.21..3561811.21 rows=16 width=126) (actual time=84777.592..84777.598 rows=3 loops=1)
                          Group Key: drvd_table.state_name
                          Extra Text: (seg16)  Hash chain length 1.0 avg, 1 max, using 1 of 256 buckets; total 0 expansions.

                          Extra Text: (seg55)  Hash chain length 1.0 avg, 1 max, using 3 of 256 buckets; total 0 expansions.

                          ->  HashAggregate  (cost=3536801.21..3546801.21 rows=15625 width=126) (actual time=55061.682..83224.555 rows=18213280 loops=1)
                                Group Key: drvd_table.state_name, drvd_table.enrolled
                                Extra Text: (seg9)   6548256 groups total in 32 batches; 1 overflows; 6548260 spill groups.
(seg9)   Hash chain length 3.5 avg, 56 max, using 2022647 of 2228224 buckets; total 2 expansions.

                                Extra Text: (seg16)  4520853 groups total in 32 batches; 1 overflows; 4520857 spill groups.
(seg16)  Hash chain length 4.8 avg, 44 max, using 1060433 of 1179648 buckets; total 2 expansions.

                                Extra Text: (seg38)  18213280 groups total in 96 batches; 33 overflows; 36426566 spill groups.
(seg38)  Hash chain length 4.4 avg, 125 max, using 8266841 of 8519680 buckets; total 130 expansions.

                                ->  Redistribute Motion 64:64  (slice1; segments: 64)  (cost=3499301.21..3519301.21 rows=15625 width=126) (actual time=0.043..22491.174 rows=18213407 loops=1)
                                      Hash Key: drvd_table.state_name
                                      ->  HashAggregate  (cost=3499301.21..3499301.21 rows=15625 width=126) (actual time=11660.611..17730.740 rows=882192 loops=1)
                                            Group Key: drvd_table.state_name, drvd_table.enrolled
                                            Extra Text: (seg6)   Hash chain length 3.5 avg, 15 max, using 249700 of 262144 buckets; total 2 expansions.

                                            ->  Subquery Scan on drvd_table  (cost=0.00..2544946.34 rows=1988240 width=126) (actual time=1.926..16468.038 rows=2046801 loops=1)
                                                  ->  Seq Scan on "MV_NCD_+_Disease_AO" fct  (cost=0.00..2387504.28 rows=1988240 width=917) (actual time=1.920..8211.659 rows=2046801 loops=1)
                                                        Filter: ((time_id >= 20180101) AND (time_id <= 20210926))
              ->  Hash  (cost=3561821.21..3561821.21 rows=16 width=126) (actual time=74899.974..74899.974 rows=3 loops=1)
                    ->  Subquery Scan on y  (cost=3561801.21..3561821.21 rows=16 width=126) (actual time=74899.950..74899.962 rows=3 loops=1)
                          ->  HashAggregate  (cost=3561801.21..3561811.21 rows=16 width=126) (actual time=74899.946..74899.953 rows=3 loops=1)
                                Group Key: drvd_table_1.state_name
                                Extra Text: (seg4)   Hash chain length 1.0 avg, 1 max, using 1 of 256 buckets; total 0 expansions.

                                Extra Text: (seg16)  Hash chain length 1.0 avg, 1 max, using 1 of 256 buckets; total 0 expansions.

                                Extra Text: (seg55)  Hash chain length 1.0 avg, 1 max, using 3 of 256 buckets; total 0 expansions.

                                ->  HashAggregate  (cost=3536801.21..3546801.21 rows=15625 width=126) (actual time=61938.117..77786.367 rows=12707614 loops=1)
                                      Group Key: drvd_table_1.state_name, drvd_table_1.enrolled_over30
                                      Extra Text: (seg9)   3930566 groups total in 32 batches; 1 overflows; 3930573 spill groups.
(seg9)   Hash chain length 4.0 avg, 21 max, using 1118108 of 1179648 buckets; total 2 expansions.

                                      Extra Text: (seg16)  2465456 groups total in 32 batches; 1 overflows; 2465460 spill groups.
(seg16)  Hash chain length 4.7 avg, 19 max, using 646640 of 655360 buckets; total 2 expansions.

                                      Extra Text: (seg38)  12707614 groups total in 32 batches; 1 overflows; 12707624 spill groups.
(seg38)  Hash chain length 3.3 avg, 42 max, using 4036553 of 4325376 buckets; total 66 expansions.

                                      ->  Redistribute Motion 64:64  (slice2; segments: 64)  (cost=3499301.21..3519301.21 rows=15625 width=126) (actual time=17655.281..36324.833 rows=12707741 loops=1)
                                            Hash Key: drvd_table_1.state_name
                                            ->  HashAggregate  (cost=3499301.21..3499301.21 rows=15625 width=126) (actual time=19090.419..21563.015 rows=624372 loops=1)
                                                  Group Key: drvd_table_1.state_name, drvd_table_1.enrolled_over30
                                                  Extra Text: (seg6)   Hash chain length 3.4 avg, 15 max, using 186359 of 262144 buckets; total 2 expansions.

                                                  ->  Subquery Scan on drvd_table_1  (cost=0.00..2544946.34 rows=1988240 width=126) (actual time=1.094..17799.314 rows=2046801 loops=1)
                                                        ->  Seq Scan on "MV_NCD_+_Disease_AO" fct_1  (cost=0.00..2387504.28 rows=1988240 width=917) (actual time=1.090..8803.155 rows=2046801 loops=1)
                                                              Filter: ((time_id >= 20180101) AND (time_id <= 20210926))
Planning time: 11.463 ms
  (slice0)    Executor memory: 673K bytes.
  (slice1)    Executor memory: 32218K bytes avg x 64 workers, 32232K bytes max (seg13).
  (slice2)    Executor memory: 32217K bytes avg x 64 workers, 32232K bytes max (seg3).
* (slice3)    Executor memory: 5684K bytes avg x 64 workers, 33527K bytes max (seg16).  Work_mem: 31851K bytes max, 1034325K bytes wanted.
Memory used:  128000kB
Memory wanted:  8275596kB
Optimizer: Postgres query optimizer
Execution time: 189313.546 ms

**Comment by pusarya** [comment]
Hello Guys

To counter this problem of Count distinct delays, We used HLL extensions for count approximation.

https://github.com/citusdata/postgresql-hll

Now we use some aggregate functions mentioned as count distinct alternative.

One of the query plan is below.
It seems GPORCA is kicked off but still parallelization of function doesn't look to invoke

**Query -1**
explain analyse
select 
sum(hll_cardinality(enrolled))::int as Enrolled_All, 
sum(hll_cardinality(enrolled_over30))::int as Enrolled_30,
sum(hll_cardinality(cbac_completed))::int as cbac_completed
from 
goi_dwh."MV_NCD_+_Disease_HLL_AO" fct
where 
fct.time_id between 20180101 and 20211031

--Query Plan--
Result  (cost=0.00..1094.73 rows=1 width=12) (actual time=1673.041..1673.042 rows=1 loops=1)
  ->  Aggregate  (cost=0.00..1094.73 rows=1 width=24) (actual time=1673.031..1673.031 rows=1 loops=1)
        ->  Gather Motion 32:1  (slice1; segments: 32)  (cost=0.00..1094.73 rows=1 width=24) (actual time=1060.906..1672.933 rows=32 loops=1)
              ->  Aggregate  (cost=0.00..1094.73 rows=1 width=24) (actual time=1534.190..1534.190 rows=1 loops=1)
                    ->  Seq Scan on "MV_NCD_+_Disease_HLL_AO"  (cost=0.00..1020.49 rows=1037389 width=71) (actual time=0.881..725.279 rows=1046584 loops=1)
                          Filter: ((time_id >= 20180101) AND (time_id <= 20211031))
Planning time: 7.342 ms
  (slice0)    Executor memory: 656K bytes.
  (slice1)    Executor memory: 820K bytes avg x 32 workers, 820K bytes max (seg0).
Memory used:  128000kB
Optimizer: Pivotal Optimizer (GPORCA)
Execution time: 1685.408 ms


**Query2**
select 
hll_cardinality(hll_union_agg(enrolled)) as enrolled ,
hll_cardinality(hll_union_agg(enrolled_over30)) as enrolled_over30 ,
hll_cardinality(hll_union_agg(cbac_completed)) as cbac_completed 
from 
goi_dwh."MV_NCD_+_Disease_HLL_AO" fct
inner join goi_dwh.locationwise_population_details pop on pop.location_type = fct.state_id 
where --fct.state_name ='Karnataka' and
--fct.state_id = 129 and fct.district_id = 12923 and 
fct.time_id between 20180101 and 20211031

**Query Plan**
Result  (cost=0.00..8918.91 rows=1 width=24) (actual time=18859.309..18859.310 rows=1 loops=1)
  ->  Aggregate  (cost=0.00..8918.91 rows=1 width=24) (actual time=18858.701..18858.701 rows=1 loops=1)
        ->  Gather Motion 32:1  (slice1; segments: 32)  (cost=0.00..6543.11 rows=33196436 width=71) (actual time=1.490..7488.769 rows=33429307 loops=1)
              ->  Seq Scan on "MV_NCD_+_Disease_HLL_AO"  (cost=0.00..1020.49 rows=1037389 width=71) (actual time=0.715..809.550 rows=1046584 loops=1)
                    Filter: ((time_id >= 20180101) AND (time_id <= 20211031))
Planning time: 6.343 ms
  (slice0)    Executor memory: 1440K bytes.
  (slice1)    Executor memory: 734K bytes avg x 32 workers, 828K bytes max (seg5).
Memory used:  128000kB
Optimizer: Pivotal Optimizer (GPORCA)
Execution time: 18860.651 ms


So Query 2 is taking 17 sec more due to hll_union_agg function.
Want to check if there is any way to parallelize it

**Comment by vraghavan78** [comment]
Not planning to work on this in the immediate timeline.
