### ISSUE TITLE
High System CPU usage observed right after vacuum on catalog table

### ISSUE THREAD

**Issue by sokolval** [greenplum-db/gpdb#12646]
### Greenplum version or build
PostgreSQL 9.4.24 (Greenplum Database 6.17.3 build dev) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609, 64-bit compiled on Sep  8 2021 17:27:53
### OS version and uname -a
Linux hostname 4.19.62-13 #1 SMP Mon Jul 29 17:22:59 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
### autoconf options used ( config.status --config )
./config.status --config
'--with-perl' '--with-python' '--without-gssapi' '--enable-gpcloud' '--with-libxml' '--with-system-tzdata=/usr/share/zoneinfo' '--prefix=/usr/local/gpdb'
### Installation information ( pg_config )
BINDIR = /usr/local/gpdb/bin
DOCDIR = /usr/local/gpdb/share/doc/postgresql
HTMLDIR = /usr/local/gpdb/share/doc/postgresql
INCLUDEDIR = /usr/local/gpdb/include
PKGINCLUDEDIR = /usr/local/gpdb/include/postgresql
INCLUDEDIR-SERVER = /usr/local/gpdb/include/postgresql/server
LIBDIR = /usr/local/gpdb/lib/x86_64-linux-gnu
PKGLIBDIR = /usr/local/gpdb/lib/x86_64-linux-gnu/postgresql
LOCALEDIR = /usr/local/gpdb/share/locale
MANDIR = /usr/local/gpdb/share/man
SHAREDIR = /usr/local/gpdb/share/postgresql
SYSCONFDIR = /etc/postgresql
PGXS = /usr/local/gpdb/lib/x86_64-linux-gnu/postgresql/pgxs/src/makefiles/pgxs.mk
CONFIGURE = '--build=x86_64-linux-gnu' '--prefix=/usr' '--includedir=/usr/local/gpdb/include' '--mandir=/usr/local/gpdb/share/man' '--infodir=/usr/local/gpdb/share/info' '--sysconfdir=/etc' '--localstatedir=/var' '--disable-silent-rules' '--libdir=/usr/local/gpdb/lib/x86_64-linux-gnu' '--libexecdir=/usr/local/gpdb/lib/x86_64-linux-gnu' '--disable-maintainer-mode' '--disable-dependency-tracking' '--with-perl' '--with-python' '--without-gssapi' '--disable-gpcloud' '--with-libxml' '--with-system-tzdata=/usr/share/zoneinfo' '--prefix=/usr/local/gpdb' '--enable-ic-proxy' 'build_alias=x86_64-linux-gnu' 'CFLAGS=-g -O2 -fstack-protector-strong -Wformat -Werror=format-security' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'CXXFLAGS=-g -O2 -fstack-protector-strong -Wformat -Werror=format-security'
CC = gcc
CPPFLAGS = -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2 -I/usr/local/gpdb/include
CFLAGS = -Wall -Wmissing-prototypes -Wpointer-arith -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fno-aggressive-loop-optimizations -Wno-unused-but-set-variable -Wno-address -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -std=gnu99 -Werror=uninitialized -Werror=implicit-function-declaration -I/usr/local/gpdb/include
CFLAGS_SL = -fPIC
LDFLAGS = -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,--as-needed -Wl,-rpath,'/usr/local/gpdb/lib/x86_64-linux-gnu',--enable-new-dtags -L/usr/local/gpdb/lib/x86_64-linux-gnu
LDFLAGS_EX = 
LDFLAGS_SL = 
LIBS = -lpgcommon -lpgport -lxerces-c -lxml2 -lrt -luv -lzstd -lrt -lcrypt -ldl -lm -L/usr/local/gpdb/lib/x86_64-linux-gnu
VERSION = PostgreSQL 9.4.24

### Expected bahvior
No outstanding CPU utilization, all tables could be vacuumed and cluster continues normal life
### Actual behavior
After vacuumig even small table (like pg_tablespace) CPU consumtions on all segment hosts spikes to high values and keeps server highly utilized for 1 minute at least. More time with larger tables. This delays calculations and prevents normal vacuuming of catalog tables
### Step to reproduce the behavior
Moved 1 segment from seghost to 2ndary master host and we started facing such issues

### Anomalies observed
`~$ strace -c -p  16669
strace: Process 16669 attached
strace: [ Process PID=16669 runs in x32 mode. ]
strace: [ Process PID=16669 runs in 64 bit mode. ]
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
 38.73    0.270727          18     14888         1 select
 20.65    0.144373           2     87094        62 read
 14.67    0.102583           5     19726       152 recvfrom
  9.89    0.069149        2766        25           munmap
  3.07    0.021472           5      4166      1918 shutdown
  2.48    0.017324           4      4196           fcntl
  2.25    0.015710           4      4144           close
  1.91    0.013339           6      2231       163 accept
  1.30    0.009075         252        36           brk
  1.29    0.009004           4      2098           getsockname
  0.83    0.005817           5      1066           write
  0.56    0.003943           2      1742           lseek
  0.56    0.003900           6       690           sendto
  0.33    0.002304           4       519        12 open
  0.23    0.001642           8       194       159 unlink
  0.20    0.001373           4       386           epoll_ctl
  0.16    0.001094           6       193           pipe2
  0.14    0.000966           5       193           epoll_create1
  0.11    0.000740          24        31           fdatasync
  0.10    0.000724           4       193           eventfd2
  0.09    0.000596           8        76        18 stat
  0.08    0.000552           3       193           epoll_wait
  0.08    0.000526           8        66        66 access
  0.07    0.000508          17        30        30 connect
  0.04    0.000288           1       245           semop
  0.04    0.000277           7        38           kill
  0.03    0.000230           8        30           socket
  0.03    0.000211           7        31        31 poll
  0.03    0.000198           3        66           rt_sigprocmask
  0.02    0.000119           5        25           mmap
  0.02    0.000113           1       146        32 rt_sigreturn
  0.01    0.000096           3        30           getsockopt
  0.01    0.000051           3        16           fstat
  0.00    0.000006           6         1           rt_sigaction
  0.00    0.000006           1         9           fsync
  0.00    0.000001           1         2           mprotect
  0.00    0.000000           0         1           futex
------ ----------- ----------- --------- --------- ----------------
100.00    0.699037                144816      2644 total
`
Observed errors in strace output

**Comment by sokolval** [comment]
More observations to this issue:
High CPU consumption (especially high number of syscalls) is getting observed not at the exact moment of vacuum working, but few seconds after the vacuum stopped.
Potential supplement to issue details is that we observe it only when there is some load (like 15+) running sessions on the cluster. Another supplement to our particular case is that we have slightly uneven distribution of segments across hosts.
all hosts but one have 3 primary and 3 mirrors on board, while 1 host contains 2 primaries and 2 mirrors.
This was a forced measure due to we need to make less segments per host, but limited number of new hosts.
However the CPU overusage observed independently of number of segments per host.

Do you have any recommendations which could be adjusted to mitigate such behavior?
What could be the reason for this?

We see cluster reinitialization as a last resort option to overcome this case.

**Comment by lij55** [comment]
Hi @sokolval ,

the information is a bit little to identify the issue. it seems there are a lot of network traffic according to the strace summary. it doesn't look like a vacuum related action.
do you happen to run gpcc or other tools to indicate what's the network status at that time?

**Comment by ashwinstar** [comment]
Given not sufficient information to RCA on the issue but the isolated report of the issue. Closing the same for now. If the issue happens again, needs to be investigated more on which process in system continued to consume CPU and what that process was doing (via collecting pstacks) to get better idea.
