### ISSUE TITLE
6X: Wrong results for SRF within COALESCE

### ISSUE THREAD

**Issue by chrishajas** [greenplum-db/gpdb#12657]
## Bug Report
In GPDB6, a SRF within a conditional execution construct is allowed and can produce incorrect results. This is also the case in Postgres 9.4. In GPDB master, this was fixed with 69f4b9c85f168ae006929eec44fc44d569e846b9 and 0436f6bde8848b7135f19dd7f8548b8c2ae89a34 and returns an error instead. 

This occurs with both Orca and planner, but for Orca this will be fixed and return an error `set-valued function called in context that cannot accept a set` once https://github.com/greenplum-db/gpdb/pull/12623 is backported. Ideally planner should do the same (and this should be handled in parsing).

### Repro
```
create table nested_srf(a text);
insert into nested_srf values ('abc,def,ghi');
select count(*) from (select trim(coalesce(regexp_split_to_table((a)::text, ','::text),'')) from nested_srf)a;
 count
-------
     1
(1 row)
```

**Comment by dpandhi-git** [comment]
with @ashwinstar error out on 7x, not fixing for 6x

`postgres=# select count(*) from (select trim(coalesce(regexp_split_to_table((a)::text, ','::text),'')) from nested_srf)a;
ERROR:  set-returning functions are not allowed in COALESCE`
