### ISSUE TITLE
error in PolicyEagerFreeAssignOperatorMemoryKB makes query end without calling mppExecutorCleanup

### ISSUE THREAD

**Issue by violet2016** [greenplum-db/gpdb#12690]
## Bug Report
In GPDB6, when memory is limit, query could throw an error "insufficient memory reserved for statement" without calling mppExecutorCleanup function and left some hooks should be called in the function not called at all.

### Greenplum version or build
6.17.5
### OS version and uname -a
centos 7
### Expected behavior
mppExecutorCleanup should be called at the end whenever an error happened.
### Step to reproduce the behavior
1. attach a running gpdb postgres connecton process with gdb, set breakpoints at PolicyEagerFreeAssignOperatorMemoryKB and mppExecutorCleanup
2. run a query like "select 1" with the postgres connection
3. when break at PolicyEagerFreeAssignOperatorMemoryKB, step before the condition line of the errmsg
4. set ctx.groupTree->groupMemKB to 1
5. the error will occure
6. You can see gdb not stop at the breakpoint of mppExecutorCleanup

**Comment by adam8157** [comment]
Status summary: the first has a problem, so we reverted it on the 6X_STABLE, and had the following fix (https://github.com/greenplum-db/gpdb/pull/13870) on the main branch.

**Comment by adam8157** [comment]
The new 6X version fix: https://github.com/greenplum-db/gpdb/pull/14677
