### ISSUE TITLE
Cannot drop table after creating extension failure and in a new session (cache lookup failed for extension)

### ISSUE THREAD

**Issue by kainwen** [greenplum-db/gpdb#12713]
### Greenplum version or build

master (top commit: 9a00841af7c26097a539ad527428be0341ce03d0)
6x (top commit: 3f8c5812b12b203adfce7ae2339c8b19c710048e)
not sure for 5X

### Expected behavior

works well

### Actual behavior

Cannot drop table, throw errors.

```
ERROR:  cache lookup failed for extension 16405 (objectaddress.c:3570)  (seg1 127.0.1.1:7003 pid=14513) (objectaddress.c:3570)
```

### Step to reproduce the behavior

1. First using a normal use (not super user) to try to create extension and hit an error (we need the error to reproduce the bug).
2. Then do not logout the session, just in this session create a table and insert some data
3. Next, quit the session, and start a new one, in the new session try to drop the table using the normal user, and it will error out. (**If you drop table in the same session, it can work. Strange, we also need to explain this.**)

```
gpadmin=# set role test;
SET
gpadmin=> create extension gp_inject_fault ;
ERROR:  permission denied to create extension "gp_inject_fault"
HINT:  Must be superuser to create this extension.
gpadmin=> create table t(a int);
CREATE TABLE
gpadmin=> insert into t values (1);
INSERT 0 1
gpadmin=> quit;
gpadmin@zlv-ubuntu:~/gpdb$ psql
psql (12beta2)
Type "help" for help.

gpadmin=# set role test;
SET
gpadmin=> drop table t;
ERROR:  cache lookup failed for extension 16415 (objectaddress.c:3570)  (seg1 127.0.1.1:7003 pid=16991) (objectaddress.c:3570)
gpadmin=>
```

**Comment by kainwen** [comment]
It seems the first steps broke the catalog consistency:

```
SUMMARY REPORT: FAILED
===================================================================
Completed 14 test(s) on database 'gpadmin' at 2021-10-20 13:14:26 with elapsed time 0:00:07
Found a total of 2 issue(s)

----------------------------------------------------
Relation oid: 16387
Relation schema: public
Relation name: t

    Name of test which found this issue: missing_extraneous_pg_depend
        Extra depend metadata of {'classid': 1259, 'objid': 16387, 'objsubid': 0, 'refclassid': 3079, 'refobjid': 16386, 'refobjsubid': 0, 'deptype': 'e'} on content 0 (zlyu:6000)
        Missing depend metadata of {'classid': 1259, 'objid': 16387, 'objsubid': 0, 'refclassid': 3079, 'refobjid': 16386, 'refobjsubid': 0, 'deptype': 'e'} on content -1 (zlyu:5432)


----------------------------------------------------
Object oid: 16386
Table name: pg_extension

    Name of test which found this issue: dependency_pg_extension
    Table pg_extension has a dependency issue on oid 16386 at content 0


Failed test(s) that are not reported here: dependency
See /home/gpadmin/gpAdminLogs/gpcheckcat_20211020.log for detail

```

**Comment by kainwen** [comment]
It seems the failed `create extension` statement leaves some uncleaned global variable in each QEs.

I set the `gp_vmem_idle_resource_timeout` to '1s',  then those QEs will be cleaned very soon. And this issue is gone.

--------

Next, I set back `gp_vmem_idle_resource_timeout` to a huge value, like `10min`, then using `gpcheckcat` to verify this.

```
gpadmin=# set role test;
SET
gpadmin=> create extension gp_inject_fault;
ERROR:  permission denied to create extension "gp_inject_fault"
HINT:  Must be superuser to create this extension.
gpadmin=>
```

After the above steps, running `gpcheckcat`, no issues found.

Then  create a table in the above session, 

```
gpadmin=> create table t(a int);
NOTICE:  Table doesn't have 'DISTRIBUTED BY' clause -- Using column named 'a' as the Greenplum Database data distribution key for this table.
HINT:  The 'DISTRIBUTED BY' clause determines the distribution of data. Make sure column(s) chosen are the optimal data distribution key to minimize skew.
CREATE TABLE
```

And now let's run `gpcheckcat`, we found several issues:

```
SUMMARY REPORT: FAILED
===================================================================
Completed 14 test(s) on database 'gpadmin' at 2021-10-20 22:04:41 with elapsed time 0:00:08
Found a total of 2 issue(s)

----------------------------------------------------
Relation oid: 33310
Relation schema: public
Relation name: t

    Name of test which found this issue: missing_extraneous_pg_depend
        Missing depend metadata of {'classid': 1259, 'objid': 33310, 'objsubid': 0, 'refclassid': 3079, 'refobjid': 32769, 'refobjsubid': 0, 'deptype': 'e'} on content -1 (zlyu:7000)


----------------------------------------------------
Object oid: 32769
Table name: pg_extension

    Name of test which found this issue: dependency_pg_extension
    Table pg_extension has a dependency issue on oid 32769 at content 0
    Table pg_extension has a dependency issue on oid 32769 at content 1
    Table pg_extension has a dependency issue on oid 32769 at content 2


Failed test(s) that are not reported here: dependency
```

I think this is the core reason for this bug. Still need more time to look into this.

**Comment by kainwen** [comment]
I think the root cause has been found:

when `create extension gp_inject_fault;` such extension create statement fails, it forget to clean the global variable `creating_extension` in QEs.

So just after this statement fails, QD's `creating_extension` is false, but all QEs `creating_extension` is true.

Then when we create a table, `heap_create_with_catalog` will invoke `recordDependencyOnCurrentExtension` to see if it should add a `pg_depend` entry.

On QD, it does not, but on QEs, it does thus leads to catalog inconsistency.

--------

I manually use gdb to attach to those QEs, and `p creating_extension = 0`, then quit gdb.

The issue is gone.

----------

Next, we have to find a good way to fix this issue.

**Comment by kainwen** [comment]
Fixed by
* master (https://github.com/greenplum-db/gpdb/pull/12758)
* 6x (https://github.com/greenplum-db/gpdb/pull/12767)

**Comment by jiangdaokun** [comment]
I have encountered this problem. My current version is 6.17.2. I want to know which version fixes this bug

**Comment by kainwen** [comment]
> I have encountered this problem. My current version is 6.17.2. I want to know which version fixes this bug

Since 6.18.2.

To fix the issue, upgrading is not enough. You need to manually fix the catalog using the following steps:

1. confirm that you encounter the same issue
2. remove the extra entry in catalog on segments

**Comment by jiangdaokun** [comment]
Thanks for your reply

> 1. confirm that you encounter the same issue
yes；when I drop table, the error message:

org.jkiss.dbeaver.model.sql.DBSQLException: SQL 错误 [XX000]: ERROR: cache lookup failed for extension 19452 (objectaddress.c:2277)  (seg41 0.0.0.1:6001 pid=19917) (objectaddress.c:2277)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:133)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:510)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:441)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:169)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:428)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:813)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:3273)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:118)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:169)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:116)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:4577)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.postgresql.util.PSQLException: ERROR: cache lookup failed for extension 19452 (objectaddress.c:2277)  (seg41 0.0.0.1:6001 pid=19917) (objectaddress.c:2277)
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2553)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2285)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:323)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:481)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:401)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:322)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:308)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:284)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:279)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:330)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:130)


> 2. remove the extra entry in catalog on segments
How to do this? Is there any reference document；

**Comment by kainwen** [comment]
If the same issue, based on the error message :

```
cache lookup failed for extension 16415 (objectaddress.c:3570)  (seg1 127.0.1.1:7003 pid=16991) (objectaddress.c:3570)
```

We know the extension `16415` should not exist in `pg_depend`.

Run the SQL to fetch the information from segments:

```sql
select * from gp_dist_random('pg_depend') where  refobjid = 16415;
```

Then go to every segment using utility mode to delete this extra entry (can be done via script or tools). Then do a gpcheckcat (should be OK now), if everything is OK, drop table should be OK now.
