### ISSUE TITLE
RLE compression should support ZSTD as block compression underneath

### ISSUE THREAD

**Issue by ashwinstar** [greenplum-db/gpdb#12721]
## Feature Request

**Is your feature request related to a problem? Please describe:**
Currently, RLE for compress levels 2-4 uses zlib compression with various levels for block compression. Given zstd is better than zlib having the option to perform RLE+ZSTD would be helpful.

**Describe the feature you'd like to request:**
RLE compression type should provide more compression levels like maybe 5 which does RLE and then ZSTD with some optimal compresslevel of zstd used for it.

**Comment by soumyadeep2007** [comment]
> **Describe the feature you'd like to request:**
> RLE compression type should provide more compression levels like maybe 5 which does RLE and then ZSTD with some optimal compresslevel of zstd used for it.

Better in what sense?
I want to understand the ask better. Is it the fact that customers just want rle to do zstd, due to better runtime? Or do they want a compresslevel for RLE that will beat rle compresslevel=4 (zlib clevel=9) in terms of disk footprint?

If the latter is true, then compresslevel=5 makes sense. Otherwise if the former is true, it doesn't make sense because **ascending numbers of the compresslevel param should imply lesser disk space at the cost of higher CPU**. Then we are better off providing a GUC `gp_rle_compress_method = zlib (default) | zstd`.

**Comment by ashwinstar** [comment]
> I want to understand the ask better. Is it the fact that customers just want rle to do zstd, due to better runtime? Or do they want a compresslevel for RLE that will beat rle compresslevel=4 (zlib clevel=9) in terms of disk footprint?

Expectation is and hence the ask that it will help with both more for the runtime.

> providing a GUC gp_rle_compress_method = zlib (default) | zstd, based on which we can toggle between zstd and zlib at the existing compress levels for RLE.

The main aspect is the tables DDL information should be recorded in catalog as needs to be represented back during dump/restore or upgrades. If its based on GUC how do we store the knowledge at table level - as GUC can just flip one way or other. Hence compress level records the source of truth for the behavior in-place and required for future.

> it doesn't make sense because ascending numbers of the compresslevel param should imply lesser disk space at the cost of higher CPU.

I understand it doesn't fit the theme and current documentation. Though feel mostly with proper documentation updates can help Customers with the concept. If there is better alternative which helps to implement this on STABLE branch and ability to record the table DDL in catalog all for it to consider.

**Comment by soumyadeep2007** [comment]
> > I want to understand the ask better. Is it the fact that customers just want rle to do zstd, due to better runtime? Or do they want a compresslevel for RLE that will beat rle compresslevel=4 (zlib clevel=9) in terms of disk footprint?
> 
> Expectation is and hence the ask that it will help with both more for the runtime.

Well, seems like zstd level = 1 allegedly beats zlib level = 9 according to:
https://gregoryszorc.com/blog/2017/03/07/better-compression-with-zstandard/#:~:text=On%20one%20end%2C%20zstd%20level,that%20is%20only%202.3%25%20larger.
```
 On one end, zstd level 1 is ~3.4x faster than zlib level 1 while achieving better compression than zlib level 9!
```
Maybe we don't have to do that much explaining after all!

> The main aspect is the tables DDL information should be recorded in catalog as needs to be represented back during dump/restore or upgrades. If its based on GUC how do we store the knowledge at table level - as GUC can just flip one way or other. Hence compress level records the source of truth for the behavior in-place and required for future.

You keep telling me this aspect and I keep forgetting! :D #amnesia

> I understand it doesn't fit the theme and current documentation. Though feel mostly with proper documentation updates can help Customers with the concept. If there is better alternative which helps to implement this on STABLE branch and ability to record the table DDL in catalog all for it to consider.

Yeah nothing straightforward can really be done for a stable branch. Perhaps we could make `gp_rle_compress_method` an attoption, but there are many complications there we don't want to deal with.

**Comment by soumyadeep2007** [comment]
Addressed with https://github.com/greenplum-db/gpdb/pull/17184 and https://github.com/greenplum-db/gpdb/pull/17147
