### ISSUE TITLE
Wrong result of bugbuster cursor case

### ISSUE THREAD

**Issue by pengzhout** [greenplum-db/gpdb#1276]
Repo steps: (has a fail rate, please try several times)

```
set GP_ENABLE_SLOW_CURSOR_TESTMODE=ON;
drop table if exists y_schema.y;
drop schema if exists y_schema;

create schema y_schema;
create table y_schema.y (a int, b int) distributed by (a);
Begin;
insert into y_schema.y values(10, 666);
declare c0 cursor for select * from y_schema.y where b =666 order by 1;
savepoint x;
update y_schema.y set b =333 where b =666;
fetch c0;
select * from y_schema.y where b =666 order by 1;
end;
```

Results:

```
gpadmin=# set GP_ENABLE_SLOW_CURSOR_TESTMODE=ON;
SET
gpadmin=# drop table if exists y_schema.y;
DROP TABLE
gpadmin=# drop schema if exists y_schema;
DROP SCHEMA
gpadmin=# --end_ignore
gpadmin=#
gpadmin=# create schema y_schema;
CREATE SCHEMA
gpadmin=# create table y_schema.y (a int, b int) distributed by (a);
CREATE TABLE
gpadmin=# Begin;
BEGIN
gpadmin=# insert into y_schema.y values(10, 666);
INSERT 0 1
gpadmin=# --order 1
gpadmin=# declare c0 cursor for select * from y_schema.y where b =666 order by 1;
DECLARE CURSOR
gpadmin=# savepoint x;
SAVEPOINT
gpadmin=# update y_schema.y set b =333 where b =666;
UPDATE 1
gpadmin=# fetch c0;
 a  |  b
----+-----
 10 | 666
(1 row)

gpadmin=# select * from y_schema.y where b =666 order by 1;
 a  |  b
----+-----
 10 | 666  <=========================================== here is supposed to be zero
(1 row)
```

As we investigated, this bug was introduced by a453004ea1946b5c141bd26ac871ac6edde64f37, snippet in src/backend/utils/time/tqual.c might be the core
```
            if (!TransactionIdIsCurrentTransactionId(HeapTupleHeaderGetXmax(tuple)))
            {
                /* deleting subtransaction must have aborted */
                SetHintBits(tuple, buffer, relation, HEAP_XMAX_INVALID,
                            InvalidTransactionId);
                return true;
            }
```

The possible root cause:

line `update y_schema.y set b =333 where b =666` in the sub transaction updated tuple before cursor QE. while cursor reading that tuple to check if it satisfies MVCC, it saw that tuple was created by current transaction but updated by the transaction `savepoint x`, then it checked if the other transaction was itself or its sub transaction , due to the current mechanism of GPDB reader QE cursor snapshot, cursor QE could not find transaction id of `savepoint x` in its sub transaction buffer which was inited at the same time as when cursor was declared, `src/backend/access/transam/xact.c: isCurrentTransactionId = FindXidInXidBuffer(&subxbuf, xid, &cnt, &index);`, so cursor masks xmax of the tuple invalid . Then `select * from y_schema.y where b =666 order by 1` could see the tuple due to its cmax marked as invalid.

@hlinnaka @ashwinstar @asimrp Could you please take a look?

**Comment by hlinnaka** [comment]
On 11/03/2016 10:45 AM, Tang Pengzhou wrote:
> ```
>
> As we investigated, this bug was introduced by a453004ea1946b5c141bd26ac871ac6edde64f37, snippet in src/backend/utils/time/tqual.c might be the core
> ```
>             if (!TransactionIdIsCurrentTransactionId(HeapTupleHeaderGetXmax(tuple)))
>             {
>                 /* deleting subtransaction must have aborted */
>                 SetHintBits(tuple, buffer, relation, HEAP_XMAX_INVALID,
>                             InvalidTransactionId);
>                 return true;
>             }
> ```
>
> The possible root cause:
>
> line `update y_schema.y set b =333 where b =666` in the sub
> transaction updated tuple before cursor QE. while cursor reading that
> tuple to check if it satisfies MVCC, it saw that tuple was created by
> current transaction but updated by the transaction `savepoint x`,
> then it checked if the other transaction was itself or its sub
> transaction , due to the current mechanism of GPDB reader QE cursor
> snapshot, cursor QE could not find transaction id of `savepoint x` in
> its sub transaction buffer which was inited at the same time as when
> cursor was declared, `src/backend/access/transam/xact.c:
> isCurrentTransactionId = FindXidInXidBuffer(&subxbuf, xid, &cnt,
> &index);`, so cursor masks xmax of the tuple invalid . Then `select *
> from y_schema.y where b =666 order by 1` could see the tuple due to
> its cmax marked as invalid.

Hmm, so the problem is that in a QE reader process, 
TransactionIdIsCurrentTransactionId() returns false, for a sub-XID that 
is in fact part of the current top-level transaction. I think we need to 
add some more code into TransactionIdCurrentTransactionId() to check for 
that case. Perhaps have it check the PGPROC->subxid cache of the 
"parent" process (is that the right term), and if the cache is 
overflowed, call SubTransGetTopmostTransaction().

- Heikki

**Comment by pengzhout** [comment]
@hlinnaka you are right, we need to enhance the TransactionIdCurrentTransactionId(), but GPDB seems to use tmp files to share snapshot include sub-transactions  between QE writer and QE cursor reader.  We have no strong background on this area, is catalog and storage team the right team to take this issue? @ryantang @Eulerizeit thanks.

**Comment by ashwinstar** [comment]
Yes we will take care of this.

- AshwinA

On Nov 3, 2016, at 7:10 PM, Tang Pengzhou <notifications@github.com> wrote:

@hlinnaka <https://github.com/hlinnaka> you are right, we need to enhance
the TransactionIdCurrentTransactionId(), but GPDB seems to use tmp files to
share snapshot include sub-transactions between QE writer and QE cursor
reader. We have no strong background on this area, is catalog and storage
team the right team to take this issue? @ryantang
<https://github.com/ryantang> @Eulerizeit <https://github.com/Eulerizeit>
thanks.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/greenplum-db/gpdb/issues/1276#issuecomment-258327653>,
or mute the thread

**Comment by pengzhout** [comment]
@ashwinstar thanks a lot.
