### ISSUE TITLE
Issue with Materialize over Bitmap Index Scan

### ISSUE THREAD

**Issue by InnerLife0** [greenplum-db/gpdb#12796]
6X_STABLE, ORCA
Excess target list for Materialize over Bitmap Index Scan causing differences in memory tuple bindings, which leads to incorrect query results or out of bounds memory access.
__________

Few months ago I've [reported](https://github.com/greenplum-db/gpdb/pull/11963) about an issue with projection of Materialize node. There was a [fix](https://github.com/greenplum-db/gpdb/pull/12176), introduced and merged by GPDB team. The fix seems right, but it revealed a new bug.
```sql
drop table material_bitmapscan;
create table material_bitmapscan(i int, j int, k timestamp) with(appendonly=true) distributed replicated;
create index material_bitmapscan_idx on material_bitmapscan using btree(k);
insert into material_bitmapscan
select i, mod(i, 10), timestamp '2021-06-01' + interval '1' day * mod(i, 30)
from generate_series(1, 10000) i;

explain verbose with mat as(
    select i, j from material_bitmapscan where i = 2 and j = 2 and k = timestamp '2021-06-03'
) 
select m1.i
from mat m1 join mat m2 on m1.j = m2.j;

                                                        QUERY PLAN                                                        
--------------------------------------------------------------------------------------------------------------------------
 Gather Motion 1:1  (slice1; segments: 1)  (cost=0.00..1252.18 rows=1 width=4)
   Output: share0_ref3.i
   ->  Sequence  (cost=0.00..1252.18 rows=1 width=4)
         Output: share0_ref3.i
         ->  Shared Scan (share slice:id 1:0)  (cost=0.00..390.18 rows=1 width=1)
               Output: share0_ref1.i, share0_ref1.j
               ->  Materialize  (cost=0.00..390.18 rows=1 width=1)
                     Output: material_bitmapscan.i, material_bitmapscan.j, material_bitmapscan.k
                     ->  Bitmap Heap Scan on public.material_bitmapscan  (cost=0.00..390.18 rows=1 width=8)
                           Output: material_bitmapscan.i, material_bitmapscan.j, material_bitmapscan.k
                           Recheck Cond: (material_bitmapscan.k = '2021-06-03 00:00:00'::timestamp without time zone)
                           Filter: ((material_bitmapscan.i = 2) AND (material_bitmapscan.j = 2))
                           ->  Bitmap Index Scan on material_bitmapscan_idx  (cost=0.00..0.00 rows=0 width=0)
                                 Index Cond: (material_bitmapscan.k = '2021-06-03 00:00:00'::timestamp without time zone)
         ->  Hash Join  (cost=0.00..862.00 rows=1 width=4)
               Output: share0_ref3.i
               Hash Cond: (share0_ref3.j = share0_ref2.j)
               ->  Result  (cost=0.00..431.00 rows=1 width=8)
                     Output: share0_ref3.i, share0_ref3.j
                     Filter: (share0_ref3.j = 2)
                     ->  Shared Scan (share slice:id 1:0)  (cost=0.00..431.00 rows=1 width=8)
                           Output: share0_ref3.i, share0_ref3.j
               ->  Hash  (cost=431.00..431.00 rows=1 width=4)
                     Output: share0_ref2.j
                     ->  Result  (cost=0.00..431.00 rows=1 width=4)
                           Output: share0_ref2.j
                           Filter: (share0_ref2.j = 2)
                           ->  Shared Scan (share slice:id 1:0)  (cost=0.00..431.00 rows=1 width=4)
                                 Output: share0_ref2.i, share0_ref2.j
 Optimizer: Pivotal Optimizer (GPORCA)
 Settings: optimizer=on
(31 rows)
```
Look at the `Output` of `Bitmap Heap Scan`. It contains probably redundant `material_bitmapscan.k`, which then materialized, which then causing query to return 0 rows (see the reason below). Ordinary, query should return one row - disabling of bitmap scan can prove this `set optimizer_enable_bitmapscan=off;`.

The reason is in differences between memory tuple bindings, which [created](https://github.com/greenplum-db/gpdb/blob/1242aadf0137d3b26ee42c80e579e78bd7a805c7/src/backend/executor/execTuples.c#L307) based on target list. The target list used by `Shared Scan` contains 2 attributes. The target list materialized inside CTE contains 3 attributes. When filling binding map, the attribute with timestamp type [placed](https://github.com/greenplum-db/gpdb/blob/1242aadf0137d3b26ee42c80e579e78bd7a805c7/src/backend/access/common/memtuple.c#L225) first, so accessing([1](https://github.com/greenplum-db/gpdb/blob/1242aadf0137d3b26ee42c80e579e78bd7a805c7/src/backend/executor/nodeResult.c#L104), [2](src/backend/executor/execQual.c)) memory tuple using offsets from another binding (with 2 attributes) leads to reading some garbage values. [Filtering](https://github.com/greenplum-db/gpdb/blob/1242aadf0137d3b26ee42c80e579e78bd7a805c7/src/backend/executor/execQual.c#L2135) using such values leads to undefined behavior (missed row in our case).

Here is some proof from the production environment.
```
#2  0x00005613bc37f195 in NextInputSlot (node=<optimized out>) at nodeResult.c:104
104			bool passesFilter = !qual || ExecQual(qual, econtext, false);
(gdb) p *(uint16 *)((char *)candidateInputSlot->PRIVATE_tts_memtuple + candidateInputSlot->tts_mt_bind->bind.bindings[0].offset)
$11 = 37888
```
`37888` is obviously pretty high offset, and so, this caused another type of error for us: `Cannot access memory at address xxx`.

The temporary workaround is to explicitly add `material_bitmapscan.k` to target list by rewriting a query like so:
```
explain verbose with mat as(
    select i, j, k from material_bitmapscan where i = 2 and j = 2 and k = timestamp '2021-06-03'
) 
...
```
Now I'm searching for a right solution. For simple test, I've decided to simply comment out this [line](https://github.com/greenplum-db/gpdb/blob/1242aadf0137d3b26ee42c80e579e78bd7a805c7/src/backend/gporca/libgpopt/src/translate/CTranslatorExprToDXL.cpp#L973). It works, but it's probably ugly - I still interesting why we need to add recheck column to output list.

I'm ready to create a PR with additional regression tests, but want to hear team's opinion about the bug and solution.
Thank you.

**Comment by InnerLife0** [comment]
Digging deeper I see the [commit](https://github.com/arenadata/gpdb/commit/97edf9b1cbd47c33918e5780e04ea241b59a2f46) which introduced the addition of Recheck and Filter condition's columns to Output list.
I was able to compile gpos, pgorca and gpdb to check if test was relevant and worked on old version of gporca. It's interesting to know, that `pcrsOutput` really didn't contain all necessary columns 5 years ago. But my question is why this problem was solved from this side? It's true, I don't see the whole picture, so I want to ask @vraghavan78. I know it was ages ago, but could you kindly try to help us and remember the reason of such solution?
This time I testing the solution, which removes `AddBitmapFilterColumns` as Output list already contains all necessary columns. Additionally, I want to add parent and child plans targetlist comparison into `TranslateDXLCTEProducerToSharedScan`, to not shoot into our leg so painfully in the future.

**Comment by khannaekta** [comment]
@InnerLife0 Thanks for reporting.
On digging a bit into why ORCA introduced the addition of Recheck and Filter condition's columns to Output list, the reason is that the executor code back then was handled via gpdb specific node `BITMAPTABLESCAN` instead of `BITMAPHEAPSCAN` exec node.
Prior to the [commit](https://github.com/greenplum-db/gpdb/commit/97edf9b1cbd47c33918e5780e04ea241b59a2f46) for AOCO tables, the tuple slot returned to BITMAPTABLESCAN by the BitmapIndexScan(under it) had only the output attribute required, but actually it needed more attributes to evaluate the recheck condition, which would result in passing uninitialized field(for the recheck/filter condition attributes) in the TupleTableSlot to the expression evaluator, and that would lead to crash/incorrect results. That is why this commit, fixed it by projecting the recheck/scalar condition aswell.

With the refactoring of executor code for GPDB6 as part of [commit](https://github.com/greenplum-db/gpdb/commit/db5163474d2deea03e482ed34c2e68ea96c8b88a), `BITMAPTABLESCAN` was replaced by `BITMAPHEAPSCAN` altogether which no longer needs projecting the recheck/scalar condition attributes(similar to planner). So your proposed solution of removing `AddBitmapFilterColumns` from the output list, seems the path forward.
I am working on a PR for the same.

**Comment by InnerLife0** [comment]
@khannaekta Thanks for answer.
Can you take a look at our repo [PR](https://github.com/arenadata/gpdb/pull/284)? It contains extended regression test, all fixes to mdp files and existing plans, and additional check condition. I will move it to greenplum-db repo it's ok.

**Comment by khannaekta** [comment]
Fixed as part of commit: https://github.com/greenplum-db/gpdb/pull/12976/commits/45fe0edd750700207172642f39767eb29dd76556
