### ISSUE TITLE
elog info of ExecModifyTable function is not suitable

### ISSUE THREAD

**Issue by wangxuqi** [greenplum-db/gpdb#12808]
##  Greenplum version or build -- master 
GPDB-specific junk attributes elog info is not correct.
For now elog info of segid_attno attribute is  "action is NULL"
and elog info of action_attno attribute is  "gp_segment_id is NULL"
The elog info may need to exhange.  segid_attno -> "gp_segment_id is NULL" and action_attno -> "action is NULL"
```
				/*
				 * Extract GPDB-specific junk attributes.
				 */
				if (AttributeNumberIsValid(segid_attno))
				{
					datum = ExecGetJunkAttribute(slot,
												 segid_attno,
												 &isNull);
					/* shouldn't ever get a null result... */
					if (isNull)
						elog(ERROR, "action is NULL");

					segid = DatumGetInt32(datum);
				}
				if (AttributeNumberIsValid(action_attno))
				{
					datum = ExecGetJunkAttribute(slot,
												 action_attno,
												 &isNull);
					/* shouldn't ever get a null result... */
					if (isNull)
						elog(ERROR, "gp_segment_id is NULL");

					action = DatumGetInt32(datum);
				}
```

**Comment by kainwen** [comment]
@wangxuqi Good catch! Would you please open a PR to fix this? Thanks!

**Comment by wangxuqi** [comment]
> @wangxuqi Good catch! Would you please open a PR to fix this? Thanks!

see https://github.com/greenplum-db/gpdb/pull/12815
