### ISSUE TITLE
Different plans for UNION queries between different compilers. Unspecified behavior for regression tests.

### ISSUE THREAD

**Issue by InnerLife0** [greenplum-db/gpdb#12809]
6X_STABLE
One of regression tests added recently in this [commit](https://github.com/arenadata/gpdb/commit/65beb84d7919cd3b6fdf577f0448dba36000f5c9) can provide different results on different platforms or even different compiler versions on the same platform(?).
```
-- case 6 without CTE, nested subquery
explain (costs off) select * from (
	select dt from (
		select
		(
			select c from extra_flow_dist where b = x
		) dt
		from (select ( max(1) ) x) a
		union
		select
		(
			select c from extra_flow_dist where b = x
		) dt
		from (select ( max(1) ) x) aa
	) tbl
) run_dt,
extra_flow_dist1
where dt < '2010-01-01'::date;
```
C can't specify [evaluation order](https://en.cppreference.com/w/c/language/eval_order) of two `recurse_union_children()` calls at [this](https://github.com/greenplum-db/gpdb/blob/1d06421cd53121b8f52476961c97b14dea99bba6/src/backend/optimizer/prep/prepunion.c#L536) line. The target output of query above [assumes](https://github.com/arenadata/gpdb/commit/65beb84d7919cd3b6fdf577f0448dba36000f5c9#diff-e628cc11984af10095102c9b9098b2dd25556f8baee9618dd9e5b00140298a86R2488) second call to `recurse_union_children()` executed first. On the machine with another architecture (and compiler version of course) we've got first `recurse_union_children()` executed first.
Regression diffs looks like:
```
--- \/home\/gpadmin\/gpdb_src\/src\/test\/regress\/expected\/subselect_gp\.out	2021-10-26 06:28:45.873541028 +0000
+++ \/home\/gpadmin\/gpdb_src\/src\/test\/regress\/results\/subselect_gp\.out	2021-10-26 06:28:46.165531859 +0000
@@ -4669,28 +4673,28 @@
          ->  Subquery Scan on tbl
                Filter: (tbl.dt < '01-01-2010'::date)
                ->  Unique
-                     Group Key: ((SubPlan 2))
+                     Group Key: ((SubPlan 1))
                      ->  Sort
-                           Sort Key (Distinct): ((SubPlan 2))
+                           Sort Key (Distinct): ((SubPlan 1))
                            ->  Append
                                  ->  Subquery Scan on a
                                        ->  Aggregate
                                              ->  Result
-                                       SubPlan 2  (slice3; segments: 3)
+                                       SubPlan 1  (slice3; segments: 3)
                                          ->  Result
-                                               Filter: (extra_flow_dist_1.b = a.x)
+                                               Filter: (extra_flow_dist.b = a.x)
                                                ->  Materialize
                                                      ->  Broadcast Motion 3:3  (slice1; segments: 3)
-                                                           ->  Seq Scan on extra_flow_dist extra_flow_dist_1
+                                                           ->  Seq Scan on extra_flow_dist
                                  ->  Subquery Scan on aa
                                        ->  Aggregate
                                              ->  Result
-                                       SubPlan 1  (slice3; segments: 3)
+                                       SubPlan 2  (slice3; segments: 3)
                                          ->  Result
-                                               Filter: (extra_flow_dist.b = aa.x)
+                                               Filter: (extra_flow_dist_1.b = aa.x)
                                                ->  Materialize
                                                      ->  Broadcast Motion 3:3  (slice2; segments: 3)
-                                                           ->  Seq Scan on extra_flow_dist
+                                                           ->  Seq Scan on extra_flow_dist extra_flow_dist_1
          ->  Seq Scan on extra_flow_dist1
 GP_IGNORE:(29 rows)
```
The fact evaluation order is unspecified in general means incorrectness of such plans comparison. How can we fix query/explain processing to avoid dealing with unspecified behavior?

**Comment by kainwen** [comment]
Thanks for your report. @InnerLife0 

I do not think this issue is a real bug. It is the SubPlan Id printed in the plan that is not stable that might make the test flaky.

I search that if the execution order of children of UnionAll is defined, but do not find anything.

----------

> The fact evaluation order is unspecified in general means incorrectness of such plans comparison. How can we fix query/explain processing to avoid dealing with unspecified behavior?

The easiest fix method from my perspective is just to add an  alternative answer file, Greenplum's regress test already support this, see the answer file for case `isolation2/fts_error`

**Comment by InnerLife0** [comment]
> I do not think this issue is a real bug. It is the SubPlan Id printed in the plan that is not stable that might make the test flaky.

Probably, yes, it's not a bug cause nothing breaks and both plans are valid, but it's incorrect to deal with unspecified behavior here, imo. Besides SubPlan ID there is an `extra_flow_dist_1` alias which makes impossible to use another approach with removed `(costs off)` clause.

> The easiest fix method from my perspective is just to add an alternative answer file, Greenplum's regress test already support this, see the answer file for case `isolation2/fts_error`

That's an option. The only thing that worries me is the amount of copypaste. Should we move this test to a separate file? Is GPDB team even interested in such PR or its benefits are not actual?

**Comment by dpandhi-git** [comment]
We do not sees this issues in our CI. As we don't have clear reproduction we decided not to fix it
