### ISSUE TITLE
[Doc] Wiki How to build on OSX miss

### ISSUE THREAD

**Issue by darionyaphet** [greenplum-db/gpdb#12850]
## Bug Report

Hello experts:

When I read the wiki at [Contributor Guide](https://github.com/greenplum-db/gpdb/wiki/Contributor-Guide#build) and want to build source code from Mac OS. I found the link `How to build on OSX` is missing. thanks ~

**Comment by higuoxing** [comment]
Hi, thanks for reporting. We will work on adding the guide later. You're able to find the guide here https://github.com/greenplum-db/gpdb/blob/master/README.macOS.md

**Comment by darionyaphet** [comment]
ok it is useful  & thanks
