### ISSUE TITLE
GPDB6 print out "provided user name (xxx) and authenticated user name (gpadmin) do not match" log when access external table

### ISSUE THREAD

**Issue by violet2016** [greenplum-db/gpdb#12851]
### Greenplum version or build
6.17.5+dev.1.g89abca9 build commit:89abca9000fe3f32862d94276d54b5947fd8b80a
### OS version and uname -a
ubuntu 18.04
Linux gpcc-main 5.10.16.3-microsoft-standard-WSL2
### Installation information ( pg_config )
BINDIR = /home/gpadmin/usr/local/gpdb_default/bin
DOCDIR = /home/gpadmin/usr/local/gpdb_default/share/doc/postgresql
HTMLDIR = /home/gpadmin/usr/local/gpdb_default/share/doc/postgresql
INCLUDEDIR = /home/gpadmin/usr/local/gpdb_default/include
PKGINCLUDEDIR = /home/gpadmin/usr/local/gpdb_default/include/postgresql
INCLUDEDIR-SERVER = /home/gpadmin/usr/local/gpdb_default/include/postgresql/server
LIBDIR = /home/gpadmin/usr/local/gpdb_default/lib
PKGLIBDIR = /home/gpadmin/usr/local/gpdb_default/lib/postgresql
LOCALEDIR = /home/gpadmin/usr/local/gpdb_default/share/locale
MANDIR = /home/gpadmin/usr/local/gpdb_default/man
SHAREDIR = /home/gpadmin/usr/local/gpdb_default/share/postgresql
SYSCONFDIR = /home/gpadmin/usr/local/gpdb_default/etc/postgresql
PGXS = /home/gpadmin/usr/local/gpdb_default/lib/postgresql/pgxs/src/makefiles/pgxs.mk
CONFIGURE = '--with-quicklz' '--enable-gpperfmon' '--with-gssapi' '--enable-mapreduce' '--enable-orafce' '--enable-ic-proxy' '--enable-orca' '--with-libxml' '--with-pgport=5432' '--enable-tap-tests' '--enable-debug-extensions' '--with-perl' '--with-python' '--with-openssl' '--with-pam' '--with-ldap' '--with-includes=' '--with-libraries=' '--disable-rpath' 'LDFLAGS=-Wl,--enable-new-dtags -Wl,-rpath,$ORIGIN/../lib' '--prefix=/usr/local/greenplum-db-devel' '--mandir=/usr/local/greenplum-db-devel/man' 'CC=gcc -m64' 'CFLAGS=-m64 -O3 -fargument-noalias-global -fno-omit-frame-pointer -g'
CC = gcc -m64
CPPFLAGS = -D_GNU_SOURCE -I/usr/include/libxml2 -I/home/gpadmin/usr/local/gpdb_default/include
CFLAGS = -Wall -Wmissing-prototypes -Wpointer-arith -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fno-aggressive-loop-optimizations -Wno-unused-but-set-variable -Wno-address -m64 -O3 -fargument-noalias-global -fno-omit-frame-pointer -g -std=gnu99 -Werror=uninitialized -Werror=implicit-function-declaration -I/home/gpadmin/usr/local/gpdb_default/include
CFLAGS_SL = -fPIC
LDFLAGS = -Wl,--enable-new-dtags -Wl,-rpath,$ORIGIN/../lib -Wl,--as-needed -L/home/gpadmin/usr/local/gpdb_default/lib
LDFLAGS_EX =
LDFLAGS_SL =
LIBS = -lpgcommon -lpgport -lxerces-c -lxml2 -lpam -lrt -lyaml -lgssapi_krb5 -luv -lquicklz -lzstd -lrt -lcrypt -ldl -lm -L/home/gpadmin/usr/local/gpdb_default/lib
VERSION = PostgreSQL 9.4.24

### Expected behavior
Do not print out the log message
### Step to reproduce the behavior
0. create an empty file /tmp/gpdblog.csv, and copy the following content to it.
```
2021-11-22 06:48:35.470683 UTC,"gpadmin","template1",p28200,th252745856,"127.0.0.1","26299",2021-11-22 06:48:35 UTC,0,con7,,seg-1,,dx3,,sx1,"PANIC","00000","The previous session was reset because its gang was disconnected (session id = 6). The new session id = 7",,,,,,,0,,"cdbgang.c",742,
```
1. create 2 external tables using following sqls in test_db database:
```
CREATE TABLE test_history (
      logtime          TIMESTAMP WITHOUT TIME ZONE
    , loguser          TEXT
    , logdatabase      TEXT
    , logpid           TEXT
    , logthread        TEXT
    , loghost          TEXT
    , logport          TEXT
    , logsessiontime   TIMESTAMP WITHOUT TIME ZONE
    , logtransaction   INTEGER
    , logsession       TEXT
    , logcmdcount      TEXT
    , logsegment       TEXT
    , logslice         TEXT
    , logdistxact      TEXT
    , loglocalxact     TEXT
    , logsubxact       TEXT
    , logseverity      TEXT
    , logstate         TEXT
    , logmessage       TEXT
    , logdetail        TEXT
    , loghint          TEXT
    , logquery         TEXT
    , logquerypos      INTEGER
    , logcontext       TEXT
    , logdebug         TEXT
    , logcursorpos     INTEGER
    , logfunction      TEXT
    , logfile          TEXT
    , logline          INTEGER
    , logstack         TEXT
)
WITH (
	  APPENDONLY=true
	, ORIENTATION=column
	, COMPRESSTYPE=RLE_TYPE
	, COMPRESSLEVEL=2
)
DISTRIBUTED BY (logtime);

CREATE EXTERNAL WEB TABLE test_external (
LIKE test_history)
EXECUTE 'cat /tmp/gpdblog.csv'
ON MASTER
FORMAT 'csv' (delimiter E',' null E'' escape E'"' quote E'"')
ENCODING 'UTF8'
SEGMENT REJECT LIMIT 100 PERCENT;
```
2. make sure system user is gpadmin, create a gpdb user, for example test_user, and login with psql -U test_user test_db
3. run "INSERT INTO test_history SELECT * FROM test_external WHERE logseverity IN ('WARNING', 'ERROR', 'FATAL', 'PANIC');"
4. open gpdb log, you can see an INFO log "provided user name (test_user) and authenticated user name (gpadmin) do not match",,,,,,,0,,"hba.c",2089, in log file.

**Comment by adam8157** [comment]
Added this into pg_hba.conf
```
host     all         test_user       trust
```

and did this to get the privilege of running the insert query
```
create role test_user login;
GRANT ALL PRIVILEGES ON TABLE test_history TO test_user;
GRANT ALL PRIVILEGES ON TABLE test_external TO test_user;
```

Not reproduced, what have I missed?

**Comment by adam8157** [comment]
I tried creating the role as a super, also not reproduced.

**Comment by adam8157** [comment]
In `cdbconn_doConnectStart()`:
```
	/*
	 * For entry DB connection, we make sure both "hostaddr" and "host" are
	 * empty string. Or else, it will fall back to environment variables and
	 * won't use domain socket in function connectDBStart.
	 *
	 * For other QE connections, we set "hostaddr". "host" is not used.
	 */
	if (segdbDesc->segindex == MASTER_CONTENT_ID &&
		IS_QUERY_DISPATCHER())
	{
		keywords[nkeywords] = "hostaddr";
		values[nkeywords] = "";
		nkeywords++;
	}
	else
	{
		Assert(cdbinfo->config->hostip != NULL);
		keywords[nkeywords] = "hostaddr";
		values[nkeywords] = cdbinfo->config->hostip;
		nkeywords++;
	}

	keywords[nkeywords] = "host";
	values[nkeywords] = "";
	nkeywords++;
```

Then in `connectDBStart()`:
```
#ifdef HAVE_UNIX_SOCKETS
		/* pghostaddr and pghost are NULL, so use Unix domain socket */
		node = NULL;
		hint.ai_family = AF_UNIX;
		UNIXSOCK_PATH(portstr, portnum, conn->pgunixsocket);
		if (strlen(portstr) >= UNIXSOCK_PATH_BUFLEN)
		{
			appendPQExpBuffer(&conn->errorMessage,
							  libpq_gettext("Unix-domain socket path \"%s\" is too long (maximum %d bytes)\n"),
							  portstr,
							  (int) (UNIXSOCK_PATH_BUFLEN - 1));
			conn->options_valid = false;
			goto connect_errReturn;
		}
```

Then in `internal_client_authentication()`:
```
		/* 
		 * The entry-DB (or QE at the master) case.
		 *
		 * The goal here is to block network connection from out of
		 * master to master db with magic bit packet.
		 * So, only when it comes from the same host, the connection
		 * is authenticated, if this connection is TCP/UDP. We
		 * don't assume the connection is via unix domain socket,
		 * but if it comes, just authenticate it. We'll need to
		 * verify user on UDS case, but for now we don't do too much
		 * for the goal described above.
		 */
...
		else if (port->raddr.addr.ss_family == AF_UNIX)
		{
			if (!auth_peer(port))    <----- the warning happens here
```
