### ISSUE TITLE
gpdb codegen question

### ISSUE THREAD

**Issue by wjzeng** [greenplum-db/gpdb#1285]
1 Why gpdb codegen is not based on llvm-c API development?
2 Can you share codegen's todo list?

**Comment by hardikar** [comment]
I can answer question 1. This decision was made to maximize the benefits we can get from the C++ features:

1. LLVM and Clang are both implemented in C++. It's C interface is effectively a wrapper around the C++ implementation. Practically this means the C interface is less expressive than the C++ API. Compare the functions available the C API and C++ API of the fundamental IR Builder.
2. Using C++ would give us access to a number of LLVM defined data structures and classes. Employing those gives us greater control when generating LLVM IR and to create development-friendly utilities. An example here is the implementation of EXPLAIN CODEGEN in GPDB. (https://github.com/greenplum-db/gpdb/blob/master/src/backend/codegen/codegen_manager.cc#L114)
3. LLVM IR is a typed language and the type conversion between C/C++ types to LLVM can quickly become cumbersome and error prone. Using C++ template meta-programming, we can address this issue very cleanly.  See below for an example.
4. Similar to 3, Using C++ template type inference also helps us out when referencing external global variables or external functions. The types of the external global variable and function is automatically inferred (at GPDB compile time) and then converted to it's equivalent LLVM types in a simple, single C++ statement. For example :
    ```
    // extern int foo (int);
    codegen_utils->ir_builder()->RegisterExternalFunction(foo);
    ```

Example for Point 3:

```c++
// If we want to create a function with signature :
// void simple_func_llvm_ir_module(int64_t* input_array, int64_t* output_array);
// Step 1a : Get return type

llvm::Type* ret_type = llvm::Type::getVoidTy(*context);


// Step 1b : Get types of all arguments
std::vector<llvm::Type*> argument_types;
llvm::Type* arg1_int_ptr = llvm::Type::getInt64Ty(*context)->getPointerTo();
argument_types.emplace_back(arg1_int_ptr);


llvm::Type* arg2_int_ptr = llvm::Type::getInt64Ty(*context)->getPointerTo();
argument_types.emplace_back(arg2_int_ptr);


// Step 1c : Get FunctionType from return and argument types.
llvm::FunctionType* func_type = llvm::FunctionType::get(ret_type, argument_types, false);


// Step 1d : Create the function.
llvm::Function* simple_func_ir_module =
  llvm::Function::Create(func_type, llvm::GlobalValue::ExternalLinkage,
    "simple_func_llvm_ir_module", module);


// Using C++ meta-programming, this is simplified as:

typedef void (*FuncTy) (int64_t* input_array, int64_t* output_array);

llvm::Function* simple_func_ir_module = codegen_utils->CreateFunction<FuncTy>(
    "simple_func_llvm_ir_module", module);
```

**Comment by vraghavan78** [comment]
Thanks @hardikar 

Some of the items in our immediate todos:
1. We are wrapping up TPC-H Q1. We only have "average" left.
2. Instantiate PGGenericFuncGenerator for all simple int8 and int4 operators 
3. Investigate how we can auto-generate code for catalog functions based on understanding current approaches and our initial idea. 
4. Improve debug-ability of our codegen.
5. Support operation on partitioned tables (Dynamic Partition Scan operator used by Orca)
6. Support Memtuples.

Please let us know if there is anything else we can address.

**Comment by wjzeng** [comment]
Thank you very much for your answer
