### ISSUE TITLE
`gpload` v6.x update rows incorrectly if `GPLOAD.OUTPUT.MATCH_COLUMNS` contains columns with `NULL` value

### ISSUE THREAD

**Issue by CC-Hsu** [greenplum-db/gpdb#12887]
## Bug Report
GPDB v6.x
### Greenplum version or build
GPDB v6.x
### OS version and uname -a
CentOS 7.x
### autoconf options used ( config.status --config )
Packaged RPM

### Actual behavior
When `GPLOAD.OUTPUT.MATCH_COLUMNS` list contains null-able columns, updated rows might miss some rows.

I read the `gpload.py` code and find that this might be caused by using `=` for matching column conditions.
https://github.com/greenplum-db/gpdb/blob/6.18.2/gpMgmt/bin/gpload.py#L2860
https://github.com/greenplum-db/gpdb/blob/master/gpMgmt/bin/gpload.py#L2859

Maybe this should be changed to use [`IS NOT DISTINCT FROM`](https://www.postgresql.org/docs/9.4/functions-comparison.html) rather than `=` for matching condition.

**Comment by xiaoxiaoHe-E** [comment]
Hi, after discussion, we think null equals null doesn't make sense.  So we are not going to change the behavior. I'm closing this issue.
