### ISSUE TITLE
[6X] The Postgress processes on segment servers have strange priority and nice values.

### ISSUE THREAD

**Issue by jnf009** [greenplum-db/gpdb#12891]
### Greenplum version or build
gpdb5.x 
or
gpdb6.x

### OS version and uname -a
CentOS Linux release 7.8.2003 (Core)
Linux gp-data01 3.10.0-1127.13.1.el7.x86_64 #1 SMP Tue Jun 23 15:46:38 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

### Expected behavior

希望postgres进程和普通linux进程一样，PR=20   NI=0

Translated: The Postgres processes should have the same priority and nice values as other Linux processes: PR=20, NI=0.

### Actual behavior
gpdb5.x和gpdb6.x的Segment节点fork出来的postgres进程默认PR=39   NI=19，这样就导致CPU的NI占比很高，
也推高了load average
而普通的其他应用进程默认都是PR=20   NI=0

Translated: The priority of the Postgres processes on segments are PR=39, NI=19 (gpdb-6x and gpdb-5x), which results in higher "load average". The priority of normal processes are PR=20, NI=0.

### Step to reproduce the behavior
安装好gpdb5.x 或者gpdb6.x，在Segment节点通过linux的top命令观察就可以看到，Master节点时没有这个问题

Translated: Install gpdb-6x or gpdb-5x, inspect the processes' priority with 'top' command on segment servers.

![gp](https://user-images.githubusercontent.com/68093634/144354854-a5403ed4-3c2d-434b-9a29-d7f0b45a3afb.png)

**Comment by higuoxing** [comment]
Hi, I found some document related to your issue. Does that work for you?

https://community.pivotal.io/s/article/Queries-Running-with-Lower-Priority-on-the-Segments-when-compared-to-Mastergpsegworkerrelativepriority?language=en_US

**Comment by lij55** [comment]
> gpdb5.x和gpdb6.x的Segment节点fork出来的postgres进程默认PR=39 NI=19，这样就导致CPU的NI占比很高，
也推高了load average

Load average 是不是应该是统计的所有进程的资源使用情况，无论nice值多少。即使进程nice为0，work load总数是一样的。对应你的例子，如果postgres进程的nice值为0，那么ni为0，但us就变成62.7了

另外nice值通常由CPU动态调整，占用CPU时间越多的进程倾向于给调更高的nice值。
