### ISSUE TITLE
NOT-IN can choose hash join if both sides are non-nullable.

### ISSUE THREAD

**Issue by kainwen** [greenplum-db/gpdb#12930]
## Feature Request

**Is your feature request related to a problem? Please describe:**

For multi-column `NOT-IN`, currently, Greenplum does not choose hash join. See detailed comments at https://github.com/greenplum-db/gpdb/pull/11579#issuecomment-793385278

By Current, I mean:

* master branch (top: 81bb545ef9801bd429687d5bce0ead7da197b1a5)
* 6X (top: e357dbbfc8b1ce7fd05ae)
* 5X (actually this version has bug on this pattern of query).

**Describe the feature you'd like to request:**

If we can know both sides are non-nullable, we might choose hash join.

**Comment by ashwinstar** [comment]
Even upstream PostgreSQL doesn't (or only GPDB doesn't but upstream does)? Just trying to understand if even upstream doesn't then should we propose the solution there as well and seek inputs/feedback?

**Comment by kainwen** [comment]
> Even upstream PostgreSQL doesn't (or only GPDB doesn't but upstream does)? Just trying to understand if even upstream doesn't then should we propose the solution there as well and seek inputs/feedback?

upstream Postgres does not pull up such sublink. It uses subplan（hashes subplan）those part of executor code are careful designed.

Greenplum handle subplan by either broadcast or gather. I do not test if gp not pull up's perf. Maybe have a try.
