### ISSUE TITLE
FATAL:  writer segworker group shared snapshot collision on id 

### ISSUE THREAD

**Issue by Maaciekk** [greenplum-db/gpdb#12939]
## Bug Report
Hi,

We've installed Greenplum Database 6.18.1 and occasionally experience errors :

`2021 -12 -14 08 :38 :28.659800 CET,
"dwh_user",
"dwh",
p432262,
th38717568,
"10.10.112.141",
"46565",
2021 -12 -14 08 :36 :08 CET,
0,
con239705,
cmd21,
seg -1,
,
dx349350,
,
sx1,
"ERROR",
"58M01",
"failed to acquire resources on one or more segments",
"FATAL:  writer segworker group shared snapshot collision on id 239705. Slot array dump: Local SharedSnapshot Slot Dump: currSlots: 43 maxSlots: 1836 (SLOT index: 0 slotid: 235297 QDxid: 341553 pid: 100953)(SLOT index: 1 slotid: 239782 QDxid: 349335 pid: 482812)(SLOT index: 2 slotid: 237282 QDxid: 345571 pid: 270236)(SLOT index: 3 slotid: 239760 QDxid: 349292 pid: 479132)(SLOT index: 4 slotid: 237612 QDxid: 346185 pid: 292580)(SLOT index: 5 slotid: 239781 QDxid: 349336 pid: 482833)(SLOT index: 6 slotid: 239787 QDxid: 349340 pid: 483111)(SLOT index: 7 slotid: 237309 QDxid: 345633 pid: 272341)(SLOT index: 8 slotid: 239691 QDxid: 349341 pid: 483286)(SLOT index: 9 slotid: 239745 QDxid: 349255 pid: 477254)(SLOT index: 10 slotid: 239786 QDxid: 349338 pid: 482958)(SLOT index: 11 slotid: 237962 QDxid: 346622 pid: 319871)(SLOT index: 12 slotid: 239793 QDxid: 349342 pid: 483549)(SLOT index: 13 slotid: 24 QDxid: 349343 pid: 483596)(SLOT index: 14 slotid: 237269 QDxid: 345553 pid: 269672)(SLOT index: 15 slotid: 239705 QDxid: 349195 pid: 474615)(SLOT index: 16 slotid: 235959 QDxid: 342979 pid: 159229)(SLOT index: 17 slotid: 239762 QDxid: 349337 pid: 479326)(SLOT index: 18 slotid: 239474 QDxid: 348935 pid: 455077)(SLOT index: 19 slotid: 239795 QDxid: 349349 pid: 483687)(SLOT index: 20 slotid: 235648 QDxid: 342273 pid: 128138)(SLOT index: 21 slotid: 234907 QDxid: 349339 pid: 443309)(SLOT index: 22 slotid: 239360 QDxid: 348859 pid: 447929)(SLOT index: 23 slotid: 238810 QDxid: 347950 pid: 393583)(SLOT index: 24 slotid: 238045 QDxid: 346858 pid: 328388)(SLOT index: 25 slotid: 239807 QDxid: 349351 pid: 484808)(SLOT index: 26 slotid: 238689 QDxid: 347808 pid: 384857)(SLOT index: 27 slotid: 239772 QDxid: 349327 pid: 481451)(SLOT index: 28 slotid: 237618 QDxid: 346196 pid: 292989)(SLOT index: 29 slotid: 23 QDxid: 349344 pid: 483762)(SLOT index: 30 slotid: 239805 QDxid: 349348 pid: 484502)(SLOT index: 32 slotid: 239387 QDxid: 349061 pid: 463928)(SLOT index: 33 slotid: 238519 QDxid: 347504 pid: 372825)(SLOT index: 34 slotid: 239372 QDxid: 348825 pid: 445472)(SLOT index: 35 slotid: 238233 QDxid: 347099 pid: 345894)(SLOT index: 36 slotid: 239645 QDxid: 349331 pid: 469144)(SLOT index: 37 slotid: 239752 QDxid: 349274 pid: 478049)(SLOT index: 41 slotid: 238543 QDxid: 347555 pid: 375262)(SLOT index: 42 slotid: 222759 QDxid: 342909 pid: 155349)(SLOT index: 46 slotid: 235970 QDxid: 342999 pid: 159934)(SLOT index: 51 slotid: 234906 QDxid: 341109 pid: 71818)(SLOT index: 52 slotid: 235984 QDxid: 343428 pid: 160577)(SLOT index: 53 slotid: 227665 QDxid: 334640 pid: 469055) (sharedsnapshot.c:394)
 (seg10 10.10.114.137:6010)",
,
,
,
,
"",
0,
,
"cdbgang_async.c",
241,`

### Greenplum version or build

Greenplum Database 6.18.1 on x86_64-unknown-linux-gnu, compiled by gcc (GCC) 6.4.0, 64-bit

### OS version and uname -a
Linux  3.10.0-1062.9.1.el7.x86_64 #1 SMP Mon Dec 2 08:31:54 EST 2019 x86_64 x86_64 x86_64 GNU/Linux

### Expected behavior
Run and complete SQL with SUCCESS

### Actual behavior
Crash SQL and report ERROR

"failed to acquire resources on one or more segments",
"FATAL:  writer segworker group shared snapshot collision on id 239705. Slot array dump: Local SharedSnapshot Slot Dump: currSlots: 43 maxSlots: 1836 (SLOT index: 0 slotid: 235297 QDxid: 341553 pid: 100953)(SLOT index: 1 slotid: 239782 QDxid: 349335 pid: 482812)(SLOT index: 2 slotid: 237282 QDxid: 345571 pid: 270236)(SLOT index: 3 slotid: 239760 QDxid: 349292 pid: 479132)(SLOT index: 4 slotid: 237612 QDxid: 346185 pid: 292580)(SLOT index: 5 slotid: 239781 QDxid: 349336 pid: 482833)(SLOT index: 6 slotid: 239787 QDxid: 349340 pid: 483111)(SLOT index: 7 slotid: 237309 QDxid: 345633 pid: 272341)(SLOT index: 8 slotid: 239691 QDxid: 349341 pid: 483286)(SLOT index: 9 slotid: 239745 QDxid: 349255 pid: 477254)(SLOT index: 10 slotid: 239786 QDxid: 349338 pid: 482958)(SLOT index: 11 slotid: 237962 QDxid: 346622 pid: 319871)(SLOT index: 12 slotid: 239793 QDxid: 349342 pid: 483549)(SLOT index: 13 slotid: 24 QDxid: 349343 pid: 483596)(SLOT index: 14 slotid: 237269 QDxid: 345553 pid: 269672)(SLOT index: 15 slotid: 239705 QDxid: 349195 pid: 474615)(SLOT index: 16 slotid: 235959 QDxid: 342979 pid: 159229)(SLOT index: 17 slotid: 239762 QDxid: 349337 pid: 479326)(SLOT index: 18 slotid: 239474 QDxid: 348935 pid: 455077)(SLOT index: 19 slotid: 239795 QDxid: 349349 pid: 483687)(SLOT index: 20 slotid: 235648 QDxid: 342273 pid: 128138)(SLOT index: 21 slotid: 234907 QDxid: 349339 pid: 443309)(SLOT index: 22 slotid: 239360 QDxid: 348859 pid: 447929)(SLOT index: 23 slotid: 238810 QDxid: 347950 pid: 393583)(SLOT index: 24 slotid: 238045 QDxid: 346858 pid: 328388)(SLOT index: 25 slotid: 239807 QDxid: 349351 pid: 484808)(SLOT index: 26 slotid: 238689 QDxid: 347808 pid: 384857)(SLOT index: 27 slotid: 239772 QDxid: 349327 pid: 481451)(SLOT index: 28 slotid: 237618 QDxid: 346196 pid: 292989)(SLOT index: 29 slotid: 23 QDxid: 349344 pid: 483762)(SLOT index: 30 slotid: 239805 QDxid: 349348 pid: 484502)(SLOT index: 32 slotid: 239387 QDxid: 349061 pid: 463928)(SLOT index: 33 slotid: 238519 QDxid: 347504 pid: 372825)(SLOT index: 34 slotid: 239372 QDxid: 348825 pid: 445472)(SLOT index: 35 slotid: 238233 QDxid: 347099 pid: 345894)(SLOT index: 36 slotid: 239645 QDxid: 349331 pid: 469144)(SLOT index: 37 slotid: 239752 QDxid: 349274 pid: 478049)(SLOT index: 41 slotid: 238543 QDxid: 347555 pid: 375262)(SLOT index: 42 slotid: 222759 QDxid: 342909 pid: 155349)(SLOT index: 46 slotid: 235970 QDxid: 342999 pid: 159934)(SLOT index: 51 slotid: 234906 QDxid: 341109 pid: 71818)(SLOT index: 52 slotid: 235984 QDxid: 343428 pid: 160577)(SLOT index: 53 slotid: 227665 QDxid: 334640 pid: 469055) (sharedsnapshot.c:394)
 (seg10 10.10.114.137:6010)",

### Step to reproduce the behavior
Its hard to reproduce because error occurs in random SQL's. In pg_log on segments there is no mention about any error in this time.

**Comment by kainwen** [comment]
Can you provide more details about:
1. the SQLs involving the issue
2. Shared Snapshot should be related to Cursor, what is your client to access Greenplum?
3. What are your workloads? (Logs on master and segments might be helpful).

**Comment by kainwen** [comment]
JDBC's prepared statement is just like cursor.

**Comment by Maaciekk** [comment]
1. Ok, so is there any GUC parameter we can try to fine tune, e.g. gp_cached_segworkers_threshold ?.
2. What's the best way to debug missing resources?

P.S
we've migrated from GP 5.25 to GP 6.18, on GP 5.25 there were no error like "failed to acquire resources on one or more segments"

**Comment by ashwinstar** [comment]
Please refer to these mailing list threads for the topic https://groups.google.com/a/greenplum.org/g/gpdb-dev/c/ybJ-JtY2HTY/m/ps3bjlPRAwAJ and https://groups.google.com/a/greenplum.org/g/gpdb-users/c/jQm_PyhHID8/m/GxulyIL3BAAJ Please help answer these questions asked in the thread

Would like to understand more in which scenarios you are seeing this snapshot collision error.
Is GUC gp_vmem_idle_resource_timeout coming into play for these sessions?
Do you have a work-load where the session remains idle for this GUC gp_vmem_idle_resource_timeout time and then queries are executed again using the same session?

Most likely then adjusting/increasing the value of GUC gp_vmem_idle_resource_timeout should help resolve the situation.

In past increasing the value of GUC gp_snapshotadd_timeout also provided relief from this error (though I personally as a developer don't like this solution, though no downsides)

**Comment by Maaciekk** [comment]
We have gp_vmem_idle_resource_timeout set to 18 seconds (default). By how many seconds do I have to increase this parameter e.g. 2, 5? 

About idle session, I have to check our scenarios.

**Comment by ashwinstar** [comment]
> We have gp_vmem_idle_resource_timeout set to 18 seconds (default). By how many seconds do I have to increase this parameter e.g. 2, 5?

This totally will depend on your workload, once you check your sessions and how is the behavior. What's keeping the resources idle, how aggressively wish to cleanup idle resources and all such details.

**Comment by lij55** [comment]
Hi @Maaciekk , 

does #13112 (which is in 6.20.0) fix your issue?

**Comment by Maaciekk** [comment]
Hi, we are getting ready to upgrade probably next week. I'll be back with feedback.

**Comment by kainwen** [comment]
@QingMa-gp Would you please help check if this is fixed? Thanks.

**Comment by QingMa-gp** [comment]
This issue has been fixed by https://github.com/greenplum-db/gpdb/pull/13143.
