### ISSUE TITLE
error include header file "nodes/relation.h"

### ISSUE THREAD

**Issue by wangxuqi** [greenplum-db/gpdb#12954]
### Greenplum version
Master 

relation.h has been moved from` include/nodes/relation.h `to`  include/access/relation.h`. but header include in var.h still use the old one.

-- var.h
```
#ifndef VAR_H
#define VAR_H

#include "nodes/relation.h"
```

**Comment by ashwinstar** [comment]
When is this file used? Current compilation doesn't fail.

**Comment by wangxuqi** [comment]
> When is this file used? Current compilation doesn't fail.

These is no file include header `var.h` for now. So it doesn't break the compilation. 
But it still a remain problem. If we include `var.h` in other file, it will break.

**Comment by ashwinstar** [comment]
It's not clear to me what purpose this file serves, when would it be required to be included or is it just dead code

**Comment by wangxuqi** [comment]
Maybe is just dead code, this row should be deleted.

**Comment by higuoxing** [comment]
Fixed by commit 51f886e.
