### ISSUE TITLE
gpconfig/gpinitsystem comments other GUC with same prefix by accident

### ISSUE THREAD

**Issue by DellCurry** [greenplum-db/gpdb#12957]
## Bug Report
When we use **gpconfig** to add a new parameter, it may comment another parameter with the same prefix, because in **gpconfig_hepler.py** line 96, the function **_comment_parameter()_** uses _**startswith**_ to match the GUC.

For example, if we use gpconfig to add 2 GUCs, **gp_resqueue_priority** and **gp_resqueue_priority_cpucores_per_segment** to the postgresql.conf:
![image](https://user-images.githubusercontent.com/30748980/147177580-aac66e9c-133d-4053-88b9-bb3ad2aa8328.png)

Then we try to modify **gp_resqueue_priority** to 'on' by typing **_gpconfig -c gp_resqueue_priority -v 'on'_**.

Now we go back to the postgresql.conf in either master node or segment node, we will find:
![image](https://user-images.githubusercontent.com/30748980/147177966-fbfa2207-4420-4f59-b43a-0dc2503ee569.png)

The GUC **gp_resqueue_priority_cpucores_per_segment** is also commented because it has the same prefix with **gp_resqueue_priority**.

The same accident also happens in **gpinitsystem** with **-p** option, it will call _**SED_PG_CONF**_ in **gp_bash_functions.sh**, which also uses prefix match somewhere.

### Greenplum version or build
6X_STABLE

### OS version and uname -a
CentOS 7

### Expected behavior
When adding a GUC, only the exact old GUC in postgresql.conf would be commented.

### Actual behavior
Other GUCs with same prefix would also be commented.

### Step to reproduce the behavior
$ gpconfig -c gp_resqueue_priority -v 'off'
$ gpconfig -c gp_resqueue_priority_cpucores_per_segment -v '2'
$ gpconfig -c gp_resqueue_priority -v 'on'

**Comment by hidva** [comment]
A Great Cache!

**Comment by zhaorui20005** [comment]
@DellCurry Would you please submit a pr for this issue?

**Comment by DellCurry** [comment]
> @DellCurry Would you please submit a pr for this issue?

Ok, I am preparing a pr to this issue.

Also, add steps to reproduce this bug in **gpinitsystem** here:

In gpAux/gpdemo/demo_cluster.sh, add a new line in the head:

**BLDWRAP_POSTGRES_CONF_ADDONS="gp_resqueue_priority_cpucores_per_segment=2|gp_resqueue_priority='off'"**

Then follow the steps in **README.md** to start the demo cluster.

When the demo cluster is up, go to a segment dir and look at the **postgresql.conf** (The conf file on master is correct):
![image](https://user-images.githubusercontent.com/30748980/147330349-28b28f64-0f5c-4212-83ee-e4eb0004b1ad.png)
