### ISSUE TITLE
GP JDBC URL Property lack

### ISSUE THREAD

**Issue by BeyondTheBlade** [greenplum-db/gpdb#12953]
## Enhancement
GP version 6.16.3

I need create JDBC URL By GP Driver. But I can't set 'DB Schema' property in GP JDBC URL.
Now I only use PG JDBC URL to link GP. 
example:
 jdbc:postgresql://<host>:<port>/<dbName>?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&currentSchema=<schema>&reWriteBatchedInserts=true
I want know GP how to set these property in GP JDBC URL.
If GP can. Please tell me. thanks

**Comment by prismcore** [comment]
jdbc:pivotal:greenplum://xxx:2345;DatabaseName=xxx"

**Comment by BeyondTheBlade** [comment]
> 

I know it, but it's not what I want. That only set DatabaseName,I want to set  currentSchema like PGSQL

**Comment by lij55** [comment]
Greenplum 6 and later should be compitable with the Driver of postgresql 9.4 and later. It should be support such URL: `jdbc:postgresql://localhost:5432/mydatabase?currentSchema=myschema`
(https://stackoverflow.com/questions/4168689/is-it-possible-to-specify-the-schema-when-connecting-to-postgres-with-jdbc)

what about your JDBC driver version?

**Comment by BeyondTheBlade** [comment]
> Greenplum 6 and later should be compitable with the Driver of postgresql 9.4 and later. It should be support such URL: `jdbc:postgresql://localhost:5432/mydatabase?currentSchema=myschema` (https://stackoverflow.com/questions/4168689/is-it-possible-to-specify-the-schema-when-connecting-to-postgres-with-jdbc)
> 
> what about your JDBC driver version?

I Know it,but I want to use GP‘s JDBC driver instead of PG’s JDBC driver.
I just see "jdbc:pivotal:greenplum://xxx:2345;DatabaseName=xxx" in GP‘s website.
I want to use GP driver complete.But I can’t find these params in GP‘s website.

**Comment by lij55** [comment]
I couldn't find the related properties either from : https://docs.progress.com/bundle/datadirect-connect-jdbc-51/page/Connection-Properties_2.html
However, does it work by setting`set search_path to 'schema'` after connection?

**Comment by BeyondTheBlade** [comment]
> I couldn't find the related properties either from : https://docs.progress.com/bundle/datadirect-connect-jdbc-51/page/Connection-Properties_2.html However, does it work by setting`set search_path to 'schema'` after connection?

postgresql‘s settings can work，but I want greenplum's JDBC Driver also supply it

**Comment by lij55** [comment]
closing this issue as it is out of control of this repo. thanks.
