### ISSUE TITLE
CHECKPOINT WAL can not replay

### ISSUE THREAD

**Issue by weinan003** [greenplum-db/gpdb#12977]
### Greenplum version or build
master branch

### Actual behavior
In gpdb master branch, CHECKPOINT WAL can not always replay success.

### Step to reproduce the behavior
1. Preparing a bash script as follow
```
$ cat frequent_drop_create_table.sh
for i in {1..2000}; do echo "psql -c 'create table t_$1_$i (c1 int); drop table t_$1_$i';" | bash; done
```
2. Performing the script as follow, and wait about 2 mins
```
for i in {1..128}; do echo "source frequent_drop_create_table.sh $i > ~/tmp/test$i 2>&1 &"|bash;done
```
3. execute `gpstop -rai`

Most likely, the master node will not restart success due to CHECKPOINT WAL being illegal.

**Comment by haolinw** [comment]
Closed as it is fixed by https://github.com/greenplum-db/gpdb/pull/14473.
