### ISSUE TITLE
gp_sparse_vector extension need strict operator to handle NULL operands

### ISSUE THREAD

**Issue by Aegeaner** [greenplum-db/gpdb#12986]
### Greenplum version or build
6X

### OS version and uname -a
Linux localhost.localdomain 4.18.0-305.19.1.el8_4.x86_64 #1 SMP Wed Sep 15 15:39:39 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Expected behavior
The equal operator `svec_l2_eq` will handle NULL rows well, and no PANIC happens.

### Actual behavior
The master will PANIC.

### Step to reproduce the behavior

1.) create extension gp_sparse_vector;
2.) set search_path = ‘sparse_vector’;
3.) Run the query

```
gpadmin=# select a.table_name,b.column_name, case when ((a.character_maximum_length == b.character_maximum_length) or ( a.numeric_precision==b.numeric_precision) or (a.numeric_scale==b.numeric_scale)) then 'Y' else 'N' end from information_schema.columns a inner join information_schema.columns b on a.table_name=b.table_name and a.column_name=b.column_name order by a.ordinal_position;
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
```

**Comment by lij55** [comment]
closing issue as fix is merged.
