### ISSUE TITLE
[Doc] GP6 init system locale settings: doc description not the same as behavior

### ISSUE THREAD

**Issue by Aegeaner** [greenplum-db/gpdb#13033]
### Greenplum version or build
Greenplum 5X, 6X

### Expected behavior
If not locale is explicitly passed by `-n [locale_setting]` option,  `en_US.utf8` is used instead of system default locale setting.

```
https://github.com/greenplum-db/gpdb/blob/aba0ba2af5cd758c1706c1b4ab342998daa64c48/gpMgmt/bin/lib/gp_bash_functions.sh#L1459
https://github.com/greenplum-db/gpdb/blob/aba0ba2af5cd758c1706c1b4ab342998daa64c48/gpMgmt/bin/gpinitsystem#L303
```
**The document should be the same as above behavior.**

### Actual behavior

As [the current GP6 doc](https://github.com/greenplum-db/gpdb/blob/aba0ba2af5cd758c1706c1b4ab342998daa64c48/gpMgmt/doc/gpinitsystem_help#L119) described:
```
--locale=<locale> | -n <locale>  

 Sets the default locale used by Greenplum Database. If not specified, 
 the LC_ALL, LC_COLLATE, or LANG environment variable of the master 
 host determines the locale. If these are not set, the default locale 
 is C (POSIX). 
```
### Step to reproduce the behavior

```
1. gpinitsystem without passing the -n option.
2. set LC_ALL
3. locale not set as expected, in fact en_US.utf8 is used.
```

**Comment by lij55** [comment]
Hi @Aegeaner ,

what's your OS and locale of the Greenplum host? and what's the OS and locale where you run the SSL client (for example, ssh from Mac or Windows to a remote Linux server)? We noticed some SSH client will pass through the client locale to server side. If so, simpley setting LC_ALL is not enough.

**Comment by dpandhi-git** [comment]
with CM team docs are updated 
https://docs.vmware.com/en/VMware-Tanzu-Greenplum/6/greenplum-database/GUID-utility_guide-ref-gpinitsystem.html
