### ISSUE TITLE
is there any plan when gp7 will be release?

### ISSUE THREAD

**Issue by hslightdb** [greenplum-db/gpdb#13057]
## Feature Request

**Is your feature request related to a problem? Please describe:**

**Describe the feature you'd like to request:**

**Comment by qingduyu** [comment]
we want the  upinsert feature ,

**Comment by ashwinstar** [comment]
Great to know. We don't have plan date for GPDB7 release yet. Won't be in 2022 is known so far. We are actively working to get it in ready state.
