### ISSUE TITLE
pg_catalog.pg_partitions doesn't exist

### ISSUE THREAD

**Issue by anderson753** [greenplum-db/gpdb#13080]
### Greenplum version or build
master
### OS version and uname -a
ubuntu
### autoconf options used ( config.status --config )
./configure --with-perl --with-python --with-libxml --with-gssapi --prefix=/usr/local/gpdb
### Installation information ( pg_config )
make -j8
make -j8 install
### Expected behavior
I expect system view can be see
### Actual behavior
I compile and install the gpdb master source code, and successfully run the demo cluster(coordinate 2 segment 3 mirror 3),then i use pgadmin login the gpdb server and click schema then report pg_catalog.pg_partitions doesn't exist,I find there is no init some system view,could somebody help me?

**Comment by SmartKeyerror** [comment]
MASTER branch no longer uses `pg_catalog.pg_partition` and `pg_catalog.pg_partitions`, but uses `pg_catalog.pg_partitioned_table`. 

In 6X-STABLE, GPDB implements its own partitioned table, but in MASTER branch, tt merges the upstream implementation (PostgreSQL 10+).So the tables and views will also be different between the two versions.

**Comment by lij55** [comment]
A better way is to create a view with the same name and the same content on GP7 and later, for both `pg_partition` and all the other missing catalog tables. The reasion is that a lot of tools (internal and exteranl) relies on thoses catalog tables. 
Such behavior change will cuase existing tools stopping work.

**Comment by anderson753** [comment]
> MASTER branch no longer uses `pg_partition` and `pg_partitions`, but uses `pg_catalog.pg_partitioned_table`.
> 
> In 6X-STABLE, GPDB implements its own partitioned table, but in MASTER branch, tt merges the upstream implementation (PostgreSQL 10+).So the tables and views will also be different between the two versions.

thanks a lot

**Comment by anderson753** [comment]
> A better way is to create a view with the same name and the same content on GP7 and later, for both `pg_partition` and all the other missing catalog tables. The reasion is that a lot of tools (internal and exteranl) relies on thoses catalog tables. Such behavior change will cuase existing tools stopping work.

thanks a lot

**Comment by anderson753** [comment]
> MASTER branch no longer uses `pg_partition` and `pg_partitions`, but uses `pg_catalog.pg_partitioned_table`.
> 
> In 6X-STABLE, GPDB implements its own partitioned table, but in MASTER branch, tt merges the upstream implementation (PostgreSQL 10+).So the tables and views will also be different between the two versions.

**Comment by anderson753** [comment]
>
