### ISSUE TITLE
gpexand failes after enterning blank line for new hosts

### ISSUE THREAD

**Issue by wangsenyuan** [greenplum-db/gpdb#13167]
## Bug Report
using gpexpand to add new segments in existing segment hosts, after entering blank line promoted for new hosts, gpexpand exists with error
### Greenplum version or build
opensource greenplum 6.19
### OS version and uname -a
Linux mdw 3.10.0-1160.53.1.el7.x86_64 #1 SMP Fri Jan 14 13:59:45 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
### Installation information ( pg_config )
BINDIR = /usr/local/greenplum-db-6.19.0/bin
DOCDIR = /usr/local/greenplum-db-6.19.0/share/doc/postgresql
HTMLDIR = /usr/local/greenplum-db-6.19.0/share/doc/postgresql
INCLUDEDIR = /usr/local/greenplum-db-6.19.0/include
PKGINCLUDEDIR = /usr/local/greenplum-db-6.19.0/include/postgresql
INCLUDEDIR-SERVER = /usr/local/greenplum-db-6.19.0/include/postgresql/server
LIBDIR = /usr/local/greenplum-db-6.19.0/lib
PKGLIBDIR = /usr/local/greenplum-db-6.19.0/lib/postgresql
LOCALEDIR = /usr/local/greenplum-db-6.19.0/share/locale
MANDIR = /usr/local/greenplum-db-6.19.0/man
SHAREDIR = /usr/local/greenplum-db-6.19.0/share/postgresql
SYSCONFDIR = /usr/local/greenplum-db-6.19.0/etc/postgresql
PGXS = /usr/local/greenplum-db-6.19.0/lib/postgresql/pgxs/src/makefiles/pgxs.mk
CONFIGURE = '--disable-debug-extensions' '--disable-tap-tests' '--enable-orca' '--with-zstd' '--with-gssapi' '--with-libxml' '--with-perl' '--with-python' '--with-openssl' '--with-pam' '--with-ldap' '--with-extra-version= Open Source' '--prefix=/usr/local/greenplum-db-6.19.0' '--mandir=/usr/local/greenplum-db-6.19.0/man' 'CC=gcc' 'CFLAGS=-O3 -fargument-noalias-global -fno-omit-frame-pointer -g'
CC = gcc
CPPFLAGS = -D_GNU_SOURCE -I/usr/include/libxml2 -I/usr/local/greenplum-db-6.19.0/include
CFLAGS = -Wall -Wmissing-prototypes -Wpointer-arith -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fno-aggressive-loop-optimizations -Wno-unused-but-set-variable -Wno-address -O3 -fargument-noalias-global -fno-omit-frame-pointer -g -std=gnu99 -Werror=uninitialized -Werror=implicit-function-declaration -I/usr/local/greenplum-db-6.19.0/include
CFLAGS_SL = -fPIC
LDFLAGS = -Wl,--as-needed -Wl,-rpath,'/usr/local/greenplum-db-6.19.0/lib',--enable-new-dtags -L/usr/local/greenplum-db-6.19.0/lib
LDFLAGS_EX =
LDFLAGS_SL =
LIBS = -lpgcommon -lpgport -lxerces-c -lxml2 -lpam -lrt -lgssapi_krb5 -lzstd -lrt -lcrypt -ldl -lm -L/usr/local/greenplum-db-6.19.0/lib
VERSION = PostgreSQL 9.4.26
### Expected behavior
gpexpand should continue
### Actual behavior
gpexpand:mdw:gpadmin-[ERROR]:-gpexpand failed: You must be adding two or more hosts when expanding a system with mirroring enabled.

**Comment by kainwen** [comment]
Hello, the error message is very clear: 

> You must be adding two or more hosts when expanding a system with mirroring enabled.

Please read the doc: https://greenplum.docs.pivotal.io/6-19/utility_guide/ref/gpexpand.html

If you have question on this, gpdb-user mailing list might be a good place to ask and discuss. Or you can continue discuss here in the closed issue.

**Comment by wangsenyuan** [comment]
> Hello, the error message is very clear:
> 
> > You must be adding two or more hosts when expanding a system with mirroring enabled.
> 
> Please read the doc: https://greenplum.docs.pivotal.io/6-19/utility_guide/ref/gpexpand.html
> 
> If you have question on this, gpdb-user mailing list might be a good place to ask and discuss. Or you can continue discuss here in the closed issue.

I followed the codes, at lease 2 new segment hosts needed anyway. 

But, according to the doc, https://gpdb.docs.pivotal.io/6-13/admin_guide/expand/expand-initialize.html
`To add segments to existing hosts only, enter a blank line at this prompt. Do not specify localhost or any existing host name.`

blank line is the way to add new segments in existing hosts; 
Am I wrong?

**Comment by wangsenyuan** [comment]
Or when mirror is enabled, there is no way to add new segments without add new hosts?

**Comment by ashwinstar** [comment]
re-opening this issue as seems either documentation or tool prompt needs to be enhanced or fixed. (I don't have the answer yet on which aspect needs fixing)

**Comment by lij55** [comment]
Hi @wangsenyuan , could you please share us which parameter you run with gpexpland? 
BTW, what happens if you enter the same hostname as those existing ones?

**Comment by SmartKeyerror** [comment]
@wangsenyuan 

> Or when the mirror is enabled, there is no way to add new segments without adding new hosts?

Yes, we could not use the current hosts' configuration to perform gpexapnd if mirror enabled. 

The reason is a primary segment and its mirror must be on different hosts to ensure high availability, this has been described in the doc: [Segment Mirroring Configurations](https://greenplum.docs.pivotal.io/6-19/best_practices/ha.html#topic_ngz_qf4_tt).

**Comment by wangsenyuan** [comment]
> Hi @wangsenyuan , could you please share us which parameter you run with gpexpland? BTW, what happens if you enter the same hostname as those existing ones?

sorry for late response. I run gpexpand without parameters

**Comment by wangsenyuan** [comment]
> @wangsenyuan
> 
> > Or when the mirror is enabled, there is no way to add new segments without adding new hosts?
> 
> Yes, we could not use the current hosts' configuration to perform gpexapnd if mirror enabled.
> 
> The reason is a primary segment and its mirror must be on different hosts to ensure high availability, this has been described in the doc: [Segment Mirroring Configurations](https://greenplum.docs.pivotal.io/6-19/best_practices/ha.html#topic_ngz_qf4_tt).

I guessed so. However, from the code, it seems not be able to process when mirroring enabled. 
`if gparray.get_mirroring_enabled():
        if num_new_hosts < 2:
            raise ExpansionError('You must be adding two or more hosts when expanding a system with mirroring enabled.')
        mirror_type = ask_string(
            "\nYou must now specify a mirroring strategy for the new hosts.  Spread mirroring places\n" \
            "a given hosts mirrored segments each on a separate host.  You must be \n" \
            "adding more hosts than the number of segments per host to use this. \n" \
            "Grouped mirroring places all of a given hosts segments on a single \n" \
            "mirrored host.  You must be adding at least 2 hosts in order to use this.\n\n",
            "What type of mirroring strategy would you like?",
            'grouped', ['spread', 'grouped'])`

**Comment by SmartKeyerror** [comment]
I think the error message for this question is clear enough, so I close this issue.

Feel free to reopen this if you have different perspectives, or create a pull request for this directly. 

Thanks.
