### ISSUE TITLE
cache lookup failed for relation 25 (pg_inherits.c:279)

### ISSUE THREAD

**Issue by SmartKeyerror** [greenplum-db/gpdb#13195]
### Greenplum version or build

6X_STABLE.

master does not have this issue

### Expected behavior

`select pg_catalog.gp_dump_query_oids()` will return correct results, not ERROR.

### Actual behavior

Return ERROR: cache lookup failed for relation 25 (pg_inherits.c:279)

### Step to reproduce the behavior

```
postgres=# CREATE TABLE t (pid varchar(1), dummy varchar(1)) DISTRIBUTED BY (pid);
CREATE TABLE

postgres=# CREATE VIEW s AS SELECT 'D' as dummy;
WARNING:  column "dummy" has type "unknown"
DETAIL:  Proceeding with relation creation anyway.
CREATE VIEW

postgres=# select pg_catalog.gp_dump_query_oids('select * from t join s on t.dummy = s.dummy');
ERROR:  cache lookup failed for relation 25 (pg_inherits.c:279)
```

**Comment by SmartKeyerror** [comment]
The root cause is that GPDB used a function wrapper to convert an `UNKNOWN` type to `TEXT` type. 

For some consideration, GPDB will first convert `UNKNOWN` type to `CString`, and then convert to what it should be converted, we can find this logic in function `coerce_type()`:

```cpp
args = list_make3(fe,
            makeConst(OIDOID, -1, InvalidOid, sizeof(Oid),
                            ObjectIdGetDatum(intypioparam),
                            false, true),
            makeConst(INT4OID, -1, InvalidOid, sizeof(int32),
                            Int32GetDatum(-1),
                            false, true));
```

In the end, the const of the `OIDOID` type will remain in the Query Tree, and the subsequent executor will traverse the entire tree and look for a legal Relation OID, and the const node of the `OIDOID` type will also be considered a legal Relation OID. This OID is actually a wrapper added by GPDB itself, and has no physical entity, so it finally fails when `has_subclass()` queries the system cache through `relationId`, because this is not a real legal OID.

**Comment by lij55** [comment]
closing it as the fix is merged.
