### ISSUE TITLE
Reopen #1250

### ISSUE THREAD

**Issue by fengttt** [greenplum-db/gpdb#1323]
While release build seems to work, the debug build hit assert.   I tried to re-open 1250 but seems github only allow me to open new issues.   Therefore, here it is, 

ftian=# create table sale(cn int, vn int) distributed by (cn, vn);
CREATE TABLE
ftian=# create view myview as select sum(distinct sale.cn) from sale group by grouping sets(sale.vn, sale.cn);
CREATE VIEW
ftian=# select * from myview;
FATAL:  Unexpected internal error (planner.c:1348)
DETAIL:  FailedAssertion("!((var->varno == 65001 || (var->varno > 0 && var->varno <= list_length(root->parse->rtable))) && "Plan contains var that refer outside the rtable.")", File: "planner.c", Line: 1348)

**Comment by ascherbaum-pivotal** [comment]
For reference: https://github.com/greenplum-db/gpdb/issues/1250

**Comment by d** [comment]
@fengttt I don't think this happens on master any more, can you close this?

**Comment by vraghavan78** [comment]
Closing issue. Please reopen if it still exists.
