### ISSUE TITLE
mac osx 12.3 m1 max compile gp

### ISSUE THREAD

**Issue by aresnasa** [greenplum-db/gpdb#13249]
## Bug Report
cann't find lib
### Greenplum version or build
7.0 beta
### OS version and uname -a
Mac OSX M1 Max arm64
Darwin 21.4.0 Darwin Kernel Version 21.4.0
### autoconf options used ( config.status --config )
 ./configure --with-perl --with-python --with-libxml --with-gssapi 

### Installation information ( pg_config )
configure: error: libevent is required for gpfdist

### Fix this issue
run README.macOS.bash
do README.macOS.md
 ./configure LDFLAGS=-L/usr/local/lib --with-perl --with-python --with-libxml --with-gssapi  --with-includes=/usr/local/include —prefix=$HOME/gpdb

**Comment by aresnasa** [comment]
7.0 alpha

**Comment by lij55** [comment]
Hi @aresnasa 
what's your compiler? did you try `brew install libevent`?

**Comment by lij55** [comment]
verified that `CFLAGS="-I/opt/homebrew/include"  LDFLAGS="-L/opt/homebrew/lib" ./configure XXX` works

**Comment by aresnasa** [comment]
> Hi @aresnasa what's your compiler? did you try `brew install libevent`?

I have installed the libevent,but if don't set CFLAGS and LDFLAGS configure throw error: libevent is required for gpfdist

**Comment by lij55** [comment]
> I have installed the libevent,but if don't set CFLAGS and LDFLAGS configure throw error: libevent is required for gpfdist

It seems the reason is that '/opt/homebrew' is not in the default search path of dependencies. I'm not Mac expert so I don't know how do it in a Mac's way but CFALGS and LDFLAGS usually used for such purpose.

**Comment by wonb168** [comment]
CFLAGS="-I/opt/homebrew/include"  LDFLAGS="-L/opt/homebrew/lib" ./configure XXX works,
but then `make`, still error:
```
xml.c:1025:45: error: incompatible function pointer types passing 'void (void *, xmlErrorPtr)' (aka 'void (void *, struct _xmlError *)') to parameter of type 'xmlStructuredErrorFunc' (aka 'void (*)(void *, const struct _xmlError *)') [-Wincompatible-function-pointer-types]
        xmlSetStructuredErrorFunc((void *) errcxt, xml_errorHandler);
                                                   ^~~~~~~~~~~~~~~~
/opt/homebrew/Cellar/libxml2/2.12.5_1/include/libxml2/libxml/xmlerror.h:898:29: note: passing argument to parameter 'handler' here
                                 xmlStructuredErrorFunc handler);
```
