### ISSUE TITLE
MKsort with POSTGIS geometry type cause coredump

### ISSUE THREAD

**Issue by wuyuhao28** [greenplum-db/gpdb#13315]
## Bug Report
MKsort with POSTGIS geometry type cause coredump, or ASSERT Failure.
If we turn off mksort, use tuplesort instead, everything is good.

I had learned tuplesort_mk.c and tuplesort.c and done some debug works, and I find that in MKsort, the key compare function is _lwgeom_cmp_; but tuplesort key compare function is _comparison_shim_, which will call _lwgeom_cmp_, see _sortsupport:comparison_shim()_. So I think MKSort may get unexpected compare result when using _lwgeom_cmp_ compare function.

Causing this difference is from the sortsupport, tuplesort use sortsupport, call _comparison_shim_ means we treats _lwgeom_cmp_ as an 'old-style comparator'; but MKsort do not have this work.

### Greenplum version or build
6X_STABLE

### autoconf options used ( config.status --config )
--enable-cassert

### Expected behavior
Sort success

### Actual behavior
Assest Failure
ERROR:  Unexpected internal error (tuplesort_mkqsort.c:254)  (seg2 slice1 100.81.113.25:16002 pid=172034) (tuplesort_mkqsort.c:254)
DETAIL:  FailedAssertion("!(rightIndex >= leftIndex+2)", File: "tuplesort_mkqsort.c", Line: 254)
HINT:  Process 172034 will wait for gp_debug_linger=120 seconds before termination.
Note that its locks and other resources will not be released until then.

if config without casset , core dump happens

### Step to reproduce the behavior
Using **DEMO** cluster(3 primary, 3 mirror).

```
CREATE extension postgis;
CREATE TABLE geometries (name varchar, geom geometry);

INSERT INTO geometries VALUES
  ('Point', 'POINT(0 0)'),
  ('Linestring', 'LINESTRING(0 0, 1 1, 2 1, 2 2)'),
  ('Polygon', 'POLYGON((0 0, 1 0, 1 1, 0 1, 0 0))'),
  ('PolygonWithHole', 'POLYGON((0 0, 10 0, 10 10, 0 10, 0 0),(1 1, 1 2, 2 2, 2 1, 1 1))'),
  ('Collection', 'GEOMETRYCOLLECTION(POINT(2 0),POLYGON((0 0, 1 0, 1 1, 0 1, 0 0)))');

select * from geometries order by 2;
```

**Comment by z-wenlin** [comment]
Thanks for reporting the issue. 
I tried to reproduce on my local by using `postgis-2.5.4+pivotal.6.build.1`, but it's working fine.
What's the postgis version are you using? Did you installed it by using gppkg?

**Comment by lij55** [comment]
Hi @wuyuhao28 ,

do you still have the issue?

**Comment by wuyuhao28** [comment]
Sorry for replying late.
I've found that the postgis version I used may have some problem, will close this issue.

Thanks !
