### ISSUE TITLE
Internal error:gpmmon.c:1080 agg_dup failed

### ISSUE THREAD

**Issue by linyuanpapapa** [greenplum-db/gpdb#13345]
## Bug Report
-FATAL： [Internal error:gpmmon.c:1080] agg_dup failed
  error 22 (Invalid argument)
It was the cause of the recovery mode of the database system，and I do not know why。
### Greenplum version or build
PG_VERSION:9.4
build：6.0.0-beta.1 build dev
### OS version and uname -a
Centos 7.4.1708
### Expected behavior
no message
### Actual behavior
no message
### Step to reproduce the behavior
no message

**Comment by kainwen** [comment]
6.0.0-beta.1 build dev is a really old version.

Please try on recent GPDB version to see if still having BUG.

Close this, feel free to reopen if needed.
