### ISSUE TITLE
Resgroup's memory usage doesn't count the startup chunks of a session process.

### ISSUE THREAD

**Issue by dreamedcheng** [greenplum-db/gpdb#13397]
## Bug Report

I found that a resgroup currently won't count the startup memory chunks of a session process.  This will cause that the control of memory usage in a resgroup not that accurate, we may have `n_running_procs * startupchunk` chunks out of control in a group! This is may be a big number.  

When `MemoryFailure_VmemExhausted` error raised, users may found the the regroup may still have available memory through resgroup related views. This might confuse users.  Fortunately, for now, I didn't find other sever problems.

**Comment by dpandhi-git** [comment]
@SmartKeyerror can you check this ?

**Comment by SmartKeyerror** [comment]
Yeah, actually we have already noticed this.

**Comment by SmartKeyerror** [comment]
I checked the `ResGroupReserveMemory()` again, and found that it used `IsResGroupEnabled()` to judge whether we enable the resource group, not using `IsResGroupActivated()`. The difference between them is that `IsResGroupEnabled()` will return `true` after setting the GUC, and `IsResGroupActivated()` will return true after `InitResManager()` is returned.

So in the current implementation, the startup memory chunks already have been counted, we do not need any fixation.

Close this issue, and please feel free to reopen it, thanks.
