### ISSUE TITLE
master panic when when we cancel a query

### ISSUE THREAD

**Issue by zxuejing** [greenplum-db/gpdb#13393]
### Greenplum version or build
gpdb 6.19.0

### Expected behavior
when we cancel a query,  this query can be canceled and an error  occurred.
### Actual behavior
there is a panic on QD.
### Step to reproduce the behavior

create table t1(tc1 int);
insert into t1 select generate_series(1,10000);
analyze gp_segment_configuration;
select * from gp_segment_configuration a,t1 , gp_segment_configuration b where a.dbid=t1.tc1;
-- this query has 3 gangs, 2 entrydb reader gangs, and 1 n-readergang.
--in cdbdisp_DestroyDispatcherState the first gang and second gang is entrydb gang

```
foreach(lc, ds->allocatedGangs)                                            
 {                                                                          
      Gang *gp = lfirst(lc);                                             
      RecycleGang(gp, ds->forceDestroyGang);                             
} 
```
--when we RecycleGang the second gang, according to the below codes this gang will be destroyed(segdesc is freed).
when we Recycle the third gang, somewhere will go to palloc-->AllocSetAlloc-->AllocSetAllocImpl-->gp_malloc-->gp_malloc_internal-->VmemTracker_ReserveVmem.
 here we send a cancel signal to QD manual and QD received the signal in VmemTracker_ReserveVmem and throw an error before we finish cdbdisp_DestroyDispatcherState.
 then we call atAbort_DispatcherState--> cdbdisp_DestroyDispatcherState to rollback, here the second gang is freed the second time, and causes a panic.
```
maxLen = segdbDesc->segindex == -1 ?
					MAX_CACHED_1_GANGS : gp_cached_gang_threshold;
	if (!isWriter && list_length(cdbinfo->freelist) >= maxLen)
		goto destroy_segdb;
```

**Comment by ashwinstar** [comment]
Nice find and analysis 👏

**Comment by zxuejing** [comment]
> Do I need to set a breakpoint in VmemTracker_ReserveVmem and `select pg_cancel_backend(pid)` to cancel the query to reproduction this case? The real problem is that segdb will be freed twice in this case?

yes, I think the problem is that the segdb is freed twice and cause panic.
but the path below is hit not every time when palloc is called, we must hit some condition then we can go into  VmemTracker_ReserveVmem
when we in VmemTracker_ReserveVmem, we can select pg_cancel_backend(PID) to give a cancel signal.

 palloc-->AllocSetAlloc-->AllocSetAllocImpl-->gp_malloc-->gp_malloc_internal-->VmemTracker_ReserveVmem.

**Comment by wfnuser** [comment]
> 

Well, I found the code implement AtAbort_DispatcherState looks like:
```
	if (CurrentGangCreating != NULL)
	{
		RecycleGang(CurrentGangCreating, true);
		CurrentGangCreating = NULL;
	}
```
Which means the recycleGang will only happen in the process of the gang creation. But actually it's not.

Maybe the crash is happened here in the following calling path.
`AtAbort_DispatcherState -> CdbResourceOwnerWalker -> cdbdisp_cancelDispatch -> cdbdisp_checkDispatchResult_async`

```
		/*
		 * Which QEs are still running and could send results to us?
		 */
		for (i = 0; i < db_count; i++)
		{
			dispatchResult = pParms->dispatchResultPtrArray[i];
			segdbDesc = dispatchResult->segdbDesc;
			conn = segdbDesc->conn;

			if (pParms->waitMode == DISPATCH_WAIT_ACK_ROOT &&
				checkAckMessage(dispatchResult, pParms->ackMessage))
			{
				ack_count++;
				continue;
			}
```
the segdbDesc has already be cleared and the segmentfault happened?

I'm not so sure. And how to fix it? Any idea?

**Comment by zxuejing** [comment]
you are right， this can cause a panic. I have not had any good idea yet, cdbdisp_destroyDispatcherState should not throw any exception by designing.

**Comment by wfnuser** [comment]
> you are right， this can cause a panic. I have not had any good idea yet, cdbdisp_destroyDispatcherState should not throw any exception by designing.

Thanks. I will dig into this problem and share my discover later.

**Comment by zxuejing** [comment]
thanks！

**Comment by zxuejing** [comment]
panic stack:
```
#0  0x00007faac73574fb in raise () from /data/logs/308185/packcore-postgres.669221.181669.core/lib64/libpthread.so.0
#1  0x0000000000bf51c0 in StandardHandlerForSigillSigsegvSigbus_OnMainThread (processName=<optimized out>, postgres_signal_arg=11) at elog.c:5581
#2  <signal handler called>
#3  pfree (pointer=0x759e3c8) at mcxt.c:1299
#4  0x0000000000c8d18a in cdbconn_termSegmentDescriptor (segdbDesc=segdbDesc@entry=0x759e3c8) at cdbconn.c:119
#5  0x0000000000cdf936 in cdbcomponent_recycleIdleQE (segdbDesc=0x759e3c8, forceDestroy=forceDestroy@entry=0 '\000') at cdbutil.c:930
#6  0x0000000000c9498f in RecycleGang (gp=0x7edcf08, forceDestroy=0 '\000') at cdbgang.c:943
#7  0x0000000000c8e14e in cdbdisp_destroyDispatcherState (ds=0x252db58) at cdbdisp.c:377
#8  0x0000000000c8e4f1 in cleanup_dispatcher_handle (h=<optimized out>) at cdbdisp.c:493
#9  cdbdisp_cleanupDispatcherHandle (owner=owner@entry=0x2241fa8) at cdbdisp.c:560
#10 0x0000000000c3238d in CdbResourceOwnerWalker (callback=0xc8e480 <cdbdisp_cleanupDispatcherHandle>, owner=0x2241fa8) at resowner.c:1375
#11 CdbResourceOwnerWalker (owner=<optimized out>, callback=callback@entry=0xc8e480 <cdbdisp_cleanupDispatcherHandle>) at resowner.c:1379
#12 0x0000000000c8e6d6 in AtAbort_DispatcherState () at cdbdisp.c:516
#13 0x000000000072d064 in AbortTransaction () at xact.c:3304
#14 0x000000000072fa85 in AbortCurrentTransaction () at xact.c:3979
#15 0x0000000000a88c50 in PostgresMain (argc=1, argv=argv@entry=0x1ff3eb8, dbname=<optimized out>, username=0x1ff3df8 "marchadm") at postgres.c:4999
#16 0x00000000006ae482 in BackendRun (port=0x1ff5e90) at postmaster.c:4828
#17 BackendStartup (port=0x1ff5e90) at postmaster.c:4485
#18 ServerLoop () at postmaster.c:1948
#19 0x0000000000a0f6b2 in PostmasterMain (argc=argc@entry=6, argv=argv@entry=0x1f991c0) at postmaster.c:1518
#20 0x00000000006b23f1 in main (argc=6, argv=0x1f991c0) at main.c:245
```

**Comment by kainwen** [comment]
Fixed by https://github.com/greenplum-db/gpdb/pull/13456 and https://github.com/greenplum-db/gpdb/pull/13448
