### ISSUE TITLE
Errors - After GP Cluster Expansion

### ISSUE THREAD

**Issue by PushkarArya** [greenplum-db/gpdb#13437]
Hi team
We have cluster if 32 Primary and 32 Mirror segments.
We extended same to 40 Primary and 40 Mirror.
After expansion successful, _our normal Greenplum functions started throwing below errors

SQL Error [XX000]: ERROR: transaction 1651265154-0000000064 at level 1 already processed (current level 0) (cdbtm.c:2424)  (seg10 10.189.10.177:6002 pid=111417) (cdbtm.c:2424)
  Where: PL/pgSQL function line 33 during exception cleanup

Can someone guide, what this means and probable cause of same.

**Comment by lij55** [comment]
Hi @PushkarArya ,

what about the Greenplum version that you are running? do you try to drop and re-create those functions?

**Comment by PushkarArya** [comment]
@lij55 - Thanks for Response.
Greenplum OSS version 6.17 is deployed.

We are trying to drop and recreate all Pgplsql functions, after extending cluster to 40 primary and 40 Mirror segments.

In Functions , 
1)We use all sort of Insert statements with complex views.
{ Also noticed that that Insert statement on complex view(drop and recreate view as well) gets stuck with the said error}
2) Sequences for generating IDs
3) All sort of analytical functions like partition over() and row_number()

**Comment by PushkarArya** [comment]
Due to this error , 
we had to revert the cluster back to 32 Primary and 32 Mirror segments.
After restoration , all Greenplum existing functions work normally.

Error thrown looks internal error of Greenplum and little can be understood by error description.

Would appreciate any guidance on same

**Comment by lij55** [comment]
Hi @PushkarArya 

> we had to revert the cluster back to 32 Primary and 32 Mirror segments.
how did you revert the cluster back? I don't think Greenplum provide decreasing cluster script. Did you re-create the cluster? if so, do you have tried to create a new cluster with 40P+40M?

I suspect it is gpexpand that didn't handle the internal state correctly but it would need more information to identify the root cause.

**Comment by PushkarArya** [comment]
Hi @lij55 

Below is the sequence of events while expanding cluster.

Initial Scenario:-
1) Current config of 32 Primary and 32 Mirror
2) Expanded cluster through gpexpand.
3) gpexpand re-config the cluster successfully to 40 Primary and 40 Mirror.
4) Started Tables redistribution.
5) It was quite slow and was taking too long.
6) Cancelled Table Distribution successfully.
7) We dropped and Recreated All Tables, Functions, Sequences to avoid data re-distribution.
8) We faced said error quoted in ticket

Fallback Scenario:-
1) When above said steps not successful, we re-installed Greenplum database with New config of 40 Primary and 40 Mirror ( thinking our gpexpand has gone wrong).
2) Re-installation Successful.
3) Started Gp-database.
4) Recreated All tables, Function, sequences.
5) We faced same error in Insert statements inside functions.

Fall Back Scenario:-
1) Re-installed Greenplum database back to 32 Primary and 32 Mirror.
2) Recreated All Tables, Functions, Sequences
3) Now all scripts and Greenplum functions execute normally

**Comment by lij55** [comment]
it is really strange issue if the same scrip works for 32p+m but fails for 40. do you mind giving more details about the failure of script? is it OK to upload it here? what's the error message at least? thanks!

**Comment by PushkarArya** [comment]
We tried replicating scenario in our Test environment and created 40+40 segments installation of Greenplum database.

We tried running our functions containing SQL statements, and surprisingly no errors encountered.

Now We are puzzled that why exact same process gave errors in Production.

One thing i noticed in production environment, Any SQL statement like DDL, DML was giving Interconnect time out error and then failed with internal errors.

Can interconnect be an issue when there are 80 segments in Cluster ???

**Comment by ashwinstar** [comment]
> Can interconnect be an issue when there are 80 segments in Cluster ???
Nope, shouldn't matter.

What was the type of interconnect used before and after expansion earlier when failure happened. If ic-proxy type was used, then need to follow steps to update the GUC to reflect new hosts name. If not done then can face interconnect issues refer https://gpdb.docs.pivotal.io/6-11/admin_guide/managing/proxy-ic.html. If interconnect used was udpifc / tcp then doesn't matter and not sure why faced the problem.
