### ISSUE TITLE
gpdb6x 什么情况替换 pg_internal.init 会导致gp挂掉？

### ISSUE THREAD

**Issue by Moonlightflower** [greenplum-db/gpdb#13449]
Greenplum version or build
gpdb6x_stable

OS version and uname -a
centos 7.5

autoconf options used ( config.status --config )
Installation information ( pg_config )
Expected behavior
什么情况替换 pg_internal.init 会导致gp挂掉？

Actual behavior

Step to reproduce the behavior
正常使用的过程，pg_internal.init 会出现更新的情况，但是有时候会导致master 进程故障。

**Comment by lij55** [comment]
Hi @Moonlightflower ,
"替换 pg_internal.init " 指的是手动替换吗? 还是pg_internal.init会自动更新?

**Comment by lij55** [comment]
closing jira as no update for long time. the crash is caused by the abnormal operation.
