### ISSUE TITLE
GP mirror segments collect xlogs , growing pg_xlog folder and slowing performance

### ISSUE THREAD

**Issue by sokolval** [greenplum-db/gpdb#13450]
### Greenplum version or build
PostgreSQL 9.4.24 (Greenplum Database 6.19.0 build dev) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609, 64-bit compiled on Sep 8 2021 17:27:53

### OS version and uname -a
Linux hostname 4.19.62-13 https://github.com/greenplum-db/gpdb/pull/1 SMP Mon Jul 29 17:22:59 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

### autoconf options used ( config.status --config )
./config.status --config
'--with-perl' '--with-python' '--without-gssapi' '--enable-gpcloud' '--with-libxml' '--with-system-tzdata=/usr/share/zoneinfo' '--prefix=/usr/local/gpdb' '--enable-ic-proxy' '--enable-gpperfmon' 'LDFLAGS=-L/usr/lib/jni/' '--with-pam' '--with-openssl'

### Installation information ( pg_config )
BINDIR = /usr/local/gpdb/bin
DOCDIR = /usr/local/gpdb/share/doc/postgresql
HTMLDIR = /usr/local/gpdb/share/doc/postgresql
INCLUDEDIR = /usr/local/gpdb/include
PKGINCLUDEDIR = /usr/local/gpdb/include/postgresql
INCLUDEDIR-SERVER = /usr/local/gpdb/include/postgresql/server
LIBDIR = /usr/local/gpdb/lib/x86_64-linux-gnu
PKGLIBDIR = /usr/local/gpdb/lib/x86_64-linux-gnu/postgresql
LOCALEDIR = /usr/local/gpdb/share/locale
MANDIR = /usr/local/gpdb/share/man
SHAREDIR = /usr/local/gpdb/share/postgresql
SYSCONFDIR = /etc/postgresql
PGXS = /usr/local/gpdb/lib/x86_64-linux-gnu/postgresql/pgxs/src/makefiles/pgxs.mk
CONFIGURE = '--build=x86_64-linux-gnu' '--prefix=/usr' '--includedir=/usr/local/gpdb/include' '--mandir=/usr/local/gpdb/share/man' '--infodir=/usr/local/gpdb/share/info' '--sysconfdir=/etc' '--localstatedir=/var' '--disable-silent-rules' '--libdir=/usr/local/gpdb/lib/x86_64-linux-gnu' '--libexecdir=/usr/local/gpdb/lib/x86_64-linux-gnu' '--disable-maintainer-mode' '--disable-dependency-tracking' '--with-perl' '--with-python' '--without-gssapi' '--disable-gpcloud' '--with-libxml' '--with-system-tzdata=/usr/share/zoneinfo' '--prefix=/usr/local/gpdb' '--enable-ic-proxy' '--enable-gpperfmon' 'LDFLAGS=-L/usr/lib/jni/' '--with-pam' '--with-openssl' 'build_alias=x86_64-linux-gnu' 'CFLAGS=-g -O2 -fstack-protector-strong -Wformat -Werror=format-security' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'CXXFLAGS=-g -O2 -fstack-protector-strong -Wformat -Werror=format-security'
CC = gcc
CPPFLAGS = -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2 -I/usr/local/gpdb/include
CFLAGS = -Wall -Wmissing-prototypes -Wpointer-arith -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fno-aggressive-loop-optimizations -Wno-unused-but-set-variable -Wno-address -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -std=gnu99 -Werror=uninitialized -Werror=implicit-function-declaration -I/usr/local/gpdb/include
CFLAGS_SL = -fPIC
LDFLAGS = -L/usr/lib/jni/ -Wl,--as-needed -Wl,-rpath,'/usr/local/gpdb/lib/x86_64-linux-gnu',--enable-new-dtags -L/usr/local/gpdb/lib/x86_64-linux-gnu
LDFLAGS_EX = 
LDFLAGS_SL = 
LIBS = -lpgcommon -lpgport -lxerces-c -lxml2 -lpam -lrt -luv -lzstd -lrt -lcrypt -ldl -lm -L/usr/local/gpdb/lib/x86_64-linux-gnu
VERSION = PostgreSQL 9.4.26

### Expected behavior
In case of restart of cluster, after startup all primaries and mirrors working normally, pg_xlog on mirrors gets supplied with data.

### Actual behavior
For some cases during restart, mirror is unable to get stopped, after that it starts collecting new logs without applying them and causing pg_xlog folder on mirrors to grow indefinitely. pg_xlog grows starting from 1.5-1.9 GB - normal size to 291 GB and more. 
The pg_ctls stop -D /..../.. does not help to stop mirror. Mirror then can only be killed with -9 level
Additional symptom here: it seems due to such behavior the cluster experiences some issues with proper levraging the lload, and queries start running slower than usual, causing queues in resource groups.
### Step to reproduce the behavior
It is reproduced rather regular - few times a week, when cluster is restarted under heavy pressure. It is hardly reproducible manually.

**Comment by lij55** [comment]
Hi @sokolval ,

could you provide a bit more details when it happens next time:
- mirror log which failed to stop
- master log
- strace of the mirror progress
- `select * from pg_segment_configuration`
thanks

**Comment by sokolval** [comment]
Still the case was not reproduced so far. Apart from that my colleagues suggested that this is potentially fixed in GP version 6.19.4.
I will keep the issue opened until issue reproduced or we upgrade to latest version and observe for 2 weeks.

**Comment by sokolval** [comment]
Hello!
We faced the situation again.
More detailed symptoms are:
Process checkpointer on the mirrors collecting logs also consumes a lot of CPU: eg (50xx are mirror ports):
`ps -ef | grep checkpointer
gpadmin  454996  454105  0 11:52 pts/5    00:00:00 grep --color=auto checkpointer
gpadmin  639029  639014  0 Jun03 ?        00:00:23 postgres:  4001, checkpointer process   
gpadmin  639034  639018  0 Jun03 ?        00:00:24 postgres:  4002, checkpointer process   
gpadmin  639039  639016  0 Jun03 ?        00:00:23 postgres:  4000, checkpointer process   
gpadmin  639061  639019  0 Jun03 ?        00:01:05 postgres:  5000, checkpointer process   
gpadmin  639069  639015  0 Jun03 ?        00:01:07 postgres:  5001, checkpointer process   
**gpadmin  639073  639017 98 Jun03 ?        12:33:07 postgres:  5002, checkpointer process **
`
and on another host:
`ps -ef | grep checkpointer


gpadmin  573562  459905  0 11:59 pts/5    00:00:00 grep --color=auto checkpointer
gpadmin  720645  720635  0 Jun03 ?        00:00:24 postgres:  4000, checkpointer process   
gpadmin  720650  720632  0 Jun03 ?        00:00:23 postgres:  4001, checkpointer process   
gpadmin  720674  720631  0 Jun03 ?        00:01:00 postgres:  5002, checkpointer process   
**gpadmin  720678  720630 98 Jun03 ?        12:44:28 postgres:  5000, checkpointer process**   
gpadmin  720688  720633  0 Jun03 ?        00:01:03 postgres:  5001, checkpointer process   
gpadmin  720700  720634  0 Jun03 ?        00:00:23 postgres:  4002, checkpointer process `

Through strace output it seems that checkpointer fails to read some file and falls into indefinite loop.
Attached the straces: seg46 - is the mirror which suffers. seg49 - is normal mirror



[ps-ef_output.txt](https://github.com/greenplum-db/gpdb/files/8837469/ps-ef_output.txt)
[checkpointer_seg46_strace.txt](https://github.com/greenplum-db/gpdb/files/8837472/checkpointer_seg46_strace.txt)
[checkpointer_seg46_strace1.txt](https://github.com/greenplum-db/gpdb/files/8837473/checkpointer_seg46_strace1.txt)
[checkpointer_seg49_strace.txt](https://github.com/greenplum-db/gpdb/files/8837474/checkpointer_seg49_strace.txt)
[mirror_seg46_strace.txt](https://github.com/greenplum-db/gpdb/files/8837478/mirror_seg46_strace.txt)
[startup_log_extract.txt](https://github.com/greenplum-db/gpdb/files/8837468/startup_log_extract.txt)
[log_before_checkpointer_hangup.txt](https://github.com/greenplum-db/gpdb/files/8837475/log_before_checkpointer_hangup.txt)
[log_on_another_segment.txt](https://github.com/greenplum-db/gpdb/files/8837476/log_on_another_segment.txt)
[log_on_normal_day.txt](https://github.com/greenplum-db/gpdb/files/8837477/log_on_normal_day.txt)

**Comment by Stolb27** [comment]
@sokolval, the strace output is very close to a description of https://github.com/greenplum-db/gpdb/pull/13165.

**Comment by maksm90** [comment]
> @sokolval, the strace output is very close to the description of https://github.com/greenplum-db/gpdb/pull/13165. This fix was included in 6.19.4/6.20+.

yes, fix is in that PR.

**Comment by ashwinstar** [comment]
Closing this issue. Please upgrade to the latest greenplum version.
