### ISSUE TITLE
ERROR: cache lookup failed for attribute 0 of relation xxx (lsyscache.c:943). when SELECT DISTINCT <father_table> FROM <father_table>

### ISSUE THREAD

**Issue by lmzzzzz1** [greenplum-db/gpdb#13467]
## Bug Report
select distinct <table_name> from <table_name> when table is a father table (partition table and Inheritance table)

### Greenplum version or build
master branch(GP7-alpha)
6X_STABLE

### configure
compile without orca
 ./configure --disable-orca  --enable-cassert --enable-debug --with-perl  --with-python --with-libxml --with-gssapi --prefix=/home/tpch/workspace/gpdb/workspace CFLAGS="-gdwarf-2 -g3 -O0"

### Expected behavior
```
        cities
----------------------
 ("New York",2e+07,1)
(1 rows)
```

### Actual behavior
```
ERROR:  cache lookup failed for attribute 0 of relation 16433 (lsyscache.c:943)
```

### Step to reproduce the behavior

```
CREATE TABLE cities (
  name       text,
  population real,
  elevation  int     -- (in ft)
);

CREATE TABLE capitals (
  state      char(2) UNIQUE NOT NULL
) INHERITS (cities);

insert into cities values ('New York', 20000000, 1);
-- gp_statistics_pullup_from_child_partition is default off in GP7 while is set to 'on' in 6X_STABLE
set gp_statistics_pullup_from_child_partition to on;
select distinct cities from cities;
```

**Comment by kainwen** [comment]
6X still has this issue. We are backporting this to 6X, after that, then let's close this issue.

**Comment by lmzzzzz1** [comment]
> 6X still has this issue. We are backporting this to 6X, after that, then let's close this issue.

👌

**Comment by kainwen** [comment]
Fixed by

* master https://github.com/greenplum-db/gpdb/pull/13468
* 6x https://github.com/greenplum-db/gpdb/pull/13490
