### ISSUE TITLE
run tpc-h query 2 timeout

### ISSUE THREAD

**Issue by digoal** [greenplum-db/gpdb#135]
HI,
   in my test environment ,run tpc-h query 2 timeout. this is the test machine and gp configure.
   HARDware 
   24 CORE
   192G mem
   FUSINO IO ssd

   GREENPLUm:
   4.3.6
   1 master
   12 segments
   master parameter
port=1921 ##port = 5432                         # sets the database listener port for 
max_connections = 48                    # inserted by initdb
shared_buffers = 1024MB                 # inserted by initdb
max_prepared_transactions = 250         # can be 0 or more
max_fsm_pages = 1638400                 # inserted by initdb
optimizer_analyze_root_partition = on # stats collection on root partitions
gp_autostats_mode=on_no_stats           # none, on_no_stats, on_change. see documentation for semantics.
gp_autostats_on_change_threshold=2147483647 # [0..INT_MAX]. see documentation for semantics.
log_autostats=off       # print additional autostats information
datestyle = 'iso, mdy'                  # inserted by initdb
lc_messages = 'C'                       # inserted by initdb
lc_monetary = 'C'                       # inserted by initdb
lc_numeric = 'C'                        # inserted by initdb
lc_time = 'C'                           # inserted by initdb
gp_resqueue_memory_policy = 'eager_free'        # memory request based queueing. 
max_appendonly_tables = 10000 # Maximum number of append only tables that can 
gp_interconnect_type=udpifc
gp_connections_per_thread = 64
gp_segment_connect_timeout = 600s
gp_vmem_protect_limit = 8192  #Virtual memory limit (in MB).
gp_backup_directIO = off                                # enable\disable dump with direct IO
gp_backup_directIO_read_chunk_mb = 20   # Size of read Chunk buffer in directIO dump (in MB)
checkpoint_segments=64
log_min_error_statement=error
log_error_verbosity=verbose
log_statement=all
log_duration=on
enable_nestloop=off
work_mem=256MB

   segment parameter
listen_addresses='*' ##listen_addresses = '*'           # what IP address(es) to listen on;
port=40000 ##port = 5432                                # sets the database listener port for 
max_connections = 144                   # inserted by initdb
shared_buffers = 1024MB                 # inserted by initdb
max_prepared_transactions = 250         # can be 0 or more
max_fsm_pages = 1638400                 # inserted by initdb
optimizer_analyze_root_partition = on # stats collection on root partitions
gp_autostats_mode=on_no_stats           # none, on_no_stats, on_change. see documentation for semantics.
gp_autostats_on_change_threshold=2147483647 # [0..INT_MAX]. see documentation for semantics.
log_autostats=off       # print additional autostats information
datestyle = 'iso, mdy'                  # inserted by initdb
lc_messages = 'C'                       # inserted by initdb
lc_monetary = 'C'                       # inserted by initdb
lc_numeric = 'C'                        # inserted by initdb
lc_time = 'C'                           # inserted by initdb
gp_resqueue_memory_policy = 'eager_free'        # memory request based queueing. 
max_appendonly_tables = 10000 # Maximum number of append only tables that can 
gp_interconnect_type=udpifc
gp_connections_per_thread = 64
gp_segment_connect_timeout = 600s
gp_vmem_protect_limit = 8192  #Virtual memory limit (in MB).
gp_backup_directIO = off                                # enable\disable dump with direct IO
gp_backup_directIO_read_chunk_mb = 20   # Size of read Chunk buffer in directIO dump (in MB)
checkpoint_segments=64
log_min_error_statement=error
log_error_verbosity=verbose
log_statement=all
log_duration=on
enable_nestloop=off
work_mem=256MB
   

   os centos 6 x64

   tpch use https://github.com/digoal/pg_tpch
   test data use http://www.tpc.org/tpch/tools_download/dbgen-download-request.asp generate.
   1 GB data.

   test case
   http://blog.163.com/digoal@126/blog/static/16387704020151019111930303/

**Comment by yydzero** [comment]
Hi Digoal,

Thanks for reporting this.

Could  you please attach the log? Thanks!

On Wed, Dec 2, 2015 at 10:28 AM, Digoal.zhou <notifications@github.com>
wrote:

> HI,
> in my test environment ,run tpc-h query 2 timeout. this is the test
> machine and gp configure.
> HARDware
> 24 CORE
> 192G mem
> FUSINO IO ssd
>
> GREENPLUm:
> 4.3.6
> 1 master
> 12 segments
> master parameter
> port=1921 ##port = 5432 # sets the database listener port for
> max_connections = 48 # inserted by initdb
> shared_buffers = 1024MB # inserted by initdb
> max_prepared_transactions = 250 # can be 0 or more
> max_fsm_pages = 1638400 # inserted by initdb
> optimizer_analyze_root_partition = on # stats collection on root partitions
> gp_autostats_mode=on_no_stats # none, on_no_stats, on_change. see
> documentation for semantics.
> gp_autostats_on_change_threshold=2147483647 # [0..INT_MAX]. see
> documentation for semantics.
> log_autostats=off # print additional autostats information
> datestyle = 'iso, mdy' # inserted by initdb
> lc_messages = 'C' # inserted by initdb
> lc_monetary = 'C' # inserted by initdb
> lc_numeric = 'C' # inserted by initdb
> lc_time = 'C' # inserted by initdb
> gp_resqueue_memory_policy = 'eager_free' # memory request based queueing.
> max_appendonly_tables = 10000 # Maximum number of append only tables that
> can
> gp_interconnect_type=udpifc
> gp_connections_per_thread = 64
> gp_segment_connect_timeout = 600s
> gp_vmem_protect_limit = 8192 #Virtual memory limit (in MB).
> gp_backup_directIO = off # enable\disable dump with direct IO
> gp_backup_directIO_read_chunk_mb = 20 # Size of read Chunk buffer in
> directIO dump (in MB)
> checkpoint_segments=64
> log_min_error_statement=error
> log_error_verbosity=verbose
> log_statement=all
> log_duration=on
> enable_nestloop=off
> work_mem=256MB
>
> segment parameter
> listen_addresses='*' ##listen_addresses = '*' # what IP address(es) to
> listen on;
> port=40000 ##port = 5432 # sets the database listener port for
> max_connections = 144 # inserted by initdb
> shared_buffers = 1024MB # inserted by initdb
> max_prepared_transactions = 250 # can be 0 or more
> max_fsm_pages = 1638400 # inserted by initdb
> optimizer_analyze_root_partition = on # stats collection on root partitions
> gp_autostats_mode=on_no_stats # none, on_no_stats, on_change. see
> documentation for semantics.
> gp_autostats_on_change_threshold=2147483647 # [0..INT_MAX]. see
> documentation for semantics.
> log_autostats=off # print additional autostats information
> datestyle = 'iso, mdy' # inserted by initdb
> lc_messages = 'C' # inserted by initdb
> lc_monetary = 'C' # inserted by initdb
> lc_numeric = 'C' # inserted by initdb
> lc_time = 'C' # inserted by initdb
> gp_resqueue_memory_policy = 'eager_free' # memory request based queueing.
> max_appendonly_tables = 10000 # Maximum number of append only tables that
> can
> gp_interconnect_type=udpifc
> gp_connections_per_thread = 64
> gp_segment_connect_timeout = 600s
> gp_vmem_protect_limit = 8192 #Virtual memory limit (in MB).
> gp_backup_directIO = off # enable\disable dump with direct IO
> gp_backup_directIO_read_chunk_mb = 20 # Size of read Chunk buffer in
> directIO dump (in MB)
> checkpoint_segments=64
> log_min_error_statement=error
> log_error_verbosity=verbose
> log_statement=all
> log_duration=on
> enable_nestloop=off
> work_mem=256MB
>
> os centos 6 x64
>
> tpch use https://github.com/digoal/pg_tpch
> test data use
> http://www.tpc.org/tpch/tools_download/dbgen-download-request.asp
> generate.
> 1 GB data.
>
> test case
> http://blog.163.com/digoal@126/blog/static/16387704020151019111930303/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/greenplum-db/gpdb/issues/135>.
>



-- 
Best Regards,
Yandong

**Comment by digoal** [comment]
the tpch log.

**Comment by yydzero** [comment]
Thanks Digoal!

On Thu, Dec 3, 2015 at 1:42 PM, Digoal.zhou <notifications@github.com>
wrote:

> the tpch log.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/greenplum-db/gpdb/issues/135#issuecomment-161522761>.
>



-- 
Best Regards,
Yandong

**Comment by digoal** [comment]
It's a optimal problem, the test case use diffient data type for join, (int8 join int4) and Greenplum cann't use hash join when join int8 and int4, so timeout.
when i change all the join key to int8, it's ok now.
thanks .

**Comment by hlinnaka** [comment]
Hmm, I think that was fixed in the upstream in commit a635c08fa10fe545d723bcec6eb73bfdca07e2c0. That was in PostgreSQL 8.3, and it's actually coming up fairly soon in the 8.3 merge. So stay tuned!

**Comment by ashwinstar** [comment]
Closing issue as we know no further action here since issue will be fixed by 8.3 merge, not sure we already have it or coming up soon.
