### ISSUE TITLE
Failed to build on Ubuntu 22.04 with ORCA enabled

### ISSUE THREAD

**Issue by adam8157** [greenplum-db/gpdb#13514]
### Greenplum version or build

the master branch

### OS version and uname -a

Ubuntu 22.04 LTS (GNU/Linux 5.15.0-30-generic x86_64)
Linux minion 5.15.0-30-generic #31-Ubuntu SMP Thu May 5 10:00:34 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Actual behavior
```
libxerces-c-dev is already the newest version (3.2.3+debian-3build1).
libxerces-c3.2 is already the newest version (3.2.3+debian-3build1).
```

configure: error: library xerces-c is required to build with GPORCA

**Comment by ashwinstar** [comment]
@l-wang ideas?

**Comment by l-wang** [comment]
Hi @adam8157 I'm also on Ubuntu 22.04 and have not seen the problem.
```
$ uname -a
Linux station3 5.15.0-30-generic #31-Ubuntu SMP Thu May 5 10:00:34 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

May I have your configure options? Here's mine:
```
$ ./config.status --config
'--enable-depend' '--enable-debug' '--enable-cassert' '--with-perl' '--with-python' '--with-libxml' '--prefix' '/usr/local/gpdb' 'CC=clang-14' 'CXX=clang++-14' 'CFLAGS=-O0 -fno-omit-frame-pointer' 'CPPFLAGS=-O0 -fno-omit-frame-pointer'
```

Do you know where is your libxerces installed? Here's mine:
```
$ dpkg -L libxerces-c3.2
/.
/usr
/usr/lib
/usr/lib/x86_64-linux-gnu
/usr/lib/x86_64-linux-gnu/libxerces-c-3.2.so
/usr/share
/usr/share/doc
/usr/share/doc/libxerces-c3.2
/usr/share/doc/libxerces-c3.2/NEWS.Debian.gz
/usr/share/doc/libxerces-c3.2/NOTICE
/usr/share/doc/libxerces-c3.2/changelog.Debian.gz
/usr/share/doc/libxerces-c3.2/copyright
/usr/share/lintian
/usr/share/lintian/overrides
/usr/share/lintian/overrides/libxerces-c3.2
```

**Comment by adam8157** [comment]
My fault, I have a 3.1 version in `/usr/local/lib`, sorry. Removing them fixes the issue.

and my config is `CFLAGS="-O0 -g3" ./configure --prefix=`echo ~`/greenplum-db-devel --disable-pxf --disable-gpcloud --enable-orca --enable-ic-proxy --enable-cassert --enable-debug --enable-depend --enable-gpfdist --with-gssapi --with-libxml --with-openssl --with-python --with-zstd --with-includes=/usr/local/include --with-libraries=/usr/local/lib`
