### ISSUE TITLE
SEG node cannot sense detection disable detector

### ISSUE THREAD

**Issue by hashdatawang** [greenplum-db/gpdb#13516]
Question 1：On the segment node, is it necessary to disable the sensing detector

Question 2：If the detector is disabled, it needs to be broadcast to all segment nodes. Where to broadcast this message

**Comment by ashwinstar** [comment]
Apart from segment node, no other term used reads Greenplum specific. Please can you elaborate.

**Comment by lij55** [comment]
Hi @hashdatawang ,
could you please explain a bit more about what 'sensing detector' means?

**Comment by ashwinstar** [comment]
Closing, given not enough information to help.
