### ISSUE TITLE
Does greenplum database support \copy syntax?

### ISSUE THREAD

**Issue by yst001** [greenplum-db/gpdb#13511]
In the process of developing with greenplum database, I encountered the need to import the data of the local csv file into the remote greenplum database, but there was a syntax error in the process of using the \copy command.

<img width="397" alt="截屏2022-05-17 17 30 48" src="https://user-images.githubusercontent.com/44132305/168779219-b7111a3a-8328-44cd-bf31-b9219813fdea.png">

Is it because the greenplum database does not support the \copy syntax? Besides uploading the file to the database server, is there any other workaround?

**Comment by adam8157** [comment]
`\copy` is a `psql` command, Greenplum supports it. But the screenshot doesn't look like a `psql` interface.

Use `psql`, external/foreign tables, or `COPY FROM PROGRAM` ... ...

**Comment by yst001** [comment]
> `\copy` is a `psql` command, Greenplum supports it. But the screenshot doesn't look like a `psql` interface.
> 
> Use `psql`, external/foreign tables, or `COPY FROM PROGRAM` ... ...

thank you
