### ISSUE TITLE
fmt = (char*)malloc(sizeof(Length))

### ISSUE THREAD

**Issue by woshiniuren** [greenplum-db/gpdb#13573]
## Bug Report
Hi, guys ,I found many code in gpdb write similar like "fmt = (char*)malloc(sizeof(Length))", because this is in C not C++, maybe this one  "fmt = malloc(sizeof(Length))" is better ?

### Greenplum version or build
7.0.0

### OS version and uname -a
centos 7.9

**Comment by Aegeaner** [comment]
The `malloc()` return a void pointer to the allocated memory or NULL(if allocation failed). If a pointer to void is assigned to a pointer to any type other than a character type, an narrowing conversion will occur, it can be either implicit or explicit, both are ok.

**Comment by woshiniuren** [comment]
> 

in the standard, A void pointer can be converted to/from any other pointer type without an explicit cast (C11 6.3.2.3 and 6.5.16.1), this cast can leave to compilers do . I noticed that ,the gpdb may use the C89 compiler to build the binaries,which if we forget use #include<stdlib.h>,the malloc functions may have some side effect.

**Comment by Aegeaner** [comment]
A pointer to void converting to other pointer types without an explicit cast is surely OK. Currently GPDB is compiled under C99 standard.

**Comment by kainwen** [comment]
Plenty of this style of code appear in Postgres's latest master branch, I do not think it is a problem.

Close this issue. Might be better to open a thread to postgres hacker mailing list first.

Thanks.
