### ISSUE TITLE
40G size files in base directory 

### ISSUE THREAD

**Issue by JlA3APb** [greenplum-db/gpdb#13592]
## Bug Report
After a few recovery issues in GP cluster causer by network problems I found a lot of 40G size files in primary segments base directories  on crushed datanodes. For example /data/primary/gpseg31/base/1704516/5832442.1 These files contains no tables from database just consuming place on hard drive. Deleting these files from base directory has no effect on any data in database or Greenplum cluster. After deleting these files and resynchronizing data from primary to mirrors segment everything works fine.

The question is: what kind of operation inside Greenplum generates this 40G files in base directory? Maybe someone could explain a mechanism of creating these files when GP has a network interconnect problem.

I'll be appreciate for any answer or link to the proper information source about this issue.

**Comment by lij55** [comment]
Hi @JlA3APb , how do you know the big file is created during recory process? it seems to be the AO table according to the name.
what's your Greenplum version?

**Comment by ashwinstar** [comment]
Database doesn't auto create these files. Has to user action driving the creation of the table/relation files. If the server crashes while CTAS and such big table creation with insert/load was happening it could lead to leaving orphan files from those tables. Would be greatly helpful if next time issue happens, perform xlogdump and trace to which records these files belong that should help to identify the source for these files. As of now we don't have enough information to help identify.
