### ISSUE TITLE
Enable gp_vmem_protect_limit on master?

### ISSUE THREAD

**Issue by dreamedcheng** [greenplum-db/gpdb#13598]
I noticed that `gp_vmem_protect_limit` only works on segment, but in some extreme cases, master can also consume a large amount of memory footprint. I think this GUC should also take effect on master. So, do we have plan on it?

```
         /*
	 * If segment vmem is exhausted, rollback query level reservation. For non-QE
	 * processes and processes in critical section, we don't enforce VMEM, but we
	 * do track the usage.
	 */
	if (new_vmem > vmemLimitChunks &&
			Gp_role == GP_ROLE_EXECUTE && CritSectionCount == 0)
	{
		if (new_vmem > vmemLimitChunks + waivedChunks)
		{
			/* Revert query memory reservation */
			pg_atomic_sub_fetch_u32((pg_atomic_uint32 *)&MySessionState->sessionVmem, numChunksToReserve);
			/* Revert vmem reservation */
			pg_atomic_sub_fetch_u32((pg_atomic_uint32 *)segmentVmemChunks, numChunksToReserve);
			/* Revert resgroup memory reservation */
			ResGroupReleaseMemory(numChunksToReserve);

			return MemoryFailure_VmemExhausted;
		}
		waiverUsed = true;
	}
```

**Comment by lij55** [comment]
Hi @dreamedcheng , the segment and master management are slight different. 

- Single master run the single host while several segment shares one host.
- master host is often more powerful (more memories) than segment in production

it is a very reasonable request to limit the master memory usage but it doesn't make sense to share the same value as the segment. so closing this issue.
