### ISSUE TITLE
should GetTupleVisibilitySummary take multixact into consideration?

### ISSUE THREAD

**Issue by FateTHarlaown** [greenplum-db/gpdb#13625]
GetTupleVisibilitySummary directly use xmax of aocsseg tuple to search clog for transaction status. If xmax is a multi xact id, maybe we can't find the clog? Should we take multixact into consideration
```
tupleVisibilitySummary->xmax = HeapTupleHeaderGetRawXmax(tuple->t_data);
	if (!TransactionIdIsNormal(tupleVisibilitySummary->xmax))
	{
		if (tupleVisibilitySummary->xmax == FrozenTransactionId)
		{
			tupleVisibilitySummary->xmaxStatus = TupleTransactionStatus_Frozen;
		}
		else
		{
			tupleVisibilitySummary->xmaxStatus = TupleTransactionStatus_None;
		}
	}
	else if (tuple->t_data->t_infomask & HEAP_XMAX_COMMITTED)
	{
		tupleVisibilitySummary->xmaxStatus = TupleTransactionStatus_HintCommitted;
	}
	else if (tuple->t_data->t_infomask & HEAP_XMAX_INVALID)
	{
		tupleVisibilitySummary->xmaxStatus = TupleTransactionStatus_HintAborted;
	}
	else
	{
		tupleVisibilitySummary->xmaxStatus =
			GetTupleVisibilityCLogStatus(tupleVisibilitySummary->xmax);
	}
```

**Comment by ashwinstar** [comment]
Have test case in mind to showcase the problem?

**Comment by FateTHarlaown** [comment]
@ashwinstar  my gpdb instance report can't find clog here when select * from a aocs table,  but i don't konw how to reproduce. I used gdb to print the tuple's hint and xmax, it's like this
![image](https://user-images.githubusercontent.com/15060840/172297582-815c3c01-b0f0-4c63-84a9-6f92c80607ef.png)

0x1000 is HEAP_XMAX_IS_MULTI， it seems it's a lock, but I don't know how it become like this in aocs table

**Comment by FateTHarlaown** [comment]
then it use 35 as transaction id to get clog in GetTupleVisibilityCLogStatus and can't find the clog

**Comment by FateTHarlaown** [comment]
I'm not sure, is it a problem?

**Comment by FateTHarlaown** [comment]
https://github.com/greenplum-db/gpdb/pull/11532
