### ISSUE TITLE
Why we do not support update/delete with higher isolation on AO/AOCS tables?

### ISSUE THREAD

**Issue by wangxuqi** [greenplum-db/gpdb#13651]
## Delete/Update with higher isolation is not supported on AO/AOCS tables
Since Delete/Update on AO/AOCS tables has already hold an Exclusive Lock on the relation. That means we will do
Delete/Update in serializable. So I think even in higher isolation level,  we can do these behavior safely. I want to
known why we disable it.

### Code
```
if (IsolationUsesXactSnapshot())
  {
    if (forUpdate)
      ereport(ERROR,
        (errcode(ERRCODE_FEATURE_NOT_SUPPORTED),
         errmsg("updates on append-only tables are not supported in serializable transactions")));
    else
      ereport(ERROR,
         (errcode(ERRCODE_FEATURE_NOT_SUPPORTED),
         errmsg("deletes on append-only tables are not supported in serializable transactions")));
  }

```

### Actual behavior
```
CREATE TABLE foo (a INT, b INT, c CHAR(128)) WITH (appendonly=true);
INSERT INTO foo SELECT i as a, i as b, 'hello world' as c FROM generate_series(1,1000) AS i;
BEGIN TRANSACTION ISOLATION LEVEL SERIALIZABLE;
DELETE FROM foo WHERE a < 4;
ERROR:  deletes on append-only tables are not supported in serializable transactions  (seg0 gesameistd1m1.corp.emc.com:40000 pid=96582)
```

**Comment by ashwinstar** [comment]
Serializable aspect is different from locking. Locking takes effect only when one starts to operate on the this specific table. Though the snapshot for serializable table is taken at start of the transaction. So, between the time this transaction snapshot is taken and ExclusiveLock is still to acquired on this table, lot can happen (like concurrent inserts or deletes to this table by other transaction which makes it difficult to support Serializable deletes/updates for AO tables as visibility of many rows in controlled by single tuple in visimap unlike heaptuple which can carry per tuple visibility information.)

**Comment by wangxuqi** [comment]
> Serializable aspect is different from locking. Locking takes effect only when one starts to operate on the this specific table. Though the snapshot for serializable table is taken at start of the transaction. So, between the time this transaction snapshot is taken and ExclusiveLock is still to acquired on this table, lot can happen (like concurrent inserts or deletes to this table by other transaction which makes it difficult to support Serializable deletes/updates for AO tables as visibility of many rows in controlled by single tuple in visimap unlike heaptuple which can carry per tuple visibility information.)

OK. thank you for answer my question. I have got the point. Close this issue.

**Comment by wangxuqi** [comment]
> Serializable aspect is different from locking. Locking takes effect only when one starts to operate on the this specific table. Though the snapshot for serializable table is taken at start of the transaction. So, between the time this transaction snapshot is taken and ExclusiveLock is still to acquired on this table, lot can happen (like concurrent inserts or deletes to this table by other transaction which makes it difficult to support Serializable deletes/updates for AO tables as visibility of many rows in controlled by single tuple in visimap unlike heaptuple which can carry per tuple visibility information.)

OK. thank you for answer my question. I have got the point. Close this issue.
