### ISSUE TITLE
Installation on something newer than Ubuntu 18.04

### ISSUE THREAD

**Issue by alexey-milovidov** [greenplum-db/gpdb#13732]
## Feature Request

There are multiple installation manuals like this:
https://greenplum.org/install-greenplum-oss-on-ubuntu/
https://docs.vmware.com/en/VMware-Tanzu-Greenplum/6/greenplum-database/GUID-install_guide-install_gpdb.html

But all of them are only applicable for Ubuntu 18.04.
Also, I cannot find Docker examples.

**Comment by RekGRpth** [comment]
I successfully build 7 and 6 versions inside [gpdb ubuntu:latest docker](https://github.com/RekGRpth/gpdb.docker)

**Comment by lij55** [comment]
Hi @alexey-milovidov ,

doesn't below steps work for you?

```
sudo apt install -y build-essential git bison  flex

sudo apt install -y pkg-config libzstd-dev python3 python3-dev libreadline-dev libapr1-dev libevent-dev libcurl4-openssl-dev libbz2-dev libxerces-c-dev iproute2  iputils-ping python3-psutil python3-pip

sudo   pip3 install  pygresql

./configure --prefix=/opt/gpdb7
make && make install
```
