### ISSUE TITLE
memory leak when insert/copy  to a partition table 

### ISSUE THREAD

**Issue by JingYanchao** [greenplum-db/gpdb#13736]
## Bug Report
memory leak when insert/copy  to a partition table 

### Greenplum version or build
6.16.2 & 6.21.0

### OS version and uname -a
Centos7.0

### Expected behavior
the connection on the segment should not have memory leak

### Actual behavior

the connection on the segment  have memory leak

### Step to reproduce the behavior

firstly I deploy a greenplum cluster (two segment, 4c16g)

then create a partition table with index
```
CREATE TABLE public.test_part (
    id bigint NOT NULL,
    is_active smallint,
    time_timestamp timestamp without time zone NOT NULL
)
 DISTRIBUTED BY (id, time_timestamp) PARTITION BY RANGE(time_timestamp)
          (
          PARTITION pn_1 START ('2022-04-01 00:00:00'::timestamp without time zone) END ('2022-05-01 00:00:00'::timestamp without time zone) EVERY ('30 days'::interval) WITH (tablename='test_part_1_prt_pn_1', appendonly='false' ),
          PARTITION pn_2 START ('2022-05-01 00:00:00'::timestamp without time zone) END ('2022-05-31 00:00:00'::timestamp without time zone) EVERY ('30 days'::interval) WITH (tablename='test_part_1_prt_pn_2', appendonly='false' ),
          PARTITION pn_3 START ('2022-05-31 00:00:00'::timestamp without time zone) END ('2022-06-30 00:00:00'::timestamp without time zone) EVERY ('30 days'::interval) WITH (tablename='test_part_1_prt_pn_3', appendonly='false' ),
          PARTITION pn_1_20220630 START ('2022-06-30 00:00:00'::timestamp without time zone) END ('2022-07-01 00:00:00'::timestamp without time zone) WITH (tablename='test_part_1_prt_pn_1_20220630', appendonly='false' ),
          PARTITION pn_1_20220701 START ('2022-07-01 00:00:00'::timestamp without time zone) END ('2022-07-02 00:00:00'::timestamp without time zone) WITH (tablename='test_part_1_prt_pn_1_20220701', appendonly='false' ),
          PARTITION pn_1_20220702 START ('2022-07-02 00:00:00'::timestamp without time zone) END ('2022-07-03 00:00:00'::timestamp without time zone) WITH (tablename='test_part_1_prt_pn_1_20220702', appendonly='false' ),
          DEFAULT PARTITION pdefault  WITH (tablename='test_part_1_prt_pdefault', appendonly='false' )
          );


ALTER TABLE public.test_part OWNER TO gpadmin;

ALTER TABLE ONLY public.test_part
    ADD CONSTRAINT test_part_pkey PRIMARY KEY (id, time_timestamp);

CREATE INDEX test_index ON public.test_part USING btree (is_active);
```

and then I use pgbench to insert, the insert sql is 
```
\set scale 11424
\set nbranches 1 * :scale
\set ntellers 10 * :scale
\set naccounts 1000 * :scale
\setrandom aid 1 :naccounts
\setrandom bid 1 :nbranches
\setrandom tid 1 :ntellers

set optimizer = off;
INSERT INTO test_part (id,is_active,time_timestamp) VALUES (:tid, :bid, now());
```

then I start 
```
./pgbench -r -n -c 1 -j 1 -T 1200000 -f insert.sql -U gpadmin postgres
```

then log in the segment node we can see that the memory of the connection grow slowly
<img width="926" alt="image" src="https://user-images.githubusercontent.com/11496193/175959643-42f4a07f-7b38-44c6-9209-f7bc515295a8.png">

when the core version is 6.16.2, the memory grow more faster。
when the core version  is 6.21.0, better，but still leak

I need help

**Comment by kainwen** [comment]
@JingYanchao 
Hi, would you please re-test your mem-leak reproduce with optimizer on and then with optimizer off, then post result here?

```
gpconfig -c optimizer -v off;
gpstop -u
psql -c "show optimizer"
run you test. ...

----------

gpconfig -c optimizer -v on;
gpstop -u
psql -c "show optimizer"
run you test...
```

Thanks.

**Comment by JingYanchao** [comment]
> @JingYanchao Hi, would you please re-test your mem-leak reproduce with optimizer on and then with optimizer off, then post result here?
> 
> ```
> gpconfig -c optimizer -v off;
> gpstop -u
> psql -c "show optimizer"
> run you test. ...
> 
> ----------
> 
> gpconfig -c optimizer -v on;
> gpstop -u
> psql -c "show optimizer"
> run you test...
> ```
> 
> Thanks.

Thanks for your suggestion， We find that when the core version is 6.21.0，the memory of the  conn would become stable after a long time. So we believe it should be solved.

For the 6.16.2, after I merge the pr #12184 and pr# 13411  this problem Looks like be solved too.

Maybe I could close this issue after observing for a while.
Thanks

**Comment by JingYanchao** [comment]
solved
