### ISSUE TITLE
custom operator priority

### ISSUE THREAD

**Issue by effective996** [greenplum-db/gpdb#13771]
I created an operator // to replace /, but I found that the priority is wrong in the 2+3//2 case. How do I fix it

**Comment by effective996** [comment]
create or replace function div_zero(double precision, double precision) returns double precision as
' select case when $2 & <> 0 then $1/$2 else null end ;
' language sql strict
               immutable;

create operator // (procedure = div_zero, leftarg = double precision, rightarg = double precision);

**Comment by kainwen** [comment]
This part GP is not special from Postgres.

See the doc of Postgres:

[1] https://www.postgresql.org/docs/current/sql-syntax-lexical.html#SQL-PRECEDENCE

> shows the precedence and associativity of the operators in PostgreSQL. Most operators have the same precedence and are left-associative. The precedence and associativity of the operators is hard-wired into the parser. Add parentheses if you want an expression with multiple operators to be parsed in some other way than what the precedence rules imply.

and

[2] https://www.postgresql.org/docs/current/sql-createoperator.html

> It is not possible to specify an operator's lexical precedence in CREATE OPERATOR, because the parser's precedence behavior is hard-wired. See [Section 4.1.6](https://www.postgresql.org/docs/current/sql-syntax-lexical.html#SQL-PRECEDENCE) for precedence details.

**Comment by effective996** [comment]
@kainwen thanks

**Comment by kainwen** [comment]
Close this. Feel free to reopen if needed or discuss here later.
