### ISSUE TITLE
gp_dist_wait_status() failing within transaction

### ISSUE THREAD

**Issue by dnskvlnk** [greenplum-db/gpdb#13795]
## Bug Report
Hi, we are facing an issue when a query fails when we use `gp_dist_wait_status()` within a transaction. For some reason, this function destroys the current gang, and when `DTX_PROTOCOL_COMMAND_SUBTRANSACTION_RELEASE_INTERNAL` is dispatched, the gang doesn't know what to do. We've deleted this line of code and the query worked well, but we wonder why we need to destroy the gang and if there are some edge cases. @kainwen, would you explain the logic behind this function call, please?

https://github.com/greenplum-db/gpdb/blob/712fc359bcb06e0ce57709f2f34d726bc051e8b9/src/backend/utils/gdd/gddfuncs.c#L326

### Greenplum version or build
6.20.4 and any 6x, I assume

### OS version and uname -a
Ubuntu 22.04

### Expected behavior
List of current locks

### Actual behavior
`ERROR:  Distributed transaction 1657721184-0000000006 not found (cdbtm.c:2278)  (seg1 127.0.1.1:6003 pid=15559) (cdbtm.c:2278)
`
### Step to reproduce the behavior
```
begin;
select * from gp_dist_wait_status();
commit;
```

**Comment by kainwen** [comment]
In my memory, I wrote that line of code 5 years ago just to save some idle QEs not to impact the system workload.

Seems over-thought, will take a look at this. Thanks.

**Comment by dnskvlnk** [comment]
We deleted this string and all the tests have passed, I can propose a PR

**Comment by ashwinstar** [comment]
Yes please
