### ISSUE TITLE
Instructions for use `ALTER PARTITION EXCHANGE PARTITION`

### ISSUE THREAD

**Issue by cobolbaby** [greenplum-db/gpdb#13806]
### Actual behavior

The database always prompts that the partition name is wrong, but I am sure that the name of the partition table is correct again and again.

```
CREATE WRITABLE EXTERNAL TABLE ict.ictlogtestpart_ao_old_ext (LIKE ict.ictlogtestpart_ao_old_1_prt_80)
   LOCATION('s3://???/greenplum/F3_BDC/ict/ictlogtestpart_ao_old_1_prt_80/ config=/home/gpadmin/s3/s3.conf')
   FORMAT 'csv';

insert into ict.ictlogtestpart_ao_old_ext select * from ict.ictlogtestpart_ao_old_1_prt_80;

DROP EXTERNAL TABLE ict.ictlogtestpart_ao_old_ext;

CREATE EXTERNAL TABLE ict.ictlogtestpart_ao_old_1_prt_80_ext (LIKE ict.ictlogtestpart_ao_old_1_prt_80)
   LOCATION('s3://???/greenplum/F3_BDC/ict/ictlogtestpart_ao_old_1_prt_80/ config=/home/gpadmin/s3/s3.conf')
   FORMAT 'csv';

ALTER TABLE ict.ictlogtestpart_ao_old ALTER PARTITION ictlogtestpart_ao_old_1_prt_80 
   EXCHANGE PARTITION ictlogtestpart_ao_old_1_prt_80 
   WITH TABLE ict.ictlogtestpart_ao_old_1_prt_80_ext WITHOUT VALIDATION;

ERROR:  partition "ictlogtestpart_ao_old_1_prt_80" of relation "ictlogtestpart_ao_old" does not exist
SQL state: 42704

ALTER TABLE ict.ictlogtestpart_ao_old ALTER PARTITION prt_80 
   EXCHANGE PARTITION prt_80 
   WITH TABLE ict.ictlogtestpart_ao_old_1_prt_80_ext WITHOUT VALIDATION;

ERROR:  partition "prt_80" of relation "ictlogtestpart_ao_old" does not exist
SQL state: 42704
```

**Comment by ashwinstar** [comment]
Please provide your partition tables schema. Based on what you provided so far this doesn't feel right..
`ALTER PARTITION ictlogtestpart_ao_old_1_prt_80 
   EXCHANGE PARTITION ictlogtestpart_ao_old_1_prt_80` or 
`ALTER PARTITION prt_80 
   EXCHANGE PARTITION prt_80`

If ictlogtestpart_ao_old_1_prt_80 is child of ictlogtestpart_ao_old then just need `ALTER TABLE ictlogtestpart_ao_old EXCHANGE PARTITION <name>` no `ALTER PARTITION` required.

**Comment by cobolbaby** [comment]
> Please provide your partition tables schema.

```sql
-- Table: ict.ictlogtestpart_ao_old

-- DROP TABLE ict.ictlogtestpart_ao_old;

CREATE TABLE ict.ictlogtestpart_ao_old
(
    transactionid character varying(50) COLLATE pg_catalog."default" NOT NULL,
    mcbsno character varying(20) COLLATE pg_catalog."default" NOT NULL,
    testtime timestamp without time zone NOT NULL,
    devicetype character varying(20) COLLATE pg_catalog."default" NOT NULL,
    family character varying(20) COLLATE pg_catalog."default",
    model character varying(12) COLLATE pg_catalog."default",
    fixtureend character(1) COLLATE pg_catalog."default",
    fixture8 character varying(8) COLLATE pg_catalog."default",
    testpart character varying(50) COLLATE pg_catalog."default",
    location character varying(50) COLLATE pg_catalog."default",
    parttype character varying(50) COLLATE pg_catalog."default" NOT NULL,
    txtmeasureval character varying(50) COLLATE pg_catalog."default",
    measureval numeric,
    stdval numeric,
    unit character varying(50) COLLATE pg_catalog."default",
    hlim numeric,
    llim numeric,
    ispass integer NOT NULL,
    cdt timestamp without time zone,
    teststep integer NOT NULL,
    testpartnum integer,
    remark character varying(50) COLLATE pg_catalog."default",
    probe1 numeric,
    probe2 numeric,
    guard1 numeric,
    guard2 numeric,
    guard3 numeric,
    guard4 numeric,
    guard5 numeric,
    isdel integer
)
WITH (
    OIDS = FALSE,
    APPENDONLY = TRUE,
    COMPRESSLEVEL = 5
)
TABLESPACE pg_default
DISTRIBUTED BY (transactionid)
 PARTITION BY RANGE(testtime) 
          (
          START ('2019-01-01 00:00:00'::timestamp without time zone) END ('2022-12-31 00:00:00'::timestamp without time zone) EVERY ('7 days'::interval) WITH (orientation='row', appendonly='true', compresslevel='5'), 
          DEFAULT PARTITION extra  WITH (orientation='row', appendonly='true', compresslevel='5')
          ); 
```

```bash
postgres=#  \d+ ict.ictlogtestpart_ao_old
                                  数据表 "ict.ictlogtestpart_ao_old"
     栏位      |            类型             | 校对规则 |  可空的  | 预设 |   存储   | 统计目标 | 描述
---------------+-----------------------------+----------+----------+------+----------+----------+------
 transactionid | character varying(50)       |          | not null |      | extended |          |
 mcbsno        | character varying(20)       |          | not null |      | extended |          |
 testtime      | timestamp without time zone |          | not null |      | plain    |          |
 devicetype    | character varying(20)       |          | not null |      | extended |          |
 family        | character varying(20)       |          |          |      | extended |          |
 model         | character varying(12)       |          |          |      | extended |          |
 fixtureend    | character(1)                |          |          |      | extended |          |
 fixture8      | character varying(8)        |          |          |      | extended |          |
 testpart      | character varying(50)       |          |          |      | extended |          |
 location      | character varying(50)       |          |          |      | extended |          |
 parttype      | character varying(50)       |          | not null |      | extended |          |
 txtmeasureval | character varying(50)       |          |          |      | extended |          |
 measureval    | numeric                     |          |          |      | main     |          |
 stdval        | numeric                     |          |          |      | main     |          |
 unit          | character varying(50)       |          |          |      | extended |          |
 hlim          | numeric                     |          |          |      | main     |          |
 llim          | numeric                     |          |          |      | main     |          |
 ispass        | integer                     |          | not null |      | plain    |          |
 cdt           | timestamp without time zone |          |          |      | plain    |          |
 teststep      | integer                     |          | not null |      | plain    |          |
 testpartnum   | integer                     |          |          |      | plain    |          |
 remark        | character varying(50)       |          |          |      | extended |          |
 probe1        | numeric                     |          |          |      | main     |          |
 probe2        | numeric                     |          |          |      | main     |          |
 guard1        | numeric                     |          |          |      | main     |          |
 guard2        | numeric                     |          |          |      | main     |          |
 guard3        | numeric                     |          |          |      | main     |          |
 guard4        | numeric                     |          |          |      | main     |          |
 guard5        | numeric                     |          |          |      | main     |          |
 isdel         | integer                     |          |          |      | plain    |          |
子表: ict.ictlogtestpart_ao_old_1_prt_10,
      ict.ictlogtestpart_ao_old_1_prt_100,
      ict.ictlogtestpart_ao_old_1_prt_101,
      ict.ictlogtestpart_ao_old_1_prt_102,
      ict.ictlogtestpart_ao_old_1_prt_103,
      ict.ictlogtestpart_ao_old_1_prt_104,
      ict.ictlogtestpart_ao_old_1_prt_105,
      ict.ictlogtestpart_ao_old_1_prt_106,
      ict.ictlogtestpart_ao_old_1_prt_107,
      ict.ictlogtestpart_ao_old_1_prt_108,
      ict.ictlogtestpart_ao_old_1_prt_109,
      ict.ictlogtestpart_ao_old_1_prt_11,
      ...,
```

> If ictlogtestpart_ao_old_1_prt_80 is child of ictlogtestpart_ao_old then just need ALTER TABLE ictlogtestpart_ao_old EXCHANGE PARTITION <name> no ALTER PARTITION required.

Ref: https://docs.vmware.com/en/VMware-Tanzu-Greenplum/6/greenplum-database/GUID-admin_guide-ddl-ddl-partition.html#exchanging-a-leaf-child-partition-with-an-external-table-23

I would like to know how to get the partition name, it seems that it is not the table name of the partition table yet.

**Comment by cobolbaby** [comment]
Sorry, I overlooked some important hints in the documentation earlier.

> Important: When defining and altering partition designs, use the given partition name, not the table object name. The given partition name is the partitionname column value in the [pg_partitions](https://docs.vmware.com/en/VMware-Tanzu-Greenplum/6/greenplum-database/GUID-ref_guide-system_catalogs-pg_partitions.html) system view. Although you can query and load any table (including partitioned tables) directly using SQL commands, you can only modify the structure of a partitioned table using the ALTER TABLE...PARTITION clauses.
> 
> Partitions are not required to have names. If a partition does not have a name, use one of the following expressions to specify a partition: PARTITION FOR (value) or PARTITION FOR (RANK(number)).

Excuse me, if the partition name is not declared when the partition table is automatically created, can it be modified later?

**Comment by cobolbaby** [comment]
Related issue, the syntax `CREATE EXTERNAL TABLE (LIKE other_table)` does not support inheritance of `not null` constraints.

```sql
ALTER TABLE ict.ictlogtestpart_ao_old
   EXCHANGE PARTITION FOR (RANK(79)) 
   WITH TABLE ict.ictlogtestpart_ao_old_1_prt_80_ext WITHOUT VALIDATION;

ERROR:  column "transactionid" in child table must be marked NOT NULL
SQL state: 42804
```

**Comment by l-wang** [comment]
> Sorry, I overlooked some important hints in the documentation earlier.
> 
> > Important: When defining and altering partition designs, use the given partition name, not the table object name. The given partition name is the partitionname column value in the [pg_partitions](https://docs.vmware.com/en/VMware-Tanzu-Greenplum/6/greenplum-database/GUID-ref_guide-system_catalogs-pg_partitions.html) system view. Although you can query and load any table (including partitioned tables) directly using SQL commands, you can only modify the structure of a partitioned table using the ALTER TABLE...PARTITION clauses.
> > Partitions are not required to have names. If a partition does not have a name, use one of the following expressions to specify a partition: PARTITION FOR (value) or PARTITION FOR (RANK(number)).
> 
> The following SQL works.
> 
> ```sql
> ALTER TABLE ict.ictlogtestpart_ao_old
>    EXCHANGE PARTITION FOR (RANK(79)) 
>    WITH TABLE ict.ictlogtestpart_ao_old_1_prt_80_ext WITHOUT VALIDATION;
> ```

Yes that's how you do it. The child partitions w/ auto-generated names won't have the `partitionname` column populated in the `pg_partitions` view, so we would have to use FOR (value) or FOR (RANK(number)) to identify a child partition in the ALTER TABLE ... PARTITION commands.

> Excuse me, if the partition name is not declared when the partition table is automatically created, can it be modified later?

Yes, we can modify later. Here's how: 

```sql
ALTER TABLE ict.ictlogtestpart_ao_old RENAME PARTITION FOR (RANK(79)) TO newname;
```

or

```sql
ALTER TABLE ict.ictlogtestpart_ao_old RENAME PARTITION FOR ('2020-06-30 00:00:00'::timestamp without time zone) TO newname;
```
Refer to docs here: https://docs.vmware.com/en/VMware-Tanzu-Greenplum/6/greenplum-database/GUID-admin_guide-ddl-ddl-partition.html#topic79

**Comment by l-wang** [comment]
> Related issue, the syntax `CREATE EXTERNAL TABLE (LIKE other_table)` does not support inheritance of `not null` constraints.
> 
> ```sql
> ALTER TABLE ict.ictlogtestpart_ao_old
>    EXCHANGE PARTITION FOR (RANK(79)) 
>    WITH TABLE ict.ictlogtestpart_ao_old_1_prt_80_ext WITHOUT VALIDATION;
> 
> ERROR:  column "transactionid" in child table must be marked NOT NULL
> SQL state: 42804
> ```

@cobolbaby This is documented: https://docs.vmware.com/en/VMware-Tanzu-Greenplum/6/greenplum-database/GUID-admin_guide-ddl-ddl-partition.html#exchanging-a-leaf-child-partition-with-an-external-table-23. Specifically: 
> Exchanging a leaf child partition with an external table is not supported if the partitioned table contains a column with a check constraint or a NOT NULL constraint.

For more information, see docs on external tables here: https://gpdb.docs.pivotal.io/6-10/ref_guide/sql_commands/CREATE_EXTERNAL_TABLE.html. Specifically: 

> column_name
> The name of a column to create in the external table definition. Unlike regular tables, external tables do not have column constraints or default values, so do not specify those.
> LIKE other_table
> The LIKE clause specifies a table from which the new external table automatically copies all column names, data types and Greenplum distribution policy. If the original table specifies any column constraints or default column values, those will not be copied over to the new external table definition.

**Comment by cobolbaby** [comment]
alright, I got it.
