### ISSUE TITLE
gpdb configure failure - gpopt/init.h GPOPT header file is required

### ISSUE THREAD

**Issue by StigPem** [greenplum-db/gpdb#1380]
Apologies in advance if this is posted to the wrong place. 
I’ve been trying to install Greenplum with gp-orca. 
I currently have Greenplum installed and running on a test server so have had to use an upgrade method to install the new version with orca to test the optimisers, hence the /usr/local/gpdb4 prefixes.

gp-xerces, gpos and gporca all seem to install OK. 
ctest returns 100% OK after the gporca install.

When I try to configure gpdb I get the following  (last few lines of the output) :

checking for unistd.h... yes
checking gpopt/init.h usability... no
checking gpopt/init.h presence... no
checking for gpopt/init.h... no
configure: error: gpopt/init.h GPOPT header file is required for Greenplum Query Optimizer (orca)

The file exists in /usr/local/gpdb4/gporca/include/gpopt so I’m a bit confused as to why the install should fail.

I guess it’s installed in an incorrect location. Can anyone point out where I’ve made an error, or give me some advice to get this working ?

The code I ran for all of the installs is as follows  (logged in as root ) :

 git clone https://github.com/greenplum-db/gp-xerces /usr/local/gpdb4/gp-xerces

cd /usr/local/gdb4/gp-xerces
mkdir build
cd build

../configure --prefix=/usr/local/gpdb4

make
make install

git clone https://github.com/greenplum-db/gpos /usr/local/gpdb4/gpos

cd /usr/local/gdb4/gpos
mkdir build
cd build

cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local/gpdb4/gpos ../

make
make install

git clone https://github.com/greenplum-db/gporca /usr/local/gpdb4/gporca

cd /usr/local/gpdb4/gporca
mkdir build
cd build

cmake -D CMAKE_INSTALL_PREFIX=/usr/local/gpdb4/gporca -D XERCES_INCLUDE_DIR=/usr/local/gpdb4/include -D XERCES_LIBRARY=/usr/local/gpdb4/lib/libxerces-c.so -D GPOS_INCLUDE_DIR=/usr/local/gpdb4/gpos/include -D GPOS_LIBRARY=/usr/local/gpdb4/gpos/lib/libgpos.so ../

make
make install

I then ran ctest and got the following :

100% tests passed, 0 tests failed out of 67

Total Test time (real) = 377.36 sec

Next, I got the gpdb code :

git clone https://github.com/greenplum-db/gpdb.git /usr/local/gpdb4/gpdb

cd /usr/local/gpdb4/gpdb

./configure --with-openssl --with-libxml --with-libxslt --with-python --with-perl --enable-mapreduce --enable-orca --prefix=/usr/local/gpdb4/gpdb

.... then it failed :-(

**Comment by StigPem** [comment]
I got the configure to work with this -

./configure --with-openssl --with-libxml --with-libxslt --with-python --with-perl --enable-orca --with-includes=/usr/local/gpdb4/gporca/include/gpopt --prefix=/usr/local/gpdb4/gpdb --exec-prefix=/usr/local/gpdb4/gpdb

However the make fails with -

/usr/local/gpdb4/gporca/include/naucrates/dxl/xml/dxltokens.h:21:39: fatal error: xercesc/util/XMLUniDefs.hpp: No such file or directory
 #include <xercesc/util/XMLUniDefs.hpp>
                                       ^
compilation terminated.
make[4]: *** [CMappingVarColId.o] Error 1
make[4]: Leaving directory `/usr/local/gpdb4/gpdb/src/backend/gpopt/translate'
make[3]: *** [translate-recursive] Error 2
make[3]: Leaving directory `/usr/local/gpdb4/gpdb/src/backend/gpopt'
make[2]: *** [gpopt-recursive] Error 2
make[2]: Leaving directory `/usr/local/gpdb4/gpdb/src/backend'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/usr/local/gpdb4/gpdb/src'
make: *** [all] Error 2

Any ideas anyone ?

**Comment by vraghavan78** [comment]
@oarap @xinzweb @hsyuan @d can you help @StigPem

**Comment by vraghavan78** [comment]
@hlinnaka's comment:

```
Use the configure --with-includes option to point to the headers, and --with-libs option to point to the lib. For example, my configure line is:

./configure --prefix=/home/heikki/gpdb.master --with-perl CXX="ccache g++" CC="ccache gcc" --enable-debug --with-python --enable-depend --with-libxml --with-includes=/home/heikki/gpdb/orca-install/include:/home/heikki/gpdb/extinclude --with-libs=/home/heikki/gpdb/orca-install/lib/:/home/heikki/gpdb/extlib --enable-ddboost --with-openssl --enable-mapreduce --enable-orca
```

**Comment by vraghavan78** [comment]
@StigPem please let us know if this helped. If not please re-open the issue.

**Comment by StigPem** [comment]
Thanks for the pointers. I finally got it installed.
The key for me was to find the files that were not being found and then include the relevant include or lib as required.
