### ISSUE TITLE
AO/AOCS error on  within group

### ISSUE THREAD

**Issue by wangxuqi** [greenplum-db/gpdb#13818]
### Step to reproduce the behavior
```
 create table perct WITH (appendonly=true) as select a, a / 10 as b from generate_series(1, 100)a distributed by (a);
 select percentile_cont(0.5) within group (order by a) from perct;
```

### Error
` ERROR:  virtual tuple table slot does not have system attributes (execTuples.c:151)  (seg1 slice1 11.158.187.244:7003 pid=58496) (execTuples.c:151)`

**Comment by kainwen** [comment]
Seems a bug introduced by ORCA's feature:  b90f95280868d892d028a07a3535f4c847db2d2a

**Comment by khannaekta** [comment]
Tried locally and it seems to be working on current master at commit: 10f7e0d
Closing issue for now
