### ISSUE TITLE
How to split default partition with subpartition

### ISSUE THREAD

**Issue by jinmojing** [greenplum-db/gpdb#13827]
## Feature Request

Greenplum-db version: 6.17.2

We create a table named item2 with two partition two years ago . The dll of table like this:

partition by range (time) subpartition by list (cat1) subpartition template( subpartition cat122852001 values ('122852001'), subpartition cat50013864 values ('50013864')........., default subpartition other_cat)(START (date '2016-01-01') INCLUSIVE END (date '2020-12-01') EXCLUSIVE EVERY (INTERVAL '1 month'), DEFAULT PARTITION other_time );

When we check the db data, we found that all data last then 2021-01 are in the same partition as "other_time", and the partition is become too big now.

So we want to split the default time partition. But we notice that gp only support split default subpartition not the parent default partition (https://gp-docs-cn.github.io/docs/ref_guide/sql_commands/ALTER_TABLE.html)

How can we split default partition  without drop the table and redo it?

**Is your feature request related to a problem? Please describe:**

**Describe the feature you'd like to request:**

**Comment by lij55** [comment]
I don't think greenplum support this and I'm afraid re-creating is the easiest way to do it. I will close this issue as it is hard to support in near future.
