### ISSUE TITLE
unclear flag of GetOldestXmin() in appendonly_compaction.c

### ISSUE THREAD

**Issue by avamingli** [greenplum-db/gpdb#13830]
### Greenplum version or build
7x 
## Enhancement
inside aoco_index_build_range_scan()

```c
			if (cutoff_xid == InvalidTransactionId)
				cutoff_xid = GetOldestXmin(NULL, true);

			visible_to_all = TransactionIdPrecedes(xmin, cutoff_xid);
```

while function signature is
```c
GetOldestXmin(Relation rel, int flags)
```
And there seems no flags definition as `0x01`.

What should the flags be ?

**Comment by adam8157** [comment]
I believe it should be `AppendOptimizedRecycleDeadSegments()` but not `aoco_index_build_range_scan()`, it's the only place I fould.
