### ISSUE TITLE
gpconfig display issue

### ISSUE THREAD

**Issue by zeromax007** [greenplum-db/gpdb#1388]
gpconfig -c pljava_vmoptions -v \''-Xms512m '-Xmx1024m\' -m \''-Xms1024m '-Xmx4096m\'

gpconfig -s pljava_vmoptions
Values on all segments are consistent
GUC          : pljava_vmoptions
Master  value: -Xms1024m -Xmx4096m
Segment value: -Xms1024m -Xmx4096m

In postgresql.conf , pljava_vmoptions value is right. This is just display issue with using gpconfig -s.

**Comment by ivannovick** [comment]
@skahler-pivotal can you have a look?

**Comment by skahler-pivotal** [comment]
The way gpconfig works is that when you run -s it reads from the current values set for the user. We are adding a flag ( https://github.com/greenplum-db/gpdb/pull/1820 ) which is --file that will tell gpconfig to read directly from the postgresql.conf files

**Comment by zeromax007** [comment]
I used gpstop -u to reload the config changing, but it's still display incorrect.

**Comment by skahler-pivotal** [comment]
That parameter seems to only be populated from the postgresql.conf when the system is restarted, it doesn't looked like the -u process populates it to the user environment.
