### ISSUE TITLE
[ARM CI] openlab is EOL

### ISSUE THREAD

**Issue by bzhaoopenstack** [greenplum-db/gpdb#13903]
So apologized that openLab was EOL recently. We are no choice and forced to close openlab services.

That means the original regression test on openLab ARM machines are dead forever. We can consider to remove it now.

Even openlab is EOL, but gpdb community can consider another way to test Greenplum on ARM, because we can donate ARM resources(VM) for testing. Such as:

```
1. Integrate the said ARM instances into your CICD system.
2. Integrate the said ARM instances into Github Action as a self-host.
```

Sorry that openLab is EOL, please consider whether community need ARM resources to test for making sure gpdb work well on different ARCH.

Waiting for your feedback.

Thanks.

**Comment by higuoxing** [comment]
Hi @bzhaoopenstack, Thanks for your generous offer! Seems that integrating ARM instances into the GitHub Action is an easier option. Do you have any suggestions? I can help maintain it.

**Comment by higuoxing** [comment]
This thread hasn't been active for a long time. I'll close this issue. Feel free to re-open.
