### ISSUE TITLE
Why don't we support "streaming bottom" in aggregate anymore?

### ISSUE THREAD

**Issue by wfnuser** [greenplum-db/gpdb#13919]
Hi. I'm recently researching on aggregate implementation in greenplum. And I have noticed that the "streaming bottom" feature has been removed in PG_12_MERGE. 
I'm just wondering why is that? Maybe we can bring it back? I have traced the related commits but still have no clue about that.
@kainwen

**Comment by kainwen** [comment]
we are spiking now.

**Comment by kainwen** [comment]
Feel free to research and share with community. Thanks.

**Comment by wfnuser** [comment]
> we are spiking now.

Cool. Looking forward to that. It will be very kind of you if you will notice me in the future discussion.

**Comment by adam8157** [comment]
https://github.com/greenplum-db/gpdb/pull/13949
