### ISSUE TITLE
ERROR: failed to acquire resources -  cdbgang_async.c

### ISSUE THREAD

**Issue by miklnx** [greenplum-db/gpdb#13976]
## Bug Report
ERROR: CLI execute error: [SAS][ODBC Greenplum Wire Protocol driver][Greenplum]ERROR: failed to acquire resources on one or more
segments(Detail server closed the connection unexpectedly
This probably means the server terminated abnormally
before or
while processing the request.
(seg41 10.10.114.138:6017); File cdbgang_async.c; Line 244; Routine cdbgang_createGang_async;

### Greenplum version or build
6.19.4 953778b47d418bb463e4abb2d982ba27dd281010

### OS version and uname -a
Linux w2c14mdw 3.10.0-957.21.3.el7.x86_64 #1 SMP Fri Jun 14 02:54:29 EDT 2019 x86_64 x86_64 x86_64 GNU/Linux

### Expected behavior
SQL is successful.

### Actual behavior
SQL ends with an error

**Comment by kainwen** [comment]
Can you please paste the log from `seg41`, and see if there is any core dumps at that machine during the time?

**Comment by miklnx** [comment]
@kainwen  I looked through the logs, but found no information about the error there. How can I change the log's level so that it is visible in the future?

**Comment by miklnx** [comment]
That's exactly what I meant. @kainwen there is no ERROR information. I've attached log from this time.
[seg_log_obfuscated.txt](https://github.com/greenplum-db/gpdb/files/9425722/seg_log_obfuscated.txt)

**Comment by ashwinstar** [comment]
Closing as lagging info to RCA
