### ISSUE TITLE
gpssh-exkeys succeeds but gpssh reports Error: No user name available to Login method

### ISSUE THREAD

**Issue by yst001** [greenplum-db/gpdb#13971]
I use docker to deploy the greenplum cluster, use the docker image of centos7, the rpm package is greenplum-db-6.16.3-rhel7-x86_64.rpm, during the deployment process, I encountered the situation that gpssh-exkeys succeeded but gpssh failed, which corresponds to master and other nodes have been configured for ssh password-free operation.
Screenshot below：
<img width="974" alt="Snipaste_2022-08-20_11-08-35" src="https://user-images.githubusercontent.com/44132305/185726716-157111e4-abdd-4381-80b4-267e0b71cac7.png">

how should i solve this problem?

**Comment by zjpedu** [comment]
This doesn't look like a bug. You shouldn't be doing this as the root user. Is it right?

**Comment by Aegeaner** [comment]
Try switching to the `gpadmin` user.

**Comment by zjpedu** [comment]
> Try switching to the `gpadmin` user.

https://github.com/greenplum-db/gpdb/blob/master/gpMgmt/bin/gppylib/util/ssh_utils.py#L175

**Comment by ashwinstar** [comment]
Closing this old issue, please let us know if still problem then we will try to investigate.
