### ISSUE TITLE
gpfdist and gpload not work when there're some segments deployed on master host and segment host

### ISSUE THREAD

**Issue by YinAqu** [greenplum-db/gpdb#1399]
Hi, dear team:
I'm a new guy, I've got two hosts in my greenplum DBMS, which consists of a master host named `mdw` and a segment host named `sdw1`. 
When I deploy some segments on `sdw1` only,  gpfdist and gpload work well.
When I deploy some segments on `mdw` making it as a single node system, gpfdist and gpload work well.
But when I deploy some segments **on both of them**, gpfdist and gpload get stuck without any error information.
It gets stuck all the time without exiting and any error information like this:
```
tpch=# insert into nation select * from ext_nation ;

```
or
```
[gpadmin@mdw ~]$ gpload -f gpload.yaml -l gpload.log
2016-12-01 08:25:47|INFO|gpload session started 2016-12-01 08:25:47
2016-12-01 08:25:47|INFO|started gpfdist -p 8081 -P 8082 -f "/home/gpadmin/*.csv" -t 30
```
Is this a bug or if I mistake any configuration? Plz help me on this and if it can be reproduced and it were a bug or it's designed, plz let me know, I'll appreciate it.

**Comment by YinAqu** [comment]
Well, I tested it further, and I found it might not be gpfdist's business.
I used psql utility within the mdw host to connect greenplum, I got stuck at the `insert into` statement at the first time. Then I used `ctrl c` to cancel it, issued 'insert into' again, it worked.
```
tpch=# insert into nation(n_name,n_regionkey,n_comment) values('3','4','hh');
tpch=# select * from nation;
 n_nationkey |          n_name           | n_regionkey | n_comment 
-------------+---------------------------+-------------+-----------
           7 | 3                         |           4 | hh
(1 row)
```
However, it always got stuck at the statement `tpch=# insert into nation select * from ext_nation ;`
And I found update statement `update nation set n_name='xi' where n_nationkey=7;` always got stuck as well. It's totally weird..

**Comment by eurekaka** [comment]
@lij55 FYI

**Comment by YinAqu** [comment]
I fixed it myself. There was something wrong in my /etc/hosts like this:
```
127.0.0.1   mdw localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
```
Removing the `mdw` from the `127.0.0.1` line fixed my issue.
Anyway, tks your comment in time @eurekaka, and I'll close this issue.
