### ISSUE TITLE
How to restrict the execution plan

### ISSUE THREAD

**Issue by cobolbaby** [greenplum-db/gpdb#14136]
## Feature Request

**Is your feature request related to a problem? Please describe:**

For some specific queries in PG, in order to ensure stable execution performance, we often use `enable_xxx` or `pg_hint_plan` to customize the SQL execution plan. 
There are similar demands in GP. But I found that the `enable_xxx` setting does not take effect in many cases, so I would like to ask if GP provides some other ways to customize the execution plan?

GP Version: 6.20.5

**Describe the feature you'd like to request:**

**Comment by kainwen** [comment]
Hi, there are two optimizers in Greenplum:

* Postgres legacy planner
* ORCA

When the GUC `optimizer` is set off, it will always use `Postgres legacy planner`; when `optimizer = true`, it will firstly try generate the plan using `ORCA`, if failing to get a valid plan, it will fallback to `Postgres legacy planner`. 

`set optimizer_tracefallback = 1` can show the reason when ORCA fallback to planner happens.

So GUCs like `enable_hashjoin`, `enable_xxx` are concepts for  `Postgres legacy planner` and can only take effect when planning via `legacy planner`.

If you want to control or hint the plan  of ORCA, you need GUCs like `optimizer_enable_xxx`, you can have a list in GPDB's doc or take a look at here: https://github.com/greenplum-db/gpdb/blob/master/src/backend/utils/misc/guc_gp.c (search `optimizer_` in this page.

-------

I suppose there is no problem in this issue, so I close it. Feel free to discuss here or reopen.

**Comment by cobolbaby** [comment]
```
set optimizer = off;
set enable_hashjoin = off;
set enable_nestloop = on;

explain analyse 
select
    r.mcbsno,
    s.family,
    s.model,
    r.desc_station as station,
    s.pdline,
    r.causecode,
    r.desc_cause as defect,
    r.location,
    to_char(r.repcdt, 'yyyy-mm-dd hh24:mi:dd') as test_date
from
    dw.fact_pca_rep r
    join dw.fact_pca_yield_unit s on r.mcbsno = s.mcbsno
    and r.wc = s.wc
    and (
        r.rework = s.rework
        or r.repcdt = s.test_date
        or s.rework is null
    )
where
    s.verify_fail = 1
    and r.is_transfered = 'N'
    and trim(r.desc_station) in ('ICT3')
    and s.family = 'MATTERHORN'
    and s.test_date >= date_trunc(
        'hour',
        '2022-04-27T23:00:00Z' at time zone 'Asia/Shanghai'
    )
    and s.test_date < date_trunc(
        'hour',
        (
            '2022-05-04T22:00:00Z' at time zone 'Asia/Shanghai'
        ) + interval '1 hour'
    )
    and s.board_type = 'SC'
    and s.customer in ('HPQ')

"Gather Motion 20:1  (slice1; segments: 20)  (cost=32304.01..52132818.19 rows=36 width=80) (actual time=4271.853..6163.235 rows=31 loops=1)"
"  ->  Nested Loop  (cost=32304.01..52132818.19 rows=2 width=80) (actual time=2935.468..4869.739 rows=4 loops=1)"
"        Join Filter: (((r.mcbsno)::text = (s.mcbsno)::text) AND ((r.wc)::text = (s.wc)::text) AND ((r.rework = s.rework) OR (r.repcdt = s.test_date) OR (s.rework IS NULL)))"
"        ->  Seq Scan on fact_pca_rep r  (cost=0.00..1722973.50 rows=2868 width=64) (actual time=0.444..3574.318 rows=155736 loops=1)"
"              Filter: ((is_transfered = 'N'::text) AND (btrim((desc_station)::text) = 'ICT3'::text))"
"        ->  Materialize  (cost=32304.01..10124120.32 rows=1561 width=49) (actual time=0.001..0.004 rows=14 loops=154938)"
"              ->  Bitmap Heap Scan on fact_pca_yield_unit s  (cost=32304.01..10123964.22 rows=1561 width=49) (actual time=131.101..439.545 rows=14 loops=1)"
"                    Recheck Cond: ((test_date >= '2022-04-28 07:00:00'::timestamp without time zone) AND (test_date < '2022-05-05 07:00:00'::timestamp without time zone))"
"                    Filter: ((verify_fail = 1) AND ((family)::text = 'MATTERHORN'::text) AND ((board_type)::text = 'SC'::text) AND ((customer)::text = 'HPQ'::text))"
"                    ->  Bitmap Index Scan on idx_dw_fact_pca_yield_unit_testdate  (cost=0.00..32296.20 rows=87330 width=0) (actual time=35.146..35.146 rows=102261 loops=1)"
"                          Index Cond: ((test_date >= '2022-04-28 07:00:00'::timestamp without time zone) AND (test_date < '2022-05-05 07:00:00'::timestamp without time zone))"
"Planning time: 3.210 ms"
"  (slice0)    Executor memory: 183K bytes."
"  (slice1)    Executor memory: 6054K bytes avg x 20 workers, 6071K bytes max (seg9).  Work_mem: 5427K bytes max."
"Memory used:  204800kB"
"Optimizer: Postgres query optimizer"
"Execution time: 6165.639 ms"
```

**Comment by kainwen** [comment]
> ```sql
> set optimizer = off;
> set enable_hashjoin = off;
> set enable_nestloop = on;
> 
> explain analyse 
> select
>     r.mcbsno,
>     s.family,
>     s.model,
>     r.desc_station as station,
>     s.pdline,
>     r.causecode,
>     r.desc_cause as defect,
>     r.location,
>     to_char(r.repcdt, 'yyyy-mm-dd hh24:mi:dd') as test_date
> from
>     dw.fact_pca_rep r
>     join dw.fact_pca_yield_unit s on r.mcbsno = s.mcbsno
>     and r.wc = s.wc
>     and (
>         r.rework = s.rework
>         or r.repcdt = s.test_date
>         or s.rework is null
>     )
> where
>     s.verify_fail = 1
>     and r.is_transfered = 'N'
>     and trim(r.desc_station) in ('ICT3')
>     and s.family = 'MATTERHORN'
>     and s.test_date >= date_trunc(
>         'hour',
>         '2022-04-27T23:00:00Z' at time zone 'Asia/Shanghai'
>     )
>     and s.test_date < date_trunc(
>         'hour',
>         (
>             '2022-05-04T22:00:00Z' at time zone 'Asia/Shanghai'
>         ) + interval '1 hour'
>     )
>     and s.board_type = 'SC'
>     and s.customer in ('HPQ')
> 
> "Gather Motion 20:1  (slice1; segments: 20)  (cost=32304.01..52132818.19 rows=36 width=80) (actual time=4271.853..6163.235 rows=31 loops=1)"
> "  ->  Nested Loop  (cost=32304.01..52132818.19 rows=2 width=80) (actual time=2935.468..4869.739 rows=4 loops=1)"
> "        Join Filter: (((r.mcbsno)::text = (s.mcbsno)::text) AND ((r.wc)::text = (s.wc)::text) AND ((r.rework = s.rework) OR (r.repcdt = s.test_date) OR (s.rework IS NULL)))"
> "        ->  Seq Scan on fact_pca_rep r  (cost=0.00..1722973.50 rows=2868 width=64) (actual time=0.444..3574.318 rows=155736 loops=1)"
> "              Filter: ((is_transfered = 'N'::text) AND (btrim((desc_station)::text) = 'ICT3'::text))"
> "        ->  Materialize  (cost=32304.01..10124120.32 rows=1561 width=49) (actual time=0.001..0.004 rows=14 loops=154938)"
> "              ->  Bitmap Heap Scan on fact_pca_yield_unit s  (cost=32304.01..10123964.22 rows=1561 width=49) (actual time=131.101..439.545 rows=14 loops=1)"
> "                    Recheck Cond: ((test_date >= '2022-04-28 07:00:00'::timestamp without time zone) AND (test_date < '2022-05-05 07:00:00'::timestamp without time zone))"
> "                    Filter: ((verify_fail = 1) AND ((family)::text = 'MATTERHORN'::text) AND ((board_type)::text = 'SC'::text) AND ((customer)::text = 'HPQ'::text))"
> "                    ->  Bitmap Index Scan on idx_dw_fact_pca_yield_unit_testdate  (cost=0.00..32296.20 rows=87330 width=0) (actual time=35.146..35.146 rows=102261 loops=1)"
> "                          Index Cond: ((test_date >= '2022-04-28 07:00:00'::timestamp without time zone) AND (test_date < '2022-05-05 07:00:00'::timestamp without time zone))"
> "Planning time: 3.210 ms"
> "  (slice0)    Executor memory: 183K bytes."
> "  (slice1)    Executor memory: 6054K bytes avg x 20 workers, 6071K bytes max (seg9).  Work_mem: 5427K bytes max."
> "Memory used:  204800kB"
> "Optimizer: Postgres query optimizer"
> "Execution time: 6165.639 ms"
> ```
> 
> ```sql
> set optimizer = on;
> set optimizer_enable_hashjoin = off;
> 
> explain analyse 
> select
>     r.mcbsno,
>     s.family,
>     s.model,
>     r.desc_station as station,
>     s.pdline,
>     r.causecode,
>     r.desc_cause as defect,
>     r.location,
>     to_char(r.repcdt, 'yyyy-mm-dd hh24:mi:dd') as test_date
> from
>     dw.fact_pca_rep r
>     join dw.fact_pca_yield_unit s on r.mcbsno = s.mcbsno
>     and r.wc = s.wc
>     and (
>         r.rework = s.rework
>         or r.repcdt = s.test_date
>         or s.rework is null
>     )
> where
>     s.verify_fail = 1
>     and r.is_transfered = 'N'
>     and trim(r.desc_station) in ('ICT3')
>     and s.family = 'MATTERHORN'
>     and s.test_date >= date_trunc(
>         'hour',
>         '2022-04-27T23:00:00Z' at time zone 'Asia/Shanghai'
>     )
>     and s.test_date < date_trunc(
>         'hour',
>         (
>             '2022-05-04T22:00:00Z' at time zone 'Asia/Shanghai'
>         ) + interval '1 hour'
>     )
>     and s.board_type = 'SC'
>     and s.customer in ('HPQ')
> 
> "Gather Motion 20:1  (slice1; segments: 20)  (cost=0.00..7742.65 rows=15025 width=72) (actual time=53.333..199.560 rows=31 loops=1)"
> "  ->  Result  (cost=0.00..7740.02 rows=752 width=72) (actual time=6.996..55.825 rows=4 loops=1)"
> "        ->  Nested Loop  (cost=0.00..7739.97 rows=752 width=80) (actual time=6.984..55.803 rows=4 loops=1)"
> "              Join Filter: true"
> "              ->  Index Scan using idx_dw_fact_pca_yield_unit_testdate on fact_pca_yield_unit  (cost=0.00..98.39 rows=64 width=49) (actual time=1.165..156.646 rows=14 loops=1)"
> "                    Index Cond: ((test_date >= '2022-04-28 07:00:00'::timestamp without time zone) AND (test_date < '2022-05-05 07:00:00'::timestamp without time zone))"
> "                    Filter: ((verify_fail = 1) AND ((family)::text = 'MATTERHORN'::text) AND ((board_type)::text = 'SC'::text) AND ((customer)::text = 'HPQ'::text))"
> "              ->  Index Scan using idx_dw_fact_pca_rep_mcbsno on fact_pca_rep  (cost=0.00..7641.37 rows=1 width=57) (actual time=0.120..0.191 rows=0 loops=8)"
> "                    Index Cond: ((mcbsno)::text = (fact_pca_yield_unit.mcbsno)::text)"
> "                    Filter: (((wc)::text = (fact_pca_yield_unit.wc)::text) AND ((rework = fact_pca_yield_unit.rework) OR (repcdt = fact_pca_yield_unit.test_date) OR (fact_pca_yield_unit.rework IS NULL)) AND (is_transfered = 'N'::text) AND (btrim((desc_station)::text) = 'ICT3'::text))"
> "Planning time: 164.877 ms"
> "  (slice0)    Executor memory: 322K bytes."
> "  (slice1)    Executor memory: 212K bytes avg x 20 workers, 214K bytes max (seg0)."
> "  (slice2)    "
> "  (slice3)    "
> "  (slice4)    "
> "  (slice5)    "
> "Memory used:  204800kB"
> "Optimizer: Pivotal Optimizer (GPORCA)"
> "Execution time: 200.958 ms"
> ```

The above cases show it works well?

**Comment by cobolbaby** [comment]
Yes.
