### ISSUE TITLE
GP6 doesn't support set transaction snapshot

### ISSUE THREAD

**Issue by xiaoxiaoHe-E** [greenplum-db/gpdb#14177]
### Greenplum version or build
PostgreSQL 9.4.26 (Greenplum Database 6.21.0+dev.37.g2d4a9cd4d0 build dev)

### Actual behavior
we can still see new data after set the transaction snapshot to the snapshot before new data.

### Step to reproduce the behavior

we have two sessions connecting to GPDB: 
session1: start transaction and export a snapshot
session2: start transaction and set the snapshot to the snapshotID exported from session1
session3: insert data

timeline:

session1： 
```
gpadmin=# start transaction;
START TRANSACTION
gpadmin=# SET TRANSACTION ISOLATION LEVEL REPEATABLE READ READ ONLY ;
SET
gpadmin=# select * from pg_export_snapshot();
 pg_export_snapshot
--------------------
 0000051F-1
(1 row)

gpadmin=# select * from t;
 c
---
(0 rows)
```

session2:
```
gpadmin=# start transaction;
START TRANSACTION
gpadmin=# SET TRANSACTION ISOLATION LEVEL REPEATABLE READ READ ONLY ;
SET
gpadmin=# set transaction SNAPSHOT '0000051F-1';
SET
```

session3:
```
gpadmin=# insert into t values(12);
INSERT 0 1
```

after insert data:
session1: no new data 
```
gpadmin=# select * from t;
 c
---
(0 rows)
```
session2: we can see the new data
```
gpadmin=# select * from t;
 c
----
 12
(1 row)

```

I also tried this procedure in gp6 segments and gp7. They all work fine. Only gp6 has this problem.

Besides, I found that these two documents have conflict of this `set transaction snapshot` command: https://docs.vmware.com/en/VMware-Tanzu-Greenplum/6/greenplum-database/GUID-ref_guide-feature_summary.html
https://docs.vmware.com/en/VMware-Tanzu-Greenplum/6/greenplum-database/GUID-ref_guide-sql_commands-SET_TRANSACTION.html

**Comment by SmartKeyerror** [comment]
### RCA

Because 6X-STABLE is still using the `DistributedTransactionTimeStamp` to check the visibility, which 7.0-Alpha has removed this filed from `DistributedSnapshot` in the PR #10910. In 6X-STABLE, we will not write the timestamp into snapshot files, it just like:

```
smart@stable:~/workspace/gpdb/gpAux/gpdemo/datadirs/qddir/demoDataDir-1/pg_snapshots$ cat 000002DF-1
xid:735
dbid:12812
iso:2
ro:1
xmin:735
xmax:735
xcnt:0
sof:0
sxcnt:0
rec:0
dsxminall:5
dsid:12
dsxmin:5
dsxmax:5
dsxcnt:0
``` 

So in the function `ImportSnapshot()` we could not get the value of timestamp in QD, then there is no way to serialize this value and pass it to QE, so this value will be 0 in QE, and will lead to the wrong judgment of visibility.
