### ISSUE TITLE
Unstable test case in master branch

### ISSUE THREAD

**Issue by wangxuqi** [greenplum-db/gpdb#14183]
![image](https://user-images.githubusercontent.com/13748374/192510683-21aa0476-0ae6-48d1-94ae-416fc37575c5.png)
I have see many failed build on CI tests because of `qp_union_intersect` failed. But when I run it locally, it return with expect
result. It seems not very stable. Does any one known the root reason and fix it?

**Comment by kainwen** [comment]
https://github.com/greenplum-db/gpdb/pull/14048

already have PR seems no need to have an issue
