### ISSUE TITLE
Enum hashing for distribution across segments is inconsistent across databases

### ISSUE THREAD

**Issue by AJR-VMware** [greenplum-db/gpdb#14198]
### Greenplum version or build
Greenplum Database 6.21.0+dev.152.g72d9dff1c4 build dev

### OS version and uname -a
Linux ajrdevbox 5.15.0-48-generic #54~20.04.1-Ubuntu SMP Thu Sep 1 16:17:26 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### autoconf options used ( config.status --config )
./configure --with-perl --with-python --with-libxml --enable-mapreduce --enable-orafce --disable-orca --with-openssl --enable-cassert --enable-debug --enable-depend CFLAGS='-O0 -fno-omit-frame-pointer'

### Installation information ( pg_config )
BINDIR = /usr/local/gpdb/bin
DOCDIR = /usr/local/gpdb/share/doc/postgresql
HTMLDIR = /usr/local/gpdb/share/doc/postgresql
INCLUDEDIR = /usr/local/gpdb/include
PKGINCLUDEDIR = /usr/local/gpdb/include/postgresql
INCLUDEDIR-SERVER = /usr/local/gpdb/include/postgresql/server
LIBDIR = /usr/local/gpdb/lib
PKGLIBDIR = /usr/local/gpdb/lib/postgresql
LOCALEDIR = /usr/local/gpdb/share/locale
MANDIR = /usr/local/gpdb/share/man
SHAREDIR = /usr/local/gpdb/share/postgresql
SYSCONFDIR = /usr/local/gpdb/etc/postgresql
PGXS = /usr/local/gpdb/lib/postgresql/pgxs/src/makefiles/pgxs.mk
CONFIGURE = '--with-perl' '--with-python' '--with-libxml' '--enable-mapreduce' '--enable-orafce' '--disable-orca' '--with-openssl' '--enable-cassert' '--enable-debug' '--enable-depend' 'CFLAGS=-O0 -fno-omit-frame-pointer'
CC = gcc
CPPFLAGS = -D_GNU_SOURCE -I/usr/include/libxml2 -I/usr/local/gpdb/include
CFLAGS = -Wall -Wmissing-prototypes -Wpointer-arith -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fno-aggressive-loop-optimizations -Wno-unused-but-set-variable -Wno-address -Werror=implicit-fallthrough=3 -Wno-format-truncation -Wno-stringop-truncation -g -ggdb -O0 -fno-omit-frame-pointer -std=gnu99 -Werror=uninitialized -Werror=implicit-function-declaration -I/usr/local/gpdb/include
CFLAGS_SL = -fPIC
LDFLAGS = -Wl,--as-needed -Wl,-rpath,'/usr/local/gpdb/lib',--enable-new-dtags -L/usr/local/gpdb/lib
LDFLAGS_EX = 
LDFLAGS_SL = 
LIBS = -lpgcommon -lpgport -lxml2 -lrt -lyaml -lzstd -lrt -lcrypt -ldl -lm -L/usr/local/gpdb/lib
VERSION = PostgreSQL 9.4.26

### Expected behavior
Enum values should be predictably assigned to the same segments across databases.

### Actual behavior
Enum values are assigned non-deterministically to segments based on values that differ across databases.

### Step to reproduce the behavior
```sh
# repro script
dropdb testdb
createdb testdb
psql -d testdb -c "create type colors as enum ('red', 'green', 'blue');"
psql -d testdb -c "create table legacy_enum(color colors) distributed by(color);"
psql -d testdb -c "insert into legacy_enum values ('red');"
psql -d testdb -c "SELECT gp_segment_id, count(1) as row_count FROM public.legacy_enum group by gp_segment_id order by gp_segment_id;"
```
This script can be run repeatedly, and will demonstrate the inserted tuple being assigned to different segment IDs.  Because the effect is non-deterministic it may take a few re-runs to see this on smaller clusters.  Screenshot attached of the effect on a local demo cluster.

![Screenshot from 2022-09-29 10-12-34](https://user-images.githubusercontent.com/107145309/193076528-976df443-add2-460e-b57b-19e5b77a043d.png)

**Comment by ashwinstar** [comment]
@AJR-VMware is continuing to debug this further and will update here in coming days...

**Comment by AJR-VMware** [comment]
# Root Cause
* when an enum is created, each value is is assigned an oid
```sql
testdb=# create type colors as enum ('red', 'green', 'blue');
CREATE TYPE
testdb=# select oid,* from pg_enum;
  oid  | enumtypid | enumsortorder | enumlabel 
-------+-----------+---------------+-----------
 16400 |     16398 |             1 | red
 16402 |     16398 |             2 | green
 16404 |     16398 |             3 | blue
(3 rows)
```

* when a table is distributed by an enum column, the routine that is used to calculate the segment ID upon data insert references only the oid of the enum value, meaning it will be arbitrarily different for any given database as the OIDs may be assigned differently.
```sql
create table legacy_enum(color colors) distributed by(color);
insert into legacy_enum values ('blue');
insert into legacy_enum values ('red'), ('green');
```
* This is done in `cdbmutate.c -- directDispatchCalculateHash` for inserting a single row
* This is done in `copy.c -- GetTargetSeg` when copying in data
* It is unclear how this process is accomplished when multiple values are inserted at once

* This causes problems for backup/restore, because GetTargetSeg will often result in errorsabout data being allocated to the wrong segment, due to the enum values having different OIDs on the db being restored to

# Possible Solutions
* prevent distributing by enum columns
    * if enum column is indicated as one of multiple distribution keys, instead distribute only by the others
    * if only enum column is available distribute randomly instead
* refactor above functions to consider contents of the enum value for hashing
    * that is, distributed by a hash of 'red' instead of a hash of the OID 16400

**Comment by soumyadeep2007** [comment]
Great analysis!

> prevent distributing by enum columns
if enum column is indicated as one of multiple distribution keys, instead distribute only by the others
if only enum column is available distribute randomly instead

We would like to ban it with an ERROR instead "cannot distribute by an enum column", that's what we typically do for such things.

> refactor above functions to consider contents of the enum value for hashing
that is, distributed by a hash of 'red' instead of a hash of the OID 16400

That is a great idea. Unfortunately however, enum types can be altered (including their elements' ordinal position :trollface: ). See [PG docs](https://www.postgresql.org/docs/12/sql-altertype.html#:~:text=ADD%20VALUE%20%5B%20IF%20NOT%20EXISTS%20%5D%20%5B%20BEFORE%20%7C%20AFTER%20%5D) So if `red` has `enumsortorder = 1` in the beginning, it can end up with a different value after an ALTER. So any rows inserted with that original sort order in mind may now belong to the wrong content-id in the post-ALTER world.

So, this is too much trouble to support IMO and we can just ban it w/ errcode FEATURE_NOT_SUPPORTED.

**Comment by ashwinstar** [comment]
> So, this is too much trouble to support IMO and we can just ban it w/ errcode FEATURE_NOT_SUPPORTED.

Range partitioning for enum is allowed in upstream and GPDB7 code. How does that work?

**Comment by AJR-VMware** [comment]
After digging into a bit, here's what I've found.

- A range partition in both upstream and GPDB7 is still partitioning by the OID of the enum value, as shown in the ranges below
- The enum values are given OIDs sequentially, and always in the same order given in the create type statement.
- Because of the syntax for creating partition tables, they will always create the correct table by name and reference the correct OID for the current database.  Thus while the OIDs are still non-deterministic, all the individual steps are still valid and should work, even in a backup/restore situation.
- This does, however, artificially limit the ranges that can be expressed in a range partition, as trying to create overlapping or out-of-order ranges across OIDs will throw an error regardless of the values in the enum

```sh
testdb=# create type colors as enum ('red', 'green', 'blue', 'yellow');
CREATE TYPE
testdb=# select oid,* from pg_enum ;
  oid  |  oid  | enumtypid | enumsortorder | enumlabel 
-------+-------+-----------+---------------+-----------
 16958 | 16958 |     16957 |             1 | red
 16960 | 16960 |     16957 |             2 | green
 16962 | 16962 |     16957 |             3 | blue
 16964 | 16964 |     16957 |             4 | yellow
(4 rows)
```
```SQL
create type colors as enum ('red', 'green', 'blue', 'yellow');
create table legacy_enum(color colors) PARTITION BY RANGE (color) distributed by (color);
CREATE TABLE legacy_enum_red PARTITION OF legacy_enum FOR VALUES FROM ('red') to ('green');
CREATE TABLE legacy_enum_green PARTITION OF legacy_enum FOR VALUES FROM ('green') to ('blue');
CREATE TABLE legacy_enum_blue PARTITION OF legacy_enum FOR VALUES FROM ('blue') to ('yellow');
CREATE TABLE legacy_enum_yellow PARTITION OF legacy_enum default;
insert into legacy_enum values ('red'), ('green'), ('blue'), ('yellow');
```

**Comment by ashwinstar** [comment]
Thanks!

> Unfortunately however, enum types can be altered (including their elements' ordinal position ￼ ).

Does this have any impact on partitioning?

**Comment by AJR-VMware** [comment]
I'm not clear how that would be possible.   Per https://www.postgresql.org/docs/current/datatype-enum.html

>Although enum types are primarily intended for static sets of values, there is support for adding new values to an existing enum type, and for renaming values (see [ALTER TYPE](https://www.postgresql.org/docs/current/sql-altertype.html)). Existing values cannot be removed from an enum type, nor can the sort ordering of such values be changed, short of dropping and re-creating the enum type.

**Comment by soumyadeep2007** [comment]
Okay I was paranoid for no reason (checked against both GPDB and Postgres 16):

```sql
create type colors as enum ('red', 'green', 'blue', 'yellow');
create table legacy_enum(color colors) PARTITION BY RANGE (color);
CREATE TABLE legacy_enum_red PARTITION OF legacy_enum FOR VALUES FROM ('red') to ('green');
CREATE TABLE legacy_enum_green PARTITION OF legacy_enum FOR VALUES FROM ('green') to ('blue');
CREATE TABLE legacy_enum_blue PARTITION OF legacy_enum FOR VALUES FROM ('blue') to ('yellow');
CREATE TABLE legacy_enum_yellow PARTITION OF legacy_enum default;
insert into legacy_enum values ('red'), ('green'), ('blue'), ('yellow');

alter type colors add value 'orange' before 'yellow';

-- Now if we insert 'orange', it correctly hashes to the blue partition!
postgres=# insert into legacy_enum values('orange');
INSERT 0 1
postgres=# select * from legacy_enum_blue;
 color  
--------
 blue
 orange
(2 rows)

-- The following reveals why:
postgres=# select * from pg_enum;
  oid  | enumtypid | enumsortorder | enumlabel 
-------+-----------+---------------+-----------
 16386 |     16385 |             1 | red
 16388 |     16385 |             2 | green
 16390 |     16385 |             3 | blue
 16392 |     16385 |             4 | yellow
 16409 |     16385 |           3.5 | orange   <------------------------- 3.5!!! Sneaky! Also, notice that the oid is much higher
(5 rows)
```
Existing enum constants ('blue' and 'yellow') indeed don't have their ordinal positions changed!

> A range partition in both upstream and GPDB7 is still partitioning by the OID of the enum value, as shown in the ranges below

So the `enumsortorder` is what is dictating range partitioning and not the `oid`. See `compare_values_of_enum()` and following stack for tuple routing upon insert:

```
compare_values_of_enum typcache.c:2484
enum_cmp_internal enum.c:296
enum_cmp enum.c:377
FunctionCall2Coll fmgr.c:1146
partition_rbound_datum_cmp partbounds.c:3588
partition_range_datum_bsearch partbounds.c:3728
get_partition_for_tuple execPartition.c:1535
ExecFindPartition execPartition.c:321
ExecPrepareTupleRouting nodeModifyTable.c:3404
ExecInsert nodeModifyTable.c:734
...
```

I think with all this in mind, we can use the `enumsortorder` to do our hashing.

**Comment by l-wang** [comment]
Actually, upstream Postgres as of now (16devel) would suffer the same problem for HASH Partitioning with pg_dump and pg_restore.

Repro on upstream PG16devel:

```sql
create database test;
\c test
create type colors as enum ('red', 'green', 'blue', 'yellow');
create table part (color colors) partition by hash(color);
create table prt_0 partition of part for values with (modulus 3, remainder 0);
create table prt_1 partition of part for values with (modulus 3, remainder 1);
create table prt_2 partition of part for values with (modulus 3, remainder 2);
insert into part values ('red');
```
Then we would have `satisfies_hash_partition()` as the partition constraint for each child partition like below:
```
test=# select * from prt_2;
 color 
-------
 red
(1 row)

test=# \d+ prt_0
                                         Table "public.prt_0"
 Column |  Type  | Collation | Nullable | Default | Storage | Compression | Stats target | Description 
--------+--------+-----------+----------+---------+---------+-------------+--------------+-------------
 color  | colors |           |          |         | plain   |             |              | 
Partition of: part FOR VALUES WITH (modulus 3, remainder 0)
Partition constraint: satisfies_hash_partition('16395'::oid, 3, 0, color)
Access method: heap
```
Now backup and restore database `test` into `test2`:
```sh
usr/local/pgsql/bin/pg_dump -d test -f /tmp/dump.sql
usr/local/pgsql/bin/createdb test2
/usr/local/pgsql/bin/psql test2 -f /tmp/dump.sql
```

The generated sql file would insert data directly into the child partition like below:
```
COPY public.prt_2 (color) FROM stdin;
red
\.
```

`pg_restore` gets the following ERROR:
```
psql:/tmp/dump.sql:135: ERROR:  new row for relation "prt_2" violates partition constraint
```

**Comment by AJR-VMware** [comment]
@ashwinstar I finally have some bandwidth to circle back to this.  
Per @l-wang comments on [this PR](https://github.com/greenplum-db/gpdb/pull/14242/files) it sounds like adding a catalog table lookup to the enum hash function is not a good call.  However, there are many assumptions baked throughout the code about enums being represented simply as OIDs (see btree_enum.c for example).

I am not sure what the best next steps would be for resolving this.  Given the complexity of re-implementing enums as arrays of [oid,enumsortorder], I wonder if we're back to banning distribution by enum fields.  That would leave the same issue in both GPDB and upstream for using enums as partition keys for hash partitions.

I'd be curious to hear your thoughts.  Thank you!

**Comment by AJR-VMware** [comment]
Resolved by: https://github.com/greenplum-db/gpdb/pull/14704
