### ISSUE TITLE
Is it a bad idea to use LZ4 compression for AOCO tables?

### ISSUE THREAD

**Issue by zhjwpku** [greenplum-db/gpdb#14220]
LZ4 compression is used for MariaDB Enterprise ColumnStore tables[0], and upstream Postgres
uses LZ4 for full-page writes in WAL [1] and toast compression [4]. LZ4 claims it is a extreamly fast
compression algorithm with acceptable compression ratio(see lzbench benchmarks [2]), so I
think it might be a good idea to implement it for gpdb Append-Optimized tables, see #14219.

Then I did some benchmarks to test its performance, use the tpch dataset(scale = 1) and its 
queries [3].

### AOCO tables

First I test with AOCO tables, results:

#### Load time(ms)
| compresstype/table | customer | lineitem | nation | orders | part | partsupp | region | supplier |
|----|----|----|----|----|----|----|----|----|
| zstd-1 | 263.573 | 18503.218 | 4.327 | 2999.307 | 366.919 | 1332.789 | 2.178 | 31.185 |
| zlib-1 | 815.016 | 22364.697 | 2.982 | 4294.813 | 467.137 | 1957.461 | 3.669 | 34.353 |
| lz4fast-1 | 376.789 | 17069.180 | 4.324 | 3336.350 | 324.844 | 1044.733 | 2.070 | 19.976 |
| lz4hc-3 | 710.396 | 23646.050 | 3.064 | 4028.217 | 564.752 | 2401.848 | 6.249 | 33.812 |
| lz4hc-4 | 774.177 | 26686.915 | 2.513 | 5005.852 | 663.493 | 2957.557 | 2.318 | 50.373 |
| lz4hc-9 | 1072.746 | 59036.378 | 2.271 | 7273.430 | 1257.223 | 3566.052 | 2.096 | 47.085 |
| lz4hc-12 | 2384.220 | 184759.094 | 3.104 | 20177.971 | 2084.076 | 8031.963 | 2.650 | 127.612 |

#### Compress Ratio
| compresstype/table | customer | lineitem | nation | orders | part | partsupp | region | supplier |
|----|----|----|----|----|----|----|----|----|
| zstd-1 | 2.8 | 3.97 | 2.35 | 3.85 | 4.64 | 3.5 | 1.51 | 2.72 |
| zlib-1 | 2.68 | 3.77 | 2.39 | 3.68 | 4.48 | 3.34 | 1.57 | 2.59 |
| lz4fast-1 | 1.84 | 2.32 | 1.7 | 2.42 | 2.57 | 2.27 | 1.28 | 1.79 |
| lz4hc-3 | 2.1 | 2.91 | 1.87 | 2.85 | 3.39 | 2.83 | 1.35 | 2.01 |
| lz4hc-4 | 2.14 | 3.03 | 1.87 | 2.93 | 3.51 | 2.91 | 1.35 | 2.04 |
| lz4hc-9 | 2.2 | 3.31 |  1.89 | 3.08 | 3.76 | 3.03 | 1.35 | 2.08 |
| lz4hc-12 | 2.22 | 3.37 | 1.89 | 3.12 | 3.81 | 3.09 | 1.38 | 2.1 |

#### Query time(ms)
| compresstype/query | Query 1 | Query 3 | Query 5 | Query 6 | Query 10 | Query 12 | Query 14 | Query 19 |
|----|----|----|----|----|----|----|----|----|
| zstd-1 |  12750.708 | 1935.844 | 2850.552 | 1123.828 | 2172.468 | 1363.040 | 1389.341 | 1475.799 |
| zlib-1 | 12255.473 | 1796.140 | 3055.062 | 1455.529 | 1697.410 | 1591.493 | 1611.563 | 1564.087 |
| lz4fast-1 | 11833.921 | 1737.127 | 2917.798 | 1310.874 | 1846.998 | 1587.378 | 674.486 | 1274.537 |
| lz4hc-3 | 13334.714 | 1934.698 | 2964.451 | 1522.425 | 1732.611 | 1615.380 | 630.600 | 1243.352 |
| lz4hc-4 | 12910.341 | 1645.480 | 2929.098 | 1210.480 | 1665.366 | 1594.494 | 752.928 | 1216.242 |
| lz4hc-9 | 10241.605 | 1995.816 | 2659.824 | 761.416 | 1616.680 | 1610.694 | 704.800 | 1297.918 |
| lz4hc-12 | 10437.719 | 1240.470 | 2473.957 | 842.155 | 1499.599 | 1693.635 | 741.334 | 1226.010 |

From the above results, zstd's compression ratio and load time seems outperform all lz4 kinds, lz4-9's
query performance is a little better than zstd and zlib, but without testing zstd with higher compress-
level.

So it seems lz4 is not a good competitor for Append-Optimized tables.

### AORO tables

Then I do the same test for AORO tables with zstd-1 and lz4fast-1, results:

#### Load time(ms)
| compresstype/table | customer | lineitem | nation | orders | part | partsupp | region | supplier |
|----|----|----|----|----|----|----|----|----|
| zstd-1 | 420.967 | 19895.121 | 4.442 | 3068.569 | 421.113 | 1549.022 | 1.753 | 26.155 |
| lz4fast-1 | 354.301 | 18861.442 | 1.951 | 2776.222 | 354.543 | 1118.629 | 4.124 | 18.566 |

#### Compress Ratio
| compresstype/table | customer | lineitem | nation | orders | part | partsupp | region | supplier |
|----|----|----|----|----|----|----|----|----|
| zstd-1 | 2.21 | 2.97 | 2.35 | 3.13 | 2.88 | 2.96 | 1.64 | 2.15 |
| lz4fast-1 | 1.8 | 2.26 | 1.83 | 2.45 | 2.21 | 2.13 | 1.42 | 1.73 |

#### Query time(ms)
| compresstype/query | Query 1 | Query 3 | Query 5 | Query 6 | Query 10 | Query 12 | Query 14 | Query 19 |
|----|----|----|----|----|----|----|----|----|
| zstd-1 | 14025.561 | 3314.817 | 4519.812 | 2158.636 | 2823.705 | 2737.597 | 2555.599 | 2229.838 |
| lz4fast-1 | 11181.969 | 2198.581 | 2934.344 | 1537.930 | 2831.776 | 2430.712 | 1577.658 | 2076.878 |

For AORO tables, LZ4 is really faster than Zstd, though the compression ratio is poor than zstd.

### Question

For the above tests, seems LZ4 is more proper for row oriented tables, so is it bad idea to use LZ4
for column oriented tables? If so, why Mariadb ColumnStore choose LZ4 other than Zstd?

[0] https://mariadb.com/docs/reference/mdb/system-variables/columnstore_compression_type/
[1] https://github.com/postgres/postgres/commit/4035cd5d4eee4dae797bfc77ab07f8dcd8781b41
[2] https://github.com/inikep/lzbench#benchmarks
[3] https://gist.github.com/zhjwpku/d8ffe0f37a8fb425c226b6f071187f36
[4] https://www.postgresql.org/message-id/E1lNKw9-0008DT-1L%40gemulon.postgresql.org

**Comment by soumyadeep2007** [comment]
Closing this issue. See reasoning [here](https://github.com/greenplum-db/gpdb/pull/14219#issuecomment-1414557402).
