### ISSUE TITLE
gpactivatestandby requires master data directory to be set twice

### ISSUE THREAD

**Issue by shubh8689** [greenplum-db/gpdb#1424]
This is similar behavior as seen under #1145  but for gpactivatestandby. I have already submitted a pull request #1385 to fix #1145 . The changes should be similar, will submit a pull request for this issue as well.

As per current behavior, both, environment variable MASTER_DATA_DIRECTORY and -d parameter should be set. They must also have the same value.

[gpadmin@smdw ~]$ gpactivatestandby -d /usr/local/
20161207:14:19:13:000729 gpactivatestandby:smdw:gpadmin-[CRITICAL]:-Current setting of MASTER_DATA_DIRECTORY not same as -d parameter.
[gpadmin@smdw ~]$ echo $MASTER_DATA_DIRECTORY 
/data/gpdb/gpsegmnt-1

**Comment by ivannovick** [comment]
@Chibin @oakbarrett has this fix been merged? Can we close the issue?

**Comment by ivannovick** [comment]
@skahler-pivotal for more follow up

**Comment by Chibin** [comment]
@ivannovick Not yet, we'll be doing this soon.

**Comment by shubh8689** [comment]
Last time I didn't have the merge rights and Daniel helped me. I was recently added to GPDB org. I can give it a try. Are we following https://github.com/greenplum-db/greenplum-db.github.io/wiki/Merging-Pull-Requests to maintain a linear commit history ?

**Comment by danielgustafsson** [comment]
Correct, merge commits are only allowed for merging upstream PostgreSQL releases.

**Comment by cjcjameson** [comment]
@skahler-pivotal Closing this issue as the PR has been pushed.
