### ISSUE TITLE
gporca can not get correct result when records in multiple partitions

### ISSUE THREAD

**Issue by cherchill2333** [greenplum-db/gpdb#14303]
### Greenplum version or build
Greenplum Database 6.21.2

### OS version and uname -a
Linux db.prod.dc 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

### Expected behavior
output : 2022-10-23
### Actual behavior
output : 2022-10-22
### Step to reproduce the behavior
1. create tables
```
create table public.test
(datedday date)
WITH (
	appendonly=false
)
PARTITION BY RANGE(datedday) 
          (
          PARTITION pn_20221022 START ('2022-10-22'::date) END ('2022-10-23'::date),
          PARTITION pn_20221023 START ('2022-10-23'::date) END ('2022-10-24'::date),
          DEFAULT PARTITION pdefault
);
```
2. load data
```
insert into public.test(datedday)  
select ('2022-10-22'::date)
union 
select ('2022-10-23'::date);
```
3. query
```
select max(datedday) 
from public.test 
where datedday='2022-10-23' 
or 
datedday=('2022-10-23'::date -interval '1 day');
```
result
```
2022-10-22
```
but if  disable GPORCA  before query (set optimizer = off ), we can get the correct result .

**Comment by kainwen** [comment]
Fixed by https://github.com/greenplum-db/gpdb/pull/14535
