### ISSUE TITLE
172576000 - COPY  may still exist

### ISSUE THREAD

**Issue by dblife1024** [greenplum-db/gpdb#14317]
hi，

IN https://greenplum.docs.pivotal.io/6-8/relnotes/gpdb-68-release-notes.html  that has
“172576000 - COPY
If data format errors occurred while copying data into a partitioned table with a COPY FROM command in single row error isolation mode, Greenplum Database might crash when a query executor (QE) did not handle the data format error correctly. This issue is resolved.”
From the observation in the afternoon，this bug may still exist. 
My version is 6.19.4. It is partition table that contains 10 million data. and It has been running for a month. 
Just when I  execute copy data, the segment will crash. After replacing it with insert, everything is normal.

**Comment by kainwen** [comment]
Sorry for long time no reply. Do you have any LOGs or coredump available?

**Comment by kainwen** [comment]
Close due to lack of necessary artifacts (cores, logs, sqls...).

Feel free to open new issue with artifacts.
