### ISSUE TITLE
The redistribution of millions of data may cause some SQL execution delays that rely on small redistribution.

### ISSUE THREAD

**Issue by cobolbaby** [greenplum-db/gpdb#14321]
### Greenplum version or build

- 6.20.5

### Actual behavior

I found that if there are tens of millions of table data redistribution in the cluster, it will often cause a relatively large performance jitter, and the execution time of other SQL will be significantly delayed. Because the server hardware uses a 10 Gigabit network card, I am not sure what the bottleneck point of the database is at this time. If data redistribution is unavoidable, how should we avoid other SQLs being affected by the redistribution? What parameters can be optimized?

**Comment by kainwen** [comment]
Can you paste the minirepro and plan here?

**Comment by cobolbaby** [comment]
This is a common phenomenon and you should be able to reproduce it. 

Because the SQL involves a huge table, it is not convenient to dump.

**Comment by kainwen** [comment]
> It seems that if two or three million-level data are redistributed in the cluster, GP will experience performance jitter. This is a common phenomenon and you should be able to reproduce it.
> 
> Because the SQL involves a huge table, it is not convenient to dump.

minirepro has nothing to do with data, it helps developers reproduce planning locally.

Please provide minirepro and the plan, otherwise, we cannot help on this issue.

**Comment by ashwinstar** [comment]
@cobolbaby are you using Resource Groups for resource management? We don't have direct knob to control n/w usage, though using RG can control CPU usage between different workload that should help.

**Comment by cobolbaby** [comment]
> are you using Resource Groups for resource management

I just config the resource queue.

**Comment by kainwen** [comment]
Long time no response. Close it.

Feel free to re-open if artifacts are available.

**Comment by cobolbaby** [comment]
Caused by udp buffer.
