### ISSUE TITLE
Provide MPP version of PostgreSQL stat* functionality

### ISSUE THREAD

**Issue by ashwinstar** [greenplum-db/gpdb#14337]
## Feature Request
PostgreSQL has many stat views/functions like
```
stat_all_indexes
stat_all_tables
stat_bgwriter
stat_database
stat_replication
statio_all_indexes
statio_all_sequences
statio_all_tables
and more...
```
This information is available at each GPDB segment level locally. Though no centralized MPP version of these exists to expose them as single interface to fetch the values via coordinator node.

**Is your feature request related to a problem? Please describe:**
Need to login in utility mode to fetch these details currently which is extremely inconvenient.

**Describe the feature you'd like to request:**
PR https://github.com/greenplum-db/gpdb/pull/5314 attempted to solve the current state though never reached the finish line and remained in WIP state. This issue is to track the feature request from that PR. We should try to take the PR to completion.  Or longer term think of some other innovative solution to the problem like is there *auto* way to have MPP interface for all such PostgreSQL views/functions similar to `gp_dist_random` for tables :-) then don't need to handcode MPP version of each PostgreSQL equivalent.

**Comment by maksm90** [comment]
There was attempt to implement this for statistics on tables and indexes in https://github.com/greenplum-db/gpdb/pull/13520

**Comment by ashwinstar** [comment]
@huansong I am guessing this can be closed now as done?

**Comment by huansong** [comment]
Yes. Done via https://github.com/greenplum-db/gpdb/pull/15239.
