### ISSUE TITLE
Query very slow with simple query through master.

### ISSUE THREAD

**Issue by soulfere** [greenplum-db/gpdb#14333]
### Greenplum version or build
6.16.2
### OS version and uname -a
CentOS 7.3
### Expected behavior
A partitioned table with 600 partitions, partitioned and distributed by date column, one partition's data is stored on one instance. Query single partition through master.
### Actual behavior
There is a big difference in query speed between partitions. Some partitions performance fast, some even cannot get data.
When I query the data directly from segment. The performance is consistent between partitions.
When I check the query plan, I found a huge delay.
Query:
EXPLAIN ANALYZE SELECT * FROM table_1_prt_660 LIMIT 1;
Part of query plain:
 ->  Seq Scan on table_1_prt_660  (cost=0.00..470.17 rows=608734 width=87) (**actual time=10513.343..10513.343** rows=1 loops=1)

**Comment by kainwen** [comment]
The artifacts in this issue does not seem a bug. Please find where the time is spent when slowness happens.

Serveral directions:

1. constantly pstack on segment and master
2. set debug guc on and analyze the log

```set log_dispatch_stats to on;
set log_min_messages to debug1;
set log_min_duration_statement to 0;
set gp_log_gang to debug;
```

**Comment by kainwen** [comment]
Long time no response. Close this.
Feel free to re-open if needed.
