### ISSUE TITLE
gpmovemirrors: add disk space check

### ISSUE THREAD

**Issue by ashwinstar** [greenplum-db/gpdb#14340]
## Enhancement
gpmovemirrors fails late while creating mirrors (after running for several hours), if we find that there isn't enough disk space on the host. This change is to have a disk space check before we start creating mirrors/copying data.

Draft PR for reference https://github.com/greenplum-db/gpdb/pull/11892 when picking this enhancement mostly can be used to take it forward.

**Comment by nimish350** [comment]
Fixed by https://github.com/greenplum-db/gpdb/pull/16158

**Comment by kainwen** [comment]
> Fixed by #16158

Seem the above PR is not merged.

**Comment by nimish350** [comment]
> > Fixed by #16158
> 
> Seem the above PR is not merged.

Its added for merge approval.
