### ISSUE TITLE
COPY ON SEGMENT references wrong column for distribution key in child partition tables with out-of-order columns

### ISSUE THREAD

**Issue by AJR-VMware** [greenplum-db/gpdb#14353]
### Greenplum version or build
`PostgreSQL 12beta2 (Greenplum Database 7.0.0-alpha.0+dev.15878.g5fcb4ad9ad build dev) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0, 64-bit compiled on Oct 25 2022 16:39:31`

### OS version and uname -a
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.5 LTS"
NAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Fossa)"
```

`uname -a :`  `Linux ajrdevbox 5.15.0-52-generic #58~20.04.1-Ubuntu SMP Thu Oct 13 13:09:46 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

### autoconf options used ( config.status --config )
`'--with-perl' '--with-python' '--with-libxml' '--enable-mapreduce' '--enable-orafce' '--disable-orca' '--with-openssl' '--enable-debug' '--enable-depend' 'CFLAGS=-O0 -fno-omit-frame-pointer'`

### Installation information ( pg_config )
```
BINDIR = /usr/local/gpdb/bin
DOCDIR = /usr/local/gpdb/share/doc/postgresql
HTMLDIR = /usr/local/gpdb/share/doc/postgresql
INCLUDEDIR = /usr/local/gpdb/include
PKGINCLUDEDIR = /usr/local/gpdb/include/postgresql
INCLUDEDIR-SERVER = /usr/local/gpdb/include/postgresql/server
LIBDIR = /usr/local/gpdb/lib
PKGLIBDIR = /usr/local/gpdb/lib/postgresql
LOCALEDIR = /usr/local/gpdb/share/locale
MANDIR = /usr/local/gpdb/share/man
SHAREDIR = /usr/local/gpdb/share/postgresql
SYSCONFDIR = /usr/local/gpdb/etc/postgresql
PGXS = /usr/local/gpdb/lib/postgresql/pgxs/src/makefiles/pgxs.mk
CONFIGURE = '--with-perl' '--with-python' '--with-libxml' '--enable-mapreduce' '--enable-orafce' '--disable-orca' '--with-openssl' '--enable-debug' '--enable-depend' 'CFLAGS=-O0 -fno-omit-frame-pointer'
CC = gcc
CPPFLAGS = -D_GNU_SOURCE -I/usr/include/libxml2
CFLAGS = -Wall -Wmissing-prototypes -Wpointer-arith -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-unused-but-set-variable -Werror=implicit-fallthrough=3 -Wno-format-truncation -Wno-stringop-truncation -g -O0 -fno-omit-frame-pointer  -Werror=uninitialized -Werror=implicit-function-declaration
CFLAGS_SL = -fPIC
LDFLAGS = -Wl,--as-needed -Wl,-rpath,'/usr/local/gpdb/lib',--enable-new-dtags
LDFLAGS_EX = 
LDFLAGS_SL = 
LIBS = -lpgcommon -lpgport -lpthread -lbz2 -lxml2 -lrt -lssl -lcrypto -lz -lreadline -lrt -lcrypt -ldl -lm  -lcurl -lzstd
VERSION = PostgreSQL 12beta2
```

### Expected behavior
Running `copy on segment`  will successfully load data from the correct segment, as determined by the distribution key.

### Actual behavior
Running copy on segment references the wrong distribution key if child partition tables have columns in a different order than the parent table.  This causes errors on data load via `copy on segment`.

### Step to reproduce the behavior
Run the below DDL in a  test DB on a 3-segment cluster.  Run gpbackup on this DB, then restore to a new one.  The third row (1,2,'a') will not be loaded via `copy on segment` because it is assigned to segment 1, but the code references `b` instead of `a` when trying to copy it in, and incorrectly determines it should be on segment 0 instead.
```sql
CREATE TABLE public.mlparted (
	a integer,
	b integer,
	c text
) PARTITION BY RANGE (a) DISTRIBUTED BY (a);

CREATE TABLE public.mlparted1 (
	b integer NOT NULL,
	a integer NOT NULL,
	c text
) DISTRIBUTED BY (a);
ALTER TABLE ONLY public.mlparted ATTACH PARTITION public.mlparted1 FOR VALUES FROM (1) TO (2);


CREATE TABLE public.mlparted_def (
	a integer,
	b integer,
	c text
) DISTRIBUTED BY (a);
ALTER TABLE ONLY public.mlparted ATTACH PARTITION public.mlparted_def DEFAULT;

insert into mlparted values (10, 2, 'a');
insert into mlparted values (11, 2, 'a');
insert into mlparted values (1, 2, 'a');
```

**Comment by higuoxing** [comment]
Hi @AJR-VMware, thanks for reporting the issue. I'm working on this issue. But it seems that `gpbackup` doesn't support gpdb7?

I'm using the `main` branch of `gpbackup` and I've executed the given DDL in `postgres` db. Then I run the `gpbackup` against the `postgres` db.

There's an error message saying `pg_partition_rules` doesn't exist.

```
20221113:21:04:51 gpbackup:v:laptop:302991-[INFO]:-gpbackup version = 1.26.0+dev.2.g68cebca
20221113:21:04:51 gpbackup:v:laptop:302991-[INFO]:-Greenplum Database Version = 7.0.0-alpha.0+dev.15953.g0c6e53f4c9 build dev
20221113:21:04:51 gpbackup:v:laptop:302991-[INFO]:-Starting backup of database postgres
20221113:21:04:51 gpbackup:v:laptop:302991-[INFO]:-Backup Timestamp = 20221113210451
20221113:21:04:51 gpbackup:v:laptop:302991-[INFO]:-Backup Database = postgres
20221113:21:04:51 gpbackup:v:laptop:302991-[INFO]:-Gathering table state information
20221113:21:04:51 gpbackup:v:laptop:302991-[CRITICAL]:-ERROR: relation "pg_partition_rule" does not exist (SQLSTATE 42P01)
20221113:21:04:52 gpbackup:v:laptop:302991-[INFO]:-Found neither /home/v/.local/gpdb7/bin/gp_email_contacts.yaml nor /home/v/gp_email_contacts.yaml
20221113:21:04:52 gpbackup:v:laptop:302991-[INFO]:-Email containing gpbackup report /home/v/x/gh/gpdb7/gpAux/gpdemo/datadirs/qddir/demoDataDir-1/backups/20221113/20221113210451/gpbackup_20221113210451_report will not be sent
20221113:21:04:52 gpbackup:v:laptop:302991-[WARNING]:-Encountered error during cleanup: 20221113:21:04:52 gpbackup:v:laptop:302991-[CRITICAL]:-ERROR: column "waiting" does not exist (SQLSTATE 42703)
```

I would like know are you running `gpbackup` against gpdb7? As far as I know, the `pg_partition_rule` catalog table has been removed in gpdb7.

**Comment by AJR-VMware** [comment]
Hi!  Sorry about that, I'm a dev on the Greenplum Data Protection team, I forgot that work isn't merged into `main` yet.  Our gp7 support branch can be found at the link below.  It will work on most examples, though there's still some edge case work to support (notably subpartition templates still not there yet).  You should be able to get databases backed up and restored on 7 using that branch, and this repro will show up there as expected.

https://github.com/greenplum-db/gpbackup/tree/gpdb7_support
