### ISSUE TITLE
GRANT for partitioned and unpartitioned tables in one command

### ISSUE THREAD

**Issue by lveraszto** [greenplum-db/gpdb#14446]
## Bug Report
When i run a GRANT command for more tables which contains partitioned and unpartitioned tables the GRANT command says success but only partitioned tables get the granted permission. **Workaround**: split the command to GRANT permissions only for partitioned tables and GRANT with another command to unpartitioned tables.
### Greenplum version or build
6.22
### OS version and uname -a
macOS different versions, centOS
### Expected behavior
All tables should get the permission OR command should fail.
### Actual behavior
Not all tables get the permission even if the comamdn was successful.
### Step to reproduce the behavior
**GRANTING**
`GRANT SELECT ON my_not_partitioned_Table, my_partitioned_table TO my role;`
**Check the permissions**
`SELECT * FROM information_schema.table_privileges`

**Comment by kainwen** [comment]
6X fixed by https://github.com/greenplum-db/gpdb/pull/14594
Main branch not reproduce the issue.
