### ISSUE TITLE
6.12 up to v6.22， sql run slower even crash

### ISSUE THREAD

**Issue by wonb168** [greenplum-db/gpdb#14454]
## Bug Report
6.12 up to v6.22， sql run slower even crash
### Greenplum version or build
6.22
### OS version and uname -a
centos7
### Expected behavior
same to 6.12
### Actual behavior
much more slower than v6.12
### Step to reproduce the behavior
explain analyze , then find **broadcast** and **nested loop** in it, but after `analyze table`, then run OK.
but there are too many tables, and write `analyze table` in business code is unfriendly。
why?
and how to resolve this?
Now, I tried to test change gp_autostats_mode and gp_autostats_on_change_threshold.
any other method to get the Statistics timely and accurate？

**Comment by kainwen** [comment]
There are 2 problems in this:

1  .crash: 
we need to collect cores, logs and minirepro

2 . > explain analyze , then find broadcast and nested loop in it, but after analyze table, then run OK.

Can you share minirepro of such SQL here? It looks just like stats info is out-of-date. What is the plan before and after `analyze`?

Business code should not touch this. DBA should try to maintain stats info make it up-to-date.

**Comment by ashwinstar** [comment]
@wonb168 would be helpful if you can share the info asked above to investigate the problem, without that sorry to say we can't help much.
