### ISSUE TITLE
[6X] Missing pg_attribute_encoding entries for table created with (appendonly,orientation=column)

### ISSUE THREAD

**Issue by huansong** [greenplum-db/gpdb#14510]
## Bug Report

Just like AO table that can be created with the convenient `(appendonly)` option which implicitly indicates that `appendonly=true`, when table is created with `(appendonly,orientation=column)` it is made an AOCO table. However, we don't seem to create pg_attribute_encoding for it, resulting in error behavior. E.g.:

```
postgres=# create table foo(a int) with(appendonly,orientation=column);
CREATE TABLE
postgres=# \d+ foo
                                         Append-Only Columnar Table "public.foo"
 Column |  Type   | Modifiers | Storage | Stats target | Compression Type | Compression Level | Block Size | Description
--------+---------+-----------+---------+--------------+------------------+-------------------+------------+-------------
 a      | integer |           | plain   |              | None             | 0                 | 32768      |
Checksum: t
Distributed by: (a)
Options: appendonly=true, orientation=column

postgres=# insert into foo select * from generate_series(1,1000);
ERROR:  No relation attribute options for 'foo', column #1  in pg_attribute_encoding (aocsam.c:155)  (seg1 127.0.1.1:6003 pid=22070) (aocsam.c:155)

postgres=# select count(*) from pg_attribute_encoding a, pg_class c where a.attrelid=c.oid and c.relname = 'foo';
 count
-------
     0
(1 row)
```
Seems that the problem happens in `transformCreateStmt->is_aocs` where it skips `appendonly` option because it doesn't carry an argument: https://github.com/greenplum-db/gpdb/blob/6X_STABLE/src/backend/parser/parse_utilcmd.c#L4703-L4707 . So the stmt->attr_encodings is not populated. 

Luckily it won't cause data corruption because no insert can be done in that situation, so its impact is limited. Also 7X doesn't have this problem. But it would still be nice to avoid this situation.

### Greenplum version or build
6X_STABLE branch (head 48fc156ecde048f476034c72e06969cdadbd1e5c)

**Comment by ashwinstar** [comment]
Seems fine to fail the CREATE with that syntax instead of trying to fix anywhere else in code.

**Comment by huansong** [comment]
@ashwinstar We can just replace "appendonly" with "appendonly=true" on the syntax level. Failing that case needs to cross-check different reloptions (i.e. "appendonly" and "orientation") which actually needs more "fix" than below.

```
--- a/src/backend/parser/gram.y
+++ b/src/backend/parser/gram.y
@@ -3193,7 +3193,10 @@ reloption_elem:
                                }
                        | ColLabel
                                {
-                                       $$ = makeDefElem($1, NULL);
+                                       if (strcmp($1, "appendonly") == 0)
+                                               $$ = makeDefElem($1, (Node *) makeString(pstrdup("true")));
+                                       else
+                                               $$ = makeDefElem($1, NULL);
                                }
                        | ColLabel '.' ColLabel '=' def_arg
                                {
```

**Comment by ashwinstar** [comment]
Okay, proposed seems fine to me and actually better. As upstream also allows specifying only keyword without value to convey TRUE for things. Thank you.
