### ISSUE TITLE
AOCO: error on read after ADD COLUMN + INSERT + ABORT

### ISSUE THREAD

**Issue by divyeshddv** [greenplum-db/gpdb#14518]
## Bug Report
AOCO table read fails after ADD COLUMN + INSERT + ABORT
With the following error:
```
postgres=# select * from t;
ERROR:  Unexpected internal error (assert.c:48)  (seg0 slice1 127.0.0.1:7002 pid=31563) (assert.c:48)
DETAIL:  FailedAssertion("!(((__builtin_constant_p(((varattrib_4b *) (dv))->va_4byte.va_header) ? ((__uint32_t)((((__uint32_t)(((varattrib_4b *) (dv))->va_4byte.va_header) & 0xff000000U) >> 24) | (((__uint32_t)(((varattrib_4b *) (dv))->va_4byte.va_header) & 0x00ff0000U) >> 8) | (((__uint32_t)(((varattrib_4b *) (dv))->va_4byte.va_header) & 0x0000ff00U) << 8) | (((__uint32_t)(((varattrib_4b *) (dv))->va_4byte.va_header) & 0x000000ffU) << 24))) : _OSSwapInt32(((varattrib_4b *) (dv))->va_4byte.va_header)) & 0x3FFFFFFF) <= aocs_vpinfo_size(nvp))", File: "aocssegfiles.c", Line: 401)
```
### Greenplum version or build:
main

### OS version and uname -a 
Darwin Kernel Version 21.6.0

### Expected behavior
SELECT should work fine and show existing rows

### Actual behavior
SELECT query fails with assertion failure

### Step to reproduce the behavior
```
create table t(a int, b int, c int) using ao_column;
insert into t select i,i,i from generate_series(1,10)i;
begin;
alter table t add column d int;
insert into t select i,i from generate_series(1,10)i;
abort;
select * from t;
```

**Comment by ashwinstar** [comment]
How about we adjust code to ignore vpinfo column entries with eof=0 during reads? (and let next insert correctly adjust the vpinfo). As frozen insert (after add column) should have eof=0 and update with any valid eof will get rolled back as that's mvcc.

This should have minimum impact to code, compared to taking out frozen inserts or using snapshot dirty for handling this rare case scenario. Thoughts?

**Comment by divyeshddv** [comment]
> How about we adjust code to ignore vpinfo column entries with eof=0 during reads? (and let next insert correctly adjust the vpinfo). As frozen insert (after add column) should have eof=0 and update with any valid eof will get rolled back as that's mvcc.
> 
> This should have minimum impact to code, compared to taking out frozen inserts or using snapshot dirty for handling this rare case scenario. Thoughts?

The initial insert after add column (in InsertInitialAOCSFileSegInfo) which will update it with a eof>0 is also a frozen insert. This doesn't get rolled back.

**Comment by ashwinstar** [comment]
> > How about we adjust code to ignore vpinfo column entries with eof=0 during reads? (and let next insert correctly adjust the vpinfo). As frozen insert (after add column) should have eof=0 and update with any valid eof will get rolled back as that's mvcc.
> 
> > 
> 
> > This should have minimum impact to code, compared to taking out frozen inserts or using snapshot dirty for handling this rare case scenario. Thoughts?
> 
> 
> 
> If it is just add column thats rolled back, we don't have any issues as eof=0.
> 
> But the initial insert after add column (in InsertInitialAOCSFileSegInfo) which will update it with a eof>0 is also a frozen insert. This doesn't get rolled back.

That's surprising! Can we convert just that eof>0 into non-frozen for main branch? (I am yet to look at code, just blindly asking question)

**Comment by divyeshddv** [comment]
> That's surprising! Can we convert just that eof>0 into non-frozen for main branch? (I am yet to look at code, just blindly asking question)

InsertInitialAOCSFileSegInfo is used for first inserts for all cases (including new table)
Do you mean changing it only for a newly added column?

I think we can try adding a eof=0 frozen entry in add column operation itself. 
So that initial insert later can use a simple insert which can be reverted.
Think this should work. Thoughts?

**Comment by ashwinstar** [comment]
- on non-assert build - seems things are working fine and don't get any failure - so is the issue only related to that assert? Or its going to cause memory corruption for `memcpy(&aocs_seginfo->vpinfo, dv, VARSIZE(dv));`. If its later then really we should have ERROR check for this condition and not just assert
- If I am reading the code correctly `InsertInitialAOCSFileSegInfo()` is not passed EOF value at all. It calls `create_aocs_vpinfo()` which does `palloc0()` for creating the vpinfo which means EOF has to be 0 in frozen insert and can't be a valid EOF... and this can be also seen via below sql query added to repro `select * from gp_toolkit.__gp_aocsseg('t');`

```sql
postgres=# drop table t;
DROP TABLE
postgres=# create table t(a int, b int, c int) using ao_column;
CREATE TABLE
postgres=# insert into t select i,i,i from generate_series(1,10)i;
INSERT 0 10

postgres=# select * from gp_toolkit.__gp_aocsseg('t') where segment_id = 0;
 segment_id | segno | column_num | physical_segno | tupcount | eof | eof_uncompressed | modcount | formatversion | state 
------------+-------+------------+----------------+----------+-----+------------------+----------+---------------+-------
          0 |     1 |          0 |              1 |        5 |  64 |               64 |        1 |             3 |     1
          0 |     1 |          1 |            129 |        5 |  64 |               64 |        1 |             3 |     1
          0 |     1 |          2 |            257 |        5 |  64 |               64 |        1 |             3 |     1
(3 rows)

postgres=# begin;
BEGIN
postgres=# alter table t add column d int;
ALTER TABLE
postgres=# select * from gp_toolkit.__gp_aocsseg('t') where segment_id = 0;
 segment_id | segno | column_num | physical_segno | tupcount | eof | eof_uncompressed | modcount | formatversion | state 
------------+-------+------------+----------------+----------+-----+------------------+----------+---------------+-------
          0 |     1 |          0 |              1 |        5 |  64 |               64 |        2 |             3 |     1
          0 |     1 |          1 |            129 |        5 |  64 |               64 |        2 |             3 |     1
          0 |     1 |          2 |            257 |        5 |  64 |               64 |        2 |             3 |     1
          0 |     1 |          3 |            385 |        5 |  48 |               48 |        2 |             3 |     1
(4 rows)

postgres=# insert into t select i,i from generate_series(1,10)i;
INSERT 0 10
postgres=# select * from gp_toolkit.__gp_aocsseg('t') where segment_id = 0;
 segment_id | segno | column_num | physical_segno | tupcount | eof | eof_uncompressed | modcount | formatversion | state 
------------+-------+------------+----------------+----------+-----+------------------+----------+---------------+-------
          0 |     0 |          0 |              0 |        5 |  64 |               64 |        1 |             3 |     1
          0 |     0 |          1 |            128 |        5 |  64 |               64 |        1 |             3 |     1
          0 |     0 |          2 |            256 |        5 |  48 |               48 |        1 |             3 |     1
          0 |     0 |          3 |            384 |        5 |  48 |               48 |        1 |             3 |     1
          0 |     1 |          0 |              1 |        5 |  64 |               64 |        2 |             3 |     1
          0 |     1 |          1 |            129 |        5 |  64 |               64 |        2 |             3 |     1
          0 |     1 |          2 |            257 |        5 |  64 |               64 |        2 |             3 |     1
          0 |     1 |          3 |            385 |        5 |  48 |               48 |        2 |             3 |     1
(8 rows)

postgres=# abort;
ROLLBACK
postgres=# select * from gp_toolkit.__gp_aocsseg('t') where segment_id = 0;
 segment_id | segno | column_num | physical_segno | tupcount | eof | eof_uncompressed | modcount | formatversion | state 
------------+-------+------------+----------------+----------+-----+------------------+----------+---------------+-------
          0 |     0 |          0 |              0 |        0 |   0 |                0 |        0 |             3 |     1
          0 |     0 |          1 |            128 |        0 |   0 |                0 |        0 |             3 |     1
          0 |     0 |          2 |            256 |        0 |   0 |                0 |        0 |             3 |     1
          0 |     1 |          0 |              1 |        5 |  64 |               64 |        1 |             3 |     1
          0 |     1 |          1 |            129 |        5 |  64 |               64 |        1 |             3 |     1
          0 |     1 |          2 |            257 |        5 |  64 |               64 |        1 |             3 |     1
(6 rows)

postgres=# select * from t;
 a  | b  | c  
----+----+----
  5 |  5 |  5
  6 |  6 |  6
  9 |  9 |  9
 10 | 10 | 10
  1 |  1 |  1
  2 |  2 |  2
  3 |  3 |  3
  4 |  4 |  4
  7 |  7 |  7
  8 |  8 |  8
(10 rows)

postgres=# select * from gp_toolkit.__gp_aocsseg('t') where segment_id = 0;
 segment_id | segno | column_num | physical_segno | tupcount | eof | eof_uncompressed | modcount | formatversion | state 
------------+-------+------------+----------------+----------+-----+------------------+----------+---------------+-------
          0 |     0 |          0 |              0 |        0 |   0 |                0 |        0 |             3 |     1
          0 |     0 |          1 |            128 |        0 |   0 |                0 |        0 |             3 |     1
          0 |     0 |          2 |            256 |        0 |   0 |                0 |        0 |             3 |     1
          0 |     1 |          0 |              1 |        5 |  64 |               64 |        1 |             3 |     1
          0 |     1 |          1 |            129 |        5 |  64 |               64 |        1 |             3 |     1
          0 |     1 |          2 |            257 |        5 |  64 |               64 |        1 |             3 |     1
(6 rows)

```
after abort only rows with EOF=0 are visible for newly added segno=0 (EOF>0 like 64 and 48 are not visible after abort) means they were not frozen and can't be really.

**Comment by divyeshddv** [comment]
> > And change assert to error.
> > I thought the plan is to fix the code and as a result not treat this condition as error instead accept it if EOF=0. So, should only ERROR if EOF !=0.

Yes, the error condition would have to change. Will factor in the eof into new error condition

**Comment by divyeshddv** [comment]
Fixed in PR https://github.com/greenplum-db/gpdb/pull/14832
