### ISSUE TITLE
Getting Segmentation fault when enabling resource group

### ISSUE THREAD

**Issue by naveenreddy3** [greenplum-db/gpdb#14524]
### Greenplum version or build

PostgreSQL 9.4.26 (Greenplum Database 6.21.0 build commit:d0087e3b24c54d203ca8bb315559205f13cd6393) on x86_64-unknown-linux-gnu, compiled by gcc (GCC) 6.4.0, 64-bit compiled on Jun 10 2022 01:44:57

### OS version and uname -a
Centos 7

### Issue
I have a greenplum db with gpcc, it was working fine. Then i enabled the resource group after that am facing the segmentation error. When i checked the master logs i got to know that gpcc runs the query recursively and that query causing the issue. If i disable the resource group, same query am able to run (adding the query). 

### Query:

```
SELECT '2022-11-22 14:30:15' AS ctime
	, r.rsgname
	, f.groupid
	, f.num_running
	, f.num_queueing
	, ((json_each_text(f.cpu_usage))::text::gpmetrics.t_rsg_seginfo).segid
	, ((json_each_text(f.cpu_usage))::text::gpmetrics.t_rsg_seginfo).v as cpu_usage_percent
	, (json_populate_record(null::gpmetrics.t_rsg_mem,((json_each(f.memory_usage))::text::gpmetrics.t_rsg_seginfo).v::JSON)).*
	, c1.value AS concurrency_limit
	, c2.value AS cpu_rate_limit
FROM pg_resgroup_get_status(NULL::oid) f(groupid, num_running, num_queueing, num_queued, num_executed, total_queue_duration, cpu_usage, memory_usage)
INNER JOIN pg_resgroup r
	ON f.groupid = r.oid
INNER JOIN pg_resgroupcapability c6
	ON f.groupid = c6.resgroupid AND c6.reslimittype = 6 AND c6.value = '0'::text -- filter those memory_auditor != vmtracker
LEFT JOIN pg_resgroupcapability c1
	ON f.groupid = c1.resgroupid AND c1.reslimittype = 1
LEFT JOIN pg_resgroupcapability c2
	ON f.groupid = c2.resgroupid AND c2.reslimittype = 2;RESET optimizer;
```

### Error:

```
2022-11-22 13:12:00.057884 UTC,,,p18102,th0,,,2022-11-22 13:11:48 UTC,0,con4,cmd53,seg-1,,,,,"PANIC","XX000","Unexpected internal error: Master process received signal SIGSEGV",,,,,,,0,,,,"1    0x7f004584b630 libpthread.so.0 <symbol not found> + 0x4584b630
2    0xc97b9d postgres <symbol not found> (cdbconn.c:717)
3    0x935e7b postgres pqInternalNotice (fe-exec.c:895)
4    0x93a345 postgres PQgetvalue (fe-exec.c:3108)
5    0xc44f63 postgres pg_resgroup_get_status (resgroup_helper.c:141)
6    0x8cc41c postgres ExecMakeTableFunctionResult (execQual.c:2397)
7    0x8efebe postgres <symbol not found> (nodeFunctionscan.c:141)
8    0x8d0fb9 postgres ExecScan (execScan.c:84)
9    0x8c30b8 postgres ExecProcNode (execProcnode.c:1043)
10   0x8e5338 postgres ExecHashJoin (tuptable.h:159)
11   0x8c3038 postgres ExecProcNode (execProcnode.c:1078)
12   0x8e5338 postgres ExecHashJoin (tuptable.h:159)
13   0x8c3038 postgres ExecProcNode (execProcnode.c:1078)
14   0x8e5338 postgres ExecHashJoin (tuptable.h:159)
15   0x8c3038 postgres ExecProcNode (execProcnode.c:1078)
16   0x8e5338 postgres ExecHashJoin (tuptable.h:159)
17   0x8c3038 postgres ExecProcNode (execProcnode.c:1078)
18   0x8f0d65 postgres ExecResult (tuptable.h:159)
19   0x8c2eb8 postgres ExecProcNode (execProcnode.c:970)
20   0x8ba0e9 postgres <symbol not found> (tuptable.h:159)
21   0x8bae0e postgres standard_ExecutorRun (execMain.c:3097)
22   0xa96337 postgres <symbol not found> (pquery.c:1159)
23   0xa98361 postgres PortalRun (pquery.c:1006)
24   0xa92a90 postgres <symbol not found> (postgres.c:1856)
25   0xa95140 postgres PostgresMain (postgres.c:5321)

2022-11-22 13:11:45.050699 UTC,,,p17700,th1210398848,,,,0,,,seg-1,,,,,"LOG","00000","server process (PID 17791) was terminated by signal 11: Segmentation fault","Failed process was running: SET optimizer = off;
2022-11-22 13:11:45.050743 UTC,,,p17700,th1210398848,,,,0,,,seg-1,,,,,"LOG","00000","terminating any other active server processes",,,,,,,0,,"postmaster.c",3729,
2022-11-22 13:11:45.050748 UTC,,,p17719,th1210398848,,,,0,,,seg-1,,,,,"WARNING","01000","ic-proxy-server: received signal 3",,,,,,,0,,"ic_proxy_main.c",379,
2022-11-22 13:11:45.050753 UTC,,,p17700,th1210398848,,,,0,,,seg-1,,,,,"LOG","00000","worker process: ic proxy process (PID 17719) exited with exit code 1",,,,,,,0,,"postmaster.c",3990,
2022-11-22 13:11:45.050759 UTC,"gpmon","gpperfmon",p18081,th1210398848,"88.99.208.94","47726",2022-11-22 13:11:45 UTC,0,,,seg-1,,,,,"FATAL","57P03","the database system is resetting",,,,,,,0,,"postmaster.c",2584,
2022-11-22 13:11:45.050774 UTC,,,p17700,th1210398848,,,,0,,,seg-1,,,,,"LOG","00000","all server processes terminated; reinitializing",,,,,,,0,,"postmaster.c",4264,
2022-11-22 13:11:45.120174 UTC,,,p18083,th1210398848,,,,0,,,seg-1,,,,,"LOG","00000","database system was interrupted; last known up at 2022-11-22 13:11:26 UTC",,,,,,,0,,"xlog.c",6446,
2022-11-22 13:11:45.120269 UTC,"gpmon","postgres",p18084,th1210398848,"88.99.208.94","47730",2022-11-22 13:11:45 UTC,0,,,seg-1,,,,,"FATAL","57P03","the database system is in recovery mode","last replayed record at 0/0",,,,,,0,,"postmaster.c",2579

```

### postgress config

listen_addresses='*'
log_statement=all
checkpoint_segments=8
gp_contentid=-1
TimeZone='UTC'
max_statement_mem=48GB
statement_mem=1GB
gp_resource_manager='group'
gp_workfile_limit_files_per_query=150000
log_timezone = 'UTC'
gp_vmem_protect_limit = 28192

**Comment by kainwen** [comment]
Can you please share us with the core file?

You can use `packcore` tool (shipped with Greenplum) to make a coredump package.

**Comment by naveenreddy3** [comment]
Hi Kainwen,

Thanks for the response, please refer to the link for coredump.

https://gofile.io/d/gZW2EC

**Comment by kainwen** [comment]
> pg_resgroup_get_status(NULL::oid) f(groupid, num_running, num_queueing, num_queued, num_executed, total_queue_duration, cpu_usage, memory_usage)

Thanks. Will look into this later.

**Comment by naveenreddy3** [comment]
Hi @kainwen ,

Did you get the chance to work on it?

**Comment by kainwen** [comment]
> Hi @kainwen ,
> 
> Did you get the chance to work on it?

Not yet. Busy with other work.

**Comment by kainwen** [comment]
> Hi @kainwen ,
> 
> Did you get the chance to work on it?

The core file helps. Thanks @naveenreddy3 

Spend some time on this this night, it might be due to a bug of the function `MPPnoticeReceiver`. Need more time to RCA and then fix.

**Comment by echoabhishek** [comment]
Even I am facing the same issue.

We recently migrated data from old Greeplum v6.13 cluster to new Greenplum v6.21 cluster.
The migration was successful and was carried out by gpcopy.
But suddenly, after enabling resource groups it's throwing the same error as soon as I start GPCC (v6.4.0).
Without resource group everything works fine.

For time being we have disabled resource groups.
It would be great if there was a resolution for this.

**Comment by echoabhishek** [comment]
Hi @kainwen 
Let me pull out the core file in a while.
The error log is very similar to what @naveenreddy3 is seeing.

However, there is one peculiar thing I realized which is different between my two clusters. The Segment Value for 'gp_resource_manager' is coming different in the new cluster, the one which is giving issues.

```
# gpconfig -s gp_resource_manager
Values on all segments are consistent
GUC          : gp_resource_manager
Master  value: group
Segment value: queue
```

Any idea if this could be causing the issue?

**Comment by naveenreddy3** [comment]
Hi @kainwen,

I checked the value against 'gp_resource_manager' and figured out that I hardcoded resource group in postgres.conf but it didn't affect the segments.

```
# gpconfig -s gp_resource_manager
Values on all segments are consistent
GUC          : gp_resource_manager
Master  value: group
Segment value: queue
```

Post that I ran the command `gpconfig -c gp_resource_manager -v "group"`, after running that command it started working fine.

**Comment by ashwinstar** [comment]
Thanks for that finding. Re-opened the issue just for team to see if any possibility exist to validate the GUC to make sure is consistent across cluster and can avoid crash is this situation.

**Comment by SmartKeyerror** [comment]
> Thanks for that finding. Re-opened the issue just for team to see if any possibility exist to validate the GUC to make sure is consistent across cluster and can avoid crash is this situation.

If we use the command of `gpconfig -c gp_resource_manager -v group`, the `gp_resource_manager` must be consistent across the cluster, or this will fail if we don't configure Linux Cgroup well.

**Comment by kainwen** [comment]
> > Thanks for that finding. Re-opened the issue just for team to see if any possibility exist to validate the GUC to make sure is consistent across cluster and can avoid crash is this situation.
> 
> If we use the command of `gpconfig -c gp_resource_manager -v group`, the `gp_resource_manager` must be consistent across the cluster, or this will fail if we don't configure Linux Cgroup well.

They might use `alter system` (the dispatch behavior is not the same 6x and main).

This issue lead me to look into the code of `MPPnoticeReceiver` (the panic place). I see some type of notice will not set the 
 variable `line`, this is the place we need to take deep look from my side.

**Comment by kainwen** [comment]
Close this, I believe it is the same as https://github.com/greenplum-db/gpdb/issues/15194.
Will also check here once that issue is fixed.
