### ISSUE TITLE
Missing python libraries in installation of 6.22.2

### ISSUE THREAD

**Issue by akotuc** [greenplum-db/gpdb#14530]
## Bug Report
After installation of 6.22.2 version `psutil` and `yaml` python libraries are missing in `/usr/local/greenplum-db-6.22.2/lib/python/`

### Greenplum version or build
6.22.2

### OS version and uname -a
Linux 3.10.0-1160.71.1.el7.x86_64 #1 SMP Tue Jun 28 15:37:28 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Expected behavior
`psutil` and `yaml` exists in `/usr/local/greenplum-db-6.22.2/lib/python/` and `gpssh` / `gpscp` are working.

### Actual behavior
`psutil` and `yaml` libs are missing in `/usr/local/greenplum-db-6.22.2/lib/python/` and `gpssh` / `gpscp` are complaining about missing import `psutil`.

### Step to reproduce the behavior
Install 6.22.2 from release https://github.com/greenplum-db/gpdb/releases/download/6.22.2/open-source-greenplum-db-6.22.2-rhel7-x86_64.rpm

**Comment by bradfordboyle** [comment]
Greenplum recently introduce a new configure flag called `--with-pythonsrc-ext` (see 0798c63e66) that defaults to `no`. Without this flag, the vendored dependencies in `gpMgmt/bin/pythonSrc/ext` (which includes `psutil` and `PyYAML`) don't get build. Looking at the output of `/usr/local/greenplum-db-6.22.2/bin/pg_config --configure` it looks like this flag is missing from the open source build of GPDB 6.22.2.

**Comment by 50wu** [comment]
Thanks all for the information. The team is looking at it, the issue will be fixed by the next release.
