### ISSUE TITLE
unrecognized configuration parameter "ssl_renegotiation_limit"

### ISSUE THREAD

**Issue by cobolbaby** [greenplum-db/gpdb#14550]
### Greenplum version or build

- 6.20.5

### Actual behavior

When the .Net client connects to Greenplum, the database will report the error.

### Step to reproduce the behavior

- .Net Program Connection String

```
connectionString="Server=xxxx;Port=xxxx;UserId=xxxx;Password=xxxx;Database=xxxx;"
```

- gpdb-2022-11-29_000000.csv

```
2022-11-29 00:07:44.788016 CST,"bdctester","F3_BDC",p2422243,th-2102937472,"192.168.0.21","61491",2022-11-29 00:07:44 CST,0,con10437867,cmd1,seg-1,,,,sx1,"ERROR","42704","unrecognized configuration parameter ""ssl_renegotiation_limit""",,,,,,"SET ssl_renegotiation_limit=0",0,,"guc.c",5907,
2022-11-29 00:07:44.788064 CST,"bdctester","F3_BDC",p2422243,th-2102937472,"192.168.0.21","61491",2022-11-29 00:07:44 CST,0,con10437867,cmd1,seg-1,,,,sx1,"LOG","00000","An exception was encountered during the execution of statement: SET ssl_renegotiation_limit=0",,,,,,"SET ssl_renegotiation_limit=0",0,,"elog.c",2116,
```

**Comment by SmartKeyerror** [comment]
Could you please provide more details? Thanks. Since we can not reproduce this problem with what you have provided.

The error happened when you connect Greenplum? Or something else?

**Comment by cobolbaby** [comment]
> The error happened when you connect Greenplum

Yes. When the client connects to Greenplum, the database will throw this exception. However, even if it's an error, it does not affect the subsequent operations of the client.

**Comment by SmartKeyerror** [comment]
When I search the code, the GUC of `ssl_renegotiation_limit` is no longer supported, and we deleted it from the configuration file in Greenplum 6. But there has some legacy in docs, will remove it.

If your connection tool adds this parameter automatically, just ignore this ERROR. Or remove this config from the connect string.

**Comment by cobolbaby** [comment]
> the GUC of ssl_renegotiation_limit is no longer supported

But I found that `ssl_renegotiation_limit` is still in the master branch.Does GP7 support the option again?

**Comment by SmartKeyerror** [comment]
> But I found that `ssl_renegotiation_limit` is still in the master branch.Does GP7 support the option again?

Nope, it's not supported.

```
	{
		{"ssl_renegotiation_limit", PGC_USERSET, CONN_AUTH_SSL,
			gettext_noop("SSL renegotiation is no longer supported; this can only be 0."),
			NULL,
			GUC_NO_SHOW_ALL | GUC_NOT_IN_SAMPLE | GUC_DISALLOW_IN_FILE,
		},
		&ssl_renegotiation_limit,
		0, 0, 0,
		NULL, NULL, NULL
	},
```

**Comment by ashwinstar** [comment]
This is PG 9.5 release note mention regarding same
---
Decommission server configuration parameter ssl_renegotiation_limit, which was deprecated in earlier releases (Andres Freund)

While SSL renegotiation is a good idea in theory, it has caused enough bugs to be considered a net negative in practice, and it is due to be removed from future versions of the relevant standards. We have therefore removed support for it from PostgreSQL. The ssl_renegotiation_limit parameter still exists, but cannot be set to anything but zero (disabled). It's not documented anymore, either.
---

**Comment by Stolb27** [comment]
Hi there!
This GUC is still present in the gpdb documentation. Moreover, it was brought back to gpdb main branch to save "backward compatibility" (during sync PG9.5?). What about kicking out it before gpdb 7 release? Can you suggest the best way to suggest corrections to the gpdb documentation (open a new issue or pull request, feedback form on doc site)?

**Comment by lisakowen** [comment]
hi @Stolb27 , thanks for the input.  re: the greenplum docs, feel free to submit an issue for requested updates.  we also welcome PRs for doc changes if you are so inclined.
