### ISSUE TITLE
EXPLAIN ANALYZE on foreign scan will fail insist/assert if # of segments are different

### ISSUE THREAD

**Issue by lmzzzzz1** [greenplum-db/gpdb#14573]
## Bug Report
EXPLAIN ANALYZE on foreign scan will fail insist/assert, when the foreign server has the mpp_execute 'all segments' options and the remote GPDB server's size is larger than local GPDB.

### Greenplum version or build
6X_STABLE
master
6.22.2

### Expected behavior
postgres=# explain analyze  select * from public.t;
                                                            QUERY PLAN
----------------------------------------------------------------------------------------------------------------------------------
 Gather Motion 4:1  (slice1; segments: 4)  (cost=100.00..7088.00 rows=344400 width=8) (actual time=7.774..9.431 rows=200 loops=1)
   ->  Foreign Scan on t  (cost=100.00..2783.00 rows=86100 width=8) (actual time=0.865..0.873 rows=60 loops=1)
         Relations:
 Optimizer: Postgres query optimizer
 Planning Time: 0.520 ms
   (slice0)    Executor memory: 37K bytes.
   (slice1)    Executor memory: 38K bytes avg x 4 workers, 43K bytes max (seg4).
 Memory used:  128000kB
 Execution Time: 178.696 ms
(9 rows)

### Actual behavior
postgres=# explain analyze  select * from public.t;
ERROR:  Unexpected internal error (explain_gp.c:915)

### Step to reproduce the behavior
remote GPDB: 4 segments
local GPDB: 3segment

sql in remote GPDB(4 segs): 

```
create extension gp_parallel_retrieve_cursor;
create table t1(a int, b int, c int);
insert into t1 values(1,1,1),(2,2,2),(3,3,3);
```

sql in remote GPDB(3 segs):
```
create extension greenplum_fdw;
CREATE SERVER f_server FOREIGN DATA WRAPPER greenplum_fdw
            OPTIONS (dbname 'postgres', port '5432', host '192.168.1.123',mpp_execute 'all segments',num_segments '4');

CREATE USER MAPPING FOR CURRENT_USER SERVER f_server;  

CREATE FOREIGN TABLE t (
    a int,
    b int
    c int
) SERVER  f_server OPTIONS (schema_name 'public', table_name 't1');

select * from t;
explain select * from t;
explain analyze select * from t;
```

**Comment by SmartKeyerror** [comment]
Already fixed by #14574, close this issue.
