### ISSUE TITLE
transformWindowClause function in the parese_clause.c 

### ISSUE THREAD

**Issue by yifeiyangecnu** [greenplum-db/gpdb#1458]
in src/backend/parser/parese_clause.c
	in the function transformWindowClause
line :517   **foreach(tmp,winout)**
  winout is initialize with NIL,and no other assigned,
so it's always false for the for statement,but it's not the purpose

**Comment by jianlirong** [comment]
Please check the line 739 of the file: winout = lappend(winout, newspec);

**Comment by yifeiyangecnu** [comment]
thank you
