### ISSUE TITLE
Incremental recovery add pg_controldata output of target directory

### ISSUE THREAD

**Issue by l-wang** [greenplum-db/gpdb#14627]
## Enhancement

Currently, when doing an incremental recovery in verbose mode with "gprecoverseg -v", we record the pg_controldata output of the source data directory before running pg_rewind. 

Can we would also record the pg_controldata output of the target data directory before running pg_rewind? 

Context: Recently I've been investigating pg_rewind failures due to missing wal files. Often times at the time of performing incremental recovery(pg_rewind), the target segments have been shutdown for quite sometime, and if the incremental recovery failed, users usually choose to perform a full recovery as a workaround to bring the target segments up. This sequence of operations would erase the clue of what had happened on the target segment before it went down in the first place. Recording the pg_controldata output of the target data directory before running pg_rewind would tell us when and what was the latest checkpoint on the target segment before it went down, and that would be very helpful for future investigations.

@divyeshddv and I took the first stab and wrote below patch that does what we wanted. However, we weren't sure if this is the best place to make this change, we also weren't sure how to properly add test cases for it. Can we get some help making this into production?

```diff
From b646cf2f11089b65fcd72bca56f978046a822403 Mon Sep 17 00:00:00 2001
From: Alexandra Wang <walexandra@vmware.com>
Date: Fri, 9 Dec 2022 12:04:28 -0800
Subject: [PATCH] Incremental recovery add pg_controldata output of target
 directory

When doing an incremental recovery in verbose mode with "gprecoverseg
-v", we record the pg_controldata output of the source data directory
before running pg_rewind. Ideally we would also like to record the
pg_controldata output of the target data directory before running
pg_rewind. If the following pg_rewind command failed, the
pg_controldata output of the target data directory would be very
helpful for investigating the root cause, as the pg_controldata output
would tell us when and what was the last checkpoint on the target
segment before it went down.

Co-authored-by: Divyesh Vanjare <vanjared@vmware.com>
---
 gpMgmt/sbin/gpsegrecovery.py | 9 ++++++++-
 1 file changed, 8 insertions(+), 1 deletion(-)

diff --git a/gpMgmt/sbin/gpsegrecovery.py b/gpMgmt/sbin/gpsegrecovery.py
index 563b7726709..8f4d3629d92 100644
--- a/gpMgmt/sbin/gpsegrecovery.py
+++ b/gpMgmt/sbin/gpsegrecovery.py
@@ -1,7 +1,7 @@
 #!/usr/bin/env python3
 
 from gppylib.recoveryinfo import RecoveryErrorType
-from gppylib.commands.pg import PgBaseBackup, PgRewind
+from gppylib.commands.pg import PgBaseBackup, PgRewind, PgControlData
 from recovery_base import RecoveryBase, set_recovery_cmd_results
 from gppylib.commands.base import Command
 from gppylib.commands.gp import SegmentStart
@@ -61,6 +61,13 @@ class IncrementalRecovery(Command):
 
     @set_recovery_cmd_results
     def run(self):
+        self.error_type = RecoveryErrorType.DEFAULT_ERROR
+        self.logger.info("Running pg_controldata")
+        ctlcmd = PgControlData(name='run pg_controldata', datadir=self.recovery_info.target_datadir)
+        ctlcmd.run(validateAfter=True)
+        res = ctlcmd.get_results()
+        self.logger.info("Finished pg_controldata {} for dbid {}:\nstdout: {}\nstderr: {}".format(self.recovery_info.target_datadir, self.recovery_info.target_segment_dbid, res.stdout, res.stderr))
+
         self.logger.info("Running pg_rewind with progress output temporarily in %s" % self.recovery_info.progress_file)
         self.error_type = RecoveryErrorType.REWIND_ERROR
         cmd = PgRewind('rewind dbid: {}'.format(self.recovery_info.target_segment_dbid),
-- 
2.34.1
```

@greenplum-db/cluster-management

**Comment by Annu149** [comment]
PR https://github.com/greenplum-db/gpdb/pull/14648 has been raised for this enhancement
