### ISSUE TITLE
PARALLEL RETRIEVE CURSOR on select transient record types crash

### ISSUE THREAD

**Issue by lmzzzzz1** [greenplum-db/gpdb#14645]
## Bug Report
Hello，I am researching FDW based on PARALLEL RETRIEVE CURSOR, and found that when the return type is record and retrieve more than once, it will cause the postgres backend process to crash.

### Greenplum version or build
7.0
6X_STABLE

### OS version and uname -a
centos7

### autoconf options used ( config.status --config )
./configure --enable-orca --disable-gpfdist --with-perl --with-python  --enable-debug --with-libxml  CFLAGS='-gdwarf-2 -g3 -O0'

### Step to reproduce the behavior

terminal1:
```
BEGIN;
DECLARE c1 PARALLEL RETRIEVE CURSOR FOR 
    SELECT (1,2,3) 
    UNION 
    SELECT (2,3,4);
SELECT endpointname,auth_token,hostname,port,state FROM gp_get_endpoints() WHERE cursorname='c1';
```

terminal2:
```
# in shell
PGOPTIONS='-c gp_retrieve_conn=true' psql -h localhost  -p 51797 -d postgres

# in psql
RETRIEVE 1 FROM ENDPOINT c10000000c0000000d;
RETRIEVE 1 FROM ENDPOINT c10000000c0000000d;
```

### Expected behavior
```
RETRIEVE 1 FROM ENDPOINT c10000000c0000000d;
   row
---------
 (1,2,3)
(1 row)

RETRIEVE 1 FROM ENDPOINT c10000000c0000000d;
   row
---------
 (2,3,4)
(1 row)

```

### Actual behavior
postgres crash

**Comment by adam8157** [comment]
Fixed by https://github.com/greenplum-db/gpdb/pull/14646, will submit a PR for 6X if this issue exists too.
