### ISSUE TITLE
Cannot create temporary table like existing table with comments

### ISSUE THREAD

**Issue by Smyatkin-Maxim** [greenplum-db/gpdb#14649]
## Bug Report
```(sql)
CREATE TABLE tbl (i integer);
COMMENT ON COLUMN tbl.i IS 'Airflow';
CREATE TEMPORARY TABLE tbl2 (LIKE tbl INCLUDING ALL);
```
Only happens when creating a temporary table including comments or including all.

### Expected behavior
Table is created

### Actual behavior
ERROR:  schema "" does not exist  (seg0 127.0.1.1:6002 pid=163838)

### Greenplum version or build
6X_STABLE

### OS version and uname -a
Linux 5.15.0-56-generic #62~20.04.1-Ubuntu SMP Tue Nov 22 21:24:20 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### autoconf options used ( config.status --config )
'--enable-debug-extensions' '--enable-debug' '--enable-cassert' '--enable-gpperfmon' '--with-python' '--with-libxml' '--enable-depend' 'CFLAGS=-fno-omit-frame-pointer -Wno-implicit-fallthrough -O0 -g -pthread'

### Installation information ( pg_config )
Default

**Comment by SmartKeyerror** [comment]
The main branch also has this problem:

```
postgres=# CREATE TABLE tbl (i integer);
NOTICE:  Table doesn't have 'DISTRIBUTED BY' clause -- Using column named 'i' as the Greenplum Database data distribution key for this table.
HINT:  The 'DISTRIBUTED BY' clause determines the distribution of data. Make sure column(s) chosen are the optimal data distribution key to minimize skew.
CREATE TABLE
postgres=# COMMENT ON COLUMN tbl.i IS 'Airflow';
COMMENT
postgres=# CREATE TEMPORARY TABLE tbl2 (LIKE tbl INCLUDING ALL);
NOTICE:  table doesn't have 'DISTRIBUTED BY' clause, defaulting to distribution columns from LIKE table
ERROR:  schema "" does not exist  (seg2 127.0.0.1:7004 pid=319176)
```

**Comment by SmartKeyerror** [comment]
### RCA

When QD generates query tree and serializes it to string and sends it to QE, and QE will deserialize it to a plan tree. In this process, Greenplum seems not to consider the difference between NULL and an empty string, so if the original value is a NULL, QE may deserialize it to an empty string, which could lead error happened:

```
Oid
RangeVarGetRelidExtended(const RangeVar *relation, LOCKMODE lockmode,
						 uint32 flags,
						 RangeVarGetRelidCallback callback, void *callback_arg)
{
     /* other codes */
    else if (relation->schemaname)
    {
	    Oid			namespaceId;
    
	    /* use exact schema given */
	    namespaceId = LookupExplicitNamespace(relation->schemaname, missing_ok);
	    if (missing_ok && !OidIsValid(namespaceId))
		    relId = InvalidOid;
	    else
		    relId = get_relname_relid(relation->relname, namespaceId);
    }
}
```

As we can see, we just verify the `relation->schemaname` is NULL or not NULL, but we do not verify it is an empty string, and an empty string is an illegal schema name, so it's impossible to find the namespace OID via `LookupExplicitNamespace`, and error message "schema "" does not exist" would be thrown eventually.

**Comment by SmartKeyerror** [comment]
If we add the following simple patch, this issue will be solved:

```
diff --git a/src/backend/catalog/namespace.c b/src/backend/catalog/namespace.c
index 361090a76b3..2f439b5d9dd 100644
--- a/src/backend/catalog/namespace.c
+++ b/src/backend/catalog/namespace.c
@@ -3086,6 +3086,8 @@ makeRangeVarFromNameList(List *names)
                        break;
                case 2:
                        rel->schemaname = strVal(linitial(names));
+                       if (rel->schemaname && strlen(rel->schemaname) == 0)
+                               rel->schemaname = NULL;
                        rel->relname = strVal(lsecond(names));
                        break;
                case 3:
```

**Comment by ashwinstar** [comment]
Cusious to learn why having "comment" on column plays role is manifesting this error or error happens even without comment?

**Comment by Smyatkin-Maxim** [comment]
> Cusious to learn why having "comment" on column plays role is manifesting this error or error happens even without comment?

As far as I can tell it only appears with column comment and temporary tables. I've tried a bunch of more complicated examples including storage options, constraints, indexes - only comments seem to fail.

I've had a different patch in mind:
```
diff --git a/src/backend/parser/parse_utilcmd.c b/src/backend/parser/parse_utilcmd.c
index b85a0c0aa4..df809551be 100644
--- a/src/backend/parser/parse_utilcmd.c
+++ b/src/backend/parser/parse_utilcmd.c
@@ -1215,11 +1215,22 @@ transformTableLikeClause(CreateStmtContext *cxt, TableLikeClause *table_like_cla
                        CommentStmt *stmt = makeNode(CommentStmt);
 
                        stmt->objtype = OBJECT_COLUMN;
-                       stmt->object = (Node *) list_make3(makeString(cxt->relation->schemaname),
-                                                                                          makeString(cxt->relation->relname),
-                                                                                          makeString(def->colname));
-                       stmt->comment = comment;
 
+                       /* Schema might be missing when creating from temporary table */
+                       if (cxt->relation->schemaname)
+                       {
+                               stmt->object = (Node *) list_make3(makeString(cxt->relation->schemaname),
+                                                                                                  makeString(cxt->relation->relname),
+                                                                                                  makeString(def->colname));
+                       }
+                       else
+                       {
+                               Assert(cxt->relation->relpersistence != RELPERSISTENCE_TEMP);
+                               stmt->object = (Node *) list_make2(makeString(cxt->relation->relname),
+                                                                                                  makeString(def->colname));
+                       }
+
+                       stmt->comment = comment;
```
but @SmartKeyerror  patch looks more generic IMO, hence it`s better

**Comment by ashwinstar** [comment]
@SmartKeyerror please open PR with proposed code change to fix the issue. Thanks.

**Comment by SmartKeyerror** [comment]
> @SmartKeyerror please open PR with proposed code change to fix the issue. Thanks.

Sure, I'll fix it this week.

It might be offensive to ask this question, but I'm very curious that you don't need to sleep?

**Comment by Smyatkin-Maxim** [comment]
@SmartKeyerror I already had unit tests for this one, perhaps it will save you some typing [tests.txt](https://github.com/greenplum-db/gpdb/files/10372876/tests.txt)

**Comment by SmartKeyerror** [comment]
> @SmartKeyerror I already had unit tests for this one. Sharing it to save you some typing [tests.txt](https://github.com/greenplum-db/gpdb/files/10372876/tests.txt)

That's really helpful, you're so thoughtful, thanks a lot!

**Comment by kainwen** [comment]
Fixed by
* main branch: https://github.com/greenplum-db/gpdb/pull/14742  
* 6X: https://github.com/greenplum-db/gpdb/pull/14857

**Comment by huuhuuhuu** [comment]
I found that this fix will influence behavior while i query pg_class using '::regclass'.
For example:
before:
`postgres=# select * from pg_class where oid='"".t_comments_a'::regclass
postgres-# ;
ERROR:  schema "" does not exist
LINE 1: select * from pg_class where oid='"".t_comments_a'::regclass`

after this fix was introduced
`postgres=# select * from pg_class where oid='"".t_comments_a'::regclass
postgres-# ;
   relname    | relnamespace | reltype | reloftype | relowner | relam | relfilenode | reltablespace | relpages | reltu
ples | relallvisible | reltoastrelid | relhasindex | relisshared | relpersistence | relkind | relstorage | relnatts | 
relchecks | relhasoids | relhaspkey | relhasrules | relhastriggers | relhassubclass | relispopulated | relreplident | 
relfrozenxid | relminmxid | relacl | reloptions 
--------------+--------------+---------+-----------+----------+-------+-------------+---------------+----------+------
-----+---------------+---------------+-------------+-------------+----------------+---------+------------+----------+-
----------+------------+------------+-------------+----------------+----------------+----------------+--------------+-
-------------+------------+--------+------------
 t_comments_a |         2200 |   16386 |         0 |       10 |     0 |       16384 |             0 |        0 |      
   0 |             0 |             0 | f           | f           | p              | r       | h          |        1 | 
        0 | f          | f          | f           | f              | f              | t              | d            | 
         725 |          1 |        | 
(1 row)
`

So,  is this what we expect？
