### ISSUE TITLE
Catalog inconsistency in `relhassubclass` after analyze

### ISSUE THREAD

**Issue by chrishajas** [greenplum-db/gpdb#14644]
### Greenplum version or build
GP6 and main branch

After analyzing a table with a dropped subclass, the value on the coordinator may differ from the segments.

`relhassubclass` is True if table or index has (or once had) any inheritance children or partitions. After analyzing, this value should be the current state. However, in GPDB analyze is not updating the coordinator's value, only the segments.

Repro:
```
CREATE TYPE test_type2 AS (a int, b text);
CREATE TABLE test_tbl2 OF test_type2;
CREATE TABLE test_tbl2_subclass () INHERITS (test_tbl2);

DROP TABLE test_tbl2_subclass;
analyze; -- before analyze, relhassubclass is true, after analyze, relhassubclass is false on the segments, but true on the coordinator still.
select gp_segment_id, relhassubclass from pg_class where relname = 'test_tbl2';
select gp_segment_id, relhassubclass from gp_dist_random('pg_class') where relname = 'test_tbl2';
```

**Comment by kainwen** [comment]
Fixed by:

* main branch: https://github.com/greenplum-db/gpdb/pull/14978
* 6x: https://github.com/greenplum-db/gpdb/pull/15018
