### ISSUE TITLE
Private reporting of security vulnerability

### ISSUE THREAD

**Issue by Sim4n6** [greenplum-db/gpdb#14659]
Hi GPDB team,

I may have identified a security vulnerability in the latest code source. Could you please enable the "[Private reporting of security vulnerability](https://docs.github.com/en/code-security/security-advisories/guidance-on-reporting-and-writing/privately-reporting-a-security-vulnerability)" feature in GitHub, so I could proceed privately?

Many thanks for considering my request.

**Comment by Sim4n6** [comment]
![image](https://user-images.githubusercontent.com/13036531/207927375-d4bdfee0-e392-430a-8992-f63bae9c2c46.png)

**Comment by ashwinstar** [comment]
Done. Also, as alternative like stated in [security policy](https://github.com/greenplum-db/gpdb/security/policy) can also email to security@greenplum.org
