### ISSUE TITLE
Wrong Result of multi-dqa hashagg in planner

### ISSUE THREAD

**Issue by charliettxx** [greenplum-db/gpdb#14688]
## Bug Report
Wrong Result of multi-dqa hashagg in planner
### Greenplum version or build
only main
### OS version and uname -a
centos7
### autoconf options used ( config.status --config )
optimizer = off
### Installation information ( pg_config )
optimizer = off
### Expected behavior
create table t1(a int, b int, c int);
insert into t1 values(1, 1, 1);                                                                                         
insert into t1 values(2, 2, 2);                                                                                         
insert into t1 values(3, 3, 3);
insert into t1 values(null, null, null);

postgres=# set enable_hashagg = off;                                                                                     
SET
postgres=# select count(distinct a), count(distinct b) from t1 group by c;                                               
 count | count 
-------+-------
     1 |     1
     1 |     1
     1 |     1
     0 |     0
(4 rows)
### Actual behavior
create table t1(a int, b int, c int);
insert into t1 values(1, 1, 1);                                                                                         
insert into t1 values(2, 2, 2);                                                                                         
insert into t1 values(3, 3, 3);
insert into t1 values(null, null, null);

postgres=# set enable_hashagg = on;                                                                                      
SET
postgres=# select count(distinct a), count(distinct b) from t1 group by c;                                               
 count | count 
-------+-------
     0 |     0
     1 |     1
     1 |     1
     0 |     0
     1 |     1
(5 rows)

**Comment by kainwen** [comment]
Fixed by https://github.com/greenplum-db/gpdb/pull/14927
