### ISSUE TITLE
Hang of multi-dqa in planner

### ISSUE THREAD

**Issue by charliettxx** [greenplum-db/gpdb#14728]
## Bug Report
Hang of multi-dqa in planner
### Greenplum version or build
 only in 7 main branch
### OS version and uname -a
centos7
### Expected behavior
no hang
### Actual behavior
hang
### Step to reproduce the behavior

create table t1(a int, b int, c int);
insert into t1 values(1, 1, 1);
insert into t1 values(2, 2, 2);
insert into t1 values(3, 3, 3);

select count(distinct a) filter(where a > 1), count(distinct b) from t1;

then hang..

**Comment by CharlieTTXX** [comment]
updated:
there is another bug for this case;

```
set enable_hashagg = off;
set enable_groupagg = on;

postgres=# explain select count(distinct a) filter(where a > 1), count(distinct b) from t1;
                                       QUERY PLAN                                        
-----------------------------------------------------------------------------------------
 Aggregate  (cost=1916.58..1916.59 rows=1 width=16)
   ->  Gather Motion 3:1  (slice1; segments: 3)  (cost=0.00..1332.33 rows=77900 width=8)
         ->  Seq Scan on t1  (cost=0.00..293.67 rows=25967 width=8)
 Optimizer: Postgres query optimizer
(4 rows)

postgres=# select count(distinct a) filter(where a > 1), count(distinct b) from t1;
 count | count 
-------+-------
     3 |     3
(1 row)
```

Results is wrong and also inconsistant with upstream. Expected behavior:
```
postgres=# explain select count(distinct a) filter(where a > 1), count(distinct b) from t1;
                         QUERY PLAN                         
------------------------------------------------------------
 Aggregate  (cost=45.70..45.71 rows=1 width=16)
   ->  Seq Scan on t1  (cost=0.00..30.40 rows=2040 width=8)
(2 rows)

postgres=# select count(distinct a) filter(where a > 1), count(distinct b) from t1;
 count | count 
-------+-------
     2 |     3
(1 row)
```
Seems something corrupted in ExecAggnode.

**Comment by CharlieTTXX** [comment]
> select count(distinct a) filter(where a > 1), count(distinct b) from t1;

I'll report another issue for this follow-up bug, seems not related to current issue.

**Comment by adam8157** [comment]
![image](https://user-images.githubusercontent.com/153160/218386531-9e78d5d7-d04d-4190-bfe6-3806c4dd3e13.png)

**Comment by kainwen** [comment]
Fixd by https://github.com/greenplum-db/gpdb/pull/14950
