### ISSUE TITLE
 gpssh-exkeys Password-free access fails and no error is reported due to  replace scp with rsync 

### ISSUE THREAD

**Issue by anjingde** [greenplum-db/gpdb#14744]
## Bug Report

 #  step 5
    #
    #    Set or update the authentication files on each remote host.
    #    For each new host, copy (and replace) the authorized_keys,
    #    known_hosts, and id_rsa{.,pub} files.  For existing hosts,
    #    merge the common authorized_keys and known_hosts content
    #    into the local copy of the remote host's files and replace
    #    the existing host's versions.
    #
    print();
    print('[STEP 5 of 5] copy authentication files to all remote hosts')
    errmsg = None

    try:

        # MPP-13617
        def canonicalize(s):
            if ':' not in s: return s
            return '\[' + s + '\]'

        for h in GV.newHosts:
            cmd = ('rsync -q -e "ssh -o BatchMode=yes -o NumberOfPasswordPrompts=0" ' +
                   '%s %s %s %s %s:.ssh/ 2>&1'
                   % (GV.authorized_keys_fname,
                      GV.known_hosts_fname,
                      GV.id_rsa_fname,
                      GV.id_rsa_pub_fname,
                      canonicalize(h.host())))
            h.popen(cmd)

when id_rsa and id_rsa.pub have generated(the size and the time are same but the content  is different from the  coordinator),  in my test, 
There is a certain probability that rsync may not copy id_rsa and id_rsa.pub to other segment ,so the segment can't ssh other segment without password  when using quick check. 

so, maybe we should use  rsync -q -c -e "ssh -o BatchMode=yes -o NumberOfPasswordPrompts=0"    -c change the defalut 
algorithm

**Comment by ashwinstar** [comment]
@piyushc01 please can team look into this failure

**Comment by kpraveen457** [comment]
@anjingde can you please share the steps to reproduce this issue.
