### ISSUE TITLE
Assert: insert AO table with returning ctid

### ISSUE THREAD

**Issue by huiliang-liu** [greenplum-db/gpdb#14759]
## Bug Report
Failed assertion if insert data into an AO table with returning ctid

### Greenplum version or build
Greenplum Database 6.23.0

### OS version and uname -a
centos7, Linux 3.10.0-1160.24.1.el7.x86_64

### Expected behavior
insert successfully and return the ctid

### Actual behavior
ERROR:  Unexpected internal error (execTuples.c:1583)  (seg2 slice2 10.117.190.244:7002 pid=15933) (execTuples.c:1583)
DETAIL:  FailedAssertion("!(((bool) (((const void*)(&(slot->PRIVATE_tts_synthetic_ctid)) != ((void *)0)) && ((&(slot->PRIVATE_tts_synthetic_ctid))->ip_posid != 0))))", File: "execTuples.c", Line: 1583)
HINT:  Process 15933 will wait for gp_debug_linger=120 seconds before termination.
Note that its locks and other resources will not be released until then.

### Step to reproduce the behavior
```
gpadmin=# CREATE TABLE returning_ctid_ao (f1 serial, f2 text) WITH (appendonly=true) DISTRIBUTED BY (f1);
CREATE TABLE
gpadmin=# INSERT INTO returning_ctid_ao(f2) VALUES ('test1') RETURNING ctid;
ERROR:  Unexpected internal error (execTuples.c:1583)  (seg2 slice2 10.117.190.244:7002 pid=15933) (execTuples.c:1583)
DETAIL:  FailedAssertion("!(((bool) (((const void*)(&(slot->PRIVATE_tts_synthetic_ctid)) != ((void *)0)) && ((&(slot->PRIVATE_tts_synthetic_ctid))->ip_posid != 0))))", File: "execTuples.c", Line: 1583)
HINT:  Process 15933 will wait for gp_debug_linger=120 seconds before termination.
Note that its locks and other resources will not be released until then.
```

**Comment by kainwen** [comment]
Does main branch have the issue?

**Comment by huiliang-liu** [comment]
> Does main branch have the issue?

No, main branch doesn't have this issue. And AOCO table on gpdb6 works well too

**Comment by kainwen** [comment]
Fixed by https://github.com/greenplum-db/gpdb/pull/14771
