### ISSUE TITLE
Readable external tables' distribution policy could be altered but not created with

### ISSUE THREAD

**Issue by adam8157** [greenplum-db/gpdb#14754]
## Bug Report

```
gpadmin=# create external web table t1_readable (c1 int) execute 'cat /tmp/t1_seg${GP_SEGMENT_ID}.txt' on all format 'csv' distributed by (c1);
ERROR:  readable external tables can't specify a DISTRIBUTED BY clause

gpadmin=# create external web table t1_readable (c1 int) execute 'cat /tmp/t1_seg${GP_SEGMENT_ID}.txt' on all format 'csv';
CREATE EXTERNAL TABLE

gpadmin=# alter external table t1_readable set distributed by (c1);
ALTER FOREIGN TABLE
```

### Greenplum version or build
main branch

### Expected behavior
We should allow creating readable external tables with a distribution policy, or don't allow altering readable external tables.

**Comment by adam8157** [comment]
Please review all the related behaviors of external and foreign tables.

**Comment by RuiWang-vmw** [comment]
@adam8157  Thank you. 6X_STABLE is correct. The main branch has some problem. So I assign the issue to you?
