### ISSUE TITLE
Make license more obvious

### ISSUE THREAD

**Issue by timothyclemansinsea** [greenplum-db/gpdb#1476]
Many Github repos ave their license near the top on Github. GPDB doesn't and because there is not a license header in the readme I missed it when I first wrote this issue. I was really happy to see Apache license though :)

**Comment by hlinnaka** [comment]
Hi Tim!

Hmm. The second paragraph in the README says "The Greenplum project is released under the Apache 2 license". I think that's quite prominent. I guess we could add a "## License" header before that paragraph, though; do you think that would be helpful/worthwhile?

**Comment by ivannovick** [comment]
Hi Tim,

I see this file in the root directory, https://github.com/greenplum-db/gpdb/blob/master/LICENSE

Any reason this is not good enough.

Plus @rvs for his input?

**Comment by timothyclemansinsea** [comment]
Making it appear at top right in Github would be helpful

**Comment by danielgustafsson** [comment]
The license in the top right corner on Github is per automatic discovery of the LICENSE file. I'm not sure why Github doesn't pick it up though, but the licensee Ruby gem used seems to be very good at picking up Apache 2 license files (same issue is in https://github.com/gradle/gradle and https://github.com/grails/grails-core for example). I've made an attempt to fix this in #1559 but I'm unsure if (a) it works and (b) if it's worth it.

**Comment by danielgustafsson** [comment]
I pushed #1559 and the license is now properly identified by Github in the top-right corner on the repository. Thanks for the report.
