### ISSUE TITLE
incorrect Redistribute Motion in partition table join

### ISSUE THREAD

**Issue by ashwinstar** [greenplum-db/gpdb#14775]
### Greenplum version or build
7X

This is conversion https://github.com/greenplum-db/gpdb/pull/13423 to github issue as proposed code change was risky in it and needs to be freshly coded. Given not able to visit the code changes currently, track the same as github issue to be fixed in future.

Description from the PR:
There will have a Redistribute Motion node, if we join a partition table to another normal table,
and the distributed key is varchar(), and the join restriction is distributed key, just like this:
```
postgres=# create table foo (id varchar(32), t varchar(32))
distributed by (id)
partition by range(t)
(
  partition p1 start ('0') end ('100'),
  partition p2 start ('101') end ('201') 
);

postgres=# create table bar (id varchar(32), t varchar(32))
distributed by (id);

postgres=# explain (costs off) select * from bar a join foo b on a.id=b.id;
                         QUERY PLAN                         
------------------------------------------------------------
 Gather Motion 3:1  (slice2; segments: 3)
   ->  Hash Join
         Hash Cond: ((b.id)::text = (a.id)::text)
         ->  Redistribute Motion 3:3  (slice1; segments: 3)
               Hash Key: b.id
               ->  Append
                     ->  Seq Scan on foo_1_prt_p1 b
                     ->  Seq Scan on foo_1_prt_p2 b_1
         ->  Hash
               ->  Seq Scan on bar a
 Optimizer: Postgres query optimizer
```
The reason is that when we use cdb_pull_up_eclass to upgrade the equivalence class in the append
path, the RelabelType is ignored, resulting in the creation of unnecessary equivalence members,
resulting in a wrong judgment in the subsequent cdbpath_match_preds_to_both_distkeys, and then
adds the wrong motion node.

**Comment by kainwen** [comment]
Hi @ashwinstar  the old PR is to fix the issue https://github.com/greenplum-db/gpdb/issues/13402, it just forget to mention in the pr message (it write this in test case).  Let me close this issue.
