### ISSUE TITLE
compile postgis-2.5.9 failed

### ISSUE THREAD

**Issue by 409582940** [greenplum-db/gpdb#14783]
![image](https://user-images.githubusercontent.com/53630948/212274110-a3d87e34-93eb-4a1e-9c1b-d32ae0c16a61.png)

I try to install the greenplum plug-in postGIS on the arm architecture server by compiling. The result of executing the ./configure command is normal. But the execution of the make command failed, as shown in the figure

local Greenplum Version: 'postgres (Greenplum Database) 6.16.1 build commit:10171814c15886ff864fad19b89b3a7c224e0a97'

master Greenplum Version: 'PostgreSQL 9.4.24

on aarch64-unknown-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623

Linux mdw 4.18.0-193.28.1.el7.aarch64 #1 SMP Wed Oct 21 16:25:35 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux

**Comment by beeender** [comment]
This issue should be raised in https://github.com/greenplum-db/geospatial since it is not related to gpdb compiling.
