### ISSUE TITLE
ERROR:  could not find hash function for hash operator 2139062142 (execGrouping.c:241)

### ISSUE THREAD

**Issue by CharlieTTXX** [greenplum-db/gpdb#14817]
## Bug Report
ERROR:  could not find hash function for hash operator 2139062142 (execGrouping.c:241)

### Greenplum version or build
only 6X, main don't have such issue

### OS version and uname -a
centos

### autoconf options used ( config.status --config )
set optimizer = off;

### Step to reproduce the behavior

CREATE TABLE products (product_id int, name text, price numeric);
ALTER TABLE products ADD PRIMARY KEY (product_id);

set enable_groupagg = off;
postgres=# SELECT count(distinct name), price FROM products GROUP BY product_id;
ERROR:  could not find hash function for hash operator 2139062142 (execGrouping.c:241)

**Comment by CharlieTTXX** [comment]
https://github.com/greenplum-db/gpdb/pull/14781

**Comment by kainwen** [comment]
Fixed by https://github.com/greenplum-db/gpdb/pull/14781 on 6X.
