### ISSUE TITLE
brin_summarize_new_values() takes very long to run for AO table

### ISSUE THREAD

**Issue by ashwinstar** [greenplum-db/gpdb#14836]
### Greenplum version or build
7X

### Expected behavior
Efficient running of `brin_summarize_new_values()` is crucial for BRIN index usage

### Actual behavior
This is crucial function for BRIN working. Regular inserts doesn't keep the BRIN index updated. Using `brin_summarize_new_values()` one can summarize the values.

### Step to reproduce the behavior

```sql
drop table t_list;
create table t_list as select generate_series(1,100000000) id;
drop table if exists table_ao_brin;
create table table_ao_brin (id int, descr text, created_at timestamp) using ao_row with (compresstype=zstd);
CREATE INDEX table_ao_brin_idx_created_at ON table_ao_brin USING brin(created_at) with (pages_per_range=10);
insert into table_ao_brin select id, 'test ' || id, '2012-01-01 0:00'::timestamptz + id * interval '2 sec' from t_list;
analyze table_ao_brin;
select brin_summarize_new_values('table_ao_brin_idx_created_at');
```

`brinsummarize()` has loop `for (; startBlk < heapNumBlocks; startBlk += pagesPerRange)`. In above repro - `heapNumBlocks=33555450`. It extracts it based on `brin_ao_tid_ranges()`, which seems to be using last sequence value from gp_fastsequence table to calculate the nblocks return value

**Comment by ashwinstar** [comment]
I have updated the repro which felt slow. The total number of pages summarized with that is 306 so quite big number
```sql
ashwin=# select brin_summarize_new_values('table_ao_brin_idx_created_at');
 brin_summarize_new_values 
---------------------------
                       306
(1 row)
```
So, not sure if something is really inefficient or with that many pages it going to be slow. (I don't have timing on so don't have the timing number for this but for sure is > 5 mins range)

**Comment by soumyadeep2007** [comment]
With ORCA off, and an unoptimized build:

main (without PR: #15027)
```
 brin_summarize_new_values 
---------------------------
                       306
(1 row)

Time: 588847.024 ms (09:48.847)
```

with PR: #15027 
```
 brin_summarize_new_values 
---------------------------
                       306
(1 row)

Time: 533280.676 ms (08:53.281)
```

I know the reason why this is slow.

Because this FIXME is not fixed yet. Each call to `summarize_range` results in full sequential scan of the AO/CO rel! :)  
```
/*
	* GPDB_12_MERGE_FIXME: How to properly do a partial scan? Currently,
	* we scan the whole table, and throw away tuples that are not in the
	* range. That's clearly very inefficient.
	*/
if (ItemPointerGetBlockNumber(&slot->tts_tid) < start_blockno ||
	(numblocks != InvalidBlockNumber && ItemPointerGetBlockNumber(&slot->tts_tid) >= numblocks))
	continue;
```
