### ISSUE TITLE
ORCA picks seqscan over indexscan though actual execution works faster with indexscan

### ISSUE THREAD

**Issue by ashwinstar** [greenplum-db/gpdb#14866]
## Bug Report
Opening the issue reported by OSS user via greenplum slack to track.

### Greenplum version or build
6X_STABLE (6.21)

### Expected behavior
Indexscan is picked instead of seqscan as it will be faster to execute.

### Actual behavior
When joining a table with ps1.detections on objid, the query planner will not always choose to use the index on detections (ps1_detections_objid_idx).

It will choose to use the index when the other table is small and when the other table reaches a certain threshold, it will choose to use a sequential scan on ps1.detections.  This also applied to joining the results of a subquery with ps1.detections.

On average a sequential scan on ps1.detections takes approximately 30 minutes so this is a detriment to the performance of the query.

For example, this code produces the following execution plan with a table size of 10000 which uses the index and finishes within milliseconds:

```sql
create temp table tmp_table as select objid from ps1.mean_object limit 10000;
explain analyze select d.objid, d.detectid from ps1.detections as d
inner join tmp_table as t on d.objid=t.objid;

 Gather Motion 168:1  (slice2; segments: 168)  (cost=0.00..421010.15 rows=8257942906 width=16)
  ->  Nested Loop  (cost=0.00..126728.52 rows=49154423 width=16)
        Join Filter: true
        ->  Redistribute Motion 168:168  (slice1; segments: 168)  (cost=0.00..431.00 rows=60 width=8)
              Hash Key: tmp_table.objid
              ->  Seq Scan on tmp_table  (cost=0.00..431.00 rows=60 width=8)
        ->  Index Scan using ps1_detections_objid_idx on detections  (cost=0.00..122082.04 rows=4916 width=16)
              Index Cond: (objid = tmp_table.objid)
Optimizer: Pivotal Optimizer (GPORCA)
```

The same code with a table size of 20000 produces the following execution plan with performs a sequential scan on ps1.detections and take around 30 minutes:

```sql
create temp table tmp_table as select objid from ps1.mean_object limit 20000;
explain select d.objid, d.detectid from ps1.detections as d
inner join tmp_table as t on d.objid=t.objid;

Gather Motion 168:1  (slice2; segments: 168)  (cost=0.00..761449.77 rows=16515885812 width=16)
  ->  Hash Join  (cost=0.00..172886.52 rows=98308845 width=16)
        Hash Cond: (detections.objid = tmp_table.objid)
        ->  Seq Scan on detections  (cost=0.00..73059.53 rows=440172935 width=16)
        ->  Hash  (cost=431.01..431.01 rows=120 width=8)
              ->  Redistribute Motion 168:168  (slice1; segments: 168)  (cost=0.00..431.01 rows=120 width=8)
                    Hash Key: tmp_table.objid
                    ->  Seq Scan on tmp_table  (cost=0.00..431.00 rows=120 width=8)
Optimizer: Pivotal Optimizer (GPORCA)
```

### Step to reproduce the behavior
Attaching minirepro and queries to help repro the behavior.
[greenplumqueryperformanceissue.zip](https://github.com/greenplum-db/gpdb/files/10539151/greenplumqueryperformanceissue.zip)

**Comment by ashwinstar** [comment]
@gpopt fyi.. issue we discussed, opened this for tracking... Please feel free to post your thoughts and teams plan on the same.

**Comment by gpopt** [comment]
Thanks for reporting the issue.
This is a known issue of Orca's cost model that sometimes it can't reflect the exact execution cost. However, we can manually tune the cost model by setting `set optimizer_segments=30;` or some other value, we will see that Orca generated plan with Index Scan.
In the future, we are planning to add hint support to Orca, so that users can tune or control the plan easily.

**Comment by cobolbaby** [comment]
`optimizer_nestloop_factor` can be set higher.

**Comment by gpopt** [comment]
> `optimizer_nestloop_factor` can be set higher.

Yes, that is also a tuning GUC we can use.

**Comment by kainwen** [comment]
@gpopt Lazy ask here, do you know if this issue also exist in main branch? Thanks.

**Comment by gpopt** [comment]
@kainwen Yes, the issue still exists in main branch.

**Comment by sshen-stsci** [comment]
We also tried an experiment setting it higher all the way up to 1048576 and it still is using the sequential scan. Any help will be very appreciated!

**Comment by gpopt** [comment]
@sshen-stsci You can disable hashjoin so that Orca can pick indexed nestloop join by `set optimizer_enable_hashjoin=off;`.

**Comment by wfnuser** [comment]
Hi guys. I'm reading orca related code recently. And I'm wondering how was the CostModel parameters determined in the first place. Like following:
```cpp
// sequential i/o bandwidth
const CDouble CCostModelParamsGPDB::DSeqIOBandwidthVal = 1024.0;

// random i/o bandwidth
const CDouble CCostModelParamsGPDB::DRandomIOBandwidthVal = 30.0;

// tuple processing bandwidth
const CDouble CCostModelParamsGPDB::DTupProcBandwidthVal = 512.0;

// output bandwidth
const CDouble CCostModelParamsGPDB::DOutputBandwidthVal = 256.0;

// scan initialization cost factor
const CDouble CCostModelParamsGPDB::DInitScanFacorVal = 431.0;

// table scan cost unit
const CDouble CCostModelParamsGPDB::DTableScanCostUnitVal = 5.50e-07;

// index scan initialization cost factor
const CDouble CCostModelParamsGPDB::DInitIndexScanFactorVal = 142.0;

// index block cost unit
const CDouble CCostModelParamsGPDB::DIndexBlockCostUnitVal = 1.27e-06;
```

Is there any document or paper about this part? I have no clue yet. 
BTW, I'm really interested in ORCA. If there are any easy to get started issues, I'd love to help.😄

**Comment by 24nishant** [comment]
> Hi guys. I'm reading orca related code recently. And I'm wondering how was the CostModel parameters determined in the first place. Like following:
> 
> ```c++
> // sequential i/o bandwidth
> const CDouble CCostModelParamsGPDB::DSeqIOBandwidthVal = 1024.0;
> 
> // random i/o bandwidth
> const CDouble CCostModelParamsGPDB::DRandomIOBandwidthVal = 30.0;
> 
> // tuple processing bandwidth
> const CDouble CCostModelParamsGPDB::DTupProcBandwidthVal = 512.0;
> 
> // output bandwidth
> const CDouble CCostModelParamsGPDB::DOutputBandwidthVal = 256.0;
> 
> // scan initialization cost factor
> const CDouble CCostModelParamsGPDB::DInitScanFacorVal = 431.0;
> 
> // table scan cost unit
> const CDouble CCostModelParamsGPDB::DTableScanCostUnitVal = 5.50e-07;
> 
> // index scan initialization cost factor
> const CDouble CCostModelParamsGPDB::DInitIndexScanFactorVal = 142.0;
> 
> // index block cost unit
> const CDouble CCostModelParamsGPDB::DIndexBlockCostUnitVal = 1.27e-06;
> ```
> 
> Is there any document or paper about this part? I have no clue yet. BTW, I'm really interested in ORCA. If there are any easy to get started issues, I'd love to help.😄

@wfnuser , Thank you for your interest and queries on ORCA. I will try to find details on the cost model parameters and get back to you. You can refer, '[ORCA bootcamp](https://github.com/greenplum-db/gpdb/wiki/ORCA-Training-Boot-Camp)', its provide an easy way know details of ORCA and to start working on it.

**Comment by wfnuser** [comment]
> @wfnuser , Thank you for your interest and queries on ORCA. I will try to find details on the cost model parameters and get back to you. You can refer, '[ORCA bootcamp](https://github.com/greenplum-db/gpdb/wiki/ORCA-Training-Boot-Camp)', its provide an easy way know details of ORCA and to start working on it.

Thanks a lot. That's an awesome document and definitely helps a lot.

**Comment by 24nishant** [comment]
The 'Main' branch as of today, is able to select 'Index scan' plan for both of the queries given in the minirepro.  

QUERY 1:  
explain analyze with mycte as (select objid from ps1.mean_object limit 100000)
select d.objid, d.detectid
from ps1.detections as d
inner join mycte as m on d.objid=m.objid;


pilot_catalog-# pilot_catalog=# \i ~/Downloads/greenplumqueryperformanceissue/seq_scan.sql

QUERY PLAN

 ```
Gather Motion 3:1  (slice1; segments: 3)  (cost=0.00..1884552.60 rows=700230 width=16) (actual time=7.215..7.215 rows=0 loops=1)
   ->  Nested Loop  (cost=0.00..1884510.84 rows=233410 width=16) (actual time=0.000..5.148 rows=0 loops=1)
         Join Filter: true
         ->  Redistribute Motion 1:3  (slice2)  (cost=0.00..1284195.87 rows=33334 width=8) (actual time=0.000..5.145 rows=0 loops=1)
               Hash Key: mean_object.objid
               ->  Limit  (cost=0.00..1284193.79 rows=100000 width=8) (actual time=0.000..5.892 rows=0 loops=1)
                     ->  Gather Motion 3:1  (slice3; segments: 3)  (cost=0.00..1284192.99 rows=100000 width=8) (actual time=0.000..5.890 rows=0 loops=1)
                           ->  Limit  (cost=0.00..1284190.01 rows=33334 width=8) (actual time=0.000..0.896 rows=0 loops=1)
                                 ->  Seq Scan on mean_object  (cost=0.00..1231808.67 rows=3520233472 width=8) (actual time=0.000..0.893 rows=0 loops=1)
         ->  Index Scan using ps1_detections_objid_idx on detections  (cost=0.00..600294.80 rows=3 width=16) (never executed)
               Index Cond: (objid = mean_object.objid)
 Optimizer: Pivotal Optimizer (GPORCA)
 Planning Time: 61.688 ms
   (slice0)    Executor memory: 58K bytes.
   (slice1)    Executor memory: 44K bytes avg x 3 workers, 44K bytes max (seg0).
   (slice2)    Executor memory: 13K bytes (entry db).
   (slice3)    Executor memory: 37K bytes avg x 3 workers, 37K bytes max (seg0).
 Memory used:  128000kB
 Execution Time: 8.440 ms
(19 rows)
```


Query2: 
explain analyze with mycte as (select objid from ps1.mean_object limit 20000)
select d.objid, d.detectid
from ps1.detections as d
inner join mycte as m on d.objid=m.objid;


pilot_catalog-# \i ~/Downloads/greenplumqueryperformanceissue/index_scan.sql

 QUERY PLAN

```
 Gather Motion 3:1  (slice1; segments: 3)  (cost=0.00..1404262.31 rows=140046 width=16) (actual time=7.970..7.971 rows=0 loops=1)
   ->  Nested Loop  (cost=0.00..1404253.96 rows=46682 width=16) (actual time=0.000..5.187 rows=0 loops=1)
         Join Filter: true
         ->  Redistribute Motion 1:3  (slice2)  (cost=0.00..1284190.97 rows=6667 width=8) (actual time=0.000..5.184 rows=0 loops=1)
               Hash Key: mean_object.objid
               ->  Limit  (cost=0.00..1284190.55 rows=20000 width=8) (actual time=0.000..6.606 rows=0 loops=1)
                     ->  Gather Motion 3:1  (slice3; segments: 3)  (cost=0.00..1284190.39 rows=20000 width=8) (actual time=0.000..6.604 rows=0 loops=1)
                           ->  Limit  (cost=0.00..1284189.80 rows=6667 width=8) (actual time=0.000..1.275 rows=0 loops=1)
                                 ->  Seq Scan on mean_object  (cost=0.00..1231808.67 rows=3520233472 width=8) (actual time=0.000..1.272 rows=0 loops=1)
         ->  Index Scan using ps1_detections_objid_idx on detections  (cost=0.00..120058.96 rows=3 width=16) (never executed)
               Index Cond: (objid = mean_object.objid)
 Optimizer: Pivotal Optimizer (GPORCA)
 Planning Time: 57.511 ms
   (slice0)    Executor memory: 58K bytes.
   (slice1)    Executor memory: 44K bytes avg x 3 workers, 44K bytes max (seg0).
   (slice2)    Executor memory: 13K bytes (entry db).
   (slice3)    Executor memory: 37K bytes avg x 3 workers, 37K bytes max (seg0).
 Memory used:  128000kB
 Execution Time: 9.352 ms
(19 rows)
```
