### ISSUE TITLE
Function get_ao_compression_ratio() reports an error “ERROR:  table is not an append-only relation” for AO partition table

### ISSUE THREAD

**Issue by minmindu** [greenplum-db/gpdb#14876]
### Greenplum version or build

7X

### OS version and uname -a

Redhat8

### Expected behavior

When applying the function `get_ao_compression_ratio()` to a root partition, expect the same behaviour as GPDB v6. 

### Actual behavior

It reports an error “_ERROR:  ‘foo_partition’ is not an append-only relation_” on the root partition even though the partition table is an AO table. (note: foo_parition is the partitioned table name). 

See the below section for reproduced steps. 

### Step to reproduce the behavior

1. Testing table with data:

```
CREATE TABLE public.foo_partition
(id SERIAL, value TEXT, sales_date date)
WITH (appendoptimized=true, orientation=column, compresstype=zlib, compresslevel=5)
DISTRIBUTED BY (id)
PARTITION BY RANGE (sales_date)
(
  -- monthly
  START (date '2015-01-01') INCLUSIVE END (date '2021-01-01') EXCLUSIVE  EVERY (INTERVAL '1 month')
);

INSERT INTO public.foo_partition(sales_date)
SELECT  generate_series('2015-01-01'::date, '2020-12-31', '20d')::date;
```

2. Verify the table storage type — ao_column

```
demo=# \dt foo_partition
                        List of relations
 Schema |     Name      |       Type        |  Owner  |  Storage
--------+---------------+-------------------+---------+-----------
 public | foo_partition | partitioned table | gpadmin | ao_column
(1 row)
```

3. Test the function get_ao_compression_ratio()
— Result in GP7:
```
demo=# select get_ao_compression_ratio('public.foo_partition');
ERROR:  'foo_partition' is not an append-only relation
```

-- Result in GP6 (as expected)
```
testdb=# select get_ao_compression_ratio('public.foo_partition');
 get_ao_compression_ratio
--------------------------
                       -1
```

**Comment by l-wang** [comment]
Right now we exclude partitioned table as append-optimized tables even if we store ao_row/ao_column as the storage type in the catalog.

See code at https://github.com/greenplum-db/gpdb/blob/main/src/include/utils/rel.h#L454
```c
#define RelationIsAppendOptimized(relation) \
	((RelationIsAoRows(relation) || RelationIsAoCols(relation)) && \
		relation->rd_rel->relkind != RELKIND_PARTITIONED_TABLE)
```

The definition for function `get_ao_compression_ratio()`:
```c
/**************************************************************
 * get_ao_compression_ratio
 *
 * Given an append-only table oid or name calculate the effective
 * compression ratio for this append only table stored data.
 * If this info is not available (pre 3.3 created tables) then
 * return -1.
 **************************************************************/
Datum
get_ao_compression_ratio(PG_FUNCTION_ARGS)
```

So what is the expected output for partitioned table with AO storage type? Do we want just return -1 or calculate the average compression ratio of its AO children (if any)?

**Comment by ashwinstar** [comment]
Seems best would be to keep the behavior consistent with 6X here. Returning the ratio for children in mixed hierarchy would be super confusing.

**Comment by kainwen** [comment]
Fixed by https://github.com/greenplum-db/gpdb/pull/15390
