### ISSUE TITLE
Connector: Metabase

### ISSUE THREAD

**Issue by dannyeuu** [greenplum-db/gpdb#14907]
### Metabase connector request
Metabase is the BI tool with the friendly UX and integrated tooling to let your company explore data on their own

I created a feature request on Metabase repository too https://github.com/metabase/metabase/issues/6950

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by ashwinstar** [comment]
Sure, though anything required  to be done from greenplum side?

**Comment by ashwinstar** [comment]
No real action on this github issue hence closing the same. Can continue to track the :+1: in the description for interest in feature.
