### ISSUE TITLE
Wrong result of Multi count(distinct xxx) on primary key

### ISSUE THREAD

**Issue by charliettxx** [greenplum-db/gpdb#14911]
## Bug Report
Wrong result of Multi count(distinct xxx) on primary key

### Greenplum version or build
main branch, not in 6X

### Step to reproduce the behavior
set optimizer = off;

create table t1(a int, b int, c int, d int, e int, primary key(a,b));
insert into t1  select i, i, i %4, i %7, i %17 from generate_series(1, 100) i;
analyze t1;

set enable_groupagg = off;
select count(distinct a), count(distinct d), e from t1 group by a, b;
 count | count | e  
-------+-------+----
     1 |     1 |   
     1 |     1 |  0
     1 |     1 | 11
     1 |     1 |   
     1 |     1 | 16
     1 |     1 | 12
     1 |     1 |   
     1 |     1 |   
     1 |     1 |   
     1 |     1 |   
     1 |     1 |   
     1 |     1 |   
     1 |     1 |   
     1 |     1 |   
     1 |     1 |  2
     1 |     1 |   
     1 |     1 | 10
     1 |     1 |   
     1 |     1 |  0
     1 |     1 |  7
     1 |     1 |   

The last column `e` in above sql was filled with unexpected NULL value.

**Comment by kainwen** [comment]
Fixed by https://github.com/greenplum-db/gpdb/pull/14954
