### ISSUE TITLE
添加新列后，analyze操作报错：index 6 exceed size of vpinfo array size 6

### ISSUE THREAD

**Issue by Chinaboy2018** [greenplum-db/gpdb#14914]
### Greenplum version or build
Greenplum 5.19.0
### OS version and uname -a
redhat7.5
### Expected behavior
analzye
### Actual behavior
升级gpcc4.9至4.19，部分表新增字段。gpcc安装完成之后，执行了analyze操作，发生报错index 6 exceed size of vpinfo array size 6

### Step to reproduce the behavior
1、停止gpcc4.9
2、安装gpcc4.13.0
3、待安装完成后，对gpperfmon库执行analyzedb操作
4、部分新增字段的表无法收集统计信息：index 6 exceed size of vpinfo array size 6

**Comment by yangru** [comment]
Please issue a jira bug for us, GPCC bugs are not supposed to appear here.
