### ISSUE TITLE
Concurrent UPDATE partitioned table crash w/ global deadlock detector and ORCA

### ISSUE THREAD

**Issue by l-wang** [greenplum-db/gpdb#14935]
### Greenplum version or build

7X only as of 2dd9f7a2ece

### OS version and uname -a

Ubuntu 22.04

### autoconf options used ( config.status --config )

The following config crashes:
```
'--enable-depend' '--with-perl' '--with-python' '--with-libxml' '--prefix' '/usr/local/gpdb' 'CC=clang-12' 'CXX=clang++-12' 'CFLAGS=-O3 -fno-omit-frame-pointer' 'CPPFLAGS=-O3 -fno-omit-frame-pointer' 'LD_LIBRARY_PATH=/usr/local/lib''
```

The following config which enables debug errors:
```
'--enable-depend' '--enable-debug' '--enable-cassert' '--with-perl' '--with-python' '--with-libxml' '--prefix' '/usr/local/gpdb' 'CC=clang-12' 'CXX=clang++-12' 'CFLAGS=-O0 -fno-omit-frame-pointer -pthread -g -g3' 'CPPFLAGS=-O0 -fno-omit-frame-pointer'
```

### Expected behavior

Concurrently UPDATE partitioned table should not crash the database. The later UPDATE should be blocked or canceled by the global deadlock detector.

### Actual behavior

Concurrently UPDATE partitioned table crashes on the segment with retail build or emits assertion error with debug build.

### Step to reproduce the behavior

1. Enable global deadlock detector if not already:
```sh
gpconfig -c gp_enable_global_deadlock_detector -v on
gpstop -air
```

2. Create a partitioned table and insert some data:
```sql
create table part(a int, b int, c int) partition by range(b) (start (1) end (7) every (3));
insert into part values (1, 1, 1), (1, 2, 1);
```
3. Perform UPDATE in two concurrent sessions:
```sql
UPDATE part SET c = 1;
```
Specifically, perform queries in the two concurrent sessions (S1 and S2) as below:

```
S1: BEGIN;
S1: UPDATE part SET c = 1;
S2: UPDATE part SET c = 1
S1: COMMIT;
```

Session 2 crashes with retail build:
```
ERROR:  Error on receive from seg1 127.0.1.1:7003 pid=355223: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
```

Session 2 ERRORs with debug build:
```
ERROR:  Unexpected internal error (assert.c:48)  (seg1 127.0.1.1:7003 pid=305120) (assert.c:48)
DETAIL:  FailedAssertion("!(rti > 0 && rti <= epqstate->parentestate->es_range_table_size)", File: "execMain.c", Line: 3564)
```

**Comment by gpopt** [comment]
Is it related with this PR https://github.com/greenplum-db/gpdb/pull/14304?
@chrishajas @THANATOSLAVA

**Comment by kainwen** [comment]
RCA:

When GDD is enabled, heap tuples can be concurrently updated on segments. When waking up from transaction lock and the other transaction is committed, this QE will do EvalPlanQual to see what it need to do with the new tuple. (Yes, means the other transaction is doing a heap_update).

ORCA's plan  for DML on partition table takes advantage of `DynamicScan`, this is quite different from planner's method, method's MofityTable plannode has many child plans, sort of like append to expand all the leafs of partition.

Thus the InitPlan stage, planner's plan will init all ResultRelations, however, ORCA's plan only contain root as result relation, does not init for leaf results.

More reproduces:

GDD enabled, heap table, partition table.

1. session 1 begin; and then do a heap_update on the target partition table
2. session 2 need to invoke eval plan qual,
  - orca enabled
  - delete on the root partition
  - update on the root partition


--------------------

On 6X, orca's update is all using split-update, and Greenplum will consider this pattern possible to tuple move, thus will throw error without executing EvalPlanQual. But with DELETE it also throw the same error, which is confusing.

**Comment by charliettxx** [comment]
https://github.com/greenplum-db/gpdb/pull/15253 has been merged, we could close it.
