### ISSUE TITLE
Greenplum segment table mismatch

### ISSUE THREAD

**Issue by NaveenReddy1** [greenplum-db/gpdb#14964]
## Bug Report

Few days back i took the backup for one of primary segments and somehow the data got corrupted in that segment, so we deleted the segment. With the backup segment we started the db. So in that period new tables got created in other segments. When i tried to run the select query for that table getting the error `(ERROR:  relation not found (OID 4099972) DETAIL:  This can be validly caused by a concurrent delete operation on this object.)`. Can someone please suggest what we can do?

### Greenplum version or build

PostgreSQL 9.4.26 (Greenplum Database 6.21.0 build commit:d0087e3b24c54d203ca8bb315559205f13cd6393) on x86_64-unknown-linux-gnu, compiled by gcc (GCC) 6.4.0, 64-bit compiled on Jun 10 2022 01:44:57

**Comment by kainwen** [comment]
Can you try `gpcheckcat` to see if there are any catalog issues

**Comment by ashwinstar** [comment]
Your steps clearly the wrong thing was done. Greenplum forms consistent database collectively from all segments. Can't just rollback on segment in cluster to old state and expect things to work. Obviously, new tables are missing in reverted segment and will give error.
