### ISSUE TITLE
Pgdump in GPDB7 cannot dump partition leaf tables

### ISSUE THREAD

**Issue by xiaoxiaoHe-E** [greenplum-db/gpdb#15014]
## Feature Request

In GPDB7, pgdump cannot dump the leaf tables of a partition table.  However, in GPDB6, the same pgdump command can dump the intact partition table.

Here is an example of a partition table to be copied:
```
CREATE TABLE public.test_partition (
    a integer,
    b text
)
 DISTRIBUTED BY (a) PARTITION BY RANGE(a)
          (
          PARTITION test_partition_1 START (1) END (10) WITH (tablename='test_partition_1_prt_test_partition_1', appendonly='false'),
          PARTITION test_partition_2 START (10) END (20) WITH (tablename='test_partition_1_prt_test_partition_2', appendonly='false')
          );
 ;
```

The pg_dump command:
```
pg_dump --gp-syntax -h localhost -p 7000 -U gpadmin -s -t '"public"."test_partition"' 'gpadmin'
```

The dump result in GPDB7:
```
CREATE TABLE public.test_partition (
    a integer,
    b text
)
 DISTRIBUTED BY (a) PARTITION BY RANGE(a);
```

**Comment by bmdoil** [comment]
Curious why we need '--gp-syntax' flag for pg_dump? Without that pg_dump should dump partitions using upstream syntax including the DDL for all leaf partitions.

**Comment by xiaoxiaoHe-E** [comment]
> Curious why we need '--gp-syntax' flag for pg_dump? Without that pg_dump should dump partitions using upstream syntax including the DDL for all leaf partitions.

No, I tried the command without `--gp-syntax`.  It still only dumps the root table.
```
[gpadmin@localhost ~] $ pg_dump  -h localhost -p 7000 -U gpadmin -s -t '"public"."test_partition"' 'gpadmin'
--
-- Greenplum Database database dump
--

-- Dumped from database version 12.12
-- Dumped by pg_dump version 12.12

SET gp_default_storage_options = '';
SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: test_partition; Type: TABLE; Schema: public; Owner: gpadmin
--

CREATE TABLE public.test_partition (
    a integer,
    b text
)
PARTITION BY RANGE (a) DISTRIBUTED BY (a);


ALTER TABLE public.test_partition OWNER TO gpadmin;

--
-- Greenplum Database database dump complete
--
```

**Comment by xiaoxiaoHe-E** [comment]
We can find some detailed discussion of pg_dump behavior here: https://github.com/greenplum-db/gpdb/issues/5003#issuecomment-1429170630

**Comment by jimmyyih** [comment]
I'm really surprised that upstream Postgres doesn't support a flag for pg_dump to dump the entire partition table (e.g. something like `--follow-partition-tree`).  Maybe check pgsql-hackers to see if there are any proposals and see how we can help contribute.

**Comment by ashwinstar** [comment]
https://www.postgresql.org/message-id/flat/5aa393b5-5f67-8447-b83e-544516990ee2%40migops.com

**Comment by ashwinstar** [comment]
> https://www.postgresql.org/message-id/flat/5aa393b5-5f67-8447-b83e-544516990ee2%40migops.com

Just for reference upstream committed the change today for this https://github.com/postgres/postgres/commit/a563c24c9574b74f4883c004c89275bba03c3c26, we can use that to fulfill our needs.
