### ISSUE TITLE
operator class XXX is missing support function 2 for type YYY

### ISSUE THREAD

**Issue by interma** [greenplum-db/gpdb#15036]
## Bug Report
This issue was found by sqlancer.

### Greenplum version or build
main branch

### Expected behavior
No Error

### Actual behavior
one example
```
psql:bug19.sql:5: ERROR:  operator class "varbit_ops" of access method hash is missing support function 2 for type bit varying
```

### Step to reproduce the behavior
Many cases:

**operator class "varbit_ops" of access method hash is missing support function 2 for type bit varying**
```
\c test;
DROP DATABASE IF EXISTS sqlancer;
CREATE DATABASE sqlancer ;
\c sqlancer;
CREATE UNLOGGED TABLE t0(c0 BIT VARYING(209) , c1 inet  CHECK ((((((((('(-1801253712,-320506471)'::int4range)*('[-1817824393,465626574]'::int4range)))+((('[467656382,1638768471)'::int4range)*('(-1437707946,-213244347]'::int4range)))))*((((('(-1312391224,1457011184]'::int4range)*('(969835070,1232061343)'::int4range)))+((('(-9223372036854775808,-523864176]'::int4range)*('[-1066890734,972447613]'::int4range)))))))&<('[-1935212876,-816671473]'::int4range)))) PARTITION BY HASH((t0.c0), (t0.c1));
```

**operator class "bit_ops" of access method hash is missing support function 2 for type bit**
```
CREATE TEMP TABLE IF NOT EXISTS t4(c0 int4range , c1 BIT VARYING(241) ) PARTITION BY HASH((t4.c1)) WITH (autovacuum_freeze_table_age=920041461,      parallel_workers=365, autovacuum_freeze_max_age=7584841, autovacuum_analyze_scale_factor=0, autovacuum_analyze_threshold=1233539922,                 autovacuum_vacuum_cost_delay=88, autovacuum_vacuum_cost_limit=7937, autovacuum_vacuum_threshold=1582358368, autovacuum_vacuum_scale_factor=0) ON     COMMIT PRESERVE ROWS ;
```

**operator class "cdbhash_float8_ops" of access method hash is missing support function 2 for type double precision**
```
CREATE TEMP TABLE IF NOT EXISTS t0(c0 FLOAT , c1 money  NULL) PARTITION BY HASH((t0.c0)cdbhash_float8_ops);
```

**operator class "cdbhash_oid_ops" of access method hash is missing support function 2 for type oid**
```
CREATE TABLE IF NOT EXISTS t3(c0 integer , c1 BIT VARYING(43) ) PARTITION BY HASH((t3.c0)cdbhash_oid_ops);
```

**Comment by hyongtao-db** [comment]
HI Hongxu,
I found an easy way to reproduce this bug and test it in both pg12.12 and gpdb7.
In pg12.12:
```
gpadmin=# CREATE TABLE t(c BIT) PARTITION BY HASH((t.c));
ERROR:  data type bit has no default operator class for access method "hash"
```
In gpdb7:
```
gpadmin=#  CREATE TABLE t(c BIT) PARTITION BY HASH((t.c));
ERROR:  operator class "bit_ops" of access method hash is missing support function 2 for type bit
```
I think the behavior and ERROR are almost the same.

**Comment by gtygo** [comment]
Hi,@hyongtao-db, I debugged the error. It seems that the wrong id was used when reading the system table, which resulted in the incorrect tuple being read. Can I try to fix it?

**Comment by hyongtao-db** [comment]
Hi @gtygo , of course, all the contribution is welcome. Thanks a lot.

**Comment by interma** [comment]
> Hi,@hyongtao-db, I debugged the error. It seems that the wrong id was used when reading the system table, which resulted in the incorrect tuple being read. Can I try to fix it?

Thanks @gtygo , please go ahead.
And since this issue also exists in pg12, please refer to its improvement (may in higher version).

**Comment by kainwen** [comment]
@gtygo if you already started the talk in upstream mailing list, would you please also paste here?
Thanks so much.

**Comment by gtygo** [comment]
@kainwen hi, upstream mailing list discussion here: https://www.postgresql.org/message-id/flat/CANZS%2BG_OpRDKNop%2BhsTCNBOq9C8bERyNPtE1gCsJm8kCt%3D1dDw%40mail.gmail.com

**Comment by kainwen** [comment]
I read and play with this issue recently. I don't think this is actually a problem.

It is just Greenplum does not support this kind of type to be used as partition key using default opclass. 

If users really want to use this as partition key, they need to provide opclass themselves.

As mentioned in Upstream thread, to be a parition key using hash, it needs to implement extened hash proc.

Close this.

Thanks @gtygo for you work!
