### ISSUE TITLE
Missing a colon in LD_LIBRARY_PATH

### ISSUE THREAD

**Issue by Simon-Wong** [greenplum-db/gpdb#15031]
## Bug Report
When I configure and make and make install a gpdb  in the way  that I package the library file in the installation directory,it work well at fist,but not good after restart my pc.My GNOME desktop get black when I login as gpadmin!
I think it should be a bug about settings,so I see the file greenplum_path.sh and get the line about LD_LIBRARY_PATH.
I find that if I add a colon like that
LD_LIBRARY_PATH="${GPHOME}/lib:${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
---------------------------------------^
The desktop get back again.
### Greenplum version or build
6.23.0
### OS version and uname -a
Centos 7 2003
### autoconf options used ( config.status --config )
I use LDFLAGS=-L/xxxxx and use -I/XXXX for all libraies,not via yum.
### Expected behavior
Nomal desktop
### Actual behavior
My GNOME desktop is BLACK when I use gpadmin to login.

**Comment by Simon-Wong** [comment]
just a misunderstanding

**Comment by beeender** [comment]
No, you should not need that colon. 

```
${parameter:+word}

    If parameter is null or unset, nothing is substituted, otherwise the expansion of word is substituted.

    $ var=123
    $ echo ${var:+var is set and not null}
    var is set and not null
```

https://www.gnu.org/software/bash/manual/bash.html#Shell-Parameter-Expansion

I doubt it was caused by our shell. What is your shell? sh?
