### ISSUE TITLE
query failed.

### ISSUE THREAD

**Issue by laixiong** [greenplum-db/gpdb#1507]
when we start a query on a large table,we got that error message:
"unable to read table "xx" file "xx" (errcode 5)  read postition 7077888 (small offset 61440),actual read length  -1 (large read length 65535) (seg57 slice1 mdw22:40003 pid=28960)"

and I find the exception from file "src/backend/cdb/cdbbufferedread.c",does any one can tell me what happened to this file, and how to fixed it. thanks.

**Comment by hlinnaka** [comment]
Errcode 5 file stands for EIO, "Input/output error". Is there anything in the server log, indicating a disk failure or similar?

(That error message is horrible. Aside from the typo, it should use %m to print a human-readable error message rather than the raw errno. We should fix that.)

**Comment by laixiong** [comment]
@hlinnaka ,there is no messages mentioned about disk failure,
here is the full log in primary segment log file( and master instance logged nothing expect the main error.)
2017-01-03 11:23:34.515896 CST,"model","model",p32429,th2101761824,"12.10.6.75","46655",2017-01-03 11:23:07 CST,75347679,con799674,cmd2,seg57,slice1,dx1838324,x75347679,sx1,"ERROR","58030","unable to read table ""event_1_prt_p201701"" file ""base/25707/118958067.8961"" (errcode 5)read postition 7077888 (small offset 61440),actual read length -1 (large read length 65536)",,,,,,"select  location,count(1) as cnt from event where location is not null and ctime BETWEEN 1483286400 and 1483372746 GROUP BY location  order by cnt desc",0,,"cdbbufferedread.c",218,"Stack trace:
1    0xadad0e postgres errstart + 0x4ee
2    0xba4ddc postgres BufferedReadGrowBuffer + 0x28c
3    0xb98f46 postgres AppendOnlyStorageRead_Content + 0x276
4    0xac4f20 postgres datumstreamread_block + 0x4b0
5    0x5aa997 postgres aocs_getnext + 0x297
6    0x74481a postgres AOCSScanNext + 0x2a
7    0x73802c postgres ExecTableScanRelation + 0xbc
8    0x770f43 postgres ExecTableScan + 0x23
9    0x72ca0d postgres ExecProcNode + 0x46d
10   0x74b596 postgres ExecAppend + 0x26
11   0x72ca40 postgres ExecProcNode + 0x4a0
12   0x71cb05 postgres agg_hash_initial_pass + 0x1605
13   0x7532ec postgres ExecAgg + 0x1a9c
14   0x72cab7 postgres ExecProcNode + 0x517
15   0x76713e postgres ExecMotion + 0x57e
16   0x72c886 postgres ExecProcNode + 0x2e6
17   0x72199c postgres <symbol not found> + 0x72199c
18   0x722156 postgres ExecutorRun + 0x356
19   0x971e09 postgres PortalRun + 0xcc9
20   0x96a95b postgres PostgresMain + 0x18ab
21   0x8c707e postgres <symbol not found> + 0x8c707e
22   0x8c9e20 postgres PostmasterMain + 0xff0
23   0x7c85af postgres main + 0x44f
24   0x3f0161ecdd libc.so.6 __libc_start_main + 0xfd
25   0x48a759 postgres <symbol not found> + 0x48a759
"

**Comment by hlinnaka** [comment]
On 01/04/2017 10:46 AM, laixiong wrote:
> @hlinnaka ,there is no messages mentioned about disk failure,
> here is the full log in primary segment log file( and master instance logged nothing expect the main error.)

Did you check the Operating System's syslog? /var/log/messages and similar.

- Heikki

**Comment by laixiong** [comment]
os log message (master node,segment node all have this message):
kernel:TCP: time wait bucket table overflow
kernel: __ratelimit: xx callbacks suppressed

**Comment by laixiong** [comment]
updates:
We find this file in mirror segment is ok. we copy it to primary segment,and then restart the query, it works well.
