### ISSUE TITLE
data loss: convert float 0.5 to int

### ISSUE THREAD

**Issue by kmjs233** [greenplum-db/gpdb#15123]
### Greenplum version or build
6.21.1
### OS version and uname -a
el7
3.10.0-1160.45.1
### Expected behavior
float 0.5 -> int 1
### Actual behavior
float 0.5 -> int 0
float 1.5 -> int 2
no loss is expected in float 0.5, floor(0.5+0.5) = 1

### Step to reproduce the behavior
select pg_catalog.int4(float '0.5')
select pg_catalog.int4(float '1.5')

**Comment by kainwen** [comment]
I don't think this is a bug. Latest Postgres is also the same behavior.

And I also test OCaml  version 4.13.1:

```
utop # Int.of_float 0.5;;
- : int = 0
```

**Comment by remotefish** [comment]
Interesting.  I am not saying it is a bug or not, but I think there do have some behaviors hard to understand:

```sql
select '0.5'::float4::int4;
 int4
------
    0
(1 row)

select '0.5'::float8::int4;
 int4
------
    0
(1 row)

select '0.5'::numeric::int4;
 int4
------
    1
(1 row)

select 0.5::int4;
 int4
------
    1
(1 row)
```

Looks like float->int casting & numeric->int casting are using different policies.  In fact I think there is nothing wrong because float is not an accurate type at all.  However when I write `0.5::int4` I do thought I'm expressing `'0.5'::float4::int4`, but it is not.

**Comment by kmjs233** [comment]
I would call it a bug since it's not precision loss. Following IEEE 754 standard, 0.5 can be represented as floating point with no loss. I'm quite interested in where the loss is.
We do have:
floor（float '0.5' +float '0.5')::int = 1

**Comment by kainwen** [comment]
> I would call it a bug since it's not precision loss. Following IEEE 754 standard, 0.5 can be represented as floating point with no loss. I'm quite interested in where the loss is. We do have: floor（float '0.5' +float '0.5')::int = 1

Hi @kmjs233 

I search the C std, find in https://www.open-std.org/jtc1/sc22/wg14/www/docs/n1548.pdf in Section `H.2.4 Type conversions`, the 2nd paragraph:

>  In the above conversions from floating to integer, the use of (cast)x can be replaced with (cast)round(x), (cast)rint(x), (cast)nearbyint(x), (cast)trunc(x), (cast)ceil(x), or (cast)floor(x). In addition, C’s floating-point to integer conversion functions, lrint(), llrint(), lround(), and llround(), can be used. They all meet LIA−1’s requirements on floating to integer rounding for in-range values. For out-of-range values, the conversions shall silently wrap for the modulo types.

C-language does not require type cast expression from float to integer using `round`. It mentions the requirement is from LIA. So I think for SQL it can also choose any as implementation. (I do not search SQL-standard).

**Comment by kainwen** [comment]
> However when I write `0.5::int4` I do thought I'm expressing `'0.5'::float4::int4`, but it is not.

Hi @remotefish 

Greenplum (Postgres) has lexical tokens for float and string, so the two expressions have different syntax tree.

**Comment by kmjs233** [comment]
(cast)round(x), (cast)rint(x), (cast)nearbyint(x), (cast)trunc(x), (cast)ceil(x), (cast)floor(x)
I'm still wondering which one is in use, and if any of these has current behavior:
0.5 -> 0
0.6 -> 1
1.5 -> 2

**Comment by kmjs233** [comment]
it seems rint does it, always  return even numbers when remainder is 0.5

**Comment by kainwen** [comment]
> it seems rint does it, always return even numbers when remainder is 0.5

Yeah. The function `dtoi4` of Greenplum (Postgres) will call `rint` to cast float to int.

```c
/*
 *      dtoi4           - converts a float8 number to an int4 number
 */
Datum
dtoi4(PG_FUNCTION_ARGS)
{
    float8      num = PG_GETARG_FLOAT8(0);

    /*
     * Get rid of any fractional part in the input.  This is so we don't fail
     * on just-out-of-range values that would round into range.  Note
     * assumption that rint() will pass through a NaN or Inf unchanged.
     */
    num = rint(num);

    /* Range check */
    if (unlikely(isnan(num) || !FLOAT8_FITS_IN_INT32(num)))
        ereport(ERROR,
                (errcode(ERRCODE_NUMERIC_VALUE_OUT_OF_RANGE),
                 errmsg("integer out of range")));

    PG_RETURN_INT32((int32) num);
}
```

If you are converting from numeric to float, to code path is to call the function will do something like `round`.

```c
/*
 * Convert numeric to int8, rounding if needed.
 *
 * If overflow, return false (no error is raised).  Return true if okay.
 */
static bool
numericvar_to_int64(const NumericVar *var, int64 *result)
{
    NumericDigit *digits;
    int         ndigits;
    int         weight;
    int         i;
    int64       val;
    bool        neg;
    NumericVar  rounded;

    /* Round to nearest integer */
    init_var(&rounded);
    set_var_from_var(var, &rounded);
    round_var(&rounded, 0);
```
