### ISSUE TITLE
ERROR:  could not pull up equivalence class using projected target list (pathkeys.c:1539)

### ISSUE THREAD

**Issue by interma** [greenplum-db/gpdb#15149]
## Bug Report
This issue was found by sqlancer.

### Greenplum version or build
main branch

### Expected behavior
No Error

### Actual behavior
```
psql:pathkeys.sql:47: ERROR:  could not pull up equivalence class using projected target list (pathkeys.c:1539)
```

### Step to reproduce the behavior
See the attached sql file 
[pathkeys.txt](https://github.com/greenplum-db/gpdb/files/10906684/pathkeys.txt)

**Comment by dreamedcheng** [comment]
Hi, I opened a PR to fix this issue. Could you please take a look? Thanks.

**Comment by interma** [comment]
Sorry for the late reply, looks your PR has been reviewed.
Thanks @dreamedcheng for your contribution!

**Comment by interma** [comment]
PR merged, and this issue doesn't exist in 6x.
