### ISSUE TITLE
TRUSTED_SHELL not be used in gpinitsystem

### ISSUE THREAD

**Issue by RMTT** [greenplum-db/gpdb#15176]
# Bug Report
TRUSTED_SHELL not be used in gpinitsystem

### Greenplum version or build
6X_STABLE

### OS version and uname -a
4.18.0-448.el8.x86_64

### Expected behavior
gpinitsystem can use TRUSTED_SHELL in configuration file.

### Actual behavior
gpinitsystem not use TRUSTED_SHELL in configuration file.

### Step to reproduce the behavior
```shell
# before this, echo gpcreateseg command in gpcreateseg.sh
make create-demo-cluster 
```

`gpinitsystem` call `gpceateseg.sh`:
https://github.com/greenplum-db/gpdb/blob/6741bf9449dc5bd2999beb6111a082c5a91a32b6/gpMgmt/bin/gpinitsystem#L1424-L1426

But in `gpcreateseg.sh`, the `TRUSTED_SHELL` will be reset, so it always be the default value:
https://github.com/greenplum-db/gpdb/blob/6741bf9449dc5bd2999beb6111a082c5a91a32b6/gpMgmt/bin/lib/gpcreateseg.sh#L27-L33C3

**Comment by khuddlefish** [comment]
Hi @RMTT Can you tell us more about what you're hoping to do with the TRUSTED_SHELL value? I believe by our docs it only has one valid value (ssh) so it isn't really needed. We will probably want to clean up the variable in future versions since it isn't used. Is there some additional use you're hoping to get out of it?

**Comment by RMTT** [comment]
@khuddlefish  I found this variable when i use `make create-demo-cluster`  https://github.com/greenplum-db/gpdb/blob/ec9dbd18630f077f34e74c9685241b206bf8b050/gpAux/gpdemo/demo_cluster.sh#L320

But this variable not used in `gpinitsystem` actually, so i think it's a little bug, because according to the [doc](https://docs.vmware.com/en/VMware-Tanzu-Greenplum/7/greenplum-database/GUID-utility_guide-ref-gpinitsystem.html?hWord=N4IghgNiBcICoCUCqBlOBRAIgfRQCXQBlCQBfIA) , `gpinitsystem` should use `TRUSTED_SHELL` to run command.

> We will probably want to clean up the variable in future versions since it isn't used.

It's ok, but dont hardcode the path of `ssh` command.
