### ISSUE TITLE
gp_svec.so crashed in sdata_to_float8arr

### ISSUE THREAD

**Issue by hslightdb** [greenplum-db/gpdb#15206]
## Bug Report
gp_svec.so crashed in sdata_to_float8arr

#0  0x0000fffbf0863470 in raise () from /usr/lib64/libpthread.so.0
#1  0x0000000000f26f74 in StandardHandlerForSigillSigsegvSigbus_OnMainThread (processName=0x149ae08 "Segment process", postgres_signal_arg=11)
    at elog.c:5126
#2  0x0000000000d672e8 in CdbProgramErrorHandler (postgres_signal_arg=11) at postgres.c:3709
#3  <signal handler called>
#4  0x0000fffbe010cfb8 in sdata_to_float8arr (sdata=0xa6a16b0) at SparseData.c:249
#5  0x0000fffbe0104648 in svec_return_array_internal (svec=0xa6a16a8) at sparse_vector.c:49
#6  0x0000fffbe0104998 in svec_return_array (fcinfo=0xa6a0180) at sparse_vector.c:156
#7  0x0000000000aa791c in ExecInterpExpr (state=0xa6a0918, econtext=0xa69f4a0, isnull=0xffffd787a487) at execExprInterp.c:641
#8  0x0000000000aa977c in ExecInterpExprStillValid (state=0xa6a0918, econtext=0xa69f4a0, isNull=0xffffd787a487) at execExprInterp.c:1876
#9  0x0000000000af9e0c in ExecEvalExprSwitchContext (state=0xa6a0918, econtext=0xa69f4a0, isNull=0xffffd787a487)
    at ../../../src/include/executor/executor.h:362
#10 0x0000000000af9e70 in ExecProject (projInfo=0xa6a0910) at ../../../src/include/executor/executor.h:396
#11 0x0000000000afa120 in ExecResult (pstate=0xa69f390) at nodeResult.c:157
#12 0x0000000000abe314 in ExecProcNodeGPDB (node=0xa69f390) at execProcnode.c:623
#13 0x0000000000abe1d0 in ExecProcNodeFirst (node=0xa69f390) at execProcnode.c:584
#14 0x0000000000b126bc in ExecProcNode (node=0xa69f390) at ../../../src/include/executor/executor.h:271
#15 0x0000000000b12a08 in execMotionSender (node=0xa69f0a0) at nodeMotion.c:227
#16 0x0000000000b12988 in ExecMotion (pstate=0xa69f0a0) at nodeMotion.c:191
#17 0x0000000000abe314 in ExecProcNodeGPDB (node=0xa69f0a0) at execProcnode.c:623
#18 0x0000000000abe1d0 in ExecProcNodeFirst (node=0xa69f0a0) at execProcnode.c:584
#19 0x0000000000ab1e70 in ExecProcNode (node=0xa69f0a0) at ../../../src/include/executor/executor.h:271
#20 0x0000000000ab5928 in ExecutePlan (estate=0xa69ee60, planstate=0xa69f0a0, use_parallel_mode=false, operation=CMD_SELECT, sendTuples=false, 
    numberTuples=0, direction=ForwardScanDirection, dest=0xa67a660, execute_once=false) at execMain.c:2619
#21 0x0000000000ab2fe0 in standard_ExecutorRun (queryDesc=0xa699c70, direction=ForwardScanDirection, count=0, execute_once=false) at execMain.c:869
#22 0x0000000000ab2d34 in ExecutorRun (queryDesc=0xa699c70, direction=ForwardScanDirection, count=0, execute_once=false) at execMain.c:748
#23 0x0000000000d6cda8 in PortalRunSelect (portal=0xa620c10, forward=true, count=0, dest=0xa67a660) at pquery.c:1140
#24 0x0000000000d6c9fc in PortalRun (portal=0xa620c10, count=9223372036854775807, isTopLevel=true, run_once=false, dest=0xa67a660, 
    altdest=0xa67a660, completionTag=0xffffd787ab10 "") at pquery.c:978
#25 0x0000000000d6345c in exec_mpp_query (
    query_string=0xa5311de "SELECT a,b::float8[] cross_product_equals FROM (SELECT a,b FROM test) foo WHERE b = foo.b ORDER BY a;", 
    serializedPlantree=0xa531244 "(\265/\375`\305\003=\n", serializedPlantreelen=337, serializedQueryDispatchDesc=0xa531395 "(\265/\375`\032", 
    serializedQueryDispatchDesclen=142) at postgres.c:1438
#26 0x0000000000d6a408 in PostgresMain (argc=1, argv=0xa56b630, dbname=0xa55d580 "contrib_regression", 

(gdb) f 4
#4  0x0000fffbe010cfb8 in sdata_to_float8arr (sdata=0xa6a16b0) at SparseData.c:249
249				array[aptr] = ((double *)(sdata->vals->data))[i];
(gdb) p i, aptr, j, sdata->total_value_count, sdata->unique_value_count
$1 = 0
(gdb) p aptr
$2 = 8905
(gdb) p j
$3 = 8905
(gdb) p sdata->total_value_count
$4 = 0
(gdb) p sdata->unique_value_count
$5 = 0
(gdb) p sdata->vals->data
Cannot access memory at address 0x0
(gdb) p iptr
$6 = 0xa6a171c "\376"
(gdb) p array
$7 = (double *) 0xa690080

### Greenplum version or build
tag 7.0.0.beta.1

### OS version and uname -a
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/aarch64-linux-gnu/7.3.0/lto-wrapper
Target: aarch64-linux-gnu
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,fortran,lto --enable-plugin --enable-initfini-array --disable-libgcj --without-isl --without-cloog --enable-gnu-indirect-function --build=aarch64-linux-gnu --with-stage1-ldflags=' -Wl,-z,relro,-z,now' --with-boot-ldflags=' -Wl,-z,relro,-z,now' --with-multilib-list=lp64
Thread model: posix
gcc version 7.3.0 (GCC) 

Linux 4.19.90-24.4.v2101.ky10.aarch64 #1 SMP Mon May 24 14:45:37 CST 2021 aarch64 aarch64 aarch64 GNU/Linux

### Installation information ( pg_config )
CONFIGURE = '--prefix=/home/aaa/gp7bin' '--enable-debug' '--with-openssl' '--with-libxml' '--with-uuid=ossp' 'CFLAGS=-O0 -g' 'CXXFLAGS=-O0 -g'
CC = gcc
CPPFLAGS = -D_GNU_SOURCE -I/usr/include/libxml2
CFLAGS = -Wall -Wmissing-prototypes -Wpointer-arith -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-unused-but-set-variable -Werror=implicit-fallthrough=3 -Wno-format-truncation -g -O0 -g  -Werror=uninitialized -Werror=implicit-function-declaration
CFLAGS_SL = -fPIC
LDFLAGS = -Wl,--as-needed -Wl,-rpath,'/home/aaa/gp7bin/lib',--enable-new-dtags
LDFLAGS_EX = 
LDFLAGS_SL = 
LIBS = -lpgcommon -lpgport -lpthread -lxerces-c -lbz2 -lxml2 -lrt -lssl -lcrypto -lz -lreadline -lrt -lcrypt -ldl -lm  -lcurl -lzstd 
VERSION = PostgreSQL 12.12

### Step to reproduce the behavior
make create-demo-cluster
cd gpcontrib/gp_sparse_vector
make installcheck

**Comment by yaowangm** [comment]
@hslightdb I tried to repro but failed:
```
test gp_svec                      ... ok         2024 ms
test gp_svec_features             ... ok          552 ms

=====================
 All 2 tests passed.
=====================
```
I noticed your repro is on ARM64 (aarch64-linux-gnu) env, and my running is on x64 env. Is the repro available only on ARM64?

**Comment by yaowangm** [comment]
As discussed with Ashwin, I closed the PR since it seems the error only occurs on ARM64 and GPDB doesn't officially support ARM64. We can reopen this if reporter provides more details, but it's not urgent anyway.

**Comment by wxzkenny** [comment]
This problem also occurs on X86 and is more likely to occur on ARM
