### ISSUE TITLE
gpdb 6.23.1做truncate很慢

### ISSUE THREAD

**Issue by lhrbest** [greenplum-db/gpdb#15213]
我这边有个gpdb，6.23.1版本，
现象是做truncate操作很慢，对空表重复做truncate都需要2分钟的时间（肯定没有锁和阻塞的）
![finalize_1679038690873_958](https://user-images.githubusercontent.com/28920732/225845107-46c45728-3385-4b32-9c0d-1e77c92d6350.jpg)

**Comment by ashwinstar** [comment]
Just to understand full detail can you share cluster configuration (like how many segments in cluster, number of segments per host and such..)

**Comment by ashwinstar** [comment]
Not able to repro and no details, closing the issue.
