### ISSUE TITLE
Summary views for all gp_stat_progress_* views

### ISSUE THREAD

**Issue by l-wang** [greenplum-db/gpdb#15268]
## Feature Request

Create a summary view for each of the following system views:
- `gp_stat_progress_analyze`
- `gp_stat_progress_cluster` 
- `gp_stat_progress_create_index` 
- `gp_stat_progress_copy`,
- `gp_stat_progress_vacuum`
- `gp_stat_progress_basebackup`

Each summary view should group by database id, table id and phases. If table is partitioned, aggregate the values, if table is replicated, average the values over all segments. Refer to https://github.com/greenplum-db/gpdb/pull/15239 for definition of the `gp_stat_progress_*` views.

For each of the summary view, create an isolation2 test case, feel free to use gp_inject_fault.

**Comment by ashwinstar** [comment]
@l-wang is this completed?

**Comment by l-wang** [comment]
@ashwinstar Yes! This is completed by https://github.com/greenplum-db/gpdb/pull/15327
