### ISSUE TITLE
The value of InterruptHoldoffCount remains 1 after a statement finished.

### ISSUE THREAD

**Issue by zxuejing** [greenplum-db/gpdb#15278]
## Bug Report
this issue is reported by @lmzzzzz1  in pr https://github.com/greenplum-db/gpdb/pull/15203 
### Greenplum version or build
the latest main branch

### Expected behavior
drop table if exists t1;
create table t1(a int, b int);
insert into t1 values (-1,1);

BEGIN;
DECLARE c1 CURSOR FOR select count(*) from t1 group by sqrt(a);

ABORT;
ERROR:  cannot take square root of a negative number  (seg2 slice1 10.232.123.123:52433 pid=112402)

Use gdb attach pid of QD, the value of InterruptHoldoffCount should be 0.

### Actual behavior
Use gdb attach pid of QD, and p InterruptHoldoffCount, the value is 1, and this will affect the process of ProcessInterrupts later.

void
ProcessInterrupts(const char* filename, int lineno)
{
	/* OK to accept any interrupts now? */
	if (InterruptHoldoffCount != 0 || CritSectionCount != 0)
		**return**;
      ......
}
### Pg's behavior
PG does not have this issue. error occurs in fetch not abort.
postgres=# create table t1(a int, b int);
CREATE TABLE
postgres=# insert into t1 values (-1,1);
INSERT 0 1
postgres=# BEGIN;
BEGIN
postgres=# DECLARE c1 CURSOR FOR select count(*) from t1 group by sqrt(a);
DECLARE CURSOR

postgres=# fetch c1;
ERROR:  cannot take square root of a negative number
postgres=# abort;
ROLLBACK

**Comment by lmzzzzz1** [comment]
Hi @zxuejing 
I tried to fix this problem. Would resetting it to 0 at the end of the sigsetjmp code block solve this issue?

**Comment by zxuejing** [comment]
> Hi @zxuejing I tried to fix this problem. Would resetting it to 0 at the end of the sigsetjmp code block solve this issue?

Yes, resetting InterruptHoldoffCount to 0 can solve this issue.

If we throw an error by elog(ERROR,xxxx) the InterruptHoldoffCount will be set to 0.
however, in this issue, we got the error from segment, and do not use elog to throw error, we use ReThrowError in mppExecutorFinishup to throw the constructed error, So InterruptHoldoffCount does not set to 0.

ReThrowError is a method to rethrow an error we construct.
So I think we also should to set InterruptHoldoffCount to 0 in ReThrowError.

But I'm not sure it makes sense to change it this way.

**Comment by adam8157** [comment]
The main branch is fixed by https://github.com/greenplum-db/gpdb/pull/15279, @zxuejing will submit a PR for 6X.

**Comment by kainwen** [comment]
Fixed by:
* main branch: https://github.com/greenplum-db/gpdb/pull/15279
* 6x: https://github.com/greenplum-db/gpdb/pull/15412
