### ISSUE TITLE
wrong result of concurrent DML in partition table

### ISSUE THREAD

**Issue by charliettxx** [greenplum-db/gpdb#15289]
## Bug Report
wrong result of concurrent DML in partition table
### Greenplum version or build
only 7x master

### OS version and uname -a
centos7
### autoconf options used ( config.status --config )
optimizer = on
gp_enable_global_deadlock_detector = on

### Installation information ( pg_config )
gpconfig -c gp_enable_global_deadlock_detector -v on
gpconfig -c optimizer -v on
gpstop
gpstart

### Step to reproduce the behavior
create table part(a int, b int, c int) partition by range(b) (start (1) end (7) every (3));
insert into part values (1, 1, 1);

S1: Begin;
S1: Delete from part where b = 1;
S2: update part set b = 1;
S1: commit;

### Expected behavior
postgres=# select * from part;
 a | b | c 
---+---+---
(0 row)

we shoudn't see any result from table part, because all rows have been deleted by transaction S1

### Actual behavior
postgres=# select * from part;
 a | b | c 
---+---+---
 1 | 1 | 1
(1 row)

that is wrong result

**Comment by kainwen** [comment]
Will 6X has the issue? @charliettxx

**Comment by charliettxx** [comment]
> Will 6X has the issue? @charliettxx

nope, 6X don't have such issue, and it has raised error like this PR did.
