### ISSUE TITLE
Long text fields are truncated in logs gpdb-*.csv

### ISSUE THREAD

**Issue by matseevski** [greenplum-db/gpdb#15319]
### Greenplum version or build
PostgreSQL 9.4.26 (Greenplum Database 6.23.0 build dev) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609, 64-bit compiled on Dec 29 2022 14:20:54

### OS version and uname -a
Linux hostname 4.19.62-13 https://github.com/greenplum-db/gpdb/pull/1 SMP Mon Jul 29 17:22:59 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

### autoconf options used ( config.status --config )
./config.status --config
'--with-perl' '--with-python' '--without-gssapi' '--enable-gpcloud' '--with-libxml' '--with-system-tzdata=/usr/share/zoneinfo' '--prefix=/usr/local/gpdb' '--enable-ic-proxy' '--enable-gpperfmon' 'LDFLAGS=-L/usr/lib/jni/' '--with-pam' '--with-openssl'

### Installation information ( pg_config )
BINDIR = /usr/local/gpdb/bin
DOCDIR = /usr/local/gpdb/share/doc/postgresql
HTMLDIR = /usr/local/gpdb/share/doc/postgresql
INCLUDEDIR = /usr/local/gpdb/include
PKGINCLUDEDIR = /usr/local/gpdb/include/postgresql
INCLUDEDIR-SERVER = /usr/local/gpdb/include/postgresql/server
LIBDIR = /usr/local/gpdb/lib/x86_64-linux-gnu
PKGLIBDIR = /usr/local/gpdb/lib/x86_64-linux-gnu/postgresql
LOCALEDIR = /usr/local/gpdb/share/locale
MANDIR = /usr/local/gpdb/share/man
SHAREDIR = /usr/local/gpdb/share/postgresql
SYSCONFDIR = /etc/postgresql
PGXS = /usr/local/gpdb/lib/x86_64-linux-gnu/postgresql/pgxs/src/makefiles/pgxs.mk
CONFIGURE = '--build=x86_64-linux-gnu' '--prefix=/usr' '--includedir=/usr/local/gpdb/include' '--mandir=/usr/local/gpdb/share/man' '--infodir=/usr/local/gpdb/share/info' '--sysconfdir=/etc' '--localstatedir=/var' '--disable-silent-rules' '--libdir=/usr/local/gpdb/lib/x86_64-linux-gnu' '--libexecdir=/usr/local/gpdb/lib/x86_64-linux-gnu' '--disable-maintainer-mode' '--disable-dependency-tracking' '--with-perl' '--with-python' '--without-gssapi' '--disable-gpcloud' '--with-libxml' '--with-system-tzdata=/usr/share/zoneinfo' '--prefix=/usr/local/gpdb' '--enable-ic-proxy' '--enable-gpperfmon' 'LDFLAGS=-L/usr/lib/jni/' '--with-pam' '--with-openssl' 'build_alias=x86_64-linux-gnu' 'CFLAGS=-g -O2 -fstack-protector-strong -Wformat -Werror=format-security' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'CXXFLAGS=-g -O2 -fstack-protector-strong -Wformat -Werror=format-security'
CC = gcc
CPPFLAGS = -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2 -I/usr/local/gpdb/include
CFLAGS = -Wall -Wmissing-prototypes -Wpointer-arith -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fno-aggressive-loop-optimizations -Wno-unused-but-set-variable -Wno-address -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -std=gnu99 -Werror=uninitialized -Werror=implicit-function-declaration -I/usr/local/gpdb/include
CFLAGS_SL = -fPIC
LDFLAGS = -L/usr/lib/jni/ -Wl,--as-needed -Wl,-rpath,'/usr/local/gpdb/lib/x86_64-linux-gnu',--enable-new-dtags -L/usr/local/gpdb/lib/x86_64-linux-gnu
LDFLAGS_EX =
LDFLAGS_SL =
LIBS = -lpgcommon -lpgport -lxerces-c -lxml2 -lpam -lrt -luv -lzstd -lrt -lcrypt -ldl -lm -L/usr/local/gpdb/lib/x86_64-linux-gnu
VERSION = PostgreSQL 9.4.26

### Expected behavior
very long text fields are not truncated in logs (gpdb-*.csv)
or
you can adjust max text field length for logs

### Actual behavior
very long text fields (>81000 chars) are truncated in logs

### Step to reproduce the behavior
Turn on statement logging or auto_explain and run long query text (>81000 chars)

**Comment by hyongtao-db** [comment]
This bug is fixed by #11946  in GPDB-7X, but still lacks a test case. 
I added one test case in #16669 

 I totally believe that cherry-picking #11946 and #16669 and backporting them to GPDB-6X, the bug in 6X will be fixed.

**Comment by hyongtao-db** [comment]
Check the behavior of very long log in PG12.12. PG12.12 never do any truncation when writing log. It is diff from GPDB.

**Comment by hyongtao-db** [comment]
PR #16674 is merged into 6X. I think GPDB will keep its own log behavior. 
Close this issue now. Please feel free to reopen it.
