### ISSUE TITLE
[6X] TRUNCATE AO/CO table created in the same transaction doesn't remove its extended datafiles

### ISSUE THREAD

**Issue by huansong** [greenplum-db/gpdb#15342]
## Bug Report

TRUNCATE an AO/CO table should remove all the extended (segment) datafiles of the table. But in 6X if the table is created and truncated in the same transaction, those datafiles are not removed. Basically they are left being orphaned until the datafiles are overwritten by new INSERTs into the table, or the table is dropped as a whole (which would remove all datafiles including both non-extended and extended ones).

For example on a demo cluster:
```sql
postgres=# begin;
BEGIN
postgres=# create table ao(a int) with(appendonly);
NOTICE:  Table doesn't have 'DISTRIBUTED BY' clause -- Using column named 'a' as the Greenplum Database data distribution key for this table.
HINT:  The 'DISTRIBUTED BY' clause determines the distribution of data. Make sure column(s) chosen are the optimal data distribution key to minimize skew.
CREATE TABLE
postgres=# insert into ao select * from generate_series(1,10);
INSERT 0 10
postgres=# truncate ao;
TRUNCATE TABLE
postgres=# end;
COMMIT
postgres=# select gp_segment_id,relfilenode from gp_dist_random('pg_class') where gp_segment_id = 0 and relname = 'ao';
 gp_segment_id | relfilenode
---------------+-------------
             0 |       65583
(1 row)

postgres=# \! find . -name "65583*" 
./gpAux/gpdemo/datadirs/dbfast_mirror1/demoDataDir0/base/12847/65583.1
./gpAux/gpdemo/datadirs/dbfast_mirror1/demoDataDir0/base/12847/65583
./gpAux/gpdemo/datadirs/dbfast1/demoDataDir0/base/12847/65583.1
./gpAux/gpdemo/datadirs/dbfast1/demoDataDir0/base/12847/65583

-- The aoseg table is correctly truncated though
postgres=# select gp_toolkit.__gp_aoseg('ao') from gp_dist_random('gp_id') where gp_segment_id = 0;
 __gp_aoseg
------------
(0 rows)
``` 

On a 7X cluster, those datafiles are remove in such case, just like what TRUCNATE the table in a standalone transaction would do.

### Greenplum version or build
`6X_STABLE`. Head 8cde4629095725d6a368b47eaa6e6a484e5b5c8e.

### OS version and uname -a
Linux station1 5.0.0-38-generic #41-Ubuntu SMP Tue Dec 3 00:27:35 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

### Installation information ( pg_config )
./configure --prefix=/usr/local/gpdb6 --disable-gpcloud --with-python --enable-orca --enable-debug --enable-depend --enable-tap-tests --enable-ic-proxy CFLAGS=-O0 -fno-omit-frame-pointer -Wduplicated-cond -Wduplicated-branches --no-create --no-recursion

**Comment by huansong** [comment]
Actually... it seems expected that the files are not removed in this case. Heap tables have the same behavior: those datafiles will just be truncated to size zero. This behavior is consistent among GPDB6 and 7.

Now it seems that it is 7X's AO/CO table that have different behavior: the AO table created and inserted by the same transaction will not have extended files being created at all. The data are written to the non-extended datafile, so of course TRUNCATE won't do anything to non-existed extended datafiles.

Since there's no buggy behavior so far, removing the bug label for now.

**Comment by ashwinstar** [comment]
Yes, the code has choice when it can perform safe truncation (new relfilenodes and swap) and unsafe truncation (directly truncate the existing files) based on if truncate can be rolled back or not (transactional). So, within same transaction as create it uses unsafe truncation method as you traced out.

**Comment by huansong** [comment]
Thanks for the explanation @ashwinstar ! I'm closing the issue as it's a non-issue.
