### ISSUE TITLE
Performance Optimization for Counting in Greenplum

### ISSUE THREAD

**Issue by z17033** [greenplum-db/gpdb#15347]
## Enhancement
Recently, a business is Using Greenplum and Vertica for performance comparison and found that there is a significant difference in performance between the two when calculating the count process.
After consulting with a Vertica engineer, it was found that Vertica has special optimizations when calculating counts.

In Vertica, because column storage is compressed , and statistical information is counted in each block, it does not need to scan every row when executing count. It only needs to add up the non-empty count of each block, making it faster.

**Comment by wuyuhao28** [comment]
Using Greenplum AOCS table may help improve some performance, but not much.
Because of the lack of columnar table support and limitations in its execution model, I think it's a bit hard to optimize count like Vertica in PostgreSQL, but in Greenplum we may make it by add new type of Node or Expr.

**Comment by ashwinstar** [comment]
Doable yes. Should do - maybe. Yes, one may win POCs by faking performance this way. Real workloads and benchmarks don't generally do just count(*) so mileage varies.
Some thoughts on this topic are captured here https://github.com/greenplum-db/gpdb/issues/12719

**Comment by ashwinstar** [comment]
Closing this as already being discussed in referenced issue.
