### ISSUE TITLE
How many fields can a Greenplum table support at most

### ISSUE THREAD

**Issue by jiangzhaohong** [greenplum-db/gpdb#15409]
Hello, may I ask：
How many fields can a Greenplum table (Row table and Column table) support at most?

thank you!

**Comment by ashwinstar** [comment]
Same as heap, 1600 max columns for a table.
What number requirement do you have?

(also for purely questions can use gpdb-dev@greenplum.org or gpdb-users@greenplum.org mailing-lists instead)

**Comment by jiangzhaohong** [comment]
> Same as heap, 1600 max columns for a table. What number requirement do you have?
> 
> (also for purely questions can use [gpdb-dev@greenplum.org](mailto:gpdb-dev@greenplum.org) or [gpdb-users@greenplum.org](mailto:gpdb-users@greenplum.org) mailing-lists instead)

Thank you for your answer！
We need to design a table to store patient clinical events, which may require several thousand fields, with more than 1600 fields.
Is there any way to increase this limit or other suggestions.Thanks!

**Comment by ashwinstar** [comment]
No way to remove this limit. Possibly create multiple tables with some common unique identifier column to join together them.
