### ISSUE TITLE
Strange behaviour of parser during SQL clause evaluation with grouping() function.

### ISSUE THREAD

**Issue by sokolval** [greenplum-db/gpdb#15416]
### Greenplum version or build
PostgreSQL 9.4.26 (Greenplum Database 6.24.1 build dev0) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609, 64-bit compiled on Apr 20 2023 14:52:43
### OS version and uname -a
Linux hostname 4.19.62-13 https://github.com/greenplum-db/gpdb/pull/1 SMP Mon Jul 29 17:22:59 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
### autoconf options used ( config.status --config )
./config.status --config
'--with-perl' '--with-python' '--without-gssapi' '--enable-gpcloud' '--with-libxml' '--with-system-tzdata=/usr/share/zoneinfo' '--prefix=/usr/local/gpdb' '--enable-ic-proxy' '--enable-gpperfmon' 'LDFLAGS=-L/usr/lib/jni/' '--with-pam' '--with-openssl'
### Installation information ( pg_config )
BINDIR = /usr/local/gpdb/bin
DOCDIR = /usr/local/gpdb/share/doc/postgresql
HTMLDIR = /usr/local/gpdb/share/doc/postgresql
INCLUDEDIR = /usr/local/gpdb/include
PKGINCLUDEDIR = /usr/local/gpdb/include/postgresql
INCLUDEDIR-SERVER = /usr/local/gpdb/include/postgresql/server
LIBDIR = /usr/local/gpdb/lib/x86_64-linux-gnu
PKGLIBDIR = /usr/local/gpdb/lib/x86_64-linux-gnu/postgresql
LOCALEDIR = /usr/local/gpdb/share/locale
MANDIR = /usr/local/gpdb/share/man
SHAREDIR = /usr/local/gpdb/share/postgresql
SYSCONFDIR = /etc/postgresql
PGXS = /usr/local/gpdb/lib/x86_64-linux-gnu/postgresql/pgxs/src/makefiles/pgxs.mk
CONFIGURE = '--build=x86_64-linux-gnu' '--prefix=/usr' '--includedir=/usr/local/gpdb/include' '--mandir=/usr/local/gpdb/share/man' '--infodir=/usr/local/gpdb/share/info' '--sysconfdir=/etc' '--localstatedir=/var' '--disable-silent-rules' '--libdir=/usr/local/gpdb/lib/x86_64-linux-gnu' '--libexecdir=/usr/local/gpdb/lib/x86_64-linux-gnu' '--disable-maintainer-mode' '--disable-dependency-tracking' '--with-perl' '--with-python' '--without-gssapi' '--disable-gpcloud' '--with-libxml' '--with-system-tzdata=/usr/share/zoneinfo' '--prefix=/usr/local/gpdb' '--enable-ic-proxy' '--enable-gpperfmon' 'LDFLAGS=-L/usr/lib/jni/' '--with-pam' '--with-openssl' 'build_alias=x86_64-linux-gnu' 'CFLAGS=-g -O2 -fstack-protector-strong -Wformat -Werror=format-security' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'CXXFLAGS=-g -O2 -fstack-protector-strong -Wformat -Werror=format-security'
CC = gcc
CPPFLAGS = -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2 -I/usr/local/gpdb/include
CFLAGS = -Wall -Wmissing-prototypes -Wpointer-arith -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fno-aggressive-loop-optimizations -Wno-unused-but-set-variable -Wno-address -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -std=gnu99 -Werror=uninitialized -Werror=implicit-function-declaration -I/usr/local/gpdb/include
CFLAGS_SL = -fPIC
LDFLAGS = -L/usr/lib/jni/ -Wl,--as-needed -Wl,-rpath,'/usr/local/gpdb/lib/x86_64-linux-gnu',--enable-new-dtags -L/usr/local/gpdb/lib/x86_64-linux-gnu
LDFLAGS_EX = 
LDFLAGS_SL = 
LIBS = -lpgcommon -lpgport -lxerces-c -lxml2 -lpam -lrt -luv -lzstd -lrt -lcrypt -ldl -lm -L/usr/local/gpdb/lib/x86_64-linux-gnu
VERSION = PostgreSQL 9.4.26

### Expected behavior
Execution result returned or error reported

test1=# select count(*), grouping(s) from t3;
ERROR:  column "s" does not exist
LINE 1: select count(*), grouping(s) from t3;
                                  ^
test1 =# select count(*), grouping(b) from t3;
ERROR:  column "t3"."b" is not in GROUP BY
test1 =# select count(*), grouping(b) from t3 group by b;
 count | grouping 
-------+----------
(0 rows)

test1 =# select count(*), grouping(a) from t3 group by b;
ERROR:  column "t3"."a" is not in GROUP BY

### Actual behavior
I get error message ERROR:  unrecognized node type: 925 (nodeFuncs.c:3588)
### Step to reproduce the behavior
create table t3 (a int, b text) distributed randomly;
CREATE TABLE
test1=# select count(*), grouping(s) from t3;
ERROR:  unrecognized node type: 925 (nodeFuncs.c:3588)
test1=# select count(*), grouping(b) from t3;
ERROR:  unrecognized node type: 925 (nodeFuncs.c:3588)

The error is strangely reproduced when connecting by psql or DataGrip on one exact cluster.
It is not reproduced on another one.
I have lack of ideas where and what at to look.
Appreciate on any idea how this could be addressed.

**Comment by sokolval** [comment]
I suspect this is somehow limited to exact cluster, but absolutely do not understand how to reproduce properly.
It could be working fine on any other environment I guess.

**Comment by sokolval** [comment]
I was able to reproduce this case on a small vm with just 2 segments.
So the symptoms are visible when version is 6.24.1 and everything works well on 6.23.0
I mean I created a table create table t4 (a int, b text) distributed randomly; on 6.23.0 and upgraded binaries to 6.24.1 and got an error ERROR: unrecognized node type: 925 (nodeFuncs.c:3588)
Then I downgraded cluster binaries version back to 6.23  - and query worked fine:
`a1=# select count(), grouping(b) from t4 group by (b);
 count | grouping 
-------+----------
(0 rows)

a1=# select count(), grouping(b) from t3 group by (b);
 count | grouping 
-------+----------
(0 rows)

a1=# \q`

Then I upgraded to 6.24.1 again and the issue is happening.
`a1=# select version();
                                                                                           version                                                                                            
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 PostgreSQL 9.4.26 (Greenplum Database 6.24.1 build dev0) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609, 64-bit compiled on Apr 20 2023 14:52:43
(1 row)

a1=# select count(), grouping(s) from t3;
ERROR:  unrecognized node type: 925 (nodeFuncs.c:3588)
`

**Comment by kainwen** [comment]
I do not reproduce the issue locally with your upgrade method.

Can you:

1. share LOGS to see if there is any stack trace?
2. can you use GDB to attach to the QD (forked by coordinator), and break  at `nodeFuncs.c:358`, and continue, and run the SQL (throw note type 925 error), and show the backtrace and then generator a core to share here

**Comment by kainwen** [comment]
I have reproduced this issue, it is introduced by 7d741e5d93948d15b6212eb3f2937e92ca5dc62a
and reproduced under resgroup.

The new feature is to bypass catalog query, and it will walk the raw_express_tree using the util function `raw_expression_tree_walker` (postgres provided), and there are some node type Greenplum does not include.

**Comment by sokolval** [comment]
Here is the stacktrace if it helps:
2023-04-25 10:34:21.286089 MSK,"u1","a1",p976799,th-632694976,"[local]",,2023-04-25 10:34:18 MSK,0,con21,cmd1,seg-1,,,,sx1,"ERROR","XX000","unrecognized node type: 925 (nodeFuncs.c:3588)",,,,,,"select count(), grouping(b) from t3 group by (b);",0,,"nodeFuncs.c",3588,"Stack trace:
1    0xaf9ea8 postgres errstart + 0x248
2    0xafca60 postgres elog_finish + 0xd0
3    0x8f01bf postgres raw_expression_tree_walker + 0x13f
4    0x8f02d9 postgres raw_expression_tree_walker + 0x259
5    0x8f03ca postgres raw_expression_tree_walker + 0x34a
6    0x8f067d postgres raw_expression_tree_walker + 0x5fd
7    0xb2d3d7 postgres AssignResGroupOnMaster + 0x267
8    0x72695d postgres StartTransactionCommand + 0x6dd
9    0x9eea1d postgres <symbol not found> + 0x9eea1d
10   0x9f16cf postgres <symbol not found> + 0x9f16cf
11   0x9f4f24 postgres PostgresMain + 0x1cf4
12   0x6b6cce postgres <symbol not found> + 0x6b6cce
13   0x990059 postgres PostmasterMain + 0x1089
14   0x6b982b postgres main + 0x42b
15   0x7fe7d7324840 libc.so.6 __libc_start_main + 0xf0
16   0x6c5749 postgres _start + 0x29
"

Indeed the issue gets reproduced with Resource group management, while with resource queue the query works fine. Switching between resgroup and resqueue makes issue appear when running on reagroup.

**Comment by ashwinstar** [comment]
Thanks a lot @sokolval for reporting this issue. We will fix it next 6X_STABLE release.

**Comment by kainwen** [comment]
A PR is opened to fix this issue https://github.com/greenplum-db/gpdb/pull/15441
I find 3 other node tags. See test and commit message of the PR.

**Comment by kainwen** [comment]
Fixed by https://github.com/greenplum-db/gpdb/pull/15441 on 6X.
Main branch does not have this exact same issue. But we will later investigate the same problem-pattern for main branch.
