### ISSUE TITLE
ERROR:  no pre-assigned OID for relation "output"

### ISSUE THREAD

**Issue by asubramanya** [greenplum-db/gpdb#1543]
```
gptest=# create table input(x int); 
NOTICE:  Table doesn't have 'DISTRIBUTED BY' clause -- Using column named 'x' as the Greenplum Database data distribution key for this table.
HINT:  The 'DISTRIBUTED BY' clause determines the distribution of data. Make sure column(s) chosen are the optimal data distribution key to minimize skew.
CREATE TABLE
gptest=# insert into input select * from generate_series(1, 10);
INSERT 0 10
gptest=# CREATE OR REPLACE FUNCTION inputArray() RETURNS INT[] AS $$
DECLARE theArray INT[];
BEGIN
   SELECT array(SELECT * FROM input ORDER BY x) INTO theArray;
   RETURN theArray;
EXCEPTION WHEN OTHERS THEN RAISE NOTICE 'Catching the exception ...%', SQLERRM;
END;
$$ LANGUAGE plpgsql;
CREATE FUNCTION
gptest=# create table output as select inputArray()::int[] as x;
NOTICE:  Table doesn't have 'DISTRIBUTED BY' clause -- Using column(s) named 'x' as the Greenplum Database data distribution key for this table.
HINT:  The 'DISTRIBUTED BY' clause determines the distribution of data. Make sure column(s) chosen are the optimal data distribution key to minimize skew.
ERROR:  no pre-assigned OID for relation "output" (oid_dispatch.c:580)  (seg1 127.0.0.1:25433 pid=71448)
```

It seems like there are two dispatches involving the above query. The first is for executing the function inputArray(). The second one dispatches the main plan for creating the table. In the first dispatch `GetAssignedOidsForDispatch()` function copies the list of assigned oids to dispatch to segments and sets the `dispatch_oids` list to null. This list contains the oid assigned for `output`. The second dispatch which tries to create the `output` table on the segments again calls `GetAssignedOidsForDispatch()` function. But since the `dispatch_oids` list is set to null, the list of oids dispatched to the segments is empty and the segments are not able to find the oid for the relation.

@hlinnaka  This seems related to oid dispatch patch. Can you please take a look?

**Comment by vraghavan78** [comment]
Assigning it to @yydzero to triage

**Comment by asubramanya** [comment]
Assigning to @hlinnaka since it looks related to f9016da2a65a27c6e80be9bfec80861787b52a85

**Comment by hlinnaka** [comment]
Pushed a fix, thanks for the report!
