### ISSUE TITLE
Unable to completely drop attributes

### ISSUE THREAD

**Issue by Gogogofyl** [greenplum-db/gpdb#15459]
## Bug Report
Create a new table with 1600 attributes, and the maximum number of columns has been reached. But after droping a few attributes, I was unable to add new ones. In fact, the deleted attribute still occupies this position and has not been truly deleted.

`
Create a table with 1600 fields (reaching the upper limit), then drop several fields and create new ones, but the addition failed.

test=# alter table t1 add column co1599 int;
ALTER TABLE
test=# alter table t1 add column co1600 int;
ALTER TABLE
test=# alter table t1 add column co1601 int;
psql: ERROR:  table can have at most 1600 columns

then, I drop column co1600 and add it again, failed:

test=# alter table t1 drop column co1600;
ALTER TABLE
test=# alter table t1 add column co1600 int;
psql: ERROR:  table can have at most 1600 columns

then, I drop column co1600 again:

test=# alter table t1 drop column co1600;
psql: ERROR: column "co1600" of relation "t1" dose not exist
`

**Comment by ashwinstar** [comment]
Dropped columns are not removed from catalog. That's the behavior we inherit from upstream and avoids rewrite of table during drop column. So, no plans for now to modify the behavior. Understand it can be annoying. We are considering enhancing the behavior for Columnar tables to such reuse of dropped column for newly added columns. For now, closing the issue.
