### ISSUE TITLE
numeric column returns incorrect results and garbled characters

### ISSUE THREAD

**Issue by A2uuuu** [greenplum-db/gpdb#15478]
## Bug Report
I have many SQL statements that continuously perform calculations on numeric columns, store them in temporary tables, and then perform the next step of calculations. At some point during this process, the calculation of a numeric column returns incorrect results and garbled characters, and an error message is displayed.

In the following example, I have simplified the SQL statement, but in reality, it is more complex. I have found that if I retain the precision of numeric columns, for example, by retaining 10 decimal places, the calculation results are correct and I do not get garbled characters.

### Greenplum version or build
PostgreSQL 9.4.24 (Greenplum Database 6.12.1 build commit:7ec4678f29dd922d7d44501f5fc344b5d0d4d49f Open Source) on x86_64-unknown-linux-gnu, compiled by gcc (GCC) 6.4.0, 64-bit compiled on Nov 20 2020 18:43:31

### OS version and uname -a
Linux 3.10.0-1160.31.1.el7.86_64 #1 SMP Thu Jun 10 13:32:12 UTC 2021 x86_64 ×86_64 ×86_64 GNU/Linux

### Expected behavior
When I retain precision
![截屏2023-05-05 15 23 49无水印](https://user-images.githubusercontent.com/57938012/236399327-ea087e3d-128e-4788-aa6a-f1c418631f57.png)

### Actual behavior
When I execute normally
![截屏2023-05-05 15 28 28无水印](https://user-images.githubusercontent.com/57938012/236401045-6a1bccc8-51aa-48ad-b30b-9e0e098d5218.png)
![截屏2023-05-05 15 29 05无水印](https://user-images.githubusercontent.com/57938012/236401061-12d4f9f1-9472-45a9-a2a7-d622f1f18a02.png)

### Step to reproduce the behavior
I have not encountered this issue in simple SQL statements. It only occurs in a specific scenario, where a long and complex SQL calculation is required to reproduce it. I apologize that I am unable to provide the tables and SQL statements required to reproduce the issue.

**Comment by kainwen** [comment]
I see the version is 6.12 which is a quite old version. Although I do not have any memory on which commit we fixed such things, I recommend you to upgrade to recent 6X version and see if the error is still there or not.

**Comment by A2uuuu** [comment]
> I see the version is 6.12 which is a quite old version. Although I do not have any memory on which commit we fixed such things, I recommend you to upgrade to recent 6X version and see if the error is still there or not.

Due to the impact on multiple projects in a production environment, I have temporarily avoided this issue by retaining precision. Anyway, thank you for your answer.

**Comment by ashwinstar** [comment]
Closing the issue for now based on @kainwen comment. If issue is encountered on recent version please feel free to open issue for us to investigate. Thanks.
