### ISSUE TITLE
Mixed aggregation shoule be memory intensive opearator

### ISSUE THREAD

**Issue by rainmaple** [greenplum-db/gpdb#15485]
## Enhancement
7.0 branch is tracing pg12, in which many of the AGGs' new features are introduced. `Mixed Agg` strategy is one of the new type which may appear in `hash+sort` agg or `hash+plain` agg. Due to `Mixed Agg` strongly binding to HashAgg, so this operator should be memory intensive.

**Comment by rainmaple** [comment]
I have fixed this in pull request https://github.com/greenplum-db/gpdb/pull/15486

**Comment by kainwen** [comment]
Fixed by https://github.com/greenplum-db/gpdb/pull/15486
Thanks @rainmaple for your contribution!
