### ISSUE TITLE
Does GreenPlum support columnar store with geometry type data?

### ISSUE THREAD

**Issue by flyly0755** [greenplum-db/gpdb#15488]
## Enhancement
Just want to make sure GreenPlum whether support columnar store with geometry type data?
I have take a try with competitor product: OpenGauss which doesn't support columnar store with geometry type data with error info:
**ERROR: type "geometry" is not supported in column store**
Coz GreenPlum and OpenGauss both depend on postgres and postgis, so maybe GreenPlum also  doesn't support columnar store with geometry type data.

**Comment by ashwinstar** [comment]
Greenplum has no such limitation based on data type. If column can be created with a data type - Greenplum's column store can be used for it.

**Comment by kainwen** [comment]
Close this since there is nothing to do for Greenplum. We already support it.
