### ISSUE TITLE
gpstop issue, "Sending SIGQUIT signal" error

### ISSUE THREAD

**Issue by qqcvd** [greenplum-db/gpdb#1551]
Hello,
I have a gpstop issue : 
When I stop greenplum cluster I get the following messages:
20170113:17:09:06:013242 gpstop:gp-master01:gpadmin-[INFO]:-Failed to shutdown master with pg_ctl.
20170113:17:09:06:013242 gpstop:gp-master01:gpadmin-[INFO]:-Sending SIGQUIT signal...
(you can see the full log in the attached file)

I tested it after removing the standby master (gpinitstandby -r) and the error diseappear.
If I recreate the standby master with gpinitstandby , the problem come back.

Do you have any idea about my problem?

Regards
[gpstop_20170113.zip](https://github.com/greenplum-db/gpdb/files/704859/gpstop_20170113.zip)

**Comment by ashwinstar** [comment]
Thank you for reporting the issue @qqcvd. Yes, @jimmy recently committed a fix 5f2688acc6aff4813f6eefe17b5e77abd441fa3b for the same to fix `gpstop -M fast` which is what you are running. Try with latest code and lets us know if that resolves issue for you.

Just FYI.. there still remains similar issue with `-M Smart` which will be fixed soon as well.

**Comment by ivannovick** [comment]
please let us know if recent code is not working

**Comment by qqcvd** [comment]
Thank you for yours answers. We will test it next week.
Thanks a lot.
Regards.

**Comment by qqcvd** [comment]
It works.
Thank you.
Regards.
