### ISSUE TITLE
ALTER TABLE SET DISTRIBUTED BY could create inconsistent toast table names

### ISSUE THREAD

**Issue by huansong** [greenplum-db/gpdb#15534]
### Greenplum version or build
main branch, HEAD 5de7ba5ce8df1c2f03a10fa9f602abf9933555df

### Expected behavior
A table's toast table should have a name such as `pg_toast_<tableoid>`. The `<tableoid>` should be the OID of the main table, and it shouldn't change during table rewrite, since the main table's OID won't change during table rewrite.

### Actual behavior
`ALTER TABLE DISTRIBUTED BY` would change the name of the toast table. It's probably being changed to have the table OID of the temporary table that's created during a table rewrite.

This inconsistency won't cause immediate impact, but could have a problem when the OID wraps around: we could be creating a table with a table OID same as the temporary table mentioned before, which doesn't exist anymore (since it doesn't exist, we can pick up the same OID). And, if the new table needs a toast table, we would be creating a toast table with the same name as the one that still exists, resulting in errors like : 
```
ERROR:  relation "pg_toast_32794" already exists
```

Found this in some CI flakiness where the exact above scenario happened, around the regress test `oid_wraparound` which manually makes OID wrapped around.

### Step to reproduce the behavior
Let's see three cases:
1. Bad case: `ALTER TABLE SET DISTRIBUTED BY`:
```sql
postgres=# create table t1(a text, b int);
CREATE TABLE
postgres=# alter table t1 set distributed by (b);
ALTER TABLE
postgres=# select oid,relname,reltoastrelid,reltoastrelid::regclass from pg_class where relname = 't1';
  oid  | relname | reltoastrelid |      reltoastrelid
-------+---------+---------------+-------------------------
 16384 | t1      |         16393 | pg_toast.pg_toast_16390
(1 row)
```
The toast table name has 16390 instead of 16384.

2. Good case: `ALTER TABLE SET LOGGED|UNLOGGED`:
```sql
postgres=# create table t2(a text, b int);
CREATE TABLE
postgres=# alter table t2 set logged;
ALTER TABLE
postgres=# alter table t2 set unlogged;
ALTER TABLE
postgres=# select oid,relname,reltoastrelid,reltoastrelid::regclass from pg_class where relname = 't2';
  oid  | relname | reltoastrelid |      reltoastrelid
-------+---------+---------------+-------------------------
 16396 | t2      |         16405 | pg_toast.pg_toast_16396
(1 row)
```
The toast table name is unchanged.

3. Good case: `ALTER TABLE SET ACCESS METHOD`:
```sql
postgres=# create table t3(a text, b int);
CREATE TABLE
postgres=# alter table t3 set access method ao_row;
ALTER TABLE
postgres=# alter table t3 set access method heap;
ALTER TABLE
postgres=# select oid,relname,reltoastrelid,reltoastrelid::regclass from pg_class where relname = 't3';
  oid  | relname | reltoastrelid |      reltoastrelid
-------+---------+---------------+-------------------------
 16408 | t3      |         16427 | pg_toast.pg_toast_16408
(1 row)
```
The toast table name is unchanged.

**Comment by gtygo** [comment]
It seems that the issue is caused by the lack of logical exchange between `tmp relid` and `tar relid` during the execution of alter table distributed xxx.

**Comment by huansong** [comment]
Fixed by #15580

**Comment by huansong** [comment]
Reopen due to #16657 . Need alternative approach.

**Comment by matt-song** [comment]
working with @interma on another issue and finding this one. we reproduced the issue on 7.0 via below command:
```
drop table if exists test_toast;
create table test_toast (id int,  message text );
insert into test_toast select id, repeat( 'a',  1000 * 1024 )  from generate_series(1,10) id;
select oid,relname,reltoastrelid,reltoastrelid::regclass from pg_class where relname = 'test_toast';
alter table test_toast set distributed by (message);
select * from test_toast ;

ERROR:  could not open relation with OID 18310  (seg0 slice1 10.216.2.11:20000 pid=1832895)
DETAIL:  This can be validly caused by a concurrent delete operation on this object.
```
confirmed can not reproduce on 7.1. adding this comment just for reference in the future for those who have similar error :)
