### ISSUE TITLE
pg.InternalError: missing "=" after "with\\\\quotes'" in connection info string

### ISSUE THREAD

**Issue by avamingli** [greenplum-db/gpdb#15542]
### Greenplum version or build

7x main branch

### Actual behavior

```diff
diff -I HINT: -I CONTEXT: -I GP_IGNORE: -U3 /home/gpadmin/work/gp7/src/test/regress/expected/gpcopy.out /home/gpadmin/work/gp7/src/test/regress/results/gpcopy.out
--- /home/gpadmin/work/gp7/src/test/regress/expected/gpcopy.out	2023-05-14 21:02:15.874289031 +0800
+++ /home/gpadmin/work/gp7/src/test/regress/results/gpcopy.out	2023-05-14 21:02:15.914288710 +0800
@@ -1627,6 +1664,17 @@
 reset client_min_messages;
 CREATE DATABASE "funny copy""db'with\\quotes";
 \! python3 test_dbconn.py 1
+Traceback (most recent call last):
+  File "/home/gpadmin/work/gp7/src/test/regress/test_dbconn.py", line 30, in <module>
+    test_connect_special_dbname(dbname)
+  File "/home/gpadmin/work/gp7/src/test/regress/test_dbconn.py", line 22, in test_connect_special_dbname
+    conn = dbconn.connect(url)
+  File "/home/gpadmin/install/gp7/lib/python/gppylib/db/dbconn.py", line 263, in connect
+    connection = pgdb.connect(**conninfo)
+  File "/usr/lib/python3/dist-packages/pgdb.py", line 1670, in connect
+    cnx = _connect(dbname, dbhost, dbport, dbopt, dbuser, dbpasswd)
+pg.InternalError: missing "=" after "with\\\\quotes'" in connection info string
+
 \c "funny copy""db'with\\quotes"
 -- echo will behave differently on different platforms, force to use bash with -E option
 COPY (SELECT 'data1') TO PROGRAM 'cat > /tmp/gpcopyenvtest; /usr/bin/env bash -c ''echo -E database in COPY TO: $GP_DATABASE >> /tmp/gpcopyenvtest '' ' ESCAPE 'OFF';
```

### Step to reproduce the behavior

run regression gpcopy case.

**Comment by kainwen** [comment]
Same as https://github.com/PyGreSQL/PyGreSQL/issues/77 ?

**Comment by avamingli** [comment]
> Same as [PyGreSQL/PyGreSQL#77](https://github.com/PyGreSQL/PyGreSQL/issues/77) ?

Will have a try later.

**Comment by avamingli** [comment]
> > Same as [PyGreSQL/PyGreSQL#77](https://github.com/PyGreSQL/PyGreSQL/issues/77) ?
> 
> Will have a try later.

@kainwen Hi, I spend some time on this. And it reproduces every time. 
This case is introduced by a workaround https://github.com/greenplum-db/gpdb/commit/e66e2a0bd46f15a2f009aaa8b4a392b3b43e1e92

I'm not sure if GPDB's CI has a different lib fixed the bug https://github.com/PyGreSQL/PyGreSQL/issues/77, but on my Ubuntu, after tried to upgrade python3-pygresql, the issue exists(maybe the pygresql is not updated on apt sources).

Dig for a while, I found the error shows that db url is not matched with argument 1 in test_dbconn.py,  `funny copy` is not preg matched rightly and the error reported.

I'm not familiar  with  pygresql lib or test_dbconn.py, a simple approach is replace `funny copy` db to `funny_copy` avoiding 
flaky not matched problem. And it works for me.

Not sure for all the OS, or other developers have got this issue, I will create a pr, it seems no harm and risk to apply it.

**Comment by avamingli** [comment]
Fixed in https://github.com/greenplum-db/gpdb/pull/16016

**Comment by kainwen** [comment]
Now in main branch, the py client API is replaced. Is this issue still there for main? @avamingli Thanks.

**Comment by avamingli** [comment]
> Now in main branch, the py client API is replaced. Is this issue still there for main? @avamingli Thanks.

Hi, @kainwen I have a try with main branch,  this issue has been resolved  on my machine.

```shell
test gpcopy                       ... ok         6538 ms

=====================
 All 1 tests passed.
=====================
```

While I try with main branch, anew issues arise #16571 , it has nothing to do with this issue, this could be closed.
