### ISSUE TITLE
The result of the hierarchical query is incorrect

### ISSUE THREAD

**Issue by hslightdb** [greenplum-db/gpdb#15555]
### Greenplum version or build
7.0.0-beta.3
### OS version and uname -a
rockylinux
Linux localhost.localdomain 4.18.0-425.3.1.el8.x86_64
### autoconf options used ( config.status --config )
'--with-perl' '--with-python' '--with-libxml' '--with-gssapi' '--prefix=/home/green/gpdb'
### Installation information ( pg_config )
BINDIR = /home/green/gpdb/bin
DOCDIR = /home/green/gpdb/share/doc/postgresql
HTMLDIR = /home/green/gpdb/share/doc/postgresql
INCLUDEDIR = /home/green/gpdb/include
PKGINCLUDEDIR = /home/green/gpdb/include/postgresql
INCLUDEDIR-SERVER = /home/green/gpdb/include/postgresql/server
LIBDIR = /home/green/gpdb/lib
PKGLIBDIR = /home/green/gpdb/lib/postgresql
LOCALEDIR = /home/green/gpdb/share/locale
MANDIR = /home/green/gpdb/share/man
SHAREDIR = /home/green/gpdb/share/postgresql
SYSCONFDIR = /home/green/gpdb/etc/postgresql
PGXS = /home/green/gpdb/lib/postgresql/pgxs/src/makefiles/pgxs.mk
CONFIGURE = '--with-perl' '--with-python' '--with-libxml' '--with-gssapi' '--prefix=/home/green/gpdb'
CC = gcc
CPPFLAGS = -D_GNU_SOURCE -I/usr/include/libxml2
CFLAGS = -Wall -Wmissing-prototypes -Wpointer-arith -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-unused-but-set-variable -Werror=implicit-fallthrough=3 -Wno-format-truncation -Wno-stringop-truncation -O3  -Werror=uninitialized -Werror=implicit-function-declaration
CFLAGS_SL = -fPIC
LDFLAGS = -Wl,--as-needed -Wl,-rpath,'/home/green/gpdb/lib',--enable-new-dtags
LDFLAGS_EX = 
LDFLAGS_SL = 
LIBS = -lpgcommon -lpgport -lpthread -lxerces-c -lbz2 -lxml2 -lrt -lgssapi_krb5 -lz -lreadline -lrt -lcrypt -ldl -lm  -lcurl -L/usr/lib -lzstd 
VERSION = PostgreSQL 12.12

### Expected behavior
 empno | ename  |   job    | mgr  |  hiredate  |   sal   |  comm   | deptno 
-------+--------+----------+------+------------+---------+---------+--------
  7698 | BLAKE  | MANAGER  | 7839 | 1981-05-01 | 2850.00 |         |     30
  7654 | MARTIN | SALESMAN | 7698 | 1981-09-28 | 1250.00 | 1400.00 |     30
  7499 | ALLEN  | SALESMAN | 7698 | 1981-02-20 | 1600.00 |  300.00 |     30
  7900 | JAMES  | CLERK    | 7698 | 1981-12-03 |  950.00 |         |     30
  7844 | TURNER | SALESMAN | 7698 | 1981-09-08 | 1500.00 |    0.00 |     30
  7521 | WARD   | SALESMAN | 7698 | 1981-02-22 | 1250.00 |  500.00 |     30
(6 rows)

### Actual behavior
 empno | ename |   job   | mgr  |  hiredate  |   sal   | comm | deptno 
-------+-------+---------+------+------------+---------+------+--------
  7698 | BLAKE | MANAGER | 7839 | 1981-05-01 | 2850.00 |      |     30

### Step to reproduce the behaviorvim 1
CREATE TABLE emp_ (
empno NUMERIC(4) NOT NULL,
ename VARCHAR(10),
job VARCHAR(9),
mgr int,
hiredate DATE,
sal NUMERIC(7,2),
comm NUMERIC(7,2),
deptno NUMERIC(2)
) distributed by (empno);

set DateStyle to "ISO, MDY"; 

INSERT INTO emp_ VALUES (7369,'SMITH','CLERK',7902,'17-DEC-80',800,NULL,20);
INSERT INTO emp_ VALUES (7499,'ALLEN','SALESMAN',7698,'20-FEB-81',1600,300,30);
INSERT INTO emp_ VALUES (7521,'WARD','SALESMAN',7698,'22-FEB-81',1250,500,30);
INSERT INTO emp_ VALUES (7566,'JONES','MANAGER',7839,'02-APR-81',2975,NULL,20);
INSERT INTO emp_ VALUES (7654,'MARTIN','SALESMAN',7698,'28-SEP-81',1250,1400,30);
INSERT INTO emp_ VALUES (7698,'BLAKE','MANAGER',7839,'01-MAY-81',2850,NULL,30);
INSERT INTO emp_ VALUES (7782,'CLARK','MANAGER',7839,'09-JUN-81',2450,NULL,10);
INSERT INTO emp_ VALUES (7788,'SCOTT','ANALYST',7566,'19-APR-87',3000,NULL,20);
INSERT INTO emp_ VALUES (7839,'KING','PRESIDENT',NULL,'17-NOV-81',5000,NULL,10);
INSERT INTO emp_ VALUES (7844,'TURNER','SALESMAN',7698,'08-SEP-81',1500,0,30);
INSERT INTO emp_ VALUES (7876,'ADAMS','CLERK',7788,'23-MAY-87',1100,NULL,20);
INSERT INTO emp_ VALUES (7900,'JAMES','CLERK',7698,'03-DEC-81',950,NULL,30);
INSERT INTO emp_ VALUES (7902,'FORD','ANALYST',7566,'03-DEC-81',3000,NULL,20);
INSERT INTO emp_ VALUES (7934,'MILLER','CLERK',7782,'23-JAN-82',1300,NULL,10);
-- explain 
WITH RECURSIVE cte_emp_ AS (
         SELECT emp_.empno,
            emp_.ename,
            emp_.job,
            emp_.mgr,
            emp_.hiredate,
            emp_.sal,
            emp_.comm,
            emp_.deptno
           FROM emp_
          WHERE emp_.empno = 7698::numeric::numeric
        UNION ALL
         SELECT emp_.empno,
            emp_.ename,
            emp_.job, 
            emp_.mgr,
            emp_.hiredate,
            emp_.sal,
            emp_.comm,
            emp_.deptno
            FROM emp_,
            cte_emp_ cte_emp__1 
            WHERE cte_emp__1.empno = emp_.mgr
        )
 SELECT cte_emp_.empno,
    cte_emp_.ename,
    cte_emp_.job,
    cte_emp_.mgr,
    cte_emp_.hiredate,
    cte_emp_.sal,
    cte_emp_.comm,
    cte_emp_.deptno
   FROM cte_emp_;

**Comment by SmartKeyerror** [comment]
If you build the Greenplum with `--enable-cassert`, and execute the following SQL, will throw Assert Error:

```
CREATE TABLE emp_ (
empno NUMERIC(4) NOT NULL,
ename VARCHAR(10),
job VARCHAR(9),
mgr int,
hiredate DATE,
sal NUMERIC(7,2),
comm NUMERIC(7,2),
deptno NUMERIC(2)
) distributed by (empno);

INSERT INTO emp_ VALUES (7369,'SMITH','CLERK',7902,'17-DEC-80',800,NULL,20);
FATAL:  Unexpected internal error (assert.c:44)
DETAIL:  FailedAssertion("!(((void *)0) != node)", File: "walkers.c", Line: 795)
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
```

**Comment by yanwr1** [comment]
The pr #15526 have fixed the issue,  For insert statement, the targetlist is NIL, it will trigger the assert fault.

**Comment by kainwen** [comment]
With the panic fix PR get in already now, the wrong answer issue is still there.

**Comment by QingMa-gp** [comment]
From my local test results, it appears to be a regression problem.
```
-- postgresql@12
empno | ename  |   job    | mgr  |  hiredate  |   sal   |  comm   | deptno 
-------+--------+----------+------+------------+---------+---------+--------
  7698 | BLAKE  | MANAGER  | 7839 | 1981-05-01 | 2850.00 |         |     30
  7499 | ALLEN  | SALESMAN | 7698 | 1981-02-20 | 1600.00 |  300.00 |     30
  7521 | WARD   | SALESMAN | 7698 | 1981-02-22 | 1250.00 |  500.00 |     30
  7654 | MARTIN | SALESMAN | 7698 | 1981-09-28 | 1250.00 | 1400.00 |     30
  7844 | TURNER | SALESMAN | 7698 | 1981-09-08 | 1500.00 |    0.00 |     30
  7900 | JAMES  | CLERK    | 7698 | 1981-12-03 |  950.00 |         |     30
(6 rows)

-- gpdb6
empno | ename  |   job    | mgr  |  hiredate  |   sal   |  comm   | deptno 
-------+--------+----------+------+------------+---------+---------+--------
  7698 | BLAKE  | MANAGER  | 7839 | 1981-05-01 | 2850.00 |         |     30
  7900 | JAMES  | CLERK    | 7698 | 1981-12-03 |  950.00 |         |     30
  7844 | TURNER | SALESMAN | 7698 | 1981-09-08 | 1500.00 |    0.00 |     30
  7521 | WARD   | SALESMAN | 7698 | 1981-02-22 | 1250.00 |  500.00 |     30
  7654 | MARTIN | SALESMAN | 7698 | 1981-09-28 | 1250.00 | 1400.00 |     30
  7499 | ALLEN  | SALESMAN | 7698 | 1981-02-20 | 1600.00 |  300.00 |     30
(6 rows)

-- gpdb7
empno | ename |   job   | mgr  |  hiredate  |   sal   | comm | deptno 
-------+-------+---------+------+------------+---------+------+--------
  7698 | BLAKE | MANAGER | 7839 | 1981-05-01 | 2850.00 |      |     30
(1 row)
```

**Comment by kainwen** [comment]
I think I know the root cause of this issue:

1. recursive CTE is now only supported by legacy planner
2. the worktable scan's locus is setting based on non-recursive path plan
3. on 6X, hash distributed locus will be transformed to stewn locus thus no such bugs, refer to 6X code: `create_worktablescan_path`
4. on main branch, the code is refactored during merge 9.6, it loses the transformation of hash to strewn.
5. not in this case, the hash locus from base rel `emp_` has a filter on its distributed key, and this filter only exists on the non-recursive part's scan, which means it cannot be used as locus of worktable scan.

Simply bring back the locus transformation can fix this issue.

**Comment by l-wang** [comment]
Thank you Zhenghua for the RCA and context sharing w/ me. I'm working on the fix.
