### ISSUE TITLE
gserialized_estimate.c:910:8: error: too many arguments to function ‘get_attstatsslot’

### ISSUE THREAD

**Issue by mrrobot3333** [greenplum-db/gpdb#15634]
## 
gserialized_estimate.c:910:8: error: too many arguments to function ‘get_attstatsslot’
   rv = get_attstatsslot(stats_tuple, 0, 0, stats_kind, InvalidOid,
        ^~~~~~~~~~~~~~~~
In file included from gserialized_estimate.c: 100:
/usr/local/greenplum-db-6.24.3/include/postgresql/server/utils/lsyscache.h:210:13: note: declared here
 extern bool get_attstatsslot(AttStatsSlot *sslot, HeapTuple statstuple,
             ^~~~~~~~~~~~~~~~
gserialized_estimate.c:923:3: error: too many arguments to function ‘free_attstatsslot’
   free_attstatsslot(0, NULL, 0, floatptr, nvalues);
   ^~~~~~~~~~~~~~~~~
In file included from gserialized_estimate.c: 100:
/usr/local/greenplum-db-6.24.3/include/postgresql/server/utils/lsyscache.h:212:13: note: declared here
 extern void free_attstatsslot(AttStatsSlot *sslot);

### OL8.7 
i can't solve this error,
![postgis](https://github.com/greenplum-db/gpdb/assets/134881632/f4c0e957-579f-4df1-ae46-487ef5a6a7dd)

below dependencies look fine. someone can help me?
![postgis1](https://github.com/greenplum-db/gpdb/assets/134881632/09d382f3-52e0-443f-b3c4-1deab1144383)

**Comment by hyongtao-db** [comment]
I am so sorry I didn't get it. Could you please share us the link or info about `gserialized_estimate.c`? Thanks a lot.

**Comment by ashwinstar** [comment]
Closing this issue as without full details - no way to help. Based on file name details looks like trying to compile some postgis code. Though without details its hard to interpret the things. Just in case interested in PostGIS then we have repository https://github.com/greenplum-db/geospatial which hosts code which compiles against GPDB.
