### ISSUE TITLE
Urgent: build fails on IBM Power architecture 

### ISSUE THREAD

**Issue by asanjar** [greenplum-db/gpdb#1563]
build fails with error :
checking build system type... config/config.guess: unable to guess system type

This script, last modified 2011-05-11, has failed to recognize
the operating system you are using. It is advised that you
download the most up to date version of the config scripts from

  http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.guess;hb=HEAD
and
  http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.sub;hb=HEAD

If the version you run (config/config.guess) is already up to date, please
send the following data and any information you think might be
pertinent to <config-patches@gnu.org> in order to provide the needed
information to handle your system.
 
config.guess timestamp = 2011-05-11

uname -m = ppc64le
uname -r = 4.4.0-21-generic
uname -s = Linux
uname -v = #37-Ubuntu SMP Mon Apr 18 18:30:22 UTC 2016

**Solution:
replace the outdated config/config.guess with the latest one from 
wget -O config.guess 'http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.guess;hb=HEAD'**

**Comment by hlinnaka** [comment]
PR #1554 addresses this.

**Comment by ivannovick** [comment]
Closing the issue as we have a PR.... @asanjar can you help verify the fix with the PR?

**Comment by asanjar** [comment]
yes,will do, thanks

**Comment by asanjar** [comment]
+1 build successfully on IBM Power

**Comment by hlinnaka** [comment]
Pushed the PR, so it should work now.
