### ISSUE TITLE
interconnect network error 

### ISSUE THREAD

**Issue by southpolekat** [greenplum-db/gpdb#15658]
## Bug Report
`WARNING:  interconnect may encountered a network error, please check your network  (seg4 slice1 172.25.0.92:60000 pid=4040)
DETAIL:  Failed to send packet (seq 1) to 127.0.0.1:34223 (pid 10221 cid -1) after 100 retries.
WARNING:  interconnect may encountered a network error, please check your network  (seg5 slice1 172.25.0.92:60001 pid=4041)
DETAIL:  Failed to send packet (seq 1) to 127.0.0.1:34223 (pid 10221 cid -1) after 100 retries.
WARNING:  interconnect may encountered a network error, please check your network  (seg6 slice1 172.25.0.92:60002 pid=4042)
DETAIL:  Failed to send packet (seq 1) to 127.0.0.1:34223 (pid 10221 cid -1) after 100 retries.
WARNING:  interconnect may encountered a network error, please check your network  (seg7 slice1 172.25.0.92:60003 pid=4043)
DETAIL:  Failed to send packet (seq 1) to 127.0.0.1:34223 (pid 10221 cid -1) after 100 retries.
`
### Greenplum version or build
6.21.0 to 6.24.3

### OS version and uname -a
Ubuntu 18.04.6 LTS
Linux gpdb2 5.15.0-72-generic #79~20.04.1-Ubuntu SMP Thu Apr 20 22:12:07 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Step to reproduce the behavior
- Clean install a greenplum cluster with two nodes
- psql -c "create table tt (i int);"
- psql -c "select * from tt;"

Notes:
- This issue does not happen in single node setup
- Version 6.20.5 or older is working fine

**Comment by southpolekat** [comment]
The database was initialized with setting
MASTER_HOSTNAME=localhost
Therefore some segments on other host connect to the master host using IP 127.0.0.1

**Comment by zhengpingzhong** [comment]
How did the problem get solved?

**Comment by southpolekat** [comment]
I updated the MASTER_HOSTNAME in the cluster configuration file.
I deleted the database system and initialized it.
