### ISSUE TITLE
can we bypass 2PC for readonly transaction?

### ISSUE THREAD

**Issue by xiong-gang** [greenplum-db/gpdb#1567]
I noticed transactions as follow will perform WAL write during 2PC, does it make sense?

```
begin;
end;
```

```
begin;
select * from t;
end;
```

**Comment by asimrp** [comment]
Hi Gang, once we have lazy XIDs fully implemented, there will be no WAL logs and 2PC overhead for read-only transactions.  Until then, this is expected behavior.

**Comment by xiong-gang** [comment]
Cool, thanks for the reply. @asimrp

**Comment by yydzero** [comment]
@asimrp any rough ETA for lazy XIDs?

**Comment by asimrp** [comment]
The lazy XID work is quite intrusive and needs tests to for validation.  All tests under `src/test/tinc/tincrepo/mpp/gpdb/tests/storage` must pass before making lazy XID work.  We are actively working on making tests green.

**Comment by yydzero** [comment]
Thanks a lot Asim for the quick response!
