### ISSUE TITLE
ERROR:  catalog is missing 25 attribute(s) for relid 24671 when VACUUM FULL 

### ISSUE THREAD

**Issue by hyongtao-db** [greenplum-db/gpdb#15681]
### Greenplum version or build
7X at [fd553fdb](https://github.com/greenplum-db/gpdb/commit/fd553fdb073674b22fe665d45a2c6721fab2a3ba)

### Expected behavior
In pg 12.12:
```
[gpadmin@localhost ~]$ createdb testvacuum
[gpadmin@localhost ~]$ psql -d testvacuum
psql (12.12)
Type "help" for help.

testvacuum=# VACUUM FULL;
VACUUM
```
In gpdb 6X:
```
[gpadmin@localhost ~]$ createdb testvacuum
[gpadmin@localhost ~]$ psql -d testvacuum
psql (9.4.26)
Type "help" for help.

testvacuum=# VACUUM FULL;
VACUUM
testvacuum=#
```
### Actual behavior && Step to reproduce the behavior
In gpdb 7X:
```
[gpadmin@localhost ~]$ createdb testvacuum
[gpadmin@localhost ~]$ psql -d testvacuum
psql (12.12)
Type "help" for help.

testvacuum=# VACUUM FULL;
ERROR:  catalog is missing 25 attribute(s) for relid 24671 (relcache.c:706)
testvacuum=#

```

**Comment by haolinw** [comment]
The issue was fixed by @huansong's commit [15e1978b65c2f2c8fc81f14a335ecb2acabd5c30](https://github.com/greenplum-db/gpdb/commit/15e1978b65c2f2c8fc81f14a335ecb2acabd5c30), close it.
