### ISSUE TITLE
The ic-proxy bgworker always running  when configure with --enable-ic-proxy?

### ISSUE THREAD

**Issue by jiaqizho** [greenplum-db/gpdb#15689]
## Enhancement
1. ./configure --enable-ic-proxy --xxxx
2. make create-demo-cluster
3. gpconfig -c gp_interconnect_type -v tcp  
4. gpstop -ar

still got a `ic_proxy bgworker` started and some `.s.PGSQL.ic_proxy.7000.*` socket file generated.
![image](https://github.com/greenplum-db/gpdb/assets/8388185/35e20b08-854a-4600-855c-30c84df85570)

i am not sure that is a expected behavior or not?

**Comment by Aegeaner** [comment]
This is a known issue as it's controlled by a complier flag `ENABLE_IC_PROXY` which is static, instead of a GUC. If compiled with this flag, the background workers will automaticlly start.

**Comment by ashwinstar** [comment]
Given `gp_interconnect_type` can be set at session level there is no co-relation between `gp_interconnect_type` value and `ic_proxy bgworker` presence. @jiaqizho please can you state the real problem (using too much memory or resources or such) for requesting the enhancement?

**Comment by jiaqizho** [comment]
> Given `gp_interconnect_type` can be set at session level there is no co-relation between `gp_interconnect_type` value and `ic_proxy bgworker` presence. @jiaqizho please can you state the real problem (using too much memory or resources or such) for requesting the enhancement?

@ashwinstar Just curious why it's designed this way :)
