### ISSUE TITLE
Segmentation fault when running backslash commands in psql 

### ISSUE THREAD

**Issue by jmcatamney** [greenplum-db/gpdb#15695]
### Greenplum version or build

This issue was observed in 7X on Centos 7, and in both 6X and 7X on Rocky 8, on a particular machine.  I was not able to reproduce the issue in our Concourse environment using the same GPDB versions and OSes.

### Issue description

When executing any psql command beginning with a backslash (`\d`, `\connect`, etc.), psql experiences a segmentation fault.

### Cause of the issue

In `src/bin/psql/psqlscanslash.c`, in the following code block:

```
#line 1324 "psqlscanslash.c"

    while ( /*CONSTCOND*/1 )        /* loops until end-of-file is reached */
        {    
        yy_cp = yyg->yy_c_buf_p;

        /* Support of yytext. */
        *yy_cp = yyg->yy_hold_char;

        /* yy_bp points to the position in yy_ch_buf of the start of
         * the current run.
         */
        yy_bp = yy_cp;

        yy_current_state = yyg->yy_start;

        ...
```

`yyg->yy_c_buf_p` is null on the first execution, causing the segfault on the next line.

### Proposed fix

`psqlscanslash.c` is actually a generated file, based on `psqlscanslash.l` in the same directory.  There seems to be some funkiness around the treatment of newlines on some platforms, according to `src/fe_utils/psqlscan.l`:

```
 * In order to make the world safe for Windows and Mac clients as well as
 * Unix ones, we accept either \n or \r as a newline.  A DOS-style \r\n
 * sequence will be seen as two successive newlines, but that doesn't cause
 * any problems.  Comments that start with -- and extend to the next
 * newline are treated as equivalent to a single whitespace character.
```
So adding the following lines before the `other` on line 119 in `psqlscanslash.l`...

```
newline         [\n\r]
non_newline     [^\n\r]
```

...and then regenerating the file with `make` appears to fix the issue.  There do not appear to be any other side effects of adding those lines, but I haven't done extensive testing to verify this.

Thanks to @huansong for helping to debug this and identifying the fix.

**Comment by huansong** [comment]
Paired w/ @jmcatamney on this, but we couldn't repro this issue anymore. We suspected that some commit between last-seen repro and now had resolved the issue somehow. The only recent commit I found that might be related is https://github.com/greenplum-db/gpdb/commit/fc896f45d6d8 (made into main branch in Jan 2023). But even reverting it won't give us a repro. Not sure what else we can do at this point, I'm closing this PR for now.
