### ISSUE TITLE
The Sql will experience network error when running 3600 seconds. interconnect encountered a network error please check your network

### ISSUE THREAD

**Issue by xuzhiyu01** [greenplum-db/gpdb#15728]
### Greenplum version or build

Greenplum Database 6.22.0
### OS version and uname -a
centos 7.9 
### Installation information ( pg_config )

BINDIR = /usr/local/greenplum-db-6.22.0/bin
DOCDIR = /usr/local/greenplum-db-6.22.0/share/doc/postgresql
HTMLDIR = /usr/local/greenplum-db-6.22.0/share/doc/postgresql
INCLUDEDIR = /usr/local/greenplum-db-6.22.0/include
PKGINCLUDEDIR = /usr/local/greenplum-db-6.22.0/include/postgresql
INCLUDEDIR-SERVER = /usr/local/greenplum-db-6.22.0/include/postgresql/server
LIBDIR = /usr/local/greenplum-db-6.22.0/lib
PKGLIBDIR = /usr/local/greenplum-db-6.22.0/lib/postgresql
LOCALEDIR = /usr/local/greenplum-db-6.22.0/share/locale
MANDIR = /usr/local/greenplum-db-6.22.0/man
SHAREDIR = /usr/local/greenplum-db-6.22.0/share/postgresql
SYSCONFDIR = /usr/local/greenplum-db-6.22.0/etc/postgresql
PGXS = /usr/local/greenplum-db-6.22.0/lib/postgresql/pgxs/src/makefiles/pgxs.mk
CONFIGURE = '--disable-debug-extensions' '--disable-tap-tests' '--enable-orca' '--with-zstd' '--with-gssapi' '--with-libxml' '--with-perl' '--with-python' '--with-openssl' '--with-pam' '--with-ldap' '--with-extra-version= Open Source' '--prefix=/usr/local/greenplum-db-6.22.0' '--mandir=/usr/local/greenplum-db-6.22.0/man' 'CC=gcc' 'CFLAGS=-O3 -fargument-noalias-global -fno-omit-frame-pointer -g'
CC = gcc
CPPFLAGS = -D_GNU_SOURCE -I/usr/include/libxml2 -I/usr/local/greenplum-db-6.22.0/include
CFLAGS = -Wall -Wmissing-prototypes -Wpointer-arith -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fno-aggressive-loop-optimizations -Wno-unused-but-set-variable -Wno-address -O3 -fargument-noalias-global -fno-omit-frame-pointer -g -std=gnu99 -Werror=uninitialized -Werror=implicit-function-declaration -I/usr/local/greenplum-db-6.22.0/include
CFLAGS_SL = -fPIC
LDFLAGS = -Wl,--as-needed -Wl,-rpath,'/usr/local/greenplum-db-6.22.0/lib',--enable-new-dtags -L/usr/local/greenplum-db-6.22.0/lib
LDFLAGS_EX =
LDFLAGS_SL =
LIBS = -lpgcommon -lpgport -lxerces-c -lxml2 -lpam -lrt -lgssapi_krb5 -lzstd -lrt -lcrypt -ldl -lm -L/usr/local/greenplum-db-6.22.0/lib
VERSION = PostgreSQL 9.4.26

### Expected behavior

The big sql could running succesfully. I could wait if need more time. But unable to report a error and exit. 

### Actual behavior

I have a procedure which contain big sql. This store procedure will report this error after 1 hour. 
If i only execute this sql. It's also report this error. 
-----------------------------------------------------------------
"ERROR"."58M01","interconnect encountered a network error please check your network (seg11 slice1 172.50.13.45:6003 pid=75242)"
"Did not get any response from 172.50.13.43:15699(pid 30065 cid3) in 3600 seconds " 
-----------------------------------------------------------------
Then I adjust this parameter to TCP. 
gpconfig -c gp_interconnect_type -v TCP

re-run store procedure or SQL. I get similar error. It's also failed after 3600 second. 
-----------------------------------------------------------------
Time out waiting for response from motion receiver during TCP interconnect teardown 
(seg1 slice1 172.50.13.43:6001 pid=12428)
32 connection(s) with pending reponse after 3600 seconds.
-----------------------------------------------------------------
### Step to reproduce the behavior

Linux kernel configuration. 

cat >> /etc/sysctl.conf << EOF
# used for green plum#
kernel.shmall = 65978638
kernel.shmmax = 270248501248
kernel.shmmni = 4096
vm.overcommit_memory = 2 
vm.overcommit_ratio = 95 
net.ipv4.ip_local_port_range = 10000 65535 
kernel.sem = 250 2048000 200 8192
kernel.sysrq = 1
kernel.core_uses_pid = 1
kernel.msgmnb = 65536
kernel.msgmax = 65536
kernel.msgmni = 2048
net.ipv4.tcp_syncookies = 1
net.ipv4.conf.default.accept_source_route = 0
net.ipv4.tcp_max_syn_backlog = 4096
net.ipv4.conf.all.arp_filter = 1
net.ipv4.ipfrag_high_thresh = 41943040
net.ipv4.ipfrag_low_thresh = 31457280
net.ipv4.ipfrag_time = 60
net.core.netdev_max_backlog = 10000
net.core.rmem_max = 2097152
net.core.wmem_max = 2097152
vm.swappiness = 10
vm.zone_reclaim_mode = 0
vm.dirty_expire_centisecs = 500
vm.dirty_writeback_centisecs = 100
vm.dirty_background_ratio = 0 
vm.dirty_ratio = 0
vm.dirty_background_bytes = 1610612736
vm.dirty_bytes = 4294967296
# used for green plum#
EOF

**Comment by ashwinstar** [comment]
Closing this issue as no repro or details provided to move forward.
