### ISSUE TITLE
ERROR:  could not pull up equivalence class using projected target list (pathkeys.c:1539)

### ISSUE THREAD

**Issue by hyongtao-db** [greenplum-db/gpdb#15767]
### Greenplum version or build
gpdb 7X at [6ed96f6](https://github.com/greenplum-db/gpdb/commit/6ed96f69af682a5a2e7795c63b0b98c3e6626e8a)

### Expected behavior
The behavior in pg12.12 , gpdb 6X and gpdb 7X before [aff2a34](https://github.com/greenplum-db/gpdb/commit/aff2a34333ab31d86e65505cefd3e6144dbe67da) are all the same. The result test in pg12.12 is shown as below:
``` SQL
[gpadmin@localhost ~]$ psql
psql (12.12)
Type "help" for help.

gpadmin=# create table t (c0 int, c1 int);
CREATE TABLE
gpadmin=# insert into t values(1,0),(2,1);
INSERT 0 2
gpadmin=#
gpadmin=# SELECT MAX(c0) FROM t
gpadmin-# UNION ALL
gpadmin-# SELECT MAX(c0) FROM t
gpadmin-# GROUP BY 1*t.c0;
 max
-----
   2
   2
   1
(3 rows)

gpadmin=#
```
### Actual behavior
The test result at gpdb 7X at [6ed96f6](https://github.com/greenplum-db/gpdb/commit/6ed96f69af682a5a2e7795c63b0b98c3e6626e8a)
```
create table t (c0 int, c1 int);
insert into t values(1,0),(2,1);

SELECT MAX(c0) FROM t
UNION ALL
SELECT MAX(c0) FROM t
GROUP BY 1*t.c0;

ERROR:  could not pull up equivalence class using projected target list (pathkeys.c:1539)
```
### Analyse
pg12.12 , gpdb 6X and gpdb 7X before [aff2a34](https://github.com/greenplum-db/gpdb/commit/aff2a34333ab31d86e65505cefd3e6144dbe67da) don't have this bug. I think it's strong related with  [aff2a34](https://github.com/greenplum-db/gpdb/commit/aff2a34333ab31d86e65505cefd3e6144dbe67da) 

Please focus on `GROUP BY 1*t.c0;`. If we change it from`GROUP BY 1*t.c0;` to `GROUP BY t.c0;`, the behavior is correct.
``` SQL
[gpadmin@localhost gpdb]$ psql
psql (12.12)
Type "help" for help.

gpadmin=# create table t (c0 int, c1 int);
NOTICE:  Table doesn't have 'DISTRIBUTED BY' clause -- Using column named 'c0' as the Greenplum Database data distribution key for this table.
HINT:  The 'DISTRIBUTED BY' clause determines the distribution of data. Make sure column(s) chosen are the optimal data distribution key to minimize skew.
ERROR:  relation "t" already exists
gpadmin=# insert into t values(1,0),(2,1);
ELECT MAX(c0) FROM t
GROUP BY 1*t.c0;INSERT 0 2
gpadmin=# 
gpadmin=# SELECT MAX(c0) FROM t
UNION ALL
SELECT MAX(c0) FROM t
GROUP BY 1*t.c0;
ERROR:  could not pull up equivalence class using projected target list (pathkeys.c:1539)
gpadmin=# SELECT MAX(c0) FROM t
UNION ALL
SELECT MAX(c0) FROM t
GROUP BY t.c0;
 max 
-----
   2
   1
   2
(3 rows)

gpadmin=#
```

**Comment by hyongtao-db** [comment]
I still don't get the RCA of this bug. But #15768 may be a solution of this bug.

**Comment by charliettxx** [comment]
I suppose `1*t.c0` could not by found in targetlist, but there are two things out of curiosity.

- why planner didn't optimize `1*t.c0 `to `t.c0`, they are equal
- why 1*t.c0 was not added to targetlist. Normally, group by clause should by added into query targetlist.

**Comment by kainwen** [comment]
>  why planner didn't optimize 1*t.c0 to t.c0, they are equal

@charliettxx they might not, `*` might not be the `*` in your mind. If we do want such kind of optimization, it has to be encoded in catalog.

**Comment by hyongtao-db** [comment]
>why planner didn't optimize 1*t.c0 to t.c0, they are equal

The explain result in pg12.12 is shown as below, the behavior is strong related with upstream. 
```
gpadmin=# explain SELECT MAX(c0) FROM t
UNION ALL
SELECT MAX(c0) FROM t
GROUP BY 1*t.c0;
                                QUERY PLAN
---------------------------------------------------------------------------
 Append  (cost=38.25..93.32 rows=201 width=4)
   ->  Aggregate  (cost=38.25..38.26 rows=1 width=4)
         ->  Seq Scan on t  (cost=0.00..32.60 rows=2260 width=4)
   ->  Subquery Scan on "*SELECT* 2"  (cost=49.55..54.05 rows=200 width=4)
         ->  HashAggregate  (cost=49.55..52.05 rows=200 width=8)
               Group Key: (1 * t_1.c0)
               ->  Seq Scan on t t_1  (cost=0.00..38.25 rows=2260 width=8)
(7 rows)

gpadmin=# explain SELECT MAX(c0) FROM t
UNION ALL
SELECT MAX(c0) FROM t
GROUP BY t.c0;
                                QUERY PLAN
---------------------------------------------------------------------------
 Append  (cost=38.25..87.17 rows=201 width=4)
   ->  Aggregate  (cost=38.25..38.26 rows=1 width=4)
         ->  Seq Scan on t  (cost=0.00..32.60 rows=2260 width=4)
   ->  Subquery Scan on "*SELECT* 2"  (cost=43.90..47.90 rows=200 width=4)
         ->  HashAggregate  (cost=43.90..45.90 rows=200 width=8)
               Group Key: t_1.c0
               ->  Seq Scan on t t_1  (cost=0.00..32.60 rows=2260 width=4)
(7 rows)

```

**Comment by hyongtao-db** [comment]
With this commit [6ed96f6](https://github.com/greenplum-db/gpdb/commit/6ed96f69af682a5a2e7795c63b0b98c3e6626e8a),

```
		if (!IsA(key, Var) &&
			!cdbpullup_missingVarCheck(key, targetlist))
			return key;
```
`cdbpullup_missingVarCheck(key, targetlist)` will return false, which means it contains this Var.
And `return key` will return T_OpExpr key.


Without this commit [6ed96f6](https://github.com/greenplum-db/gpdb/commit/6ed96f69af682a5a2e7795c63b0b98c3e6626e8a),

```
		if (!IsA(key, Var) &&
			!cdbpullup_missingVarWalker(key, targetlist))
		{
			return key;
		}
```
`cdbpullup_missingVarWalker(key, targetlist)` will return ture, which means it misses this Var.

So I think `cdbpullup_missingVarCheck()` is not an equivalent optimization of `cdbpullup_missingVarWalker()`.
We need to spike it furtherly.

----------------------------------------------------------------------

Another interesting thing. With or without commit [6ed96f69](https://github.com/greenplum-db/gpdb/commit/6ed96f69af682a5a2e7795c63b0b98c3e6626e8a ) , both pipelines can pass when we remove this elog `elog(ERROR, "could not pull up equivalence class using projected target list");` directly.

I close this pr #15768.

**Comment by kainwen** [comment]
I open a PR https://github.com/greenplum-db/gpdb/pull/15797
to revert the commit that introduces the regression and also add this case as guarding so that later we can do a correct refactor.

**Comment by kainwen** [comment]
Revert PR is pushed, close this issue. Later details might be found in the comment parts of https://github.com/greenplum-db/gpdb/issues/15079.

**Comment by hyongtao-db** [comment]
After PR reverted, everything is OK now. This is test result in GPDB 7X:
```
gpadmin=# create table t (c0 int, c1 int);
NOTICE:  Table doesn't have 'DISTRIBUTED BY' clause -- Using column named 'c0' as the Greenplum Database data distribution key for this table.
HINT:  The 'DISTRIBUTED BY' clause determines the distribution of data. Make sure column(s) chosen are the optimal data distribution key to minimize skew.
CREATE TABLE
gpadmin=# insert into t values(1,0),(2,1);
INSERT 0 2
gpadmin=#
gpadmin=# SELECT MAX(c0) FROM t
gpadmin-# UNION ALL
gpadmin-# SELECT MAX(c0) FROM t
gpadmin-# GROUP BY 1*t.c0;
 max
-----
   2
   2
   1
(3 rows)

```
Thanks for your work @kainwen .
