### ISSUE TITLE
[7X] `\di+` can not show the same name indexes.

### ISSUE THREAD

**Issue by zhrt123** [greenplum-db/gpdb#15791]
## Bug Report
After we create the same name index on the heap table and the temporary table, we can only get the temporary table's index by `\di+`. This bug is also found on the latest pg.

### Greenplum version or build
GPDB7 main

### Expected behavior
After creating two index and using `\di+`, the results should be:
```
\di+
                         List of relations
   Schema    | Name | Type  | Owner | Table |  Size  | Description 
-------------+------+-------+-------+-------+--------+-------------
 pg_temp_298 | idx1 | index | zhrt  | t2    | 128 kB | 
 public      | idx1 | index | zhrt  | t1    | 128 kB | 
(2 row)
```

### Actual behavior
```
\di+
                         List of relations
   Schema    | Name | Type  | Owner | Table |  Size  | Description 
-------------+------+-------+-------+-------+--------+-------------
 pg_temp_298 | idx1 | index | zhrt  | t2    | 128 kB | 
(1 row)
```

### Step to reproduce the behavior
```
create table t1(c1 int);
create temp table t2(c1 int);

create index idx1 on t1(c1);
\di+
                      List of relations
 Schema | Name | Type  | Owner | Table |  Size  | Description 
--------+------+-------+-------+-------+--------+-------------
 public | idx1 | index | zhrt  | t1    | 128 kB | 
(1 row)

create index idx1 on t2(c1);
\di+
                         List of relations
   Schema    | Name | Type  | Owner | Table |  Size  | Description 
-------------+------+-------+-------+-------+--------+-------------
 pg_temp_298 | idx1 | index | zhrt  | t2    | 128 kB | 
(1 row)
```

**Comment by ashwinstar** [comment]
Paste link to upstream PostgreSQL thread once created. Thanks.

**Comment by hyongtao-db** [comment]
Update it in upstream PostgresSQL with Hao Zhang, BUG #18290:

**Comment by hyongtao-db** [comment]
Get a response from Tom Lane https://www.postgresql.org/message-id/1240720.1705247863%40sss.pgh.pa.us
```
This is not a bug: \di is operating as documented, namely showing you
the indexes that are visible in your current search_path.  The
temp index masks the similarly-named one in public.  You could see
both of them with "\di+ *.*", "\di+ *.idx1", or other forms.  For
more info see
```

Testing in pg16.1
```
gpadmin=# \di+ *.idx1
                                          List of relations
  Schema   | Name | Type  |  Owner  | Table | Persistence | Access method |    Size    | Descript
ion
-----------+------+-------+---------+-------+-------------+---------------+------------+---------
----
 pg_temp_3 | idx1 | index | gpadmin | t2    | temporary   | btree         | 8192 bytes |
 public    | idx1 | index | gpadmin | t1    | permanent   | btree         | 8192 bytes |
(2 rows)
```

**Comment by zhrt123** [comment]
> Get a response from Tom Lane https://www.postgresql.org/message-id/1240720.1705247863%40sss.pgh.pa.us
> 
> ```
> This is not a bug: \di is operating as documented, namely showing you
> the indexes that are visible in your current search_path.  The
> temp index masks the similarly-named one in public.  You could see
> both of them with "\di+ *.*", "\di+ *.idx1", or other forms.  For
> more info see
> ```
> 
> Testing in pg16.1
> 
> ```
> gpadmin=# \di+ *.idx1
>                                           List of relations
>   Schema   | Name | Type  |  Owner  | Table | Persistence | Access method |    Size    | Descript
> ion
> -----------+------+-------+---------+-------+-------------+---------------+------------+---------
> ----
>  pg_temp_3 | idx1 | index | gpadmin | t2    | temporary   | btree         | 8192 bytes |
>  public    | idx1 | index | gpadmin | t1    | permanent   | btree         | 8192 bytes |
> (2 rows)
> ```

Yes, I'll close this issue since this is a feature of pg.
