### ISSUE TITLE
ERROR:  could not find hash distribution key expressions in target list (createplan.c:8252

### ISSUE THREAD

**Issue by hyongtao-db** [greenplum-db/gpdb#15793]
### Greenplum version or build
gpdb 7X at [6ed96f6](https://github.com/greenplum-db/gpdb/commit/6ed96f69af682a5a2e7795c63b0b98c3e6626e8a)

### Expected behavior
The behavior in pg12.12 , gpdb 6X and gpdb 7X before [aff2a34](https://github.com/greenplum-db/gpdb/commit/aff2a34333ab31d86e65505cefd3e6144dbe67da) are all the same. The result test in pg12.12 is shown as below:
``` SQL
gpadmin=# create table test1 (c0 int);
CREATE TABLE
gpadmin=# create table test2 (c0 int);
CREATE TABLE
gpadmin=# SELECT * FROM test1 CROSS JOIN test2 WHERE NOT ((test1.c0)+(test1.c0)!=(test2.c0));
 c0 | c0
----+----
(0 rows)
```
### Actual behavior
The test result in gpdb 7X at [6ed96f6](https://github.com/greenplum-db/gpdb/commit/6ed96f69af682a5a2e7795c63b0b98c3e6626e8a)
```
create table test1 (c0 int);
create table test2 (c0 int);
SELECT * FROM test1 CROSS JOIN test2 WHERE NOT ((test1.c0)+(test1.c0)!=(test2.c0));

ERROR:  could not find hash distribution key expressions in target list (createplan.c:8252)
```
### Analyse
pg12.12 , gpdb 6X and gpdb 7X before [aff2a34](https://github.com/greenplum-db/gpdb/commit/aff2a34333ab31d86e65505cefd3e6144dbe67da) don't have this bug. I think it's strong related with  [aff2a34](https://github.com/greenplum-db/gpdb/commit/aff2a34333ab31d86e65505cefd3e6144dbe67da) 

The problem maybe same as [issue 15767](https://github.com/greenplum-db/gpdb/issues/15767)

**Comment by kainwen** [comment]
I open a PR https://github.com/greenplum-db/gpdb/pull/15797
to revert the commit that introduces the regression and also add this case as guarding so that later we can do a correct refactor.

**Comment by kainwen** [comment]
Revert PR is pushed, close this issue. Later details might be found in the comment parts of https://github.com/greenplum-db/gpdb/issues/15079.

**Comment by hyongtao-db** [comment]
After PR reverted, everything is OK. It is test result in GPDB 7X:

```SQL
[gpadmin@gpcopy-dest gpdemo]$ psql
psql (12.12)
Type "help" for help.

gpadmin=# create table test1 (c0 int);
NOTICE:  Table doesn't have 'DISTRIBUTED BY' clause -- Using column named 'c0' as the Greenplum Database data distribution key for this table.
HINT:  The 'DISTRIBUTED BY' clause determines the distribution of data. Make sure column(s) chosen are the optimal data distribution key to minimize skew.
CREATE TABLE
gpadmin=# create table test2 (c0 int);
NOTICE:  Table doesn't have 'DISTRIBUTED BY' clause -- Using column named 'c0' as the Greenplum Database data distribution key for this table.
HINT:  The 'DISTRIBUTED BY' clause determines the distribution of data. Make sure column(s) chosen are the optimal data distribution key to minimize skew.
CREATE TABLE
gpadmin=# SELECT * FROM test1 CROSS JOIN test2 WHERE NOT ((test1.c0)+(test1.c0)!=(test2.c0));
 c0 | c0
----+----
(0 rows)

gpadmin=#
```

Thanks for your work @kainwen
