### ISSUE TITLE
enable_materialize is off doesn't take effect.

### ISSUE THREAD

**Issue by avamingli** [greenplum-db/gpdb#15798]
### Greenplum version or build
7x

### Expected behavior
No material node when enable_materialize is off.

### Step to reproduce the behavior

```sql
create table t1(id int) distributed by (id);
create index on t1(id);
insert into t1 values(generate_series(1, 100));
analyze t1;
set enable_seqscan =off;
set enable_material =off;
explain (costs off)
select * from
  (select count(id) from t1 where id > 10) ss
  right join (values (1),(2),(3)) v(x) on true;
                             QUERY PLAN
---------------------------------------------------------------------
 Nested Loop Left Join
   ->  Values Scan on "*VALUES*"
   ->  Materialize
         ->  Finalize Aggregate
               ->  Gather Motion 3:1  (slice1; segments: 3)
                     ->  Partial Aggregate
                           ->  Index Only Scan using t1_id_idx on t1
                                 Index Cond: (id > 10)
 Optimizer: Postgres query optimizer
(9 rows)
```

RC :
When `enable_materialize `is false, planner doesn't generate Materialize path. But in create_nestloop_plan(), different from PG, GP add Materialize Node for inner plan without checking `enable_materialize`

Shall we follow PG's the definition of GUC `enable_materialize `  ?
> Enables the planner's use of materialization

**Comment by soumyadeep2007** [comment]
>  But in create_nestloop_plan(), different from PG, GP add Materialize Node for inner plan without checking enable_materialize

This materialize node has been inserted in response to a deadlock hazard. So we have no choice but to insert it.
