### ISSUE TITLE
an issue in exec_stmt_return

### ISSUE THREAD

**Issue by kuien** [greenplum-db/gpdb#158]
In GPDB
```sql
create type xyz as (a int, b int);
select row(1,2)::xyz;
create or replace function return_xyz() returns xyz as $$ begin
    return row(1,2)::xyz;
end $$ language plpgsql;
```
Above PLPGSQL throws out an error:
__ERROR:  RETURN must specify a record or row variable in function returning tuple at or near "row"__

While in PG, it works well:
```sh
test=# create or replace function return_xyz() returns xyz as $$ begin
test$#     return row(1,2)::xyz;
test$# end $$ language plpgsql;
CREATE FUNCTION
```

**Comment by kuien** [comment]
I found a way to bypass this issue:
```sql
create type xyz as (a int, b int);
select row(1,2)::xyz;
create or replace function return_xyz() returns xyz as $$
declare
    ret xyz%ROWTYPE;
begin
    ret = row(1,2)::xyz;
    return ret;
end $$ language plpgsql;
```
It works on GP. Any suggestion on that?

**Comment by hlinnaka** [comment]
On 08/12/15 04:48, Kuien Liu wrote:
> in GPDB, below PLPGSQL throws out an error:
> __ERROR:  RETURN must specify a record or row variable in function returning tuple at or near "row"__
>
> ```sql
> create type xyz as (a int, b int);
> select row(1,2)::xyz;
> create or replace function return_xyz() returns xyz as $$ begin
>      return row(1,2)::xyz;
> end $$ language plpgsql;
> ```
> While in PG, it works well:
> ```sh
> test=# create or replace function return_xyz() returns xyz as $$ begin
> test$#     return row(1,2)::xyz;
> test$# end $$ language plpgsql;
> CREATE FUNCTION
> ```

This is a version difference, rather than GPDB vs PostgreSQL difference. 
The behaviour was changed in PostgreSQL 9.3, by this commit:

> commit 31a891857a128828d47d93c63e041f3b69cbab70
> Author: Tom Lane <tgl@sss.pgh.pa.us>
> Date:   Thu Dec 6 23:09:52 2012 -0500
>
>     Improve pl/pgsql to support composite-type expressions in RETURN.
>
>     For some reason lost in the mists of prehistory, RETURN was only coded to
>     allow a simple reference to a composite variable when the function's return
>     type is composite.  Allow an expression instead, while preserving the
>     efficiency of the original code path in the case where the expression is
>     indeed just a composite variable's name.  Likewise for RETURN NEXT.
>
>     As is true in various other places, the supplied expression must yield
>     exactly the number and data types of the required columns.  There was some
>     discussion of relaxing that for pl/pgsql, but no consensus yet, so this
>     patch doesn't address that.
>
>     Asif Rehman, reviewed by Pavel Stehule
>

So we'll get that eventually, when we merge with PostgreSQL 9.3.

- Heikki

**Comment by kuien** [comment]
Yes, you are right, Heikki. I found some similar things from web.
http://www.postgresql.org/message-id/flat/1492.1349708962@sss.pgh.pa.us#1492.1349708962@sss.pgh.pa.us

**Comment by danielgustafsson** [comment]
Closing this, once we merge 9.3 from upstream gpdb will support this.
