### ISSUE TITLE
SERIAL type could have decreasing values

### ISSUE THREAD

**Issue by huansong** [greenplum-db/gpdb#15837]
### Greenplum version or build
main branch (HEAD cb294b9987aae4fa994982168b7dd553291fc508)

### Expected behavior
The SERIAL column of a table should have increasing values for each new row. There could be gaps (i.e. some values are unused), but the general expectation seems to be that the next SERIAL number shouldn't go backward. According to the [PG doc](https://www.postgresql.org/docs/current/datatype-numeric.html#DATATYPE-SERIAL):
> This section describes a PostgreSQL-specific way to create an autoincrementing column

### Actual behavior
In some case we might see `INSERT` getting smaller SERIAL number than previous `INSERT`:
```sql
postgres=# create table t1(a int, id serial);
CREATE TABLE
postgres=# insert into t1 values(1);
INSERT 0 1
postgres=# insert into t1 select * from generate_series(2,4);
INSERT 0 3
postgres=# insert into t1 values(5);
INSERT 0 1
postgres=# insert into t1 values(6);
INSERT 0 1
postgres=# select * from t1;
 a | id
---+----
 1 |  1
 2 | 21
 3 | 22
 4 | 23
 5 |  2
 6 |  3
(6 rows)
```
This is probably related to #15204, where we increased the cache size of implicitly-created sequence number (including SERIAL) to 20. So we might be getting serial number from an "outdated" cache. Perhaps we should make sure we don't reuse a cache that has been used by the previous query?

**Comment by huansong** [comment]
cc @yanwr1 @adam8157

**Comment by vraghavan78** [comment]
This seems to work with GPORCA.

```sql
vraghavan=# drop table t1;
DROP TABLE
vraghavan=# create table t1(a int, id serial);
NOTICE:  Table doesn't have 'DISTRIBUTED BY' clause -- Using column named 'a' as the Greenplum Database data distribution key for this table.
HINT:  The 'DISTRIBUTED BY' clause determines the distribution of data. Make sure column(s) chosen are the optimal data distribution key to minimize skew.
CREATE TABLE
vraghavan=# insert into t1 values(1);
INSERT 0 1
vraghavan=# insert into t1 select * from generate_series(2,4);
INSERT 0 3
vraghavan=# insert into t1 values(5);
INSERT 0 1
vraghavan=# insert into t1 values(6);
INSERT 0 1
vraghavan=# select * from t1;
 a | id
---+----
 5 |  5
 6 |  6
 2 |  2
 3 |  3
 4 |  4
 1 |  1
(6 rows)
```

**Comment by vraghavan78** [comment]
I tried with Planner too it works. Do we a repro. Here is what I get w/ planner. 

```sql
vraghavan=# set optimizer =off;
SET
vraghavan=# drop table t1;
DROP TABLE
vraghavan=# create table t1(a int, id serial);
NOTICE:  Table doesn't have 'DISTRIBUTED BY' clause -- Using column named 'a' as the Greenplum Database data distribution key for this table.
HINT:  The 'DISTRIBUTED BY' clause determines the distribution of data. Make sure column(s) chosen are the optimal data distribution key to minimize skew.
CREATE TABLE
vraghavan=# insert into t1 values(1);
INSERT 0 1
vraghavan=# insert into t1 select * from generate_series(2,4);
INSERT 0 3
vraghavan=# insert into t1 values(5);
INSERT 0 1
vraghavan=# insert into t1 values(6);
INSERT 0 1
vraghavan=# select * from t1;
 a | id
---+----
 5 |  5
 6 |  6
 1 |  1
 2 |  2
 3 |  3
 4 |  4
(6 rows)
```

**Comment by hyongtao-db** [comment]
> I tried with Planner too it works. Do we a repro. Here is what I get w/ planner.

Hi Venky, I think it is a flaky case and strong ralated with time duration. Could you please try that _insert_, _wait a minute_ and _insert_ again.

**Comment by yanwr1** [comment]
after fix the issue #14851 , the serial performance is the same as the sequence.
the pg docs says about sequence:

> Furthermore, although multiple sessions are guaranteed to allocate distinct sequence values, the values might be generated out of sequence when all the sessions are considered. For example, with a cache setting of 10, session A might reserve values 1..10 and return nextval=1, then session B might reserve values 11..20 and return nextval=11 before session A has generated nextval=2. Thus, with a cache setting of one it is safe to assume that nextval values are generated sequentially; with a cache setting greater than one you should only assume that the nextval values are all distinct, not that they are generated purely sequentially. Also, last_value will reflect the latest value reserved by any session, whether or not it has yet been returned by nextval.

for above case , when execute single column insertion, show the  plan, they use  same qe(entry db) to generate nextval() value, when insert 5 and 6, the serial column was acquired from cache value(1,20).
```
postgres=# explain analyze insert into t1 values(6);
                                                        QUERY PLAN                                                         
---------------------------------------------------------------------------------------------------------------------------
 Insert on t1  (cost=0.00..0.02 rows=1 width=8) (actual time=0.000..0.897 rows=0 loops=1)
   ->  Result  (cost=0.00..0.00 rows=1 width=12) (actual time=0.844..0.845 rows=1 loops=1)
         ->  Redistribute Motion 1:3  (slice1)  (cost=0.00..0.00 rows=1 width=8) (actual time=0.841..0.842 rows=1 loops=1)
               Hash Key: (6)
               ->  Result  (cost=0.00..0.00 rows=1 width=1) (actual time=0.031..0.032 rows=1 loops=1)
 Optimizer: Pivotal Optimizer (GPORCA)
 Planning Time: 6.918 ms
   (slice0)    Executor memory: 36K bytes avg x 3 workers, 36K bytes max (seg0).
   (slice1)    Executor memory: 41K bytes (entry db).
 Memory used:  128000kB
 Execution Time: 1.810 ms
(11 rows)
```
-------
show the another plan for insert statement:
```
postgres=# explain analyze insert into t1 select * from generate_series(2,4);
                                                            QUERY PLAN                                                         
    
-------------------------------------------------------------------------------------------------------------------------------
----
 Insert on t1  (cost=0.00..15.68 rows=334 width=8) (actual time=0.000..0.151 rows=0 loops=1)
   ->  Result  (cost=0.00..0.05 rows=1000 width=12) (actual time=0.045..0.095 rows=3 loops=1)
         ->  Result  (cost=0.00..0.01 rows=1000 width=4) (actual time=0.010..0.013 rows=3 loops=1)
               ->  Function Scan on generate_series  (cost=0.00..0.00 rows=1000 width=4) (actual time=0.008..0.009 rows=3 loops
=1)
 Optimizer: Pivotal Optimizer (GPORCA)
 Planning Time: 7.070 ms
   (slice0)    Executor memory: 45K bytes avg x 3 workers, 63K bytes max (seg0).  Work_mem: 17K bytes max.
 Memory used:  128000kB
 Execution Time: 1.004 ms
(9 rows)
```
the nextval column is generated by another qe process (of writer gang), it first get netxtval() value from qd and then use the cache value(21,40).

**Comment by adam8157** [comment]
The sequence has the same issue, which "should be" auto-incrementing too.

To me, this issue is a performance trade-off, unless we change the codes to have a session-level sequence cache or something other, I prefer the current better performance behavior.

**Comment by huansong** [comment]
This issue is only repro'ed with ORCA. With planner the two INSERTs below have similar plans where all rows are generated on QD and then redistributed to the QEs. So the serial numbers in both INSERT are retrieved from QD's sequence cache. Therefore, no out-of-order serial number can be seen.
```sql
postgres=# set optimizer = false;
SET
postgres=# explain analyze insert into t1 values(1);
                                                            QUERY PLAN
----------------------------------------------------------------------------------------------------------------------------------
 Insert on t1  (cost=0.00..0.04 rows=1 width=8) (actual time=0.000..2.186 rows=0 loops=1)
   ->  Redistribute Motion 1:3  (slice1; segments: 1)  (cost=0.00..0.04 rows=1 width=8) (actual time=1.808..1.810 rows=1 loops=1)
         Hash Key: 1
         ->  Result  (cost=0.00..0.01 rows=1 width=8) (actual time=1.213..1.214 rows=1 loops=1)
 Optimizer: Postgres query optimizer
 Planning Time: 2.502 ms
   (slice0)    Executor memory: 37K bytes avg x 3 workers, 37K bytes max (seg0).
   (slice1)    Executor memory: 41K bytes (seg0).
 Memory used:  128000kB
 Execution Time: 47.763 ms
(10 rows)

postgres=# explain analyze insert into t1 select * from generate_series(1,10);
                                                            QUERY PLAN
----------------------------------------------------------------------------------------------------------------------------------
 Insert on t1  (cost=0.00..0.29 rows=3 width=8) (actual time=0.000..1.935 rows=0 loops=1)
   ->  Redistribute Motion 1:3  (slice1; segments: 1)  (cost=0.00..0.29 rows=3 width=8) (actual time=1.707..1.712 rows=5 loops=1)
         Hash Key: generate_series.generate_series
         ->  Function Scan on generate_series  (cost=0.00..0.15 rows=10 width=8) (actual time=0.189..0.679 rows=10 loops=1)
 Optimizer: Postgres query optimizer
 Planning Time: 0.529 ms
   (slice0)    Executor memory: 36K bytes avg x 3 workers, 36K bytes max (seg0).
   (slice1)    Executor memory: 62K bytes (seg0).  Work_mem: 17K bytes max.
 Memory used:  128000kB
 Execution Time: 4.203 ms
(10 rows)
```

> This seems to work with GPORCA

@vraghavan78  Just checking - are your running on the latest main? The corresponding commit after which this issue started to appear was a fairly recent one https://github.com/greenplum-db/gpdb/commit/5c153a0f7f14ec7ad281ba4f30117a6b583481f6.

**Comment by huansong** [comment]
> the pg docs says about sequence
>> Furthermore, although multiple sessions are guaranteed to allocate distinct sequence values, the values might be generated out of sequence when all the sessions are considered

Understood that upstream has documented a similar issue, but I think there are subtle differences about the current GPDB issue:
1. The current issue is about SERIAL type, which to a user is not equal to SEQUENCE (although internally they are) and might have different anticipation even in the documentation;
2. The current issue appears in **a single session**. I think to a user it is more easily understandable that parallel sessions could have out-of-order sequence/serial numbers, but it might be hard to anticipate that even a single session can do that.

That being said, I don't have enough experience to make a judgement call about the right user expectation, but just quoting from Louis Mugnano:
> From a user perspective (someone who has been developing on many databases over 30 years), gaps are normal with sequences / serial columns but having the number decrease is not normal and there could easily be assumptions that wouldn't be the case

**Comment by yanwr1** [comment]
> With planner the two INSERTs below have similar plans where all rows are generated on QD and then redistributed to the QEs. So the serial numbers in both INSERT are retrieved from QD's sequence cache.

the planner doesn't have the issue, it's not because they are all generated from QD,  they are all generated on the same QE process(of a 1-gang).

> The current issue appears in a single session. 

Yes, the issue happens in single session in GPDB, but gpdb is a mpp cluster, it will have multi QE to process the customer request, in some way, it's similar with the parallel session in postgres.

> it seems to me that since all the "original" sequence numbers are generated on QD in a single-threaded fashion, QD should have the knowledge about whether a cache is "outdated" or not. And in this case, if the QD gets sequence request from the QE and generates a bunch of new sequence numbers, the previous local cache that the QD keeps for itself should be regarded "outdated"


When a qe process first receive a nextval() value request, it will create a hash table, and send a nextval request to QD, after receive the nextval from QD, the sequence cache info will be stored in the hashtable entry. Before the cache value is exhausted, QE will use the cache value to return the nextval, it won't send request to QD again. 
Each QE process will create a sequence hash table, QD can't know which QE's cache is outdated. Also QD will always forward nextval cache numbers for QE's request, but it can't influence other QE's cache info. The sequence hash table will continue to exist on QE as long as the  QE process is not exit, it's different from parallel session in pg.

**Comment by ashwinstar** [comment]
Given the full clarity provided now for the issue, I would recommend we document the behavior properly similar to upstream and no fix is required for the same. Based on how tuples are hashed in GPDB, cached values for SERIAL even within same session can't be predicted and hence only DISTINCT aspect can be guaranteed (which seems reasonable).

Is this really new issue then, ideally with any cache setting higher than 1 any version of GPDB should exhibit this behavior right?

**Comment by adam8157** [comment]
> Is this really new issue then, ideally with any cache setting higher than 1 any version of GPDB should exhibit this behavior right?

As my understanding, with any cache setting higher than 1 any version of GPDB should exhibit this behavior.

**Comment by huansong** [comment]
> QD can't know which QE's cache is outdated

Ah I missed that. In that case, the only way to avoid the issue is let QE invalidate its own cache after every query. But that contradicts the performance goal and would cause a lot of waste in the sequence numbers.

I'm ok with no fix and documenting the limitation.

**Comment by huansong** [comment]
> Lets make sure someone is driving up to bring this to completion with crystal clear example in documentation for our users to understand the behavior and not assume on sequential aspect while coding application. Thanks

I've created an internal doc story with detailed descriptions.

This issue can be closed.
