### ISSUE TITLE
Sequence not collected in minirepro

### ISSUE THREAD

**Issue by lintzc** [greenplum-db/gpdb#15856]
## Bug Report
When a table has a sequence (not created by serial or bigserial), the sequence is ignored by minirepro.
It causes the failure of the run of the output query generated by minirepro.

### Greenplum version or build
GPDB 6.23.1 
### OS version and uname -a
Centos 7.8
Linux mdw 3.10.0-1127.18.2.el7.x86_64 #1 SMP Sun Jul 26 15:27:06 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

### Expected behavior
Collect the sequence used in nextval in the minirepro

### Actual behavior
The sequence DDL is not collected by minirepro

### Step to reproduce the behavior
[gpadmin@mdw tmp]$ psql -d uab_test <<EOF
drop schema prd_risk_alm cascade ;
create schema prd_risk_alm;
create sequence prd_risk_alm.seq_rowid_misys_bgpf;

CREATE TABLE prd_risk_alm.misys_bgpf (
    insertion_date date ,
    source_date double precision ,
    bgeqf character varying(2) ,
    rowid bigint DEFAULT nextval('prd_risk_alm.seq_rowid_misys_bgpf'::regclass) 
)  DISTRIBUTED RANDOMLY;
EOF
NOTICE:  drop cascades to 2 other objects
DETAIL:  drop cascades to sequence prd_risk_alm.seq_rowid_misys_bgpf
drop cascades to table prd_risk_alm.misys_bgpf
DROP SCHEMA
CREATE SCHEMA
CREATE SEQUENCE
CREATE TABLE
[gpadmin@mdw tmp]$ echo "select * from prd_risk_alm.misys_bgpf;" > /tmp/qry.sql
[gpadmin@mdw tmp]$ minirepro uab_test -q /tmp/qry.sql -f /tmp/minirepro_qry.sql
Connecting to database: host=mdw, port=6432, user=gpadmin, db=uab_test ...
Extracting metadata from query file /tmp/qry.sql ...
psql uab_test --pset footer --no-psqlrc -Atq -h mdw -p 6432 -U gpadmin -f /tmp/20230627030427/toolkit.sql
Invoking pg_dump to dump DDL ...
pg_dump -h mdw -p 6432 -U gpadmin -sxO uab_test --relation-oids 46928572 --function-oids 0 -f /tmp/20230627030427/pg_dump_out.sql
Writing schema DDLs ...
Writing relation and function DDLs ...
Writing table statistics ...
Writing column statistics ...
Attaching raw query text ...
--- MiniRepro completed! ---
WARNING: This tool collects statistics about your data, including most common values, which requires some data elements to be included in the output file.
Please review output file to ensure it is within corporate policy to transport the output file.
[gpadmin@mdw tmp]$ grep seq_rowid_misys_bgpf /tmp/minirepro_qry.sql 
    rowid bigint DEFAULT nextval('prd_risk_alm.seq_rowid_misys_bgpf'::regclass)

**Comment by kainwen** [comment]
@yanwr1 I think we need to backport this to 6X.

**Comment by kainwen** [comment]
Fixed by
* https://github.com/greenplum-db/gpdb/pull/16056 (main branch)
* https://github.com/greenplum-db/gpdb/pull/16089 (6x)
