### ISSUE TITLE
Results diff in regression isolation2/bitmap_index_concurrent

### ISSUE THREAD

**Issue by avamingli** [greenplum-db/gpdb#15919]
### Greenplum version or build

7x

### Step to reproduce the behavior

Run regression isolation2/bitmap_index_concurrent.

```diff
+++ /code/gpdb_src/src/test/isolation2/results/bitmap_index_concurrent.out	2023-07-05 14:25:16.122302084 +0800
@@ -325,7 +325,7 @@
 1<:  <... completed>
  count 
 -------
- 2201  
+ 2202  
 (1 row)
```
It belongs to 
>--
-- Test 2, run Index Scan on the bitmap index when there's backend
-- insert running.

Seems a flaky case,  only repro once, run regression again and  there is no diffs without any changes.

**Comment by vraghavan78** [comment]
Cannot repro.
