### ISSUE TITLE
Vacuum Analyze on AO table crash.

### ISSUE THREAD

**Issue by avamingli** [greenplum-db/gpdb#15916]
### Greenplum version or build

7x a171d183e3239d0b008466557a450e2aa7c3b208

### Step to reproduce the behavior

Use  steps  in issue https://github.com/greenplum-db/gpdb/issues/15914

Actually I want to have a try with that issue, but got coredump when exec `vacuum analyze t2i;`

<img width="1760" alt="image" src="https://github.com/greenplum-db/gpdb/assets/17311022/4479e217-f47a-4f1b-9b36-c6bdccd1d363">

<img width="1845" alt="image" src="https://github.com/greenplum-db/gpdb/assets/17311022/bc73986e-10b8-4dc0-a7c5-7e5daadf5a9c">

Not sure for that, checked the disk, there is still much space.
<img width="848" alt="image" src="https://github.com/greenplum-db/gpdb/assets/17311022/f16143f5-5d38-45dc-9c07-8ca6988930c3">

**Comment by haolinw** [comment]
Interesting, the `Assert(ao_vacuum_phase == VACOPT_AO_PRE_CLEANUP_PHASE || Gp_role != GP_ROLE_EXECUTE);` is obviously wrong as it should be at `VACOPT_AO_COMPACT_PHASE` phase at that moment. Forget why adding that assert previously.

**Comment by haolinw** [comment]
Haven't reproduced the issue so far. I always ended with "No space left..." but didn't see the subsequent fail assertion like above. The fix seems not that difficult but I would prefer to getting it reproduced before fixing it, as it is not that serious and happens in extreme circumstance. Curious about how to create a failure happened in different processes on the same segment in one vacuum operation.

@avamingli is this issue able to reproduced stably in your environment ? Will be very helpful if you can provide some distinct patterns to reproduce it.

**Comment by avamingli** [comment]
HI, rebase to main branch at commit 2bf59c40ffbba2e300fd5aca7555cb3865553134 , have another try and reproduce it.

<img width="1776" alt="image" src="https://github.com/greenplum-db/gpdb/assets/17311022/176ee43c-1f0f-4b20-9c46-aa3504a7ecb6">

<img width="1782" alt="image" src="https://github.com/greenplum-db/gpdb/assets/17311022/2b5249ed-64ce-43fa-9b43-993987a57325">


Init cluster using gpdemo.sh, 3 segments & 3 mirror on a local machine.
gpadmin@i-v3roa8c2:/var/crash$ uname -a
Linux i-v3roa8c2 5.15.0-25-generic #25-Ubuntu SMP Wed Mar 30 15:54:22 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

All I do is just copy the sql in issue #15914 
```sql
create table t2i (a int) with (appendonly=true, orientation=row, compresstype=zlib, compresslevel=3);
insert into t2i select i from generate_series(1,10000000)i;
insert into t2i select * from t2i;
insert into t2i select * from t2i;
insert into t2i select * from t2i;
insert into t2i select * from t2i;
insert into t2i select * from t2i;
insert into t2i select * from t2i;
insert into t2i select * from t2i;
select count(*) from t2i;
create index on t2i(a);
vacuum analyze t2i;
explain (analyze, buffers) select count(*) from t2i where a > 991243 and a < 1045762;
```

**Comment by haolinw** [comment]
Thanks, for quick check, could you also print out ao_vacuum_phase at that core stack ?

**Comment by avamingli** [comment]
> Thanks, for quick check, could you also print out ao_vacuum_phase at that core stack ?

<img width="1644" alt="image" src="https://github.com/greenplum-db/gpdb/assets/17311022/cabbfcbc-26a7-4b32-b9f5-34002041b1d8">

**Comment by haolinw** [comment]
Thanks, mine reported no space left when doing create index, as below:

<img width="1146" alt="image" src="https://github.com/greenplum-db/gpdb/assets/90174703/37b1c292-4c22-4928-b21f-2d82468d57bb">

<img width="1790" alt="image" src="https://github.com/greenplum-db/gpdb/assets/90174703/fa91eeb4-cb40-4f07-b5a8-0d1f38e6b8d0">

Did you see the "No space left" message core stack in the log ? It should be printed by default, please also paste it here if convenient for you then I can try to reproduce it by hacking the code at least.

**Comment by avamingli** [comment]
> Did you see the "No space left" message core stack in the log ? It should be printed by default, please also paste it here if convenient for you then I can try to reproduce it by hacking the code at least.

Sorry, I clear my env, I guess there should be.
By searching  the  error message, there is only one place with that message:
```c
could not extend file \"%s\": wrote only %d of %d bytes at block %u",
						FilePathName(v->mdfd_vfd),
```
in codes
```c

	if ((nbytes = FileWrite(v->mdfd_vfd, buffer, BLCKSZ, seekpos, WAIT_EVENT_DATA_FILE_EXTEND)) != BLCKSZ)
	{
		if (nbytes < 0)
			ereport(ERROR,
					(errcode_for_file_access(),
					 errmsg("could not extend file \"%s\": %m",
							FilePathName(v->mdfd_vfd)),
					 errhint("Check free disk space.")));
		/* short write: complain appropriately */
		ereport(ERROR,
				(errcode(ERRCODE_DISK_FULL),
				 errmsg("could not extend file \"%s\": wrote only %d of %d bytes at block %u",
						FilePathName(v->mdfd_vfd),
						nbytes, BLCKSZ, blocknum),
				 errhint("Check free disk space.")));
	}
```
If write some bytes nbytes > 0 , it will get that errors, else the errors maybe as yours, it depends on left space on disk when writing the last block.

And did you config enable assertion?

**Comment by haolinw** [comment]
Yes, I did, you can see the time spending, if I didn't enable assertion, the time spending will be much faster.

**Comment by haolinw** [comment]
> If write some bytes nbytes > 0 but not enough for a BLOCKSZ, it will get that errors, else the errors maybe as yours, it depends on left space on disk when writing the last block.

Yes, this need create a proper size of file on disk to occupy spaces, as tune this size might be tricky and has various possibilities that does't hit the issue, so if you have and provide the core stack or later when you repro the case again, I can hack the code base on that to force it failed at that point. Meanwhile, I will tune the size before getting that info.

**Comment by haolinw** [comment]
Finally, I can reproduce the issue by leaving the disk space around 67G with 3p3m cluster configuration. The "No space left" happened at create index, and the FailedAssertion happened at vacuum statement, they were in serialized steps. The log has more information after create index failure, like `requesting fts retry as mirror didn't connect yet but in grace period: 10"` and `signaling configuration reload: setting synchronous_standby_names to ''` before failed assertion, which looks more complicate than thought. Will dig more.

**Comment by haolinw** [comment]
RCA is no disk space left caused mirror startup process failed to do replay and exited, result in the whole mirror instance down, and finally FTS probe threshold exceeded, leading to FTS version changed which matches the condition to close the old CDB connection and open a new one at the next DTX start (vacuum post-cleanup in this case). Then new QE process with NULL vacrelstats in the vacuum post-cleanup phase failed the assertion.

**Comment by haolinw** [comment]
Using `gprecoverseg -a` could workaround as my local test once obtained enough disk space.
