### ISSUE TITLE
"gprecoverseg --differential" would generate extra wal files and never release 

### ISSUE THREAD

**Issue by krun2010qq** [greenplum-db/gpdb#15952]
### Greenplum version or build

Greenplum Database 7.0.0-beta.4

### OS version and uname -a

Linux cdw7 4.18.0-425.3.1.el8.x86_64 #1 SMP Fri Sep 30 11:45:06 EDT 2022 x86_64 x86_64 x86_64 GNU/Linux

### autoconf options used ( config.status --config )
NA
### Installation information ( pg_config )
NA

### Expected behavior

The wal files' size should be under the GUC `max_wal_size` 

### Actual behavior

Primary segment keep generating the wal files and never rotate

### Step to reproduce the behavior
-- Stop the mirror
-- Run the gprecoverseg --differential"
-- Attach the GDB to the rsync process on the primary segment. This step I did was trying to simulate the rsync slowness(Later I found this step is not necessary; without this step, the "differential recover" would also keep generating the wals) 
-- After the segment got recovered, the unnecessary wal files would not be deleted and ultimately make the disk out of space.

**Comment by krun2010qq** [comment]
I found that the GDB step is still necessary:

`[gpadmin@sdw1 ~]$ cat attach_gdb.sh
#!/bin/bash

# Check if rsync process is running
if pgrep rsync > /dev/null; then
    echo "rsync process found. Attaching gdb..."

    # Get the process ID of rsync
    rsync_pid=$(pgrep rsync)

    # Attach gdb to the rsync process
    gdb -p $rsync_pid
else
    echo "No rsync process found."
fi`

We need to GDB attach to the rsync process and wait for the wal files size on primary to be bigger than `max_wal_size`

**Comment by ashwinstar** [comment]
> After the segment got recovered, the unnecessary wal files would not be deleted and ultimately make the disk out of space

While the rsync is running WAL files will be collected and not deleted. That's functioning as designed.

Wish to make sure did you validate after mirror connected to primary post recovery and data from primary to mirror started to sync - still the files on primary were not deleted? As WAL files on primary will only be deleted once mirror successfully connects to primary.

**Comment by shrakesh** [comment]
### RCA: 
1. Firstly checked the pg_replication_slots table post differential recovery. 
```
          slot_name           | plugin | slot_type | datoid | database | temporary | active | active_pid | xmin | catalog_xmin | restart_lsn | confirmed_flush_lsn | wal_status | safe_wal_size
-------------------------------+--------+-----------+--------+----------+-----------+--------+------------+------+--------------+-------------+---------------------+------------+---------------
internal_wal_replication_slot |        | physical  |        |          | f         | f      |            |      |              | 1/A0000028  |                     | extended   |
```

in the table for the slot active was false, and restart_lsn was updated to last checkpoint, was not updating when the load was coming.  

2. verified that the walsender and walreceiver process was running. 
```
[~/workspace/gpdb: {diff_performance} ?]$ ps -ef | grep walsender
  501 62956 62929   0  8:12PM ??         0:00.03 postgres:  7002, walsender shrakesh 127.0.0.1(52393) streaming 4/E16AD98
  
[~/workspace/gpdb: {diff_performance} ?]$ ps -ef | grep walreceiver
  501 62955 62934   0  8:12PM ??         0:00.47 postgres:  7005, walreceiver   streaming 4/E16AD98
```

3. verified the replication on pg_stat_replication, the state was shwoing streaming (something like shown below table, taken from different session so pid and lsn might differ)
```
[~/workspace/gpdb/gpMgmt: {diff_performance} ?]$ psql -c "select * from gp_dist_random('pg_stat_replication')"
  pid  | usesysid | usename  | application_name | client_addr | client_hostname | client_port |          backend_start           | backend_xmin |   state   |  sent_lsn  | write_lsn  | flush_lsn  | replay_lsn | write_lag | flush_lag | replay_lag | sync_priority | sync_state |            reply_time
-------+----------+----------+------------------+-------------+-----------------+-------------+----------------------------------+--------------+-----------+------------+------------+------------+------------+-----------+-----------+------------+---------------+------------+----------------------------------
 73552 |       10 | shrakesh | gp_walreceiver   | 127.0.0.1   |                 |       56139 | 2023-07-11 23:55:33.642063+05:30 |              | streaming | 5/BC000060 | 5/BC000060 | 5/BC000060 | 5/BC000060 |           |           |            |             1 | sync       | 2023-07-11 23:58:04.230946+05:30
 29480 |       10 | shrakesh | gp_walreceiver   | 127.0.0.1   |                 |       54595 | 2023-07-11 22:30:36.53532+05:30  |              | streaming | 5/AE678640 | 5/AE678640 | 5/AE678640 | 5/AE678640 |           |           |            |             1 | sync       | 2023-07-11 23:58:03.451138+05:30
 29488 |       10 | shrakesh | gp_walreceiver   | 127.0.0.1   |                 |       54596 | 2023-07-11 22:30:36.570468+05:30 |              | streaming | 5/AE955C28 | 5/AE955C28 | 5/AE955C28 | 5/AE955C28 |           |           |            |             1 | sync       | 2023-07-11 23:58:03.626321+05:30
```

was not sure why it is happening, did some debug sessions and found that the postgresql.auto.conf generated after differential recovery was missing the information about primary_slot_name = 'internal_wal_replication_slot'
this setting is required to specify an existing replication slot to be used when connecting to the sending server via streaming replication to control resource removal on the primary. 

***Why it is not appending primary_slot_name to postgresql.auto.conf ?***

when we run pg_basebackup with --write-conf-file option it generates the recovery conf file ( postgresql.auto.conf) and internal.auto.conf. postgresql.auto.conf contains the replication details. 
but in the function GenerateRecoveryConfig() there is a check 
```
if (replication_slot)
{
	/* unescaped: ReplicationSlotValidateName allows [a-z0-9_] only */
	appendPQExpBuffer(contents, "primary_slot_name = '%s'\n",
					  replication_slot);
}
```

As we are not providing slot name while running pg_basebackup with --write-conf-files-only option it was not able to append the primary_slot_name info. 

***Fix***:  
updated differential recovery code to run pg_basebackup with --slot option along with --write-conf-files-only to generate the correct postgresql.auto.conf file.

**Comment by shrakesh** [comment]
PR open: 
https://github.com/greenplum-db/gpdb/pull/15981
