### ISSUE TITLE
[Question] Difference between eternal and foreign table in the latest version

### ISSUE THREAD

**Issue by LonwoLonwo** [greenplum-db/gpdb#15950]
Hello, team!

I have a question.
According to this comment:
https://github.com/greenplum-db/gpdb/commit/b62e06014d1237ab9b3657e30609d2630954134d

now the external tables are abolished and turned into foreign tables?

But I can see the different syntax for these tables in your docs:

https://docs.vmware.com/en/VMware-Greenplum/7/greenplum-database/ref_guide-sql_commands-CREATE_FOREIGN_TABLE.html

https://docs.vmware.com/en/VMware-Greenplum/7/greenplum-database/ref_guide-sql_commands-CREATE_EXTERNAL_TABLE.html

How can I understand now - what table was created by the user? From the system tables/views?
 Previously I used data from the "pg_exttable" table. Now I only have `pg_catalog.pg_class.relkind` column with the "f" value for external and foreign tables.

So, I'm confused. Please, help me.

**Comment by ashwinstar** [comment]
External table is just syntactic sugar on-top of foreign tables for gpdb7. Internally everything is stored and processed as foreign table only.

So, only for legacy purposes use external tables till not able to modify legacy application. All need new code should just use foreign table directly.

**Comment by ashwinstar** [comment]
@adam8157 any pointers aware of to provide here?

**Comment by adam8157** [comment]
> External table is just syntactic sugar on-top of foreign tables for gpdb7. Internally everything is stored and processed as foreign table only.

Correct.

> About readable/writable status? About formatting, encoding, etc., to create the correct table DDL? Only from [ftoptions](https://docs.vmware.com/en/VMware-Greenplum/6/greenplum-database/ref_guide-system_catalogs-pg_foreign_table.html)?

Greenplum 7 still provides the legacy external table syntax and the `pg_exttable` (it's a view now).

If you are developing an extension manipulating the external data, external table and foreign table API both work on Greenplum 7. We recommend you use the new foreign table API and query `pg_foreign_table` and its `ftoptions`.

ref: https://github.com/greenplum-db/gpdb/pull/10015

**Comment by LonwoLonwo** [comment]
Thanks for clarifying!
