### ISSUE TITLE
Why Greenplum 6 does not support autovacuum,then greenplum 7 support?

### ISSUE THREAD

**Issue by yzsdb** [greenplum-db/gpdb#16144]
## Bug Report
GP7 support autovacuum ,but GP6 does not.

**Comment by ashwinstar** [comment]
GPDB7 is net new major version based on PG12. Has lot of newer features which GPDB6 doesn't. With major version there are lot of enhancements to vacuum and auto-vacuum framework which helped us to enable autovacuum for catalog tables in GPDB7.
