### ISSUE TITLE
Confused with DATA_DIRECTORY settings

### ISSUE THREAD

**Issue by flyly0755** [greenplum-db/gpdb#16169]
## Enhancement
With https://docs.vmware.com/en/VMware-Greenplum/6/greenplum-database/install_guide-init_gpdb.html#topic8 this guide topic,
4 hosts and 8 network interfaces(2 per host)

> sdw1-1
> sdw1-2
> sdw2-1
> sdw2-2
> sdw3-1
> sdw3-2
> sdw4-1
> sdw4-2

but DATA_DIRECTORY with 6 paths,
 

> declare -a DATA_DIRECTORY=(/data1/primary /data1/primary /data1/primary /data2/primary /data2/primary /data2/primary)

How is the relation between 6 paths and 4 hosts?

If the cluster with 1 masters and 2 segment hosts, can I set DATA_DIRECTORY as below ?
 declare -a DATA_DIRECTORY=(/xxx/primary) ----2 segments both with standalone /xxx/primary path.

**Comment by kainwen** [comment]
Master (or Cooridnator)'s data directory is `MASTER_DIRECTORY`.   The length of `DATA_DIRECTORY` is how many segments are there in a single segment host. And hostnames are passed via cmdline of `gpinitsystem`.

I don't see any confusion. Close this issue. Feel free to discuss here if you have more questions.

**Comment by flyly0755** [comment]
> Master (or Cooridnator)'s data directory is `MASTER_DIRECTORY`. The length of `DATA_DIRECTORY` is how many segments are there in a single segment host. And hostnames are passed via cmdline of `gpinitsystem`.
> 
> I don't see any confusion. Close this issue. Feel free to discuss here if you have more questions.

So here means with 4 hosts，every hosts with 6 segments, every host with dir path like 
/data1/primary/gpseg0 
/data1/primary/gpseg1  
/data1/primary/gpseg2  
/data2/primary/gpseg3  
/data2/primary/gpseg4  
/data2/primary/gpseg5 
?

**Comment by flyly0755** [comment]
> 

got it, thx! But i think maybe this point need more detail explain in the install guide page, so can better understand the logic.

> declare -a DATA_DIRECTORY=(/data1/primary /data1/primary /data1/primary /data2/primary /data2/primary /data2/primary)
Maybe with such config as below,
 

> declare -a DATA_DIRECTORY=(/data1/primary  /data2/primary)

>  declare -a SEGMENT_NUMBER=6

seems more reasonable:) every host with 2 data dir, and total 6 segments on this 2 data dirs, so 3 segments with 1 data dir(6/2)
This is really counter-intuitive with (/data1/primary /data1/primary /data1/primary /data2/primary /data2/primary /data2/primary)   :(

**Comment by flyly0755** [comment]
At the same time, I am confused with these 2 paths(data1, data2),
Why with 2 data dirs in one hosts instead of one data dir, what is the purpose?
As Far as I Know, the mirror data dir is use for data backup, the data in every DATA_DIRECTORY segments dir is different(load share mode).
If I want to create 6 segments in one host, whether all use data1 is OK?

> declare -a DATA_DIRECTORY=(/data1/primary /data1/primary /data1/primary /data1/primary /data1/primary /data1/primary)

I am rookie in greenplum, sorry for these base doubt.

**Comment by kainwen** [comment]
> Why with 2 data dirs in one hosts instead of one data dir, what is the purpose?

Different data dirs means you can have different disk hardwares for segments, which will benefit IO performance.

**Comment by flyly0755** [comment]
> > Why with 2 data dirs in one hosts instead of one data dir, what is the purpose?
> 
> Different data dirs means you can have different disk hardwares for segments, which will benefit IO performance.

Thank you so much, answered all my doubts. Linux machine may mount several disk hardwares, if want to store data on multiple disk hardwares on one host, so can use multiple data dirs to distinguish different disk, right?
At the same time, the better solution is to set multiple network interfaces on one host to map multiple disk hardwares for better IO performance，
for example sdw1-1, sdw1-2 these 2  network interfaces both belong to host sdw1, so with /data1/primary dir to map NI sdw1-1, 
and /data2/primary to map NI sdw1-2, right?

**Comment by kainwen** [comment]
> Linux machine may mount several disk hardwares, if want to store data on multiple disk hardwares on one host, so can use multiple data dirs to distinguish different disk, right?

Correct.

---------

> At the same time, the better solution is to set multiple network interfaces on one host to map multiple disk hardwares for better IO performance，

I don't have much experience on this topic and I don't understand how disk map with network interface. Normally there can be 2 network interfaces with high speed in each GPDB cluster host.
