### ISSUE TITLE
gpinitsystem initialize database which hang on Waiting for parallel processes step

### ISSUE THREAD

**Issue by flyly0755** [greenplum-db/gpdb#16206]
## Bug Report
Use normal no-root account to install standalone gp database environment, first extra file from rpm package
```shell
rpm2cpio open-source-greenplum-db-6.22.3-rhel7-x86_64.rpm | cpio -idv
```
after finish all kinds of linux configure, then use cmd below to initailize 
```shell
gpinitsystem  -c **configpath**
```
but stuck with output  as below, approximately every second output one . char and never stop
```shell
[INFO]:-Waiting for parallel processes batch [1], please wait...
.user@machineip's password: .............................................................
```
I am confused why with persistent . output when need to input password.
At same time, why need input so many times password, before encount this problem i had input 9 times same linux account password(every time with correct password, coz if input wrong password, will raise password wrong warining). 9 times  with sometimes user@ip, sometime user@hostname
### Greenplum version or build
both gpdb-6.22.3 and gpdb-6.13.0
 
### OS version and uname -a
Linux 3.10.0-1160.59.1.el7.x86_64 #1 SMP Wed Feb 23 16:47:03 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by ashwinstar** [comment]
The pre-requirement is to have passwd less SSH setup between hosts to avoid need for keying passwd [Enabling Passwordless SSH](https://docs.vmware.com/en/VMware-Greenplum/7/greenplum-database/install_guide-install_gpdb.html#topic_xmb_gb5_vhb)

**Comment by flyly0755** [comment]
> The pre-requirement is to have passwd less SSH setup between hosts to avoid need for keying passwd [Enabling Passwordless SSH](https://docs.vmware.com/en/VMware-Greenplum/7/greenplum-database/install_guide-install_gpdb.html#topic_xmb_gb5_vhb)

thx! got it. But I think maybe add some passwd less setup tips is better when executing gpinitsystem cmd  without passwd less setup before.
