### ISSUE TITLE
[Feature] The Java server implementation of gpfdist allows us to easily import and export large data

### ISSUE THREAD

**Issue by laglangyue** [greenplum-db/gpdb#16205]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Sometimes we need to import and export large data, and currently we can only use the greenplum park connector. However, there are some issues, such as binary data or special data processing. However, GSC is not open source and we cannot modify its code.
Or in other scenarios, for seatunnel or other data platforms, we cannot import or export large data and can only use the jdbc protocol

**Describe the feature you'd like to request:**
The Java server implementation of gpfdist allows us to easily import and export large data!

**Comment by bradfordb-vmware** [comment]
Greenplum's [Platform Extension Framework (PXF)](https://github.com/greenplum-db/pxf) is open source and can be used to read and write external data files. Have you looked at using PXF for your import and export work?
