### ISSUE TITLE
Reading files with line ending 'CR' does not read anything

### ISSUE THREAD

**Issue by andreasscherbaum** [greenplum-db/gpdb#1621]
An external table with the file:// protocol, and

```
NEWLINE AS 'CR'
```

Does not read any data:

```
DROP EXTERNAL TABLE IF EXISTS file_test_ext_crlf_read;
CREATE READABLE EXTERNAL TABLE file_test_ext_crlf_read (
  LIKE file_test_int
)
LOCATION ('file://gpdb:40000/data/source/external_table_file_data_cr.csv')
FORMAT 'CSV' (HEADER DELIMITER AS ',' NEWLINE AS 'CR');
```

```
SELECT gp_segment_id, * FROM file_test_ext_crlf_read;
 gp_segment_id | id | data 
---------------+----+------
(0 rows)
```

The file *external_table_file_data_cr.csv* is 10 lines (plus header) in CR line endings.

**Comment by andreasscherbaum** [comment]
Data Files:
https://drive.google.com/open?id=0B0YS4ec0zw70cm16UjM0aklRSnM
https://drive.google.com/open?id=0B0YS4ec0zw70cXRGZ05wd3pUNkk
https://drive.google.com/open?id=0B0YS4ec0zw70U3BZSzJhR25DaEE

**Comment by asimrp** [comment]
@HaozhouWang can this issue be closed?  You seem to have merged a fix already.  If so, please close this issue.

**Comment by HaozhouWang** [comment]
@asimrp Yes, this issue has been fixed. I close it now.
Thanks!
