### ISSUE TITLE
executing 'gpinitsystem -c gpinitsystem_config' outputs export: command not found and so on, then initialize databse failed

### ISSUE THREAD

**Issue by flyly0755** [greenplum-db/gpdb#16228]
## Bug Report
check SHELL is /bin/bash, then executing 'gpinitsystem -c gpinitsystem_config' with output  export: command not found
and ulimit: Command not found and
xxx/bin/postgres: error while loading shared libraries: libxerces-c-3.1.so 
check shell is /bin/bash(echo $0), and command ulimit and export both exist.
and ldd postgres can find libxerces-c-3.1.so 
seems some inner init script uses other SHELL(maybe csh, under csh SHELL without ulimit and export instead of setenv), but I am not sure about it, need your guys' help to debug it, thx!
### Greenplum version or build
both 6.22.3 and 6.13.0

**Comment by ashwinstar** [comment]
Please can you provide the output of gpinitsystem with errors.

No other shell is used bash is used by gpinitsystem. Hoping greenplum_path.sh was sourced.

**Comment by flyly0755** [comment]
> Please can you provide the output of gpinitsystem with errors.
> 
> No other shell is used bash is used by gpinitsystem. Hoping greenplum_path.sh was sourced.

sorry about that, install in another machine, cannot got the full output.
But I am sure, I have sourced greenplum_path.sh before gpinitsystem process.

**Comment by flyly0755** [comment]
After debug, found issue occured with method CHK_OPEN_FILES in file bin/gpinitsystem
**OPEN_VALUE=$( REMOTE_EXECUTE_AND_GET_OUTPUT $1 "ulimit -n" )**
this line, REMOTE_EXECUTE_AND_GET_OUTPUT seems meaning execute ulimit -n in another, which means run in a new shell vironment, right? maybe this new shell vironment uses /bin/csh by default(coz the terminal that i trigger command ''gpinitsystem -c gpinitsystem_config' use /bin/csh, i just changed to /bin/bash before run this commmand)
```shell
CHK_OPEN_FILES () {
	LOG_MSG "[INFO]:-Start Function $FUNCNAME"
	LOG_MSG "[INFO]:-Checking $1"
	**OPEN_VALUE=$( REMOTE_EXECUTE_AND_GET_OUTPUT $1 "ulimit -n" )**
	if [ $OPEN_VALUE -lt $OS_OPENFILES ];then
		LOG_MSG "[WARN]:-Host $1 open files limit is $OPEN_VALUE should be >= $OS_OPENFILES" 1
		EXIT_STATUS=1
		ULIMIT_WARN=1
	fi
	LOG_MSG "[INFO]:-End Function $FUNCNAME"
}
```

**Comment by shrakesh** [comment]
@flyly0755  try these steps: 
1.  set the default shell to bash for that you can run 
    `chsh -s /bin/bash` 
 2.  source ~/.bashrc   or start a new shell.  
 3.  source greenplum_path.sh 
 4. try gpinitsystem 

 if you still facing issues with the above-listed env.
 5.   try updating file limits to unlimited 
      `ulimit -f unlimited`

**Comment by flyly0755** [comment]
> 1. chsh

bingo, thank you so much! There are no more command not found issue
but now occured with a new issue, seems hang on with REMOTE_EXECUTE_AND_GET_OUTPUT(log stop at Start Function REMOTE_EXECUTE_AND_GET_OUTPUT), maybe can't connect remote machine. but what i install is standalonewe mode just with one machine:( very weird seems like.

**Comment by flyly0755** [comment]
With further debug, located the code line that hang with:

> SEG_HOSTNAME=$( REMOTE_EXECUTE_AND_GET_OUTPUT $MHOST "$HOSTNAME" )
line 600 in file gpinitsystem
and method defined in gp_bash_functions.sh
```shell
REMOTE_EXECUTE_AND_GET_OUTPUT () {
  INITIAL_DEBUG_LEVEL=$DEBUG_LEVEL
  DEBUG_LEVEL=0

  LOG_MSG "[INFO]:-Start Function $FUNCNAME"
  HOST="$1"
  CMD="echo 'GP_DELIMITER_FOR_IGNORING_BASH_BANNER';$2"
  OUTPUT=$( $TRUSTED_SHELL "$HOST" "$CMD" | $AWK '/^GP_DELIMITER_FOR_IGNORING_BASH_BANNER/ {seen = 1} seen {print}' | $TAIL -n +2 )
  RETVAL=$?
  if [ $RETVAL -ne 0 ]; then
 
     LOG_MSG "[FATAL]:- Command $CMD on $HOST failed with error status $RETVAL" 2
  else
     LOG_MSG "[INFO]:-Completed $TRUSTED_SHELL $HOST $CMD"
  fi
  LOG_MSG "[INFO]:-End Function $FUNCNAME"

  DEBUG_LEVEL=$INITIAL_DEBUG_LEVEL
  #Return output
  echo "$OUTPUT"
}
```

**Comment by shrakesh** [comment]
@flyly0755 what I feel is the env included passwordless connection is not properly set up in your system. I would ask you to go through your platform-specific readme **README.platform.md** file for the instruction. 
you may initially try with demo cluster creation the script and instruction for which is available on https://github.com/greenplum-db/gpdb/tree/main/gpAux/gpdemo
please let me know if you face any issues with that.

**Comment by flyly0755** [comment]
@shrakesh The root cause of this issue is default shell configuration. The machine i used is configued with csh default, i change it to bash with some other method(at the last line of ~/.cshrc add bash) instead of **chsh -s /bin/bash** method(without enough permission so can't use chsh to change). During database init every time ssh remote operation fisrt still use csh, than change to bash(use ps command can found both chs and bash records), but can't get back from sub-process successfully after the remote operation(normal situation is ssh-->bash run-->exit ssh, what i occured is ssh-->default csh-->change to bash-->bash run-->exit ssh failed,stuck here)

**Comment by flyly0755** [comment]
And now i take a try with link https://github.com/greenplum-db/gpdb/tree/main/gpAux/gpdemo to install a demo cluster, but with some question.
First i think this demo cluster is installed from src code, right?
Then with step --> 3. Source greenplum_path.sh

	. /usr/local/gpdb/greenplum_path.sh

Can't find greenplum_path.sh in gpdb-6.22.3.zip this compressed file. 
Then i find it somewhere and copy it under decompressed gpdb-6.22.3 dir.
But in step --> 4. Create the cluster:

	make cluster

raise error xxx/gpMgmt/bin/lib/gp_bash_version.sh: No such file or directory, so i check the lib dir but found gp_bash_version.sh.in file, I don't know the difference between sh and sh.in files, but I think the content in these 2 files are some, so I copy a gp_bash_version.sh file from gp_bash_version.sh.in.
And try  it again, but with new error, 
```log
[WARN]: -No inindb file, unable to verify id
[INFO]: -Checking configuration parameters, please wait...
[FATAL]: -Unable to locate initdb Script Exiting!
==========================
gpinitsystem returned: 2
```

**Comment by flyly0755** [comment]
I think maybe can consider add shell type check to solve this issue.
When ssh operation, first check whether shell after ssh is bash, if it isn't bash, then change to bash, and after ssh operation, need to consider jump back instead of stuck there.
