### ISSUE TITLE
gpstop may create lock file in wrong path

### ISSUE THREAD

**Issue by jimmyyih** [greenplum-db/gpdb#16283]
### Greenplum version or build
The commit that created the minor regression:
https://github.com/greenplum-db/gpdb/commit/a4c9e2d37eb5f10b9902b250b8d0f1d801736686.

### Expected behavior
gpstop will create the lock file in the coordinator's data directory.

### Actual behavior
gpstop will create the lock file only in $COORDINATOR_DATA_DIRECTORY or $MASTER_DATA_DIRECTORY.  Or fail to run if the environment variable is not set.

### Step to reproduce the behavior
1. Create gpdemo cluster (with or without mirrors, it doesn't matter).
2. Source gpdemo env file.
3. Save the $COORDINATOR_DATA_DIRECTORY (e.g. copy it into clipboard or store it in a local env var)
4. Set the $COORDINATOR_DATA_DIRECTORY to `/tmp` (or wherever you want to observe).
5. Run `gpstop -d /saved/real/coordinator/data/directory/path`

The gpstop lock file will be created in `/tmp` instead of the explicit coordinator data directory provided by the user with the `-d` flag.  If you don't have $COORDINATOR_DATA_DIRECTORY set, gpstop will fail which is probably the bigger issue.

---

Although this is a minor regression to gpstop, it actually revealed that this has been a long hidden bug in our Python utilities that utilize the common `-d` flag and depend on lockfile creation.  To visualize the issue, the flow goes like this:
* Utility calls `simple_main()` with `pidlockpath` main option.
    - Finding the `pidlockpath` main option, it will then create the lock via `SimpleMainLock()`
        - pidlock path is obtained via `gp.get_coordinatordatadir()` which only gets the data directory path from the environment.
    - Afterwards, the user-provided args are parsed.

It seems to be a design issue from early Greenplum days where `-d` flag and the locking do not match up unless the `-d` input is the same value as the environment variable.  The `-d` flag is pretty much useless in this situation.

The affected utilities currently in main are gpstop, gpstart (calls gpstop), and potentially gprecoverseg.

This issue was found from a test that uses `gpstart -d` to start up multiple GPDB clusters for test parallelization.

**Comment by jimmyyih** [comment]
Easy fix could be to move the locking to after parsing the user-provided utility args so that we always have the correct coordinator data directory.  But not sure the repercussions of doing that or why it was designed like this in the first place.

**Comment by jimmyyih** [comment]
This should presumably be fixed with https://github.com/greenplum-db/gpdb/pull/16433.

**Comment by ashwinstar** [comment]
Just to state explicitly gpstart and gpstop used to work fine with `-d` option without setting the `MASTER_DATA_DIRECTORY` env variable and after commit a4c9e2d it doesn't. Hence its a regression and lets fix it.

**Comment by shrakesh** [comment]
@ashwinstar Yes for gpstop and gpstart it is a regression caused by commit https://github.com/greenplum-db/gpdb/commit/a4c9e2d37eb5f10b9902b250b8d0f1d801736686.
