### ISSUE TITLE
GPCHECKPERF has a problem

### ISSUE THREAD

**Issue by Qfur890416** [greenplum-db/gpdb#16356]
## Bug Report
While using gpcheckperf to check hardware performance,
gpdb-6.23.5  gpcheckperf's result is accpetable, 
but in the same machine,
gpdb-6.25.1 gpcheckperf's result is unacceptable
### Greenplum version or build
GPDB-6.25.1
### OS version and uname -a
centos 7.9
Linux mdw 3.10.0-1160.el7.x86_64 #1 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
### autoconf options used ( config.status --config )
none
### Installation information ( pg_config )

[root@mdw ~]# /usr/local/greenplum-db-6.25.1/bin/pg_config
BINDIR = /usr/local/greenplum-db-6.25.1/bin
DOCDIR = /usr/local/greenplum-db-6.25.1/share/doc/postgresql
HTMLDIR = /usr/local/greenplum-db-6.25.1/share/doc/postgresql
INCLUDEDIR = /usr/local/greenplum-db-6.25.1/include
PKGINCLUDEDIR = /usr/local/greenplum-db-6.25.1/include/postgresql
INCLUDEDIR-SERVER = /usr/local/greenplum-db-6.25.1/include/postgresql/server
LIBDIR = /usr/local/greenplum-db-6.25.1/lib
PKGLIBDIR = /usr/local/greenplum-db-6.25.1/lib/postgresql
LOCALEDIR = /usr/local/greenplum-db-6.25.1/share/locale
MANDIR = /usr/local/greenplum-db-6.25.1/man
SHAREDIR = /usr/local/greenplum-db-6.25.1/share/postgresql
SYSCONFDIR = /usr/local/greenplum-db-6.25.1/etc/postgresql
PGXS = /usr/local/greenplum-db-6.25.1/lib/postgresql/pgxs/src/makefiles/pgxs.mk
CONFIGURE = '--disable-debug-extensions' '--disable-tap-tests' '--enable-orca' '--with-zstd' '--with-gssapi' '--with-libxml' '--with-perl' '--with-python' '--with-openssl' '--with-pam' '--with-ldap' '--with-pythonsrc-ext' '--with-uuid=e2fs' '--with-extra-version= Open Source' '--prefix=/usr/local/greenplum-db-6.25.1' '--mandir=/usr/local/greenplum-db-6.25.1/man' 'CC=gcc' 'CFLAGS=-O3 -fargument-noalias-global -fno-omit-frame-pointer -g'
CC = gcc
CPPFLAGS = -D_GNU_SOURCE -I/usr/include/libxml2 -I/usr/local/greenplum-db-6.25.1/include
CFLAGS = -Wall -Wmissing-prototypes -Wpointer-arith -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fno-aggressive-loop-optimizations -Wno-unused-but-set-variable -Wno-address -O3 -fargument-noalias-global -fno-omit-frame-pointer -g -std=gnu99 -Werror=uninitialized -Werror=implicit-function-declaration -I/usr/local/greenplum-db-6.25.1/include
CFLAGS_SL = -fPIC
LDFLAGS = -Wl,--as-needed -Wl,-rpath,'/usr/local/greenplum-db-6.25.1/lib',--enable-new-dtags -L/usr/local/greenplum-db-6.25.1/lib
LDFLAGS_EX =
LDFLAGS_SL =
LIBS = -lpgcommon -lpgport -lxerces-c -lxml2 -lpam -lrt -lgssapi_krb5 -lzstd -lrt -lcrypt -ldl -lm -L/usr/local/greenplum-db-6.25.1/lib
VERSION = PostgreSQL 9.4.26

### Expected behavior
![image](https://github.com/greenplum-db/gpdb/assets/124649613/2ae11706-6943-488b-8ef4-8c8b84c5fe12)
![image](https://github.com/greenplum-db/gpdb/assets/124649613/8bddb2b2-9331-470b-849f-f5e91d39766d)

### Actual behavior
![image](https://github.com/greenplum-db/gpdb/assets/124649613/1c2e170f-14ff-4b3a-8c14-c2ed577d6cd5)
![image](https://github.com/greenplum-db/gpdb/assets/124649613/4c279d8d-a5d4-4aa6-97bb-3aabd5bc6fd0)

### Step to reproduce the behavior
All I did is just install and test. I'm using vm as test lab.

**Comment by nimish350** [comment]
What is the gpcheckperf command that you are using to test this? We will try to replicate this inhouse?

**Comment by nimish350** [comment]
Thank you @Qfur890416 for reporting this. I was able to reproduce this behavior inhouse. We will fix it from here.
