### ISSUE TITLE
How to get the real execution plan of the running SQL

### ISSUE THREAD

**Issue by cobolbaby** [greenplum-db/gpdb#16364]
## Feature Request

**Is your feature request related to a problem? Please describe:**

The execution time of some pl/pgsql is very unstable, sometimes it only takes a few seconds, and sometimes more than ten minutes. I'm sure it's not a lock issue, and I suspect the execution plan might be different. But how do I get the real execution plan of the running SQL, especially the embedded SQL in a complex function?

**Describe the feature you'd like to request:**

**Comment by ashwinstar** [comment]
Use auto_explain extension.

**Comment by cobolbaby** [comment]
If I want to output the auto_explain log to the log file, I need to adjust `log_min_messages`, but lowering the level will cause a large number of logs that do not require care.

In addition, auto_explain needs to wait for the successful execution of sql before outputting information. If the statement execution times out, auto_explain will not output anything.

**Comment by adam8157** [comment]
> auto_explain.log_level (enum) 
auto_explain.log_level selects the log level at which auto_explain will log the query plan. Valid values are DEBUG5, DEBUG4, DEBUG3, DEBUG2, DEBUG1, INFO, NOTICE, WARNING, and LOG. The default is LOG. Only superusers can change this setting.

**Comment by cobolbaby** [comment]
> auto_explain.log_level (enum)

That's great.

**Comment by adam8157** [comment]
That's not possible, setting to FATAL means every auto_explain log message will cancel the query session.

I guess you could keep your `log_min_messages` as FATAL and hack the auto_explain codes to log messages no matter what the log level is. Closing this.
