### ISSUE TITLE
There is a memory leak in CdbDispatchCommand

### ISSUE THREAD

**Issue by uglthinx** [greenplum-db/gpdb#16374]
### Greenplum version or build
all

### the problem
`CdbDispatchCommand` call `CdbDispatchCommandToSegments` and use `cdbcomponent_getCdbComponentsList()` to get the `segments`, but the `segments` param is never pfree. If we call `CdbDispatchCommand` in a while loop, there will be a memory leak.

**Comment by ashwinstar** [comment]
- Do we have some real scenario to showcase the problem?
- In which context is this memory allocated - don't we reset or free that context? Means wish to know what's the lifecycle of this leak?

**Comment by uglthinx** [comment]
If I run the following code, the `segments` will never be pfree, a memory leak occurs.
```
while (true)
{
    CdbDispatchCommand(buf.data, DF_NONE, &cdb_pgresults);
    cdbdisp_clearCdbPgResults(&cdb_pgresults);
}
```

**Comment by ashwinstar** [comment]
> If I run the following code, the `segments` will never be pfree, a memory leak occurs.
> 
> ```
> while (true)
> {
>     CdbDispatchCommand(buf.data, DF_NONE, &cdb_pgresults);
>     cdbdisp_clearCdbPgResults(&cdb_pgresults);
> }
> ```

I understand that - but that's artificial case. Please would be good to provide as asked some real scenario?
There are many places in code where can write while loop and no pfree exist at function level - but is done at context level at some higher level like at stmt or transaction end. Hence, asking the questions to clarify the impact.

**Comment by uglthinx** [comment]
Fine, I tried to use MemoryContext to manage this part of memory, and then the memory leak will not happen.

**Comment by ashwinstar** [comment]
> Fine, I tried to use MemoryContext to manage this part of memory, and then the memory leak will not happen.

Seeking clarification to your stmt- so you had to make code change to use some MemoryContext or this code already uses Memory Context properly hence no leak? If you had to add code to use MemoryContext what's the real scenario or use-case for the same (to ask again earlier question).

**Comment by uglthinx** [comment]
Early, I wanted to use `CdbDispatchCommand ` to implement a certain function, such as continuously querying whether tuple exists. I put `CdbDispatchCommand ` to execute in a while condition (inside a transaction), then memory leak occurs, even if I execute `cdbdisp_clearCdbPgResults`. So I checked this part of code as said before. Now I use Memory Context to manage it, and Reset the context after each execution of `CdbDispatchCommand`.
