### ISSUE TITLE
recursive CTE raise ERROR "GROUP BY in a recursive query is not implemented", even if GROUP BY table is not recursive CTE

### ISSUE THREAD

**Issue by wuyuhao28** [greenplum-db/gpdb#16422]
## Bug Report
main branch has this bug, 6X is good.

This bug is introduced by #14656 , I'm not sure why RangeSubselect in checkWellFormedRecursionWalker is removed, but Subselect context will be involved in recursive context and cause elog ERROR.

### Step to reproduce the behavior
A simple way to reproduce this issue: 

```
create table test_cte (a int, b int);

EXPLAIN
WITH RECURSIVE r(c1, c2) as 
(
  select a as c1, b as c2 from test_cte
  union all
  select r.c1, r.c2 from r
  join 
  (
    select a as c1,  b as c2 from test_cte
    union all
    select a as c1 , max(b) as c2 from test_cte group by c1
  ) as tmp_table
  on r.c1 = tmp_table.c1
)
select * from r join test_cte on r.c1 = a;
```
In this SQL,  RECURSIVE CTE is **_r_**,  while **_group by c1_** is on test_cte, I think it has nothing to do with RECURSIVE CTE and this SQL should be supported. 

### Expected behavior
plan will show (In 6X_STABLE it is OK)
### Actual behavior
An ERROR raised:
`ERROR:  GROUP BY in a recursive query is not implemented`

**Comment by kainwen** [comment]
Fixed by https://github.com/greenplum-db/gpdb/pull/16695
