### ISSUE TITLE
greenplum7 High availability issue

### ISSUE THREAD

**Issue by suige** [greenplum-db/gpdb#16432]
## Feature Request

**Is your feature request related to a problem? Please describe:**
Does Greenplum7 have new high-availability features for the Master node?

**Describe the feature you'd like to request:**
Does Greenplum7 have new high-availability features for the Master node?

**Comment by ashwinstar** [comment]
No, Greenplum 7 doesn't have any NEW high-availability aspect for master/coordinator node compared to Greenplum 6. And there is so far no plan for the same.
