### ISSUE TITLE
REFRESH MATERIALIZED VIEW fails with "relation "pg_aoblkdir_xxx" already exists" as for AO materialized view with btree index

### ISSUE THREAD

**Issue by Weslyn-Xia** [greenplum-db/gpdb#16447]
### Greenplum version or build
PostgreSQL 9.4.26 (Greenplum Database 6.25.1 build commit:337d85331f0330dea32d229f450da438d5e948f6) on x86_64-unknown-linux-gnu, compiled by gcc (GCC) 6.4.0, 64-bit compiled on Jul 19 2023 21:12:28

### OS version and uname -a
mdw 3.10.0-1160.15.2.el7.x86_64 #1 SMP Wed Feb 3 15:06:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
Linux *.compute.internal 4.18.0-477.15.1.el8_8.x86_64 #1 SMP Fri Jun 2 08:27:19 EDT 2023 x86_64 x86_64 x86_64 GNU/Linux
reproducible on both RHEL7 & RHEL8

### autoconf options used ( config.status --config )
N/A

### Installation information ( pg_config )
N/A

### Expected behavior
successfully refresh the MATERIALIZED VIEW

### Actual behavior
Errored out with "relation "pg_aoblkdir_xxx" already exists"

### Step to reproduce the behavior
```
gpadmin=# CREATE TABLE base_table (idn character varying(10) NOT NULL);
NOTICE:  Table doesn't have 'DISTRIBUTED BY' clause -- Using column named 'idn' as the Greenplum Database data distribution key for this table.
HINT:  The 'DISTRIBUTED BY' clause determines the distribution of data. Make sure column(s) chosen are the optimal data distribution key to minimize skew.
CREATE TABLE
Time: 4.135 ms
gpadmin=# CREATE MATERIALIZED VIEW base_view
gpadmin-# WITH (APPENDONLY=true)
gpadmin-# AS
gpadmin-# SELECT tt1.idn AS idn_ban
gpadmin-# FROM base_table tt1;
NOTICE:  Table doesn't have 'DISTRIBUTED BY' clause. Creating a NULL policy entry.
SELECT 0
Time: 22.235 ms
gpadmin=# CREATE INDEX test_id1 on base_view using btree(idn_ban);
CREATE INDEX
Time: 6.594 ms
gpadmin=# REFRESH MATERIALIZED VIEW base_view ;
ERROR:  relation "pg_aoblkdir_16911" already exists  (seg0 10.117.190.196:29786 pid=20411)
Time: 140.875 ms
```

**Comment by SmartKeyerror** [comment]
The main branch has some problems too, but the error message is not the same as for 6X:

```
postgres=# CREATE TABLE base_table (idn character varying(10) NOT NULL);
postgres=# CREATE MATERIALIZED VIEW base_view WITH (APPENDONLY=true) AS SELECT tt1.idn AS idn_ban FROM base_table tt1;
postgres=# CREATE INDEX test_id1 on base_view using btree(idn_ban);

postgres=# REFRESH MATERIALIZED VIEW base_view ;
ERROR:  could not open relation with OID 0  (seg2 127.0.1.1:7004 pid=16810)
DETAIL:  This can be validly caused by a concurrent delete operation on this object.
```

**Comment by SmartKeyerror** [comment]
### RCA for 7X

First we need to know how does Greenplum implement the command of `REFRESH MATERIALIZED VIEW`, here is the code comments:

> This refreshes the materialized view by creating a new table and swapping the relfilenodes of the new table and the old materialized view, so the OID of the original materialized view is preserved.

So in QD, it will execute `ExecRefreshMatView` and dispatch the plan tree to QEs and execute. Unlike QD, QE will swap the relation file node at `transientrel_shutdown()`, and all OID of new file nodes should be assigned and dispatched by QD. 

But QD doesn't assign new OID for block directory:

```
extern Oid make_new_heap_with_colname(Oid OIDOldHeap, Oid NewTableSpace, Oid NewAccessMethod,
									  List *NewEncodings,
									  Datum newoptions,
									  char relpersistence,
									  LOCKMODE lockmode,
									  bool createAoBlockDirectory,
									  bool makeCdbPolicy,
									  char *colprefix);

/*
* Create the transient table that will receive the regenerated data. Lock
* it against access by any other process until commit (by which time it
* will be gone).
*/
OIDNewHeap = make_new_heap_with_colname(matviewOid, tableSpace, matviewRel->rd_rel->relam, NULL, (Datum)0, relpersistence,
							   ExclusiveLock, false, true, "_$");
```

We can see the parameter of `createAoBlockDirectory` is `false`, and does not dispatch it to QE.

**Comment by Aegeaner** [comment]
> But QD doesn't assign new OID for block directory:

It seems the OID for new relation have been created inside `make_new_heap_with_colname()`:
https://github.com/greenplum-db/gpdb/blob/b15fb5d0b2ecfcd25d3fbc62799808f23b8d44c7/src/backend/commands/cluster.c#L815-L838

And the OID for block directory is the same for the temporary relation.
