### ISSUE TITLE
[ORCA] CXformEagerAgg and CXformPushGbBelowJoin is same?

### ISSUE THREAD

**Issue by iwanttobepowerful** [greenplum-db/gpdb#16448]

**Comment by dgkimura** [comment]
I agree that these two xforms look very similar.

I think `CXformEagerAgg` may have been intended to eventually replace `CXformPushGbBelowJoin`.  Based on the code comments, `CXformPushGbBelowJoin` has restrictions based on foreign keys... 

https://github.com/greenplum-db/gpdb/blob/8a4e9d4e675c4ec9dbb08eb55eb1a775bf124913/src/backend/gporca/libgpopt/src/xforms/CXformUtils.cpp#L657-L659

that `CXformEagerAgg` tries to remove...

https://github.com/greenplum-db/gpdb/blob/8a4e9d4e675c4ec9dbb08eb55eb1a775bf124913/src/backend/gporca/libgpopt/src/xforms/CXformEagerAgg.cpp#L10-L11

Another hint that this is unfinished work is that `CXformEagerAgg` has an experimental trace flag `EopttraceEnableEagerAgg`...

https://github.com/greenplum-db/gpdb/blob/8a4e9d4e675c4ec9dbb08eb55eb1a775bf124913/src/backend/gporca/libgpopt/src/xforms/CXformEagerAgg.cpp#L67-L74

that maps to GUC `optimizer_enable_eageragg` that is default false...

https://github.com/greenplum-db/gpdb/blob/8a4e9d4e675c4ec9dbb08eb55eb1a775bf124913/src/backend/utils/misc/guc_gp.c#L2858-L2865

So, I think you're right that we should try to finish up the work required to use `CXformEagerAgg` more broadly and then get rid of `CXformPushGbBelowJoin`.
