### ISSUE TITLE
EXPLAIN ANALYZE often omits Sort Method

### ISSUE THREAD

**Issue by hlinnaka** [greenplum-db/gpdb#1646]
For a Sort node, you are supposed to get a Sort Method row in EXPLAIN ANALYZE output, which tells what whether the sort was performed in memory or it spilled to disk, or if it was done with a heap with a limit. For example:

```
postgres=# explain analyze select * from generate_series(1, 100) g order by g limit 100;
                                                QUERY PLAN                                                
----------------------------------------------------------------------------------------------------------
 Limit  (cost=50.72..50.97 rows=100 width=4)
   Rows out:  100 rows with 0.731 ms to first row, 0.825 ms to end, start offset by 0.161 ms.
   ->  Sort  (cost=50.72..53.22 rows=1000 width=4)
         Sort Key: g
         Sort Method:  top-N heapsort  Memory: 25kB
         Rows out:  100 rows with 0.728 ms to first row, 0.767 ms to end, start offset by 0.163 ms.
         Executor memory:  49K bytes.
         Work_mem used:  49K bytes. Workfile: (0 spilling)
         ->  Function Scan on generate_series g  (cost=0.00..12.50 rows=1000 width=4)
               Rows out:  100 rows with 0.166 ms to first row, 0.228 ms to end, start offset by 0.218 ms.
               Work_mem used:  9K bytes.
 Slice statistics:
   (slice0)    Executor memory: 118K bytes.  Work_mem: 49K bytes max.
 Statement statistics:
   Memory used: 128000K bytes
 Optimizer status: legacy query optimizer
 Total runtime: 1.009 ms
(17 rows)
```

But in many cases, it is not printed:
```
postgres=# explain analyze select * from generate_series(1, 100) g order by g;
                                             QUERY PLAN                                             
----------------------------------------------------------------------------------------------------
 Sort  (cost=62.33..64.83 rows=1000 width=4)
   Sort Key: g
   Rows out:  100 rows with 0.301 ms to first row, 0.327 ms to end, start offset by 0.076 ms.
   Executor memory:  49K bytes.
   Work_mem used:  49K bytes. Workfile: (0 spilling)
   ->  Function Scan on generate_series g  (cost=0.00..12.50 rows=1000 width=4)
         Rows out:  100 rows with 0.093 ms to first row, 0.121 ms to end, start offset by 0.126 ms.
         Work_mem used:  9K bytes.
 Slice statistics:
   (slice0)    Executor memory: 118K bytes.  Work_mem: 49K bytes max.
 Statement statistics:
   Memory used: 128000K bytes
 Optimizer status: legacy query optimizer
 Total runtime: 0.415 ms
(14 rows)
```

In the above case, it's omitted, because the Sort is "eagerly freed", and loses the information. Another case is when the Sorts are performed in the segment nodes rather than the QD node - the information is not transmitted back to the QD in that case, and won't be printed.

**Comment by karthijrk** [comment]
Regarding the Sort Method for the segments, I assume each segment can choose the sort method it wants to be based on the number of tuples it has. So I don't know how we can better represent that on `analyze` output. 

@hlinnaka What's you thought?

**Comment by hlinnaka** [comment]
On 02/02/2017 11:39 PM, Karthikeyan Jambu Rajaraman wrote:
> Regarding the Sort Method for the segments, I assume each segment can
> choose the sort method it wants to be based on the number of tuples
> it has. So I don't know how we can better represent that on `analyze`
> output.

We have a lot of things like that. Some sorts and hash aggs spill, 
others don't, for example. And the number of rows processed by a node 
varies across segments all the time. Surely we have a way to deal with 
and report all that in way that makes sense? If we don't, we need to 
invent one.

- Heikki

**Comment by karthijrk** [comment]
ok, I am not sure if there is one. So we need to come up with one. I will send an email in gpdb-dev to start the conversation.

**Comment by ascherbaum-pivotal** [comment]
For reference, the discussion thread: https://groups.google.com/a/greenplum.org/forum/#!topic/gpdb-dev/V-zIshnNzyE
