### ISSUE TITLE
Cannot switch to resource_manager group-v2

### ISSUE THREAD

**Issue by Chibin** [greenplum-db/gpdb#16536]
## Bug Report

After updating the `/sys/fs/cgroup/cgroup.subtree_control` and a `systemd daemon-reload` happens before I use the cgroup.

I will hit an issue similar to below:
```
$ gpconfig -c gp_resource_manager -v group-v2;
[CRITICAL]:-new GUC value failed validation: [cdw:cgroup is not properly configured: file '/sys/fs/cgroup/gpdb/cpuset.cpus' does not exist],[sdw1:cgroup is not properly configured: file '/sys/fs/cgroup/gpdb/cpuset.cpus' does not exist]
new GUC value failed validation: [cdw:cgroup is not properly configured: file '/sys/fs/cgroup/gpdb/cpuset.cpus' does not exist],[sdw1:cgroup is not properly configured: file '/sys/fs/cgroup/gpdb/cpuset.cpus' does not exist]
```

You can see the following behavior:
```
$ cat /sys/fs/cgroup/cgroup.subtree_control
cpuset cpu io memory pids
$ systemd daemon-reload
$ cat /sys/fs/cgroup/cgroup.subtree_control
memory pids
```

It looks like some controllers in cgroup cgroup.subtree_control are removed after systemd daemon-reload if systemd sees that they are not used.

We may need to investigate `Delegate=` when creating our own service.
https://manpages.ubuntu.com/manpages/focal/en/man5/systemd.resource-control.5.html
https://systemd.io/CGROUP_DELEGATION/

Very similar symptom to this: https://bugzilla.redhat.com/show_bug.cgi?id=1139223#c16

### OS version and uname -a
RHEL8

**Comment by kainwen** [comment]
@Tao-T @Chibin can this issue be closed? Thanks!

**Comment by Tao-T** [comment]
I think we can close this issue now as PR #16589 has provided a workaround with `Delegate` and no repro of this issue these days.

GPDB and Systemd both tries to manage cgroup files so may step on each other's toes. We should keep tracing on how Systemd (and other common init process ) would manage cgroup, so avoid possible future collisions.

**Comment by Chibin** [comment]
Agreed, this should be resolved now.
