### ISSUE TITLE
Question : Best way to do transformation and loading through Greenplum

### ISSUE THREAD

**Issue by kelvien** [greenplum-db/gpdb#1654]
First of all, I can't assign a label to this issue. So if you have permission to do so, please add the question label to this issue. Thank you

My question :
What is the best way to do the transformation of ETL in Greenplum ?
I have a script that does all of the extraction. And the transformation and loading are done at the same time through Greenplum.
I am doing something like : (As a simple example, I'm upper-case-ing names)
`CREATE TABLE big_table AS SELECT id, name,  upper(name) AS transformed_name FROM small_table.`
And I start getting into a memory issue : 
` Canceling query because of high VMEM usage. Used: 17096MB, available 1896MB, red zone: 17100MB (runaway_cleaner.c:135)  (seg49 slice2 a7.local:1026 pid=15101) (cdbdisp.c:1320)`
My concern is not adding up more memory, but more in a long term, where as the number of rows I am dealing with, it will keep giving me the memory issue. So, am I actually doing the Transformation and Loading right way ? Or do I have a misunderstanding in fully utilizing Greenplum power ?
Thank you!

**Comment by kelvien** [comment]
I also have to add, the memory warning comes up when I run a stored procedure that does many queries int it.
Due the design of my application, the process in the procedure has to go through some tables. Basically the procedure creates temp tables, and loading them to a permanent table while joining it with a table a couple times.

**Comment by ivannovick** [comment]
Hi @kelvien can you post this as a question to the mailing list.  We are just tracking code level bugs and improvements etc in the issues.  Thx!
