### ISSUE TITLE
Missing `"` in subpartition template name of `pg_get_expr()`

### ISSUE THREAD

**Issue by kainwen** [greenplum-db/gpdb#16558]
### Greenplum version or build

`7.0.0`

### Expected behavior

`pg_get_expr` return SQL (in text) can be executable.

### Actual behavior

Missing `"` for special-char names.

### Step to reproduce the behavior

```sql
gpadmin=# CREATE TABLE public.logs
(
  log_id integer,
  log_date date,
  log_type text
)
WITH (APPENDONLY=FALSE)
DISTRIBUTED RANDOMLY
PARTITION BY RANGE(log_date)
    SUBPARTITION BY LIST(log_type)
(
    -- Child table name: logs_1_prt_p1
    PARTITION p1 START ('2023-01-01') END ('2023-03-31') WITH (APPENDONLY=FALSE)
    (
        -- Child table name: logs_1_prt_p1_2_prt_s1
        SUBPARTITION s1 VALUES ('1', '2', '3') WITH (APPENDONLY=FALSE)
    )
);
ALTER TABLE public.logs SET SUBPARTITION TEMPLATE
(
    SUBPARTITION "1 2" VALUES ('1', '2', '3')
);
CREATE TABLE
ALTER TABLE
gpadmin=# SELECT level, pg_get_expr(template, relid, true) FROM gp_partition_template WHERE relid = 'public.logs'::regclass ORDER BY 1 DESC;
 level |                          pg_get_expr
-------+----------------------------------------------------------------
     1 | SUBPARTITION TEMPLATE(SUBPARTITION 1 2 VALUES ('1', '2', '3'))
(1 row)
```

The name in the last output `SUBPARTITION TEMPLATE(SUBPARTITION 1 2 VALUES ('1', '2', '3'))`, the `1 2` should be `"1 2"`.

**Comment by hyongtao-db** [comment]
@kainwen Hi Zhenghua,
With the patch in #16578 , some test cases will be affected. Take an example:

``` diff
 SELECT level, pg_get_expr(template, relid) from gp_partition_template t WHERE t.relid = 'subpart_templ_encoding'::regclass;
- level |                                                                                                          pg_get_expr                                                                                                           
--------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-     1 | SUBPARTITION TEMPLATE(SUBPARTITION sp1 VALUES (1, 2, 3, 4, 5), COLUMN i ENCODING (compresstype=zlib), COLUMN j ENCODING (compresstype=rle_type), COLUMN k ENCODING (compresstype=zlib), COLUMN l ENCODING (compresstype=zlib))
+ level |                                                                                                           pg_get_expr                                                                                                            
+-------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
+     1 | SUBPARTITION TEMPLATE(SUBPARTITION "sp1" VALUES (1, 2, 3, 4, 5), COLUMN i ENCODING (compresstype=zlib), COLUMN j ENCODING (compresstype=rle_type), COLUMN k ENCODING (compresstype=zlib), COLUMN l ENCODING (compresstype=zlib))
 (1 row)
```
In this case, I think both `sp` and `"sp1"` are OK. What's your opinion?

**Comment by kainwen** [comment]
> @kainwen Hi Zhenghua, With the patch in #16578 , some test cases will be affected. Take an example:
> 
> ```diff
>  SELECT level, pg_get_expr(template, relid) from gp_partition_template t WHERE t.relid = 'subpart_templ_encoding'::regclass;
> - level |                                                                                                          pg_get_expr                                                                                                           
> --------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
> -     1 | SUBPARTITION TEMPLATE(SUBPARTITION sp1 VALUES (1, 2, 3, 4, 5), COLUMN i ENCODING (compresstype=zlib), COLUMN j ENCODING (compresstype=rle_type), COLUMN k ENCODING (compresstype=zlib), COLUMN l ENCODING (compresstype=zlib))
> + level |                                                                                                           pg_get_expr                                                                                                            
> +-------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
> +     1 | SUBPARTITION TEMPLATE(SUBPARTITION "sp1" VALUES (1, 2, 3, 4, 5), COLUMN i ENCODING (compresstype=zlib), COLUMN j ENCODING (compresstype=rle_type), COLUMN k ENCODING (compresstype=zlib), COLUMN l ENCODING (compresstype=zlib))
>  (1 row)
> ```
> 
> In this case, I think both `sp` and `"sp1"` are OK. What's your opinion? Please refer to https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/gpdb-dev-hyt-rocky8/jobs/icw_planner_rocky8/builds/1 for more details.

Would you please check what is the behavior of 6X?

**Comment by hyongtao-db** [comment]
> Would you please check what is the behavior of 6X?

It is a new feature in gpdb 7X,
```
Use the `pg_get_expr()` helper function with `gp_partition_template` to get a more user-friendly view of the template, as follows:

SELECT pg_get_expr(template, relid) FROM gp_partition_template 
  WHERE relid = '<table_name>'::regclass;
```

Please refer to https://github.com/greenplum-db/gpdb/pull/14288

**Comment by hyongtao-db** [comment]
The info below is from Miao Chen @water32  . Thanks for reporting this bug.
*------------------------------------------------------------------------------------*

In GPDB 7X, the catalog of the partition table is different from 6X. The partition template can only be parsed from the template field of the gp_partition_template system table. The result of the parsing is that there is no quote. 

``` GPDB 7X
# select pg_get_expr(template, relid, true) from gp_partition_template where relid='test_partition_template'::regclass;
                                                                  pg_get_expr
-----------------------------------------------------------------------------------------------------------------------------------------------
 SUBPARTITION TEMPLATE(SUBPARTITION 1 2 3 VALUES (1000), SUBPARTITION  HI 1 VALUES (2000))
 SUBPARTITION TEMPLATE(SUBPARTITION 4 5 6 START (200::integer) END (300::integer), SUBPARTITION  HI 2 START (300::integer) END (400::integer))
(2 rows)

```

In GPDB 6X, we use special field storage partition name, there is no quote problem here.

Test corresponding sql in GPDG 6X:
```
select parname, pg_get_expr(parlistvalues, parchildrelid), pg_get_expr(parrangestart, parchildrelid),pg_get_expr(parrangeend, parchildrelid)
from pg_partition_rule where paroid in (select oid from pg_partition where paristemplate and parrelid='test_partition_template'::regclass);
 parname | pg_get_expr | pg_get_expr | pg_get_expr
---------+-------------+-------------+-------------
 1 2 3   | 1000        |             |
  HI 1   | 2000        |             |
 4 5 6   |             | 200         | 300
  HI 2   |             | 300         | 400
(4 rows)
```

**Comment by hyongtao-db** [comment]
Pair with Zhenghua Lyu, we do some additional test about `pg_get_expr`:

#### Test in GPDB 7X
``` GPDB 7X
gpadmin=# create table t("a 123" int check ("a 123" > 5));
gpadmin=# select pg_get_expr(conbin, 't'::regclass::oid, true) from pg_constraint order by oid desc limit 1;
 pg_get_expr
-------------
 "a 123" > 5
(1 row)
```

#### Test in PG12.12
```
$ psql
psql (12.12)
Type "help" for help.

gpadmin=# create table t("a 123" int check ("a 123" > 5));
CREATE TABLE
gpadmin=# select pg_get_expr(conbin, 't'::regclass::oid, true) from pg_constraint sc limit 1;
 pg_get_expr
-------------
 "a 123" > 5
(1 row)

```

The `"` in both of them are OK.

**Comment by hyongtao-db** [comment]
#16578 is merged. Close it.
