### ISSUE TITLE
gpfdist of gpdb7.0.0 displaying incorrect help or not having this feature?

### ISSUE THREAD

**Issue by Gogogofyl** [greenplum-db/gpdb#16564]
gpdb 7.0.0 version:
Gpfdist added “-ssl_verify_pee” option, displayed through '-- help' but without corresponding option.

gpfdist --help
··· ···
gpfdist [-d <directory>] [-p <http_port>] [-l <log_file>] [-t <timeout>] 
[-S] [-w <time>] [-v | -V] [-m <max_length>] [--ssl <certificate_path>]
[--compress] [--multi_thread <number_of_threads>] [-k <seconds>]

gpfdist [-? | --help] | --version
··· ···

**Comment by RuiWang-vmw** [comment]
OK, we will update the help message soon.

**Comment by hyongtao-db** [comment]
Related pr #16595 is under review.

**Comment by hyongtao-db** [comment]
PR #16595 is merged. Close it. Thank you for your good catch. @Gogogofyl
