### ISSUE TITLE
gawk: cmd. line:1: warning: regexp escape sequence `\#' is not a known regexp operator

### ISSUE THREAD

**Issue by avamingli** [greenplum-db/gpdb#16570]
### Greenplum version or build
7 main commit f9ed97c9bd2239f64f7897d465545a7ceb8f1008

### OS version and uname -a

Linux i-v3roa8c2 5.15.0-76-generic #83-Ubuntu SMP Thu Jun 15 19:16:32 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Actual behavior

a warning shows:
```shell
gawk: cmd. line:1: warning: regexp escape sequence `\#' is not a known regexp operator
```

### Step to reproduce the behavior
```shell
./configure --enable-debug --enable-cassert --with-libxml --with-perl --enable-tap-tests
````

**Comment by kainwen** [comment]
Under review https://github.com/greenplum-db/gpdb/pull/16334

**Comment by hyongtao-db** [comment]
#16334 is merged. Close it.
