### ISSUE TITLE
SIGSEGV on gp 6.24

### ISSUE THREAD

**Issue by yuqaf1989** [greenplum-db/gpdb#16626]
## Bug Report

we have a production gp cluster,  we find a sql that will cause coredump immediately.
It seems that something error with funcion ` hash_any (k=<optimized out>, keylen=<optimized out>) at hashfunc.c:323`
then I check the sourcecode , it was committed 16 years ago. may not the root cause.

coredump info: 

Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f06f4a12b7f in raise () from /lib64/libpthread.so.0
[Current thread is 1 (Thread 0x7f06f8857d00 (LWP 940515))]
(gdb) bt
#0  0x00007f06f4a12b7f in raise () from /lib64/libpthread.so.0
#1  0x0000000000be15c8 in StandardHandlerForSigillSigsegvSigbus_OnMainThread (processName=<optimized out>, postgres_signal_arg=11) at elog.c:5620
#2  <signal handler called>
#3  0x000000000071a04b in hash_any (k=<optimized out>, keylen=<optimized out>) at hashfunc.c:323
#4  0x0000000000b2afc0 in hash_numeric (fcinfo=<optimized out>) at numeric.c:1635
#5  0x0000000000be42a8 in FunctionCall1Coll (flinfo=flinfo@entry=0x7f06f7e14268, collation=collation@entry=0, arg1=<optimized out>) at fmgr.c:1314
#6  0x00000000009268a7 in calc_hash_value (inputslot=0x2fab2e0, aggstate=0x2db2760) at execHHashagg.c:179
#7  agg_hash_initial_pass (aggstate=aggstate@entry=0x2db2760) at execHHashagg.c:977
#8  0x00000000008f20f2 in ExecAgg (node=node@entry=0x2db2760) at nodeAgg.c:1167
#9  0x00000000008daf48 in ExecProcNode (node=node@entry=0x2db2760) at execProcnode.c:1093
#10 0x000000000091c60b in execMotionSender (node=0x2db2130) at nodeMotion.c:303
#11 ExecMotion (node=node@entry=0x2db2130) at nodeMotion.c:260
#12 0x00000000008daed8 in ExecProcNode (node=node@entry=0x2db2130) at execProcnode.c:1121
#13 0x00000000008d25f9 in ExecutePlan (estate=estate@entry=0x2db1cf8, planstate=0x2db2130, operation=operation@entry=CMD_SELECT, sendTuples=sendTuples@entry=0 '\000', 
    numberTuples=numberTuples@entry=0, direction=direction@entry=ForwardScanDirection, dest=0x7f06f7bfc410) at execMain.c:3202
#14 0x00000000008d3150 in ExecutePlan (dest=0x7f06f7bfc410, direction=ForwardScanDirection, numberTuples=0, sendTuples=0 '\000', operation=CMD_SELECT, planstate=<optimized out>, 
    estate=0x2db1cf8) at execMain.c:3168
#15 standard_ExecutorRun (queryDesc=0x2d845a8, direction=ForwardScanDirection, count=0) at execMain.c:1119
#16 0x00000000008d32c5 in ExecutorRun (queryDesc=queryDesc@entry=0x2d845a8, direction=direction@entry=ForwardScanDirection, count=count@entry=0) at execMain.c:992
#17 0x0000000000a95927 in PortalRunSelect (portal=portal@entry=0x2dafce8, forward=forward@entry=1 '\001', count=0, count@entry=9223372036854775807, dest=dest@entry=0x7f06f7bfc410)
    at pquery.c:1158
#18 0x0000000000a97691 in PortalRun (portal=portal@entry=0x2dafce8, count=count@entry=9223372036854775807, isTopLevel=isTopLevel@entry=1 '\001', dest=dest@entry=0x7f06f7bfc410, 
    altdest=altdest@entry=0x7f06f7bfc410, completionTag=completionTag@entry=0x7ffd6083c310 "") at pquery.c:999
#19 0x0000000000a90939 in exec_mpp_query (
    query_string=0x2ea5992 "with tb_info as \n    (select coalesce(A.project_id,B.project_id)project_id,coalesce(A.package_id,B.package_id)package_id,B.package_name,\n    B.object_id,B.object_name,COALESCE(A.supplier_id,B.supplier"..., serializedQuerytree=<optimized out>, serializedQuerytreelen=<optimized out>, serializedPlantree=<optimized out>, 
    serializedPlantreelen=<optimized out>, serializedParams=<optimized out>, serializedParamslen=0, serializedQueryDispatchDesc=0x2eabd2e "(\265/\375`\322`\265s", 
    serializedQueryDispatchDesclen=3712) at postgres.c:1386
#20 0x0000000000a94d74 in PostgresMain (argc=<optimized out>, argv=argv@entry=0x2d8ae80, dbname=<optimized out>, username=<optimized out>) at postgres.c:5481
#21 0x0000000000a1c7ed in BackendRun (port=0x2d84360) at postmaster.c:4816
#22 BackendStartup (port=0x2d84360) at postmaster.c:4480
#23 ServerLoop () at postmaster.c:1945
#24 0x0000000000a1d795 in PostmasterMain (argc=argc@entry=5, argv=argv@entry=0x2d4f130) at postmaster.c:1515
#25 0x00000000006de99b in main (argc=5, argv=0x2d4f130) at main.c:245
(gdb) f 3
#3  0x000000000071a04b in hash_any (k=<optimized out>, keylen=<optimized out>) at hashfunc.c:323
323     hashfunc.c: No such file or directory.
(gdb) x/50i 0x000000000071a04b
=> 0x71a04b <hash_any+27>:      add    0x8(%rdi),%ecx
   0x71a04e <hash_any+30>:      sub    $0xc,%esi
   0x71a051 <hash_any+33>:      add    $0xc,%rdi
   0x71a055 <hash_any+37>:      add    -0x8(%rdi),%eax
   0x71a058 <hash_any+40>:      sub    %ecx,%r8d
   0x71a05b <hash_any+43>:      add    %edx,%r8d
   0x71a05e <hash_any+46>:      mov    %ecx,%edx
   0x71a060 <hash_any+48>:      add    %eax,%ecx
   0x71a062 <hash_any+50>:      rol    $0x4,%edx
   0x71a065 <hash_any+53>:      xor    %r8d,%edx
   0x71a068 <hash_any+56>:      sub    %edx,%eax
   0x71a06a <hash_any+58>:      mov    %eax,%r8d
   0x71a06d <hash_any+61>:      mov    %edx,%eax
   0x71a06f <hash_any+63>:      add    %ecx,%edx
   0x71a071 <hash_any+65>:      rol    $0x6,%eax
   0x71a074 <hash_any+68>:      xor    %r8d,%eax
   0x71a077 <hash_any+71>:      sub    %eax,%ecx
   0x71a079 <hash_any+73>:      mov    %ecx,%r8d
   0x71a07c <hash_any+76>:      mov    %eax,%ecx
   0x71a07e <hash_any+78>:      add    %edx,%eax
   0x71a080 <hash_any+80>:      rol    $0x8,%ecx
   0x71a083 <hash_any+83>:      xor    %r8d,%ecx
   0x71a086 <hash_any+86>:      mov    %ecx,%r8d
   0x71a089 <hash_any+89>:      sub    %ecx,%edx
   0x71a08b <hash_any+91>:      add    %eax,%ecx
   0x71a08d <hash_any+93>:      rol    $0x10,%r8d
   0x71a091 <hash_any+97>:      xor    %r8d,%edx
   0x71a094 <hash_any+100>:     mov    %edx,%r8d
   0x71a097 <hash_any+103>:     sub    %edx,%eax
   0x71a099 <hash_any+105>:     add    %ecx,%edx
   0x71a09b <hash_any+107>:     ror    $0xd,%r8d
   0x71a09f <hash_any+111>:     xor    %r8d,%eax
   0x71a0a2 <hash_any+114>:     mov    %eax,%r8d
   0x71a0a5 <hash_any+117>:     sub    %eax,%ecx
   0x71a0a7 <hash_any+119>:     add    %edx,%eax
   0x71a0a9 <hash_any+121>:     rol    $0x4,%r8d
   0x71a0ad <hash_any+125>:     xor    %r8d,%ecx
   0x71a0b0 <hash_any+128>:     cmp    $0xb,%esi
   0x71a0b3 <hash_any+131>:     ja     0x71a048 <hash_any+24>
   0x71a0b5 <hash_any+133>:     mov    %esi,%esi
   0x71a0b7 <hash_any+135>:     jmpq   *0x100b018(,%rsi,8)
   0x71a0be <hash_any+142>:     xchg   %ax,%ax
   0x71a0c0 <hash_any+144>:     movzbl 0x5(%rdi),%r8d
   0x71a0c5 <hash_any+149>:     movzbl 0x4(%rdi),%r9d
   0x71a0ca <hash_any+154>:     mov    %r8d,%r10d
   0x71a0cd <hash_any+157>:     movzbl 0x6(%rdi),%r8d
   0x71a0d2 <hash_any+162>:     shl    $0x8,%r10d
   0x71a0d6 <hash_any+166>:     shl    $0x10,%r8d
   0x71a0da <hash_any+170>:     add    %r10d,%r8d
   0x71a0dd <hash_any+173>:     add    %r8d,%r9d

### Greenplum version or build

PostgreSQL 9.4.26 (Greenplum Database 6.24.6 build commit:65583e9f5cccae53d49944762bb1ab1302647321 Open Source) on x86_64-unknown-linux-gnu, compiled by gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-
18), 64-bit compiled on Jun 29 2023 06:31:02

### OS version and uname -a

centos 8.6

**Comment by kainwen** [comment]
@yuqaf1989 Can you share us with the core dump (using packcore tool) and the minirepro of the SQL to help debug?

Without these two artifacts, it is hard to RCA.

**Comment by chrishajas** [comment]
@yuqaf1989 Can you test this on 6.25.1? There is a known issue that we introduced in https://github.com/greenplum-db/gpdb/pull/14781 and fixed in https://github.com/greenplum-db/gpdb/pull/15872 that caused incorrect grouping index col order.

**Comment by kainwen** [comment]
Long time no response and it might have already been fixed. Close it.
