### ISSUE TITLE
Could not open temp file when executing FunctionScan in InitPlan

### ISSUE THREAD

**Issue by xuebinsu** [greenplum-db/gpdb#16679]
## Bug Report

An error occur when attempting to execute FunctionScan in InitPlan:

```
gpadmin=# SELECT ARRAY(SELECT f FROM pg_resgroup_get_status(NULL::oid) AS f);
ERROR:  could not open temporary file "FUNCTION_SCAN_414_1.0" from BufFile "FUNCTION_SCAN_414_1": No such file or directory
```

The query plan is as follows:

```
gpadmin=# explain verbose SELECT ARRAY(SELECT f FROM pg_resgroup_get_status(NULL::oid) AS f);
                                                 QUERY PLAN                                                  
-------------------------------------------------------------------------------------------------------------
 Result  (cost=10.00..10.01 rows=1 width=32)
   Output: $1
   InitPlan 2 (returns $1)
     ->  Function Scan on pg_catalog.pg_resgroup_get_status f_1  (cost=0.00..10.00 rows=1000 width=24)
           Output: f_1.*
           Function Call: pg_resgroup_get_status(NULL::oid)
           InitPlan 1 (returns $0)
             ->  Function Scan on pg_catalog.pg_resgroup_get_status f  (cost=0.00..10.00 rows=1000 width=24)
                   Output: f.*
                   Function Call: pg_resgroup_get_status(NULL::oid)
 Optimizer: Postgres-based planner
(11 rows)
```

Interestingly, this plan contains 2 initplans, which seems unnecessary. For example, if we run a similar query with `pg_resgroup_get_status()` replaced with `generate_series()`, only one initplan is generated:

```
gpadmin=# explain verbose SELECT ARRAY(SELECT f FROM generate_series(1, 1) AS f);
                                       QUERY PLAN                                        
-----------------------------------------------------------------------------------------
 Result  (cost=0.01..0.02 rows=1 width=32)
   Output: $0
   InitPlan 1 (returns $0)
     ->  Function Scan on pg_catalog.generate_series f  (cost=0.00..0.01 rows=1 width=4)
           Output: f.f
           Function Call: generate_series(1, 1)
 Optimizer: Postgres-based planner
(7 rows)
```

### Greenplum version or build

```
gpadmin=# select version();
                                                                                                               version                                                                                                                
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 PostgreSQL 12.12 (Greenplum Database 7.0.0+dev.77.g6050ff131f build dev) on x86_64-pc-linux-gnu, compiled by gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-18), 64-bit compiled on Oct 31 2023 03:32:24 (with assert checking) Bhuvnesh C.
(1 row)
```

### OS version and uname -a

Probably not relevant.

### autoconf options used ( config.status --config )

Probably not relevant.

### Installation information ( pg_config )

Probably not relevant.

### Expected behavior

- Only 1 InitPlan is generated.
- Query can run without any error.

### Actual behavior

See above.

### Step to reproduce the behavior

See above.

**Comment by hyongtao-db** [comment]
Hi Xuebin, I found some info, maybe useful.

```
    > **Note** `EXECUTE ON INITPLAN` is only supported in functions that are used in the `FROM` clause of a `CREATE TABLE AS` or `INSERT` command such as the `get_data()` function in these commands.

    ```
    CREATE TABLE t AS SELECT * FROM get_data();
    
    INSERT INTO t1 SELECT * FROM get_data();
    ```
```

**Comment by SmartKeyerror** [comment]
For a quick look, I think the RCA lies to PR  #10156, has some corner cases that PR didn't consider.

**Comment by SmartKeyerror** [comment]
After some investigation, this issue was brought by #9542, which introduced a new location option for function: EXECUTE ON INITPLAN and did some patches at #10156.

Theoretically, if a SubLink could transform into InitPlan, then we should not consider invoking the function `append_initplan_for_function_scan()` to make another sub PlannerInfo, this is the RCA of this issue.

But I have no good idea to fix it, the simplest way is to add a global variable, tell `append_initplan_for_function_scan()` the current situation, and just do nothing. But I don't like global variables.

I need some time to think about it.

**Comment by adam8157** [comment]
Fixed by https://github.com/greenplum-db/gpdb/pull/16803
