### ISSUE TITLE
ORCA derived statistics only for used columns in CLogicalSetOp

### ISSUE THREAD

**Issue by wangpanCN** [greenplum-db/gpdb#16771]
## Enhancement

Currently, ORCA derives statistics for all output columns in CLogicalSetOp.
For example,
```
create table t1(a int,  b int, c int, d int) distributed by(a);
create table t2(a int,  b int, c int, d int) distributed by(a);

select * from t1 union all select * from t2;

select * from t1 join t2 on t1.a = t2.a;
```

if we execute the `union all` SQL, ORCA will derive statistics for all of the columns a, b, c, and d. But it is useless. If there are too many columns in the table, and the type of them are varchar or other string-related type, it will waste a lot of time to derive useless statistics.
Instead, if we execute the `join` SQL, ORCA will derive statistics for only the join keys(t1.a and t2.a in this case). It`s much more reasonable.

**Comment by vraghavan78** [comment]
Agreed!
