### ISSUE TITLE
Failed to restart cluster after a pair of segments were killed

### ISSUE THREAD

**Issue by feeling0713** [greenplum-db/gpdb#16824]
### Greenplum version or build
Tags：7.0.0
### OS version and uname -a
centos7 ； Linux sdw1 3.10.0-1160.el7.x86_64 #1 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
### autoconf options used ( config.status --config )
--with-gssapi --with-perl --with-python --with-libxml --with-openssl --prefix=/usr/local/gpdb7
### Installation information ( pg_config )
BINDIR = /usr/local/gpdb7/bin
DOCDIR = /usr/local/gpdb7/share/doc/postgresql
HTMLDIR = /usr/local/gpdb7/share/doc/postgresql
INCLUDEDIR = /usr/local/gpdb7/include
PKGINCLUDEDIR = /usr/local/gpdb7/include/postgresql
INCLUDEDIR-SERVER = /usr/local/gpdb7/include/postgresql/server
LIBDIR = /usr/local/gpdb7/lib
PKGLIBDIR = /usr/local/gpdb7/lib/postgresql
LOCALEDIR = /usr/local/gpdb7/share/locale
MANDIR = /usr/local/gpdb7/share/man
SHAREDIR = /usr/local/gpdb7/share/postgresql
SYSCONFDIR = /usr/local/gpdb7/etc/postgresql
PGXS = /usr/local/gpdb7/lib/postgresql/pgxs/src/makefiles/pgxs.mk
CONFIGURE = '--with-gssapi' '--with-perl' '--with-python' '--with-libxml' '--with-openssl'  '--prefix=/usr/local/gpdb7'  
CC = gcc
CPPFLAGS = 
CFLAGS = -Wall -Wmissing-prototypes -Wpointer-arith -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-unused-but-set-variable -Werror=implicit-fallthrough=3 -Wno-format-truncation
CFLAGS_SL = 
LDFLAGS = 
LDFLAGS_EX = 
LDFLAGS_SL = 
LIBS = -lpgcommon -lpgport -lpthread -lxerces-c -lbz2 -lxml2 -lrt -lssl -lcrypto -lgssapi_krb5 -lz -lreadline -lncurses -lrt -lcrypt -ldl -lm -lcurl -L/lib -lzstd  
VERSION = PostgreSQL 12.12
### Expected behavior
When a pair of segments are killed, execute 'gpstop - r' to recover the cluster。
### Actual behavior
gpstart stuck in “[INFO]:-Commencing parallel segment instance shutdown, please wait... ...”
### Step to reproduce the behavior
I killed a pair of segments to test the functionality of FTS。
When I tried to create a table but failed, I checked the cluster status。

postgres=# create table test00(id int);                  
NOTICE:  Table doesn't have 'DISTRIBUTED BY' clause -- Using column named 'id' as the Greenplum Database data distribution key for this table.
HINT:  The 'DISTRIBUTED BY' clause determines the distribution of data. Make sure column(s) chosen are the optimal data distribution key to minimize skew.
ERROR:  failed to acquire resources on one or more segments
DETAIL:  FTS detected one or more segments are down
postgres=# select * from gp_segment_configuration;
 dbid | content | role | preferred_role | mode | status | port | hostname | address |           datadir           
------+---------+------+----------------+------+--------+------+----------+---------+-----------------------------
    1 |      -1 | p    | p              | n    | u      | 5432 | sdw1     | sdw1    | /data/gpdata/master/gpseg-1
    3 |       1 | p    | p              | s    | u      | 6001 | sdw1     | sdw1    | /data/gpdata/primary/gpseg1
    9 |       1 | m    | m              | s    | u      | 7001 | sdw2     | sdw2    | /data/gpdata/mirror/gpseg1
    2 |       0 | p    | p              | s    | u      | 6000 | sdw1     | sdw1    | /data/gpdata/primary/gpseg0
    8 |       0 | m    | m              | s    | u      | 7000 | sdw2     | sdw2    | /data/gpdata/mirror/gpseg0
    5 |       3 | p    | p              | s    | u      | 6001 | sdw2     | sdw2    | /data/gpdata/primary/gpseg3
   11 |       3 | m    | m              | s    | u      | 7001 | sdw3     | sdw3    | /data/gpdata/mirror/gpseg3
    6 |       4 | p    | p              | s    | u      | 6000 | sdw3     | sdw3    | /data/gpdata/primary/gpseg4
   12 |       4 | m    | m              | s    | u      | 7000 | sdw1     | sdw1    | /data/gpdata/mirror/gpseg4
    7 |       5 | p    | p              | s    | u      | 6001 | sdw3     | sdw3    | /data/gpdata/primary/gpseg5
   13 |       5 | m    | m              | s    | u      | 7001 | sdw1     | sdw1    | /data/gpdata/mirror/gpseg5
    4 |       2 | m    | p              | n    | d      | 6000 | sdw2     | sdw2    | /data/gpdata/primary/gpseg2
   10 |       2 | p    | m              | n    | u      | 7000 | sdw3     | sdw3    | /data/gpdata/mirror/gpseg2
(13 rows)

According to the manual, execute gpstop - r to restart the cluster, but it failed.
Therefore, attempting to execute gpstart to start the cluster resulted in the following phenomenon:
20231207:09:22:52:126274 gpstart:sdw1:gpadmin-[INFO]:-Commencing parallel primary and mirror segment instance startup, please wait...
............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
20231207:09:32:57:126274 gpstart:sdw1:gpadmin-[INFO]:-Process results...
20231207:09:32:57:126274 gpstart:sdw1:gpadmin-[INFO]:-
20231207:09:32:57:126274 gpstart:sdw1:gpadmin-[INFO]:-
20231207:09:32:57:126274 gpstart:sdw1:gpadmin-[INFO]:-
20231207:09:32:57:126274 gpstart:sdw1:gpadmin-[ERROR]:-No segment started for content: 2.
20231207:09:32:57:126274 gpstart:sdw1:gpadmin-[INFO]:-dumping success segments: ['sdw2:/data/gpdata/mirror/gpseg0:content=0:dbid=8:role=m:preferred_role=m:mode=s:status=u', 'sdw2:/data/gpdata/mirror/gpseg1:content=1:dbid=9:role=m:preferred_role=m:mode=s:status=u', 'sdw2:/data/gpdata/primary/gpseg3:content=3:dbid=5:role=p:preferred_role=p:mode=s:status=u', 'sdw1:/data/gpdata/primary/gpseg0:content=0:dbid=2:role=p:preferred_role=p:mode=s:status=u', 'sdw1:/data/gpdata/primary/gpseg1:content=1:dbid=3:role=p:preferred_role=p:mode=s:status=u', 'sdw1:/data/gpdata/mirror/gpseg4:content=4:dbid=12:role=m:preferred_role=m:mode=s:status=u', 'sdw1:/data/gpdata/mirror/gpseg5:content=5:dbid=13:role=m:preferred_role=m:mode=s:status=u', 'sdw3:/data/gpdata/mirror/gpseg3:content=3:dbid=11:role=m:preferred_role=m:mode=s:status=u', 'sdw3:/data/gpdata/primary/gpseg4:content=4:dbid=6:role=p:preferred_role=p:mode=s:status=u', 'sdw3:/data/gpdata/primary/gpseg5:content=5:dbid=7:role=p:preferred_role=p:mode=s:status=u']
20231207:09:32:57:126274 gpstart:sdw1:gpadmin-[INFO]:-----------------------------------------------------
20231207:09:32:57:126274 gpstart:sdw1:gpadmin-[INFO]:-DBID:10  FAILED  host:'sdw3' datadir:'/data/gpdata/mirror/gpseg2' with reason:'PG_CTL failed.'
20231207:09:32:57:126274 gpstart:sdw1:gpadmin-[INFO]:-----------------------------------------------------

20231207:09:32:57:126274 gpstart:sdw1:gpadmin-[INFO]:-----------------------------------------------------
20231207:09:32:57:126274 gpstart:sdw1:gpadmin-[INFO]:-   Successful segment starts                                            = 10
20231207:09:32:57:126274 gpstart:sdw1:gpadmin-[WARNING]:-Failed segment starts                                                = 1    <<<<<<<<
20231207:09:32:57:126274 gpstart:sdw1:gpadmin-[WARNING]:-Skipped segment starts (segments are marked down in configuration)   = 1    <<<<<<<<
20231207:09:32:57:126274 gpstart:sdw1:gpadmin-[INFO]:-----------------------------------------------------
20231207:09:32:57:126274 gpstart:sdw1:gpadmin-[INFO]:-Successfully started 10 of 11 segment instances, skipped 1 other segments <<<<<<<<
20231207:09:32:57:126274 gpstart:sdw1:gpadmin-[INFO]:-----------------------------------------------------
20231207:09:32:57:126274 gpstart:sdw1:gpadmin-[WARNING]:-Segment instance startup failures reported
20231207:09:32:57:126274 gpstart:sdw1:gpadmin-[WARNING]:-Failed start 1 of 11 segment instances <<<<<<<<
20231207:09:32:57:126274 gpstart:sdw1:gpadmin-[WARNING]:-Review /home/gpadmin/gpAdminLogs/gpstart_20231207.log
20231207:09:32:57:126274 gpstart:sdw1:gpadmin-[INFO]:-----------------------------------------------------
20231207:09:32:57:126274 gpstart:sdw1:gpadmin-[WARNING]:-****************************************************************************
20231207:09:32:57:126274 gpstart:sdw1:gpadmin-[WARNING]:-There are 1 segment(s) marked down in the database
20231207:09:32:57:126274 gpstart:sdw1:gpadmin-[WARNING]:-To recover from this current state, review usage of the gprecoverseg
20231207:09:32:57:126274 gpstart:sdw1:gpadmin-[WARNING]:-management utility which will recover failed segment instance databases.
20231207:09:32:57:126274 gpstart:sdw1:gpadmin-[WARNING]:-****************************************************************************
20231207:09:32:57:126274 gpstart:sdw1:gpadmin-[INFO]:-Commencing parallel segment instance shutdown, please wait...
...
..
20231207:09:33:03:126274 gpstart:sdw1:gpadmin-[ERROR]:-gpstart error: Do not have enough valid segments to start the array.

In GP6, the cluster can be restarted normally, and I found that the recover.conf file in the data directory of mirror will be deleted; However, in GP7, the standby. signal file in the original mirror's data directory was not deleted, and there was an additional promote file in the original primary's data directory. I suspect it may be related to this.

**Comment by ashwinstar** [comment]
> According to the manual, execute gpstop - r to restart the cluster

Please can you point to manual. As it feels incorrect to ask for restart of cluster in this segment failure case.

If some segment failed, failover will happen itself. Later when wish to recover the original primary need to us gprecoverseg. Surprised gpstop came in picture. (We still need to look into reported problem and fix it.)

**Comment by feeling0713** [comment]
The website for the manual is   https://docs.vmware.com/en/VMware-Greenplum/7/greenplum-database/utility_guide-ref-gprecoverseg.html?hWord=N4IghgNiBcIOYAcBOBTAxgewG4gL5A
![gprecoverseg](https://github.com/greenplum-db/gpdb/assets/153146826/01d72dea-f04f-4544-a4ee-7e6fa4a5e585)
Because both the primary segment and its mirror have failed,restart the cluster according to the above method.

When I delete the standby. signal file in the original mirror's data directory, I can restart the cluster.
But when executing gprecoverseg, the initial primary cannot be restored, and gprecoverseg -F needs to be executed to restore it.

**Comment by soumyadeep2007** [comment]
This is quite possibly fixed by https://github.com/greenplum-db/gpdb/pull/16873.
@feeling0713 please try the latest 7 build.
