### ISSUE TITLE
gpinitsystem command return success (return 0 code) when we use unknown option (e.g. --ignore-warnings) and the execution nothing do (show the command usage)

### ISSUE THREAD

**Issue by jose-l-goncalves-alb** [greenplum-db/gpdb#16848]
### Greenplum version or build
7.0.0
### OS version and uname -a
$ cat /etc/redhat-release
Red Hat Enterprise Linux release 8.9 (Ootpa)
Linux 4.18.0-513.9.1.el8_9.x86_64 x86_64 x86_64 x86_64 GNU/Linux

### Installation information ( pg_config )
BINDIR = /usr/local/greenplum-db-7.0.0/bin
DOCDIR = /usr/local/greenplum-db-7.0.0/share/doc/postgresql
HTMLDIR = /usr/local/greenplum-db-7.0.0/share/doc/postgresql
INCLUDEDIR = /usr/local/greenplum-db-7.0.0/include
PKGINCLUDEDIR = /usr/local/greenplum-db-7.0.0/include/postgresql
INCLUDEDIR-SERVER = /usr/local/greenplum-db-7.0.0/include/postgresql/server
LIBDIR = /usr/local/greenplum-db-7.0.0/lib
PKGLIBDIR = /usr/local/greenplum-db-7.0.0/lib/postgresql
LOCALEDIR = /usr/local/greenplum-db-7.0.0/share/locale
MANDIR = /usr/local/greenplum-db-7.0.0/man
SHAREDIR = /usr/local/greenplum-db-7.0.0/share/postgresql
SYSCONFDIR = /usr/local/greenplum-db-7.0.0/etc/postgresql
PGXS = /usr/local/greenplum-db-7.0.0/lib/postgresql/pgxs/src/makefiles/pgxs.mk
CONFIGURE = '--disable-debug-extensions' '--disable-tap-tests' '--enable-orca' '--with-zstd' '--with-gssapi' '--with-libxml' '--with-perl' '--with-python' 'PYTHON=python3' '--with-openssl' '--with-pam' '--with-ldap' '--with-llvm' '--with-pythonsrc-ext' '--with-uuid=e2fs' '--with-extra-version= Open Source' '--prefix=/usr/local/greenplum-db-7.0.0' '--mandir=/usr/local/greenplum-db-7.0.0/man' 'CC=gcc' 'CFLAGS=-O3 -fargument-noalias-global -fno-omit-frame-pointer -g' 'PKG_CONFIG_PATH=/usr/local/lib64/pkgconfig'
CC = gcc
CPPFLAGS = -D_GNU_SOURCE -I/usr/include/libxml2
CFLAGS = -Wall -Wmissing-prototypes -Wpointer-arith -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-unused-but-set-variable -Werror=implicit-fallthrough=3 -Wno-format-truncation -Wno-stringop-truncation -O3 -fargument-noalias-global -fno-omit-frame-pointer -g  -Werror=uninitialized -Werror=implicit-function-declaration
CFLAGS_SL = -fPIC
LDFLAGS = -L/usr/lib64 -Wl,--as-needed -Wl,-rpath,'/usr/local/greenplum-db-7.0.0/lib',--enable-new-dtags
LDFLAGS_EX =
LDFLAGS_SL =
LIBS = -lpgcommon -lpgport -lpthread -lxerces-c -lbz2 -lxml2 -lpam -lrt -lssl -lcrypto -lgssapi_krb5 -lz -lreadline -lrt -lcrypt -ldl -lm  -lcurl -L/usr/lib -lzstd
VERSION = PostgreSQL 12.12

### Expected behavior
The result code should non zero (e.g. 1)

### Actual behavior
20231213:14:12:35:007518 gpinitsystem:acmcmn-el8-gp7:gpadmin-[ERROR]:-Unknown option --ignore-warnings

With result code 0

### Step to reproduce the behavior
$ /usr/local/greenplum-db/bin/gpinitsystem -c /usr/local/greenplum-db/gpinitsystem_config -h /usr/local/greenplum-db/hostfile_gpinitsystem --ignore-warnings

The option --ignore-warnings exists at 6 version, but at 7 version doesn't.
Our automation (ansible playbook) assume that the command runned with success.

**Comment by ashwinstar** [comment]
@nimish350 simple but annoying one, lets fix it
