### ISSUE TITLE
Why can't AutoVacuum automatically recycle user tables?

### ISSUE THREAD

**Issue by HelloYJohn** [greenplum-db/gpdb#16865]
## Feature Request
AutoVauum can automatically recycle user tables

In greenplum7.0, AutoVacuum can't automatically recycle user tables. I want to know why? Is it difficult to implement, or has it been implemented, has bugs, and is not enabled.

**Comment by ashwinstar** [comment]
We wish to enable the feature in iterations for autovacuum. The reason we continue to take conservative approach is there were many issues reported in past (decades before) for autovacuum in GPDB. Over many releases things have improved in terms of vacuum functionality. So,
- prior to GPDB6 autovacuum is enabled for template0 and wrap around cases
- starting GPDB7 we enabled autovacuum for catalog tables to keep bloat in check (which is majority reason for performance problems and given system tables needs to be handled by system admins)

Once feedback and tuning work fine for catalog tables, we would extend the logic for user tables as well. Though yes more aspects need to be thought through for user tables like do we autovacuum on individual segments independently or dispatch in central place coordinator. If take first approach then how to maintain stats on coordinator. If take second approach - how to optimize for segments where no work might be required and such aspects.

**Comment by HelloYJohn** [comment]
Thanks
