### ISSUE TITLE
Providing `optimizer_enable_indexscan` and `optimizer_enable_bitmapscan` to ask GPORCA to use index or not

### ISSUE THREAD

**Issue by CC-Hsu** [greenplum-db/gpdb#16885]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Hi, Team.

Currently when there exists some indexes at a partition table, GPORCA tends to utilize these indexes during a SQL JOIN,
but then it is very easy to choose nested loop join if the table is joined with some other table on these indexed columns.

Usually we find the following query plan pattern happens when joining a relatively small table with a large partition table.
1. At the first stage (dynamic) bitmap index scans and a bitmap heap scan are used on the partition table
2. On the (relatively) small table, a seq scan is performed
3. A nested loop join works on data of the seq scan (small table) output and bitmap heap scan rows

And this usually causes unending execution (exceeds many hours).

However, if the partition table does not have indexes (by dropping these indexes), GPORCA can utilize dynamic seq scan then hash join processing; usually the same query can be finished within several minutes (with some higher memory utilization).

Such slowness (when indexes exist) is very significant when handling joining ~10^4 rows against partition table with lots of rows.

Usually such tweak in PGSQL is achieved by disabling query plan related GUCs, [`enable_indexscan`](https://docs.vmware.com/en/VMware-Greenplum/6/greenplum-database/ref_guide-config_params-guc-list.html#enable_indexscan), [`enable_bitmapscan`](https://docs.vmware.com/en/VMware-Greenplum/6/greenplum-database/ref_guide-config_params-guc-list.html#enable_bitmapscan), and [`enable_nestloop`](https://docs.vmware.com/en/VMware-Greenplum/6/greenplum-database/ref_guide-config_params-guc-list.html#enable_nestloop).

But I find that the above GUCs does not work for GPORCA, and there lacks equivalent GUCs on index scan, bitmap index scan, and nestloop join.

**Describe the feature you'd like to request:**

I think GPDB should provides `optimizer_enable_indexscan` and `optimizer_enable_bitmapscan` for hinting GPORCA query planner.

If possible, I think such GUCs should be included in GPDB v6, not just in GPDB7, since many users are still using GPDB v6.

Best Regards.

**Comment by dgkimura** [comment]
For GPORCA dynamic scans, the convention is `optimizer_enable_dynamic*`:

```
$ git grep optimizer_enable_dynamic src/include/utils/guc.h
src/include/utils/guc.h:extern bool optimizer_enable_dynamictablescan;
src/include/utils/guc.h:extern bool optimizer_enable_dynamicindexonlyscan;
```

So, I think the GUCs you're proposing would be `optimizer_enable_dynamicindexscan` and `optimizer_enable_dynamicbitmapscan`.

It may be worth noting that there is in-progress work (https://github.com/greenplum-db/gpdb/pull/16731) to enable scan hints, which I think would also workaround your problem.  However, I do not think that will be back-ported to 6X.

As for your actual issue of GPORCA is picking the sub-optimal plan, are you able to provide an example setup demonstrating the problem?  Perhaps as a separate issue, I think it would be best to figure out a real solution that doesn't require GUCs or hints.

**Comment by CC-Hsu** [comment]
Hi, dgkimura,

Thanks for your correction and feedback. 😊

I'll try to prepare a test case about the mentioned situation.

However, is it possible to consider to add `optimizer_enable_dynamic_indexscan`, `optimizer_enable_dynamic_bitmapscan`, etc?

These GUC options can be used as coarse control tool, and it can provide GPDB users a similar user experience to PGSQL.

P.S. Looking forward to the query hint feature in GPDB v7. 😄

Best Regards.

**Comment by dgkimura** [comment]
On Wed, Dec 20, 2023 at 7:32 PM CC-Hsu wrote:
> I'll try to prepare a test case about the mentioned situation.

Cool, that'll would be really helpful.

> However, is it possible to consider to add optimizer_enable_dynamic_indexscan, optimizer_enable_dynamic_bitmapscan, etc?

Yeah, I think it's worth considering.  It's simple to code and I can see value in keeping GPORCA GUCs aligned with PLANNER GUCs.

**Comment by CC-Hsu** [comment]
Hi, dgkimura,

It's glad to hear that the purposed GUCs improvement is possible to add.

Is it possible to see these GUCs in GPDB 6.x later?
