### ISSUE TITLE
Where is greenplum_fdw with greenplum 7.0?

### ISSUE THREAD

**Issue by xinpengthk** [greenplum-db/gpdb#16892]
I have installed the greeenplum 7.0, but I can't find the greenplum_fdw extension in pg_available_extensions, and when I execute the command create extension greenplum_fdw, there is a error told me that No greenplum_fdw.control file.

testdb=# select * from pg_available_extensions;
          name          | default_version | installed_version |                                            comment

------------------------+-----------------+-------------------+---------------------------------------------------------------------------------------
--------
 plperl                 | 1.0             |                   | PL/Perl procedural language
 file_fdw               | 1.0             |                   | foreign-data wrapper for flat file access
 plpython3u             | 1.0             | 1.0               | PL/Python3U untrusted procedural language
 sslinfo                | 1.2             |                   | information about SSL certificates
 gp_internal_tools      | 1.0.0           |                   | Different internal tools for Greenplum
 gp_inject_fault        | 1.0             |                   | simulate various faults for testing purposes
 orafce                 | 3.13            |                   | Functions and operators that emulate a subset of functions and packages from the Oracl
e RDBMS
 hstore                 | 1.6             |                   | data type for storing sets of (key, value) pairs
 gp_sparse_vector       | 1.0.1           |                   | SParse vector implementation for GreenPlum
 btree_gin              | 1.3             |                   | support for indexing common datatypes in GIN
 isn                    | 1.2             |                   | data types for international product numbering standards
 gp_distribution_policy | 1.0             |                   | check distribution policy in a GPDB cluster
 gp_exttable_fdw        | 1.0             | 1.0               | External Table Foreign Data Wrapper for Greenplum
 gp_toolkit             | 1.2             | 1.2               | various GPDB administrative views/functions
 citext                 | 1.6             |                   | data type for case-insensitive character strings
 pgcrypto               | 1.3             |                   | cryptographic functions
 gp_debug_numsegments   | 1.0             |                   | get / set default numsegments when creating tables
 plperlu                | 1.0             |                   | PL/PerlU untrusted procedural language
 dblink                 | 1.2             |                   | connect to other PostgreSQL databases from within a database
 postgres_fdw           | 1.0             |                   | foreign-data wrapper for remote PostgreSQL servers
 ltree                  | 1.1             |                   | data type for hierarchical tree-like structures
 plpgsql                | 1.0             | 1.0               | PL/pgSQL procedural language
 fuzzystrmatch          | 1.1             |                   | determine similarities and distance between strings
 pg_trgm                | 1.4             |                   | text similarity measurement and index searching based on trigrams
 gp_replica_check       | 0.0.1           |                   |
 pageinspect            | 1.9             |                   | inspect the contents of database pages at a low level
 gp_legacy_string_agg   | 1.0.0           |                   | Legacy one-argument string_agg implementation for Greenplum
 roaringbitmap          | 0.2.66          | 0.2.66            | Extension for RoaringBitmaps
 pljava                 | 1.5.0           | 1.5.0             | PL/Java procedural language (https://tada.github.io/pljava/)
(29 rows)

testdb=# create extension greenplum_fdw;
ERROR:  could not open extension control file "/usr/local/greenplum-7.0/share/postgresql/extension/greenplum_fdw.control": No such file or directory

**Comment by hyongtao-db** [comment]
Hello, thank you for your attention.

`greeenplum_fdw` is an extension of `gp-stream-server`. `gp-stream-server` is not open-source and can only be used by customers who buy licenses.

**Comment by xinpengthk** [comment]
Thanks for your response.

**Comment by xinpengthk** [comment]
Sorry to bother you again. Where can I see a quotation and document about gp-stream-server and greenplum_fdw？
