### ISSUE TITLE
Resource groups have performance interference with each other

### ISSUE THREAD

**Issue by fairyfar** [greenplum-db/gpdb#16929]
Resource groups have performance interference with each other

## 1. Greenplum version or build
```
                                                                                                                 version                                                                                                              
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 PostgreSQL 12.12 (Greenplum Database 7.0.0-beta.1+dev.1237.gb741d59cfb build dev) on x86_64-pc-linux-gnu, compiled by gcc (GCC) 9.3.1 20200408 (Red Hat 9.3.1-2), 64-bit compiled on Jan  4 2024 15:52:46 (with assert checking) Bhuvnesh C.
(1 row)
```

## 2. Prepare test data
```sql
-- Create resource groups and users
postgres=# create resource group rg_busy with (cpu_max_percent = 1, concurrency = 200);
postgres=# create user user_busy superuser resource group rg_busy;

postgres=# create resource group rg_mon WITH (cpu_max_percent = 10);
postgres=# create user user_mon superuser resource group rg_mon;

postgres=# select * from gp_toolkit.gp_resgroup_config;
 groupid |   groupname   | concurrency | cpu_max_percent | cpu_weight | cpuset | memory_limit | min_cost | io_limit
---------+---------------+-------------+-----------------+------------+--------+--------------+----------+----------
    6437 | default_group | 20          | 20              | 100        | -1     | -1           | 500      | -1
    6441 | system_group  | 0           | 10              | 100        | -1     | -1           | 500      | -1
    6438 | admin_group   | 20          | 10              | 100        | -1     | -1           | 500      | -1
   90648 | rg_mon        | 20          | 10              | 100        | -1     | -1           | 0        | -1
   90646 | rg_busy       | 200         | 1               | 100        | -1     | -1           | 0        | -1
(5 rows)

-- Create a table for testing
postgres=# create table t_mon(a int);
postgres=# insert into t_mon select generate_series(1, 1000);
```

Notes: Modify `pg_hba.conf` so that new users can login.

## 3. Test & Observation

Execute monitor query on a terminal to observe the performance change of `rg_mon` group.

```bash
[yz@bogon ~]$ watch -n 1 "time psql -d postgres -U user_mon -c 'select count(*) from t_mon;'"
```

On the other terminal, run a concurrent testing script to consume `rg_busy` group's CPU.

```bash
[yz@bogon ~]$ cat ./test.sh
for ((i=0; i<500; i++)); do
  for ((i=0; i<150; i++)); do
    psql -d postgres -U user_busy -c "select 1;" > /dev/null &
  done
  wait
done
```

When the CPU usage of `rg_busy` group reaches the limit, the performance of `rg_mon` group is very shaky.
The execution time varies from tens of milliseconds to a few seconds.

## 4. Root causes

After catch the stack, it is found that when the CPU usage of `rg_busy` group reaches limit, 
the locking and unlocking of `ResGroupLock` becomes significantly longer.
As a result, the access to `ResGroupLock` by `rg_mon` group also becomes longer time.

On the other hand, if the current session is reused by another transaction, then the new transaction to locking ResGroupLock in `AssignResGroupOnCoordinator` and `SwitchResGroupOnSegment` will also cause the performance of the other groups to slow down.

## 5. Suggestion

At the start of `UnassignResGroup` function, move the current process to `system_group` group (`cpu_max_percent` of `system_group` needs to be increased) or to the root group of GPDB.

The patches are as follows:

```diff
[yz@bogon gpdb_src]$ git diff src/backend/utils/resgroup/resgroup.c
diff --git a/src/backend/utils/resgroup/resgroup.c b/src/backend/utils/resgroup/resgroup.c
index b13702e56b..89544145e4 100644
--- a/src/backend/utils/resgroup/resgroup.c
+++ b/src/backend/utils/resgroup/resgroup.c
@@ -1616,6 +1616,8 @@ UnassignResGroup(void)
        ResGroupData            *group;
        ResGroupSlotData        *slot;

+       cgroupOpsRoutine->attachcgroup(SYSTEMRESGROUP_OID, MyProcPid, false);
+
        if (bypassedGroup)
        {
                /* bypass mode ref count is only maintained on qd */
```

PS:

## 6. General reasons

I'm trying to figure out more general reasons.

I have found that when critical sections are accessed in different resource groups, performance interference between resource groups occurs.

Make a simple demo:

Step 1: Compile
```c
[yz@bogon shared_sem]$ cat shared_sem.c
#include <stdio.h>
#include <errno.h>
#include <time.h>
#include <sys/shm.h>
#include <semaphore.h>

sem_t *psem = NULL;
key_t shmKey = 1000;
int shmId = -1;

void LockSem(sem_t *sem)
{
	int status;
 	do
	{
		status = sem_wait(sem);
	} while (status < 0 && errno == EINTR);
}

void UnlockSem(sem_t *sem)
{
	int status;
	do
	{
		status = sem_post(sem);
	} while (status < 0 && errno == EINTR);
}

int main(int argc, char **argv)
{
	if (argc > 1)
		shmId = atoi(argv[1]);
	if (shmId < 0)
		shmId = shmget(shmKey, sizeof(sem_t), IPC_CREAT | IPC_EXCL | 0600);
	printf("shmId: %d \n", shmId);
	if (shmId < 0)
		return 1;

	psem = shmat(shmId, NULL, 0);
	if (sem_init(psem, 1, 1) < 0)
	{
		printf("sem_init failed.\n");
		return 1;
	}

	struct timeval start = {};
	struct timeval end = {};
	long time_used;
	while (1)
	{
		gettimeofday(&start, NULL);
		LockSem(psem);
		UnlockSem(psem);
		gettimeofday(&end, NULL);

		time_used = (end.tv_sec - start.tv_sec) * 1000 + (end.tv_usec - start.tv_usec) / 1000;
		if (time_used > 5)
			printf("time: %ld ms\n", time_used);
	}

	shmdt(psem);
	shmctl(shmId, 0, NULL);
	return 0;
}

[yz@bogon shared_sem]$ gcc -lpthread shared_sem.c -o shared_sem
```

Step 2: Run the demo program on two clients. Observe the timing output. It should be in milliseconds.

```bash
[yz@bogon sys_cgroup]$ ./shared_sem
shmId: 4161545

[yz@bogon sys_cgroup]$ ./shared_sem 4161545
shmId: 4161545
```

Step 3: Move one of the processes to a cgroup with less CPU quota (1% of one CPU core).

```bash
[root@bogon test]# pwd
/sys/fs/cgroup/cpu/test
[root@bogon test]# cat cpu.cfs_period_us
100000
[root@bogon test]# echo 1000 > cpu.cfs_quota_us   # 1% CPU limit

[root@bogon test]# ps aux | grep shared_sem
yz       29662 99.6  0.0   6388   396 pts/6    R+   11:55   0:32 ./shared_semp
yz       29705 82.3  0.0   6388   396 pts/5    R+   11:56   0:02 ./shared_sem 4161545

[root@bogon test]# echo 29662 > cgroup.procs

Notes: use `ipcrm -m 4161545` to remove the shared memory.
```

It can be observed that another process that does not limit CPU also appears to slow down.

**Comment by yanwr1** [comment]
Thanks for your work.

I think the main reason why this happens is heavy concurrency. ResGroupLock is a shared lock between processes, process in group rg_busy and rg_mon all use the lock to acquire resgroup info, when group rg_busy set a low cpu limt, acquire and release the shared lock will also get less cpu resourece, and effect others process which access the same lock. move the unassign group work to system group can't solve the problem completely. when process in system group reach cpu limit, it also will reduce performance.

I suggest for a group with high concurrency and high CPU usage, we should alter the group's setting, set more cpu resource for the group.

As you said, not only for the lock ResGroupLock, as they access the same memory for the situation, they will influence each other,  maybe the better way is to alter the group configuration.

**Comment by fairyfar** [comment]
tks!

**Comment by kainwen** [comment]
Can we close this issue now? @fairyfar @yanwr1 
Thanks.

**Comment by fairyfar** [comment]
> Can we close this issue now? @fairyfar @yanwr1 Thanks.

I think it's ok.
