### ISSUE TITLE
ORCA & orafce: add new type, create partition table, select table ORCA coredump

### ISSUE THREAD

**Issue by HelloYJohn** [greenplum-db/gpdb#16981]
## Bug Report
ORCA & orafce: add new type, ORCA coredump
### Greenplum version or build
PostgreSQL 12.12 (Greenplum Database 7.0.0+dev.261.g946eb7793c build dev) on x86_64-apple-darwin23.2.0, compiled by Apple clang version 15.0.0 (clang-1500.1.0.2.5), 64-bit compiled on Dec 26 2023 09:22:45 Bhuvnesh C.

### Expected behavior
no coredump
### Actual behavior
coredump
### Step to reproduce the behavior
[oracle-date.patch](https://github.com/greenplum-db/gpdb/files/13934284/oracle-date.patch)
S1. add a new type oracle.date
``` bash
cd gpcontrib/orafce
git apply oracle-date.patch
make clean && make install
```
S2. drop extension orafce, rerstart gpdb, create extension orafce
if you have any about orafce, please backup it.
``` sql
 drop extension orafce cascade;
 \! gpstop -ra
create extension orafce;
```
S3. create partition table and select partition table 
``` sql
set search_path to oracle;
drop table test_upsert_single_pk_date cascade;
create table test_upsert_single_pk_date (
        single_id oracle.date,
        name varchar,
        gender varchar not null,
        age oracle.date,
        height integer,
        weight integer,
        constraint "single_id_pk_date" primary key(single_id)
)DISTRIBUTED BY (single_id)partition by RANGE(single_id);
create table test_upsert_single_pk_date_p1 partition of test_upsert_single_pk_date for values from ('1990-1-1') to ('1999-12-31');

create table test_upsert_single_pk_date_p2 partition of test_upsert_single_pk_date for values from ('1999-12-31') to ('2010-12-31');

create table test_upsert_single_pk_date_p3 partition of test_upsert_single_pk_date for values from ('2010-12-31') to ('2023-12-31');

create table test_upsert_single_pk_date_p4 partition of test_upsert_single_pk_date for values from ('2023-12-31') to ('2099-12-31');

create table test_upsert_single_pk_date_default partition of test_upsert_single_pk_date default;
select * from test_upsert_single_pk_date;
```

**Comment by chrishajas** [comment]
Thanks for the report! I looked into this a bit. The cause is that Orca calls out to a function, `get_qual_for_range`, which evaluates the partition bounds for the table. Because it's a custom type with custom comparator functions, it creates an expression and evaluates this. It tries to use Orca, which means that it tries to reinitialize and overwrites an Orca worker in the same stack--which isn't expected behavior and puts Orca in an undefined state.

**Comment by HelloYJohn** [comment]
```
In short, orca calls orca in a statement because calling SPI. Do you think what's best solution?
1. Prohibited use pl/sql in partition table
2. partition table get_qual_for_range doesn't call SPI
3. orca nest orca is ok
```

**Comment by chrishajas** [comment]
I think want to call this SPI call, since it's important for partition selection/partition bounds evaluation. In 818c05258b227aaaaf66efac211ee46f0679e594 we do:
```
+               /*
+                * Orca doesn't support parameterized queries (which the below FunctionCall
+                * is), and would end up throwing an exception and falling back to planner
+                * anyway. This fallback could also trample memory contexts and cause errors.
+                * Instead, temporarily disable Orca when making this function call.
+                */
+               optimizerBackup = optimizer;
+               optimizer = false;
                cmpval = DatumGetInt32(FunctionCall2Coll(&partsupfunc[i],
                                                                                                 partcollation[i],
                                                                                                 datums1[i],
                                                                                                 datums2[i]));
+               optimizer = optimizerBackup;
```

which is something we might want to do here, as running Orca for these SPI calls isn't necessary IMO (and won't provide any benefit). I think supporting orca nesting orca calls would be error-prone.

**Comment by HelloYJohn** [comment]
Want everything, get nothing

**Comment by chrishajas** [comment]
With https://github.com/greenplum-db/gpdb/commit/6cd1c5ecfca79323e36df3bfb97a1bfeec36b06d Orca no longer crashes when Orca calls itself but instead falls back gracefully, thanks for the report!
