### ISSUE TITLE
can gp6 upgrade to gp7 in same server？

### ISSUE THREAD

**Issue by wonb168** [greenplum-db/gpdb#17108]
My gp6 cluster is in centos7，
but gp7 need centos8+，
can upgrade gp6 to gp7 in same server？
otherwise，will need BUY some other servers to install gp7，and then dump gp6 data to it。

thank you！

**Comment by ashwinstar** [comment]
In-place upgrade for 6->7 is work in progress, so its not available yet.
If in-place upgrade existed, the way to do it for your case would be OS upgrade from centos7 to centos8 first. Then upgrade GPDB from 6->7.

For now your best option is backup from 7 and restore to 8 (if using any partitioned tables with text partition columns then those might need some fixing post upgrade).
