### ISSUE TITLE
compile in mac m2 error

### ISSUE THREAD

**Issue by wonb168** [greenplum-db/gpdb#17181]
```
git submodule update --init
```
but tell me not a git compository:
![image](https://github.com/greenplum-db/gpdb/assets/25274931/94d83f87-0540-42b3-8c9e-c27640983283)

**Comment by higuoxing** [comment]
It looks that your source code is a release tarball which is not a code repo managed by git. The submodule is googletest which is used for testing the gpcloud. If you don't need to running gpcloud unit testing, you don't need the submodule. If you want to run gpcloud's unit testing, you will need to clone the source code using git.

```
git clone git@github.com:greenplum-db/gpdb.git
# or
git clone https://github.com/greenplum-db/gpdb.git
```
