### ISSUE TITLE
The view pg_exttable do not contain PERSISTENTLY option for LOG ERRORS

### ISSUE THREAD

**Issue by water32** [greenplum-db/gpdb#17180]
### Greenplum version or build

7.1

### Expected behavior

The view pg_exttable's column options contain string "error_log_persistent=true" to be consistent with gp6 and gp5

### Actual behavior

The pg_exttable. options  is NULL

### Step to reproduce the behavior
In version 6 and version 5:
```
DROP EXTERNAL TABLE if exists public.test_ext;

CREATE READABLE EXTERNAL TABLE public.test_ext
(
  id int
)
LOCATION(
  'file://gp6/test.txt'
)
FORMAT 'TEXT' ( delimiter 'off')
LOG ERRORS PERSISTENTLY SEGMENT REJECT LIMIT 10 PERCENT;
SELECT options FROM pg_exttable WHERE reloid = 'public.test_ext'::regclass;
           options
-----------------------------
 {error_log_persistent=true}
(1 row)
```
In version 7:
```
DROP EXTERNAL TABLE if exists public.test_ext;

CREATE READABLE EXTERNAL TABLE public.test_ext
(
  id int
)
LOCATION(
  'file://gp6/test.txt'
)
FORMAT 'TEXT' ( delimiter 'off')
LOG ERRORS PERSISTENTLY SEGMENT REJECT LIMIT 10 PERCENT;
SELECT logerrors, options FROM pg_exttable WHERE reloid = 'public.test_ext'::regclass;
 logerrors | options
-----------+---------
 t         |
(1 row)
```
In function pg_exttable, have a comment saying that the pg_exttable.options attribute is not required, but in fact, in versions 6 and 5, will store "error_log_persistent=true" in the pg_exttable.options for "PERSISTENTLY". And, in the struct ExtTableEntry, the attribute options is used to store pg_exttable.fmtopts and the real options are missing.

**Comment by water32** [comment]
In addition, the pg_exttable view seems to have performance problems, because even querying a single record, the index cannot be used.

**Comment by jingwen-yang-yjw** [comment]
Hi @water32 ,
In GP7, `pg_exttable` catalog is removed. `pg_exttable.options` are merged into `ForeignTable.options` and we can find them in pg_foreign_table catalog.
Moreover, struct `ExtTableEntry` is built by deparsing `ForeignTable.options`, that is, `ftoptions`.
```
testdb=# select * from pg_foreign_table where ftrelid = 'public.test_ext'::regclass;
 ftrelid | ftserver |                                                                                                     ftoptions

---------+----------+--------------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------
  157457 |    13703 | {format=text,delimiter=off,"null=\\N","escape=\\",location_uris=file://gp6/test.txt,execute_on=ALL_SEGMENTS,reject_limit=
10,reject_limit_type=percentage,log_errors=persistently,encoding=UTF8,is_writable=false}
(1 row)
```
I create a PR to provide more detailed information about logerrors in pg_exttable view.
PR: https://github.com/greenplum-db/gpdb/pull/17182

**Comment by jingwen-yang-yjw** [comment]
> In addition, the pg_exttable view seems to have performance problems, because even querying a single record, the index cannot be used.

The information in pg_exttable view is obtained from pg_foregin_table catalog in GP7. (Instead of pg_exttable catalog in GP6)
If we can build index in  pg_foregin_table catalog table, I think the index can be used.

**Comment by water32** [comment]
> > In addition, the pg_exttable view seems to have performance problems, because even querying a single record, the index cannot be used.
> 
> The information in pg_exttable view is obtained from pg_foregin_table catalog in GP7. (Instead of pg_exttable catalog in GP6) If we can build index in pg_foregin_table catalog table, I think the index can be used.

The pg_foreign_table have an index on ftrelid，if the function pg_exttable() only format one row from pg_foreign_table, query on view pg_exttable can use the table's index.

**Comment by jingwen-yang-yjw** [comment]
> > > In addition, the pg_exttable view seems to have performance problems, because even querying a single record, the index cannot be used.
> > 
> > 
> > The information in pg_exttable view is obtained from pg_foregin_table catalog in GP7. (Instead of pg_exttable catalog in GP6) If we can build index in pg_foregin_table catalog table, I think the index can be used.
> 
> The pg_foreign_table have an index on ftrelid，if the function pg_exttable() only format one row from pg_foreign_table, query on view pg_exttable can use the table's index.

Thanks a lot for your information.
I tried to query `pg_foreign_table` in GP7 directly. The plan is as follows.
```
testdb=# explain verbose select * from pg_foreign_table where ftrelid = 'public.test_ext'::regclass;
                                 QUERY PLAN
-----------------------------------------------------------------------------
 Seq Scan on pg_catalog.pg_foreign_table  (cost=0.00..1.04 rows=1 width=293)
   Output: ftrelid, ftserver, ftoptions
   Filter: (pg_foreign_table.ftrelid = '157457'::oid)
 Optimizer: Postgres-based planner
(4 rows)
```
According to my debugging, the estimate cost of `Index Scan` is higher than `Seq Scan`. So `Seq Scan` is selected here.
But the planner also considers `Index Scan`.

So I think if `Index Scan` has less cost, the index will be used.

**Comment by water32** [comment]
> > > > In addition, the pg_exttable view seems to have performance problems, because even querying a single record, the index cannot be used.
> > > 
> > > 
> > > The information in pg_exttable view is obtained from pg_foregin_table catalog in GP7. (Instead of pg_exttable catalog in GP6) If we can build index in pg_foregin_table catalog table, I think the index can be used.
> > 
> > 
> > The pg_foreign_table have an index on ftrelid，if the function pg_exttable() only format one row from pg_foreign_table, query on view pg_exttable can use the table's index.
> 
> Thanks a lot for your information. I tried to query `pg_foreign_table` in GP7 directly. The plan is as follows.
> 
> ```
> testdb=# explain verbose select * from pg_foreign_table where ftrelid = 'public.test_ext'::regclass;
>                                  QUERY PLAN
> -----------------------------------------------------------------------------
>  Seq Scan on pg_catalog.pg_foreign_table  (cost=0.00..1.04 rows=1 width=293)
>    Output: ftrelid, ftserver, ftoptions
>    Filter: (pg_foreign_table.ftrelid = '157457'::oid)
>  Optimizer: Postgres-based planner
> (4 rows)
> ```
> 
> According to my debugging, the estimate cost of `Index Scan` is higher than `Seq Scan`. So `Seq Scan` is selected here. But the planner also considers `Index Scan`.
> 
> So I think if `Index Scan` has less cost, the index will be used.


According to my code read and debug, Now, the function pg_exttable in gp_exttable_fdw.c will out all external table records, so, query on view pg_exttable will never use index, only add a filter after Function Scan like:
```
postgres=# set enable_seqscan to 0;
SET
postgres=# explain select * from pg_exttable where reloid = 'public.test_ext'::regclass::oid;
                            QUERY PLAN
-------------------------------------------------------------------
 Function Scan on pg_exttable  (cost=0.00..12.50 rows=1 width=176)
   Filter: (reloid = '19035'::oid)
 Optimizer: Postgres-based planner
(3 rows)

postgres=# explain select * from pg_foreign_table where ftrelid = 'public.test_ext'::regclass::oid;
                                              QUERY PLAN
-------------------------------------------------------------------------------------------------------
 Index Scan using pg_foreign_table_relid_index on pg_foreign_table  (cost=0.14..8.15 rows=1 width=240)
   Index Cond: (ftrelid = '19035'::oid)
 Optimizer: Postgres-based planner
(3 rows)
```
To further explain what I mean, let me give you a demo:
```
CREATE OR REPLACE FUNCTION test_exttable(IN reloid oid, OUT urilocation text[], OUT execlocation text[], OUT fmttype "char", OUT fmtopts text, OUT "options" text[], OUT command text, OUT rejectlimit integer, OUT rejectlimittype "char", OUT logerrors boolean, OUT "encoding" integer, OUT "writable" boolean) RETURNS SETOF record
AS $$SELECT urilocation, execlocation, fmttype, fmtopts, options, command, rejectlimit, rejectlimittype, logerrors, encoding, writable FROM pg_exttable WHERE  reloid = $1;$$
LANGUAGE sql VOLATILE COST 1.0 ROWS 1000.0;

CREATE OR REPLACE VIEW test_exttable AS
SELECT ftrelid reloid, (test_exttable(f.ftrelid)).* FROM pg_foreign_table f WHERE ftserver = 13703;
```
If the implementation of the test_exttable function is changed to parsing a single row of pg_foreign_table.ftoptions, then the query on the view test_exttable will allow the use of index.

**Comment by jingwen-yang-yjw** [comment]
> > > > > In addition, the pg_exttable view seems to have performance problems, because even querying a single record, the index cannot be used.
> > > > 
> > > > 
> > > > The information in pg_exttable view is obtained from pg_foregin_table catalog in GP7. (Instead of pg_exttable catalog in GP6) If we can build index in pg_foregin_table catalog table, I think the index can be used.
> > > 
> > > 
> > > The pg_foreign_table have an index on ftrelid，if the function pg_exttable() only format one row from pg_foreign_table, query on view pg_exttable can use the table's index.
> > 
> > 
> > Thanks a lot for your information. I tried to query `pg_foreign_table` in GP7 directly. The plan is as follows.
> > ```
> > testdb=# explain verbose select * from pg_foreign_table where ftrelid = 'public.test_ext'::regclass;
> >                                  QUERY PLAN
> > -----------------------------------------------------------------------------
> >  Seq Scan on pg_catalog.pg_foreign_table  (cost=0.00..1.04 rows=1 width=293)
> >    Output: ftrelid, ftserver, ftoptions
> >    Filter: (pg_foreign_table.ftrelid = '157457'::oid)
> >  Optimizer: Postgres-based planner
> > (4 rows)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > According to my debugging, the estimate cost of `Index Scan` is higher than `Seq Scan`. So `Seq Scan` is selected here. But the planner also considers `Index Scan`.
> > So I think if `Index Scan` has less cost, the index will be used.
> 
> According to my code read and debug, Now, the function pg_exttable in gp_exttable_fdw.c will out all external table records, so, query on view pg_exttable will never use index, only add a filter after Function Scan like:
> 
> ```
> postgres=# set enable_seqscan to 0;
> SET
> postgres=# explain select * from pg_exttable where reloid = 'public.test_ext'::regclass::oid;
>                             QUERY PLAN
> -------------------------------------------------------------------
>  Function Scan on pg_exttable  (cost=0.00..12.50 rows=1 width=176)
>    Filter: (reloid = '19035'::oid)
>  Optimizer: Postgres-based planner
> (3 rows)
> 
> postgres=# explain select * from pg_foreign_table where ftrelid = 'public.test_ext'::regclass::oid;
>                                               QUERY PLAN
> -------------------------------------------------------------------------------------------------------
>  Index Scan using pg_foreign_table_relid_index on pg_foreign_table  (cost=0.14..8.15 rows=1 width=240)
>    Index Cond: (ftrelid = '19035'::oid)
>  Optimizer: Postgres-based planner
> (3 rows)
> ```
> 
> To further explain what I mean, let me give you a demo:
> 
> ```
> CREATE OR REPLACE FUNCTION test_exttable(IN reloid oid, OUT urilocation text[], OUT execlocation text[], OUT fmttype "char", OUT fmtopts text, OUT "options" text[], OUT command text, OUT rejectlimit integer, OUT rejectlimittype "char", OUT logerrors boolean, OUT "encoding" integer, OUT "writable" boolean) RETURNS SETOF record
> AS $$SELECT urilocation, execlocation, fmttype, fmtopts, options, command, rejectlimit, rejectlimittype, logerrors, encoding, writable FROM pg_exttable WHERE  reloid = $1;$$
> LANGUAGE sql VOLATILE COST 1.0 ROWS 1000.0;
> 
> CREATE OR REPLACE VIEW test_exttable AS
> SELECT ftrelid reloid, (test_exttable(f.ftrelid)).* FROM pg_foreign_table f WHERE ftserver = 13703;
> ```
> 
> If the implementation of the test_exttable function is changed to parsing a single row of pg_foreign_table.ftoptions, then the query on the view test_exttable will allow the use of index.

Thanks for your detailed explanation! I got your point.
I'll look into how to implement your idea. Thanks again for the insight!

**Comment by jingwen-yang-yjw** [comment]
Fixed by https://github.com/greenplum-db/gpdb/pull/17182. So close it here.
