### ISSUE TITLE
[7.X]Some questions about GP7 resource groups.

### ISSUE THREAD

**Issue by FYIsunny** [greenplum-db/gpdb#17195]
**Greenplum version or build**
postgres=# select version();
version

PostgreSQL 12.12 (Greenplum Database 7.0.0-beta.0 build dev) on aarch64-unknown-linux-gnu, compiled by gcc (GCC) 7.3.0,
64-bit compiled on Feb 7 2024 09:46:23 Bhuvnesh C.
(1 row)

**OS version and uname -a**
centos 7

**Actual behavior**
Could you please take a look at the following questions:
1.I need to confirm again, in the statement "The parameter MEMORY_LIMIT of a resource group sets the maximum amount of memory reserved for this resource group on a segment", when creating a resource group, does the MEMORY_LIMIT parameter refer to the memory limit on the segment host, or the memory of a single primary segment on the segment host?

2.The default value of gp_resource_group_bypass_direct_dispatch for a resource group is true, which bypasses the resource group's limits. This raises the question of why the default isn't false. Or is it that setting it to false only takes effect at the session level?

3.Which one do you recommend using: "select * from gp_toolkit.gp_resgroup_status_per_segment;" or "SELECT * FROM gp_toolkit.gp_resgroup_status_per_host;" to obtain more precise and real-time statistics of segment memory usage?

4.Can I calculate the real-time memory usage of each segment by dividing the memory_usage from gp_resgroup_status_per_host by the number of primary segments?

5.I need to confirm again, in the statement "The parameter MEMORY_LIMIT of a resource group sets the maximum amount of memory reserved for this resource group on a segment", when creating a resource group, does the MEMORY_LIMIT parameter refer to the memory limit on the segment host, or the memory of a single primary segment on the segment host?

6.When creating a new resource group, what is the recommended maximum value for MEMORY_LIMIT? For example, there is a calculation example for resource queues. Could you also provide an example for a resource group? The example for a resource queue is: "Set MEMORY_LIMIT to 90% of memory available on a per-segment basis. For example, if a host has 48 GB of physical memory and 6 segment instances, then the memory available per segment instance is 8 GB. You can calculate the recommended MEMORY_LIMIT for a single queue as 0.90*8=7.2 GB. If there are multiple queues created on the system, their total memory limits must also add up to 7.2 GB."

7.If multiple resource groups have allocated all available memory, would there be a situation of memory resource contention when all resource groups are actively utilizing their allocated memory?

8.If one instance experiences an exception, would the memory resource limit for another instance increase?

**Comment by kainwen** [comment]
I reply in issue https://github.com/greenplum-db/gpdb/issues/17174
We will try to reply when having time. Please don't duplicate things.
