### ISSUE TITLE
ERROR: for SELECT DISTINCT, ORDER BY expressions must appear in select list

### ISSUE THREAD

**Issue by wonb168** [greenplum-db/gpdb#17288]
my sql:	
```
explain analyze
SELECT DISTINCT plan_name as label, plan_code as value 
FROM tenant_hggp7_biz.gto_distribution_plan
ORDER BY convert_to(plan_name,'GBK'), plan_code
```
this sql is OK in gp6,
but in gp7:
```
ERROR: for SELECT DISTINCT, ORDER BY expressions must appear in select list
```
how to solve? if have mothod by not editing the sql code?

**Comment by kainwen** [comment]
This commit 18188949bcd08a1f147afdd9f56557346c870c63 introduces this.
6X's code is GPDB-specific code. Later the above commit remove the logic to keep the same as upstream.

**Comment by kainwen** [comment]
Seems we don't want to do much for 7X (keep the same as upstream). Close this. Please rewrite the SQL. Thanks for the discussion.

**Comment by wonb168** [comment]
can void this via setting charset？eg. zh_CN.utf-8
