### ISSUE TITLE
installation package not working 

### ISSUE THREAD

**Issue by Krishnapro** [greenplum-db/gpdb#17290]
I'm trying to download the Greenplum Database version 7 to install on CentOs 7 from this link - https://network.pivotal.io/products/vmware-greenplum#/releases/1462218/file_groups/18520 but it's broken or not working.

please help me to install gpdb.

**Comment by higuoxing** [comment]
Greenplum 7 officially doesn't support CentOS7. I think you should upgrade your system to RHEL8/Rocky8/Oracle Linux8.

**Comment by Krishnapro** [comment]
Thank you for the update.
