### ISSUE TITLE
Find bug "ERROR:  token for user id: 10, session: 11 doesn't exist (cdbendpoint.c:942)" when I use PARALLEL RETRIEVE CURSOR

### ISSUE THREAD

**Issue by lmzzzzz1** [greenplum-db/gpdb#17325]
## Bug Report
While using the PARALLEL RETRIEVE CURSOR, I encountered an error:
```sql
postgres=# select * from gp_endpoints ;
ERROR:  token for user id: 10, session: 11 doesn't exist (cdbendpoint.c:942)  (seg0 11.164.61.163:7002 pid=117390) (cdbendpoint.c:942)
```

### Greenplum version or build
7 & 6

### OS version and uname -a
centos7

### Step to reproduce the behavior
Upon examining the code for gp_get_segment_endpoints and get_token_from_session_hashtable, I realized that this is related to the concurrent use of the PARALLEL RETRIEVE CURSOR.

https://github.com/greenplum-db/gpdb/blob/b5f82e709fccc6110ec5539f6e6899e08aa71080/src/backend/cdb/endpoint/cdbendpoint.c#L332-L337

When QE setup endpoints, It will step1. `alloc_endpoint` step2. `setup_endpoint_token_entry`, modify shared memory's `sharedEndpoints` and `EndpointTokenHash` respectively. Both of them will invoke `LWLockAcquire(ParallelCursorEndpointLock, LW_EXCLUSIVE)` and `LWLockRelease` to acquire and release the LWLOCK. 

However, in a concurrent scenario, session1 executes `declare c1 PARALLEL RETRIEVE CURSOR FOR select * from t`; after its QE finishes `alloc_endpoint` and successfully modifies `sharedEndpoints`, it is about to execute `setup_endpoint_token_entry` to modify `EndpointTokenHash`. At this moment, session2 executes `select * FROM pg_catalog.gp_endpoints;`, which preempts the `ParallelCursorEndpointLock`, leading to the absence of `EndpointTokenHash`, resulting in the above ERROR.

![image](https://github.com/greenplum-db/gpdb/assets/43360234/32aa0abc-8267-46db-9114-2f8c11ffe3a8)

To verify this issue, you can insert 
```c
pg_usleep(10000000L) 
```
between lines 336 and 337, then open two sessions to test it.

**Comment by adam8157** [comment]
Fixed by https://github.com/greenplum-db/gpdb/pull/17326
