### ISSUE TITLE
gppkg in version 7 issues

### ISSUE THREAD

**Issue by lmugnano4537** [greenplum-db/gpdb#17328]
## Bug Report
The new version of gppkg has a few issues that make it difficult to work with when it's used in automation scripts (like gpoptional for example):

1) When I run gppkg query and put output to a file the file contains all kinds of escape garbage characters because the "display" version is displaying unnecessary messages in color.  
2) The gppkg query should just tell me what packages are installed, period (like it did in prior versions).  As a user I really don't care that the script is "Detecting network topology", nor do I need gppkg to tell me how many coordinator and segment instances I have.  These are the messages that are in color that are causing output to files to contain all the junk.  These messages should only be included when -v (verbose) output is chosen since the output has nothing to do with the request I made which is to query package names
3) gppkg query --local appears to give me the output I want (no junk characters in the output and no unnecessary messages.  HOWEVER, for some reason when I run with the --local option the DataSciencePython3.9 package doesn't get returned.  I don't know if this is a bug since I really don't know what --local means.

### Greenplum version or build
VMware Greenplum 7.1

### OS version and uname -a
CentOS Stream release 8
Linux gpdb7 6.4.16-linuxkit #1 SMP PREEMPT_DYNAMIC Tue Oct 10 20:42:40 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Expected behavior
- gppkg query should return just the list of packages with no additional messages unless the user include verbose option
- gppkg query --local should return the DataSciencePython3.9 (don't know what others wouldn't be returned, must be some difference in this package vs others that is causing --local to not display it)

### Actual behavior
Here is what I get in output file when I run gppkg query > out1
^[[0A^[[0m
^[[0m^[[1mDetecting network topology^[[0m^[[0m:^[[0m^[[0m    ^[[0m^[[0m[^[[0m^[[0m^[[0m^[[0m                                                               ^[[0m^[[0m]^[[0m^[[0m ^[[0m^[[0m0.0^[[0m^[[0m^[[0m^[[0m^M^[[0m^[[1A^[[0m
^[[0m^[[1mDetecting network topology^[[0m^[[0m:^[[0m^[[0m    ^[[0m^[[0m[^[[0m^[[0m^[[0m^[[0m                                                               ^[[0m^[[0m]^[[0m^[[0m ^[[0m^[[0m0.0^[[0m^[[0m^[[0m^[[0m^M^[[0m^[[1A^[[0m
^[[0m^[[1mDetecting network topology^[[0m^[[0m:^[[0m^[[0m    ^[[0m^[[0m[^[[0m^[[0m^[[0m^[[0m                                                               ^[[0m^[[0m]^[[0m^[[0m ^[[0m^[[0m0.0^[[0m^[[0m^[[0m^[[0m^M^[[0m^[[1A^[[0m
^[[0m^[[1mDetecting network topology^[[0m^[[0m:^[[0m^[[0m    ^[[0m^[[0m[^[[0m^[[0m^[[0m^[[0m                                                               ^[[0m^[[0m]^[[0m^[[0m ^[[0m^[[0m0.0^[[0m^[[0m^[[0m^[[0m^M^[[0m^[[1A^[[0m
^[[0m^[[1mDetecting network topology^[[0m^[[0m:^[[0m^[[0m    ^[[0m^[[0m[^[[0m^[[0m^[[0m^[[0m                                                               ^[[0m^[[0m]^[[0m^[[0m ^[[0m^[[0m0.0^[[0m^[[0m^[[0m^[[0m^M^[[0m^[[1A^[[0m
^[[0m^[[1mDetecting network topology^[[0m^[[0m:^[[0m^[[0m    ^[[0m^[[0m[^[[0m^[[0m^[[0m^[[0m                                                               ^[[0m^[[0m]^[[0m^[[0m ^[[0m^[[0m0.0^[[0m^[[0m^[[0m^[[0m^M^[[0m^[[1A^[[0m
^[[0m^[[1mDetecting network topology^[[0m^[[0m:^[[0m^[[0m    ^[[0m^[[0m[^[[0m^[[0m^[[0m^[[0m                                                               ^[[0m^[[0m]^[[0m^[[0m ^[[0m^[[0m0.0^[[0m^[[0m^[[0m^[[0m^M^[[0m^[[1A^[[0m
^[[0m^[[1mDetecting network topology^[[0m^[[0m:^[[0m^[[0m    ^[[0m^[[0m[^[[0m^[[0m===^[[0m>^[[0m^[[0m^[[0m                                                           ^[[0m^[[0m]^[[0m^[[0m ^[[0m^[[0m1.0^[[0m^[[0m^[[0m^[[0m^M^[[0m^[[1A^[[0m
^[[0m^[[1mDetecting network topology^[[0m^[[0m:^[[0m^[[0m    ^[[0m^[[0m[^[[0m^[[0m===^[[0m>^[[0m^[[0m^[[0m                                                           ^[[0m^[[0m]^[[0m^[[0m ^[[0m^[[0m1.0^[[0m^[[0m^[[0m^[[0m^M^[[0m^[[1A^[[0m
^[[0m^[[1mDetecting network topology^[[0m^[[0m:^[[0m^[[0m    ^[[0m^[[0m[^[[0m^[[0m===^[[0m>^[[0m^[[0m^[[0m                                                           ^[[0m^[[0m]^[[0m^[[0m ^[[0m^[[0m1.0^[[0m^[[0m^[[0m^[[0m^M^[[0m^[[1A^[[0m
^[[0m^[[1mDetecting network topology^[[0m^[[0m:^[[0m^[[0m    ^[[0m^[[0m[^[[0m^[[0m===^[[0m>^[[0m^[[0m^[[0m                                                           ^[[0m^[[0m]^[[0m^[[0m ^[[0m^[[0m1.0^[[0m^[[0m^[[0m^[[0m^M^[[0m^[[1A^[[0m
^[[0m^[[1mDetecting network topology^[[0m^[[0m:^[[0m^[[0m    ^[[0m^[[0m[^[[0m^[[0m=======^[[0m>^[[0m^[[0m^[[0m                                                       ^[[0m^[[0m]^[[0m^[[0m ^[[0m^[[0m2.0^[[0m^[[0m^[[0m^[[0m^M^[[0m^[[1A^[[0m
^[[0m^[[1mDetecting network topology^[[0m^[[0m:^[[0m^[[0m    ^[[0m^[[0m[^[[0m^[[0m=======^[[0m>^[[0m^[[0m^[[0m                                                       ^[[0m^[[0m]^[[0m^[[0m ^[[0m^[[0m2.0^[[0m^[[0m^[[0m^[[0m^M^[[0m^[[1A^[[0m
^[[0m^[[1mDetecting network topology^[[0m^[[0m:^[[0m^[[0m    ^[[0m^[[0m[^[[0m^[[0m=======^[[0m>^[[0m^[[0m^[[0m                                                       ^[[0m^[[0m]^[[0m^[[0m ^[[0m^[[0m2.0^[[0m^[[0m^[[0m^[[0m^M^[[0m^[[1A^[[0m
^[[0m^[[1mDetecting network topology^[[0m^[[0m:^[[0m^[[0m    ^[[0m^[[0m[^[[0m^[[0m=======^[[0m>^[[0m^[[0m^[[0m                                                       ^[[0m^[[0m]^[[0m^[[0m ^[[0m^[[0m2.0^[[0m^[[0m^[[0m^[[0m^M^[[0m^[[1A^[[0m
"i" 93L, 18079C                                                                                                               1,1           Top
^[[0m^[[1mDetecting network topology^[[0m^[[0m:^[[0m^[[0m    ^[[0m^[[0m[^[[0m^[[0m========================================================^[[0m>^[[0m^[[0m^[[0m     ^[[0m^[[0m]^[[0m^[[0m ^[[0m^[[0m14.0^[[0m^[[0m^[[0m^[[0m^M^[[0m^[[1A^[[0m
^[[0m^[[1mDetecting network topology^[[0m^[[0m:^[[0m^[[0m    ^[[0m^[[0m[^[[0m^[[0m========================================================^[[0m>^[[0m^[[0m^[[0m     ^[[0m^[[0m]^[[0m^[[0m ^[[0m^[[0m14.0^[[0m^[[0m^[[0m^[[0m^M^[[0m^[[1A^[[0m
^[[0m^[[1mDetecting network topology^[[0m^[[0m:^[[0m^[[0m    ^[[0m^[[0m[^[[0m^[[0m========================================================^[[0m>^[[0m^[[0m^[[0m     ^[[0m^[[0m]^[[0m^[[0m ^[[0m^[[0m14.0^[[0m^[[0m^[[0m^[[0m^M^[[0m^[[1A^[[0m
^[[0m^[[1mDetecting network topology^[[0m^[[0m:^[[0m^[[0m    ^[[0m^[[0m[^[[0m^[[0m=============================================================^[[0m>^[[0m^[[0m^[[0m^[[0m^[[0m]^[[0m^[[0m ^[[0m^[[0m15.0^[[0m^[[0m^[[0m^[[0m^M^[[0m^[[1A^[[0m
^[[0m^[[1mDetecting network topology^[[0m^[[0m:^[[0m^[[0m    ^[[0m^[[0m[^[[0m^[[0m=============================================================^[[0m>^[[0m^[[0m^[[0m^[[0m^[[0m]^[[0m^[[0m ^[[0m^[[0m15.0^[[0m^[[0m^[[0m^[[0m^M^[[0m^[[1A^[[0m
^[[0m^[[1mDetecting network topology^[[0m^[[0m:^[[0m^[[0m    ^[[0m^[[0m[^[[0m^[[0m=============================================================^[[0m>^[[0m^[[0m^[[0m^[[0m^[[0m]^[[0m^[[0m ^[[0m^[[0m15.0^[[0m^[[0m^[[0m^[[0m^M^[[0m^[[1A^[[0m
^[[0m^[[1mDetecting network topology^[[0m^[[0m:^[[0m^[[0m    ^[[0m^[[0m[^[[0m^[[0m=============================================================^[[0m>^[[0m^[[0m^[[0m^[[0m^[[0m]^[[0m^[[0m ^[[0m^[[0m15.0^[[0m^[[0m^[[0m^[[0m^M^[[0m^[[1A^[[0m
^[[0m^[[1mDetecting network topology^[[0m^[[0m:^[[0m^[[0m    ^[[0m^[[0m[^[[0m^[[0m=============================================================^[[0m>^[[0m^[[0m^[[0m^[[0m^[[0m]^[[0m^[[0m ^[[0m^[[0m15.0^[[0m^[[0m^[[0m^[[0m^M^[[0m^[[1A^[[0m
^[[0m^[[1mDetecting network topology^[[0m^[[0m:^[[0m^[[0m    ^[[0m^[[0m[^[[0m^[[0m=============================================================^[[0m>^[[0m^[[0m^[[0m^[[0m^[[0m]^[[0m^[[0m ^[[0m^[[0m15.0^[[0m^[[0m^[[0m^[[0m^M^[[0m^[[1A^[[0m
^[[0m^[[1mDetecting network topology^[[0m^[[0m:^[[0m^[[0m    ^[[0m^[[0m[^[[0m^[[0m=============================================================^[[0m>^[[0m^[[0m^[[0m^[[0m^[[0m]^[[0m^[[0m ^[[0m^[[0m15.0^[[0m^[[0m^[[0m^[[0m^M^[[0m^[[1A^[[0m
^[[0m^[[1mDetecting network topology^[[0m^[[0m:^[[0m^[[0m    ^[[0m^[[0m[^[[0m^[[0m=============================================================^[[0m>^[[0m^[[0m^[[0m^[[0m^[[0m]^[[0m^[[0m ^[[0m^[[0m15.0^[[0m^[[0m^[[0m^[[0m^M^[[0m^[[1A^[[0m
^[[0m^[[1mDetecting network topology^[[0m^[[0m:^[[0m^[[0m    ^[[0m^[[0m[^[[0m^[[0m=============================================================^[[0m^[[0m=^[[0m^[[0m]^[[0m^[[0m ^[[0m^[[m[OK]^[[m^[[0m^[[0m^[[0m^M^[[0m
^[[0m^[[0m^[[0m^[[0m^[[m1 coordinator and 4 segment instances are detected on 1 unique host.^[[m^[[0m
^[[0mDataSciencePython3.9 - 2.1.0
MetricsCollector - 7.0.0_gp_7.0.0
greenplum_backup_restore - 1.30.4-gp7
h3-pg - h3-pg-v4.1.2+pivotal.1_gpdb7.0
pgvector - 0.5.1-0
postgresml - 2.7.13+greenplum.1.0.1

### Step to reproduce the behavior
Run gppkg query and pipe output to file.  Look at file using vi or od -c to see all the escape characters in the output.   If the first package (in my case above the "DataSciencePython3.9 - 2.1.0") was at least on it's own line then I can probably clean things up easier but, like I said, all these messages don't provide any user value so they shouldn't be there at all

**Comment by beeender** [comment]
Thanks a lot for your feedback! However, gppkg became a commercial product from GP7, issues related to it should not be tracked here.

We will evaluate your feedback and create internal issues for it.

**Comment by lmugnano4537** [comment]
ok, I'll open a SR then from my customer account I was testing this for although they aren't running 7 yet so, at this point, I'm evaluating 7 and trying to tell them everything that is going to break as well as new and improved features.  Obviously I want to reduce the "what is going to break" section as much as possible

**Comment by Sasasu** [comment]
>  for some reason when I run with the --local option the DataSciencePython3.9 package doesn't get returned. I don't know if this is a bug since I really don't know what --local means.

`--local` means gppkg will not query the hole cluster. If DataSciencePython3.9 does not shows in `query --local`, it means the current host does not have `DataSciencePython3.9` installed. try `sync --dryrun`, it will show some message about how to fix your cluster. 

> Run gppkg query and pipe output to file. Look at file using vi or od -c to see all the escape characters in the output. 

like `apt`, gppkg does not have a script interface, but you can use `--accept --verbose` to get some script friendly interface, `-v` will disable TUI.

And, please open a commercial ticket, gppkg is used to distribute closed source software.

**Comment by lmugnano4537** [comment]
Thanks for the additional information on the implementation of the new gppkg.  I think I figured out a way to make it such that the gp6 and gp7 versions of gppkg can work in the script we have
