### ISSUE TITLE
How to read the storage files of an AO table and recover the data as much as possible.

### ISSUE THREAD

**Issue by cobolbaby** [greenplum-db/gpdb#17365]
## Feature Request

**Is your feature request related to a problem? Please describe:**

When I face issues such as disk bad blocks, I need to recover the data as much as possible.

**Describe the feature you'd like to request:**

Could ignore the read error ?

**Comment by ashwinstar** [comment]
I believe you are reading the comment wrong on https://github.com/greenplum-db/gpdb/issues/11163#issuecomment-1216408442. The comment says either copy the full data directory from mirror or copy full files related to a particular affected table from mirror. It's not saying copy part of data from a file. That's too much unnecessary aspect and no plans. If file on primary can't be trusted just throw it away and see if mirror file is intact and use it. No point try to extract some portion of data from mirror file to fix things.

**Comment by cobolbaby** [comment]
@ashwinstar 

Sorry to bother you again. Currently, both the Primary and Mirror have issues reading a certain table. Under these circumstances, I just hope to recover as much data as possible.

**Comment by ashwinstar** [comment]
> recover as much data as possible

Maximum possibility I sense to recover data is from blocks which are before the block with checksum error. As all blocks following it we don't even know where they start can't retrieve anything beyond bad block.

> Could the operations on AO table files be encapsulated into a library that would be convenient to call?

I don't understand the requirement. https://github.com/greenplum-db/filedump uses AO headers and can dump similar to heap the metadata portion. You can always build more tools using the header files of AO, unclear why a library is required or will do.

**Comment by cobolbaby** [comment]
> https://github.com/greenplum-db/filedump uses AO headers and can dump similar to heap the metadata portion

If [filedump](https://github.com/greenplum-db/filedump) could parse the data from the AO table file, that would be sufficient to meet the requirements.

> Maximum possibility I sense to recover data is from blocks which are before the block with checksum error. As all blocks following it we don't even know where they start can't retrieve anything beyond bad block.

That's enough.
