### ISSUE TITLE
GPDB7 REGRESSION: External partitions isn't working as documented or as gpdb6 worked

### ISSUE THREAD

**Issue by lmugnano4537** [greenplum-db/gpdb#17405]
## Bug Report
It looks there may be some issue with creating external partitions in Greenplum 7.  The below test works in 6 but fails in Greenplum 7 with the error shown.  The documentation is also out of date because the example in the documentation uses partitionname in the alter statement which is no longer a column in Greenplum 7.  Is there a new way to do this in 7 that can be documented?

Here is the full test:
Note: Prior to this, start gpfdist process on port 8099
Ex: gpfdist -d /home/gpadmin/gptools/partition_maint -p 8099 -l /tmp/log &

create schema rp_tests;
DROP TABLE IF EXISTS RP_TESTS.RP_DATE_EXT;

CREATE TABLE RP_TESTS.RP_DATE_EXT
(
    RP_INT      INTEGER,
    RP_DATE DATE,
    RP_TIMESTAMP TIMESTAMP,
    RP_DIST_KEY INTEGER
)
WITH (
        APPENDONLY=TRUE
        ,COMPRESSTYPE=ZLIB
        ,COMPRESSLEVEL=9
        ,ORIENTATION=COLUMN
)
DISTRIBUTED BY (RP_DIST_KEY)
PARTITION BY RANGE(RP_DATE)
(
        START (DATE '2015-06-01') INCLUSIVE
        END (DATE '2016-01-01') EXCLUSIVE EVERY (INTERVAL '1 DAY')
);

COMMENT ON TABLE RP_TESTS.RP_DATE_EXT IS 'Range Partition on Date for external parts test';
INSERT into RP_TESTS.RP_DATE_EXT(select generate_series(1,100),'2015-06-01',null,generate_series(1,100));
INSERT into RP_TESTS.RP_DATE_EXT(select generate_series(1,100),'2015-07-01',null,generate_series(1,100));
INSERT into RP_TESTS.RP_DATE_EXT(select generate_series(1,100),'2015-08-01',null,generate_series(1,100));

create writable external table rp_tests.ext_rp_date_ext20150601 (like "rp_tests"."rp_date_ext") 
location ('gpfdist://localhost:8099/rp_tests_ext_rp_date_ext201506011714178411_0321875_0.gz') 
format 'text' (delimiter '|' null '');

insert into rp_tests.ext_rp_date_ext20150601 
select * from "rp_tests"."rp_date_ext" 
where rp_date >= '2015-06-01' and rp_date < '2015-06-02';

create external table rp_tests.r_ext_rp_date_ext20150601 (like "rp_tests"."rp_date_ext") 
location ('gpfdist://localhost:8099/rp_tests_ext_rp_date_ext201506011714178411_0321875_0.gz') 
format 'text' (delimiter '|' null '');

alter table "rp_tests"."rp_date_ext" 
      alter partition for ('2015-06-01') 
      exchange partition for ('2015-06-01') 
      with table rp_tests.r_ext_rp_date_ext20150601 
      without validation;

NOTICE:  specifying "WITHOUT VALIDATION" acts as no operation
DETAIL:  If the new partition is a regular table, validation is performed to make sure all the rows obey partition constraint. If the new partition is external or foreign table, no validation is performed.
ERROR:  table "rp_date_ext_1_prt_1" is not partitioned

### Greenplum version or build
7.1

### OS version and uname -a
All

### Expected behavior
The partition should be exchanged with the external table and become and external partition on the table.

### Actual behavior
Fails, same test works fine in Greenplum 6

### Step to reproduce the behavior
See above

**Comment by lmugnano4537** [comment]
The below set of commands (using the new syntax) does work so maybe you can just change the documentation to reflect the new syntax and indicate the old syntax no longer is supported in this case:

externalize_part_step1:
    create writable external table rp_tests.ext_rp_date_ext20150602 (like "rp_tests"."rp_date_ext") location ('gpfdist://localhost:8099/rp_tests_ext_rp_date_ext201506021714268232_3423479_0.gz') format 'text' (delimiter '|' null '')

externalize_part_step2:
    insert into rp_tests.ext_rp_date_ext20150602 select * from rp_tests.rp_date_ext_1_prt_2

Rows Inserted: 100
externalize_part_step3:
    create external table rp_tests.r_ext_rp_date_ext20150602 (like "rp_tests"."rp_date_ext") location ('gpfdist://localhost:8099/rp_tests_ext_rp_date_ext201506021714268232_3423479_0.gz') format 'text' (delimiter '|' null '')

externalize_part_step4:
    alter table "rp_tests"."rp_date_ext" detach partition rp_tests.rp_date_ext_1_prt_2

externalize_part_step5:
    alter table "rp_tests"."rp_date_ext" attach partition rp_tests.r_ext_rp_date_ext20150602 for values from ('2015-06-02') to ('2015-06-03')

externalize_part_step6.1:
    drop table rp_tests.rp_date_ext_1_prt_2

externalize_part_step6.2:
    drop external table rp_tests.ext_rp_date_ext20150602

Here is the link to the incorrect documentation in 7.1:

https://docs.vmware.com/en/VMware-Greenplum/7/greenplum-database/admin_guide-ddl-classic-partition.html#topic_yhz_gpn_qs

"Exchanging a Leaf Partition with an External Table"

**Comment by ashwinstar** [comment]
@huansong @Chibin work together and see what follow-up is required for this one. New syntax usage is preferred for sure compared to old exchange as its better.

Though we should still know why old syntax didn't work - as expected to work (guessing something funky going on with partition name - didn't check the details).

**Comment by Chibin** [comment]
Just throwing this out here, I saw found this test that's similar?:

```
-- This used to work on GPDB 6 and below, but it is now rejected. ALTER
-- PARTITION is used to address subpartitions, it is not needed otherwise.
create table parttab_y (a int4, b int4) distributed by (a);
alter table parttab alter partition for (1) exchange partition for (1) with table parttab_y;
ERROR:  table "parttab_1_prt_1" is not partitioned
```

**Comment by huansong** [comment]
Yes `ALTER PARTITION` is supposed to be used in a multi-level partition hierarchy. As mentioned in doc:
```
If altering a partition deeper than the first level of partitions, use ALTER PARTITION clauses to specify which sub-partition in the hierarchy you want to alter
```

If we run this it would work:
```sql
alter table "rp_tests"."rp_date_ext"
exchange partition for ('2015-06-01')
with table rp_tests.r_ext_rp_date_ext20150601
without validation;
```

For some more detailed comment see: https://github.com/greenplum-db/gpdb/issues/15055#issuecomment-1444378136.

**Comment by lmugnano4537** [comment]
Cool, thanks.
