### ISSUE TITLE
IS GPDB4.3.8 or 4.3.9 not correct at million records'  multiplying multi  numberic columns' ? 

### ISSUE THREAD

**Issue by gloCalHelp** [greenplum-db/gpdb#1747]
Dear GPDB's authors and pioneers,

      Is there anyone who can confirm me with that new GPDB versions' over 1 million records' multi numberic coloumns' multiplying and dividing and adding results, are all having a very very tiny difference with Excel's muliplying, dividing and adding results? 

     It is strange that, 4 months ago, when I tested GPDB 4.3.8 (or 4.3.9 not so sure) by  multiplying, dividing, adding million records'   multi  numberic columns' , and compared the results with WPS or MS Excel's   multiplying, dividing, adding's results,  only the GPDB's multiplying result has over single  digit     difference with Excel's multiplying on the same columns' data. Please check the screencopy. 
the -25.765625 is the difference result of 1 million records' multi numberic colomns' multiplying, the other two results of dividing and adding  have a reasonable tiny difference.

![100mrecmultimultiplyerror](https://cloud.githubusercontent.com/assets/2160811/22878060/2b376900-f213-11e6-974d-16d98c346ca1.jpg)

**Comment by hlinnaka** [comment]
Can you share the actual table schema, data and query?

My first guess is that it could be rounding errors, if you're using the floating point datatypes, float4 or float8, rather than numeric.

**Comment by ascherbaum-pivotal** [comment]
What exactly is the "new GPDB version" for you? Is it a 4.3 or a 5.x?

**Comment by gloCalHelp** [comment]
@ascherbaum-pivotal  I am sorry to make you puzzled, the new GPDB version is better to refer to newer version than 4.3.9, I think.  And isn't my offering this strange bug a great benefit to GPDB's future market?

@hlinnaka  I am sorry that I don't keep the 4 months ago's  query, I just keep table schema and data in a Excel file, I did these fundament tests with other 2 colleagues and test not only once. The table schema is: 
DROP TABLE IF EXISTS "public"."testLoadData";
CREATE TABLE "public"."testLoadData" (
"id" int8 DEFAULT nextval('"testLoadData_id_seq"'::regclass) NOT NULL,
"SSYF" varchar(18),
"xfsbh" varchar(18),
"gfmc" varchar(168),
"xfmc" varchar(168),
"kprq" varchar(19),
"fpdm" varchar(15),
"fphm" varchar(10),
"wp_id" int2,
"hwmc" varchar(168),
"je" numeric(26,4),
"sl" numeric(12,4),
"rzsj" varchar(19),
"se" numeric(26,4)
)
WITH (OIDS=FALSE)
;

And the muliplying query should be : select sum(a.se*a.sl*a.je) from  "public"."testLoadData" as a where id >1000 and id <1011000. 

Anyway, if you have a GPDB which is storing a table with over 1 million records and over 3 numberic(*,4/5/6)    columns , could you have a comparing test with excel's muliplying now?

And I am also looking for a big data relative job in China big cities, anyone recommend a good big data architecture job to me will get a small monthly sharing to prove I am deserving your recommendation.

**Comment by hlinnaka** [comment]
That indeed seems strange, but the thing is, there just isn't enough information here to reproduce it. We'd need to see the actual data and query. Or even better, a small artificial test case using made-up data that shows the same problem.

Adding up numerics is a very common operation, so I'd be very surprised if it's producing incorrect results. That's why I'm betting on a rounding error or a similar issue that isn't a bug but expected behavior. But hard to tell, without more a clear test case.

**Comment by ascherbaum-pivotal** [comment]
@gloCalHelp Sorry for the confusion. This is not about benefits for future markets, but about tracking down which version you are using, and what was the last version where this worked for you.

As Heikki pointed out: it would be helpful if you can create a small test case which shows the problem. The DDL, a few hundred lines of data, just the colums you are using in your query, and the actual query. That should be enough to reproduce the problem, hopefully.

And another question: did you verify the results in a commandline client, or just in Excel?

**Comment by gloCalHelp** [comment]
@hlinnaka  at the beginning, I was also feeling doubt on a rounding error or expected result, but I have extended the precision of numberic to 4 decimal place. 
@ascherbaum-pivotal  as you all seeing, not only me but  3 persons' testing , we multiplying around 1 million records, and only produce -25. differences, if I did again as your saying of only a few hundred lines, I guest that the diffence may be only smaller than 0.001, which can often be ignored. 

but anyway, I am not working on Greenplum now and I can not test now.

In order to let me and others to continue with suggesting other companies to use Greenplum, 
is there anyone who can do a similar number of 1 million records' multi numberic coloumns' multiplying? and
select out the numberic coloumn's data to Excel to do a multiplying result comparing?

@ascherbaum-pivotal  we did the comparing on two kinds of Excel, one is WPS excel and the other is MS excel.

**Comment by gloCalHelp** [comment]
@ascherbaum-pivotal  in fact, doing this comparing test with excel should be the fastest and easiest method to confirm GPDB 4.3.8's multiplying correctness. I don't believe command line client has a faster way than excel  to get over 3 millions' data in and multiplying.

**Comment by hlinnaka** [comment]
I don't think this is going to go anywhere, until we have a reproducible test case, so I'm closing this issue for now. Feel free to reopen once you have a clear test case to demonstrate the problem.

**Comment by andreasscherbaum** [comment]
Ok, I spent a few minutes looking into this issue. After all, don't want to risk a bug.

Here is what I did:

- wrote a small Perl script which generates random numbers (10000000 rows, 3 columns, up to 100000 before decimal point, 4 digits after decimal point)
- installed the following GBDP versions: 4.3.8.0, 4.3.9.0, 4.3.11.1
- created a table with 3x NUMERIC(15, 4) columns in each database
- did SUM of each column, and SUM of all three columns multiplied, and SUM of all three columns added


The SQL code for the test:
```
\set ON_ERROR_STOP
\set ECHO all

SELECT version();

DROP TABLE IF EXISTS issue1747;
CREATE TABLE issue1747 (
  col1       NUMERIC(15, 4),
  col2       NUMERIC(15, 4),
  col3       NUMERIC(15, 4)
) DISTRIBUTED RANDOMLY;

\timing
COPY issue1747 FROM '/home/gpadmin/random_numbers.csv' WITH DELIMITER AS E'\t';
\timing

SELECT COUNT(*) FROM issue1747;

SELECT SUM(col1) AS col1,
       SUM(col2) AS col2,
       SUM(col3) AS col3
  FROM issue1747;

SELECT SUM(col1 * col2 * col3)
  FROM issue1747;

SELECT SUM(col1 + col2 + col3)
  FROM issue1747;
```


The script which generates the random data:
```
#!/usr/bin/env perl

use strict;

my $lines = 10000000;
my $numbers = 3;
my $decimal_positions = 4;
my $random_max = 100000;

for (my $l1 = 1; $l1 <= $lines; $l1++) {
    my @line = ();
    for (my $l2 = 1; $l2 <= $numbers; $l2++) {
        push(@line, generate_random_number($random_max, $decimal_positions));
    }
    print join("\t", @line) . "\n";
}

sub generate_random_number {
    my $max = shift;
    my $pos = shift;

    # first generate a random number
    my $num = rand($max);
    # now round this number to the specified number of decimal positions
    my $factor = 10 ** $pos;
    $num = int($num * $factor) / $factor;

    return $num;
}
```

For installation I used the Ansible scripts from here: https://github.com/andreasscherbaum/gpdb-ansible

**Comment by andreasscherbaum** [comment]
```
issue1747=# \i ./1747.sql
\set ON_ERROR_STOP
\set ECHO all
SELECT version();
                                                                       version                                                                        
------------------------------------------------------------------------------------------------------------------------------------------------------
 PostgreSQL 8.2.15 (Greenplum Database 4.3.8.0 build 1) on x86_64-unknown-linux-gnu, compiled by GCC gcc (GCC) 4.4.2 compiled on Mar 28 2016 00:15:29
(1 row)

DROP TABLE IF EXISTS issue1747;
psql:./1747.sql:6: NOTICE:  table "issue1747" does not exist, skipping
DROP TABLE
CREATE TABLE issue1747 (
  col1       NUMERIC(15, 4),
  col2       NUMERIC(15, 4),
  col3       NUMERIC(15, 4)
) DISTRIBUTED RANDOMLY;
CREATE TABLE
\timing
Timing is on.
COPY issue1747 FROM '/home/gpadmin/random_numbers.csv' WITH DELIMITER AS E'\t';
COPY 10000000
Time: 9263,526 ms
\timing
Timing is off.
SELECT COUNT(*) FROM issue1747;
  count   
----------
 10000000
(1 row)

SELECT SUM(col1) AS col1,
       SUM(col2) AS col2,
       SUM(col3) AS col3
  FROM issue1747;
       col1        |       col2        |       col3        
-------------------+-------------------+-------------------
 499920731025.5451 | 499968669008.1543 | 499983943153.9183
(1 row)

SELECT SUM(col1 * col2 * col3)
  FROM issue1747;
                 sum                 
-------------------------------------
 1249688599162366534555.920116869161
(1 row)

SELECT SUM(col1 + col2 + col3)
  FROM issue1747;
        sum         
--------------------
 1499873343187.6177
(1 row)
```

**Comment by andreasscherbaum** [comment]
```
issue1747=# \i ./1747.sql
SELECT version();
                                                                       version                                                                        
------------------------------------------------------------------------------------------------------------------------------------------------------
 PostgreSQL 8.2.15 (Greenplum Database 4.3.9.0 build 1) on x86_64-unknown-linux-gnu, compiled by GCC gcc (GCC) 4.4.2 compiled on Aug  8 2016 05:36:26
(1 row)

DROP TABLE IF EXISTS issue1747;
psql:./1747.sql:6: NOTICE:  table "issue1747" does not exist, skipping
DROP TABLE
CREATE TABLE issue1747 (
  col1       NUMERIC(15, 4),
  col2       NUMERIC(15, 4),
  col3       NUMERIC(15, 4)
) DISTRIBUTED RANDOMLY;
CREATE TABLE
\timing
Timing is on.
COPY issue1747 FROM '/home/gpadmin/random_numbers.csv' WITH DELIMITER AS E'\t';
COPY 10000000
Time: 11060,288 ms
\timing
Timing is off.
SELECT COUNT(*) FROM issue1747;
  count   
----------
 10000000
(1 row)

SELECT SUM(col1) AS col1,
       SUM(col2) AS col2,
       SUM(col3) AS col3
  FROM issue1747;
       col1        |       col2        |       col3        
-------------------+-------------------+-------------------
 499920731025.5451 | 499968669008.1543 | 499983943153.9183
(1 row)

SELECT SUM(col1 * col2 * col3)
  FROM issue1747;
                 sum                 
-------------------------------------
 1249688599162366534555.920116869161
(1 row)

SELECT SUM(col1 + col2 + col3)
  FROM issue1747;
        sum         
--------------------
 1499873343187.6177
(1 row)
```

**Comment by andreasscherbaum** [comment]
```
issue1747=# \i ./1747.sql
SELECT version();
                                                                                               version                                                                                                
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 PostgreSQL 8.2.15 (Greenplum Database 4.3.11.1 build commit: 9fad76371cc5554375f0c32ae46571eccf41c75b) on x86_64-unknown-linux-gnu, compiled by GCC gcc (GCC) 4.4.2 compiled on Jan  5 2017 02:11:56
(1 row)

DROP TABLE IF EXISTS issue1747;
psql:./1747.sql:6: NOTICE:  table "issue1747" does not exist, skipping
DROP TABLE
CREATE TABLE issue1747 (
  col1       NUMERIC(15, 4),
  col2       NUMERIC(15, 4),
  col3       NUMERIC(15, 4)
) DISTRIBUTED RANDOMLY;
CREATE TABLE
\timing
Timing is on.
COPY issue1747 FROM '/home/gpadmin/random_numbers.csv' WITH DELIMITER AS E'\t';
COPY 10000000
Time: 11351,206 ms
\timing
Timing is off.
SELECT COUNT(*) FROM issue1747;
  count   
----------
 10000000
(1 row)

SELECT SUM(col1) AS col1,
       SUM(col2) AS col2,
       SUM(col3) AS col3
  FROM issue1747;
       col1        |       col2        |       col3        
-------------------+-------------------+-------------------
 499920731025.5451 | 499968669008.1543 | 499983943153.9183
(1 row)

SELECT SUM(col1 * col2 * col3)
  FROM issue1747;
                 sum                 
-------------------------------------
 1249688599162366534555.920116869161
(1 row)

SELECT SUM(col1 + col2 + col3)
  FROM issue1747;
        sum         
--------------------
 1499873343187.6177
(1 row)
```

**Comment by andreasscherbaum** [comment]
@gloCalHelp I can't see any difference in this calculations, and the numbers are certainly big enough to match your numbers in your Excel sheet.

Please go back and verify that Excel is not fooling you, by rounding numbers which do not fit the internal data types.

**Comment by andreasscherbaum** [comment]
On request from @Eulerizeit I ran the same tests on PostgreSQL (9.4.7) as well - just to make sure there are no differences between the two products.

```
issue1747=# \i 1747.sql                                                                                                                                                                                                                                                      
SELECT version();                                                                                                                                                                                                                                                             
                                                    version                                                                                                                                                                                                                   
---------------------------------------------------------------------------------------------------------------                                                                                                                                                               
 PostgreSQL 9.4.7 on x86_64-unknown-linux-gnu, compiled by gcc (Ubuntu 5.2.1-22ubuntu2) 5.2.1 20151010, 64-bit                                                                                                                                                                
(1 row)                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                              
DROP TABLE IF EXISTS issue1747;                                                                                                                                                                                                                                               
psql:1747.sql:6: NOTICE:  table "issue1747" does not exist, skipping                                                                                                                                                                                                          
DROP TABLE                                                                                                                                                                                                                                                                    
CREATE TABLE issue1747 (                                                                                                                                                                                                                                                      
  col1       NUMERIC(15, 4),                                                                                                                                                                                                                                                  
  col2       NUMERIC(15, 4),                                                                                                                                                                                                                                                  
  col3       NUMERIC(15, 4)                                                                                                                                                                                                                                                    
);
CREATE TABLE
\timing
Timing is on.
COPY issue1747 FROM '/home/ads/pivotal/ansible/gpdb-host/random_numbers.csv' WITH DELIMITER AS E'\t';
COPY 10000000
Time: 12991,438 ms
\timing
Timing is off.
SELECT COUNT(*) FROM issue1747;
  count   
----------
 10000000
(1 row)

SELECT SUM(col1) AS col1,
       SUM(col2) AS col2,
       SUM(col3) AS col3
  FROM issue1747;
       col1        |       col2        |       col3        
-------------------+-------------------+-------------------
 499920731025.5451 | 499968669008.1543 | 499983943153.9183
(1 row)

SELECT SUM(col1 * col2 * col3)
  FROM issue1747;
                 sum                 
-------------------------------------
 1249688599162366534555.920116869161
(1 row)

SELECT SUM(col1 + col2 + col3)
  FROM issue1747;
        sum         
--------------------
 1499873343187.6177
(1 row)
```

Same results with PostgreSQL as well. This rules out a bug in the product, and is a strong pointer that Excel can't handle big data numbers.

**Comment by gloCalHelp** [comment]
Well, thank you all pioneers to do the test, and maybe it is 2 kinds of Excel's shortcoming.  but why the dividing and adding has a reasonable tiny difference with Excels' results except multiplying?

Anyway, because your tests are all done in Postgres, if someone can test the computing with other databases, it would be more convincing.

**Comment by andreasscherbaum** [comment]
@gloCalHelp What's wrong with this test here?

```
SUM(col1 * col2 * col3)
```

Initially you claimed that this is a bug between Greenplum versions 4.3.8 and 4.3.9.

I tested both versions with operations on 10M rows, and couldn't find a difference. Plus in addition I compared the results to the latest Greenplum version, and PostgreSQL. All show the same results.

At this point I'm going to demand that you provide us with a test case (DDL, data, queries) so we can repeat your specific problem and see if that is a Greenplum problem.

I also would like to point you to this Excel documentation:

https://support.office.com/en-us/article/Data-types-in-Data-Models-E2388F62-6122-4E2B-BCAD-053E3DA9BA90#__toc327893213

Please read the table carefully, and let me know which data type can fit your large numbers with a high precision. Hint: there is none.
Your data is stored in "Decimal Number", which, by definition, is imprecise. Or put it another way: all your calculations in Excel are flawed.
Additional reading: https://en.wikipedia.org/wiki/Floating_point

Again: please go back and verify that Excel is not fooling you. Excel does not even have the capabilities to store large precise numbers.

**Comment by gloCalHelp** [comment]
@andreasscherbaum  maybe you are right, but there are at least these doubts:
1, your tests are all based on Postgres, but our initial aims are to check whether Greenplum 4.3.8(9)'s 4 fundamental mathematics' operation are correct or not.
2, if excel is not good at big number and plenty numbers' operating, then why 3 fundamental mathematics' opearating is correct with very tiny difference except multiplying?
3,   what is your words of "Your data is stored in Decimal Number, which, by definition, is imprecise. " referring to ? in Greenplum, you can see my submission table schema is using numberic type but not Decimal number type.
...

I have quit the former job and I cann't go back to check the multiplying in Greenplum.

**Comment by andreasscherbaum** [comment]
@gloCalHelp Your fundamental problem is that Greenplum does the correct math, but Excel then shows the data in an imprecise data type. Please follow up on my additional reading suggestion in my previous post. Even if Greenplum does the correct math, you have no data type in Excel which can show the correct values. They data might differ slightly.

Your fundamental assumption is that you believe Excel is always correct. Yet you have to prove that the calculations you do in Excel are more precise than the math in Greenplum.

Another additional reading:
https://support.microsoft.com/en-us/help/78113/floating-point-arithmetic-may-give-inaccurate-results-in-excel
https://blogs.office.com/2008/04/10/understanding-floating-point-precision-aka-why-does-excel-give-me-seemingly-wrong-answers/

**Comment by gloCalHelp** [comment]
@andreasscherbaum  and other repliers, thank you all very much for your taking time to guiding me. 

I don't think Excel can always do well computing especially when big data is bigger than 1 million records, that is why our tests at the beginning only choose about 1 million  records but not too bigger,  

And I am not so good at Excel as your knowing data types in Excel, but as my post screencopy shows, you can find that I have made Excel to allow over 10 decimal digits to clear the possibly rounding problem.

And from this issue founding, you can find that I am loving technique and I am an attentive specialist which is one of the most important characteristic  for a specialist or a researcher. I have several other popular big data systems' designing and optimizing experience. 
I wish I could continue with joining you to work as a big data architecture or else big data analysis position, and to prove that I am  a thankful person, I will share a little of my monthly incomes to you for your successful recommendation. my mail address is jiaxinlin@live.com .
