### ISSUE TITLE
Assertion failure from resource queues

### ISSUE THREAD

**Issue by hlinnaka** [greenplum-db/gpdb#1758]
I tried to run "wrkloadadmin" regression test from bugbuster concurrently with the "resource_queue" regression test from the main suite.

I used this schedule file (wrkloadadmin depends on the "tenk1" table, created and populated by create_table and copy tests):
```
test: create_table
test: copy
test: resource_queue wrkloadadmin
```

I got:
```
  CREATE RESOURCE QUEUE mgmtuser2 ACTIVE THRESHOLD 7;
  CREATE RESOURCE QUEUE mgmtuser3 ACTIVE THRESHOLD 9;
  CREATE RESOURCE QUEUE mgmtuser4 ACTIVE THRESHOLD 8;
! FATAL:  Unexpected internal error (resqueue.c:2040)
! DETAIL:  AssertImply failed("!(!(gp_resqueue_memory_policy != RESQUEUE_MEMORY_POLICY_NONE) || (v1 == v2 && "Resource queue / shared structure do not match on memory limit in policy AUTO."))", File: "resqueue.c", Line: 2040)
! HINT:  Process 3569 will wait for gp_debug_linger=120 seconds before termination.
! Note that its locks and other resources will not be released until then.
! server closed the connection unexpectedly
!       This probably means the server terminated abnormally
!       before or while processing the request.
! connection to server was lost

```

**Comment by xiong-gang** [comment]
Added a story in MPP backlog

**Comment by xiong-gang** [comment]
This can be simply repro as follow:

Session 1:
create resource queue rq1 with (active_statements=2, memory_limit='1024MB');
begin;
alter resource queue rq1 with (memory_limit='2GB');


Session 2:
create resource queue rq2 with (active_statements=2, memory_limit='1024MB');


The update in session 1 is invisible to session 2, so when session 2 call function AssertMemoryLimitsMatch, it finds the `memory limit` in shared memory (ResQueueHash) is 2GB, but the value in catalog is still 1024MB.

I think we should disable the validation in function AssertMemoryLimitsMatch. How do you think? @hlinnaka

**Comment by xiong-gang** [comment]
Merged, https://github.com/greenplum-db/gpdb/pull/1925
