### ISSUE TITLE
Does "content" in the table gp_segment_configuration for every segment equal the "gp_segment_id"?  

### ISSUE THREAD

**Issue by 21090310** [greenplum-db/gpdb#1775]
I think it equals the gp_segment_id, but i am not sure. I tested it with query 1 :
```
select gp_segment_id,count(*) from test group by gp_segment_id;
```
The result:
```
 gp_segment_id | count
---------------+-------
             2 | 66681
             1 | 66712
             0 | 66618
```
I login each segment, and query 2: 
```
select count(*) from test;
```
When the gp_segment_id equals the content of segment, the count in the result of query 2 is the same as query 1's.
So i think content equals gp_segment_id, is it true?

**Comment by ashwinstar** [comment]
Yes that correct @21090310 .

**Comment by 21090310** [comment]
Thank U.
