### ISSUE TITLE
View's definition in pg_views is incorrect when it's SELECT SQL contains filter condition

### ISSUE THREAD

**Issue by water32** [greenplum-db/gpdb#1854]
Create a view like:

create or replace view test_view_filter
as select
count( * ) filter(where relkind='r') r,
count( * ) a
from pg_class;

After create, query the pg_views as:

select * from pg_views where viewname = 'test_view_filter';

The definition column value not contain any "filter" word.
When I query the view as:

select * from test_view_filter;

I can get the right result, but when I try use the definition in the pg_views to recreate it.
The result change to wrong.

When I use count(1) replace count( * ), It can works, although the FILTER be replaced with CASE WHEN
I reappear this BUG in version 4371,4372 on RHEL and 4372 on SuSE

**Comment by hlinnaka** [comment]
Fixed, thanks for the report! With the fix, it will still come out as the CASE-WHEN construct, but at least it will produce the same query results.
