### ISSUE TITLE
Non-tech: licence and stable releases

### ISSUE THREAD

**Issue by salahaldin** [greenplum-db/gpdb#189]
Hello Guys, I was playing with greenplum and I have seen that git repository is getting updated on hourly basis which is amazing. I have encountered some bugs which are already reported due to the merge of upstream patches. 
To overcome this issue I have used the binaries provided from pivotal, but the licence there is not apache2. 
So my question to the community:
Where I can find stable releases?
To pivotal:
I know that some parts of greenplum still commercial such as command centre, but what about the database server binaries such as  greenplum-db-4.3.6.2-build-1-RHEL5-x86_64 and so on

**Comment by ivannovick** [comment]
Hello,

The source code for 4.3 Greenplum is not open source, but the latest code
in GitHub is the same as that plus many new commits.  As a community we
need to get ready for our first open source release version based on the
latest code in GitHub, and this is a work in progress.

Cheers,
Ivan

**Comment by ashwinstar** [comment]
Closing was answered.
