### ISSUE TITLE
High VMEM Usage on a stored procedure

### ISSUE THREAD

**Issue by kelvien** [greenplum-db/gpdb#1934]
Is the 'High VMEM usage' error expected on a stored procedure that has multiple intensive queries in it ?
I was able to get through the queries without the error when I run them manually outside of the stored procedure. I am talking about moving around 2 billion rows of data.
My stored procedure sample code is a series of CTAS, INSERTs, and DELETE : 
`CREATE OR REPLACE FUNCTION crunchData() RETURNS VOID AS $$
BEGIN
    EXECUTE 'CREATE TEMP TABLE AS ...';
    EXECUTE 'INSERT INTO ...';
    EXECUTE 'CREATE TEMP TABLE AS ...';
    EXECUTE 'INSERT INTO ...';
    EXECUTE 'DELETE FROM ...';
    EXECUTE 'INSERT INTO ...';
END $$ language plpgsql;`
Is this caused by data that is in a transaction being stored in the GPDB memory ?

**Comment by sushi30** [comment]
Did you find a solution? Why was the issue closed?

**Comment by kelvien** [comment]
IIRC, there was a fundamental table structure that we changed to optimize the queries within the store procedure. This error tell you the limit you have with your current DB spec and the amount of data you are dealing with, so we need to try optimizing our way up through our queries/table structures.
