### ISSUE TITLE
Some questions about test/regress/sql/arrays.sql

### ISSUE THREAD

**Issue by 21090310** [greenplum-db/gpdb#1943]
When I compare the arrays.sql file in Greenplum 4.3.99 with arrays.sql file in PostgreSQL 9.4, I confuse the sql as follows：
```
-- select 33 = any ('{1,null,3}');  -- MPP: 11852
```

I try the sql in Greenplum 4.3.99  and PostgreSQL 9.4, it return the same result:
```
postgres=# select 33 = any ('{1,null,3}');
 ?column?
----------

(1 row)
```
What is the meaning ？ Why the sql is commented out ？

**Comment by hlinnaka** [comment]
MPP-11852 refers to a ticket in greenplum's bug tracker, before it was open sourced. Here's the text from the ticket:

> The following queries should produce equivalent results:
> 
> select 33 = any ('{1,null,3}');
> 
> select 33 = any (select 1 union all select null union all select 3);
> 
> The first query incorrectly returns false, the second correctly returns null.
>
> Works in Postgres, broken in gp.

A developer commented: 
> This seems to be a bug in the fast-path expression evaluation.

It was unceremoniously fixed shortly after it was reported. Before it was fixed, you got this result:

```
GreenplumDB=# select 33 = any ('{1,null,3}');
?column?
----------
f
(1 row)
```

I'm not sure why the test left commented-out then. Probably an oversight. We should re-enable it.

**Comment by 21090310** [comment]
Awesome, I get what I want. Thank you very much !

**Comment by hlinnaka** [comment]
Oh, it was re-enabled a long time ago already, by commit e81df1d2e22a17fe6fc108969e3d19d7b361c5a8. So we're all good.

**Comment by hlinnaka** [comment]
The old bug tickets are not available to the public, unfortunately. We couldn't publish them, because they contain customer details etc. But we're happy to extract information from them as needed, so if there's a particular one you're interested in, just send an email to gpdb-dev and someone can pull it up.
