### ISSUE TITLE
Gpperfmon Install

### ISSUE THREAD

**Issue by VinnyPembe** [greenplum-db/gpdb#1987]
Hello,

This isn't an 'issue' as such, I'm just not entirely sure where else to post so I apologise! Basically, I'm trying to test if Gpperfmon can be installed or not with the open source version of GPDB. I understand that the GPCC web-interface utilities are non-compatible, but I only require gpperfmon itself anyway. How do I go about installing this?

I've just installed a fresh version of GPDB, but the command 'gpperfmon_install' is not found. Plus, I can't seem to find any other reference of it inside my install files. I've searched around on the web but not found anything thus far. Cheers in advance for any help :)

**Comment by VinnyPembe** [comment]
Ps, this is the command I used to install the GPDB software, just in case I missed of a required package -

./configure --prefix=/usr/local/gpdb --with-openssl --with-libxml --with-libxslt --with-python --with-perl --with-includes=/usr/local/gpdb/include --with-libs=/usr/local/gpdb/lib --enable-orca

**Comment by skahler-pivotal** [comment]
the management and monitoring group is about to embark upon a track of work to validate gpperfmon on 5.0. we haven't started on it yet, but will in the near future. At this point in time I don't believe it will build

**Comment by Chibin** [comment]
This is getting addressed with the following PR:
https://github.com/greenplum-db/gpdb/pull/2154

**Comment by skahler-pivotal** [comment]
@VinnyPembe is this something we can close at this point?

**Comment by VinnyPembe** [comment]
Yep, this is fine to close. Cheers very much!
