### ISSUE TITLE
run gpcheckperf: gpnetbenchServer is not found

### ISSUE THREAD

**Issue by huxuanlai** [greenplum-db/gpdb#199]
The same issue is reported and fixed in https://issues.apache.org/jira/browse/HAWQ-63, but not fixed in gpdb.

**Comment by jimmyyih** [comment]
Hello,

Have you tried building gpnetbenchServer and gpnetbenchClient in this directory: gpAux/platform/

**Comment by skahler-pivotal** [comment]
We found it and put it back :)
