### ISSUE TITLE
Running gp_dump with the special database names that contain backslash return error ?

### ISSUE THREAD

**Issue by 21090310** [greenplum-db/gpdb#1997]
When I run gp_dump with database name contains backslash like this : 
```
gp_dump -p 15432 -U xxx --gp-d=xxxx --gp-r=xxxx --gp-s=p --gp-k=20170308140624 --no-lock --gp-c --no-expand-children "abcdefg()\\4"
```
Unfortunately,  it return error as follows：
```
20170309:10:48:55|gp_dump-[ERROR]:-connection to database "abcdefg()4" failed : FATAL:  database "abcdefg()4" does not exist
```
I try with "abcdefg()\4" and "abcdefg()\\\4" and "abcdefg()\\\\4", it return same error. 

Is it a bug ?

**Comment by jmcatamney** [comment]
If you want to use gp_dump to backup a database with backslashes in the name, you can do so by using single quotes for the database name (`gp_dump 'abcdefg()\\4'`) or escaping each backslash and using double quotes (`gp_dump "abcdefg()\\\\4"`), as the shell will resolve a double-backslash into a single backslash before passing it to gp_dump unless the database name is single-quoted.

However, in general, the gpcrondump utility is the one you should use to perform a backup; gp_dump is only intended to be called by gpcrondump, and using gp_dump directly on the command line is unsupported.  You can perform an equivalent dump to the gp_dump command line you've provided by setting the PGUSER and PGPORT environment variables to the appropriate values and running `gpcrondump -x 'abcdefg()\\4'`.

**Comment by 21090310** [comment]
Unfortunately, I run <code>gp_dump 'abcdefg()\\4'</code> and <code>gp_dump "abcdefg()\\\\4"</code>, it return same error. And I use <code>gpcrondump -x 'abcdefg()\\4'</code>, the error is as follow:
```
20170327:17:23:46:008120 gpcrondump:xxxx-[DEBUG]:-Checking if MASTER_DATA_DIRECTORY env variable is set.
20170327:17:23:46:008120 gpcrondump:xxxx-[DEBUG]:-Obtaining master's port from master data directory
20170327:17:23:46:008120 gpcrondump:xxxx-[DEBUG]:-Starting GpCronDump
20170327:17:23:46:008120 gpcrondump:xxxx-[INFO]:-gp_dump running...
20170327:17:23:46:008120 gpcrondump:xxxx-[DEBUG]:-Starting ValidateDatabaseExists
20170327:17:23:46:008120 gpcrondump:xxxx-[DEBUG]:-Connecting to dbname='template1'
20170327:17:23:46:008120 gpcrondump:xxxx-[DEBUG]:-Ending ValidateDatabaseExists
20170327:17:23:46:008120 gpcrondump:xxxx-[DEBUG]:-Ending GpCronDump
20170327:17:23:46:008120 gpcrondump:xxxx-[ERROR]:-gpcrondump error: Database abcdefg()\\4 does not exist.
```
The file ./tmp_basedir_for_gpdb_bld/lib/python/gppylib/db/dbconn.py will retrun error when database name contain double backslashes.

**Comment by oakbarrett** [comment]
issue noted, and will be addressed in the rewrite of gpbackup & gprestore as discussed here: 

https://groups.google.com/a/greenplum.org/forum/#!topic/gpdb-dev/LO-rNwRyL9w
