### ISSUE TITLE
Fatal error with --enable-orca option

### ISSUE THREAD

**Issue by phoccer** [greenplum-db/gpdb#20]
When I try to compile with the --enable-orca option I receive the following error:

In file included from CConfigParamMapping.cpp:19:0:
../../.././src/include/gpopt/config/CConfigParamMapping.h:18:23: fatal error: gpos/base.h: No such file or directory
#include "gpos/base.h"

A find of the gpdb source directory shows doesn't return a gpos directory.

**Comment by edespino** [comment]
At the current time the new Pivotal query optimizer (orca) is not available in the open source.  Rest assured, it will be in the not too distant future.  We use this flag for our internal builds where it is currently available.  Subscribe to the announcements list to ensure you receive notification of it's Open Source availability.

Regards,
-=ed espino

**Comment by edespino** [comment]
On second thought, I am reopening this issue.  If the "--enable-orca" flag is used, "configure" should fail if appropriate header files and libraries are not found on the system.  A build check should be added.  Thanks for raising this issue Tim.

**Comment by edespino** [comment]
I am validating a fix to configure that will check for Greenplum Query Optimizer header files:

```
# Check for Greenplum Query Optimizer (orca) and supporting Greenplum OS header files.
if test "$enable_orca" = yes ; then
  AC_CHECK_HEADERS(gpopt/init.h, [], [AC_MSG_ERROR([gpopt/init.h GPOPT header file is required for Greenplum Query Optimizer (orca)])])
fi

if test "$enable_orca" = yes ; then
  AC_CHECK_HEADERS(gpos/assert.h, [], [AC_MSG_ERROR([gpos/assert.h GPOS header file is required for Greenplum Query Optimizer (orca)])])
fi
```

**Comment by edespino** [comment]
We are now checking for Greenplum Query Optimizer and GPOS header files during configure if --enable-orca is used.

**Comment by hlinnaka** [comment]
That patch was reverted, so re-open the issue

**Comment by edespino** [comment]
Merged updated approach into master.  Also update Pivotal Makefiles to allow configure to locate gpopt and gpos header files.

**Comment by ypopkov** [comment]
When I try to start the demo cluster I get the messages below - does it mean no query optimizer is available in the absence of Orca?

```
 optimizer 
-----------
 off
(1 row)

            gp_opt_version             
---------------------------------------
 Server has been compiled without ORCA
(1 row)
```
