### ISSUE TITLE
ERROR 42501 argument to pg_get_expr() must come from system catalogs parse_func.c

### ISSUE THREAD

**Issue by jonasbu11** [greenplum-db/gpdb#2000]
This behavior has been observed in postgresql 8.3.23 and 9.0b3 (link below) where a user (not superuser) attempts to pass valid columns from system catalogs referenced by join alias.  AFAIK is has been fixed in more recent versions of postgresql.

Current build of GPDB.

Example of failing query:
select pa.oid,
       pr.parchildrelid,             
       pg_get_expr(parlistvalues, parchildrelid )as ListValues, 
       pr.oid,                 
       pr.parparentrule
  from  pg_catalog.pg_partition_rule pr
  join  pg_catalog.pg_partition pa on pr.paroid = pa.oid

https://www.postgresql.org/message-id/flat/AANLkTilrQ6AZDWXfFTKTnusncqekVlbXP_6IqGEXRLiE%40mail.gmail.com#AANLkTilrQ6AZDWXfFTKTnusncqekVlbXP_6IqGEXRLiE@mail.gmail.com

**Comment by jonasbu11** [comment]
To clarify why this matters:  Several user tools (Aginity, pgadminIII, e.g.) use this when generating table info.

**Comment by hlinnaka** [comment]
We have the full fix in GPDB, too, but the check contains a list of allowed system catalogs, and the GPDB-specific pg_partition_rule table isn't listed. Thanks for the report, I'll go fix that!

**Comment by hlinnaka** [comment]
This has now been fixed. Thanks!
