### ISSUE TITLE
Explain error because of subplan double parallelized

### ISSUE THREAD

**Issue by hsyuan** [greenplum-db/gpdb#2002]
Repro:

```sql
create table t(a int, b int, c int);
explain select * from t T1 where b = (select max(b) from t T2 where T2.a = T1.a group by c) and b < 10;

FATAL:  Unexpected internal error (cdbllize.c:1152)
DETAIL:  FailedAssertion("!(flow->req_move == MOVEMENT_NONE)", File: "cdbllize.c", Line: 1152)
HINT:  Process 71055 will wait for gp_debug_linger=120 seconds before termination.
Note that its locks and other resources will not be released until then.
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
The connection to the server was lost. Attempting reset: Succeeded.
```

Planner generated equivalent classes predicate `b = Subplan and b < 10 and Subplan < 10` for above query. The 2 Subplans are shallow copies that have plan_id pointing to the same plan inside of PlannerInfo initplans. After the 1st subplan is parallelized, it marks `is_parallelized` as true, but for the 2nd subplan, the `is_parallelized` is still false, so planner tries to parallelize the same plan node that is already parallelized, hence error. It seems like moving the attribute `is_parallelized` from `Subplan` to `Plan` pointed by the subplan doesn't work either.

**Comment by hlinnaka** [comment]
We should process the InitPlans in a separate step, probably before processing the main plan. We stopped processing subplans recursively like that in the rest of the system, in commit eab6b8b27e that we got with the PostgreSQL 8.3 merge. But we never got around to refactor cdbparallelize to do the same.

**Comment by bhuvnesh2703** [comment]
Here is a PR for the fix: https://github.com/greenplum-db/gpdb/pull/2443/files, pls review

**Comment by hlinnaka** [comment]
This was fixed by PR 2443, closing.
