### ISSUE TITLE
Multi segments per node per disk vs one segment per node on RAID10

### ISSUE THREAD

**Issue by amosbird** [greenplum-db/gpdb#2007]
What choice should I make to deploy gpdb? Based on `postgres` I think raid10 is better compared to multi tablespaces. I'm not sure if this is true for gpdb.

**Comment by sonicmvb** [comment]
raid 5 is better in perf/price

**Comment by skahler-pivotal** [comment]
I believe the two methods you are talking about here would be to 1) give each segment it's own set of disk 2) run all segments on a shared set of disk.

Ideally everything running in the cluster stays parallel so therefore each having it's own individual disk setup would be the most parallel. While this is an aim there are queries out there that tend to cause the system to skew so one node has to do more work, often when working with uniqueness or data where there is an abundance of one value. In the case of having multiple segments on a larger disk array you are able to still leverage the throughput of the array for these processes that aren't even across the system. You don't end up throttled by a single disk trying to handle that situation while other may be idle in the system having already completed their smaller piece.

**Comment by amosbird** [comment]
@skahler-pivotal Thanks for the help. Do you mean that gpdb will still use multiple segments on one node to do parallel query execution?

**Comment by skahler-pivotal** [comment]
Yes, gpdb will use a hashing algo on the data which ideally ends up with the data spread evenly across all of the segments. When a query is run every segment will participate in the query on it's piece, potentially passing tuples around to other nodes or aggregating them as needed by the query plan. So the query is executed in parallel across all of the nodes.

**Comment by hsyuan** [comment]
Close this issue, since it has been answered.
