### ISSUE TITLE
psql hang while gpdb state is ok

### ISSUE THREAD

**Issue by sonicmvb** [greenplum-db/gpdb#2048]
envrionment
gpdb version 4.1.2.4
master     OS centos 6.8
node        OS centos 5.4 ,centos 5,8 ,centos 6,8  mixed

after gprecoverseg  operation,  use psql connect to database  with 3-5 seconds delay (abnormal)
can not query any tables  while gpstate -s returns no errors

logs in pg_logs shows nothing happens ,just hang

issues means 4.1 bugs or something else goes wrong ?

**Comment by ivannovick** [comment]
4.1.2.4 is way too old.  Can you refile this with a recent version of Greenplum based on open source?
