### ISSUE TITLE
Greenplum initsystem failed

### ISSUE THREAD

**Issue by zhangguohan** [greenplum-db/gpdb#2067]
HI,

  When I run gpinitsystem -c /home/gpadmin/gpconfigs/gpinitsystem_config ，failed ? 

gpstop failed. (Reason='Unrecognised Greenplum Version 'PostgreSQL 8.3.23 (Greenplum Database build dev) on x86_64-pc-linux-gnu, compiled by GCC gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11) compiled on Mar 19 2017 01:05:37'') exiting

OS:CentOS Linux release 7.3.1611
GCC:gcc-4.8.5
PYthon:python-2.7.5
Greenplum:5.0.0.alpha.0
----------------------------------log----------------------------------------------------------------------

[gpadmin@mdw ~]$ gpinitsystem -c /home/gpadmin/gpconfigs/gpinitsystem_config 
20170319:02:48:30:033711 gpinitsystem:mdw:gpadmin-[INFO]:-Checking configuration parameters, please wait...
20170319:02:48:30:033711 gpinitsystem:mdw:gpadmin-[INFO]:-Reading Greenplum configuration file /home/gpadmin/gpconfigs/gpinitsystem_config
20170319:02:48:30:033711 gpinitsystem:mdw:gpadmin-[INFO]:-Locale has not been set in /home/gpadmin/gpconfigs/gpinitsystem_config, will set to default value
20170319:02:48:30:033711 gpinitsystem:mdw:gpadmin-[INFO]:-Locale set to en_US.utf8
20170319:02:48:30:033711 gpinitsystem:mdw:gpadmin-[INFO]:-MASTER_MAX_CONNECT not set, will set to default value 250
20170319:02:48:30:033711 gpinitsystem:mdw:gpadmin-[INFO]:-Checking configuration parameters, Completed
20170319:02:48:30:033711 gpinitsystem:mdw:gpadmin-[INFO]:-Commencing multi-home checks, please wait...
..
20170319:02:48:31:033711 gpinitsystem:mdw:gpadmin-[INFO]:-Configuring build for standard array
20170319:02:48:31:033711 gpinitsystem:mdw:gpadmin-[INFO]:-Commencing multi-home checks, Completed
20170319:02:48:31:033711 gpinitsystem:mdw:gpadmin-[INFO]:-Building primary segment instance array, please wait...
..
20170319:02:48:31:033711 gpinitsystem:mdw:gpadmin-[INFO]:-Checking Master host
20170319:02:48:31:033711 gpinitsystem:mdw:gpadmin-[INFO]:-Checking new segment hosts, please wait...
..
20170319:02:48:33:033711 gpinitsystem:mdw:gpadmin-[INFO]:-Checking new segment hosts, Completed
20170319:02:48:34:033711 gpinitsystem:mdw:gpadmin-[INFO]:-Greenplum Database Creation Parameters
20170319:02:48:34:033711 gpinitsystem:mdw:gpadmin-[INFO]:---------------------------------------
20170319:02:48:34:033711 gpinitsystem:mdw:gpadmin-[INFO]:-Master Configuration
20170319:02:48:34:033711 gpinitsystem:mdw:gpadmin-[INFO]:---------------------------------------
20170319:02:48:34:033711 gpinitsystem:mdw:gpadmin-[INFO]:-Master instance name       = EMC Greenplum DW
20170319:02:48:34:033711 gpinitsystem:mdw:gpadmin-[INFO]:-Master hostname            = mdw
20170319:02:48:34:033711 gpinitsystem:mdw:gpadmin-[INFO]:-Master port                = 5432
20170319:02:48:34:033711 gpinitsystem:mdw:gpadmin-[INFO]:-Master instance dir        = /gpmaster/gpseg-1
20170319:02:48:34:033711 gpinitsystem:mdw:gpadmin-[INFO]:-Master LOCALE              = en_US.utf8
20170319:02:48:34:033711 gpinitsystem:mdw:gpadmin-[INFO]:-Greenplum segment prefix   = gpseg
20170319:02:48:34:033711 gpinitsystem:mdw:gpadmin-[INFO]:-Master Database            = tank
20170319:02:48:34:033711 gpinitsystem:mdw:gpadmin-[INFO]:-Master connections         = 250
20170319:02:48:34:033711 gpinitsystem:mdw:gpadmin-[INFO]:-Master buffers             = 128000kB
20170319:02:48:34:033711 gpinitsystem:mdw:gpadmin-[INFO]:-Segment connections        = 750
20170319:02:48:34:033711 gpinitsystem:mdw:gpadmin-[INFO]:-Segment buffers            = 128000kB
20170319:02:48:34:033711 gpinitsystem:mdw:gpadmin-[INFO]:-Checkpoint segments        = 8
20170319:02:48:34:033711 gpinitsystem:mdw:gpadmin-[INFO]:-Encoding                   = UNICODE
20170319:02:48:34:033711 gpinitsystem:mdw:gpadmin-[INFO]:-Postgres param file        = Off
20170319:02:48:34:033711 gpinitsystem:mdw:gpadmin-[INFO]:-Initdb to be used          = /usr/local/gpdb-5.0.0/bin/initdb
20170319:02:48:34:033711 gpinitsystem:mdw:gpadmin-[INFO]:-GP_LIBRARY_PATH is         = /usr/local/gpdb-5.0.0/lib
20170319:02:48:34:033711 gpinitsystem:mdw:gpadmin-[INFO]:-Ulimit check               = Passed
20170319:02:48:34:033711 gpinitsystem:mdw:gpadmin-[INFO]:-Array host connect type    = Single hostname per node
20170319:02:48:34:033711 gpinitsystem:mdw:gpadmin-[INFO]:-Master IP address [1]      = ::1
20170319:02:48:34:033711 gpinitsystem:mdw:gpadmin-[INFO]:-Master IP address [2]      = 10.218.94.67
20170319:02:48:34:033711 gpinitsystem:mdw:gpadmin-[INFO]:-Master IP address [3]      = fe80::217:faff:fe00:9370
20170319:02:48:34:033711 gpinitsystem:mdw:gpadmin-[INFO]:-Standby Master             = Not Configured
20170319:02:48:34:033711 gpinitsystem:mdw:gpadmin-[INFO]:-Primary segment #          = 1
20170319:02:48:34:033711 gpinitsystem:mdw:gpadmin-[INFO]:-Total Database segments    = 2
20170319:02:48:34:033711 gpinitsystem:mdw:gpadmin-[INFO]:-Trusted shell              = ssh
20170319:02:48:34:033711 gpinitsystem:mdw:gpadmin-[INFO]:-Number segment hosts       = 2
20170319:02:48:34:033711 gpinitsystem:mdw:gpadmin-[INFO]:-Mirroring config           = OFF
20170319:02:48:34:033711 gpinitsystem:mdw:gpadmin-[INFO]:----------------------------------------
20170319:02:48:34:033711 gpinitsystem:mdw:gpadmin-[INFO]:-Greenplum Primary Segment Configuration
20170319:02:48:34:033711 gpinitsystem:mdw:gpadmin-[INFO]:----------------------------------------
20170319:02:48:34:033711 gpinitsystem:mdw:gpadmin-[INFO]:-sdw01 	/gpdata/gpseg0 	40000 	2 	0
20170319:02:48:34:033711 gpinitsystem:mdw:gpadmin-[INFO]:-sdw02 	/gpdata/gpseg1 	40000 	3 	1

Continue with Greenplum creation Yy|Nn (default=N):
> y
20170319:02:48:37:033711 gpinitsystem:mdw:gpadmin-[INFO]:-Building the Master instance database, please wait...
20170319:02:48:42:033711 gpinitsystem:mdw:gpadmin-[INFO]:-Starting the Master in admin mode
20170319:02:48:48:033711 gpinitsystem:mdw:gpadmin-[INFO]:-Commencing parallel build of primary segment instances
20170319:02:48:48:033711 gpinitsystem:mdw:gpadmin-[INFO]:-Spawning parallel processes    batch [1], please wait...
..
20170319:02:48:48:033711 gpinitsystem:mdw:gpadmin-[INFO]:-Waiting for parallel processes batch [1], please wait...
..............
20170319:02:49:03:033711 gpinitsystem:mdw:gpadmin-[INFO]:------------------------------------------------
20170319:02:49:03:033711 gpinitsystem:mdw:gpadmin-[INFO]:-Parallel process exit status
20170319:02:49:03:033711 gpinitsystem:mdw:gpadmin-[INFO]:------------------------------------------------
20170319:02:49:03:033711 gpinitsystem:mdw:gpadmin-[INFO]:-Total processes marked as completed           = 2
20170319:02:49:03:033711 gpinitsystem:mdw:gpadmin-[INFO]:-Total processes marked as killed              = 0
20170319:02:49:03:033711 gpinitsystem:mdw:gpadmin-[INFO]:-Total processes marked as failed              = 0
20170319:02:49:03:033711 gpinitsystem:mdw:gpadmin-[INFO]:------------------------------------------------
20170319:02:49:03:033711 gpinitsystem:mdw:gpadmin-[INFO]:-Deleting distributed backout files
20170319:02:49:03:033711 gpinitsystem:mdw:gpadmin-[INFO]:-Removing back out file
20170319:02:49:03:033711 gpinitsystem:mdw:gpadmin-[INFO]:-No errors generated from parallel processes
20170319:02:49:03:033711 gpinitsystem:mdw:gpadmin-[INFO]:-Restarting the Greenplum instance in production mode
20170319:02:49:04:044138 gpstop:mdw:gpadmin-[INFO]:-Starting gpstop with args: -a -l /home/gpadmin/gpAdminLogs -i -m -d /gpmaster/gpseg-1
20170319:02:49:04:044138 gpstop:mdw:gpadmin-[INFO]:-Gathering information and validating the environment...
20170319:02:49:04:044138 gpstop:mdw:gpadmin-[INFO]:-Obtaining Greenplum Master catalog information
20170319:02:49:04:044138 gpstop:mdw:gpadmin-[INFO]:-Obtaining Segment details from master...
20170319:02:49:04:044138 gpstop:mdw:gpadmin-[CRITICAL]:-gpstop failed. (Reason='Unrecognised Greenplum Version 'PostgreSQL 8.3.23 (Greenplum Database  build dev) on x86_64-pc-linux-gnu, compiled by GCC gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11) compiled on Mar 19 2017 01:05:37'') exiting...
20170319:02:49:04:gpinitsystem:mdw:gpadmin-[FATAL]:-Failed to stop new Greenplum instance, check log file Script Exiting!

**Comment by zhangguohan** [comment]
****#

**Comment by zhngling** [comment]
git clone https://github.com/greenplum-db/gpdb.git 
not use the zip

**Comment by zhangguohan** [comment]
renew use git clone https://github.com/greenplum-db/gpdb.git  is OK! Thanks  @zhngling

**Comment by Chibin** [comment]
@tom-meyer @dsharp-pivotal For visibility.
