### ISSUE TITLE
Greenplum Database 5.0.0 quicklz compression not supported ?

### ISSUE THREAD

**Issue by zhangguohan** [greenplum-db/gpdb#2070]
Hi  everyone

when I`m user compression Table Storage Model test, tips  ERROR:  quicklz compression not supported (quicklz_compression.c:26)

Greenplum compile parameter : ./configure --with-perl --with-python --with-libxml --enable-mapreduce --prefix=/usr/local/gpdb-5.0.0

Specific operation as follows :

------------------------------------------------------------

tank=# create table foozip (like foo) with(appendonly=true,compresstype=zlib,compresslevel=1,orientation=column);
NOTICE:  Table doesn't have 'DISTRIBUTED BY' clause, defaulting to distribution columns from LIKE table
CREATE TABLE
tank=# insert into foozip select * from foo;
INSERT 0 30000

tank=# create table fooquick (like foo) with(appendonly=true,compresstype=quicklz,compresslevel=1,orientation=column);
NOTICE:  Table doesn't have 'DISTRIBUTED BY' clause, defaulting to distribution columns from LIKE table
CREATE TABLE
tank=# insert into fooquick select * from foo;
ERROR:  quicklz compression not supported (quicklz_compression.c:26)  (seg0 10.218.62.42:40000 pid=17522)
tank=# select version();
 PostgreSQL 8.3.23 (Greenplum Database 5.0.0-alpha.0+dev.212.gb533bcb build dev)

**Comment by hlinnaka** [comment]
Quicklz compression is not supported in the open source GPDB 5 version, unfortunately. It could not be open sourced with the rest of the codebase, because of licensing issues.

What is the Table Storage Model test?

**Comment by zhangguohan** [comment]
OOO, Thank you! @hlinnaka
