### ISSUE TITLE
compilation error: gppc.c:56:45: error: expected declaration specifiers or ‘...’ before ‘(’ token

### ISSUE THREAD

**Issue by marcin-github** [greenplum-db/gpdb#2071]
Hi!
I'm new here, I would like to try greenplum-db. When I compile gpdb I'm getting compilation error. I suspect that it is because I've got installed postgres-9.5 on the box.

`./configure --prefix=/usr --build=x86_64-pc-linux-gnu --host=x86_64-pc-linux-gnu --mandir=/usr/share/man --infodir=/usr/share/info --datadir=/usr/share --sysconfdir=/etc --localstatedir=/var/lib --docdir=/usr/share/doc/gpdb-9999 --htmldir=/usr/share/doc/gpdb-9999/html --libdir=/usr/lib64 --disable-snmp --without-python --without-pam`

[...]
`x86_64-pc-linux-gnu-gcc -O2 -pipe -march=corei7 -mtune=native    -fno-unwind-tables -fno-asynchronous-unwind-tables -fuse-linker-plugin -s    -ftracer    -fuse-ld=gold -fvar-tracking-assignments -std=gnu99
-Wall -Wmissing-prototypes -Wpointer-arith -Wendif-labels -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fno-aggressive-loop-optimizations -Wno-unused-but-set-variable -Wno-addre
ss  -fpic -I/usr/include/postgresql/server -I/usr/include/postgresql/internal -I../../../src/include -D_GNU_SOURCE  -DSO_MAJOR_VERSION=1  -c -o gppc.o gppc.c
gppc.c:56:45: error: expected declaration specifiers or ‘...’ before ‘(’ token
  ErrorContextCallback  errcontext;
                                             ^
gppc.c:66:29: error: ‘BOOLOID’ undeclared here (not in a function)
 const GppcOid GppcOidBool = BOOLOID;
                             ^
gppc.c:67:29: error: ‘CHAROID’ undeclared here (not in a function)
 const GppcOid GppcOidChar = CHAROID;
                             ^
gppc.c:68:29: error: ‘INT2OID’ undeclared here (not in a function)
 const GppcOid GppcOidInt2 = INT2OID;
                             ^
gppc.c:69:29: error: ‘INT4OID’ undeclared here (not in a function)
 const GppcOid GppcOidInt4 = INT4OID;
                             ^
gppc.c:70:29: error: ‘INT8OID’ undeclared here (not in a function)
 const GppcOid GppcOidInt8 = INT8OID;
                             ^
gppc.c:71:31: error: ‘FLOAT4OID’ undeclared here (not in a function)
 const GppcOid GppcOidFloat4 = FLOAT4OID;
                               ^
gppc.c:72:31: error: ‘FLOAT8OID’ undeclared here (not in a function)
 const GppcOid GppcOidFloat8 = FLOAT8OID;
                               ^
gppc.c:73:29: error: ‘TEXTOID’ undeclared here (not in a function)
 const GppcOid GppcOidText = TEXTOID;
                             ^
gppc.c:74:32: error: ‘VARCHAROID’ undeclared here (not in a function)
 const GppcOid GppcOidVarChar = VARCHAROID;
                                ^
gppc.c:75:31: error: ‘BPCHAROID’ undeclared here (not in a function)
 const GppcOid GppcOidBpChar = BPCHAROID;
                               ^
gppc.c:76:30: error: ‘BYTEAOID’ undeclared here (not in a function)
 const GppcOid GppcOidBytea = BYTEAOID;
                              ^
gppc.c:77:32: error: ‘NUMERICOID’ undeclared here (not in a function)
 const GppcOid GppcOidNumeric = NUMERICOID;
                                ^
gppc.c:78:29: error: ‘DATEOID’ undeclared here (not in a function)
 const GppcOid GppcOidDate = DATEOID;
                             ^
gppc.c:79:29: error: ‘TIMEOID’ undeclared here (not in a function)
 const GppcOid GppcOidTime = TIMEOID;
                             ^
gppc.c:80:31: error: ‘TIMETZOID’ undeclared here (not in a function)
 const GppcOid GppcOidTimeTz = TIMETZOID;
                               ^
gppc.c:81:34: error: ‘TIMESTAMPOID’ undeclared here (not in a function)
 const GppcOid GppcOidTimestamp = TIMESTAMPOID;
                                  ^
gppc.c:82:36: error: ‘TIMESTAMPTZOID’ undeclared here (not in a function)
 const GppcOid GppcOidTimestampTz = TIMESTAMPTZOID;
gppc.c:83:33: error: ‘ANYTABLEOID’ undeclared here (not in a function)
 const GppcOid GppcOidAnyTable = ANYTABLEOID;
                                 ^
gppc.c: In function ‘GppcDatumGetAnyTable’:
gppc.c:516:2: warning: return from incompatible pointer type
  return DatumGetPointer(x);
  ^
gppc.c: In function ‘GppcDatumGetTupleDesc’:
gppc.c:525:2: warning: return from incompatible pointer type
  return DatumGetPointer(x);
  ^
gppc.c: In function ‘GppcDatumGetHeapTuple’:
gppc.c:534:2: warning: return from incompatible pointer type
  return DatumGetPointer(x);
  ^
gppc.c: In function ‘TFGetFuncExpr’:
gppc.c:1250:3: warning: implicit declaration of function ‘exprType’ [-Wimplicit-function-declaration]
   exprType(list_nth(fexpr->args, argno)) != typid)
   ^
gppc.c: In function ‘GppcTFGetArgDatum’:
gppc.c:1283:2: warning: implicit declaration of function ‘ExecEvalFunctionArgToConst’ [-Wimplicit-function-declaration]
  return ExecEvalFunctionArgToConst(fexpr, argno, isnull);
  ^
gppc.c: In function ‘GppcTFInputDesc’:
gppc.c:1295:2: error: unknown type name ‘TableValueExpr’
  TableValueExpr    *texpr;
  ^
gppc.c:1308:11: error: ‘TableValueExpr’ undeclared (first use in this function)
  texpr = (TableValueExpr *) list_nth(fexpr->args, argno);
           ^
gppc.c:1308:11: note: each undeclared identifier is reported only once for each function it appears in

gppc.c:1308:27: error: expected expression before ‘)’ token
  texpr = (TableValueExpr *) list_nth(fexpr->args, argno);
                           ^
gppc.c:1309:52: error: ‘T_TableValueExpr’ undeclared (first use in this function)
  if (!texpr || !IsA(texpr, TableValueExpr))
                                                    ^
gppc.c:1316:25: error: request for member ‘subquery’ in something not a structure or union
  qexpr = (Query *) texpr->subquery;
                         ^
gppc.c: In function ‘GppcInstallReportCallback’:
gppc.c:1376:46: error: expected declaration specifiers or ‘...’ before ‘(’ token
  ErrorContextCallback    *errcontext;
                                              ^
gppc.c:1378:53: error: lvalue required as left operand of assignment
  errcontext = error_context_stack;
                                                     ^
gppc.c:1382:57: error: request for member ‘callback’ in something not a structure or union
   if (errcontext->callback == ReportCallbackInvoker &&
                                                         ^
gppc.c:1383:5: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
    ((GppcReportCallbackState) errcontext->arg)->func == func &&
     ^
gppc.c:1383:81: error: request for member ‘arg’ in something not a structure or union
    ((GppcReportCallbackState) errcontext->arg)->func == func &&
                                                                                 ^
gppc.c:1383:5: warning: value computed is not used [-Wunused-value]
    ((GppcReportCallbackState) errcontext->arg)->func == func &&
     ^

gppc.c:1384:5: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
    ((GppcReportCallbackState) errcontext->arg)->arg == arg)
     ^
gppc.c:1384:81: error: request for member ‘arg’ in something not a structure or union
    ((GppcReportCallbackState) errcontext->arg)->arg == arg)
                                                                                 ^
gppc.c:1384:5: warning: value computed is not used [-Wunused-value]
    ((GppcReportCallbackState) errcontext->arg)->arg == arg)
     ^
gppc.c:1385:11: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
    return (GppcReportCallbackState) errcontext;
           ^
gppc.c:1385:11: warning: value computed is not used [-Wunused-value]
gppc.c:1385:4: warning: return from incompatible pointer type
    return (GppcReportCallbackState) errcontext;
    ^
gppc.c:1386:54: error: lvalue required as left operand of assignment
   errcontext = errcontext->previous;
                                                      ^
gppc.c:1386:106: error: request for member ‘previous’ in something not a structure or union
   errcontext = errcontext->previous;
                                                                                                          ^
gppc.c:1386:90: warning: left-hand operand of comma expression has no effect [-Wunused-value]
   errcontext = errcontext->previous;
                                                                                          ^
gppc.c:1393:53: error: lvalue required as left operand of assignment
  errcontext = (ErrorContextCallback *) cbstate;
                                                     ^
gppc.c:1397:52: error: request for member ‘callback’ in something not a structure or union
  errcontext->callback = ReportCallbackInvoker;
                                                    ^
gppc.c:1398:52: error: request for member ‘arg’ in something not a structure or union
  errcontext->arg = cbstate;
                                                    ^
gppc.c:1399:52: error: request for member ‘previous’ in something not a structure or union
  errcontext->previous = error_context_stack;
                                                    ^
gppc.c:1400:22: warning: assignment makes pointer from integer without a cast
  error_context_stack = errcontext;
                      ^
gppc.c:1400:58: warning: right-hand operand of comma expression has no effect [-Wunused-value]
  error_context_stack = errcontext;
                                                          ^
gppc.c: In function ‘GppcUninstallReportCallback’:
gppc.c:1415:46: error: expected declaration specifiers or ‘...’ before ‘(’ token
  ErrorContextCallback    *errcontext, *next;
                                              ^
gppc.c:1417:53: error: lvalue required as left operand of assignment
  errcontext = error_context_stack;
                                                     ^
gppc.c:1418:2: error: ‘next’ undeclared (first use in this function)
  next = NULL;
  ^
gppc.c:1421:58: warning: comparison of distinct pointer types lacks a cast
   if (errcontext == (ErrorContextCallback *) cbstate)
                                                          ^
gppc.c:1423:44: warning: left-hand operand of comma expression has no effect [-Wunused-value]
   next = errcontext;
                                            ^
gppc.c:1423:3: warning: statement with no effect [-Wunused-value]
   next = errcontext;
   ^
gppc.c:1424:54: error: lvalue required as left operand of assignment
   errcontext = errcontext->previous;
                                                      ^
gppc.c:1424:106: error: request for member ‘previous’ in something not a structure or union
   errcontext = errcontext->previous;
                                                                                                          ^
gppc.c:1424:90: warning: left-hand operand of comma expression has no effect [-Wunused-value]
   errcontext = errcontext->previous;
                                                                                          ^
gppc.c:1429:71: error: request for member ‘previous’ in something not a structure or union
    next->previous = errcontext->previous;
                                                                       ^
gppc.c:1429:55: warning: left-hand operand of comma expression has no effect [-Wunused-value]
    next->previous = errcontext->previous;
                                                       ^
gppc.c:1431:24: warning: assignment makes pointer from integer without a cast
    error_context_stack = errcontext->previous;
                        ^
gppc.c:1431:76: error: request for member ‘previous’ in something not a structure or union
    error_context_stack = errcontext->previous;
                                                                            ^
gppc.c:1433:9: warning: passing argument 1 of ‘pfree’ makes pointer from integer without a cast
   pfree(errcontext);
         ^
In file included from /usr/include/postgresql/server/postgres.h:49:0,
                 from gppc.c:10:
/usr/include/postgresql/server/utils/palloc.h:81:13: note: expected ‘void *’ but argument is of type ‘int’
 extern void pfree(void *pointer);
             ^
gppc.c:1433:3: error: too many arguments to function ‘pfree’
   pfree(errcontext);
   ^
In file included from /usr/include/postgresql/server/postgres.h:49:0,
                 from gppc.c:10:
/usr/include/postgresql/server/utils/palloc.h:81:13: note: declared here
 extern void pfree(void *pointer);
             ^
gppc.c: In function ‘GppcHeapFormTuple’:
gppc.c:1486:2: warning: implicit declaration of function ‘heap_form_tuple’ [-Wimplicit-function-declaration]
  return (GppcHeapTuple) heap_form_tuple((TupleDesc) tupdesc, values, nulls);
  ^
gppc.c:1486:9: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
  return (GppcHeapTuple) heap_form_tuple((TupleDesc) tupdesc, values, nulls);
         ^
gppc.c: In function ‘GppcBuildHeapTupleDatum’:
gppc.c:1497:8: warning: assignment makes pointer from integer without a cast
  tuple = heap_form_tuple((TupleDesc) tupdesc, values, nulls);
        ^
gppc.c: In function ‘GppcCStringGetNumeric’:
gppc.c:680:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
make[3]: *** [<builtin>: gppc.o] Error 1`

**Comment by marcin-github** [comment]
gcc-4.9.4

What should I do to compile gpdb?

**Comment by hlinnaka** [comment]
I think you're right that this is caused by the fact that you already have PostgreSQL 9.5 installed on the box. And in particular, because it's installed in the same directory. In fact, if you tried to do "make install", it would overwrite files from your existing PostgreSQL 9.5 installation, and create a mess. Better to install GPDB in a different location (i.e. use a different --prefix, and other directory options).

**Comment by marcin-github** [comment]
I don't afraid overwriting files because I'm using package manager (I didn't mention about it). I set prefix to something not generic and now it's ok.
Thank you!
