### ISSUE TITLE
pg_class does not have reltablespace filled in

### ISSUE THREAD

**Issue by davecramer** [greenplum-db/gpdb#2080]
select oid, relname, reltablespace from pg_class where relname = 'entry';
  oid  | relname | reltablespace 
-------+---------+---------------
 24686 | entry   |             0

**Comment by Eulerizeit** [comment]
@asimrp @ashwinstar can you look at this please

**Comment by ashwinstar** [comment]
@davecramer can you provide more clues, that line doesn't say much. For tables in default tablespace of a database, pg_class entry records `0` as reltablespace. At runtime it finds it from pg_database what's default tablespace for the database.

**Comment by davecramer** [comment]
@ashwinstar in that case it is working as designed.For some reason I thought this was filled in upstream

**Comment by ashwinstar** [comment]
Only for tables in non-default tablespace for a database it will have value. It's thins way to easy database creation by filesystem copy of pg_class instead of modifying the same later.
