### ISSUE TITLE
open source GPDB 5 version  relation "gp_master_mirroring" does not exist?

### ISSUE THREAD

**Issue by zhangguohan** [greenplum-db/gpdb#2088]
HI ,everyone

When we try to use gp_master_mirroring check the synchronization process, prompt "gp_master_mirroring "does not exist?, the open source GPDB 5 does not support check synchronization  stat?

[gpadmin@mdw ~]$ gpstate 
20170323:16:34:20:018371 gpstate:mdw:gpadmin-[INFO]:-Starting gpstate with args: 
20170323:16:34:20:018371 gpstate:mdw:gpadmin-[INFO]:-local Greenplum Version: 'postgres (Greenplum Database) 5.0.0-alpha.0+dev.212.gb533bcb build dev'
20170323:16:34:20:018371 gpstate:mdw:gpadmin-[INFO]:-master Greenplum Version: 'PostgreSQL 8.3.23 (Greenplum Database 5.0.0-alpha.0+dev.212.gb533bcb build dev) on x86_64-pc-linux-gnu, compiled by GCC gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11) compiled on Mar 19 2017 10:21:20'
20170323:16:34:20:018371 gpstate:mdw:gpadmin-[INFO]:-Obtaining Segment details from master...
20170323:16:34:20:018371 gpstate:mdw:gpadmin-[INFO]:-Gathering data from segments...
. 
20170323:16:34:21:018371 gpstate:mdw:gpadmin-[INFO]:-Greenplum instance status summary
20170323:16:34:21:018371 gpstate:mdw:gpadmin-[INFO]:-----------------------------------------------------
20170323:16:34:21:018371 gpstate:mdw:gpadmin-[INFO]:-   Master instance                                = Active
20170323:16:34:21:018371 gpstate:mdw:gpadmin-[INFO]:-   Master standby                                 = sdw03
20170323:16:34:21:018371 gpstate:mdw:gpadmin-[INFO]:-   Standby master state                           = Standby host passive
20170323:16:34:21:018371 gpstate:mdw:gpadmin-[INFO]:-   Total segment instance count from metadata     = 3
20170323:16:34:21:018371 gpstate:mdw:gpadmin-[INFO]:-----------------------------------------------------
20170323:16:34:21:018371 gpstate:mdw:gpadmin-[INFO]:-   Primary Segment Status
20170323:16:34:21:018371 gpstate:mdw:gpadmin-[INFO]:-----------------------------------------------------
20170323:16:34:21:018371 gpstate:mdw:gpadmin-[INFO]:-   Total primary segments                         = 3
20170323:16:34:21:018371 gpstate:mdw:gpadmin-[INFO]:-   Total primary segment valid (at master)        = 3
20170323:16:34:21:018371 gpstate:mdw:gpadmin-[INFO]:-   Total primary segment failures (at master)     = 0
20170323:16:34:21:018371 gpstate:mdw:gpadmin-[INFO]:-   Total number of postmaster.pid files missing   = 0
20170323:16:34:21:018371 gpstate:mdw:gpadmin-[INFO]:-   Total number of postmaster.pid files found     = 3
20170323:16:34:21:018371 gpstate:mdw:gpadmin-[INFO]:-   Total number of postmaster.pid PIDs missing    = 0
20170323:16:34:21:018371 gpstate:mdw:gpadmin-[INFO]:-   Total number of postmaster.pid PIDs found      = 3
20170323:16:34:21:018371 gpstate:mdw:gpadmin-[INFO]:-   Total number of /tmp lock files missing        = 0
20170323:16:34:21:018371 gpstate:mdw:gpadmin-[INFO]:-   Total number of /tmp lock files found          = 3
20170323:16:34:21:018371 gpstate:mdw:gpadmin-[INFO]:-   Total number postmaster processes missing      = 0
20170323:16:34:21:018371 gpstate:mdw:gpadmin-[INFO]:-   Total number postmaster processes found        = 3
20170323:16:34:21:018371 gpstate:mdw:gpadmin-[INFO]:-----------------------------------------------------
20170323:16:34:21:018371 gpstate:mdw:gpadmin-[INFO]:-   Mirror Segment Status
20170323:16:34:21:018371 gpstate:mdw:gpadmin-[INFO]:-----------------------------------------------------
20170323:16:34:21:018371 gpstate:mdw:gpadmin-[INFO]:-   Mirrors not configured on this array
20170323:16:34:21:018371 gpstate:mdw:gpadmin-[INFO]:-----------------------------------------------------
[gpadmin@mdw ~]$

**Comment by ashwinstar** [comment]
gp_master_mirroring was the table used in 4.2 version. It has been removed or doesn't exists since 4.3 and 5.0 OSS. New master mirroring implementation based on wal replication is used for newer GPDB versions so instead use `select * from pg_stat_replication`, refer to docs which provide information on newer functionality and functions.
