### ISSUE TITLE
Replace "ed" dependency used by gpinitsystem and gpcreateseg.sh

### ISSUE THREAD

**Issue by edespino** [greenplum-db/gpdb#21]
Currently used by gpinitsystem and gpcreateseg.sh and defined in the function "ED_PG_CONF" (defined  in gpMgmt/bin/lib/gp_bash_functions.sh), replace the use of "ed" (line-oriented text editor) with a more readily available package (example: sed).

If "ed" is not available, one will see somewhat messages similar to "[WARN]:-Failed to replace #port in */postgresql.conf".  One needs to hunt around to actually see that "ed" is missing from the runtime environment.

**Comment by Xangis** [comment]
I ran into this problem recently and had to spend a little time tracking it down. Would be in favor of sed as a replacement.

**Comment by edespino** [comment]
@Xangis - I hope to merge this pull request today.
