### ISSUE TITLE
Failed to start Master instance in admin mode in version 5.0.0-alpha.0 

### ISSUE THREAD

**Issue by mstaryi** [greenplum-db/gpdb#2101]
I‘m build a gpdb on centos 6.7 prepare to install, when executed the gpinitsystem I was encountered the “Failed to start Master instance in admin mode” error:

20170327:18:08:03:009605 gpstart:file3:gpadmin-[CRITICAL]:-Failed to start Master instance in admin mode
20170327:18:08:03:009605 gpstart:file3:gpadmin-[CRITICAL]:-Error occurred: non-zero rc: 1
 Command was: 'env GPSESSID=0000000000 GPERA=None $GPHOME/bin/pg_ctl -D /data/master/gpseg-1 -l /data/master/gpseg-1/pg_log/startup.log -w -t 600 -o " -p 5432 -b 1 -z 0 --silent-mode=true -i -M master -C -1 -x 0 -c gp_role=utility " start'
rc=1, stdout='waiting for server to start.......................................................... stopped waiting
', stderr='pg_ctl: could not start server
Examine the log output.
' 
I found an error line “/usr/local/GP-5.0.0/bin/postgres: invalid option -- 'z'” in startup.log, when I check the options with “postgres --help", no “-z” option also.
What's the problem?

My build configure option was:
./configure --prefix=${gpdb_path} --with-gssapi --with-libedit-preferred --with-perl --with-python --with-openssl \
            --with-pam --with-krb5 --with-ldap --with-libxml --with-ossp-uuid --enable-cassert --enable-debug \
            --enable-testutils --enable-debugbreak --enable-depend --enable-mapreduce

**Comment by mstaryi** [comment]
This problem was caused by the coverage of the old version of gppylib directory, my compiler script has some problems. thanks

**Comment by danielgustafsson** [comment]
I was about to say, it seems you are running an old version of the management tools (gp.py in particular), `-z X` was removed in favor of `--gp_num_contents_in_cluster=X`. Seems you found it as well so closing this.
