### ISSUE TITLE
CTAS with duplicated distribution keys should throw syntax error

### ISSUE THREAD

**Issue by ysung-pivotal** [greenplum-db/gpdb#2120]
"create table 'aaa' as select * from bbb distributed by (key1, key1, key2);" should throw syntax error ", just like "create table bbb (key1, key2, key3) distributed by (key1, key1, key2); ", "ERROR, "duplicate column ", "key1"" in Distributed By clause.  
 Instead, the table created without any error. 
when \d+ aaa, it does show duplicate column in distributed by clause.

**Comment by danielgustafsson** [comment]
Fixed via #2128
