### ISSUE TITLE
Delete From table with partition

### ISSUE THREAD

**Issue by salahaldin** [greenplum-db/gpdb#2148]
Hello, 

I am using an old version of greenplum, so I can not tell if this already fixed/reported  or not 

I am getting the following error. 
` DELETE FROM master  WHERE date_iso ='2017-04-01';
ERROR:  could not find junk ctid column (execMain.c:1973)
`
Master is the parent table and it has several childs as follws:
` db=# \d+ master
                           Table "master"
     Column      |           Type           | Modifiers | Storage  | Description
-----------------+--------------------------+-----------+----------+-------------
 date_iso        | date                     | not null  | plain    |
...
Child tables: master_2016_01,
              master_2016_02,
              master_2016_03,
              master_2016_04
Has OIDs: no
Distributed randomly
Partition by: (date_iso)`

Deleting data from the child table goes fine without errors

Regards

**Comment by funnyxj** [comment]
try vacuum full master, execute again.

**Comment by salahaldin** [comment]
Thank you it works now.

**Comment by mahbubur-rahman-healthiq** [comment]
I am experiencing the similar issue on deleting or updating any record and it is showing the error message as 

ERROR:  could not find junk ctid column (execMain.c:2047)

I already tried vacuum full and it did not work. I am using greenplum 5.5. 

Any suggestions or hint will be appreciated.

**Comment by david-kelly-healthiq** [comment]
We solved this issue by changing the setting for the optimizer. In GP 5.5 this had a direct relationship to updating and deleting data.

set optimizer=off;
