### ISSUE TITLE
why the Docs have no install guide

### ISSUE THREAD

**Issue by qinzl1** [greenplum-db/gpdb#2185]

**Comment by cjcjameson** [comment]
Hi there! Are you thinking about the Readme here? https://github.com/greenplum-db/gpdb#build-gpdb-with-planner is a good start that goes through installation but isn't comprehensive.

The bulk of the documentation is checked in here: https://github.com/greenplum-db/gpdb/tree/master/gpdb-doc and rendered to here: http://docs-greenplum-db-staging.cfapps.io/docs-gpdb/common/pivotal-gpdb-features.html ( @dyozie right? )

Are you thinking about other documentation, hosted externally? There's some information on Greenplum.org, like: http://greenplum.org/gpdb-sandbox-tutorials/, and also some Youtube videos at https://www.youtube.com/GreenplumDatabase
