### ISSUE TITLE
merge join can not work

### ISSUE THREAD

**Issue by Toknowledge** [greenplum-db/gpdb#2195]
We find below bug in the latest GP code:

```
create table t1(a int, b int);
create table t2(x int, y int not null);
create index index_a on t1 (a);
create index index_y on t2 (y);

set enable_nestloop to off;
set enable_hashjoin to off;
set enable_mergejoin to on;

EXPLAIN SELECT * from t1 where a not in (select y from t2);

server report : EROR: merge join not support JOIN_LASJ_NOTIN
```

It seems that commit 'eefa4e04bc06fb26c4a0b6732d5fd9a4bbe2d441' has fixed some scenarios, but it does not cover above case.

**Comment by Toknowledge** [comment]
```
diff --git a/src/backend/optimizer/path/joinpath.c b/src/backend/optimizer/path/joinpath.c
index 17d486a..f5c7825 100644
--- a/src/backend/optimizer/path/joinpath.c
+++ b/src/backend/optimizer/path/joinpath.c
@@ -944,6 +944,9 @@ select_mergejoin_clauses(RelOptInfo *joinrel,
        bool            have_nonmergeable_joinclause = false;
        ListCell   *l;
 
+       if(jointype == JOIN_LASJ_NOTIN)
+               return NIL;
+
        foreach(l, restrictlist)
        {
                RestrictInfo *restrictinfo = (RestrictInfo *) lfirst(l);

```

**Comment by hsyuan** [comment]
Since merge join doesn't support JOIN_LASJ_NOTIN, planner should generate plan with `subplan` instead of error out.

**Comment by hlinnaka** [comment]
Opened PR #2674 to fix this. Yeah, we need to teach the planner to not generate merge join paths for LASJ_NOTIN joins. `select_mergejoin_clauses` doesn't seem like quite he right place for it, I think the mergejoin_clauses that it builds are used for other purposes too (there is a comment in the call site, which says that it's called even when merge joins are not enabled). In the PR, I stuck the check in match_unsorted_outer() instead, we have some similar checks in there already.

**Comment by hlinnaka** [comment]
Committed PR #2674, this is now fixed.
