### ISSUE TITLE
make build failing

### ISSUE THREAD

**Issue by deepakgupta8777** [greenplum-db/gpdb#2217]
Error log is as follows:

make[4]: Entering directory '/home/deepak/gpdb/src/backend/gpopt/translate'
g++ -O3 -Wall -Wpointer-arith -Wendif-labels -Wformat-security -fno-strict-aliasing -fwrapv -fno-aggressive-loop-optimizations -Wno-unused-but-set-variable -Wno-address -I../../../../src/include -D_GNU_SOURCE -I/usr/include/libxml2   -c -o CTranslatorRelcacheToDXL.o CTranslatorRelcacheToDXL.cpp
CTranslatorRelcacheToDXL.cpp: In static member function ‘static gpmd::IMDIndex* gpdxl::CTranslatorRelcacheToDXL::Pmdindex(gpos::IMemoryPool*, gpopt::CMDAccessor*, gpmd::IMDId*)’:
CTranslatorRelcacheToDXL.cpp:1068:11: error: no matching function for call to ‘gpmd::CMDIndexGPDB::CMDIndexGPDB(gpos::IMemoryPool*&, gpmd::IMDId*&, gpmd::CMDName*&, gpmd::CMDIdGPDB*, bool&, gpmd::IMDIndex::EmdindexType&, gpmd::IMDId*&, bool, gpos::DrgPul*&, gpos::DrgPul*&, gpmd::DrgPmdid*&, NULL)’
           );
           ^
In file included from CTranslatorRelcacheToDXL.cpp:62:0:
/usr/local/include/naucrates/md/CMDIndexGPDB.h:82:4: note: candidate: gpmd::CMDIndexGPDB::CMDIndexGPDB(gpos::IMemoryPool*, gpmd::IMDId*, gpmd::CMDName*, gpos::BOOL, gpmd::IMDIndex::EmdindexType, gpmd::IMDId*, gpos::BOOL, gpos::DrgPul*, gpos::DrgPul*, gpmd::DrgPmdid*, gpmd::IMDPartConstraint*)
    CMDIndexGPDB
    ^
/usr/local/include/naucrates/md/CMDIndexGPDB.h:82:4: note:   candidate expects 11 arguments, 12 provided
/usr/local/include/naucrates/md/CMDIndexGPDB.h:77:4: note: candidate: gpmd::CMDIndexGPDB::CMDIndexGPDB(const gpmd::CMDIndexGPDB&)
    CMDIndexGPDB(const CMDIndexGPDB &);
    ^
/usr/local/include/naucrates/md/CMDIndexGPDB.h:77:4: note:   candidate expects 1 argument, 12 provided
CTranslatorRelcacheToDXL.cpp: In static member function ‘static gpmd::IMDIndex* gpdxl::CTranslatorRelcacheToDXL::PmdindexPartTable(gpos::IMemoryPool*, gpopt::CMDAccessor*, LogicalIndexInfo*, gpmd::IMDId*, const gpmd::IMDRelation*)’:
CTranslatorRelcacheToDXL.cpp:1275:11: error: no matching function for call to ‘gpmd::CMDIndexGPDB::CMDIndexGPDB(gpos::IMemoryPool*&, gpmd::IMDId*&, gpmd::CMDName*&, gpmd::IMDId*, bool&, gpmd::IMDIndex::EmdindexType&, gpmd::IMDId*&, gpos::BOOL&, gpos::DrgPul*&, gpos::DrgPul*&, gpmd::DrgPmdid*&, gpmd::CMDPartConstraintGPDB*&)’
           );
           ^
In file included from CTranslatorRelcacheToDXL.cpp:62:0:
/usr/local/include/naucrates/md/CMDIndexGPDB.h:82:4: note: candidate: gpmd::CMDIndexGPDB::CMDIndexGPDB(gpos::IMemoryPool*, gpmd::IMDId*, gpmd::CMDName*, gpos::BOOL, gpmd::IMDIndex::EmdindexType, gpmd::IMDId*, gpos::BOOL, gpos::DrgPul*, gpos::DrgPul*, gpmd::DrgPmdid*, gpmd::IMDPartConstraint*)
    CMDIndexGPDB
    ^
/usr/local/include/naucrates/md/CMDIndexGPDB.h:82:4: note:   candidate expects 11 arguments, 12 provided
/usr/local/include/naucrates/md/CMDIndexGPDB.h:77:4: note: candidate: gpmd::CMDIndexGPDB::CMDIndexGPDB(const gpmd::CMDIndexGPDB&)
    CMDIndexGPDB(const CMDIndexGPDB &);
    ^
/usr/local/include/naucrates/md/CMDIndexGPDB.h:77:4: note:   candidate expects 1 argument, 12 provided
<builtin>: recipe for target 'CTranslatorRelcacheToDXL.o' failed
make[4]: *** [CTranslatorRelcacheToDXL.o] Error 1
make[4]: Leaving directory '/home/deepak/gpdb/src/backend/gpopt/translate'
../../../src/backend/common.mk:43: recipe for target 'translate-recursive' failed
make[3]: *** [translate-recursive] Error 2
make[3]: Leaving directory '/home/deepak/gpdb/src/backend/gpopt'
common.mk:43: recipe for target 'gpopt-recursive' failed
make[2]: *** [gpopt-recursive] Error 2
make[2]: Leaving directory '/home/deepak/gpdb/src/backend'
Makefile:17: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/deepak/gpdb/src'
GNUmakefile:14: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by hsyuan** [comment]
please get latest gpdb and gporca, and build again.

**Comment by vraghavan78** [comment]
It works now.
