### ISSUE TITLE
GPDB5.0 has plans to support oracle_fdw\Mysql_fdw \Redis_fdw and other related FDW?

### ISSUE THREAD

**Issue by zhangguohan** [greenplum-db/gpdb#2237]

**Comment by hlinnaka** [comment]
No, GPDB 5 will not support FDWs. The current plan is to support them in GPDB 6, after merging with PostgreSQL 8.4-9.1, where FDW support was added to PostgreSQL.

**Comment by zhangguohan** [comment]
Thank you! @hlinnaka
