### ISSUE TITLE
produce zero result when 'optimizer_static_partition_selection = off'

### ISSUE THREAD

**Issue by ppggff** [greenplum-db/gpdb#2249]
When 'optimizer_static_partition_selection = off', query may produce zero result.
Example:
```
TEST=# create table t(a int)partition by range(a)(end(10), end(20), end(30));
NOTICE:  Table doesn't have 'DISTRIBUTED BY' clause -- Using column named 'a' as the Greenplum Database data distribution key for this table.
HINT:  The 'DISTRIBUTED BY' clause determines the distribution of data. Make sure column(s) chosen are the optimal data distribution key to minimize skew.
NOTICE:  CREATE TABLE will create partition "t_1_prt_1" for table "t"
NOTICE:  CREATE TABLE will create partition "t_1_prt_2" for table "t"
NOTICE:  CREATE TABLE will create partition "t_1_prt_3" for table "t"
CREATE TABLE


TEST=# insert into t values(11);
INSERT 0 1
TEST=# insert into t values(22);
INSERT 0 1



TEST=# set optimizer_static_partition_selection to off;
SET
TEST=# explain select * from t;
                                           QUERY PLAN
-------------------------------------------------------------------------------------------------
 Gather Motion 2:1  (slice1; segments: 2)  (cost=0.00..431.00 rows=1 width=4)
   ->  Sequence  (cost=0.00..431.00 rows=1 width=4)
         ->  Partition Selector for t (dynamic scan id: 1)  (cost=10.00..100.00 rows=50 width=4)
         ->  Dynamic Table Scan on t (dynamic scan id: 1)  (cost=0.00..431.00 rows=1 width=4)
 Settings:  optimizer=on
 Optimizer status: PQO version 2.23.0
(6 rows)

TEST=#
TEST=# select * from t;
 a
---
(0 rows)
```

It may be caused by "https://github.com/greenplum-db/gpdb/commit/7b6dc9bfff555e902a6a5b9333023a4c618de3fe".

**Comment by dhanashreek89** [comment]
Hi Zhenqi, thanks for bringing this up. Jesse and I will take a quick look at it. Before we get back to you, make sure you reach a wider community by posting this question on [our mailing list](gpdb-dev@greenplum.org).

Thanks!
Dhanashree and Jesse (@d)

**Comment by hsyuan** [comment]
Why do we need this GUC? Shouldn't it be removed?
We already have `optimizer_enable_partition_selection` to control whether to enable partition elimination or not, having GUC `optimizer_static_partition_selection` to control static partition elimination doesn't make sense to me.

I recommend we remove this GUC. 
Thoughts?

**Comment by hsyuan** [comment]
BTW, I don't think it is related with that specific commit.

**Comment by dhanashreek89** [comment]
`optimizer_enable_partition_selection` only controls the printable filters. It is used in `PexprExtractPredicatesOnPartKeys()`. If this guc is off , the `<dxl:PrintableFilter>` does not contain filter expression and just a boolean Const set to true.  Also we never try to execute PrintablePredicate. So this guc only affects `Explain` behavior.

Whereas, `optimizer_static_partition_selection` controls the static partition selection and has impact on executor. Hence we (Ekta and I) think that they are semantically different and we can not remove `optimizer_static_partition_selection`.

Thanks
Ekta and Dhanashree

**Comment by hsyuan** [comment]
I don't think so. check this out:

```
hyuan=# set optimizer_enable_partition_selection = on;
hyuan=# explain select * from t where a < 10;
                                           QUERY PLAN
-------------------------------------------------------------------------------------------------
 Gather Motion 3:1  (slice1; segments: 3)  (cost=0.00..431.00 rows=1 width=4)
   ->  Sequence  (cost=0.00..431.00 rows=1 width=4)
         ->  Partition Selector for t (dynamic scan id: 1)  (cost=10.00..100.00 rows=34 width=4)
               Filter: a < 10
               Partitions selected: 1 (out of 3)
         ->  Dynamic Table Scan on t (dynamic scan id: 1)  (cost=0.00..431.00 rows=1 width=4)
               Filter: a < 10
 Settings:  gp_cte_sharing=on; optimizer=on
 Optimizer status: PQO version 2.23.0
(9 rows)

hyuan=# set optimizer_enable_partition_selection = off;
hyuan=# explain select * from t where a < 10;
                                           QUERY PLAN
-------------------------------------------------------------------------------------------------
 Gather Motion 3:1  (slice1; segments: 3)  (cost=0.00..431.00 rows=1 width=4)
   ->  Sequence  (cost=0.00..431.00 rows=1 width=4)
         ->  Partition Selector for t (dynamic scan id: 1)  (cost=10.00..100.00 rows=34 width=4)
               Partitions selected: 3 (out of 3)
         ->  Dynamic Table Scan on t (dynamic scan id: 1)  (cost=0.00..431.00 rows=1 width=4)
               Filter: a < 10
 Settings:  gp_cte_sharing=on; optimizer=on
 Optimizer status: PQO version 2.23.0
(8 rows)
```

Both static and dynamic partition selection can be controlled by `optimizer_enable_partition_selection`. Hence I don't think we need GUC `optimizer_static_partition_selection` specifically for static partition selection. It seems redundant.

**Comment by dhanashreek89** [comment]
@hsyuan The partition selection is not really controlled by `optimizer_enable_partition_selection`. In your both queries, the guc `optimizer_static_partition_selection` is on by default hence there is static partition elimination.

But in general, yes we agree that we don't need to control static partition elimination by a guc. We should always go for it whenever possible.

We will remove `optimizer_static_partition_selection`.

**Comment by ppggff** [comment]
@dhanashreek89 thanks for fixing.
