### ISSUE TITLE
incremental resync from change tracking log bug

### ISSUE THREAD

**Issue by lannis** [greenplum-db/gpdb#225]
I read this function FileRepPrimary_ResyncBufferPoolIncrementalWrite() and find this code may be not correct.   

As far as i know that before excute incwrite we got a series of CTL info, and i think the CTL end lsn should be equal or bigger than page lsn, because we collect CTL information from xlog records which write ahead data.   

So it's hard to understand this code, the condition is not consistent  with the ereport info.
`if (XLByteLE(result->entries[ii].lsn_end, PageGetLSN(page)))  
				{  
					if (! XLByteEQ(PageGetLSN(page), result->entries[ii].lsn_end))  
					{  
						ereport(LOG,  
							(errmsg("Resynchonize buffer pool relation '%u/%u/%u' block '%d' has page lsn less than CT lsn, "  
								"lsn end change tracking '%s(%u/%u)' lsn page '%s(%u/%u)' "  
								"number of blocks '%d'",  
								smgr_relation->smgr_rnode.spcNode,  
								smgr_relation->smgr_rnode.dbNode,  
								smgr_relation->smgr_rnode.relNode,  
								result->entries[ii].block_num,  
								XLogLocationToString(&loc),  
								loc.xlogid,  
								loc.xrecoff, 
								XLogLocationToString(&loc1),  
								loc1.xlogid,  
								loc1.xrecoff,  
								numBlocks),  
							 FileRep_errcontext()));  
                                     }  
				smgrwrite(smgr_relation, result->entries[ii].block_num,  (char *)BufferGetBlock(buf), FALSE);
				}`

Maybe i think, the condition should be like this:
`if (XLByteLE(PageGetLSN(page), result->entries[ii].lsn_end))  `

**Comment by GodenYao** [comment]
Your statement on incwrite seems correct. 
However, as you mentioned the code is hard to understand. we haven't seen any bugs surfaced related to this logic.

Can you see if you can come up with some test cases that would fail due to the current logic?
