### ISSUE TITLE
Add Requirements File for Python Modules

### ISSUE THREAD

**Issue by Xangis** [greenplum-db/gpdb#23]
It's not clear what versions of the Python modules (lockfile, paramiko, etc) are best for use with gpdb. 

Please include a requirements.txt file to make it easy to install all of the python dependencies/extras in one shot with pip.

**Comment by jimmyyih** [comment]
We were thinking of adding a requirements.txt before but #2 covers this pretty well.  Do you still see a need for a requirements.txt if #2 is merged in?

**Comment by Xangis** [comment]
That looks like a pretty good solution.

I ran into a problem where my colleague had lockfile 0.8 installed and I had 0.10.2 installed, and it wasn't clear what the problem was at first (0.8 does not work and 0.10 does). As long as there's a clean way to be sure that the correct Python modules are installed and at the right versions it should be good.

**Comment by Xangis** [comment]
In case it's useful, though, this is the requirements.txt file I've been using and it seems to work. Not sure if the versions are the best to use:

PSI==0.3b2
lockfile==0.11
paramiko==1.15.4
epydoc==3.0.1

**Comment by skahler-pivotal** [comment]
Closing issue due to it being covered in [#2](https://github.com/greenplum-db/gpdb/pull/2)
