### ISSUE TITLE
Resource Queue NOT working with jdbc/odbc client

### ISSUE THREAD

**Issue by srinivasmattapalli** [greenplum-db/gpdb#2308]
Tested with 5.0.alpha release. Any client connected through libpq (psql, pgAdmin) uses RQ, but the jobs submitted through official JDBC, and 3rd party ODBC drivers seems to bypass RQ ( tested with Spark ).

In our use case, spark is launching 100's of queries at once, but since RQ is not getting used ( confirmed with gp_resqueue_status, gp_rsq_activity ) all queries are getting executed simultaneously, and eventually master going out of Memory 

Log file is filled with errors (similar to below), when the spark job is submitted..

2017-04-25 17:41:42.752726 UTC,"test1","gpdb",p7081,th-2005497984,"172.17.24.135","46656",2017-04-25 17:41:38 UTC,0,con100665,cmd1,seg-1,,dx107329,,sx1,"LOG","00000","could not unlink file ""base/16384/pgsql_tmp/pgsql_tmp_sess100665_w7081_qdxid107329_qdcid0_sync1"": No such file or directory",,,,,,,0,,"fd.c",1164,

**Comment by davecramer** [comment]
This is interesting. How would the connection make any difference. Do we use any session level GUC's to enable the RQ?

**Comment by eurekaka** [comment]
Opened PR https://github.com/greenplum-db/gpdb/pull/2344 for this.

**Comment by hlinnaka** [comment]
PR #2344 was pushed. Can this be closed now?
