### ISSUE TITLE
missing sort node when planning aggregate function by ORCA

### ISSUE THREAD

**Issue by Eric5553** [greenplum-db/gpdb#2318]
**How to reproduce:**
Following issue was hit when running installcheck-good case polymorphism.sql with ORCA enabled.
```
CREATE TABLE INT8_TBL(q1 int8, q2 int8);
INSERT INTO INT8_TBL VALUES('  123   ','  456');
INSERT INTO INT8_TBL VALUES('123   ','4567890123456789');
INSERT INTO INT8_TBL VALUES('4567890123456789','123');
INSERT INTO INT8_TBL VALUES('4567890123456789','4567890123456789');
INSERT INTO INT8_TBL VALUES('4567890123456789','-4567890123456789');

create function add_group(grp anyarray, ad anyelement, size integer)
  returns anyarray
  as $$
begin
  if grp is null then
    return array[ad];
  end if;
  if array_upper(grp, 1) < size then
    return grp || ad;
  end if;
  return grp;
end;
$$
  language plpgsql immutable;

create aggregate build_group(anyelement, integer) (
  SFUNC = add_group,
  STYPE = anyarray
);

select build_group(q1,3) from (select q1 from int8_tbl order by q1) as t;
```
The expected result should be
```
 {123,123,4567890123456789}
```
but we got random result 
``` 
{123,123,4567890123456789}  or {4567890123456789,4567890123456789,4567890123456789}
```

**What we found**
By explaining the query plan, we found the ORCA generated query plan missed SORT node.

ORCA Optimizer
```
                                     QUERY PLAN
------------------------------------------------------------------------------------
 Aggregate  (cost=0.00..431.00 rows=1 width=8)
   ->  Gather Motion 2:1  (slice1; segments: 2)  (cost=0.00..431.00 rows=1 width=8)
         ->  Table Scan on int8_tbl  (cost=0.00..431.00 rows=1 width=8)
 Settings:  optimizer=on
 Optimizer status: PQO version 2.23.0
```
Legacy Optimizer
```
                                    QUERY PLAN
----------------------------------------------------------------------------------
 Aggregate  (cost=1.07..1.08 rows=1 width=32)
   ->  Gather Motion 2:1  (slice1; segments: 2)  (cost=1.02..1.06 rows=1 width=8)
         Merge Key: int8_tbl.q1
         ->  Sort  (cost=1.02..1.02 rows=1 width=8)
               Sort Key: int8_tbl.q1
               ->  Seq Scan on int8_tbl  (cost=0.00..1.01 rows=1 width=8)
 Settings:  optimizer=off
 Optimizer status: legacy query optimizer
```

**Comment by hsyuan** [comment]
The sort operator is superfluous and can be removed. Even you have an order clause, the subquery output order is not guaranteed.

**Comment by vraghavan78** [comment]
SQL standard states that Order by clause inside derived table does not guarantee order of output tuples. Orca will not drop order by clause if it has limit, but note that by SQL standard this does not guarantee the output is sorted.

Look it in another way, assume that there is a database X that stores the database in a sorted order. By SQL standard selecting tuples out of this table in database X is not guarantee to be sorted. A derived table is the same in spirit.

I am closing this issue, since we are not going to fix this as Orca is compliant with SQL standard definition.

**Comment by Eric5553** [comment]
@vraghavan78 @hsyuan  Thanks so much for your explanation. 

Since the aggregation function in this case is tuple order sensitive. To make the test result consistent and not dependent on different optimizer engine(legacy/ORCA), we should slightly modify the test case, right?

Following could be an alternative way to clear the test.
```
select build_group(q1,3) from (select q1 from int8_tbl order by q1 limit 3) as t;
```

**Comment by vraghavan78** [comment]
hmm.... I guess that  is the only way.
