### ISSUE TITLE
Build failing with "--enable-orca" flag set

### ISSUE THREAD

**Issue by srinivasmattapalli** [greenplum-db/gpdb#2361]
Using latest code for gp-xerces, gporca, gpdb.

Builds successfully without "--enable-orca" flag.

error log
========
make[4]: Leaving directory `/usr/src/rpm/SOURCES/gpdb/src/backend/gpopt/config'
make -C translate all
make[4]: Entering directory `/usr/src/rpm/SOURCES/gpdb/src/backend/gpopt/translate'
g++ -Wall -Wpointer-arith -Wendif-labels -Wformat-security -fno-strict-aliasing -fwrapv -fno-aggressive-loop-optimizations -Wno-unused-but-set-variable -Wno-address -I../../../../src/include -D_GNU_SOURCE -I/usr/include/libxml2   -c -o CMappingColIdVar.o CMappingColIdVar.cpp
g++ -Wall -Wpointer-arith -Wendif-labels -Wformat-security -fno-strict-aliasing -fwrapv -fno-aggressive-loop-optimizations -Wno-unused-but-set-variable -Wno-address -I../../../../src/include -D_GNU_SOURCE -I/usr/include/libxml2   -c -o CMappingVarColId.o CMappingVarColId.cpp
g++ -Wall -Wpointer-arith -Wendif-labels -Wformat-security -fno-strict-aliasing -fwrapv -fno-aggressive-loop-optimizations -Wno-unused-but-set-variable -Wno-address -I../../../../src/include -D_GNU_SOURCE -I/usr/include/libxml2   -c -o CMappingElementColIdParamId.o CMappingElementColIdParamId.cpp
g++ -Wall -Wpointer-arith -Wendif-labels -Wformat-security -fno-strict-aliasing -fwrapv -fno-aggressive-loop-optimizations -Wno-unused-but-set-variable -Wno-address -I../../../../src/include -D_GNU_SOURCE -I/usr/include/libxml2   -c -o CMappingColIdVarPlStmt.o CMappingColIdVarPlStmt.cpp
g++ -Wall -Wpointer-arith -Wendif-labels -Wformat-security -fno-strict-aliasing -fwrapv -fno-aggressive-loop-optimizations -Wno-unused-but-set-variable -Wno-address -I../../../../src/include -D_GNU_SOURCE -I/usr/include/libxml2   -c -o CMappingElementColIdTE.o CMappingElementColIdTE.cpp
g++ -Wall -Wpointer-arith -Wendif-labels -Wformat-security -fno-strict-aliasing -fwrapv -fno-aggressive-loop-optimizations -Wno-unused-but-set-variable -Wno-address -I../../../../src/include -D_GNU_SOURCE -I/usr/include/libxml2   -c -o CDXLTranslateContextBaseTable.o CDXLTranslateContextBaseTable.cpp
g++ -Wall -Wpointer-arith -Wendif-labels -Wformat-security -fno-strict-aliasing -fwrapv -fno-aggressive-loop-optimizations -Wno-unused-but-set-variable -Wno-address -I../../../../src/include -D_GNU_SOURCE -I/usr/include/libxml2   -c -o CCTEListEntry.o CCTEListEntry.cpp
g++ -Wall -Wpointer-arith -Wendif-labels -Wformat-security -fno-strict-aliasing -fwrapv -fno-aggressive-loop-optimizations -Wno-unused-but-set-variable -Wno-address -I../../../../src/include -D_GNU_SOURCE -I/usr/include/libxml2   -c -o CContextDXLToPlStmt.o CContextDXLToPlStmt.cpp
g++ -Wall -Wpointer-arith -Wendif-labels -Wformat-security -fno-strict-aliasing -fwrapv -fno-aggressive-loop-optimizations -Wno-unused-but-set-variable -Wno-address -I../../../../src/include -D_GNU_SOURCE -I/usr/include/libxml2   -c -o CDXLTranslateContext.o CDXLTranslateContext.cpp
g++ -Wall -Wpointer-arith -Wendif-labels -Wformat-security -fno-strict-aliasing -fwrapv -fno-aggressive-loop-optimizations -Wno-unused-but-set-variable -Wno-address -I../../../../src/include -D_GNU_SOURCE -I/usr/include/libxml2   -c -o CQueryMutators.o CQueryMutators.cpp
g++ -Wall -Wpointer-arith -Wendif-labels -Wformat-security -fno-strict-aliasing -fwrapv -fno-aggressive-loop-optimizations -Wno-unused-but-set-variable -Wno-address -I../../../../src/include -D_GNU_SOURCE -I/usr/include/libxml2   -c -o CTranslatorScalarToDXL.o CTranslatorScalarToDXL.cpp
g++ -Wall -Wpointer-arith -Wendif-labels -Wformat-security -fno-strict-aliasing -fwrapv -fno-aggressive-loop-optimizations -Wno-unused-but-set-variable -Wno-address -I../../../../src/include -D_GNU_SOURCE -I/usr/include/libxml2   -c -o CTranslatorDXLToScalar.o CTranslatorDXLToScalar.cpp
CTranslatorDXLToScalar.cpp: In member function ‘Expr* gpdxl::CTranslatorDXLToScalar::PexprFromDXLNodeScalar(const gpdxl::CDXLNode*, gpdxl::CMappingColIdVar*)’:
CTranslatorDXLToScalar.cpp:120:4: error: ‘EdxlopScalarPartListValues’ was not declared in this scope
   {EdxlopScalarPartListValues, &CTranslatorDXLToScalar::PexprPartListValues},
    ^
CTranslatorDXLToScalar.cpp:121:4: error: ‘EdxlopScalarPartListNullTest’ was not declared in this scope
   {EdxlopScalarPartListNullTest, &CTranslatorDXLToScalar::PexprPartListNullTest},
    ^
CTranslatorDXLToScalar.cpp: In member function ‘Expr* gpdxl::CTranslatorDXLToScalar::PexprPartListValues(const gpdxl::CDXLNode*, gpdxl::CMappingColIdVar*)’:
CTranslatorDXLToScalar.cpp:1756:2: error: ‘CDXLScalarPartListValues’ was not declared in this scope
  CDXLScalarPartListValues *pdxlop = CDXLScalarPartListValues::PdxlopConvert(pdxlnPartListValues->Pdxlop());
  ^
CTranslatorDXLToScalar.cpp:1756:28: error: ‘pdxlop’ was not declared in this scope
  CDXLScalarPartListValues *pdxlop = CDXLScalarPartListValues::PdxlopConvert(pdxlnPartListValues->Pdxlop());
                            ^
CTranslatorDXLToScalar.cpp:1756:37: error: ‘CDXLScalarPartListValues’ is not a class or namespace
  CDXLScalarPartListValues *pdxlop = CDXLScalarPartListValues::PdxlopConvert(pdxlnPartListValues->Pdxlop());
                                     ^
CTranslatorDXLToScalar.cpp: In member function ‘Expr* gpdxl::CTranslatorDXLToScalar::PexprPartListNullTest(const gpdxl::CDXLNode*, gpdxl::CMappingColIdVar*)’:
CTranslatorDXLToScalar.cpp:1781:2: error: ‘CDXLScalarPartListNullTest’ was not declared in this scope
  CDXLScalarPartListNullTest *pdxlop = CDXLScalarPartListNullTest::PdxlopConvert(pdxlnPartListNullTest->Pdxlop());
  ^
CTranslatorDXLToScalar.cpp:1781:30: error: ‘pdxlop’ was not declared in this scope
  CDXLScalarPartListNullTest *pdxlop = CDXLScalarPartListNullTest::PdxlopConvert(pdxlnPartListNullTest->Pdxlop());
                              ^
CTranslatorDXLToScalar.cpp:1781:39: error: ‘CDXLScalarPartListNullTest’ is not a class or namespace
  CDXLScalarPartListNullTest *pdxlop = CDXLScalarPartListNullTest::PdxlopConvert(pdxlnPartListNullTest->Pdxlop());
                                       ^
make[4]: *** [CTranslatorDXLToScalar.o] Error 1
make[4]: Leaving directory `/usr/src/rpm/SOURCES/gpdb/src/backend/gpopt/translate'
make[3]: *** [translate-recursive] Error 2
make[3]: Leaving directory `/usr/src/rpm/SOURCES/gpdb/src/backend/gpopt'
make[2]: *** [gpopt-recursive] Error 2
make[2]: Leaving directory `/usr/src/rpm/SOURCES/gpdb/src/backend'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/usr/src/rpm/SOURCES/gpdb/src'

**Comment by hsyuan** [comment]
This means you are not using latest Orca or you didn't correctly install it.

**Comment by d** [comment]
Hi @srinivasmattapalli! Thank you for checking out Greenplum database! We'd love to help you, but we couldn't reproduce your problem. Could you tell us a step-by-step sequence to reproduce your problem? To facilitate the precision of communication, a Linux container-based repro will be preferred, but any other general information may help too.

Here are the questions that we'd prefer you provide before we are able to further work on this:

0. What are the exact commits of ORCA and gp-xerces are you using?
0. How did you build them? Show us how you configured the build system (autoconf and cmake)
0. With what flags did you run your `./configure` for Greenplum?

Judging on your error message. Looks like your ORCA headers are stale.

**Comment by srinivasmattapalli** [comment]
Thanks Jesse (d) and Haisheng (hsuyan) for looking into this. 

Old gporca was the cause of this issue. After downloading latest version of gporca, build deployed successfully.
