### ISSUE TITLE
How to upgrade existing 5.0.0-dev cluster to newer version

### ISSUE THREAD

**Issue by srinivasmattapalli** [greenplum-db/gpdb#2399]
Hi,

We have a test cluster running on Greenplum Version: "postgres (Greenplum Database) 5.0.0 build dev" ( March opensource build )

We  planned to test out new fixes in Alpha.3 opensource, by replacing the software and upgrade catalog version. But, it seems like "gpmigrator/gpmigrator_mirror" utils are no more available in 5.0 release. Can we use pg_upgrade reliably to upgrade existing cluster in-place ? 

Thanks.

**gpstart LOG**
20170508:23:43:08:035416 gpstart:staging-dev-gp-master:gpadmin-[INFO]:-Starting gpstart with args: 
20170508:23:43:08:035416 gpstart:staging-dev-gp-master:gpadmin-[INFO]:-Gathering information and validating the environment...
20170508:23:43:08:035416 gpstart:staging-dev-gp-master:gpadmin-[INFO]:-Greenplum Binary Version: 'postgres (Greenplum Database) 5.0.0-alpha.3+dev.4.ga030149 build dev'
20170508:23:43:08:035416 gpstart:staging-dev-gp-master:gpadmin-[INFO]:-Greenplum Catalog Version: '301705051'
20170508:23:43:08:035416 gpstart:staging-dev-gp-master:gpadmin-[INFO]:-MASTER_DIRECTORY Catalog Version: '301702171'
20170508:23:43:08:035416 gpstart:staging-dev-gp-master:gpadmin-[INFO]:-Catalog Version of master directory incompatible with binaries
20170508:23:43:08:035416 gpstart:staging-dev-gp-master:gpadmin-[ERROR]:-gpstart error: Catalog Versions are incompatible

**Comment by hlinnaka** [comment]
Safest option would be to use pg_dumpall and restore. pg_upgrade might work, but it's mainly been developed for upgrading from GPDB 4.3, so it might not work on that source version. It's a bit fiddly to use, too, the tooling to run it across the whole cluster have not been written yet.

**Comment by Chibin** [comment]
> We planned to test out new fixes in Alpha.3 opensource, by replacing the software and upgrade catalog version. But, it seems like "gpmigrator/gpmigrator_mirror" utils are no more available in 5.0 release. 

Right, gpmigrator is an old utility that should not apply for GPDB5.
If there's a catalog change within 5.0, as hlinnaka mentioned, the safest (simplest perhaps?) option right now is doing a pg_dumpall and then doing a restore to the new cluster.

**Comment by skahler-pivotal** [comment]
There aren't any utilities that will in place upgrade 5.0-dev to 5.0-alpha.

We removed gpmigrator as it was around moving with 4.x versions and will instead make use of pg_upgrade under the covers for in place migrations. Thus far the concentration has been on making a 4.3 -> 5.0 migration happen using pg_upgrade and we are still doing work in that area.

The suggested method to go from dev -> alpha or dev-> beta when it hits would be to backup and then restore into the newer system.

Once we are locked on catalog changes and hit the beta period we should be binary swapable.

**Comment by srinivasmattapalli** [comment]
Thanks for the info and suggestions.

I assume, since catalog changes are not yet locked, dump and restore dev -> alpha, may not be binary swappable with beta ( alpha -> beta )

**Comment by Eulerizeit** [comment]
Catalog is locked to our best effort in alpha, We encountered a bug we
needed to address that necessitated a catalog change.

-- Rob

On Tue, May 9, 2017 at 2:34 PM, srinivasmattapalli <notifications@github.com
