### ISSUE TITLE
checkinc.py doesn't seem to do whatever it was intended to do

### ISSUE THREAD

**Issue by davecramer** [greenplum-db/gpdb#2426]
Looking at the code it appears to be confirming that the include files are in the installation include directory. Using:

p1 = subprocess.Popen(bindir + 'pg_config --includedir', stdout=subprocess.PIPE, shell=True)
p2 = subprocess.Popen(bindir + 'pg_config --pkgincludedir', stdout=subprocess.PIPE, shell=True)

to get directories to search for. This step is done *before* installation so I fail to see how it would find anything.

Strangely it succeeds on linux, and some macos but not mine, hence the investigation.

Is this file really necessary at all ?

**Comment by ashwinstar** [comment]
Corresponding PR was closed, hence closing the issue as well.
