### ISSUE TITLE
 GUC standard_conforming_strings: Default value on

### ISSUE THREAD

**Issue by lintzc** [greenplum-db/gpdb#2427]
there is an issue on the external tables. Because of this issue, the Informatica PWX connector for Greenplum can't be used on  top of GPDB 5.0 alpha3.

The issue is related to the GUC standard_conforming_strings:
- In GPDB 4.3.x, its default value is  off
- In GPDB 5.0 alpha3, its default value is  on

Because of this new default value, the external table below (generated by Informatica PWX for GP) fails:
drop external table if exists ext_gpload20170510_161623_8312;
create external table ext_gpload20170510_161623_8312
(cartid integer,saveday integer,cartstatusid smallint,memberid integer,parentcartid integer,deliveryaddressid integer,invoiceaddressid integer
,totalamount numeric(19,4),refundamount numeric(10,4),siteid smallint,originalorderid integer,deliverymode integer,deliverydatemin timestamp without time zone
,deliverydatemax timestamp without time zone,paymentdate timestamp without time zone,creationdate timestamp without time zone
,modificationdate timestamp without time zone,savetime timestamp without time zone,load_dts timestamp without time zone)
location('gpfdist://etl_host:8010/\\\\.\\pipe\\file_0_pipe')
format'text' (delimiter '|' null '\\N' escape '\\' )
encoding'utf8' ;
With the error:
ERROR:  escape must be a single character, or [OFF/off] to disable escapes

The same query (in GPDB 4.3.x) works fine.

If you set standard_conforming_strings to off (as in GPDB 4.3.x), it works.
gpadmin=# set standard_conforming_strings=off;
SET
gpadmin=# drop external table if exists ext_gpload20170510_161623_8312;
NOTICE:  table "ext_gpload20170510_161623_8312" does not exist, skipping
DROP EXTERNAL TABLE
gpadmin=# create external table ext_gpload20170510_161623_8312
gpadmin-# (cartid integer,saveday integer,cartstatusid smallint,memberid integer,parentcartid integer,deliveryaddressid integer,invoiceaddressid integer,totalamount numeric(19,4),refundamount numeric(10,4)
gpadmin(# ,siteid smallint,originalorderid integer,deliverymode integer,deliverydatemin timestamp without time zone,deliverydatemax timestamp without time zone,paymentdate timestamp without time zone
gpadmin(# ,creationdate timestamp without time zone,modificationdate timestamp without time zone,savetime timestamp without time zone,load_dts timestamp without time zone)
gpadmin-# location('gpfdist://etl_host:8010/\\\\.\\pipe\\file_0_pipe')
gpadmin-# format'text' (delimiter '|' null '\\N' escape '\\' )
gpadmin-# encoding'utf8' ;
WARNING:  nonstandard use of \\ in a string literal
LINE 5: location('gpfdist://etl_host:8010/\\\\.\\pipe\\file_0_pipe')
                 ^
HINT:  Use the escape string syntax for backslashes, e.g., E'\\'.
WARNING:  nonstandard use of \\ in a string literal
LINE 6: format'text' (delimiter '|' null '\\N' escape '\\' )
                                         ^
HINT:  Use the escape string syntax for backslashes, e.g., E'\\'.
WARNING:  nonstandard use of \\ in a string literal
LINE 6: format'text' (delimiter '|' null '\\N' escape '\\' )
                                                      ^
HINT:  Use the escape string syntax for backslashes, e.g., E'\\'.
CREATE EXTERNAL TABLE

In the GPDB 5.0 alpha guide (https://gpdb.docs.pivotal.io/500Alpha/ref_guide/config_params/guc-list.html#standard_conforming_strings), we can read:
   Reports whether ordinary string literals ('...') treat backslashes literally, as specified in the SQL standard. The value is currently always off, indicating that backslashes are treated as escapes. It is planned that this will change to on in a future release when string literal syntax changes to meet the standard. Applications may check this parameter to determine how string literals will be processed. The presence of this parameter can also be taken as an indication that the escape string syntax (E'...') is supported.

Value Range	Default	Set Classifications
Boolean	off	read only

So the default value is actually different in GPDB 5.0 alpha and in the documentation.

I think that the default value of standard_conforming_strings is GPDB 5.0 alpha3 is not correct.
Besides, the documentation is not correct because we can change this GUC: this GUC is not read only.

**Comment by hlinnaka** [comment]
The change to turn standard_conforming_strings=on by default is intentional. Informatica PWX connector needs to be adjusted for that. (I'm sure you noticed the warnings you got on 4.3 already)

But you're right that the documentation is not up-to-date, that needs to be fixed.

**Comment by dyozie** [comment]
Will update the docs to account for standard_conforming_strings=on by default, and mention this change in the release notes.  

What are the correct set classifications for this GUC?

**Comment by lintzc** [comment]
Indeed, I noticed the warnings.
But my concern is that I am not sure if Informatica will fix this issue quickly and even if they do it, it will be on the last releases. All the customers I know using Informatica takes a lot of time before upgrading their Informatica SW.
So these customers will have to set standard_conforming_strings to off for the roles using Informatica.

BTW, is there a communication to all the vendors officially supporting Greenplum about the changes in GPDB 5?
I am pretty sure that this kind of issue will exist for other vendors.

**Comment by hlinnaka** [comment]
On 05/12/2017 08:23 AM, lintzc wrote:
> Indeed, I noticed the warnings.
> But my concern is that I am not sure if Informatica will fix this issue quickly and even if they do it, it will be on the last releases. All the customers I know using Informatica takes a lot of time before upgrading their Informatica SW.

For better or worse, they're not going to jump to GPDB5 at the drop of a 
hat either.

> So these customers will have to set standard_conforming_strings to off for the roles using Informatica.

Yeah, that's a good work-around.

> BTW, is there a communication to all the vendors officially supporting Greenplum about the changes in GPDB 5?
> I am pretty sure that this kind of issue will exist for other vendors.

I don't know, @inovick?

- Heikki

**Comment by hlinnaka** [comment]
The documentation has been fixed, I don't think there's anything more to do here, so closing.
