### ISSUE TITLE
Update with json accessor fails

### ISSUE THREAD

**Issue by paladan** [greenplum-db/gpdb#2430]
Hey guys! We ran into an issue while working with GPDB5 Alpha 3 on a table of 8 million rows. While attempting to access a property of an inner json, we received the following error. Included below is the original command and error, as well as the stack trace from pg_log, the table schema we were using, and a sample row of data.

**Original Command and Error:**
```
gpadmin=#  update logs set component =  jason::json#>>'{@source,program}' ;
# 10.05NOTICE:  Releasing segworker groups to finish aborting the transaction.
ERROR:  Error on receive from seg0 127.0.0.1:40000 pid=20961: server closed the connection unexpectedly
DETAIL:
    This probably means the server terminated abnormally
    before or while processing the request.
ERROR:  could not connect to segment: initialization of segworker group failed (cdbgang.c:224)
```

**Stack Trace from pg_log:**
```
2017-05-11 17:16:39.544900 UTC,,,p20961,th0,,,2017-05-11 17:05:21 UTC,0,con8,cmd14,seg0,,,,,"PANIC","XX000","Unexp
ected internal error: Segment process received signal SIGSEGV",,,,,,,0,,,,"1    0x7f99e1c80370 libpthread.so.0 <sy
mbol not found> + 0xe1c80370
2    0x915434 postgres <symbol not found> (json.c:103)
3    0x915c1b postgres pg_parse_json (json.c:273)
4    0x918e72 postgres json_extract_path_text (jsonfuncs.c:557)
5    0x693cbe postgres <symbol not found> (execQual.c:2018)
6    0x69d770 postgres ExecTargetList (execQual.c:6268)
7    0x69d97f postgres ExecProject (execQual.c:6459)
8    0x6c43a0 postgres ExecTableScan (tuptable.h:157)
9    0x69034b postgres ExecProcNode (execProcnode.c:1011)
10   0x68da7c postgres <symbol not found> (execMain.c:2760)
11   0x68e022 postgres ExecutorRun (execMain.c:886)
```

**Schema:**
```
gpadmin=# \d+ logs
                             Table "public.logs"
  Column   |            Type             | Modifiers | Storage  | Description
-----------+-----------------------------+-----------+----------+-------------
 timestamp | timestamp without time zone |           | plain    |
 jason     | text                        |           | extended |
 iserror   | boolean                     |           | plain    |
 component | text                        |           | extended |
Has OIDs: no
Distributed by: (timestamp)
```

**Sample Row:**
```
gpadmin=# select * from logs limit 1;
-[ RECORD 1 ]-
timestamp | 2017-04-19 17:21:49.696
jason     | {"@timestamp":"2017-04-19T17:21:49.696Z","port":59712,"@ingestor":{"service":"syslog","job":"ingestor/1","timestamp":"2017-04-19T17:21:49.758+00:00"},"@parser":{"job":"parser/12","timestamp":"2017-04-19T17:21:49.959+00:00","duration":1},"@type":"syslog","@message":"{\"timestamp\":\"1492622509.696033478\",\"source\":\"guardian\",\"message\":\"guardian.run.finished\",\"log_level\":1,\"data\":{\"handle\":\"4a825ce2-4e6a-419d-4812-51128f55ac4f\",\"path\":\"/tmp/lifecycle/healthcheck\",\"session\":\"1152834\"}}","syslog_pri":"14","@raw":"<14>2017-04-19T17:21:49.696081+00:00 10.10.148.107 vcap.garden [job=cell_2xl_z2 index=3]  {\"timestamp\":\"1492622509.696033478\",\"source\":\"guardian\",\"message\":\"guardian.run.finished\",\"log_level\":1,\"data\":{\"handle\":\"4a825ce2-4e6a-419d-4812-51128f55ac4f\",\"path\":\"/tmp/lifecycle/healthcheck\",\"session\":\"1152834\"}}","tags":["syslog_standard","source","auto_deployment"],"syslog_severity_code":6,"syslog_facility_code":1,"syslog_facility":"user-level","syslog_severity":"informational","@source":{"host":"10.10.148.107","job":"cell_2xl_z2","index":3,"vm":"cell_2xl_z2/3","program":"garden","ip":"10.10.148.107","deployment":"Unknown"},"@timer":{"ingested_to_parsed":202}}
iserror   | f
component | {"host":"10.10.148.107","job":"cell_2xl_z2","index":3,"vm":"cell_2xl_z2/3","program":"garden","ip":"10.10.148.107","deployment":"Unknown"}
```

**Comment by hlinnaka** [comment]
Hmm. I suspect we're missing upstream commit 66008564f8ce570f7ad6368fbde2138e946d328b, that might explain it. @danielgustafsson, when you backported the JSON functions, did you pick up any follow-up commits? Looking at the commit history, I believe we should backport all commits in:
```
git log a570c98d7fa0841f17bbf51d62d02d9e493c7fcc..pgsql/REL9_3_STABLE src/backend/utils/adt/json.c
```

**Comment by danielgustafsson** [comment]
> On 12 May 2017, at 07:33, Heikki Linnakangas <notifications@github.com> wrote:
> 
> Hmm. I suspect we're missing upstream commit 6600856, that might explain it. @danielgustafsson, when you backported the JSON functions, did you pick up any follow-up commits? Looking at the commit history, I believe we should backport all commits in:
> 
> git log a570c98d7fa0841f17bbf51d62d02d9e493c7fcc..pgsql/REL9_3_STABLE src/backend/utils/adt/json.c
I picked the smallest subset that would give the most use, to avoid backporting too much. Glancing at the referenced commit I'd say we need that one (at least), not backporting that one was an oversight.

**Comment by hlinnaka** [comment]
Ok, I opened PR #2435 to sync the json-related files completely with PostgreSQL 8.3. It seems easier than cherry-picking individual commits.

@paladan, I wasn't able to re-produce the segfault you saw with the sample row you gave above, but I'm pretty sure that PR 2345 will fix it. If you can compile GPDB from source, could you test that PR to verify that it fixes your problem, please? If not, you can wait for the next alpha version, which should include the fix.

**Comment by paladan** [comment]
@hlinnaka - We have a workaround that will work for us for the next few weeks, so we would be willing to wait for the next alpha. Thanks for looking into this!

**Comment by hlinnaka** [comment]
Pushed the fix now. It just missed GPDB 5 alpha4, unfortunatley, so it's not included in that yet. But will be included in the next version.

I'm closing this on the assumption that it has been fixed, but if you could verify your original test case with the next version when it comes out, that'd be great. Thanks!
