### ISSUE TITLE
Why my cluster is so slow?

### ISSUE THREAD

**Issue by laixiong** [greenplum-db/gpdb#2446]
my greenplum database cluster running for many days, it has 16 segment node,6 primary 6 mirror per segment node,and 15,000,000,000 records load into it every day.
now it is very slow when we use a easy sql like blow,before test we stopped the load process and set the log_min_messages to debug1:

example 1: select * from bigtable1 limit 200; costs:160+s

example 2:select * from bigtable2 limit 200; costs:15+s
example 3:
CREATE TABLE zbyintest0511 WITH (APPENDONLY=TRUE,ORIENTATION=COLUMN,COMPRESSTYPE=ZLIB,COMPRESSLEVEL=5) AS (SELECT F_0 , F_1 , F_2 , F_3 , F_4 , F_5 , F_6 , F_7 , F_8 , F_9 , F_10 , F_11 , F_12 , F_13 , F_14 , F_15 , F_16  FROM test20170511 WHERE  F_2 = '36019') distributed randomly;

test20170511 just have 200 records,when we use CTAS to create a new table, it costs about 60-100s,
but when we split it to 2 sql, it costs 3s,which seems normal:
create table zbyintest0511 as select * from test20170511 where 1=2;
insert into zbyintest0511 select * from test20170511;

[example1.log.txt](https://github.com/greenplum-db/gpdb/files/1000367/example1.log.txt)
[example2.log.txt](https://github.com/greenplum-db/gpdb/files/1000369/example2.log.txt)
[example3.log.txt](https://github.com/greenplum-db/gpdb/files/1000368/example3.log.txt)

**Comment by yydzero** [comment]
Thanks for reporting. A few questions:

1) Which Greenplum version are you using?
2) What is your hardware spec, including network switch?
3) What is gpcheckperf result?
4) From example1.log.txt, it takes 25 seconds to create gang & generate plan which is unusual.

**Comment by laixiong** [comment]
@yydzero , Thank you for replying me so quickly.
1.version :4.3.5.2
2.64G RAM,1 Gigabit Ethernet switching;
3.we will do it later.

**Comment by qzren1982** [comment]
Expected results

**Comment by qzren1982** [comment]
@laixiong  Expected results

**Comment by ashwinstar** [comment]
For commercial version of GPDB, please reach out through commercial support channel.
