### ISSUE TITLE
Several tests fail if build with --disable-orca

### ISSUE THREAD

**Issue by andreasscherbaum** [greenplum-db/gpdb#2467]
The following tests fail when GPDB is compiled with --disable-orca:

- gp_metadata
- bitmapscan
- bitmapscan_ao
- bfv_catalog
- bfv_catalog
- gp_optimizer
- bfv_statistic
- qp_left_anti_semi_join

All failed tests are ORCA related.

**Comment by andreasscherbaum** [comment]
Either the tests should be updated, or the README should be clarified that ORCA is a requirement now.

**Comment by ashwinstar** [comment]
Tests always failed without ORCA, nothing changed there. I agree though
that ALL the tests must PASS, irrespective of with or without ORCA. Should
not be noted in README they would fail.

One dirty way would be to have answer file for planner with expected ERRORs
without ORCA for these tests but still it should pass the test. Or better
not run these tests if will fail without ORCA.

**Comment by vraghavan78** [comment]
PR: https://github.com/greenplum-db/gpdb/pull/2473

**Comment by vraghavan78** [comment]
Now only gp_metadata, and gp_optimizer fails.

**Comment by vraghavan78** [comment]
gp_optimizer is now ok. Please create a new File for gp-metadata. Closing issue
