### ISSUE TITLE
PbsHashJoinXforms error while compiling and installing GPDB with Planner

### ISSUE THREAD

**Issue by Bhattpankaj2000** [greenplum-db/gpdb#2533]
I get an error of **PbsHashJoinXforms** while compiling and installing GPDB. I am using gpdb 5.0.0-alpha.6 on Ubuntu 16.04. 
The error message comes while executing 'make'. Error log message is as below-

> make[3]: Entering directory '/home/pankaj/Downloads/gpdb-master/src/backend/gpopt'
> make -C config all
> make[4]: Entering directory '/home/pankaj/Downloads/gpdb-master/src/backend/gpopt/config'
> g++ -O3 -Wall -Wpointer-arith -Wendif-labels -Wformat-security -fno-strict-aliasing -fwrapv -fno-aggressive-loop-optimizations -Wno-unused-but-set-variable -Wno-address -I../../../../src/include -D_GNU_SOURCE -I/usr/include/libxml2   -c -o CConfigParamMapping.o CConfigParamMapping.cpp
> CConfigParamMapping.cpp: In static member function ‘static gpos::CBitSet* gpdxl::CConfigParamMapping::PbsPack(gpos::IMemoryPool*, gpos::ULONG)’:
> CConfigParamMapping.cpp:453:26: error: ‘PbsHashJoinXforms’ is not a member of ‘gpopt::CXform’
>    CBitSet *pbsHashJoin = CXform::PbsHashJoinXforms(pmp);
>                           ^
> <builtin>: recipe for target 'CConfigParamMapping.o' failed
> make[4]: *** [CConfigParamMapping.o] Error 1
> make[4]: Leaving directory '/home/pankaj/Downloads/gpdb-master/src/backend/gpopt/config'
> ../../../src/backend/common.mk:43: recipe for target 'config-recursive' failed
> make[3]: *** [config-recursive] Error 2
> make[3]: Leaving directory '/home/pankaj/Downloads/gpdb-master/src/backend/gpopt'
> common.mk:43: recipe for target 'gpopt-recursive' failed
> make[2]: *** [gpopt-recursive] Error 2
> make[2]: Leaving directory '/home/pankaj/Downloads/gpdb-master/src/backend'
> Makefile:17: recipe for target 'all' failed
> make[1]: *** [all] Error 2
> make[1]: Leaving directory '/home/pankaj/Downloads/gpdb-master/src'
> GNUmakefile:14: recipe for target 'all' failed
> make: *** [all] Error 2

**Comment by hsyuan** [comment]
Please use latest version of Orca.

**Comment by Chibin** [comment]
> Please use latest version of Orca.

Is there a visible way for an OSS user to know/view which version of Orca they need to use?
If not, would adding a git submodule for Orca be good?
I see that we do some kind of linking for Orca versions anyways, might as well do it for the actual commit of when that version was built, so people can retrieve it easier?
Thoughts?

**Comment by hsyuan** [comment]
Git submodule would be a good option.

Another options is:
Let Orca version always bump the patch version (2.0.XXX), instead of minor
version (2.XXX.0), if there is no API change.
As long as there API change, bump the minor version.
In GPDB's configure file,  check if the installed Orca major.minor version
greater equal than the required version. If not, abort.



~ ~ ~
Haisheng Yuan

**Comment by cjcjameson** [comment]
@hsyuan @Chibin Can you please add your thoughts on the dev-list discussion about dependency management? https://groups.google.com/a/greenplum.org/forum/#!topic/gpdb-dev/5uQnYbLESpM

I'd like to keep the discussion consolidated there while the ideas are still pretty raw. Thanks!

**Comment by Bhattpankaj2000** [comment]
Used gporca-2.32.0 for compiling and this sorted out the issue. Thanks for the valuable suggestions. 
Cheers.

**Comment by Chibin** [comment]
> In GPDB's configure file,  check if the installed Orca major.minor version
> greater equal than the required version. If not, abort.

Yeah, it would definitely be better. At least the user knows if something will break during compilation.

By the way, this is me being oblivious, is Orca backwards compatible? Let's say I go back to a commit a year ago and compile with the latest Orca version, would that still work?


> @hsyuan @Chibin Can you please add your thoughts on the dev-list discussion about dependency management? https://groups.google.com/a/greenplum.org/forum/#!topic/gpdb-dev/5uQnYbLESpM
> 
> I'd like to keep the discussion consolidated there while the ideas are still pretty raw. Thanks!

Sure, sounds good.

**Comment by hsyuan** [comment]
> By the way, this is me being oblivious, is Orca backwards compatible?
Let's say I go back to a commit a year ago and compile with the latest Orca
version, would that still work?

No, it is not backwards compatible.

~ ~ ~
Haisheng Yuan
