### ISSUE TITLE
Window gpload requires 32-bit Python

### ISSUE THREAD

**Issue by kdunn926** [greenplum-db/gpdb#254]
Using gpload in a Windows environment with a 64-bit Python interpreter produces the following error:

```
> gpload.py -f gpload-test.yaml

gpload was unable to import The PyGreSQL Python module (pg.py) - DLL load failed with error code 193
```

Using Python 2.5.4 32-bit seems to correct the issue.

**Comment by ivannovick** [comment]
is this error when compiling from source, or with binaries provided from Pivotal?

**Comment by kdunn926** [comment]
This is a runtime error; gpload.py is raw Python, so the same behavior exists regardless of being OSS unpackaged or Pivotal packaged.

**Comment by ivannovick** [comment]
Is this a packing error or a code error you think?  We should fix it up @schubert @lij55

**Comment by lij55** [comment]
Environment issue. Python 2.5 dependency is hardcoded because of DLL file.

**Comment by danielgustafsson** [comment]
Since Python 2.5 was EOL'd in 2011, we need a strategy to remove this dependency.

**Comment by lij55** [comment]
What about upload gpload to pypi(https://pypi.python.org/pypi) so that any user can install it though pip? @ivannovick @yydzero

**Comment by ivannovick** [comment]
@schubert do you know next step

**Comment by schubert** [comment]
Yup. I tracked down the problem (I think). The bundled pygresql library was compiled against Python 2.5 and not 2.6. So it's not so much a 32-bit vs. 64-bit issue as it is a 2.5 vs. 2.6 issue.

I think I can surgically replace that correctly here.

The next step is to experiment with substuting the packaged pygresql with the contents of http://www.pygresql.org/files/PyGreSQL-4.0.win32-py2.6.msi and validating that they work. If those are 32-bit based then we may need to re-compile it for 64-bit as well. We'll see.

Fundamentally though this requires re-releasing the CCL components.

@kdunn926 can you tell me what version you ran into this issue on? Did you actually compile the current GPDB codebase to get the win32 components? Or are you using a 4.3.x. release from distribution?

**Comment by kdunn926** [comment]
Forgive me for not recalling the specifics, this issue was raised more than 1 year ago. We faced this  with multiple customers and spent too many hours spent tracking down the fact we needed to use a *very* specific Python version and architecture - mainly due to the ambiguity of the error, hence the proposed "fix". 

What I can say for sure: download the Pivotal Greenplum loader packages on Windows (server) with the above 2.5.4, 32bit Python installation, then execute gpload - it should succeed. Do the same for a 2.5.4 64bit Python installation, then execute gpload - it will fail with the error above.

@schubert - it's entirely possible that is the right fix, patching the runtime with a clear warning was intended to be a quick "fix" for new loader utils releases.

**Comment by lij55** [comment]
Unite will work on the error message

**Comment by Eulerizeit** [comment]
@lij55 is this being addressed?

**Comment by lij55** [comment]
We are working on other emergency task but we will solve this definitely.

**Comment by ashwinstar** [comment]
@lij55 Its close to year now, just wish to put this on your radar to fix and close out.
