### ISSUE TITLE
backup and restore

### ISSUE THREAD

**Issue by qzren1982** [greenplum-db/gpdb#2564]
Can the PostgreSQL database have the same backup and restore tools as Oracle's RMAN?
Or does GPDB need backup?

**Comment by qzren1982** [comment]
Good question

**Comment by d** [comment]
Hi @qzren1982 , thank you for your interest in Greenplum Database. However, it is unclear if the question you asked is appropriate for an "issue" on Github. More over, "like"ing your own comment without adding substance to the question won't help the community prioritize or help you. Mind moving over to the gpdb-user@greenplum.org?
