### ISSUE TITLE
Assert break in the AOCSFileSegInfo size calculation

### ISSUE THREAD

**Issue by Eulerizeit** [greenplum-db/gpdb#2567]
Issue reported by @jianlirong in https://github.com/greenplum-db/gpdb/pull/1818

The Assert(VARSIZE(dv) <= aocs_vpinfo_size(nvp)) makes no sense. The Following SQL can break this assert:

create table myao_rollback(i int , j int) with (appendonly=true, orientation=column);
begin;
alter table myao_rollback add column k int default 0;
insert into myao_rollback select i , i + 10, i - 10 from generate_series(1,10) i;
rollback;
SELECT * FROM myao_rollback;

This is because for the insert operation, a new segno (here it is 1) is assigned, and there is a corresponding tuple inserted into pg_aoseg with xmin as FrozenTransactionId.

**Comment by jianlirong** [comment]
I just did a double check, and this issue still exists with the master branch. So, would somebody please explain a little bit why we just closed this issue without any comment or further action? Thanks.
