### ISSUE TITLE
Two questions regarding lock related code

### ISSUE THREAD

**Issue by eurekaka** [greenplum-db/gpdb#257]
Hi there,

I have two questions regarding lock related code:

* The first question is: in function ProcSleep, after the process has been waken up, either with lock granted or deadlock detected, it would re-acquire the lock table's partition LWLock.

   The code episode is here:
   ```
/*
     * Re-acquire the lock table's partition lock.  We have to do this to hold
     * off cancel/die interrupts before we can mess with lockAwaited (else we
     * might have a missed or duplicated locallock update).
     */
    LWLockAcquire(partitionLock, LW_EXCLUSIVE);

    /*
     * We no longer want LockErrorCleanup to do anything.
     */
    lockAwaited = NULL;

    /*
     * If we got the lock, be sure to remember it in the locallock table.
     */
    if (MyProc->waitStatus == STATUS_OK)
        GrantAwaitedLock();

    /*
     * We don't have to do anything else, because the awaker did all the
     * necessary update of the lock table and MyProc.
     */
    return MyProc->waitStatus;
  ```
   Questions are:
   (1) The comment says that "we might have a missed or duplicated locallock update", in what cases would we hit this if without holding the LWLock?
   (2) The comment says "we have to do this to hold off cancel/die interrupts", then: why using LWLockAcquire instead of HOLD_INTERRUPTS directly?
   From the handler of SIGINT and SIGTERM, seems nothing serious would be processed here(especially LockWaitCancel), since ImmediateInterruptOK is false, and no CHECK_FOR_INTERRUPS is called before releasing this LWLock. Why should we hold off cancel/die interrupts here?
   (3) Before releasing this LWLock, the only share memory access is MyProc->waitStatus; since the process has been granted the lock or removed from the lock's waiting list because of deadlock, is it possible some other processes would access this field? if not, then why we need LWLock here? what does this lock protect?

* The second question is:
   The PROCLOCKTAG struct is like:
   ```
typedef struct PROCLOCKTAG
{
	/* NB: we assume this struct contains no padding! */
	LOCK	   *myLock;			/* link to per-lockable-object information */
	PGPROC	   *myProc;			/* link to PGPROC of owning backend */
} PROCLOCKTAG;
   ```
   The question is: why we can use pointer here in the struct, since the PROCLOCKTAG would reside in share memory, and the LOCK and PGPROC structs are also in share memory.

   Consider this case: one process wants to acquire a lock, so it builds a PROCLOCKTAG and inserts it into LockMethodProcLockHash using the pointer of a LOCK, which is the mapping from a LOCK struct in share memory to the local process; then if another process is iterating the LockMethodProcLockHash, and it has its own mapping from a LOCK struct in share memory to its own address space; because the address space of these two processes are independent, there is chance that their LOCK pointer is exactly same, while the LOCK objects referenced in the share memory are actually different, then this would lead to unexpected results.

   There is a comment saying that:
   >We can use pointers here because the PROCLOCKTAG need only be unique for the lifespan of the PROCLOCK, and it will never outlive the lock or the proc.
  
   Hmm, I don't understand what this comment means actually, and it cannot explain the above case obviously.

Apologize if I missed anything here, and really appreciate if someone can help me on these two questions. Thanks

**Comment by hlinnaka** [comment]
On 11/01/16 05:49, Kenan Yao wrote:
> Hi there,
>
> I have two questions regarding lock related code:
>
> * The first question is: in function ProcSleep, after the process has been waken up, either with lock granted or deadlock detected, it would re-acquire the lock table's partition LWLock.
>
>     The code episode is here:
>     ```
> /*
>       * Re-acquire the lock table's partition lock.  We have to do this to hold
>       * off cancel/die interrupts before we can mess with lockAwaited (else we
>       * might have a missed or duplicated locallock update).
>       */
>      LWLockAcquire(partitionLock, LW_EXCLUSIVE);
>
>      /*
>       * We no longer want LockErrorCleanup to do anything.
>       */
>      lockAwaited = NULL;
>
>      /*
>       * If we got the lock, be sure to remember it in the locallock table.
>       */
>      if (MyProc->waitStatus == STATUS_OK)
>          GrantAwaitedLock();
>
>      /*
>       * We don't have to do anything else, because the awaker did all the
>       * necessary update of the lock table and MyProc.
>       */
>      return MyProc->waitStatus;
>    ```
>     Questions are:
>     (1) The comment says that "we might have a missed or duplicated locallock update", in what cases would we hit this if without holding the LWLock?
>     (2) The comment says "we have to do this to hold off cancel/die interrupts", then: why using LWLockAcquire instead of HOLD_INTERRUPTS directly?
>     From the handler of SIGINT and SIGTERM, seems nothing serious would be processed here(especially LockWaitCancel), since ImmediateInterruptOK is false, and no CHECK_FOR_INTERRUPS is called before releasing this LWLock. Why should we hold off cancel/die interrupts here?

Hmm. Yeah, I don't really understand that either. Could be just 
paranoia, in case ImmediateInterruptOK is set, after all.

>     (3) Before releasing this LWLock, the only share memory access is MyProc->waitStatus; since the process has been granted the lock or removed from the lock's waiting list because of deadlock, is it possible some other processes would access this field? if not, then why we need LWLock here? what does this lock protect?

Note that the lock is still held at return, and it's up to the caller to 
release it. The caller might do more stuff that needs the lock. Looking 
at the only caller, though, it's only doing some sort of a sanity check 
on proclock->holdmask before releasing the lock.

If nothing else, it does make the API less surprising, when the lock 
that is held on entry, is still (or again) held at return...

> * The second question is:
>     The PROCLOCKTAG struct is like:
>     ```
> typedef struct PROCLOCKTAG
> {
> 	/* NB: we assume this struct contains no padding! */
> 	LOCK	   *myLock;			/* link to per-lockable-object information */
> 	PGPROC	   *myProc;			/* link to PGPROC of owning backend */
> } PROCLOCKTAG;
>     ```
>     The question is: why we can use pointer here in the struct, since the PROCLOCKTAG would reside in share memory, and the LOCK and PGPROC structs are also in share memory.
>
>     Consider this case: one process wants to acquire a lock, so it builds a PROCLOCKTAG and inserts it into LockMethodProcLockHash using the pointer of a LOCK, which is the mapping from a LOCK struct in share memory to the local process; then if another process is iterating the LockMethodProcLockHash, and it has its own mapping from a LOCK struct in share memory to its own address space; because the address space of these two processes are independent, there is chance that their LOCK pointer is exactly same, while the LOCK objects referenced in the share memory are actually different, then this would lead to unexpected results.
>
>     There is a comment saying that:
>     >We can use pointers here because the PROCLOCKTAG need only be unique for the lifespan of the PROCLOCK, and it will never outlive the lock or the proc.
>
>     Hmm, I don't understand what this comment means actually, and it cannot explain the above case obviously.

The shared memory segment is in fact always mapped to the same address 
in all processes. It's created by postmaster, and all the child 
processes inherit it at fork(). On Windows we use fork() + exec(), so we 
have to jump through some hoops to attach the shared memory segment to 
the same address in each process, and we've actually had some problems 
with that over the years thanks to some address space randomization 
features IIRC.

In earlier PostgreSQL version (8.2 included), there was the mechanism of 
ShmemBase and SHMEM_OFFSET, to support mapping it to different addresses 
in different processes. But it was never complete, some structs used 
direct pointers to shared memory even back then. In later PostgreSQL 
releases, we stopped pretending that we'd ever support that, and got rid 
of SHMEM_OFFSET.

- Heikki

**Comment by eurekaka** [comment]
Thanks Heikki, that helps a lot.
