### ISSUE TITLE
appendonly表增加增加字段必须设置default值问题

### ISSUE THREAD

**Issue by qzren1982** [greenplum-db/gpdb#2592]
Gp环境：4.3.11
appendonly表增加增加字段必须设置default值问题
如果一张大数据量的表。增加一个字段 会卡死，PG版本：8.2.15
1，新版本是否有改善或者有没有其他方法？

Translate it to English:
In GPDB 4.3.11, for Append Only table, if we add a new column, we must set a default value for the newly added column.
If the table is very large (I think he means if the table has a lot of rows), adding a new column will freeze or hang the database.

Does the newer version of GPDB resolve the issue? Or do you have any other approaches that we can use to walk around this issue?

**Comment by ashwinstar** [comment]
With translation it reads "Gp environment: 4.3.11
Appendonly table to increase the field must be set to increase the value of the problem
If a large amount of data on the table. Add a field to stuck, PG version: 8.2.15
1, whether the new version has improved or is there any other way?"

The question is not clear please can you provide more context and clarify. Also, if its for 4.3 which is commercial version and not open-source please channel the inquiry via Pivotal support instead.

**Comment by hsyuan** [comment]
Translate it to English:
In GPDB 4.3.11, for Append Only table, if we add a new column, we must set a default value for the newly added column.
If the table is very large (I think he means if the table has a lot of rows), adding a new column will freeze or hang the database.

Does the newer version of GPDB resolve the issue? Or do you have any other approaches that we can use to walk around this issue?

**Comment by hsyuan** [comment]
@qzren1982 Using append only column store is recommended.

**Comment by hsyuan** [comment]
Close this issue, since it is already answered.
If you have any questions, feel free to ask.

**Comment by qzren1982** [comment]
@hsyuan 
Thank you for your advice.
AOCS do you mean to use createas to recreate a new table with new default
 column?

**Comment by hsyuan** [comment]
No, for the current table, nothing we can do.

But for such kind a case, I would recommend you create AOCS table:
```sql
CREATE TABLE bar (a int, b text) 
    WITH (appendonly=true, orientation=column)
    DISTRIBUTED BY (a);
```
See here:
https://gpdb.docs.pivotal.io/43140/admin_guide/ddl/ddl-storage.html#topic39

**Comment by qzren1982** [comment]
from ： https://gpdb.docs.pivotal.io/43140/admin_guide/ddl/ddl-storage.html#topic39
i do not find  i needed，
i know for a big table in Oracle，perform a ddl operation。add a colum with a default value is very quickly！
The principle is that Oracle modifies only the data dictionary defined by the table instead of actually modifying the data in the table！！
