### ISSUE TITLE
ERROR:  external table gphdfs protocol command ended with error. sh: GPHOME/lib//hadoop/hadoop_env.sh: No such file or directory

### ISSUE THREAD

**Issue by huangpeide** [greenplum-db/gpdb#2610]
system:cdh5.9+jdk1.8+greenplum-db-4.3.14.0

set this:
gpconfig -c gp_hadoop_target_version -v "'hadoop2'"
gpconfig -c gp_hadoop_home -v "'/opt/cloudera/parcels/CDH/lib/hadoop'"

query error:
[SQL]SELECT * from qqcnt

[Err] ERROR:  external table gphdfs protocol command ended with error. sh: GPHOME/lib//hadoop/hadoop_env.sh: No such file or directory  (seg2 slice1 node2:40000 pid=4225)
DETAIL:  
Error: Could not find or load main class com.emc.greenplum.gpdb.hdfsconnector.HDFSReader
Command: source $GPHOME/lib//hadoop/hadoop_env.sh;java $GP_JAVA_OPT -classpath $CLASSPATH com.emc.greenplum.gpdb.hdfsconnector.HDFSReader $GP_SEGMENT_ID $GP_SEGMENT_COUNT TEXT cdh4.1-gnet-1.2.0.0 'gphdfs://node1:8020/user/hive/warehouse/ods.db/qqcnt' '000000002500044000000002500044000000002500044000000002500044000000002500044000000002500044000000002500044' 'id,qqnum,nick,age,gender,auth,qunnum,'
External table qqcnt, file gphdfs://node1:8020/user/hive/warehouse/ods.db/qqcnt

**Comment by huangpeide** [comment]
create external table qqcnt1 
(
		id	int,	
		qqnum	varchar(100),	
		nick	varchar(100),	
		age	int	,
		gender	int	,
		auth	int	,
		qunnum varchar(100)
) location ('gphdfs://node1:8020/user/hive/warehouse/ods.db/qqcnt/*') format 'TEXT' (DELIMITER E'\001');

**Comment by ivannovick** [comment]
@lij55  any idea?

**Comment by huangpeide** [comment]
any body help?

**Comment by hsyuan** [comment]
@yydzero Can unite team help?

**Comment by yydzero** [comment]
From the error message, looks like there is no below file: could you check whether it exist or not? This file will setup all the needed classpath for Java.

$GPHOME/lib//hadoop/hadoop_env.sh

@vVineet

**Comment by huangpeide** [comment]
![image](https://user-images.githubusercontent.com/7991283/27162956-df5d113e-51b6-11e7-8e15-91081b5b4fe9.png)
@yydzero

**Comment by huangpeide** [comment]
export JAVA_HOME=/usr/java/jdk1.8.0_111
export HADOOP_HOME=/opt/cloudera/parcels/CDH/lib/hadoop
#source /usr/local/greenplum-db/greenplum_path.sh

export GP_JAVA_OPT='-Xmx1000m -XX:+DisplayVMOutputToStderr'
export PATH=$JAVA_HOME/bin:$PATH
JAVA=$JAVA_HOME/bin/java
CLASSPATH="$GPHOME"/"$GP_HADOOP_CONN_JARDIR"/$GP_HADOOP_CONN_VERSION.jar
export HADOOP_COMMON_HOME="${HADOOP_HOME}"
CLASSPATH=${HADOOP_HOME}/hadoop/etc/hadoop:${HADOOP_HOME}/etc/hadoop:${HADOOP_HOME}/conf:${CLASSPATH}

# add libs to CLASSPATH
for f in $HADOOP_COMMON_HOME/*.jar; do
  CLASSPATH=${CLASSPATH}:$f;
done

if [ -d "$HADOOP_COMMON_HOME/lib" ]; then
for f in $HADOOP_COMMON_HOME/lib/*.jar; do
  CLASSPATH=${CLASSPATH}:$f;
done
fi

if [ -d "$HADOOP_COMMON_HOME/hadoop/lib" ]; then
for f in $HADOOP_COMMON_HOME/hadoop/lib/*.jar; do
  CLASSPATH=${CLASSPATH}:$f;
done
fi

if [ -d "$HADOOP_COMMON_HOME/hadoop" ]; then
for f in $HADOOP_COMMON_HOME/hadoop/*.jar; do
  CLASSPATH=${CLASSPATH}:$f;
done
fi

if [ -d "$HADOOP_COMMON_HOME/hadoop-hdfs" ]; then
for f in $HADOOP_COMMON_HOME/hadoop-hdfs/*.jar; do
  CLASSPATH=${CLASSPATH}:$f;
done
fi

if [ -d "$HADOOP_COMMON_HOME/hadoop-mapreduce" ]; then
for f in $HADOOP_COMMON_HOME/hadoop-mapreduce/*.jar; do
  CLASSPATH=${CLASSPATH}:$f;
done
fi

if [ -d "$HADOOP_COMMON_HOME/hadoop-yarn" ]; then
for f in $HADOOP_COMMON_HOME/hadoop-yarn/*.jar; do
  CLASSPATH=${CLASSPATH}:$f;
done
fi

if [ -d "$HADOOP_COMMON_HOME/lib/jsp-2.1" ]; then
for f in $HADOOP_COMMON_HOME/lib/jsp-2.1/*.jar; do
  CLASSPATH=${CLASSPATH}:$f;
done
fi

#for hadoop 2.0

#for hadoop 2.0
#added by Greenplum begin
for f in /opt/cloudera/parcels/CDH/jars/hadoop-*.jar;do
CLASSPATH=${CLASSPATH}:$f;
done

for f in /usr/local/greenplum-db/lib/hadoop/cdh4.1-*.jar;do
CLASSPATH=${CLASSPATH}:$f;
done
#added by Greenplum end

if [ -d "${HADOOP_HOME}/share/hadoop/common" ]; then
for f in ${HADOOP_HOME}/share/hadoop/common/*.jar; do
	  CLASSPATH=${CLASSPATH}:$f;
done
fi

if [ -d "${HADOOP_HOME}/share/hadoop/common/lib" ]; then
for f in ${HADOOP_HOME}/share/hadoop/common/lib/*.jar; do
	    CLASSPATH=${CLASSPATH}:$f;
done
fi

if [ -d "$HADOOP_HOME/share/hadoop/hdfs" ]; then
for f in $HADOOP_HOME/share/hadoop/hdfs/*.jar; do
	CLASSPATH=${CLASSPATH}:$f;
done
fi

if [ -d "$HADOOP_HOME/share/hadoop/mapreduce" ]; then
for f in $HADOOP_HOME/share/hadoop/mapreduce/*.jar; do
	CLASSPATH=${CLASSPATH}:$f;
done
fi

if [ -d "$HADOOP_HOME/share/hadoop/yarn" ]; then
for f in $HADOOP_HOME/share/hadoop/yarn/*.jar; do
	CLASSPATH=${CLASSPATH}:$f;
done
fi

if [ -d "$HADOOP_HOME/share/hadoop/httpfs/tomcat/lib" ]; then
for f in $HADOOP_HOME/share/hadoop/httpfs/tomcat/lib/*.jar; do
	  CLASSPATH=${CLASSPATH}:$f;
done
fi

#for hadoop 2.0 end

#added by Greenplum end

if [ -d "$HADOOP_COMMON_HOME/build/ivy/lib/Hadoop-Common/common" ]; then
for f in $HADOOP_COMMON_HOME/build/ivy/lib/Hadoop-Common/common/*.jar; do
  CLASSPATH=${CLASSPATH}:$f;
done
fi

if [ -d "$HADOOP_COMMON_HOME/build/ivy/lib/Hadoop-Hdfs/common" ]; then
for f in $HADOOP_COMMON_HOME/build/ivy/lib/Hadoop-Hdfs/common/*.jar; do
  CLASSPATH=${CLASSPATH}:$f;
done
fi

if [ -d "$HADOOP_COMMON_HOME/build/ivy/lib/Hadoop/common" ]; then
for f in $HADOOP_COMMON_HOME/build/ivy/lib/Hadoop/common/*.jar; do
  CLASSPATH=${CLASSPATH}:$f;
done
fi

# setup 'java.library.path' for native-hadoop code if necessary
JAVA_LIBRARY_PATH=''
if [ -d "${HADOOP_HOME}/build/native" -o -d "${HADOOP_HOME}/lib/native" ]; then
  JAVA_PLATFORM=`CLASSPATH=${CLASSPATH} ${JAVA} -Xmx32m ${HADOOP_JAVA_PLATFORM_OPTS} org.apache.hadoop.util.PlatformName | sed -e "s/ /_/g"`
  
  if [ -d "$HADOOP_HOME/build/native" ]; then
    JAVA_LIBRARY_PATH=${HADOOP_HOME}/build/native/${JAVA_PLATFORM}/lib
  fi
  
  if [ -d "${HADOOP_HOME}/lib/native" ]; then
    if [ "x$JAVA_LIBRARY_PATH" != "x" ]; then
      JAVA_LIBRARY_PATH=${JAVA_LIBRARY_PATH}:${HADOOP_HOME}/lib/native/${JAVA_PLATFORM}
    else
      JAVA_LIBRARY_PATH=${HADOOP_HOME}/lib/native/${JAVA_PLATFORM}
    fi
  fi
fi
export LD_LIBRARY_PATH="$JAVA_LIBRARY_PATH"
if [ "x$JAVA_LIBRARY_PATH" != "x" ]; then
  GP_JAVA_OPT="$GP_JAVA_OPT -Djava.library.path=$JAVA_LIBRARY_PATH"
fi  

export GP_JAVA_OPT=$GP_JAVA_OPT
export CLASSPATH=$CLASSPATH

**Comment by lij55** [comment]
Hi @huangpeide ,

This is known issue of 4.3.13 and 4.3.14. It will be fixed in 4.3.14.1. For GPDB5, it is OK.

**Comment by qzren1982** [comment]
hdp is not this problem
