### ISSUE TITLE
Dependencies not recorded properly for base types

### ISSUE THREAD

**Issue by khuddlefish** [greenplum-db/gpdb#2622]
Repro
```
CREATE FUNCTION base_fn_in(cstring) returns opaque as 'boolin' language internal;
CREATE FUNCTION base_fn_out(opaque) returns opaque as 'boolout' language internal;
CREATE TYPE base_type(input=base_fn_in, output=base_fn_out);

\df
                            List of functions
 Schema |     Name     | Result data type | Argument data types |  Type
--------+--------------+------------------+---------------------+--------
 public | base_fn_in  | base_type        | cstring             | normal
 public | base_fn_out | cstring          | base_type           | normal

DROP TYPE base_type;

\df
ERROR:  cache lookup failed for type 22241 (format_type.c:137)
```
When we first create the functions, they are not dependent on other objects. However, when we create base_type, the functions are modified to use the new type. Then, dropping the type first causes the functions to have a cache lookup error because they are missing a new dependency. It is possible to clean up the state if you run `DROP FUNCTION base_fn_out(base_type) CASCADE;` and then `DROP FUNCTION base_fn_in(cstring);`, but if you run `DROP TYPE base_type;` first, it is impossible to drop base_fn_out. Base types should make users run CASCADE to clean up dependencies in the other direction.

**Comment by khuddlefish** [comment]
Reported as a bug to pgsql-bugs

**Comment by hlinnaka** [comment]
Link to the pgsql-bugs discussion: https://www.postgresql.org/message-id/20170614232259.1424.82774%40wrigleys.postgresql.org

**Comment by hlinnaka** [comment]
Fixed in upstream by commit 30681c830d.

**Comment by d** [comment]
@hlinnaka are you, or anybody, working on porting that to Greenplum?

**Comment by hlinnaka** [comment]
On 18 June 2017 02:30:56 EEST, Jesse Zhang <notifications@github.com> wrote:
>@hlinnaka are you, or anybody, working on porting that to Greenplum?

Not me, at least.

- Heikki

**Comment by d** [comment]
Just realized this is a very old syntax, none of our internal tools dump out SQL like that, so it's probably a very low priority bug

**Comment by khuddlefish** [comment]
@d It is pretty low priority, but it is still a bug. Since we already have a fix available in Postgres, I think someone should port it to Greenplum soon. Otherwise we will definitely forget about it. @hlinnaka would you be willing to do it since you wrote the patch? Thanks for the fast response btw :)

**Comment by hlinnaka** [comment]
Meh, I can't be bothered. There are dozens of minor bugs like this that have been fixed in more recent versions of PostgreSQL, but we haven't backported. But feel free to cherry-pick it if you feel like it, I presume it will apply without much changes.
