### ISSUE TITLE
Use Semantic Versioning for ORCA version checking

### ISSUE THREAD

**Issue by d** [greenplum-db/gpdb#2638]
# This is a placeholder
As most of the work probably needs to happen on the ORCA side

## What challenge are you facing?
As a contributor to ORCA making a (source) backwards-compatible change, I should be able to bump the _minor_ version and be able to build gpdb without updating the gpdb tree. Today I'll be forced to choose between:
  1. Not bumping the version at all
  1. Bumping the patch version
  1. Bumping the minor version and come back to bump the minor version in [orca.m4](config/orca.m4)

This is a matter of taste, but I do believe strongly in adhering to [widely accepted semantics of versioning](http://semver.org/) (even loosely). Specifically, this (loosely, with nuance) means:

  1. If an ORCA improvement requires code change in Greenplum to _compile_ , a *major* version bump is needed, so that the unchanged version of Greenplum can abort at `configure` time
  1. If an ORCA change requires no code change in Greenplum to _compile_, then a *minor* or *patch* bump is permissible.

## Modest Proposals
- Check _major.minor_ compatibility in `configure`
- Or maybe ORCA can supply a simple version check (in the form of `orca-config` or `orca-version-greater`) to simplify this in GPDB

**Comment by cjcjameson** [comment]
Confirmed that is still the case... (config/orca.m4) is still setting up configure to check for specific minor versions.

**Comment by ashwinstar** [comment]
@vraghavan78 Was anything already done for this request or are there any plans to deal with it ? Just looking to see if need to continue tracking this or something that can be closed.
