### ISSUE TITLE
No protection against torn pages in bitmap index XLOG code

### ISSUE THREAD

**Issue by hlinnaka** [greenplum-db/gpdb#2650]
I just noticed that the all bitmap index WAL-logging code sets `XLogRecData.buffer` to InvalidBuffer. That means that there is no protection from torn pages, making bitmap indexes not very crash-safe.

**Comment by Eulerizeit** [comment]
Is that in the HEAP xlog code, the AO/AOCO xlog code or both?

-- Rob

**Comment by hlinnaka** [comment]
On 20 June 2017 22:51:27 EEST, Robert Eckhardt <notifications@github.com> wrote:
>Is that in the HEAP xlog code, the AO/AOCO xlog code or both?

Neither, it's the bitmap index code. Ie. if you do "CREATE INDEX ... USING bitmap;", on any kind of table. That index might get corrupted on an OS crash or power failure.

- Heikki

**Comment by Eulerizeit** [comment]
@hlinnaka Do we need to double check if this is fixed?

**Comment by hlinnaka** [comment]
This was fixed by PR #5482. I glanced quickly at the all the WAL-logging code in bitmap AM, and I think we're now covered.
