### ISSUE TITLE
Aggregation improve suggestion

### ISSUE THREAD

**Issue by zeromax007** [greenplum-db/gpdb#2671]
Create aggregate has PREFUNC to optimizing aggregate execution. But if aggregation used internal data type for performance， it can't be transmitted between segment and master.

It is recommended to add a FFUNC for segment, let us can convert to transmittable data type.

**Comment by hlinnaka** [comment]
PostgreSQL 9.6 added the concept of partial aggregates, with support functions to combine two aggregate states, and to serialize/deserialize aggregate state. Once we get there, we can also use those serialize/deserialize functions between the master and segments.
