### ISSUE TITLE
gpssh-exkeys get hostname of hosts specified by IP, and add a record for hostname to knowhosts file

### ISSUE THREAD

**Issue by silenceshell** [greenplum-db/gpdb#2697]
I pass a hostfile to `gpssh-exkeys`, like:

```
192.168.128.158
192.168.128.165
192.168.128.164
192.168.128.149
```

`gpssh-exkeys` will set full mesh ssh password-less for the hosts listed above, but I met a problem.
I also set hostnames in `/etc/hosts` for all hosts listed above.

```
192.168.128.158 m1.adb.g1.com
192.168.128.165 m2.adb.g1.com
192.168.128.164 s1.adb.g1.com
192.168.128.149 s2.adb.g1.com
```

If I `ssh IP`, like `ssh 192.168.128.149`, password-less function works fine. But if I `ssh hostname`, I got some warnings:

```
ssh s2.adb.g1.com
The authenticity of host 's2.adb.g1.com (192.168.128.149)' can't be established.
ECDSA key fingerprint is 38:3d:3c:7b:25:c2:f8:2c:a2:22:64:1c:18:f3:14:a6.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 's2.adb.g1.com' (ECDSA) to the list of known hosts.
Warning: the ECDSA host key for 's2.adb.g1.com' differs from the key for the IP address '192.168.128.149'
Offending key for IP in /home/gpadmin/.ssh/known_hosts:1
Are you sure you want to continue connecting (yes/no)? yes
Last login: Thu Jun 22 22:34:39 2017
```

I guess it is because gpssh-exkeys generated knownhosts record for 192.168.128.149 use RSA only , but ssh command in my os(centos 7.2.) use DSA default, so ssh client got different fingerprints and complained.

After ssh to s2.adb.g1.com, the knowhosts file will be added a new record of s2.adb.g1.com.

```
s2.adb.g1.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBGjajSm9J4RwWHKn96m1VJ0dpwH54zD7SGpGagmXa7g4Rh5vXolYUIZJ1QfNRZ14NccQVz3AzLzrfJ43H5IZWD4=
```

If I set both IP and hostname in hostfile, password-less function works fine for IP and hostname.

Is it a good idea to allow `gpssh-exkeys` to get hostname of hosts specified by IP, and add a record for hostname to knowhosts file? It is much more convenient.

**Comment by ivannovick** [comment]
@Nirali13 can you validate if this is still a problem?
