### ISSUE TITLE
"configure" is generating an error (./configure: line 11909: #include: command not found)

### ISSUE THREAD

**Issue by edespino** [greenplum-db/gpdb#2699]
I noticed the following `configure` error output referencing line 11909:

```
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
./configure: line 11909: #include: command not found
checking atomic.h usability... no
checking atomic.h presence... no
checking for atomic.h... no
checking crypt.h usability... no
checking crypt.h presence... no
```
It appears commit [204aba3](https://github.com/greenplum-db/gpdb/commit/204aba38b58a51f9ec89814598bac8a597196831#diff-3b3a6ec97232deb43dc14319a73872c1_) introduced an incorrect reference to `AC_INCLUDES_DEFAULT` on a line by itself.

**Comment by asimrp** [comment]
This is being addressed by PR https://github.com/greenplum-db/gpdb/pull/2659

**Comment by ashwinstar** [comment]
Since #2659 was pushed closing this issue.
