### ISSUE TITLE
make on CentOS 7 using --with-perl errors out

### ISSUE THREAD

**Issue by phoccer** [greenplum-db/gpdb#27]
I'm using the following configure on a CentOS 7 machine:

./configure --with-perl --with-python --enable-dtrace --enable-snmp --with-openssl --with-ldap --with-krb5 --prefix=/usr/local/gpdb

The configure runs without error or warning. When I attempt to run a make, it cranks away for a while then eventually errors out:

"/usr/share/perl5/ExtUtils/xsubpp": No file or directory

Running locate on my machine I find xsubpp in a different location

/usr/share/perl5/vendor_perl/ExtUtils/xsubpp

Setting up a symlink fixes the make error. 

ln -s /usr/share/perl5/vendor_perl/ExtUtils/xsubpp /usr/share/perl5/ExtUtils/xsubpp

**Comment by hlinnaka** [comment]
This was fixed back in 2011 in upstream, see discussion at http://www.postgresql.org/message-id/9B946296-A2EB-4B45-A190-153F06662F8B@kineticode.com. I couldn't figure out what the work-around mentioned in that thread was, so it seemed best to backpatch this fix. So I did. Thanks for the report!
