### ISSUE TITLE
About  ORCA version error during configure of gpdb

### ISSUE THREAD

**Issue by abekn** [greenplum-db/gpdb#2715]
When I executed  "configure" command for gpdb,  then I encountered following error.

*****
./configure --with-perl --with-python --with-libxml --prefix=/usr/local/gpdb
...
checking Checking ORCA version... configure: error: Your ORCA version is expected to be 2.34.XXX
*****

Just in case, I tried to use clone command with "-b" option and cmpiled.

*****
git clone -b v2.34.1 https://github.com/greenplum-db/gporca.git
# git branch
* v2.34.1
*****

Of  course, "git pull --ff-only" was also tried.
But , situation  does not change.

Is there any workaround?

**Comment by oarap** [comment]
Could you please provide more information about your environment and steps you followed while installing gporca and gpdb?

**Comment by hsyuan** [comment]
Where did you install orca?

**Comment by abekn** [comment]
OS : CentOS Linux release 7.3.1611

Afetr install "gp-xerces" ,  I tried to execute using the following steps .

-- installed gporca
cd /usr/local/src
git clone -b v2.34.0 https://github.com/greenplum-db/gporca.git
cd gporca
git checkout -b v2.34.0
mkdir build
cd build
cmake3 ../
make -j7
make install

Until this , there was no error.

-- installed gpdb
cd /usr/local/src
git clone https://github.com/greenplum-db/gpdb
cd gpdb
./configure --enable-orca --with-perl --with-python --with-libxml --prefix=/usr/local/gpdb
...
checking Checking ORCA version... configure: error: Your ORCA version is expected to be 2.34.XXX


Error happened.

**Comment by hsyuan** [comment]
Can you try adding `/usr/local` to `/etc/ld.so.conf.d` and run `ldconfig`?

**Comment by abekn** [comment]
Hi hsyuan

After adding "/usr/local/lib" and "/usr/local/lib64" to "/etc/ld.so.conf",  I re-executed "configure" command.
Then , I could execute "configure" without error.

Thank you very much.
