### ISSUE TITLE
why postgres use -z options to specify segment numer in the cluster

### ISSUE THREAD

**Issue by hli1992** [greenplum-db/gpdb#2716]
I have seen that postgres have -z options to start postmaster, like:
```
14026 ?        Ss     0:00 /home/hli/gpdb/bin/postgres -D /home/hli/gdata/gpseg-1 -p 6432 -b 1 -z 2 --silent-mode=true -i -M master -C -1 -x 0 -E
14027 ?        Ss     0:14  \_ postgres: port  6432, master logger process                                                                           
29487 ?        Ss     0:00  \_ postgres: port  6432, stats collector process                                                                         
29488 ?        Ss     0:12  \_ postgres: port  6432, writer process                                                                                  
29489 ?        Ss     0:01  \_ postgres: port  6432, checkpoint process                                                                              
29490 ?        S      0:00  \_ postgres: port  6432, seqserver process                                                                               
29491 ?        S      0:01  \_ postgres: port  6432, ftsprobe process                                                                                
29492 ?        S      0:03  \_ postgres: port  6432, sweeper process                                                                                 
29513 ?        tsl    0:00  \_ postgres: port  6432, hli postgres [local] con16 [local] cmd5 EXPLAIN
```
Can we count the segment number from catalog gp_segment_configuation rather than use -z options?

**Comment by funnyxj** [comment]
gp_segment_configuation on in master node, while segment can not get the segment number. Only master tell it

**Comment by hli1992** [comment]
The master node can pass segment number to segments like "SeqServer port" and "SeqServer host" ?
@funnyxj

**Comment by funnyxj** [comment]
yes

**Comment by hlinnaka** [comment]
-z stands for `gp_num_contents_in_cluster`. But it's not actually used anymore, the startup scripts use the longer `--gp_num_contents_in_cluster=X` option now (see commit d7e6e0ecac).

And why do we pass it on the command line? And the same for `--gp_dbid`? Good question. That's just the way it has been implemented, currently. The gpstart script reads the values from a file called `gp_dbid` (or at least the dbid, I'm not sure where the number of segments comes from), and passes them to postmaster on the command line. Could we get the value from somewhere else? Yeah, probably.

Actually, when I do GPDB development on my laptop, I don't use the normal gpMgmt scripts to initialize and start the cluster. I use my own little bash scripts, and in the scripts, I don't pass those values in the command line. Instead, they're put in the postgresql.conf files of each node when the cluster is initialized. Much less hassle.

There was some discussion on gpdb-dev a while ago on refactoring the startup scripts, see https://groups.google.com/a/greenplum.org/d/msg/gpdb-dev/7NWwUPr9jH8/s9nBOkKiGAAJ. The discussion died off with no concrete results, but IMHO if we're going to rewrite or refactor the gpMgmt scripts, we should adopt that approach, and write the correct dbid and gp_num_contents_in_cluster values in a file under the data directory, like gp_dbid. Teach 'postmaster` to read those values directly from there, without having to pass them on the command line.

Anyway, I don't think there's anything broken or TODO here as such, so closing this issue.
