### ISSUE TITLE
Can not compile gpdb

### ISSUE THREAD

**Issue by flochman** [greenplum-db/gpdb#2739]
I tried copile gpdb on debian stretch but was not succesfull because compiling error in gporca. I got error issue in github there.

When I tried compile gpdb withouth orca it gives me an error :

apr-1-config is required for gpfdist, unable  to find binary

but I have libarp1 installed.

I installed evryting what was written in README.debian

**Comment by hlinnaka** [comment]
`apr-1-config` is in the `libapr1-dev` package. Looks like that's missing from the list of packages README.debian. I'll go add it, thanks!

**Comment by hlinnaka** [comment]
I think you could also build without gpfdist, by passing the --disable-gpfdist option.

**Comment by flochman** [comment]
@hlinnaka 

Compilation on debian also needs libevent-dev and libxml2-dev. They are not listed in readme.debian

Please write these libs to readme.debian  for other users not confused.

**Comment by flochman** [comment]
@hlinnaka 

Also needed to add to readme.debian libperl-dev for compilation

**Comment by Eulerizeit** [comment]
It would be great if you could submit a PR updating the read me to include
what you needed to do to get it working.

-- Rob

**Comment by flochman** [comment]
@Eulerizeit 

Hi,

after installing libapr1-dev libevent-dev libxml2-dev and libperl-dev appart from readme.debian  I succesfully finished compilation.

So only these libraries need to be add to readme.debian. 

I needed these:

apt-get install -y gcc g++
apt-get install -y ccache
apt-get install -y libreadline-dev
apt-get install -y bison flex
apt-get install -y zlib1g-dev
apt-get install -y openssl libssl-dev
apt-get install -y libpam-dev
apt-get install -y libcurl4-dev
apt-get install -y libbz2-dev
apt-get install -y python-dev
apt-get install -y ssh
apt-get install -y libapr1-dev
apt-get install -y libevent-dev
apt-get install -y libxml2-dev
apt-get install -y libperl-dev

**Comment by flochman** [comment]
@Eulerizeit 

I successfuly compiled gpdb only without GPORCA.

 In GPORCA is compiling error which is not be solved installing libs.

**Comment by hlinnaka** [comment]
Ok, added those missing packages to README.debian. That still leaves the GPORCA issue, but at least the README is now up-to-date as far as it goes.
