### ISSUE TITLE
Docker instructions do not work with the latest master build

### ISSUE THREAD

**Issue by lavjain** [greenplum-db/gpdb#2749]
Development with Docker

We provide a docker image with all dependencies required to compile and test GPDB. You can view the dependency dockerfile at ./src/tools/docker/base/Dockerfile. The image is hosted on docker hub at pivotaldata/gpdb-devel. This docker image is currently under heavy development.

A quickstart guide to Docker can be found on the Pivotal Engineering Journal.

**Comment by lavjain** [comment]
make -j4 results in
```
make[2]: Leaving directory `/workspace/gpdb/src/backend/snowball'
make -C include all
make[2]: Entering directory `/workspace/gpdb/src/include'
(cd /workspace/gpdb/src/include/catalog/ && ./duplicate_oids)
Duplicate OIDS\n--------------\n5039
make[2]: *** [check_oids] Error 1
make[2]: Leaving directory `/workspace/gpdb/src/include'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/workspace/gpdb/src'
make: *** [all] Error 2
bash-4.1# exit
exit
```

**Comment by hsyuan** [comment]
It hasn't been maintained for a long time.
You can use this repo to run GPDB on docker: https://github.com/d/bug-free-fortnight

**Comment by xinzweb** [comment]
Shall we do something to fix it? I got different error, when I even try to do the `docker build .`

```
checking for unistd.h... yes
./configure: line 11909: #include: command not found
checking how to run the C++ preprocessor... g++ -E
checking gpos/_api.h usability... no
checking gpos/_api.h presence... no
checking for gpos/_api.h... no
configure: error: GPOS header files are required for Pivotal Query Optimizer (orca)
The command '/bin/sh -c ./configure --with-python --with-perl --enable-mapreduce --with-libxml --prefix=/usr/local/gpdb --disable-gpcloud' returned a non-zero code: 1
```

**Comment by brendanstephens** [comment]
A correction would be good -- the article is useful and well composed.
It should also provide some direction where to run the commands from.

The path used in `docker build -t pivotaldata/gpdb-devel -f ./docker/base/Dockerfile .` is invalid and attempting to generate the build from inside the gpdb folder will generate an error.

**Comment by ashwinstar** [comment]
Seems @lavjain resolved this by adding Dockerfile for compiling.
