### ISSUE TITLE
Indexes of sub-partitions won't be dropped when the INDEX of parent table is dropped

### ISSUE THREAD

**Issue by godouxm** [greenplum-db/gpdb#2757]
Indexes on sub-partitions won't be dropped when the index of parent table is dropped.  The two reasons I raise this issue are:

1. CREATE INDEX and DROP INDEX should be relative. 
2. For more convenience, it is much easier to drop hundreds to thousands sub-partition indexes in one time. 

Another small reason is that it may not be noticed there are two indexes on sub-partition after create-drop-create.

case 1:

1. create a partition table
2. create index on the table
3. drop the index
4. check the index on the sub-partition table, it's still there.

case 2:

1. create a partition table
2. create index on the table
3. drop the index
4. create the same index again
5. check index on the sub-partition table, it will be two index(s).

postgres=# create table t (id int, dt date) DISTRIBUTED BY (id)  PARTITION BY range (dt)
postgres-#  (START ('2017-06-01') END ('2017-06-30') EVERY (1),
postgres(#   DEFAULT PARTITION June);
NOTICE:  CREATE TABLE will create partition "t_1_prt_june" for table "t"
NOTICE:  CREATE TABLE will create partition "t_1_prt_2" for table "t"
NOTICE:  CREATE TABLE will create partition "t_1_prt_3" for table "t"
NOTICE:  CREATE TABLE will create partition "t_1_prt_4" for table "t"
NOTICE:  CREATE TABLE will create partition "t_1_prt_5" for table "t"
NOTICE:  CREATE TABLE will create partition "t_1_prt_6" for table "t"
NOTICE:  CREATE TABLE will create partition "t_1_prt_7" for table "t"
NOTICE:  CREATE TABLE will create partition "t_1_prt_8" for table "t"
NOTICE:  CREATE TABLE will create partition "t_1_prt_9" for table "t"
NOTICE:  CREATE TABLE will create partition "t_1_prt_10" for table "t"
NOTICE:  CREATE TABLE will create partition "t_1_prt_11" for table "t"
NOTICE:  CREATE TABLE will create partition "t_1_prt_12" for table "t"
NOTICE:  CREATE TABLE will create partition "t_1_prt_13" for table "t"
NOTICE:  CREATE TABLE will create partition "t_1_prt_14" for table "t"
NOTICE:  CREATE TABLE will create partition "t_1_prt_15" for table "t"
NOTICE:  CREATE TABLE will create partition "t_1_prt_16" for table "t"
NOTICE:  CREATE TABLE will create partition "t_1_prt_17" for table "t"
NOTICE:  CREATE TABLE will create partition "t_1_prt_18" for table "t"
NOTICE:  CREATE TABLE will create partition "t_1_prt_19" for table "t"
NOTICE:  CREATE TABLE will create partition "t_1_prt_20" for table "t"
NOTICE:  CREATE TABLE will create partition "t_1_prt_21" for table "t"
NOTICE:  CREATE TABLE will create partition "t_1_prt_22" for table "t"
NOTICE:  CREATE TABLE will create partition "t_1_prt_23" for table "t"
NOTICE:  CREATE TABLE will create partition "t_1_prt_24" for table "t"
NOTICE:  CREATE TABLE will create partition "t_1_prt_25" for table "t"
NOTICE:  CREATE TABLE will create partition "t_1_prt_26" for table "t"
NOTICE:  CREATE TABLE will create partition "t_1_prt_27" for table "t"
NOTICE:  CREATE TABLE will create partition "t_1_prt_28" for table "t"
NOTICE:  CREATE TABLE will create partition "t_1_prt_29" for table "t"
NOTICE:  CREATE TABLE will create partition "t_1_prt_30" for table "t"
CREATE TABLE
postgres=# 
postgres=# 
postgres=# create index t_id on t(id);
NOTICE:  building index for child partition "t_1_prt_june"
NOTICE:  building index for child partition "t_1_prt_2"
NOTICE:  building index for child partition "t_1_prt_3"
NOTICE:  building index for child partition "t_1_prt_4"
NOTICE:  building index for child partition "t_1_prt_5"
NOTICE:  building index for child partition "t_1_prt_6"
NOTICE:  building index for child partition "t_1_prt_7"
NOTICE:  building index for child partition "t_1_prt_8"
NOTICE:  building index for child partition "t_1_prt_9"
NOTICE:  building index for child partition "t_1_prt_10"
NOTICE:  building index for child partition "t_1_prt_11"
NOTICE:  building index for child partition "t_1_prt_12"
NOTICE:  building index for child partition "t_1_prt_13"
NOTICE:  building index for child partition "t_1_prt_14"
NOTICE:  building index for child partition "t_1_prt_15"
NOTICE:  building index for child partition "t_1_prt_16"
NOTICE:  building index for child partition "t_1_prt_17"
NOTICE:  building index for child partition "t_1_prt_18"
NOTICE:  building index for child partition "t_1_prt_19"
NOTICE:  building index for child partition "t_1_prt_20"
NOTICE:  building index for child partition "t_1_prt_21"
NOTICE:  building index for child partition "t_1_prt_22"
NOTICE:  building index for child partition "t_1_prt_23"
NOTICE:  building index for child partition "t_1_prt_24"
NOTICE:  building index for child partition "t_1_prt_25"
NOTICE:  building index for child partition "t_1_prt_26"
NOTICE:  building index for child partition "t_1_prt_27"
NOTICE:  building index for child partition "t_1_prt_28"
NOTICE:  building index for child partition "t_1_prt_29"
NOTICE:  building index for child partition "t_1_prt_30"
CREATE INDEX
postgres=# 
postgres=# \d t
       Table "public.t"
 Column |  Type   | Modifiers 
--------+---------+-----------
 id     | integer | 
 dt     | date    | 
Indexes:
    "t_id" btree (id)
Number of child tables: 30 (Use \d+ to list them.)
Distributed by: (id)
Partition by: (dt)

postgres=# \d t_1_prt_june
 Table "public.t_1_prt_june"
 Column |  Type   | Modifiers 
--------+---------+-----------
 id     | integer | 
 dt     | date    | 
Indexes:
    "t_id_1_prt_june" btree (id)
Inherits: t
Distributed by: (id)

postgres=# 
postgres=# 
postgres=# drop index t_id;
WARNING:  Only dropped the index "t_id"
HINT:  To drop other indexes on child partitions, drop each one explicitly.
DROP INDEX
postgres=# 
postgres=# \d t
       Table "public.t"
 Column |  Type   | Modifiers 
--------+---------+-----------
 id     | integer | 
 dt     | date    | 
Number of child tables: 30 (Use \d+ to list them.)
Distributed by: (id)
Partition by: (dt)

postgres=# \d t_1_prt_june
 Table "public.t_1_prt_june"
 Column |  Type   | Modifiers 
--------+---------+-----------
 id     | integer | 
 dt     | date    | 
Indexes:
    "t_id_1_prt_june" btree (id)
Inherits: t
Distributed by: (id)

postgres=# 
postgres=# 
postgres=# create index t_id on t(id);
NOTICE:  building index for child partition "t_1_prt_june"
NOTICE:  building index for child partition "t_1_prt_2"
NOTICE:  building index for child partition "t_1_prt_3"
NOTICE:  building index for child partition "t_1_prt_4"
NOTICE:  building index for child partition "t_1_prt_5"
NOTICE:  building index for child partition "t_1_prt_6"
NOTICE:  building index for child partition "t_1_prt_7"
NOTICE:  building index for child partition "t_1_prt_8"
NOTICE:  building index for child partition "t_1_prt_9"
NOTICE:  building index for child partition "t_1_prt_10"
NOTICE:  building index for child partition "t_1_prt_11"
NOTICE:  building index for child partition "t_1_prt_12"
NOTICE:  building index for child partition "t_1_prt_13"
NOTICE:  building index for child partition "t_1_prt_14"
NOTICE:  building index for child partition "t_1_prt_15"
NOTICE:  building index for child partition "t_1_prt_16"
NOTICE:  building index for child partition "t_1_prt_17"
NOTICE:  building index for child partition "t_1_prt_18"
NOTICE:  building index for child partition "t_1_prt_19"
NOTICE:  building index for child partition "t_1_prt_20"
NOTICE:  building index for child partition "t_1_prt_21"
NOTICE:  building index for child partition "t_1_prt_22"
NOTICE:  building index for child partition "t_1_prt_23"
NOTICE:  building index for child partition "t_1_prt_24"
NOTICE:  building index for child partition "t_1_prt_25"
NOTICE:  building index for child partition "t_1_prt_26"
NOTICE:  building index for child partition "t_1_prt_27"
NOTICE:  building index for child partition "t_1_prt_28"
NOTICE:  building index for child partition "t_1_prt_29"
NOTICE:  building index for child partition "t_1_prt_30"
CREATE INDEX
postgres=# 
postgres=# \d t
       Table "public.t"
 Column |  Type   | Modifiers 
--------+---------+-----------
 id     | integer | 
 dt     | date    | 
Indexes:
    "t_id" btree (id)
Number of child tables: 30 (Use \d+ to list them.)
Distributed by: (id)
Partition by: (dt)

postgres=# \d t_1_prt_june
 Table "public.t_1_prt_june"
 Column |  Type   | Modifiers 
--------+---------+-----------
 id     | integer | 
 dt     | date    | 
Indexes:
    "t_id_1_prt_june" btree (id)
    "t_id_1_prt_june1" btree (id)
Inherits: t
Distributed by: (id)

**Comment by hsyuan** [comment]
We have hint messages showing that:
```
WARNING: Only dropped the index "t_id"
HINT: To drop other indexes on child partitions, drop each one explicitly.
```
Next time when we create index again, it doesn't check the index existence for subpartition. 

@foyzur @vraghavan78 
This is the expected behavior, right?

**Comment by hsyuan** [comment]
@godouxm We will create story to address this issue. It should drop the leaf indexes when dropping index for root partition table. 
@vraghavan78 , do you agree?

**Comment by asimrp** [comment]
Non-leaf partitions have no data.  DROP INDEX dropping only a non-leaf index is not very helpful.  Therefore, I agree with @hsyuan's proposal.

**Comment by godouxm** [comment]
@hsyuan Thank you for the response. 

I've seen that messages actually.  I prefer that it should drop the leaf indexes since the user may not notice the indexes are still there.

Glad to hear that this will be fixed. Thank you. @asimrp @hsyuan

**Comment by berlin-ab** [comment]
@tvesely @kalensk Is this issue related to the work you've been doing recently?

**Comment by kalensk** [comment]
Yes, this should be fixed in our upcoming PR in which we introduce the INTERNAL_AUTO dependency.

**Comment by kalensk** [comment]
This should be fixed by PR https://github.com/greenplum-db/gpdb/pull/7047 once that gets merged.

**Comment by Eulerizeit** [comment]
@kalensk did you check? Can this be closed?

**Comment by dkrieger-pvtl** [comment]
> @kalensk did you check? Can this be closed?

Yes, #7047 fixes this.  We repeated the original reproduction steps and the reported issues are resolved(see below).  However, as noted in https://github.com/greenplum-db/gpdb/pull/6877#issuecomment-471430111, when we cascade indexes to children, we do not print out the Notice's such as `NOTICE:  CREATE TABLE will create partition "t_1_prt_june" for table "t"`.


```
psql (9.4.20)
Type "help" for help.

------------------Case 1 setup---------------

postgres=# create table t (id int, dt date) DISTRIBUTED BY (id) PARTITION BY range (dt) (START ('2017-06-01') END ('2017-06-30') EVERY (1),DEFAULT PARTITION June);
NOTICE:  CREATE TABLE will create partition "t_1_prt_june" for table "t"
NOTICE:  CREATE TABLE will create partition "t_1_prt_2" for table "t"
NOTICE:  CREATE TABLE will create partition "t_1_prt_3" for table "t"
NOTICE:  CREATE TABLE will create partition "t_1_prt_4" for table "t"
NOTICE:  CREATE TABLE will create partition "t_1_prt_5" for table "t"
NOTICE:  CREATE TABLE will create partition "t_1_prt_6" for table "t"
NOTICE:  CREATE TABLE will create partition "t_1_prt_7" for table "t"
NOTICE:  CREATE TABLE will create partition "t_1_prt_8" for table "t"
NOTICE:  CREATE TABLE will create partition "t_1_prt_9" for table "t"
NOTICE:  CREATE TABLE will create partition "t_1_prt_10" for table "t"
NOTICE:  CREATE TABLE will create partition "t_1_prt_11" for table "t"
NOTICE:  CREATE TABLE will create partition "t_1_prt_12" for table "t"
NOTICE:  CREATE TABLE will create partition "t_1_prt_13" for table "t"
NOTICE:  CREATE TABLE will create partition "t_1_prt_14" for table "t"
NOTICE:  CREATE TABLE will create partition "t_1_prt_15" for table "t"
NOTICE:  CREATE TABLE will create partition "t_1_prt_16" for table "t"
NOTICE:  CREATE TABLE will create partition "t_1_prt_17" for table "t"
NOTICE:  CREATE TABLE will create partition "t_1_prt_18" for table "t"
NOTICE:  CREATE TABLE will create partition "t_1_prt_19" for table "t"
NOTICE:  CREATE TABLE will create partition "t_1_prt_20" for table "t"
NOTICE:  CREATE TABLE will create partition "t_1_prt_21" for table "t"
NOTICE:  CREATE TABLE will create partition "t_1_prt_22" for table "t"
NOTICE:  CREATE TABLE will create partition "t_1_prt_23" for table "t"
NOTICE:  CREATE TABLE will create partition "t_1_prt_24" for table "t"
NOTICE:  CREATE TABLE will create partition "t_1_prt_25" for table "t"
NOTICE:  CREATE TABLE will create partition "t_1_prt_26" for table "t"
NOTICE:  CREATE TABLE will create partition "t_1_prt_27" for table "t"
NOTICE:  CREATE TABLE will create partition "t_1_prt_28" for table "t"
NOTICE:  CREATE TABLE will create partition "t_1_prt_29" for table "t"
NOTICE:  CREATE TABLE will create partition "t_1_prt_30" for table "t"
CREATE TABLE
postgres=#  create index t_id on t(id);
CREATE INDEX
postgres=# \d t
       Table "public.t"
 Column |  Type   | Modifiers
--------+---------+-----------
 id     | integer |
 dt     | date    |
Indexes:
    "t_id" btree (id)
Number of child tables: 30 (Use \d+ to list them.)
Distributed by: (id)
Partition by: (dt)

postgres=# \d t_1_prt_june
 Table "public.t_1_prt_june"
 Column |  Type   | Modifiers
--------+---------+-----------
 id     | integer |
 dt     | date    |
Indexes:
    "t_1_prt_june_id_idx" btree (id)
Inherits: t
Distributed by: (id)

------------------Case 1: drop of index cascades to child partitions---------------

postgres=# drop index t_id;
DROP INDEX
postgres=#  \d t
       Table "public.t"
 Column |  Type   | Modifiers
--------+---------+-----------
 id     | integer |
 dt     | date    |
Number of child tables: 30 (Use \d+ to list them.)
Distributed by: (id)
Partition by: (dt)

postgres=# \d t_1_prt_june
 Table "public.t_1_prt_june"
 Column |  Type   | Modifiers
--------+---------+-----------
 id     | integer |
 dt     | date    |
Inherits: t
Distributed by: (id)

------------------Case 2: no state left from Case 1---------------
postgres=# create index t_id on t(id);
CREATE INDEX
postgres=#  \d t
       Table "public.t"
 Column |  Type   | Modifiers
--------+---------+-----------
 id     | integer |
 dt     | date    |
Indexes:
    "t_id" btree (id)
Number of child tables: 30 (Use \d+ to list them.)
Distributed by: (id)
Partition by: (dt)

postgres=# \d t_1_prt_june
 Table "public.t_1_prt_june"
 Column |  Type   | Modifiers
--------+---------+-----------
 id     | integer |
 dt     | date    |
Indexes:
    "t_1_prt_june_id_idx" btree (id)
Inherits: t
Distributed by: (id)
```
