### ISSUE TITLE
The size of the database file fluctuates up and down

### ISSUE THREAD

**Issue by huangwei04** [greenplum-db/gpdb#2772]
When I import data with gpload, I find that the size of the database file is not always increasing, and several times the size became smaller. Who can tell me why? What has GP done during this period?
I use the commond"du -sh /data/primary/gpseg0/base/17283" to check the database file size every 2 seconds.
the sizeof 16391.6 change，like this: 
508M ->764M->895M->664M
888M->1.2G->940M
log:
32M	16391.6
32M	16391.6
64M	16391.6
64M	16391.6
128M	16391.6
128M	16391.6
128M	16391.6
128M	16391.6
256M	16391.6
256M	16391.6
256M	16391.6
256M	16391.6
256M	16391.6
256M	16391.6
256M	16391.6
256M	16391.6
256M	16391.6
256M	16391.6
256M	16391.6
256M	16391.6
284M	16391.6
316M	16391.6
316M	16391.6
316M	16391.6
316M	16391.6
380M	16391.6
380M	16391.6
380M	16391.6
380M	16391.6
380M	16391.6
508M	16391.6
508M	16391.6
508M	16391.6
508M	16391.6
508M	16391.6
508M	16391.6
508M	16391.6
508M	16391.6
508M	16391.6
508M	16391.6
508M	16391.6
764M	16391.6
764M	16391.6
764M	16391.6
764M	16391.6
764M	16391.6
764M	16391.6
764M	16391.6
764M	16391.6
764M	16391.6
764M	16391.6
764M	16391.6
895M	16391.6
664M	16391.6
664M	16391.6
696M	16391.6
696M	16391.6
760M	16391.6
760M	16391.6
760M	16391.6
760M	16391.6
760M	16391.6
888M	16391.6
888M	16391.6
888M	16391.6
888M	16391.6
888M	16391.6
888M	16391.6
888M	16391.6
888M	16391.6
888M	16391.6
888M	16391.6
888M	16391.6
888M	16391.6
888M	16391.6
1.2G	16391.6
1.2G	16391.6
1.2G	16391.6
1.2G	16391.6
1.2G	16391.6
1.2G	16391.6
1.2G	16391.6
940M	16391.6
940M	16391.6
940M	16391.6

**Comment by hsyuan** [comment]
@asimrp 
I think this is due to checkpointing, right?

**Comment by funnyxj** [comment]
Appendonly table ?

**Comment by asimrp** [comment]
This looks like an appendonly table because the size of a relfile in heap is limited to 1G.

If a appendonly segment file contains data inserted by an aborted transaction at the end of it, vacuum will truncate it.  This is the only case where size on disk of an appendonly segment file can do down.

@huangwei04 can you please confirm if `gpload` encountered failures during your experiment that might have caused insert transactions to be aborted?

If no, @ashwinstar and I feel that something might have gone wrong during the measurement.

@hsyuan This is not due to WAL because the `du` command is run with a specific database directory as argument.  WAL is not maintained in a database specific directory.  In this case, it should be kept at `gpseg0/pg_xlog/`.

**Comment by huangwei04** [comment]
@funnyxj Not a Appendonly table.the create table sql:
create table t_call_bak
(
	id bigint,
	number text,
	name text,
	content1 text,
	content2 text,
	content3 text,
	content4 text,
	content5 text,
	content6 text,
	updatetime text	
)distributed by (id);

@asimrp  Gpload is successful every time. 
log:
[gpadmin@localhost hw]$ gpload -f myload.sh 
2017-07-14 14:37:47|INFO|gpload session started 2017-07-14 14:37:47
2017-07-14 14:37:47|INFO|setting schema 'public' for table 't_call_bak'
2017-07-14 14:37:47|INFO|started gpfdist -p 8081 -P 8082 -f "/home/hw/data/data*" -t 30
2017-07-14 14:42:15|INFO|running time: 267.75 seconds
2017-07-14 14:42:15|INFO|rows Inserted          = 51298843
2017-07-14 14:42:15|INFO|rows Updated           = 0
2017-07-14 14:42:15|INFO|data formatting errors = 0
2017-07-14 14:42:15|INFO|gpload succeeded

**Comment by huangwei04** [comment]
@hsyuan 谢谢关注哈。

**Comment by Eulerizeit** [comment]
Can you please provide us with any additional information such as the
version, operating system, etc.

Rob

**Comment by huangwei04** [comment]
@robertmu @Eulerizeit 
This is a simple performance test for gpload. When the read and write rate of the hard disk is limited, the size of the database files is larger than the actual size, resulting in more time spent.
1、gp version:
20170717:19:42:22:038352 gpstate:localhost:gpadmin-[INFO]:-local Greenplum Version: 'postgres (Greenplum Database) 5.0.0-alpha build dev'
20170717:19:42:22:038352 gpstate:localhost:gpadmin-[INFO]:-master Greenplum Version: 'PostgreSQL  (Greenplum Database 5.0.0-alpha build dev) on x86_64-pc-linux-gnu, compiled by GCC gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-4) compiled on Jul 17 2016 00:19:47 (with assert checking)'

2、operating system:
 Red Hat Enterprise Linux Server release 6.5 (Santiago)

3、The configuration file is default

4、
./configure --prefix=/home/greenplum --with-gssapi --with-pgport=5432 --with-libedit-preferred --with-perl --with-python --with-openssl --with-pam --with-krb5 --with-ldap --with-libxml --enable-cassert --enable-debug --enable-testutils --enable-debugbreak --enable-depend

5、The file system of the disk is XFS
/dev/vdb /data xfs rw 0 0
/dev/vdb                    1.0T   34G  991G   4% /data
