### ISSUE TITLE
Key features as we lock in the 5.0 release with betas

### ISSUE THREAD

**Issue by cjcjameson** [greenplum-db/gpdb#2784]
Just keeping track of features that jump out as major improvements for users, worthy of highlighting in the upcoming release and getting any final beta feedback on.  **Feel Free to Edit my Post!**

- [ ] Faster analyze
- [ ] Default [ORCA query optimizer](https://github.com/greenplum-db/gporca) on + ORCA improvements
- [ ] Recursive common table expressions (not yet, still in private branch)
- [ ] Improved aggregate queries
- [ ] Improved performance on nested queries
- [ ] Improved dynamic partition elimination with planner
- [ ] Improved executor performance by eliminating alien nodes
- [ ] Heap checksums (as of July 2017 still in flight)
- [ ] Lazy XID
- [ ] JSON
- [ ] COPY Local

In some sense, this issue might a working draft for what hopefully might become [release notes with the open source release](https://github.com/greenplum-db/gpdb/releases)

**Comment by hsyuan** [comment]
@vraghavan78 will Recursive CTE go into beta?
