### ISSUE TITLE
Refactor analyze.c to merge with upstream changes from PGSQL

### ISSUE THREAD

**Issue by xinzweb** [greenplum-db/gpdb#279]
Current analyze.c in GPDB is different from PostgreSQL version.

Here are few differences observed:

PGSQL has:

    acquire_inherited_sample_rows 
    acquire_sample_rows
    analyze_rel
    compare_mcvs
    compare_rows
    compare_scalars
    compute_distinct_stats
    compute_index_stats
    compute_scalar_stats
    compute_trivial_stats
    ...

Where the GPDB has:

    analyzeComputeAttributeStatistics
    analyzeComputeAverageWidth
    analyzeComputeHistogram
    ...
    analyzeNullCount
    ...
    gp_statistics_estimate_reltuples_relpages_ao_cs
    ...
    spiCallback_getEachResultComplumnAsArray
    ...

This issue is created to make the analyze.c matching with upstream.

**Comment by hsyuan** [comment]
Should we close this issue? Since @hlinnaka already merged with upstream.

**Comment by hlinnaka** [comment]
Yeah, I think so. closed.
