### ISSUE TITLE
Resource Queue usage reporting

### ISSUE THREAD

**Issue by srinivasmattapalli** [greenplum-db/gpdb#2798]
In beta.3 release, Resource Queue usage information is not getting populated in gp_toolkiot.gp_resqueue_status, gp_rsq_activity views. "stats_queue_level" is turned on.

In 5.0-alpha release, we have seen the issue only with 3rd party ODBC ( https://github.com/greenplum-db/gpdb/issues/2308). 

Is there any other package/views we can use to identify how many sessions, memory in use, sessions waiting for RQ related information.

**Comment by ivannovick** [comment]
@gaos1 can you have a look at this?

**Comment by pengzhout** [comment]
I build the latest gpdb and find no view to show the current memory usage in a resource queue, 
but gp_toolkit.gp_resq_activity can show the waiting status of a session and how many sessions in a resource queue.
```
gpadmin=# select * from gp_toolkit.gp_resq_activity;
 resqprocpid | resqrole | resqoid | resqname |           resqstart           | resqstatus
-------------+----------+---------+----------+-------------------------------+------------
       44896 | gpadmin  |   73029 | q1       | 2017-07-18 20:09:38.984653-04 | running
       44868 | gpadmin  |   73029 | q1       | 2017-07-18 20:09:46.511448-04 | waiting
(2 rows)

gpadmin=# select resqname, count(*) as procs from gp_toolkit.gp_resq_activity group by resqname;
 resqname | procs
----------+-------
 q1       |     2
(1 row)
```

FYI, memory usage can be displayed in our upcoming feature - resource group.

**Comment by pengzhout** [comment]
To be correct, resource queue do have memory usage for a resource queue named 'rsqmemoryvalue' in gp_toolkit.gp_resqueue_status.

```
gpadmin=# select rsqname, rsqmemorylimit, rsqmemoryvalue from gp_toolkit.gp_resqueue_status ;
  rsqname   | rsqmemorylimit | rsqmemoryvalue
------------+----------------+----------------
 q1         |    1.04858e+09 |    3.49525e+08
 pg_default |             -1 |              0
(2 rows)
```

**Comment by srinivasmattapalli** [comment]
Did you get the latest build  from github and compiled from source or using the last released build build.3 on GitHub ? Any parameters to be configured for RQ information to show up ?

**Comment by pengzhout** [comment]
I built it from the latest github source code and no parameters configured for RQ. Can you attach your output of gp_toolkit.gp_resqueue_status and gp_toolkit.gp_resq_activity? and make sure there are queries running within resource queue.

**Comment by srinivasmattapalli** [comment]
Thanks, pengzhout.

Yes, Resource Queue is working with beta.3. I was running smaller length queries and expecting each connections to be reported in gp_toolkit.gp_resqueue_status. With queries taking longer time, I can see they are getting reported in both tables. Thanks.
