### ISSUE TITLE
some wrong with 'contains_nonconstant_walker'

### ISSUE THREAD

**Issue by liruto** [greenplum-db/gpdb#285]
Supposed the first argument is given a VAR node,  'contains_nonconstant_walker' would return FALSE. It's obviously wrong that VAR doesn't contain anything non-constant,isn't it?

**Comment by hlinnaka** [comment]
On 20/01/16 12:35, liruto wrote:
> Supposed the first argument is given a VAR node,
> 'contains_nonconstant_walker' would return FALSE It's obviously wrong
> that VAR doesn't contain anything non-constant,isn't it?

Hmm, I think you're right. The saving grace is that the function is used 
only in one place, to test if an INSERT .. VALUES() contains anything 
but constants. I believe there can't be any Vars in the list in that 
context. It would still be prudent to check, IMO.

Also, why does the walker call contain_volatile_functions() on every 
node it traverses? That's a waste of time, as 
contain_volatile_functions() recurses; it'd be enough to call it once at 
the root node.

Poking around that case, I bumped up into this:

create table pt (i int, j int, k int) distributed by (i) partition by 
range(k)
(start(1) end(10) every(2));
alter table pt_1_prt_2 set distributed randomly;
insert into pt values (1, 1, random());

psql:/tmp/pt-const-bug.sql:4: FATAL:  Unexpected internal error 
(cdbmutate.c:564)
DETAIL:  FailedAssertion("!(((((Node*)(tle->expr))->type) == T_Const))", 
File: "cdbmutate.c", Line: 564)
HINT:  Process 20240 will wait for gp_debug_linger=120 seconds before 
termination.
Note that its locks and other resources will not be released until then.
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.

I'm not sure what, but there's something wrong there..

- Heikki

**Comment by hlinnaka** [comment]
Fixed, by PR #2972. Thanks for the report!
