### ISSUE TITLE
GpPersistent_IsPersistentRelation OID's should be marked in the catalog to be visible to the users

### ISSUE THREAD

**Issue by davecramer** [greenplum-db/gpdb#2856]
https://github.com/greenplum-db/gpdb/blob/a0db527da23d4c78f423346ccde483e9d79b8696/src/include/catalog/gp_persistent.h#L436

Having these special OID's only visible in the code makes it difficult for users to script around the fact that these are not participating in MVCC, or vacuuming. 

Either add a column in pg_class or add a table linked to pg_class which can be queried by scripts

**Comment by Eulerizeit** [comment]
@asimrp @ashwinstar

**Comment by asimrp** [comment]
All persistent tables are recorded as tables in `pg_class`.  Is this not sufficient?
```
postgres=# select oid, * from pg_class where relname like 'gp_persistent%';
 oid  |            relname            | relnamespace | reltype | relowner | relam | relfilenode | reltablespace | relpages | reltuples | reltoastrelid | reltoastidxid | relhasindex | relisshared | relkind | relstorage | relnatts | relchecks | reltriggers | relukeys | relfkeys | relrefs | relhasoids | relhaspkey | relhasrules | relhassubclass | relfrozenxid |    relacl     | reloptions 
------+-------------------------------+--------------+---------+----------+-------+-------------+---------------+----------+-----------+---------------+---------------+-------------+-------------+---------+------------+----------+-----------+-------------+----------+----------+---------+------------+------------+-------------+----------------+--------------+---------------+------------
 5090 | gp_persistent_relation_node   |           11 |    6990 |       10 |     0 |        5090 |          1664 |        1 |       257 |             0 |             0 | f           | t           | r       | h          |       18 |         0 |           0 |        0 |        0 |       0 | f          | f          | f           | f              |          678 | {=r/apraveen} | 
 5091 | gp_persistent_database_node   |           11 |    6991 |       10 |     0 |        5091 |          1664 |        1 |         1 |             0 |             0 | f           | t           | r       | h          |        8 |         0 |           0 |        0 |        0 |       0 | f          | f          | f           | f              |          678 | {=r/apraveen} | 
 5092 | gp_persistent_tablespace_node |           11 |    6992 |       10 |     0 |        5092 |          1664 |        1 |         0 |             0 |             0 | f           | t           | r       | h          |        8 |         0 |           0 |        0 |        0 |       0 | f          | f          | f           | f              |          678 | {=r/apraveen} | 
 5093 | gp_persistent_filespace_node  |           11 |    6993 |       10 |     0 |        5093 |          1664 |        1 |         0 |             0 |             0 | f           | t           | r       | h          |       11 |         0 |           0 |        0 |        0 |       0 | f          | f          | f           | f              |          678 | {=r/apraveen} | 
(4 rows)
```

**Comment by davecramer** [comment]
Well it does leave out one table notably: GpGlobalSequenceRelationId

How do I know that these are not vacuumed from pg_class ?



Dave Cramer

**Comment by ashwinstar** [comment]
On Wed, Aug 2, 2017 at 10:27 AM, Dave Cramer <notifications@github.com>
wrote:

> Well it does leave out one table notably: GpGlobalSequenceRelationId
>
> How do I know that these are not vacuumed from pg_class ?
>

Would like to know the need for knowing the same ?

**Comment by davecramer** [comment]
So if you are monitoring freeze_age using age() and since the frozenxid of
the mentioned tables never changes as the current xid cycles through the
age will be > SOME_ARBITRARY_THRESHOLD for some time and then magically
disappear.


Dave Cramer

**Comment by ashwinstar** [comment]
On Wed, Aug 2, 2017 at 10:34 AM, Dave Cramer <notifications@github.com>
wrote:

> So if you are monitoring freeze_age using age() and since the frozenxid of
> the mentioned tables never changes as the current xid cycles through the
> age will be > SOME_ARBITRARY_THRESHOLD for some time and then magically
> disappear.
>

Thanks Dave, Get the context for the original question, I feel the way to
solve it is not by exposing persistent tables in catalog and user have to
exclude it from age. Instead recording relfrozenxid for those tables
as InvalidTransactionId similar to Indexes. I think its not just persistent
tables but same needs to be done for AO/CO tables as well. Will have PR for
it soon, let me know if that meets the needs.

**Comment by davecramer** [comment]
On 8 August 2017 at 16:28, Ashwin Agrawal <notifications@github.com> wrote:

> On Wed, Aug 2, 2017 at 10:34 AM, Dave Cramer <notifications@github.com>
> wrote:
>
> > So if you are monitoring freeze_age using age() and since the frozenxid
> of
> > the mentioned tables never changes as the current xid cycles through the
> > age will be > SOME_ARBITRARY_THRESHOLD for some time and then magically
> > disappear.
> >
>
> Thanks Dave, Get the context for the original question, I feel the way to
> solve it is not by exposing persistent tables in catalog and user have to
> exclude it from age. Instead recording relfrozenxid for those tables
> as InvalidTransactionId similar to Indexes. I think its not just persistent
> tables but same needs to be done for AO/CO tables as well. Will have PR for
> it soon, let me know if that meets the needs.
>
> +1

Thanks!


Dave Cramer
