### ISSUE TITLE
centos vagrant fails during configure

### ISSUE THREAD

**Issue by davecramer** [greenplum-db/gpdb#2859]
vagrant up gpdb or gpdb_without_orca

configure --prefix=/usr/local/gpdb

fails with
==> gpdb_without_gporca: ./configure: line 11942: #include: command not found

https://github.com/greenplum-db/gpdb/blob/master/configure#L11942

**Comment by danielgustafsson** [comment]
If you apply the patch in https://github.com/greenplum-db/gpdb/pull/2659, does that make it work?

**Comment by davecramer** [comment]
@danielgustafsson sadly, no. But at least I no longer have the #include error command not found.

Thanks!
