### ISSUE TITLE
Assertion failure from shareinput_walker when gp_cte_sharing is ON

### ISSUE THREAD

**Issue by gcaragea** [greenplum-db/gpdb#287]
I'm hitting an assertion in the planner when running the following repro on latest master
```
create table t (c int);
insert into t values (2);
set gp_cte_sharing=on;

explain 
with cte0 (e) as (values (0), (1)) 
select c, count(distinct d) disc_d
from (
    select c, d
    from (
      select 
        case 
          when t.c in (select e from cte0) then 'a'
          when t.c not in (select e from cte0) then 'b'
        end as d,
        c
      from t, cte0
    ) A 
    group by c, d
) B
group by c;

FATAL:  Unexpected internal error (cdbmutate.c:2082)
DETAIL:  FailedAssertion("!(((void *)0) != plan_slicemark.plan)", File: "cdbmutate.c", Line: 2082)
HINT:  Process 5632 will wait for gp_debug_linger=120 seconds before termination.
```

Stack trace on the QD process is: 
```
(lldb) bt
* thread #1: tid = 0xdc51, 0x939ebace libsystem_kernel.dylib`__select + 10, queue = 'com.apple.main-thread', stop reason = signal SIGSTOP
  * frame #0: 0x939ebace libsystem_kernel.dylib`__select + 10
    frame #1: 0x0087921b postgres`pg_usleep(microsec=30000000) + 126 at pgsleep.c:43
    frame #2: 0x0063d418 postgres`elog_debug_linger(edata=0x00b7ba20) + 370 at elog.c:4088
    frame #3: 0x0063599b postgres`errfinish(dummy=0) + 383 at elog.c:602
    frame #4: 0x0063373c postgres`ExceptionalCondition(conditionName=0x00a9ec80, errorType=0x00a9dbac, fileName=0x00a9dba0, lineNumber=2082) + 272 at assert.c:48
    frame #5: 0x00773775 postgres`shareinput_mutator_xslice_1(node=0x7d9e6c2c, ctxt=0x7d9b3414, fPop='\0') + 405 at cdbmutate.c:2082
    frame #6: 0x00772bc5 postgres`shareinput_walker(f=0x007735e0, node=0x7d9e6c2c, ctxt=0x7d9b3414) + 161 at cdbmutate.c:1790
    frame #7: 0x00772ee9 postgres`shareinput_walker(f=0x007735e0, node=0x7d9e6a18, ctxt=0x7d9b3414) + 965 at cdbmutate.c:1866
    frame #8: 0x00772ee9 postgres`shareinput_walker(f=0x007735e0, node=0x7d9e6814, ctxt=0x7d9b3414) + 965 at cdbmutate.c:1866
    frame #9: 0x00772d8d postgres`shareinput_walker(f=0x007735e0, node=0x7d9e4eec, ctxt=0x7d9b3414) + 617 at cdbmutate.c:1832
    frame #10: 0x00772ee9 postgres`shareinput_walker(f=0x007735e0, node=0x7d9e4c2c, ctxt=0x7d9b3414) + 965 at cdbmutate.c:1866
    frame #11: 0x00772ee9 postgres`shareinput_walker(f=0x007735e0, node=0x7d9e494c, ctxt=0x7d9b3414) + 965 at cdbmutate.c:1866
    frame #12: 0x00772ee9 postgres`shareinput_walker(f=0x007735e0, node=0x7d9e45e0, ctxt=0x7d9b3414) + 965 at cdbmutate.c:1866
    frame #13: 0x00772ee9 postgres`shareinput_walker(f=0x007735e0, node=0x7d9e6ed0, ctxt=0x7d9b3414) + 965 at cdbmutate.c:1866
    frame #14: 0x00773de1 postgres`apply_shareinput_xslice(plan=0x7d9e6ed0, glob=0x7d9b33ec) + 144 at cdbmutate.c:2271
    frame #15: 0x00459db5 postgres`standard_planner(parse=0x7d9c562c, cursorOptions=0, boundParams=0x00000000) + 1094 at planner.c:452
    frame #16: 0x00459893 postgres`planner(parse=0x7d9774c8, cursorOptions=0, boundParams=0x00000000) + 740 at planner.c:293
    frame #17: 0x005222dc postgres`pg_plan_query(querytree=0x7d9774c8, boundParams=0x00000000) + 79 at postgres.c:811
    frame #18: 0x0029bf15 postgres`ExplainOneQuery(query=0x7d9774c8, stmt=0x7d99e9b8, queryString=0x7c1cd82c, params=0x00000000, tstate=0x7d9b3000) + 148 at explain.c:320
    frame #19: 0x0029bb14 postgres`ExplainQuery(stmt=0x7d99e9b8, queryString=0x7c1cd82c, params=0x00000000, dest=0x7d99d7a0) + 373 at explain.c:180
    frame #20: 0x00531a8d postgres`ProcessUtility(parsetree=0x7d99e9b8, queryString=0x7d99d42c, params=0x00000000, isTopLevel='\x01', dest=0x7d99d7a0, completionTag=0xbff5ae34) + 6096 at utility.c:1392
    frame #21: 0x0052db2a postgres`PortalRunUtility(portal=0x7c1d182c, utilityStmt=0x7d99e9b8, isTopLevel='\x01', dest=0x7d99d7a0, completionTag=0xbff5ae34) + 611 at pquery.c:1515
    frame #22: 0x0052d729 postgres`FillPortalStore(portal=0x7c1d182c, isTopLevel='\x01') + 176 at pquery.c:1367
    frame #23: 0x0052cff0 postgres`PortalRun(portal=0x7c1d182c, count=9223372036854775807, isTopLevel='\x01', dest=0x7d9a96a8, altdest=0x7d9a96a8, completionTag=0xbff5af7e) + 814 at pquery.c:1104
    frame #24: 0x00524316 postgres`exec_simple_query(query_string=0x7c1cd82c, seqServerHost=0x00000000, seqServerPort=-1) + 2465 at postgres.c:1731
    frame #25: 0x00529a68 postgres`PostgresMain(argc=1, argv=0x7d13d430, dbname=0x7d13d330, username=0x7d13d304) + 3812 at postgres.c:4654
    frame #26: 0x004b6798 postgres`BackendRun(port=0x7c8579f0) + 702 at postmaster.c:6699
    frame #27: 0x004b5d59 postgres`BackendStartup(port=0x7c8579f0) + 381 at postmaster.c:6386
    frame #28: 0x004ad7c1 postgres`ServerLoop + 1122 at postmaster.c:2450
    frame #29: 0x004ab93d postgres`PostmasterMain(argc=18, argv=0x7b68af90) + 5694 at postmaster.c:1526
    frame #30: 0x003c6c50 postgres`main(argc=18, argv=0x7b68af90) + 840 at main.c:206
    frame #31: 0x92f4d701 libdyld.dylib`start + 1
```

Not sure when this was introduced, can someone familiar with the planner please take a look?

Thanks.

**Comment by hlinnaka** [comment]
On 20/01/16 22:04, George Caragea wrote:
> I'm hitting an assertion in the planner when running the following repro on latest master
> ...
> Not sure when this was introduced, can someone familiar with the planner please take a look?

I'll take a look. It might well be caused the merge of the equivalence 
classes patch; that moved things around in pathkey handling a lot. Thanks!

- Heikki

**Comment by atris** [comment]
I doubt that it came from the equivalence class because we saw it on an
older version on client side.

**Comment by hlinnaka** [comment]
On 20/01/16 22:29, Atri Sharma wrote:
> I doubt that it came from the equivalence class because we saw it on an
> older version on client side.

Oh. In that case, I withdraw my offer to debug this :-).

(if no-one else volunteers, though, I could still have a look..)

- Heikki

**Comment by atris** [comment]
Please feel free. Please let me know if I can help

**Comment by hlinnaka** [comment]
On 20/01/16 22:04, George Caragea wrote:
> I'm hitting an assertion in the planner when running the following repro on latest master
> ```
> create table t (c int);
> insert into t values (2);
> set gp_cte_sharing=on;
>
> explain
> with cte0 (e) as (values (0), (1))
> select c, count(distinct d) disc_d
> from (
>      select c, d
>      from (
>        select
>          case
>            when t.c in (select e from cte0) then 'a'
>            when t.c not in (select e from cte0) then 'b'
>          end as d,
>          c
>        from t, cte0
>      ) A
>      group by c, d
> ) B
> group by c;
>
> FATAL:  Unexpected internal error (cdbmutate.c:2082)
> DETAIL:  FailedAssertion("!(((void *)0) != plan_slicemark.plan)", File: "cdbmutate.c", Line: 2082)
> HINT:  Process 5632 will wait for gp_debug_linger=120 seconds before termination.

I think I figured this out. In apply_shareinput_xslice(), we do this:

>     /*
>      * a subplan might have a SharedScan consumer while the SharedScan producer
>      * is in the main plan,
>      * we need to store SharedScan nodes in main plan into traversal context
>      *  before traversing subplans
>      */
>     shareinput_walker(shareinput_mutator_xslice_1, (Node *) plan, ctxt);
>     foreach (lp, glob->subplans)
>     {
>         Plan	   *subplan = (Plan *) lfirst(lp);
>         shareinput_walker(shareinput_mutator_xslice_1, (Node *) subplan, ctxt);
>     }

So the walker assumes that it will always encounter the producer before 
its consumers. According to the comment, we walk the plans in order: 1. 
top plan, 2. all subplans, to ensure that we find always find the 
producer first, in case the top plan contains a producer and subplan its 
consumer. But the situation can just as well be the reverse: a subplan 
can contain a producer for the top-plan, or for another subplan.

A simple fix is to split the first pass into two: first find all the 
proucers, and add them to the context, and leave consumers alone. And 
then, in separate pass once all the producers have been collected, 
process all the consumers.

I'll post a pull request for this shortly. Thanks for the report!

- Heikki

**Comment by gcaragea** [comment]
Thanks for looking into this Heikki. I saw the PR.

**Comment by hlinnaka** [comment]
Pushed to master. I don't have the setup to build and test on 4.3 stable branch at hand, so I'll leave that to Someone Else to do.

**Comment by addisonhuddy** [comment]
Any reason this is still open?

**Comment by hlinnaka** [comment]
No, don't think so. Closed.
