### ISSUE TITLE
Found that column name change in pg_catalog.pg_exttable table

### ISSUE THREAD

**Issue by rmadiwaledba** [greenplum-db/gpdb#2886]
I was testing one tool to migrate the data from postgres to greenplum. It was failing on opensource version of GPDB  after detail debug found that tool uses pg_exttable catalog to track external tables and web tables and it was failing as column name in the  pg_exttable is different compare to licence version of gpdb and the column name is "urilocation"  on opensource gpdb and in licence version it is named as "location" that is the reason it was failing.

Here is the error on opensource gpdb 
`DBMS error [[ODBC 20101 driver][20101]ERROR: column x.location does not exist]. 
`
My question is whether the name of the column is changed or it is bug ?

**Comment by hlinnaka** [comment]
The name of the field has indeed been changed from location to urilocation in GPDB 5. See commit ac2fd68027a6b42cd17ca5be92b64a20fb677c47. You will need to adjust the migration tool accordingly.

I'm curious, though, why does the migration tool need to query the pg_exttable catalog, when you're migrating from postgres to greenplum?
