### ISSUE TITLE
gpstart hangs if there is an error starting the master 

### ISSUE THREAD

**Issue by davecramer** [greenplum-db/gpdb#2944]
Recently observed a failure to start the master and gpstart has to be killed using -KILL

**Comment by skahler-pivotal** [comment]
Can you tell at what point the start process hung? Is any output in gpstart_YYYYMMDD.log that could help figure out the problem?

**Comment by davecramer** [comment]
Scott,

Here is exactly what happens

gpstart -a

20170814:06:25:56:064736 gpstart:gpmdw:gpadmin-[INFO]:-Starting gpstart
with args: -a
20170814:06:25:56:064736 gpstart:gpmdw:gpadmin-[INFO]:-Gathering
information and validating the environment...
20170814:06:25:56:064736 gpstart:gpmdw:gpadmin-[INFO]:-Greenplum Binary
Version: 'postgres (Greenplum Database) 5.0.0-beta.7 build dev'
20170814:06:25:56:064736 gpstart:gpmdw:gpadmin-[INFO]:-Greenplum Catalog
Version: '301705051'
20170814:06:25:56:064736 gpstart:gpmdw:gpadmin-[INFO]:-Starting Master
instance in admin mode

in the gpstartlogs

20170814:05:36:37:061613 gpstart:gpmdw:gpadmin-[INFO]:-Starting gpstart
with args: -a
20170814:05:36:37:061613 gpstart:gpmdw:gpadmin-[INFO]:-Gathering
information and validating the environment...
20170814:05:36:37:061613 gpstart:gpmdw:gpadmin-[INFO]:-Greenplum Binary
Version: 'postgres (Greenplum Database) 5.0.0-beta.7 build dev'
20170814:05:36:38:061613 gpstart:gpmdw:gpadmin-[INFO]:-Greenplum Catalog
Version: '301705051'
20170814:05:36:38:061613 gpstart:gpmdw:gpadmin-[INFO]:-Starting Master
instance in admin mode

in the

master log files:

2017-08-14 05:36:38.964945
PDT,,,p61623,th1171789696,,,,0,,,seg-1,,,,,"LOG","00000","TransitionToMasterOrMirrorless:
initializing XLog startup",,,,,,,0,,"primary_mirror_mode.c",1886,
2017-08-14 05:36:38.965021
PDT,,,p61623,th1171789696,,,,0,,,seg-1,,,,,"LOG","00000","TransitionToMasterOrMirrorless:
starting database",,,,,,,0,,"primary_mirror_mode.c",1900,
2017-08-14 05:36:38.965843
PDT,,,p61625,th1171789696,,,,0,,,seg-1,,,,,"LOG","00000","database system
was shut down at 2017-08-14 05:34:28 PDT",,,,,,,0,,"xlog.c",6474,
2017-08-14 05:36:38.967900
PDT,,,p61625,th1171789696,,,,0,,,seg-1,,,,,"LOG","00000","end of
transaction log location is 0/9F70AB0",,,,,,,0,,"xlog.c",7090,
2017-08-14 05:36:38.969851
PDT,,,p61625,th1171789696,,,,0,,,seg-1,,,,,"WARNING","01000","page
verification failed, calculated checksum 63232 but expected
55627",,,,,,,0,,"bufpage.c",142,
2017-08-14 05:36:38.969881
PDT,,,p61625,th1171789696,,,,0,,,seg-1,,,,,"FATAL","XX001","invalid page in
block 0 of relation global/5090",,,,,,,0,,"bufmgr.c",407,
2017-08-14 05:36:38.972835
PDT,,,p61623,th1171789696,,,,0,,,seg-1,,,,,"LOG","00000","startup process
(PID 61625) exited with exit code 1",,,,,,,0,,"postmaster.c",5560,
2017-08-14 05:36:38.972861
PDT,,,p61623,th1171789696,,,,0,,,seg-1,,,,,"LOG","00000","aborting startup
due to startup process failure",,,,,,,0,,"postmaster.c",4385,


Looking into this a bit more pg_ctl does not fail at this point so gpstart
is waiting for pg_ctl to fail.

Dave

davec@openscg.com

**Comment by Chibin** [comment]
Right, I said this in a separate email, but more relevant here.

```
pg_ctl seems to hold out for the entire duration of the timeout even if the sever already failed to startup.

we changed the postgresql.conf file to have a broken name=value, so we expected postgres server to fail immediately, but pg_ctl waits for the full timeout.

pg_ctrl just prints out: `waiting for server to start.............................................................................................................................................................................................` for a while

```

**Comment by ashwinstar** [comment]
Merge with postgres 9.4 fixed the pg_ctl issue mentioned above via this upstream commit 57f54b5e4eb5fedb102d4006857c226b47f21e28. So, this issue is not seen in latest release on GPDB6 and forward.
