### ISSUE TITLE
gpfdist holds RAM on using -m argument

### ISSUE THREAD

**Issue by kelvien** [greenplum-db/gpdb#2962]
I notice that gpfdist is holding up RAM on using the -m argument.
i.e: gpfdist -p 8081 -d . -m 256000000
When gpfdist is triggered by a query, the gpfdist process will start using the RAM, but it will not release the RAM after the query is finished.

Process starts of with 0% CPU, and ~0.1% RAM
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                
47971 khidayat  20   0   19512   1688   1316 S 0.000 0.010   0:00.00 gpfdist -p 8082 -d -m 256000000

Spikes up when query that utilizes external table is triggered
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                
47321 khidayat  20   0 8020036 3.184g   1488 S 3.987 20.28   0:04.15 gpfdist -p 8082 -d -m 256000000

CPU goes back to 0% on finished query, and memory is not released.
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                
47321 khidayat  20   0 8020036 3.184g   1488 S 0         20.28   0:04.15 gpfdist -p 8082 -d -m 256000000

I am using gploaders v.4.3.8.1

Is this the expected behavior of gpfdist ?

**Comment by hsyuan** [comment]
@pivotal-mike Who is the one familiar with gpfdist?

**Comment by pivotal-mike** [comment]
@lij55 @adam8157 Can I ask you take a look?

**Comment by yydzero** [comment]
Include @pf-qiu & @yuanzhao also

**Comment by adam8157** [comment]
where it allocates:
https://github.com/greenplum-db/gpdb/blob/138cc11993f8493a5b9f021b7b7ab75adf9b429a/src/bin/gpfdist/gpfdist.c#L2967

where it frees:
https://github.com/greenplum-db/gpdb/blob/138cc11993f8493a5b9f021b7b7ab75adf9b429a/src/bin/gpfdist/gpfdist.c#L4204

It's not supposed to hold the RAM, will try to reproduce it

**Comment by lij55** [comment]
Thanks, @kelvien 
I can reproduce it with latest gpfdist. It looks like the memory leaks.
We will investigate it soon.

**Comment by kelvien** [comment]
Tried out Greenplum loaders v.5, and the problem still persists.
This is `top` after my query that utilized the external table completed. The memory started out with ~0.1% and ended at 48.61%. Stays at 48.61% until the process is terminated. 
`  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND

63211 kelvien  20   0 8270284 7.632g   2024 S 5.648 48.61   0:11.29 /usr/local/greenplum-loaders-5.0.0/bin/gpfdist -p 8083 -d /data/kelvien/readable_external_tables/ -m 256000000`

**Comment by pf-qiu** [comment]
Hi @kelvien .
We have investigated this issue. Memory buffer controlled by -m parameter is cached by memory pool, and reused for subsequent requests. This way it don't have to allocate and deallocate from system. This buffer is per segment so if you use a gpdb cluster with larger segment number, memory usage will increase. We consider this is expected behavior.

**Comment by kelvien** [comment]
@pf-qiu thanks.. Is there a benefit in caching it for the subsequent requests ? I'm not an expert in memory management, but it seems like there won't be much time overhead since we are dealing with RAM anyway.
