### ISSUE TITLE
ORCA version 2.40.XXX

### ISSUE THREAD

**Issue by MicGir** [greenplum-db/gpdb#2995]
During gpdb configure i get ...

"checking Checking ORCA version... configure: error: Your ORCA version is expected to be 2.40.XXX"

the gpdb and gporca are boths freshly cloned ...

Cheers
Michel

**Comment by hlinnaka** [comment]
Have a look at config.log, to see what the exact error you got is. There's a lot of output there, search for `ORCA`.

When I compile from sources on my laptop, I install the orca libraries to a non-standard location. Therefore I have to pass the include and lib location, with the `--with-includes` and `--with-libs` options to configure. But that's not enough, I also have to make the libs dir available in LD_LIBRARY_PATH, so that when the configure script tries to execute the test program to determine the version, it is found. So all in all, I use something like this:
```
LD_LIBRARY_PATH=/home/heikki/gpdb/orca-install/lib ./configure --with-includes=/home/heikki/gpdb/orca-install/include --with-libs=/home/heikki/gpdb/orca-install/lib/ <other flags>
```

**Comment by MicGir** [comment]
Thanks a lot,

will have a look for sure !

But this looks  … like … very hard coded at script level …. Is «config.log»


| int
| main ()
| {
|
| return strncmp("2.40.", GPORCA_VERSION_STRING, 5);
|
|   ;
|   return 0;
| }
configure:12552: error: Your ORCA version is expected to be 2.40.XXX

Thanks a lot for your reponse 😊
Michel
Von: Heikki Linnakangas<mailto:notifications@github.com>
Gesendet: Sonntag, 20. August 2017 18:52
An: greenplum-db/gpdb<mailto:gpdb@noreply.github.com>
Cc: MicGir<mailto:mgirod@outlook.de>; Author<mailto:author@noreply.github.com>
Betreff: Re: [greenplum-db/gpdb] ORCA version 2.40.XXX (#2995)


Have a look at config.log, to see what the exact error you got is. There's a lot of output there, search for ORCA.

When I compile from sources on my laptop, I install the orca libraries to a non-standard location. Therefore I have to pass the include and lib location, with the --with-includes and --with-libs options to configure. But that's not enough, I also have to make the libs dir available in LD_LIBRARY_PATH, so that when the configure script tries to execute the test program to determine the version, it is found. So all in all, I use something like this:

LD_LIBRARY_PATH=/home/heikki/gpdb/orca-install/lib ./configure --with-includes=/home/heikki/gpdb/orca-install/include --with-libs=/home/heikki/gpdb/orca-install/lib/ <other flags>

**Comment by paul-guo-** [comment]
According to the code in configure, you could search for the version.h in
your system to find where the header file is located at; you could set the
orca code to the required version (e.g. git reset --hard if you git-cloned
the gporca repo and then rebuild).

```
#include "gpopt/version.h"
#include <string.h>

int
main ()
{

return strncmp("2.39.", GPORCA_VERSION_STRING, 5);

  ;
  return 0;
}
```

By the way, the checking code should really print out GPORCA_VERSION_STRING
IMO.


2017-08-21 6:47 GMT+08:00 MicGir <notifications@github.com>:

**Comment by hsyuan** [comment]
If you are using centos7, can you try adding /usr/local to /etc/ld.so.conf.d and run ldconfig?

**Comment by hsyuan** [comment]
I think it should be resolved by above comment. so close it.
