### ISSUE TITLE
gpinitsystem redirects some error messages to /dev/null

### ISSUE THREAD

**Issue by yydzero** [greenplum-db/gpdb#3044]
Compiled Greenplum master on mac, and got following error when initialize cluster:

```
[FATAL]:-Failed to complete obtain psql count Master gp_segment_configuration
```

While there is no any more error information. 'gpinitsystem -D' does not help here.

The reason is that `bin/gpinitsystem` has redirect all error messages to /dev/null:

```
CHK_COUNT=`env PGOPTIONS="-c gp_session_role=utility" $PSQL -p $MASTER_PORT 
-d "$U_DB" -A -t -c "SELECT count(*) FROM $GP_CONFIG_TBL WHERE content=${U_CONTENT} 
AND preferred_role='${U_ROLE}';" 2>/dev/null` >> $LOG_FILE 2>&1
```

So why do we need to redirect error message to /dev/null?  **2>/dev/null** above.

**Comment by ashwinstar** [comment]
Updated the title to better reflect the problem and confirming even current gpinitsystem code continues to have this behaviour.

**Comment by pobbatihari** [comment]
This issue has been addressed in master as well as 6X.
