### ISSUE TITLE
Add binary format to external table 

### ISSUE THREAD

**Issue by yew011** [greenplum-db/gpdb#3055]
Hi,

Would like to check if there is any plan to support 'binary' format to the external table.

Or if there is any non-obvious impact?

Thanks,
Alex Wang,

**Comment by hlinnaka** [comment]
I don't think there are any plans to do that at the moment. It shouldn't be too hard to implement, but the use case seems pretty thing. Usually, when people have data lying around in files, they will be in text or CSV format.

**Comment by yew011** [comment]
@hlinnaka Thx for the confirmation, closing the issue,
