### ISSUE TITLE
installcheck failed for ecpg

### ISSUE THREAD

**Issue by yydzero** [greenplum-db/gpdb#306]
```
$ cd src/interfaces/ecpg
$ make installcheck

make[2]: Entering directory `/home/gpadmin/workspace/oss/gpdb/src/interfaces/ecpg/test/connect'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/home/gpadmin/workspace/oss/gpdb/src/interfaces/ecpg/test/connect'
make -C sql all
make[2]: Entering directory `/home/gpadmin/workspace/oss/gpdb/src/interfaces/ecpg/test/sql'
../../preproc/ecpg --regression -I./../../include -o dyntest.c -I. dyntest.pgc
dyntest.pgc:64: ERROR: syntax error at or near "sql"
make[2]: *** [dyntest.c] Error 3
make[2]: *** Deleting file `dyntest.c'
make[2]: Leaving directory `/home/gpadmin/workspace/oss/gpdb/src/interfaces/ecpg/test/sql'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/home/gpadmin/workspace/oss/gpdb/src/interfaces/ecpg/test'
make: *** [installcheck] Error 2
```

**Comment by renkemingithub** [comment]
modify the row:
exec sql fetch in MYCURS into sql descriptor MYDESC;

turn into    exec sql fetch MYCURS into descriptor MYDESC;

then make installcheck. ok.

**Comment by renkemingithub** [comment]
func.pgc: need to modify. 
turn Log into my_Log. 

parser.pgc: need to modifty. 
nulls last  , not be realized by greenplum. delete it. ok.

**Comment by renkemingithub** [comment]
delete " set data"   , turn into 
 EXEC SQL ALTER TABLE T ALTER COLUMN Item2 TYPE smallint;
then compile . ok

**Comment by yydzero** [comment]
Cool, thanks renkemingithub, would you please file a PR?

On Mon, Jan 25, 2016 at 5:18 PM, renkemingithub <notifications@github.com>
wrote:

> delete " set data" , turn into
> EXEC SQL ALTER TABLE T ALTER COLUMN Item2 TYPE smallint;
> then compile . ok
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/greenplum-db/gpdb/issues/306#issuecomment-174756612>.
>



-- 
Best Regards,
Yandong

**Comment by renkemingithub** [comment]
show.pgc: delete the row.
EXEC SQL SET search_path TO :var;  compile . then ok.

**Comment by renkemingithub** [comment]
PR ?

**Comment by renkemingithub** [comment]
rnull.pgc： 
turn bool into int. then ok.
$create table test(id int, c char(10), s smallint, i int, b int, f float, l bigint, dbl double precision,
                                           dec decimal, dat date, tmp timestamptz);

**Comment by renkemingithub** [comment]
thread_implicit.pgc：
add “”。 then ok.
 EXEC SQL SELECT "COUNT(*)" INTO :l_rows FROM test_thread;

**Comment by renkemingithub** [comment]
test.tar in gpdb-master/src/interfaces/ecpg directory. 
tar xvf test.tar . then make installcheck . ok.

**Comment by yydzero** [comment]
PR = Pull Request :)

Let me know if you need any help for filing PR

On Mon, Jan 25, 2016 at 5:57 PM, renkemingithub <notifications@github.com>
wrote:

> test.tar in gpdb-master/src/interfaces/ecpg directory.
> tar xvf test.tar . then make installcheck . ok.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/greenplum-db/gpdb/issues/306#issuecomment-174772022>.
>



-- 
Best Regards,
Yandong

**Comment by ivannovick** [comment]
@yydzero any action item needed on this issue?

**Comment by yydzero** [comment]
SQL file need changes according to @renkemingithub's comments

**Comment by ivannovick** [comment]
@yydzero can you help close it out, or it takes more work?

**Comment by yydzero** [comment]
Just tried this on master,  it is still broken while in different places (earlier). It will take more work

**Comment by ashwinstar** [comment]
@yydzero Please can we post what more needs to be done here or its continuing to fail on latest ?

**Comment by yydzero** [comment]
@ashwinstar the remaining work is to make install check pass:
```
$ cd src/interfaces/ecpg
$ make installcheck
```
