### ISSUE TITLE
Invalid input for statement_mem

### ISSUE THREAD

**Issue by gaos1** [greenplum-db/gpdb#3072]
Hit this in GPDB V5 Beta 6. 

1.  Re-produce process:
   gpconfig -c statement_mem -v 2GB 
   gpconfig -c max_statement_mem -v 20GB
   gprestart -M fast
   gpstart

2. Issue Description:
2017-08-18 16:21:18.157871 GMT,,,p5988,th1803626272,,,,0,,,seg-1,,,,,"FATAL","XX000","Invalid input for statement_mem. Must be less than max_statement_mem (2048000 kB). (cdbvars.c:1372)",,,,,,,,"gpvars_assign_statement_mem","cdbvars.c",1372,1    0x94ac3b postgres errstart + 0x1db

2    0x94c9b4 postgres elog_finish + 0xb4

3    0xa89c68 postgres <symbol not found> (cdbvars.c:1372)

4    0x96e30d postgres set_config_option + 0xc0d

5    0x974254 postgres ProcessConfigFile + 0x304

6    0x9745ee postgres SelectConfigFiles + 0x8e

7    0x7caa56 postgres PostmasterMain (postmaster.c:1112)

8    0x700807 postgres main (main.c:206)

9    0x308761ecdd libc.so.6 __libc_start_main + 0xfd

10   0x4c2cbd postgres <symbol not found> + 0x4c2cbd

**Comment by phan-pivotal** [comment]
Hi Simon,
Thanks for help logging the issue.

**Comment by guofengrichard** [comment]
Looks like a bug in gpdb.

In the process of gpdb starting, function `ProcessConfigFile()` will be called.
On step of this function is to check if all options are valid with new GUC values, but without actually setting them.

```
    for (item = head; item; item = item->next)
    {
       ...

        if (!set_config_option(item->name, item->value, context,
                               PGC_S_FILE, GUC_ACTION_SET, false))  <==== check but NOT set
            goto cleanup_list;
    }
```

This is the problem with GUC `statement_mem` and `max_statement_mem`.
The new value of `statement_mem` will be checked against the old value of `max_statement_mem`,
so this issue emerges.

**Comment by guofengrichard** [comment]
One point need to notice: `max_statement_mem` should be set before `statement_mem` in this case.

**Comment by guofengrichard** [comment]
This issue also exists for GUC `max_resource_groups` and `max_connections`.

**Comment by phan-pivotal** [comment]
@guofengrichard 
A quick response. 
Thanks.

**Comment by Neilxzn** [comment]
@gaos1 now i have the same problem. Now I can connect  my gpdb now because of it. How did u fix your db without reinstalling the db? thank you!!

**Comment by gaos1** [comment]
you need to make sure that max_statement_mem should be set before statement_mem in psql or conf file.

**Comment by gaos1** [comment]
then set them in postgresql.conf in your master/segment data directory in
proper order and restart cluster.

**Comment by Neilxzn** [comment]
@gaos1 it works！！！Thank you !!
