### ISSUE TITLE
Irrelevant default timezone_abbreviations

### ISSUE THREAD

**Issue by jbgood** [greenplum-db/gpdb#3103]
GP has old and irrelevant timezone_abbreviations config files. 
E.g. MSK has offset 14400, which is wrong.

Guess you need to merge these config files from actual postgresql release.

**Comment by hlinnaka** [comment]
@schubert, something to add to the release checklist. We should update the timezone data files regularly, before every release. Or at least that's how we do it in PostgreSQL, and is probably expected by users.

**Comment by danielgustafsson** [comment]
:+1: We discussed recently to always pull the timezone files from the current upstream PostgreSQL release when cutting a Greenplum release.

**Comment by schubert** [comment]
Makes sense. I thought I saw a postgres release checklist in their docs somewhere but now I can't find it. If we don't have a release checklist doc file we should probably start one. Toplevel README.md is getting too large and probably should be broken up into smaller chunks and turn most of it into a ToC.

**Comment by hlinnaka** [comment]
On 08/30/2017 08:03 PM, Michael Schubert wrote:
> Makes sense. I thought I saw a postgres release checklist in their
> docs somewhere but now I can't find it. If we don't have a release
> checklist doc file we should probably start one. Toplevel README.md
> is getting too large and probably should be broken up into smaller
> chunks and turn most of it into a ToC.

https://wiki.postgresql.org/wiki/Release_process

- Heikki

**Comment by hlinnaka** [comment]
On 08/30/2017 08:03 PM, Michael Schubert wrote:
> Makes sense. I thought I saw a postgres release checklist in their
> docs somewhere but now I can't find it.

https://wiki.postgresql.org/wiki/Release_process

- Heikki

**Comment by professor** [comment]
I noticed that @danielgustafsson updated the tznames files. 

Postgres does lists MSK as 14400 https://github.com/postgres/postgres/blob/master/src/timezone/tznames/Europe.txt

Are we able to close this issue?

**Comment by danielgustafsson** [comment]
> On 02 Sep 2017, at 00:41, Todd Sedano <notifications@github.com> wrote:
> 
> I noticed that @danielgustafsson updated the tznames files.
> 
> Postgres does lists MSK as 14400 https://github.com/postgres/postgres/blob/master/src/timezone/tznames/Europe.txt
> 
> Are we able to close this issue?

The TZ update was backed out again due to a problem with the datafiles, so it’s not fixed yet.

**Comment by skahler-pivotal** [comment]
Still experiencing issues around this, needs to bubble back up to relevancy

--note @jingli

**Comment by ashwinstar** [comment]
I think this is resolved hence closing the same. If something remaining please feel free to re-open stating what remains.
