### ISSUE TITLE
gpAux/gpperfmon/src/gpmon compile error 

### ISSUE THREAD

**Issue by renkemingithub** [greenplum-db/gpdb#314]
how to compile gpmon ?

**Comment by hlinnaka** [comment]
@edespino, can you answer this one? I've never tried building that thing, and I don't know what it does.

**Comment by ivannovick** [comment]
is this a real issue @skahler-pivotal ?

**Comment by Chibin** [comment]
> is this a real issue @skahler-pivotal ?

Took a look and we may need to modify some parts of the makefile.

**Comment by garryfan2013** [comment]
Hi, guys , I've tried to make gpperfmon, seems some ext/{arch} header directories are missing,
If there is any solutions to this? Thanks

**Comment by skahler-pivotal** [comment]
we added a track recently to start working on the gpperfmon pieces, some of this should shake out over the next few weeks

**Comment by skahler-pivotal** [comment]
gpmon should be compiling now with the --enable-gpperfmon during configure
