### ISSUE TITLE
configure: error: Your ORCA version is expected to be 2.41.XXX

### ISSUE THREAD

**Issue by menghuanguaishou** [greenplum-db/gpdb#3146]
When I run 
“./configure --with-perl --with-python --with-libxml --prefix=/usr/local/gpdb”
with the flowing errors like this:
configure: error: Your ORCA version is expected to be 2.41.XXX
But I get the latest version both bpdb and gporca ,Who can help me,please!

**Comment by hsyuan** [comment]
Weird. If both are latest, it should work.
Did you install the latest gporca?

**Comment by menghuanguaishou** [comment]
I pull the latest code by "git pull --ff-only" ,Its no use.But I down the version gporca-2.41.0,It's OK,Thanks very much!

**Comment by hsyuan** [comment]
cheers!
