### ISSUE TITLE
Quicklz alternatives

### ISSUE THREAD

**Issue by daledude** [greenplum-db/gpdb#3155]
I was unable to find any conversations about Quicklz being replaced with an alternative so I was hoping to maybe start one. Appologies if I missed a thread somewhere.

Possible alternatives used by other databases:
[lz4](https://github.com/lz4/lz4)
[zstd](http://facebook.github.io/zstd/)
[snappy](https://github.com/google/snappy)

**Comment by hlinnaka** [comment]
There is zlib and a simple Run-Length-Encoder there already. I agree that one of those newer algorithms you listed would be better for most use cases though.

**Comment by hlinnaka** [comment]
Aside from compressing table data, Greenplum also compresses the plan tree that it sends from the QD to the QE nodes, and temporary files. We currently use zlib for compressing the plan trees, and there's a choice of zlib or bzip2 for the temporary files. Something like snappy, with a better compression/decompression speed but worse compression ratio, would be better for those uses.

**Comment by Eulerizeit** [comment]
I think we are unlikely to replace Quicklz. We are very likely to add additional compression algorithms if there is a use case for it. What are you trying to achieve?

**Comment by daledude** [comment]
The hope is better levels compression with their obvious varying overheads. I can only make assumptions based on experience with other databases so take my request with a huge grain of salt.

I currently compress older data with zstd with Clickhouse database which also has lz4. The zstd compression gives me about 5:1 and lz4 is about 3:1. zstd has a bit more overhead depending on the volume of data and type of query but the space savings alone are worth it to us.

I also use zlib, snappy and no compression with Tokudb. zlib in this case gives fair compression but queries using this engine are considerably slower than snappy or no compression.

I very lightly tested the bigtop build of the 5.0-alpha some months ago with 26 mil records. I couldn't get a query less than 6 seconds with indexed or non-indexed fields across 8 segments on 8 core/32 "cpu" Dell. Same queries in Clickhouse/Tokudb(not zlib) were ~1 seconds. I will accept discarding anything to do with other databases but giving as reference. The sweet spot to get to 6 seconds was compresstype=zlib, compresslevel=3 which gave 4.23:1. rle_type with level 3 also did pretty good.

**Comment by hlinnaka** [comment]
On 09/11/2017 01:47 AM, Dale Dude wrote:
> The hope is better levels compression with their obvious varying
> overheads. I can only make assumptions based on experience with other
> databases so take my request with a huge grain of salt.
> 
> I currently compress older data with zstd with Clickhouse database
> which also has lz4. The zstd compression gives me about 5:1 and lz4
> is about 3:1. zstd has a bit more overhead depending on the volume of
> data and type of query but the space savings alone are worth it to
> us.

Yeah, seems that zstd would be a good choice for GPDB as well. Based on 
zstd's own benchmarks, it's faster than zlib, and also compresses better 
(got to take benchmarks with a grain of salt, of course, but I believe 
that's more or less true). But even more interesting IMHO is that it's 
got a wide range of "tunability". It's very fast at low compression 
levels, but compresses very well at high levels.

It's got a compatible license, and it comes as a library with a decent API.

- Heikki

**Comment by ivannovick** [comment]
zstd sounds promising!!  @Eulerizeit FYI would be great to get in our roadmap

**Comment by kapustor** [comment]
We started a topic on gpdev mailing list:
https://groups.google.com/a/greenplum.org/forum/#!topic/gpdb-dev/XoYcF97qK-Y
We are ready to implement this feature, but we need to understand that the way we are doing it correlates with devs's vision.

**Comment by hlinnaka** [comment]
Support for zstandard compression was added in commit 724f9d27b160ec3f87a5ce95eecc605808be3ced.
