### ISSUE TITLE
gprecoverseg -S ./dir.txt hang up

### ISSUE THREAD

**Issue by wqkabc** [greenplum-db/gpdb#3156]
when I run the command "gprecoverseg -S ./dir.txt", the command hangs up。
the point where command hangs up is in the file clsRecoverSegment.py,function GpRecoverSegmentProgram->cleanup(), the code is follow:
self.__pool.haltWork()
self.__pool.joinWorkers()
self.__pool.join()                # it's here! doing a Queue.join() and hangs up

after I'v changed the order of function calling as follow, It works!
self.__pool.join()
self.__pool.haltWork()
self.__pool.joinWorkers()

so, I think something is wrong.

**Comment by wqkabc** [comment]
my python version: 2.7.5

**Comment by wqkabc** [comment]
The problem is reproducible。I got same result on several different GPDB。

**Comment by skahler-pivotal** [comment]
which greenplum version or commit are built off of?

**Comment by Chibin** [comment]
> when I run the command "gprecoverseg -S ./dir.txt", the command hangs up。
> the point where command hangs up is in the file clsRecoverSegment.py,function GpRecoverSegmentProgram->cleanup(), the code is follow:
> self.__pool.haltWork()
> self.__pool.joinWorkers()
> self.__pool.join() # it's here! doing a Queue.join() and hangs up
> 
> after I'v changed the order of function calling as follow, It works!
> self.__pool.join()
> self.__pool.haltWork()
> self.__pool.joinWorkers()
> 
> so, I think something is wrong.

The suggested changes looks right, did you want to create a PR for this?

**Comment by wqkabc** [comment]
@skahler-pivotal 
GPDB4.3.99    I'v installed from source code/　OS：centos7.0

@Chibin
I'v tried to create PR。It seems that I have no permission。

**Comment by Chibin** [comment]
> @Chibin
> I'v tried to create PR。It seems that I have no permission。

@wqkabc You'll need to fork the gpdb repo and create a branch in your own gpdb forked repo.
Afterwards, you can create a pull request to the main gpdb repo.
Hope that helps.
