### ISSUE TITLE
Your ORCA version is expected to be 2.40.XXX

### ISSUE THREAD

**Issue by menghuanguaishou** [greenplum-db/gpdb#3163]
There is a problem with installing Greenplum：Your ORCA version is expected to be 2.40.XXX。
Centos7。
I have installed gporca-2.41.0 and gp-xerces-3.1.2-p1.
But the following error occurred when installing gpdb-5X_STABLE：

    checking for InitDXL in -lnaucrates... yes
    checking for gpopt_init in -lgpopt... yes
    checking Checking ORCA version... configure: error: Your ORCA version is expected to be 2.41.XXX

But I Install gpdb-5.0.0-beta.10
The following error occurs：
checking Checking ORCA version... configure: error: Your ORCA version is expected to be 2.40.XXX
How can I make it，Can someone help me？Thanks！

**Comment by menghuanguaishou** [comment]
I change the code in the file of 'configure'
I add 'echo 1' at the line of 2179 of the file 'configure' like this


fi
  rm -rf conftest.dSYM conftest_ipa8_conftest.oo
  eval $as_lineno_stack; ${as_lineno_stack:+:} unset as_lineno
  as_fn_set_status $ac_retval
  echo 1      #I add this row
} # ac_fn_cxx_try_run


Its OK，But I down not know why,Who can tell me why？Thanks

**Comment by hsyuan** [comment]
every gpdb version requires a specific gporca version. you have to install the exact orca version.

**Comment by menghuanguaishou** [comment]
I use gpdb-5.0.0-beta.10 try it again,But I use the version gporca-2.40.0 gporca-2.40.1 gporca-2.40.2 gporca-2.40.3 from the tag,they are not work.It's also has the errors.

checking Checking ORCA version... configure: error: Your ORCA version is expected to be 2.40.XXX
I clear up by the following codes when I install every gporca package.
rm -rf /usr/local/include/naucrates
rm -rf /usr/local/include/gpdbcost
rm -rf /usr/local/include/gpopt
rm -rf /usr/local/include/gpos
rm -rf /usr/local/lib/libnaucrates.so*
rm -rf /usr/local/lib/libgpdbcost.so*
rm -rf /usr/local/lib/libgpopt.so*
rm -rf /usr/local/lib/libgpos.so*

**Comment by menghuanguaishou** [comment]
@hsyuan @michaelklishin @foobar @flavorjones @tanzeeb  Can you help me please!I want to use gpdb-5.0.0-beta.10

**Comment by hsyuan** [comment]
gpdb 5 beta 10 uses orca 2.40.X
5X_stable uses orca 2.41.X at the moment.
@oarap Anything we can do to help @melanieplageman out?

**Comment by menghuanguaishou** [comment]
@hsyuan 
I do build in Centos7.3
First,I install the depends by following steps:
yum install -y gcc gcc-c++ zlib zlib-devel bzip2-devel autoconf automake libevent-devel apr-devel curl-devel ed python-paramiko python-devel perl-ExtUtils-Embed readline-devel apr-util-devel libevent-devel libxml2-devel libtool.x86_64 
Second I install the gp-xerces-3.1.2-p1 by following steps:
mkdir build
cd build
../configure --prefix=/usr/local
make
make install

Second, I build gporca-2.41.0.This is only one gporca which version is 2.41.0 in the tag,So I don't think I have something wrong,I build it by these codes:
mkdir build
cd build
cmake ../
make
sudo make install
Then, their is the wrong when I configure the gpdb-5X_STABLE by the codes:
./configure --with-perl --with-python --with-libxml --prefix=/usr/local/gpdb
The error is Your ORCA version is expected to be 2.41.XXX.
I learn that steps from the page https://github.com/greenplum-db/gpdb,
I do that process above by each group below: 
gpdb-5.0.0-beta.10 +  gporca-2.40.0
gpdb-5.0.0-beta.10 +  gporca-2.40.1
gpdb-5.0.0-beta.10 +  gporca-2.40.2
gpdb-5.0.0-beta.10 +  gporca-2.40.3
gpdb-5X_STABLE + gporca-2.41.0
They have the same wrong  Your ORCA version is expected to be 2.40.XXX  or  Your ORCA version is expected to be 2.41.XXX.
So I think their must be something wrong.It maybe no right gporca which can configure gpdb successfully

**Comment by menghuanguaishou** [comment]
I have do install the gporca by ninja
mkdir gporca/build
cd gporca/build
cmake -GNinja ..
ninja install
cd ../..
Their are the same result every time

**Comment by hsyuan** [comment]
Can you try adding /usr/local to /etc/ld.so.conf.d and run ldconfig?

**Comment by hsyuan** [comment]
Add "/usr/local/lib" and "/usr/local/lib64" to "/etc/ld.so.conf", re-execute "configure" command.

**Comment by menghuanguaishou** [comment]
@hsyuan  Thank you very very much!It's perfect.I make it!
I'm not very good at compiling, so I'm prone to some simple problems
Sometimes user local libs are not in the /etc/ld.so.conf,I make it by following steps:
vi /etc/ld.so.conf.d/usrlocallib.conf  add the content:
/usr/local/lib
/usr/local/lib64
save and execute the command: ldconfig 
      [root@bogon ld.so.conf.d]# ldconfig
      [root@bogon ld.so.conf.d]# 
It will be helpful that someone write the content to the page https://github.com/greenplum-db/gpdb,I think.

**Comment by xiaozhifan** [comment]
i install find then same problem . log ：
checking Checking ORCA version... configure: error: Your ORCA version is expected to be 2.64.XXX
but i check my lib as:
ldconfig -v
/lib:
	libxerces-c-3.1.so -> libxerces-c.so
	libnaucrates.so.3 -> libnaucrates.so.2.64.0
	libgpos.so.3 -> libgpos.so.2.64.0
	libgpopt.so.3 -> libgpopt.so.2.64.0
	libgpdbcost.so.3 -> libgpdbcost.so.2.64.0

now could you help me to reslov this problem :)
