### ISSUE TITLE
install greenplum success,but hang in select

### ISSUE THREAD

**Issue by lyb1985031** [greenplum-db/gpdb#318]
i install greenplum on three machines,one master,two segment.
create db/table works fine,select version() works fine.
but when i execute select or insert,there is no error information,just hang up.
how can i find the reason that gp works like that.

system info:
CentOS Linux release 6.2 (Final)

greenplum version:
greenplum-db-4.3.6.2-build-1-RHEL5-x86_64

**Comment by eurekaka** [comment]
Hi,

Find the master process of your session, then use pstack or gdb to see
where it is handing on from the stack. Hope this can help.

Cheers,
Kenan

**Comment by lyb1985031** [comment]
Hi,

Find the master process of your session, then use pstack or gdb to see
where it is handing on from the stack. Hope this can help.

Cheers,
Kenan

3ks,just forgot pstack. I'ill try later. I'm updating system now.

**Comment by lyb1985031** [comment]
eurekaka 3ks,just forgot pstack. I'ill try later. I'm updating system now.

**Comment by lyb1985031** [comment]
i just update system from centos6.5 to centos7. Then gp works fine.
