### ISSUE TITLE
Broken readme: orca still needs xerxes

### ISSUE THREAD

**Issue by professor** [greenplum-db/gpdb#3211]
This commit broke the installation process on a new machine: https://github.com/greenplum-db/gpdb/commit/f87100f4f1fe7e714a57c6f56a13ce7ea506472a#diff-04c6e90faac2675aa89e2176d2eec7d8

```
→ mkdir gporca/build
→ cd gporca/build
→ cmake ../
-- The CXX compiler identification is AppleClang 8.1.0.8020042
-- The C compiler identification is AppleClang 8.1.0.8020042
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Build type: RelWithDebInfo
-- Performing Test COMPILER_HAS_WALL
-- Performing Test COMPILER_HAS_WALL - Success
-- Performing Test COMPILER_HAS_WERROR
-- Performing Test COMPILER_HAS_WERROR - Success
-- Performing Test COMPILER_HAS_WEXTRA
-- Performing Test COMPILER_HAS_WEXTRA - Success
-- Performing Test COMPILER_HAS_PEDANTIC_ERRORS
-- Performing Test COMPILER_HAS_PEDANTIC_ERRORS - Success
-- Performing Test COMPILER_HAS_WNO_VARIADIC_MACROS
-- Performing Test COMPILER_HAS_WNO_VARIADIC_MACROS - Success
-- Performing Test COMPILER_HAS_WNO_TAUTOLOGICAL_UNDEFINED_COMPARE
-- Performing Test COMPILER_HAS_WNO_TAUTOLOGICAL_UNDEFINED_COMPARE - Success
-- Performing Test COMPILER_HAS_G3
-- Performing Test COMPILER_HAS_G3 - Success
-- Performing Test COMPILER_HAS_FNO_OMIT_FRAME_POINTER
-- Performing Test COMPILER_HAS_FNO_OMIT_FRAME_POINTER - Success
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE
CMake Error at /usr/local/Cellar/cmake/3.9.1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Xerces (missing: XERCES_LIBRARY XERCES_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.9.1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:377 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindXerces.cmake:12 (find_package_handle_standard_args)
  CMakeLists.txt:131 (find_package)
-- Configuring incomplete, errors occurred!
See also "/Users/pivotal/workspace/gpdb/gporca/build/CMakeFiles/CMakeOutput.log".
```

**Comment by hlinnaka** [comment]
You still need Xerces, but it doesn't need to be the custom-built and patched version anymore. Whatever version comes with your OS or distribution should work now. Xerces is now the same as e.g. libxml or zlib; you need to have it installed, but we don't go into details in the readme on how to install them.

Did that help? Or am I missing something?

**Comment by professor** [comment]
Maybe the issue is that we're not able to detect the system libraries for Xerxes.

**Comment by hlinnaka** [comment]
Perhaps. The build instructions for ORCA, in ORCA's readme, actually still talk about patching and compiling Xerces from source. I removed the check that enforced that you're using a patched version, but maybe there's still something funny there. It works for me, though...

**Comment by danielgustafsson** [comment]
autoconf still checks for Xerces, see https://github.com/greenplum-db/gpdb/blob/master/config/orca.m4#L4 for the check. The above output seems to be from building ORCA and CMake is checking for Xerces there as well, if it doesn't find it then breaking out of the build is correct.

**Comment by professor** [comment]
For macOS, what is the preferred way of installing xerxes? brew install
libxml2 ?

I'm having flashbacks and traumau from Nokogiri XML and macOS.

On Fri, Sep 8, 2017 at 11:42 AM, Daniel Gustafsson <notifications@github.com

**Comment by danielgustafsson** [comment]
> On 08 Sep 2017, at 20:46, Todd Sedano <notifications@github.com> wrote:
> 
> For macOS, what is the preferred way of installing xerxes? brew install
> libxml2 ?

brew install xerces-c
