### ISSUE TITLE
greenplum tutorial does not include pg_hba.conf step for new users

### ISSUE THREAD

**Issue by lisakowen** [greenplum-db/gpdb#3217]
i was trying out a few of the exercises in the faa tutorial on greenplum.org.  i was not using the sandbox VM, but instead a multi-node docker env for my gpdb cluster.

the "create users and roles" exercise creates two users - user1 and user2. the "create and prepare database" exercise includes a step to connect to the tutorial database as user1 (psql -U user1 tutorial).  this fails, as there is no pg_hba.conf entry for user1 in my environment.

would it be reasonable to at least describe the pg_hba.conf entry that exists in the sandbox VM for user*?  this would allow someone to go through at least the first few tutorial exercises in a non-sandbox-VM environment.  (i haven't tried all of the exercises.)

**Comment by lavjain** [comment]
Thanks a lot for bringing this up. It makes perfect sense to describe how to edit pg_hba.conf to allow access to user*.

**Comment by skahler-pivotal** [comment]
There is an addition on greenplum.org now that explains the pg_hba.conf and editing it
