### ISSUE TITLE
starting greenplum is OK，but gpstop is failure.

### ISSUE THREAD

**Issue by pkw1155402** [greenplum-db/gpdb#324]
Hi, friends
I can start greenplum  through gpstart，but one segments can't stop after gpstop.
Anyone can help me?

The operations is at below:

[gpadmin@node1 tmp]$ gpstart
20160129:16:17:51:004185 gpstart:node1:gpadmin-[INFO]:-Starting gpstart with args: 
20160129:16:17:51:004185 gpstart:node1:gpadmin-[INFO]:-Gathering information and validating the environment...
20160129:16:17:51:004185 gpstart:node1:gpadmin-[INFO]:-Greenplum Binary Version: 'postgres (Greenplum Database) 4.3.6.2 build 1'
20160129:16:17:51:004185 gpstart:node1:gpadmin-[INFO]:-Greenplum Catalog Version: '201310150'
20160129:16:17:51:004185 gpstart:node1:gpadmin-[INFO]:-Starting Master instance in admin mode
20160129:16:17:52:004185 gpstart:node1:gpadmin-[INFO]:-Obtaining Greenplum Master catalog information
20160129:16:17:52:004185 gpstart:node1:gpadmin-[INFO]:-Obtaining Segment details from master...
20160129:16:17:52:004185 gpstart:node1:gpadmin-[INFO]:-Setting new master era
20160129:16:17:52:004185 gpstart:node1:gpadmin-[INFO]:-Master Started...
20160129:16:17:52:004185 gpstart:node1:gpadmin-[INFO]:-Shutting down master
20160129:16:17:54:004185 gpstart:node1:gpadmin-[INFO]:---------------------------
20160129:16:17:54:004185 gpstart:node1:gpadmin-[INFO]:-Master instance parameters
20160129:16:17:54:004185 gpstart:node1:gpadmin-[INFO]:---------------------------
20160129:16:17:54:004185 gpstart:node1:gpadmin-[INFO]:-Database                 = template1
20160129:16:17:54:004185 gpstart:node1:gpadmin-[INFO]:-Master Port              = 1928
20160129:16:17:54:004185 gpstart:node1:gpadmin-[INFO]:-Master directory         = /data/master/gpseg-1/
20160129:16:17:54:004185 gpstart:node1:gpadmin-[INFO]:-Timeout                  = 600 seconds
20160129:16:17:54:004185 gpstart:node1:gpadmin-[INFO]:-Master standby           = Off 
20160129:16:17:54:004185 gpstart:node1:gpadmin-[INFO]:---------------------------------------
20160129:16:17:54:004185 gpstart:node1:gpadmin-[INFO]:-Segment instances that will be started
20160129:16:17:54:004185 gpstart:node1:gpadmin-[INFO]:---------------------------------------
20160129:16:17:54:004185 gpstart:node1:gpadmin-[INFO]:-   Host    Datadir                Port
20160129:16:17:54:004185 gpstart:node1:gpadmin-[INFO]:-   node1   /data/primary/gpseg0   40000
20160129:16:17:54:004185 gpstart:node1:gpadmin-[INFO]:-   node2   /data/primary/gpseg1   40000

Continue with Greenplum instance startup Yy|Nn (default=N):
> y
20160129:16:17:55:004185 gpstart:node1:gpadmin-[INFO]:-Commencing parallel segment instance startup, please wait...
... 
20160129:16:17:58:004185 gpstart:node1:gpadmin-[INFO]:-Process results...
20160129:16:17:58:004185 gpstart:node1:gpadmin-[INFO]:-----------------------------------------------------
20160129:16:17:58:004185 gpstart:node1:gpadmin-[INFO]:-   Successful segment starts                                            = 2
20160129:16:17:58:004185 gpstart:node1:gpadmin-[INFO]:-   Failed segment starts                                                = 0
20160129:16:17:58:004185 gpstart:node1:gpadmin-[INFO]:-   Skipped segment starts (segments are marked down in configuration)   = 0
20160129:16:17:58:004185 gpstart:node1:gpadmin-[INFO]:-----------------------------------------------------
20160129:16:17:58:004185 gpstart:node1:gpadmin-[INFO]:-
20160129:16:17:58:004185 gpstart:node1:gpadmin-[INFO]:-Successfully started 2 of 2 segment instances 
20160129:16:17:58:004185 gpstart:node1:gpadmin-[INFO]:-----------------------------------------------------
20160129:16:17:58:004185 gpstart:node1:gpadmin-[INFO]:-Starting Master instance node1 directory /data/master/gpseg-1/ 
20160129:16:17:59:004185 gpstart:node1:gpadmin-[INFO]:-Command pg_ctl reports Master node1 instance active
20160129:16:17:59:004185 gpstart:node1:gpadmin-[INFO]:-No standby master configured.  skipping...
20160129:16:17:59:004185 gpstart:node1:gpadmin-[INFO]:-****Database successfully started**
**[gpadmin@node1 tmp]$ 
[gpadmin@node1 tmp]$ 
[gpadmin@node1 tmp]$ 
[gpadmin@node1 tmp]$ gpstate -s
20160129:16:34:16:006234 gpstate:node1:gpadmin-[INFO]:-Starting gpstate with args: -s
20160129:16:34:16:006234 gpstate:node1:gpadmin-[INFO]:-local Greenplum Version: 'postgres (Greenplum Database) 4.3.6.2 build 1'
20160129:16:34:16:006234 gpstate:node1:gpadmin-[INFO]:-master Greenplum Version: 'PostgreSQL 8.2.15 (Greenplum Database 4.3.6.2 build 1) on x86_64-unknown-linux-gnu, compiled by GCC gcc (GCC) 4.4.2 compiled on Nov 12 2015 23:50:28'
20160129:16:34:16:006234 gpstate:node1:gpadmin-[INFO]:-Obtaining Segment details from master...
20160129:16:34:16:006234 gpstate:node1:gpadmin-[INFO]:-Gathering data from segments...
. 
20160129:16:34:17:006234 gpstate:node1:gpadmin-[INFO]:-----------------------------------------------------
20160129:16:34:17:006234 gpstate:node1:gpadmin-[INFO]:--Master Configuration & Status
20160129:16:34:17:006234 gpstate:node1:gpadmin-[INFO]:-----------------------------------------------------
20160129:16:34:17:006234 gpstate:node1:gpadmin-[WARNING]:-*****************************************************
20160129:16:34:17:006234 gpstate:node1:gpadmin-[WARNING]:-**DATABASE IS PROBABLY UNAVAILABLE
**20160129:16:34:17:006234 gpstate:node1:gpadmin-[WARNING]:-Review Instance Status in log file or screen output for more information
20160129:16:34:17:006234 gpstate:node1:gpadmin-[WARNING]:-*****************************************************
20160129:16:34:17:006234 gpstate:node1:gpadmin-[INFO]:-   Master host                    = node1
20160129:16:34:17:006234 gpstate:node1:gpadmin-[INFO]:-   Master postgres process ID     = 4241
20160129:16:34:17:006234 gpstate:node1:gpadmin-[INFO]:-   Master data directory          = /data/master/gpseg-1
20160129:16:34:17:006234 gpstate:node1:gpadmin-[INFO]:-   Master port                    = 1928
20160129:16:34:17:006234 gpstate:node1:gpadmin-[INFO]:-   Master current role            = dispatch
20160129:16:34:17:006234 gpstate:node1:gpadmin-[INFO]:-   Greenplum initsystem version   = 4.3.6.2 build 1
20160129:16:34:17:006234 gpstate:node1:gpadmin-[INFO]:-   Greenplum current version      = PostgreSQL 8.2.15 (Greenplum Database 4.3.6.2 build 1) on x86_64-unknown-linux-gnu, compiled by GCC gcc (GCC) 4.4.2 compiled on Nov 12 2015 23:50:28
20160129:16:34:17:006234 gpstate:node1:gpadmin-[INFO]:-   Postgres version               = 8.2.15
20160129:16:34:17:006234 gpstate:node1:gpadmin-[INFO]:-   Master standby                 = No master standby configured
20160129:16:34:17:006234 gpstate:node1:gpadmin-[INFO]:-----------------------------------------------------
20160129:16:34:17:006234 gpstate:node1:gpadmin-[INFO]:-Segment Instance Status Report
20160129:16:34:17:006234 gpstate:node1:gpadmin-[INFO]:-----------------------------------------------------
20160129:16:34:17:006234 gpstate:node1:gpadmin-[INFO]:-   Segment Info
20160129:16:34:17:006234 gpstate:node1:gpadmin-[INFO]:-      Hostname                          = node1
20160129:16:34:17:006234 gpstate:node1:gpadmin-[INFO]:-      Address                           = sdw1
20160129:16:34:17:006234 gpstate:node1:gpadmin-[INFO]:-      Datadir                           = /data/primary/gpseg0
20160129:16:34:17:006234 gpstate:node1:gpadmin-[INFO]:-      Port                              = 40000
20160129:16:34:17:006234 gpstate:node1:gpadmin-[INFO]:-   Status
20160129:16:34:17:006234 gpstate:node1:gpadmin-[WARNING]:-   PID                               = Not found                                       <<<<<<<<
20160129:16:34:17:006234 gpstate:node1:gpadmin-[INFO]:-      Configuration reports status as   = Up
20160129:16:34:17:006234 gpstate:node1:gpadmin-[WARNING]:-   **Database status                   = Process error -- database process may be down **  <<<<<<<<
20160129:16:34:17:006234 gpstate:node1:gpadmin-[INFO]:-----------------------------------------------------
20160129:16:34:17:006234 gpstate:node1:gpadmin-[INFO]:-   Segment Info
20160129:16:34:17:006234 gpstate:node1:gpadmin-[INFO]:-      Hostname                          = node2
20160129:16:34:17:006234 gpstate:node1:gpadmin-[INFO]:-      Address                           = sdw2
20160129:16:34:17:006234 gpstate:node1:gpadmin-[INFO]:-      Datadir                           = /data/primary/gpseg1
20160129:16:34:17:006234 gpstate:node1:gpadmin-[INFO]:-      Port                              = 40000
20160129:16:34:17:006234 gpstate:node1:gpadmin-[INFO]:-   Status
20160129:16:34:17:006234 gpstate:node1:gpadmin-[INFO]:-      PID                               = 31565
20160129:16:34:17:006234 gpstate:node1:gpadmin-[INFO]:-      Configuration reports status as   = Up
20160129:16:34:17:006234 gpstate:node1:gpadmin-[INFO]:-      Database status                   = Up
20160129:16:34:17:006234 gpstate:node1:gpadmin-[WARNING]:-*****************************************************
20160129:16:34:17:006234 gpstate:node1:gpadmin-[WARNING]:-DATABASE IS PROBABLY UNAVAILABLE
20160129:16:34:17:006234 gpstate:node1:gpadmin-[WARNING]:-Review Instance Status in log file or screen output for more information
20160129:16:34:17:006234 gpstate:node1:gpadmin-[WARNING]:-*****************************************************
20160129:16:34:17:006234 gpstate:node1:gpadmin-[WARNING]:-*****************************************************
20160129:16:34:17:006234 gpstate:node1:gpadmin-[WARNING]:-Warnings have been generated during status processing
20160129:16:34:17:006234 gpstate:node1:gpadmin-[WARNING]:-Check log file or review screen output
20160129:16:34:17:006234 gpstate:node1:gpadmin-[WARNING]:-*****************************************************
[gpadmin@node1 tmp]$ 
[gpadmin@node1 tmp]$ 
[gpadmin@node1 tmp]$ 
[gpadmin@node1 tmp]$ gpstop
20160129:16:38:30:006576 gpstop:node1:gpadmin-[INFO]:-Starting gpstop with args: 
20160129:16:38:30:006576 gpstop:node1:gpadmin-[INFO]:-Gathering information and validating the environment...
20160129:16:38:30:006576 gpstop:node1:gpadmin-[INFO]:-Obtaining Greenplum Master catalog information
20160129:16:38:30:006576 gpstop:node1:gpadmin-[INFO]:-Obtaining Segment details from master...
20160129:16:38:30:006576 gpstop:node1:gpadmin-[INFO]:-Greenplum Version: 'postgres (Greenplum Database) 4.3.6.2 build 1'
20160129:16:38:30:006576 gpstop:node1:gpadmin-[INFO]:---------------------------------------------
20160129:16:38:30:006576 gpstop:node1:gpadmin-[INFO]:-Master instance parameters
20160129:16:38:30:006576 gpstop:node1:gpadmin-[INFO]:---------------------------------------------
20160129:16:38:30:006576 gpstop:node1:gpadmin-[INFO]:-   Master Greenplum instance process active PID   = 4241
20160129:16:38:30:006576 gpstop:node1:gpadmin-[INFO]:-   Database                                       = template1
20160129:16:38:30:006576 gpstop:node1:gpadmin-[INFO]:-   Master port                                    = 1928
20160129:16:38:30:006576 gpstop:node1:gpadmin-[INFO]:-   Master directory                               = /data/master/gpseg-1/
20160129:16:38:30:006576 gpstop:node1:gpadmin-[INFO]:-   Shutdown mode                                  = smart
20160129:16:38:30:006576 gpstop:node1:gpadmin-[INFO]:-   Timeout                                        = 120
20160129:16:38:30:006576 gpstop:node1:gpadmin-[INFO]:-   Shutdown Master standby host                   = Off
20160129:16:38:30:006576 gpstop:node1:gpadmin-[INFO]:---------------------------------------------
20160129:16:38:30:006576 gpstop:node1:gpadmin-[INFO]:-Segment instances that will be shutdown:
20160129:16:38:30:006576 gpstop:node1:gpadmin-[INFO]:---------------------------------------------
20160129:16:38:30:006576 gpstop:node1:gpadmin-[INFO]:-   Host    Datadir                Port    Status
20160129:16:38:30:006576 gpstop:node1:gpadmin-[INFO]:-   node1   /data/primary/gpseg0   40000   u
20160129:16:38:30:006576 gpstop:node1:gpadmin-[INFO]:-   node2   /data/primary/gpseg1   40000   u

Continue with Greenplum instance shutdown Yy|Nn (default=N):
> y
20160129:16:38:31:006576 gpstop:node1:gpadmin-[INFO]:-There are 0 connections to the database
20160129:16:38:31:006576 gpstop:node1:gpadmin-[INFO]:-Commencing Master instance shutdown with mode='smart'
20160129:16:38:31:006576 gpstop:node1:gpadmin-[INFO]:-Master host=node1
20160129:16:38:31:006576 gpstop:node1:gpadmin-[INFO]:-Commencing Master instance shutdown with mode=smart
20160129:16:38:31:006576 gpstop:node1:gpadmin-[INFO]:-Master segment instance directory=/data/master/gpseg-1/
20160129:16:38:32:006576 gpstop:node1:gpadmin-[INFO]:-Attempting forceful termination of any leftover master process
20160129:16:38:32:006576 gpstop:node1:gpadmin-[INFO]:-Terminating processes for segment /data/master/gpseg-1/
20160129:16:38:32:006576 gpstop:node1:gpadmin-[ERROR]:-**Failed to kill processes for segment /data/master/gpseg-1/: ([Errno 3] No such process)
**20160129:16:38:32:006576 gpstop:node1:gpadmin-[INFO]:-No standby master host configured
20160129:16:38:32:006576 gpstop:node1:gpadmin-[INFO]:-Commencing parallel segment instance shutdown, please wait...
20160129:16:38:32:006576 gpstop:node1:gpadmin-[INFO]:-0.00% of jobs completed
20160129:16:38:42:006576 gpstop:node1:gpadmin-[INFO]:-100.00% of jobs completed
20160129:16:38:42:006576 gpstop:node1:gpadmin-[INFO]:-----------------------------------------------------
20160129:16:38:42:006576 gpstop:node1:gpadmin-[INFO]:-   Segments stopped successfully      = 2
20160129:16:38:42:006576 gpstop:node1:gpadmin-[INFO]:-   Segments with errors during stop   = 0
20160129:16:38:42:006576 gpstop:node1:gpadmin-[INFO]:-----------------------------------------------------
20160129:16:38:42:006576 gpstop:node1:gpadmin-[INFO]:-Successfully shutdown 2 of 2 segment instances 
20160129:16:38:42:006576 gpstop:node1:gpadmin-[INFO]:-Database successfully shutdown with no errors reported
20160129:16:38:42:006576 gpstop:node1:gpadmin-[INFO]:-Cleaning up leftover gpmmon process
20160129:16:38:42:006576 gpstop:node1:gpadmin-[INFO]:-No leftover gpmmon process found
20160129:16:38:42:006576 gpstop:node1:gpadmin-[INFO]:-Cleaning up leftover gpsmon processes
20160129:16:38:43:006576 gpstop:node1:gpadmin-[INFO]:-No leftover gpsmon processes on some hosts. not attempting forceful termination on these hosts
20160129:16:38:43:006576 gpstop:node1:gpadmin-[INFO]:-Cleaning up leftover shared memory
[gpadmin@node1 tm

**Comment by ashwinstar** [comment]
Log says "20160129:16:38:42:006576 gpstop:node1:gpadmin-[INFO]:- Segments stopped successfully = 2" so when you say one segment was not stopped did you see the process running for it after gpstop completed ? (Also, just curious seems you are running 4.3.6.2 version and not master.)

**Comment by kaknikhil** [comment]
> 20160129:16:38:42:006576 gpstop:node1:gpadmin-[INFO]:-Successfully shutdown 2 of 2 segment instances
@pkw1155402  :
* it says here that all the segment instances were successfully stopped . Why do you think that one of the segments was still running? 
* Since you mentioned that gpstart works fine , were you able to access the database after gpstart ?
* Also can you paste the output of "select * from gp_segment_configuration"?

**Comment by kaknikhil** [comment]
Hi @pkw1155402 : since there is no update , I am closing this issue for now. Please reopen the issue if you are still having problems with stopping the cluster.
