### ISSUE TITLE
error while running sudo make on gbdb-master 

### ISSUE THREAD

**Issue by rahulsingh0978** [greenplum-db/gpdb#3254]
In file included from include/reader.h:4:0,
from include/gpreader.h:4,
from src/gpcloud.cpp:25:
include/s3common_headers.h:8:26: fatal error: openssl/hmac.h: No such file or directory

**Comment by hsyuan** [comment]
Did you install openssl?

**Comment by hlinnaka** [comment]
I presume you figured this out eventually, so closing. Feel free to post to gpdb-dev or open a new issue if you still need help.

**Comment by yydzero** [comment]
encounter this issue also, @adam8157 mentioned 'sudo yum install openssl-devel' will solve it.
