### ISSUE TITLE
stanullfrac in pg_statisic is getting NaN values which messes up gp_toolkit view

### ISSUE THREAD

**Issue by lmugnano** [greenplum-db/gpdb#3259]
I have a customer who uses results of gp_toolkit.gp_bloat_expected_pages for other processing.  They are hitting an issue with GPDB5 where that view is returning NaN for the column btdexppages in one of the rows.  I traced the gp_toolkit view and determined that the issue is coming from the pg_statistic table stanullfrac column.  I was also to reproduce the same issue in my local VM and the issue occurs in both our environments on starelid  = 2618.

Can you look into why this value is making it into the pg_statistic table and, if it really is valid in being there, then can we change the gp_toolkit gp_bloat_expected_pages view to handle this value and return a number or null to the caller otherwise we'll have to tell customers that they have to change all there code that use these views to handle the NaN condition.  

I can't think of a reason why NaN would be required to be set in this table so would prefer to see where this is originating from (what is inserting it) and fix it there.

SELECT  stawidth, stanullfrac  FROM pg_statistic pgs where starelid = 2618;

**Comment by hlinnaka** [comment]
This seems to happen, when the sample acquired by ANALYZE consists entirely of values that are considered "too large", and not included in the sample. To reproduce:

```
postgres=# create table foo (t text) distributed randomly;
CREATE TABLE
postgres=# alter table foo  alter column t set storage plain;
ALTER TABLE
postgres=# insert into foo select repeat('x', 10000);
INSERT 0 1
postgres=# analyze foo;
ANALYZE
postgres=# select * from pg_statistic where starelid='foo'::regclass;
 starelid | staattnum | stanullfrac | stawidth | stadistinct | stakind1 | stakind2 | stakind3 | stakind4 | staop1 | staop2 | staop3 | staop4 | stanumbers1 | stanumbers2 | stanumbers3 | stanu
mbers4 | stavalues1 | stavalues2 | stavalues3 | stavalues4 
----------+-----------+-------------+----------+-------------+----------+----------+----------+----------+--------+--------+--------+--------+-------------+-------------+-------------+------
-------+------------+------------+------------+------------
    16420 |         1 |         NaN |        0 |           0 |        0 |        0 |        0 |        0 |      0 |      0 |      0 |      0 |             |             |             |      
       |            |            |            | 
(1 row)

```

**Comment by ivannovick** [comment]
@hlinnaka what would you suggest as a "fix" as this does appear to be a real customer scenario.

**Comment by hlinnaka** [comment]
As a quick work-around, you can fix the stats with:
```
set allow_system_table_mods='dml';
update pg_statistic set stanullfrac=0 where stanullfrac = 'NaN';
```

Off-hand, I'm not sure what the proper fix in code would be, to avoid it from happening in the first place. It doesn't very hard to fix, but someone will need to have a look.

**Comment by hlinnaka** [comment]
Fixed, thanks for the report! The fix will appear in the next 5.X minor version.

**Comment by lmugnano** [comment]
Hi @hlinnaka, once a customer deploys the 5.x release that contains this fix, will re-doing analyze of the impacted tables fix the NaN values that exist in the table or do we need to have them do a one-off update to update the value as per your original work-around?

set allow_system_table_mods='dml';
update pg_statistic set stanullfrac=0 where stanullfrac = 'NaN';

Thanks
