### ISSUE TITLE
make command in gbdb causes this below error

### ISSUE THREAD

**Issue by rahulsingh0978** [greenplum-db/gpdb#3266]
g++ -O3 -std=gnu99  -Wall -Wmissing-prototypes -Wpointer-arith -Wendif-labels -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fno-aggressive-loop-optimizations -Wno-unused-but-set-variable -Wno-address  -L../../src/port -L../../src/port -Wl,--as-needed -Wl,-rpath,'/usr/local/gpdb/lib',--enable-new-dtags -Wl,-E access/SUBSYS.o bootstrap/SUBSYS.o catalog/SUBSYS.o parser/SUBSYS.o commands/SUBSYS.o executor/SUBSYS.o fts/SUBSYS.o lib/SUBSYS.o libpq/SUBSYS.o gp_libpq_fe/SUBSYS.o main/SUBSYS.o nodes/SUBSYS.o optimizer/SUBSYS.o port/SUBSYS.o postmaster/SUBSYS.o regex/SUBSYS.o replication/SUBSYS.o rewrite/SUBSYS.o storage/SUBSYS.o tcop/SUBSYS.o tsearch/SUBSYS.o utils/SUBSYS.o ../../src/timezone/SUBSYS.o cdb/SUBSYS.o gpopt/SUBSYS.o ../../src/port/libpgport_srv.a -lgpopt -lnaucrates -lgpdbcost -lgpos -lxerces-c -lbz2 -lxml2 -lrt -lz -lcrypt -ldl -lm -L/usr/lib/x86_64-linux-gnu -lcurl -lpthread -o postgres
gpopt/SUBSYS.o: In function `gpdxl::CTranslatorRelcacheToDXL::PimdobjCast(gpos::IMemoryPool*, gpmd::IMDId*)':
(.text+0x1b679): undefined reference to `gpmd::CMDCastGPDB::CMDCastGPDB(gpos::IMemoryPool*, gpmd::IMDId*, gpmd::CMDName*, gpmd::IMDId*, gpmd::IMDId*, bool, gpmd::IMDId*)'
gpopt/SUBSYS.o: In function `gpdxl::CTranslatorRelcacheToDXL::PmdpartcnstrFromNode(gpos::IMemoryPool*, gpopt::CMDAccessor*, gpos::CDynamicPtrArray<gpdxl::CDXLColDescr, &(void gpos::CleanupRelease<gpdxl::CDXLColDescr>(gpdxl::CDXLColDescr*))>*, Node*, gpos::CDynamicPtrArray<unsigned int, &(void gpos::CleanupDelete<unsigned int>(unsigned int*))>*, bool)':
(.text+0x1f0e8): undefined reference to `gpmd::CMDPartConstraintGPDB::CMDPartConstraintGPDB(gpos::IMemoryPool*, gpdxl::CDXLNode*, gpos::CDynamicPtrArray<unsigned int, &(void gpos::CleanupDelete<unsigned int>(unsigned int*))>*, bool)'
gpopt/SUBSYS.o: In function `gpdxl::CTranslatorRelcacheToDXL::PmdindexPartTable(gpos::IMemoryPool*, gpopt::CMDAccessor*, LogicalIndexInfo*, gpmd::IMDId*, gpmd::IMDRelation const*)':
(.text+0x20839): undefined reference to `gpmd::CMDIndexGPDB::CMDIndexGPDB(gpos::IMemoryPool*, gpmd::IMDId*, gpmd::CMDName*, bool, gpmd::IMDIndex::EmdindexType, gpmd::IMDId*, bool, gpos::CDynamicPtrArray<unsigned int, &(void gpos::CleanupDelete<unsigned int>(unsigned int*))>*, gpos::CDynamicPtrArray<unsigned int, &(void gpos::CleanupDelete<unsigned int>(unsigned int*))>*, gpos::CDynamicPtrArray<gpmd::IMDId, &(void gpos::CleanupRelease<gpmd::IMDId>(gpmd::IMDId*))>*, gpmd::IMDPartConstraint*)'
gpopt/SUBSYS.o: In function `gpdxl::CTranslatorRelcacheToDXL::Pmdindex(gpos::IMemoryPool*, gpopt::CMDAccessor*, gpmd::IMDId*)':
(.text+0x20eba): undefined reference to `gpmd::CMDIndexGPDB::CMDIndexGPDB(gpos::IMemoryPool*, gpmd::IMDId*, gpmd::CMDName*, bool, gpmd::IMDIndex::EmdindexType, gpmd::IMDId*, bool, gpos::CDynamicPtrArray<unsigned int, &(void gpos::CleanupDelete<unsigned int>(unsigned int*))>*, gpos::CDynamicPtrArray<unsigned int, &(void gpos::CleanupDelete<unsigned int>(unsigned int*))>*, gpos::CDynamicPtrArray<gpmd::IMDId, &(void gpos::CleanupRelease<gpmd::IMDId>(gpmd::IMDId*))>*, gpmd::IMDPartConstraint*)'
gpopt/SUBSYS.o: In function `gpdxl::CTranslatorRelcacheToDXL::Pmdrel(gpos::IMemoryPool*, gpopt::CMDAccessor*, gpmd::IMDId*)':
(.text+0x227b0): undefined reference to `gpmd::CMDRelationGPDB::CMDRelationGPDB(gpos::IMemoryPool*, gpmd::IMDId*, gpmd::CMDName*, bool, gpmd::IMDRelation::Erelstoragetype, gpmd::IMDRelation::Ereldistrpolicy, gpos::CDynamicPtrArray<gpmd::CMDColumn, &(void gpos::CleanupRelease<gpmd::CMDColumn>(gpmd::CMDColumn*))>*, gpos::CDynamicPtrArray<unsigned int, &(void gpos::CleanupDelete<unsigned int>(unsigned int*))>*, gpos::CDynamicPtrArray<unsigned int, &(void gpos::CleanupDelete<unsigned int>(unsigned int*))>*, gpos::CDynamicPtrArray<char, &(void gpos::CleanupDelete<char>(char*))>*, unsigned int, bool, gpos::CDynamicPtrArray<gpos::CDynamicPtrArray<unsigned int, &(void gpos::CleanupDelete<unsigned int>(unsigned int*))>, &(void gpos::CleanupRelease<gpos::CDynamicPtrArray<unsigned int, &(void gpos::CleanupDelete<unsigned int>(unsigned int*))> >(gpos::CDynamicPtrArray<unsigned int, &(void gpos::CleanupDelete<unsigned int>(unsigned int*))>*))>*, gpos::CDynamicPtrArray<gpmd::IMDId, &(void gpos::CleanupRelease<gpmd::IMDId>(gpmd::IMDId*))>*, gpos::CDynamicPtrArray<gpmd::IMDId, &(void gpos::CleanupRelease<gpmd::IMDId>(gpmd::IMDId*))>*, gpos::CDynamicPtrArray<gpmd::IMDId, &(void gpos::CleanupRelease<gpmd::IMDId>(gpmd::IMDId*))>*, gpmd::IMDPartConstraint*, bool)'
gpopt/SUBSYS.o: In function `gpdxl::CTranslatorRelcacheToDXL::Pmdrel(gpos::IMemoryPool*, gpopt::CMDAccessor*, gpmd::IMDId*)':
(.text+0x22902): undefined reference to `gpmd::CMDRelationExternalGPDB::CMDRelationExternalGPDB(gpos::IMemoryPool*, gpmd::IMDId*, gpmd::CMDName*, gpmd::IMDRelation::Ereldistrpolicy, gpos::CDynamicPtrArray<gpmd::CMDColumn, &(void gpos::CleanupRelease<gpmd::CMDColumn>(gpmd::CMDColumn*))>*, gpos::CDynamicPtrArray<unsigned int, &(void gpos::CleanupDelete<unsigned int>(unsigned int*))>*, bool, gpos::CDynamicPtrArray<gpos::CDynamicPtrArray<unsigned int, &(void gpos::CleanupDelete<unsigned int>(unsigned int*))>, &(void gpos::CleanupRelease<gpos::CDynamicPtrArray<unsigned int, &(void gpos::CleanupDelete<unsigned int>(unsigned int*))> >(gpos::CDynamicPtrArray<unsigned int, &(void gpos::CleanupDelete<unsigned int>(unsigned int*))>*))>*, gpos::CDynamicPtrArray<gpmd::IMDId, &(void gpos::CleanupRelease<gpmd::IMDId>(gpmd::IMDId*))>*, gpos::CDynamicPtrArray<gpmd::IMDId, &(void gpos::CleanupRelease<gpmd::IMDId>(gpmd::IMDId*))>*, gpos::CDynamicPtrArray<gpmd::IMDId, &(void gpos::CleanupRelease<gpmd::IMDId>(gpmd::IMDId*))>*, int, bool, gpmd::IMDId*)'
collect2: error: ld returned 1 exit status
Makefile:79: recipe for target 'postgres' failed
make[2]: *** [postgres] Error 1
make[2]: Leaving directory '/usr/local/gpdb-5.0.0-alpha.6/src/backend'
Makefile:17: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/usr/local/gpdb-5.0.0-alpha.6/src'
GNUmakefile:14: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by hlinnaka** [comment]
Sorry for the late response!

This was probably because of a mismatch between the installed ORCA version, and the version that was required by the GPDB code at that time. There has been a lot of changes since, so this issue probably isn't relevant anymore. Closing, but please open a new issue or post to gpdb-dev if you're still having trouble with building GPDB.
