### ISSUE TITLE
vacuum does not update last_vacuumed on system tables on the master

### ISSUE THREAD

**Issue by davecramer** [greenplum-db/gpdb#3275]
last vacuumed is only updated on the segments not on the master

**Comment by asimrp** [comment]
Can you please elaborate, Dave?  What is `last_vacuumed`?  Is it a column in a system catalog?

**Comment by davecramer** [comment]
@asimrp yes it is in pg_stat_user_tables and pg_stat_system_tables.

Currently last_vacuum is only updated on the segments which is useful, a function which went out and queried the segments would be useful. 

Thanks

**Comment by JunfengYang** [comment]
This is already fixed in commit e6f93033289e492beffbf47ef3af53e044f02ecd on master branch.
@gaos1 @baobao0206  Do we need to backport it to 6X and 5X?

**Comment by gaos1** [comment]
@JunfengYang the fix involves catalog change and we cannot backport to 5X and 6X. per discussion with @baobao0206 , we offered workaround in doc to let customer manually get this.

**Comment by asimrp** [comment]
I agree that the need can be served with a simple workaround in back branches.
