### ISSUE TITLE
Rewrite the way a DTM initialization error is logged, to retain file & lineno. 

### ISSUE THREAD

**Issue by Eulerizeit** [greenplum-db/gpdb#3286]
Bumped into an issue that was difficult to track down, where I the system wouldn't allow connections, and all I got on the log was "Unexpected internal error", where the file name and line number of where it came from were rewritten in the master, rendering it useless. So I changed the way such errors during TM initialization are reported, to not be so useless. That resulted in this commit in the iteration_2 branch:
* commit 8dcec3acfa93eaf045df08318cd874c4bfba7679
Author: Heikki Linnakangas <hlinnakangas@pivotal.io>
Date:   Wed Sep 13 15:29:59 2017 +0300

**Comment by hlinnaka** [comment]
Merged the PR, closing.
