### ISSUE TITLE
Fix conflicts in src/backend/postmaster/

### ISSUE THREAD

**Issue by Eulerizeit** [greenplum-db/gpdb#3287]
This commit message I wrote as note to myself explains it:
commit e38a2b34c8d74ab693eec081ee7df80349c2a720
Author: Heikki Linnakangas <hlinnakangas@pivotal.io>
Date:   Wed Sep 13 12:17:19 2017 +0300

   Fix conflicts in src/backend/postmaster/
    
   NOTE: This reverts the check for superuser_reserved_connections back
    the way it is in upstream. It was changed in GPDB, to be
    "ReservedBackends > MaxBackends" rather than "ReservedBackends >= MaxBackends",
    but I don't see how that's more correct or better. I tracked that change in
    the old pre-open-sourcing repository to this commit:
    
   $ git log -w -p -n1 f3e98a1ef5f
    commit f3e98a1ef5fc5915662077b137c563371ea1c0a4
    Author: <redacted to protect the innocent>
    Date:   Mon Apr 6 15:04:33 2009 -0800
    
       Fixed guc check for ReservedBackends.
    
       [git-p4: depot-paths = "//cdb2/main/": change = 33269]
    
   diff --git a/cdb-pg/src/backend/postmaster/postmaster.c b/cdb-pg/src/backend/postmaster/postmaster.c
    index 73da7c98ba..e727b7aeaa 100644
    --- a/cdb-pg/src/backend/postmaster/postmaster.c
    +++ b/cdb-pg/src/backend/postmaster/postmaster.c
    @@ -827,7 +827,7 @@ PostmasterMain(int argc, char *argv[])
            /*
             * Check for invalid combinations of GUC settings.
             */
    -       if (ReservedBackends >= MaxBackends)
    +       if (ReservedBackends > MaxBackends)
            {
                    write_stderr("%s: superuser_reserved_connections must be less than max_connections\n", progname);
                    ExitPostmaster(1);
    
   So, there was no explanation there either.

**Comment by hlinnaka** [comment]
Opened PR for this: https://github.com/greenplum-db/gpdb/pull/3288
