### ISSUE TITLE
to_json() function is not available in GPDB 5.0.0

### ISSUE THREAD

**Issue by mkiyama** [greenplum-db/gpdb#3290]
This hint is returned.
___
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
___

Casting to json data type works.
The function is  documented in the GPDB 5.0.0 docs and is documented in the Postgres docs.

**Comment by Eulerizeit** [comment]
This has been removed from the documentation with https://github.com/greenplum-db/gpdb/pull/3303
