### ISSUE TITLE
plr function with arguments ERROR out

### ISSUE THREAD

**Issue by stanlyxiang** [greenplum-db/gpdb#3298]
pull master code, install plr  gppkg.
I wrote a plr function with arguments and it ERROR out when I select the funtion.
```
regression=# create or replace function r_max(arg1 integer) returns integer as $$                                       return (arg1)
$$ language plr;
CREATE FUNCTION
regression=# select r_max(4); 
ERROR:  cache lookup failed for argument type 413 (plr.c:1187)
CONTEXT:  In PL/R function r_max
```

if the function has no arguments:
```
regression=# create or replace function r_test() returns integer as $$                                                  return (1)                                                                                                              
$$ language plr;
regression=# select r_test();
 r_test
--------
      1
(1 row)
```

no problem with gpdb code tag:5.0.0.

**Comment by hsyuan** [comment]
@zhangh43

**Comment by zhangh43** [comment]
@hsyuan we are checking which commit broke the plr pipeline.
In future, we will run pl related test for every gpdb commits to quickly identify the regression commit

**Comment by hlinnaka** [comment]
@zhangh43, did you figure this out? Is this still broken?

**Comment by yydzero** [comment]
@zhangh43 is this still a problem?

**Comment by HaozhouWang** [comment]
I tested it with the newest plr and gpdb master. This issue has been fixed.
```sql
create or replace function r_max(arg1 integer) returns integer as $$ 
return (arg1)
$$ language plr;

select r_max(4);
 r_max
-------
     4
(1 row)
```

**Comment by hlinnaka** [comment]
> I tested it with the newest plr and gpdb master. This issue has been fixed.

Cool, thanks! Closed.
