### ISSUE TITLE
an unknowed issue.

### ISSUE THREAD

**Issue by bj-wangjunping** [greenplum-db/gpdb#3321]
![default](https://user-images.githubusercontent.com/26620614/30578458-9882f68a-9d46-11e7-8b2a-924ee38bab0b.png)

this is the sql:

SELECT dt AS __timestamp,        count(distinct member_id) FROM da.user_behavior_data WHERE dt >= SUBSTR('2017-09-01 00:00:00',1,10)   AND dt <= SUBSTR('2017-09-19 13:33:47',1,10)   AND project_grade IN (2) GROUP BY dt 

Time used:30s

But,as you see int the query plan,most time be used in " Gather Motion "

Who know this?

Thank you so much!

**Comment by chenmin1992** [comment]
一看就是国人[笑cry]。看执行计划你这个不是浪费在gather motion，是那个表扫描啊，应该优化表扫描！楼主遇到过这个Exception吗？https://github.com/greenplum-db/gpdb/issues/3300

**Comment by hsyuan** [comment]
@chenmin1992 is right. Most of the time is spent on full table scan.

**Comment by vraghavan78** [comment]
Closing this issue since there is no action at this point.
