### ISSUE TITLE
verify changes in src/backend/utils/adt/selfuncs.c

### ISSUE THREAD

**Issue by Eulerizeit** [greenplum-db/gpdb#3340]
In https://github.com/greenplum-db/gpdb/pull/3339 there was a FIXME comment added to the code.  Currently the code works and the tests are green it just needs to be reviewed for a gut check. 

* GPDB_84_MERGE_FIXME: this entire function is a massive conflict
* because of the confusing backports and merges throughout its history.
* At Venky's suggestion we have replaced this section with the 8.4
* logic and removed CDB-specific pieces. Revisit.

**Comment by vraghavan78** [comment]
Did a quick pass. Looks good! Sorry for the delay
