### ISSUE TITLE
Investigate heap_release_fetch function

### ISSUE THREAD

**Issue by Eulerizeit** [greenplum-db/gpdb#3342]
heap_release_fetch was removed in upstream, because it was unused. However, it was still used in one GPDB-specific function, in nbtree.c. Replace the call in nbtree.c with a ReleaseBuffer() + heap_fetch(), and add a GPDB_84_MERGE_FIXME to revisit.

**Comment by berlin-ab** [comment]
The call to `heap_release_fetch` has been replaced with `ReleaseBuffer()` and `heap_fetch()`. We still need to revisit this to see if there is a performance hit by this solution.

**Comment by hlinnaka** [comment]
This hasn't come up in any performance tests, and is going to be refactored heavily with the upcoming PostgreSQL v12 merge and table AM API changes and the contrib/amcheck module. Closing.
