### ISSUE TITLE
A  doubt about gp master node.

### ISSUE THREAD

**Issue by bj-wangjunping** [greenplum-db/gpdb#3355]
HI,when i execute a sql,just like:
_select member_id,mobile from DIM.dim_user t where t.member_id in ('056e6ff9b5264fb09cde91f27892fb4b','056e6ff9b5264fb09cde91f27892fb4b','08492ebdf2d14d58a2ae2d5ee1d24aa0','1404965d0b0e4e1f83ea8c3e7747a7f2','16e0e745a86d4f0e8cc13eeeb01ee81f','2972187aa4394cc09c79364164ed7f46','2972187aa4394cc09c79364164ed7f46','2cb971e7ff9241caba0e0c312c7b11e5','3e472dd369b54952b1ba34fb0871f23d','3e472dd369b54952b1ba34fb0871f23d','3fc7c2d278894326a078148ff826d99d','3fc7c2d278894326a078148ff826d99d',')_

There are hundreds of  values  in this sql for filter，and i find the mater node use too much time do some thing, that means the segment wait a long time until recieve the sql request.

Why  the master node use so much time?

**Comment by hsyuan** [comment]
show me the explain analyze result.

**Comment by bj-wangjunping** [comment]
@hsyuan 
![default](https://user-images.githubusercontent.com/26620614/30733218-aaeb4728-9fa8-11e7-94d1-3a0c41d0cd4d.png) 

thanks

**Comment by hsyuan** [comment]
Did you mean Orca spent a lot of time on generating plan for this query?

**Comment by bj-wangjunping** [comment]
@hsyuan  It is very fast when i  execute "explain select ...." ,but too slow when " explain analyze  select ....",
more than 1 min.

**Comment by bj-wangjunping** [comment]
just now,i use another sql : 
select *  from DIM.dim_user t where t.member_id  =any ('{056e6ff9b5264fb09cde91f27892fb4b,056e6ff9b5264fb09cde91f27892fb4b,.....})

It's very fast.

who can tell me what is the diff between "in“ and  “= any”?

**Comment by hsyuan** [comment]
how fast is it? can you show me both plans? 
there should be no diff  between "in“ and “= any”

**Comment by hsyuan** [comment]
What is your gpdb version? Is it debug build?

**Comment by hsyuan** [comment]
closing this since there is no more response, so no action is required.

**Comment by hsyuan** [comment]
For query `select * from t1 where a = any ('{676938,644105,563810,276810,309612}'::bigint[]);`, we got parse tree like this:
```
:quals
         {SCALARARRAYOPEXPR
         :opno 410
         :opfuncid 467
         :useOr true
         :args (
            {VAR
            :varno 1
            :varattno 1
            :vartype 20
            :vartypmod -1
            :varlevelsup 0
            :varnoold 1
            :varoattno 1
            }
            {CONST
            :consttype 1016
            :consttypmod -1
            :constlen -1
            :constbyval false
            :constisnull false
            :constvalue 64 [ 0 0 0 64 1 0 0 0 0 0 0 0 20 0 0 0 5 0 0 0 1 0 0 0
             74 84 10 0 0 0 0 0 9 -44 9 0 0 0 0 0 98 -102 8 0 0 0 0 0 74 57 4
            0 0 0 0 0 108 -71 4 0 0 0 0 0 ]
            }
         )
         }
      }
```

But for query `select * from t1 where a in ('676938','644105','563810','276810','309612');`, we got the following parse tree for predicates:
```
:quals
         {SCALARARRAYOPEXPR
         :opno 410
         :opfuncid 467
         :useOr true
         :args (
            {VAR
            :varno 1
            :varattno 1
            :vartype 20
            :vartypmod -1
            :varlevelsup 0
            :varnoold 1
            :varoattno 1
            }
            {ARRAY
            :array_typeid 1016
            :element_typeid 20
            :elements (
               {CONST
               :consttype 20
               :consttypmod -1
               :constlen 8
               :constbyval true
               :constisnull false
               :constvalue 8 [ 74 84 10 0 0 0 0 0 ]
               }
               {CONST
               :consttype 20
               :consttypmod -1
               :constlen 8
               :constbyval true
               :constisnull false
               :constvalue 8 [ 9 -44 9 0 0 0 0 0 ]
               }
               {CONST
               :consttype 20
               :consttypmod -1
               :constlen 8
               :constbyval true
               :constisnull false
               :constvalue 8 [ 98 -102 8 0 0 0 0 0 ]
               }
               {CONST
               :consttype 20
               :consttypmod -1
               :constlen 8
               :constbyval true
               :constisnull false
               :constvalue 8 [ 74 57 4 0 0 0 0 0 ]
               }
               {CONST
               :consttype 20
               :consttypmod -1
               :constlen 8
               :constbyval true
               :constisnull false
               :constvalue 8 [ 108 -71 4 0 0 0 0 0 ]
               }
            )
            :multidims false
            }
         )
         }
```
I believe Orca translator in GPDB side spent too much time on translating it.

**Comment by hsyuan** [comment]
Thanks @bj-wangjunping for reporting this issue. This is an Orca translator performance issue.

**Comment by hsyuan** [comment]
Fixed by commit https://github.com/greenplum-db/gpdb/commit/1c82fac22d76492c9392aadc0bc6935fbeb2fd87
