### ISSUE TITLE
Changing the datatype of an external table requires a dummy USING

### ISSUE THREAD

**Issue by hlinnaka** [greenplum-db/gpdb#3356]
This doesn't make much sense:

```
postgres=# alter external  table exttest alter column t type integer;
ERROR:  column "t" cannot be cast to type "pg_catalog.int4"
postgres=# alter external  table exttest alter column t type integer using 123;
ALTER EXTERNAL TABLE
postgres=# 
```

This makes perfect sense for a regular table with data in it. If you change the datatype of a regular table, you must specify how to convert the existing data to match the new datatype, so you have to use a USING clause (unless there's a cast, in which case that is used by default). But an external table doesn't have any data, managed by GPDB, so there's no reason to require a conversion function. In fact, the system will just ignore any USING clause you give.

**Comment by mkiyama** [comment]
Added this to the doc tracker story about the issues w/ ALTER EXTERNAL TABLE
