### ISSUE TITLE
gptransfer utility fails when source and target have different GPHOME path. 

### ISSUE THREAD

**Issue by amanjeetsingh** [greenplum-db/gpdb#3365]
gptransfer picks up GPHOME variable value from the host from where it's called from, and if the two environments have different value of GPHOME, then the utility fails. 

**Following excerpt from gptransfer utility will fail the program as it doesn't meet validation requirements**

 self._gphome = get_gphome()
        if not FileDirExists.remote('remote gphome check',
                                    self._options.source_host, self._gphome):
            raise ProgramArgumentValidationException('GPHOME directory does not exist on %s'
                                                     % self._options.source_host)

In our case, we were migrating data between two GP clusters of different sizes and with different value of GPHOME environment variable. Even though GPHOME is set on each of the two clusters, the program fails with "validation error". 

# SOURCE GREENPLUM
=> python -c "import os; x=os.getenv('GPHOME',None); print(x); exit()"
[ sdw9] /usr/local/greenplum-db/.
[ sdw2] /usr/local/greenplum-db/.
[ sdw8] /usr/local/greenplum-db/.
[ smdw] /usr/local/greenplum-db/.
[sdw11] /usr/local/greenplum-db/.
[ sdw7] /usr/local/greenplum-db/.
[  mdw] /usr/local/greenplum-db/.
[ sdw6] /usr/local/greenplum-db/.
[ sdw1] /usr/local/greenplum-db/.
[ sdw5] /usr/local/greenplum-db/.
[sdw10] /usr/local/greenplum-db/.
[ sdw4] /usr/local/greenplum-db/.
[sdw12] /usr/local/greenplum-db/.
[ sdw3] /usr/local/greenplum-db/.
=> 
 
# TARGET GREENPLUM ENVIRONMENT
gpadmin@gdm : /home/gpadmin # gpssh -f ~/worker-nodes
=> python -c "import os; x=os.getenv('GPHOME',None); print(x); exit()"
[ugpl215.] /usr/local/pivotal/greenplum-db/.
[ugpl219.] /usr/local/pivotal/greenplum-db/.
[ugpl212.] /usr/local/pivotal/greenplum-db/.
[ugpl117.] /usr/local/pivotal/greenplum-db/.
[ugpl211.] /usr/local/pivotal/greenplum-db/.
[ugpl115.] /usr/local/pivotal/greenplum-db/.
[ugpl217.] /usr/local/pivotal/greenplum-db/.
[ugpl116.] /usr/local/pivotal/greenplum-db/.
[ugpl113.] /usr/local/pivotal/greenplum-db/.
[ugpl213.] /usr/local/pivotal/greenplum-db/.
[ugpl119.] /usr/local/pivotal/greenplum-db/.
[ugpl214.] /usr/local/pivotal/greenplum-db/.
[ugpl111.] /usr/local/pivotal/greenplum-db/.
[ugpl114.] /usr/local/pivotal/greenplum-db/.
[ugpl216.] /usr/local/pivotal/greenplum-db/.
[ugpl112.] /usr/local/pivotal/greenplum-db/.
[ugpl218.] /usr/local/pivotal/greenplum-db/.
[ugpl118.] /usr/local/pivotal/greenplum-db/.

Would be good if gptransfer could work across two environments with different values of GPHOME environment variable. 

Thanks

**Comment by funnyxj** [comment]
what is the error log?

**Comment by berlin-ab** [comment]
Feature removed. Closing this issue.
