### ISSUE TITLE
Duplicate NodeTag

### ISSUE THREAD

**Issue by fengttt** [greenplum-db/gpdb#3374]
src/include/nodes/nodes.h

T_TriggerData = 950,

T_CdbExplain_StatHdr = 950,

Need to bump it up a little bit.

**Comment by hsyuan** [comment]
yep, thanks, should bump to 1000 or so.

**Comment by hsyuan** [comment]
Fixed by commit https://github.com/greenplum-db/gpdb/commit/c406a3f0fec6c230bc1359fb5fe0f9cb20c86de2, thanks for reporting.
