### ISSUE TITLE
a typo of 'cdbpath_match_preds_to_partkey_tail' ?

### ISSUE THREAD

**Issue by liruto** [greenplum-db/gpdb#340]
During Looking for an equijoin comparison to the partkey item, a typo results in suboptimal query plan.
An example:

create table t2(tc1 oid, tc2 int) distributd by (tc1);
create table t3(tc1 oid, tc2 int) distributd by (tc1);

mycluster=# explain select * from pg_class left join ( t2 left join t3 on t2.tc1 = t3.tc1) on oid = t2.tc1;
                                             QUERY PLAN                                              
-----------------------------------------------------------------------------------------------------
 Gather Motion 4:1  (slice3; segments: 4)  (cost=0.16..92.94 rows=1830 width=222)
   ->  Hash Left Join  (cost=0.16..92.94 rows=458 width=222)
         Hash Cond: pg_class.oid = t2.tc1
         ->  Redistribute Motion 1:4  (slice1)  (cost=0.00..69.90 rows=1830 width=210)
               Hash Key: pg_class.oid
               ->  Seq Scan on pg_class  (cost=0.00..33.30 rows=1830 width=210)
         ->  Hash  (cost=0.12..0.12 rows=1 width=16)
               ->  Redistribute Motion 4:4  (slice2; segments: 4)  (cost=0.01..0.12 rows=1 width=16)
                     Hash Key: t2.tc1
                     ->  Hash Left Join  (cost=0.01..0.05 rows=1 width=16)
                           Hash Cond: t2.tc1 = t3.tc1
                           ->  Seq Scan on t2  (cost=0.00..0.00 rows=1 width=8)
                           ->  Hash  (cost=0.00..0.00 rows=1 width=8)
                                 ->  Seq Scan on t3  (cost=0.00..0.00 rows=1 width=8)
(14 rows)

"Redistribute Motion 4:4" is redundant, I think. The following plan would be right and more optimal, and should be the intention of the coder, isn't it? The done work was merely a change from "else if (CdbPathLocus_IsHashed(ctx->locus))" to "else if (CdbPathLocus_IsHashedOJ(ctx->locus))", then i got it.

mycluster=# explain select * from pg_class left join ( t2 left join t3 on t2.tc1 = t3.tc1) on oid = t2.tc1;
                                      QUERY PLAN                                       
---------------------------------------------------------------------------------------
 Gather Motion 4:1  (slice2; segments: 4)  (cost=0.09..92.88 rows=1830 width=222)
   ->  Hash Left Join  (cost=0.09..92.88 rows=458 width=222)
         Hash Cond: pg_class.oid = t2.tc1
         ->  Redistribute Motion 1:4  (slice1)  (cost=0.00..69.90 rows=1830 width=210)
               Hash Key: pg_class.oid
               ->  Seq Scan on pg_class  (cost=0.00..33.30 rows=1830 width=210)
         ->  Hash  (cost=0.05..0.05 rows=1 width=16)
               ->  Hash Left Join  (cost=0.01..0.05 rows=1 width=16)
                     Hash Cond: t2.tc1 = t3.tc1
                     ->  Seq Scan on t2  (cost=0.00..0.00 rows=1 width=8)
                     ->  Hash  (cost=0.00..0.00 rows=1 width=8)
                           ->  Seq Scan on t3  (cost=0.00..0.00 rows=1 width=8)
(12 rows)

**Comment by hlinnaka** [comment]
Good catch! Fixed, thanks.
