### ISSUE TITLE
5x stable branch pg_proc bugs

### ISSUE THREAD

**Issue by vitesse-ftian** [greenplum-db/gpdb#3407]
Some entries in the file is plainly wrong, maybe a version mismatch.   I have no idea how the code actually can compile -- maybe the compiler/preprocess has bugs too.   Here is one example,

DATA(insert OID = 3951 (  json_extract_path	        PGNSP PGUID 12 1 0 25 f f t f i  2 0 114 f "114 1009" "{114,1009}" "{i,v}" "{from_json,path_elems}" _null_ json_extract_path - _null_ _null_ n ));

**Comment by vitesse-ftian** [comment]
Hmm, this actually is an interesting one.   How do you plan to upgrade the catalog, for those who already deployed gpdb5?

**Comment by vitesse-ftian** [comment]
Let's look at the one before 3951,

DATA(insert OID = 3950 (  json_array_element_text   PGNSP PGUID 12 1 0  f f t f i  2 25  "114 23" _null_ _null_ 

After PGUID, the data is 12 1 0 25 vs 12 1 0 f 

So there must be some added columns in table pg_proc, whatever 25 means.     Later columns have more mismatches.

**Comment by hlinnaka** [comment]
Ah, I see!

Most of the DATA lines in pg_proc.h have 21 columns, like in PostgreSQL 8.3, even though we have some extra columns in GPDB. This is to make merging and diffing with upstream easier. The trick is the GPDB-specific columns are marked and fivend efaults at the top of pg_proc.h, with the `GPDB_COLUMN_DEFAULT` macros. There's a perl script, process_col_defaults.pl, that processes the file and injects the default values for the missing columns, at compilation time. But some rows that need non-default values for those GPDB-added columns. Those rows have values for all 26 columns. json_extract_path is one of those special cases.

**Comment by vitesse-ftian** [comment]
false alarm?   :-)    Really scary

**Comment by hlinnaka** [comment]
:-). It seems we could use some more comments on this, though. Perhaps add a note in the list of attributes, where the GDPB_COLUMN_DEFAULTs are.

I recently added another mechanism to specify non-default values for those GPDB-added columns. Some functions in pg_proc.h have only 21 columns in the DATA line, but have a separate GPDB_EXTRA_COL() directive before the DATA line to give values for the missing columns. I wonder if we should switch to that mechanism for all of the rows that currently list all 26 columns in the DATA line. Might be less confusing.

**Comment by vitesse-ftian** [comment]
But this is still scary -- so the perl script really handles default cleanly, or, it works just because the default column happens to be an int, followed by a different type bool?   Say if the default column is also a bool,   
12 1 0 f f 
You will have lot of fun deciding if this is 
12 1 0 default f f
or 
12 1 0 f default f

**Comment by hlinnaka** [comment]
The perl script expects all rows have either 21 or 26 columns. If throws an error if it's any other number. So for rows with 21 columns, it injects all the defaults at the right places, and if it has 26 columns, it uses the row as it is.

**Comment by vitesse-ftian** [comment]
Ah, I see.  All or none.  Transactional defaults.  :-)
