### ISSUE TITLE
because there is no code in the ORCA translator to handle the new FILTER expressions, ORCA will just fallback on them

### ISSUE THREAD

**Issue by Eulerizeit** [greenplum-db/gpdb#3428]
After PR https://github.com/greenplum-db/gpdb/pull/3162 Orca falls back to the planner with new Filtering expressions.

**Comment by vraghavan78** [comment]
Since it is a new feature, "cleanly falling back to planner" is a viable alternative as of now. Created a internal tracker story to make sure we track this. Will update GPDB 6.0 docs of unsupported GPORCA feature.
