### ISSUE TITLE
gpssh-exkeys fails with SSHd options hmac digests & kex algorithm 

### ISSUE THREAD

**Issue by phennessy** [greenplum-db/gpdb#3439]
gpssh-exkeys does not support SSH centos7/rhel7 sshd_config options for hmac digests OR kex algorithms. 
These options are not enabled by default in either distro however they seem to appear more often in environments with greater secure requirements.

**Comment by ivannovick** [comment]
@skahler-pivotal any idea on this?

**Comment by skahler-pivotal** [comment]
Have a spot in the backlog to take a look at this.

**Comment by Tylarb** [comment]
This should be fixed with in 5.6.1:
https://gpdb.docs.pivotal.io/560/relnotes/GPDB_561_README.html#topic_cq5_vkf_dbb

```
29089 - gpssh
The Greenplum Database utilities gpssh-exkeys and gpseginstall failed when they were run on a host system running RHEL 7.4 with FIPS enabled. The utilities did not support the FIPS-compatible SSH key exchange algorithm.
```

**Comment by mkiyama** [comment]
I believe, this is the commit in the 5X_STABLE branch
https://github.com/greenplum-db/gpdb/commit/987a651617c22baaa330bc585dfd0a921767f252

Can this issue be closed?

**Comment by doty-pivotal** [comment]
@phennessy, thank you for reporting this issue.  As both @Tylarb and @mkiyama point out, we have updated the version of `paramiko`, the python ssh library we are using.  This update fixed the issues customers were observing on RHEL7 systems that were configured to be FIPS compliant.  We feel that at this time this issue can be closed.  

If this is not the case, we can re-open or create a new issue.  If this happens, we will need to see the error message that you see when running `gpssh-exkeys`, the `sshd_config`, and version of `sshd` that is causing the issue.  We would also need to know if, after exchanging the keys manually, if you continue to get errors when running `gpssh` as well.
