### ISSUE TITLE
Informatica IDR 9_6_4 requires implicit cast from text to int 

### ISSUE THREAD

**Issue by phennessy** [greenplum-db/gpdb#3440]
Informatica IDR 9_6_4 dispatches catalog queries when establishing connections to GP5.0.0 prior to job execution that appear to require the implicit cast of text to int4 & int2. This implicit cast was removed in PostgreSQL 8.3.x and Greenplum 5.0.0 to avoid the potential for wrong results when casting text to a set of datatypes in favor of explicit casts as a best practice.
The catalog query issued by IDR is not configurable by the end user. 
As a workaround the implicit cast may be recreated until the IDR issue is addressed. 
https://github.com/interchange/interchange/blob/master/eg/pg83-implicit-casts.sql

**Comment by lij55** [comment]
You need to add the missing cast function manually in Greenplum5.
