### ISSUE TITLE
add_orca_conan_remote is not idempotent

### ISSUE THREAD

**Issue by goutamtadi1** [greenplum-db/gpdb#3457]
https://github.com/greenplum-db/gpdb/blob/f8d66c155ac46593b9fe7f14ecae9b2bba432a24/concourse/scripts/build_orca.py#L8-L9

Our orca build failed on Concourse and we wanted to debug why and hijacked the concourse container and retried the ORCA build using 
```
python gpdb_src/concourse/scripts/build_orca.py --bintrayRemote=conan-gpdb --bintrayRemoteURL=https://api.bintray.com/conan/greenplum-db/gpdb-oss
```
and we see the error:
```
ERROR: Remote 'conan-gpdb' already exists in remotes (use update to modify)
```
which could be more robust if we make it idempotent for running multiple times.

**Comment by Eulerizeit** [comment]
So, making our utilities and such idempotent is not a design choice GPDB has made up to this point and a function lacking Idempotence is probably a bigger discussion than filing an issue.  

@skahler-pivotal @pivotal-mike

**Comment by hsyuan** [comment]
@bhuvnesh2703 Can you help?

**Comment by bchaudhary** [comment]
In this case it’s pretty simple to check if the remote exists and if not add that else don’t, we could add that.

**Comment by cjcjameson** [comment]
We might get to it in our backlog also, to-be-determined. Not high-priority

Bigger picture, we're starting to work with the existing python scripts in
`concourse/scripts` and they might be becoming the way open-source builds
(on various platforms) are produced. We'll probably encounter a few more
bumps and will look to PR fixes into them.

But if folks have reasons why these python scripts, originally contributed
by those who work on GPORCA to run the build with Conan, should not be used
more widely, do speak up.

**Comment by yydzero** [comment]
Is conan still recommended tools for gpdb to handle dependencies?

**Comment by ivannovick** [comment]
i dont think this is still relevant
