### ISSUE TITLE
Sanitycheck commented out code in bufmask.c

### ISSUE THREAD

**Issue by danielgustafsson** [greenplum-db/gpdb#3483]
This section was commented out during the merge, it needs to be sanitychecked.

``` 56 /* GPDB_84_MERGE_FIXME */
 57 #if 0
 58     /*
 59      * During replay, if the page LSN has advanced past our XLOG record's LSN,
 60      * we don't mark the page all-visible. See heap_xlog_visible() for
 61      * details.
 62      */
 63     PageClearAllVisible(page);
 64 #endif```

**Comment by tvesely** [comment]
We don't seem to have ported the `PD_ALL_VISIBLE` flag, so assuming that flag is not going to be added, it looks like it is proper to remove this from `mask_page_hint_bits`.

`PD_ALL_VISIBLE` appears to be a performance optimization for heap tables. If all the tuples in a page are visible to the system, the page will be marked with `PD_ALL_VISIBLE`. This flag is used in `heapgetpage` to short-circuit visibility checking. I looked at the PostgreSQL upstream code for 8.4, and it looks like it is only being used to mark empty pages, but in the future it should be possible to use it to improve visibility checking for non-empty pages.

Should we be looking into adding this flag?

**Comment by ashwinstar** [comment]
The check was basically changed from `PG_VERSION_NUM >= 80400`.

```
diff --git a/src/backend/access/common/bufmask.c b/src/backend/access/common/bufmask.c
index ef6ca82..66fb1f9 100644
--- a/src/backend/access/common/bufmask.c
+++ b/src/backend/access/common/bufmask.c
@@ -53,7 +53,8 @@ mask_page_hint_bits(Page page)
        PageClearFull(page);
        PageClearHasFreeLinePointers(page);

-#if PG_VERSION_NUM >= 80400
+/* GPDB_84_MERGE_FIXME */
+#if 0
        /*
         * During replay, if the page LSN has advanced past our XLOG record's LSN,
         * we don't mark the page all-visible. See heap_xlog_visible() for
```

So, it seems its sometime in future in 8.4 and for now we have commented it with 0, but should be enabled once `PD_ALL_VISIBLE` makes in.

**Comment by asimrp** [comment]
As has been noted, disabling the call to `PageClearAllVisible()` makes sense for 8.4.  Closing this issue as the FIXME has been analyzed.

**Comment by ashwinstar** [comment]
Taken care by https://github.com/greenplum-db/gpdb/pull/3952
