### ISSUE TITLE
TAP tests enabled in the build

### ISSUE THREAD

**Issue by Eulerizeit** [greenplum-db/gpdb#3491]
Looking through the code it seems as though the config flag that enables the TAP tests to run is the same config flag used in the build. We should not be shipping tests compiled to customers since there is no reason to make sure these are 'safe'. 

Could someone familiar with the TAP tests look into this.

**Comment by yydzero** [comment]
@Eulerizeit Do you mean we are shipping TAP tests in tarball?

**Comment by ashwinstar** [comment]
@macroyuyang please, can you verify if that's not the case and close the issue or fix the same.

**Comment by macroyuyang** [comment]
Close this issue because it seems we don't ship tests complied to customers
