### ISSUE TITLE
  Redistribute Motion execute slow.

### ISSUE THREAD

**Issue by bj-wangjunping** [greenplum-db/gpdb#3515]
![default](https://user-images.githubusercontent.com/26620614/31529687-5011ba7e-b00d-11e7-915d-420fbb8c5c71.png)
Sql:
SELECT level_1 AS level_1,
       product_name AS product_name,
       project_name AS project_name,
       pay_at AS pay_at,
       gmv_time AS gmv_time,
       SUM(order_sub_price)   gmv
FROM da.order_detail_data
WHERE level_1 IN ('DSC',
                  'FWYT',
                  'DLV')
  AND region_name IN ('hangzhou')
  AND is_be_gmv IN (1)
GROUP BY level_1,
         product_name,
         project_name,
         pay_at,
         gmv_time
ORDER BY gmv DESC
LIMIT 5000

**As above ,  Redistribute Motion used more than 2s,(total 2.5s)
How can optimize this sql or greenplum config?
Thanks 。
**

**Comment by pengzhout** [comment]
@bj-wangjunping Actually current explain analyze has some defects, for some operators, like table scan in your case,  it only displays the time consumed by QE who returns the most number of tuples. That means the QE who is slowing the whole query will be hidden by the explain analyze. 

For example:
Create a table with bellow distribution:
```
gpadmin=# select gp_segment_id , * from abc;
 gp_segment_id | c1 | c2
---------------+----+----
             0 |  1 |  0
             0 |  1 |  0
             0 |  1 |  0
             0 |  1 |  0
             0 |  1 |  0
             1 |  3 | 10
(6 rows)
```
And run query 
```
gpadmin=# explain analyze select pg_sleep(c2) from abc;
                                                               QUERY PLAN
----------------------------------------------------------------------------------------------------------------------------------------
 Gather Motion 3:1  (slice1; segments: 3)  (cost=0.00..1.01 rows=1 width=4)
   Rows out:  6 rows at destination with 0.954 ms to first row, 10006 ms to end, start offset by 0.356 ms.
   ->  Seq Scan on abc  (cost=0.00..1.01 rows=1 width=4)
         Rows out:  Avg 3.0 rows x 2 workers.  Max 5 rows (seg0) with 0.062 ms to first row, 0.068 ms to end, start offset by 1.174 ms.
 Slice statistics:
   (slice0)    Executor memory: 322K bytes.
   (slice1)    Executor memory: 167K bytes avg x 3 workers, 167K bytes max (seg0).
 Statement statistics:
   Memory used: 128000K bytes
 Optimizer status: legacy query optimizer
 Total runtime: 10006.708 ms
(11 rows)
```

As you see, the output of analyze did not show that seg1 is slow, this may misguide you that the scan is very fast but the gather motion is slow.

**Comment by pengzhout** [comment]
To identify the problem, I created a patch to display the slowest qe for each operator like
```
gpadmin=# explain analyze select pg_sleep(c2) from abc;
                                                                                 QUERY PLAN
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Gather Motion 3:1  (slice1; segments: 3)  (cost=0.00..1.01 rows=1 width=4)
   Rows out:  6 rows at destination with 1.016 ms to first row, 10006 ms to end, start offset by 5.734 ms. Slowest qExec with 10006 ms.
   ->  Seq Scan on abc  (cost=0.00..1.01 rows=1 width=4)
         Rows out:  Avg 3.0 rows x 2 workers.  Max 5 rows (seg0) with 0.129 ms to first row, 0.134 ms to end, start offset by 6.478 ms. Slowest qExec (seg1) with 10005 ms.
 Slice statistics:
   (slice0)    Executor memory: 322K bytes.
   (slice1)    Executor memory: 167K bytes avg x 3 workers, 167K bytes max (seg0).
 Statement statistics:
   Memory used: 128000K bytes
 Optimizer status: legacy query optimizer
 Total runtime: 10011.943 ms
(11 rows)
```
the patch link is https://gist.github.com/pengzhout/8db275772c7d8531fc1eb21b9aea9611,
let's see which operator node is slowing down your query.

**Comment by pengzhout** [comment]
another way is "set gp_log_interconnect to debug" and check if log files contain too much message like "resending packet (seq"

**Comment by hsyuan** [comment]
closing it, no action is required.
