### ISSUE TITLE
Sub-xid array not cleared in GetSnapshotData() when sharing a local snapshot

### ISSUE THREAD

**Issue by hlinnaka** [greenplum-db/gpdb#3528]
We were seeing failures like this on the 8.4 merge `iteration_3_redux` branch:
```
*** ./expected/appendonly.out	2017-10-15 18:40:31.212406024 +0000
--- ./results/appendonly.out	2017-10-15 18:40:31.240406024 +0000
***************
*** 1225,1238 ****
  IN (SELECT segrelid FROM pg_appendonly WHERE relid IN (SELECT oid FROM pg_class
  WHERE relname='appendonly_subxans_test1'));
     case    | objmod | last_sequence | gp_segment_id 
! -----------+--------+---------------+---------------
!  NormalXid |      0 |             0 |             0
!  NormalXid |      0 |             0 |             1
!  NormalXid |      0 |             0 |             2
!  NormalXid |      1 |           100 |             0
!  NormalXid |      1 |           100 |             1
!  NormalXid |      1 |           100 |             2
! (6 rows)
  
  -- create table in top transaction but first insert in sub-transaction
  BEGIN;
--- 1225,1232 ----
  IN (SELECT segrelid FROM pg_appendonly WHERE relid IN (SELECT oid FROM pg_class
  WHERE relname='appendonly_subxans_test1'));
   case | objmod | last_sequence | gp_segment_id 
! ------+--------+---------------+---------------
! (0 rows)
  
  -- create table in top transaction but first insert in sub-transaction
  BEGIN;

```

The `appendonly` test contains several queries like that, and at random, one of them would fail. When i run the `appendonly` test alone, it always passed, but when together with the other tests in the same group, I was able to reproduce that.

I think the underlying cause was that the sub-transactions array was not being initialized in GetSnapshotData(), in the codepath where it gets the snapshot from the SharedLocalSnapshot slot. I was able to fix that by initializing `subxcnt = -1', meaning "overflowed", in that codepath. See commit https://github.com/greenplum-db/gpdb-postgres-merge/commit/b3cc8119bc968a3cc2125c55970eb19c2a253383.

But I believe this is a pre-existing issue, on GPDB5 (and possible before that). There have been changes to the way snapshots are managed on the `iteration_3_redux` branch, which probably somehow made this happen more frequently, but the subxcnt field isn't reset even on master or GPDB5.

**Comment by yydzero** [comment]
@asimrp is this fixed already?

**Comment by asimrp** [comment]
I haven't seen the `appendonly` test fail like that in recent times.  However, it does not feel right that subxip array is not included in the shared snapshot.  Shouldn't the reader QEs know about their writer's subtransactions, so as the correctly determine visibility?  I think we should take this opportunity to rethink the snapshot sharing idea between multiple processes executing as part of the same session.  We can refer to how this problem is solved in upstream parallel worker framework.

**Comment by ashwinstar** [comment]
https://github.com/asimrp/gpdb/commit/1a83f5507be15fe0011435d0a0a7969296d0433a fixed this issue, hence closing the same.
