### ISSUE TITLE
Explain fails with / with no optimizer.

### ISSUE THREAD

**Issue by karthijrk** [greenplum-db/gpdb#354]
When I tried to explain on some query it fails. Here by attached the mini-repo to reproduce this issue.

@atris  - FYI - iust filed gpdb issue to keep track.

Error snapshot:
![image](https://cloud.githubusercontent.com/assets/5432707/12957531/ecf679dc-cfe1-11e5-9cb4-8ab404b45a53.png)

[dml_join_q09_mini_rep.txt](https://github.com/greenplum-db/gpdb/files/125308/dml_join_q09_mini_rep.txt)

**Comment by hlinnaka** [comment]
This is the same issue as #332

**Comment by vraghavan78** [comment]
Thanks @hlinnaka and @karthijrk

**Comment by karthijrk** [comment]
oh, yes, Its a duplicate (#332). Let me close this issue.
