### ISSUE TITLE
Include Docs Compilation in master pipeline

### ISSUE THREAD

**Issue by cjcjameson** [greenplum-db/gpdb#3545]
Follow-on to #2596, we do want to guard against non-compiling documentation check-ins, and we don't want to validate or tag a release without knowing that the docs successfully compile.

**Comment by mkiyama** [comment]
I tried to add David and mistakenly deleted the other assignees.

**Comment by berlin-ab** [comment]
@mkiyama Is this an issue that we still want, or should it be closed?

**Comment by mkiyama** [comment]
+ @dyozie 
I think this can be closed. There is a docs pipeline that the docs team monitors that compiles the OSS docs

**Comment by dyozie** [comment]
That's right - should be fine to close this.
