### ISSUE TITLE
Map table's filename on segment to table name

### ISSUE THREAD

**Issue by kapustor** [greenplum-db/gpdb#3558]
From version 5.0 naming of datafiles in segment dirs has changed:

_In Greenplum Database 5.0, for the pg_class system catalog table, the relfilenode and (internal) OID values for a given relation are completely decoupled. If you created any scripts that assume relfilenode and OID are the same, then you must modify those scripts. Additionally, any assumptions that you may have made about the equivalency of relfilenodes across the Greenplum Database master and segment hosts are no longer valid. As in previous Greenplum Database releases, a relfilenode is guaranteed to be unique only across a tablespace in Greenplum Database version 5.0._

For now relfilenode in pg_class table are correct only localy on segments. Here is a short example:

```
db_prod=# select oid, relname, relfilenode from pg_class where oid=17442;
  oid  | relname | relfilenode
-------+---------+-------------
 17442 | ttt1    |       17333
(1 row)

db_prod=# \q
[gpadmin@pds-greenplun50-rh5z gpseg3]$ locate 17333
/data1/master/gpseg-1/base/16384/17333

[gpadmin@pds-greenplun50-rh5z gpseg3]$ PGOPTIONS='-c gp_session_role=utility' psql -p 40003 -d db_prod
psql (8.3.23)
Type "help" for help.

db_prod=# select oid, relname, relfilenode from pg_class where oid=17442;
  oid  | relname | relfilenode
-------+---------+-------------
 17442 | ttt1    |       16579
(1 row)

db_prod=# \q
[gpadmin@pds-greenplun50-rh5z gpseg3]$ locate 16579
/data1/mirror/gpseg0/base/16384/16579
/data1/mirror/gpseg1/base/16384/16579
/data1/primary/gpseg0/base/16384/16579
/data1/primary/gpseg1/base/16384/16579
/data2/mirror/gpseg2/base/16384/16579
/data2/mirror/gpseg3/base/16384/16579
/data2/primary/gpseg2/base/16384/16579
/data2/primary/gpseg3/base/16384/16579
```

How can I now map a filename to a table, whoes data it contains?

**Comment by ashwinstar** [comment]
On Wed, Oct 18, 2017 at 9:05 AM, Dmitriy Pavlov <notifications@github.com>
wrote:

> From version 5.0 naming of datafiles in segment dirs has changed:
>
> *In Greenplum Database 5.0, for the pg_class system catalog table, the
> relfilenode and (internal) OID values for a given relation are completely
> decoupled. If you created any scripts that assume relfilenode and OID are
> the same, then you must modify those scripts. Additionally, any assumptions
> that you may have made about the equivalency of relfilenodes across the
> Greenplum Database master and segment hosts are no longer valid. As in
> previous Greenplum Database releases, a relfilenode is guaranteed to be
> unique only across a tablespace in Greenplum Database version 5.0.*
>
> For now relfilename in pg_class table are correct only localy on segments.
> Here is a short example:
>
> `db_prod=# select oid, relname, relfilenode from pg_class where oid=17442;
> oid | relname | relfilenode
> -------+---------+-------------
> 17442 | ttt1 | 17333
> (1 row)
>
> db_prod=# \q
> [gpadmin@pds-greenplun50-rh5z gpseg3]$ locate 17333
> /data1/master/gpseg-1/base/16384/17333
>
> [gpadmin@pds-greenplun50-rh5z gpseg3]$ PGOPTIONS='-c
> gp_session_role=utility' psql -p 40003 -d db_prod
> psql (8.3.23)
> Type "help" for help.
>
> db_prod=# select oid, relname, relfilenode from pg_class where oid=17442;
> oid | relname | relfilenode
> -------+---------+-------------
> 17442 | ttt1 | 16579
> (1 row)
>
> db_prod=# \q
> [gpadmin@pds-greenplun50-rh5z gpseg3]$ locate 16579
> /data1/mirror/gpseg0/base/16384/16579
> /data1/mirror/gpseg1/base/16384/16579
> /data1/primary/gpseg0/base/16384/16579
> /data1/primary/gpseg1/base/16384/16579
> /data2/mirror/gpseg2/base/16384/16579
> /data2/mirror/gpseg3/base/16384/16579
> /data2/primary/gpseg2/base/16384/16579
> /data2/primary/gpseg3/base/16384/16579`
>
> How can I now map a filename to a table, whoes data it contains?
>
The filename maybe different across nodes, using the query

`select gp_segment_id, oid, relname, relfilenode from
gp_dist_random('pg_class');` can get mapping of rename to relfilnode for
each segment. Note gp_segment_id in query corresponds to `content` id in
`select * from gp_segment_configuration` or gpseg0. Primary and mirror pair
will always have same relfilenode.

Just note even before 5.0 this may be the case ts just with 5.0 frequency
is much higher.

**Comment by kapustor** [comment]
Thank you, @ashwinstar , I've test it, everything's ckear now.
