### ISSUE TITLE
View code with ts=4 by default on github

### ISSUE THREAD

**Issue by pivotal-ning-yu** [greenplum-db/gpdb#3571]
Viewing code and PR on github is convenient, however the tabstop width is 8 by default, this sometimes make the code ugly and hard to understand.

As github supports [editorconfig](http://editorconfig.org/) we could makes ts=4 default on github for gpdb, in my personal experiments it works perfectly:

https://github.com/pivotal-ning-yu/gpdb/blob/editorconfig/src/backend/commands/alter.c
https://github.com/pivotal-ning-yu/gpdb/blob/editorconfig/gpMgmt/bin/Makefile

The only change needed is to put a `.editorconfig` file under root dir:
https://github.com/pivotal-ning-yu/gpdb/blob/editorconfig/.editorconfig

Do you think we should put one on gpdb master branch?

**Comment by danielgustafsson** [comment]
> On 19 Oct 2017, at 08:23, Ning Yu <notifications@github.com> wrote:

> Do you think we should put one on gpdb master branch?

Given the amount of code review we perform on Github, it seems like a good idea to me.

**Comment by ashwinstar** [comment]
👍 from me too.

**Comment by pivotal-ning-yu** [comment]
A PR was created for this change, once it got applied to master then all the new PRs based on it will have  ts=4 by default on github.

**Comment by pivotal-ning-yu** [comment]
The PR was merged.

Then I rebased one of my open PR, https://github.com/greenplum-db/gpdb/pull/3474/files, the effect is:
- ts is 4 for the files which are displayed by default, like `resgroupcmds.c`;
- ts is still 8 for the files that are not displayed by default ("Large diffs are not rendered by default."), like `resgroup.c`;

Looks like github's support on editorconfig is not perfect yet, but I think it's still worthy to keep this file, at least it should work for small PRs. Thank you guys, let me close this issue now.

**Comment by danielgustafsson** [comment]
> On 19 Oct 2017, at 10:16, Ning Yu <notifications@github.com> wrote:

> Looks like github's support on editorconfig is not perfect yet, but I think it's still worthy to keep this file, at least it should work for small PRs. Thank you guys, let me close this issue now.

Agreed, some support is better than no support at all IMO.
