### ISSUE TITLE
timezone 'CST' is not recognized correctly in China

### ISSUE THREAD

**Issue by kuien** [greenplum-db/gpdb#3574]
On some platforms, for example, Linux will use CST (China Standard Time) as time string suffix of GMT+8, hence the external log tables in Greenplum will be parsed incorrectly. A simple case to prove it:

```sql
postgres=# select '2017-10-19 18:00 CST'::timestamp with time zone;
timestamptz
-------------------------------
2017-10-19 17:00:00-07
(1 row)
```

 I tracked that change in Postgres:

```
        commit e8dac6f1e09e5bc7604caa6f111d6c80a8b98295
        Author: Tom Lane <tgl@sss.pgh.pa.us>
        Date:   Wed Dec 24 16:35:23 2014 -0500

            Add CST (China Standard Time) to our lists of timezone abbreviations.

            For some reason this seems to have been missed when the lists in
            src/timezone/tznames/ were first constructed ...
```

We need a way to recognize CST for users in China naturally. I have submit a PR on Hawq: https://github.com/apache/incubator-hawq/pull/1292, we may simply set ```timezone_abbreviations = "Asia"``` to achieve it.

If necessary, I'd like to pick it to GP as well.

**Comment by lij55** [comment]
Hi @kuien ,

Could we close this issue?

**Comment by Eulerizeit** [comment]
Fixed with https://github.com/greenplum-db/gpdb/pull/4432 and https://github.com/greenplum-db/gpdb/pull/4646
