### ISSUE TITLE
gpperfmon: gpsmon doesn't send packets in proper order

### ISSUE THREAD

**Issue by jchampio** [greenplum-db/gpdb#3585]
As part of the postgres-merge work, we're running into a [constant failure](https://gpdb.data.pivotal.ci/teams/main/pipelines/postgres_merge/jobs/MM_gpperfmon) of the `MM_gpperfmon` tests. We're pretty certain at this point that gpmmon expects gpmon packets to arrive in a specific order, and gpsmon is not sending them in that order.

For instance, when processing `QUERYSEG` packets, [gpmmon tries to look up a key](https://github.com/greenplum-db/gpdb/blob/master/gpAux/gpperfmon/src/gpmon/gpmon_agg.c#L245) that is only [set when processing `QLOG` packets](https://github.com/greenplum-db/gpdb/blob/master/gpAux/gpperfmon/src/gpmon/gpmon_agg.c#L374). But gpsmon [sends `QUERYSEG` packets first](https://github.com/greenplum-db/gpdb/blob/master/gpAux/gpperfmon/src/gpmon/gpsmon.c#L714), and then [`QLOG` packets later](https://github.com/greenplum-db/gpdb/blob/master/gpAux/gpperfmon/src/gpmon/gpsmon.c#L745). So all of the `QUERYSEG` packets are dropped without action, since we have no keys in the hashtable to match them. The end result is that cpu_skew measurements are not correctly reported (gpmmon complains, `No segments for CPU skew calculation`).

Assuming this root cause is correct, I still have two major open questions:

1) Why is this currently green on master? We have been unable to reproduce a successful test run on a CentOS image with either master or merge code.
2) ~Why are we using UDP if packet order matters?~ (see below)

**Comment by Chibin** [comment]
> Why are we using UDP if packet order matters?

One thing to clarify, UDP is used if it's from the segment to gpsmon (local connection). But the communication from gpsmon to gpmmon uses TCP.

**Comment by jchampio** [comment]
> But the communication from gpsmon to gpmmon uses TCP.

Ah, thanks for pointing that out.
