### ISSUE TITLE
Money type overflow

### ISSUE THREAD

**Issue by vitesse-ftian** [greenplum-db/gpdb#36]
Upstream Postgres Money is 8 bytes.   Greenplum uses 4 bytes.   If running TPCH using MONEY data type, you will see negative amount of sum (overflow).

This is same issue as in HAWQ-19.   Caleb points out the upstream,
https://github.com/postgres/postgres/commit/74a40190aabd27b052ea7a63e93f7ed47743755d#diff-7ddd78dd264f8cf2a62cf572baf90b84

**Comment by hlinnaka** [comment]
Yeah, the money datatype was widened to 64-bits in PostgreSQL 8.3, and greenplum is based on 8.2.

We'll have to deal with this as we merge with 8.3. I'm hoping that we could make pg_upgrade to work for going from 8.2 to 8.3, but that's going to be a problem. 'money' isn't a very widely used datatype though, so perhaps we can simply require dump+restore for any tables using 'money'.

**Comment by yydzero** [comment]
If we decided to ask customer to do this, clear documentation is needed.
To avoid we totally forget this, it is better to record this somewhere,
maybe greenplum.org wiki.

Besides, does anyone know how to contribute to doc/wiki?

Regards,
Yandong

On Tue, Nov 3, 2015 at 4:09 AM, Heikki Linnakangas <notifications@github.com
> wrote:

> Yeah, the money datatype was widened to 64-bits in PostgreSQL 8.3, and
> greenplum is based on 8.2.
>
> We'll have to deal with this as we merge with 8.3. I'm hoping that we
> could make pg_upgrade to work for going from 8.2 to 8.3, but that's going
> to be a problem. 'money' isn't a very widely used datatype though, so
> perhaps we can simply require dump+restore for any tables using 'money'.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/greenplum-db/gpdb/issues/36#issuecomment-153142738>.
>



-- 
Best Regards,
Yandong

**Comment by hlinnaka** [comment]
The patch to widen money datatype to 64-bits has been merged from 8.3, so I'll close this issue.
