### ISSUE TITLE
Insert table more than an hour with a few data

### ISSUE THREAD

**Issue by bj-wangjunping** [greenplum-db/gpdb#3604]
The sql is : 
insert into table t select * from t1 where ....;
Actually,only less than 100 rows need be inserted;
But, this sql will be always running ,even more than an hour, And then  i killed it.

Sometimes,I run "analyze t1;analyze t",that is helpful.

So,why?

**Comment by hsyuan** [comment]
Can you show me the plan before you analyze and after you analyze? Without further information, we can't do RCA.

**Comment by vraghavan78** [comment]
Closing it due to no response. Please re-open it if the issue is reproducible.
