### ISSUE TITLE
Gang/Interconnect leak on certain case

### ISSUE THREAD

**Issue by magi345** [greenplum-db/gpdb#3644]
@pengzhout @xiong-gang 
backend/tcop/pquery PortalRunMulti->ProcessQuery

When I run src/test/regress/sql/plpgsql.sql
The line should produce an error
```
insert into PLine values ('PL.002', '-101', '', 'PS.base.ta2');
2017-10-26 15:04:56.746991 CST,"gpadmin","template1",p2097,th951805760,"10.152.10.131","23960",2017-10-26 15:04:55 CST,75479,con6,cmd434,seg1,,dx275,x75479,sx1,"ERROR","0A000","function cannot execu     te on segment because it accesses relation ""public.pslot""",,,,,"SQL statement ""select * from PSlot where slotname =  $1 ""
2517 PL/pgSQL function ""tg_backlink_set"" line 17 at SQL statement
2518 SQL statement ""SELECT  tg_backlink_set( $1 ,  $2 )""
```

On such case the parent query's ExecutorEnd is not reached, may cause Gang/Interconnect leak.
```
	ExecutorRun(queryDesc, ForwardScanDirection, 0L);

	/* Now take care of any queued AFTER triggers */
	AfterTriggerEndQuery(queryDesc->estate);      <<<<< This function throw the error

	autostats_get_cmdtype(queryDesc, &cmdType, &relationOid);

	/*
	 * Now, we close down all the scans and free allocated resources.
	 */
	ExecutorEnd(queryDesc);
```

**Comment by pengzhout** [comment]
@HaozhouWang , thanks, this is a known issue, current mechanism of cleaning up of dispatch and interconnect context cannot cover all error cases, as @hlinnaka suggested before, we should use
resource owner or similar ways to do the cleanup, we already have a story to track this.

**Comment by yydzero** [comment]
As we have refactor to use Resource Owner, so close this one.
