### ISSUE TITLE
Insert locks whole table when using GPORCA

### ISSUE THREAD

**Issue by Darych** [greenplum-db/gpdb#3674]
I've faced an issue when we tested our app against Greenplum 5.0.0. When our app makes concurrent inserts in different sessions to one table, I receive the following error message:
```
ERROR: deadlock detected
Process 10300 waits for ExclusiveLock on relation 16903 of database 16385; blocked by process 10302.
Process 10302 waits for ExclusiveLock on relation 16903 of database 16385; blocked by process 10300.;
Error while executing the query
SQL statement: INSERT INTO "public"."IDR_RECOVERY" (config, task_id, subtask_id, cycle_id, table_name, status, scn, scn_low) VALUES(?, ?, ?, ?, ?, ?, ?, ?)
```
When I disabled GPORCA on the database, inserts run fine.
I have checked GP logs and compare them with GP 4.2.1.2. Everything is looking similar. Logs from 4.2.1.2 and 5.0.0 attached.

Full versions of Greenplums:
1. PostgreSQL 8.2.15 (Greenplum Database 4.2.1.2 build 2) on x86_64-unknown-linux-gnu, compiled by GCC gcc (GCC) 4.4.2 compiled on Jun 11 2012 16:28:44
2. PostgreSQL 8.3.23 (Greenplum Database 5.0.0 build commit:458a89ba2d99f62ac212f2c87d24addcc5f58b9f) on x86_64-pc-linux-gnu, compiled by GCC gcc 
(GCC) 6.2.0 compiled on Sep  7 2017 20:31:27

Also, I tried to use JDBC client DBeaver. I started 2 sessions and run insert in the 1st session and try to run insert in the 2nd session, but it's blocked and waited for commit in the 1st session.

[GPv4_log.txt](https://github.com/greenplum-db/gpdb/files/1426417/GPv4_log.txt)
[GPv5_log.txt](https://github.com/greenplum-db/gpdb/files/1426418/GPv5_log.txt)

**Comment by Darych** [comment]
Hi, do you need any additional information regarding this issue? Did you reproduce it?
Thanks.

**Comment by Eulerizeit** [comment]
@Darych as per the conversation on slack, could you please update this if `optimizer = off` is a successful workaround?

**Comment by Darych** [comment]
@Eulerizeit will check in week and update.

**Comment by renkemin** [comment]
this problem, i meet too.  i tried you way , but not succeed. i adopt gpdb 5.0.0 build dev.

**Comment by renkemin** [comment]
do you adopt the same version?

**Comment by Darych** [comment]
I haven't tried it yet. Hopefully will try it this month.

**Comment by asimrp** [comment]
I think this should be fixed by https://github.com/greenplum-db/gpdb/pull/4041

**Comment by renkemin** [comment]
thank, i just tried. it succeeded.

**Comment by asimrp** [comment]
Closing as the fix is merged to master.
