### ISSUE TITLE
ERROR:  JOIN qualification may not refer to other relations. (initsplan.c:285)

### ISSUE THREAD

**Issue by hlinnaka** [greenplum-db/gpdb#368]
Bumped into this while debugging issue #332:

```
create table r (a int) distributed by (a);
create table p (a int, b int) distributed by (a);
create table p2 (a int, b int) inherits (p) distributed by (b);

postgres=# explain delete from p where b = 1 or (b=2 and a in (select b from r));
ERROR:  JOIN qualification may not refer to other relations. (initsplan.c:285)
```

**Comment by liruto** [comment]
I looked into this and it seems to be coming from the absence work of subplan's adjust in 'adjust_appendrel_attrs_mutator'.After the following modification, it seems to run well.
```
diff --git a/src/backend/optimizer/prep/prepunion.c b/src/backend/optimizer/prep/prepunion.c
index f3d3b81..acb2287 100644
--- a/src/backend/optimizer/prep/prepunion.c
+++ b/src/backend/optimizer/prep/prepunion.c
@@ -1327,7 +1327,8 @@ adjust_appendrel_attrs_mutator(Node *node, AppendRelInfoContext *ctx)
                        root->glob->subrtables = lappend(root->glob->subrtables, newrtable);
                        newsp->plan_id = list_length(root->glob->subplans);
                }
-               return (Node *) newsp;
+               return expression_tree_mutator(newsp, adjust_appendrel_attrs_mutator,
+                                                                  (void *) ctx);
        }
```
I'm not sure it, without more useful comments, and could anyone explain for me why it may have to create a copy of subplan here? Thanks~

**Comment by hlinnaka** [comment]
A-ha! I'm not sure how exactly that leads to the error, but a "mutator" is always supposed to create a deep copy of the tree, so that's clearly a bug.

**Comment by liruto** [comment]
@hlinnaka The original "_or_" condition contains only one _varno_, with partial adjustment(replace _varno_ 1 with 2), then it has two. So when pushing it down in distribution phrase, at the top of join tree, it was found that "_or_" condition with _'relids=6=2+4'(varno=1,2)_ has some reference error when scope is merely 4(_varno=2_). 

The "_expression mutator_" deals with a shallow copy of _subplan_ at the same time, why not choose it but  a deep copy here? Else, it seems that a copy of _subplan_ has some difference from other expression, why do just here but nothing done in "_expression mutator_"?

**Comment by hlinnaka** [comment]
expression_tree_mutator() creates a deep copy. It creates a shallow copy of the node itself first (FLATCOPY() macro), and then it recurses into every sub-node, and that recursion will recursively create a copy of each subnode. So it's a deep copy.

**Comment by hlinnaka** [comment]
It would be good to grep through all our "mutator" functions to make sure there are no more bugs like this lurking, i.e. ensure that they all create a deep copy.

**Comment by hlinnaka** [comment]
I think I was confused when looking at this back in February. We were constructing a deep copy, like a mutator is supposed to. copyObject() performs a deep copy. That wasn't the problem. However, because we didn't call expression_tree_mutator() on the SubPlan, we were not recursing into its children.

I created PR #1630 to fix this. It's essentially the same as @liruto's fix, but I rearranged the code slightly to avoid unnecessarily creating a second temporary copy of the SubPlan. Thanks for the debugging, @liruto!

**Comment by hlinnaka** [comment]
Committed PR #1630, which fixed this issue. Closing.

**Comment by kelvien** [comment]
I'm experiencing a similar issue at GP v.4.3.11.1
`ERROR:  JOIN qualification may not refer to other relations. (initsplan.c:237)`
My query has multiple subqueries in a `DELETE` statement. What is the version that is going to include this fix ?

**Comment by hlinnaka** [comment]
On 02/09/2017 08:49 PM, Kelvien Hidayat wrote:
> I'm experiencing a similar issue at GP v.4.3.11.1
> `ERROR:  JOIN qualification may not refer to other relations. (initsplan.c:237)`
> My query has multiple subqueries in a `DELETE` statement. What is the
> version that is going to include this fix ?

This should be fixed in the minor version. I guess that would be 4.3.12 
or 4.3.11.2.

- Heikki
