### ISSUE TITLE
Unable to recover a mirror segment since CT_METADATA is not correct on the corresponding primary segment

### ISSUE THREAD

**Issue by cindyzqt** [greenplum-db/gpdb#3707]
Hi guys,

I expand the Greenplum cluster this week. The expansion succeeds. However, after that, a mirror is down. So I try to recover it with gprecoverseg. But it returns the error "Unable to connect to database....".

I've searched online for it. All posts say the reason is CT_METADATA file on the corresponding primary is corrupted. So I check in my cluster and find it's true. But I've tried all suggested solutions as follows, no lucks..

Solution tried 1:
stop the cluster
backup the CT_METADATA file of the primary that have issues
copy CT_METADATA file from other working primary to the primary which has issues
start the cluster
run gprecoverseg
Solution tried 2:
stop the cluster
backup the CT_METADATA file of the primary having issues
remove all files under pg_changetracking under the primary
start the cluster
run gprecoverseg

No matter which method I try, it still returns the same original error. And I find that after stop and start the cluster, the CT_METADATA file of the problem primary gets changed or gone!! So it seems copying the meta file from other primary doesn't work for me! The meta file seemed to be modified during startup.

After restart the cluster, I can see the corresponding mirror is running but the primary just rejects to accept the connection from it since the primary finds itself meta file is not correct...

Here is my configuration. Can anyone please help? The issue is blocking me for 2 days already....

dbid | content | role | preferred_role | mode | status | port  |               hostname               |          address           | replication_port | san_mounts
------+---------+------+----------------+------+--------+-------+--------------------------------------+----------------------------+------------------+------------
  289 |     158 | p    | p              | c    | u      | 40102 | abc-s40.abc | abc-s40.abc |            41102 |
  337 |     158 | m    | m              | r    | d      | 50102 | abc-s43.abc | abc-s43.abc |            51102 |

On the primary s40, the CT_METADATA file either gets changed or gone after restart. Can anyone please help take a look?

Thanks a lot!!

**Comment by cjcjameson** [comment]
@cindyzqt Hi there! Sorry to hear about the issue. Can you tell us more information about your cluster configuration and versions? cc/ @skahler-pivotal

**Comment by skahler-pivotal** [comment]
@cindyzqt it would also help to see the gprecoverseg_YYYYMMDD.log for the point at which you ran gprecoverseg

**Comment by cindyzqt** [comment]
@cjcjameson Thanks a for the reply! the issue is resolved now. i tried to recover the segment incrementally.  but it seems the CT_METADATA is corrupted so it returns "Unable to connect to database". When I tried to do full recovery on the segment, i forgot to check if the replication port was in use. now it's resolved after I killed the other process using the port and then did a full recovery on the failure mirror segment. But I still have a question. There is no much information available online for this CT_METADATA file. May I know what's written in it and how it used? How can I identify if this file is corrupted or not on the segment?

**Comment by cindyzqt** [comment]
@skahler-pivotal Thanks a lot for the reply! the issue is resolved now. But I still have a question. There is no much information available online for this CT_METADATA file. May I know what's written in it and how it's used? How can I identify if this file is corrupted or not on the segment?

**Comment by Eulerizeit** [comment]
@cindyzqt I think the CT_METADATA file has to do with change tracking. @asimrp should be able to provide more context if I'm correct.

**Comment by ashwinstar** [comment]
>> May I know what's written in it and how it's used?

Yes, its used to change track (relfilenode, block-num) while mirror is down on primary. Used then to incrementally recover the mirror by de-duplicating block numbers and transferring only those changed blocks to mirror.

>> How can I identify if this file is corrupted or not on the segment?

There is no external utility / way to find if this file is corrupted, as it being internal system file. gprecoverseg utility when fired will fail incremental recovery and advice to run full if this is found corrupted.

Closing the issue as resolved.
