### ISSUE TITLE
Compile error when enable codegen under Ubuntu 16.04

### ISSUE THREAD

**Issue by JinHai-CN** [greenplum-db/gpdb#3711]
./configure --disable-orca --enable-debug --with-perl --with-python --with-libxml --enable-codegen --prefix=/usr/local/gpdb --enable-profiling --enable-thread-safety

llvm3.7 and clang3.7 already installed by apt-get install.

And three more issues popped during the ./configure phase:
1.
./configure: line 12149: #include: command not found

2. 
configure: WARNING: header file <yaml.h> is not found. disabling transformations for gpfdist.

3. on cmake and llvm part, there is no CMAKE_PREFIX_PATH is this OK?
checking for cmake... /usr/bin/cmake
configure: using cmake version 3.5.1
Executing cmake command : /usr/bin/cmake -DCMAKE_PREFIX_PATH= -DCMAKE_INSTALL_PREFIX=/usr/local/gpdb -DCMAKE_BUILD_TYPE=Debug .
-- Found LLVM 3.7.1
-- Using LLVMConfig.cmake in: /usr/share/llvm-3.7/cmake
-- Configuring done
-- Generating done
-- Build files have been written to: /home/jinhai/development/gpdb/src/backend/codegen

detailed error information as following.
===============================
[  5%] Building CXX object CMakeFiles/SUBSYS.o.dir/codegen_wrapper.cc.o
In file included from /home/jinhai/development/gpdb/src/backend/codegen/include/codegen/utils/gp_codegen_utils.h:21:0,
                 from /home/jinhai/development/gpdb/src/backend/codegen/include/codegen/base_codegen.h:21,
                 from /home/jinhai/development/gpdb/src/backend/codegen/codegen_wrapper.cc:20:
/home/jinhai/development/gpdb/src/backend/codegen/include/codegen/utils/codegen_utils.h: In static member function ‘static bool gpcodegen::codegen_utils_detail::ArithOpMaker<double>::CheckDoubleVal(double, double, double, bool)’:
/home/jinhai/development/gpdb/src/backend/codegen/include/codegen/utils/codegen_utils.h:1463:35: error: ‘isinf’ was not declared in this scope
     bool inf_is_valid = isinf(arg0) || isinf(arg1);
                                   ^
/home/jinhai/development/gpdb/src/backend/codegen/include/codegen/utils/codegen_utils.h:1463:35: note: suggested alternative:
In file included from /usr/include/c++/5/random:38:0,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from /home/jinhai/development/gpdb/src/backend/codegen/include/codegen/utils/annotated_type.h:20,
                 from /home/jinhai/development/gpdb/src/backend/codegen/include/codegen/utils/codegen_utils.h:29,
                 from /home/jinhai/development/gpdb/src/backend/codegen/include/codegen/utils/gp_codegen_utils.h:21,
                 from /home/jinhai/development/gpdb/src/backend/codegen/include/codegen/base_codegen.h:21,
                 from /home/jinhai/development/gpdb/src/backend/codegen/codegen_wrapper.cc:20:
/usr/include/c++/5/cmath:621:5: note:   ‘std::isinf’
     isinf(_Tp __x)
     ^
At global scope:
cc1plus: warning: unrecognized command line option ‘-Wno-deprecated-register’
cc1plus: warning: unrecognized command line option ‘-Wno-c99-extensions’

**Comment by JinHai-CN** [comment]
Solved:
All places using isinf, just add the namespace, which is std::isinf.

**Comment by hsyuan** [comment]
Thanks for your update, @JinHai-CN. I will close this issue, since it was resolved.
