### ISSUE TITLE
BUG gp_workfile_limit_per_segment can not limit KB per segment?

### ISSUE THREAD

**Issue by digoal** [greenplum-db/gpdb#372]
i had set the parameter gp_workfile_limit_per_segment=25165824 (about 24GB), and restart GP.
THE gp env:
1 master
2 segment
70GB data per segment.

when run a TPC-H sql(7.sql), gp use 250GB in $GPDATA/base/xxx/pgsql_tmp/workfile_set* per segment.

and when i see gp_toolkit.gp_workfile_usage_per_segment , there is only 4GB per segment.  

And when disk 100% used, Greenplum raise some error , do not have sufficient freespace for write tmpfile .   

can greenplum limit tmpfile and spillfile at same time.

**Comment by gcaragea** [comment]
Thanks for reporting this. 
How do you measure the 250GB number? 

There is a known issue about the disk space accounting used by gp_toolkit.gp_workfile_usage_per_segment and gp_workfile_limit_per_segment. Basically we measure actual bytes written to disk. But the OS (well the file system code actually) allocates space in blocks, which can be anywhere from 512B to several MB, depending on your file system. 

When GPDB creates very many small files, the OS will allocate a lot more disk space than we report. Can you look at the contents of $GPDATA/base/xxx/pgsql_tmp/workfile_set* and see if you have many files, and if they are small? 

Thanks.

**Comment by vraghavan78** [comment]
@digoal please let me know if this is still an issue.
