### ISSUE TITLE
Question on data storage in GP

### ISSUE THREAD

**Issue by JinHai-CN** [greenplum-db/gpdb#3733]
### Greenplum version or build
5.1
### Step to reproduce the behavior

Question:
I create a table with column storage and insert a lot of data. Can I know which segment server the specific column used?

Thank you.

**Comment by hlinnaka** [comment]
There's a pseudo-column called `gp_segment_id` which tells you that:
```
postgres=# CREATE TABLE foo (id int4);
NOTICE:  Table doesn't have 'DISTRIBUTED BY' clause -- Using column named 'id' as the Greenplum Database data distribution key for this table.
HINT:  The 'DISTRIBUTED BY' clause determines the distribution of data. Make sure column(s) chosen are the optimal data distribution key to minimize skew.
CREATE TABLE
postgres=# INSERT INTO foo VALUES(1);
INSERT 0 1
postgres=# INSERT INTO foo VALUES(2);
INSERT 0 1
postgres=# INSERT INTO foo VALUES(3);
INSERT 0 1
postgres=# select gp_segment_id, * from foo;
 gp_segment_id | id 
---------------+----
             1 |  3
             0 |  1
             0 |  2
(3 rows)

```

**Comment by ashwinstar** [comment]
On Thu, Nov 2, 2017 at 9:05 AM, Jin Hai <notifications@github.com> wrote:

> Greenplum version or build
>
> 5.1
> OS version and uname -a autoconf options used ( config.status --config ) Installation
> information ( pg_config ) Expected behavior Actual behavior Step to
> reproduce the behavior
>
> Question:
> I create a table with column storage and insert a lot of data. Can I know
> which segment server the specific column used?
>
To clarify column storage doesn't not split columns across segment servers.
For a table rows will get distributed across servers based on distribution
specified. Then that row/tuples will get divided into different files on a
segment server. Columnar storage divides the data for every column in
separate file but the row/tuple fully lives on a single segment server.

**Comment by JinHai-CN** [comment]
@ashwinstar 
OK, Now I understand it.  

But I still have more questions on the whole process. After reading the GP document, I know master will send the plan tree to segment server for query. 
- Does segment server still use 'volcano' model to get the tuple one by one even it uses columnar storage engine? 
- When segment server get a tuple, will it cache it and get all tuples together then send them to master server? Or when segment server get a tuple, just send it to master server and doesn't wait all tuples are collected?
- I also notice we can use codegen in GP. I want to know if GP will use codegen to fuse some execution engine operation to accelerate the query process. Am I right?

@hlinnaka 
Thank you for your help.

**Comment by vraghavan78** [comment]
@JinHai-CN we have a prototype implementation of codegen. But after much discussion, we decided to shelf that idea since Postgres is already considering codegen. Currently codegen is an unexercised code in the repro.

**Comment by ashwinstar** [comment]
On Thu, Nov 2, 2017 at 8:00 PM, Jin Hai <notifications@github.com> wrote:
>
> But I still have more questions on the whole process. After reading the GP
> document, I know master will send the plan tree to segment server for query.
>
>    - Does segment server still use 'volcano' model to get the tuple one
>    by one even it uses columnar storage engine?
>
> Yes. Column storage in Greenplum is mainly abstracted at storage level
currently. So, yes mostly everything above storage treats it generically.
Column storage is mainly implemented as of now to optimize and have storage
efficiency like to reduce IO (by either pulling only required columns or
compressing data better based on data type, etc...). Not much leverage is
taken of columnar aspect in execution engine.

>
>    - When segment server get a tuple, will it cache it and get all tuples
>    together then send them to master server? Or when segment server get a
>    tuple, just send it to master server and doesn't wait all tuples are
>    collected?
>
> Segment does buffer and send in batch the tuples to master, not a tuple at
a time.

>
>    - I also notice we can use codegen in GP. I want to know if GP will
>    use codegen to fuse some execution engine operation to accelerate the query
>    process. Am I right?
>
> Venky answered this separately.

**Comment by JinHai-CN** [comment]
@vraghavan78 Thank you for your reply. Then, according to your statement, since I already built codegen part in GP, should I remove it. I mean, will this part code be executed?

@ashwinstar Do you have any document describe the detailed information on current columnar storage like what kind of format, data structure, layout ... One more question is do you have any plan to do the vectorized execution engine on the columnar storage? Thank you for your answer.

**Comment by hsyuan** [comment]
If you set codegen to on, then codegen will be executed. otherwise, not.

**Comment by ashwinstar** [comment]
>> Do you have any document describe the detailed information on current columnar storage like what kind of format, data structure, layout ... 

There is [README](https://github.com/greenplum-db/gpdb/blob/master/src/backend/access/appendonly/README) which provides high level information for append-only. Also, can check [this file](https://github.com/greenplum-db/gpdb/blob/master/src/include/cdb/cdbappendonlystorage_int.h) for data structures involved for AO/CO disk format and these directories have [AO](https://github.com/greenplum-db/gpdb/blob/master/src/backend/access/appendonly) and [CO](https://github.com/greenplum-db/gpdb/blob/master/src/backend/access/aocs) code. Also, attaching block layout pic for a AO/CO block on-disk within a file.
![42696847](https://user-images.githubusercontent.com/11396815/32408780-f28fb1ac-c15b-11e7-840c-18fce1ade674.jpg)
 We will be enhancing README with more extensive content soon.

>> One more question is do you have any plan to do the vectorized execution engine on the columnar storage?

It's not on list of current priority items. Mostly seems better to have codegen first then go for vectorized execution.
