### ISSUE TITLE
Merge removed XLogInitRelationCache 

### ISSUE THREAD

**Issue by Eulerizeit** [greenplum-db/gpdb#3754]
See upstream commit a213f1ee6 for context.

```
GPDB_84_MERGE_FIXME: we removed XLogInitRelationCache from this
code because it doesn't exist in upstream anymore. Does it need a
replacement?
```

[./src/backend/access/transam/xlog.c:7637](https://github.com/greenplum-db/gpdb-postgres-merge/blob/iteration_3_redux/src/backend/access/transam/xlog.c#L7637)
[./src/backend/access/transam/xlog.c:7943](https://github.com/greenplum-db/gpdb-postgres-merge/blob/iteration_3_redux/src/backend/access/transam/xlog.c#L7943)

**Comment by hlinnaka** [comment]
No, it doesn't need a replacement. Removed the GPDB_84_MERGE comments.
