### ISSUE TITLE
Planner estimation math. We did our best to get it working, but it needs a review

### ISSUE THREAD

**Issue by Eulerizeit** [greenplum-db/gpdb#3757]
Planner estimation math. We did our best to get it working, but it needs a review from someone who understands what the estimation is supposed to be doing.

```
/* GPDB_84_MERGE_FIXME: review the estimation math here; 8.4 changed
 the logic around. In particular, we capped the minimum parent_rows at 1,
 whereas upstream will divide by any positive number. We also set
 rel->width to width_avg if the parent_rows are zero, whereas upstream
* sets it to zero.*/

/* GPDB_84_MERGE_FIXME: ensure that this rel->tuples count works for us.*/
/*Set "raw tuples" count equal to "rows" for the appendrel; needed because
 some places assume rel->tuples is valid for any baserel.*/

 /* GPDB_84_MERGE_FIXME: ensure this math is okay compared to before the merge */
```

[./src/backend/optimizer/path/allpaths.c:593](https://github.com/greenplum-db/gpdb-postgres-merge/blob/iteration_3_redux/src/backend/optimizer/path/allpaths.c#L593)
[./src/backend/optimizer/path/allpaths.c:621](https://github.com/greenplum-db/gpdb-postgres-merge/blob/iteration_3_redux/src/backend/optimizer/path/allpaths.c#L621)
[./src/backend/optimizer/plan/createplan.c:4147](https://github.com/greenplum-db/gpdb-postgres-merge/blob/iteration_3_redux/src/backend/optimizer/plan/createplan.c#L4147)

**Comment by vraghavan78** [comment]
allpaths fixed by https://github.com/greenplum-db/gpdb/commit/de5792eed63cf740b3bfa85f8f0e9ee21b9edec6

we have an internal story for createplan.c so closing this issue.
