### ISSUE TITLE
FLOAT[48]PASSBYVAL changes -- reverts GPDB custom logic 

### ISSUE THREAD

**Issue by Eulerizeit** [greenplum-db/gpdb#3758]
FLOAT[48]PASSBYVAL changes. GPDB has substantially changed the logic around by-val vs. by-ref attributes, with the justification that we do not support by-ref attributes in certain situations. Unfortunately this causes large merge headaches. Can we revert our custom logic and simply force ./configure to hardcode the #defines the way we want them?

[./src/backend/optimizer/plan/planagg.c:531](https://github.com/greenplum-db/gpdb-postgres-merge/blob/iteration_3_redux/src/backend/optimizer/plan/planagg.c#L531)
[./src/backend/utils/adt/float.c:2184](https://github.com/greenplum-db/gpdb-postgres-merge/blob/iteration_3_redux/src/backend/utils/adt/float.c#L2184)
[./src/backend/utils/adt/int8.c:684](https://github.com/greenplum-db/gpdb-postgres-merge/blob/iteration_3_redux/src/backend/utils/adt/int8.c#L684)
[./src/backend/utils/fmgr/fmgr.c:2061](https://github.com/greenplum-db/gpdb-postgres-merge/blob/iteration_3_redux/src/backend/utils/fmgr/fmgr.c#L2061)

**Comment by hlinnaka** [comment]
Fixed by commit 154eae38e6 on the `iteration_3_redux` branch.
