### ISSUE TITLE
SELECT INTO changes -- check for correctness

### ISSUE THREAD

**Issue by Eulerizeit** [greenplum-db/gpdb#3759]
We moved the private DR_intorel struct into execdesc.h since the SELECT INTO relation is needed in autostats.c. Check to make sure this is the correct approach.

```
/* CTAS -- see executor/execMain.c for DR_intorel magic
GPDB_84_MERGE_FIXME: is this even close to correct? How do
we test that this is working correctly? */

/* GPDB_84_MERGE_FIXME: this is supposed to be private to
 execMain.c, but postmaster/autostats.c needs the relationOid
 that we can seemingly only get from this struct's .rel field.
 Is this what we want? 
```

[./src/backend/postmaster/autostats.c:206](https://github.com/greenplum-db/gpdb-postgres-merge/blob/iteration_3_redux/src/backend/postmaster/autostats.c#L206)
[./src/include/executor/execdesc.h:277](https://github.com/greenplum-db/gpdb-postgres-merge/blob/iteration_3_redux/src/include/executor/execdesc.h#L277)

**Comment by hlinnaka** [comment]
I moved the struct back to where it is in upstream, and added an accessor function, `GetIntoRelOid()` into execMain.c, that can be used to get the OID from other files.
