### ISSUE TITLE
greenplum uses private function of libapr

### ISSUE THREAD

**Issue by oflebbe** [greenplum-db/gpdb#3768]
### Greenplum version or build
5.1.0

### OS version and uname -a
opensuse

### Expected behavior
Does not compile

### Step to reproduce the behavior

See https://issues.apache.org/jira/browse/BIGTOP-2901  
gpdb uses the private function from libapr  `apr_signal_init` . 
With that function in place bigtop will not have greenplum releases.

**Comment by hlinnaka** [comment]
Thanks for the report, @oflebbe! 

This was fixed in `master` branch (albeit accidentally) in commit 830aad5938f. @weinan003, I think we need to backport that commit to 5X_STABLE.

**Comment by d** [comment]
I believe this was resolved for both 5X_STABLE and master, can someone with a (real) computer close this if that's true?
