### ISSUE TITLE
`gpfdist` used deprecated OpenSSL library on OSX 

### ISSUE THREAD

**Issue by xinzweb** [greenplum-db/gpdb#380]
Current OSX got compilation warning like:

```
gcc -g -O2   -I/usr/bin/..//include/apr-1   -DDARWIN -DSIGPROCMASK_SETS_THREAD_MASK -DDARWIN_10 -I../../../src/include -I. -DGP_VERSION="4.3.99.00 build dev" -DGPFXDIST  -c -o gpfdist.o gpfdist.c
gpfdist.c:1843:11: warning: 'BIO_new' is deprecated: first deprecated in OS X 10.7 [-Wdeprecated-declarations]
                r->io = BIO_new(BIO_f_buffer());
```

This is due to OSX deprecated OpenSSL support by 10.7 and replaced by Common Crypto. Please see http://stackoverflow.com/questions/7406946/why-is-apple-deprecating-openssl-in-macos-10-7-lion.

There are few work arounds like using own installed version of OpenSSL on OSX to get around the deprecation warning like:  http://stackoverflow.com/questions/25264333/deprecated-openssl-functionality

This issue is opened to figure out best way to fix the `deprecated-declarations` warning on OSX for `gpfdist`. Few options could be:
- Install local version of OpenSSL and redirect the compiler to use something under `/usr/local/` other than default OpenSSL libraries by OSX.
- On OSX using Common Crypto other than OpenSSL.

**Comment by hlinnaka** [comment]
On 16/02/16 17:44, Xin Zhang wrote:
> Current OSX got compilation warning like:
>
> ```
> gcc -g -O2   -I/usr/bin/..//include/apr-1   -DDARWIN -DSIGPROCMASK_SETS_THREAD_MASK -DDARWIN_10 -I../../../src/include -I. -DGP_VERSION="4.3.99.00 build dev" -DGPFXDIST  -c -o gpfdist.o gpfdist.c
> gpfdist.c:1843:11: warning: 'BIO_new' is deprecated: first deprecated in OS X 10.7 [-Wdeprecated-declarations]
>                  r->io = BIO_new(BIO_f_buffer());
> ```
>
> This is due to OSX deprecated OpenSSL support by 10.7 and replaced by Common Crypto. Please see http://stackoverflow.com/questions/7406946/why-is-apple-deprecating-openssl-in-macos-10-7-lion.
>
> There are few work arounds like using own installed version of OpenSSL on OSX to get around the deprecation warning like:  http://stackoverflow.com/questions/25264333/deprecated-openssl-functionality
>
> This issue is opened to figure out best way to fix the `deprecated-declarations` warning on OSX for `gpfdist`. Few options could be:
>
> * Install local version of OpenSSL and redirect the compiler to use something under `/usr/local/` other than default OpenSSL libraries by OSX.
> * On OSX using Common Crypto other than OpenSSL.

Hmm. The server code and libpq has the same problem. How does this work 
for libpq? gpfdist should pick up the same configure options as libpq, 
at least after PR #351. So perhaps we should focus on PR #351 and see if 
this gets resolved as a side-effect.

- Heikki

**Comment by atris** [comment]
+1

**Comment by Chibin** [comment]
You will see a similar issue with libpq if you use --with-openssl during the configure.

With PR #351 gpfdist enforces the OpenSSL check, however, gpfdist does not define USE_SSL. This is the reason why you don't see the similar issue with libpq.

Should gpfdist define USE_SSL as well if gpfdist is enabled?

**Comment by hlinnaka** [comment]
On 17/02/16 02:25, Marbin Tan wrote:
> You will see a similar issue with libpq if you use --with-openssl during the configure.

Ah, I see.

> With PR #351 gpfdist enforces the OpenSSL check, however, gpfdist does not define USE_SSL. This is the reason why you don't see the similar issue with libpq.
>
> Should gpfdist define USE_SSL as well if gpfdist is enabled?

Yeah, that would be best.

- Heikki

**Comment by hlinnaka** [comment]
I believe this has been fixed, as we have USE_SSL guards on the OpenSSL-dependent code in gpfdist now. @xinzweb, can you verify and close, please?

**Comment by xinzweb** [comment]
Yes, it's no longer complain. 

```
ccache cc -no-cpp-precomp -O3 -std=gnu99  -Wall -Wmissing-prototypes -Wpointer-arith -Winline -Wendif-labels -Wformat-security -fno-strict-aliasing -fwrapv -Wno-address  -g -O2 -DGPFXDIST -I. -I../../../src/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/libxml2  -I/usr/local/opt/openssl/include -I/usr/local/opt/apr/libexec/include/apr-1  -DDARWIN -DSIGPROCMASK_SETS_THREAD_MASK -DDARWIN_10  -c -o gpfdist.o gpfdist.c
```
