### ISSUE TITLE
Assertion error and server reset when union a heap table and a ON MASTER external web table

### ISSUE THREAD

**Issue by magi345** [greenplum-db/gpdb#3807]
### Greenplum version or build
Build from master commit 640fd9d5898a4937a54d13f4a5b2fd0238f37a27

### OS version and uname -a
CentOS Linux release 7.1.1503 (Core)
Linux mdw.staging.gpcc 3.10.0-229.el7.x86_64 #1 SMP Fri Mar 6 11:36:42 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

### autoconf options used ( config.status --config )
'--prefix=/home/gpadmin/gpdb_master_staging' '--with-includes=/home/gpadmin/orca/2_48_4/include:/home/gpadmin/orca/gpos_home/include:/home/gpadmin/orca/gp-xerces_home/include' '--with-libraries=/home/gpadmin/orca/2_48_4/lib:/home/gpadmin/orca/gpos_home/lib:/home/gpadmin/orca/gp-xerces_home/lib' '--with-pgport=5432' '--with-libedit-preferred' '--with-openssl' '--with-pam' '--with-python' '--with-ldap' '--enable-cassert' '--enable-debug' '--enable-testutils' '--enable-debugbreak' '--enable-depend' '--disable-mapreduce' '--enable-gpfdist' '--enable-orca' '--enable-gpperfmon' '--enable-thread-safety-force' 'CFLAGS=-O3' 'CXXFLAGS=-O3'

### Installation information ( pg_config )
BINDIR = /home/gpadmin/gpdb_master_staging/bin
DOCDIR = /home/gpadmin/gpdb_master_staging/share/doc/postgresql
HTMLDIR = /home/gpadmin/gpdb_master_staging/share/doc/postgresql
INCLUDEDIR = /home/gpadmin/gpdb_master_staging/include
PKGINCLUDEDIR = /home/gpadmin/gpdb_master_staging/include/postgresql
INCLUDEDIR-SERVER = /home/gpadmin/gpdb_master_staging/include/postgresql/server
LIBDIR = /home/gpadmin/gpdb_master_staging/lib
PKGLIBDIR = /home/gpadmin/gpdb_master_staging/lib/postgresql
LOCALEDIR = /home/gpadmin/gpdb_master_staging/share/locale
MANDIR = /home/gpadmin/gpdb_master_staging/share/man
SHAREDIR = /home/gpadmin/gpdb_master_staging/share/postgresql
SYSCONFDIR = /home/gpadmin/gpdb_master_staging/etc/postgresql
PGXS = /home/gpadmin/gpdb_master_staging/lib/postgresql/pgxs/src/makefiles/pgxs.mk
CONFIGURE = '--prefix=/home/gpadmin/gpdb_master_staging' '--with-includes=/home/gpadmin/orca/2_48_4/include:/home/gpadmin/orca/gpos_home/include:/home/gpadmin/orca/gp-xerces_home/include' '--with-libraries=/home/gpadmin/orca/2_48_4/lib:/home/gpadmin/orca/gpos_home/lib:/home/gpadmin/orca/gp-xerces_home/lib' '--with-pgport=5432' '--with-libedit-preferred' '--with-openssl' '--with-pam' '--with-python' '--with-ldap' '--enable-cassert' '--enable-debug' '--enable-testutils' '--enable-debugbreak' '--enable-depend' '--disable-mapreduce' '--enable-gpfdist' '--enable-orca' '--enable-gpperfmon' '--enable-thread-safety-force' 'CFLAGS=-O3' 'CXXFLAGS=-O3'
CC = gcc
CPPFLAGS = -D_GNU_SOURCE -I/home/gpadmin/gpdb_master_staging/include
CFLAGS = -O3 -std=gnu99 -Wall -Wmissing-prototypes -Wpointer-arith -Wendif-labels -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fno-aggressive-loop-optimizations -Wno-unused-but-set-variable -Wno-address -g -ggdb -I/home/gpadmin/gpdb_master_staging/include
CFLAGS_SL = -fpic
LDFLAGS = -Wl,--as-needed -Wl,-rpath,'/home/gpadmin/gpdb_master_staging/lib',--enable-new-dtags -L/home/gpadmin/gpdb_master_staging/lib
LDFLAGS_SL =
LIBS = -lpgport -lgpopt -lnaucrates -lgpdbcost -lgpos -lxerces-c -lpam -lrt -lcrypt -ldl -lm -L/home/gpadmin/gpdb_master_staging/lib
VERSION = PostgreSQL 8.4devel

### Expected behavior
no exception

### Actual behavior
exception happened and server reset

### Step to reproduce the behavior
template1=# CREATE TABLE test1 (id int);
NOTICE:  Table doesn't have 'DISTRIBUTED BY' clause -- Using column named 'id' as the Greenplum Database data distribution key for this table.
HINT:  The 'DISTRIBUTED BY' clause determines the distribution of data. Make sure column(s) chosen are the optimal data distribution key to minimize skew.
CREATE TABLE
template1=# CREATE EXTERNAL WEB TABLE test2 (id int) EXECUTE 'echo 1 2> /dev/null || true' ON MASTER FORMAT 'csv' (delimiter E',');
CREATE EXTERNAL TABLE
template1=#
template1=# (SELECT 1 FROM test1 LIMIT 1)
template1-# union
template1-# (SELECT 2 FROM test2 LIMIT 1);
FATAL:  Unexpected internal error (cdbsetop.c:174)
DETAIL:  FailedAssertion("!(subplanflow->flotype == FLOW_SINGLETON && subplanflow->segindex == 0)", File: "cdbsetop.c", Line: 174)
HINT:  Process 17284 will wait for gp_debug_linger=120 seconds before termination.
Note that its locks and other resources will not be released until then.
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
The connection to the server was lost. Attempting reset: Succeeded.

@adam8157

**Comment by hlinnaka** [comment]
Reproducible on 5X_STABLE as well.

**Comment by adam8157** [comment]
Reproduced on 5X_STABLE, please noted, it only fails at the first time. You might need to dropdb then createdb to reproduce.

**Comment by magi345** [comment]
@hsyuan @vraghavan78

**Comment by hsyuan** [comment]
can't reproduce it on master.

**Comment by magi345** [comment]
It is not reproducable by installing gpdb release from PivNet.
However, it happens on my built-from-source gpdb installation, with --enable-debug and --enable-cassert on.

**Comment by hlinnaka** [comment]
Fixed in master and 5X_STABLE now.

**Comment by magi345** [comment]
Thanks a lot for addressing this issue
