### ISSUE TITLE
Assertion failure in reorder_pathkeys()

### ISSUE THREAD

**Issue by hlinnaka** [greenplum-db/gpdb#3808]
### Greenplum version or build
Checkout from master

### Expected behavior

Works on 5X_STABLE:
```
postgres=# create table foo (a int4, b int4) distributed by (a);
CREATE TABLE
postgres=# SELECT a, b                       
FROM foo
WHERE a = 300
GROUP BY CUBE((a),(b));
 a | b 
---+---
(0 rows)
```

### Actual behavior

```
postgres=# SELECT a, b                                          
FROM foo
WHERE a = 300
GROUP BY CUBE((a),(b));
FATAL:  Unexpected internal error (plangroupext.c:245)
DETAIL:  FailedAssertion("!(pos < numgrpkeys)", File: "plangroupext.c", Line: 245)
```

It seems that the `reorder_pathkeys` function doesn't work, when the path key doesn't contain all the grouping columns. In this query, because `a` is a constant, it is left out of the path key.

**Comment by ashwinstar** [comment]
Actually close the issue now as previously intended.
