### ISSUE TITLE
`--enable-orca` build failed with `HMIUl` unknown type

### ISSUE THREAD

**Issue by xinzweb** [greenplum-db/gpdb#381]
I saw following error message when `configure` with `--enable-orca`, and then `make`:
```
../../../../src/include/gpopt/translate/CTranslatorUtils.h:323:64: error: unknown type name 'HMIUl'
                        DrgPul *PdrgpulColIds(IMemoryPool *pmp, List *plTargetList, HMIUl *phmiulAttnoColId);
```

I was able to build a week ago, anybody hit similar issue? What's potential fix for this one? Thanks.

**Comment by hlinnaka** [comment]
On 16/02/16 18:29, Xin Zhang wrote:
> I saw following error message when `configure` with `--enable-orca`, and then `make`:
> ```
> ../../../../src/include/gpopt/translate/CTranslatorUtils.h:323:64: error: unknown type name 'HMIUl'
>                          DrgPul *PdrgpulColIds(IMemoryPool *pmp, List *plTargetList, HMIUl *phmiulAttnoColId);
> ```
>
> I was able to build a week ago, anybody hit similar issue? What's potential fix for this one? Thanks.

Make sure you're using a recent-enough version of ORCA. Commit 
1c8745ec19431e7790b7e844adee9252800a53f8 and the corresponding commit in 
ORCA, moved the typedef for HMIUl from a header file in GPDB to a header 
file in ORCA.

- Heikki

**Comment by xinzweb** [comment]
Thanks a lot @hlinnaka. That's the problem. All compiled great after I synced the GPORCA. Thanks.
