### ISSUE TITLE
Remove walk around of gpfdist '--sslclean' option on AIX

### ISSUE THREAD

**Issue by lij55** [greenplum-db/gpdb#3831]
### Greenplum version or build
GPDB/gpfdist 5.x, 6.x

## description

* Figure out if --sslclean is actually needed anywhere anymore.
* If it is still needed, figure out what exactly the problem is that it's working around.
* Then figure out if we can fix whatever that problem is, properly, without resorting to a flag like --sslclean.
* If that fails, then document that problem, and how the --sslclean helps with that, in the help message.

**Comment by hlinnaka** [comment]
The '--sslclean' option was removed in commit d94bebb5053f521cd8af01b2463ac5ea5a797a79. Closing.

**Comment by lij55** [comment]
Thanks, Heikki!
