### ISSUE TITLE
Replay of appendonly insert records should behave similar to heap

### ISSUE THREAD

**Issue by asimrp** [greenplum-db/gpdb#3843]
`ao_insert_replay()` behaves similar to the heap counterpart if the underlying segment file does not exist.  It, however, fails the xlog replay with `elog(ERROR)` if `seek()` to the eof in the insert xlog recrod fails.  Heap redo routines on the other hand, treat the seek failure identical to the case when file doesn't exist.  The replay continues and an entry is made in invalid page table.  Is there is reason why replay of appendonly insert record needs to differ here?

**Comment by asimrp** [comment]
Based on conversation with @ashwinstar the following case illustrates why replay of AO insert records must not halt the recovery with `elog(ERROR)`.
```SQL
begin;
insert into ao_table ...; -- EOF of AO segment file extended from, say, 100 to 200
-- checkpoint / last restart point is updated to an LSN after the above AO insert record.
insert into ao_table ...; -- EOF extended further from 200 to 300
abort;
vacuum ao_table; -- The AO segment file truncated to EOF 100
```
If standby restarts after replaying the AO truncate record emitted by `vacuum`, it will resume WAL replay from last restart point and try to replay AO insert record.  The seek to EOF 200 will fail because the file is truncated to EOF 100.

Therefore, AO insert replay should record the segment file and the EOF into the invalid page table.  Upon replaying a truncate record, all entries in the invalid page table having EOF greater than the truncate EOF can be forgotten.

**Comment by ashwinstar** [comment]
Actually its reverse, HEAP used to work this way before 8.4 merge.
```
/*                                                                                                                                                                                  
 * XLogReadBuffer                                                                                                                                                                   
 *              Read a page during XLOG replay                                                                                                                                     * If the page doesn't exist or contains zeroes, we return InvalidBuffer.                                                                                                           
 * In this case the caller should silently skip the update on this page.                                                                                                            
 * (In this situation, we expect that the page was later dropped or truncated.                                                                                                      
 * If we don't see evidence of that later in the WAL sequence, we'll complain                                                                                                       
 * at the end of WAL replay.)                                                                                                                                                       
```
and since 8.4 and onwards it says
```
    /*                                                                                                                                                                              
     * Create the target file if it doesn't already exist.  This lets us cope                                                                                                       
     * if the replay sequence contains writes to a relation that is later                                                                                                           
     * deleted.  (The original coding of this routine would instead suppress                                                                                                        
     * the writes, but that seems like it risks losing valuable data if the                                                                                                         
     * filesystem loses an inode during a crash.  Better to write the data                                                                                                          
     * until we are actually told to delete the file.)                                                                                                                              
     */
```
So, essentially HEAP now starts working similar to AO and both behave similarly.
Also, important to note in case of AO the way seek it performed during replay, it not going to fail if file doesn't have that much data yet. As the way seek works irrespective of the length of file will seek to that offset from requested position and write the data (sure file will have hole in it for this case) . But it will not result in seek failure as such. We will write the data and if truncation has happened then will happen again during recovery. Hence nothing needs to be taken care for this issue.
