### ISSUE TITLE
make: *** [create-demo-cluster] Error 

### ISSUE THREAD

**Issue by dhcn** [greenplum-db/gpdb#3858]
### Greenplum version or build
git hub current code when this issue is posted
### OS version and uname -a
Linux iZ2zee9bjg74lkb535ye09Z 4.4.0-62-generic #83-Ubuntu SMP Wed Jan 18 14:10:15 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
### Installation information ( pg_config )
BINDIR = /usr/local/gpdb/bin
DOCDIR = /usr/local/gpdb/share/doc/postgresql
HTMLDIR = /usr/local/gpdb/share/doc/postgresql
INCLUDEDIR = /usr/local/gpdb/include
PKGINCLUDEDIR = /usr/local/gpdb/include/postgresql
INCLUDEDIR-SERVER = /usr/local/gpdb/include/postgresql/server
LIBDIR = /usr/local/gpdb/lib
PKGLIBDIR = /usr/local/gpdb/lib/postgresql
LOCALEDIR = /usr/local/gpdb/share/locale
MANDIR = /usr/local/gpdb/share/man
SHAREDIR = /usr/local/gpdb/share/postgresql
SYSCONFDIR = /usr/local/gpdb/etc/postgresql
PGXS = /usr/local/gpdb/lib/postgresql/pgxs/src/makefiles/pgxs.mk
CONFIGURE = '--with-perl' '--with-python' '--with-libxml' '--with-gssapi' '--prefix=/usr/local/gpdb'
CC = gcc
CPPFLAGS = -D_GNU_SOURCE -I/usr/local/gpdb/include
CFLAGS = -O3 -std=gnu99 -Wall -Wmissing-prototypes -Wpointer-arith -Wendif-labels -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fno-aggressive-loop-optimizations -Wno-unused-but-set-variable -Wno-address -I/usr/local/gpdb/include
CFLAGS_SL = -fpic
LDFLAGS = -Wl,--as-needed -Wl,-rpath,'/usr/local/gpdb/lib',--enable-new-dtags -L/usr/local/gpdb/lib
LDFLAGS_SL = 
LIBS = -lpgport -lgpopt -lnaucrates -lgpdbcost -lgpos -lxerces-c -lxml2 -lrt -lgssapi_krb5 -lcrypt -ldl -lm -L/usr/local/gpdb/lib
VERSION = PostgreSQL 8.4devel
### Expected behavior
make create-demo-cluster
### Actual behavior
make create-demo-cluster
make -C gpAux/gpdemo create-demo-cluster
make[1]: Entering directory '/root/gpdb_src/gpAux/gpdemo'
======================================================================
            ______  _____  ______  _______ _______  _____
           |  ____ |_____] |     \ |______ |  |  | |     |
           |_____| |       |_____/ |______ |  |  | |_____|

----------------------------------------------------------------------

  This is a demo of the Greenplum Database system.  We will create
  a cluster installation with master and 6 segment instances
  (3 primary & 3 mirror).

    GPHOME ................. : /usr/local/gpdb
    MASTER_DATA_DIRECTORY .. : /root/gpdb_src/gpAux/gpdemo/datadirs/qddir/demoDataDir-1

    MASTER PORT (PGPORT) ... : 15432
    SEGMENT PORTS .......... : 25432 25433 25434 25435 25436 25437 25438 25439 25440 25441 25442 25443

  NOTE(s):

    * The DB ports identified above must be available for use.
    * An environment file gpdemo-env.sh has been created for your use.

======================================================================

==========================================================================================
executing:
  /usr/local/gpdb/bin/gpinitsystem -a -c clusterConfigFile -l /root/gpdb_src/gpAux/gpdemo/datadirs/gpAdminLogs ""
==========================================================================================

20171112:19:41:22:024826 gpinitsystem:iZ2zee9bjg74lkb535ye09Z:root-[INFO]:-Checking configuration parameters, please wait...
20171112:19:41:22:gpinitsystem:iZ2zee9bjg74lkb535ye09Z:root-[FATAL]:-Unable to run this script as root Script Exiting!
========================================
gpinitsystem returned: 2
========================================

======================================================================
                           OPTIMIZER STATE
----------------------------------------------------------------------
  Optimizer state .. : psql: could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/tmp/.s.PGSQL.15432"?
======================================================================

psql: could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/tmp/.s.PGSQL.15432"?
======================================================================

Makefile:48: recipe for target 'create-demo-cluster' failed
make[1]: *** [create-demo-cluster] Error 2
make[1]: Leaving directory '/root/gpdb_src/gpAux/gpdemo'
GNUmakefile:189: recipe for target 'create-demo-cluster' failed
make: *** [create-demo-cluster] Error 2

**Comment by dhcn** [comment]
add new user to Compile and install

**Comment by d** [comment]
As a convention (and opinion) Postgres (and hence Greenplum) refuses to run as UID 0. This is behaving as expected. Closing.

**Comment by vishal2601** [comment]
Dont run the script with root user. clone the project inside /home/gpadmin directory and then compile the project.
