### ISSUE TITLE
nodeAssertOp test condition

### ISSUE THREAD

**Issue by vitesse-ftian** [greenplum-db/gpdb#3864]
### Greenplum version or build
master

### Step to reproduce the behavior
nodeAssertOp.c line 67, it says if the predicate is evaluated to NOT NULL AND FALSE, then throw exception.   This is a very strange test for not true -- shouldn't be NULL OR FALSE?

**Comment by hsyuan** [comment]
hmm, it looks weird, we will take a look.

**Comment by yydzero** [comment]
@vitesse-ftian is this still an issue on latest master?

**Comment by bhuvnesh2703** [comment]
A null could be returned in case of strict function with NULL input arguments. In those cases isNull as marked as true, for other's where the function is really evaluated it marks isNull as false, so technically it just says that error out only when the function is not strict and the assert condition evaluates to false.
