### ISSUE TITLE
gpperfmon_install does not use port for creating the database

### ISSUE THREAD

**Issue by davecramer** [greenplum-db/gpdb#3867]
### Greenplum version or build
5.1.0
### OS version and uname -a
centos
### Expected behavior
should use port when it tries to create the database
### Actual behavior
does not
### Step to reproduce the behavior
install gpdb on any port but 5432
execute gpperfmon_install --enable --password changeme --port 15432

fix is in gpperfmon_install

cmd = Command("PGPORT=%d createdb gpperfmon", % (options.port) )
    commands.append(cmd)
    cmd = Command("PGPORT=%d psql -f %s/lib/gpperfmon/gpperfmon.sql gpperfmon" % (options.port, gphome))
    commands.append(cmd)

**Comment by cjcjameson** [comment]
Thanks for calling this out -- @kongyew @Chibin @skahler-pivotal for visibility

**Comment by ivannovick** [comment]
this utility is deprecated
