### ISSUE TITLE
compiling gphdfs (gpdb/gpAux/extensions/gphdfs)

### ISSUE THREAD

**Issue by spothineni** [greenplum-db/gpdb#388]
Hi,
We are trying to compile the code of gphdfs we have following problem, I think the repo url doesn't exists any more.

Please let us know if there is any work around.

Thanks
Sudhir

[ivy:retrieve]
[ivy:retrieve] :: problems summary ::
[ivy:retrieve] :::: WARNINGS
[ivy:retrieve]  Host repo.eng.pivotal.io not found. url=https://repo.eng.pivotal.io/artifactory/gpdb-ext-release-local/apache/hadoop-core/0.20.1-gphdce-1.0.0.0/ivys/ivy-0.20.1-gphdce-1.0.0.0.xml
[ivy:retrieve]  Host repo.eng.pivotal.io not found. url=https://repo.eng.pivotal.io/artifactory/gpdb-ext-release-local/apache/hadoop-core/0.20.1-gphdce-1.0.0.0/jars/hadoop-core-0.20.1-gphdce-1.0.0.0.jar
[ivy:retrieve]      module not found: apache#hadoop-core;0.20.1-gphdce-1.0.0.0
[ivy:retrieve]  ==== local: tried
[ivy:retrieve]    /opt/ivy/modules/apache/hadoop-core/ivy-0.20.1-gphdce-1.0.0.0.xml
[ivy:retrieve]    -- artifact apache#hadoop-core;0.20.1-gphdce-1.0.0.0!hadoop-core.jar:
[ivy:retrieve]    /opt/ivy/modules/apache/hadoop-core/jars/hadoop-core-0.20.1-gphdce-1.0.0.0.jar
[ivy:retrieve]  ==== shared: tried
[ivy:retrieve]    https://repo.eng.pivotal.io/artifactory/gpdb-ext-release-local/apache/hadoop-core/0.20.1-gphdce-1.0.0.0/ivys/ivy-0.20.1-gphdce-1.0.0.0.xml
[ivy:retrieve]    -- artifact apache#hadoop-core;0.20.1-gphdce-1.0.0.0!hadoop-core.jar:
[ivy:retrieve]    https://repo.eng.pivotal.io/artifactory/gpdb-ext-release-local/apache/hadoop-core/0.20.1-gphdce-1.0.0.0/jars/hadoop-core-0.20.1-gphdce-1.0.0.0.jar
[ivy:retrieve]  ==== public: tried
[ivy:retrieve]    http://repo1.maven.org/maven2/apache/hadoop-core/0.20.1-gphdce-1.0.0.0/hadoop-core-0.20.1-gphdce-1.0.0.0.pom
[ivy:retrieve]    -- artifact apache#hadoop-core;0.20.1-gphdce-1.0.0.0!hadoop-core.jar:
[ivy:retrieve]    http://repo1.maven.org/maven2/apache/hadoop-core/0.20.1-gphdce-1.0.0.0/hadoop-core-0.20.1-gphdce-1.0.0.0.jar
[ivy:retrieve]      ::::::::::::::::::::::::::::::::::::::::::::::
[ivy:retrieve]      ::          UNRESOLVED DEPENDENCIES         ::
[ivy:retrieve]      ::::::::::::::::::::::::::::::::::::::::::::::
[ivy:retrieve]      :: apache#hadoop-core;0.20.1-gphdce-1.0.0.0: not found
[ivy:retrieve]      ::::::::::::::::::::::::::::::::::::::::::::::
[ivy:retrieve]
[ivy:retrieve] :: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS

BUILD FAILED
/Users/spothineni/Sudhir/dev/ESGE-5688/gpdb/gpAux/extensions/gphdfs/build.xml:114: impossible to resolve dependencies:
    resolve failed - see output for details

Total time: 1 second
make: **\* [dist/gphd-1.0-gnet-1.0.0.1.jar] Error 1

**Comment by yew011** [comment]
I still could not build gphdfs,,,

Is there plan to allow people outside Pivotal to build it ? as mentioned in this commit log
commit 9c854010b14ed96e211fbb6205e57f6704b1a878

**Comment by lavjain** [comment]
Here is the PR that should address this issue:

https://github.com/greenplum-db/gpdb/pull/3947
