### ISSUE TITLE
Behave tests should capture and echo STDOUT/STDERR

### ISSUE THREAD

**Issue by danielgustafsson** [greenplum-db/gpdb#3914]
Currently when a Behave test for a gpMgmt program fails the vital STDOUT/STDERR output is missing from the Concourse logs. See example below from the merge pipeline:
```
    When the user runs "gpinitsystem -a -c ../gpAux/gpdemo/clusterConfigFile -l /tmp/gpinitsystemtest -s localhost -P 21100 -F pg_system:$MASTER_DATA_DIRECTORY/newstandby -h ../gpAux/gpdemo/hostfile" # 46.149s
    Then gpinitsystem should return a return code of 0                                                                                                                                                  # 0.001s
      Traceback (most recent call last):"-c ../gpAux/gpdemo/clusterConfigFile -l /tmp/gpinitsystemtest -s localhost -P 21100 -F pg_system:$MASTER_DATA_DIRECTORY/newstandby -h ../gpAux/gpdemo/hostfile
        File "build/bdist.linux-x86_64/egg/behave/model.py", line 1173, in run
          match.run(runner.context)
        File "build/bdist.linux-x86_64/egg/behave/model.py", line 1589, in run
          self.func(context, *args, **kwargs)
        File "/tmp/build/657cd205/gpdb_src/gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py", line 705, in impl
          check_return_code(context, ret_code)
        File "/tmp/build/657cd205/gpdb_src/gpMgmt/test/behave_utils/utils.py", line 188, in check_return_code
          "expected return code '%s' does not equal actual return code '%s' %s" % (ret_code, context.ret_code, emsg))
      Exception: expected return code '0' does not equal actual return code '1'

    And gpinitsystem should print "Log file scan check passed" to stdout
    And sql "select * from gp_toolkit.__gp_user_namespaces" is executed in "postgres" db


Failing scenarios:
  test/behave/mgmt_utils/gpinitsystem.feature:68  gpinitsystem should warn but not fail when standby cannot be instantiated
```
The output from `gpinitsystem` is required to be able to figure out why it returned 1 instead of 0. Fixing this means capturing `STDOUT` and `STDERR` and echoing to the screen when there is a failure. The traceback should further be removed IMHO since it's just visual noise.

**Comment by khuddlefish** [comment]
That's a good ask. We've been frustrated for a long time with the error reporting of these tasks. Especially when it fails on a return code step. This is definitely something we could look into. Is it something you would need urgently @danielgustafsson or just a nice-to-have at some point?

**Comment by Eulerizeit** [comment]
@khuddlefish urgency is a little difficult to define. The situation now is when we are trying to figure out what tests are breaking what concourse shows is less than useful. Essentially what is shown is something like 1=/= 0 here is a Python stack that points to a test and not an error. This makes figuring out the actual issue very difficult.

**Comment by Chibin** [comment]
The least we could do is tail the log of the utility we're running when there's an error.

**Comment by Eulerizeit** [comment]
@khuddlefish @Chibin Anything would be helpful. When y'all are fiddling with the code you know where to look for the errors, it is hopefully in the code you changed. During the merge there is no specific code changed, everything kinda changes which leads to a lot of behave test fixing in the dark.

**Comment by chrishajas** [comment]
@Chibin I think tail the output log when an the utility exits with a nonzero exit code in the behave step would be a good idea and shouldn't be too difficult.

**Comment by hlinnaka** [comment]
Now that PR #3928 has been pushed, I believe this can be closed.
