### ISSUE TITLE
Greenplum tutorial fails at load data step

### ISSUE THREAD

**Issue by Symbolics** [greenplum-db/gpdb#3930]
### Greenplum version or build
5.0.0
### OS version and uname -a
Sandbox downloaded from Pivotal website
### Expected behavior
FAA data loaded with COPY
### Actual behavior
psql:copy_into_airlines.sql:1: ERROR:  syntax error at or near "INTO"
LINE 1: ... faa.d_airlines FROM STDIN  CSV HEADER LOG ERRORS INTO faa.f...
### Step to reproduce the behavior
http://greenplum.org/gpdb-sandbox-tutorials/data-loading/ in the "Loading data with the COPY statement" step

**Comment by mkiyama** [comment]
I believe in GPDB 5.0+ the INTO <error_tbl> clause of COPY command is not valid. It was deprecated in 4.3 and removed in 5.0.

As a workaround you can remove the clause from the SQL command. 

Here is a link to the deprecated and removed features in GPDB 5.0
http://gpdb.docs.pivotal.io/500/relnotes/GPDB_500_README.html#topic_osh_g4m_5y

Hope this helps.

**Comment by skahler-pivotal** [comment]
The package of sandbox tutorials has been changed so they should work in 5.0 now
