### ISSUE TITLE
Failed to complete obtain psql count Master gp_segment_configuration  Script Exiting!

### ISSUE THREAD

**Issue by jinxiaoxin** [greenplum-db/gpdb#3931]
when i use gpinitsystem init greenplum database.
ERROR.

 I met this issue on CentOS6.X

20171120:16:23:13:029010 gpinitsystem:master1:gpadmin-[INFO]:-Building the Master instance database, please wait...
20171120:16:23:20:029010 gpinitsystem:master1:gpadmin-[INFO]:-Starting the Master in admin mode
20171120:16:24:27:gpinitsystem:master1:gpadmin-[FATAL]:-Failed to complete obtain psql count Master gp_segment_configuration  Script Exiting!
20171120:16:24:27:029010 gpinitsystem:master1:gpadmin-[WARN]:-Script has left Greenplum Database in an incomplete state
20171120:16:24:27:029010 gpinitsystem:master1:gpadmin-[WARN]:-Run command /bin/bash /home/gpadmin/gpAdminLogs/backout_gpinitsystem_gpadmin_20171120_162308 to remove these changes
20171120:16:24:27:029010 gpinitsystem:master1:gpadmin-[INFO]:-Start Function BACKOUT_COMMAND
20171120:16:24:27:029010 gpinitsystem:master1:gpadmin-[INFO]:-End Function BACKOUT_COMMAND

**Comment by cjcjameson** [comment]
Hi there! This error can come up in a few different ways. Can you please add more information about what you were doing that led to the error, and what version of the code you're on?

**Comment by jinxiaoxin** [comment]
@cjcjameson 
linux's version:CentOS 6.8
Greenplum's version :greenplum-db-4.3.17.1-rhel5-x86_64
LOG：
`[gpadmin@master1 gpconfigs]$ gpinitsystem -c gpinitsystem_config  -h /tmp/hostfile_segments
20171120:16:23:01:028065 gpinitsystem:master1:gpadmin-[INFO]:-Checking configuration parameters, please wait...
20171120:16:23:01:028065 gpinitsystem:master1:gpadmin-[INFO]:-Reading Greenplum configuration file gpinitsystem_config
20171120:16:23:01:028065 gpinitsystem:master1:gpadmin-[INFO]:-Locale has not been set in gpinitsystem_config, will set to default value
20171120:16:23:01:028065 gpinitsystem:master1:gpadmin-[INFO]:-Locale set to en_US.utf8
20171120:16:23:01:gpinitsystem:master1:gpadmin-[FATAL]:-Master host data directory /data/master/gpseg-1 already exists Script Exiting!
[gpadmin@master1 gpconfigs]$ rm -rf /data/master/gpseg-1
[gpadmin@master1 gpconfigs]$ gpinitsystem -c gpinitsystem_config  -h /tmp/hostfile_segments
20171120:16:23:09:029010 gpinitsystem:master1:gpadmin-[INFO]:-Checking configuration parameters, please wait...
20171120:16:23:09:029010 gpinitsystem:master1:gpadmin-[INFO]:-Reading Greenplum configuration file gpinitsystem_config
20171120:16:23:09:029010 gpinitsystem:master1:gpadmin-[INFO]:-Locale has not been set in gpinitsystem_config, will set to default value
20171120:16:23:09:029010 gpinitsystem:master1:gpadmin-[INFO]:-Locale set to en_US.utf8
20171120:16:23:09:029010 gpinitsystem:master1:gpadmin-[INFO]:-No DATABASE_NAME set, will exit following template1 updates
20171120:16:23:09:029010 gpinitsystem:master1:gpadmin-[INFO]:-MASTER_MAX_CONNECT not set, will set to default value 250
20171120:16:23:09:029010 gpinitsystem:master1:gpadmin-[INFO]:-Checking configuration parameters, Completed
20171120:16:23:09:029010 gpinitsystem:master1:gpadmin-[INFO]:-Commencing multi-home checks, please wait...
..
20171120:16:23:09:029010 gpinitsystem:master1:gpadmin-[INFO]:-Configuring build for standard array
20171120:16:23:09:029010 gpinitsystem:master1:gpadmin-[INFO]:-Commencing multi-home checks, Completed
20171120:16:23:09:029010 gpinitsystem:master1:gpadmin-[INFO]:-Building primary segment instance array, please wait...
..
20171120:16:23:10:029010 gpinitsystem:master1:gpadmin-[INFO]:-Checking Master host
20171120:16:23:10:029010 gpinitsystem:master1:gpadmin-[INFO]:-Checking new segment hosts, please wait...
..
20171120:16:23:11:029010 gpinitsystem:master1:gpadmin-[INFO]:-Checking new segment hosts, Completed
20171120:16:23:11:029010 gpinitsystem:master1:gpadmin-[INFO]:-Greenplum Database Creation Parameters
20171120:16:23:11:029010 gpinitsystem:master1:gpadmin-[INFO]:---------------------------------------
20171120:16:23:11:029010 gpinitsystem:master1:gpadmin-[INFO]:-Master Configuration
20171120:16:23:11:029010 gpinitsystem:master1:gpadmin-[INFO]:---------------------------------------
20171120:16:23:11:029010 gpinitsystem:master1:gpadmin-[INFO]:-Master instance name       = EMC Greenplum DW
20171120:16:23:11:029010 gpinitsystem:master1:gpadmin-[INFO]:-Master hostname            = master1
20171120:16:23:11:029010 gpinitsystem:master1:gpadmin-[INFO]:-Master port                = 5432
20171120:16:23:11:029010 gpinitsystem:master1:gpadmin-[INFO]:-Master instance dir        = /data/master/gpseg-1
20171120:16:23:11:029010 gpinitsystem:master1:gpadmin-[INFO]:-Master LOCALE              = en_US.utf8
20171120:16:23:11:029010 gpinitsystem:master1:gpadmin-[INFO]:-Greenplum segment prefix   = gpseg
20171120:16:23:11:029010 gpinitsystem:master1:gpadmin-[INFO]:-Master Database            = 
20171120:16:23:11:029010 gpinitsystem:master1:gpadmin-[INFO]:-Master connections         = 250
20171120:16:23:11:029010 gpinitsystem:master1:gpadmin-[INFO]:-Master buffers             = 128000kB
20171120:16:23:11:029010 gpinitsystem:master1:gpadmin-[INFO]:-Segment connections        = 750
20171120:16:23:11:029010 gpinitsystem:master1:gpadmin-[INFO]:-Segment buffers            = 128000kB
20171120:16:23:11:029010 gpinitsystem:master1:gpadmin-[INFO]:-Checkpoint segments        = 8
20171120:16:23:11:029010 gpinitsystem:master1:gpadmin-[INFO]:-Encoding                   = UNICODE
20171120:16:23:11:029010 gpinitsystem:master1:gpadmin-[INFO]:-Postgres param file        = Off
20171120:16:23:11:029010 gpinitsystem:master1:gpadmin-[INFO]:-Initdb to be used          = /usr/local/greenplum-db/./bin/initdb
20171120:16:23:11:029010 gpinitsystem:master1:gpadmin-[INFO]:-GP_LIBRARY_PATH is         = /usr/local/greenplum-db/./lib
20171120:16:23:11:029010 gpinitsystem:master1:gpadmin-[INFO]:-Ulimit check               = Passed
20171120:16:23:11:029010 gpinitsystem:master1:gpadmin-[INFO]:-Array host connect type    = Single hostname per node
20171120:16:23:11:029010 gpinitsystem:master1:gpadmin-[INFO]:-Master IP address [1]      = ::1
20171120:16:23:11:029010 gpinitsystem:master1:gpadmin-[INFO]:-Master IP address [2]      = 10.105.10.121
20171120:16:23:11:029010 gpinitsystem:master1:gpadmin-[INFO]:-Master IP address [3]      = fe80::250:56ff:fe8c:16fb
20171120:16:23:12:029010 gpinitsystem:master1:gpadmin-[INFO]:-Standby Master             = Not Configured
20171120:16:23:12:029010 gpinitsystem:master1:gpadmin-[INFO]:-Primary segment #          = 1
20171120:16:23:12:029010 gpinitsystem:master1:gpadmin-[INFO]:-Total Database segments    = 2
20171120:16:23:12:029010 gpinitsystem:master1:gpadmin-[INFO]:-Trusted shell              = ssh
20171120:16:23:12:029010 gpinitsystem:master1:gpadmin-[INFO]:-Number segment hosts       = 2
20171120:16:23:12:029010 gpinitsystem:master1:gpadmin-[INFO]:-Mirroring config           = OFF
20171120:16:23:12:029010 gpinitsystem:master1:gpadmin-[INFO]:----------------------------------------
20171120:16:23:12:029010 gpinitsystem:master1:gpadmin-[INFO]:-Greenplum Primary Segment Configuration
20171120:16:23:12:029010 gpinitsystem:master1:gpadmin-[INFO]:----------------------------------------
20171120:16:23:12:029010 gpinitsystem:master1:gpadmin-[INFO]:-slave2 	/data/primary/gpseg0 	40000 	2 	0
20171120:16:23:12:029010 gpinitsystem:master1:gpadmin-[INFO]:-slave3 	/data/primary/gpseg1 	40000 	3 	1
Continue with Greenplum creation Yy/Nn>
y
20171120:16:23:13:029010 gpinitsystem:master1:gpadmin-[INFO]:-Building the Master instance database, please wait...
20171120:16:23:20:029010 gpinitsystem:master1:gpadmin-[INFO]:-Starting the Master in admin mode
20171120:16:24:27:gpinitsystem:master1:gpadmin-[FATAL]:-Failed to complete obtain psql count Master gp_segment_configuration  Script Exiting!
20171120:16:24:27:029010 gpinitsystem:master1:gpadmin-[WARN]:-Script has left Greenplum Database in an incomplete state
20171120:16:24:27:029010 gpinitsystem:master1:gpadmin-[WARN]:-Run command /bin/bash /home/gpadmin/gpAdminLogs/backout_gpinitsystem_gpadmin_20171120_162308 to remove these changes
20171120:16:24:27:029010 gpinitsystem:master1:gpadmin-[INFO]:-Start Function BACKOUT_COMMAND
20171120:16:24:27:029010 gpinitsystem:master1:gpadmin-[INFO]:-End Function BACKOUT_COMMAND`

**Comment by cjcjameson** [comment]
Hi there, so for 4.3 versions of Greenplum, those are closed-source commercial releases only. Please feel free to reach out through official Pivotal support channels.
