### ISSUE TITLE
does greenplum support  syntax  'on duplicate key update' of mysql?

### ISSUE THREAD

**Issue by jinxiaoxin** [greenplum-db/gpdb#3941]
mysql:
INSERT INTO the_table (id, column_1, column_2) 
VALUES (1, 'A', 'X'), (2, 'B', 'Y'), (3, 'C', 'Z')
ON CONFLICT (id) DO UPDATE 
  SET column_1 = excluded.column_1, 
      column_2 = excluded.column_2;

**Comment by hlinnaka** [comment]
No, that syntax is not supported.

PostgreSQL 9.5 added a feature like that, but it will take a few more major releases until GPDB will catch up to that, so don't hold your breath.

**Comment by jinxiaoxin** [comment]
@hlinnaka 
If I have the request like that, how should I do in GP?

**Comment by hlinnaka** [comment]
On 11/21/2017 06:14 PM, jinxiaoxin wrote:
> @hlinnaka If I have the request like that, how should I do in GP?

Take a look at this PostgreSQL wiki page:

https://wiki.postgresql.org/wiki/UPSERT#PostgreSQL_.28today.29

Most of that page is about the development of the upstream ON CONFLICT 
UPDATE feature, but that "PostgreSQL (today)" section lists some 
workarounds that you could use in older versions. Those should be 
applicable to GPDB as well.

- Heikki

**Comment by jinxiaoxin** [comment]
@hlinnaka  thanks
