### ISSUE TITLE
How to force GPDB 5 use index? greenplum5.X版本，如何操作才能走强制索引？

### ISSUE THREAD

**Issue by gucong115** [greenplum-db/gpdb#3967]
目前数据表建立索引之后，大多数时候orca优化器都不走索引，在4.3.X的版本中，只要加一句话
set enable_seqscan = off; 就能走索引了，但是5.X版本就不会走，需要将优化器更改为
legacy query optimizer之后，在用set enable_seqscan = off; 语句实现强制索引，目前orca的优化器如何才能让建立的索引生效呢？
[还有建立多个索引之后，如何指定优先走哪个索引呢？（这个问题4.X版本的的时候也没找到解决方案）

**Comment by gucong115** [comment]
？？？

**Comment by lij55** [comment]
In short, how to force to use index for ORCA in GDPB5? How to specify which index to use if there are multiple indexes?

**Comment by gucong115** [comment]
如果是中国人的话，能用中文回复不？谢谢各位大神！汉语现在连美国总统的孙女都在学，我们干嘛不用呢=.=

**Comment by hsyuan** [comment]
`enable_seqscan ` only valid for legacy planner, it doesn't apply for orca.  you can `set optimizer_enable_tablescan=off;` to force Orca use index scan.

**Comment by hsyuan** [comment]
There is no way for Orca to specify which index has high priority.

**Comment by yydzero** [comment]
@hsyuan any reason to use a new GUC instead of reusing enable_seqscan?

**Comment by hsyuan** [comment]
I don't know. It was made long time ago. Maybe some historical reason.

~ ~ ~
Haisheng Yuan

**Comment by yydzero** [comment]
@vraghavan78 do you have any context?

**Comment by d** [comment]
@gucong115 can you elaborate your problems? To help us reproduce your problem, please provide:

1. The DDL (`CREATE TABLE` and `CREATE INDEX`)
1. The stats (use `minirepro` or `gpsd`, or `INSERT INTO ...`)
1. Your query and plan (`EXPLAIN ANALYZE SELECT`)
1. Prove that index scan is superior.

Please note that Github is *not* a support forum for a commercial product, for that, please contact your regular Pivotal support.

Note that even with legacy planner, `set enable_seqscan = off` does *not* "force index scan": it merely assigns a high cost to sequential scan and *lures* the planner to pick an index scan (if it's reasonable given the new high cost of sequential scan).

**Comment by vraghavan78** [comment]
@yydzero optimizer and planner GUCS are kept different since:

1. Not all gucs translate across the two optimizers.
2. The underlying is not usually identical.

**Comment by yydzero** [comment]
Thanks Venky. Closed as reporter has resolved his issue.
