### ISSUE TITLE
How many slots will be sent out on motion phase?

### ISSUE THREAD

**Issue by JinHai-CN** [greenplum-db/gpdb#3977]
### Greenplum version or build
gpdb-5.1.0
### OS version and uname -a
ubuntu 16.04

Question:
As we know, there are three types of motion: gather/broadcast/redistribution which means when segments collect enough tuples, they will send me out to master or other segments. question is how many tuples the segment collect will trigger the segment server sending out tuples? I suppose the segment server won't collect all tuples and then send out if the number of tuples is very big.

**Comment by pengzhout** [comment]
The default size is 8K, you can change it using GUC gp_max_packet_size.

**Comment by pengzhout** [comment]
Yes, if it contains complete tuples, the receiver will process them when it needs more tuples.

**Comment by JinHai-CN** [comment]
Sorry, I am a little bit confused. Would you please double confirm when the receiver starts process the tuples? Thank you very much.

**Comment by pengzhout** [comment]
For default interconnect type ('UDPIFC'), an interconnect thread per backend is responsible for receiving interconnect packets and putting them to according queue, the main thread will fetch those packets from the queue as needed when it processes to execute the MOTION node (I suppose this is what you mean "starts process the tuples"), so the tuples may not be processed immediately by main thread if it is processing other nodes (eg. creating hash table for hash join).
