### ISSUE TITLE
Is it possible to setup the GP as pure HA deployment?

### ISSUE THREAD

**Issue by JinHai-CN** [greenplum-db/gpdb#3989]
I mean only one master node with a mirror node as the backup.

**Comment by ashwinstar** [comment]
Not sure I understand the question. If the ask is can we create only master and standby without any segments (primaries) then answer is NO.

Also, might be helpful to leverage mailing lists gpdb-dev@greenplum.org or gpdb-users@greenplum.org for questions/queries instead of issues.
