### ISSUE TITLE
Build failure on OS X

### ISSUE THREAD

**Issue by davecramer** [greenplum-db/gpdb#4]
OS X 10.10.5
Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.5.0

./configure
make
results in
strlcpy.c:45:1: error: expected parameter declarator
strlcpy(char *dst, const char *src, size_t siz)
^
/usr/include/secure/_string.h:105:44: note: expanded from macro 'strlcpy'
  __builtin___strlcpy_chk (dest, src, len, __darwin_obsz (dest))
                                           ^
/usr/include/secure/_common.h:39:62: note: expanded from macro '__darwin_obsz'
#define __darwin_obsz(object) __builtin_object_size (object, _USE_FORTIFY_LEVEL > 1 ? 1 : 0)
                                                             ^
/usr/include/secure/_common.h:30:32: note: expanded from macro '_USE_FORTIFY_LEVEL'
#    define _USE_FORTIFY_LEVEL 2
                               ^
strlcpy.c:45:1: error: expected ')'
/usr/include/secure/_string.h:105:44: note: expanded from macro 'strlcpy'
  __builtin___strlcpy_chk (dest, src, len, __darwin_obsz (dest))
                                           ^
/usr/include/secure/_common.h:39:62: note: expanded from macro '__darwin_obsz'
#define __darwin_obsz(object) __builtin_object_size (object, _USE_FORTIFY_LEVEL > 1 ? 1 : 0)
                                                             ^
/usr/include/secure/_common.h:30:32: note: expanded from macro '_USE_FORTIFY_LEVEL'
#    define _USE_FORTIFY_LEVEL 2
                               ^
strlcpy.c:45:1: note: to match this '('
/usr/include/secure/_string.h:105:44: note: expanded from macro 'strlcpy'
  __builtin___strlcpy_chk (dest, src, len, __darwin_obsz (dest))
                                           ^
/usr/include/secure/_common.h:39:53: note: expanded from macro '__darwin_obsz'
#define __darwin_obsz(object) __builtin_object_size (object, _USE_FORTIFY_LEVEL > 1 ? 1 : 0)
                                                    ^
strlcpy.c:45:1: warning: type specifier missing, defaults to 'int' [-Wimplicit-int]
strlcpy(char *dst, const char *src, size_t siz)
^
/usr/include/secure/_string.h:105:44: note: expanded from macro 'strlcpy'
  __builtin___strlcpy_chk (dest, src, len, __darwin_obsz (dest))
                                           ^
/usr/include/secure/_common.h:39:31: note: expanded from macro '__darwin_obsz'
#define __darwin_obsz(object) __builtin_object_size (object, _USE_FORTIFY_LEVEL > 1 ? 1 : 0)
                              ^
strlcpy.c:45:1: error: conflicting types for '__builtin___strlcpy_chk'
/usr/include/secure/_string.h:105:3: note: expanded from macro 'strlcpy'
  __builtin___strlcpy_chk (dest, src, len, __darwin_obsz (dest))
  ^
strlcpy.c:45:1: note: '__builtin___strlcpy_chk' is a builtin with type 'unsigned long (char *, const char *,
      unsigned long, unsigned long)'
/usr/include/secure/_string.h:105:3: note: expanded from macro 'strlcpy'
  __builtin___strlcpy_chk (dest, src, len, __darwin_obsz (dest))
  ^
strlcpy.c:45:1: error: definition of builtin function '__builtin___strlcpy_chk'
strlcpy(char *dst, const char *src, size_t siz)
^
/usr/include/secure/_string.h:105:3: note: expanded from macro 'strlcpy'
  __builtin___strlcpy_chk (dest, src, len, __darwin_obsz (dest))
  ^
2 warnings and 4 errors generated.

**Comment by film42** [comment]
I don't think it's intended to support OSX. Their support systems list can be found here: http://gpdb.docs.pivotal.io/4360/prep_os-system-req.html#topic2

I worked through some of these errors by using os `strlcpy` and `strlcat` and I'm currently at:

```
gcc -O3 -std=gnu99  -Wall -Wmissing-prototypes -Wpointer-arith -Wendif-labels -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-unused-but-set-variable -Wno-address  -I../../../../src/include   -c -o crc32c.o crc32c.c
clang: warning: optimization flag '-fexcess-precision=standard' is not supported
clang: warning: argument unused during compilation: '-fexcess-precision=standard'
warning: unknown warning option '-Wno-unused-but-set-variable'; did you mean '-Wno-unused-const-variable'? [-Wunknown-warning-option]
crc32c.c:536:13: warning: unknown pragma ignored [-Wunknown-pragmas]
#pragma GCC target ("sse4.2")
            ^
In file included from crc32c.c:538:
/Library/Developer/CommandLineTools/usr/bin/../lib/clang/7.0.0/include/nmmintrin.h:28:2: error: "SSE4.2 instruction set not enabled"
#error "SSE4.2 instruction set not enabled"
 ^
crc32c.c:548:9: warning: implicit declaration of function '_mm_crc32_u32' is invalid in C99 [-Wimplicit-function-declaration]
                crc = _mm_crc32_u32(crc, *(uint32*) p_buf);
                      ^
crc32c.c:557:9: warning: implicit declaration of function '_mm_crc32_u8' is invalid in C99 [-Wimplicit-function-declaration]
                crc = _mm_crc32_u8(crc, *p_buf++);
                      ^
crc32c.c:559:9: warning: implicit declaration of function '_mm_crc32_u16' is invalid in C99 [-Wimplicit-function-declaration]
                crc = _mm_crc32_u16(crc, *(uint16_t*) p_buf);
                      ^
crc32c.c:588:20: warning: implicit declaration of function '_mm_crc32_u64' is invalid in C99 [-Wimplicit-function-declaration]
        crc64bit = _mm_crc32_u64(crc64bit, *(uint64*) p_buf);
                   ^
crc32c.c:644:25: error: use of undeclared identifier 'bit_SSE4_2'
        bool hasSSE42 = (ecx & bit_SSE4_2) != 0;
                               ^
6 warnings and 2 errors generated.
make[4]: *** [crc32c.o] Error 1
make[3]: *** [hash-recursive] Error 2
make[2]: *** [utils-recursive] Error 2
make[1]: *** [all] Error 2
make: *** [all] Error 2
```

**Comment by rizo** [comment]
The same issue occurs on FreeBSD 10.2.

Adding `<string.h>` include does not seems to solve the problem.
Before that I had to manually set the pthread lib variable:  `PTHREAD_LIBS=-lpthread`.


Here's the log just for reference:

```
Using GNU make found at /usr/local/bin/gmake
gmake[1]: Entering directory '/home/rizo/src/gpdb'
/usr/local/bin/gmake -C src all
gmake[2]: Entering directory '/home/rizo/src/gpdb/src'
/usr/local/bin/gmake -C port all
gmake[3]: Entering directory '/home/rizo/src/gpdb/src/port'
cc -O3 -std=gnu99  -Wall -Wmissing-prototypes -Wpointer-arith -Wendif-labels -Wformat-security -fno-strict-aliasing -fwrapv -Wno-unused-but-set-variable -Wno-address -I/usr/local/include -I../../src/port -DFRONTEND -I../../src/include   -c -o exec.o exec.c
warning: unknown warning option '-Wno-unused-but-set-variable'; did you mean '-Wno-unused-const-variable'? [-Wunknown-warning-option]
exec.c:352:2: warning: implicitly declaring library function 'strlcpy' with type 'unsigned long (char *, const char *, unsigned long)'
        strlcpy(link_buf, fname, sizeof(link_buf));
        ^
exec.c:352:2: note: please include the header <string.h> or explicitly provide a declaration for 'strlcpy'
exec.c:609:29: error: use of undeclared identifier 'NSIG'
                                 WTERMSIG(exitstatus) < NSIG ?
                                                        ^
exec.c:610:6: error: use of undeclared identifier 'sys_siglist'
                                 sys_siglist[WTERMSIG(exitstatus)] : "(unknown)");
                                 ^
2 warnings and 2 errors generated.
<builtin>: recipe for target 'exec.o' failed
gmake[3]: *** [exec.o] Error 1
gmake[3]: Leaving directory '/home/rizo/src/gpdb/src/port'
Makefile:17: recipe for target 'all' failed
gmake[2]: *** [all] Error 2
gmake[2]: Leaving directory '/home/rizo/src/gpdb/src'
GNUmakefile:14: recipe for target 'all' failed
gmake[1]: *** [all] Error 2
gmake[1]: Leaving directory '/home/rizo/src/gpdb'
*** Error code 2

Stop.
make: stopped in /home/rizo/src/gpdb
```

**Comment by film42** [comment]
I was able to get OSX building. PR is open!

**Comment by hlinnaka** [comment]
I pushed pull request #31, so the SSE failure should be fixed now (thanks @film42!). Can you verify that it actually fixed the original OS X issue, please?

**Comment by film42** [comment]
It works! Thanks!
