### ISSUE TITLE
unable to connect greenplum postgres from external client

### ISSUE THREAD

**Issue by rahulsingh0978** [greenplum-db/gpdb#4001]
### OS version and uname -a,  ubantu 16.04
gp-xerces - v3.1.2-p1
gporca  v2.43.1
### Expected behavior
trying to connect greenplum postgres but unable to connect through external postgres client, tried to update external machine ip in the hba config file , but on starting the cluster again and trying to connect with the postgre client the ip is getting removedfrom the hba.config . dont know where is the exact location of the hba.config file as everytime the cluster is started the file gets overrided..

### Step to reproduce the behavior
. /usr/local/gpdb/greenplum_path.sh
cd /greenplum/gpdb-master/gpAux/gpdemo
make create-demo-cluster  or make cluster
cd /greenplum/gpdb-master/gpAux/gpdemo
make create-demo-cluster  or make cluster
when tried to connect to this machine through client, it shows error . add ip to hba.config.
please tell the exact location of hba config in linux ubantu.

**Comment by rahulsingh0978** [comment]
somebody please on this issue.

**Comment by pengzhout** [comment]
greenplum/gpdb-master/gpAux/gpdemo/datadirs/qddir/demoDataDir-1/pg_hba.conf
