### ISSUE TITLE
if the default server remote ssh login port is not 22

### ISSUE THREAD

**Issue by jinxiaoxin** [greenplum-db/gpdb#4009]
if the default server remote ssh login port is not 22，does install scripts of gpdb work？for example: 'gpssh-exkeys'   'gpseginstall '

**Comment by jinxiaoxin** [comment]
if can work,why ：
'''
[root@bigdata01 ~]# gpseginstall -f /tmp/hostfile_exkeys -u gpadmin -p xxxxxx
20171130:17:31:24:021448 gpseginstall:bigdata01:root-[INFO]:-Installation Info:
link_name greenplum-db
binary_path /opt/greenplum-db-4.3.17.1
binary_dir_location /opt
binary_dir_name greenplum-db-4.3.17.1
20171130:17:31:24:021448 gpseginstall:bigdata01:root-[INFO]:-check cluster password access
  *** Enter password for bigdata03: 
  *** Enter password for bigdata03: 
  *** Enter password for bigdata03: 
  *** Enter password for bigdata03: 
  *** Enter password for bigdata03: 
20171130:17:31:38:021448 gpseginstall:bigdata01:root-[ERROR]:-could not successfully access all machines
20171130:17:31:38:021448 gpseginstall:bigdata01:root-[ERROR]:-trace: Did not get a valid password for host bigdata03
20171130:17:31:38:021448 gpseginstall:bigdata01:root-[CRITICAL]:-early exit from gpseginstall
'''

**Comment by jinxiaoxin** [comment]
the password  is correct

**Comment by cjcjameson** [comment]
For your specific case, please reach out to Pivotal Support for product versions 4.3.x, as that's commercial release only.

Nonetheless, I think your first question is possibly interesting -- tagging @skahler-pivotal @Chibin to see if we can get you an answer because I don't know off the top of my head.

**Comment by jinxiaoxin** [comment]
@cjcjameson server ssh port is not 22,i dont install success.

**Comment by skahler-pivotal** [comment]
by default those utilities only use the standard ssh port and we haven't added an option to use a non-standard port in all of the utilities.

we can add this as a feature request, for tools that use ssh to be allowed to be passed a parameter that would allow them to work non-standard ports.

**Comment by skahler-pivotal** [comment]
at this point gpssh-exkeys and gpseginstall haven't been written to take into account and alternate ssh setup. You would need to exchange the keys manually and manually push the binaries around the system.
