### ISSUE TITLE
Version detection not work even correct gporca version was installed 

### ISSUE THREAD

**Issue by Dishcreate** [greenplum-db/gpdb#4039]
gpdb version 6.0.0-alpha.0
OS -Centos 6.2

I installed gporca version 2.50.2 but there is error when configure gpdb 6.0.0-alpha.0 as below.
checking Checking ORCA version... configure: error: Your ORCA version is expected to be 2.50.XXX
Can anyone help to fix this error ?

**Comment by hlinnaka** [comment]
Have a look at the config.log file for more details on what exactly went wrong.

Make sure the ORCA library is in the library path. If you didn't install it in a standard system location like /usr/lib or /usr/local/lib, you can use `LD_LIBRARY_PATH=<path to orca libs> ./configure ...`

**Comment by Dishcreate** [comment]
@hlinnaka 
I used it as 
./configure --with-perl --with-python --with-libxml --with-gssapi --with-includes=/usr/local/include --with-libraries=/usr/local/lib --prefix=/usr/local/gpdb 
ORCA  library is in that path

**Comment by danielgustafsson** [comment]
Just to rule out the simple things, what does the following return?:
```sh
grep GPORCA_VERSION_STRING /usr/local/include/gpopt/version.h
```

**Comment by Dishcreate** [comment]
@danielgustafsson 
This is the output
#define GPORCA_VERSION_STRING "2.50.2"

**Comment by danielgustafsson** [comment]
Thats very odd, I can't see why that would fail. Will see if I can reproduce it synthetically

**Comment by Dishcreate** [comment]
@hlinnaka @danielgustafsson 
Kind remind both of you to solve this problem

**Comment by hlinnaka** [comment]
Are there any clues in config.log?
- Heikki

**Comment by Dishcreate** [comment]
@hlinnaka  
There is no clue in config.log file it was exit as follow
configure: exit 127

**Comment by hlinnaka** [comment]
If you search config.log for the error you got, `Your ORCA version is expected`, or for `Checking ORCA version`, you should see the details of how that test failed. Is there a compiler or linker error around there? I can also take a look, if you attach the config.log here.

**Comment by Dishcreate** [comment]
_

**Comment by Dishcreate** [comment]
@hlinnaka 
Here is the config.log file
[config.log](https://github.com/greenplum-db/gpdb/files/1550873/config.log)

**Comment by hlinnaka** [comment]
On 12/12/17 11:08, DInusha DIlanka wrote:
> @hlinnaka
> Here is the config.log file
> [config.log](https://github.com/greenplum-db/gpdb/files/1550873/config.log)

Thanks! A-ha, there was this error in the log file:

```
configure:12534: checking Checking ORCA version
configure:12564: g++ -std=c++11 -o conftest  -O3 -Wall -Wpointer-arith 
-Wendif-labels -Wformat-security -fno-strict-aliasing -fwrapv 
-fno-aggressive-loop-optimizations -Wno-unused-but-set-variable 
-Wno-address -I/home/gcc/include  -D_GNU_SOURCE -I/usr/include/libxml2 
-I/usr/local/include -L/home/gcc/lib   -L/usr/local/lib conftest.cpp 
-lgpopt -lnaucrates -lgpdbcost -lgpos -lxerces-c -lbz2 -lxml2 -lrt 
-lgssapi_krb5 -lz -lreadline -lcrypt -ldl -lm  -lcurl   >&5
configure:12564: $? = 0
configure:12564: ./conftest
./conftest: symbol lookup error: /home/miniconda/lib/libreadline.so.6: 
undefined symbol: PC
configure:12564: $? = 127
configure: program exited with status 127
```

So, looks like some sort of confusion with libreadline. Do you have a 
special copy of libreadline in /home/miniconda/lib? What version of 
libreadline did you intend to use?

It was actually affecting the earlier configure test for "checking for 
ANSI C header files" already. The result of that was "no", because of 
the libreadline issue, but I bet the result should've been "yes" on your 
system.

- Heikki

**Comment by Dishcreate** [comment]
@hlinnaka 
Can i use --without-readline ?

**Comment by hlinnaka** [comment]
On 12/12/17 13:03, DInusha DIlanka wrote:
> @hlinnaka
> Can i use --without-readline ?

Sure. Makes psql less convenient, but it should work.

- Heikki
