### ISSUE TITLE
Improve plan_tree_walker function signature

### ISSUE THREAD

**Issue by vitesse-ftian** [greenplum-db/gpdb#4040]
### Greenplum version or build
master
### Step to reproduce the behavior

in src/include/optimizer/walkers.h, the function signature is,

plan_tree_walker(Node*, bool (*walker)(), void *context);

The walker function should be of type bool *(walker)(Node*, void*).  This is a minor issue but newer gcc may generate annoying warnings.

**Comment by krait007** [comment]
Hi @vitesse-ftian 
How to reappear the warnings?   I build with gcc:  6.4.0、7.2.0、8.1.0，did not find any warnings about walker function.

**Comment by hlinnaka** [comment]
I believe both styles of defining a function pointer argument are legal. Furthermore, the signature of `plan_tree_walker` is the same as `expression_tree_walker`'s. `expression_tree_walker` is an upstream function, and people compile PostgreSQL with a wide range of compilers.

Closing.
