### ISSUE TITLE
show hint message and notice when  revoke does nothing actually

### ISSUE THREAD

**Issue by gaos1** [greenplum-db/gpdb#4060]
### Greenplum version or build
GPDB master

### Behavior
With the PR https://github.com/greenplum-db/gpdb/pull/4050,
end users will see a notice "no privileges could be revoked" ,  it is better to show additional hint so that users can get known that they are not allowed to revoke privileges in some cases. 

draft notice and hint message: 
NOTICE: no privileges could be revoked
HINT: There are some cases that you can't deny a permission with REVOKE, e.g. if the permission is inherited through another role or PUBLIC

### Step to reproduce the behavior
```
*  User 1 created a table and and gives access to user 2 with grant option
* User 2 grants access to user 3
*  When gpadmin tries to revoke privilege from user3. 
```

**Comment by gaos1** [comment]
@mkiyama

**Comment by yydzero** [comment]
any further action do we need to take?

**Comment by ivannovick** [comment]
decide to not act on this
