### ISSUE TITLE
gpfdist: installcheck kills any processes containing 'gpfdist'

### ISSUE THREAD

**Issue by jchampio** [greenplum-db/gpdb#4071]
Here's the symptom on my machine:

```
$ make -C src/bin/gpfdist installcheck
(using postmaster on Unix socket, port 15432)
============== dropping database "gpfdist_regression" ==============
DROP DATABASE
============== creating database "gpfdist_regression" ==============
CREATE DATABASE
ALTER DATABASE
============== checking optimizer status              ==============
Optimizer enabled. Using optimizer answer files whenever possible
============== checking gp_resource_manager status    ==============
Resource group disabled. Using default answer files
============== checking codegen status                ==============
Codegen disabled
============== running regression test queries        ==============
test gpfdist2             ... make[1]: *** [installcheck] Terminated: 15
make: *** [installcheck] Terminated: 15
Terminated: 15
```

This is odd enough, but my interest was really piqued when Vim got killed during a test run. :grin: Turns out many of the gpfdist SQL tests set up functions that look like this:

```
CREATE EXTERNAL WEB TABLE exttab1_gpfdist_stop (x text)
execute E'(ps -A |grep [g]pfdist |awk \'{print $1;}\' |xargs kill) > /dev/null 2>&1; echo "stopping..."'
```

In my case this kills not only any running gpfdist processes, but also the make process running the test itself (and any poor innocent text editors with gpfdist source code open). This should be scoped way back.

**Comment by Eulerizeit** [comment]
@schubert @yydzero could you please point the right people to this.

**Comment by pf-qiu** [comment]
We will have a look at this and find a better way to stop gpfdist

**Comment by dujialun** [comment]
Hi @jchampio We fix this bug in this PR, https://github.com/greenplum-db/gpdb/pull/4106. I think you must run it under the Mac OS, which "ps -A" has different behavior comparing to the CentOS. As you know GPDB is not official supported under MacOS, thought the new code won't kill any other unrelated programs, the cases won't pass due to gpfdist doesn't work well under MacOS.
