### ISSUE TITLE
Documentation doesn't explain versioning

### ISSUE THREAD

**Issue by danielgustafsson** [greenplum-db/gpdb#4074]
There is no explanation in the documentation what the various parts of the version means, ie the semver components. We should probably document this somewhere such that administrators know which version bumps will be binary compatible.

**Comment by lisakowen** [comment]
@danielgustafsson - i picked up this work.

is this the sort of information you were looking for?  and is it true?  (actual text in the docs will likely differ):

Greenplum Database releases with the same Major release number are guaranteed to be backwards compatible.
Greenplum Database revs the Major release number for catalog changes, or when incompatible feature changes or incompatible new features are introduced.
The Minor release number for a given Major release is revved when backwards compatible new features are introduced or when a Greenplum Database feature is deprecated.
Greenplum Database revs the Patch release number for a given Minor release for backwards-compatible bug fixes.

**Comment by dyozie** [comment]
Adding @ivannovick to this thread for review of the above.

**Comment by ivannovick** [comment]
Above text looks good to me

**Comment by danielgustafsson** [comment]
Feature deprecation is by definition a not backwards compatible change, so I would assume we only do that for major release. Otherwise looks good to me.

**Comment by danielgustafsson** [comment]
Closing this as #4193 has been opened add this to the documentation.
