### ISSUE TITLE
Build the gpdb on CentOS 7 Fail

### ISSUE THREAD

**Issue by dapengtx** [greenplum-db/gpdb#4088]
### Greenplum version or build
6.0.0-alpha.0+dev.1681.gdabf34b build dev-oss

### OS version and uname -a
CentOs
Linux localhost.localdomain 3.10.0-123.el7.x86_64 #1 SMP Mon Jun 30 12:09:22 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

### autoconf options used ( config.status --config )
./configure --with-perl --with-python --with-libxml --with-gssapi --prefix=/usr/local/greenplum-db/

### Installation information ( pg_config )
vacuum.c: 在函数‘vacuum’中:
vacuum.c:1318:18: 错误：此函数中的‘stats_context.updated_stats’在使用前可能未初始化 [-Werror=maybe-uninitialized]
    list_free_deep(stats_context.updated_stats);
                  ^
vacuum.c:963:21: 附注：‘stats_context.updated_stats’在此声明
  VacuumStatsContext stats_context;
                     ^
In file included from ../../../src/include/access/tupdesc.h:19:0,
                 from ../../../src/include/access/htup.h:19,
                 from ../../../src/include/utils/relcache.h:19,
                 from ../../../src/include/access/xlog.h:21,
                 from ../../../src/include/access/clog.h:14,
                 from vacuum.c:29:
../../../src/include/nodes/pg_list.h:82:21: 错误：此函数中的‘analyze_relations’在使用前可能未初始化 [-Werror=maybe-uninitialized]
  return l ? l->head : NULL;
                     ^
vacuum.c:376:11: 附注：‘analyze_relations’在此声明
  List    *analyze_relations;
           ^
In file included from ../../../src/include/access/tupdesc.h:19:0,
                 from ../../../src/include/access/htup.h:19,
                 from ../../../src/include/utils/relcache.h:19,
                 from ../../../src/include/access/xlog.h:21,
                 from ../../../src/include/access/clog.h:14,
                 from vacuum.c:29:
../../../src/include/nodes/pg_list.h:94:23: 错误：此函数中的‘vacuum_relations’在使用前可能未初始化 [-Werror=maybe-uninitialized]
  return l ? l->length : 0;
                       ^
vacuum.c:375:11: 附注：‘vacuum_relations’在此声明
  List    *vacuum_relations;
           ^
cc1: some warnings being treated as errors
make[3]: *** [vacuum.o] 错误 1
make[3]: 离开目录“/home/gpadmin/gpdb/src/backend/commands”
make[2]: *** [commands-recursive] 错误 2
make[2]: 离开目录“/home/gpadmin/gpdb/src/backend”
make[1]: *** [all] 错误 2
make[1]: 离开目录“/home/gpadmin/gpdb/src”
make: *** [all] 错误 2

### Expected behavior
build Fail
### Actual behavior
can be build success
### Step to reproduce the behavior
1. run the config command by below:
./configure --with-perl --with-python --with-libxml --with-gssapi --prefix=/usr/local/gpdb

2. make the build by below command then apper the error
make -j8

**Comment by dapengtx** [comment]
Hi all, 
I try to build the gpdb as a long time, and failed, please help me to fix this issue.

very thanks.

**Comment by hsyuan** [comment]
What is the complier version are you using?
You can remove the the flag`-Werror=uninitialized` to unblock you first.

**Comment by xinzweb** [comment]
Would you please share which compiler you are using?

Also, we found different issue when run with your configuration:

```
fileam.c: In function ‘externalgettup_custom’:
fileam.c:1044:11: error: ‘error_caught’ is used uninitialized in this function [-Werror=uninitialized]
     bool  error_caught = false;
           ^~~~~~~~~~~~
In file included from ../../../../src/include/postgres.h:53:0,
                 from fileam.c:34:
../../../../src/include/utils/elog.h:394:15: error: ‘save_exception_stack’ is used uninitialized in this function [-Werror=uninitialized]
   sigjmp_buf *save_exception_stack = PG_exception_stack; \
               ^~~~~~~~~~~~~~~~~~~~
../../../../src/include/utils/elog.h:394:15: note: ‘save_exception_stack’ was declared here
   sigjmp_buf *save_exception_stack = PG_exception_stack; \
               ^
fileam.c:1049:5: note: in expansion of macro ‘PG_TRY’
     PG_TRY();
     ^~~~~~
../../../../src/include/utils/elog.h:395:25: error: ‘save_context_stack’ is used uninitialized in this function [-Werror=uninitialized]
   ErrorContextCallback *save_context_stack = error_context_stack; \
                         ^~~~~~~~~~~~~~~~~~
../../../../src/include/utils/elog.h:395:25: note: ‘save_context_stack’ was declared here
   ErrorContextCallback *save_context_stack = error_context_stack; \
                         ^
```
That's on ubuntu 17.10 and gcc 7.2.0

**Comment by hsyuan** [comment]
closing this issue since we got no more response.

**Comment by dapengtx** [comment]
@hsyuan please find my complier version below:
GNU Make 3.82
Built for x86_64-redhat-linux-gnu
Copyright (C) 2010  Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.


and how to remove the flag  -Werror=uninitialized

**Comment by dapengtx** [comment]
sorry for i not reply to you in time

**Comment by dapengtx** [comment]
and the gcc version info below:

使用内建 specs。
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
目标：x86_64-redhat-linux
配置为：../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
线程模型：posix
gcc 版本 4.8.5 20150623 (Red Hat 4.8.5-16) (GCC)

**Comment by xinzweb** [comment]
Thanks a lot for the additional information. With gcc 4.8.5, I got following error:

```
tidbitmap.c: In function ‘tbm_generic_iterate’:
tidbitmap.c:738:22: warning: unused variable ‘hashBitmap’ [-Wunused-variable]
     const TIDBitmap *hashBitmap = (const TIDBitmap *) tbm;
                      ^
In file included from ../../../src/include/postgres.h:54:0,
                 from execQual.c:37:
execQual.c: In function ‘ExecMakeTableFunctionResult’:
../../../src/include/utils/palloc.h:142:23: error: ‘oldcontext’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
  CurrentMemoryContext = context;
                       ^
execQual.c:2082:16: note: ‘oldcontext’ was declared here
  MemoryContext oldcontext;
                ^

vacuum.c: In function ‘vacuum’:
vacuum.c:1320:18: error: ‘stats_context.updated_stats’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
    list_free_deep(stats_context.updated_stats);
                  ^
vacuum.c:965:21: note: ‘stats_context.updated_stats’ was declared here
  VacuumStatsContext stats_context;
                     ^
In file included from ../../../src/include/access/tupdesc.h:19:0,
                 from ../../../src/include/access/htup.h:19,
                 from ../../../src/include/utils/relcache.h:19,
                 from ../../../src/include/access/xlog.h:21,
                 from ../../../src/include/access/clog.h:14,
                 from vacuum.c:29:
../../../src/include/nodes/pg_list.h:82:21: error: ‘analyze_relations’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
  return l ? l->head : NULL;
                     ^
vacuum.c:378:11: note: ‘analyze_relations’ was declared here
  List    *analyze_relations;
           ^
In file included from ../../../src/include/access/tupdesc.h:19:0,
                 from ../../../src/include/access/htup.h:19,
                 from ../../../src/include/utils/relcache.h:19,
                 from ../../../src/include/access/xlog.h:21,
                 from ../../../src/include/access/clog.h:14,
                 from vacuum.c:29:
../../../src/include/nodes/pg_list.h:94:23: error: ‘vacuum_relations’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
  return l ? l->length : 0;
                       ^
vacuum.c:377:11: note: ‘vacuum_relations’ was declared here
  List    *vacuum_relations;
           ^
```

With gcc 6.2.0, I got no errors.

Re-open the issue, since I can repro the on the gcc 4.8.5 on CentOs 7.

**Comment by d** [comment]
Older versions of GCC generate false negatives -- warnings where they might not be warranted. This is not a Greenplum issue. Please consider using Fedora, or better, Ubuntu if you plan to hack on the code.

**Comment by dapengtx** [comment]
@xinzweb thanks for your reply, and can you give me a way can to completed install the build now

**Comment by dapengtx** [comment]
@xinzweb I try to change the gcc version to 6:
use yum to install the gcc below:
`yum install devtoolset-3-gcc devtoolset-3-gcc-c++`
then run command change the gcc version to 6:
`source /opt/rh/devtoolset-3/enable`
the get the gcc version info below
```
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/opt/rh/devtoolset-6/root/usr/libexec/gcc/x86_64-redhat-linux/6.3.1/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,fortran,lto --prefix=/opt/rh/devtoolset-6/root/usr --mandir=/opt/rh/devtoolset-6/root/usr/share/man --infodir=/opt/rh/devtoolset-6/root/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --enable-plugin --with-linker-hash-style=gnu --enable-initfini-array --disable-libgcj --with-default-libstdcxx-abi=gcc4-compatible --with-isl=/builddir/build/BUILD/gcc-6.3.1-20170216/obj-x86_64-redhat-linux/isl-install --enable-libmpx --enable-gnu-indirect-function --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 6.3.1 20170216 (Red Hat 6.3.1-3) (GCC) 
```
then i try to reconfigure and make the build, and appear other issue also.....
```
/opt/rh/devtoolset-6/root/usr/libexec/gcc/x86_64-redhat-linux/6.3.1/ld: libpq/auth.o: undefined reference to symbol 'gss_delete_sec_context@@gssapi_krb5_2_MIT'
//lib64/libgssapi_krb5.so.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:79: recipe for target 'postgres' failed
make[2]: *** [postgres] Error 1
make[2]: Leaving directory '/home/gpadmin/gpdb/src/backend'
Makefile:17: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/gpadmin/gpdb/src'
GNUmakefile:14: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by xinzweb** [comment]
@dapengtx follow the instruction (like https://www.linkedin.com/pulse/installing-gcc-620-centosrhel-7-ben-lewis/) to compile and build gcc 6.2.0 on the CentOs7, then you can start from there. Or you can follow @d suggested to use a different linux platform. I am using ubuntu 17.10, and it came with 7.2.0.

**Comment by xinzweb** [comment]
I assume you did the 6 instead of 3

```
yum install centos-release-scl-rh centos-release-scl
yum check-update
yum install devtoolset-6-gcc devtoolset-6-gcc-c++
source /opt/rh/devtoolset-6/enable
```

I can build it on my CentOs7 environment.

```
[root@6bac28cb4d86 gpdb]# gcc --version
gcc (GCC) 6.3.1 20170216 (Red Hat 6.3.1-3)
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

Sorry, I am not expert on the exact error of `DSO missing from command line`, I suspect some external dependency on the `gssapi` caused the issue on your environment. I would try without the `--with-gssapi` and see if that can work around the issue you have.

**Comment by dapengtx** [comment]
@xinzweb  very thanks for you, i try to make the build after run the make clean, install complated now!!!
very thanks!

**Comment by xinzweb** [comment]
Great to know that. Close the issue.

**Comment by XuHuaiyu** [comment]
@xinzweb Hi, I meet the same error message like [the above comment](https://github.com/greenplum-db/gpdb/issues/4088#issuecomment-351582760) mentioned when I try to execute `make`.

``` shell
[gpadmin@ip-172-16-5-38 gpdb]$ gcc --version
gcc (GCC) 6.3.1 20170216 (Red Hat 6.3.1-3)
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE
```

``` shell
$ CFLAGS="-O0 -g3 -ggdb3" \
  ./configure 	--with-perl --with-python --with-libxml --enable-debug --enable-cassert \
--disable-orca --disable-gpcloud --disable-gpfdist \ 
--prefix=/home/gpadmin/gpdb.master
$ make
...
/opt/rh/devtoolset-6/root/usr/libexec/gcc/x86_64-redhat-linux/6.3.1/ld: libpq/auth.o: undefined reference to symbol 'gss_delete_sec_context@@gssapi_krb5_2_MIT'
//lib64/libgssapi_krb5.so.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:68: recipe for target 'postgres' failed
make[2]: *** [postgres] Error 1
make[2]: Leaving directory '/data3/xhy/gpdb/src/backend'
Makefile:34: recipe for target 'all-backend-recurse' failed
make[1]: *** [all-backend-recurse] Error 2
make[1]: Leaving directory '/data3/xhy/gpdb/src'
GNUmakefile:11: recipe for target 'all-src-recurse' failed
make: *** [all-src-recurse] Error 2
```
Can you help me here?
