### ISSUE TITLE
Is gpdb support read and write data with hdfs?

### ISSUE THREAD

**Issue by kisskevin** [greenplum-db/gpdb#412]
Is gpdb support read and write data with hdfs? what is the different between gpdb and hawq? thanks ,I'am wander about the two product .

**Comment by yydzero** [comment]
gpdb support read/write data with hdfs using gphdfs protocol.

HAWQ could operate data on HDFS directly without external table protocol.

On Mon, Feb 22, 2016 at 3:46 PM, kisskevin <notifications@github.com> wrote:

> Is gpdb support read and write data with hdfs? what is the different
> between dpdb and hawq? thanks ,I'am wander about the two product .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/greenplum-db/gpdb/issues/412>.
>



-- 
Best Regards,
Yandong

**Comment by kisskevin** [comment]
@yydzero thank you ! 
I have another question , I saw the docs from http://gpdb.docs.pivotal.io , it seem like 'HDFS Protocol' dose not support the apache hadoop hdfs ? how about HAWQ ? it have already contain it's own hdfs ? when I install HAWQ ?

**Comment by yydzero** [comment]
It should works even not listed in doc

On Mon, Feb 22, 2016 at 4:40 PM, kisskevin <notifications@github.com> wrote:

> @yydzero <https://github.com/yydzero> thank you !
> I have another question , I saw the docs from http://gpdb.docs.pivotal.io
> , it seem like 'HDFS Protocol' dose not support the apache hadoop hdfs ?
> how about HAWQ ? it have already contain it's own hdfs ? when I install
> HAWQ ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/greenplum-db/gpdb/issues/412#issuecomment-187074082>.
>



-- 
Best Regards,
Yandong

**Comment by lufeng1102** [comment]
Hi @yydzero ,  I use gphdfs protocol to load data from HDFS (cdh5.4.0), but throw an exception like this 
```
test=# select * from tmp_test;
ERROR:  external table gphdfs protocol command ended with error. Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/hadoop/mapreduce/lib/input/FileInputFormat  (seg14 slice1 compute-04-02-39:40002 pid=21867)
DETAIL:  
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2570)
        at java.lang.Class.getMethod0(Class.java:2813)
        at java.lang.Class.getMethod(Class.java:1663)
        at sun.launcher.LauncherHelper.getMainMethod(LauncherHelper.java:494)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:486)
Caused by: java.lang.ClassNotFoun
Command: 'gphdfs://10.128.46.39:8020/tmp/1.dat'
```

My gphd version is 1.1 and has already set gp_hadoop_home to /usr/lib/hadoop. 

Thanks

**Comment by yydzero** [comment]
please use gphdfs version 1.2.

If still got class not found exception, take a look at hadoop_env.sh file
under $GPHOME, and verify whether it includes the notfound class.

besides, need to install proper hadoop client library on all segments.

On Thu, Apr 21, 2016 at 8:10 PM, lufeng <notifications@github.com> wrote:

> Hi @yydzero <https://github.com/yydzero> , I use gphdfs protocol to load
> data from HDFS (cdh5.4.0), but throw an exception like this
>
> test=# select * from tmp_test;
> ERROR:  external table gphdfs protocol command ended with error. Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/hadoop/mapreduce/lib/input/FileInputFormat  (seg14 slice1 compute-04-02-39:40002 pid=21867)
> DETAIL:
>         at java.lang.Class.getDeclaredMethods0(Native Method)
>         at java.lang.Class.privateGetDeclaredMethods(Class.java:2570)
>         at java.lang.Class.getMethod0(Class.java:2813)
>         at java.lang.Class.getMethod(Class.java:1663)
>         at sun.launcher.LauncherHelper.getMainMethod(LauncherHelper.java:494)
>         at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:486)
> Caused by: java.lang.ClassNotFoun
> Command: 'gphdfs://10.128.46.39:8020/tmp/1.dat'
>
> My gphd version is 1.1 and has already set gp_hadoop_home to
> /usr/lib/hadoop.
>
> Thanks
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/greenplum-db/gpdb/issues/412#issuecomment-212886138>
>



-- 
Best Regards,
Yandong
