### ISSUE TITLE
I had an exception when I was created  ：make create-demo-cluster  

### ISSUE THREAD

**Issue by asen477** [greenplum-db/gpdb#4141]
make -C gpAux/gpdemo create-demo-cluster
make[1]: Entering directory '/home/trunks/Downloads/gpdb/gpdb/gpAux/gpdemo'
FATAL: The GPHOME enviroment variable is not set.

  You can set it by sourcing the greenplum_path.sh
  file in your Greenplum installation directory.

Makefile:48: recipe for target 'create-demo-cluster' failed
make[1]: *** [create-demo-cluster] Error 1
make[1]: Leaving directory '/home/trunks/Downloads/gpdb/gpdb/gpAux/gpdemo'
GNUmakefile:190: recipe for target 'create-demo-cluster' failed
make: *** [create-demo-cluster] Error 

How to solve？

**Comment by hsyuan** [comment]
source /your_own_path/greenplum_path.sh

**Comment by asen477** [comment]
@hsyuan Thinks
source gpAux/gpdemo/gpdemo-env.sh
After that
operating system：deepin 15.5

make -C gpAux/gpdemo create-demo-cluster
make[1]: Entering directory '/home/trunks/Downloads/gpdb/gpdb/gpAux/gpdemo'
======================================================================
            ______  _____  ______  _______ _______  _____
           |  ____ |_____] |     \ |______ |  |  | |     |
           |_____| |       |_____/ |______ |  |  | |_____|

----------------------------------------------------------------------

  This is a demo of the Greenplum Database system.  We will create
  a cluster installation with master and 6 segment instances
  (3 primary & 3 mirror).

    GPHOME ................. : /usr/local/gpdb
    MASTER_DATA_DIRECTORY .. : /home/trunks/Downloads/gpdb/gpdb/gpAux/gpdemo/datadirs/qddir/demoDataDir-1

    MASTER PORT (PGPORT) ... : 15432
    SEGMENT PORTS .......... : 25432 25433 25434 25435 25436 25437 25438 25439 25440 25441 25442 25443

  NOTE(s):

    * The DB ports identified above must be available for use.
    * An environment file gpdemo-env.sh has been created for your use.

======================================================================

==========================================================================================
executing:
  /usr/local/gpdb/bin/gpinitsystem -a -c clusterConfigFile -l /home/trunks/Downloads/gpdb/gpdb/gpAux/gpdemo/datadirs/gpAdminLogs ""
==========================================================================================

[FATAL]:-Scripts must be run by a user account that has SHELL=/bin/bash
[INFO]:-/bin/bash exists, please update user account shell
========================================
gpinitsystem returned: 2
========================================

======================================================================
                           OPTIMIZER STATE
----------------------------------------------------------------------
  Optimizer state .. : psql: could not connect to server: 没有那个文件或目录
	Is the server running locally and accepting
	connections on Unix domain socket "/tmp/.s.PGSQL.15432"?
======================================================================

psql: could not connect to server: 没有那个文件或目录
	Is the server running locally and accepting
	connections on Unix domain socket "/tmp/.s.PGSQL.15432"?
======================================================================

Makefile:48: recipe for target 'create-demo-cluster' failed
make[1]: *** [create-demo-cluster] Error 2
make[1]: Leaving directory '/home/trunks/Downloads/gpdb/gpdb/gpAux/gpdemo'
GNUmakefile:190: recipe for target 'create-demo-cluster' failed
make: *** [create-demo-cluster] Error 2

**Comment by hsyuan** [comment]
```
source gpAux/gpdemo/gpdemo-env.sh
SHELL=/bin/bash
```

**Comment by yydzero** [comment]
any updates on this issue?

**Comment by ashwinstar** [comment]
I am closing the issue considering no response as last recommendation resolved the problem. If not and still faced with the issue feel free to let us know.
