### ISSUE TITLE
DBlink doesn't work with Postgresql 8.3.23 and  9.6 ?

### ISSUE THREAD

**Issue by kongyew** [greenplum-db/gpdb#4148]
### Greenplum version or build
GPDB 5.2

### OS version and uname -a
Centos

### Installation information ( pg_config )
Testing dblink from Greenplum to access Postgresql 8.3.23 and 9.6

### Expected behavior
Connection is successful when we run these commands.

gpadmin=# SELECT dblink_connect('host=postgresql port=5432 dbname=postgres');
ERROR:  could not establish connection
DETAIL:  FATAL:  unsupported frontend protocol 28675.0: server supports 1.0 to 3.0

### Actual behavior
ERROR:  could not establish connection
DETAIL:  FATAL:  unsupported frontend protocol 28675.0: server supports 1.0 to 3.0

### Step to reproduce the behavior.
Follow these instructions to setup DBLink on GPDB 5.2
Link: https://gpdb.docs.pivotal.io/520/utility_guide/dblink.html

**Comment by lij55** [comment]
The dblink in Greenplum is for Greenplum cluster of same version only currently.

**Comment by mkiyama** [comment]
@lij55 Are you saying gpdb dblink only connects gpdb <--> gpdb
and gpdb has to be the same version?

thanks

**Comment by kongyew** [comment]
This feature seems limited since postgresql dblink can connect other postgresql servers.   I wonder what is the typical use case if dblink can work for GPDB cluster with same version.

**Comment by hlinnaka** [comment]
Works on GPDB master now.

**Comment by adam8157** [comment]
Fixed by #9462
