### ISSUE TITLE
CentOS 6.5 ./configure :   configure: error: library 'gpos' is required

### ISSUE THREAD

**Issue by LightYears88** [greenplum-db/gpdb#4149]
I have install the dependencies  sucessfully.My step  
./README.CentOS.bash
./configure --with-perl --with-python --with-libxml --with-gssapi --prefix=$HOME/greenplum-db
My error details:
checking CURL_LIBS... -lcurl  
checking whether CURLOPT_MAIL_FROM is declared... no
checking for BZ2_bzDecompress in -lbz2... yes
checking for strnicmp in -lxerces-c... yes
checking for Xerces-C... checking for gpos_init in -lgpos... no
configure: error: library 'gpos' is required for Pivotal Query Optimizer (orca)

It seems like the library gpos is needed. But I don't know where the library to find? Which library should I install?

**Comment by danielgustafsson** [comment]
gpos is a part of the Orca optimizer, so installing Orca will bring in all the libraries required. See the section **"Building Greenplum Database with GPORCA"** in the Greenplum [README.md](https://github.com/greenplum-db/gpdb/blob/master/README.md) file for instructions on how to install via dependency manager or compile it from source.

**Comment by LightYears88** [comment]
thans

**Comment by danielgustafsson** [comment]
Post either a new item here or on the [gpdb-users mailinglist](http://greenplum.org/mailing-lists/) in case there are any other problems.

**Comment by CorleoneZ** [comment]
But I watched .md ,i can't found it

**Comment by CorleoneZ** [comment]
> configure: error: library 'gpos' is required for GPORCA


i got this problem and i install gpdb many days,but it is too  complex.
help me
