### ISSUE TITLE
No tags or releases to coincide with releases on Pivotal

### ISSUE THREAD

**Issue by inviscid** [greenplum-db/gpdb#415]
Would it be possible to have tags or releases that coincide with the official Greenplum releases.

**Comment by ascherbaum-pivotal** [comment]
The official releases from Pivotal are - as of now - based on the GPDB version 4 branch. The GitHub repository is the version 5 branch, with upcoming features.

The version 4 branch is not public, but all new features and bug fixes go into the version 5 branch, the previous branch is just for maintaining purposes.

As of now we don't have an official tagging or releasing system, based on the GitHub repository.
