### ISSUE TITLE
Documentation to build extension gphdfs along with Greenplum database

### ISSUE THREAD

**Issue by jagatsingh** [greenplum-db/gpdb#4164]
Update the Readme to include the documentation for gphdfs build and install.

### Greenplum version or build
5.3.0

**Comment by lavjain** [comment]
GPHDFS is being deprecated in favor of PXF. Please take a look at  https://hdb.docs.pivotal.io/230/hawq/pxf/HawqExtensionFrameworkPXF.html

**Comment by schubert** [comment]
Well that may be the case but GPHDFS isn't going away from 5.x since we don't pull features in a major release only between releases.

It's not unreasonable to ask for us to document a feature that is going to live in 5X_STABLE for quite some time (years).

cc @kongyew

**Comment by kongyew** [comment]
@lavjain  Please confirm this issue is fixed. If yes, we can close this issue

**Comment by ivannovick** [comment]
gphdfs is deprecated
