### ISSUE TITLE
psql gives fatal error 

### ISSUE THREAD

**Issue by Dishcreate** [greenplum-db/gpdb#4167]
I have install greenplum on my server and create gpadmin user. After I try to run this command 
`$GHOME/bin/psql `
But it gives below error 
`psql: FATAL:  could not open relation 1664/0/1260: No such file or directory`
Can any one help to find reason for this error

**Comment by pengzhout** [comment]
I met similar issue before, in my case the whole global directory was gone somehow, so I'm curious does global directory exist under your $MASTER_DATA_DIRECTORY? ``` ls $MASTER_DATA_DIRECTORY```

**Comment by Dishcreate** [comment]
Yes
MASTER_DATA_DIRECTORY=/tmp/gpdb-cluster2/qddir/demoDataDir-1

**Comment by pengzhout** [comment]
Can you help to attach the output of ```ls  /tmp/gpdb-cluster2/qddir/demoDataDir-1```?

**Comment by Dishcreate** [comment]
Yes sure
base     gpperfmon          pg_clog               pg_hba.conf    pg_multixact  pg_tblspc              PG_VERSION       postmaster.opts
global   gpssh.conf         pg_distributedlog     pg_ident.conf  pg_stat_tmp   pg_twophase            pg_xlog          postmaster.pid
gp_dbid  pg_changetracking  pg_distributedxidmap  pg_log         pg_subtrans   pg_utilitymodedtmredo  postgresql.conf

**Comment by pengzhout** [comment]
Ahh, not the same issue I met in the pipeline job, but the fatal message seems to indicate that file "/tmp/gpdb-cluster2/qddir/demoDataDir-1/global/1260" doesn't exist or has no proper right.

**Comment by Dishcreate** [comment]
Do you know the reason why this happen?

**Comment by pengzhout** [comment]
@Dishcreate so is file 1260 confirmed missing in your environment? please list all files under /tmp/gpdb-cluster2/qddir/demoDataDir-1/global/ to see if other catalog tables are lost too.

**Comment by Dishcreate** [comment]
@pengzhout 
`-rw------- 1 gpadmin gpadmin 32768 Dec 18 10:52 1136
-rw------- 1 gpadmin gpadmin 65536 Dec 18 10:52 1137
-rw------- 1 gpadmin gpadmin 32768 Dec 18 10:52 1213
-rw------- 1 gpadmin gpadmin 32768 Dec 18 10:53 1214
-rw------- 1 gpadmin gpadmin 65536 Dec 18 10:52 1232
-rw------- 1 gpadmin gpadmin 65536 Dec 18 10:52 1233
-rw------- 1 gpadmin gpadmin 32768 Dec 18 10:59 1260
-rw------- 1 gpadmin gpadmin     0 Dec 18 10:52 1261
-rw------- 1 gpadmin gpadmin 32768 Dec 18 10:53 1262
-rw------- 1 gpadmin gpadmin 32768 Dec 18 10:53 2396
-rw------- 1 gpadmin gpadmin 65536 Dec 18 10:52 2397
-rw------- 1 gpadmin gpadmin 65536 Dec 18 10:53 2671
-rw------- 1 gpadmin gpadmin 65536 Dec 18 10:53 2672
-rw------- 1 gpadmin gpadmin 65536 Dec 18 10:52 2676
-rw------- 1 gpadmin gpadmin 65536 Dec 18 10:52 2677
-rw------- 1 gpadmin gpadmin 32768 Dec 18 10:52 2694
-rw------- 1 gpadmin gpadmin 32768 Dec 18 10:52 2695
-rw------- 1 gpadmin gpadmin 65536 Dec 18 10:52 2697
-rw------- 1 gpadmin gpadmin 65536 Dec 18 10:52 2698
-rw------- 1 gpadmin gpadmin     0 Dec 18 10:52 2842
-rw------- 1 gpadmin gpadmin 32768 Dec 18 10:52 2843
-rw------- 1 gpadmin gpadmin     0 Dec 18 10:52 2844
-rw------- 1 gpadmin gpadmin 32768 Dec 18 10:52 2845
-rw------- 1 gpadmin gpadmin     0 Dec 18 10:52 2846
-rw------- 1 gpadmin gpadmin 32768 Dec 18 10:52 2847
-rw------- 1 gpadmin gpadmin 65536 Dec 18 10:52 2858
-rw------- 1 gpadmin gpadmin     0 Dec 18 10:52 5000
-rw------- 1 gpadmin gpadmin 32768 Dec 18 10:52 5001
-rw------- 1 gpadmin gpadmin 32768 Dec 18 10:52 5003
-rw------- 1 gpadmin gpadmin     0 Dec 18 10:52 5006
-rw------- 1 gpadmin gpadmin 32768 Dec 18 10:52 5009
-rw------- 1 gpadmin gpadmin     0 Dec 18 10:52 5029
-rw------- 1 gpadmin gpadmin     0 Dec 18 10:52 5030
-rw------- 1 gpadmin gpadmin 32768 Dec 18 10:53 5033
-rw------- 1 gpadmin gpadmin 32768 Dec 18 10:53 5036
-rw------- 1 gpadmin gpadmin 32768 Dec 18 10:53 5039
-rw------- 1 gpadmin gpadmin 98304 Dec 18 10:53 5090
-rw------- 1 gpadmin gpadmin 32768 Dec 18 10:53 5091
-rw------- 1 gpadmin gpadmin     0 Dec 18 10:52 5092
-rw------- 1 gpadmin gpadmin     0 Dec 18 10:52 5093
-rw------- 1 gpadmin gpadmin 32768 Dec 18 10:53 5096
-rw------- 1 gpadmin gpadmin 32768 Dec 18 10:53 6026
-rw------- 1 gpadmin gpadmin 65536 Dec 18 10:52 6027
-rw------- 1 gpadmin gpadmin 65536 Dec 18 10:52 6028
-rw------- 1 gpadmin gpadmin 65536 Dec 18 10:52 6029
-rw------- 1 gpadmin gpadmin 32768 Dec 18 10:59 6056
-rw------- 1 gpadmin gpadmin 65536 Dec 18 10:59 6057
-rw------- 1 gpadmin gpadmin 65536 Dec 18 10:59 6058
-rw------- 1 gpadmin gpadmin 32768 Dec 18 10:52 6059
-rw------- 1 gpadmin gpadmin 32768 Dec 18 10:53 6060
-rw------- 1 gpadmin gpadmin 65536 Dec 18 10:52 6061
-rw------- 1 gpadmin gpadmin 65536 Dec 18 10:52 6062
-rw------- 1 gpadmin gpadmin 65536 Dec 18 10:52 6063
-rw------- 1 gpadmin gpadmin     0 Dec 18 10:52 6070
-rw------- 1 gpadmin gpadmin 65536 Dec 18 10:53 6090
-rw------- 1 gpadmin gpadmin 65536 Dec 18 10:53 6091
-rw------- 1 gpadmin gpadmin     0 Dec 18 10:52 6092
-rw------- 1 gpadmin gpadmin 32768 Dec 18 10:52 6093
-rw------- 1 gpadmin gpadmin     0 Dec 18 10:52 6094
-rw------- 1 gpadmin gpadmin 32768 Dec 18 10:52 6095
-rw------- 1 gpadmin gpadmin 32768 Dec 18 10:52 6101
-rw------- 1 gpadmin gpadmin 32768 Dec 18 10:52 6102
-rw------- 1 gpadmin gpadmin 65536 Dec 18 10:53 6106
-rw------- 1 gpadmin gpadmin 65536 Dec 18 10:53 6107
-rw------- 1 gpadmin gpadmin 32768 Dec 18 10:52 6108
-rw------- 1 gpadmin gpadmin 32768 Dec 18 10:52 6109
-rw------- 1 gpadmin gpadmin 32768 Dec 18 10:52 6436
-rw------- 1 gpadmin gpadmin 32768 Dec 18 10:52 6439
-rw------- 1 gpadmin gpadmin 65536 Dec 18 10:52 6440
-rw------- 1 gpadmin gpadmin 65536 Dec 18 10:53 6441
-rw------- 1 gpadmin gpadmin 65536 Dec 18 10:53 6442
-rw------- 1 gpadmin gpadmin 65536 Dec 18 10:53 6443
-rw------- 1 gpadmin gpadmin 65536 Dec 18 10:52 6444
-rw------- 1 gpadmin gpadmin 65536 Dec 18 10:52 6445
-rw------- 1 gpadmin gpadmin 65536 Dec 18 10:52 6446
-rw------- 1 gpadmin gpadmin 65536 Dec 18 10:52 6447
-rw------- 1 gpadmin gpadmin 65536 Dec 18 10:52 6448
-rw------- 1 gpadmin gpadmin 65536 Dec 18 10:52 6998
-rw------- 1 gpadmin gpadmin    51 Dec 18 10:54 pg_auth
-rw------- 1 gpadmin gpadmin     0 Dec 18 10:54 pg_auth_time_constraint
-rw------- 1 gpadmin gpadmin  8192 Dec 18 10:59 pg_control
-rw------- 1 gpadmin gpadmin    76 Dec 18 10:54 pg_database
-rw------- 1 gpadmin gpadmin    16 Dec 18 10:53 pg_fsm.cache
-rw------- 1 gpadmin gpadmin 11180 Dec 18 10:54 pg_internal.init
`

**Comment by Dishcreate** [comment]
@pengzhout 
-rw------- 1 gpadmin gpadmin 32768 Dec 18 10:52 1136
-rw------- 1 gpadmin gpadmin 65536 Dec 18 10:52 1137
-rw------- 1 gpadmin gpadmin 32768 Dec 18 10:52 1213
-rw------- 1 gpadmin gpadmin 32768 Dec 18 10:53 1214
-rw------- 1 gpadmin gpadmin 65536 Dec 18 10:52 1232
-rw------- 1 gpadmin gpadmin 65536 Dec 18 10:52 1233
-rw------- 1 gpadmin gpadmin 32768 Dec 18 10:59 1260
-rw------- 1 gpadmin gpadmin     0 Dec 18 10:52 1261
-rw------- 1 gpadmin gpadmin 32768 Dec 18 10:53 1262
-rw------- 1 gpadmin gpadmin 32768 Dec 18 10:53 2396
-rw------- 1 gpadmin gpadmin 65536 Dec 18 10:52 2397
-rw------- 1 gpadmin gpadmin 65536 Dec 18 10:53 2671
-rw------- 1 gpadmin gpadmin 65536 Dec 18 10:53 2672
-rw------- 1 gpadmin gpadmin 65536 Dec 18 10:52 2676
-rw------- 1 gpadmin gpadmin 65536 Dec 18 10:52 2677
-rw------- 1 gpadmin gpadmin 32768 Dec 18 10:52 2694
-rw------- 1 gpadmin gpadmin 32768 Dec 18 10:52 2695
-rw------- 1 gpadmin gpadmin 65536 Dec 18 10:52 2697
-rw------- 1 gpadmin gpadmin 65536 Dec 18 10:52 2698
-rw------- 1 gpadmin gpadmin     0 Dec 18 10:52 2842
-rw------- 1 gpadmin gpadmin 32768 Dec 18 10:52 2843
-rw------- 1 gpadmin gpadmin     0 Dec 18 10:52 2844
-rw------- 1 gpadmin gpadmin 32768 Dec 18 10:52 2845
-rw------- 1 gpadmin gpadmin     0 Dec 18 10:52 2846
-rw------- 1 gpadmin gpadmin 32768 Dec 18 10:52 2847
-rw------- 1 gpadmin gpadmin 65536 Dec 18 10:52 2858
-rw------- 1 gpadmin gpadmin     0 Dec 18 10:52 5000
-rw------- 1 gpadmin gpadmin 32768 Dec 18 10:52 5001
-rw------- 1 gpadmin gpadmin 32768 Dec 18 10:52 5003
-rw------- 1 gpadmin gpadmin     0 Dec 18 10:52 5006
-rw------- 1 gpadmin gpadmin 32768 Dec 18 10:52 5009
-rw------- 1 gpadmin gpadmin     0 Dec 18 10:52 5029
-rw------- 1 gpadmin gpadmin     0 Dec 18 10:52 5030
-rw------- 1 gpadmin gpadmin 32768 Dec 18 10:53 5033
-rw------- 1 gpadmin gpadmin 32768 Dec 18 10:53 5036
-rw------- 1 gpadmin gpadmin 32768 Dec 18 10:53 5039
-rw------- 1 gpadmin gpadmin 98304 Dec 18 10:53 5090
-rw------- 1 gpadmin gpadmin 32768 Dec 18 10:53 5091
-rw------- 1 gpadmin gpadmin     0 Dec 18 10:52 5092
-rw------- 1 gpadmin gpadmin     0 Dec 18 10:52 5093
-rw------- 1 gpadmin gpadmin 32768 Dec 18 10:53 5096
-rw------- 1 gpadmin gpadmin 32768 Dec 18 10:53 6026
-rw------- 1 gpadmin gpadmin 65536 Dec 18 10:52 6027
-rw------- 1 gpadmin gpadmin 65536 Dec 18 10:52 6028
-rw------- 1 gpadmin gpadmin 65536 Dec 18 10:52 6029
-rw------- 1 gpadmin gpadmin 32768 Dec 18 10:59 6056
-rw------- 1 gpadmin gpadmin 65536 Dec 18 10:59 6057
-rw------- 1 gpadmin gpadmin 65536 Dec 18 10:59 6058
-rw------- 1 gpadmin gpadmin 32768 Dec 18 10:52 6059
-rw------- 1 gpadmin gpadmin 32768 Dec 18 10:53 6060
-rw------- 1 gpadmin gpadmin 65536 Dec 18 10:52 6061
-rw------- 1 gpadmin gpadmin 65536 Dec 18 10:52 6062
-rw------- 1 gpadmin gpadmin 65536 Dec 18 10:52 6063
-rw------- 1 gpadmin gpadmin     0 Dec 18 10:52 6070
-rw------- 1 gpadmin gpadmin 65536 Dec 18 10:53 6090
-rw------- 1 gpadmin gpadmin 65536 Dec 18 10:53 6091
-rw------- 1 gpadmin gpadmin     0 Dec 18 10:52 6092
-rw------- 1 gpadmin gpadmin 32768 Dec 18 10:52 6093
-rw------- 1 gpadmin gpadmin     0 Dec 18 10:52 6094
-rw------- 1 gpadmin gpadmin 32768 Dec 18 10:52 6095
-rw------- 1 gpadmin gpadmin 32768 Dec 18 10:52 6101
-rw------- 1 gpadmin gpadmin 32768 Dec 18 10:52 6102
-rw------- 1 gpadmin gpadmin 65536 Dec 18 10:53 6106
-rw------- 1 gpadmin gpadmin 65536 Dec 18 10:53 6107
-rw------- 1 gpadmin gpadmin 32768 Dec 18 10:52 6108
-rw------- 1 gpadmin gpadmin 32768 Dec 18 10:52 6109
-rw------- 1 gpadmin gpadmin 32768 Dec 18 10:52 6436
-rw------- 1 gpadmin gpadmin 32768 Dec 18 10:52 6439
-rw------- 1 gpadmin gpadmin 65536 Dec 18 10:52 6440
-rw------- 1 gpadmin gpadmin 65536 Dec 18 10:53 6441
-rw------- 1 gpadmin gpadmin 65536 Dec 18 10:53 6442
-rw------- 1 gpadmin gpadmin 65536 Dec 18 10:53 6443
-rw------- 1 gpadmin gpadmin 65536 Dec 18 10:52 6444
-rw------- 1 gpadmin gpadmin 65536 Dec 18 10:52 6445
-rw------- 1 gpadmin gpadmin 65536 Dec 18 10:52 6446
-rw------- 1 gpadmin gpadmin 65536 Dec 18 10:52 6447
-rw------- 1 gpadmin gpadmin 65536 Dec 18 10:52 6448
-rw------- 1 gpadmin gpadmin 65536 Dec 18 10:52 6998
-rw------- 1 gpadmin gpadmin    51 Dec 18 10:54 pg_auth
-rw------- 1 gpadmin gpadmin     0 Dec 18 10:54 pg_auth_time_constraint
-rw------- 1 gpadmin gpadmin  8192 Dec 18 10:59 pg_control
-rw------- 1 gpadmin gpadmin    76 Dec 18 10:54 pg_database
-rw------- 1 gpadmin gpadmin    16 Dec 18 10:53 pg_fsm.cache
-rw------- 1 gpadmin gpadmin 11180 Dec 18 10:54 pg_internal.init

**Comment by pengzhout** [comment]
Sadly, I have no idea now. + @hlinnaka @danielgustafsson @ashwinstar @asimrp who have a better experience.

**Comment by asimrp** [comment]
Hi @Dishcreate, apologies for responding so late.  The error is emitted by `mdopen()` function.  Can you please answer the following questions?
1. What version of code are you using?
2. Does your GPDB deployment contain mirrors?
3. Can you confirm the error happened on master?  You will have to lookup master logs and look for "could not open relation 1664/0/1260"?  Master logs can be found in `$MASTER_DATA_DIRECTORY/pg_log/`
4. Is the error still happening?  If so, then set `log_min_messages=debug` in `$MASTER_DATA_DIRECTORY/postgresql.conf` and try again.  Then post the logs generated in master's log file.
