### ISSUE TITLE
ALTER TYPE RENAME returns error

### ISSUE THREAD

**Issue by lisakowen** [greenplum-db/gpdb#4192]
ithe ALTER TYPE RENAME command does not appear to be working.
- tab completion is working for the command
- i noticed there were no tests for ALTER TYPE RENAME
- the command, when executed, returns an error:

testdb=# CREATE TYPE type1 AS (f1 int, f2 text);
CREATE TYPE
testdb=# ALTER TYPE type1 RENAME type1new;
ERROR:  syntax error at or near "RENAME"
LINE 1: ALTER TYPE type1 RENAME type1new;
                         ^
testdb=# ALTER TYPE type1 RENAME TO type1new;
ERROR:  syntax error at or near "RENAME"
LINE 1: ALTER TYPE type1 RENAME TO type1new;

i built gpdb master branch at commit 1258a14f2fbbc using the pivotaldata/gpdb-dev docker image.

should this command work in gpdb master branch?

**Comment by hlinnaka** [comment]
Yeah, that should work on `master` branch. It does work for me. Are you sure you were using a correct version? What does `select version()` return?

**Comment by lisakowen** [comment]
thanks for checking, @hlinnaka .  i was using a suspect build in a docker image.  

tried it again in a new build.  finding that the first variant does not work, but the second docs (RENAME TO):

testdb=# CREATE TYPE type1 AS (f1 int, f2 text);
CREATE TYPE
testdb=# ALTER TYPE type1 RENAME type1new;
ERROR:  syntax error at or near "type1new"
LINE 1: ALTER TYPE type1 RENAME type1new;
                                ^
testdb=# select version();
                                                                                
                                          version                               
                                                                                
            
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
------------
 PostgreSQL 8.4devel (Greenplum Database 6.0.0-alpha.0+dev.1643.g787d72a build c
ommit:787d72aeaefc81e1e4a638eb6b876f5b1d1cb20e-oss) on x86_64-pc-linux-gnu, comp
iled by GCC gcc (GCC) 6.2.0, 64-bit compiled on Dec  4 2017 19:24:02 (with asser
t checking)
(1 row)

testdb=# ALTER TYPE type1 RENAME TO type1new;
ALTER TYPE
