### ISSUE TITLE
GPHDFS with Kerberos does not work (GPDB 5.3.0)

### ISSUE THREAD

**Issue by mayukhghoshme** [greenplum-db/gpdb#4221]
Greenplum Version: 
================
`PostgreSQL 8.3.23 (Greenplum Database 5.0.0 build dev) on x86_64-pc-linux-gnu, compiled by GCC gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-16), 64-bit compiled
on Dec 24 2017 00:31:05`

OS Version:
========
`Linux 3.10.0-514.6.1.el7.x86_64 #1 SMP Wed Jan 18 13:06:36 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

Repro:
=====

Writable Ext Table creation:
======================
`gpadmin=# create writable external table test_gphdfs(id int) location('gphdfs://getnamenode:8020/user/gpadmin/test_gphdfs') format 'text';
CREATE EXTERNAL TABLE
Time: 764.839 ms`

Inserting records:
==============
`gpadmin=# insert into test_gphdfs values(100);
ERROR:  external table gphdfs protocol command ended with error. 17/12/28 02:08:28 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable  (seg28 xx.xxx.x.xxx:40004 pid=50303)
DETAIL:

17/12/28 02:08:28 INFO Configuration.deprecation: mapred.output.compression.type is deprecated. Instead, use mapreduce.output.fileoutputformat.compress.type
17/12/28 02:08:28 INFO Configuration.deprecation: mapred.output.compression.codec is deprecated. Instead, use mapreduce.output.fileoutputformat.compress.codec
17/12/28 02:08:28 WARN shortcircuit.Doma
Command: execute:source $GPHOME/lib//hadoop/hadoop_env.sh;java $GP_JAVA_OPT -classpath $CLASSPATH com.emc.greenplum.gpdb.hdfsconnector.HDFSWriter $GP_SEGMENT_ID $GP_XID TEXT cdh4.1-gnet-1.2.0.0 'gphdfs://getnamenode:8020/user/gpadmin/test_gphdfs' `

Inserting records after kinit:
=======================
`gpssh -f hostfile
=> kinit -kt /home/gpadmin/gphdfs.service.keytab gpa...@xxx.xx.com
[sdw7]
[smdw]
[ mdw]
[sdw4]
[sdw6]
[sdw5]
[sdw1]
[sdw2]
[sdw3]
=> quit`

`gpadmin=# insert into test_gphdfs values(100);
INSERT 0 1
Time: 8255.564 ms
gpadmin=# \q`

**Comment by hlinnaka** [comment]
I suppose https://github.com/greenplum-db/gpdb/pull/6735 makes this moot.

**Comment by frankgh** [comment]
@hlinnaka GPHDFS is only being removed from 6.

**Comment by berlin-ab** [comment]
Should this be moved to PXF, or closed?

**Comment by lavjain** [comment]
There is no new development being done on GPHDFS. The recommendation is to move to PXF (works with 5.X and supports Kerberos).
