### ISSUE TITLE
How to load data in memory for OLTP in gp?

### ISSUE THREAD

**Issue by Junvn** [greenplum-db/gpdb#4263]

**Comment by hlinnaka** [comment]
There is nothing to "pin" some table into memory. But if a table is accessed frequently, it will surely stay in cache. So it will effectively work like an in-memory table for all practical purposes.

That is true at least for heap tables. Append-Optimized tables never use the shared buffer cache. They will also be cached in the OS cache, but there's still always a syscall involved in accessig it.

**Comment by hlinnaka** [comment]
Closing this, but feel free to post to the gpdb-users mailing list if you want to discuss further (http://greenplum.org/mailing-lists/). Others on that list might have better suggestions or ideas, if you describe in more detail what you're trying to do.

**Comment by Junvn** [comment]
thank you for your advise @hlinnaka
