### ISSUE TITLE
aggregates bug in make installcheck-good

### ISSUE THREAD

**Issue by fengttt** [greenplum-db/gpdb#427]
src/test/regression/expected/aggregates.out, about line 550, 
select array_agg(distinct a)
  from (values (1),(2),(1),(3),(null),(2)) v(a);
##  array_agg 

 {1,2,3}
(1 row)

I believe the result should be {1,2,3,null}.

**Comment by liruto** [comment]
Hmm, I think you're right. In function '_process_ordered_aggregate_single_', agg(DISTINCT x) dropped null values of x unconditionally, regardless of the transition function's strictness.	
```
		/*
		 * If DISTINCT mode, and not distinct from prior, skip it.
		 */
		if (isDistinct && *isNull ) 
		{ 
			/* per SQL, DISTINCT doesn't use nulls */
		}
		else if (isDistinct &&
				 haveOldVal &&
				 ((oldIsNull && *isNull) ||
				  (!oldIsNull && !*isNull &&
				   DatumGetBool(FunctionCall2(&peraggstate->equalfn,
											  oldVal, *newVal)))))
		{
			/* equal to prior, so forget this one */
			if (!peraggstate->inputtypeByVal && !*isNull)
				pfree(DatumGetPointer(*newVal));
		}
```
In PostgresSQL after commit '_SHA-1: 34d26872ed816b299eef2fa4240d55316697f42d_', result should be the same as your expected, I think.

**Comment by hardikar** [comment]
Fixed with https://github.com/greenplum-db/gpdb/pull/1293.
