### ISSUE TITLE
Doc updates required - gpcondump/gpdbresore being removed.

### ISSUE THREAD

**Issue by mkiyama** [greenplum-db/gpdb#4288]
This issue describes the changes to the GPDB documentation for the replacement
of the utilities gpcondump/gpdbresore with gpbackup/gprestore.

This pull request removes gpcrondump/gpdbrestore https://github.com/greenplum-db/gpdb/pull/4286

However, documentation in gpdb-doc is not being changed in the PR.

The documentation will be updated with information about gpbackup and gprestore  in separate PRs

**Comment by yydzero** [comment]
@mkiyama is this still an issue?

**Comment by mkiyama** [comment]
docs have been updated in the master branch.
