### ISSUE TITLE
ERROR:  Unexpected internal error (cdbgang.c:1662)

### ISSUE THREAD

**Issue by chongzi777** [greenplum-db/gpdb#4294]
### Greenplum version or build
PostgreSQL 8.2.15 (Greenplum Database 4.3.13.0 build 1) on x86_64-unknown-linux-gnu, compiled by GCC gcc (GCC) 4.4.2 compiled on Apr 26 2017 16:30:57
### OS version and uname -a
CentOS release 6.6 (Final)
Kernel \r on an \m
### Expected behavior
I added a new role, and set the permissions
### Actual behavior
login succeeded, but error when execute the query,the error message are:
"ERROR:  Unexpected internal error (cdbgang.c:1662)"

**Comment by hsyuan** [comment]
Nothing we can do with these info. Can you elaborate? How can I reproduce it?

**Comment by yydzero** [comment]
@chongzi777 could you please describe reproduce steps? Thanks for reporting.

**Comment by ashwinstar** [comment]
Unfortunate not enough info to investigate the issue. Try the latest master if still happens please report back with detailed repro steps to help investigate and fix the issue.
