### ISSUE TITLE
get wrong metadata by jdbc (step 2 restultsetmetadata)

### ISSUE THREAD

**Issue by wjzeng** [greenplum-db/gpdb#4296]
### Greenplum version or build
PostgreSQL 8.3.23 (Greenplum Database 5.2.0 build commit:bd246497f15c815452ba4f702b2926a5c4e8b376) on x86_64-pc-linux-gnu, compiled by GCC gcc (GCC) 6.2.0 compiled on Nov 18 2017 00:05:03
### Step to reproduce the behavior
run testGreenplum.java
[testGreenplum.zip](https://github.com/greenplum-db/gpdb/files/1622357/testGreenplum.zip)

get 3 results
1 columns info
2 restultsetmetadata
3 columns info

The data in step 2 is different from 1 3
![gp_res](https://user-images.githubusercontent.com/10137513/34824246-9b41bcaa-f708-11e7-9907-c02fe82d5112.jpeg)

**Comment by hsyuan** [comment]
Thanks for reporting. I think this is a known issue. Orca doesn't preserve the transient type info, vartypmod. Can you try turning optimizer off?

**Comment by wjzeng** [comment]
set optimizer = off;
The result is correct
so, it is a bug introduced by orac?

**Comment by hsyuan** [comment]
Yes, it is not newly introduced. The issue has been existing for long. We are working on this recently. Stay tuned.

**Comment by wjzeng** [comment]
Got it, thank you for your reply

**Comment by ivannovick** [comment]
its this an ORCA bug still @vraghavan78 ?

**Comment by lij55** [comment]
verified on 6.19.1 with orca:
```
test=# \d test_metadata 
        Table "public.test_metadata"
 Column |         Type          | Modifiers 
--------+-----------------------+-----------
 c1     | character varying(10) | 
 c2     | numeric(18,2)         | 
Distributed by: (c1)

test=# show optimizer;
 optimizer 
-----------
 on
(1 row)

test=# select version();
                                                                                                version                                                                             
                   
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-------------------
 PostgreSQL 9.4.26 (Greenplum Database 6.19.1 build commit:0e314744a460630073b46cea7b7cf20a81e3da63) on x86_64-unknown-linux-gnu, compiled by gcc (GCC) 6.4.0, 64-bit compiled on Ja
n 18 2022 13:41:23
(1 row)

test=# show optimizer;
 optimizer 
-----------
 on
(1 row)

```
The result are:
```
Get Table(test_metadata) Columns Info:
tableName 	 colname 	  type 	  typeName 	 length
test_metadata	c1	12	CHARACTER VARYING	10	0
test_metadata	c2	2	NUMERIC	18	2

Get Table (test_metadata) ResultSetMetaData:
tableName 	  colname 	 type 	 typeName 	 prec 	 displaySize
test_metadata	c1	12	CHARACTER VARYING	10	0	10
test_metadata	c2	2	NUMERIC	18	2	20

Get Table(tmp_test_metadata) Columns Info:
tableName 	 colname 	  type 	  typeName 	 length
tmp_test_metadata	c1	12	CHARACTER VARYING	10	0
tmp_test_metadata	c2	2	NUMERIC	18	2

Process finished with exit code 0
```

it seems fixed on GP6.

Please feel free to reopen it if you found it still exist, @wjzeng . Thanks!
