### ISSUE TITLE
[Docs] - wrong paragraph name in Best Practices

### ISSUE THREAD

**Issue by kapustor** [greenplum-db/gpdb#4297]
### Greenplum version or build
5.2, 5.3
### OS version and uname -a
n/a
### autoconf options used ( config.status --config )
n/a
### Installation information ( pg_config )
n/a
### Expected behavior
The problem is on best practices page:
https://gpdb.docs.pivotal.io/520/best_practices/sysconfig.html
https://gpdb.docs.pivotal.io/530/best_practices/sysconfig.html
differs from 
https://gpdb.docs.pivotal.io/510/best_practices/sysconfig.html

The paragraph that starts with "The gp_vmem_protect_limit server configuration parameter specifies..."
in 5.1 is called "Segment Memory Configuration", which is correct. But in 5.2 and 5.3 it is called "Resource Queue Segment Memory Configuration", which is actually located on the same page, but later.
### Actual behavior
The paragraph that starts with "The gp_vmem_protect_limit server configuration parameter specifies..." is called "Resource Queue Segment Memory Configuration" instead of "Segment Memory Configuration".
### Step to reproduce the behavior
Click https://gpdb.docs.pivotal.io/530/best_practices/sysconfig.html

P.S. I'm not bore

**Comment by lisakowen** [comment]
i believe gp_vmem_protect_limit is applicable only when Resource Queue-based resource management is active in Greenplum Database.  Other config parameters come into play for segment memory configuration when Resource Group-based resource management is active (see https://gpdb.docs.pivotal.io/530/admin_guide/workload_mgmt_resgroups.html and https://gpdb.docs.pivotal.io/530/ref_guide/config_params/guc_category-list.html#topic444).  

the new section names reflect that the config in those sections is applicable when   Resource Queue-based resource management is active.  we do not currently have any content in best practices related to the (new) resource groups feature.

**Comment by kapustor** [comment]
@lisakowen Do you have any links on gp_vmem_protect_limit is applicable only when Resource Queue-based resource management is active? 
As I know, this parameter is applicable always - even when there are no resource groups and resource queues in DB. AFAIK, it is a low-level stop factor for any query that will hit segments mem limit.

**Comment by kapustor** [comment]
For example, you can find gp_vmem_protect_limit descroption here:
https://discuss.pivotal.io/hc/en-us/articles/201947018-Pivotal-Greenplum-GPDB-Memory-Configuration

**Comment by lisakowen** [comment]
the link you reference is a knowledge base article.  it was probably written without considering resources groups.

here are some doc links that qualify gp_vmem_protect limit as resource queue-specific:
- the GUC description identifies this parameter as valid when resource queues are used: https://gpdb.docs.pivotal.io/530/ref_guide/config_params/guc-list.html#gp_vmem_protect_limit
- this is a memory overview page:  https://gpdb.docs.pivotal.io/530/admin_guide/wlmgmt_intro.html

resource group-based resource management is a new feature, just recently moved from experimental status.  the docs do not in every case have parallel content for resource groups.  also, the docs do not address the scenario where no resource management scheme is active.

maybe the engineering team can provide more context - @gaos1 .

**Comment by dyozie** [comment]
Right - Resource Groups were only experimental until the 5.2.0 release, so
it's not surprising that older documentation assumes resource queues are
being used.

http://gpdb.docs.pivotal.io/530/ref_guide/config_params/guc_category-list.html#topic444
calls out the gucs that are used when resource groups are active.

-David

**Comment by kapustor** [comment]
Wow. Can't belive gp_vmem_protect_limit isnt a global parameter and doesn't work for RG.

So, as I understand, now if using RG you dont need to think about memory limit when installing GP as gp_resource_group_memory_limit is a percentage value, not absolute. Am I right?

Anyway, sorry, thats my bad. Ill close the issue after response.

**Comment by lisakowen** [comment]
@kapustor not sure if you noticed this section - https://gpdb.docs.pivotal.io/530/admin_guide/workload_mgmt_resgroups.html#topic8339717 - it describes how memory is managed at the node/segment/resourcegroup/transaction levels when resource groups are active.
