### ISSUE TITLE
gpdb master restart is getting very slow and has error

### ISSUE THREAD

**Issue by hsyuan** [greenplum-db/gpdb#4351]
latest master branch on macOS Sierra. Probably after WALReplicate merge.

Error message:
`
20180117:18:54:54:039446 gpstop:hyuan-mac:hyuan-[WARNING]:-Error occured while stopping the standby master: ExecutionError: 'non-zero rc: 1' occured.  Details: 'ssh -o 'StrictHostKeyChecking no' hyuan-mac ". /usr/local/gpdb/greenplum_path.sh; $GPHOME/bin/pg_ctl -D /Users/hyuan/gpdb/gpAux/gpdemo/datadirs/standby -m fast -w -t 120 stop"'  cmd had rc=1 completed=True halted=False
  stdout=''
  stderr='pg_ctl: PID file "/Users/hyuan/gpdb/gpAux/gpdemo/datadirs/standby/postmaster.pid" does not exist
Is server running?
`

`
20180117:18:56:28:039446 gpstop:hyuan-mac:hyuan-[CRITICAL]:-Error occurred: non-zero rc: 1
 Command was: '$GPHOME/bin/gpstart -a -d /Users/hyuan/gpdb/gpAux/gpdemo/datadirs/qddir/demoDataDir-1'
rc=1, stdout='20180117:18:54:58:039582 gpstart:hyuan-mac:hyuan-[INFO]:-Starting gpstart with args: -a -d /Users/hyuan/gpdb/gpAux/gpdemo/datadirs/qddir/demoDataDir-1
`

**Comment by ashwinstar** [comment]
Can you check and provide logs in `/Users/hyuan/gpdb/gpAux/gpdemo/datadirs/standby` why it failed to start ? That should provide clue, seems standby is not starting for master and hence gpstart is reporting failure but taking time to report that failure.

**Comment by hsyuan** [comment]
```
2018-01-18 00:55:07.639505 GMT,,,p39822,th-1814064192,,,,0,,,seg-1,,,,,"LOG","00000","removing all temporary files",,,,,,,,"RemovePgTempFiles","fd.c",2127,
2018-01-18 00:55:07.641746 GMT,,,p39822,th-1814064192,,,,0,,,seg-1,,,,,"FATAL","XX000","could not create shared memory segment: Cannot allocate memory (pg_shmem.c:183)","Failed system call was shmget(key=16432001, size=223070024, 03600).","This error usually means that PostgreSQL's request for a shared memory segment exceeded available memory or swap space. To reduce the request size (currently 223070024 bytes), reduce PostgreSQL's shared_buffers parameter (currently 4000) and/or its max_connections parameter (currently 253).
The PostgreSQL documentation contains more information about shared memory configuration.
Process 39822 will wait for gp_debug_linger=120 seconds before termination.
Note that its locks and other resources will not be released until then.",,,,,,"InternalIpcMemoryCreate","pg_shmem.c",183,1    0x1076af030 postgres errstart + 0x5c0
2    0x107493c13 postgres InternalIpcMemoryCreate + 0x153
3    0x1074938ba postgres PGSharedMemoryCreate + 0x8a
4    0x107504842 postgres CreateSharedMemoryAndSemaphores + 0x582
5    0x1074a9475 postgres reset_shared + 0xc5
6    0x1074a8779 postgres PostmasterMain + 0x1019
7    0x107384f04 postgres main + 0x314
8    0x7fff8aee6235 libdyld.dylib start + 0x1
9    0xd 0x0000000d (in postgres)

2018-01-18 01:14:49.237850 GMT,,,p41624,th-1814064192,,,,0,,,seg-1,,,,,"LOG","00000","removing all temporary files",,,,,,,,"RemovePgTempFiles","fd.c",2127,
2018-01-18 01:14:49.240199 GMT,,,p41624,th-1814064192,,,,0,,,seg-1,,,,,"FATAL","XX000","could not create shared memory segment: Cannot allocate memory (pg_shmem.c:183)","Failed system call was shmget(key=16432001, size=223070024, 03600).","This error usually means that PostgreSQL's request for a shared memory segment exceeded available memory or swap space. To reduce the request size (currently 223070024 bytes), reduce PostgreSQL's shared_buffers parameter (currently 4000) and/or its max_connections parameter (currently 253).
The PostgreSQL documentation contains more information about shared memory configuration.
Process 41624 will wait for gp_debug_linger=120 seconds before termination.
Note that its locks and other resources will not be released until then.",,,,,,"InternalIpcMemoryCreate","pg_shmem.c",183,1    0x10130b030 postgres errstart + 0x5c0
2    0x1010efc13 postgres InternalIpcMemoryCreate + 0x153
3    0x1010ef8ba postgres PGSharedMemoryCreate + 0x8a
4    0x101160842 postgres CreateSharedMemoryAndSemaphores + 0x582
5    0x101105475 postgres reset_shared + 0xc5
6    0x101104779 postgres PostmasterMain + 0x1019
7    0x100fe0f04 postgres main + 0x314
8    0x7fff8aee6235 libdyld.dylib start + 0x1
9    0xd 0x0000000d (in postgres)

```

**Comment by hsyuan** [comment]
Not only happens on me, at least 3 of QP members have the same issue.

**Comment by ashwinstar** [comment]
Its failing as not able to allocate shared memory for number of segments tried to be created.

There was commit which bumped the max_connections to 250 for gpdemo
```
commit 6cd8395cdccf51a3619ae7fcdf6ba63d3f051c04
Author: Xin Zhang <xzhang@pivotal.io>
Date:   Thu Jan 11 15:17:23 2018 -0800

    Add DEFAULT_QD_MAX_CONNECTION to 250
```
that seems to be the reason got failures. Either bump the kernel parameters of system to allocate more shared memory OR can bring down `DEFAULT_QD_MAX_CONNECTION` to 25 which was previous value. Some isolation2 tests need it to `> 150` but in general don't need it at 250.

**Comment by hsyuan** [comment]
I don't think we should set the default value to 250 just for test reason. This is going to affect all the developers. Instead, in you isolation 2 test or CI pipeline you can set it to 250 for test reason.

**Comment by asimrp** [comment]
Agree with Haisheng, default 250 for max_connections seems too high.  I use 150.

**Comment by Eulerizeit** [comment]
@xinweb Can this be changed to 150?

**Comment by hsyuan** [comment]
Can we change it back to 25, or remove it from Makefile?

For testing the isolation 2 test suite, we can set the value before running
the test or set it in the CI pipeline.

~ ~ ~
Haisheng Yuan

**Comment by ashwinstar** [comment]
On Thu, Jan 18, 2018 at 10:37 AM, Haisheng Yuan <notifications@github.com>
wrote:

> Can we change it back to 25, or remove it from Makefile?
>
> For testing the isolation 2 test suite, we can set the value before running
> the test or set it in the CI pipeline.
>

CI already sets it. This was more to align with default setting should pass
the ICW tests for anyone deploying.

**Comment by hsyuan** [comment]
If CI sets it to 250, why do we need the default value here?

~ ~ ~
Haisheng Yuan

**Comment by xinzweb** [comment]
would you please try the value 150 and see if that passed?

**Comment by xinzweb** [comment]
I tried to keep a consistent cluster configuration across all ICW tests.

**Comment by xinzweb** [comment]
Added patch https://github.com/greenplum-db/gpdb/commit/659be26d02cf9f15533cf1e49303dea63e2958be to reduce the max connection. Thanks.
