### ISSUE TITLE
onfigure: error: Your ORCA version is expected to be 2.53.XXX

### ISSUE THREAD

**Issue by rroks** [greenplum-db/gpdb#4353]
hi
I got this issue when configuring gpdb(version 5.4)

I used
`./configure --without-readline --prefix=/usr/local/gpdb --with-libraries=/usr/local/lib --with-includes=/usr/local/include`
but failed
then I ran
`grep GPORCA_VERSION_STRING /usr/local/include/gpopt/version.h`
and got
`#define GPORCA_VERSION_STRING "2.53.11"`
by the way, gporca is under
> /usr/local/lib

any ideas about how to solve this?

(At first I thought it was due to the wrong gporca version, but I didn't know how to figure it out. It would be more convenient to see version info in README.)

**Comment by hsyuan** [comment]
follow instruction here:
https://github.com/greenplum-db/gporca/commit/2a5e9fce472d3f1a29c16e1e53974ad5925ee735

or this:
https://github.com/greenplum-db/gpdb/blob/master/README.linux.md

**Comment by rroks** [comment]
Thanks.
It works now.
Just because I forgot to run `ldconfig` after configuring `/etc/ld.so.conf`.
And at first, I didn't know that gporca should be put under /usr/local/lib.

**Comment by hsyuan** [comment]
Cool, I am closing this issue.
