### ISSUE TITLE
Get ImportError: No module named site while deploying to new machine

### ISSUE THREAD

**Issue by recyclerzhu2015** [greenplum-db/gpdb#4382]
### Greenplum version or build
5.4.0 
### OS version and uname -a
CentOS7.4
3.10.0-693.2.2.el7.x86_64 #1 SMP Tue Sep 12 22:26:13 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
### autoconf options used ( config.status --config )
./configure --enable-orca --enable-mapreduce  --enable-gpperfmon --with-perl --with-python --with-libxml --with-gssapi --enable-snmp --prefix=/usr/local/gpdb
### Expected behavior
build success
### Actual behavior
build success
### Step to reproduce the behavior

Question:
While I deploying compiled zip file to a clean machine, I tried to run command gpssh and get error as below:
ImportError: No module named site
I am confusing hot to generate directory under ../gpdb-src/gpAux/ext/.....
And also if I have to copy python home to /usr/local/greenplum-db/ext/python

**Comment by skahler-pivotal** [comment]
Did you source the greenplum_path.sh program in order to add paths to the user before running gpssh on the clean machine?

**Comment by recyclerzhu2015** [comment]
thanks for your response skahler, currently it is possible for me to install gp cluster. but I have to install a lot of dependencies on the master to make sure gp command works. I was interesting in the release steps via gpAux, I tried the makefile under this folder and failed.

**Comment by skahler-pivotal** [comment]
the dependancies should be wrapped up in the final build. personally I'm using make and configure with and using a prefix to push everything to a path outside my build directory ( /usr/local/gpdb in my case ) within that directory all your dependancies as well as a greenplum_path.sh file which will adjust the PYTHONPATH and PATH variables to help satisfy the dependancies

**Comment by yydzero** [comment]
@recyclerzhu2015 is this still an issue?

Hope https://github.com/yydzero/yydzero.github.io/blob/master/_posts/2015-10-29-how-to-build-gpdb.markdown will help u about dependencies.
