### ISSUE TITLE
Performance of Greenplum JDBC Driver vs Postgresql JDBC Driver

### ISSUE THREAD

**Issue by shubifeng** [greenplum-db/gpdb#4395]
The question is: they did a perf test on GreenplumDriver vs postgresql Driver for 150K queries with GPDB 5.3, org.postgresql.Driver is 10% faster than com.pivotal.jdbc.GreenplumDriver. Why does this happen?

![default](https://user-images.githubusercontent.com/6796352/35311226-6f8a2844-00f0-11e8-8a96-c570eaa23bae.png)

![default](https://user-images.githubusercontent.com/6796352/35311277-b233286c-00f0-11e8-86f6-12e8be431bed.png)

**Comment by hsyuan** [comment]
Oh, I didn't know we even have our own JDBC driver. @yydzero Do you know which team to ask?

**Comment by Eulerizeit** [comment]
@hsyuan the Greenplum drivers we distribute are from Data Direct.

**Comment by hsyuan** [comment]
The question is: they did a perf test on GreenplumDriver vs postgresql Driver for 150K queries with GPDB 5.3,  org.postgresql.Driver is 10% faster than com.pivotal.jdbc.GreenplumDriver. Why does this happen?

**Comment by d** [comment]
Hi @shubifeng, thank you for your interest in Greenplum Database! We'd like to help you, but before that, can you share more information about

1. What performance difference you are seeing?
1. How can any other member of the Greenplum community replicate your results?


Jesse

**Comment by yydzero** [comment]
@shubifeng as Jesse said, it would be helpful if you could describe more about your tests.

@hsyuan Greenplum uses DataDirector JDBC driver, while there is another driver based on PostgreSQL's JDBC driver.

**Comment by shubifeng** [comment]
The question is: they did a perf test on GreenplumDriver vs postgresql Driver for 150K queries with GPDB 5.3, org.postgresql.Driver is 10% faster than com.pivotal.jdbc.GreenplumDriver. Why does this happen?

![default](https://user-images.githubusercontent.com/6796352/35311226-6f8a2844-00f0-11e8-8a96-c570eaa23bae.png)

![default](https://user-images.githubusercontent.com/6796352/35311277-b233286c-00f0-11e8-86f6-12e8be431bed.png)

**Comment by shubifeng** [comment]
what's the question ?

**Comment by shubifeng** [comment]
@hsyuan @yydzero The greenplumDriver vs postgresql Driver，Which one should I choose?

**Comment by yydzero** [comment]
Try with greenplum driver, 10% difference does not make a big difference.

**Comment by hsyuan** [comment]
Closing this issue, which I think has been resolved.
