### ISSUE TITLE
custom de-duplicate function cannot work in 5.x

### ISSUE THREAD

**Issue by gaos1** [greenplum-db/gpdb#4398]
### Greenplum version or build
5.X including The latest master. 

### Expected behavior
Select merge_table() is expected to succeed with a notice: "unique_violation".  It can run success with the notice in 4.3.x and PosgreSQL. 
### Actual behavior
The SQL is failed with the following error message:
```
postgres=# select merge_table();
ERROR:  duplicate key value violates unique constraint "test1_pkey"  (seg0 172.17.0.2:35432 pid=353)
DETAIL:  Key (id)=(1) already exists.
CONTEXT:  SQL statement "insert into test1 select * from test2"
PL/pgSQL function "merge_table" line 5 at EXECUTE statement
```
### Step to reproduce the behavior
```
drop table if exists test1;
drop table if exists test2;
create table test1(id int primary key);
create table test2(id int primary key);
insert into test1 values(1);
insert into test2 values(1);
CREATE OR REPLACE FUNCTION merge_table() RETURNS void AS
$BOY$
DECLARE
   v_insert_sql varchar;
BEGIN
     v_insert_sql :='insert into test1 select * from test2';
     EXECUTE v_insert_sql;
     EXCEPTION WHEN unique_violation THEN
     raise notice 'unique_violation';
END;
$BOY$
LANGUAGE plpgsql volatile;
select merge_table();
```

**Comment by Eulerizeit** [comment]
@danielgustafsson @hlinnaka could you look at this please.

**Comment by danielgustafsson** [comment]
This is due to the dispatcher dropping the actual errcode and replaces it with a data exception, thus the exception fires but never traps. A stab at fixing this is in #4401.

**Comment by d** [comment]
#4401 has been merged to master (in a different commit), closing this issue.
