### ISSUE TITLE
gpssh unable to login

### ISSUE THREAD

**Issue by rroks** [greenplum-db/gpdb#4412]
I used `$ gpssh-exkeys -h slavegu1` as a root user
and then `gpssh -h slavegu1 -v`, tried to connect to 'slavegu1'
but got

> [WARN] Reference default values as $MASTER_DATA_DIRECTORY/gpssh.conf could not be found
Using delaybeforesend 0.05 and prompt_validation_timeout 1.0
Note: command history unsupported on this machine ...
[Reset ...]
[ERROR] unable to login to slavegu1
hint: use gpssh-exkeys to setup public-key authentication between hosts

I also tried to connect to 'slavegu1' via `ssh slavegu1` and it works.

What cloud the cause be?

25 Jan-
I also tried to clean up `.ssh/authorized_keys` file, check ssh configuration and config `$MASTER_DATA_DIRECTORY/gpssh.conf`, but `gpssh` still doesn't work.

**Comment by lij55** [comment]
Hi @rroks ，

Do you mean you run 'gpss ...' command as root?

**Comment by rroks** [comment]
ye, I run these commands as root
I have no idea what happened
 I just reinstalled the system and tried to config the system and install gp again, then it works
The pivotal gp documentation has some wrong configurations, I met some errors during installing gpdb.

**Comment by hsyuan** [comment]
Closing this issue, since it has been resolved.
