### ISSUE TITLE
请问jdbc连接gpdb时怎么配置主备ip

### ISSUE THREAD

**Issue by shubifeng** [greenplum-db/gpdb#4429]

**Comment by lij55** [comment]
Hi @shubifeng ,
could you please explain what does '主备ip' means?
##
可以解释下，‘主备ip’具体是指什么吗？

**Comment by lij55** [comment]
Hi @shubifeng ,
could you please explain what does '主备ip' means?
##
可以解释下，‘主备ip’具体是指什么吗？

**Comment by shubifeng** [comment]
主备IP is means  master and standby‘s ip.  when master network is unreachable，then the jdbc client is normally。 
**jdbc:pivotal:greenplum://192.168.1.211:2345;DatabaseName=bizdata** the driver url can both use master and standby ip?

**Comment by lij55** [comment]
Currently the JDBC driver doesn't support this feature.

Only ip address of master is allowed in the JDBC URL. If original master is down, you need to promote standby master to new master manually first and set its IP address to a new JDBC url.
