### ISSUE TITLE
Unstable test dispatch.sql in 5X_STABLE

### ISSUE THREAD

**Issue by magi345** [greenplum-db/gpdb#4434]
In 5X_STABLE regression test, the dispatch.sql is not always work as expected.
After a fresh `gpinitsystem` or `make cluster`, before manually restart the gpdb, this test can pass. But once the gpdb is restarted, this test always hang.

In master branch, this problem no more exists after https://github.com/greenplum-db/gpdb/pull/4349. I tried backport https://github.com/greenplum-db/gpdb/commit/108399220c2eeeac720aa0dc19473b98b1715de6 and https://github.com/greenplum-db/gpdb/commit/85e484bd335a2c78d7871a88203ca88885ae9630 but the problem still exists.

```
#0  0x00007f83998c2bd3 in select () from /lib64/libc.so.6
#1  0x0000000000b0b4fd in FtsNotifyProber () at cdbfts.c:146
#2  0x0000000000b0b75e in FtsTestConnection (failedDBInfo=0x2001ff8, fullScan=1 '\001') at cdbfts.c:197
#3  0x0000000000b0b96e in FtsTestSegmentDBIsDown (segdbDesc=0x2001ec0, size=3) at cdbfts.c:255
#4  0x0000000000ad6895 in createGang_async (type=GANGTYPE_PRIMARY_WRITER, gang_id=1, size=3, content=-1) at cdbgang_async.c:288
#5  0x0000000000ad17f4 in createGang (type=GANGTYPE_PRIMARY_WRITER, gang_id=1, size=3, content=-1) at cdbgang.c:292
#6  0x0000000000ad171f in AllocateWriterGang () at cdbgang.c:263
#7  0x000000000070c11c in AssignGangs (queryDesc=0x1ff5620) at execUtils.c:1647
#8  0x00000000006eac8b in ExecutorStart (queryDesc=0x1ff5620, eflags=0) at execMain.c:576
#9  0x00000000008f24cf in PortalStart (portal=0x1fe1280, params=0x0, snapshot=0x0, seqServerHost=0x0, seqServerPort=-1, ddesc=0x0) at pquery.c:727
#10 0x00000000008eae79 in exec_simple_query (query_string=0x1fcb290 "SELECT 1 FROM gp_dist_random('gp_id');", seqServerHost=0x0, seqServerPort=-1) at postgres.c:1774
#11 0x00000000008efbd6 in PostgresMain (argc=1, argv=0x1ecce98, dbname=0x1ecca20 "regression", username=0x1ecc9e0 "gpadmin") at postgres.c:5012
#12 0x0000000000881a25 in BackendRun (port=0x1ed0dd0) at postmaster.c:6711
#13 0x00000000008810f4 in BackendStartup (port=0x1ed0dd0) at postmaster.c:6397
#14 0x000000000087a04c in ServerLoop () at postmaster.c:2447
#15 0x00000000008787b8 in PostmasterMain (argc=15, argv=0x1ea0d90) at postmaster.c:1532
#16 0x000000000079213c in main (argc=15, argv=0x1ea0d90) at main.c:206
```

### Greenplum version or build
Found: 5X_STABLE (5.4)
No problem: master

### OS version and uname -a
CentOS Linux release 7.1.1503 (Core)
Linux wh_dev 3.10.0-229.el7.x86_64 #1 SMP Fri Mar 6 11:36:42 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

### autoconf options used ( config.status --config )
--prefix=/home/gpadmin/usr/local/greenplum-db-5.0.0' '--with-pgport=15432' '--with-libedit-preferred' '--with-perl' '--with-python' '--with-openssl' '--with-pam' '--with-ldap' '--with-libxml' '--enable-cassert' '--enable-debug' '--enable-testutils' '--enable-debugbreak' '--enable-depend' '--disable-mapreduce' '--disable-gpfdist' '--disable-orca' '--enable-thread-safety-force' 'CFLAGS=-O0' 'CXXFLAGS=-O0

### Installation information ( pg_config )
BINDIR = /home/gpadmin/usr/local/greenplum-db-5.0.0/bin
DOCDIR = /home/gpadmin/usr/local/greenplum-db-5.0.0/doc/postgresql
HTMLDIR = /home/gpadmin/usr/local/greenplum-db-5.0.0/doc/postgresql
INCLUDEDIR = /home/gpadmin/usr/local/greenplum-db-5.0.0/include
PKGINCLUDEDIR = /home/gpadmin/usr/local/greenplum-db-5.0.0/include/postgresql
INCLUDEDIR-SERVER = /home/gpadmin/usr/local/greenplum-db-5.0.0/include/postgresql/server
LIBDIR = /home/gpadmin/usr/local/greenplum-db-5.0.0/lib
PKGLIBDIR = /home/gpadmin/usr/local/greenplum-db-5.0.0/lib/postgresql
LOCALEDIR = /home/gpadmin/usr/local/greenplum-db-5.0.0/share/locale
MANDIR = /home/gpadmin/usr/local/greenplum-db-5.0.0/share/man
SHAREDIR = /home/gpadmin/usr/local/greenplum-db-5.0.0/share/postgresql
SYSCONFDIR = /home/gpadmin/usr/local/greenplum-db-5.0.0/etc/postgresql
PGXS = /home/gpadmin/usr/local/greenplum-db-5.0.0/lib/postgresql/pgxs/src/makefiles/pgxs.mk
CC = gcc
CPPFLAGS = -D_GNU_SOURCE -I/home/gpadmin/usr/local/greenplum-db-5.0.0/include
CFLAGS = -O0 -std=gnu99 -Wall -Wmissing-prototypes -Wpointer-arith -Wendif-labels -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fno-aggressive-loop-optimizations -Wno-unused-but-set-variable -Wno-address -g -ggdb -I/home/gpadmin/usr/local/greenplum-db-5.0.0/include
CFLAGS_SL = -fpic
LDFLAGS = -Wl,--as-needed -Wl,-rpath,'/home/gpadmin/usr/local/greenplum-db-5.0.0/lib',--enable-new-dtags -L/home/gpadmin/usr/local/greenplum-db-5.0.0/lib
LDFLAGS_SL =
LIBS = -lpgport -lxml2 -lpam -lrt -lcrypt -ldl -lm -L/home/gpadmin/usr/local/greenplum-db-5.0.0/lib
VERSION = PostgreSQL 8.3.23

**Comment by magi345** [comment]
@pengzhout We workaround this in https://github.com/greenplum-db/gpdb/pull/4443. However the problem of dispatch test still exists.

**Comment by yydzero** [comment]
@magi345 is this still a problem?
