### ISSUE TITLE
psql input.c should test return value instead of errno for write_history

### ISSUE THREAD

**Issue by vitesse-ftian** [greenplum-db/gpdb#4437]
### Greenplum version or build
master

### Step to reproduce the behavior

In input.c, around line 400, we should test return value instead of peeking at errno.   
This can cause some frivolous error messages printed when psql exits.

**Comment by ashwinstar** [comment]
PR ?

**Comment by vitesse-ftian** [comment]
This also happens in 5X_STABLE as of today.

ftian@ftian-XPS-15-9560:~$ psql
psql (8.3.23)
Type "help" for help.

ftian=# \q
could not save history to file "/home/ftian/.psql_history": No such file or directory


The fix is easy, input.c line 400.

-			errno = 0;
-			(void) write_history(fname);
-			if (errno == 0)
+
+			if (write_history(fname) == 0) {
 				return true;
+			}
