### ISSUE TITLE
gpfdist should require libyaml

### ISSUE THREAD

**Issue by adam8157** [greenplum-db/gpdb#4441]
https://github.com/greenplum-db/gpdb/blob/master/src/bin/gpfdist/Makefile#L23

```
ifeq ($(have_yaml),yes)
  GPFDIST_LIBS += -lyaml
  OBJS += transform.o
  ifneq ($(PORTNAME),win32)
    override CPPFLAGS := -DGPFXDIST $(CPPFLAGS)
  endif
endif
```

For now it's only an option while `configure`, I built it without libyaml several times, the behavior turned out quite different.

**Comment by adam8157** [comment]
@pf-qiu @lij55 what do you think?

**Comment by pf-qiu** [comment]
gpfdist don't need libyaml if transform is not enabled. Other behavior should be same.
What differences have you observed?

**Comment by adam8157** [comment]
Max line limit is 32KB without `-DGPFXDIST`, 256MB with it.
