### ISSUE TITLE
cannot access pg_controldata for dbid 

### ISSUE THREAD

**Issue by Chiuchip** [greenplum-db/gpdb#4456]

**Comment by Chiuchip** [comment]
> Greenplum-db-5.0.0
when i try to init the database, i encounter a script like that:
20180131:00:55:26:075210 gpstop:mdw:gpadmin-[INFO]:-Master host=localhost.localdomain
20180131:00:55:26:075210 gpstop:mdw:gpadmin-[INFO]:-Commencing Master instance shutdown with mode=immediate
20180131:00:55:26:075210 gpstop:mdw:gpadmin-[INFO]:-Master segment instance directory=/gpmaster/gpseg-1
20180131:00:55:27:075210 gpstop:mdw:gpadmin-[INFO]:-Attempting forceful termination of any leftover master process
20180131:00:55:27:075210 gpstop:mdw:gpadmin-[INFO]:-Terminating processes for segment /gpmaster/gpseg-1
20180131:00:55:27:075299 gpstart:mdw:gpadmin-[INFO]:-Starting gpstart with args: -a -l /home/gpadmin/gpAdminLogs -d /gpmaster/gpseg-1
20180131:00:55:27:075299 gpstart:mdw:gpadmin-[INFO]:-Gathering information and validating the environment...
20180131:00:55:27:075299 gpstart:mdw:gpadmin-[INFO]:-Greenplum Binary Version: 'postgres (Greenplum Database) 5.0.0 build commit:458a89ba2d99f62ac212f2c87d24addcc5f58b9f'
20180131:00:55:27:075299 gpstart:mdw:gpadmin-[INFO]:-Greenplum Catalog Version: '301705051'
20180131:00:55:27:075299 gpstart:mdw:gpadmin-[INFO]:-Starting Master instance in admin mode
20180131:00:55:28:075299 gpstart:mdw:gpadmin-[INFO]:-Obtaining Greenplum Master catalog information
20180131:00:55:28:075299 gpstart:mdw:gpadmin-[INFO]:-Obtaining Segment details from master...
20180131:00:55:28:075299 gpstart:mdw:gpadmin-[INFO]:-Setting new master era
20180131:00:55:28:075299 gpstart:mdw:gpadmin-[INFO]:-Master Started...
20180131:00:55:28:075299 gpstart:mdw:gpadmin-[WARNING]:-cannot access pg_controldata for dbid 2 on host localhost.localdomain
20180131:00:55:28:075299 gpstart:mdw:gpadmin-[CRITICAL]:-No segments responded to ssh query for heap checksum. Not starting the array.
20180131:00:55:28:067328 gpinitsystem:mdw:gpadmin-[WARN]:
20180131:00:55:28:067328 gpinitsystem:mdw:gpadmin-[WARN]:-Failed to start Greenplum instance; review gpstart output to
20180131:00:55:28:067328 gpinitsystem:mdw:gpadmin-[WARN]:- determine why gpstart failed and reinitialize cluster after resolving
20180131:00:55:28:067328 gpinitsystem:mdw:gpadmin-[WARN]:- issues.  Not all initialization tasks have completed so the cluster
20180131:00:55:28:067328 gpinitsystem:mdw:gpadmin-[WARN]:- should not be used.
20180131:00:55:29:067328 gpinitsystem:mdw:gpadmin-[WARN]:-gpinitsystem will now try to stop the cluster
20180131:00:55:29:067328 gpinitsystem:mdw:gpadmin-[WARN]:
20180131:00:55:29:075521 gpstop:mdw:gpadmin-[INFO]:-Starting gpstop with args: -a -l /home/gpadmin/gpAdminLogs -i -d /gpmaster/gpseg-1
20180131:00:55:29:075521 gpstop:mdw:gpadmin-[INFO]:-Gathering information and validating the environment...
20180131:00:55:29:075521 gpstop:mdw:gpadmin-[INFO]:-Obtaining Greenplum Master catalog information
20180131:00:55:29:075521 gpstop:mdw:gpadmin-[INFO]:-Obtaining Segment details from master...
20180131:00:55:29:075521 gpstop:mdw:gpadmin-[INFO]:-Greenplum Version: 'postgres (Greenplum Database) 5.0.0 build commit:458a89ba2d99f62ac212f2c87d24addcc5f58b9f'
20180131:00:55:29:075521 gpstop:mdw:gpadmin-[INFO]:-There are 0 connections to the database
20180131:00:55:29:075521 gpstop:mdw:gpadmin-[INFO]:-Commencing Master instance shutdown with mode='immediate'
20180131:00:55:29:075521 gpstop:mdw:gpadmin-[INFO]:-Master host=localhost.localdomain
20180131:00:55:29:075521 gpstop:mdw:gpadmin-[INFO]:-Commencing Master instance shutdown with mode=immediate
20180131:00:55:29:075521 gpstop:mdw:gpadmin-[INFO]:-Master segment instance directory=/gpmaster/gpseg-1
20180131:00:55:30:075521 gpstop:mdw:gpadmin-[INFO]:-Attempting forceful termination of any leftover master process
20180131:00:55:30:075521 gpstop:mdw:gpadmin-[INFO]:-Terminating processes for segment /gpmaster/gpseg-1
20180131:00:55:30:075521 gpstop:mdw:gpadmin-[INFO]:-No standby master host configured
20180131:00:55:30:075521 gpstop:mdw:gpadmin-[INFO]:-Commencing parallel segment instance shutdown, please wait...
20180131:00:55:30:075521 gpstop:mdw:gpadmin-[INFO]:-0.00% of jobs completed
20180131:00:55:40:075521 gpstop:mdw:gpadmin-[INFO]:-100.00% of jobs completed
20180131:00:55:40:075521 gpstop:mdw:gpadmin-[INFO]:-----------------------------------------------------
20180131:00:55:40:075521 gpstop:mdw:gpadmin-[INFO]:-   Segments stopped successfully      = 1
20180131:00:55:40:075521 gpstop:mdw:gpadmin-[INFO]:-   Segments with errors during stop   = 0
20180131:00:55:40:075521 gpstop:mdw:gpadmin-[INFO]:-----------------------------------------------------
20180131:00:55:40:075521 gpstop:mdw:gpadmin-[INFO]:-Successfully shutdown 1 of 1 segment instances 
20180131:00:55:40:075521 gpstop:mdw:gpadmin-[INFO]:-Database successfully shutdown with no errors reported
20180131:00:55:40:075521 gpstop:mdw:gpadmin-[INFO]:-Cleaning up leftover gpmmon process
20180131:00:55:40:075521 gpstop:mdw:gpadmin-[INFO]:-No leftover gpmmon process found
20180131:00:55:40:075521 gpstop:mdw:gpadmin-[INFO]:-Cleaning up leftover gpsmon processes
20180131:00:55:40:075521 gpstop:mdw:gpadmin-[INFO]:-No leftover gpsmon processes on some hosts. not attempting forceful termination on these hosts
20180131:00:55:40:075521 gpstop:mdw:gpadmin-[INFO]:-Cleaning up leftover shared memory
20180131:00:55:40:067328 gpinitsystem:mdw:gpadmin-[INFO]:-Successfully shutdown the Greenplum instance
20180131:00:55:40:067328 gpinitsystem:mdw:gpadmin-[WARN]:
20180131:00:55:41:067328 gpinitsystem:mdw:gpadmin-[WARN]:-Failed to start Greenplum instance; review gpstart output to
20180131:00:55:41:067328 gpinitsystem:mdw:gpadmin-[WARN]:- determine why gpstart failed and reinitialize cluster after resolving
20180131:00:55:41:067328 gpinitsystem:mdw:gpadmin-[WARN]:- issues.  Not all initialization tasks have completed so the cluster
20180131:00:55:41:067328 gpinitsystem:mdw:gpadmin-[WARN]:- should not be used.
20180131:00:55:41:067328 gpinitsystem:mdw:gpadmin-[WARN]:
20180131:00:55:41:gpinitsystem:mdw:gpadmin-[FATAL]: starting new instance failed; Script Exiting!

**Comment by danielgustafsson** [comment]
> On 31 Jan 2018, at 10:04, Chiuchip <notifications@github.com> wrote:

> 20180131:00:55:28:075299 gpstart:mdw:gpadmin-[INFO]:-Master Started...
> 20180131:00:55:28:075299 gpstart:mdw:gpadmin-[WARNING]:-cannot access pg_controldata for dbid 2 on host localhost.localdomain
> 20180131:00:55:28:075299 gpstart:mdw:gpadmin-[CRITICAL]:-No segments responded to ssh query for heap checksum. Not starting the array.

This seems like an ssh issue, have you followed the instructions for setting up ssh access in https://github.com/greenplum-db/gpdb/blob/master/README.linux.md ?
