### ISSUE TITLE
GP start createdb: could not connect to database postgres: FATAL:  DTM initialization: failure during startup recovery, retry failed, check segment status (cdbtm.c:1513)

### ISSUE THREAD

**Issue by xiem22153** [greenplum-db/gpdb#4457]
createdb: could not connect to database postgres: FATAL:  DTM initialization: failure during startup recovery, retry failed, check segment status (cdbtm.c:1513)

**Comment by asimrp** [comment]
Can you please post relevant master and segment logs?
