### ISSUE TITLE
Bug in _outScanInfo

### ISSUE THREAD

**Issue by fengttt** [greenplum-db/gpdb#446]
if (rte->type != RTE_SUBQUERY)

It seems shout be ret->rtekind, or the code is really twisted.

**Comment by armenatzoglou** [comment]
Thanks for raising this issue. This code was modified in f3983337f2eca4465d2b7c3b0354bda1bf92a4f3   and eventually was removed as dead code in 87b97b94e47c099634906035d910f8a510cfb312.
