### ISSUE TITLE
"cache lookup failed for attribute XX" error while inserting a row in inherited tables

### ISSUE THREAD

**Issue by dhanashreek89** [greenplum-db/gpdb#4462]
### Greenplum version or build
 PostgreSQL 8.4.0 (Greenplum Database 6.0.0-alpha.0+dev.3077.g9d9c555 build dev-oss) on x86_64-apple-darwin16.4.0, compiled by GCC Apple LLVM version 8.0.0 (clang-800.0.42.1), 64-bit compiled on Jan 26 2018 13:55:10 (with assert checking)

### Step to reproduce the behavior
```
CREATE SCHEMA qp_misc_jiras;

CREATE TABLE qp_misc_jiras.tablea (
ssn integer,
lastname character varying,
junk integer
) DISTRIBUTED BY (ssn);

CREATE TABLE qp_misc_jiras.tableb (
id integer,
lastname character varying,
morejunk integer
) DISTRIBUTED BY (id);

CREATE TABLE qp_misc_jiras.tablec (
ssn integer,
lastname character varying,
junk integer,
id integer,
morejunk integer,
uid1 integer,
uid2 integer,
uid3 integer
) INHERITS (qp_misc_jiras.tablea, qp_misc_jiras.tableb) DISTRIBUTED BY (uid1, uid2, uid3);

-- This query fails
INSERT INTO qp_misc_jiras.tablea VALUES (1, 'smith', 42);
ERROR:  cache lookup failed for attribute 11 of relation 16398 (lsyscache.c:943)
CONTEXT:  SQL statement "select Ta.ssn , (case when pg_column_size(Ta.lastname) > 1024 then NULL else Ta.lastname  end) as lastname, (case when Ta.lastname is NULL then false else true end), Ta.junk  from qp_misc_jiras.tablea as Ta  limit 30000 "
```

- The issue does not occurs if the inherited attributes aren't re-stated (i.e. just `CREATE TABLE tablec (uid1 integer, uid2 integer, uid3 integer) INHERITS...`), works fine.
- Also the lookup failure happens during `analyze`. If autostats are turned off then the INSERT passes.

```
pivotal=# set gp_autostats_mode=none;
SET
pivotal=# INSERT INTO qp_misc_jiras.tablea VALUES (1, 'smith', 42);
INSERT 0 1
```

**Comment by yydzero** [comment]
Still exist on latest master

**Comment by ashwinstar** [comment]
Checked still continues to fail on latest master.

**Comment by hlinnaka** [comment]
Fixed in master. But still present in 5X_STABLE.

**Comment by lij55** [comment]
closing old gp5 only issue as it is fixed in later version.
