### ISSUE TITLE
Many warnings in pg_backup_files.c, pg_backup_tar.c

### ISSUE THREAD

**Issue by fengttt** [greenplum-db/gpdb#447]
And they look like real bug to me.

For example, the following code,
gzFile *FH = gzopen(...)

gzopen returns gzFile, not gzFile*.

**Comment by hlinnaka** [comment]
Yeah, this is inherited from the upstream. It was fixed in upstream commits d923125b77 and 19f45565f5, in PostgreSQL 9.2. We'll get it when we merge with 9.2.

I must admit those warnings are pretty annoying, so I'm quite tempted to cherry-pick those.

**Comment by hlinnaka** [comment]
Ok, opened PR #2672 to backport those fixes.

**Comment by hlinnaka** [comment]
Pushed PR #2672. There are a few other warnings left, but I think we can consider this done for now.
