### ISSUE TITLE
add segment error,why

### ISSUE THREAD

**Issue by xiem22153** [greenplum-db/gpdb#4481]
[ERROR]:-ExecutionError: 'Error Executing Command: ' occured.  Details: '/usr/local/greenplum-db/./bin/lib/gpconfigurenewsegment -c /data/primary/gpseg2:40000:true:false:4 -n -t ./gpexpand_schema.tar -B 2'  cmd had rc=1 completed=True halted=False
stdout=''
stderr='ExecutionError: 'non-zero rc: 2' occured.  Details: '/bin/tar -C /data/primary/gpseg2 -xf ./gpexpand_schema.tar'  cmd had rc=2 completed=True halted=False
stdout=''
stderr='/bin/tar: ./gpexpand_schema.tar: Cannot open: No such file or directory
/bin/tar: Error is not recoverable: exiting now
''
'
stderr='ExecutionError: 'Error Executing Command: ' occured.  Details: '/usr/local/greenplum-db/./bin/lib/gpconfigurenewsegment -c /data/primary/gpseg2:40000:true:false:4 -n -t ./gpexpand_schema.tar -B 2'  cmd had rc=1 completed=True halted=False
stdout=''
stderr='ExecutionError: 'non-zero rc: 2' occured.  Details: '/bin/tar -C /data/primary/gpseg2 -xf ./gpexpand_schema.tar'  cmd had rc=2 completed=True halted=False
stdout=''
stderr='/bin/tar: ./gpexpand_schema.tar: Cannot open: No such file or directory
/bin/tar: Error is not recoverable: exiting now

**Comment by skahler-pivotal** [comment]
It looks like it can't find the tar file, I'm guessing there is an error earlier on generating it. Which version are you running?

**Comment by skahler-pivotal** [comment]
duplicate #4473

**Comment by xiem22153** [comment]
@skahler-pivotal  thank you ,I wrote the host name wrong.
