### ISSUE TITLE
the port of ssh is not 22，how execute gpssh-exkeys ？

### ISSUE THREAD

**Issue by shubifeng** [greenplum-db/gpdb#4483]
the port of ssh is not 22，how execute gpssh-exkeys ？

**Comment by pivotal-ning-yu** [comment]
Maybe use ssh-copy-id instead?

**Comment by paul-guo-** [comment]
Maybe set port mapping using iptables?

**Comment by hsyuan** [comment]
by default those utilities only use the standard ssh port and we haven't added an option to use a non-standard port in all of the utilities.

Check duplicate issue:
https://github.com/greenplum-db/gpdb/issues/4009

**Comment by skahler-pivotal** [comment]
You would probably want to control the ssh client by setting ~/.ssh/config or you can set it up system wide with /etc/ssh/ssh_config at that point everything that is going to call ssh under the covers should use the defaults set there
