### ISSUE TITLE
recursive query syntax of greenplum

### ISSUE THREAD

**Issue by shubifeng** [greenplum-db/gpdb#4487]
怎么实现递归查询？

**Comment by d** [comment]
Hi, thank you for your interest using SQL with Greenplum Database.
Have you considered [searching for how to write a SQL query recursively](http://lmgtfy.com/?q=Postgres+8.4+recursive+common+table+expression)?

**Comment by shubifeng** [comment]
@d PostgreSQL 8.3.23 (Greenplum Database 5.3.0 build commit:2155c5a8cf8bb7f13f49c6e248fd967a74fed591) on x86_64-pc-linux-gnu, compiled by GCC gcc (GCC) 6.2.0, 64-bit compiled on Dec  5 2017 19:10:20    is not support 8.4 “WITH RECURSIVE” feature.

**Comment by shubifeng** [comment]
When will update to  version9.3 for PostgreSQL base of Greenplum ?

**Comment by hsyuan** [comment]
set gp_recursive_cte_prototype = on;

Recursive CTE is not GA yet.

**Comment by shubifeng** [comment]
@hsyuan 你好，请问在哪个文件中设置  ‘gp_recursive_cte_prototype = on;’
