### ISSUE TITLE
delete master segment,cannot gpstart

### ISSUE THREAD

**Issue by xiem22153** [greenplum-db/gpdb#4490]
![default](https://user-images.githubusercontent.com/35788605/35851991-9be990c2-0b64-11e8-856c-a1f08eb8a7e3.png)

**Comment by xiem22153** [comment]
Frequently encountered this problem, have something to start successfully.

**Comment by yydzero** [comment]
What is the greenplum version?

Could you please also try with gpstart -v and 
1) copy command line output here;
2) copy log file here, log file is under ~/gpAdminLogs/ by default.

**Comment by ashwinstar** [comment]
Sorry, but the issue doesn't have clear description of the problem faced. To help understand and resolve the issue will need more clear description of the problem being faced and above questions answered. Closing the issue, feel free to reopen is still an issue.
