### ISSUE TITLE
segment WAL replication can not complete syncing

### ISSUE THREAD

**Issue by deem0n** [greenplum-db/gpdb#4493]
### Red Hat Enterprise Linux Server release 7.4 (Maipo)
Linux mdw 3.10.0-693.el7.x86_64 #1 SMP Thu Jul 6 19:56:57 EDT 2017 x86_64 x86_64 x86_64 GNU/Linux

### autoconf options used ( config.status --config )
'--with-libraries=/tmp/gpdb-5.3.0/depends/build/lib' '--with-includes=/tmp/gpdb-5.3.0/depends/build/include' '--with-perl' '--with-python' '--with-libxml' '--with-libxslt' '--with-gssapi' '--with-openssl' '--enable-orca' '--enable-gpperfmon' '--enable-segwalrep' '--prefix=/usr/local/gpdb-5.3.0'

### Installation information ( pg_config )
```
BINDIR = /usr/local/gpdb-5.3.0/bin
DOCDIR = /usr/local/gpdb-5.3.0/doc/postgresql
HTMLDIR = /usr/local/gpdb-5.3.0/doc/postgresql
INCLUDEDIR = /usr/local/gpdb-5.3.0/include
PKGINCLUDEDIR = /usr/local/gpdb-5.3.0/include/postgresql
INCLUDEDIR-SERVER = /usr/local/gpdb-5.3.0/include/postgresql/server
LIBDIR = /usr/local/gpdb-5.3.0/lib
PKGLIBDIR = /usr/local/gpdb-5.3.0/lib/postgresql
LOCALEDIR = /usr/local/gpdb-5.3.0/share/locale
MANDIR = /usr/local/gpdb-5.3.0/share/man
SHAREDIR = /usr/local/gpdb-5.3.0/share/postgresql
SYSCONFDIR = /usr/local/gpdb-5.3.0/etc/postgresql
PGXS = /usr/local/gpdb-5.3.0/lib/postgresql/pgxs/src/makefiles/pgxs.mk
CC = gcc
CPPFLAGS = -D_GNU_SOURCE -I/usr/local/gpdb-5.3.0/include
CFLAGS = -O3 -std=gnu99 -Wall -Wmissing-prototypes -Wpointer-arith -Wendif-labels -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fno-aggressive-loop-optimizations -Wno-unused-but-set-variable -Wno-address -I/usr/local/gpdb-5.3.0/include
CFLAGS_SL = -fpic
LDFLAGS = -Wl,--as-needed -Wl,-rpath,'/usr/local/gpdb-5.3.0/lib',--enable-new-dtags -L/usr/local/gpdb-5.3.0/lib
LDFLAGS_SL =
LIBS = -lpgport -lgpopt -lnaucrates -lgpdbcost -lgpos -lxerces-c -lxslt -lxml2 -lrt -lgssapi_krb5 -lcrypt -ldl -lm -L/usr/local/gpdb-5.3.0/lib
VERSION = PostgreSQL 8.3.23
```

### Expected behavior

gprecoverseg -aF and following gprecoverseg -r should complete recover

### Actual behavior

The sync process stale forever

### Step to reproduce the behavior

Kill -9 primary postmaster on the segment while it performs SQL query. Wait mirror to switch to primary. Try to recover. The problem is discussed at https://groups.google.com/a/greenplum.org/forum/#!topic/gpdb-users/IyVNraDXow0

You can check necessary logs at https://yadi.sk/d/q56hKmhr3S6rwg

The files included:
master.gpdb-2018-02-05_115342.csv
master.gpdb-2018-02-05_115350.csv
sdw2.mirror.gpdb-2018-02-05_115348.csv
sdw3.primary.gpdb-2018-02-05_115349.csv
gpAdminLogs/gprecoverseg_20180201.log
gpAdminLogs/gprecoverseg_20180202.log

**Comment by ashwinstar** [comment]
For 5.3 `--enable-segwalrep` was feature in development for 6.0 and never intended for 5.0. The code for `--enable-segwalrep` will be ripped out of 5.x soon. For 5.x filerep should be used for HA and this config flag should to be turned on.

Master (6.0 and +) uses wal replication for HA, so if wish to evaluate / try out same please use latest master.
