### ISSUE TITLE
gpperfmon_install utility is not available within ubuntu package

### ISSUE THREAD

**Issue by baileygm** [greenplum-db/gpdb#4513]
When installing Greenplum OSS using the distributed Ubuntu binaries - https://greenplum.org/install-greenplum-oss-on-ubuntu/ - it appears that the "gpperfmon_install" command-line utility is not contained within the Ubuntu package.

**Comment by cjcjameson** [comment]
Confirmed that I also see this difference / lack. Looking to folks who worked more closely with the rpm to triage or provide more info.

Where is the PPA configuration code which is used to host the RPMs? I saw a typo in the repository PPA blurb that spits out after `add-apt-repository ppa:greenplum/db` and wanted to PR a fix.

**Comment by huoshan12345** [comment]
same here

**Comment by EldhoKSuresh** [comment]
Facing the same issue. Is there any workaround?

**Comment by baileygm** [comment]
Not that I have found, I stopped using the ubuntu binaries and built from source

> Facing the same issue. Is there any workaround?

**Comment by ivannovick** [comment]
this utility is deprecated
