### ISSUE TITLE
" make create-demo-cluster"command is failed because of "Failed to create standby" error

### ISSUE THREAD

**Issue by vishal2601** [greenplum-db/gpdb#4517]
### Greenplum version or build
4.3.10
### OS version and uname -a
centos 6.9
### Installation information ( pg_config )
I am running make command with gpadmin user.
### Expected behavior
make create-demo-cluster should create cluster without any error message.
### Actual behavior
[gpadmin@gpdb-sandbox gpdb]$  make create-demo-cluster
make -C gpAux/gpdemo create-demo-cluster
make[1]: Entering directory '/home/gpadmin/gpdb/gpAux/gpdemo'
======================================================================
            ______  _____  ______  _______ _______  _____
           |  ____ |_____] |     \ |______ |  |  | |     |
           |_____| |       |_____/ |______ |  |  | |_____|

----------------------------------------------------------------------

  This is a demo of the Greenplum Database system.  We will create
  a cluster installation with master and 6 segment instances
  (3 primary & 3 mirror).

    GPHOME ................. : /usr/local/greenplum-db/.
    MASTER_DATA_DIRECTORY .. : /home/gpadmin/gpdb/gpAux/gpdemo/datadirs/qddir/demoDataDir-1

    MASTER PORT (PGPORT) ... : 15432
    STANDBY PORT ........... : 16432
    SEGMENT PORTS .......... : 25432 25433 25434 25435 25436 25437

  NOTE(s):

    * The DB ports identified above must be available for use.
    * An environment file gpdemo-env.sh has been created for your use.

======================================================================

WARNING: fsync is off, database consistency is not guaranteed.

======================================================================
CLUSTER_CONFIG_POSTGRES_ADDONS: clusterConfigPostgresAddonsFile
----------------------------------------------------------------------

fsync=off

======================================================================

==========================================================================================
executing:
  /usr/local/greenplum-db/./bin/gpinitsystem -a -c clusterConfigFile -l /home/gpadmin/gpdb/gpAux/gpdemo/datadirs/gpAdminLogs -p clusterConfigPostgresAddonsFile -s gpdb-sandbox.localdomain -P 16432 -F /home/gpadmin/gpdb/gpAux/gpdemo/datadirs/standby ""
==========================================================================================

20180208:17:08:57:000545 gpinitsystem:gpdb-sandbox:gpadmin-[INFO]:-Checking configuration parameters, please wait...
20180208:17:08:57:000545 gpinitsystem:gpdb-sandbox:gpadmin-[INFO]:-Reading Greenplum configuration file clusterConfigFile
20180208:17:08:57:000545 gpinitsystem:gpdb-sandbox:gpadmin-[INFO]:-Locale has not been set in clusterConfigFile, will set to default value
20180208:17:08:57:000545 gpinitsystem:gpdb-sandbox:gpadmin-[INFO]:-Locale set to en_US.utf8
20180208:17:08:57:000545 gpinitsystem:gpdb-sandbox:gpadmin-[INFO]:-No DATABASE_NAME set, will exit following template1 updates
20180208:17:08:57:000545 gpinitsystem:gpdb-sandbox:gpadmin-[INFO]:-MASTER_MAX_CONNECT not set, will set to default value 150
20180208:17:08:57:000545 gpinitsystem:gpdb-sandbox:gpadmin-[INFO]:-Detected a single host GPDB array build, reducing value of BATCH_DEFAULT from 60 to 4
20180208:17:08:57:000545 gpinitsystem:gpdb-sandbox:gpadmin-[INFO]:-Checking configuration parameters, Completed
20180208:17:08:57:000545 gpinitsystem:gpdb-sandbox:gpadmin-[INFO]:-Commencing multi-home checks, please wait...
.
20180208:17:08:57:000545 gpinitsystem:gpdb-sandbox:gpadmin-[INFO]:-Configuring build for standard array
20180208:17:08:58:000545 gpinitsystem:gpdb-sandbox:gpadmin-[INFO]:-Commencing multi-home checks, Completed
20180208:17:08:58:000545 gpinitsystem:gpdb-sandbox:gpadmin-[INFO]:-Building primary segment instance array, please wait...
...
20180208:17:08:58:000545 gpinitsystem:gpdb-sandbox:gpadmin-[INFO]:-Building group mirror array type , please wait...
...
20180208:17:08:59:000545 gpinitsystem:gpdb-sandbox:gpadmin-[INFO]:-Checking Master host
20180208:17:08:59:000545 gpinitsystem:gpdb-sandbox:gpadmin-[INFO]:-Checking new segment hosts, please wait...
......
20180208:17:09:00:000545 gpinitsystem:gpdb-sandbox:gpadmin-[INFO]:-Checking new segment hosts, Completed
20180208:17:09:01:000545 gpinitsystem:gpdb-sandbox:gpadmin-[INFO]:-Building the Master instance database, please wait...
20180208:17:09:11:000545 gpinitsystem:gpdb-sandbox:gpadmin-[INFO]:-Starting the Master in admin mode
20180208:17:09:18:000545 gpinitsystem:gpdb-sandbox:gpadmin-[INFO]:-Commencing parallel build of primary segment instances
20180208:17:09:18:000545 gpinitsystem:gpdb-sandbox:gpadmin-[INFO]:-Spawning parallel processes    batch [1], please wait...
...
20180208:17:09:19:000545 gpinitsystem:gpdb-sandbox:gpadmin-[INFO]:-Waiting for parallel processes batch [1], please wait...
.......................
20180208:17:09:42:000545 gpinitsystem:gpdb-sandbox:gpadmin-[INFO]:------------------------------------------------
20180208:17:09:42:000545 gpinitsystem:gpdb-sandbox:gpadmin-[INFO]:-Parallel process exit status
20180208:17:09:42:000545 gpinitsystem:gpdb-sandbox:gpadmin-[INFO]:------------------------------------------------
20180208:17:09:42:000545 gpinitsystem:gpdb-sandbox:gpadmin-[INFO]:-Total processes marked as completed           = 3
20180208:17:09:43:000545 gpinitsystem:gpdb-sandbox:gpadmin-[INFO]:-Total processes marked as killed              = 0
20180208:17:09:43:000545 gpinitsystem:gpdb-sandbox:gpadmin-[INFO]:-Total processes marked as failed              = 0
20180208:17:09:43:000545 gpinitsystem:gpdb-sandbox:gpadmin-[INFO]:------------------------------------------------
20180208:17:09:43:000545 gpinitsystem:gpdb-sandbox:gpadmin-[INFO]:-Commencing parallel build of mirror segment instances
20180208:17:09:43:000545 gpinitsystem:gpdb-sandbox:gpadmin-[INFO]:-Spawning parallel processes    batch [1], please wait...
...
20180208:17:09:43:000545 gpinitsystem:gpdb-sandbox:gpadmin-[INFO]:-Waiting for parallel processes batch [1], please wait...
.........
20180208:17:09:52:000545 gpinitsystem:gpdb-sandbox:gpadmin-[INFO]:------------------------------------------------
20180208:17:09:52:000545 gpinitsystem:gpdb-sandbox:gpadmin-[INFO]:-Parallel process exit status
20180208:17:09:52:000545 gpinitsystem:gpdb-sandbox:gpadmin-[INFO]:------------------------------------------------
20180208:17:09:52:000545 gpinitsystem:gpdb-sandbox:gpadmin-[INFO]:-Total processes marked as completed           = 3
20180208:17:09:52:000545 gpinitsystem:gpdb-sandbox:gpadmin-[INFO]:-Total processes marked as killed              = 0
20180208:17:09:52:000545 gpinitsystem:gpdb-sandbox:gpadmin-[INFO]:-Total processes marked as failed              = 0
20180208:17:09:52:000545 gpinitsystem:gpdb-sandbox:gpadmin-[INFO]:------------------------------------------------
20180208:17:09:53:000545 gpinitsystem:gpdb-sandbox:gpadmin-[INFO]:-Deleting distributed backout files
20180208:17:09:53:000545 gpinitsystem:gpdb-sandbox:gpadmin-[INFO]:-Removing back out file
20180208:17:09:53:000545 gpinitsystem:gpdb-sandbox:gpadmin-[INFO]:-No errors generated from parallel processes
20180208:17:09:53:000545 gpinitsystem:gpdb-sandbox:gpadmin-[INFO]:-Starting initialization of standby master gpdb-sandbox.localdomain
20180208:17:09:53:020311 gpinitstandby:gpdb-sandbox:gpadmin-[ERROR]:-Failed to retrieve configuration information from the master.
20180208:17:09:53:020311 gpinitstandby:gpdb-sandbox:gpadmin-[ERROR]:-Failed to create standby
20180208:17:09:53:020311 gpinitstandby:gpdb-sandbox:gpadmin-[ERROR]:-Error initializing standby master: bad format for filespaces:/home/gpadmin/gpdb/gpAux/gpdemo/datadirs/standby
20180208:17:09:53:gpinitsystem:gpdb-sandbox:gpadmin-[FATAL]:-Initialization of standby master failed Script Exiting!
========================================
gpinitsystem returned: 0
========================================

======================================================================
                           OPTIMIZER STATE
----------------------------------------------------------------------
  Optimizer state .. : psql: FATAL:  System was started in master-only utility mode - only utility mode connections are allowed
======================================================================

psql: FATAL:  System was started in master-only utility mode - only utility mode connections are allowed
======================================================================

make[1]: Leaving directory '/home/gpadmin/gpdb/gpAux/gpdemo'
### Step to reproduce the behavior
cd depends
./configure
make
make install_local
cd ..
./configure --with-perl --with-python --with-libxml --with-gssapi --prefix=/usr/local/gpdb
make -j8
make -j8 install
source /usr/local/gpdb/greenplum_path.sh
make create-demo-cluster

**Comment by cjcjameson** [comment]
Hi @vishal2601 -- a little confused. You say you're running a 4.3.x version, which is not open source, but you also provide reproduction steps consistent with an open source build. Can you clarify?

**Comment by vishal2601** [comment]
Version detail:
 PostgreSQL 8.5devel (Greenplum Database 6.0.0-alpha.0+dev.3729.g6a371cb build dev-oss) on x86_64-pc-linux-gnu, compiled by GCC gcc (GCC) 4.8.5 20150
623 (Red Hat 4.8.5-16), 64-bit compiled on Feb 12 2018 08:22:55
(1 row)

My problem solved after i tried same thing in centos 7.1.
