### ISSUE TITLE
Replace "source" with . (dot)

### ISSUE THREAD

**Issue by andreasscherbaum** [greenplum-db/gpdb#455]
Ubuntu is using "dash" as default shell

ads@diamond:~$ ls -ld /bin/sh
lrwxrwxrwx 1 root root 4 Nov 23 17:05 /bin/sh -> dash

The "dash" shell does not understand "source", which is a "bash" extension. The proper way to do it is just use a dot to source other files into the current shell. This affects at least the README and a number of examples.

**Comment by danielgustafsson** [comment]
Considering that we require bash for much of gpMgmt, is it useful to support non-bash shells? I don't object to the change per se (unless where it would deviate from upstream should that be the case) but if we explicitly support other shells we should perhaps ensure the rest of the scripts work with them?

**Comment by andreasscherbaum** [comment]
We want to improve gpMgmt anyway. The main reason is outlined in the original posting: Ubuntu does not even have bash as the standard shell. We surely will see more such problems in the future.

**Comment by danielgustafsson** [comment]
Probably yes, ideally we should be more shell agnostic.

**Comment by andreasscherbaum** [comment]
@Eulerizeit The problem is not solved, right?

**Comment by Eulerizeit** [comment]
Not fixed but also not being picked up.
