### ISSUE TITLE
SEGFAULT in the master optimizer with ORCA enabled

### ISSUE THREAD

**Issue by dashawake** [greenplum-db/gpdb#4581]
### Greenplum version or build
5.1.0, sha=8435db1
### OS version and uname -a
Linux awake-greenplum 4.9.76 #1-NixOS SMP Wed Jan 10 08:29:55 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
### Installation information ( pg_config )
BINDIR = /usr/local/awake-greenplum-db-5.1.0-8435db1.2017.10.19/bin
DOCDIR = /usr/local/awake-greenplum-db-5.1.0-8435db1.2017.10.19/doc/postgresql
HTMLDIR = /usr/local/awake-greenplum-db-5.1.0-8435db1.2017.10.19/doc/postgresql
INCLUDEDIR = /usr/local/awake-greenplum-db-5.1.0-8435db1.2017.10.19/include
PKGINCLUDEDIR = /usr/local/awake-greenplum-db-5.1.0-8435db1.2017.10.19/include/postgresql
INCLUDEDIR-SERVER = /usr/local/awake-greenplum-db-5.1.0-8435db1.2017.10.19/include/postgresql/server
LIBDIR = /usr/local/awake-greenplum-db-5.1.0-8435db1.2017.10.19/lib
PKGLIBDIR = /usr/local/awake-greenplum-db-5.1.0-8435db1.2017.10.19/lib/postgresql
LOCALEDIR = /usr/local/awake-greenplum-db-5.1.0-8435db1.2017.10.19/share/locale
MANDIR = /usr/local/awake-greenplum-db-5.1.0-8435db1.2017.10.19/share/man
SHAREDIR = /usr/local/awake-greenplum-db-5.1.0-8435db1.2017.10.19/share/postgresql
SYSCONFDIR = /usr/local/awake-greenplum-db-5.1.0-8435db1.2017.10.19/etc/postgresql
PGXS = /usr/local/awake-greenplum-db-5.1.0-8435db1.2017.10.19/lib/postgresql/pgxs/src/makefiles/pgxs.mk
CC = gcc
CPPFLAGS = -D_GNU_SOURCE -I/usr/local/awake-greenplum-db-5.1.0-8435db1.2017.10.19/include
CFLAGS = -O3 -std=gnu99 -Wall -Wmissing-prototypes -Wpointer-arith -Wendif-labels -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fno-aggressive-loop-optimizations -Wno-unused-but-set-variable -Wno-address -I/usr/local/awake-greenplum-db-5.1.0-8435db1.2017.10.19/include
CFLAGS_SL = -fpic
LDFLAGS = -Wl,--as-needed -Wl,-rpath,'/usr/local/awake-greenplum-db-5.1.0-8435db1.2017.10.19/lib',--enable-new-dtags -L/usr/local/awake-greenplum-db-5.1.0-8435db1.2017.10.19/lib
LDFLAGS_SL =
LIBS = -lpgport -lgpopt -lnaucrates -lgpdbcost -lgpos -lxerces-c -lrt -lcrypt -ldl -lm -L/usr/local/awake-greenplum-db-5.1.0-8435db1.2017.10.19/lib
VERSION = PostgreSQL 8.3.23
### Expected behavior
The master not to crash.
### Actual behavior
The master crashes after seemingly very lightweight queries.
```
master/gpsne-1/pg_log/gpdb-2018-02-23_062039.csv-2018-02-23 17:36:03.310539 UTC,,,p541,th2145310784,,,,0,,,seg-1,,,,,"LOG","00000","3rd party error log:
master/gpsne-1/pg_log/gpdb-2018-02-23_062039.csv-Unexpected exception reached top of execution stack: major=200 minor=14 file=CTranslatorUtils.cpp line=162",,,,,,,,"SysLoggerMain","syslogger.c",618,
master/gpsne-1/pg_log/gpdb-2018-02-23_062039.csv-2018-02-23 17:36:03.310578 UTC,"gpadmin","asset",p29620,th2145310784,"172.18.128.6","52328",2018-02-23 16:13:43 UTC,0,con4507,cmd33,seg-1,,dx5995,,sx1,"LOG","00000","Planner produced plan :0",,,,,,"SELECT e.typdelim FROM pg_catalog.pg_type t, pg_catalog.pg_type e WHERE t.oid = $1 and t.typelem = e.oid",0,,"orca.c",60,
master/gpsne-1/pg_log/gpdb-2018-02-23_062039.csv-2018-02-23 17:36:03.310841 UTC,"gpadmin","asset",p29620,th2145310784,"172.18.128.6","52328",2018-02-23 16:13:43 UTC,0,con4507,cmd34,seg-1,,dx5995,,sx1,"LOG","00000","execute <unnamed>: SELECT e.typdelim FROM pg_catalog.pg_type t, pg_catalog.pg_type e WHERE t.oid = $1 and t.typelem = e.oid","parameters: $1 = '2951'",,,,,"SELECT e.typdelim FROM pg_catalog.pg_type t, pg_catalog.pg_type e WHERE t.oid = $1 and t.typelem = e.oid",0,,"postgres.c",2788,
master/gpsne-1/pg_log/gpdb-2018-02-23_062039.csv:2018-02-23 17:36:03.350465 UTC,,,p29620,th0,,,2018-02-23 16:13:43 UTC,0,con4507,cmd34,seg-1,,,,,"PANIC","XX000","Unexpected internal error: Master process received signal SIGSEGV",,,,,,,0,,,,"1    0x7fa27f794944 libgpopt.so.3 _ZN5gpopt22CConstraintConjunctionC2EPN4gpos11IMemoryPoolEPNS1_16CDynamicPtrArrayINS_11CConstraintEXadL_ZNS1_14CleanupReleaseIS5_EEvPT_EEEE + 0x44
master/gpsne-1/pg_log/gpdb-2018-02-23_062039.csv-2    0x7fa27f78f2a8 libgpopt.so.3 _ZN5gpopt11CConstraint14PcnstrConjDisjEPN4gpos11IMemoryPoolEPNS1_16CDynamicPtrArrayIS0_XadL_ZNS1_14CleanupReleaseIS0_EEvPT_EEEEb + 0x98
master/gpsne-1/pg_log/gpdb-2018-02-23_062039.csv-3    0x7fa27f8213af libgpopt.so.3 _ZN5gpopt8CLogical33PpcDeriveConstraintFromPredicatesEPN4gpos11IMemoryPoolERNS_17CExpressionHandleE + 0x38f
master/gpsne-1/pg_log/gpdb-2018-02-23_062039.csv-4    0x7fa27f7b1adb libgpopt.so.3 _ZN5gpopt19CDrvdPropRelational6DeriveEPN4gpos11IMemoryPoolERNS_17CExpressionHandleEPNS_13CDrvdPropCtxtE + 0xbb
master/gpsne-1/pg_log/gpdb-2018-02-23_062039.csv-5    0x7fa27f8087e6 libgpopt.so.3 _ZN5gpopt11CExpression9PdpDeriveEPNS_13CDrvdPropCtxtE + 0xa6
master/gpsne-1/pg_log/gpdb-2018-02-23_062039.csv-6    0x7fa27f7cceab libgpopt.so.3 _ZN5gpopt6CUtils13FHasOuterRefsEPNS_11CExpressionE + 0xb
master/gpsne-1/pg_log/gpdb-2018-02-23_062039.csv-7    0x7fa27f816d93 libgpopt.so.3 _ZN5gpopt23CExpressionPreprocessor31PexprRemoveSuperfluousOuterRefsEPN4gpos11IMemoryPoolEPNS_11CExpressionE + 0x323
master/gpsne-1/pg_log/gpdb-2018-02-23_062039.csv-8    0x7fa27f81d23b libgpopt.so.3 _ZN5gpopt23CExpressionPreprocessor15PexprPreprocessEPN4gpos11IMemoryPoolEPNS_11CExpressionEPNS_10CColRefSetE + 0xbb
master/gpsne-1/pg_log/gpdb-2018-02-23_062039.csv-9    0x7fa27f7c80b2 libgpopt.so.3 _ZN5gpopt13CQueryContextC2EPN4gpos11IMemoryPoolEPNS_11CExpressionEPNS_13CReqdPropPlanEPNS1_16CDynamicPtrArrayINS_7CColRefEXadL_ZNS1_11CleanupNULLIS9_EEvPT_EEEEPNS8_IN4gpmd7CMDNameEXadL_ZNS1_13CleanupDeleteISG_EEvSC_EEEEb + 0x102
master/gpsne-1/pg_log/gpdb-2018-02-23_062039.csv-10   0x7fa27f7c86a7 libgpopt.so.3 _ZN5gpopt13CQueryContext11PqcGenerateEPN4gpos11IMemoryPoolEPNS_11CExpressionEPNS1_16CDynamicPtrArrayIjXadL_ZNS1_13CleanupDeleteIjEEvPT_EEEEPNS6_IN4gpmd7CMDNameEXadL_ZNS7_ISD_EEvS9_EEEEb + 0x4c7
master/gpsne-1/pg_log/gpdb-2018-02-23_062039.csv-11   0x7fa27f87ad7b libgpopt.so.3 _ZN5gpopt10COptimizer13PdxlnOptimizeEPN4gpos11IMemoryPoolEPNS_11CMDAccessorEPKN5gpdxl8CDXLNodeEPKNS1_16CDynamicPtrArrayIS7_XadL_ZNS1_14CleanupReleaseIS7_EEvPT_EEEESG_PNS_19IConstExprEvaluatorEjjjPNSA_INS_12CSearchStageEXadL_ZNS1_13CleanupDeleteISJ_EEvSD_EEEEPNS_16COptimizerConfigEPKc + 0x3bb
```
### Step to reproduce the behavior
Have not figured out the reproduceability. The crashes seem to happen randomly about dozen times a day.

**Comment by dhanashreek89** [comment]
Could you identify the query that is resulting into a crash ?

**Comment by dashawake** [comment]
I believe there is no specific one that causes this crash to happen, but not very confident yet. Is there a way to determine from the JDBC layer if the master crashed during a query? From the logs, I only have access to the queries before this happens, which are select-* queries on tables with a dozen of rows, that we keep for configuration.

**Comment by dashawake** [comment]
This is one example of seemingly random queries crashing the server. The table has only one row, and the first call crashes the server. When it's back, the same query doesn't.

```asset=# select version from table_versions where name = 'ipinterval_summary' limit 1;
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
The connection to the server was lost. Attempting reset: Succeeded.
asset=# select * from table_versions;
        name        | version
--------------------+---------
 ipinterval_summary |       3
(1 row)

asset=# select version from table_versions where name = 'ipinterval_summary' limit 1;
 version
---------
       3
(1 row)```

**Comment by vraghavan78** [comment]
@dashawake please re-open the issue with the answers to @d
