### ISSUE TITLE
Possible query planning bug (different tupdesc for scan and for result appending)

### ISSUE THREAD

**Issue by yew011** [greenplum-db/gpdb#4604]
### Greenplum version or build

Greenplum 5.5.0, commit 67afa18296aa238d53a2dfcc724da60ed2f944f0 (tag: 5.5.0)

### OS version and uname -a

```
[root:/etc/systemd/system]# uname -a
Linux hostname 4.9.76 #1-NixOS SMP Wed Jan 10 08:29:55 UTC 2018 x86_64 GNU/Linux
```

### autoconf options used ( config.status --config )

```
[root gpdb]# ./config.status --config
'--with-openssl' '--with-python' '--enable-orca' '--prefix=/usr/local/greenplum-db-5.5.0' 'CC=gcc' 'LDFLAGS=-L/usr/local/greenplum-db-5.5.0/lib' 'CPPFLAGS=-I/usr/local/greenplum-db-5.5.0/include
```

### Expected behavior

For a quite simple schema:

```
asset=# \d sessions
                   Append-Only Columnar Table "public.sessions"
             Column             |            Type            |     Modifiers
--------------------------------+----------------------------+--------------------
 id                             | uuid                       | not null
 pseudo_id                      | uuid                       |
 startts                        | timestamp with time zone   |
 endts                          | timestamp with time zone   |
 proto                          | text                       |
 bytesA2B                       | bigint                     |
 bytesB2A                       | bigint                     |
 proto                          | text                       |
 ipprotocol                     | integer                    |
Checksum: t
Number of child tables: 53 (Use \d+ to list them.)
Distributed by: (id)
Partition by: (endts)
Tablespace: "spinningtspc"
```

For the query below we expect it to succeeds,,,

```
SELECT gp_segment_id, tableoid, ctid, id, pseudo_id, proto
        FROM sessions_daily_18_02_27_1_prt_dp2018_02_27_02 AS sessions
         WHERE ((( ipprotocol = 6 ) AND (( ipprotocol = 6 ) AND (bytesB2A = bytesA2B)))) AND (endts < '2018-02-27T02:31:30Z' AND endts >= '2018-02-27T02:21:30Z')
        LIMIT 1 ;
```

### Actual behavior

Failed with the following error:

```
ERROR:  compressed data is corrupt (pg_lzcompress.c:737)
```

### Initial investigation

Via GDB into both the master process and the segment process, I discovered that the `tupledesc` for the `T_Append` plan on master process correctly has 6 attributes corresponding to columns specified in `SELECT`.  However the `tupledesc` for the `T_AOCSScan` plan on segment process has 8 attributes including the `bytesB2A` and `bytesA2B` specified in the `WHERE` clause... ... ...

This has caused the segment process using a totally different `memtuple` offset than what the master process expects...  And the exact `compressed data is corrupt` error is due to the master process expects the starting point for `proto` (type `MTB_ByRef`) column to be at offset 18, but the segment writes it at offset 38...

This is likely a query planning bug and happens regardless optimizer being set or not.

**Comment by yew011** [comment]
From the following comments in the `create_col_bind()` function

```
        /*
         * First pass, do 8 bytes aligned, native type.
         * Sencond pass, do 4 bytes aligned, native type.
         * Third pass, do 2 bytes aligned, native type.
         * Finall, do 1 bytes aligned native type.
         *
         * depends on islarge, varlena types are either handled in the
         * second pass (is large, varoffset using 4 bytes), or in the
         * third pass (not large, varoffset using 2 bytes).
         */
```

GPDB always do 8 bytes alignment first when determining the `memtuple` offset from the `tupdesc`, so when the unspecified but 8-byte size columns (`bytesB2A` and `bytesA2B`) are included in the `tupdesc`... the generated offset plan will always put those columns first resulting in a mismatch of understanding between master and segment...

**Comment by asimrp** [comment]
@yew011 your detailed investigation will help reverse-engineer a table that reproduces the issue.  If you have a table definition handy, do you mind sharing it so that we can easily reproduce and work on the issue?

**Comment by hlinnaka** [comment]
Seems to work on master. I'm not sure what fixed it, though. I hope it's correct now, and not just somehow masked by unrelated changes.

**Comment by ivannovick** [comment]
stale issue on old version
