### ISSUE TITLE
为什么会产生临时表,该怎么清理

### ISSUE THREAD

**Issue by shubifeng** [greenplum-db/gpdb#4651]
### Greenplum version or build
5.4

### OS version and uname -a
Linux mdw 3.10.0-693.11.6.el7.x86_64 #1 SMP Thu Jan 4 01:06:37 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

### temp table:
pg_temp_2099
pg_toast_temp_2099

**Comment by hlinnaka** [comment]
This sounds similar to https://github.com/greenplum-db/gpdb/issues/4061, but that was fixed in 5.4 already.

Can you explain in more detail,  how to reproduce the problem? What SQL commands did you run? What did you expect to happen?

**Comment by shubifeng** [comment]
@hlinnaka 当大数据量批量插入的时候会存在这个问题.

**Comment by hlinnaka** [comment]
> This problem exists when large amounts of data are inserted in bulk. (translation by Google translate)

I'm afraid that's still not enough information to debug this. We'd need to see a self-contained script, with the exact SQL commands.

**Comment by shubifeng** [comment]
可能是处理失败导致临时表不能自动删除.

```
CREATE TEMP TABLE vm_store_unilife_order_group_order ON COMMIT DELETE ROWS AS SELECT * FROM vm_store.unilife_order_group_order LIMIT 0;
COPY vm_store_unilife_order_group_order (id) FROM STDIN WITH DELIMITER '|' NULL '' CSV QUOTE '"' ESCAPE E'\\'; 
DELETE FROM vm_store.unilife_order_group_order WHERE EXISTS (SELECT 1 FROM vm_store_unilife_order_group_order WHERE vm_store.unilife_order_group_order.id=vm_store_unilife_order_group_order.id);
```
