### ISSUE TITLE
gpcc日志时间不对

### ISSUE THREAD

**Issue by shubifeng** [greenplum-db/gpdb#4653]
gpcc 3.3 日志时间显示不对:
 北京时间 2018-03-09 11:50:00 , 地球上的3月10日还没到来. 为什么是3月10日?

![default](https://user-images.githubusercontent.com/6796352/37189718-ba4d9f56-2390-11e8-8c22-b59d0960bcac.png)

**Comment by Eulerizeit** [comment]
This is the Open Source Greenplum Repo. I'll Make sure @jingli and the team have seen this but then the issue will be closed. You will need to follow up with whomever is providing your support.

**Comment by yydzero** [comment]
@shubifeng GPCC is closed source code and not part of OSS Greenplum, so please contact Pivotal Support. Will close this issue.
