### ISSUE TITLE
Why always gpload hang after function run2?

### ISSUE THREAD

**Issue by laixiong** [greenplum-db/gpdb#4659]
we using gpload for data batch load,but we find the load hang after running function run2(the last log was :running time: xxx seconds),and the process gpfdist maybe killed or maybe not , this happens for low probability, but it could hang for a week.
could some one figure out ?

**Comment by lij55** [comment]
Could you give us more detail about how to reproduce it?
What's the version of Greenplum and OS?

**Comment by laixiong** [comment]
gpdb version: 5.1.0
os version : centos 6.8

**Comment by laixiong** [comment]
today it happens again.
I found gpfdist was not killed successfull,
and gploader.py has 3 threads, and the arguments of them are all the same ,
gpfdist just has 1 thread(I only set 1 path in yaml control file),
process does not exists because all gploader.py threads joins.
I don't known why it create 3 threads, and I will keep debugging.

**Comment by laixiong** [comment]
Here is the stack of gpfdist process:
`gdb -p 32178
(gdb) bt
#0  .. in __lll_lock_wait_private() from /lib64/lib/libc.so.6
#1  .. in _L_lock_2164() from ..
#2  .. in __tz_convert() from ..
#3  .. in explode_time()
#4  .. in apr_time_exp_lt()
#5  .. in gwarning.constpop.16() in gpfdist.c:2671
#6  .. in process_signal() at gpfdist.c:2536
#7  <signal handler called>
#8  .. in __tzset_parse_tz() from
#9  .. in __tzfile_compute() from 
#10 .. in __tz_convert()
#11 .. in explode_time()
#12 .. in apr_time_exp_lt()
#13 .. in _gprint() at gpfdist:2671
#14 .. in gprintlnif() at gpfdist:2746
#15 .. in do_close()at gpfdist.c:4195
#16 .. in event_process_active()
#17 .. in event_base_loop()
#18 .. in event_loop()
#19 .. in event_dispatch()
#20 .. in __libc_start_main() from ..
#21 .. in _start()
`
