### ISSUE TITLE
[docs] remove gpadmin mention from PXF doc

### ISSUE THREAD

**Issue by kapustor** [greenplum-db/gpdb#4667]
gpdb/gpdb-doc/markdown/pxf/hdfs_write_pxf.html.md.erb now contain phrase:

> - You have granted the `gpadmin` user *read and write* permissions to the appropriate directories in your HDFS file system.

Since we have user impersonation while accessing Hadoop, as I understand we need to remove or change this phrase to something like:

> - You have granted your Greenplum's user that will access the external table *read and write* permissions to the appropriate directories in your HDFS file system.

**Comment by lisakowen** [comment]
good catch, @kapustor .  i will update that text.

**Comment by lisakowen** [comment]
see https://github.com/greenplum-db/gpdb/pull/4676.  (for some reason i could not "at" you on the PR?)

**Comment by kapustor** [comment]
Thanks! Maybe because I am not from Pivotal team?

**Comment by lisakowen** [comment]
not sure, i can "at" you on this issue @kapustor ...

**Comment by lisakowen** [comment]
fixed in PR above.
