### ISSUE TITLE
Regression test "qp_dml_joins" fails when GPDB is compiled without ORCA

### ISSUE THREAD

**Issue by andreasscherbaum** [greenplum-db/gpdb#4668]
### Greenplum version or build
master/head

### OS version and uname -a
Linux diagnostics-test 3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

### autoconf options used ( config.status --config )
'--prefix=/home/ads/buildfarm/install/2018-03-10_084901_master' '--disable-orca' '--with-perl' '--with-python' '--with-libxml' 'CC=/usr/bin/ccache gcc' 'CXX=/usr/bin/ccache g++'

### Expected behavior
Regression test should pass

### Actual behavior
Regression test qp_dml_joins fails with "unsifficient memory" error:

```
--- /home/ads/buildfarm/build/2018-03-10_084901_master/src/test/regress/expected/qp_dml_joins.out       2018-03-10 08:57:05.234052726 +0000
+++ /home/ads/buildfarm/build/2018-03-10_084901_master/src/test/regress/results/qp_dml_joins.out        2018-03-10 08:57:05.312059729 +0000
@@ -2495,12 +2495,9 @@
 (1 row)
 
 DELETE FROM dml_heap_pt_r USING (SELECT dml_heap_pt_r.a FROM dml_heap_pt_r, dml_heap_pt_s WHERE dml_heap_pt_r.a = dml_heap_pt_s.a)foo WHERE dml_heap_pt_r.a = foo.a;
+ERROR:  insufficient memory reserved for statement
 SELECT COUNT(*) FROM dml_heap_pt_r;
- count 
--------
-     0
-(1 row)
-
+ERROR:  current transaction is aborted, commands ignored until end of transaction block
 rollback;
 --Delete with join in USING (Delete all rows )
 begin;
@@ -2582,12 +2579,9 @@
 
 PREPARE plan_del_3 as DELETE FROM dml_heap_pt_r WHERE b in (SELECT dml_heap_pt_r.b FROM dml_heap_pt_r,dml_heap_pt_s WHERE dml_heap_pt_r.b = dml_heap_pt_s.b);
 EXECUTE plan_del_3;
+ERROR:  insufficient memory reserved for statement
 SELECT COUNT(*) FROM dml_heap_pt_r;
- count 
--------
-     0
-(1 row)
-
+ERROR:  current transaction is aborted, commands ignored until end of transaction block
 rollback;
 --Delete with PREPARE plan
 begin;

======================================================================
```

### Step to reproduce the behavior
Compile without Orca.

First I thought this is because my original testing VM has not so much memory. But I re-ran the test on a system with 128 GB RAM, and it still fails consistently.

**Comment by andreasscherbaum** [comment]
Shouldn't that be part of the regression test? After all, what is the test for if it fails all the time?

**Comment by yydzero** [comment]
@d if it is won't fix, shall we close this issue?

**Comment by ashwinstar** [comment]
We should do something here, can't have test which fails consistently and not do anything about it. I think the way we made it fix in CI is set appropriate statement_mem required by the test, instead of CI we should do the same in test if that's the requirement or else disable the test. Can't just say it will fail and keep it.
