### ISSUE TITLE
读取GP数据库表信息或者用NAVICAT打开存储过程等很慢很慢的问题

### ISSUE THREAD

**Issue by DongJianzhi0223** [greenplum-db/gpdb#4674]
### Greenplum version or build
greenplum-db-4.3.17.0
### OS version and uname -a
CETNOS 6.5
### autoconf options used ( config.status --config )

各位大神好：

  不好意思，本人英文不好，问题比较复杂就用中文问一下，希望可以得到解答。

  在GP数据库集群使用一段时间后，再用NAVICAT类似的连接工具打开数据库表或者存储过程的时候十分十分的慢，看过POSTGRESQL的JDBC的源码， 里面有段代码是循环查询，不确定原因是不是因为这个。

  还有一个棘手的问题是如果GP的主机节点内存资源吃紧，基本沾满的情况下，是否也会影响上述的情况，导致利用软件连接数据库查询时变慢，因为没有查到主机内存会影响任务快慢。

  目前是生产环境，着急解决的上述问题，希望给予回答。

**Comment by Eulerizeit** [comment]
@DongJianzhi0223 this Github is for the open source product please reach out to your support team for issues with 4.3.x.
