### ISSUE TITLE
Modify the timezone is invaild alter restart the greenplum clusters

### ISSUE THREAD

**Issue by xueyilong** [greenplum-db/gpdb#4685]
### CentOS release 6.7 (Final)

When initdb the greenplum database clusters,The default timezone and log_timezone is GMT,So use the gpconfig command change GMT to PRC,And the that's working after execute gpstop -u ,But when restart the greenplum clusters,the parameters is invaild

$ gpconfig -s timezone
Values on all segments are consistent
GUC          : timezone
Master  value: PRC
Segment value: PRC

$ gpconfig -s log_timezone
Values on all segments are consistent
GUC          : log_timezone
Master  value: PRC
Segment value: PRC

$ gpstop -a -M fast
20180313:18:55:29:017902 gpstop:l-pgdata5:gpadmin-[INFO]:-Starting gpstop with args: -a -M fast
20180313:18:55:29:017902 gpstop:l-pgdata5:gpadmin-[INFO]:-Gathering information and validating the environment...
20180313:18:55:29:017902 gpstop:l-pgdata5:gpadmin-[INFO]:-Obtaining Greenplum Master catalog information
20180313:18:55:29:017902 gpstop:l-pgdata5:gpadmin-[INFO]:-Obtaining Segment details from master...
20180313:18:55:29:017902 gpstop:l-pgdata5:gpadmin-[INFO]:-Greenplum Version: 'postgres (Greenplum Database) 5.5.0 build commit:67afa18296aa238d53a2dfcc724da60ed2f944f0'
20180313:18:55:29:017902 gpstop:l-pgdata5:gpadmin-[INFO]:-There are 1 connections to the database
20180313:18:55:29:017902 gpstop:l-pgdata5:gpadmin-[INFO]:-Commencing Master instance shutdown with mode='fast'
20180313:18:55:29:017902 gpstop:l-pgdata5:gpadmin-[INFO]:-Master host=l-pgdata5
20180313:18:55:29:017902 gpstop:l-pgdata5:gpadmin-[INFO]:-Detected 1 connections to database
20180313:18:55:29:017902 gpstop:l-pgdata5:gpadmin-[INFO]:-Switching to WAIT mode
20180313:18:55:29:017902 gpstop:l-pgdata5:gpadmin-[INFO]:-Will wait for shutdown to complete, this may take some time if
20180313:18:55:29:017902 gpstop:l-pgdata5:gpadmin-[INFO]:-there are a large number of active complex transactions, please wait...
20180313:18:55:29:017902 gpstop:l-pgdata5:gpadmin-[INFO]:-Commencing Master instance shutdown with mode=fast
20180313:18:55:29:017902 gpstop:l-pgdata5:gpadmin-[INFO]:-Master segment instance directory=/gpseg-1
20180313:18:55:30:017902 gpstop:l-pgdata5:gpadmin-[INFO]:-Attempting forceful termination of any leftover master process
20180313:18:55:30:017902 gpstop:l-pgdata5:gpadmin-[INFO]:-Terminating processes for segment /gpseg-1
20180313:18:55:30:017902 gpstop:l-pgdata5:gpadmin-[INFO]:-Stopping master standby host l-pgdata6 mode=fast
20180313:18:55:31:017902 gpstop:l-pgdata5:gpadmin-[INFO]:-Successfully shutdown standby process on l-pgdata6
20180313:18:55:31:017902 gpstop:l-pgdata5:gpadmin-[INFO]:-Targeting dbid [2, 26, 3, 27, 4, 28, 5, 29, 6, 30, 7, 31, 8, 32, 9, 33, 10, 34, 11, 35, 12, 36, 13, 37, 14, 38, 15, 39, 16, 40, 17, 41, 18, 42, 19, 43, 20, 44, 21, 45, 22, 46, 23, 47, 24, 48, 25, 49] for shutdown
20180313:18:55:31:017902 gpstop:l-pgdata5:gpadmin-[INFO]:-Commencing parallel primary segment instance shutdown, please wait...
20180313:18:55:31:017902 gpstop:l-pgdata5:gpadmin-[INFO]:-0.00% of jobs completed
20180313:18:55:33:017902 gpstop:l-pgdata5:gpadmin-[INFO]:-100.00% of jobs completed
20180313:18:55:33:017902 gpstop:l-pgdata5:gpadmin-[INFO]:-Commencing parallel mirror segment instance shutdown, please wait...
20180313:18:55:33:017902 gpstop:l-pgdata5:gpadmin-[INFO]:-0.00% of jobs completed
20180313:18:55:35:017902 gpstop:l-pgdata5:gpadmin-[INFO]:-100.00% of jobs completed
20180313:18:55:35:017902 gpstop:l-pgdata5:gpadmin-[INFO]:-----------------------------------------------------
20180313:18:55:35:017902 gpstop:l-pgdata5:gpadmin-[INFO]:-   Segments stopped successfully      = 48
20180313:18:55:35:017902 gpstop:l-pgdata5:gpadmin-[INFO]:-   Segments with errors during stop   = 0
20180313:18:55:35:017902 gpstop:l-pgdata5:gpadmin-[INFO]:-----------------------------------------------------
20180313:18:55:35:017902 gpstop:l-pgdata5:gpadmin-[INFO]:-Successfully shutdown 48 of 48 segment instances 
20180313:18:55:35:017902 gpstop:l-pgdata5:gpadmin-[INFO]:-Database successfully shutdown with no errors reported
20180313:18:55:35:017902 gpstop:l-pgdata5:gpadmin-[INFO]:-Cleaning up leftover gpmmon process
20180313:18:55:35:017902 gpstop:l-pgdata5:gpadmin-[INFO]:-No leftover gpmmon process found
20180313:18:55:35:017902 gpstop:l-pgdata5:gpadmin-[INFO]:-Cleaning up leftover gpsmon processes
20180313:18:55:35:017902 gpstop:l-pgdata5:gpadmin-[INFO]:-No leftover gpsmon processes on some hosts. not attempting forceful termination on these hosts
20180313:18:55:35:017902 gpstop:l-pgdata5:gpadmin-[INFO]:-Cleaning up leftover shared memory

$ gpstart -a
20180313:18:56:42:018342 gpstart:l-pgdata5:gpadmin-[INFO]:-Starting gpstart with args: -a
20180313:18:56:42:018342 gpstart:l-pgdata5:gpadmin-[INFO]:-Gathering information and validating the environment...
20180313:18:56:42:018342 gpstart:l-pgdata5:gpadmin-[INFO]:-Greenplum Binary Version: 'postgres (Greenplum Database) 5.5.0 build commit:67afa18296aa238d53a2dfcc724da60ed2f944f0'
20180313:18:56:42:018342 gpstart:l-pgdata5:gpadmin-[INFO]:-Greenplum Catalog Version: '301705051'
20180313:18:56:42:018342 gpstart:l-pgdata5:gpadmin-[INFO]:-Starting Master instance in admin mode
20180313:18:56:44:018342 gpstart:l-pgdata5:gpadmin-[INFO]:-Obtaining Greenplum Master catalog information
20180313:18:56:44:018342 gpstart:l-pgdata5:gpadmin-[INFO]:-Obtaining Segment details from master...
20180313:18:56:44:018342 gpstart:l-pgdata5:gpadmin-[INFO]:-Setting new master era
20180313:18:56:44:018342 gpstart:l-pgdata5:gpadmin-[INFO]:-Master Started...
20180313:18:56:44:018342 gpstart:l-pgdata5:gpadmin-[INFO]:-Heap checksum setting is consistent across the cluster
20180313:18:56:44:018342 gpstart:l-pgdata5:gpadmin-[INFO]:-Shutting down master
20180313:18:56:46:018342 gpstart:l-pgdata5:gpadmin-[INFO]:-Commencing parallel primary and mirror segment instance startup, please wait...
... 
20180313:18:56:49:018342 gpstart:l-pgdata5:gpadmin-[INFO]:-Process results...
20180313:18:56:49:018342 gpstart:l-pgdata5:gpadmin-[INFO]:-----------------------------------------------------
20180313:18:56:49:018342 gpstart:l-pgdata5:gpadmin-[INFO]:-   Successful segment starts                                            = 48
20180313:18:56:49:018342 gpstart:l-pgdata5:gpadmin-[INFO]:-   Failed segment starts                                                = 0
20180313:18:56:49:018342 gpstart:l-pgdata5:gpadmin-[INFO]:-   Skipped segment starts (segments are marked down in configuration)   = 0
20180313:18:56:49:018342 gpstart:l-pgdata5:gpadmin-[INFO]:-----------------------------------------------------
20180313:18:56:49:018342 gpstart:l-pgdata5:gpadmin-[INFO]:-Successfully started 48 of 48 segment instances 
20180313:18:56:49:018342 gpstart:l-pgdata5:gpadmin-[INFO]:-----------------------------------------------------
20180313:18:56:49:018342 gpstart:l-pgdata5:gpadmin-[INFO]:-Starting Master instance l-pgdata5 directory /gpseg-1 
20180313:18:56:50:018342 gpstart:l-pgdata5:gpadmin-[INFO]:-Command pg_ctl reports Master l-pgdata5 instance active
20180313:18:56:50:018342 gpstart:l-pgdata5:gpadmin-[INFO]:-Starting standby master
20180313:18:56:50:018342 gpstart:l-pgdata5:gpadmin-[INFO]:-Checking if standby master is running on host: l-pgdata6 in directory: /gpseg-1
20180313:18:56:51:018342 gpstart:l-pgdata5:gpadmin-[INFO]:-Database successfully started
$ gpconfig -s timezone
Values on all segments are consistent
GUC          : timezone
Master  value: GMT
Segment value: PRC
$ gpconfig -s log_timezone
Values on all segments are consistent
GUC          : log_timezone
Master  value: GMT
Segment value: GMT
$ 
$ 
$ gpstop -u
20180313:18:57:15:018713 gpstop:l-pgdata5:gpadmin-[INFO]:-Starting gpstop with args: -u
20180313:18:57:15:018713 gpstop:l-pgdata5:gpadmin-[INFO]:-Gathering information and validating the environment...
20180313:18:57:15:018713 gpstop:l-pgdata5:gpadmin-[INFO]:-Obtaining Greenplum Master catalog information
20180313:18:57:15:018713 gpstop:l-pgdata5:gpadmin-[INFO]:-Obtaining Segment details from master...
20180313:18:57:15:018713 gpstop:l-pgdata5:gpadmin-[INFO]:-Greenplum Version: 'postgres (Greenplum Database) 5.5.0 build commit:67afa18296aa238d53a2dfcc724da60ed2f944f0'
20180313:18:57:15:018713 gpstop:l-pgdata5:gpadmin-[INFO]:-Signalling all postmaster processes to reload
. 
$ gpconfig -s timezone
Values on all segments are consistent
GUC          : timezone
Master  value: PRC
Segment value: PRC
$ gpconfig -s log_timezone
Values on all segments are consistent
GUC          : log_timezone
Master  value: PRC
Segment value: PRC

**Comment by Eulerizeit** [comment]
There is already a PR, https://github.com/greenplum-db/gpdb/pull/4646, in the master branch and it will be backported to 5.x_STABLE as soon as it is committed to the master branch.
