### ISSUE TITLE
[docs] Incorrect stop cmmand for stopping PXF 

### ISSUE THREAD

**Issue by kapustor** [greenplum-db/gpdb#4692]
In file gpdb/gpdb-doc/markdown/pxf/cfginitstart_pxf.html.md.erb stop command is actually start command, and the words about the upgrade are also incorrect, this chapter is only for stopping/starting:

## <a id="stop_pxf"></a>Stopping PXF

You must explicitly stop PXF on each segment host in your Greenplum Database cluster when you upgrade PXF. Only the `gpadmin` user can stop the PXF service.

Perform the following procedure to stop PXF on each segment host in your Greenplum Database cluster.  You will use the `gpssh` command and a `seghostfile` to run the command on multiple hosts.

1. Log in to the Greenplum Database master node and set up your environment:

    ``` shell
    $ ssh gpadmin@<gpmaster>
    gpadmin@gpmaster$ . /usr/local/greenplum-db/greenplum_path.sh
    ```

3. Run the `pxf start` command to start PXF on each segment host. For example, if `seghostfile` contains a list, one-host-per-line, of the segment hosts in your Greenplum Database cluster:

    ```shell
    $ gpadmin@gpmaster$ gpssh -e -v -f seghostfile "/usr/local/greenplum-db/pxf/bin/pxf start"
    ```

**Comment by lisakowen** [comment]
thank you for noticing this copy/paste error, @kapustor .  i pushed commits to open PR 4676 to correct the inconsistencies.
