### ISSUE TITLE
Is there any API to get the column(field) name in custom external protocol develop

### ISSUE THREAD

**Issue by licycode** [greenplum-db/gpdb#4699]
### Greenplum version or build
5.0 5.2. 5.3

When I execute a sql  like "insert into my_custom_external_table(name, age) select * from internal_test_table",  I need to convert the csv or text data into the "key-value" format, such as json.  eg: { "name":"James", "age":"20"}.
However, it seems that there isn't any APIs I can use to retrieve the column name(eg: "name", "age").
Is there any way to solve my problem?  Thanks a lot.

**Comment by lij55** [comment]
convert the format out of Greenplum and load json directly?

BTW, gpdb-users@greenplum.org would be a better option to ask such question.
