### ISSUE TITLE
What is operational skew at the query level?

### ISSUE THREAD

**Issue by Junvn** [greenplum-db/gpdb#4717]

**Comment by hsyuan** [comment]
What is the error/warning message?

**Comment by Junvn** [comment]
@hsyuan 最近在看gp 5.1 的官方文档，里面有一个查询级别的操作倾斜也会引起数据库内存溢出，我想问下什么是操作倾斜，不是很懂这个概念。

**Comment by lij55** [comment]
尽管原始没有数据倾斜，但在查询时也可能出现所有数据发往同一个Segment的情况，通常时join的条件导致的。
