### ISSUE TITLE
gpdb是否支持jsonb

### ISSUE THREAD

**Issue by shubifeng** [greenplum-db/gpdb#4722]

**Comment by Eulerizeit** [comment]
Google translate: "Does gpdb support jsonb?"

Not currently. We plan to support it for the next major release since it will also support GIN indexes which are required to make JSONB functional. 

The work has not yet been done.

**Comment by shubifeng** [comment]
@Eulerizeit thank you.
请问, MySQL 增量同步到 GPDB有什么好的工具?

**Comment by Eulerizeit** [comment]
Google translate: "Excuse me, what's a good tool for MySQL incremental synchronization to GPDB?"

I honestly don't know. You might want to try on the users group. I believe we have a Chinese language group. 

@yydzero  can you confirm a Chinese language users group and maybe share a link please?

**Comment by macroyuyang** [comment]
Hi, @shubifeng, you could search and join WeChat group "Greenplum 官方技术论坛二群“. There are a lot of users there

**Comment by shubifeng** [comment]
@macroyuyang I have not search  "Greenplum 官方技术论坛二群“ of WeChat account.

**Comment by macroyuyang** [comment]
@shubifeng What's your Wechat number? I think I could add you and pull you into that group

**Comment by shubifeng** [comment]
@macroyuyang Wechat number is "night0503" .
