### ISSUE TITLE
OperationalError: Can't start transaction

### ISSUE THREAD

**Issue by anubhav3itb** [greenplum-db/gpdb#4727]
I am running pgdb.connect to make a connection to my postgresql server and cursor to execute queries. For the first time (sometimes twice) it works properly but after that it gives me 

**OperationalError: Can't start transaction**
on cursor.execute(query)

Can someone please help me on how to solve this?

**Comment by asimrp** [comment]
Are you running PostgreSQL or Greenplum?  If it is Greenplum, master logs should have more information.  If it's PostgreSQL, please post the question to one of PostgreSQL mailing lists: https://www.postgresql.org/list/

**Comment by yydzero** [comment]
@anubhav3itb any comments on @asimrp 's question?

**Comment by ashwinstar** [comment]
Closing since didn't receive info to understand or resolve the issue. Please feel free to open new one against latest code is still facing the problem.
