### ISSUE TITLE
 GPOS header files are required for Pivotal Query Optimizer (orca)

### ISSUE THREAD

**Issue by fuyoucanghai** [greenplum-db/gpdb#4747]
### Step to reproduce the behavior

在编译gp5.6.0时报错如下：
configure: error: GPOS header files are required for Pivotal Query Optimizer (orca)
系统为centos7 mini版。

百度半天没有找到类似问题，github上倒是看见有一个，不过由于是github新手，完全看不懂。。诚意邀请大神帮忙排查下这个错误原因。问题解决后可以加qq  3126595722领红包。。

**Comment by paul-guo-** [comment]
What's you configure option? How do you install ORCA before running configure?

**Comment by d** [comment]
Hi @fuyoucanghai,
Thank you for your interest in trying out Greenplum Database! We are eager to help you, however, we need your help to make it possible for us to help you. Can you try including the details of the steps of action that led to the error?

As a bonus, I'd personally strongly recommend *against* that you use CentOS as a developer platform: it is highly hostile to developers, and you have to make changes to many *default* settings in RHEL/CentOS that are designed to make developing software harder. Use Ubuntu.
