### ISSUE TITLE
Refactor DML node into ModifyTable node 

### ISSUE THREAD

**Issue by Eulerizeit** [greenplum-db/gpdb#4755]
Before 9.0, ORCA produced DML nodes, but there was no equivalent node type in Postgres. INSERT/UPDATE/DELETE was handled with bespoken code, always logically at the top of the tree.  In 9.0 Postgres introduced the ModifyTable node which does more or less the same thing as the DML node. Currently DML nodes are produced by by ORCA, and ModifyTables are produced by the Postgres planner.

We would like to refactor that so that we get rid of the DML plan type, and use the upstream ModifyTable with ORCA. 

Since this work isn't blocking it is being captured as a ToDo item to be picked up by either a new contributor or by someone doing merge work when the work isn't parallelizable.

**Comment by d** [comment]
@Eulerizeit do we clearly know the feature gap between the two executor nodes? Won't we need to bring `ModifyTable` to parity with `DML` first?

**Comment by yydzero** [comment]
Is this already fixed as part of PG 9.0/9.1 merge?

**Comment by Eulerizeit** [comment]
@yydzero  This isn't currently in 9.0/9.1 merge. It is something that is a nice to have but not a blocker. 

@d I don't think anyone has actually specifically looked into the gap. This may or may not be possible but it seems reasonable.

**Comment by yydzero** [comment]
@Eulerizeit I labeled this as 'help_wanted' just in case there is community member want to take a bit tougher issue.

**Comment by Eulerizeit** [comment]
Perfect. I think we have a few of these, it might be nice to spend some
time to better spell out what is needed.

Rob

**Comment by ashwinstar** [comment]
This was completed by PR https://github.com/greenplum-db/gpdb/pull/9157
