### ISSUE TITLE
Converge the executor nodes on the PG implementation so we can benefit from all upstream changes. 

### ISSUE THREAD

**Issue by Eulerizeit** [greenplum-db/gpdb#4760]
Currently Greenplum leverages executor nodes that have near duplicates n Postgres. In order for us to most fully/easily benefit from the Postgres code updates we will converge the executor nodes where possible. 

Since this work isn't blocking it is being captured as a ToDo item to be picked up by either a new contributor or by someone doing merge work when the work isn't parallelizable.

**Comment by yydzero** [comment]
@Eulerizeit Could you please describe more about this? I could not understand the purpose of this issue.

**Comment by Eulerizeit** [comment]
@yydzero the purpose of this is to just generally look into any executor node that is specific to GPDB that has an implementation in Postgres. The thinking behind this is that the 9.x Postgres is all about improving an optimizing the executor, if we continue to use GPDB specific executor node then we don't benefit from those improvements. 

This is a more general version of the https://github.com/greenplum-db/gpdb/issues/4755 issue. It is a specific example of this issue.

**Comment by yydzero** [comment]
Got it, thanks

**Comment by ivannovick** [comment]
we will defer this work to a future time
