### ISSUE TITLE
Refactor to clean up resources such that they are not dependent on `ExecutorEnd`

### ISSUE THREAD

**Issue by Eulerizeit** [greenplum-db/gpdb#4761]
The problem is that we use `ExecutorEnd` to clean up stuff meaning we rely on it to prevent things from leaking. In Postgres they use resource handlers. We should not rely on `ExecutorEnd`. 

This will improve stability and reduce potential leaks. 

Since this work isn't blocking it is being captured as a ToDo item to be picked up by either a new contributor or by someone doing merge work when the work isn't parallelizable.

**Comment by yydzero** [comment]
@xiong-gang How is the refactor of dispatcher/interconnect related stuff to use resource owner mechanism over ExecutorEnd?

**Comment by xiong-gang** [comment]
Yes

**Comment by yydzero** [comment]
@xiong-gang shall we close this issue?
