### ISSUE TITLE
configure: error: GPOS header files are required for Pivotal Query Optimizer (orca)

### ISSUE THREAD

**Issue by liuyang2010001256** [greenplum-db/gpdb#4836]
configure: error: GPOS header files are required for Pivotal Query Optimizer (orca)

**Comment by asimrp** [comment]
@liuyang2010001256 have you installed Orca by following "Build the optimizer" section in [README.md](https://github.com/greenplum-db/gpdb/blob/master/README.md)?

If so, please provide steps so that we can reproduce your problem.

**Comment by vraghavan78** [comment]
@liuyang2010001256 please re-open the issue if you still face issues.
