### ISSUE TITLE
Unexpected exception reached top of execution stack: major=200 minor=9 file=CTranslatorScalarToDXL.cpp line=261",,,,,,,,"SysLoggerMain","syslogger.c",633

### ISSUE THREAD

**Issue by shubifeng** [greenplum-db/gpdb#4859]
### Greenplum version or build
5.4

### OS version and uname -a
centos

![default](https://user-images.githubusercontent.com/6796352/38800862-ea7eb318-419a-11e8-9f65-522815437598.png)

**Comment by bhuvnesh2703** [comment]
@shubifeng. This message is logged into GPDB as a LOG message, it is harmless. This message is originated by ORCA. Queries on catalog by default are run using planner, and this message suggests the same. (ORCA internally marks it as error but the query will execute successfully by planner)
