### ISSUE TITLE
missing guc gp_resgroup_memory_policy

### ISSUE THREAD

**Issue by mkiyama** [greenplum-db/gpdb#4886]
### Greenplum version or build
Greenplum Binary Version: 'postgres (Greenplum Database) 6.0.0-alpha.0+dev.5279.g8510131724 build commit:851013172450d1140f3db823a78058116a4e2baf-oss'

### OS version and uname -a
centos 7

on the master branch, the GUC gp_resgroup_memory_policy seems to be missing 

This commit seems to have removed it.
https://github.com/greenplum-db/gpdb/commit/5cc0ec507d

Is it available in the 5X_STABLE branch in 
src/backend/utils/misc/guc_gp.c

**Comment by pivotal-ning-yu** [comment]
We have opened PR https://github.com/greenplum-db/gpdb/pull/4891 to add this GUC back on master. It's available in 5X branch so nothing to do on 5X.

**Comment by professor** [comment]
Since the PR has been merged, I'm closing this issue.
