### ISSUE TITLE
initdb fail on armv7 

### ISSUE THREAD

**Issue by armgong** [greenplum-db/gpdb#4893]
### Greenplum version or build
both master and 5.X
### OS version and uname -a

Linux alarm 4.16.3-1-ARCH #1 SMP PREEMPT Sun Apr 22 01:10:52 UTC 2018 armv7l GNU/Linux

### Step to reproduce the behavior
build both master and 5.X greenplum on armv7 with 4GB memory  
make && make install ...OK
cd  gpAux/gpdemo/ 
make cluster  .....fail

Command /usr/local/gpdb/bin/initdb -E UNICODE -D /gpdata/datadirs/qddir/demoDataDir-1 --locale=en_US.utf8        --max_connections=150 --shared_buffers=128000kB --data-checksums --backend_output=/gpdata/datadirs/qddir/demoDataDir-1.initdb failed with error status 1, see log file /gpdata/datadirs/gpAdminLogs/gpinitsystem_20180424.log for more detail Script Exiting!

vacuuming database template1 ... 2018-04-24 16:32:17.545754 CST,,,p2184,th-1225743536,,,,0,,cmd2,seg-9    99,,,,sx1,"FATAL","22003","value out of range: underflow",,,,,"SQL statement ""select pg_catalog.sum(p    g_catalog.gp_statistics_estimate_reltuples_relpages_oid(c.oid))::pg_catalog.float4[] from pg_catalog.p    g_class c where c.oid=1260""","ANALYZE;
271 ",,"dtof","float.c",1092,

**Comment by armgong** [comment]
it seems is a bug in  initdb.c function vacumm

**Comment by asimrp** [comment]
> see following output ,the same sql run twice but got different result!!!

On the latest master, I'm consistently getting correct output.  Looks like the changes you've made are causing this behavior?

```SQL
postgres=# select version();
                                                                                                                version                                                                                                           
     
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-----
 PostgreSQL 9.0beta3 (Greenplum Database 6.0.0-alpha.0+dev.5295.g14cb86f8d4 build dev-oss) on x86_64-pc-linux-gnu, compiled by GCC gcc (Ubuntu 7.2.0-8ubuntu3.2) 7.2.0, 64-bit compiled on Apr 25 2018 11:48:10 (with assert check
ing)
(1 row)

postgres=# select sum(b) from (select Array[1,2,3] as b) as a;
   sum   
---------
 {1,2,3}
(1 row)
```

**Comment by armgong** [comment]
@yydzero  still no progress,  need further investigation  and compare with postgresql (which run ok on armv7), may be in July when summer vacation.

**Comment by paul-guo-** [comment]
Greenplum mainly focuses on and is tested on 64bit platforms. armv7 seems to be 32bit if I remember correctly, maybe you could try 64bit armv8 (I assume there has had product for the arch since a lot of years ago I've seen various low-level infrastrucure software change for the arch).

**Comment by armgong** [comment]
@pual-guo I have both armv7 (4GB memory) and armv8 (512 MB memory)board, , I afraid 512MB not enough for run greenplum

**Comment by hlinnaka** [comment]
No action on this. I'll close this, feel free to open a new issue if there is some concrete issue with armv8.

**Comment by phan-pivotal** [comment]
@armgong Hi, any update for ARM v8?

**Comment by armgong** [comment]
just buy one phicomm n1 ，it  is aarch64  ， will try run gpdb on it when OCT vaction , just wait a few day

**Comment by armgong** [comment]
Today build gpdb with ORCA on aarch64 , system is archlinuxarm with gcc 8.3 ,after slight modify , demo cluster successful run.
~~~bash
[armgong@alarm64 gpdemo]$ psql -d template1
psql (9.4.24)
Type "help" for help.

template1=# select version()
template1-# ;
                                                                                    version

--------------------------------------------------------------------------------------------------------------------------------------------------
-----------------------------
 PostgreSQL 9.4.24 (Greenplum Database 6.0.0+dev.106.g9eb508db6a build dev) on aarch64-unknown-linux-gnu, compiled by gcc (GCC) 8.3.0, 64-bit comp
iled on Sep 25 2019 03:04:30
(1 row)

template1=# select gp_opt_version();
                gp_opt_version
----------------------------------------------
 GPOPT version: 3.72.0, Xerces version: 3.1.2
(1 row)

template1=# select 1+1;
 ?column?
----------
        2
(1 row)

template1=#

~~~~
the only place need modify is gporca
~~~c
In file included from /home/armgong/gporca/libgpos/include/gpos/types.h:28,
                 from /home/armgong/gporca/libgpos/include/gpos/utils.h:18,
                 from /home/armgong/gporca/libgpos/src/common/CStackDescriptor.cpp:12:
/home/armgong/gporca/libgpos/src/common/CStackDescriptor.cpp: In member function 'void gpos::CStackDescriptor::BackTrace(gpos::ULONG)':
/home/armgong/gporca/libgpos/include/gpos/assert.h:47:67: error: size of array 'assert_array' is negative
 #define GPOS_CPL_ASSERT(x)  extern int assert_array[ (x) ? 1 : -1 ]
                                                                   ^
/home/armgong/gporca/libgpos/src/common/CStackDescriptor.cpp:167:2: note: in expansion of macro 'GPOS_CPL_ASSERT'
  GPOS_CPL_ASSERT(!"Backtrace is not supported for this platform");
  ^~~~~~~~~~~~~~~
/home/armgong/gporca/libgpos/include/gpos/assert.h:47:40: error: unused variable 'gpos::assert_array' [-Werror=unused-variable]
 #define GPOS_CPL_ASSERT(x)  extern int assert_array[ (x) ? 1 : -1 ]
                                        ^~~~~~~~~~~~
/home/armgong/gporca/libgpos/src/common/CStackDescriptor.cpp:167:2: note: in expansion of macro 'GPOS_CPL_ASSERT'
  GPOS_CPL_ASSERT(!"Backtrace is not supported for this platform");
  ^~~~~~~~~~~~~~~
~~~
I comment out only one in  libgpos/src/common/CStackDescriptor.cpp , this line will report  error: size of array 'assert_array' is negative 
~~~c

void
CStackDescriptor::BackTrace
        (
        ULONG
        )
{
        //GPOS_CPL_ASSERT(!"Backtrace is not supported for this platform");
}
~~~
if you would like know more detail , I will post it.
