### ISSUE TITLE
Extra objects of `pg_dump -s -t`

### ISSUE THREAD

**Issue by adam8157** [greenplum-db/gpdb#4909]
```
testdb=# CREATE FUNCTION myread() RETURNS integer
as '$libdir/gpextprotocol.so', 'demoprot_import'
LANGUAGE C STABLE;
CREATE FUNCTION
testdb=# CREATE FUNCTION mywrite() RETURNS integer
as '$libdir/gpextprotocol.so', 'demoprot_export'
LANGUAGE C STABLE;
CREATE FUNCTION
testdb=# CREATE TRUSTED PROTOCOL myprot ( readfunc = 'myread', writefunc = 'mywrite');
CREATE PROTOCOL
```

```
$ pg_dump -s -x -O --no-gp-syntax  -t schema2.foo2 testdb
--
-- Greenplum Database database dump
--

SET statement_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET client_min_messages = warning;

SET search_path = schema2, pg_catalog;

SET default_tablespace = '';

SET default_with_oids = false;

--
-- Name: foo2; Type: TABLE; Schema: schema2; Owner: -; Tablespace:
--

CREATE TABLE foo2 (
    i integer
);


--
-- Name: myprot; Type: PROTOCOL; Schema: -; Owner: -
--

-- Set the search_path required to look up the functions
SET search_path = public;

CREATE TRUSTED PROTOCOL myprot ( readfunc = 'myread', writefunc = 'mywrite');


--
-- Greenplum Database database dump complete
--
```

Why the protocol is dumped also? How could I get the dump of table's schema only?

**Comment by adam8157** [comment]
@khuddlefish could you please take a look?

**Comment by Eulerizeit** [comment]
@jchampio @danielgustafsson  I'm not sure if this is on your radar.

**Comment by khuddlefish** [comment]
@adam8157 Can we get an idea of how urgently you need this to be fixed? Is it blocking your team, or do you have a way to workaround it? Just helps to know when we are prioritizing the fix.

**Comment by adam8157** [comment]
@khuddlefish this would make a major functionality of our utility not working. For that functionality we don't have a workaround right now, we recommend users to `pg_dumpall` the whole schema but not tables' as a temporary solution.

Not only protocols, what `pg_dump` users want is "executing multiple dumped table schemas should not conflict".

**Comment by chrishajas** [comment]
@adam8157 Are there other issues you've seen beside protocols? pg_dump does make an effort to not dump objects such as procedural languages and other metadata during a table-only dump.

**Comment by adam8157** [comment]
@chrishajas I roughly checked the code, thought it would dump lots of other objects, turns out I was wrong. Have tested a table on the database left by ICW today, only protocols are unnecessary as my result.

**Comment by khuddlefish** [comment]
That is consistent with our understanding as well. Most objects have
functions to check when they should be dumped. The logic for the protocol
one seems to be wrong. This was added by us so it wouldn’t have been caught
by Postgres developers.

**Comment by khuddlefish** [comment]
PR for the fix is up https://github.com/greenplum-db/gpdb/pull/4979
