### ISSUE TITLE
gpaddmirror failed

### ISSUE THREAD

**Issue by lyb1985031** [greenplum-db/gpdb#495]
I'm adding mirrors to the exist system.But part failed(29/55),the reason is PG_CTL failed.
then i want to use gprecoverseg to get the failed mirror up.the i get Unable to connect to database

so,what should i do when gpaddmirror failed.I want to remove the mirrors and try once more,but don't know how? Or is there some way to get the failed mirrors up?

**Comment by lyb1985031** [comment]
part log:
20160309:17:06:38:014768 gpaddmirrors:server00:name-[WARNING]:-Failed to start segment.  The fault prober will shortly mark it as down. Segment: server02:/home/xxx/greenplum-db/mirror/datam10/gpseg15:content=15:dbid=66:mode=r:status=d: REASON: PG_CTL failed.

20160309:17:16:39:014768 gpaddmirrors:server00:name-[WARNING]:-Failed to inform primary segment of updated mirroring state.  Segment: server03:/home/xxxx/greenplum-db/data/data6/gpseg26:content=26:dbid=28:mode=r:status=u: REASON: Conversion failed.  stdout:""  stderr:"failure: Error: MirroringFailure failure: Error: MirroringFailure 

20160309:20:28:40:004963 gprecoverseg:server00:name-[INFO]:-Checking if segments are ready
20160309:20:28:40:004963 gprecoverseg:server00:name-[INFO]:-Obtaining Segment details from master...
20160309:20:28:42:004963 gprecoverseg:server00:name-[INFO]:-Unable to connect to database. Retrying 1

psql and program(insert data) works fine

**Comment by lyb1985031** [comment]
the reason mirror failed found which is sysctl config limit,but how can i remove the exists mirror and try once more. the gp_segment_configuration can not be update or delete even if in start -m mode.
gprecoverseg still Unable to connect to database

**Comment by wwang-pivotal** [comment]
semaphore is not set as GP required. 
closed

**Comment by lyb1985031** [comment]
I reinstall the cluster. But some strange things happens.
I hava two batch machines A and B.
A and B have primary segment runs fine.
A have each other mirrors(different machines)
B have empty mirror dir
what is the reason might be?

**Comment by lyb1985031** [comment]
All segments and master works.Here are my steps:
1.initsystem(2 machines) without standby master and mirrors
2.gpexpand add more machines and segments
3.gpaddmirrors
4.gpinitstandby

then all works.
And i don't know why...

**Comment by byxiangfei** [comment]
the same problem drives me crazy!!!

**Comment by byxiangfei** [comment]
oh  it's really about the   kernel.sem   in  /etc/sysctl.conf  not correctly set as suggested.
set kernel.sem = 250 512000 100 2048
and mirror set up quickly~
