### ISSUE TITLE
pg_dump/restore could not keep the column order

### ISSUE THREAD

**Issue by adam8157** [greenplum-db/gpdb#4955]
Hi, we find this issue on 5X_STABLE, below is the reproducer, please take a look?

## Create table f_star

```
CREATE TABLE a_star (
        class           char,
        a                       int4
);

CREATE TABLE b_star (
        b                       text
) INHERITS (a_star);

CREATE TABLE c_star (
        c                       name
) INHERITS (a_star);

CREATE TABLE d_star (
        d                       float8
) INHERITS (b_star, c_star);

CREATE TABLE e_star (
        e                       int2
) INHERITS (c_star);

CREATE TABLE f_star (
        f                       polygon
) INHERITS (e_star);

ALTER TABLE f_star RENAME COLUMN f TO ff;

ALTER TABLE e_star* RENAME COLUMN e TO ee;

ALTER TABLE d_star* RENAME COLUMN d TO dd;

ALTER TABLE c_star* RENAME COLUMN c TO cc;

ALTER TABLE b_star* RENAME COLUMN b TO bb;

ALTER TABLE a_star* RENAME COLUMN a TO aa;

ALTER TABLE f_star ADD COLUMN f int4;

ALTER TABLE e_star* ADD COLUMN e int4;

ALTER TABLE a_star* ADD COLUMN a text;
```
## How it looks

```
gpadmin=# \d f_star
       Table "public.f_star"
 Column |     Type     | Modifiers
--------+--------------+-----------
 class  | character(1) |
 aa     | integer      |
 cc     | name         |
 ee     | smallint     |
 ff     | polygon      |
 f      | integer      |
 e      | integer      |
 a      | text         |
Inherits: e_star
Distributed by: (class)
```

## Dump its schema

```
pg_dump -s -x -t public.f_star gpadmin
CREATE TABLE f_star (
    ff polygon,
    f integer
)
INHERITS (e_star) DISTRIBUTED BY (class);
```

## Create again with the dumped schema
```
gpadmin=# drop table f_star;
DROP TABLE
gpadmin=# CREATE TABLE f_star (
    ff polygon,
    f integer
)
INHERITS (e_star) DISTRIBUTED BY (class);
CREATE TABLE
```

## Its column order is different
```
gpadmin=# \d f_star;
       Table "public.f_star"
 Column |     Type     | Modifiers
--------+--------------+-----------
 class  | character(1) |
 aa     | integer      |
 cc     | name         |
 ee     | smallint     |
 e      | integer      |
 a      | text         |
 ff     | polygon      |
 f      | integer      |
Inherits: e_star
Distributed by: (class)
```

**Comment by adam8157** [comment]
@jchampio @danielgustafsson

@khuddlefish the `gpbackup` has same issue

**Comment by adam8157** [comment]
FYI, this f_star table comes from ICW

**Comment by chrishajas** [comment]
I believe this thread is related: https://postgrespro.com/list/thread-id/1230301#20140313043900.398.17129@wrigleys.postgresql.org. It doesn't seem like a consensus was reached in that thread, and I don't see any commits in upstream that may have changed the behavior.

**Comment by jchampio** [comment]
@chrishajas interesting. With the upstream behavior, shouldn't we see an order like 
```
gpadmin=# \d f_star;
       Table "public.f_star"
 Column |     Type     | Modifiers
--------+--------------+-----------
 class  | character(1) |
 aa     | integer      |
 a      | text         |
 cc     | name         |
 ee     | smallint     |
 e      | integer      |
 ff     | polygon      |
 f      | integer      |
Inherits: e_star
Distributed by: (class)
```
?

**Comment by chrishajas** [comment]
@jchampio Yes, you're correct.  I don't see an obvious commit that changed the order, but assuming GPDB didn't change the behavior it must exist somewhere. In any case, it seems like accepted behavior for the column order to be different for inherited tables. As long as we use named columns during COPY statements (which pg_dump and gp_backup do), this should be fine.

**Comment by yydzero** [comment]
@oakbarrett feel free to reassign if needed.

**Comment by ashwinstar** [comment]
@chrishajas @jchampio seems nothing to be fixed here and its behaving as expected? If that's the case lets close it if not let's mention what behavior is expected and then can pick for fixing later.

**Comment by jchampio** [comment]
Yep, seems like upstream is (or was, at the time of the version of Postgres we're based on) expecting some form of this behavior. Closing `WONTFIX`; please reopen if you disagree.
