### ISSUE TITLE
MyWalSnd->sendKeepalive is not set in code 

### ISSUE THREAD

**Issue by yydzero** [greenplum-db/gpdb#4964]
MyWalSnd->sendKeepalive is used in walsender.c while no code has set it.

src//backend/replication/walsender.c:			else if (MyWalSnd->sendKeepalive

**Comment by yydzero** [comment]
@asimrp @ashwinstar could we remove sendKeepalive? if not what is its purpose?

Thanks!

**Comment by asimrp** [comment]
Thank you for spotting this, @yydzero.  Keep alive / heartbeat feature looks different in 9.3 from what we have.  `src/backend/replication` needs to be brought in sync with upstream at some point.

We seem to have the commit that introduced `WalSnd->sendKeepalive` but not the commit that removed it.

It was introduced in:
```
commit da4efa13d801ccc179f1d2c24d8a60c4a2f8ede9
Author: Simon Riggs <simon@2ndQuadrant.com>
Date:   Thu Aug 9 17:07:03 2012 +0100

    Turn off WalSender keepalives by default, users can enable if desired
```

And removed in:
```
commit 6f60fdd7015b032bf49273c99f80913d57eac284
Author: Heikki Linnakangas <heikki.linnakangas@iki.fi>
Date:   Thu Oct 11 17:39:52 2012 +0300

    Improve replication connection timeouts.

    Rename replication_timeout to wal_sender_timeout, and add a new setting
    called wal_receiver_timeout that does the same at the walreceiver side.
    There was previously no timeout in walreceiver, so if the network went down,
    for example, the walreceiver could take a long time to notice that the
    connection was lost. Now with the two settings, both sides of a replication
    connection will detect a broken connection similarly.

    It is no longer necessary to manually set wal_receiver_status_interval to
    a value smaller than the timeout. Both wal sender and receiver now
    automatically send a "ping" message if more than 1/2 of the configured
    timeout has elapsed, and it hasn't received any messages from the other end.

    Amit Kapila, heavily edited by me.
```

**Comment by d** [comment]
This field is actually implicitly initialized to `false` given the `memset` on L 1272 in https://github.com/greenplum-db/gpdb/blob/ac74f825f695721dceb263cc32548714277bc229/src/backend/replication/walsender.c#L1260-L1286
