### ISSUE TITLE
gpconfig -s shared_preload_libraries causes "not supported in DXL" error

### ISSUE THREAD

**Issue by funcode** [greenplum-db/gpdb#4980]
### Greenplum version or build
Greenplum Binary Version: 'postgres (Greenplum Database) 5.8.0+dev.26.g9570bb9ef3 build commit:9570bb9ef3eda60acabb8fd4c4359705fb92473d'
(from bin_gpdb_sles11_icw_green from 5X_STABLE)

### OS version and uname -a
SLES 12

### autoconf options used ( config.status --config )
Same as bin_gpdb_sles11_icw_green from 5X_STABLE pipeline, includes "optimizer=on"

### Step to reproduce the behavior
```sql
gpconfig -s shared_preload_libraries
Values on all segments are consistent
GUC          : shared_preload_libraries
Master  value:
Segment value:
```

Produces a weird LOG/ERROR message in pg_log, but seems to work.
> gpdb-2018-05-14_042400.csv:2018-05-14 04:25:05.135524 UTC,"gpadmin","template1",p1134,th1429096256,"::1","32858",2018-05-14 04:25:05 UTC,0,con12,cmd7,seg-1,,dx8,,sx1,"LOG","00000","2018-05-14 04:25:05:135160 UTC,THD000,ERROR,""GPDB Expression type: {PARAM :paramkind 0 :paramid 1 :paramtype 1043 :paramtypmod -1} not supported in DXL"",",,,,,"SQL function ""__gp_param_local_setting"" during startup

- @amilkh and @funcode

**Comment by vraghavan78** [comment]
This is a fallback message. When Orca does not support it throws an error and fallsback to planner. This expected behavior.
