### ISSUE TITLE
Setting vacuum_defer_cleanup_age causes assertion failure in DistributedLog_GetOldestXmin

### ISSUE THREAD

**Issue by jchampio** [greenplum-db/gpdb#4984]
In the GPDB master branch, the following assertion is tripped when using a large value of `vacuum_defer_cleanup_age`:

```
TransactionId
DistributedLog_GetOldestXmin(TransactionId oldestLocalXmin)
{
    ...
    Assert(TransactionIdFollowsOrEquals(oldestLocalXmin, result));
```

You can `gpconfig -c vacuum_defer_cleanup_age -v 1000000`, restart the database, then run ICW to reproduce.

**Comment by yydzero** [comment]
@Eulerizeit think it is yours, feel free to reassign if not.

Also I am trying to add help_wanted label for most of issues, so that community could help on it also.

**Comment by ivannovick** [comment]
is it still an issue @linwen ?

**Comment by dpandhi-git** [comment]
@huansong can you verify if it is  still a issue?

**Comment by dpandhi-git** [comment]
with @ashwinstar commit a3e0f96bc3defe3987c1610a83bf16579af9b27a removed this assertion
