### ISSUE TITLE
Refactor Makefile for regression tests

### ISSUE THREAD

**Issue by ascherbaum-pivotal** [greenplum-db/gpdb#499]
Like upstream, the regression tests should be executed using "make check" in the main directory. "make installcheck-good" seems to be a legacy of too many new test systems added to GPDB.
Also "make check" should start and stop the cluster required to run the regression tests.

**Comment by danielgustafsson** [comment]
As mentioned on off-thread, the ability to reuse an already running cluster is quite handy since startup/teardown isn't exactly an instant operation (at least not today with `make cluster`). The default can be to setup/teardown but an override would be good; like `REUSE_CLUSTER=1 make check` or something similar.

**Comment by hlinnaka** [comment]
On 09/03/16 20:29, Daniel Gustafsson wrote:
> As mentioned on off-thread, the ability to reuse an already running
> cluster is quite handy since startup/teardown isn't exactly an
> instant operation (at least not today with `make cluster`). The
> default can be to setup/teardown but an override would be good; like
> `REUSE_CLUSTER=1 make check` or something similar.

PostgreSQL has "make installcheck-parallel" for that. There are three
targets:

# Create a cluster, run the tests in parallel
make check
# Run the tests in serial, against an already-running cluster
make installcheck
# Run the tests in parallel, against an already-running cluster
make installcheck-parallel

I think we should adopt the the same makefile targets. And we can keep 
"installcheck-good" as an alias for "installcheck-parallel" for eternity.

- Heikki

**Comment by danielgustafsson** [comment]
:+1: on that suggestion

**Comment by ivannovick** [comment]
Is this issue going anywhere?

**Comment by Eulerizeit** [comment]
I think it has gone about as far as it is going to go with ICW.

Rob

**Comment by danielgustafsson** [comment]
I'm fine with closing this given the work that has been put in since.
