### ISSUE TITLE
Tablefunc is not supported in greenplum

### ISSUE THREAD

**Issue by sunnn** [greenplum-db/gpdb#4990]
### sandbox used

Why is tablefunc function of postgresql is not supported in greenplum as it is very useful while creating columnary transformations

**Comment by yydzero** [comment]
maybe try with master?

**Comment by sunnn** [comment]
@yydzero can you tell me how to do that as only uninstall file is available but not install file

**Comment by yydzero** [comment]
@sunnn you could build Greenplum from source code by following instructions at https://github.com/greenplum-db/gpdb

**Comment by ashwinstar** [comment]
Added feature tag to this issue, currently even in master contrib module tablefunc is not compiled. Might also need to see if required to make those functions MPP.

**Comment by sunnn** [comment]
@yydzero  i tried to compile the code for tablefunc but i get the below errors
![image](https://user-images.githubusercontent.com/3184992/44306366-fbdafa00-a3aa-11e8-97da-7e27265b5da3.png)

**Comment by sunnn** [comment]
@berlin-ab  hey is it by chance scheduled for GPDB6 ??

**Comment by berlin-ab** [comment]
I’m not sure. I’ll check in with some folks on Tuesday (Monday is a holiday in the US).

**Comment by skahler-pivotal** [comment]
*Note* that if you are using the sandbox, the sandbox as provided by Pivotal isn't setup to build Greenplum and you would need to install additional packages in order to make that successful.

**Comment by sunnn** [comment]
can anyone guide me through the process building the .so file from start @berlin-ab

**Comment by sunnn** [comment]
Can anyone let me know are we moving forward on this or it will be left

**Comment by Eulerizeit** [comment]
@wuj21  would be the person deciding on this. 

This might be a good and interesting topic to pick up if you are interested in making it work.

**Comment by JunfengYang** [comment]
Test on the current Master branch, the `contrib/tablefunc` module is supported now.
