### ISSUE TITLE
make install failed after configure --enable-gphdfs

### ISSUE THREAD

**Issue by vitesse-ftian** [greenplum-db/gpdb#4995]
### Greenplum version or build
5x

### OS version and uname -a
ubuntu16

### autoconf options used ( config.status --config )
--enable-gphdfs

### Step to reproduce the behavior

After enable-gphdfs, make install will fail.   make will try to create /docs dir and fail with permission.   A quick looks indicates $(INSTLOC) is not set -- I don't know much about this variable and wonder when/where should it be set.   

But I believe it should be set by upper level makefile.   And I feel a little bit nervous.  There are many shell command using $(INSTLOC), if not set, sudo make install (for example to install into /usr/local) can potentially wipe out the machine.

**Comment by berlin-ab** [comment]
@kongyew @lavjain Should this be in PXF now?

**Comment by ivannovick** [comment]
gphdfs is deprecated
