### ISSUE TITLE
make error, undefined reference to `readable_external_table_timeout'

### ISSUE THREAD

**Issue by digoal** [greenplum-db/gpdb#50]
#git log
commit b80a01e90a42db4a8918801c6f070c8f55a6c23e
Author: Heikki Linnakangas <hlinnakangas@pivotal.io>
Date:   Thu Nov 5 00:20:11 2015 +0200

    Remove useless 'initdb' bugbuster test

./configure --prefix=/opt/gpdb --without-libcurl
make error

gmake[3]: Leaving directory `/opt/soft_bak/gpdb/src/backend/cdb'
g++ -O3 -std=gnu99  -Wall -Wmissing-prototypes -Wpointer-arith -Wendif-labels -Wformat-security -fno-strict-aliasing -fwrapv -Wno-unused-but-set-variable -Wno-address -L../../src/port -L../../src/port -Wl,--as-needed -Wl,-rpath,'/opt/gpdb/lib',--enable-new-dtags -Wl,-E access/SUBSYS.o bootstrap/SUBSYS.o catalog/SUBSYS.o parser/SUBSYS.o commands/SUBSYS.o executor/SUBSYS.o foreign/SUBSYS.o fts/SUBSYS.o lib/SUBSYS.o libpq/SUBSYS.o gp_libpq_fe/SUBSYS.o main/SUBSYS.o nodes/SUBSYS.o optimizer/SUBSYS.o port/SUBSYS.o postmaster/SUBSYS.o regex/SUBSYS.o replication/SUBSYS.o rewrite/SUBSYS.o storage/SUBSYS.o tcop/SUBSYS.o utils/SUBSYS.o ../../src/timezone/SUBSYS.o cdb/SUBSYS.o ../../src/port/libpgport_srv.a -lbz2 -lrt -lz -lcrypt -ldl -lm -lpthread -o postgres
utils/SUBSYS.o:(.data+0xaab0): undefined reference to `readable_external_table_timeout'
collect2: ld returned 1 exit status
gmake[2]: *** [postgres] Error 1
gmake[2]: Leaving directory `/opt/soft_bak/gpdb/src/backend'
gmake[1]: *** [all] Error 2
gmake[1]: Leaving directory `/opt/soft_bak/gpdb/src'
gmake: *** [all] Error 2

**Comment by hlinnaka** [comment]
Fixed, thanks for the report! The "readable_external_table_timeout" was erroneously inside an ifdef USE_CURL block, even though it's also needed when building without libcurl.
