### ISSUE TITLE
Assertion failure from bfv_legacy test

### ISSUE THREAD

**Issue by hlinnaka** [greenplum-db/gpdb#500]
This query from the 'bfv_legacy' regression test trips an assertion:

postgres=# select * from mpp_t1 where a = (select a FROM mpp_t2 where mpp_t2.b > (select max(b) from mpp_t3 group by b) and mpp_t2.b=1 and mpp_t2.b=2);
ERROR:  Unexpected internal error (nodeSubplan.c:764)  (seg1 slice1 localhost:40001 pid=21327) (cdbdisp.c:1326)
DETAIL:  FailedAssertion("!(((bool) ((prmExt->ptype) != ((Oid) 0))) && "Invalid Oid for pre-evaluated parameter.")", File: "nodeSubplan.c", Line: 764)
ERROR:  could not temporarily connect to one or more segments (cdbgang.c:2472)

**Comment by hlinnaka** [comment]
Sorry, this is from the 'bfv_subquery' regression test, not 'bfv_legacy'.

**Comment by danielgustafsson** [comment]
@hlinnaka was this fixed with #807 so this can be closed?

**Comment by hlinnaka** [comment]
Yeah, I guess so, closed
