### ISSUE TITLE
Performance of ICW case 'subselect' vary widely from ORCA to legacy  planner

### ISSUE THREAD

**Issue by pengzhout** [greenplum-db/gpdb#5002]
### Greenplum version or build
latest master

With ORCA=off, subselect take 1.9s on ci pipeline, however, it takes 43s on when ORCA is on.

the main difference is introduced by the query:
```
select * from int4_tbl where
  (case when f1 in (select unique1 from tenk1 a) then f1 else null end) in
  (select ten from tenk1 b);
```

@vraghavan78 is it a known issue?

**Comment by vraghavan78** [comment]
@pengzhout thank you for pointing this out. @dhanashreek89 can we look into it?

**Comment by pengzhout** [comment]
@vraghavan78 issue still exists and also found test case 'errors' vary from 0.56s to 67s.
