### ISSUE TITLE
Comment on resource queue fails

### ISSUE THREAD

**Issue by chrishajas** [greenplum-db/gpdb#5027]
### Greenplum version or build
PostgreSQL 9.1beta2 (Greenplum Database 6.0.0-alpha.0+dev.7177.g958a672a74 build dev-oss) on x86_64-apple-darwin17.5.0, compiled by Apple LLVM version 9.1.0 (clang-902.0.39.1), 64-bit compiled on May 21 2018 09:59:11

### OS version and uname -a
Repros on Mac and Centos

### Expected behavior
Comment succeeds (last known working commit was 09b07657655d1b330c392c80cceb00fd0a21fd46), a day before the 9.1 merge.
### Actual behavior
`ERROR:  unrecognized objtype: 35 (objectaddress.c:237)`

### Step to reproduce the behavior

```
CREATE RESOURCE QUEUE rsq WITH (ACTIVE_STATEMENTS=7);
COMMENT ON RESOURCE QUEUE rsq IS 'This is a resource queue comment.';
```
Returns:
```
ERROR:  unrecognized objtype: 35 (objectaddress.c:237)
```
Stack trace:
```
1    0x1061af1e3 postgres errstart + 0x303
2    0x1061b2aed postgres elog_finish + 0xcd
3    0x105e370a2 postgres get_object_address + 0x992
4    0x105eaf738 postgres CommentObject + 0x68
5    0x1060a38ce postgres PortalRunUtility + 0xae
6    0x1060a2ee4 postgres PortalRunMulti + 0x1f4
7    0x1060a2748 postgres PortalRun + 0x1c8
8    0x1060a0e4d postgres exec_simple_query + 0x6cd
9    0x10609e11e postgres PostgresMain + 0x2a6e
10   0x10604500b postgres PostmasterMain + 0x221b
11   0x105f9cf7c postgres main + 0x37c
12   0x7fff6f43b015 libdyld.dylib start + 0x1
13   0xa 0x0000000a (in postgres)
```
This was found on the gpbackup integration pipeline, but we should add a test to ICW.

**Comment by khuddlefish** [comment]
@jchampio @danielgustafsson Do you have any idea who should work on this since it came in with a merge?

**Comment by jchampio** [comment]
@khuddlefish Any of the Postgres team should be able to hop onto it. @Eulerizeit FYI

**Comment by Eulerizeit** [comment]
@paul-guo- @guofengrichard @baobao0206 could one of you pick this up please? 

@chrishajas where is the CI this is failing in? Is it open so you could link it here?

**Comment by danielgustafsson** [comment]
Took a stab at fixing this in #5070, let's see what the pipeline thinks about that.

**Comment by chrishajas** [comment]
@Eulerizeit The CI is here: https://gpdb.bosh.pivotalci.info/teams/main/pipelines/gpbackup/jobs/integrations-master/builds/4 (it's not open to the public though). 

The repro reliably replicates the issue.

**Comment by danielgustafsson** [comment]
> On 30 May 2018, at 16:37, Chris Hajas <notifications@github.com> wrote:
> 
> @Eulerizeit The CI is here: https://gpdb.bosh.pivotalci.info/teams/main/pipelines/gpbackup/jobs/integrations-master/builds/4 (it's not open to the public though).
> 
> The repro reliably replicates the issue.

Can you test if my proposed fix solves the issue in that pipeline?

**Comment by chrishajas** [comment]
Fixed in https://github.com/greenplum-db/gpdb/commit/ace7a3e9298f241a7c0aa2ebe5c5d2a4df399ea6.
