### ISSUE TITLE
RETURNING failed on reorganized temp table

### ISSUE THREAD

**Issue by pivotal-ning-yu** [greenplum-db/gpdb#5051]
### Greenplum version or build

PostgreSQL 9.1beta2 (Greenplum Database 6.0.0-alpha.0+dev.7176.g25a90396cd build dev-oss) on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-16), 64-bit compiled on May 28 2018 13:46:34 (with assert checking)

### OS version and uname -a

```bash
$ cat /etc/redhat-release
CentOS Linux release 7.3.1611 (Core)

$ uname -a
Linux nyu-vm-centos 3.10.0-327.28.2.el7.x86_64 #1 SMP Wed Aug 3 11:11:39 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

### autoconf options used ( config.status --config )

```bash
$ ./config.status --config
'--cache-file=../config-gpdb.cache' '--with-python' '--with-perl' '--enable-mapreduce' '--disable-orca' '--with-libxml' '--with-openssl' '--disable-codegen' '--disable-gpcloud' '--enable-debug' '--enable-cassert' '--enable-dtrace' '--enable-depend' '--prefix=/home/gpadmin/opt/gpdb' 'CFLAGS=-O0 -g' 'CXXFLAGS=-O0 -g'
```

### Installation information ( pg_config )

```bash
$ pg_config
BINDIR = /home/gpadmin/opt/gpdb/bin
DOCDIR = /home/gpadmin/opt/gpdb/share/doc/postgresql
HTMLDIR = /home/gpadmin/opt/gpdb/share/doc/postgresql
INCLUDEDIR = /home/gpadmin/opt/gpdb/include
PKGINCLUDEDIR = /home/gpadmin/opt/gpdb/include/postgresql
INCLUDEDIR-SERVER = /home/gpadmin/opt/gpdb/include/postgresql/server
LIBDIR = /home/gpadmin/opt/gpdb/lib
PKGLIBDIR = /home/gpadmin/opt/gpdb/lib/postgresql
LOCALEDIR = /home/gpadmin/opt/gpdb/share/locale
MANDIR = /home/gpadmin/opt/gpdb/share/man
SHAREDIR = /home/gpadmin/opt/gpdb/share/postgresql
SYSCONFDIR = /home/gpadmin/opt/gpdb/etc/postgresql
PGXS = /home/gpadmin/opt/gpdb/lib/postgresql/pgxs/src/makefiles/pgxs.mk
CONFIGURE = '--cache-file=../config-gpdb.cache' '--with-python' '--with-perl' '--enable-mapreduce' '--disable-orca' '--with-libxml' '--with-openssl' '--disable-codegen' '--disable-gpcloud' '--enable-debug' '--enable-cassert' '--enable-dtrace' '--enable-depend' '--prefix=/home/gpadmin/opt/gpdb' 'CFLAGS=-O0 -g' 'CXXFLAGS=-O0 -g'
CC = gcc
CPPFLAGS = -D_GNU_SOURCE -I/home/gpadmin/opt/gpdb/include
CFLAGS = -O0 -g -std=gnu99 -Wall -Wmissing-prototypes -Wpointer-arith -Wendif-labels -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fno-aggressive-loop-optimizations -Wno-unused-but-set-variable -Wno-address -g -ggdb -Werror=uninitialized -I/home/gpadmin/opt/gpdb/include
CFLAGS_SL = -fpic
LDFLAGS = -Wl,--as-needed -Wl,-rpath,'/home/gpadmin/opt/gpdb/lib',--enable-new-dtags -L/home/gpadmin/opt/gpdb/lib
LDFLAGS_EX =
LDFLAGS_SL =
LIBS = -lpgport -lxml2 -lrt -lcrypt -ldl -lm -L/home/gpadmin/opt/gpdb/lib
VERSION = PostgreSQL 9.1beta2
```

### Expected behavior

`RETURNING` should work on a reorganized temp table.

### Actual behavior

`RETURNING` failed on a reorganized temp table.

### Step to reproduce the behavior

```sql
create temp table t1 (c1 int, c2 int) distributed by (c1); -- OLD
alter table t1 set distributed by (c2); -- NEW
insert into t1 values(1,1) returning *;
```

Here OLD and NEW indicate the old and new distribution policies. We also verified other `<OLD, NEW>` pairs, such as `<replicated, by (c1)>`, `<randomly, by (c1)>`, etc., the only pair that does not fail is `<by (c1), randomly>` as it's not reorganized at all, all the other pairs fail with below error:

```
ERROR:  could not open file "base/13360/t_16387": No such file or directory  (seg0 slice1 192.168.99.102:25432 pid=19711)
```

This issue only happens on temp tables.

**Comment by pivotal-ning-yu** [comment]
This issue was originally triggered when we merged https://github.com/greenplum-db/gpdb/pull/5038. Due to this issue we have reverted that PR, and we should remerge that PR once this issue gets fixed.

**Comment by Eulerizeit** [comment]
This surfaced when you tried to implement RETURNING for replicated tables?

Currently RETURNING doesn't work for everything, sounds like we need to fix
it up and add some tests.

Rob

**Comment by pivotal-ning-yu** [comment]
@Eulerizeit +1, currently there is test case `returning.sql` in ICW, but it only covers the `<by (c1), randomly>` case, which is the only case that won't fail on this issue.

**Comment by pivotal-ning-yu** [comment]
In fact `RETURNING` is not the key to trigger this issue, once a temp table is reorganized even a simple `SELECT * from t1` would also fail.

**Comment by pivotal-ning-yu** [comment]
The PR was merged just now, close this issue.
