### ISSUE TITLE
Tens of billions of data incremental tidb storage problems

### ISSUE THREAD

**Issue by 444728248** [greenplum-db/gpdb#5056]
At present, the data is incrementally increased by several billion per day, and the business database needs to provide the corresponding second level, which involves join, count, order by operation.
Tidb suits？

**Comment by d** [comment]
Did you really mean to ask the Greenplum community [a question about TiDB](https://github.com/pingcap/tidb/issues/6663)?? Given that you've gone ahead and filed a complete duplicate in pingcap/tidb#6663 I'm closing this for you.

Thank you,
Jesse
