### ISSUE TITLE
Intermittent failure in 'gpinitsystem', 'segspace*', 'fts_recovery_in_progress' who called gpstop

### ISSUE THREAD

**Issue by pengzhout** [greenplum-db/gpdb#5065]
### Greenplum version or build
latest master

### OS version and uname -a
I hit job 'gpinitsystem' and 'segspace*' failed multiple times due to gpstart or gpstop failed during those cases.

gpstart and gpstop use pg_ctl to start and stop a postgres process, it assumes postgres process will create  a file named 'postmaster.pid' within 5 seconds, but it not always true in a high workload machine like our pipeline machines. 

Upstream had a commit 6bcce25801c3fcb219e0d92198889ec88c74e2ff to address it, a quote from the commit
```
pg_ctl start with -w previously relied on a heuristic that the postmaster
    would surely always manage to create postmaster.pid within five seconds.
    Unfortunately, that fails much more often than we would like on some of the
    slower, more heavily loaded buildfarm members.
```

Created this to track the issue and help identifying similar failure quicker.

**Comment by ashwinstar** [comment]
We have the mentioned commit in GPDB6 and forward, hence closing the issue as fixed.
