### ISSUE TITLE
Tens of billions of data incremental gpdb storage problems

### ISSUE THREAD

**Issue by 444728248** [greenplum-db/gpdb#5066]
At present, the data is incrementally increased by several billion per day, and the business database needs to provide the corresponding second level, which involves join, count, order by operation.
Tidb suits？

**Comment by hsyuan** [comment]
TiDB is OLTP database. If its query performance meets your requirement, then that's it. Otherwise, use HAWQ if you don't want to redistribute your data when adding new segments.

**Comment by d** [comment]
Hi,
Thank you for you interest in Greenplum!
Did you really mean to ask the Greenplum community [a question about TiDB](https://github.com/pingcap/tidb/issues/6663)?? Given that you've gone ahead and filed a complete duplicate in pingcap/tidb#6663 I'm closing this for you.

Thank you,
Jesse
