### ISSUE TITLE
Missing --with-python fails regression tests

### ISSUE THREAD

**Issue by andreasscherbaum** [greenplum-db/gpdb#507]
The README specifies only one ./configure option: --prefix
However if --with-python is not specified, the regression tests fail:

```
*** ./expected/union_gp.out     2016-03-10 20:12:45.805013261 +0100
--- ./results/union_gp.out      2016-03-10 20:12:45.913012968 +0100
***************
*** 219,224 ****
--- 219,225 ----
  CREATE TABLE T_random (c1 int, c2 int);
  INSERT INTO T_random SELECT i, i%5 from generate_series(1,30) i;
  create language plpythonu;
+ ERROR:  could not access file "$libdir/plpython": No such file or directory
  create or replace function count_operator(explain_query text, operator text) returns int as
  $$
  rv = plpy.execute(explain_query)
***************
*** 231,236 ****
--- 232,239 ----
  return result
  $$
  language plpythonu;
+ ERROR:  language "plpythonu" does not exist
+ HINT:  Use CREATE LANGUAGE to load the language into the database.
```

**Comment by hsyuan** [comment]
The regression test use PL/Python modules to execute some tests. Maybe we need to add addtional configure instruction on how to run  regression tests. the same with other `--with-perl`, `--enable-mapreduce` configure flag.

**Comment by andreasscherbaum** [comment]
I have no problem with making Python a hard dependency.

But if that is the case, it a) must be documented and b) ./configure must fail if it is not specified.

A new developer, trying to build GPDB for the first time, will run into this problem.

**Comment by hlinnaka** [comment]
Updated README. I think that's good enough for now.
