### ISSUE TITLE
missing doc for create external temp table

### ISSUE THREAD

**Issue by hli1992** [greenplum-db/gpdb#5076]
I have seen that the latest gpdb (5X_STABLE) supports syntax
> create external temp table 

 in gram.y:
```

CreateExternalStmt:	CREATE OptWritable EXTERNAL OptWeb OptTemp TABLE qualified_name '(' OptExtTableElementList ')' 
					ExtTypedesc FORMAT Sconst format_opt ext_options_opt ext_opt_encoding_list OptSingleRowErrorHandling OptDistributedBy
						{
							CreateExternalStmt *n = makeNode(CreateExternalStmt);
							n->iswritable = $2;
							n->isweb = $4;
							$7->istemp = $5;
　　　　　　　　　　　　　　　....
```
but [the official doc](http://gpdb.docs.pivotal.io/580/ref_guide/sql_commands/CREATE_EXTERNAL_TABLE.html) could not find about temp external table.

**Comment by lij55** [comment]
Thanks @hli1992 .

I run some basic tests for 'external temp table' and it works as expected:
* table is dropped after session ending
* It can work as external table 

It looks we need to add this to document if it can work well. @dyozie @mkiyama @BrianPivotal

**Comment by BrianPivotal** [comment]
Document is updated. Thanks.

Best Regards,
Brian
