### ISSUE TITLE
Greenplum 6 cannot import a file with non-UTF8 encoding

### ISSUE THREAD

**Issue by divyabhargov** [greenplum-db/gpdb#5085]
### Greenplum version or build
6.0.0 alpha

### OS version and uname -a
Tested on Centos 6, but its possible that it exists on others.

### Installation information ( pg_config )
Used default demo cluster

### Expected behavior
A select from the external table should bring the results from the file. This is working ok on GPDB 5.

### Actual behavior
An exception is raised - "ERROR:  invalid byte sequence for encoding "UTF8": 0xe12073"

### Step to reproduce the behavior
Contents of test_utf8.csv file: 
```
3, d'automation
4,tá sé seo le tástáil dea-
5,minden amire szüksége van a szeret
```
Make sure the above file is in ISO-8859 format.
I used iconv to achieve this:
```
iconv /external/test_utf8.csv -f UTF-8 -t ISO-8869-1 -o /external/test_iso8869.csv
```

Create an external table with LATIN1 encoding that refers to the above file:
```
create external table encoding_issue (num1 int,word text)
location ('file://<hostname>:5432/external/test_iso8869.csv')
          FORMAT 'CSV'
          ENCODING 'LATIN1';
```

Now selecting from this external table (encoding_issue) causes the exception "ERROR:  invalid byte sequence for encoding "UTF8": 0xe12073"

```sql
SELECT * FROM encoding_issue;
```

As a bonus, the following `COPY` statement won't work either:

```sql
COPY (select * from encoding_issue) to '/tmp/encode.tmp' with (format 'csv',  encoding 'LATIN1');
```

The same case was tested and verified to work on Greenplum 5.7

**Comment by Eulerizeit** [comment]
@schubert @ivannovick @pivotal-mike 

In the 9.1 merge we have tried to clean up the `COPY` code. This issue is caused by that clean up and the fact that we are leveraging the `COPY` function as an external API to be used for things like External Tables. 

2 options:

1. Hack a fix around the `COPY` functionality until the FDW API lands solidly after the current merge iteration and then remember to remove it. 
1. Leave this functionality broken and the `COPY` code clean and have teams stop leveraging `COPY` and start using a proper API.

**Comment by sunnn** [comment]
Try to check for the python function which converts the file into utf8 in
greenplum db

**Comment by d** [comment]
1. We left a gap during the refactoring, and left a FIXME in
    https://github.com/greenplum-db/gpdb/blob/c8f6891d08206b6914b197e31a84c34e22c9a8d0/src/backend/access/external/fileam.c#L1253-L1254

1. The refactoring in `COPY` related code was motivated to support `file_fdw` in upstream commit postgres/postgres@8ddc05fb01ee2c423bf5613426726351e860d4b4

1. @tvesely and I previously tried two different approaches:
    1. either we jam the encoding into "format options", and eliminate `pg_exttab.encoding`
    1. or we keep the `pg_exttab.encoding`, and remember to append the encoding to the format options before calling the relevant copy code (e.g. `BeginCopyFrom` and friends)

1. The reason we commented out the following
    https://github.com/greenplum-db/gpdb/blob/c8f6891d08206b6914b197e31a84c34e22c9a8d0/src/backend/access/external/fileam.c#L1254

    is because `CopyState::client_encoding` has been absorbed into `options` in `BeginCopyFrom`, and removed from `CopyState`

1. @tvesely and I had a (actually two) WIP thrown into a branch here https://github.com/tvesely/gpdb/tree/encoding_fixes

**Comment by Eulerizeit** [comment]
@adam8157 @divyabhargov separate from this issue, Could we please add tests somewhere into the master CI so that we can more quickly/easily make sure we don't break this again in the merge process or in any of the other messing with this code?

**Comment by adam8157** [comment]
Has a temporary solution now
```
gpadmin=# SELECT * FROM encoding_issue;
 num1 |                word
------+------------------------------------
    3 |  d'automation
    4 | tá sé seo le tástáil dea-
    5 | minden amire szüksége van a szeret
(3 rows)
```

**Comment by adam8157** [comment]
Please help reviewing, I'm not sure if I have missed something.
