### ISSUE TITLE
Missing --enable-mapreduce still runs all the regression tests for mapreduce

### ISSUE THREAD

**Issue by andreasscherbaum** [greenplum-db/gpdb#510]
#434 introduces a new ./configure flag: --enable-mapreduce

If this flag is not specified, all the mapreduce regression tests are still run - and fail.

```
*** ./expected/mapred.out       2016-03-10 21:51:45.684137637 +0100
--- ./results/mapred.out        2016-03-10 21:51:45.696137593 +0100
***************
*** 243,397 ****
  -- TEST 1) complain about missing file
  --
  SELECT mapreduce('nosuchfile') ORDER BY 1;
! mapreduce
! ---------------------
! STDERR> Error: Could not open file 'nosuchfile'
! STDERR> 
! STDOUT>
! 
! (3 rows)
  --
```

**Comment by danielgustafsson** [comment]
This is the maintained behaviour from before the flag was added but as such it's not a very good one. There was a patch proposed for tackling the problem of builds with different configuration options but that failed to reach traction. A slightly less complicated (albeit a but kludgier) approach is something along these lines (untested pseudocode follows):

```diff
diff --git a/src/test/regress/GNUmakefile b/src/test/regress/GNUmakefile
index 5824729..3ffed2f 100644
--- a/src/test/regress/GNUmakefile
+++ b/src/test/regress/GNUmakefile
@@ -176,6 +176,9 @@ installcheck-good: all
        bash kerberos/setup_test.sh; \
        PGUSER="gpadmin/kerberos-test" $(pg_regress_call)  --psqldir=$(PSQLDIR) --schedule=$(srcdir)/parallel_schedule --schedule=$(srcdir)/greenplum_schedule --srcdir=$(abs_srcdir) --host=`hostname`; \
        fi
+       if [ -z "$(ENABLE_MAPREDUCE)" ]; then \
+               $(pg_regress_call) --psqldir=$(PSQLDIR) --schedule=$(srcdir)/mapred_schedule --srcdir=$(abs_srcdir); \
+       fi

 testbouncer: all
        bash -c "bouncer/setup.sh"
```
We then move the mapred testcase to `mapred_schedule`. This will quickly become unwieldy if we get a larger set of options.

Another approach is to break out the tests and move them into the separate subdirs and have make traverse the tree during ICG and run individual test suites from where the code is (sort of how the contrib tests work upstream).

**Comment by andreasscherbaum** [comment]
Why is it unwieldy? Because we have to add more options, and they obviously can't run in parallel?

**Comment by danielgustafsson** [comment]
Pretty much yes, but it's also only really a problem once we get many options so it can be a path forwards for now. A bigger stumbling block is that Pulse isn't actually using these switches and instead performs a very bespoke build so the patch above would remove mapred testing from Pulse. Nothing that can't be fixed but it increases scope a fair bit, waiting for Pulse retirement and tackling this once we have a replacement system might be an option to avoid spending time on a system which is going away quite soon.

**Comment by hlinnaka** [comment]
Updated README. I think that's good enough for now.
