### ISSUE TITLE
[WIP] Undefined macro PG_PRINTF_ATTRIBUTE in 5X_STABLE

### ISSUE THREAD

**Issue by d** [greenplum-db/gpdb#5128]
## Work-In-Progress
Don't review yet unless you can guess what's in my head

**Comment by hlinnaka** [comment]
@d, do you still remember what was in your head back in June? ;-) Or can we close this?

**Comment by d** [comment]
> @d, do you still remember what was in your head back in June? ;-) Or can we close this?

I think I fixed this in 2231dadf905 as part of #6417
