### ISSUE TITLE
checking Checking ORCA version...problem

### ISSUE THREAD

**Issue by linenlin01** [greenplum-db/gpdb#5150]
### Greenplum version or build
master or 5.8.1
### OS version and uname -a
Linux centos7 3.10.0-862.el7.x86_64 #1 SMP Fri Apr 20 16:44:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
### Step to reproduce the behavior

./configure --with-perl --with-python --with-libxml --with-gssapi --prefix=/usr/local/gpdb

```
#include "gpopt/version.h"
#include <string.h>
#include <stdio.h>
int
main ()
{
printf(GPORCA_VERSION_STRING);
return strncmp("2.56.", GPORCA_VERSION_STRING, 5);

  ;
  return 0;
}

```

print 2.56 or 2.62 fits demand but still could not configure success。

**Comment by hsyuan** [comment]
Make sure that you add /usr/local/lib and /usr/local/lib64 to /etc/ld.so.conf, then run command ldconfig.

**Comment by d** [comment]
Don't develop on Red Hat or CentOS. Use Ubuntu, you'll be less surprised
