### ISSUE TITLE
CTE & insert: not clear syntax

### ISSUE THREAD

**Issue by DmitryMaletin** [greenplum-db/gpdb#5156]
### Greenplum version or build
Greenplum Database 5.8.1 build commit:6617c3878789b04d0b11fa986ab13c41fcf710d7

### Expected behavior as in PG
WITH CTE AS (SELECT ... )
INSERT INTO SomeTable
SELECT * FROM  CTE

### Actual behavior 
It's not clear from documentation:
INSERT INTO SomeTable
WITH CTE AS (SELECT ... )
SELECT * FROM  CTE

### To reproduce 
That works in GP  
create temporary table test as select * from pg_tables where 1 = 0;

insert into test
with cte as (select * from pg_tables)
select * from cte

I would expect 

with cte as (select * from pg_tables)
insert into test
select * from cte

**Comment by d** [comment]
Can you clarify what you mean here, Dmitry?

**Comment by mkiyama** [comment]
@d please correct me if I am wrong. 
CTE queries that support a data modification clause (e.g. INSERT) seem to be a postgres 9.1 feature.
https://www.postgresql.org/docs/9.1/static/queries-with.html#QUERIES-WITH-MODIFYING

GPDB 5.x is based on 8.3. I do not believe postgres 9.1 CTE functionality is in 5.x.

**Comment by DmitryMaletin** [comment]
@mkiyama 
I guess you are right - it's from 9.x. It's work but I cannot relay on that and it's not in the documentation. 
@d 
I think the issue can be closed

**Comment by DmitryMaletin** [comment]
Current version doesn't support  CTE for data modification
