### ISSUE TITLE
Work-In-Progress: stop probing pg_attribute_encoding in pg_dump and friends

### ISSUE THREAD

**Issue by d** [greenplum-db/gpdb#5170]
### Greenplum version or build
master (6.0 alpha as of posting)

### OS version and uname -a
n/a

### Expected behavior
We only expect to support GPDB 4.3 or newer with pg_dump. In pg_dump.c.

### Actual behavior
We are explicitly checking to see if `pg_attribute_encoding` exists for all versions of the codebase, but this has existed since at least 4.2.

**Comment by d** [comment]
Strategically we seem to want to defer cleaning this up until the fixes that @jchampio and @danielgustafsson have in motion land in master

**Comment by hlinnaka** [comment]
Can we do this now?

**Comment by d** [comment]
Probably
