### ISSUE TITLE
pg_dump: set wrong schema for sequence in pg_attrdef after executed pg_dumpped sql file

### ISSUE THREAD

**Issue by liming01** [greenplum-db/gpdb#5173]
### Greenplum version or build
gpdb4, gpdb5, gpdb6

### Step to reproduce the behavior

createdb testdb1
psql testdb1
```
> CREATE SCHEMA "s""'/\;,1.s";
> CREATE TABLE "s""'/\;,1.s"."t""'/\;,1.t"("c""'/\;,1.c" serial, c2 int, c3 serial);
testdb1=# select adsrc from pg_attrdef;
                                 adsrc
------------------------------------------------------------------------
 nextval('"s""''/\\;,1.s"."t""''/\\;,1.t_c""''/\\;,1.c_seq"'::regclass)
 nextval('"s""''/\\;,1.s"."t""''/\\;,1.t_c3_seq"'::regclass)
(2 rows)
```

pg_dump -s testdb1 > 1.sql
createdb testdb
psql -f 1.sql testdb
```
testdb=# select adsrc from pg_attrdef;
                         adsrc
--------------------------------------------------------
 nextval('"t""''/\\;,1.t_c""''/\\;,1.c_seq"'::regclass)
 nextval('"t""''/\\;,1.t_c3_seq"'::regclass)
(2 rows)
```
Here the schema name lost in pg_attrdef.adsrc, which will report 'can not find the sequence' when execute statements in environment without setting search_path with this specific schema name.

**Comment by chrishajas** [comment]
pg_dump generates the correct statement in upstream (tested on 10.4) , but there hasn't been any change in that area of pg_dump.c. It seems that this commit fixed that issue https://github.com/postgres/postgres/commit/51893985d3bcf27304283f7fa67f17e017d2dafd (its description seems to match the issue you found).

Depending on the urgency of this bug, we can either cherry-pick that commit or wait until we catch up to PG10.

**Comment by chrishajas** [comment]
Also note: special characters are irrelevant in this issue and any table/schema will work.

@danielgustafsson @jchampio Do you think we need to cherry-pick this to master/5? Technically, it will still "pass" the upgrade, but the sequence won't be schema-qualified in the attrdef catalog, which would cause issues when users try to use the sequence if it wasn't in their search path.

**Comment by danielgustafsson** [comment]
I don't think this is super urgent, but I'm inclined to backport that specific commit to avoid hitting this as it would quite inconvenient.

**Comment by jchampio** [comment]
Yeah, it seems self-contained enough.

**Comment by slbteam08** [comment]
Seems this issue makes me unable to use gptransfer to migrate databases created by previous gptransfer. In my situation, I need to create a chain of migrations from Cluster 1 to Cluster 2, then from Cluster 2 to Cluster 3. Migration to Cluster 2 works fine, but all adsrc does not contain schema name inside nextval(), hence migration to Cluster 3 fails. Directly from Cluster 1 to Cluster 3 is not feasible since we have to transform some data in Cluster 2.

Currently I can only think of running ALTER TABLE statements on all affected columns in Cluster 2, but there are a lot of such columns and requires much maintenance effort. Are there better workarounds?

**Comment by khuddlefish** [comment]
@danielgustafsson Forgot about this. Since it is still causing problems for people, we should probably go ahead and fix it. Should we have the server team take responsibility for backporting this commit or should the Backup team take care of it? I just wouldn't want to interfere in merge stuff.

**Comment by slbteam08** [comment]
I just tried modifying the SQL to get sequences in gptransfer, make it insert schema name if not existing. It works in my situation so far.

```
get_depend_obj_sql = """
            select
                nspname, relname
            from pg_class,pg_namespace
            where  pg_class.relnamespace = pg_namespace.oid
                and relkind='S'
                and pg_class.oid in (
                    select
                        case when substring(adsrc from '%%nextval#(''#"%%#"''::regclass#)' for '#') like '%%\.%%' then
                            substring(adsrc from '%%nextval#(''#"%%#"''::regclass#)' for '#')::regclass::oid
                        else
                            ('%s' || '.' || substring(adsrc from '%%nextval#(''#"%%#"''::regclass#)' for '#'))::regclass::oid
                        end
                    from pg_attrdef
                    where adrelid='%s.%s'::regclass
                        and adsrc like '%%nextval(%%'
                        and adbin like '%%FUNCEXPR :funcid 1574%%'
                );""" % (
            pg.escape_string(self._table_pair.source.schema),
            pg.escape_string(self._table_pair.source.schema),
            pg.escape_string(self._table_pair.source.table))
```

**Comment by danielgustafsson** [comment]
@khuddlefish I have no strong feelings either way, but I can volunteer to deal with it today.

**Comment by danielgustafsson** [comment]
So I had a look at this today and it turns out to be a bug in `gptransfer` which causes this. I've opened a PR to fix it, but I don't really know `gptransfer` so I don't really know how to validate. 

@adam8157 @liming01 do you have any good way to test this PR?

**Comment by liming01** [comment]
Hi all,

It is not safe to test existing schema or not by executing "like '%%\.%%'", because the qualifier (table name or schema name) may contains special char including '.',  and there is no simple rule which can be easily written in SQL to figure out the schema part, that is the reason why we need to fix this bug in pg_dump, instead of workaround in gpstransfer. 

Thanks.

**Comment by danielgustafsson** [comment]
The proposed patch isn't a workaround, using `pg_attrdef.adsrc` as `gptransfer` does (and the original report here) has been deprecated since early 2005 with `pg_get_expr()` being the proper solution.

**Comment by liming01** [comment]
Agree! Thanks @danielgustafsson. 

```
testdb=# select adsrc from pg_attrdef;
                        adsrc
------------------------------------------------------
 nextval('"t""''/\;,1.t_c""''/\;,1.c_seq"'::regclass)
 nextval('"t""''/\;,1.t_c3_seq"'::regclass)
(2 rows)

testdb=# select pg_catalog.pg_get_expr(adbin, adrelid) from pg_attrdef;
                             pg_get_expr
---------------------------------------------------------------------
 nextval('"s""''/\;,1.s"."t""''/\;,1.t_c""''/\;,1.c_seq"'::regclass)
 nextval('"s""''/\;,1.s"."t""''/\;,1.t_c3_seq"'::regclass)
(2 rows)
```

**Comment by liming01** [comment]
gptransfer will be changed in PR #6051.

So I close this issue. Thanks all!
