### ISSUE TITLE
gpssh-exkeys and gpseginstall require password after keys have been exchanged (PKCS#8 encoded keys)

### ISSUE THREAD

**Issue by tylarb** [greenplum-db/gpdb#5183]
### Greenplum version or build
4.3.x and 5.x

### OS version and uname -a
Red Hat or Centos 7, any kernel

### Expected behavior
After keys have been exchanged, passwordless login should be possible using gpssh-exkeys or gpseginstall

### Actual behavior
When using PKCS#8 encoded keys (most commonly seen as the default encoding when a user is running the OS in FIPS mode), gpssh-exkeys and gpseginstall will request for password authentication, despite passwordless login being possible

### Step to reproduce the behavior

Convert the private key file on your main host (wherever you run gpseginstall) to use PKCS#8 format: (Keys will default to PKCS#8 encoding when system is running in FIPS mode)

~~~
mv ~/.ssh/id_rsa ~/.ssh/id_rsa.backup
openssl pkcs8 -topk8 < ~/.ssh/id_rsa.backup > ~/.ssh/id_rsa
~~~

Exchange keys with all hosts using ssh-copy-id.

Now run gpseginstall with your hostfile and observe that a password prompt is displayed, even though we already have the necessary keys installed.

~~~
gpseginstall -f hostfile
~~~

**Comment by ivannovick** [comment]
@tylarb is a fix still need on this?

**Comment by tylarb** [comment]
I know that gpseginstall is deprecated - I thought I heard some comments that exkeys was getting deprecated as well. I just checked, and paramiko (the source of this problem, due to its age) is no longer imported. So this should be resolved.
