### ISSUE TITLE
many times per day,some segment become invalid and the mirror also invalid.

### ISSUE THREAD

**Issue by windtalker01** [greenplum-db/gpdb#5190]
### Greenplum version or build
 PostgreSQL 8.2.15 (Greenplum Database 4.3.2.0 build 1) on x86_64-unknown-linux-gnu, compiled by GCC g
cc (GCC) 4.4.2 compiled on Jul 12 2014 17:02:40

### OS version and uname -a
Red Hat Enterprise Linux Server release 6.6 (Santiago)

### Step to reproduce the behavior

[master日志.txt](https://github.com/greenplum-db/gpdb/files/2129931/master.txt)

**Comment by ashwinstar** [comment]
4.3 is not open source version, please reach out to pivotal support for any issue related to it. Also note its extremely old version as well.

**Comment by ashwinstar** [comment]
Would me extremely happy to help and highly appreciate your interest in Greenplum and playing with the same. But would encourage using open source version 5.0 latest for the same, if wish to seek community help. If using proprietary version and need help must go via pivotal support.
