### ISSUE TITLE
greenplum.org - Docs menubar menu items

### ISSUE THREAD

**Issue by lisakowen** [greenplum-db/gpdb#5196]
the "Docs" menu bar submenu has only one item named "Tutorials".  can we add an additional menu item to "Docs" for the current release docs?  

to get to the docs, users currently need to click on the "Docs" menu bar entry, then click on "Documentation" in the single bullet in the "Read the Docs" section of the page.

**Comment by hlinnaka** [comment]
The website was revamped a while ago, the path to the docs is now "Learn" -> "Read the Docs". Closing this issue, I don't think it's relevant on the new website anymore.

(I wish the docs for the current version were even more prominent on the site, but that's a separate issue..)
