### ISSUE TITLE
COPY TO ON SEGMENT of partition table with external partition returns error

### ISSUE THREAD

**Issue by chrishajas** [greenplum-db/gpdb#5202]
PostgreSQL 9.1beta2 (Greenplum Database 6.0.0-alpha.0+dev.7331.g705db74e0c build dev-oss) on x86_64-apple-darwin17.5.0, compiled by Apple LLVM version 9.1.0 (clang-902.0.39.1), 64-bit compiled on Jun 25 2018 15:15:59

COPY TO fails for a partition table containing external partitions with the error: `COPY FROM ON SEGMENT doesn't support checking distribution key restriction when the distribution policy of the partition table is different from the main table` . This only occurs on master. I'm not sure if this is intended behavior, but it does not occurred on gpdb4/5. We can set the `gp_enable_segment_copy_checking` GUC and it will work fine. In any case, either the functionality or the error message needs to be changed.

sql to populate database `repro`:
```
CREATE WRITABLE EXTERNAL TABLE my_sales_ext (
    id integer,
    year integer,
    qtr integer,
    day integer,
    region text
) LOCATION (
    'gpfdist://gpdb_test:8080/sales_2010'
) 
FORMAT 'csv' (delimiter E',' null E'' escape E'"' quote E'"')
ENCODING 'UTF8' DISTRIBUTED BY (id);


--
-- Name: sales_1_prt_yr_1_external_partition__; Type: EXTERNAL TABLE; Schema: public; Owner: -; Tablespace: 
--

CREATE EXTERNAL TABLE sales_1_prt_yr_1_external_partition__ (
    id integer,
    year integer,
    qtr integer,
    day integer,
    region text
) LOCATION (
    'gpfdist://gpdb_test:8080/sales_2010'
) ON ALL 
FORMAT 'csv' (delimiter E',' null E'' escape E'"' quote E'"')
ENCODING 'UTF8';


--
-- Name: sales; Type: TABLE; Schema: public; Owner: -; Tablespace: 
--

CREATE TABLE sales (
    id integer,
    year integer,
    qtr integer,
    day integer,
    region text
) DISTRIBUTED BY (id) PARTITION BY RANGE(year) 
          (
          PARTITION yr_1 START (2010) END (2011) EVERY (1) WITH (tablename='sales_1_prt_yr_1', appendonly=false ), 
          PARTITION yr_2 START (2011) END (2012) EVERY (1) WITH (tablename='sales_1_prt_yr_2', appendonly=false ), 
          PARTITION yr_3 START (2012) END (2013) EVERY (1) WITH (tablename='sales_1_prt_yr_3', appendonly=false ), 
          PARTITION yr_4 START (2013) END (2014) EVERY (1) WITH (tablename='sales_1_prt_yr_4', appendonly=false )
          );
ALTER TABLE sales EXCHANGE PARTITION yr_1 WITH TABLE sales_1_prt_yr_1_external_partition__ WITHOUT VALIDATION; 
DROP TABLE sales_1_prt_yr_1_external_partition__; 

```
On gpdb6:
```
repro=# copy sales to '/tmp/<SEGID>bar' ON SEGMENT ignore external partitions;
NOTICE:  COPY ignores external partition(s)
ERROR:  COPY FROM ON SEGMENT doesn't support checking distribution key restriction when the distribution policy of the partition table is different from the main table
HINT:  "SET gp_enable_segment_copy_checking=off" can be used to disable distribution key checking.
repro=# select version();
```

On gpdb4/5:
```
repro=# copy sales to '/tmp/<SEGID>_bar' ON SEGMENT ignore external partitions;
NOTICE:  COPY ignores external partition(s)
COPY 0
```

**Comment by chrishajas** [comment]
@adam8157 We noticed this on the master branch, it does not affect gpdb4/5.

**Comment by adam8157** [comment]
This was fixed by #5140 , please try the latest code?

That error message looks not right, which is moved there by merging, will amend.

**Comment by chrishajas** [comment]
This is using the latest code (as of commit 705db74e0c002d43d48c1bacf5e8b28367da8127) and isn't related to the row count. In GPDB4/5, we don't need to set the `gp_enable_segment_copy_checking` GUC for COPY TO ON SEGMENT, only COPY FROM ON SEGMENT. However, if we don't set this GUC on COPY TO ON SEGMENT on master, it fails if a partition table contains external partitions. I'm not sure if this was an intentional change (should it require a guc or just accept it during COPY TO ON SEGMENT?) and just wanted to make sure.

**Comment by adam8157** [comment]
OIC, on it.

**Comment by adam8157** [comment]
#5204
