### ISSUE TITLE
Cannot COPY into AO table using ON SEGMENT

### ISSUE THREAD

**Issue by khuddlefish** [greenplum-db/gpdb#5221]
### Version
Seen in: 6.0.0-alpha.0+dev.7352.g464db98625 
(not observed in 6.0.0-alpha.0+dev.7301.ga99194e0e1)

### Step to reproduce the behavior
```
CREATE TABLE public.ao1 WITH (appendonly=true);
COPY public.ao1 TO '/tmp/ao<SEGID>.txt' ON SEGMENT;
COPY public.ao1 FROM '/tmp/ao<SEGID>.txt' ON SEGMENT;
```
Should get the error
```
ERROR:  append-only table "ao1" file segment "-1" entry does not exist  (seg1 127.0.0.1:25433 pid=97988)
```

I suspect this was introduced in commit https://github.com/greenplum-db/gpdb/commit/b320948dc1271798fe14632fc6011a88fc5df8b2

**Comment by adam8157** [comment]
My mistake. Please review #5236

**Comment by adam8157** [comment]
Fixed.
