### ISSUE TITLE
Do not spill regression test logfiles into ~/gpAdminLogs/

### ISSUE THREAD

**Issue by andreasscherbaum** [greenplum-db/gpdb#523]
When a demo cluster is started and stopped for the regression tests, the logfiles are written into the default directory: ~/gpAdminLogs/

Over time, this creates a huge amount of logfiles, which are never cleaned up.

Instead, this logfiles should be written into the demo cluster directory, and removed when the cluster is removed.

**Comment by danielgustafsson** [comment]
Closing this as we there is a PR now where the discussion should be taken.
