### ISSUE TITLE
Change server default encoding after gpinit

### ISSUE THREAD

**Issue by ourdark** [greenplum-db/gpdb#5237]
Can I change my server encoding to 'Latin1' after gp system initialized?

I'd like to create a database with diff encoding(Latin1) other than UTF-8 by default.
`CREATE DATABASE _dbname_ OWNER _owner_ ENCODING 'LATIN1';`

> ERROR:  encoding LATIN1 does not match server's locale en_US.utf8 (dbcommands.c:831)
> DETAIL:  The server's LC_CTYPE setting requires encoding UTF8.

I've changed my /etc/locale.cnf to Latin1, no postgres trick works for me.

**Comment by danielgustafsson** [comment]
> On 3 Jul 2018, at 09:36, ourdark <notifications@github.com> wrote:
> 
> Can I change my server encoding to 'Latin1' after gp system initialized?
> 
> I'd like to create a database with diff encoding(Latin1) other than UTF-8 by default.
> CREATE DATABASE _dbname_ OWNER _owner_ ENCODING 'LATIN1';
> 
> ERROR: encoding LATIN1 does not match server's locale en_US.utf8 (dbcommands.c:831)
> DETAIL: The server's LC_CTYPE setting requires encoding UTF8.
> 
> I've changed my /etc/locale.cnf to Latin1, no postgres trick works for me.

Unfortunately that won’t work, the encoding of the server cannot be altered without re-initialization.

**Comment by ourdark** [comment]
Make sense for me. Issue closed.
