### ISSUE TITLE
gpinitsystem --help should work without setting $GPHOME

### ISSUE THREAD

**Issue by andreasscherbaum** [greenplum-db/gpdb#524]
Right now, the gpinitsystem help option (--help) requires $GPHOME to be set in order to print out the help.

The help should be displayed without setting or requiring any environment variables.

**Comment by xinzweb** [comment]
After you run the `source greenplum_path.sh` then the GPHOME is set. We need that variable to figure out where the installation is so that we can initialize it.

**Comment by ascherbaum-pivotal** [comment]
Oh, I know. But I've seen two people trying out Greenplum and not sourcing greenplum_path.sh before.
And gpinitsystem is one of the first steps you have to do.

Hence it would be nice if it fails nicely, or prints the help, instead of just complaining about missing $GPHOME.

**Comment by danielgustafsson** [comment]
Glancing at the code it would most likely require more plumbing work than it's worth to support this cleanly. How about if we just improve the error message along the lines of this:

```diff
diff --git a/gpMgmt/bin/lib/gp_bash_functions.sh b/gpMgmt/bin/lib/gp_bash_functions.sh
index 8597e53..2c5e6c8 100755
--- a/gpMgmt/bin/lib/gp_bash_functions.sh
+++ b/gpMgmt/bin/lib/gp_bash_functions.sh
@@ -42,7 +42,9 @@ CMDPATH=(/usr/kerberos/bin /usr/sfw/bin /opt/sfw/bin /usr/local/bin /bin /usr/bi
 declare -a GPPATH
 GPPATH=( $GPHOME $MPPHOME $BIZHOME )
 if [ ${#GPPATH[@]} -eq 0 ];then
-       echo "[FATAL]:-GPHOME is not set, need to set this within environment"
+       echo "[FATAL]:-GPHOME environment variable is required to run GPDB but could not be found."
+       echo "Please set by sourcing the greenplum_path.sh in your GPDB installation directory."
+       echo "Example: ''source /usr/local/gpdb/greenplum_path.sh''"
        exit 2
 fi
```

**Comment by andreasscherbaum** [comment]
@danielgustafsson Picked up your idea, improved it a bit (and got rid of the bash syntax). Pulse is running.

**Comment by danielgustafsson** [comment]
> On 07 Apr 2016, at 19:03, Andreas Scherbaum <notifications@github.com> wrote:
> 
> @danielgustafsson Picked up your idea, improved it a bit (and got rid of the bash syntax). Pulse is running.
> 
Cool. The scripts still depend on bash to run though so if no big problem in having bash syntax.

**Comment by andreasscherbaum** [comment]
Issue #455 is there to keep track of this problem. I thought I don't let this one slip through.
