### ISSUE TITLE
multibyte regression test fails with "invalid option -- " error

### ISSUE THREAD

**Issue by imshubhangi** [greenplum-db/gpdb#5241]
### Greenplum version or build
tag 5.5.0

### OS version and uname -a
`$ cat /etc/redhat-release 
CentOS Linux release 7.4.1708 (Core) 

$ uname -a
Linux osboxes 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
`

### Actual behavior

$ ./mbregress.sh 
dropdb: database removal failed: ERROR:  database "utf8" does not exist
createdb: invalid option -- 'l'
Try "createdb --help" for more information.
euc_jp .. createdb: invalid option -- 'l'
Try "createdb --help" for more information.
failed
sjis .. failed
euc_kr .. createdb: invalid option -- 'l'
Try "createdb --help" for more information.
failed
euc_cn .. createdb: invalid option -- 'l'
Try "createdb --help" for more information.
failed
euc_tw .. createdb: invalid option -- 'l'
Try "createdb --help" for more information.
failed
big5 .. failed
utf8 .. createdb: invalid option -- 'l'
Try "createdb --help" for more information.
failed
mule_internal .. createdb: invalid option -- 'l'
Try "createdb --help" for more information.
failed

### Step to reproduce the behavior
1. Compile and build 
cd depends 
./configure
make
make install_local
cd ..
LD_LIBRARY_PATH=/home/osboxes/greenplum-db/gpdb_5.5_new_ssl/depends/build/lib ./configure   --with-libraries=/home/osboxes/greenplum-db/gpdb_5.5_new_ssl/depends/build/lib    --with-includes=/home/osboxes/greenplum-db/gpdb_5.5_new_ssl/depends/build/include  --with-perl --with-python --with-libxml  --with-gssapi   --enable-pxf    --enable-tap-tests  --prefix=/usr/local/gpdb
make -j8
make -j8 install
make create-demo-cluster
cd src/test/mb/
sh ./mbregress.sh

**Comment by hlinnaka** [comment]
Thanks for the report! Most of the failures are just because we haven't updated the expected output for some NOTICEs that Greenplum prints, and the fact that rows come out in different order than in PostgreSQL, due to the MPP nature of Greenplum. However, there seems to be one genuine bug there: in the 'sjis' test, the COPY TO STDOUT test produces wrong results.

I'll open a PR to fix the trivial issues, but someone really needs to look into that COPY case..

**Comment by hlinnaka** [comment]
Pushed the straightforward expected output fixes, but this the 'sjis' issue remains. 

See regression.diffs for that failure: [regression.diffs.txt](https://github.com/greenplum-db/gpdb/files/2278582/regression.diffs.txt)

**Comment by imshubhangi** [comment]
Hello hlinnaka, 

Thank you for working on this issue. 

Can you please let me know your inputs on following concern ? 

-------
mbregress.sh script contains createdb command usage as follows. 

`[root@osboxes mb]# grep "^createdb"  mbregress.sh 
createdb -T template0 -l C -E UTF8 utf8
`
Whereas , greenplum createdb command does not have -l option. 

`[root@osboxes mb]# createdb --help
createdb creates a PostgreSQL database.

Usage:
  createdb [OPTION]... [DBNAME] [DESCRIPTION]

Options:
  -D, --tablespace=TABLESPACE  default tablespace for the database
  -e, --echo                   show the commands being sent to the server
  -E, --encoding=ENCODING      encoding for the database
  -O, --owner=OWNER            database user to own the new database
  -T, --template=TEMPLATE      template database to copy
  --help                       show this help, then exit
  --version                    output version information, then exit

Connection options:
  -h, --host=HOSTNAME          database server host or socket directory
  -p, --port=PORT              database server port
  -U, --username=USERNAME      user name to connect as
  -w, --no-password            never prompt for password
  -W, --password               force password prompt

By default, a database with the same name as the current user is created.

Report bugs to <bugs@greenplum.org>.
`
Similarly dropdb command does not have --if-exists option. 

`[root@osboxes mb]# dropdb --help
dropdb removes a PostgreSQL database.

Usage:
  dropdb [OPTION]... DBNAME

Options:
  -e, --echo                show the commands being sent to the server
  -i, --interactive         prompt before deleting anything
  --help                    show this help, then exit
  --version                 output version information, then exit

Connection options:
  -h, --host=HOSTNAME       database server host or socket directory
  -p, --port=PORT           database server port
  -U, --username=USERNAME   user name to connect as
  -w, --no-password         never prompt for password
  -W, --password            force password prompt

Report bugs to <bugs@greenplum.org>.
`
The  createdb and dropdb commands from mbregress.sh (from master branch)  fails with error as follows. 

`[root@osboxes mb]# ./mbregress.sh 
+ grep -s c
+ echo '\c'
+ ECHO_N='echo -n'
+ ECHO_C=
+ '[' '!' -d results ']'
+ dropdb --if-exists utf8
dropdb: unrecognized option '--if-exists'
Try "dropdb --help" for more information.
+ createdb -T template0 -l C -E UTF8 utf8
createdb: invalid option -- 'l'
Try "createdb --help" for more information.
+ exit 1
`

Can you please review this ?

**Comment by hlinnaka** [comment]
The '-l' option is present on GPDB master. Might not have been present before, but now that we're caught up to PostgreSQL 9.4, it's there.

Someone still needs to look at the SJIS failure...

**Comment by hlinnaka** [comment]
Opened a discussion on that on the gpdb-dev mailing list: https://groups.google.com/a/greenplum.org/forum/#!topic/gpdb-dev/WPmHXuU9T94

**Comment by hlinnaka** [comment]
Fixed on GPDB master branch with commit a6c9b43640. Thanks for the report, @imshubhangi!
