### ISSUE TITLE
assign_plannode_id_walker missed Sequence node.

### ISSUE THREAD

**Issue by vitesse-ftian** [greenplum-db/gpdb#5247]
### Greenplum version or build
master

### Step to reproduce the behavior

In cdbmutate.c, function
assign_plannode_id_walker(Node *node, assign_plannode_id_walker_context *ctxt)

The walker missed a node type Sequence.    Children of Sequence are contained in subplans.   Shareinput_walker correctly walked sequenceg

I believe sequence node is only created by Orca, and Orca does not use assign_plannode_id_walker -- so this bug may not do any real harm but still, if my belief is wrong, or later, standard planner can create a sequence node, then this is a serious bug.

**Comment by hsyuan** [comment]
You are right. Only Orca creates Sequence node.

**Comment by ashwinstar** [comment]
So, will we get error when planner starts using Sequence node and yet to add code to handle it in `assign_plannode_id_walker()` or will be silently lost and go unnoticed? Do we need to add assert or something there then to catch in future? If it will fail nothing needs to be done and we can close the issue.
