### ISSUE TITLE
pg_stat_user_tables doesn't reflect inserts/updates/deletes/vacuums etc.

### ISSUE THREAD

**Issue by soumyadeep2007** [greenplum-db/gpdb#5253]
### Greenplum version or build
5.9.0+dev.24.ge2c4961bb4 build dev and 6
### OS version and uname -a
Darwin melville 16.5.0 Darwin Kernel Version 16.5.0: Fri Mar  3 16:52:33 PST 2017; root:xnu-3789.51.2~3/RELEASE_X86_64 x86_64
### Expected behavior
If track_counts is turned on, inserts/updates/deletes/vacuums on a table should be tracked in the corresponding row in pg_stat_user_tables. Fields such as n_tup_ins, n_tup_del, last_vacuum track such actions. These fields should reflect these changes (technically after PGSTAT_STAT_INTERVAL) and do not require a preceding analyze run.
I reproduced the expected behavior on Postgres 8.3.23 on Ubuntu 16.x
### Actual behavior
The aforementioned fields are not updated, even after PGSTAT_STAT_INTERVAL expires. However, upon going into utility mode on each segment, running analyze, we are able to see the updated counts (on the segment which was affected by the last insert/update/delete etc.)
### Step to reproduce the behavior
0) Make sure track_counts is turned on.
1) Create any table. 
2) Insert a row. 
3) Query the pg_stat_user_tables with: select * from pg_stat_user_tables where relname=<table_name>;
4) See that n_tup_ins is still 0. Expected = 1.

**Comment by asimrp** [comment]
This issue still exists on master.

**Comment by lij55** [comment]
It is fixed on master:
```
gpadmin=# create table ta (a1 int);
NOTICE:  Table doesn't have 'DISTRIBUTED BY' clause -- Using column named 'a1' as the Greenplum Database data distribution key for this table.
HINT:  The 'DISTRIBUTED BY' clause determines the distribution of data. Make sure column(s) chosen are the optimal data distribution key to minimize skew.
CREATE TABLE
gpadmin=# insert into ta values (1);
INSERT 0 1
gpadmin=# select n_tup_ins  from pg_stat_user_tables where relname='ta';
 n_tup_ins 
-----------
         1
(1 row)

```

but still on GP6
```
test=# create table ta (a1 int);
NOTICE:  Table doesn't have 'DISTRIBUTED BY' clause -- Using column named 'a1' as the Greenplum Database data distribution key for this table.
HINT:  The 'DISTRIBUTED BY' clause determines the distribution of data. Make sure column(s) chosen are the optimal data distribution key to minimize skew.
CREATE TABLE
test=# insert into ta values (1);
INSERT 0 1
test=# insert into ta values (2);
INSERT 0 1


test=# select n_tup_ins  from pg_stat_user_tables where relname='ta';
 n_tup_ins 
-----------
         0
(1 row)


```

**Comment by dpandhi-git** [comment]
closing as it worked on 7x
