### ISSUE TITLE
Planner producing bad plans for join queries with false WHERE clauses

### ISSUE THREAD

**Issue by melanieplageman** [greenplum-db/gpdb#5275]
On Greenplum current 5X_STABLE, planner is not correctly optimizing joins with FALSE restrictinfo. A query with restrictinfo such as a WHERE clause which evaluates to FALSE (e.g. `where FALSE`) should mark the join as a dummy join and simplify the plan.

For example:
```
DROP TABLE IF EXISTS foo;
DROP TABLE IF EXISTS bar;
CREATE TABLE foo (a INT);
CREATE TABLE bar (b INT);
INSERT INTO foo VALUES (1),(1);
INSERT INTO bar VALUES (1),(2);
ANALYZE foo;
ANALYZE bar;
```
The following query:
```
EXPLAIN SELECT * FROM foo, bar WHERE FALSE;
```
produces this plan on 5.9
```
                                            QUERY PLAN
-------------------------------------------------------------------------------------------------------
 Gather Motion 3:1  (slice2; segments: 3)  (cost=1.11..2.37 rows=4 width=8)
   ->  Result  (cost=1.11..2.37 rows=2 width=8)
         One-Time Filter: false
         ->  Nested Loop  (cost=1.11..2.37 rows=2 width=8)
               ->  Seq Scan on foo  (cost=0.00..1.02 rows=1 width=4)
               ->  Materialize  (cost=1.11..1.17 rows=2 width=4)
                     ->  Broadcast Motion 3:3  (slice1; segments: 3)  (cost=0.00..1.10 rows=2 width=4)
                           ->  Seq Scan on bar  (cost=0.00..1.02 rows=1 width=4)
 Settings:  optimizer=off
 Optimizer status: legacy query optimizer
(10 rows)
```
Whereas it should likely produce a plan like this (from Postgres master)
```
                QUERY PLAN
------------------------------------------
 Result  (cost=0.00..0.00 rows=0 width=8)
   One-Time Filter: false
(2 rows)
```

**Comment by hlinnaka** [comment]
This was improved in PostgreSQL 8.4. PostgreSQL 8.3 and below produce the plan with the join, and 8.4 just the Result node. GPDB is just following the corresponding upstream version's behaviour.

Note that the Result node has a `One-Time Filter: false`. It means that the nodes below it will never actually be executed, as can be seen with EXPLAIN ANALYZE: (from PostgreSQL 8.3):

```
postgres=# EXPLAIN analyze SELECT * FROM foo, bar WHERE FALSE;
                                      QUERY PLAN                                      
--------------------------------------------------------------------------------------
 Result  (cost=1.02..2.12 rows=1 width=8) (actual time=0.001..0.001 rows=0 loops=1)
   One-Time Filter: false
   ->  Nested Loop  (cost=1.02..2.12 rows=1 width=8) (never executed)
         ->  Seq Scan on foo  (cost=0.00..1.02 rows=2 width=4) (never executed)
         ->  Materialize  (cost=1.02..1.04 rows=2 width=4) (never executed)
               ->  Seq Scan on bar  (cost=0.00..1.02 rows=2 width=4) (never executed)
 Total runtime: 0.106 ms
(7 rows)
```

So even though there is some extra overhead in the planner and the executor to initialize those useless nodes below the Result, it's still very cheap.

**Comment by hlinnaka** [comment]
> I've got the same issue here. Three table join, one historical table with time filter, the plan gives huge join then filter them. I think it should actualy eval the real cost and pick a plan.

@ourdark, are you seeing an actual performance impact from that? Are the joins really being executed in your case?

**Comment by hlinnaka** [comment]
There's been no action on this, so I assume it's fine as it is. Feel free to re-open, if you can reproduce a performance problem caused by this.
