### ISSUE TITLE
Planner picks up NLJ instead of HJ

### ISSUE THREAD

**Issue by foyzur** [greenplum-db/gpdb#528]
Apparently this is an issue with equivalence class. This breaks couple of tests that we are currently porting to open source. This also can introduce significant regression. For a simple repro (abridged from one of the test suites):

```
drop table if exists foo;
drop table if exists bar;

create table foo( a int, k int) distributed by (a);

create table bar( a int, k int) distributed by (a);

insert into foo select i, i  from generate_series(1, 1000) i;

insert into bar select i % 7, i % 9 from generate_series(1, 100) i;

explain select foo.k from foo join bar on foo.a = bar.k  where foo.a = 6;
```

Explain output:

```
rahmaf2=# explain select foo.k from foo join bar on foo.a = bar.k  where foo.a = 6;
                                         QUERY PLAN
--------------------------------------------------------------------------------------------
 Gather Motion 3:1  (slice2; segments: 3)  (cost=3.26..19.46 rows=11 width=4)
   ->  Nested Loop  (cost=3.26..19.46 rows=4 width=4)
         ->  Broadcast Motion 1:3  (slice1; segments: 1)  (cost=0.00..15.54 rows=3 width=8)
               ->  Seq Scan on foo  (cost=0.00..15.50 rows=1 width=8)
                     Filter: a = 6
         ->  Materialize  (cost=3.26..3.37 rows=4 width=4)
               ->  Seq Scan on bar  (cost=0.00..3.25 rows=4 width=4)
                     Filter: k = 6
 Optimizer status: legacy query optimizer
(9 rows)
```

**Comment by foyzur** [comment]
@hlinnaka @atris could you please take a look? This is blocking our test porting process.

**Comment by hlinnaka** [comment]
On 15/03/16 19:18, foyzur wrote:
> @hlinnaka @atris could you please take a look? This is blocking our test porting process.

Ok, will take a look.

- Heikki

**Comment by hlinnaka** [comment]
So, before the equivalence classes patch, you get a plan like this:

```
postgres=# explain select foo.k from foo join bar on foo.a = bar.k  where foo.a = 6;
                                             QUERY PLAN                                         
    
------------------------------------------------------------------------------------------------
----
 Gather Motion 2:1  (slice2; segments: 2)  (cost=3.58..20.65 rows=4 width=4)
   ->  Nested Loop  (cost=3.58..20.65 rows=2 width=4)
         ->  Seq Scan on foo  (cost=0.00..17.00 rows=1 width=8)
               Filter: a = 6 AND 6 = a
         ->  Materialize  (cost=3.58..3.61 rows=2 width=4)
               ->  Redistribute Motion 2:2  (slice1; segments: 2)  (cost=0.00..3.57 rows=2 width
=4)
                     Hash Key: 6
                     ->  Seq Scan on bar  (cost=0.00..3.50 rows=2 width=4)
                           Filter: 6 = k AND k = 6
(9 rows)
```

That doesn't look like a better plan to me, at least not significantly so. The estimated cost is about the same too.

It's worth noting that the planner correctly estimates that there is only one matching row in 'foo', so broadcasting 'foo' is cheaper than redistributing 'bar', because there are more matching rows in 'bar'. If you change the data so that there are more rows in 'foo' with a=6, then the planner will produce the same plan as before. I'm not exactly sure why that changed with the equivalence classes patch, but if you look at the estimated costs of the plans, they're both about 20, so it's right on the edge of which plan it chooses. Not surprising that small unrelated changes would tip it over.

**Comment by hlinnaka** [comment]
Oh, and the reason it chooses a nested loop join over a hash join is that there is no useful hash key to join on. The filters on Seq Scan nodes already filter all rows with key != 6, so all the tuples that reach the Join node are already known to match the join condition.

**Comment by hlinnaka** [comment]
I think this has been explained away, so closing, but please feel free to re-open if I'm missing something.
