### ISSUE TITLE
Help me to find emcconnect library

### ISSUE THREAD

**Issue by wangcheng233** [greenplum-db/gpdb#529]
when I compile Greenplum with --enable-connectemc, I get an error that I can't find emcconnect library. I can't find how to install the library,help me, thank you very much.

**Comment by ivannovick** [comment]
Hi, why would you want to use this option?  Its used for building an EMC appliance with the prorpietary api.

**Comment by wangcheng233** [comment]
Hi, ivannovick, thank you for reply.I want to compile gpperfmon which is in the Greenplum source code "gpAux", but in gpmon_snmp.c, there is the code "#include emcconnect/api.h" that can't be found, so I failed to compile gpperfmon. I also can't get the gpperfmon from the official web.

**Comment by danielgustafsson** [comment]
Hi, I took a stab at building gpperfmon this morning and with the crude diff below (I had to fiddle with the APR paths and snmp lib name as well) it builds without the EMCConnect SNMP code on my Linux box. That being said, since I'm not familiar with gpperfmon I didn't validate it more than testing that it runs.

I'll have a look at giving gpperfmon some attention such that it honors the autoconf settings for building out of the box but this might get you going in the meantime.

```diff
--- a/gpAux/gpperfmon/src/gpmon/Makefile
+++ b/gpAux/gpperfmon/src/gpmon/Makefile
@@ -17,7 +17,7 @@ ifneq ($(CUSTOM_COPT),)
        COPT=$(CUSTOM_COPT)
 endif

-ifneq "$(findstring $(BLD_ARCH),rhel5_x86_64 rhel6_x86_64)" ""
+ifneq "$(findstring $(BLD_ARCH),dont_build)" ""
 GPMMON_SNMP_OBJ=gpmon_snmp.o
 CONNECTEMCLIB += -lemcconnect
 endif
@@ -28,12 +28,12 @@ GPSMON_OBJS=gpsmon.o gpmonlib.o
 SIGTEST_OBJS=sigartest.o
 SNMPTEST_OBJS=snmptest.o

-INCS=-I$(EXT_DIR)/include -I$(EXT_DIR)/include/apr-1 -I$(BLD_TOP)/../src/include -I$(LIBPQ_DIR)
-LIBS=-L$(EXT_DIR)/lib -laprutil-1 -lapr-1 -levent $$($(EXT_DIR)/bin/apu-1-config --libs) $$($(EXT_DIR)/bin/apr-1-config --libs)
+INCS=-I$(EXT_DIR)/include $(shell apr-1-config --includes) -I$(BLD_TOP)/../src/include -I$(LIBPQ_DIR)
+LIBS=-L$(EXT_DIR)/lib -laprutil-1 -lapr-1 -levent $(shell apu-1-config --libs) $(shell apr-1-config --libs)
 GPSMON_LIBS=
-GPMMON_LIBS=-L$(LIBPQ_DIR) -lpq -lm -lsnmp $(CONNECTEMCLIB)
-CFLAGS=$(OPT) $$($(EXT_DIR)/bin/apr-1-config --cflags) -Werror -Wall
-CPPFLAGS=$$($(EXT_DIR)/bin/apr-1-config --cppflags) -D$(BLD_ARCH)
+GPMMON_LIBS=-L$(LIBPQ_DIR) -lpq -lm -lnetsnmp $(CONNECTEMCLIB)
+CFLAGS=$(OPT) $(shell apr-1-config --cflags) -Werror -Wall
+CPPFLAGS=$(shell apr-1-config --cppflags) -D$(BLD_ARCH)

 ifeq "$(findstring osx,$(BLD_ARCH))" "osx"
        GPSMON_LIBS=-framework CoreServices -framework IOKit
@@ -46,7 +46,7 @@ endif

 GPSMON_LIBS+= -lm -lsigar
 SIGTEST_LIBS+= -lsigar
-SNMPTEST_LIBS+= -lsnmp
+SNMPTEST_LIBS+= -lnetsnmp

 all: gpsmon gpmmon
```

**Comment by ivannovick** [comment]
cool stuff, let me know if you need help on gpmmon / gpsmon I used to maintain it for few years

**Comment by wangcheng233** [comment]
yes, ivannovick, I need your help. I want to download greenplum-perfmon-web-4.1.1.x binary from the official web, but I didn't find it. Do you have???
Anyway, I also want to compile gpperfmon in the greenplum source code, but I didn't succeed. I tried this afternoon, but I got many problems, such as gpperfmon_path.sh missing, gpmonws.py missing and lighttpd missing, those are not in source code. So help me use gpperfmon. Thank you.

**Comment by ivannovick** [comment]
the web services and UI are not open source, only the backend agents are open source and i see the full code for the backend in the open source, git tree.  @bharath1028 you might want to clarify this.

**Comment by andreasscherbaum** [comment]
Is there an update in this issue? It's open for 6 weeks without any activity.
@ivannovick If we do not open source the UI and the web services, can we even help @wangcheng233 here?

**Comment by danielgustafsson** [comment]
We should still be able to build the backend parts properly, will open a PR with a polished up version of the patch in this thread. Thanks for bumping the issue to the top again.

**Comment by ascherbaum-pivotal** [comment]
@danielgustafsson "we" as in Pivotal or "we" as in everyone?
The "emcconnect" library is only required for the EMC DCA, I don't see why anyone must be able to use this configure flag.

**Comment by ivannovick** [comment]
@andreasscherbaum @danielgustafsson their are alternate means now for EMC DCA to get the required information.  This code should be deprecated / removed from within GPDB core engine in the MASTER branch.

**Comment by danielgustafsson** [comment]
Ok, will do.
