### ISSUE TITLE
Concurrent index build is not supported in Greenplum

### ISSUE THREAD

**Issue by asimrp** [greenplum-db/gpdb#5293]
### Greenplum version or build
6.0 / master
### Expected behavior
`CREATE INDEX CONCURRENTLY` works like it does in upstream PostgreSQL, in presence of concurrent DML on the table for which a new index is being built. 
### Actual behavior
`CREATE INDEX CONCURRENTLY` fails with "not supported" error.  GUC `gp_create_index_concurrently` (now removed) was used to disable this feature.  Even after enabling the GUC, things used to fail because the feature needs additional Greenplum-specific changes to work properly.

In upstream, concurrent index building happens in three steps (see `validate_index()` in `index.c` for details).  Each step must happen in a transaction by itself, such that the effects of the previous step are visible to all new transactions.  In Greenplum, that means each step must happen in its own distributed transaction.  Upon dispatching an `IndexStmt` to QEs, the QEs must know which step of concurrent index build to execute.  This ability must be incorporated in Greenplum so that concurrent index build may be supported.  One option is to introduce a new variable in `IndexStmt` to indicate the step to be performed for concurrent index builds.

**Comment by melanieplageman** [comment]
See this PR for removal of documentation related to this https://github.com/greenplum-db/gpdb/pull/8409

**Comment by gfphoenix78** [comment]
@wuj21  The upstream (PG 12) has support building index **concurrently** in either `CREATE INDEX` or `REINDEX`. Will Greenplum 7X support them? If not, the document also needs to update. Currently, GPDB 7X doesn't support this feature.
