### ISSUE TITLE
greenplum make error--fe-connect.c:: error

### ISSUE THREAD

**Issue by fuxingyang** [greenplum-db/gpdb#5295]
### Greenplum version or build
greenplum-master:6.0.0
### OS version and uname -a
centos6.5 x86-64
### autoconf options used ( config.status --config )
--prefix=/home/gpadmin/gpdb --with-openssl --with-libs
### Installation information ( pg_config )
make status:
**fe-connect.c**: In function '**internal_ping**'
**fe-connect.c**:2763:10: **error** :'PQPING_MIRROR_READY' undeclared  (first use in this function)
return **PQPING_MIRROR_READY**
make[3 ]: [fe-connect.o] Error 1
make[2]: [libpq-recursive] Error 2
make[1]: [all-backend-recurse] Error 2
make: [all-src-recurse] Error 2

**Comment by danielgustafsson** [comment]
I can't reproduce this, which makes sense as `PQPING_MIRROR_READY` is defined in `src/interfaces/libpq/libpq-fe.h`. Just to make sure, can you run `make -C  src/interfaces/libpq clean` first?

**Comment by fuxingyang** [comment]
I run with make -C src/interfaces/libpq clean first,then make, and the fe-connect error didn't appear.

**Comment by danielgustafsson** [comment]
Great, then the error was due to the object files in your tree being inconsistent with the source files.
