### ISSUE TITLE
Altering the storage type of the table is not supported

### ISSUE THREAD

**Issue by ashwinstar** [greenplum-db/gpdb#5300]
### Greenplum version or build
6 / master

### Expected behavior
Alter table should expose syntax to allow altering storage type of the table. Like altering from heap to ao/co, ao to heap/co, co to heap/ao. Something like 
```sql
CREATE TABLE foo (a int, b int);
ALTER TABLE foo set with(appendonly = true);
```
### Actual behavior
fails with error `ERROR:  option "appendonly" not supported`

### Step to reproduce the behavior
```sql 
create table foo (i int, j text) distributed by (j);
insert into foo select i, i::text from generate_series(1, 10) i;
alter table foo set with(appendonly = true);
```

Currently, this feature is hidden behind guc `gp_setwith_alter_storage`. This feature should be fully tested and enabled when works for all the scenarios instead behind the guc.

**Comment by yydzero** [comment]
@ashwinstar shall we close this issue?

**Comment by ashwinstar** [comment]
On Mon, Apr 1, 2019 at 9:29 PM Yandong Yao <notifications@github.com> wrote:

> @ashwinstar <https://github.com/ashwinstar> shall we close this issue?
>
No, why? Its tracking a feature which has not been implemented yet so needs
to stay open. Unless its collectively decided we don't wish to implement it
at that time fine to close with that detailed reason posted.

**Comment by yydzero** [comment]
Oh, I see, had thought this is a bug...

**Comment by lintzc** [comment]
Today, the only option for changing storage of a table is to drop and recreate the table with the new storage. It is not straigthforward and if the table is used by views, it will be far more complex.

My idea would be to add a feature to the reorganize in order to change the storage intentionally.

For example:
```
create table test1 (a int, b int) with(appendonly=true,orientation=row,compresstype=quicklz);
alter table test1
set with(reorganize=true,appendonly=true,orientation=column,compresstype=zlib);
```
It would change the storage from row-quicklz to column-zlib1.

For sure, it can be a bit complex when moving from a heap table to AO or when changing orientation.

**Comment by asimrp** [comment]
Thank you for sharing your inputs, @lintzc.  At the moment, this feature is targeted for Greenplum 7. will get to this issue in due course but until then, you are encouraged to submit a patch!

**Comment by huansong** [comment]
We have implemented this feature. We can use two syntax `SET ACCESS METHOD` and `SET WITH ()` to alter the table storage type now. E.g.:

```
CREATE TABLE foo (a int);
ALTER TABLE foo SET ACCESS METHOD ao_row;
ALTER TABLE foo SET WITH (appendoptimized=true, orientation=column);
```

The table rewrite will be happening under the hood.
