### ISSUE TITLE
Window function percentile_cont is throwing SIGSEGV error

### ISSUE THREAD

**Issue by lyndenzhang** [greenplum-db/gpdb#5334]
### Greenplum version or build
Greenplum Database 6.0.0-alpha.0+dev.7268.g578a35e build dev-oss
### OS version and uname -a
Linux mdw1-c59x 3.10.0-862.3.2.el7.x86_64 #1 SMP Mon May 21 23:36:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

### Step to reproduce the behavior

2018-07-25 14:38:16.612844 UTC,"gpadmin","VoloGP",p28104,th245573760,"172.31.25.23","17402",2018-07-25 14:38:05 UTC,0,con676,,seg153,,,,,"LOG","00000","Process interrupt for
 'query cancel pending' (postgres.c:3563)",,,,,,,0,,"postgres.c",3866,
2018-07-25 14:49:03.161211 UTC,,,p29493,th0,,,2018-07-25 14:48:56 UTC,0,con680,cmd15,seg153,slice3,,,,"PANIC","XX000","Unexpected internal error: Segment process received si
gnal SIGSEGV",,,,,,,0,,,,"1    0x953032 postgres StandardHandlerForSigillSigsegvSigbus_OnMainThread + 0x1c2
2    0x7fa10ad5f6d0 libpthread.so.0 <symbol not found> + 0xad5f6d0
3    0x985360 postgres MemoryContextFreeImpl + 0x0
4    0x9a87f2 postgres tuplesort_skiptuples_mk + 0x182
5    0x8a4a05 postgres percentile_cont_float8_final + 0x215
6    0x6960ab postgres <symbol not found> + 0x6960ab
7    0x698bcc postgres ExecAgg + 0x54c
8    0x67e84a postgres ExecProcNode + 0x52a
9    0x6b769c postgres ExecMotion + 0x3c
10   0x67e7da postgres ExecProcNode + 0x4ba
11   0x6769c9 postgres <symbol not found> + 0x6769c9
12   0x677303 postgres standard_ExecutorRun + 0x2b3
13   0x81c278 postgres <symbol not found> + 0x81c278
14   0x81df22 postgres PortalRun + 0x2b2
15   0x81644d postgres <symbol not found> + 0x81644d
16   0x81b5bb postgres PostgresMain + 0x233b
17   0x7bcc3d postgres <symbol not found> + 0x7bcc3d
18   0x7be45a postgres PostmasterMain + 0xb5a
19   0x4c3c13 postgres main + 0x3b3
20   0x7fa10a186445 libc.so.6 __libc_start_main + 0xf5
21   0x4c417f postgres <symbol not found> + 0x4c417f
"

**Comment by lyndenzhang** [comment]
This is the error message on the master node:

ERROR:  Error on receive from seg153 slice3 172.31.28.171:40025 pid=27409: server closed the connection unexpectedly
DETAIL:
        This probably means the server terminated abnormally
        before or while processing the request.

The error on the segment 153

2018-07-25 14:38:16.612844 UTC,"gpadmin","VoloGP",p28104,th245573760,"172.31.25.23","17402",2018-07-25 14:38:05 UTC,0,con676,,seg153,,,,,"LOG","00000","Process interrupt for
 'query cancel pending' (postgres.c:3563)",,,,,,,0,,"postgres.c",3866,
2018-07-25 14:49:03.161211 UTC,,,p29493,th0,,,2018-07-25 14:48:56 UTC,0,con680,cmd15,seg153,slice3,,,,"PANIC","XX000","Unexpected internal error: Segment process received si
gnal SIGSEGV",,,,,,,0,,,,"1    0x953032 postgres StandardHandlerForSigillSigsegvSigbus_OnMainThread + 0x1c2
2    0x7fa10ad5f6d0 libpthread.so.0 <symbol not found> + 0xad5f6d0
3    0x985360 postgres MemoryContextFreeImpl + 0x0
4    0x9a87f2 postgres tuplesort_skiptuples_mk + 0x182
5    0x8a4a05 postgres percentile_cont_float8_final + 0x215
6    0x6960ab postgres <symbol not found> + 0x6960ab
7    0x698bcc postgres ExecAgg + 0x54c
8    0x67e84a postgres ExecProcNode + 0x52a
9    0x6b769c postgres ExecMotion + 0x3c
10   0x67e7da postgres ExecProcNode + 0x4ba
11   0x6769c9 postgres <symbol not found> + 0x6769c9
12   0x677303 postgres standard_ExecutorRun + 0x2b3
13   0x81c278 postgres <symbol not found> + 0x81c278
14   0x81df22 postgres PortalRun + 0x2b2
15   0x81644d postgres <symbol not found> + 0x81644d
16   0x81b5bb postgres PostgresMain + 0x233b
17   0x7bcc3d postgres <symbol not found> + 0x7bcc3d
18   0x7be45a postgres PostmasterMain + 0xb5a
19   0x4c3c13 postgres main + 0x3b3
20   0x7fa10a186445 libc.so.6 __libc_start_main + 0xf5
21   0x4c417f postgres <symbol not found> + 0x4c417f
"

**Comment by asimrp** [comment]
Do you have a repro?  I haven't looked into the stack trace in detail yet but a repro based on a few SQL statements will go a long way.

**Comment by lyndenzhang** [comment]
[public.test_percentile.sql.gz](https://github.com/greenplum-db/gpdb/files/2232489/public.test_percentile.sql.gz)

Attached is the script to create a test table. I have found it's probably not caused by number of records involved but by the actual distribution of the value. The sql to test is

select 
percentile_cont(.5) within group (order by volume) 
from  test_percentile

Here is the error I am getting:
select
percentile_cont(.5) within group (order by volume)
from  test_percentile;
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.

**Comment by lyndenzhang** [comment]
Sorry mistakenly closed it, reopen the issue

**Comment by lyndenzhang** [comment]
This bug does not occur to older version GP 4.3. 
Was there a change made to tuplesort_mk recently that introduced this bug? Anyone can help on this?

**Comment by hlinnaka** [comment]
Fixed

**Comment by lyndenzhang** [comment]
Much appreciated!
