### ISSUE TITLE
GPDB stability status

### ISSUE THREAD

**Issue by NB13** [greenplum-db/gpdb#5337]
I don't know better place to ask this question, excuse me if I'm wrong.

Recently I've read this article https://www.ness.com/big-data-101-the-rise-and-fall-of-greenplum-2/ and was very surprised. Can you share your experience about GPDB stability?

**Comment by ivannovick** [comment]
This is not actually a specific bug in GPDB, so i am closing this as a GPDB issue which is for bug reports.  If you want to have a general discussion we can do it on the mailing list. But pleased come with specific questions not just a link.
