### ISSUE TITLE
Potential bug in CdbPathLocus_IsEqual()

### ISSUE THREAD

**Issue by pivotal-ning-yu** [greenplum-db/gpdb#5371]
This was previously discussed on gpdb-dev@, I moved it here for better tracking.

The macro `CdbPathLocus_IsEqual()` is defined like below:

https://github.com/greenplum-db/gpdb/blob/04e39f4a3c116e323c0fc0f47e0c6b8cd790537f/src/include/cdb/cdbpathlocus.h#L144-L147

In L146 we are comparing `(a).partkey_h` with `(b).partkey_oj`, this might be a typo.

Luckily it will not cause runtime error most of time. There are 3 callers to this macro.

In the first caller `b` is narrowed to bottleneck types (Entry and singleQE) so `partkey_h` and `partkey_oj` will both be NULL:
https://github.com/greenplum-db/gpdb/blob/04e39f4a3c116e323c0fc0f47e0c6b8cd790537f/src/backend/cdb/cdbpath.c#L100-L104

In the second caller it's similar, at least one of `a` or `b` is narrowed to SegmentGeneral so it will also have NULL partkeys:
https://github.com/greenplum-db/gpdb/blob/04e39f4a3c116e323c0fc0f47e0c6b8cd790537f/src/backend/cdb/cdbpath.c#L925-L932

The third caller is in function `cdbpathlocus_compare()`, the macro is used as a fast path, if the macro returns false a complete deep comparison will be performed:
https://github.com/greenplum-db/gpdb/blob/04e39f4a3c116e323c0fc0f47e0c6b8cd790537f/src/backend/cdb/cdbpathlocus.c#L132-L133

**Comment by hlinnaka** [comment]
The `partkey_oj` got refactored away in commit 882958da5e, so this bug doesn't exist anymore. Closing.

**Comment by pivotal-ning-yu** [comment]
Cool, thanks for the fix.
