### ISSUE TITLE
Incorrect query results with join on distribution key column that is an array

### ISSUE THREAD

**Issue by hlinnaka** [greenplum-db/gpdb#5467]
### Greenplum version or build
master

### Step to reproduce the behavior

Create test tables:
```
create table a (n numeric[]) distributed by (n);

insert into a values 
   ('{1.0}'),
   ('{2.0}'),
   ('{3.0}'),
   ('{4.0}'),
   ('{5.0}');

create table b (n numeric[]) distributed by (n);

insert into b values
   ('{1.0000}'),
   ('{2.0000}'),
   ('{3.0000}'),
   ('{4.0000}'),
   ('{5.0000}');
```

With ORCA, the following join produces incorrect results:
```
postgres=# set optimizer=off;
SET
postgres=# select * from a,b where a.n = b.n;
   n   |    n     
-------+----------
 {1.0} | {1.0000}
 {4.0} | {4.0000}
 {2.0} | {2.0000}
 {5.0} | {5.0000}
 {3.0} | {3.0000}
(5 rows)

postgres=# set optimizer=on;
SET
postgres=# select * from a,b where a.n = b.n;
   n   |    n     
-------+----------
 {1.0} | {1.0000}
(1 row)
```

The trick here is that e.g. `{2.0}` and `{2.0000}` should be considered equal, even though their on-disk representation, and the distribution hash value computed by cdbhash() are different.

I'm surprised we allow using numeric[] as a distribution key column in the first place. If the planner can't assume that (a = b) => (cdbhash(a) = cdbhash(b)), what's the point of using such a distribution key?  (I'm also surprised that the planner doesn't also get fooled by that.)

**Comment by d** [comment]
This is introduced in #4940 . However, a similar issue already exists in 5.x release series and even earlier: `float4[]`. To steal from my own comment(https://github.com/greenplum-db/gpdb/pull/4940#issuecomment-413067538) on #4940 

```sql
CREATE TEMP TABLE foo(a int, b float[]) DISTRIBUTED BY (b);
INSERT INTO foo VALUES (1, '{-0, -0}'::float[]), (1, '{-0, 0}'::float[]);

CREATE TEMP TABLE bar(c int, d float[]) DISTRIBUTED BY (c);
INSERT INTO bar(c,d) SELECT a, b FROM foo;
SELECT gp_segment_id, b, a FROM foo;
set optimizer to off;
SELECT distinct(b) FROM foo;
SELECT distinct(d) FROM bar;
```

This is the output I got (with 3 segments):
```
CREATE TEMP TABLE foo(a int, b float[]) DISTRIBUTED BY (b);
CREATE TABLE
INSERT INTO foo VALUES (1, '{-0, -0}'::float[]), (1, '{-0, 0}'::float[]);
INSERT 0 2
CREATE TEMP TABLE bar(c int, d float[]) DISTRIBUTED BY (c);
CREATE TABLE
INSERT INTO bar(c,d) SELECT a, b FROM foo;
INSERT 0 2
SELECT gp_segment_id, b, a FROM foo;
 gp_segment_id |    b    | a 
---------------+---------+---
             1 | {-0,-0} | 1
             0 | {-0,0}  | 1
(2 rows)

set optimizer to off;
SET
SELECT distinct(b) FROM foo;
    b    
---------
 {-0,-0}
 {-0,0}
(2 rows)

SELECT distinct(d) FROM bar;
   d    
--------
 {-0,0}
(1 row)

```

After the Postgres 9.2 merge, I think we made the same mistake with ranges: the current implementation can result in range-typed distribution keys that disperse tuples that are logically equal onto different segments because the hash function yields different hash code

**Comment by hlinnaka** [comment]
This was fixed in master by the big hash opclasses PR.
