### ISSUE TITLE
[NEED] Docker image with MADlib and all other nice stuff

### ISSUE THREAD

**Issue by Extarys** [greenplum-db/gpdb#5473]
Where can I get the docker image with all extentions installed? I cannot install under Ubuntu 18.04 for dev. But there is many many docker images for pgdb and they are confusing.

I was looking for a replacement to postgresql but it look more complicated than anything just to install with all the trouble I'm running in.

Thanks!

**Comment by ivannovick** [comment]
thanks for feedback, the project does not have a plan for curated docker images at this time, but there are commercial offerings if you need something like a kubernetes offering etc
