### ISSUE TITLE
XML regression tests fail

### ISSUE THREAD

**Issue by andreasscherbaum** [greenplum-db/gpdb#550]
On my Ubuntu 15.10, the XML regression tests fail which what looks like a difference in the output:

```
*** ./expected/xml.out  2016-03-19 12:07:34.643253193 +0100
--- ./results/xml.out   2016-03-19 12:07:34.667253298 +0100
***************
*** 8,15 ****
  INSERT INTO xmltest VALUES (3, '<wrong');
  ERROR:  invalid XML content
  DETAIL:  Entity: line 1: parser error : Couldn't find end of Start Tag wrong line 1
- <wrong
-       ^
  SELECT * FROM xmltest;
   id |        data        
  ----+--------------------
--- 8,13 ----
***************
*** 62,69 ****
  LINE 1: SELECT xmlconcat('bad', '<syntax');
                                  ^
  DETAIL:  Entity: line 1: parser error : Couldn't find end of Start Tag syntax line 1
- <syntax
-        ^
  SELECT xmlconcat('<foo/>', NULL, '<?xml version="1.1" standalone="no"?><bar/>');
    xmlconcat   
  --------------
--- 60,65 ----

```

Expected output is:

```
INSERT INTO xmltest VALUES (3, '<wrong');
ERROR:  invalid XML content
DETAIL:  Entity: line 1: parser error : Couldn't find end of Start Tag wrong line 1
<wrong
      ^
```

Actual output is:

```
INSERT INTO xmltest VALUES (3, '<wrong');
ERROR:  invalid XML content
DETAIL:  Entity: line 1: parser error : Couldn't find end of Start Tag wrong line 1
```

The exact position where the error occured is not emitted.

**Comment by michaelpq** [comment]
Hint: you are using libxml2 2.9.3.
http://www.postgresql.org/message-id/n3u4b4$kf4$1@ger.gmane.org

**Comment by andreasscherbaum** [comment]
Oh, thanks for the heads-up. I was just logging this issue here because I ran into it during my tests, but this looks like something we will hit across the entire platform.

**Comment by michaelpq** [comment]
You add a alternate output and you will be fine, that's what upstream did.

**Comment by andreasscherbaum** [comment]
You are talking about "085423e3e326da1b52f41aa86126f2a064a7db25", right?
This just adds another expected file, or am I missing something?

**Comment by michaelpq** [comment]
No, that's it.

**Comment by andreasscherbaum** [comment]
Ok, there is one thing I don't understand: how does adding one more "expected" file solve this problem?

**Comment by michaelpq** [comment]
It does not solve it. Postgres just escaped from it until the libxml2 folks clean up their mess, though there is... Er... Little activity regarding that: https://bugzilla.redhat.com/show_bug.cgi?id=1286692

**Comment by andreasscherbaum** [comment]
Basically this patch provides another results file, but leaves the original one in place, right? Will the regression test tool only use the second output, or both, or how does it work?

**Comment by michaelpq** [comment]
pg_regress compares the result generated with all the output files presented, and checks if there is a match. If there is a match, test passes. If not, it would generate a diff using the alternate output file with the less difference.

**Comment by ascherbaum-pivotal** [comment]
Pulse run is clean, as expected:
http://pulse-releng.greenplum.com/browse/projects/ascherbaum-GPDB-master-opt-l1/builds/69043/
