### ISSUE TITLE
Add logging facility to gphdfs

### ISSUE THREAD

**Issue by danielgustafsson** [greenplum-db/gpdb#552]
There is currently no way to emit log messages from gphdfs, see #513 for discussion.

**Comment by lij55** [comment]
Nor does all 'exec' external protocol if don't use STDERR.

**Comment by kongyew** [comment]
Included @lavjain. This issue is due to GPHDFS design that doesn't limit number of queries to HDFS including queries to Kinit.   So, the logging only helps to diagnose the issues but it doesn 't solve the root cause.

**Comment by lavjain** [comment]
GPHDFS is being deprecated starting GPDB 6.0

At this stage, we will honor bug fixes and no features/enhancements will be done on GPHDFS. The customers are strongly encouraged to move to PXF.
