### ISSUE TITLE
Remove hash index test sqls from mb test suite 

### ISSUE THREAD

**Issue by imshubhangi** [greenplum-db/gpdb#5554]
### Problem 
In mb regression test suite there exist test sql to create hash type of index. But as per [this greenplum documentation](https://gpdb.docs.pivotal.io/500/admin_guide/ddl/ddl-index.html), HASH index type is not supported. Hence, such sql can be removed from test suite.  

### Greenplum version or build
$ psql -h localhost -p 15432 -U osboxes -d tstc 
psql (8.3.23)
Type "help" for help.

tstc=# select version(); 
                                                                                       version                                    
                                                   
----------------------------------------------------------------------------------------------------------------------------------
---------------------------------------------------
 PostgreSQL 8.3.23 (Greenplum Database 5.0.0 build dev) on x86_64-pc-linux-gnu, compiled by GCC gcc (GCC) 4.8.5 20150623 (Red Hat 
4.8.5-28), 64-bit compiled on Jul  3 2018 11:06:40
(1 row)

### OS version and uname -a
$ cat /etc/redhat-release 
CentOS Linux release 7.4.1708 (Core) 
$ uname -a 
Linux osboxes 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

### Expected behavior
Unsupported sql should not be in test suite

### Actual behavior
Unsupported sql exists in test suite 

### Step to reproduce the behavior
Compile and build
cd depends
./configure
make
make install_local
cd ..
LD_LIBRARY_PATH=/home/osboxes/greenplum-db/gpdb_5.5_new_ssl/depends/build/lib ./configure --with-libraries=/home/osboxes/greenplum-db/gpdb_5.5_new_ssl/depends/build/lib --with-includes=/home/osboxes/greenplum-db/gpdb_5.5_new_ssl/depends/build/include --with-perl --with-python --with-libxml --with-gssapi --enable-pxf --enable-tap-tests --prefix=/usr/local/gpdb
make -j8
make -j8 install
make create-demo-cluster
cd src/test/mb/
sh ./mbregress.sh

**Comment by hlinnaka** [comment]
Commit 690910df85 memorized the "hash indexes are not supported" errors in the expected output, so the tests are passing now. Closing.
