### ISSUE TITLE
FOR STATEMENT trigger is not working

### ISSUE THREAD

**Issue by xiong-gang** [greenplum-db/gpdb#5630]
### Greenplum version or build
5X_STABLE and master

### OS version and uname -a
Linux 3a4f5b116729 3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

### Expected behavior
NOTICE:  trigger_func(<NULL>) called: action = INSERT, when = BEFORE, level = STATEMENT
NOTICE:  trigger_func(<NULL>) called: action = INSERT, when = AFTER, level = STATEMENT
INSERT 0 2
### Actual behavior
INSERT 0 2
### Step to reproduce the behavior

CREATE TABLE main_table (a int, b int);

CREATE FUNCTION trigger_func() RETURNS trigger LANGUAGE plpgsql NO SQL AS '
BEGIN
    RAISE NOTICE ''trigger_func(%) called: action = %, when = %, level = %'', TG_ARGV[0], TG_OP, TG_WHEN, TG_LEVEL;
    RETURN NULL;
END;';

CREATE TRIGGER before_ins_stmt_trig BEFORE INSERT ON main_table
FOR EACH STATEMENT EXECUTE PROCEDURE trigger_func('before_ins_stmt');

CREATE TRIGGER after_ins_stmt_trig AFTER INSERT ON main_table
FOR EACH STATEMENT EXECUTE PROCEDURE trigger_func('after_ins_stmt');

INSERT INTO main_table values(1,1),(1,1);

**Comment by Eulerizeit** [comment]
triggers aren't supported in Greenplum specifically because we don't have a mechanism for the segment and the master to message outside of the dispatch code.
