### ISSUE TITLE
When I set new tablespace for a database, the directory of db doesn't move to the new place

### ISSUE THREAD

**Issue by gfphoenix78** [greenplum-db/gpdb#5643]
### Greenplum version or build
master branch
### OS version and uname -a
Linux  3.10.0-862.11.6.el7.x86_64 #1 SMP Tue Aug 14 21:49:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
### Installation information ( pg_config )
BINDIR = /usr/local/gpdb/bin
DOCDIR = /usr/local/gpdb/share/doc/postgresql
HTMLDIR = /usr/local/gpdb/share/doc/postgresql
INCLUDEDIR = /usr/local/gpdb/include
PKGINCLUDEDIR = /usr/local/gpdb/include/postgresql
INCLUDEDIR-SERVER = /usr/local/gpdb/include/postgresql/server
LIBDIR = /usr/local/gpdb/lib
PKGLIBDIR = /usr/local/gpdb/lib/postgresql
LOCALEDIR = /usr/local/gpdb/share/locale
MANDIR = /usr/local/gpdb/share/man
SHAREDIR = /usr/local/gpdb/share/postgresql
SYSCONFDIR = /usr/local/gpdb/etc/postgresql
PGXS = /usr/local/gpdb/lib/postgresql/pgxs/src/makefiles/pgxs.mk
CONFIGURE = '--prefix=/usr/local/gpdb' '--with-gssapi' '--with-pgport=5432' '--with-libedit-preferred' '--with-perl' '--with-python' '--with-openssl' '--with-pam' '--with-krb5' '--enable-cassert' '--enable-debug' '--enable-debugbreak' '--enable-depend' '--with-libxml' '--disable-orca' 'CFLAGS=-O0 -g3'
CC = gcc
CPPFLAGS = -D_GNU_SOURCE -I/usr/local/gpdb/include
CFLAGS = -O0 -g3 -std=gnu99 -Wall -Wmissing-prototypes -Wpointer-arith -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fno-aggressive-loop-optimizations -Wno-unused-but-set-variable -Wno-address -g -ggdb -Werror=uninitialized -Werror=implicit-function-declaration -I/usr/local/gpdb/include
CFLAGS_SL = -fpic
LDFLAGS = -Wl,--as-needed -Wl,-rpath,'/usr/local/gpdb/lib',--enable-new-dtags -L/usr/local/gpdb/lib
LDFLAGS_EX =
LDFLAGS_SL =
LIBS = -lpgport -lxml2 -lpam -lrt -lkrb5 -lcom_err -lgssapi_krb5 -lcrypt -ldl -lm -L/usr/local/gpdb/lib
VERSION = PostgreSQL 9.2beta2
### Expected behavior
the directory of database will be moved to the new directory of the specific tablespace
### Actual behavior
the directory of database is not moved, and some data(relative too small than the amount of database `test1`) is generated
### Step to reproduce the behavior
1.  `create database test1;`
2. `create table a(id int, name text);` // under database test1
3. insert data into table a
4. create tablespace testsp location _new_place_
5. switch to other database
6. `alter database test1 set tablespace testsp`

**Comment by ashwinstar** [comment]
Thanks for reporting. Yes, I see the problem. Seems for QD it's working properly to move the database directory but for QEs it's not. We will fix it.

**Comment by ashwinstar** [comment]
Ohhh this is really interesting one to fix given how moving tablespace works. Currently, the command is not even dispatched to segments. On QD, it copies the contents from old directory to new directory (reference `movedb()`), commits the transaction and then deletes the old directory.

In MPP context, will have to modify this to do in 2 stages then.
1. QD and QEs copy the directories and perform 2PC
1. Delete the directories
I am not sure why upstream didn't use the smgr pending deletes list concept to associate the delete with the commit itself. Same as table drops. That would possibly avoid the need for 2 stages.

**Comment by asimrp** [comment]
> I am not sure why upstream didn't use the smgr pending deletes list concept to associate the delete with the commit itself. Same as table drops. That would possibly avoid the need for 2 stages.

Indeed it's a bit counter intuitive.  Create/drop database cannot be performed within a transaction but `alter database set tablespace` can be.  One reason why pending deletes is not used could be this: pending deletes has no way to record directories and adding one entry for each file within the tablespace seems overkill.
