### ISSUE TITLE
gpcrondump hang up !!

### ISSUE THREAD

**Issue by ChrisYuan** [greenplum-db/gpdb#5658]
### Greenplum version or build
greenplum-db-5.10.0
### OS version and uname -a
Red Hat Enterprise Linux Server release 7.4 (Maipo)
Linux ps1 3.10.0-693.el7.x86_64 #1 SMP Thu Jul 6 19:56:57 EDT 2017 x86_64 x86_64 x86_64 GNU/Linux
### Installation information ( pg_config )
BINDIR = /usr/local/greenplum-db-5.10.0/bin
DOCDIR = /usr/local/greenplum-db-5.10.0/doc/postgresql
HTMLDIR = /usr/local/greenplum-db-5.10.0/doc/postgresql
INCLUDEDIR = /usr/local/greenplum-db-5.10.0/include
PKGINCLUDEDIR = /usr/local/greenplum-db-5.10.0/include/postgresql
INCLUDEDIR-SERVER = /usr/local/greenplum-db-5.10.0/include/postgresql/server
LIBDIR = /usr/local/greenplum-db-5.10.0/lib
PKGLIBDIR = /usr/local/greenplum-db-5.10.0/lib/postgresql
LOCALEDIR = /usr/local/greenplum-db-5.10.0/share/locale
MANDIR = /usr/local/greenplum-db-5.10.0/man
SHAREDIR = /usr/local/greenplum-db-5.10.0/share/postgresql
SYSCONFDIR = /usr/local/greenplum-db-5.10.0/etc/postgresql
PGXS = /usr/local/greenplum-db-5.10.0/lib/postgresql/pgxs/src/makefiles/pgxs.mk
CC = gcc -m64
CPPFLAGS = -D_GNU_SOURCE -I/usr/local/greenplum-db-5.10.0/include
CFLAGS = -m64 -O3 -fargument-noalias-global -fno-omit-frame-pointer -g -std=gnu99 -Wall -Wmissing-prototypes -Wpointer-arith -Wendif-labels -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fno-aggressive-loop-optimizations -Wno-unused-but-set-variable -Wno-address -I/usr/local/greenplum-db-5.10.0/include
CFLAGS_SL = -fpic
LDFLAGS = -Wl,--as-needed -Wl,-rpath,'/usr/local/greenplum-db-devel/lib',--enable-new-dtags -L/usr/local/greenplum-db-5.10.0/lib
LDFLAGS_SL =
LIBS = -lpgport -lgpopt -lnaucrates -lgpdbcost -lgpos -lxerces-c -lxml2 -lpam -lrt -lkrb5 -lcom_err -lgssapi_krb5 -lcrypt -ldl -lm -lrt -L/usr/local/greenplum-db-5.10.0/lib
VERSION = PostgreSQL 8.3.23
### Expected behavior
I executed “gpcrondump -x postgres”
Expected finishing backup the postgres database then I can find the backfiles.
### Actual behavior
Actually after executing “gpcrondump -x postgres”,the backup process is hanging up, wait for a longtime but no response, only master backfile is there, no datafile is backed.
### Step to reproduce the behavior
Usually execute gpcrondump -x postgres, whether there is data on postgres.

**Comment by chrishajas** [comment]
gpcrondump launches independent pg_dump processes on each of the segments, so even though it may appear to be hanging, it may actually be working (albeit slowly and with no indication to the user). You can query pg_stat_activity on each segment to check whether it is still working.

Did this just start happening? If you're just testing gpcrondump, we'd recommend using our new utility, gpbackup (https://github.com/greenplum-db/gpbackup) which has better progress indication and is under active development. gpcrondump is being deprecated in favor of gpbackup.

**Comment by ChrisYuan** [comment]
OK, I will try gpbackup. I wonder it is a big issue, because I have found this appear on some of the GPDB5x release, no matter, I will closed this issue.
