### ISSUE TITLE
Assertion failure on reindex within transaction

### ISSUE THREAD

**Issue by hlinnaka** [greenplum-db/gpdb#567]
postgres=# create table bar(id int4 primary key);
NOTICE:  CREATE TABLE / PRIMARY KEY will create implicit index "bar_pkey" for table "bar"
CREATE TABLE
postgres=# begin;
BEGIN
postgres=# reindex table bar;
FATAL:  Unexpected internal error (indexcmds.c:1653)
DETAIL:  FailedAssertion("!(!IsTransactionOrTransactionBlock())", File: "indexcmds.c", Line: 1653)
HINT:  Process 18515 will wait for gp_debug_linger=120 seconds before termination.

The qp_gist_indexes4 regression test also triggers that, when you run installcheck-good with assertions enabled.

**Comment by asimrp** [comment]
I saw this failure too, during my reindex experiments.  Ideally, the transaction should abort with an error, similar to how vacuum behaves.  Let me fix it.

**Comment by asimrp** [comment]
Thanks to Ashwin for pointing out, REINDEX should not be restricted to only run outside transaction block.  I will remove the assertion, which anyway is removed in optimized builds.

`ReindexRelationList()` wraps reindex operation within `StartTransactionCommand()` and `CommitTransactionCommand()`.  Inside a transaction block, these operations do not change state of the running transaction.  So it's safe to remove the assertion.
