### ISSUE TITLE
Please help, undefined reference when make. Thanks.

### ISSUE THREAD

**Issue by MengsD** [greenplum-db/gpdb#5682]
### Greenplum version or build
le*, int)'
gpopt/SUBSYS.o: In function `gpos::CSyncHashtableIter<gpos::CCacheEntry<gpmd::IMDCacheObject*, gpopt::CMDKey*>, gpopt::CMDKey*, gpos::CSpinlockRanked<20u> >::~CSyncHashtableIter()':
(.text._ZN4gpos18CSyncHashtableIterINS_11CCacheEntryIPN4gpmd14IMDCacheObjectEPN5gpopt6CMDKeyEEES7_NS_15CSpinlockRankedILj20EEEED2Ev[_ZN4gpos18CSyncHashtableIterINS_11CCacheEntryIPN4gpmd14IMDCacheObjectEPN5gpopt6CMDKeyEEES7_NS_15CSpinlockRankedILj20EEEED5Ev]+0x130): undefined reference to `gpos::UlpExchangeAdd(unsigned long volatile*, int)'
gpopt/SUBSYS.o:(.text._ZN4gpos18CSyncHashtableIterINS_11CCacheEntryIPN4gpmd14IMDCacheObjectEPN5gpopt6CMDKeyEEES7_NS_15CSpinlockRankedILj20EEEED2Ev[_ZN4gpos18CSyncHashtableIterINS_11CCacheEntryIPN4gpmd14IMDCacheObjectEPN5gpopt6CMDKeyEEES7_NS_15CSpinlockRankedILj20EEEED5Ev]+0x14b): more undefined references to `gpos::UlpExchangeAdd(unsigned long volatile*, int)' follow
gpopt/SUBSYS.o: In function `gpopt::CAutoMDAccessor::~CAutoMDAccessor()':
(.text._ZN5gpopt15CAutoMDAccessorD2Ev[_ZN5gpopt15CAutoMDAccessorD5Ev]+0xc6): undefined reference to `gpos::clib::PvMemCpy(void*, void const*, unsigned long)'
gpopt/SUBSYS.o: In function `gpopt::CAutoMDAccessor::~CAutoMDAccessor()':
(.text._ZN5gpopt15CAutoMDAccessorD2Ev[_ZN5gpopt15CAutoMDAccessorD5Ev]+0xf4): undefined reference to `gpos::CMemoryPoolManager::m_pmpm'
gpopt/SUBSYS.o: In function `gpopt::CAutoMDAccessor::~CAutoMDAccessor()':
(.text._ZN5gpopt15CAutoMDAccessorD2Ev[_ZN5gpopt15CAutoMDAccessorD5Ev]+0x150): undefined reference to `gpos::UlpExchangeAdd(unsigned long volatile*, int)'
gpopt/SUBSYS.o: In function `gpopt::CAutoMDAccessor::~CAutoMDAccessor()':
(.text._ZN5gpopt15CAutoMDAccessorD2Ev[_ZN5gpopt15CAutoMDAccessorD5Ev]+0x162): undefined reference to `gpos::UlpExchangeAdd(unsigned long volatile*, int)'
gpopt/SUBSYS.o: In function `gpopt::CAutoMDAccessor::~CAutoMDAccessor()':
(.text._ZN5gpopt15CAutoMDAccessorD2Ev[_ZN5gpopt15CAutoMDAccessorD5Ev]+0x17a): undefined reference to `gpos::UlpExchangeAdd(unsigned long volatile*, int)'
gpopt/SUBSYS.o: In function `gpopt::CAutoMDAccessor::~CAutoMDAccessor()':
(.text._ZN5gpopt15CAutoMDAccessorD2Ev[_ZN5gpopt15CAutoMDAccessorD5Ev]+0x1a7): undefined reference to `gpos::UlpExchangeAdd(unsigned long volatile*, int)'
gpopt/SUBSYS.o: In function `gpopt::CAutoMDAccessor::~CAutoMDAccessor()':
(.text._ZN5gpopt15CAutoMDAccessorD2Ev[_ZN5gpopt15CAutoMDAccessorD5Ev]+0x244): undefined reference to `gpos::UlpExchangeAdd(unsigned long volatile*, int)'
gpopt/SUBSYS.o:(.text._ZN5gpopt15CAutoMDAccessorD2Ev[_ZN5gpopt15CAutoMDAccessorD5Ev]+0x260): more undefined references to `gpos::UlpExchangeAdd(unsigned long volatile*, int)' follow
collect2: error: ld returned 1 exit status

**Comment by asimrp** [comment]
Please try installing the latest Orca, then `make distclean` in gpdb and try building again.
