### ISSUE TITLE
function pg_relation_size() returns ERROR

### ISSUE THREAD

**Issue by BaiShaoqi** [greenplum-db/gpdb#5684]
On MASTER  (latested commit: 7ebc17ad5b2b509c2777ef83ae7c8e702c63ef49):

```
create table files ( code char(5), title varchar(40), did integer);

insert into files values ('UA502', 'Bananas', 105);

select pg_relation_size('files');
ERROR:  query plan with multiple segworker groups is not supported
HINT:  likely caused by a function that reads or modifies data in a distributed table
CONTEXT:  SQL statement "select sum(pg_relation_size('public.files'))::int8 from gp_dist_random('gp_id');"
SQL statement "select sum(pg_relation_size('public.files'))::int8 from gp_dist_random('gp_id');"
```

**Comment by hlinnaka** [comment]
Works for me. Is there  any other information you can give?

**Comment by hlinnaka** [comment]
I wasn't able to reproduce this, but it got me digging in the sources, and I found a bunch of other issues with those functions. See PR https://github.com/greenplum-db/gpdb/pull/5694. It refactors the way the size functions are dispatched, so it might well fix this issue as well, whatever it was. Please take a look.

**Comment by BaiShaoqi** [comment]
Very sorry to make the noise,  double checked, it does not happen again.

I would close it

And your PR you mentioned is a good learning stuff for me
