### ISSUE TITLE
gpfdist binary: protocol headers should be case insensitive (rfc2616)

### ISSUE THREAD

**Issue by mwright-pivotal** [greenplum-db/gpdb#5689]
### Expected behavior
X-Gp-Proto should be handled same way as X-GP-PROTO.   A reverse proxy like NGINX in front of GPFDIST may cause this

### Actual behavior
 400 Bad Request 

### Step to reproduce the behavior
send lower case header values to GPFDIST via curl

### Fix
in gpfdist.c change string comparisons starting at line 3258 to be case insensitive e.g.

......
                else if (0 == **strcasecmp**("X-GP-PROTO", r->in.req->hname[i]))
                          gp_proto = r->in.req->hvalue[i];

**Comment by danielgustafsson** [comment]
Fixed in commit cfcf035c47e318e0ddc691ea7fe5ed1dfc3dece9, thanks for the report!
