### ISSUE TITLE
How is it possible for greenplum to take so much disk space? Thanks for your help.

### ISSUE THREAD

**Issue by MengsD** [greenplum-db/gpdb#5719]
- Greenplum version: 5.9.0
- OS version: ubuntu 16.04
- greenplum runs singlenode
- question
  I try to load some csv files into database using gpload. The **csv files are 5.3G** in total (`command: du -sh `). After loading, **I `du -sh` the primary directory, and it displays 8.3G**. How is it possible?  Will the database replicate data by default ? Thanks very much.
- more details
   * table schema is 
    > drop table if exists people_hotel.data_load;
    > create table people_hotel.data_load (
    > event_id bigint,
    > time bigint,
    > object bigint,
    > city_id bigint,
    > longtitude float8,
    > latitude float8
    > )
    > distributed by (event_id)
    * #records in total is 
       > 1.0*10^8  
there are 6 fields, each is in 8 bytes,  1.0*10^8 records  are 4.5G binary bytes. that's far away from 8.3G.

   
There are some configurations:
   * gpload.yaml
     >VERSION: 1.0.0.1
>DATABASE: past_exp_one_primary
>USER: user
>HOST: ubuntu
>PORT: 5432

>GPLOAD:
>   INPUT:
>    - SOURCE:
>         LOCAL_HOSTNAME:
>           - ubuntu
>         PORT: 8081
>         FILE:
>           - /home/...*/data/*
>    - FORMAT: csv
>    - QUOTE: '"'
>    - ERROR_LIMIT: 50000
>    - ERROR_TABLE: people_hotel.load_errors
>   OUTPUT:
>    - TABLE: people_hotel.data_load
>    - MODE: INSERT
>   PRELOAD:
>    - TRUNCATE: true

    * gpinitsystem_singlenode
   >declare -a DATA_DIRECTORY=(/home/...*.../primary)

- Step to reproduce the behavior
>source $greenplum_setup_home/greenplum_path.sh 
>gpssh-exkeys -f hostlist_singlenode
>gpinitsystem -c gpinitsystem_singlenode
>
>dropdb $database
>createdb $database
>
>psql $database
>DROP SCHEMA IF EXISTS $schema_name CASCADE
>CREATE SCHEMA $schema_name;
>SET SEARCH_PATH TO $schema_name, public, pg_catalog, gp_toolkit;
>ALTER ROLE dingmengsu SET search_path TO $schema_name, public, pg_catalog, gp_toolkit
>\i exp-load.sql
>\q
>
>
>ps -A | grep gpfdist
>killall gpfdist
>
>gpload -f gpload.yaml -l gpload.log

**Comment by asimrp** [comment]
What's the output of
```SQL
select pg_size_pretty(pg_relation_size('people_hotel.data_load'));
```

**Comment by MengsD** [comment]
@asimrp 
**It shows 7116M.**  How to explain it ?

past_exp_one_primary=# select pg_size_pretty(pg_relation_size('people_hotel.data_load'));
 pg_size_pretty 
----------------
 7116 MB
(1 row)

**Comment by hlinnaka** [comment]
That sounds about right to me. In addition to the actual columns, each row has a tuple header, which is about 32 bytes.
