### ISSUE TITLE
Create partition table is very slow.

### ISSUE THREAD

**Issue by MengsD** [greenplum-db/gpdb#5723]
I run psql to create a partition table. 2 hours are gone, but it doesn't complete.  What's the problem? How to speed up? Thanks very much.

My command is 
>DROP SCHEMA IF EXISTS people_hotel CASCADE;
>CREATE SCHEMA people_hotel;
>SET SEARCH_PATH TO people_hotel, public, pg_catalog, gp_toolkit;
>ALTER ROLE dingmengsu SET search_path TO people_hotel, public, pg_catalog, gp_toolkit;
>
>-- create table event, partition by time and object
>drop table if exists people_hotel.event;
>create table people_hotel.event (
>event_id bigint,
>time bigint,
>object bigint,
>loc_id integer
>)
>distributed by (event_id)
>PARTITION BY RANGE(time)
>  SUBPARTITION by range(object)
>  SUBPARTITION TEMPLATE (
>    START (0) INCLUSIVE END (100000000) EXCLUSIVE EVERY (10000),
>    DEFAULT SUBPARTITION other_object
>  )
>(START (bigint '1527811200000') INCLUSIVE
>   END (bigint '1544975684280') INCLUSIVE
>   EVERY (bigint '2592000000'),
>   DEFAULT PARTITION other_time
>);

- greenplum runs with 1 master and 2 segment hosts, each host have 10 instances( 10 primary directory)
- Greenplum version: 5.9.0
- OS version: ubuntu 16.04

**Comment by Eulerizeit** [comment]
How many partitions and subpartitions is this creating?

Rob

**Comment by MengsD** [comment]
@Eulerizeit 
- number of partition is 8, which is supposed to be decided by the cluse 
   `(START (bigint '1527811200000') INCLUSIVE
END (bigint '1544975684280') INCLUSIVE
EVERY (bigint '2592000000')`

- number of subpartition is 10000, which is supposed to be decided by the cluse
 `START (0) INCLUSIVE END (100000000) EXCLUSIVE EVERY (10000)`.

**Comment by d** [comment]
What is the storage set-up you have? Are you using directly attached storage or SAN? If DAS, are those SATA or SAS disks? How many interfaces are there on each server? If SAN, what connection type and what bandwidth is that fiber channel?
The number of tables we are creating on each physical host is (primary + mirror): `10001 * 8 * 20 = 1,600,160`. At first glance this is very heavy I/O to create nearly two million tables at one bang on each host.

Maybe this is working as expected?

Jesse
