### ISSUE TITLE
how can i set max_prepared_transactions  bigger than 1000

### ISSUE THREAD

**Issue by lygn128** [greenplum-db/gpdb#5772]
###     ubuntu 16.04

if i set max_prepared_transactions=5000 then  i would get a err:

            _**2018-09-15 06:25:38.166962 GMT,,,p8826,th1249580864,,,,0,,,seg-1,,,,,"FATAL","22023","5000 is outside the valid range for parameter ""max_prepared_transactions"" (1 .. 1000)",,,,,,,,"set_config_option","guc.c",4882,**_

if i set 1000 then  would encounter the err in with pgadmin:

            **_FATAL: the limit of 1000 distributed transactions has been reached. (cdbtm.c:2569) DETAIL: The global user configuration (GUC) server parameter max_prepared_transactions controls this limit. server closed the connection unexpectedly This probably means the server terminated abnormally before or while processing the request._**

how to solve the problem?  thank you very much.

**Comment by asimrp** [comment]
@lygn128 under normal circumstances, you shouldn't need to increase `max_prepared_transactions`.  Looks like your GPDB instance went through a crash and the crash recovery failed with this error.  Is that correct?  Can you look into QD logs (`$MASTER_DATA_DIRECTORY/pg_log/*.csv`) for a stack trace / relevant messages?

**Comment by aa77m7a** [comment]
Maintenance of mobile phones

**Comment by asimrp** [comment]
Are you still facing this problem, @lygn128?
