### ISSUE TITLE
Concurrently update the same tuple's hash col will lead to more tuples.

### ISSUE THREAD

**Issue by kainwen** [greenplum-db/gpdb#5882]
### Greenplum version or build

Master branch(with update hash distributed columns enable and with GDD)

### Step to reproduce the behavior

Isolation2 style scripts:

```sql
create table t(c1 int, c2 int);
CREATE
insert into t select i, i from generate_series(1, 10)i;
INSERT 10

select count(*) from t;
count
-----
10
(1 row)

1: begin;
BEGIN
2: begin;
BEGIN

1: update t set c1 = c1 + 1 where c1 = 1;
UPDATE 1
2&: update t set c1 = c1 + 1 where c1 = 1;  <waiting ...>

1: end;
END
2<:  <... completed>
UPDATE 1
2: end;
END

select count(*) from t;
count
-----
11
(1 row)
```

### Reason

When implemented splitupdate plan to enable updating hash-cols, GDD is not in the repo. That is any update statement will hold the ExclusiveLock for the table. No concurrently updating is allowed.

As GDD merged in the master branch, we do not upgrade the lock. Then the splitupdate plan is not safe for concurrency.

**Comment by gaos1** [comment]
fixed by https://github.com/greenplum-db/gpdb/pull/6828
