### ISSUE TITLE
Pay attention to the parameters order of cdb_randint

### ISSUE THREAD

**Issue by zhangjackey** [greenplum-db/gpdb#5899]
The parameter order of cdb_randint is (upper, lower):

https://github.com/greenplum-db/gpdb/blob/47369d3c1d3347cd5724c4cdb6bd68a2c19c4d37/src/include/cdb/cdbutil.h#L32-L34

But there are some codes call this function by the order (lower, upper):

https://github.com/greenplum-db/gpdb/blob/47369d3c1d3347cd5724c4cdb6bd68a2c19c4d37/src/backend/cdb/cdbhash.c#L150

https://github.com/greenplum-db/gpdb/blob/47369d3c1d3347cd5724c4cdb6bd68a2c19c4d37/src/backend/cdb/cdbutil.c#L1273

If we input parameter in the order (lower, upper), the results are not uniformly distributed:

```
#include <stdio.h>
#include <math.h>

#define MAX_RANDOM_VALUE 0x7FFFFFFF

/* cdb_rand returns a random float value between 0 and 1 inclusive */
#define cdb_rand() ((double) random() / (double) MAX_RANDOM_VALUE)

/* cdb_randint returns integer value between lower and upper inclusive */
#define cdb_randint(upper,lower) \
    ( (int) floor( cdb_rand()*(((double)(upper)-(double)(lower))+0.999999) ) + (lower) )

int main(int argc, char** argv)
{
    unsigned long i = 10000000000;

    int arr1[11] = {0};
    memset(arr1, 0, sizeof(arr1));

    while(i-- > 0)
    {
        int idx = cdb_randint(0,10);
        arr1[idx] = arr1[idx] + 1;
    }

    for(i = 0; i<11; i++)
        printf("%d: %d \n", i, arr1[i]);

    return 1;
}
```

The result:

```
0: 1015
1: 1111128315
2: 1111142419
3: 1111048237
4: 1111115769
5: 1111105419
6: 1111077248
7: 1111115345
8: 1111118167
9: 1111148065
10: 1
```

**Comment by d** [comment]
I don't understand why that's an issue, by simple math, `cdb_randint(0, 10)` should provide as good (uniform) a distribution as `cdb_randint(10, 0)`, no?

**Comment by pivotal-ning-yu** [comment]
@d let's see the case when upper is 10 and lower is 0, cdb_randint() is expanded to:

```C
(int) floor( cdb_rand()*((10-0)+0.999999) ) + 0;
(int) floor( cdb_rand()*10.999999 );
```

`cdb_rand()` returns a double value in [0, 1] so the value passed to `floor()` is within range [0, 10.999999], so the result of `floor()` is within [0, 10].

When swap upper and lower, upper is 0 and lower is 10, cdb_randint() is expanded to:

```C
(int) floor( cdb_rand()*((0-10)+0.999999) ) + 10;
(int) floor( cdb_rand()*-9.000001 ) + 10;
```

So the value passed to `floor()` is within range [-9.000001, 0], so the result of `floor()` is within [-10, 0], so the final result is within [0, 10]:
- only if `cdb_rand()` returns exactly 0.0 we have the chance to get 10 as the result, as @zhangjackey 's experiment the chance is very low;
- 0 as result also have a low chance the rate is about 1/1000000, which is also proved by @zhangjackey 's experiment.

BTW here is some arithmetic results when x is defined as `double x = -10 + 0.999999;`:
- floor(x): -10.000000;
- floor(x * 0.000001): -1.000000;
- floor(x * 0.999999): -9.000000;
- floor(x * 1e-30): -1.000000;
- floor(x * (1 - 1e-30)): -10.000000;
- floor(x * 1e-300): -1.000000;
- floor(x * 0): -0.000000;

We can see how hard it is to produce the upper & lower values if we pass them in wrong order to cdb_randint();

**Comment by d** [comment]
Oh wow, I didn't pay attention to the `+0.999999` in the original formula, what use does it have? Without that sneaky `+0.999999`, lower and upper are completely symmetric

**Comment by zhangjackey** [comment]
@d  Thanks a lot for your comments. 
If we don't add the 0.999999 in the formula, the result may be equal whatever order we input,  but it is still not uniform distributed, most of the time, it may look like uniform distributed in [lower, upper), but they have a very low opportunity to get the `upper`.

Adding 0.999999 is aimed at giving a equal oppertunity to get the `upper` and the others. For example, we change the formula in the above experiment, then get the result:

```
0: 409947124
1: 409928890
2: 409973120
3: 410158161
4: 410169022
5: 410048641
6: 410146698
7: 410087113
8: 410074263
9: 410121011
10: 37
```

**Comment by hlinnaka** [comment]
`cdb_randint` seems overly complicated. And it's not very well-suited for the callers that use it.

* all callers use 0 as the lower bound.
* multiple-evaluation hazard on 'lower'
* having 'upper' as the first argument, and 'lower' as the second, feels backwards. lower, upper would be a much more natural order.
* Most callers have to do "-1" on the upper bound, because it's inclusive. Exclusive would be more natural for the callers.

I'd suggest that we replace it with a much simpler:
```
/* cdb_randint returns integer value between 0 and upper (exclusive) */
#define cdb_randint(upper)    (random() % (upper))
```

Or just replace all the calls to cdb_randint() with `random() % (upper)` directly. The distribution of that wouldn't be entirely uniform, but would be good enough for all the current callers.

PS. What's going on with the UPPER_VAL constaint, in cdbhash.c? Why isn't the call in cdbhash.c just `h->rrindex = random()`?

PPS. There's also `pg_lrand48()`. Using that would avoid any platform-dependent behavior.
