### ISSUE TITLE
Using ORCA for a partition with rewritten rules causes gp crash

### ISSUE THREAD

**Issue by darthunix** [greenplum-db/gpdb#5913]
### Greenplum version or build
Greenplum 5.8.0

## Summary

It is possible to rewrite rules for an existing table's partition though in a case of partition exchange it is prohibited to use a table with rewritten rules. After adding rules to a partition legacy optimiser returns an error (it is ok) but ORCA causes gp crash.

### Step to reproduce the behavior

```sql
create table t1 (id int, stamp date, amount int)
with (appendonly=false)
distributed by (id)
partition by range (stamp) (
  start ('2016-01-01') end ('2019-01-01') every(interval '1 year'),
  default partition extra
);

select * from pg_partitions where tablename ='t1';
-- rank: 3, partition: t1_1_prt_4

create rule "_RETURN" as on select to t1_1_prt_4 do instead 
select 1 as id, current_date as stamp, 1 as amount;

set optimizer=off;
select * from t1;
-- ERROR:  plan contains range table with relstorage='v' (allpaths.c:346)

set optimizer=on;
select * from t1;
-- [OPT]: Using default search strategy
-- server closed the connection unexpectedly
--         This probably means the server terminated abnormally
--         before or while processing the request.
-- The connection to the server was lost. Attempting reset: Failed.
```

### Expected behavior

There are two ways I think
1. ORCA doesn't cause a gp crash but returns an error
2. A user is prohibited to rewrite rules for a table that acts as a partition

**Comment by kapustor** [comment]
Greenplum 5.11.0 has the same issue - master crashes.

**Comment by bhuvnesh2703** [comment]
PR: https://github.com/greenplum-db/gpdb/pull/6364/files

**Comment by hlinnaka** [comment]
PR 6364 was merged. Has this issue been fully resolved now? Can we close it?
