### ISSUE TITLE
COPY TO/FROM PROGRAM fails if database name contains single quotes

### ISSUE THREAD

**Issue by chrishajas** [greenplum-db/gpdb#5925]
### Greenplum version or build
 PostgreSQL 9.3beta1 (Greenplum Database 6.0.0-alpha.0+dev.11250.gfbcd4b8972 build dev-oss) on x86_64-apple-darwin16.7.0, compiled by Apple LLVM version 8.0.0 (clang-800.0.42.1), 64-bit compiled on Oct  1 2018 15:42:55

Also fails on 5X

###Repro
createdb "TE'ST"
TE'ST=# create table foo (i int);
CREATE TABLE
TE'ST=# copy foo to program 'cat /tmp/foo';
ERROR:  command error message: sh: -c: line 0: unexpected EOF while looking for matching `''
DETAIL:  sh: -c: line 1: syntax error: unexpected end of file

This is only observed on COPY TO/FROM  PROGRAM, regular COPY to/from a file works. COPY TO/FROM PROGRAM ON SEGMENT also does not work. This only occurs if the database name contains single quotes.

**Comment by hlinnaka** [comment]
Pushed a fix to master.

**Comment by hlinnaka** [comment]
Had to revert the fix, so keeping this open..

**Comment by hlinnaka** [comment]
PR #6072, which fixed this issue, was pushed, so closing. Thanks for the report, @chrishajas!
