### ISSUE TITLE
Internal processes consume the slot of connection

### ISSUE THREAD

**Issue by lambgong** [greenplum-db/gpdb#5941]
### Greenplum version or build
5X_STABLE（5.0.0）

### Expected behavior
Whatever i set max_connections, i can actually get （max_connections - 5）connections
For example：
max_connections=250
postgres=\# select count(*) from pg_stat_activity; 
 count 
\-------
    245

max_connections=60
postgres=\# select count(*) from pg_stat_activity;
 count 
\-------
    55

I assume a few of the GPDB internal processes consume the slots，like "seqserver 
process", "sweeper process" and "ftsprobe process" and so on.

### Step to reproduce the behavior
I suggest to fix the math there, so that those auxiliary processes 
don't use up the connection slots.

**Comment by d** [comment]
I don't know what you're talking about. Can you clarify what you mean?

**Comment by lambgong** [comment]
Sorry for my english, this topic here will show more detail
https://groups.google.com/a/greenplum.org/forum/#!topic/gpdb-users/VWPOxRjq1YU

But recently，i find in gpdb
max_connections = superuser_reserved_connections + nosuperuser_connections
and this config superuser_reserved_connections  is 3 default
so this may  answer my questions?

**Comment by lambgong** [comment]
> I don't know what you're talking about. Can you clarify what you mean?

Sorry for my english, this topic here will show more detail
https://groups.google.com/a/greenplum.org/forum/#!topic/gpdb-users/VWPOxRjq1YU

But recently，i find in gpdb
max_connections = superuser_reserved_connections + nosuperuser_connections
and this config superuser_reserved_connections is 3 default
so this may answer my questions?

**Comment by ashwinstar** [comment]
With GPDB6 and forward, the internal processes like FTS, GDD, etc.. have been converted to background workers. With that they no more consume slot from max_connections. So, for GPDB6 and forward max connections available for non-super-user on master is `max_connections - superuser_reserved_connections`. We are not planning to fix the same for GPDB5 hence closing this issue.
