### ISSUE TITLE
update hash columns on segment in utility mode should throw an error.

### ISSUE THREAD

**Issue by kainwen** [greenplum-db/gpdb#5976]
### Greenplum version or build

Master Branch

### Reproduce Steps

We have enabled updating hash columns for GPDB via split-update technique. But if we connect to one segment via Utility mode, and we update the hash columns, we will update things incorrectly.

The following steps are based on a demo-cluster:

```sql
gpadmin=# create table t(c1 int);
NOTICE:  Table doesn't have 'DISTRIBUTED BY' clause -- Using column named 'c1' as the Greenplum Database data distribution key for this table.
HINT:  The 'DISTRIBUTED BY' clause determines the distribution of data. Make sure column(s) chosen are the optimal data distribution key to minimize skew.
CREATE TABLE
gpadmin=# insert into t select * from generate_series(1, 10);
INSERT 0 10
gpadmin=# select gp_segment_id, * from t;
 gp_segment_id | c1
---------------+----
             0 |  4
             0 |  7
             0 |  8
             1 |  2
             1 |  5
             1 |  6
             1 |  9
             1 | 10
             2 |  1
             2 |  3
(10 rows)
```

Then we connect seg2 via Utility mode:

```psql
gpadmin@zlv:~/workspace/gpdb$ PGOPTIONS='-c gp_session_role=utility' psql -p 25434
psql (9.3beta1)
Type "help" for help.

gpadmin=# \d+ t
                          Table "public.t"
 Column |  Type   | Modifiers | Storage | Stats target | Description
--------+---------+-----------+---------+--------------+-------------
 c1     | integer |           | plain   |              |
Has OIDs: no
Distributed by: (c1)

gpadmin=# explain update t set c1 = c1 + 1;
                             QUERY PLAN
---------------------------------------------------------------------
 Update on t  (cost=0.00..3229.75 rows=192600 width=14)
   ->  Split  (cost=0.00..3229.75 rows=192600 width=14)
         ->  Seq Scan on t  (cost=0.00..1303.75 rows=96300 width=14)
 Optimizer: legacy query optimizer
(4 rows)

gpadmin=# update t set c1 = c1 + 1;
UPDATE 2
gpadmin=# select * from t;
 c1
----
  2
  4
(2 rows)

gpadmin=#
```
Last, we access the table from master:

```sql
gpadmin@zlv:~/workspace/gpdb$ psql
psql (9.3beta1)
Type "help" for help.

gpadmin=# select gp_segment_id, * from t;
 gp_segment_id | c1
---------------+----
             0 |  4
             0 |  7
             0 |  8
             2 |  2
             2 |  4
             1 |  2
             1 |  5
             1 |  6
             1 |  9
             1 | 10
(10 rows)

gpadmin=#
```

**Comment by paul-guo-** [comment]
I do not think this is a bug. Utility mode should behave like single postgres which does no sense the distributed logic. People do write via utility mode should take his/her own risk. Developers or users even might expect this sometimes (e.g. debug or fix db).

**Comment by hlinnaka** [comment]
Yeah, this is case of "don't do that". But I think we could fairly easily throw an error. That would be a useful safeguard.

**Comment by Eulerizeit** [comment]
Is this an issue because of how you are doing testing?  

I'm completely ok with the fixed I just want to make sure we aren't trying to leverage utility mode for more than it's intended use. That being fixing a broken segment and nothing more.

**Comment by kainwen** [comment]
@Eulerizeit 
After gpexpanding, numsegments on QD increased, but not those on QEs.  This cause some assert fails introduced by the PR (table can be distributed part of the whole cluster)  on utility mode. We take this change to look into the problem and find this issue.
