### ISSUE TITLE
Support `COPY ( query ) TO ... ON SEGMENT`

### ISSUE THREAD

**Issue by adam8157** [greenplum-db/gpdb#5988]
```
gpadmin=# copy (select * from tbl) to '/tmp/copy_query<SEGID>' on segment;
ERROR:  'COPY (SELECT ...) TO' doesn't support 'ON SEGMENT'.
```

It would be nice to support `COPY ( query ) TO ... ON SEGMENT`, file this feature
request to note, help is welcome.

**Comment by Lakshamana** [comment]
I'm new to opensource contributions, how can I begin to study the project before I can contribute to this open issue?

**Comment by Eulerizeit** [comment]
On Wed, Oct 31, 2018 at 5:32 PM, Lakshamana <notifications@github.com>
wrote:

> I'm new to opensource contributions, how can I begin to study the project
> before I can contribute to this open issue?
>

Absolutely, we have issues marked "Help Wanted". If you have more questions
we have an open source Slack channel you are welcome to ask questions on.
You can find that and other resources on greenplum.org

-- Rob

**Comment by adam8157** [comment]
https://github.com/greenplum-db/gpdb/pull/6077

**Comment by Eulerizeit** [comment]
This was fixed on Master
