### ISSUE TITLE
Does GUC temp_tablespaces work for workfiles or other temp files?

### ISSUE THREAD

**Issue by mkiyama** [greenplum-db/gpdb#6006]
### Greenplum version or build
PostgreSQL 9.3beta1 (Greenplum Database 6.0.0-alpha.0+dev.11291.gc926492178 build commit:c9264921785faf2e097e20003d6e34f5db4035d2
-oss) on x86_64-unknown-linux-gnu, compiled by gcc (GCC) 6.2.0, 64-bit compiled on Oct  5 2018 15:24:12 (with assert checking)

### OS version and uname -a
Linux centos6-gp5-bld 2.6.32-573.el6.x86_64 #1 SMP Thu Jul 23 15:44:03 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

I have a recent GPDB 6 dev build.

The filespace functionality that was used to move temporary files to a tablespace has been removed from GPDB 6.

The GUC temp_tablespaces seems to work with with temporary files, it does not seem to work with workfiles (query spill files).

Is there a way to move temporary files such as workfiles to a non-default tablespace?

Link to feature n GPDB 5.x to docs.
http://gpdb.docs.pivotal.io/5110/admin_guide/ddl/ddl-tablespace.html#topic11

This PR added the temp_tablespaces GUC but did not enable it for temp files.
https://github.com/greenplum-db/gpdb/pull/1603

**Comment by ashwinstar** [comment]
@mkiyama query spill files also can use `temp_tablespace` GUC. Please check latest 6X_STABLE and let us know if don't see that behaviour.

**Comment by mkiyama** [comment]
Thanks for the update
Closing issue
