### ISSUE TITLE
greenpluminitsystem failed

### ISSUE THREAD

**Issue by harshareddy3110** [greenplum-db/gpdb#6009]
### Greenplum version or build 
5:11

### OS version and uname -a 
CentOS: 7
CONFIG
ARRAY_NAME="Greenplum Data Platform"
SEG_PREFIX=gpseg
PORT_BASE=46000

declare -a DATA_DIRECTORY=(/var/data/sdata/primary /var/data/sdata/primary /var/data/sdata/primary /var/data/sdata/primary)
MASTER_HOSTNAME=bm1

MASTER_DIRECTORY=/var/data/mdata

MASTER_PORT=5432

#### Shell utility used to connect to remote hosts.
TRUSTED_SHELL=ssh

#### Maximum log file segments between automatic WAL checkpoints.
CHECK_POINT_SEGMENTS=8

#### Default server-side character set encoding.
ENCODING=UNICODE
MIRROR_PORT_BASE=48000
REPLICATION_PORT_BASE=47000
MIRROR_REPLICATION_PORT_BASE=49000
declare -a MIRROR_DATA_DIRECTORY=(/var/data/sdata/mirror /var/data/sdata/mirror /var/data/sdata/mirror /var/data/sdata/mirror)
DATABASE_NAME=gp
#MACHINE_LIST_FILE=/home/gpadmin/gpconfigs/hostfile_gpinitsystem

**Comment by harshareddy3110** [comment]
greenpluminitsystem throwing 'Failure in segment mirroring; check segment logfile' error. I am getting following error message in segment logs

2018-10-16 10:56:19.510298 UTC,,,p18186,th-1038665856,,,,0,,,seg-1,,,,,"LOG","00000","'set segment state', mirroring role 'mirror role' mirroring state 'sync' segment state 'in fault' filerep state 'fault' process name(pid) 'mirror receiver process(18186)' 'cdbfilerep.c' 'L2444' 'FileRep_SetSegmentState'",,,,,,,0,,"cdbfilerep.c",1824,"Stack trace:
1    0x95dafb postgres errstart (elog.c:521)
2    0xa0f294 postgres FileRep_InsertConfigLogEntryInternal (cdbfilerep.c:1806)
3    0xa1291c postgres FileRepSubProcess_SetState (cdbfilerepservice.c:554)
4    0xa12bf2 postgres FileRepSubProcess_ProcessSignals (cdbfilerepservice.c:281)
5    0xa20935 postgres FileRepMirror_StartReceiver (cdbfilerepmirror.c:179)
6    0xa1305d postgres FileRepSubProcess_Main (cdbfilerepservice.c:819)
7    0xa0d6c6 postgres <symbol not found> (cdbfilerep.c:2667)
8    0xa12563 postgres FileRep_Main (cdbfilerep.c:3605)
9    0x586696 postgres AuxiliaryProcessMain (bootstrap.c:503)
10   0x7d0a1b postgres <symbol not found> (postmaster.c:7395)
11   0x7d539c postgres StartFilerepProcesses (postmaster.c:1622)
12   0x7dee9f postgres doRequestedPrimaryMirrorModeTransitions (primary_mirror_mode.c:1760)
13   0x7d9a61 postgres <symbol not found> (postmaster.c:2465)
14   0x7dbcaa postgres PostmasterMain (postmaster.c:1533)
15   0x4cabc7 postgres main (main.c:206)
16   0x7f84bd5f8445 libc.so.6 __libc_start_main + 0xf5
17   0x4cb11c postgres <symbol not found> + 0x4cb11c

**Comment by danielgustafsson** [comment]
This does not have enough information to do anything with, feel free to re-open if/when you have more data.

**Comment by danielgustafsson** [comment]
Sorry, your comment came between me seeing this and closing, re-opening

**Comment by asimrp** [comment]
The primary and mirror data directories don't seem to be configured correctly, my reference is the cluster config generated by `create-demo-cluster` target.  Can you try making each primary and mirror data directory unique?  Try replacing this
```
declare -a DATA_DIRECTORY=(/var/data/sdata/primary /var/data/sdata/primary /var/data/sdata/primary /var/data/sdata/primary)
```
with 
```
declare -a DATA_DIRECTORY=(/var/data/sdata/primary1 /var/data/sdata/primary2 /var/data/sdata/primary3 /var/data/sdata/primary4)
```
And similarly for mirror data directories.

**Comment by skahler-pivotal** [comment]
I'm going to close this as there hasn't been follow up for a month and I assume it was resolved. 

From the looks of it I would say there was a permissions issue, possibly selinux being on and I don't think it was a directory problem.
