### ISSUE TITLE
Inconsistent and non-deterministic Pulse failures

### ISSUE THREAD

**Issue by ascherbaum-pivotal** [greenplum-db/gpdb#608]
We have inconsistent and non-deterministic Pulse failures, and a number PR to adress the issues. This issue here is to aggregate all of the known issues and PR.

https://github.com/greenplum-db/gpdb/pull/606
https://github.com/greenplum-db/gpdb/pull/603
https://github.com/greenplum-db/gpdb/pull/623

And to confirm that the builds work once these PR are committed into master.

**Comment by ascherbaum-pivotal** [comment]
#603 is closed, but nothing committed.

@xiong-gang Do you have plans to come up with another PR to address the issue?

**Comment by xiong-gang** [comment]
No. I think @edespino or @asubramanya will change test cases instead.

**Comment by asubramanya** [comment]
@ascherbaum-pivotal @xiong-gang I have opened a new PR to update the tests #623

**Comment by ascherbaum-pivotal** [comment]
Added, thanks.

**Comment by ascherbaum-pivotal** [comment]
@edespino Do you have any update for us on the test case changes? Thanks

**Comment by ascherbaum-pivotal** [comment]
@ivannovick Can you please assign this ticket to the approbiate person? Thanks

**Comment by asubramanya** [comment]
@ascherbaum-pivotal The external table tests should be stable now on the master. Is it still failing on the latest master branch ?
