### ISSUE TITLE
Function bodies longer than ~8K aren't dumped correctly

### ISSUE THREAD

**Issue by chrishajas** [greenplum-db/gpdb#6081]
### Greenplum version or build
GPDB master
PostgreSQL 9.4beta1 (Greenplum Database 6.0.0-alpha.0+dev.12998.g1fcfe96a7a build dev-oss)

### Expected behavior
pg_dump dumps the function body, no matter its contents

### Actual behavior
If the body is larger than ~8k, it will dump an incorrect body such as 
```
CREATE FUNCTION increment(i integer) RETURNS integer
    LANGUAGE plpgsql NO SQL
    AS $$�Q$$;
```

### Step to reproduce the behavior
Create a function with the function body larger than ~8k.
```
SET check_function_bodies=false;
CREATE OR REPLACE FUNCTION increment(i integer) RETURNS integer AS $$
        BEGIN
         <insert 8k+ of anything here>
        END;
$$ LANGUAGE plpgsql;
```

This works fine on 5X_STABLE. 

The value in pg_proc's prosrc column does not contain the function body if it's larger than ~8k on master, which is where pg_dump queries to get the function body.

**Comment by hlinnaka** [comment]
Fixed in commit 2395f2fbd9, thanks for the report!
