### ISSUE TITLE
make cluster fails on centos7

### ISSUE THREAD

**Issue by ksasi** [greenplum-db/gpdb#61]
Hi,

It appears make cluster is failing on centos7, below is the standard o/p

make cluster
======================================================================
            ______  _____  ______  _______ _______  _____
           |  ____ |_____] |     \ |______ |  |  | |     |
           |_____| |       |_____/ |______ |  |  | |_____|

----------------------------------------------------------------------

  This is a demo of the Greenplum Database system.  We will create
  a cluster installation with master and 6 segment instances
  (3 primary & 3 mirror).

    GPHOME ................. : /home/kotti/projects/gpdb
    MASTER_DATA_DIRECTORY .. : /home/kotti/projects/gpdb/gpAux/gpdemo/datadirs/qddir/demoDataDir-1

    MASTER PORT (PGPORT) ... : 15432
    SEGMENT PORTS .......... : 25432 25433 25434 25435 25436 25437 25438 25439 25440 25441 25442 25443

  NOTE(s):

    * The DB ports identified above must be available for use.
    * An environment file gpdemo-env.sh has been created for your use.

======================================================================

==========================================================================================
executing:
  /home/kotti/projects/gpdb/bin/gpinitsystem -a -c clusterConfigFile ""
==========================================================================================

20151107:15:48:03:003610 gpinitsystem:centos7:kotti-[INFO]:-Checking configuration parameters, please wait...
20151107:15:48:03:003610 gpinitsystem:centos7:kotti-[INFO]:-Reading Greenplum configuration file clusterConfigFile
20151107:15:48:03:003610 gpinitsystem:centos7:kotti-[INFO]:-Locale has not been set in clusterConfigFile, will set to default value
/bin/locale: Cannot set LC_CTYPE to default locale: No such file or directory
20151107:15:48:03:003610 gpinitsystem:centos7:kotti-[INFO]:-Locale set to en_US.utf8
/bin/locale: Cannot set LC_CTYPE to default locale: No such file or directory
/bin/locale: Cannot set LC_ALL to default locale: No such file or directory
20151107:15:48:04:003610 gpinitsystem:centos7:kotti-[INFO]:-No DATABASE_NAME set, will exit following template1 updates
20151107:15:48:04:003610 gpinitsystem:centos7:kotti-[INFO]:-MASTER_MAX_CONNECT not set, will set to default value 25
20151107:15:48:04:003610 gpinitsystem:centos7:kotti-[INFO]:-Detected a single host GPDB array build, reducing value of BATCH_DEFAULT from 60 to 4
20151107:15:48:04:003610 gpinitsystem:centos7:kotti-[INFO]:-Checking configuration parameters, Completed
20151107:15:48:04:003610 gpinitsystem:centos7:kotti-[INFO]:-Commencing multi-home checks, please wait...
.
20151107:15:48:04:003610 gpinitsystem:centos7:kotti-[INFO]:-Configuring build for standard array
20151107:15:48:04:003610 gpinitsystem:centos7:kotti-[INFO]:-Commencing multi-home checks, Completed
20151107:15:48:04:003610 gpinitsystem:centos7:kotti-[INFO]:-Building primary segment instance array, please wait...
...
20151107:15:48:05:003610 gpinitsystem:centos7:kotti-[INFO]:-Building group mirror array type , please wait...
...
20151107:15:48:05:003610 gpinitsystem:centos7:kotti-[INFO]:-Checking Master host
20151107:15:48:05:003610 gpinitsystem:centos7:kotti-[INFO]:-Checking new segment hosts, please wait...
/bin/locale: Cannot set LC_CTYPE to default locale: No such file or directory
......
20151107:15:48:06:003610 gpinitsystem:centos7:kotti-[INFO]:-Checking new segment hosts, Completed
20151107:15:48:07:003610 gpinitsystem:centos7:kotti-[INFO]:-Building the Master instance database, please wait...
20151107:15:48:14:003610 gpinitsystem:centos7:kotti-[INFO]:-Starting the Master in admin mode
20151107:15:48:56:003610 gpinitsystem:centos7:kotti-[INFO]:-Commencing parallel build of primary segment instances
20151107:15:48:56:003610 gpinitsystem:centos7:kotti-[INFO]:-Spawning parallel processes    batch [1], please wait...
...
20151107:15:48:56:003610 gpinitsystem:centos7:kotti-[INFO]:-Waiting for parallel processes batch [1], please wait...
.........................
20151107:15:49:22:003610 gpinitsystem:centos7:kotti-[INFO]:------------------------------------------------
20151107:15:49:22:003610 gpinitsystem:centos7:kotti-[INFO]:-Parallel process exit status
20151107:15:49:22:003610 gpinitsystem:centos7:kotti-[INFO]:------------------------------------------------
20151107:15:49:22:003610 gpinitsystem:centos7:kotti-[INFO]:-Total processes marked as completed           = 3
20151107:15:49:22:003610 gpinitsystem:centos7:kotti-[INFO]:-Total processes marked as killed              = 0
20151107:15:49:22:003610 gpinitsystem:centos7:kotti-[INFO]:-Total processes marked as failed              = 0
20151107:15:49:22:003610 gpinitsystem:centos7:kotti-[INFO]:------------------------------------------------
20151107:15:49:22:003610 gpinitsystem:centos7:kotti-[INFO]:-Commencing parallel build of mirror segment instances
20151107:15:49:22:003610 gpinitsystem:centos7:kotti-[INFO]:-Spawning parallel processes    batch [1], please wait...
...
20151107:15:49:23:003610 gpinitsystem:centos7:kotti-[INFO]:-Waiting for parallel processes batch [1], please wait...
..
20151107:15:49:25:003610 gpinitsystem:centos7:kotti-[INFO]:------------------------------------------------
20151107:15:49:25:003610 gpinitsystem:centos7:kotti-[INFO]:-Parallel process exit status
20151107:15:49:25:003610 gpinitsystem:centos7:kotti-[INFO]:------------------------------------------------
20151107:15:49:25:003610 gpinitsystem:centos7:kotti-[INFO]:-Total processes marked as completed           = 0
20151107:15:49:25:003610 gpinitsystem:centos7:kotti-[INFO]:-Total processes marked as killed              = 0
20151107:15:49:25:003610 gpinitsystem:centos7:kotti-[WARN]:-Total processes marked as failed              = 3 <<<<<
20151107:15:49:25:003610 gpinitsystem:centos7:kotti-[INFO]:------------------------------------------------
20151107:15:49:25:003610 gpinitsystem:centos7:kotti-[FATAL]:-Errors generated from parallel processes
20151107:15:49:25:003610 gpinitsystem:centos7:kotti-[INFO]:-Dumped contents of status file to the log file
20151107:15:49:25:003610 gpinitsystem:centos7:kotti-[INFO]:-Building composite backout file
20151107:15:49:25:gpinitsystem:centos7:kotti-[FATAL]:-Failures detected, see log file /home/kotti/gpAdminLogs/gpinitsystem_20151107.log for more detail Script Exiting!
20151107:15:49:25:003610 gpinitsystem:centos7:kotti-[WARN]:-Script has left Greenplum Database in an incomplete state
20151107:15:49:25:003610 gpinitsystem:centos7:kotti-[WARN]:-Run command /bin/bash /home/kotti/gpAdminLogs/backout_gpinitsystem_kotti_20151107_154803 to remove these changes
20151107:15:49:25:003610 gpinitsystem:centos7:kotti-[INFO]:-Start Function BACKOUT_COMMAND
20151107:15:49:25:003610 gpinitsystem:centos7:kotti-[INFO]:-End Function BACKOUT_COMMAND
========================================
gpinitsystem returned: 2
========================================

======================================================================
                           OPTIMIZER STATE
----------------------------------------------------------------------
  Optimizer state .. : psql: FATAL:  System was started in master-only utility mode - only utility mode connections are allowed
======================================================================

psql: FATAL:  System was started in master-only utility mode - only utility mode connections are allowed
======================================================================

make: [cluster] Error 2 (ignored)

The /home/kotti/gpAdminLogs/gpinitsystem_20151107.log has the following details :

20151107:14:37:13:008746 gpcreateseg.sh:centos7:kotti-[INFO]:-Commencing remote /home/kotti/projects/gpdb/gpAux/gpdemo/lalshell centos7 export GPHOME=/home/kotti/projects/gpdb; . /h
ome/kotti/projects/gpdb/greenplum_path.sh; /home/kotti/projects/gpdb/bin/lib/pysync.py -x pg_log -x postgresql.conf -x postmaster.pid /home/kotti/projects/gpdb/gpAux/gpdemo/datadirs
/dbfast3/demoDataDir2 \[centos7\]:/home/kotti/projects/gpdb/gpAux/gpdemo/datadirs/dbfast_mirror3/demoDataDir2
Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
[FATAL]:-Unexpected EOF on RemotePysync output stream
20151107:14:37:14:008746 gpcreateseg.sh:centos7:kotti-[FATAL]:- Command export GPHOME=/home/kotti/projects/gpdb; . /home/kotti/projects/gpdb/greenplum_path.sh; /home/kotti/projects/
gpdb/bin/lib/pysync.py -x pg_log -x postgresql.conf -x postmaster.pid /home/kotti/projects/gpdb/gpAux/gpdemo/datadirs/dbfast3/demoDataDir2 \[centos7\]:/home/kotti/projects/gpdb/gpAu
x/gpdemo/datadirs/dbfast_mirror3/demoDataDir2 on centos7 failed with error status 3
20151107:14:37:14:008746 gpcreateseg.sh:centos7:kotti-[INFO]:-End Function RUN_COMMAND_REMOTE
20151107:14:37:14:008746 gpcreateseg.sh:centos7:kotti-[FATAL][2]:-Failed remote copy of segment data directory from centos7 to centos7
Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
[FATAL]:-Unexpected EOF on RemotePysync output stream
20151107:14:37:19:008577 gpcreateseg.sh:centos7:kotti-[FATAL]:- Command exportGPHOME=/home/kotti/projects/gpdb; . /home/kotti/projects/gpdb/greenplum_path.sh; /home/kotti/projects/
gpdb/bin/lib/pysync.py -x pg_log -x postgresql.conf -x postmaster.pid /home/kotti/projects/gpdb/gpAux/gpdemo/datadirs/dbfast1/demoDataDir0 \[centos7\]:/home/kotti/projects/gpdb/gpAu
x/gpdemo/datadirs/dbfast_mirror1/demoDataDir0 on centos7 failed with error status 3
20151107:14:37:19:008577 gpcreateseg.sh:centos7:kotti-[INFO]:-End Function RUN_COMMAND_REMOTE
20151107:14:37:19:008577 gpcreateseg.sh:centos7:kotti-[FATAL][0]:-Failed remote copy of segment data directory from centos7 to centos7
Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
[FATAL]:-Unexpected EOF on RemotePysync output stream

Please advise....

**Comment by asimrp** [comment]
Looking at this line from the output:
```
20151107:14:37:19:008577 gpcreateseg.sh:centos7:kotti-[FATAL][0]:-Failed remote copy of segment data directory from centos7 to centos7
Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
```
During initialization, the script connects to localhost using ssh.  Can you please try `ssh $(hostname)` and verify that it works without prompting for password?

**Comment by edespino** [comment]
Being a MPP system, the Greenplum management scripts execute **ssh** commands across the cluster (even in a single node cluster configuration) to interact with segment instances.  The ```Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).``` error you received indicates your ssh keys are not setup.  Please refer to the **[Installing and Configuring Greenplum on all Hosts](http://gpdb.docs.pivotal.io/4360/prep_os-install-hosts.html#topic8)** and supporting documentation related to **gpssh-exkeys** to setup your ssh-keys properly.

As Asim hinted to, you need to be able to execute a ssh command to your system where you are running ```make cluster``` without receiving a ssh password prompt.  Try the following to ensure you can execute a command on your system (in this case the **date** command - replace **<hostname>** with your system's name):  ```ssh <hostname> date```

**Comment by hlinnaka** [comment]
On 11/09/2015 01:46 AM, Ed Espino wrote:
> Being a MPP system, the Greenplum management scripts execute **ssh**
> commands across the cluster (even in a single node cluster
> configuration) to interact with segment instances

As a work-around, you can set up a cluster "the hacky way", see my post 
on gpdb-dev last week: 
https://groups.google.com/a/greenplum.org/forum/#!topic/gpdb-dev/QgK6gjgp9z8. 
That doesn't need ssh access.

- Heikki

**Comment by ksasi** [comment]
Hi All,

Setting up ssh-keys seem to have resolved the issue.Closing this issue.

Thanks....
