### ISSUE TITLE
./configure --enable-orca not find init.h

### ISSUE THREAD

**Issue by panwaitme** [greenplum-db/gpdb#613]
configure: error: gpopt/init.h GPOPT header file is required for Greenplum Query Optimizer (orca)

we are searched the file ,but not found;

**Comment by danielgustafsson** [comment]
You first need to install ORCA (it's a separate module) to be able to use it with Greenplum, see installation instructions here: https://github.com/greenplum-db/gporca/blob/master/README.md

**Comment by danielgustafsson** [comment]
No update so closing. I hope installing ORCA solved the problem, if not then please re-open the issue with the additional information.
