### ISSUE TITLE
Feature request: Allow tools which utilize ssh a broader range of configuration options

### ISSUE THREAD

**Issue by tylarb** [greenplum-db/gpdb#6140]
## Issue:

Currently, all gpdb tools which utilize ssh only allow "stock" ssh configurations:
- Port must be 22
- authorized keys, etc must be in ~/.ssh
- there's no way to specify specific id keys, etc
- The only user is the currently logged in user

## Feature request:
Adjust tools to utilize more configuration options which the ssh protocol provides

- allow --identity-file, etc to specify a new id file
- --port to specify specific port
- --user to specify specific user

**Comment by ashwinstar** [comment]
Closing this feature request given we have not seen further requests for the same. Also longer term product plan is to move away from SSH requirement itself for tools.
