### ISSUE TITLE
'pg.DB' has no attribute 'notices'

### ISSUE THREAD

**Issue by xunzhang** [greenplum-db/gpdb#616]
The problem results from file: `gpMgmt/bin/gpload.py`, since clause `self.db.notices()` in function `notice_processor` is invalid way to use `self.db`, I am confused the usage here.

**Comment by danielgustafsson** [comment]
Which version of PyGreSQL are you using when you get this error? If I understand it correctly the bundled version of PyGreSQL in Greenplum supplies a custom `.notices()` function See [pgmodule.c around line 2902](https://github.com/greenplum-db/gpdb/blob/master/gpMgmt/bin/pythonSrc/PyGreSQL-4.0/pgmodule.c#L2902) for the code.

**Comment by xunzhang** [comment]
4.1.1, I use HAWQ's gpload.py and got the error. I think HAWQ didn't copy the entire module of gpload from greenplum?

**Comment by xunzhang** [comment]
Does that mean if I use gpload outside greenplum with pip installed PyGreSQL, I will get this error?

**Comment by danielgustafsson** [comment]
> On 07 Apr 2016, at 15:00, Hong Wu <notifications@github.com> wrote:
> 
> Does that mean if I use gpload outside greenplum with pip installed PyGreSQL, I will get this error?

I’m not really a Python expert but I would think so yes, you would probably need to use the bundled version of PyGreSQL in order to use gpload.

**Comment by xunzhang** [comment]
Thanks, I will close this issue.
