### ISSUE TITLE
Incorrect size comparison in pg_dump for AO

### ISSUE THREAD

**Issue by danielgustafsson** [greenplum-db/gpdb#6171]
In PR #6161 @asimrp mentioned that `DOSizeCompare()` in pg_dump has a bug:
> It uses `relpages` as a measure of size, which is correct for heap storage but not for append-optimized storage. The correct measure of size for append-optimized tables is eof values stored in `pg_aoseg` table

**Comment by hlinnaka** [comment]
Hmm. We do set `pg_class.relpages` for AO tables, too. The planner relies on it, too.

**Comment by ashwinstar** [comment]
`DOSizeCompare()` used by `sortDataAndIndexObjectsBySize()` is used by parallel dump option of pg_dump. Dumping user data using `pg_dump` is not efficient and not recommended for GPDB.

Plus, nothing is incorrect in using `relpages` for this priority planning purpose even if used for AO tables. As Heikki mentioned we use that field for query planning so using it for parallel work planning during pg_dump is perfectly fine. Hence, I am closing this issue.
