### ISSUE TITLE
Limited number of primary segments on one machine

### ISSUE THREAD

**Issue by leskin-in** [greenplum-db/gpdb#6176]
## Summary
Greenplum database does not allow to run more than 44 primary segments simultaneously on one machine.

## Description
Hereinafter, the term "machine" denotes an operating system environment. All GPDB segments are considered to belong to one GPDB cluster.

Current implementation of `gpMgmt/bin/gppylib/gpsubprocess.py` limits the number of segments running on one machine at the same time.

Part of `gpsegstart` output:
```
[ERROR]:-filedescriptor out of range in select()
Traceback (most recent call last):
  File "/usr/lib/gpdb/lib/python/gppylib/commands/base.py", line 243, in run
    self.cmd.run()
  File "/usr/lib/gpdb/lib/python/gppylib/commands/base.py", line 711, in run
    self.exec_context.execute(self)
  File "/usr/lib/gpdb/lib/python/gppylib/commands/base.py", line 436, in execute
    (rc, stdout_value, stderr_value) = self.proc.communicate2(input=self.stdin)
  File "/usr/lib/gpdb/lib/python/gppylib/gpsubprocess.py", line 67, in communicate2
    self._read_files(timeout,output,error)
  File "/usr/lib/gpdb/lib/python/gppylib/gpsubprocess.py", line 122, in _read_files
    (rset,wset,eset) = self.__select(readList,writeList, errorList, timeout)
  File "/usr/lib/gpdb/lib/python/gppylib/gpsubprocess.py", line 216, in __select
    return select.select(iwtd, owtd, ewtd, timeout)
ValueError: filedescriptor out of range in select()
```

In this example, 90 segments were launched on one machine. This requires <img src="https://latex.codecogs.com/gif.latex?C_%7B90%7D%5E%7B2%7D" /> (4005) connections to be opened on the same machine for GPDB segments to communicate, while `select.select()` call supports no more than 1024 file descriptors.

<img src="https://latex.codecogs.com/gif.latex?C_%7B44%7D%5E%7B2%7D" /> (946) is maximum possible number of connections that can be served by `select.select()`, which means 44 is the limit on the number of GPDB primary segments on one machine.

## Proposed solution
Change [`select.select()`](https://docs.python.org/2/library/select.html#select.select) to [`select.poll()`](https://docs.python.org/2/library/select.html#select.poll) call. This allows an unlimited number of primary segments to be run simultaneously on one machine.

**Comment by d** [comment]
While you have the most context here, can you illuminate us on _why_ `gpsubprocess.py` is attempting to poll on one connection _per pair_ of primaries?

**Comment by kapustor** [comment]
Hi @jchampio!

Thats how we get it. We are using OpenPower huge machines with 120 primary and 120 mirrors segments on each machine:
```
[gpadmin@mdw ~]$ gpstart -m
20181120:12:32:07:070908 gpstart:mdw:gpadmin-[INFO]:-Starting gpstart with args: -m
20181120:12:32:07:070908 gpstart:mdw:gpadmin-[INFO]:-Gathering information and validating the environment...
20181120:12:32:07:070908 gpstart:mdw:gpadmin-[INFO]:-Greenplum Binary Version: 'postgres (Greenplum Database) 5.11.0 build 5.11.0_arenadata3-205.el7'
20181120:12:32:08:070908 gpstart:mdw:gpadmin-[INFO]:-Greenplum Catalog Version: '301705051'
20181120:12:32:08:070908 gpstart:mdw:gpadmin-[INFO]:-Master-only start requested in configuration without a standby master.

Continue with master-only startup Yy|Nn (default=N):
> y
20181120:12:32:10:070908 gpstart:mdw:gpadmin-[INFO]:-Starting Master instance in admin mode
20181120:12:32:12:070908 gpstart:mdw:gpadmin-[INFO]:-Obtaining Greenplum Master catalog information
20181120:12:32:12:070908 gpstart:mdw:gpadmin-[INFO]:-Obtaining Segment details from master...
20181120:12:32:12:070908 gpstart:mdw:gpadmin-[INFO]:-Setting new master era
20181120:12:32:12:070908 gpstart:mdw:gpadmin-[INFO]:-Master Started...
[gpadmin@mdw ~]$ PGOPTIONS='-c gp_session_role=utility' psql -d postgres
psql (8.3.23)
Type "help" for help.

postgres=# select count(1) from gp_segment_configuration where role='p';
 count
-------
   241
(1 row)

postgres=# select distinct hostname from gp_segment_configuration;
 hostname
----------
 sdw1
 mdw
 sdw2
(3 rows)

postgres=# \q
[gpadmin@mdw ~]$ uname -a
Linux mdw 3.10.0-862.11.6.el7.ppc64le #1 SMP Tue Aug 14 20:51:52 GMT 2018 ppc64le ppc64le ppc64le GNU/Linux
[gpadmin@mdw ~]$ gpssh -f arenadata_configs/arenadata_all_hosts.hosts
=> free -g
[sdw2]               total        used        free      shared  buff/cache   available
[sdw2] Mem:           2040          23        1980           0          35        2008
[sdw2] Swap:             3           0           3
[ mdw]               total        used        free      shared  buff/cache   available
[ mdw] Mem:            506           8         473           0          25         494
[ mdw] Swap:             3           0           3
[sdw1]               total        used        free      shared  buff/cache   available
[sdw1] Mem:           2040          23        1980           0          35        2007
[sdw1] Swap:             3           0           3
=> cat /proc/cpuinfo |grep processor |wc -l
[sdw2] 384
[ mdw] 192
[sdw1] 384

When using default gpsubprocess.py with select():

[gpadmin@mdw ~]$ gpstart -a
...
20181120:13:10:05:161744 gpsegstart.py_sdw1:gpadmin:sdw1:gpadmin-[ERROR]:-filedescriptor out of range in select()
Traceback (most recent call last):
  File "/usr/lib/gpdb/lib/python/gppylib/commands/base.py", line 243, in run
    self.cmd.run()
  File "/usr/lib/gpdb/lib/python/gppylib/commands/base.py", line 711, in run
    self.exec_context.execute(self)
  File "/usr/lib/gpdb/lib/python/gppylib/commands/base.py", line 436, in execute
    (rc, stdout_value, stderr_value) = self.proc.communicate2(input=self.stdin)
  File "/usr/lib/gpdb/lib/python/gppylib/gpsubprocess.py", line 67, in communicate2
    self._read_files(timeout,output,error)
  File "/usr/lib/gpdb/lib/python/gppylib/gpsubprocess.py", line 122, in _read_files
    (rset,wset,eset) = self.__select(readList,writeList, errorList, timeout)
  File "/usr/lib/gpdb/lib/python/gppylib/gpsubprocess.py", line 216, in __select
    return select.select(iwtd, owtd, ewtd, timeout)
ValueError: filedescriptor out of range in select()
20181120:13:10:14:161744 gpsegstart.py_sdw1:gpadmin:sdw1:gpadmin-[CRITICAL]:-gpsegstart.py failed. (Reason=''NoneType' object has no attribute 'rc'') exiting...


Starting with poll() returns no error and goes fine.
```

**Comment by kapustor** [comment]
@jchampio 

Changing `numWorkers` to 64 helped, but DB start took much more time - 11 minutes vs 2 minutes with `poll()`.
Seems to me like replacing `select()` to `poll()` is more correct.

**Comment by jchampio** [comment]
> Seems to me like replacing select() to poll() is more correct.

If the goal is to open up maximum parallelism on platforms that can handle it, then yes. If the goal is to enable large numbers of segments without unnecessary resource exhaustion/bottlenecking, I don't think switching to `poll()` necessarily helps us there.

> Changing numWorkers to 64 helped, but DB start took much more time - 11 minutes vs 2 minutes with poll().

This is really strange. Your current number of workers per host is 120, so artificially limiting the parallelism there should have only given you a factor-of-2 difference. Is `select()` really that much less performant on your particular platform, or is there yet another confounding factor at work here?

(The U.S. is about to go on a holiday weekend for Thanksgiving, so I'll be able to follow up next week. Thanks for investigating this with us!)

**Comment by kapustor** [comment]
> This is really strange. Your current number of workers per host is 120, so artificially limiting the parallelism there should have only given you a factor-of-2 difference.
I was thinking the same, but it is what it is :)

Select() with 64 workers:
```
20181122:10:44:30:168108 gpstart:mdw:gpadmin-[INFO]:-Commencing parallel primary and mirror segment instance startup, please wait...
............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
20181122:10:55:55:168108 gpstart:mdw:gpadmin-[INFO]:-Process results...
```


> Is select() really that much less performant on your particular platform, or is there yet another confounding factor at work here?
I am not sure. Maybe @leskin-in knows?

**Comment by leskin-in** [comment]
@kapustor, 
I suppose `poll()` and `select()` are almost equally perfomant in the case, and there should be another factor that biases the result. There is an [article](https://www.ibm.com/developerworks/aix/library/au-pollset/index.html) which describes the implementation of both these calls on our architecture in detail.

**Comment by kapustor** [comment]
Hi @jchampio 

I found an issue in my DB startup test - the results were affected by other processes.
I repeated the test clearly and thats what Ive got:

Starting with poll() and default numworkers took 1:34:
```
20181123:15:11:37:022241 gpstart:mdw:gpadmin-[INFO]:-Commencing parallel primary and mirror segment instance startup, please wait...
..............................................................................................
20181123:15:13:11:022241 gpstart:mdw:gpadmin-[INFO]:-Process results...
```

Starting with select() and 64 numworkers took 1:26:
```
20181123:15:19:17:023166 gpstart:mdw:gpadmin-[INFO]:-Commencing parallel primary and mirror segment instance startup, please wait...
.....................................................................................
20181123:15:20:43:023166 gpstart:mdw:gpadmin-[INFO]:-Process results...
```

So, select() with 64 numworkers works even faster, then poll with default numworkers.

What we shall do now? Implement a new parameter for numworkers or set it to any default low value in new PR?
Or our original PR with select() => poll() is ok because now we know athe reasons?

**Comment by jchampio** [comment]
@kapustor 

> So, select() with 64 numworkers works even faster, then poll with default numworkers.

Ah, great to know. Thanks!

> What we shall do now? Implement a new parameter for numworkers or set it to any default low value in new PR?
Or our original PR with select() => poll() is ok because now we know athe reasons?

IMO it makes sense to cap the `WorkerPool` limit at some reasonable maximum for now. If you're really interested in wiring that through as a new parameter, go for it, but I don't think anyone has asked for that yet; that's something we can prioritize ourselves as a "feature" later, if needed. I also don't think we want to go for `poll()` right now, especially if it's not clear whether there's actually a performance improvement.
