### ISSUE TITLE
ERROR:  record type has not been registered

### ISSUE THREAD

**Issue by hlinnaka** [greenplum-db/gpdb#618]
This query:

select q from (select max(f1) from int4_tbl group by f1 order by f1) q;

produces:

ERROR:  record type has not been registered

See PR #611. That was an attempt at fixing this issue, but it was a few bricks shy of a load.

**Comment by hlinnaka** [comment]
See also discussion on gpdb-dev: https://groups.google.com/a/greenplum.org/d/msg/gpdb-dev/4VPId5V0tT8/DK0ERDkaCwAJ

**Comment by dhanashreek89** [comment]
Working on a story to fix the issue "ERROR: record type has not been registered"

**Comment by Eulerizeit** [comment]
@vraghavan78 is this being looked at? It seems to maybe be causing flakey behavior in ICW.

**Comment by hlinnaka** [comment]
This was fixed by commit d8ac33080aec5a710947d43ca092b2db38d8edc2, I believe. Closing.
