### ISSUE TITLE
server crash when startup with wrong catalog version

### ISSUE THREAD

**Issue by dkrieger-pvtl** [greenplum-db/gpdb#6226]
### Greenplum version or build
GPDB6 master development

### OS version and uname -a
MacOSX High Sierra Kernel 17.7.0

### autoconf options used ( config.status --config )
'--enable-debug' '--enable-cassert' '--with-perl' '--with-python' '--with-libxml' '--with-gssapi' '--prefix=/usr/local/gpdb'

### Installation information ( pg_config )
standard demo cluster

### Expected behavior
database works OR gpstart produces an error

### Actual behavior
gpstart works, but when I run psql then do \d, the server crashes.

### Step to reproduce the behavior
This was on a branch that I just updated, so I think the CATALOG_VERSION had changed from my existing demo cluster.  I did a rebase to master, but did not do a ```make distclean```.  I did do a ```make install```.  Then,``` gpstart -a``` then ```psql -d postgres``` then do ```psql#> \d```.
PSQL:
```
psql -d postgres
psql (9.4beta1)
Type "help" for help.

postgres=# \d+
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
You are currently not connected to a database.
You are currently not connected to a database.
!> \q
```

Stack Trace:
```
[in qddir/demoDataDir-1/pg_log]
2018-11-13 07:37:13.414834 PST,"dkrieger","postgres",p5889,th-1998511232,"::1","49582",2018-11-13 07:37:11 PST,0,con7,cmd1,seg-1,,dx3,,sx1,"LOG","00000","statement: select pg_catalog.version()",,,,,,"select pg_catalog.version()",0,,"postgres.c",1615,
2018-11-13 07:37:13.704651 PST,,,p5889,th0,,,2018-11-13 07:37:11 PST,0,con7,cmd1,seg-1,,,,,"PANIC","XX000","Unexpected internal error: Master process received signal SIGSEGV",,,,,,,0,,,,"1    0x7fff5061cf5a libsystem_platform.dylib _sigtramp + 0x1a
2    0x0 0x0
3    0x108617d44 postgres copyObject + 0x5a04
4    0x1089bc784 postgres _ZN4gpdb10CopyObjectEPv + 0x64
5    0x1089b8b70 postgres _ZN9COptTasks12OptimizeTaskEPv + 0x4a0
6    0x1097cf506 libgpos.3.dylib _ZN4gpos5CTask7ExecuteEv + 0x46
7    0x1097d1a7a libgpos.3.dylib _ZN4gpos7CWorker7ExecuteEPNS_5CTaskE + 0x1a
8    0x1097ced21 libgpos.3.dylib _ZN4gpos14CAutoTaskProxy7ExecuteEPNS_5CTaskE + 0x51
9    0x1097bf2dc libgpos.3.dylib gpos_exec + 0x24c
10   0x1089b76d6 postgres _ZN9COptTasks7ExecuteEPFPvS0_ES0_ + 0x86
11   0x1089ba1db postgres _ZN9COptTasks18GPOPTOptimizedPlanEP5QueryP11SOptContext + 0x3b
12   0x1089bacc5 postgres _ZN12CGPOptimizer18GPOPTOptimizedPlanEP5QueryPb + 0x35
13   0x10868da95 postgres optimize_query + 0x125
14   0x108677f8d postgres standard_planner + 0x8d
15   0x108677eea postgres planner + 0x12a
16   0x10873e1e2 postgres pg_plan_query + 0x72
17   0x108744c79 postgres exec_simple_query + 0x699
18   0x10874354d postgres PostgresMain + 0x3f3d
19   0x1086c30ef postgres BackendRun + 0x1ff
```

**Comment by hlinnaka** [comment]
Does it work without ORCA?

If you've configured with `--enable-depend`, the build system usually correctly figures out what needs to be recompiled, so that you can just `make install` after rebasing. However, that doesn't seem to work for the C++ code in src/backend/gpopt/. I routinely do `cd src/backend/gpopt; make clean`, after switching branches because of that.

**Comment by dkrieger-pvtl** [comment]
I don't know; I should have left this demo cluster alone but we were "in a hurry" so I just issued a ```make distclean``` and rebuilt.  But I'll try reproducing by simply bumping the catalog version after building a demo cluster to see if that works to reproduce it.

**Comment by d** [comment]
What makes you think this is _because of_ a catalog mismatch between the executable and the cluster? Your backend shouldn't even start up to the point of accepting connections to begin with ...

**Comment by dkrieger-pvtl** [comment]
Simply that ```make distclean``` apparently fixed it, and "what else would have caused a few days checkins to crash the server"?  Yes, naive, but mostly a placeholder to see if someone else saw this; I haven't gotten a chance to try to reproduce it yet.

**Comment by jchampio** [comment]
> "what else would have caused a few days checkins to crash the server"?

A binary-incompatible ORCA change is a good bet. As @hlinnaka pointed out, compile-time dependencies don't work correctly for the code that links against ORCA (and the underlying libraries don't bump SONAMEs like they should when they change ABI).

**Comment by hlinnaka** [comment]
I don't think there's anything more to do here, so closing.
