### ISSUE TITLE
Dump/restore of partitioned table with partially dropped column creates fully dropped column

### ISSUE THREAD

**Issue by jchampio** [greenplum-db/gpdb#6230]
### Greenplum version

`master`, `5X_STABLE`. Probably 4 as well but I haven't checked.

### Step to reproduce the behavior

First create a partitioned table with a partially dropped column using `ALTER TABLE ONLY`:

```sql
CREATE TABLE part (a int, b int, c int)
    PARTITION BY RANGE(a) (START(1) END(2) EVERY(1));
INSERT INTO part VALUES (1, 2, 3), (1, 4, 5), (1, 6, 7);

ALTER TABLE ONLY part DROP COLUMN b;

SELECT * FROM part;
 a | c
---+---
 1 | 3
 1 | 5
 1 | 7
(3 rows)

SELECT * FROM part_1_prt_1;
 a | b | c
---+---+---
 1 | 2 | 3
 1 | 4 | 5
 1 | 6 | 7
(3 rows)
```

That is, `b` is dropped from the root table but not from the child partition.

### Expected behavior

After dumping and restoring this table, the previous behavior should remain -- a `SELECT` on `part_1_prt_1` should contain column `b`.

### Actual behavior

After dump/restore, column `b` is also dropped from the child partition, as if a full `ALTER TABLE` had been performed instead of an `ALTER TABLE ONLY`. The data for column `b` is not dumped at all.

This particular example looks a little contrived, but it has implications for upgrade, where we're trying to guarantee that the upgraded system has the same application-level semantics as the old system.

**Comment by Eulerizeit** [comment]
Behavior in Postgres 11
```
alter table only test drop column b;
ERROR:  cannot drop column from only the partitioned table when partitions exist
HINT:  Do not specify the ONLY keyword.
```

**Comment by jchampio** [comment]
Different cases that must be solved (or at least we need to decide not to solve them):

- 5X dump and restore of partially dropped column fully drops it, and will not export the data from the leaves
- 5-to-6 upgrade will currently do the same, but data is not lost (just marked as dropped and made invisible in all leaves)
- 5 and 6 both allow dropping root columns but disallow adding them back, making it difficult to dig yourself out of this situation

**Comment by jchampio** [comment]
Another problem:
- [ ] Once you drop the column from the root only, you still can't drop that column from the children.

**Comment by jchampio** [comment]
Current plan:
- Disallow `ALTER TABLE ONLY ... DROP COLUMN` on a partitioned table in 6. Warn in 4 and 5 that this situation won't dump or upgrade correctly.
- Refuse to dump or upgrade this situation in 6. Guide the DBA to fix the situation using `ALTER TABLE ... ADD COLUMN`.
- Refuse to dump this situation in 4 or 5.

**Comment by dkrieger-pvtl** [comment]
Yet another example of anomalies where we allow the column to be dropped only on the parent(from https://groups.google.com/a/greenplum.org/forum/#!topic/gpdb-dev/0SzL_gSbqKo):
```
postgres=# create table part (a int, b int, c int)                                                                                              
distributed randomly                                                                                                                          
partition by range (a) (                                                                                                                          
partition part_1 start (0) inclusive end (3) exclusive,                                                                                       
default partition part_extra);                                                                                                                                                   
postgres=# insert into part select i*3+0, i*3+1, i*3+2 from generate_series(1,3) i;
postgres=# select * from part order by a;                                                                                                      a | b  | c  
---+----+----
 3 |  4 |  5
 6 |  7 |  8
 9 | 10 | 11
postgres=# update part set c=c*2;
postgres=# select * from part order by a;
 a | b  | c  
---+----+----
 3 |  4 | 10
 6 |  7 | 16
 9 | 10 | 22
postgres=# alter table only part drop column b;                                                                                               
postgres=# update part set c=c*2;
ERROR:  relation "part" must have the same column names and column order as "part_1_prt_part_extra"  (seg2 127.0.0.1:25434 pid=5509)
```

**Comment by lij55** [comment]
Both GP6 and master branch report error while trying to drop column:

6X
```
test=# ALTER TABLE ONLY part DROP COLUMN b;
ERROR:  can't drop a column from "part"; it is a partitioned table or part thereof
```

Master
```sql
test=# ALTER TABLE ONLY part DROP COLUMN b;
ERROR:  cannot drop column from only the partitioned table when partitions exist
HINT:  Do not specify the ONLY keyword.
```

The mentioned issue seems fixed.  closing this issue now.
