### ISSUE TITLE
Go over greenplum_schedule and parallelize

### ISSUE THREAD

**Issue by danielgustafsson** [greenplum-db/gpdb#624]
There are a lot of test suites in `greenplum_schedule` that are running serially. Once the work with porting tests from Tinc into installcheck-good settles down we need to go over the schedule and see what we can do to improve the degree of parallelisation.

**Comment by d** [comment]
It's high time we did this man

**Comment by danielgustafsson** [comment]
Yes. Unless it's dealt with by then I intend to revisit this when the merge has been pushed.

**Comment by hlinnaka** [comment]
Yeah, making the tests faster, and parallelizing them is one way to do it, would be nice. I don't think there's much point in keeping this as an open issue, though, so closing.

(We have changed the test schedule many times, since this was opened, some of those changes made them more parallel.)
