### ISSUE TITLE
error: ‘recordXtime’ may be used uninitialized in this function [-Werror=maybe-uninitialized]

### ISSUE THREAD

**Issue by yydzero** [greenplum-db/gpdb#6247]
### Step to reproduce the behavior

Using latest master, on RHEL7.5, get following error when build greenplum. configure is like below:

 ./configure --prefix=/home/test/gpdb --with-python --with-perl --with-ldap --with-libxml 

```
gcc -O3 -std=gnu99  -Wall -Wmissing-prototypes -Wpointer-arith -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fno-aggressive-loop-optimizations -Wno-unused-but-set-variable -Wno-address  -Werror=uninitialized -Werror=implicit-function-declaration -I../../../../src/include -D_GNU_SOURCE -I/usr/include/libxml2  -I/home/test/gpdb/include  -c -o xlog.o xlog.c
xlog.c: In function ‘StartupXLOG’:
xlog.c:5707:21: error: ‘recordXtime’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
    recoveryStopTime = recordXtime;
                     ^
xlog.c:5654:14: note: ‘recordXtime’ was declared here
  TimestampTz recordXtime;
              ^
cc1: some warnings being treated as errors
make[4]: *** [xlog.o] Error 1
```

**Comment by d** [comment]
What is your compiler (GCC, ICC, Clang, or other?) And version is it? I cannot reproduce this with GCC 8.2.0

**Comment by yydzero** [comment]
[test@9b9b71b39722 gpdb]$ gcc --version
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-28)

**Comment by d** [comment]
Oh I'm pretty sure it fails miserably for anything below GCC 5.1 …

**Comment by yydzero** [comment]
will try it, and closed

**Comment by klkyy** [comment]
@d @yydzero  we should modify the code !

**Comment by klkyy** [comment]
@d  git patch
diff --git a/src/backend/access/transam/xlog.c b/src/backend/access/transam/xlog.c
index 47c570d..ba47146 100644
--- a/src/backend/access/transam/xlog.c
+++ b/src/backend/access/transam/xlog.c
@@ -5651,7 +5651,7 @@ static bool
 recoveryStopsAfter(XLogRecord *record)
 {
        uint8           record_info;
-       TimestampTz recordXtime;
+       TimestampTz recordXtime = 0;

        record_info = record->xl_info & ~XLR_INFO_MASK;
