### ISSUE TITLE
[Feature Narrative] A non-dump upgrade for Greenplum Database

### ISSUE THREAD

**Issue by skahler-vmware** [greenplum-db/gpdb#6264]
### Summary

PostgreSQL provides pg_upgrade to do upgrade a database from one major version to another. We should leverage pg_upgrade as a way to do database upgrades in a distributed and parallel manner.

### State

In Progress

### Problem this solves

The current method most commonly used to upgrade a database involve dumping the entire contents of the database to a backup and then restoring it into the system. This process takes a large amount of time to do the backup and restore and requires additional disk space.

pg_upgrade is designed to run on the data itself on a segment and avoid the export and import overhead as well as removing the need for a copy of the data.

### Why do this

Greenplum major version releases will accelerate over the next few years. Users will need a way to upgrade their cluster in a way that is minimally invasive and shortens any maintenance window necessary to do so.

### Preliminary research

pg_upgrade has been in use to do this on PostgreSQL databases. We should be able to leverage this tool in order to achieve similar results. This can be executed in a parallel manner so that we can make use of the available resource in a cluster to speed the process. The binary representation of one of the data types has changed between GPDB4 (not open source) and GPDB5, Postgres did not create pg_upgrade until after this had already taken place. In order to use this for a 4to5 upgrade we would need to do a data rewrite process which will make the conversion take more time. In future versions this change does not exist which could greatly enhance the speed at which the upgrade process runs.

There are a variety of things that set Greenplum apart from Postgres such as AO tables and the master and segment instances. pg_upgrade will need to be modified in order to work with Greenplum.

### Solution to be implemented

pg_upgrade will be made to work for a MasterToMaster upgrade so the process can be proven and then we will move on to a 5StableToMaster upgrade. Another tool will be created called gpupgrade that users may interact with in order to more easily manage all of the pg_upgrade process that are being ran.

### Collaboration requirements in order to implement this feature

pg_upgrade will rely heavily on pg_dump and pg_restore. Change may need to be done to these utilities in order ensure the necessary information is being extracted and can be imported into the system. This is deeper than a normal backup and restore as there needs to be a closer match in naming conventions for all objects in order to do the migration, which is not required by backup. Additionally there may be internal postgres server work in order to define or facilitate object creation in this manner.

extensions and external components will need to be considered in how they play a part in the upgrade ecosystem. This should be similar to what they experience in a binary upgrade, but additionally the data directories themselves will be replaced. Thus the need for upgrade to have knowledge about any required configuration will play a part.

### When is this feature complete

This feature would be considered complete when a user can call pg_upgrade presented in the master branch to upgrade a database from 5X_Stable to the current build. Requiring a user to do work outside of pg_upgrade in order to be ready to execute pg_upgrade, such as catalog cleanup or sharing of data generated during the master upgrade, is acceptable.

### Additions and issues related to this feature

Any work related to this feature should be tagged with the **Upgrade** label
[Upgrade](https://github.com/greenplum-db/gpdb/issues?q=label%3AUpgrade
)

**Comment by skahler-pivotal** [comment]
Issues dealing with upgrade

#6250
#6230 
#6193 
#6166 
#6149 
#6137

**Comment by skahler-pivotal** [comment]
A tool for coordination is being create called gpupgrade and it can be found [here](https://github.com/greenplum-db/gpupgrade)

**Comment by lij55** [comment]
closing this tracking issue because gpupgrade has its repo now.
