### ISSUE TITLE
[Feature Narrative] Persistent daemons to monitor and administer Greenplum Cluster

### ISSUE THREAD

**Issue by skahler-vmware** [greenplum-db/gpdb#6265]
### Summary

There should be a daemon process that exists on each host which is responsible for running Greenplum software and provide capabilities to administer the system

### State

Discussion

### Problem this solves

Greenplum currently relies on information stored within the database to do administration on the cluster as a whole. If the database is not running, many tools will not work.

Health checking of the system slows down when the database is under load leading to incorrect knowledge of the state of the cluster

Communication and the execution of actions are generally done via ssh to the hosts, this has made portions of administration hard to maintain as well as creating issues with users needing to configure ssh permissions.

Container orchestrators don't have a utility to plug into in order to ask what should be running on the local system and if it is in an okay state.

### Why do this

As Greenplum becomes a platform as opposed to just a database ways need to be found to control the database plus other pieces of software. Additionally we need to provide a better method to enact actions and communicate between hosts in a cloud enabled landscape.

### Preliminary research

While working on gpupgrade we have enacted a client, hub, agent model that communicates via gRPC. The amount of work to adapt this model to a larger scale implementation should be minimal. Currently we don't implement long running daemons on a system, but this could be changed such that the hub and agent are started at container or host start time. There are a variety of other data platform products that make use of a similar architecture.

### Solution to be implemented

TBD

### Collaboration requirements in order to implement this feature

TBD

### When is this feature complete

TBD

**Comment by lij55** [comment]
closing this issue as it will be a quite long future scope
