### ISSUE TITLE
gpssh-exkeys overwrites authorized_keys

### ISSUE THREAD

**Issue by tichimura-pivotal** [greenplum-db/gpdb#6285]
### Greenplum version or build
5.13.0

### OS version and uname -a
Ubuntu 16.04.5 LTS

### autoconf options used ( config.status --config )
n/a

### Installation information ( pg_config )
n/a

### Expected behavior
append the new entry with current entry in authorized_keys

### Actual behavior
When try to do the gpssh-exkeys on VM instance of MS Azure, it seem to overwrite the current authorized_key. We could not login again with ssh-key, and need to reset from Azure console. 

### Step to reproduce the behavior
create VM instance in Azure, run gpssh-exkeys.

**Comment by tylarb** [comment]
The behavior of gpssh-exkeys has been modified in 7X, so this should no longer be an issue.
