### ISSUE TITLE
Vacuum in utility mode in QD resets pg_class.relpages/reltuples

### ISSUE THREAD

**Issue by hlinnaka** [greenplum-db/gpdb#6287]
If you run VACUUM in the QD, in utility mode, it overwrites pg_class.relpages/reltuples with zeros. That's understandable: user tables are indeed empty in the QD. But perhaps we should not do that. There's a chance that we overwrite perfectly good stats with zeros. See discussion at https://github.com/greenplum-db/gpdb/pull/6280

**Comment by BaiShaoqi** [comment]
Hi, Heikki, have merged a pr 6870 to fix the issue. 

I close the issue now, if you find pr 6870 is not a right fix, reopen the issue.
