### ISSUE TITLE
Assert failure within dtmPreCommand when I call SPI in bgworker

### ISSUE THREAD

**Issue by gfphoenix78** [greenplum-db/gpdb#6298]
### Greenplum version or build
PostgreSQL 9.4beta1 (Greenplum Database 6.0.0-alpha.0+dev.13244.g9001b48 build dev-oss) on x86_64-unknown-linux-gnu, compiled by gcc (GCC) 8.2.0, 64-bit compiled on Nov 22 2018 02:17:25 (with assert checking)
### OS version and uname -a
Linux xxxx 3.10.0-862.11.6.el7.x86_64 #1 SMP Tue Aug 14 21:49:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
### autoconf options used ( config.status --config )
'--prefix=/usr/local/gpdb' '--with-gssapi' '--with-pgport=5432' '--with-libedit-preferred' '--with-perl' '--with-python' '--with-openssl' '--with-pam' '--with-krb5' '--enable-cassert' '--enable-debug' '--enable-debugbreak' '--enable-depend' '--with-libxml' '--disable-orca' 'CFLAGS=-O0 -g3'
### Installation information ( pg_config )
BINDIR = /usr/local/gpdb/bin
DOCDIR = /usr/local/gpdb/share/doc/postgresql
HTMLDIR = /usr/local/gpdb/share/doc/postgresql
INCLUDEDIR = /usr/local/gpdb/include
PKGINCLUDEDIR = /usr/local/gpdb/include/postgresql
INCLUDEDIR-SERVER = /usr/local/gpdb/include/postgresql/server
LIBDIR = /usr/local/gpdb/lib
PKGLIBDIR = /usr/local/gpdb/lib/postgresql
LOCALEDIR = /usr/local/gpdb/share/locale
MANDIR = /usr/local/gpdb/share/man
SHAREDIR = /usr/local/gpdb/share/postgresql
SYSCONFDIR = /usr/local/gpdb/etc/postgresql
PGXS = /usr/local/gpdb/lib/postgresql/pgxs/src/makefiles/pgxs.mk
CONFIGURE = '--prefix=/usr/local/gpdb' '--with-gssapi' '--with-pgport=5432' '--with-libedit-preferred' '--with-perl' '--with-python' '--with-openssl' '--with-pam' '--with-krb5' '--enable-cassert' '--enable-debug' '--enable-debugbreak' '--enable-depend' '--with-libxml' '--disable-orca' 'CFLAGS=-O0 -g3'
CC = gcc
CPPFLAGS = -D_GNU_SOURCE -I/usr/local/gpdb/include
CFLAGS = -O0 -g3 -std=gnu99 -Wall -Wmissing-prototypes -Wpointer-arith -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fno-aggressive-loop-optimizations -Wno-unused-but-set-variable -Wno-address -Wno-format-truncation -Wno-stringop-truncation -g -ggdb -Werror=uninitialized -Werror=implicit-function-declaration -I/usr/local/gpdb/include
CFLAGS_SL = -fpic
LDFLAGS = -Wl,--as-needed -Wl,-rpath,'/usr/local/gpdb/lib',--enable-new-dtags -L/usr/local/gpdb/lib
LDFLAGS_EX =
LDFLAGS_SL =
LIBS = -lpgcommon -lpgport -lxml2 -lpam -lrt -lgssapi_krb5 -lrt -lcrypt -ldl -lm -L/usr/local/gpdb/lib
VERSION = PostgreSQL 9.4beta1
### Stack trace
0.  0x00007f8d81129277 in raise () from /lib64/libc.so.6
1.  0x00007f8d8112a968 in abort () from /lib64/libc.so.6
2.  0x0000000000ad0fad in ExceptionalCondition (conditionName=0xe781b5 "!(debugDetail != ((void *)0))", errorType=0xe77ecb "FailedAssertion", fileName=0xe77fae "cdbtm.c", lineNumber=387) at assert.c:66
3.  0x0000000000be0121 in dtmPreCommand (debugCaller=0xe6738b "CdbDispatchUtilityStatement", debugDetail=0x0, stmt=0x0, needsTwoPhaseCommit=2 '\002', wantSnapshot=4 '\004', inCursor=0 '\000') at cdbtm.c:387
4.  0x0000000000b8bb97 in CdbDispatchUtilityStatement (stmt=0x1602970, flags=7, oid_assignments=0x157c428, cdb_pgresults=0x0) at cdbdisp_query.c:386
5.  0x00000000006c32f2 in CreateSchemaCommand (stmt=0x1602970, queryString=0x7f8d7726a5d8 "create schema if not exists diskquota_catalog;create table if not exists diskquota_catalog.database_list(dbid oid unique);") at schemacmds.c:161
6.  0x00000000009718ce in ProcessUtilitySlow (parsetree=0x1602970, queryString=0x7f8d7726a5d8 "create schema if not exists diskquota_catalog;create table if not exists diskquota_catalog.database_list(dbid oid unique);", context=PROCESS_UTILITY_QUERY, params=0x0, dest=0x1153720 <spi_printtupDR>, completionTag=0x7ffe6e479a90 "") at utility.c:1092
7.  0x00000000009717bd in standard_ProcessUtility (parsetree=0x1602970, queryString=0x7f8d7726a5d8 "create schema if not exists diskquota_catalog;create table if not exists diskquota_catalog.database_list(dbid oid unique);", context=PROCESS_UTILITY_QUERY, params=0x0, dest=0x1153720 <spi_printtupDR>, completionTag=0x7ffe6e479a90 "") at utility.c:1053
8.  0x00000000009706bc in ProcessUtility (parsetree=0x1602970, queryString=0x7f8d7726a5d8 "create schema if not exists diskquota_catalog;create table if not exists diskquota_catalog.database_list(dbid oid unique);", context=PROCESS_UTILITY_QUERY, params=0x0, dest=0x1153720 <spi_printtupDR>, completionTag=0x7ffe6e479a90 "") at utility.c:373
9.  0x00000000007849f6 in _SPI_execute_plan (plan=0x7ffe6e479bf0, paramLI=0x0, snapshot=0x0, crosscheck_snapshot=0x0, read_only=0 '\000', fire_triggers=1 '\001', tcount=0) at spi.c:2274
10. 0x0000000000781ba8 in SPI_execute (src=0x7f8d7726a5d8 "create schema if not exists diskquota_catalog;create table if not exists diskquota_catalog.database_list(dbid oid unique);", read_only=0 '\000', tcount=0) at spi.c:406
11. 0x00007f8d77266196 in exec_simple_utility (sql=0x7f8d7726a5d8 "create schema if not exists diskquota_catalog;create table if not exists diskquota_catalog.database_list(dbid oid unique);") at diskquota.c:291
12. 0x00007f8d77266119 in create_monitor_db_table () at diskquota.c:279
### Behavior
In function `dtmPreCommand`, `debugDetail` is set to `debug_query_string` by `CdbDispatchUtilityStatement`, but `debug_query_string` is null and never assigned. 
And when I set `debug_query_string` to something not null, it works.

### Step to reproduce the behavior
```
In bgworker process
{
    ...
     BackgroundWorkerInitializeConnection("postgres", NULL);
     
      sql = "create schema if not exists diskquota_catalog;"
                "create table if not exists diskquota_catalog.database_list(dbid oid unique);";
      StartTransactionCommand();
      ret = SPI_connect();
      if (ret != SPI_OK_CONNECT)
          elog(ERROR, "connect error, code=%d", ret);
      PushActiveSnapshot(GetTransactionSnapshot());
      ret = SPI_execute(sql, false, 0); // error happened here
      if (ret != SPI_OK_UTILITY)
          elog(ERROR, "sql:'%s', code %d", sql, ret);
      elog(LOG, "create database_list OK, %ld", SPI_processed);
      SPI_finish();
      PopActiveSnapshot();
      CommitTransactionCommand();
     ...
}
```

**Comment by hlinnaka** [comment]
Fixed by commit 24471e17bc.
