### ISSUE TITLE
Assertion failure with 'set default_transaction_isolation=serializable'

### ISSUE THREAD

**Issue by hlinnaka** [greenplum-db/gpdb#6388]
Per report on gpdb-users (https://groups.google.com/a/greenplum.org/d/msg/gpdb-users/iZSjRAz13Bs/ghuuH91fBwAJ)

Hi,
Our Greenplum version is 9.4beta1.

We set transaction isolation level to 'Serializable' with command 'set default_transaction_isolation=serializable'. When we tried 'select * from foo', it encountered the following error:

FailedAssertion("!(XactIsoLevel < 3)", File: "procarray.c", Line: 2090)

**Comment by lij55** [comment]
verified on both GP6 and master. It no longer repoet assert error any more. Closing this issue.
