### ISSUE TITLE
How do I back up partition tables

### ISSUE THREAD

**Issue by xiem22153** [greenplum-db/gpdb#6424]
I use:
pg_dump -d test01 -t metric_data1_prt_p20181012 -f /data/gpdata/gpbackup/xxx.sql;
but get:
![default](https://user-images.githubusercontent.com/35788605/49515277-78013b00-f8d1-11e8-80f6-3e8b7ca3eb9a.png)

Why is there no data,How to deal with,Thank you all.

**Comment by kyeap-pivotal** [comment]
pg_dump with the -t flag cannot dump child tables. 

```
...
Also, -t cannot be used to specify a child table partition. 
To dump a partitioned table, you must specify the parent table name.
```
More information on that can be found here. https://gpdb.docs.pivotal.io/43230/utility_guide/client_utilities/pg_dump.html
