### ISSUE TITLE
SIGSEGV occurs when a table is dropped.

### ISSUE THREAD

**Issue by pengzhout** [greenplum-db/gpdb#6434]
### Greenplum version or build
latest master 
### Step to reproduce the behavior
session1: create table foo (c1 int, c2 int);
session1: begin;
session1: drop table foo;
session2: select * from foo;
session1: end;
session2: will SIGSEGV.

**Comment by kainwen** [comment]
Thanks for the bug report.

The root cause is that `parserOpenTable` should never return NULL, but `CdbTryOpenRelation` might return NULL.

 https://github.com/greenplum-db/gpdb/blob/master/src/backend/parser/parse_relation.c#L1011
