### ISSUE TITLE
pg_dump doesn't dump child partition dependencies in the correct order

### ISSUE THREAD

**Issue by jchampio** [greenplum-db/gpdb#6455]
### Greenplum version or build

`master` branch. Haven't checked 4 or 5 yet, but from a code skim it looks like they probably suffer the same issue.

### Expected behavior

If a table in a cluster depends on a child partition for some reason, then `pg_dump` should create the partitioned table before creating the dependent table.

### Actual behavior

Since `pg_dump` doesn't include child partitions in its dependency graph (it [skips them entirely](https://github.com/greenplum-db/gpdb/blob/5844158/src/bin/pg_dump/pg_dump.c#L5075-L5076)), the actual dump order is undefined.

### Step to reproduce the behavior

With the following schema,
```sql
CREATE TABLE part (a int, b int) PARTITION BY RANGE(b) (START(1) END(2) EVERY(1));
-- NOTICE:  CREATE TABLE will create partition "part_1_prt_1" for table "part"
CREATE TABLE dep (a int, b part_1_prt_1);
```
here's what `pg_dump --schema-only` produces on my machine:
```sql
--
-- Name: dep; Type: TABLE; Schema: public; Owner: pchampion; Tablespace:
--

CREATE TABLE dep (
    a integer,
    b part_1_prt_1
) DISTRIBUTED BY (a);


ALTER TABLE dep OWNER TO pchampion;

--
-- Name: part; Type: TABLE; Schema: public; Owner: pchampion; Tablespace:
--

CREATE TABLE part (
    a integer,
    b integer
) DISTRIBUTED BY (a) PARTITION BY RANGE(b)
          (
          START (1) END (2) EVERY (1) WITH (tablename='part_1_prt_1', appendonly=false )
          );


ALTER TABLE part OWNER TO pchampion;
```
In this example, `dep` is created first, but one of its column types (`part_1_prt_1`) hasn't been created yet. This fails to restore.

Thanks to @d for pointing out this repro case!

**Comment by adam8157** [comment]
Tested, it's fixed by 12 merge, close this.
