### ISSUE TITLE
EXCHANGE PARTITION allows NULL value in partition key columns

### ISSUE THREAD

**Issue by jchampio** [greenplum-db/gpdb#6472]
### Greenplum version or build

`master`

### Expected behavior

GPDB should refuse to exchange a partition with a table that contains `NULL` values in its partition-key columns, if the partition's definition does not include `NULL`.

### Actual behavior

GPDB allows such an exchange to take place, and the resulting table has data that would not have been allowed to be inserted.

### Step to reproduce the behavior

```sql
CREATE TABLE part (a int)
    PARTITION BY RANGE(a) (START(1) END(2) EVERY(1));
CREATE TABLE newpart (LIKE part);

INSERT INTO newpart VALUES (null);
ALTER TABLE part EXCHANGE PARTITION FOR (1) WITH TABLE newpart;

SELECT * FROM part;
 a
---

(1 row)
```

We haven't RCA'd, but we suspect that this is due to the fact that a `CHECK` constraint will accept null values unless you explicitly reject them (which our partition `CHECK` constraints do not).

**Comment by asimrp** [comment]
How are NULL values dealt with in partition definitions in upstream PostgreSQL?

**Comment by soumyadeep2007** [comment]
Ideally, we should use this opportunity to align with upstream behavior:

1. We should create a NOT NULL constraint on each partition key for each child partition automatically while creating a partition hierarchy.

2. When we exchange partition, just like we create the check constraint for the "exchanged" table, we should add that NOT NULL constraint. If the partition to be exchanged had any nulls, trying to add the null constraint should fail. This should, in theory, very conveniently, make the EXCHANGE PARTITION fail. This failure would be akin to:

```
CREATE TABLE part (a int)                                                                                                                                                                                 PARTITION BY RANGE(a) (START(1) END(2) EVERY(1));
create table part_to_be_exchanged2(a int);
insert into part_to_be_exchanged2 values(10000);
ALTER TABLE part EXCHANGE PARTITION FOR (1) WITH TABLE part_to_be_exchanged2;
ERROR:  exchange table contains a row which violates the partitioning specification of "part"  (seg2 127.0.0.1:25434 pid=43926)
```

**Comment by lij55** [comment]
it is fixed on master/7:
```sql
test=# ALTER TABLE part EXCHANGE PARTITION FOR (1) WITH TABLE newpart;
ERROR:  partition constraint is violated by some row  (seg0 172.17.0.2:10000 pid=6751)test=# 
test=# SELECT * FROM part;
 a 
---
(0 rows)
```
but still exists on 6.

**Comment by dpandhi-git** [comment]
closing as fixed on GP7, not pressing need to fix on 6x. will revisit in case resurfaced
