### ISSUE TITLE
Error connecting to the server: FATAL:  DTM initialization: failure during startup recovery, retry failed, check segment status (cdbtm.c:1517)

### ISSUE THREAD

**Issue by ysc320106** [greenplum-db/gpdb#6473]
i see this error when i usr the pgAdmin III to connect gpdb . the config file is all default.
i didn't  see anyone report the error with (cdbtm.c:1517)

**Comment by pingLitian** [comment]
please give me a anwser of this question

**Comment by ashwinstar** [comment]
The details provided for the problem you are facing are very thin. To understand the issue and provide any help, giving clear and full details the must.

What version are you using? Repro steps? Are you connecting to master or segments? Normal connections outside of pgadmin connect to the database, fine? Does it always happen or sometimes seen? Any more details you can share to understand the issue better.

**Comment by hlinnaka** [comment]
Nothing we can do without more information. Closing, but feel free to re-open, with additional details, if you can still reproduce this.
