### ISSUE TITLE
Split update not working during concurrent update of same tuple

### ISSUE THREAD

**Issue by vraghavan78** [greenplum-db/gpdb#6488]
GPDB master.

Issue discovered during https://github.com/greenplum-db/gpdb/pull/6245

Originally it was determined it was an GPORCA problem, but after investigation, the team found that this planner plan with split update is also broken.

**Comment by zellerh** [comment]
This is an issue with how executor handles split update. This can be reproduced using planner too. Planner goes for split update when we update the distribution column. 

To reproduce in planner, have two terminals open T1 and T2

```
T1: set optimizer to off;
T1: create table t1(a int, b int) distributed by (a);
T1: begin;
T1: update t1 set a=a+10 where a=1;
T2: set optimizer to off;
T2: update t1 set a=a+15 where a=1;
T1: commit;
T1: select * from t1;
```
This produces the wrong result:
```
 a  | b
----+---
 16 | 1
 11 | 1
(2 rows)
```

**Comment by Eulerizeit** [comment]
https://github.com/greenplum-db/gpdb/pull/6506

**Comment by gaos1** [comment]
fixed by https://github.com/greenplum-db/gpdb/pull/6828
