### ISSUE TITLE
Segfault in error handling

### ISSUE THREAD

**Issue by hlinnaka** [greenplum-db/gpdb#6534]
I was working on a patch, which caused an ERROR to be raised in ExecWorkFile_Tell64(). When I hit that ERROR in the `workfile/hashjoin_spill` test, a segfault happened during abort processing:

 
    0,,,,"1    0x55c59bc9f743 postgres StandardHandlerForSigillSigsegvSigbus_OnMainThread + 0x1bd
    2    0x55c59bb226ce postgres <symbol not found> + 0x9bb226ce
    3    0x7f0a9caff6b0 libpthread.so.0 <symbol not found> + 0x9caff6b0
    4    0x55c59bd432a0 postgres <symbol not found> + 0x9bd432a0
    5    0x55c59bd435c1 postgres <symbol not found> + 0x9bd435c1
    6    0x55c59bd45966 postgres <symbol not found> + 0x9bd45966
    7    0x55c59bd4616c postgres TeardownUDPIFCInterconnect + 0x72
    8    0x55c59bd37098 postgres TeardownInterconnect + 0x43
    9    0x55c59bd379cb postgres <symbol not found> + 0x9bd379cb
    10   0x55c59bd37a6c postgres <symbol not found> + 0x9bd37a6c
    11   0x55c59bce1d29 postgres <symbol not found> + 0x9bce1d29
    12   0x55c59bce17c1 postgres <symbol not found> + 0x9bce17c1
    13   0x55c59bce1736 postgres ResourceOwnerRelease + 0xe5
    14   0x55c59b6e7ac0 postgres <symbol not found> + 0x9b6e7ac0
    15   0x55c59b6e54f8 postgres AbortCurrentTransaction + 0x1c8
    16   0x55c59bb2472e postgres PostgresMain + 0x6f5
    17   0x55c59ba928e4 postgres <symbol not found> + 0x9ba928e4
    18   0x55c59ba91f49 postgres <symbol not found> + 0x9ba91f49

 This can be reproduced by applying this patch:  

```
diff --git a/src/backend/executor/nodeHash.c b/src/backend/executor/nodeHash.c
index ed2862581d..0abb0d6c83 100644
--- a/src/backend/executor/nodeHash.c
+++ b/src/backend/executor/nodeHash.c
@@ -1662,8 +1662,11 @@ ExecHashTableExplainBatchEnd(HashState *hashState, HashJoinTable hashtable)
         /* How much was read from outer workfiles for current batch? */
 		if (hashtable->outerBatchFile &&
 			hashtable->outerBatchFile[curbatch] != NULL)
+		{
+			elog(ERROR, "simulate error");
             batchstats->ordbytes =
 				ExecWorkFile_Tell64(hashtable->outerBatchFile[curbatch]);
+		}
 
 		/*
 		 * How much was written to workfiles for the remaining batches?
```

and running the `workfile/hashjoin_spill` test.

**Comment by gkokolatos** [comment]
#6508 removes WorkFiles, which makes this issue irrelevant.

Closing.
