### ISSUE TITLE
gpstart doesn't rebalance segments correctly

### ISSUE THREAD

**Issue by xiong-gang** [greenplum-db/gpdb#6542]
reproduce steps:
1. shutdown primary segment 0
2. run `gprecoverseg -aF` to trigger primary/mirror transition
3. gpstop
4. gpstart
gpstart will try to rebalance the primary and mirror of segment 0 by updating `gp_segment_configuration`, but it doesn't handle `recovery.conf` and so on.
One observable symptom is FTS process will assert failure because primary segment 0 still think it's playing mirror role.

It works well if we run `gprecoverseg -r` to trigger rebalance after step 2.

**Comment by asimrp** [comment]
This is missing functionality compared to Greenplum 5 and we don't have a consensus on whether to implement it in 6 or get rid of it (gpstart shouldn't attempt to rebalance): https://groups.google.com/a/greenplum.org/d/msg/gpdb-dev/CiMJoBahfVc/AlxYyZFBCQAJ

**Comment by xiong-gang** [comment]
Thanks Asim.
