### ISSUE TITLE
Where is README.CentOS.bash？

### ISSUE THREAD

**Issue by QiangLion** [greenplum-db/gpdb#6550]
Where is README.CentOS.bash？

**Comment by paul-guo-** [comment]
README.CentOS.bash is under the root directory of the repository.

**Comment by xyzhh** [comment]
Same question,there is no file README.CentOS.bash in version 5.xx.x, anybody?

**Comment by xyzhh** [comment]
> README.CentOS.bash is under the root directory of the repository.

只在Master内测版本里有？官方连链接的5.xx版里都找不到啊？

**Comment by hardywen** [comment]
> > README.CentOS.bash is under the root directory of the repository.
> 
> 只在Master内测版本里有？官方连链接的5.xx版里都找不到啊？

发布的包里是没有，直接在源文件里复制就好了，里面的内容不多，就一点点脚本代码。我就是直接加个文件然后复制里面的内容进去用了。
