### ISSUE TITLE
possible memory leak when creating tables

### ISSUE THREAD

**Issue by bianhq** [greenplum-db/gpdb#6559]
### Greenplum version or build
6.0

I read the source code in src/backend/commands/tablecmds.c
[line 689](https://github.com/greenplum-db/gpdb/blob/master/src/backend/commands/tablecmds.c#L689), `heap_reloptions` returns a pointer of bytea, which is allocated by `allocateReloptStruct` inside the function:

```c
	/*
	 * Parse and validate reloptions, if any.
	 */
	reloptions = transformRelOptions((Datum) 0, stmt->options, NULL, validnsps,
									 true, false);

	(void) heap_reloptions(relkind, reloptions, true);    // line 689
```
but it seems the returned bytea pointer is not freed.

Is this a memory leak?

Thanks.

**Comment by paul-guo-** [comment]
No. The memory is taken care by memory context.

**Comment by bianhq** [comment]
Got it, thanks.
