### ISSUE TITLE
Bring queryCommandId back to PGPROC for better monitorability

### ISSUE THREAD

**Issue by magi345** [greenplum-db/gpdb#6569]
In https://github.com/greenplum-db/gpdb/commit/318e6c396eecfa5286358392a177f609a12c7dc5 some unused code was deleted, including `queryCommandId` from `PGPROC` struct.

However, when metrics_collector comes to GP6, we found that from monitoring perspective we strongly rely on this counter to do lots of work in the command center side.
This issue is to discuss if we can bring it back to GP.

Generally speaking, metrics_collector access `queryCommandId` from PGPROC in shmem to sync the gpdb internal status with external monitor agents. Under the complex network situation, async communication, and distributed system, we deeply rely on this counter to help maintain consistency for the command center. Such as garbage cleaning, history harvesting, alerting, and etc...

I have a draft fix https://github.com/magi345/gpdb/commit/9543c587594e2fb75aa3f6f2d002c1ae29c7b602
Any suggestions are welcomed. Particularly please let us know your opinions on the following questions.
  - Are there any places to make use of this counter?
  - Any test approach?

Ning Fu & Hao Wang

**Comment by hlinnaka** [comment]
Seems strange that you're accessing the ProcArray directly from the metrics collector. The backend itself can look at the global `gp_command_count` variable, is that not enough?

**Comment by magi345** [comment]
In the current implementation,
- Backends emit the global `gp_command_count` with query lifecycle events.
- A stand-alone metrics collector process play as a sidecar to emit ProcArray and friends.

We have this design from GP5 due to many reasons, such as
- query started before monitoring agent go alive
- query being queued by RG, or blocked in the optimizer, before it can fire lifecycle events to the monitoring agent
- packet loss
- packet order changed during transportation or routine scheduling

Data from ProcArray help out above cases, so we can use queryCommandId to calibrate the status of agents.
