### ISSUE TITLE
gpperfmon: gpmon also send packets for EXPLAIN-only queries

### ISSUE THREAD

**Issue by geekbosszhang** [greenplum-db/gpdb#6584]
### Expected behavior
 For explain only queries, don't need to send gpmon packets for plan nodes.
### Actual behavior
Currently, gpmon packets are also sent for explain queries, cause `ExplainOnePlan` calls `ExecutorStart/End` , inside Executor all plan nodes are called `ExecInitNode/ExecEndNode`, then gpmon packet is sent.

For this issue, could make improvement for gpperfmon code on master.

**Comment by adam8157** [comment]
gpperfmon was removed from Greenplum, close this. Feel free to reopen if you decide to fix it on, like 5X, one day.
