### ISSUE TITLE
5X_STABLE: median() with GROUP BY fails on some datasets

### ISSUE THREAD

**Issue by leskin-in** [greenplum-db/gpdb#6585]
## Summary
In Greenplum 5X_STABLE, queries using both `median()` and `GROUP BY` fail on certain datasets.

The error does not reproduce on `master` branch.

## Description
Certain datasets cause queries with both `median()` and `GROUP BY` to fail with an `ERROR:  Mergejoin: compareResult > 0, bad plan ? (nodeMergejoin.c:1172)`. An example to reproduce the error:
```
DROP TABLE IF EXISTS tab;
DROP TABLE
CREATE TABLE tab(n INT, t VARCHAR) DISTRIBUTED RANDOMLY;
CREATE TABLE
INSERT INTO tab(n, t) VALUES (1, 'им Казыбек би'),  (2, 'Им Казыбекби');
INSERT 0 2
SELECT median(n) FROM tab GROUP BY t;
psql:test_failure.sql:6: ERROR:  Mergejoin: compareResult > 0, bad plan ? (nodeMergejoin.c:1172)  (seg1 slice3 10.2.58.3:20001 pid=81249) (cdbdisp.c:254)
```
pg_log:
```
2018-12-28 11:11:33.749435 MSK,"gpadmin","adb",p6873,th1883789376,"[local]",,2018-12-28 11:11:32 MSK,0,con16,cmd7,seg-1,,dx42,,sx1,"LOG","00000","statement: SELECT median(n) FROM tab GROUP BY t;",,,,,,"SELECT median(n) FROM tab GROUP BY t;",0,,"postgres.c",1590,
2018-12-28 11:11:34.042351 MSK,"gpadmin","adb",p6873,th1883789376,"[local]",,2018-12-28 11:11:32 MSK,0,con16,cmd8,seg-1,,dx42,,sx1,"ERROR","XX000","Mergejoin: compareResult > 0, bad plan ? (nodeMergejoin.c:1172)  (seg1 slice3 10.2.58.3:20001 pid=81249) (cdbdisp.c:254)",,,,,,"SELECT median(n) FROM tab GROUP BY t;",0,,"cdbdisp.c",254,"Stack trace:
1    0x8e9956 postgres errstart + 0x1f6
2    0x96cf3c postgres cdbdisp_finishCommand + 0x1ac
3    0x96d132 postgres CdbDispatchHandleError + 0x172
4    0x65e796 postgres mppExecutorCleanup + 0x66
5    0x647d5d postgres ExecutorRun + 0x1ad
6    0x7da592 postgres <symbol not found> + 0x7da592
7    0x7dbf61 postgres PortalRun + 0x191
8    0x7d70c2 postgres <symbol not found> + 0x7d70c2
9    0x7d931c postgres PostgresMain + 0x1a3c
10   0x77c1b6 postgres <symbol not found> + 0x77c1b6
11   0x77db32 postgres PostmasterMain + 0xc52
12   0x48fe93 postgres main + 0x393
13   0x7ff46ef1b3d5 libc.so.6 __libc_start_main + 0xf5
14   0x48ffb0 postgres <symbol not found> + 0x48ffb0
"
2018-12-28 11:11:34.042586 MSK,"gpadmin","adb",p6873,th1883789376,"[local]",,2018-12-28 11:11:32 MSK,0,con16,cmd8,seg-1,,dx42,,sx1,"LOG","00000","An exception was encountered during the execution of statement: SELECT median(n) FROM tab GROUP BY t;",,,,,,,0,,,,
```
**A plan for this query is quite complex**; basically, the presence of `MergeJoin` node is a cause of the error:
```
EXPLAIN SELECT median(n) FROM tab GROUP BY t;
                                                      QUERY PLAN                                                       
-----------------------------------------------------------------------------------------------------------------------
 Gather Motion 4:1  (slice3; segments: 4)  (cost=4.72..4.80 rows=2 width=40)
   ->  GroupAggregate  (cost=4.72..4.80 rows=1 width=40)
         Group By: share0_ref2.t
         ->  Merge Join  (cost=4.72..4.77 rows=1 width=0)
               Merge Cond: NOT share0_ref2.t::text IS DISTINCT FROM share0_ref1.t::text
               ->  Sort  (cost=2.31..2.32 rows=1 width=28)
                     Sort Key: share0_ref2.t, share0_ref2.unnamed_attr
                     ->  Redistribute Motion 4:4  (slice1; segments: 4)  (cost=2.06..2.30 rows=1 width=28)
                           Hash Key: share0_ref2.t
                           ->  Shared Scan (share slice:id 1:0)  (cost=2.06..2.26 rows=1 width=28)
               ->  Sort  (cost=2.40..2.41 rows=1 width=40)
                     Sort Key: share0_ref1.t
                     ->  HashAggregate  (cost=2.34..2.37 rows=1 width=40)
                           Group By: share0_ref1.t
                           ->  Redistribute Motion 4:4  (slice2; segments: 4)  (cost=2.27..2.31 rows=1 width=64)
                                 Hash Key: share0_ref1.t
                                 ->  HashAggregate  (cost=2.27..2.27 rows=1 width=64)
                                       Group By: share0_ref1.t
                                       ->  Shared Scan (share slice:id 2:0)  (cost=2.06..2.26 rows=1 width=28)
                                             ->  Materialize  (cost=2.04..2.06 rows=1 width=28)
                                                   ->  Subquery Scan nondeduplicate  (cost=0.00..2.04 rows=1 width=28)
                                                         ->  Seq Scan on tab  (cost=0.00..2.02 rows=1 width=28)
 Optimizer status: legacy query optimizer
(23 rows)
```
The same plan is produced with ORCA enabled.

### Sample from the dataset
The actual dataset consists of 5000 tuples, each with one of 261 town names and numbers associated with them (not listed). Multiple naming variants are allowed (thus, there may be multiple highly similar strings present in one column).

One town name causes the error. There are 10 naming variants for it, but exactly two of them are important: `'им Казыбек би'` and `'Им Казыбекби'`. If one or both are removed from the dataset, no error happens. One tuple with each name is enough to reproduce the error; extra tuples do not change the situation.

The names are:
```
им
Им. Казыбек
им Казыбек би
Им Казыбекби
Им. Казыбек-би
Им Казыбек-Би
Им. Казыбек Би
Им. Казыбек-Би
Им.Казыбек-Би
Им. Кзыбек-Би
```

## Proposed solution
I found a (probable) cause of the error: [`varstr_cmp()`](https://github.com/greenplum-db/gpdb/blob/7ab79eac1c41ef4cf4e3cd0f636275862c05b795/src/backend/utils/adt/varlena.c#L1136) comparison function.

This function is used by both `Sort` and `MergeJoin` nodes; despite this, the sort order for tuples to be merged seems to be incorrect and [an assertion in `nodeMergejoin.c`](https://github.com/greenplum-db/gpdb/blob/7ab79eac1c41ef4cf4e3cd0f636275862c05b795/src/backend/executor/nodeMergejoin.c#L1171) fails.

I [tried](https://github.com/arenadata/gpdb/commits/ADBDEV-103) to fix the comparison function using different approaches. These changed the sort order in some cases, but **did not fix the error**; it was still possible to find a combination of strings (from the same dataset) on which the sort order was incorrect. The three key ideas were:
* Cutting string at the point where two different strings are of equal byte length, but taking into consideration UTF-8 variable length encoding (motivation: strings of equal length are always compared correctly);
* Use byte-by-byte strings comparison;
* Convert all strings to wide character representation (`pg_wchar`) and compare them using `mb/pg_wchar.h` (also try symbol-by-symbol comparison).

I would like to point out that `median()` is translated into a complex query plan. In addition to other operations, it involves `SharedScan` nodes whose effects are quite complex (I have found description at https://groups.google.com/a/greenplum.org/forum/#!topic/gpdb-dev/PQAbsNv23gE, https://gpcc.docs.pivotal.io/210/gpcc/topics/db-iterator-metrics.html and https://content.pivotal.io/blog/greenplum-database-adds-the-pivotal-query-optimizer). A way to fix the error could be to modify `median()` function so that it produces some other query plan.

## Instance installation information
* **GPDB**: [`5.8.0+dev.614.g7ab79ea build dev`](https://github.com/greenplum-db/gpdb/tree/7ab79eac1c41ef4cf4e3cd0f636275862c05b795)
* **OS**: `CentOS Linux release 7.6.1810 (Core)`, `Linux mdw 3.10.0-862.11.6.el7.x86_64 #1 SMP Tue Aug 14 21:49:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
* **autoconf**: `'--disable-orca' '--prefix=/usr/lib/gpdb'`
* **pg_config**:
```
BINDIR = /usr/lib/gpdb/bin
DOCDIR = /usr/lib/gpdb/doc/postgresql
HTMLDIR = /usr/lib/gpdb/doc/postgresql
INCLUDEDIR = /usr/lib/gpdb/include
PKGINCLUDEDIR = /usr/lib/gpdb/include/postgresql
INCLUDEDIR-SERVER = /usr/lib/gpdb/include/postgresql/server
LIBDIR = /usr/lib/gpdb/lib
PKGLIBDIR = /usr/lib/gpdb/lib/postgresql
LOCALEDIR = /usr/lib/gpdb/share/locale
MANDIR = /usr/lib/gpdb/share/man
SHAREDIR = /usr/lib/gpdb/share/postgresql
SYSCONFDIR = /usr/lib/gpdb/etc/postgresql
PGXS = /usr/lib/gpdb/lib/postgresql/pgxs/src/makefiles/pgxs.mk
CC = gcc
CPPFLAGS = -D_GNU_SOURCE -I/usr/lib/gpdb/include
CFLAGS = -O3 -std=gnu99 -Wall -Wmissing-prototypes -Wpointer-arith -Wendif-labels -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fno-aggressive-loop-optimizations -Wno-unused-but-set-variable -Wno-address -I/usr/lib/gpdb/include
CFLAGS_SL = -fpic
LDFLAGS = -Wl,--as-needed -Wl,-rpath,'/usr/lib/gpdb/lib',--enable-new-dtags -L/usr/lib/gpdb/lib
LDFLAGS_SL = 
LIBS = -lpgport -lrt -lcrypt -ldl -lm -L/usr/lib/gpdb/lib
VERSION = PostgreSQL 8.3.23
```

**Comment by lij55** [comment]
Hi @leskin-in , please feel free to reopen it if this is still affect. As we are migrating to GP6 and later so we would close this GP5-only issue now.
