### ISSUE TITLE
5X_STABLE: sort order for VARCHAR is incorrect on some datasets

### ISSUE THREAD

**Issue by leskin-in** [greenplum-db/gpdb#6586]
## Summary
In Greenplum 5X_STABLE, `VARCHAR` sort order (e.g. produced by `ORDER BY`) is incorrect on certain datasets.

The error does not reproduce on `master` branch.

### Description
This issue is closely related to https://github.com/greenplum-db/gpdb/issues/6585. There, a particular dataset causes `Mergejoin` node to fail with `ERROR:  Mergejoin: compareResult > 0, bad plan ? (nodeMergejoin.c:1172)`. Working on that bug, I found out its (probable) cause: [`varstr_cmp()`](https://github.com/greenplum-db/gpdb/blob/7ab79eac1c41ef4cf4e3cd0f636275862c05b795/src/backend/utils/adt/varlena.c#L1136) comparison function.

This function is used by both `Sort` and `MergeJoin` nodes; despite this, *the sort order* for tuples to be merged *seems to be incorrect* and [an assertion in `nodeMergejoin.c`](https://github.com/greenplum-db/gpdb/blob/7ab79eac1c41ef4cf4e3cd0f636275862c05b795/src/backend/executor/nodeMergejoin.c#L1171) fails.

The following queries illustrate the problem:
```
DROP TABLE IF EXISTS kazybek;
DROP TABLE
CREATE TABLE kazybek(t VARCHAR) DISTRIBUTED RANDOMLY;
CREATE TABLE
INSERT INTO kazybek(t) VALUES ('им'),  ('Им. Казыбек'), ('им Казыбек би'), ('Им Казыбекби');
INSERT 0 4
SELECT t FROM kazybek ORDER BY t ASC;
       t       
---------------
 им
 Им. Казыбек
 им Казыбек би
 Им Казыбекби
(4 rows)

SELECT 'им Казыбек би' <= 'Им Казыбекби';
 ?column? 
----------
 f
(1 row)
```

Note that correct lexicographical sort order should put strings starting with `и` before ones starting with `И` or vice versa, but it must not mix them.

### Sample from the dataset
The actual dataset consists of 5000 tuples, each with one of 261 town names and numbers associated with them (not listed). Multiple naming variants are allowed (thus, there may be multiple highly similar strings present in one column). The names are:
```
им
Им. Казыбек
им Казыбек би
Им Казыбекби
Им. Казыбек-би
Им Казыбек-Би
Им. Казыбек Би
Им. Казыбек-Би
Им.Казыбек-Би
Им. Кзыбек-Би
```
When I changed the comparison function, the sort order changed, too, but it was possible to find incorrectly sorted pair in the given dataset. The bug with `median()` was not fixed, too.

## Proposed solution
I [tried](https://github.com/arenadata/gpdb/commits/ADBDEV-103) to fix the comparison function using different approaches. These changed the sort order in some cases, but **did not fix the error**; it was still possible to find a combination of strings (from the same dataset) on which the sort order was incorrect. The three key ideas were:
* Cutting string at the point where two different strings are of equal byte length, but taking into consideration UTF-8 variable length encoding (motivation: strings of equal length are always compared correctly);
* Use byte-by-byte strings comparison;
* Convert all strings to wide character representation (`pg_wchar`) and compare them using `mb/pg_wchar.h` (also try symbol-by-symbol comparison).

## Instance installation information
* **GPDB**: [`5.8.0+dev.614.g7ab79ea build dev`](https://github.com/greenplum-db/gpdb/tree/7ab79eac1c41ef4cf4e3cd0f636275862c05b795)
* **OS**: `CentOS Linux release 7.6.1810 (Core)`, `Linux mdw 3.10.0-862.11.6.el7.x86_64 #1 SMP Tue Aug 14 21:49:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
* **autoconf**: `'--disable-orca' '--prefix=/usr/lib/gpdb'`
* **pg_config**:
```
BINDIR = /usr/lib/gpdb/bin
DOCDIR = /usr/lib/gpdb/doc/postgresql
HTMLDIR = /usr/lib/gpdb/doc/postgresql
INCLUDEDIR = /usr/lib/gpdb/include
PKGINCLUDEDIR = /usr/lib/gpdb/include/postgresql
INCLUDEDIR-SERVER = /usr/lib/gpdb/include/postgresql/server
LIBDIR = /usr/lib/gpdb/lib
PKGLIBDIR = /usr/lib/gpdb/lib/postgresql
LOCALEDIR = /usr/lib/gpdb/share/locale
MANDIR = /usr/lib/gpdb/share/man
SHAREDIR = /usr/lib/gpdb/share/postgresql
SYSCONFDIR = /usr/lib/gpdb/etc/postgresql
PGXS = /usr/lib/gpdb/lib/postgresql/pgxs/src/makefiles/pgxs.mk
CC = gcc
CPPFLAGS = -D_GNU_SOURCE -I/usr/lib/gpdb/include
CFLAGS = -O3 -std=gnu99 -Wall -Wmissing-prototypes -Wpointer-arith -Wendif-labels -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fno-aggressive-loop-optimizations -Wno-unused-but-set-variable -Wno-address -I/usr/lib/gpdb/include
CFLAGS_SL = -fpic
LDFLAGS = -Wl,--as-needed -Wl,-rpath,'/usr/lib/gpdb/lib',--enable-new-dtags -L/usr/lib/gpdb/lib
LDFLAGS_SL = 
LIBS = -lpgport -lrt -lcrypt -ldl -lm -L/usr/lib/gpdb/lib
VERSION = PostgreSQL 8.3.23
```

**Comment by hlinnaka** [comment]
Hmm. What locale are you using (`show lc_collate`)? `SELECT 'им Казыбек би' <= 'Им Казыбекби'` returns true for me, on both en_GB.utf8 and ru_RU.utf8 locales.

I find it hard to believe that varstr_cmp() would be broken. It's identical to upstream's.

To narrow this down, can you reproduce this if you `set gp_enable_mk_sort = off` and/or `set gp_enable_motion_mk_sort=off`?

**Comment by leskin-in** [comment]
@hlinnaka ,
I have tried locales `en_US.utf8` and `ru_RU.utf8` earlier (though with less tests, involving only `median()` function call); https://github.com/greenplum-db/gpdb/issues/6585 was reproduced.

After your comment, I have executed tests mentioned above against a database with locale `ru_RU.utf8`, with exactly same results. The same is true for tests with modified ``gp_enable_motion_mk_sort` or `gp_enable_mk_sort`.

Setting `gp_enable_motion_mk_sort=off` changes output to:
```
SELECT t FROM kazybek ORDER BY t ASC;
       t       
---------------
 им
 Им. Казыбек
 Им Казыбекби
 им Казыбек би
(4 rows)
```
Unfortunately, this is still incorrect sort order.

Setting `gp_enable_mk_sort = off` (with or without `gp_enable_motion_mk_sort=off`) does not change the result.

**Comment by hlinnaka** [comment]
> Setting `gp_enable_motion_mk_sort=off` changes output to:

A-ha! I assume you're building from source? Can you try cherry-picking commit fbd50c90ba from master? Come to think of it, that should've been backported in any case...

**Comment by hlinnaka** [comment]
> > Setting `gp_enable_motion_mk_sort=off` changes output to:
> 
> A-ha! I assume you're building from source? Can you try cherry-picking commit [fbd50c9](https://github.com/greenplum-db/gpdb/commit/fbd50c90bad0fae37f3ba76410448eff0170178c) from master? Come to think of it, that should've been backported in any case...

Oh, scratch that, that bug affected the gp_enable_motion_mk_sort=off case, but doesn't explain the mismatch between <= and ORDER BY ASC, when gp_enable_motion_mk_sort=on.

**Comment by hlinnaka** [comment]
@leskin-in, do you have any more clues on how I could reproduce this? I'd love to get to the bottom of this.

The script in In https://github.com/postgrespro/pgwininstall/issues/6, uses a custom "mvarchar" datatype, so I'm not sure if that example is applicable to GPDB.

I wonder if this is a bug in the locale on CentOS? What happens if you sort those strings in the shell using `sort` command?

**Comment by leskin-in** [comment]
@hlinnaka ,
I have re-checked that and found this is most likely cause: `sort` results are inconsistent, as described above. Also, I have tried running the following code:
```
#include <string.h>
#include <stdio.h>
#include <stdlib.h>

int comparator(const void* a, const void* b) {
	const char* a1 = (const char*)a;
	const char* b1 = (const char*)b;
	return strcoll(a1, b1);
}

int main() {
	char* texts[] = {"им", "Им. Казыбек", "им Казыбек би",  "Им Казыбекби"};
	qsort(texts, 4, sizeof(char*), comparator);
	for (int i = 0; i < 4; i++) {
		printf("%s\n", texts[i]);
	}	
	return 0;
}
```
and the results were inconsistent:
```
им Казыбек би
Им Казыбекби
им
Им. Казыбек
```

Test machines use `GNU libc 2.17`.

**Comment by hlinnaka** [comment]
The 'comparator` function in your test program is wrong, should be:
```
int comparator(const void* a, const void* b) {
	const char* a1 = *(const char**)a;
	const char* b1 = *(const char**)b;

	return strcoll(a1, b1);
}
```

**Comment by hlinnaka** [comment]
Also, you should call `setlocale(LC_ALL, "");` at the beginning of the program, otherwise it runs in C locale.

**Comment by leskin-in** [comment]
Thank you for correction! Now execution of the following code
```
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#include <locale.h>


int comparator(const void* a, const void* b) {
	const char* a1 = (const char*)a;
	const char* b1 = (const char*)b;
	return strcoll(a1, b1);
}

int
main ()
{
	setlocale(LC_ALL, "");
	char* texts[] = {"им", "Им. Казыбек", "Им. Казыбек-би", "им Казыбек би",  "Им Казыбекби"};
	qsort(texts, 5, sizeof(char*), comparator);
	for (int i = 0; i < 5; i++) {
		printf("%s\n", texts[i]);
	}	
	return 0;
}
```
returns output
```
им Казыбек би
Им Казыбекби
Им. Казыбек-би
им
Им. Казыбек
```

**Comment by hlinnaka** [comment]
Ok, so that agrees with the `'им Казыбек би' <='Им Казыбекби'` false result you showed earlier, and disagrees with the order returned by the query. Makes me wonder if there's a bug in sorting, then.

What does this return?
```
values ('им'), ('Им. Казыбек'), ('Им Казыбекби'), ('им Казыбек би'), ('Им. Казыбек-би') ORDER BY 1;
```

**Comment by leskin-in** [comment]
```
=# values ('им'), ('Им. Казыбек'), ('Им Казыбекби'), ('им Казыбек би'), ('Им. Казыбек-би') ORDER BY 1;
    column1     
----------------
 им
 Им. Казыбек
 им Казыбек би
 Им Казыбекби
 Им. Казыбек-би
(5 rows)
```

**Comment by hlinnaka** [comment]
Thanks! I was able to reproduce this now, on a CentOS 7 virtual machine.

Earlier, you said that `gp_enable_mk_sort` didn't make a difference, but I am seeing a difference here:
```
postgres=# set gp_enable_mk_sort=on;
SET
postgres=# values ('им'), ('Им. Казыбек'), ('Им Казыбекби'), ('им Казыбек би'), ('Им. Казыбек-би') ORDER BY 1;
    column1     
----------------
 им
 Им. Казыбек
 им Казыбек би
 Им Казыбекби
 Им. Казыбек-би
(5 rows)

postgres=# set gp_enable_mk_sort=off;
SET
postgres=# values ('им'), ('Им. Казыбек'), ('Им Казыбекби'), ('им Казыбек би'), ('Им. Казыбек-би') ORDER BY 1;
    column1     
----------------
 им
 Им. Казыбек
 Им Казыбекби
 им Казыбек би
 Им. Казыбек-би
(5 rows)
```

**Comment by hlinnaka** [comment]
Ok, this seems to be because strxfrm() on glibc is buggy. We found this out the hard way in PostgreSQL, when we tried to make use of strxfrm() to speed up sorting in 9.5, and had to revert it. See https://www.postgresql.org/message-id/flat/111D0E27-A8F3-4A84-A4E0-B0FB703863DF@s24.com.


This can be shown with this little test program:
```
#include <locale.h>
#include <string.h>
#include <stdio.h>
#include <stdlib.h>

int main() {
  int i, j;
  char* texts[] = {"Им. Казыбек", "им Казыбек би",  "Им Казыбекби", "им"};
  char *xformed[4];

  setlocale(LC_ALL, "");

  for (i = 0; i < 4; i++) {
    char buf[1000];
    int n;

    n = strxfrm(buf, texts[i], sizeof(buf));
    printf("%s: ", texts[i]);
    for (j = 0; j < n; j++)
      {
	printf("%02X", (unsigned char) buf[j]);
      }
    printf("\n");

    xformed[i] = strdup(buf);
  }

  for (i = 1; i < 4; i++) {
    char *a = texts[i-1];
    char *b = texts[i];

    printf ("\"%s\" vs \"%s\" using strcoll: %d\n", texts[i - 1], texts[i], strcoll(a, b));

    a = xformed[i-1];
    b = xformed[i];
    printf ("\"%s\" vs \"%s\" using strxfrm: %d\n", texts[i - 1], texts[i], strcmp(a, b));
  }

  return 0;
}
```
```
Им. Казыбек: C388C390C38DC2BBC386C3A4C2BCC382C38D01090909090909090909011009100909090909090103440135
им Казыбек би: C388C390C38DC2BBC386C3A4C2BCC382C38DC2BCC3880109090909090909090909090109091009090909090909090103350835
Им Казыбекби: C388C390C38DC2BBC386C3A4C2BCC382C38DC2BCC388010909090909090909090909011009100909090909090909010335
им: C388C390010909010909
"Им. Казыбек" vs "им Казыбек би" using strcoll: -1
"Им. Казыбек" vs "им Казыбек би" using strxfrm: -193
"им Казыбек би" vs "Им Казыбекби" using strcoll: 1
"им Казыбек би" vs "Им Казыбекби" using strxfrm: -7
"Им Казыбекби" vs "им" using strcoll: 1
"Им Казыбекби" vs "им" using strxfrm: 194
```

The comparisons using `strcoll` should match the comparisons done with strxfrm+strcmp. But for "им Казыбек би" vs "Им Казыбекби", they don't match. That's a libc bug.

I think we have to stop using strxfrm() in GPDB, like we did in upstream, because it's just not reliable enough on glibc versions that are commonly in use.

One remaining mystery is why you didn't see a difference from `gp_enable_mk_sort=off`. That should disable the use of strxfrm(). Are you sure you tested that correctly?

**Comment by leskin-in** [comment]
Thanks for the insight!
I retryed setting `gp_enable_mk_sort=off`, and now get the same results as in https://github.com/greenplum-db/gpdb/issues/6586#issuecomment-461399131.

**Comment by radomir9720** [comment]
> Hmm. What locale are you using (`show lc_collate`)? `SELECT 'им Казыбек би' <= 'Им Казыбекби'` returns true for me, on both en_GB.utf8 and ru_RU.utf8 locales.
> 
> I find it hard to believe that varstr_cmp() would be broken. It's identical to upstream's.
> 
> To narrow this down, can you reproduce this if you `set gp_enable_mk_sort = off` and/or `set gp_enable_motion_mk_sort=off`?

Thanks. 
`set gp_enable_mk_sort = off` works!

**Comment by hlinnaka** [comment]
https://github.com/greenplum-db/gpdb/pull/10502 has been pushed to 6X_STABLE and master, fixing this.
