### ISSUE TITLE
gpinitsystem problem when exchange fingerprint

### ISSUE THREAD

**Issue by ysjiang4869** [greenplum-db/gpdb#6592]
### Greenplum version or build
5.14

### OS version and uname -a
centos 7.5

### Expected behavior
I am developing install script for greenplum, and I do ssh fingerprint change and copy id by myself.  
When using gpiniysystem, it add fingerprint to my ~/.ssh/knownhosts. But it **overwride** content generate by my script.   
The problem is, when use hostname instean of ip , **ssh-keyscan results of hostname may be different from ssh-keyscan of ip**, so the gpinitsystem script require me to input yes too many times......

I think maybe the right way to add fingerprint is:
1.  execute key scan for all ip and write to known_hosts
2. if use hostname, read the /etc/hosts get the ip for hostname , and then ssh-keyscan the ip, last **replace the ip with hostname in the result** and write to known_hosts
3. scp known_hosts to all machine

I comment some code in gpinitsystem to avoid this problem. I think maybe the script should use method described above.

### Step to reproduce the behavior
I do this in my private cloud, so if ssh-keyscan hostname and ssh-keyscan ip produce different result, the problem can reproduce

**Comment by d** [comment]
Just be consistent: either use host names, or use ip.

**Comment by tylarb** [comment]
@d is correct - more specifically this is not a limitation of of gpssh exchange keys, but rather a security feature in ssh library itself. 

in `/etc/hosts` :
~~~
10.10.10.10  MyHost
~~~

You can easily see this - `ssh user@MyHost` will prompt to add the ssh fingerprint, but `ssh user@10.10.10.10` will prompt to add a _different_ fingerprint. The Greenplum utilities are just propagating this already existing behavior.
