### ISSUE TITLE
greenplum source 5.7.0 install but gpssh-exkeys not failed

### ISSUE THREAD

**Issue by gh95533** [greenplum-db/gpdb#6608]
### Greenplum version or build
greenplum source 5.7.0
### OS version and uname -a
Linux master 3.10.0-514.el7.x86_64 #1 SMP Tue Nov 22 16:42:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
### Expected behavior
gpssh-exkeys -f /home/gpadmin/all_segs successed
### Actual behavior
$ gpssh-exkeys  -f /home/gpadmin/all_hosts 
Traceback (most recent call last):
  File "/opt/greenplum-db/bin/gpssh-exkeys", line 48, in <module>
    import paramiko
  File "/usr/lib/python2.7/site-packages/paramiko/__init__.py", line 22, in <module>
    from paramiko.transport import SecurityOptions, Transport
  File "/usr/lib/python2.7/site-packages/paramiko/transport.py", line 38, in <module>
    from paramiko.auth_handler import AuthHandler
  File "/usr/lib/python2.7/site-packages/paramiko/auth_handler.py", line 72, in <module>
    from paramiko.ssh_gss import GSSAuth, GSS_EXCEPTIONS
  File "/usr/lib/python2.7/site-packages/paramiko/ssh_gss.py", line 55, in <module>
    GSS_EXCEPTIONS = (gssapi.GSSException,)
AttributeError: 'module' object has no attribute 'GSSException'

when i meet this question ,i check the gpssh-keys file at line 48 import  paramiko
then i execute a command 'pip list' the paramiko version 2.4.2 '

**Comment by gh95533** [comment]
when i try modify  paramiko 2.3.1
# pip list |grep paramiko
paramiko                         2.3.1
the error is the same as old

**Comment by jimmyyih** [comment]
Most likely your Python cryptography library is not up-to-date.  Try running `pip install paramiko --upgrade`.

**Comment by gh95533** [comment]
when i try to execute 'pip uninstall gssapi' then execute 'gpssh-exkeys' is successed
