### ISSUE TITLE
GUC variables cannot be rolled back in some QEs if an error happens

### ISSUE THREAD

**Issue by pengzhout** [greenplum-db/gpdb#6610]
### Greenplum version or build
Latest master
### Step to reproduce the behavior
1. break at ExecSetVariableStmt() in one QE,
2. set a GUC like search_path
3. raise an error within ExecSetVariableStmt()
4. set command failed, but some QEs still have the new GUC and QD has old GUC

Something goes wrong if GUC variables cannot be rolled back, take gp_default_storage_options for example, if it is inconsistent between segments, when creating a table, some segments may create appendonly column-store and others may create row-store for a same table.

**Comment by dpandhi-git** [comment]
Fixed Main(7X) https://github.com/greenplum-db/gpdb/pull/8533
6X https://github.com/greenplum-db/gpdb/pull/8901
