### ISSUE TITLE
DROP PARTITION <partition name> syntax does not work/error message is inaccurate

### ISSUE THREAD

**Issue by melanieplageman** [greenplum-db/gpdb#6623]
### Greenplum version or build
 PostgreSQL 9.4.20 (Greenplum Database 6.0.0-alpha.0+dev.15441.g4504c96fad build dev-oss) on x86_64-apple-darwin16.7.0, compiled by Apple LLVM version 9.0.0 (clang-900.0.39.2), 64-bit compiled on Jan  4 2019 18:08:20 (with assert checking)
### OS version and uname -a
macOS Sierra
Darwin mplageman 16.7.0 Darwin Kernel Version 16.7.0: Sun Oct 28 22:30:19 PDT 2018; root:xnu-3789.73.27~1/RELEASE_X86_64 x86_64
### autoconf options used ( config.status --config )
'CC=ccache gcc' '--prefix=/usr/local/gpdb' '--with-libxml' '--with-python' '--with-perl' '--enable-debug' '--enable-cassert' 'CFLAGS=-O0' 'CPPFLAGS=-O0' '--enable-depend'

### Issue
Given I create a partition table like this:
`CREATE TABLE t1(a INT) PARTITION BY RANGE(a) (START(1) END(4) EVERY(2));`
When I attempt to drop a partition by name as specified in the [docs](https://gpdb.docs.pivotal.io/5150/ref_guide/sql_commands/ALTER_TABLE.html)
`ALTER TABLE t1 DROP PARTITION t1_1_prt_1;`
I get this error
`ERROR:  partition "t1_1_prt_2" of relation "t1" does not exist`
However, when I use the alternative syntax,
`ALTER TABLE t1 DROP PARTITION FOR (2);`
It succeeds.
This is also the case for `EXCHANGE PARTITION`
My expectation is that the first syntax would succeed. Or, I would expect a relevant error message if we do not support that syntax.

**Comment by d** [comment]
Have you tried `ALTER TABLE t1 DROP PARTITION t1_1_prt_1;`?

**Comment by l-wang** [comment]
@d it doesn't work and based on the doc it shouldn't. `ALTER TABLE t1 DROP PARTITION FOR (1);` works.

**Comment by d** [comment]
@l-wang you are right! I just checked the code, it seems like partitions generated by `EVERY` don't have names, as evidenced by `SELECT parrelid::regclass, parname, parchildrelid::regclass FROM pg_partition_rule INNER JOIN pg_partition ON paroid = pg_partition.oid;`

**Comment by d** [comment]
@melanieplageman "partition name" is a fairly unfortunate nomenclature: in the scope of a Greenplum partitioned table, each leaf and interior table optionally has a "name". For example:

```sql
CREATE TABLE foo(a INT) PARTITION BY RANGE(a) (PARTITION first START(1) END(2), PARTITION "second" START(2) END(4));
```

You can see the "names" of the partitions like this:

```sql
SELECT parrelid::regclass, parname, parchildrelid::regclass FROM pg_partition_rule INNER JOIN pg_partition ON paroid = pg_partition.oid;
```

And the output looks like:

```
 parrelid | parname |  parchildrelid   
----------+---------+------------------
 foo      | first   | foo_1_prt_first
 foo      | second  | foo_1_prt_second
(2 rows)
```

Now that "first" and "second" are names given to the partitions: you can say something like `ALTER TABLE foo DROP PARTITION first;` and drop the partition.

Partitions don't always get names though, like when you say `EVERY`:

```sql
CREATE TABLE bar(c INT) PARTITION BY RANGE(c) (START(1) END(4) EVERY(2));
SELECT parrelid::regclass, parname, parchildrelid::regclass FROM pg_partition_rule INNER JOIN pg_partition ON paroid = pg_partition.oid;
 parrelid | parname | parchildrelid 
----------+---------+---------------
 bar      |         | bar_1_prt_1
 bar      |         | bar_1_prt_2
(2 rows)

```

**Comment by lij55** [comment]
do we need to change the doc as well for the real behavior?

**Comment by dpandhi-git** [comment]
no fix needed
