### ISSUE TITLE
the returning clause of the insert statement is not supported in this version of Greenplum database

### ISSUE THREAD

**Issue by 3zamn** [greenplum-db/gpdb#6640]
### Greenplum version or build
5.15.1
### OS version and uname -a
centos7
### Expected behavior
![image](https://user-images.githubusercontent.com/19562216/50823065-13bd1580-136e-11e9-9bee-b603094286d6.png)

### Step to reproduce the behavior
in navicat client insert something .tis error：the returning clause of the insert statement is not supported in this version of Greenplum database

**Comment by hlinnaka** [comment]
Yep, INSERT RETURNING Is not supported in GDPB 5. It will be supported in GPDB 6.I don't think there's anything more to do here, so closing.

**Comment by 3zamn** [comment]
> don't



> Yep, INSERT RETURNING Is not supported in GDPB 5. It will be supported in GPDB 6.I don't think there's anything more to do here, so closing.

How long will it take？

**Comment by Eulerizeit** [comment]
>How long will it take？

It is in master now. Feel free to compile and test it we'd love to have feedback.
