### ISSUE TITLE
ERROR could not identify a hash function for type money

### ISSUE THREAD

**Issue by BaiShaoqi** [greenplum-db/gpdb#6641]
The error only happens on orca, standard planner is doing good.

The upstream commit  related is https://github.com/postgres/postgres/commit/36ea99c84d856177ec307307788a279cc600566e

### Greenplum version or build
latest master

### Expected behavior
```
postgres=# select '(2,5)'::cashrange except select '(5,6)'::cashrange;
   cashrange
---------------
 ($2.00,$5.00)
(1 row)
```
### Actual behavior
```
postgres=# select '(2,5)'::cashrange except select '(5,6)'::cashrange;
ERROR:  could not identify a hash function for type money
```
### Step to reproduce the behavior
```
set optimizer to on;
--
-- Check behavior when subtype lacks a hash function
--

create type cashrange as range (subtype = money);

set enable_sort = off;  -- try to make it pick a hash setop implementation

select '(2,5)'::cashrange except select '(5,6)'::cashrange;

```

**Comment by BaiShaoqi** [comment]
There is a same gporca git issue in https://github.com/greenplum-db/gporca/issues/439

And Melanie has do some research on the this issue. and put some analysis in gporca git issue link.

**Comment by lij55** [comment]
verified that it is still in 6X and master now.

**Comment by khannaekta** [comment]
resolves issue on main: https://github.com/greenplum-db/gpdb/pull/15778
