### ISSUE TITLE
Question about index and partition

### ISSUE THREAD

**Issue by wangcheng233** [greenplum-db/gpdb#666]
Hello.
I create an table named tb in my Greenplum database, it has 100 partitions. when I create index on tb, GP creates index on each partition automatically. I insert about 300GB data into the table.
here is the question:
the index on each partition doesn't work. It is Seq Scan on all partitions when I query the table.

how can I use the index?

**Comment by hlinnaka** [comment]
It should work.. Perhaps the planner thinks that it's cheaper to do a seq scan than an index scan, or the index isn't useful for the WHERE clause in the query. Can you post the CREATE statements and the query you used?

**Comment by wangcheng233** [comment]
partition table:
psql -d pgroom -c "create table test_compress_part (c1 int, c2 int, c3 int, c4 int, c5 int, c6 int, c7 int, c8 int, c9 int, c10 int, c11 int, c12 int, c13 int, c14 int, c15 int, c16 int, c17 int, c18 int, c19 int, c20 int, c21 char, c22 char, c23 char, c24 char, c25 char, c26 character varying, c27 character varying, c28 character varying, c29 character varying, c30 character varying, c31 bool, c32 bool, c33 bool, c34 bool, c35 bool, c36 float, c37 float, c38 float, c39 float, c40 float) WITH (appendonly=true, orientation=column, compresstype=zlib, compresslevel=5) DISTRIBUTED BY (c1) PARTITION BY RANGE (c1) (START (0) END (2000000000) EVERY(20000000), DEFAULT PARTITION other);"

query sql:
select * from test_compress_part where c1=681927480;

time:
no index:about 18s.
create index: also about 18s.
so I explain the query sql, and find they are the same, both Seq Scan.
Did I do something wrong so as to the issue?

**Comment by hlinnaka** [comment]
On 22/04/16 09:28, wangcheng233 wrote:
> partition table:
> psql -d pgroom -c "create table test_compress_part (c1 int, c2 int, c3 int, c4 int, c5 int, c6 int, c7 int, c8 int, c9 int, c10 int, c11 int, c12 int, c13 int, c14 int, c15 int, c16 int, c17 int, c18 int, c19 int, c20 int, c21 char, c22 char, c23 char, c24 char, c25 char, c26 character varying, c27 character varying, c28 character varying, c29 character varying, c30 character varying, c31 bool, c32 bool, c33 bool, c34 bool, c35 bool, c36 float, c37 float, c38 float, c39 float, c40 float) WITH (appendonly=true, orientation=column, compresstype=zlib, compresslevel=5) DISTRIBUTED BY (c1) PARTITION BY RANGE (c1) (START (0) END (2000000000) EVERY(20000000), DEFAULT PARTITION other);"
>
> query sql:
> select * from test_compress_part where c1=681927480;
>
> time:
> no index:about 18s.
> create index: also about 18s.
> so I explain the query sql, and find they are the same, both Seq Scan.
> Did I do something wrong so as to the issue?

Hmm, the system is certainly capable of using an index for such a query, 
so it must be that the planner thinks that's it's not beneficial to do 
so. It's a column-oriented table, so it's possible that you'd end up 
reading a large fraction of the partition to get the row you need, even 
if an index is used, so that might affect the planner's decision. You 
could force it with "set enable_seqscan=off", and see if the index scan 
is actually any faster than a seqscan.

- Heikki

**Comment by wangcheng233** [comment]
thank you very much. I'll try.

**Comment by wangcheng233** [comment]
Oh yeah, when I set enable_seqscan=off, the indexes on partitions do work,thank you very much ^_^.
