### ISSUE TITLE
zombie record in gp_distribution_policy after transforming a table to a view by creating ON SELECT rules

### ISSUE THREAD

**Issue by dujialun** [greenplum-db/gpdb#6666]
### Greenplum version or build
GPDB5.x and GPDB6.x

### Step to reproduce the behavior
```
create table t1(a int) distributed by (a);
create table t2(a int) distributed by (a);
create view v1 as select * from t2;
```
Then I run "select * from gp_distribution_policy", I can see two rows, t1 and t2. There is no v1 in gp_distribution_policy, because view will not exist in this catalog table.
Then I create a new rule to transform t1 to a view.
```
create rule "_RETURN" as on select to t1 do instead select * from t2;
```
I can see t1 has been transformed to a view, for its relkind in pg_class is 'v'. But t1 still exists in gp_distribution_policy. Then I drop the view t1 by running "drop view t1;", t1 has been dropped, but the record in gp_distribution_policy still exists, it has become a zombie record.
I think it should be deleted after the table changed to view.

**Comment by dujialun** [comment]
This bug has been fixed in GPDB6.x in this PR https://github.com/greenplum-db/gpdb/pull/6768

**Comment by kainwen** [comment]
@dujialun 
Can we close this issue?
