### ISSUE TITLE
PL/Python functions cannot accept type anytable on GPDB matser

### ISSUE THREAD

**Issue by zhangteng5513** [greenplum-db/gpdb#6680]
### Greenplum version or build
master branch
https://github.com/greenplum-db/gpdb/commit/51136fd7ffc2fb97b1475e5d0082f6df38dc067b

### OS version and uname -a
centos7
Linux sdw 3.10.0-229.el7.x86_64 #1 SMP Fri Mar 6 11:36:42 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

### autoconf options used ( config.status --config )
--enable-cassert --with-perl --with-python --with-libxml --enable-mapreduce --enable-orafce --disable-orca

### Installation information ( pg_config )
BINDIR = /home/gpadmin/usr/local/greenplum-db-devel/bin
DOCDIR = /home/gpadmin/usr/local/greenplum-db-devel/share/doc/postgresql
HTMLDIR = /home/gpadmin/usr/local/greenplum-db-devel/share/doc/postgresql
INCLUDEDIR = /home/gpadmin/usr/local/greenplum-db-devel/include
PKGINCLUDEDIR = /home/gpadmin/usr/local/greenplum-db-devel/include/postgresql
INCLUDEDIR-SERVER = /home/gpadmin/usr/local/greenplum-db-devel/include/postgresql/server
LIBDIR = /home/gpadmin/usr/local/greenplum-db-devel/lib
PKGLIBDIR = /home/gpadmin/usr/local/greenplum-db-devel/lib/postgresql
LOCALEDIR = /home/gpadmin/usr/local/greenplum-db-devel/share/locale
MANDIR = /home/gpadmin/usr/local/greenplum-db-devel/man
SHAREDIR = /home/gpadmin/usr/local/greenplum-db-devel/share/postgresql
SYSCONFDIR = /home/gpadmin/usr/local/greenplum-db-devel/etc/postgresql
PGXS = /home/gpadmin/usr/local/greenplum-db-devel/lib/postgresql/pgxs/src/makefiles/pgxs.mk
CONFIGURE = '--enable-tap-tests' '--enable-gpperfmon' '--with-gssapi' '--enable-mapreduce' '--enable-orafce' '--enable-orca' '--with-libxml' '--with-apu-config=/tmp/build/f8c7ee08/gpdb_src/gpAux/ext/rhel7_x86_64/bin/apu-1-config' '--with-pgport=5432' '--with-libedit-preferred' '--enable-cassert' '--with-perl' '--with-python' '--with-includes=/tmp/build/f8c7ee08/gpdb_src/gpAux/ext/rhel7_x86_64/include /tmp/build/f8c7ee08/gpdb_src/gpAux/ext/rhel7_x86_64/include/libxml2 /tmp/build/f8c7ee08/gpdb_src/gpAux/addon/src/include' '--with-libraries=/tmp/build/f8c7ee08/gpdb_src/gpAux/ext/rhel7_x86_64/lib' '--with-openssl' '--with-pam' '--with-ldap' 'CURL_CONFIG=/tmp/build/f8c7ee08/gpdb_src/gpAux/ext/rhel7_x86_64/bin/curl-config' '--with-apr-config=/tmp/build/f8c7ee08/gpdb_src/gpAux/ext/rhel7_x86_64/bin/apr-1-config' 'ADDON_DIR=addon' '--prefix=/usr/local/greenplum-db-devel' '--mandir=/usr/local/greenplum-db-devel/man' 'CC=gcc -m64' 'CFLAGS=-m64 -O3 -fargument-noalias-global -fno-omit-frame-pointer -g'
CC = gcc -m64
CPPFLAGS = -D_GNU_SOURCE -I/tmp/build/f8c7ee08/gpdb_src/gpAux/ext/rhel7_x86_64/include -I/tmp/build/f8c7ee08/gpdb_src/gpAux/ext/rhel7_x86_64/include/libxml2 -I/home/gpadmin/usr/local/greenplum-db-devel/include
CFLAGS = -Wall -Wmissing-prototypes -Wpointer-arith -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fno-aggressive-loop-optimizations -Wno-unused-but-set-variable -Wno-address -m64 -O3 -fargument-noalias-global -fno-omit-frame-pointer -g -std=gnu99 -Werror=uninitialized -Werror=implicit-function-declaration -I/home/gpadmin/usr/local/greenplum-db-devel/include
CFLAGS_SL = -fPIC
LDFLAGS = -L/tmp/build/f8c7ee08/gpdb_src/gpAux/ext/rhel7_x86_64/lib -Wl,--as-needed -Wl,-rpath,'/usr/local/greenplum-db-devel/lib',--enable-new-dtags -L/home/gpadmin/usr/local/greenplum-db-devel/lib
LDFLAGS_EX =
LDFLAGS_SL =
LIBS = -lpgcommon -lpgport -lgpopt -lnaucrates -lgpdbcost -lgpos -lxerces-c -lxml2 -lpam -lrt -lyaml -lgssapi_krb5 -lrt -lcrypt -ldl -lm -lrt -L/home/gpadmin/usr/local/greenplum-db-devel/lib
VERSION = PostgreSQL 9.4.20

### Step to reproduce the behavior
```
CREATE LANGUAGE plpythonu;

CREATE OR REPLACE FUNCTION f1(a anytable) RETURNS SETOF text AS
$$
	return []
$$ LANGUAGE plpythonu;
```
On GPDB 5.14.0, query above will be executed normally. 

But on gpdb master, there will be an error message:
`ERROR:  PL/Python functions cannot accept type anytable` 

After brief investigation, the error message is produced on src/pl/plpython/plpy_procedure.c line 295

```
/* check argument type is OK, set up I/O function info */
switch (argTypeStruct->typtype)
{
	case TYPTYPE_PSEUDO:
		/* Disallow pseudotype argument */
		ereport(ERROR,
				(errcode(ERRCODE_FEATURE_NOT_SUPPORTED),
		  errmsg("PL/Python functions cannot accept type %s",
				 format_type_be(types[i]))));
		break;
	case TYPTYPE_COMPOSITE:
		/* we'll set IO funcs at first call */
		proc->args[pos].is_rowtype = 2;
		break;
	default:
		PLy_input_datum_func(&(proc->args[pos]),
							 types[i],
							 argTypeTup);
		break;
}
```
Why the behavior between 5.14 and master is different for the same query?

**Comment by HaozhouWang** [comment]
Thanks for reporting, we are looking at it now.

**Comment by HaozhouWang** [comment]
Hi,

Actually, this function is not a correct usage for PL/Python as the input parameter cannot be a pseudotype (i.e. anytable).
The root cause of why GPDB 5 can accept it is because of GPDB 5 missing validator function in catalog, but GPDB 6 has fixed this.

Please consider a workaround or a replacement of the PL/Python function to avoid using `anytable` as the input.
