### ISSUE TITLE
configure: error: "zstd library not found" during DB build 

### ISSUE THREAD

**Issue by Eva-Sanya** [greenplum-db/gpdb#6700]
### Greenplum version or build
5.15.1
### OS version and uname -a
RHEL 7.6
Linux ip-172-31-69-197.ec2.internal 3.10.0-957.el7.x86_64 #1 SMP Thu Oct 4 20:48:51 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
### Expected behavior
Configure to finish successfully.

### Actual behavior
Configure throwing error -
checking for ZSTD_compressCCtx in -lzstd... no
configure: error: zstd library not found.

### Step to reproduce the behavior
Build the database
# Configure build environment to install at /usr/local/gpdb
./configure --with-perl --with-python --with-libxml --with-gssapi --prefix=/usr/local/gpdb

I'm doing above step after installing prerequisites and optimizer/GPORCA but still getting the error while zstd is installed under /usr/bin/ and easily accessible from prompt.

**Comment by hlinnaka** [comment]
Greenplum needs libzstd, the library, and the development headers for it. It doesn't care about the `zstd` binary. I think the package containing the libzstd headers is called `libzstd-devel` on RHEL.

Commit 194e84e5d7 changed the configure default from `--without-zstd` to `--with-zstd`, so unless you explicitly specify `--without-zstd`, it will try to configure with libzstd. I think commit 194e84e5d7 forgot to update the list of required packages in the READMEs.

**Comment by hlinnaka** [comment]
> checking for ZSTD_compressCCtx in -lzstd... no
> configure: error: zstd library not found.

On the recent thread on gpdb-dev (https://groups.google.com/a/greenplum.org/d/msg/gpdb-dev/VxNauzvpVqk/V3S9X9PaFgAJ), we talked about the change in the configure default. That was a heated debate, but I think everyone agreed that the error message should be similar to the one from missing zlib headers, for example:

```
zlib library not found
If you have zlib already installed, see config.log for details on the
failure.  It is possible the compiler isn't looking in the proper directory.
Use --without-zlib to disable zlib support.
```
@tvesely, can you update the READMEs with the packages required, and improve the configure error you get if libzstd headers are missing, please?

**Comment by ashwinstar** [comment]
I am assuming Greenplum version or build 5.15.1 reported is wrong, as GPDB5 doesn't have zstd. Must be compiling gpdb master.

**Comment by Eva-Sanya** [comment]
@ashwinstar you are correct I cloned the master

**Comment by Eva-Sanya** [comment]
@hlinnaka Thanks, I was able to get past the error after installing the lib as you specified. Here's the next error. I guess i'm missing the list of libraries I should have installed. Do we have this listed somewhere for RHEL?

**_configure: error: libevent is required for gpfdist_**

**Comment by hlinnaka** [comment]
On 14 January 2019 17:47:18 EET, M C <notifications@github.com> wrote:
>@hlinnaka Thanks, I was able to get past the error after installing the
>lib as you specified. Here's the next error. I guess i'm missing the
>list of libraries I should have installed. Do we have this listed
>somewhere for RHEL?

Take a look at README.CentOS.bash. It's for CentOS rather than RHEL, but there shouldn't be any difference.

- Heikki

**Comment by Eva-Sanya** [comment]
@hlinnaka Yup, I followed that one for prerequisites and it doesnt have libzstd-devel. Let me retry installing all of them again. May be the list needs to be updated.

**Comment by benchristel** [comment]
Looks like we forgot to update the developer documentation when we changed the default. We will make sure that gets fixed.

**Comment by ashwinstar** [comment]
libzstd-devel was added to readme by commit 78038632db0cf0f832a410cef4c2aa52032a211b.
