### ISSUE TITLE
The version shown is incorrect

### ISSUE THREAD

**Issue by quentinliu** [greenplum-db/gpdb#6709]
### Greenplum version or build
5.15.1
### OS version and uname -a
Linux BJCSI_DELL_0_21 3.10.0-862.14.4.el7.x86_64 #1 SMP Wed Sep 26 15:12:11 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
### autoconf options used ( config.status --config )
'--disable-orca' '--enable-gphdfs' '--with-perl' '--with-python' '--with-libxml' '--prefix=/usr/local/gpdb'
### Installation information ( pg_config )
BINDIR = /usr/local/gpdb/bin
DOCDIR = /usr/local/gpdb/doc/postgresql
HTMLDIR = /usr/local/gpdb/doc/postgresql
INCLUDEDIR = /usr/local/gpdb/include
PKGINCLUDEDIR = /usr/local/gpdb/include/postgresql
INCLUDEDIR-SERVER = /usr/local/gpdb/include/postgresql/server
LIBDIR = /usr/local/gpdb/lib
PKGLIBDIR = /usr/local/gpdb/lib/postgresql
LOCALEDIR = /usr/local/gpdb/share/locale
MANDIR = /usr/local/gpdb/share/man
SHAREDIR = /usr/local/gpdb/share/postgresql
SYSCONFDIR = /usr/local/gpdb/etc/postgresql
PGXS = /usr/local/gpdb/lib/postgresql/pgxs/src/makefiles/pgxs.mk
CC = gcc
CPPFLAGS = -D_GNU_SOURCE -I/usr/local/gpdb/include
CFLAGS = -O3 -std=gnu99 -Wall -Wmissing-prototypes -Wpointer-arith -Wendif-labels -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fno-aggressive-loop-optimizations -Wno-unused-but-set-variable -Wno-address -I/usr/local/gpdb/include
CFLAGS_SL = -fpic
LDFLAGS = -Wl,--as-needed -Wl,-rpath,'/usr/local/gpdb/lib',--enable-new-dtags -L/usr/local/gpdb/lib
LDFLAGS_SL =
LIBS = -lpgport -lxml2 -lrt -lcrypt -ldl -lm -L/usr/local/gpdb/lib
VERSION = PostgreSQL 8.3.23

### Expected behavior
select version()
"PostgreSQL 8.3.23 (Greenplum Database 5.15.1 build dev) on x86_64-pc-linux-gnu, compiled by GCC gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36), 64-bit compiled on Dec 27 2018 14:44:41"
### Actual behavior
select version()
"PostgreSQL 8.3.23 (Greenplum Database 5.0.0 build dev) on x86_64-pc-linux-gnu, compiled by GCC gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36), 64-bit compiled on Dec 27 2018 14:44:41"

**Comment by danielgustafsson** [comment]
This is a known, and at length discussed, issue with the releases. The version string referred to in this issue is defined by `GP_VERSION_NUM` which in turn depends on `PACKAGE_VERSION`, and `PACKAGE_VERSION` isn't bumped during releases when the git tag is added. This is a known issue for which no resolution has been found yet.
