### ISSUE TITLE
CREATE EXTENSION WITH SCHEMA doesn't work

### ISSUE THREAD

**Issue by hlinnaka** [greenplum-db/gpdb#6716]
From PR #6713:

On 15/01/2019 18:07, Jacob Champion wrote:
> Looks like Concourse caught something:
> 
> ```
> subprocess.CalledProcessError: Command 'psql 'funny"db'"'"'with\\quotes' -t -c " CREATE EXTENSION IF NOT EXISTS gp_replica_check "' returned non-zero exit status 1
> ```
Yeah. I went down this rabbit hole to some depth.

The immediate issue is that there are shell-quoting issues in 
gp_replica_check.py. After fixing that, this was the next obstacle:

> funny"db'with\\quotes=# create extension "gp_replica_check" ;
> ERROR:  no schema has been selected to create in

There's a per-database SET option in that database, setting search_path 
to a non-existent schema.

Ok, that seems easy enough to fix, there's a CREATE EXTENSION WITH 
SCHEMA option for that. But alas:

> funny"db'with\\quotes=# create extension "gp_replica_check" with schema public;
> ERROR:  current transaction is aborted, commands ignored until end of transaction block  (seg0 127.0.0.1:40000 pid=12190)

Turns out, the WITH SCHEMA option doesn't work correctly in GPDB :-(. 
That's a separate issue from quoting the database name.

**Comment by dujialun** [comment]
I have investigated this issue, it has nothing to do with the database name. If I create a database without a special character, the result is the same. The real reason is that though you provide the schema name in `CREATE EXTENSION`, not only it will run this query but also will run related extension script in $GPHOME/share/postgresql/extension in the same transaction. Most of them are function creation statements. These statements didn't provide the right schema name, so it will fail and get the error message `ERROR:  no schema has been selected to create in`.
So I think it does not make sense to SET search_path to a non-exist schema and create extension with a specified schema.

**Comment by hlinnaka** [comment]
Yes, I know it has nothing to do with the database name. This issue is to track that bug that CREATE EXTENSION WITH SCHEMA does not work. It should not fail with that error.

**Comment by gaos1** [comment]
can you still see the issue?  I cannot see it with the latest master:
```
db1=# create database "funny""db'with\quotes";
CREATE DATABASE
db1=# \c "funny""db'with\quotes"
You are now connected to database "funny"db'with\quotes" as user "gpadmin".
funny"db'with\quotes=# create extension gp_debug_numsegments with schema public;
CREATE EXTENSION
```

**Comment by zhangh43** [comment]
RCA of this issue is as follows:
`With schema` only set the search path at Master side and didn't dispatch it to segments.
So segments cannot know the specified schema.
```
	/*
	 * Set up the search path to contain the target schema, then the schemas
	 * of any prerequisite extensions, and nothing else.  In particular this
	 * makes the target schema be the default creation target namespace.
	 *
	 * Note: it might look tempting to use PushOverrideSearchPath for this,
	 * but we cannot do that.  We have to actually set the search_path GUC in
	 * case the extension script examines or changes it.  In any case, the
	 * GUC_ACTION_SAVE method is just as convenient.
	 */
	initStringInfo(&pathbuf);
	appendStringInfoString(&pathbuf, quote_identifier(schemaName));
	foreach(lc, requiredSchemas)
	{
		Oid			reqschema = lfirst_oid(lc);
		char	   *reqname = get_namespace_name(reqschema);

		if (reqname)
			appendStringInfo(&pathbuf, ", %s", quote_identifier(reqname));
	}

	(void) set_config_option("search_path", pathbuf.data,
							 PGC_USERSET, PGC_S_SESSION,
							 GUC_ACTION_SAVE, true, 0);
```

**Comment by berlin-ab** [comment]
Checked this on GPDB master (7x) and it still is a problem:

```
± |master → berlin-ab ✓| → psql
Timing is on.
psql (9.4.20)
Type "help" for help.

adamberlin=# create schema foobar;
CREATE SCHEMA
Time: 23.165 ms
adamberlin=# create extension gp_inject_fault with schema foobar;
ERROR:  current transaction is aborted, commands ignored until end of transaction block  (seg0 127.0.0.1:7002 pid=87513)
Time: 52.508 ms
adamberlin=# select version();
                                                                                                                 version
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 PostgreSQL 9.4.20 (Greenplum Database 7.0.0-alpha.0+dev.494.g4ae077bd9d2 build dev) on x86_64-apple-darwin17.7.0, compiled by Apple LLVM version 8.1.0 (clang-802.0.42), 64-bit compiled on Jul  8 2019 21:03:56 (with assert checking)
(1 row)

```

**Comment by berlin-ab** [comment]
@hlinnaka It looks like the dependent/blocking issues have been resolved.

**Comment by ashwinstar** [comment]
I am confused with new behavior. `create extension gp_inject_fault;` passes but `create extension gp_inject_fault with schema foobar;` fails with very confusing error
```
postgres=# create schema foobar;
CREATE SCHEMA

postgres=# create extension gp_inject_fault with schema foobar;
psql: ERROR:  query plan with multiple segworker groups is not supported
HINT:  likely caused by a function that reads or modifies data in a distributed table
```

**Comment by ashwinstar** [comment]
@HaozhouWang please can you or someone from team look into to get `CREATE EXTENSION... WITH SCHEMA` working

**Comment by HaozhouWang** [comment]
No, GPDB does not support `CREATE EXTENSION... WITH SCHEMA yet.

**Comment by kainwen** [comment]
> I am confused with new behavior. `create extension gp_inject_fault;` passes but `create extension gp_inject_fault with schema foobar;` fails with very confusing error
> 
> ```
> postgres=# create schema foobar;
> CREATE SCHEMA
> 
> postgres=# create extension gp_inject_fault with schema foobar;
> psql: ERROR:  query plan with multiple segworker groups is not supported
> HINT:  likely caused by a function that reads or modifies data in a distributed table
> ```

@ashwinstar 

I see a new PR from outside-vmware https://github.com/greenplum-db/gpdb/pull/11683
And I believe it can fixes the confusing error message.

**Comment by ashwinstar** [comment]
On latest gpdb6 when I try `create extension gp_inject_fault with schema foobar;` I get new error now (PR #11683 was merged so I thought this issue will be fixed).
```
 postgres=# create extension gp_inject_fault with schema foobar;
ERROR:  no pre-assigned OID for pg_proc tuple "gp_inject_fault" (namespace:2200 keyOid1:0 keyOid2:0) (oid_dispatch.c:648)  (seg0 127.0.1.1:6002 pid=1541185) (oid_dispatch.c:648)
```

**Comment by lij55** [comment]
> On latest gpdb6 when I try `create extension gp_inject_fault with schema foobar;` I get new error now (PR #11683 was merged so I thought this issue will be fixed).
> 
> ```
>  postgres=# create extension gp_inject_fault with schema foobar;
> ERROR:  no pre-assigned OID for pg_proc tuple "gp_inject_fault" (namespace:2200 keyOid1:0 keyOid2:0) (oid_dispatch.c:648)  (seg0 127.0.1.1:6002 pid=1541185) (oid_dispatch.c:648)
> ```

then it works if adding schema 'foobar' to 'search_path'
