### ISSUE TITLE
gpkafka start gpfdist only on localhost:5001 

### ISSUE THREAD

**Issue by sydt2014** [greenplum-db/gpdb#6732]

**Comment by sydt2014** [comment]
when gpkafka load firstloadcfg.yaml it occurs :
-[CRITICAL]:-pq: connection with gpfdist failed for gpfdist://localhost:5001/gpkafkaload/%!p(MISSING)ublic%22gpkafkaloadext_b3019832bc073d9b24d343b07bcdf9df%! (MISSING)effective url: http://127.0.0.1:5001/gpkafkaload/%!p(MISSING)ublic%22gpkafkaloadext_b3019832bc073d9b24d343b07bcdf9df%! (MISSING)error code = 111 (Connection refused)  (seg0 slice1 172.23.224.6:6001 pid=4316): Failed to execute SQL: Failed to load batch 0
it didnot work with configuration of firstloadcfg.yaml of LOCAL_HOSTNAME

**Comment by yydzero** [comment]
gpkafka is closed source product, please talk with Pivotal support.  closed this issue.

**Comment by lij55** [comment]
It get fixed in 5.16 which will release quite soon. Thanks for reporting
