### ISSUE TITLE
Can indexes be compressed？

### ISSUE THREAD

**Issue by qinchaofeng** [greenplum-db/gpdb#6777]
### Greenplum version or build
GPDB 5.11.3
### OS version and uname -a
CentOS 7.x
### Step to reproduce the behavior
Can indexes be compressed,when you create tables

**Comment by hlinnaka** [comment]
No. Bitmap indexes have a built-in compression scheme to compress the bitmaps, though.

**Comment by Eulerizeit** [comment]
Most indexes, to my knowledge, are stored in heap tables, There is no compression for heap tables at all so this would be difficult.
