### ISSUE TITLE
psql \di+ trips assert

### ISSUE THREAD

**Issue by melanieplageman** [greenplum-db/gpdb#6792]
### Greenplum version or build
GPDB 6 master
### OS version and uname -a
Darwin mplageman 16.7.0 Darwin Kernel Version 16.7.0: Sun Oct 28 22:30:19 PDT 2018; root:xnu-3789.73.27~1/RELEASE_X86_64 x86_64
### autoconf options used ( config.status --config )
`'CC=ccache gcc' '--prefix=/usr/local/gpdb' '--with-libxml' '--disable-orca' '--without-zstd' '--with-python' '--with-perl' '--enable-debug' '--enable-cassert' 'CFLAGS=-O0' 'CPPFLAGS=-O0' '--enable-depend'`
### Expected behavior
When I use the extended describe index command in psql, I expect to get results that look roughly like the following:
```
postgres=# \di+
                             List of relations
 Schema |   Name    | Type  |   Owner   | Table |    Size    | Description
--------+-----------+-------+-----------+-------+------------+-------------
 public | foo_a_idx | index | mplageman | foo   | 8192 bytes |
(1 row)
```
### Actual behavior
Instead, on a debug build, I trip the following assert
`Assertion failed: (opt->translate_columns == ((void*)0) || opt->n_translate_columns >= cont.ncolumns), function printQuery, file print.c, line 2619.`
### Step to reproduce the behavior
`\di+`

I dug around a bit on this issue already. I noticed that `cont.ncolumns` is 8 and `opt->n_translate_columns` is 7. I see that opt->translate_columns is initialized in `listTables` to be a list of 7 bools. And that `cont.ncolumns` is set from what was originally passed in as `result` and its member `numAttributes` is set in `listTables`. 
In upstream 9.4, both numbers are 7 for this query. Somehow `cont.ncolumns` is 8 in GPDB. I poked around to see where this is happening and noticed that it is set to 8 somewhere in the process of executing the query to get the info for the display table
`res = PSQLexec(buf.data, false);`
But, I didn't find the place where we actually increment the `result->numAttributes` in the connection yet. 
Putting this here so someone can pick it up and just fix it--otherwise I will poke around more tomorrow.

**Comment by hlinnaka** [comment]
Opened PR #6816 to fix this. It's a one-line fix, but I also changed \di output to not display the pointless "Storage" column, and expanded the tests to test different \d commands.

**Comment by hlinnaka** [comment]
Fixed, thanks for the report!
