### ISSUE TITLE
how can I build modules in /contrib? Is this supported?

### ISSUE THREAD

**Issue by mkiyama** [greenplum-db/gpdb#6855]
I am not a developer...
I am trying to build postgres_fdw

I tried using the instructions in 
https://www.postgresql.org/docs/9.4/contrib.html

and I get

Makefile:25: ../../src/Makefile.global: No such file or directory
Makefile:26: /contrib/contrib-global.mk: No such file or directory
make: *** No rule to make target '/contrib/contrib-global.mk'.  Stop.

**Comment by HaozhouWang** [comment]
In GPDB, we need to source greenplum_path.sh first. And using the following command to build contrib modules:
```
make USE_PGXS=1
maks USE_PGXS=1 install
```

**Comment by gaos1** [comment]
Please ping Haozhou if you need more help.
