### ISSUE TITLE
Invalid use of Assert()

### ISSUE THREAD

**Issue by pivotal-ning-yu** [greenplum-db/gpdb#6869]
`Assert()` is conditionally defined with `assert()` for frontend, or `ExceptionalCondition()` when `--enable-cassert`, otherwise it expands to nothing:

https://github.com/greenplum-db/gpdb/blob/1e43b58439a917769873322de794e76b3f969f82/src/include/c.h#L737-L739

However some callers to it might behave differently depends on how it's defined:

https://github.com/greenplum-db/gpdb/blob/1e43b58439a917769873322de794e76b3f969f82/src/backend/cdb/motion/ic_common.c#L534-L541

In this example when `Assert()` is expanded to nothing the logic actually becomes:

```C
    if (Gp_interconnect_type == INTERCONNECT_TYPE_UDPIFC)
        SetupUDPIFCInterconnect(estate);
    else if (Gp_interconnect_type == INTERCONNECT_TYPE_TCP)
        SetupTCPInterconnect(estate);
    else
        MemoryContextSwitchTo(oldContext);
```

This is obviously wrong.  I guess there are also similar errors in the code, it might not be easy to find out all of them.  Instead of fixing the callers I wonder whether could we define `Assert()` to a dummy instruction instead of empty.  In fact in postgres there is already such changes to its definition:

```diff
commit 9959abb0122ca2b0e4817e20954e3083c90becdc
Author: Andres Freund <andres@anarazel.de>
Date:   Mon Dec 8 20:28:09 2014 +0100

    Define Assert() et al to ((void)0) to avoid pedantic warnings.

    gcc's -Wempty-body warns about the current usage when compiling
    postgres without --enable-cassert.

diff --git a/src/include/c.h b/src/include/c.h
index ce38d78736..93d6924c5c 100644
--- a/src/include/c.h
+++ b/src/include/c.h
@@ -578,12 +578,12 @@ typedef NameData *Name;
  */
 #ifndef USE_ASSERT_CHECKING

-#define Assert(condition)
+#define Assert(condition)   ((void)true)
 #define AssertMacro(condition)  ((void)true)
-#define AssertArg(condition)
-#define AssertState(condition)
+#define AssertArg(condition)    ((void)true)
+#define AssertState(condition)  ((void)true)
 #define AssertPointerAlignment(ptr, bndr)   ((void)true)
-#define Trap(condition, errorType)
+#define Trap(condition, errorType)  ((void)true)
 #define TrapMacro(condition, errorType) (true)

 #elif defined(FRONTEND)
```

**Comment by paul-guo-** [comment]
+1 to backport it. Good catch.

I've been liking the coding style that adds { and } for any branch code and
that could prevent this case, but that seems to not align with the PG
coding convention.

**Comment by pivotal-ning-yu** [comment]
Thanks for sharing your thoughts, I will take the job.

**Comment by jchampio** [comment]
> In this example when Assert() is expanded to nothing the logic actually becomes:
>```c
>if (Gp_interconnect_type == INTERCONNECT_TYPE_UDPIFC)
>    SetupUDPIFCInterconnect(estate);
>else if (Gp_interconnect_type == INTERCONNECT_TYPE_TCP)
>    SetupTCPInterconnect(estate);
>else
>    MemoryContextSwitchTo(oldContext);
>```
The `#define` shouldn't be able to elide the semicolon, so the end result should be something like
```c
 if (Gp_interconnect_type == INTERCONNECT_TYPE_UDPIFC) 
 	SetupUDPIFCInterconnect(estate); 
 else if (Gp_interconnect_type == INTERCONNECT_TYPE_TCP) 
 	SetupTCPInterconnect(estate); 
 else 
 	; 
  
 MemoryContextSwitchTo(oldContext); 
```
which is a little less scary. But +1 to the backport, regardless.
