### ISSUE TITLE
src/backend/storage/smgr/md.c line line 1743 and 1767

### ISSUE THREAD

**Issue by fengttt** [greenplum-db/gpdb#687]
It has a line,
			if (!MirroredBufferPool_Truncate(&v->mdmir_open, lastsegblocks * BLCKSZ) < 0)

MirroredBufferPool_Truncate returns bool, so the test is simply wrong.   I assume the line should be
                       if (!MirroredBufferPool_Truncate(...))

**Comment by danielgustafsson** [comment]
I believe you are entirely correct there. Thanks for the report, I've posted a PR with this patch so will close this issue and move the discussion there.
