### ISSUE TITLE
gpexpand copies data directory while server is running, which is unsafe

### ISSUE THREAD

**Issue by hlinnaka** [greenplum-db/gpdb#6883]
To initialize the new segments, gpexpand creates a copy of the master data directory. It's packaged in a tarball, and extracted on all the new segments. While gpexpand takes the copy, is the database running? ISTM it is. That's not safe.

**Comment by kainwen** [comment]
Hi @hlinnaka 
It firstly lock the catalog before copying datadir. Will it be safe with the lock?

**Comment by hlinnaka** [comment]
On 04/02/2019 14:33, Zhenghua Lyu wrote:
> Hi @hlinnaka <https://github.com/hlinnaka>
> It firstly lock the catalog before copying datadir. Will it be safe with 
> the lock?

No. The lock prevents concurrent DDL, but it doesn't stop other on-disk 
changes from happening.

- Heikki

**Comment by dujialun** [comment]
It has been confirmed that we can get a copy of master directory by gp_basebackup, max_wal_sender > 1 is allowed in this commit 06e7bf3269c5791edacbe90026e936cd22d64c2e.

**Comment by Eulerizeit** [comment]
@dujialun I'm not sure what we have our max_wal_sender set for right now but I'm pretty sure in Postgres the default is 10. We could certainly raise whatever it is we have if that would be useful.
