### ISSUE TITLE
complex_lt and < for complex type

### ISSUE THREAD

**Issue by fengttt** [greenplum-db/gpdb#690]
In the recent complex data type, there are methods like complex_lt and operator <.    

Using some kind of ordering for internal query processing like sort agg is one thing, exposing these in catalog, therefore public, seems to be a very bad idea given the math properties of complex number.  Should we remove these functions from catalog?

**Comment by atris** [comment]
Ah, my bad.

We discussed renaming these functions or removing them from the catalog but
I seem to have missed that during the final commit. Please feel free to do
the same, or I will be happy to remove them.

**Comment by danielgustafsson** [comment]
To ensure we're not dropping this on the floor, who is picking up this task?

**Comment by atris** [comment]
I wont be able to get to it this week. I can take it up after that

**Comment by danielgustafsson** [comment]
Cool, thanks!

**Comment by danielgustafsson** [comment]
This was fixed in #1095, closing.
