### ISSUE TITLE
Copy to file on stdout does not show count of records

### ISSUE THREAD

**Issue by sunnn** [greenplum-db/gpdb#6910]
Greenplum version 5.8
Expected behavior
After run psql -h hostname -d db -U user -c ' copy from (select * from t;') to stdout> file path
Then record count should be shown,this way it would be great to catch up on things

Actual behavior
No record count displayed

**Comment by hlinnaka** [comment]
If you use  psql's `\copy` command, you'll get the row count:  
```
$ psql postgres -c '\copy (select generate_series(1,10)) to /tmp/file' 
COPY 10
```

**Comment by sunnn** [comment]
@hlinnaka my greenplum version 5.8 from pivotal doesnt show any output onto screen

**Comment by hlinnaka** [comment]
Oh, I see, this was changed in PostgreSQL 9.4, in commit https://github.com/greenplum-db/gpdb/commit/f70a78bc1f5556546d809a8164b9ba6a907f266f.

**Comment by sunnn** [comment]
@hlinnaka yeah if anyone can add that to present 5.16 version of greenplum that would be great

**Comment by hlinnaka** [comment]
On 06/02/2019 12:34, Naresh wrote:
> @hlinnaka <https://github.com/hlinnaka> yeah if anyone can add that to 
> present 5.16 version of greenplum that would be great

I don't think we're going to backport that, it's not a bug fix. But you 
could use a newer psql version against an old server.

- Heikki

**Comment by sunnn** [comment]
@hlinnaka  so will that come up in any new version of greenplum or it will never be used??? any idea on that

**Comment by hlinnaka** [comment]
On 06/02/2019 15:05, Naresh wrote:
> @hlinnaka <https://github.com/hlinnaka> so will that come up in any new 
> version of greenplum or it will never be used??? any idea on that

The next major Greenplum release, GPDB 6, will be based on PostgreSQL 
9.4. It will include this.

- Heikki
