### ISSUE TITLE
Assertion when attempting to add a list partition to a table partitioned by range

### ISSUE THREAD

**Issue by kalensk** [greenplum-db/gpdb#6967]
When incorrectly adding a list partition to a table partitioned by range the following assertion is thrown. 

### Greenplum version or build
Master

### autoconf options used ( config.status --config )
--prefix=/usr/local/gpdb6' '--enable-depend' '--enable-debug' '--enable-cassert' '--with-perl' '--with-python' '--with-libxml' '--with-gssapi' 'CFLAGS=-O0' 'CXXFLAGS=-O0

### Expected behavior
The server correctly detects and rejects a list partition when adding to a table partitioned by range by raising an error.

### Actual behavior
When the server attempts to add a list partition it hits an assertion because it does not have the expected partition specification.

### Step to reproduce the behavior
```
postgres=# create table foo (a int, unique(a)) partition by range (a) (start(1) end(5));
NOTICE:  CREATE TABLE will create partition "foo_1_prt_1" for table "foo"
CREATE TABLE
postgres=# alter table foo add partition test values(1);
FATAL:  Unexpected internal error (cdbpartition.c:5427)
DETAIL:  FailedAssertion("!(((((const Node*)(pelem->boundSpec))->type) == T_PartitionBoundSpec))", File: "cdbpartition.c", Line: 5427)
HINT:  Process 59199 will wait for gp_debug_linger=120 seconds before termination.
Note that its locks and other resources will not be released until then.
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
The connection to the server was lost. Attempting reset: Succeeded.
```

**Comment by danielgustafsson** [comment]
Fixed in #6995
