### ISSUE TITLE
Confusion arises, if gpexpand is run with incorrect MASTER_DATA_DIRECTORY

### ISSUE THREAD

**Issue by hlinnaka** [greenplum-db/gpdb#7000]
I had two clusters initialized on my laptop, and I ran gpexpand such that MASTER_DATA_DIRECTORY was pointing to one cluster, but the PGPORT/PGHOST settings were pointing to the other cluster. I don't have the details of what exactly happens, I'm afraid, but I just remembered that that happened during testing the other day, and I forgot to log the issue then.

**Comment by berlin-ab** [comment]
What do you think the expected behavior should be?

**Comment by hlinnaka** [comment]
> What do you think the expected behavior should be?

I think there would be three valid options:

1. Use the cluster specified by MASTER_DATA_DIRECTORY, and ignore PGHOST/PGPORT and other settings.

2. Use the cluster specified by PGHOST/PGPORT, and ignore MASTER_DATA_DIRECTORY.

3. Require both, but throw an error if they don't point to the same cluster.

**Comment by ivannovick** [comment]
not all customers set PGHOST and PGPORT, but 100% of customers will set MASTER_DATA_DIRECTORY..... 

FYI

**Comment by hlinnaka** [comment]
Why did you close this? Has this been fixed?

**Comment by gaos1** [comment]
right we need a fix after a close look. Ning and I just discussed and we prefer option 3 for safety.  when PGHOST/PGPORT is set, we assume they are default values.

**Comment by dujialun** [comment]
Not only gpexpand, but all the utility tools are faced with the same issue, so I think we should fix this confusion for all.

**Comment by gaos1** [comment]
fixed by #7159 .  the final solution is option 1. Use the cluster specified by MASTER_DATA_DIRECTORY, and ignore PGHOST/PGPORT settings.
