### ISSUE TITLE
gpcheckcat generated repair-scripts don't check for failure

### ISSUE THREAD

**Issue by jchampio** [greenplum-db/gpdb#7026]
### Greenplum version or build
master, 5X

### Expected behavior
If one of the repair scripts generated by gpcheckcat fails, there should be an obvious failure mode so that 1) the DBA can address the issue immediately and 2) our tests for gpcheckcat will correctly report a failure instead of false success.

### Actual behavior
Failures are ignored. The results are piped to a log, but we don't point the DBA to that log or indicate that something has gone wrong.

### Reproduction

As of commit 28374d9a0614a61c, the `part_integrity` repair scripts don't work, but you'd never know it. (This reproduction won't work in 5X, because the repair scripts work, but we still ignore failures there too.)
```sql
CREATE TABLE test (a int, b int) DISTRIBUTED BY (a, b) PARTITION BY RANGE (a) (START(0) END(5) EVERY(1));

-- corrupt a subpartition's distribution policy
SET allow_system_table_mods = true;
UPDATE gp_distribution_policy SET distkey = ARRAY[1]::int2vector WHERE localoid='test_1_prt_1'::regclass;
```
Run gpcheckcat:
```
$ gpcheckcat -R part_integrity postgres
Truncated batch size to number of primaries: 4

Connected as user 'pchampion' to database 'postgres', port '15432', gpdb version '6.0'
-------------------------------------------------------------------
Batch size: 4
Performing test 'part_integrity'

catalog issue(s) found , repair script(s) generated in dir gpcheckcat.repair.20190220153545

Total runtime for test 'part_integrity': 0:00:00.10

SUMMARY REPORT
===================================================================
Completed 1 test(s) on database 'postgres' at 2019-02-20 15:35:46 with elapsed time 0:00:00
Failed test(s) that are not reported here: part_integrity
See /Users/pchampion/gpAdminLogs/gpcheckcat_20190220.log for detail
```
Run the repair script, which appears to work:
```
$ cat gpcheckcat.repair.20190220153545/postgres_fixdistribution_20190220153545.sql
ALTER TABLE test_1_prt_1 SET DISTRIBUTED RANDOMLY;

$ ./gpcheckcat.repair.20190220153545/runsql_20190220153545.sh
Fixing distribution policies

$ echo $?
0
```
...but it didn't, because you're not allowed to alter subpartition distribution in 6:
```
$ cat gpcheckcat.repair.20190220153545/postgres_fixdistribution_20190220153545.out
ALTER TABLE test_1_prt_1 SET DISTRIBUTED RANDOMLY;
psql:postgres_fixdistribution_20190220153545.sql:1: ERROR:  can't set the distribution policy of "test_1_prt_1"
HINT:  Distribution policy can be set for an entire partitioned table, not for one of its leaf parts or an interior branch.
```

**Comment by jchampio** [comment]
@skahler-pivotal: #7046 fixed part of this by bubbling up the correct exit code on failure. The UX is still just as bad, though; there's no indication that anything has gone wrong from the top level, unless the DBA is checking error codes:
```
$ cat gpcheckcat.repair.20190220153545/postgres_fixdistribution_20190220153545.sql
ALTER TABLE test_1_prt_1 SET DISTRIBUTED RANDOMLY;

$ ./gpcheckcat.repair.20190220153545/runsql_20190220153545.sh
Fixing distribution policies

$ echo $?
3
```
How much would you like us to change at this point?

Also, are you interested in having this backported to 5X?

**Comment by skahler-pivotal** [comment]
@jchampio I don't want to backport that to 5, there is a behavior there that while it may be incorrect, could possibly be something people are relying on. So I'd rather see that change happen at the major version.

I don't feel as part of this #7046 we should track down adjusting all of outputs, though I do think that would be a good enhancement and that this issue should stay open until we are able to do that too.

**Comment by lij55** [comment]
closing this old GP5 only issue now.
