### ISSUE TITLE
Fix unittests to cope with assertion builds and OS X

### ISSUE THREAD

**Issue by danielgustafsson** [greenplum-db/gpdb#703]
The unittests are currently not working for builds configured with `--enable-cassert` (the resolution might be to simply remove the test but it needs to be looked at again) and on OS X there are additional failures which might stem from clang vs. gcc. This issue is a reminder/TODO to get them fixed for both cases.

**Comment by ashwinstar** [comment]
@danielgustafsson Passes for me on latest with `--enable-cassert` any thing particular we need to take care here or it got fixed by itself ?

**Comment by danielgustafsson** [comment]
> On 30 Oct 2017, at 19:26, Ashwin Agrawal <notifications@github.com> wrote:
> 
> @danielgustafsson Passes for me on latest with --enable-cassert any thing particular we need to take care here or it got fixed by itself ?

If it passes for you then they have magically been fixed by something since this was created, will close. Thanks!
