### ISSUE TITLE
struct FileScanDescData should not have the field in_func_oid 

### ISSUE THREAD

**Issue by vitesse-ftian** [greenplum-db/gpdb#7038]
### Greenplum version or build
master, 5x
### Step to reproduce the behavior

Not a bug, but code smell.   Found by code review:

The field is not useful -- later in code when it is used to get FmgrInfo, a local variable should do.    Even if we decide to include this useless info, it should be an array, otherwise the code is just confusing.

**Comment by berlin-ab** [comment]
Thanks @vitesse-ftian . This sounds like an excellent opportunity for a PR contribution.

**Comment by hlinnaka** [comment]
FileScanDescData is no more, closing.
