### ISSUE TITLE
vagrant ssh should source the greenplum path

### ISSUE THREAD

**Issue by berlin-ab** [greenplum-db/gpdb#7041]
As a user of the vagrant tooling, 
I want to be able to use postgresql commands when I ssh in
So I can start using gpdb immediately, 
And I don't have to learn about the structure of the files on the image ('/usr/local/gpdb')

When I ssh into the box, 
Then the greenplum path should already be sourced for me.

**Comment by berlin-ab** [comment]
cc @oliverralbertini

**Comment by oliverralbertini** [comment]
Once the original vagrant PR is merged, we can quickly add this.

**Comment by berlin-ab** [comment]
@oliverralbertini What PR addressed this issue?

**Comment by oliverralbertini** [comment]
https://github.com/greenplum-db/gpdb/pull/7080

**Comment by berlin-ab** [comment]
Closed by #7080
