### ISSUE TITLE
ORCA supports distribution key update (docs issue?)

### ISSUE THREAD

**Issue by kapustor** [greenplum-db/gpdb#7060]
### Greenplum version or build
4.3.25 and 5.13 and 5.15 and others
### OS version and uname -a
N/A
### autoconf options used ( config.status --config )
N/A
### Installation information ( pg_config )
N/A
### Expected behavior
Docs tell us we cant update a distribution key so row cannot be moved to other segment.
The same is about updating partitioning - we cannot update partition key so a tuple be moved to another partition.
http://docs.greenplum.org/5160/admin_guide/dml.html#topic4
```
The Greenplum distribution key columns may not be updated.
```
### Actual behavior
ORCA starting from 3.9.0 (3.14.0 also) updates distribution key and partition key successfully:
```
adb=# create table ttt (id int) distributed by (id);
CREATE TABLE
adb=# insert into ttt select 1;
INSERT 0 1
adb=# select gp_segment_id, id from ttt
adb-# ;
 gp_segment_id | id
---------------+----
            54 |  1
(1 row)

adb=# update ttt set id=2 where id=1;
UPDATE 1
adb=# select gp_segment_id, id from ttt;
 gp_segment_id | id
---------------+----
            39 |  2
```
### Step to reproduce the behavior
See above.

**Comment by vraghavan78** [comment]
Orca does support updating distribution columns. Planner does not on 5

**Comment by mkiyama** [comment]
closing
