### ISSUE TITLE
`gpinitsystem` does not pick up new hostsnames if run multiple times

### ISSUE THREAD

**Issue by zachradtka** [greenplum-db/gpdb#707]
I was building a system and had a hostname that changed. I initially tried to change the hostname by editing `gp_segment_configuration`. I did the following and got an error:

```
$ gpstart -m
$ PGOPTIONS='-c gp_session_role=utility' psql
template1=# update gp_segment_configuration set hostname='<new_hostname>' where hostname='<old_hostname>';
ERROR:  permission denied: "gp_segment_configuration" is a system catalog
```

This is similar to issue #214 

Since I just installed the system, and this didn't work, I figured I would just run `gpdeletesystem` and re-run `gpinitsystem`. Sadly, that did not fix my hostname issue.

It took me quite some time, but I found that `gpinitsystem` calls [`gphostcachelookup.py`,](https://github.com/greenplum-db/gpdb/blob/d9e94bc1331958b7b5bb486202aed41f0f55cd60/gpMgmt/bin/lib/gphostcachelookup.py) which in turn calls initializes an instance of `GpInterfaceToHostNameCache` in [gphostcache.py](https://github.com/greenplum-db/gpdb/blob/d9e94bc1331958b7b5bb486202aed41f0f55cd60/gpMgmt/bin/gppylib/gphostcache.py). Because `gphostcachelookup.py` initializes `GpInterfaceToHostNameCache` with an empty array (`[]`) for the `currentHostNameAnswersForInterfaces` argument, it does not validate hostnames and always reads from the cached file `.gphostcache`.

To fix my problem I renamed the file `.gphostcache` and everything worked.

I think the possible solutions are:
- Do not cache hostnames in `.gphostcache`
- Have `gphostcachelookup.py` pass valid hostnames to `GpInterfaceToHostNameCache`
- Allow editing of `gp_segment_configuration`

**Comment by bhuvnesh2703** [comment]
to update gp_segment_configuration you should the set the below guc
set allow_system_table_mods='dml';

**Comment by zachradtka** [comment]
That is good information! I couldn't find it in the docs anywhere. Hopefully I won't have to edit `gp_segment_configuration` again.
