### ISSUE TITLE
Publish gphdfs library to a public Maven repository

### ISSUE THREAD

**Issue by kdowbecki** [greenplum-db/gpdb#71]
I wanted to use [gphdfs extension](https://github.com/greenplum-db/gpdb/tree/6b0e52beadd678c5050af9c978c26d171ba86ae0/gpAux/extensions/gphdfs) as dependency in my MapReduce job converting from Avro to GPWritable. I searched public Maven repositories and I couldn't find it. Can you please publish this library to a public Maven repository?

**Comment by yydzero** [comment]
Maybe it is quick to download GPDB binary from Pivotal Net and extract
gphdfs jar from that.

Would be nice if you could help on publishing it to maven repo.

On Tue, Nov 10, 2015 at 10:19 PM, Karol Dowbecki <notifications@github.com>
wrote:

> I wanted to use gphdfs extension
> <https://github.com/greenplum-db/gpdb/tree/6b0e52beadd678c5050af9c978c26d171ba86ae0/gpAux/extensions/gphdfs>
> as dependency in my MapReduce job converting from Avro to GPWritable. I
> searched public Maven repositories and I couldn't find it. Can you please
> publish this library to a public Maven repository?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/greenplum-db/gpdb/issues/71>.
>



-- 
Best Regards,
Yandong

**Comment by ivannovick** [comment]
@yydzero @lij55 any action item for this issue?

**Comment by lavjain** [comment]
GPHDFS code is builable now. All references to private repos have been removed.

**Comment by ivannovick** [comment]
nice!
