### ISSUE TITLE
COPY (query) TO '...' NEWLINE producing an error

### ISSUE THREAD

**Issue by CharlieRiesner** [greenplum-db/gpdb#7122]
### Greenplum version or build
5.15.1
### Expected behavior
When running `COPY (...) TO '...' NEWLINE AS 'CRLF';` to export to a file using the correct line endings.
### Actual behavior
An error is produced: `newline currently available for data loading only, not unloading`
### Step to reproduce the behavior
Run any query that does a copy to specifying the newline character

**Comment by danielgustafsson** [comment]
`NEWLINE` is not a supported option for unloading data, it's intended for specifying the type of newline to expect in the file which is loaded in `COPY .. FROM`. What is the usecase you had in mind for doing this in `COPY .. TO` ?

**Comment by GlossyPanther** [comment]
Currently I have GP hosted on a Linux environment across 8 nodes. But I want to export a file with Windows line endings. Most of the files that I deal with are from Windows environments.

**Comment by danielgustafsson** [comment]
Fair enough, that's a legitimate usecase. I've marked this as a feature request.

**Comment by adam8157** [comment]
I would suggest using `COPY (...) TO PROGRAM 'cat | sed -e "s/$/\r/" > /path/to/file';` to workaround.

I suppose upstream Postgres would like to have this feature built-in, will do some investigation.
