### ISSUE TITLE
tests 'qp_with_clause' and 'DML_over_joins' on GPDB-master-opt-l1 are unstable

### ISSUE THREAD

**Issue by kuien** [greenplum-db/gpdb#716]
I found  'qp_with_clause' and 'DML_over_joins' on GPDB-master-opt-l1 are unstable, they fail occasionally. 

For example:

1. qp_with_clause

-   http://pulse-releng.greenplum.com/browse/projects/GPDB-master-opt-l1_kuien/builds/70068/
-   http://pulse-releng.greenplum.com/browse/projects/GPDB-master-opt-l1/builds/70045/

2. DML_over_joins

-   http://pulse-releng.greenplum.com/browse/projects/GPDB-master-opt-l1_kuien/builds/70029/tests/
-   http://pulse-releng.greenplum.com/browse/projects/GPDB-master-opt-l1/builds/69831/tests/
-   http://pulse-releng.greenplum.com/browse/projects/GPDB-master-opt-l1/builds/69818/tests/

Pls help to have a look.

**Comment by vraghavan78** [comment]
Thanks @kuien for bringing this up.

qp_with_clause: Fails because of there is minor difference in the answer

7.43181e+07 vs 7.43182e+07

DML_over_joins is non-deterministics.

QO team will clean these up.

**Comment by vraghavan78** [comment]
1. qp_with_clause
Fixed by changing the query. https://github.com/greenplum-db/gpdb/commit/be43f6265ee9baf727548d7d5b716f52e64c23de

2. DML_over_joins
https://github.com/greenplum-db/gpdb/pull/787

**Comment by vraghavan78** [comment]
Fixed both @kuien please re-open the issue if it still persists.
