### ISSUE TITLE
Greenplum - deprecated library dependency

### ISSUE THREAD

**Issue by navulirs** [greenplum-db/gpdb#7191]
### Greenplum version or build
5.17.0
### Expected behavior
Expecting to use supported (not deprecated) libraries.
### Actual behavior
has dependency to deprecated library - lockfile
https://github.com/greenplum-db/gpdb/blob/master/python-dependencies.txt

**Comment by kmacoskey** [comment]
@gfphoenix78 The python dependencies are managed by the Cluster Management team.

@bharath1028 ^

**Comment by tylarb** [comment]
Lockfile was removed in https://github.com/greenplum-db/gpdb/pull/10328
