### ISSUE TITLE
Greenplum mirror segment out of sync

### ISSUE THREAD

**Issue by kishoreannapureddy** [greenplum-db/gpdb#7203]
### Greenplum version or build
postgres (Greenplum Database) 5.3.0 build commit:2155c5a8cf8bb7f13f49c6e248fd967a74fed591

### OS version and uname -a
Linux am1 3.10.0-514.10.2.el7.x86_64 #1 SMP Fri Mar 3 00:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

### Installation information ( pg_config )
BINDIR = /usr/local/greenplum-db-5.3.0/bin
DOCDIR = /usr/local/greenplum-db-5.3.0/doc/postgresql
HTMLDIR = /usr/local/greenplum-db-5.3.0/doc/postgresql
INCLUDEDIR = /usr/local/greenplum-db-5.3.0/include
PKGINCLUDEDIR = /usr/local/greenplum-db-5.3.0/include/postgresql
INCLUDEDIR-SERVER = /usr/local/greenplum-db-5.3.0/include/postgresql/server
LIBDIR = /usr/local/greenplum-db-5.3.0/lib
PKGLIBDIR = /usr/local/greenplum-db-5.3.0/lib/postgresql
LOCALEDIR = /usr/local/greenplum-db-5.3.0/share/locale
MANDIR = /usr/local/greenplum-db-5.3.0/man
SHAREDIR = /usr/local/greenplum-db-5.3.0/share/postgresql
SYSCONFDIR = /usr/local/greenplum-db-5.3.0/etc/postgresql
PGXS = /usr/local/greenplum-db-5.3.0/lib/postgresql/pgxs/src/makefiles/pgxs.mk
CC = /opt/gcc-6.2.0/bin/gcc -m64
CPPFLAGS = -D_GNU_SOURCE -I/usr/local/greenplum-db-5.3.0/include
CFLAGS = -m64 -O3 -fargument-noalias-global -fno-omit-frame-pointer -g -std=gnu99 -Wall -Wmissing-prototypes -Wpointer-arith -Wendif-labels -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fno-aggressive-loop-optimizations -Wno-unused-but-set-variable -Wno-address -I/usr/local/greenplum-db-5.3.0/include
CFLAGS_SL = -fpic
LDFLAGS = -Wl,--as-needed -Wl,-rpath,'/usr/local/greenplum-db-devel/lib',--enable-new-dtags -L/usr/local/greenplum-db-5.3.0/lib
LDFLAGS_SL = 
LIBS = -lpgport -lgpopt -lnaucrates -lgpdbcost -lgpos -lxerces-c -lxml2 -lpam -lrt -lkrb5 -lcom_err -lgssapi_krb5 -lcrypt -ldl -lm -lrt -L/usr/local/greenplum-db-5.3.0/lib
VERSION = PostgreSQL 8.3.23

One of the mirror segments has gone out of sync. Is there any recovery mode to get it in sync?

**Comment by jimmyyih** [comment]
How is it out of sync?  Can you show `gpstate` output and/or `select * from gp_segment_configuration` output?

If the mirror has gone out of sync, my assumption is that the mirror segment is down and the primary segment is in `changetracking mode` (denoted as 'c' in `gp_segment_configuration`).  Running `gprecoverseg` should bring the mirror segment back up and synchronize it back to the primary segment (the primary segment will go into `resynchronization mode` denoted as 'r').

If that doesn't work, there is always full recovery by running `gprecoverseg -f` which will essentially recreate the mirror segment entirely.

**Comment by berlin-ab** [comment]
@kishoreannapureddy We'd like to help you. Would you be able to provide more information to help us debug your issue?

**Comment by JunfengYang** [comment]
Close for now. Please reopen if you hit the problem again.
