### ISSUE TITLE
most gpexpand feature tests contain a race condition rendering them flaky

### ISSUE THREAD

**Issue by dkrieger-pvtl** [greenplum-db/gpdb#7229]
### Greenplum version or build
master, say 9a2cf8cc19

### Installation information ( pg_config )
stock build.

### Step to reproduce the behavior
The gpexpand feature tests(`gpMgmt/test/behave/mgmt_utils/gpexpand.feature`) should all pass; in particular, the following idiom in most of the feature tests contains a race:

```gherkin
   @gpexpand_verify_writable_external_redistribution
    Scenario: Verify policy of writable external table is correctly updated after redistribution 
        Given a working directory of the test as '/data/gpdata/gpexpand'
(1)-->  And the database is killed on hosts "localhost"
        And a temporary directory under "/data/gpdata/gpexpand/expandedData" to expand into
(2)-->  And the database is not running
        And the cluster is generated with "1" primaries only
```

Step (1) does an asynchronous `pkill postgres`, essentially, so the database is not necessarily down by the time (2) runs.  In particular, (2) can think there is a running database and attempt to stop it using `gpstop`, only to find that (1) subsequently completed.

Presumably, we should run only (2) in place of (1), but there may be other considerations.

(For a recent example(private, unfortunately), see https://prod.ci.gpdb.pivotal.io/teams/main/pipelines/gpdb_master/jobs/gpexpand/builds/10)

**Comment by dkrieger-pvtl** [comment]
@dujialun @kainwen @zhangjackey   Can you please take a look at this?

**Comment by gaos1** [comment]
@dujialun will work on this.

**Comment by kainwen** [comment]
Fixed by pr https://github.com/greenplum-db/gpdb/pull/7324
