### ISSUE TITLE
Planner crashes with Grouping() and ROLLUP()

### ISSUE THREAD

**Issue by hardikar** [greenplum-db/gpdb#7279]
### Greenplum version or build
GPDB master

### autoconf options used ( config.status --config )
```CFLAGS="-O1" ./configure --with-python --with-perl --disable-gpfdist --enable-orca --enable-debug --enable-cassert ```

### Step to reproduce the behavior
```
create table test (a int, b int);
insert into test values (1, 1), (null, 1);

create table jazz (g int, h int, i int);
insert into jazz values (2, 2, 2);

shardikar=# set optimizer = off;
SET
shardikar=#  select a,sum(b), (select grouping(a) from jazz group by test.a, jazz.g) from test group by rollup(a);
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
```

Logs contain:
```
2019-03-27 17:54:38.929248 CDT,,,p85703,th0,,,2019-03-27 17:54:27 CDT,0,con26,cmd8,seg-1,,,,,"PANIC","XX000","Unexpected internal error: Master process rece
ived signal SIGSEGV",,,,,,,0,,,,"1    0x10c9fb866 postgres StandardHandlerForSigillSigsegvSigbus_OnMainThread + 0x146
2    0x7fffc3335b3a libsystem_platform.dylib _sigtramp + 0x1a
3    0x7fac4d000048 0x7fac4d000048
4    0x10c86174c postgres plan_tree_walker + 0x32c
5    0x10c7bb59a postgres expression_tree_walker + 0x34a
6    0x10c8613b0 postgres walk_plan_node_fields + 0x20
7    0x10c861474 postgres plan_tree_walker + 0x54
8    0x10c842529 postgres findFirstSubqueryScan + 0x19
9    0x10c841845 postgres plan_list_rollup_plans + 0x605
10   0x10c840811 postgres plan_grouping_extension + 0x1e1
11   0x10c836648 postgres grouping_planner + 0x1688
12   0x10c833e7a postgres subquery_planner + 0x5da
13   0x10c8332e7 postgres standard_planner + 0x2c7
14   0x10c832ffc postgres planner + 0x12c
15   0x10c8e8054 postgres pg_plan_query + 0x54
16   0x10c8e812e postgres pg_plan_queries + 0x6e
17   0x10c8eb183 postgres exec_simple_query + 0x313
18   0x10c8ea5b8 postgres PostgresMain + 0x10d8
19   0x10c876a6a postgres BackendRun + 0x1ea
20   0x10c8760d4 postgres BackendStartup + 0x214
"
````

------------------------------------------------
On master, ORCA doesn't crash, but it produces wrong results:
```
shardikar=# set optimizer =on;
SET
shardikar=# select a,sum(b), (select grouping(a) from jazz group by test.a, jazz.g) from test group by rollup(a);
 a | sum | grouping
---+-----+----------
   |   1 |        0
   |   2 |        0
 1 |   1 |        0
(3 rows)
```

Postgres:
```
postgres=# select a,sum(b), (select grouping(a) from jazz group by test.a, jazz.g) from test group by rollup(a);
 a | sum | grouping
---+-----+----------
   |   2 |        1
   |   1 |        0
 1 |   1 |        0
(3 rows)
```
On 5X_STABLE, the query does not crash, but instead gives the same wrong results. 

Unfortunately, we can't do anything about the wrong results! The reason is that `struct GroupingFunc` in GPDB doesn't track the levels up information. Compare that to upstream [postgres](https://github.com/postgres/postgres/blob/3b925e905de3204ffef64fa4d53dd7bbac1a143f/src/include/nodes/primnodes.h#L342). This should be fixed once the relevant [commit](https://github.com/postgres/postgres/commit/f3d3118532175541a9a96ed78881a3b04a057128) is merge into GPDB.

_But on master, we should fix the crash!_

**Comment by hardikar** [comment]
Also, we could consider ERROR-ing in the parser when we see queries with nested GroupingFuncs.

**Comment by guofengrichard** [comment]
> Also, we could consider ERROR-ing in the parser when we see queries with nested GroupingFuncs.

The crash on master is not caused by GroupingFunc in subquery. It is because we fail to provide the correct `plan_tree_base_prefix` when recursing through a subplan node.
