### ISSUE TITLE
goldengate for bigdata  JDBC handler

### ISSUE THREAD

**Issue by devinop** [greenplum-db/gpdb#7299]
Ii wan't Synchronous data from oracle to gpdb real-time, But failed , and find some instructions in oracle documentation and goldengate configuration files:
1.Greenplum target using the Oracle branded DataDirect Greenplum JDBC driver. Contact Oracle support for the branded JDBC driver files.
2.#Contact Oracle support to get the fmwgenerictoken*.jar and wlgreenplum*.jar files

Dose anyone has these two files ????

**Comment by scqhb** [comment]
看起来是的，我也遇到了这个问题，不知道你怎么解决的

**Comment by devinop** [comment]
> 
> 
> 看起来是的，我也遇到了这个问题，不知道你怎么解决的

没解决~~~~~~~换了一种方式    用ogg bigdata+kafka+gpkafka

**Comment by scqhb** [comment]
感谢您的分享，再请教一下源端数据update或者delete操作，也是通过gpkafka同步的吗，因为我们是实时交易系统，会涉及update等dml语句

**Comment by devinop** [comment]
> 
> 
> 感谢您的分享，再请教一下源端数据update或者delete操作，也是通过gpkafka同步的吗，因为我们是实时交易系统，会涉及update等dml语句

这个我没有测试，我们的业务需求只是追加，并且我用了appendonly表，不支持dml。
测试环境我有同步过DML，用的是ogg bigdata filewriter  生成json格式的文件然后用python处理，但是做不到实时

**Comment by scqhb** [comment]
好的，感谢感谢，我继续探索如何做到实时同步

**Comment by devinop** [comment]
> 
> 
> 好的，感谢感谢，我继续探索如何做到实时同步

有方案了分享一下

**Comment by scqhb** [comment]
好的好的

**Comment by hlinnaka** [comment]
I believe there is nothing more to do about this from greenplum's side. Closing.

**Comment by CallMeKingsley97** [comment]
Contact Oracle support to get the fmwgenerictoken*.jar and wlgreenplum*.jar files
请问下  有这两个jar包了吗  最近也在搞oracle到gp实时同步，不希望通过kafka，直接通过ogg到gp，想用jdbc，但是没jar包
