### ISSUE TITLE
Lockmode for partition tables is not correct when ORCA is enabled

### ISSUE THREAD

**Issue by kainwen** [greenplum-db/gpdb#7318]
## Version
I test for the latest master branch (commit: f616837a5595db8ee0934b0cee39afa3e0e02bca).

## Table

AO Partition tables:

```sql

create table t_lockmods_ao_part (c int) with(appendonly=true)
distributed randomly partition by range (c) (start(1)  end (5) every (1), 
default partition extra);

insert into t_lockmods_ao_part select * from generate_series(1, 10);
```

Heap Partition tables:

```sql
create table t_lockmods_part (c int)  distributed randomly
partition by range (c) (start(1)  end (5) every (1),  default partition extra);

insert into t_lockmods_part select * from generate_series(1, 10);
```

### Select-for-update

`select-for-update1` can lock multiple relations, so it is not easy for mpp database to lock tuples. In Greenplum,  Select-for-update should acquire ExclusiveLock on tables.

Orca only locks the root table. No locks is held on child partitions.

```sql
gpadmin=# show optimizer;
 optimizer
-----------
 on
(1 row)

gpadmin=# begin;
BEGIN
gpadmin=# select * from t_lockmods_part for update;
 c
----
  6
  8
  9
  3
  1
 10
  2
  5
  7
  4
(10 rows)

gpadmin=# select locktype, mode, granted, relation::regclass::text from pg_locks where relation::regclass::text like 't_lockmods_part%' and gp_segment_id = -1;
 locktype |      mode       | granted |    relation
----------+-----------------+---------+-----------------
 relation | AccessShareLock | t       | t_lockmods_part
 relation | ExclusiveLock   | t       | t_lockmods_part
(2 rows)

gpadmin=#
```

Even if the above transaction is not committed or aborted, another transaction that directly update some child tables can be sucessfull:

```sql
gpadmin=# begin;
BEGIN
gpadmin=# update t_lockmods_part_1_prt_2 set c = c + 0;
UPDATE 1
```

postgres12 and greeplum with planner does not have such problems.

### UPDATE | DELETE

With Orca enabled, for partition tables it also only hold locks on root table.

So a delete on root table and a delete on some child table can be concurrently on QD, so each of them will dispatch to QE, which might lead to global deadlock or error(AO tables).

#### case error of AO table

```sql
-- transaction1 
begin;               
delete from t_lockmods ;
```

```sql
-- transaction2
begin;
delete from t_lockmods_ao_part_1_prt_2; -- will hang on QE
```

then transaction 1 commit, transaction 2 will error out:

```sql
gpadmin=# begin;
BEGIN
Time: 13.343 ms
gpadmin=# delete from t_lockmods_ao_part_1_prt_2;
ERROR:  duplicate key value violates unique constraint "pg_aovisimap_16401_index"  (seg1 10.34.54.23:25433 pid=942990)
DETAIL:  Key (segno, first_row_no)=(1, 0) already exists.
Time: 3421.209 ms
gpadmin=#
```

#### case of global deadlock

* t_lockmods_ao_part_1_prt_2 contains the tuple `(1)`; and tuple `(1)` only in this table.
* t_lockmods_ao_part_1_prt_3 contains the tuple `(2)`; and tuple `(2)` only in this table.

timeline:
1. transaction 1: begin
2. transaction2: begin
3. transaction1: update t_lockmods_ao_part set c = c + 0 where c = 1;  --ok
4. transaction2: update t_lockmods_ao_part_1_prt_3 set c = c + 0 where c = 2; --ok
5. transaction1: update t_lockmods_ao_part set c = c + 0 where c = 2; -- hang!
6. transaction2: update t_lockmods_ao_part_1_prt_2 set c = c+ 0 where c = 1; --hang

Global deadlock Occurs.

**Comment by gfphoenix78** [comment]
@kainwen Can we close this issue? I saw a PR(#7509) about the issue has been merged.
