### ISSUE TITLE
gpload test 22 disabled

### ISSUE THREAD

**Issue by danielgustafsson** [greenplum-db/gpdb#7321]
Commit 2def0c1c0779f16904affe95aaa53f508d9dba61 disabled gpload test case 22 due to it exhibiting flakiness which has been hard to reproduce. This needs to be addressed and re-enabled.

**Comment by danielgustafsson** [comment]
As an update: this is now being backported in #7610.

**Comment by d** [comment]
@huiliang-liu Has there been any follow-up to #7244 to re-enable the test?

**Comment by hlinnaka** [comment]
Ping? Have we updated the python version used in the pipeline since last summer? Could we try to re-enable the test now?

**Comment by lij55** [comment]
https://github.com/greenplum-db/gpdb/pull/13114

**Comment by lij55** [comment]
fixed
