### ISSUE TITLE
truncate unlogged table failed

### ISSUE THREAD

**Issue by zhbp366** [greenplum-db/gpdb#7340]
### Greenplum version or build
Greenplum Database 6.0.0-beta
### OS version and uname -a
centos 7.5
### Expected behavior
truncate succeed
### Actual behavior
truncate failed
ERROR:  could not create file "base/22969/58521_init": File exists
58P02
### Step to reproduce the behavior
Step 1:
CREATE unlogged  TABLE  test_unlogged (
    id bigint,
    con_id bigint,
    con_no character varying,
    order_id bigint,
    order_no character varying,
    item_id bigint,
    exp_id bigint,
    tran_record_id bigint,
    bill_id bigint,
    bill_no character varying,
    con_amount numeric(19,2),
    fin_cid character varying,
    fin_full_cnames character varying,
    item_cid character varying,
    item_full_cnames character varying,
    con_ch character varying,
    con_ch_name character varying,
    con_type character varying,
    con_type_name character varying,
    con_return_name character varying,
    follow_user_name character varying,
    appointment character varying,
    appointment_name character varying,
    sign_com_name character varying,
    deal_time character varying,
    cust_name character varying,
    item_name character varying,
    item_specs character varying,
    item_amt numeric(19,2),
    old_price numeric(19,2),
    price_percent numeric(19,2),
    item_cost numeric(19,2),
    property character varying,
    property_code character varying,
    amount numeric(19,2),
    pay_type character varying,
    submit_time character varying,
    funds_flow_time character varying,
    confirm_time character varying,
    bonus_amt numeric(19,2),
    bonus_time character varying,
    share_user_name text,
    submit_name character varying,
    company_name character varying,
    second_lvl_dept character varying,
    third_lvl_dept character varying,
    forth_lvl_dept character varying,
    fifth_lvl_dept character varying,
    cxq_con_no character varying,
    bus_cxq_amt numeric(19,2),
    cxq_audit_flag character varying,
    cxq_audit_result character varying,
    work_confirm_status character varying,
    work_confirm_flag character varying,
    work_confirm_opinion_id bigint,
    work_confirm_opinion text,
    work_confirm_time character varying,
    timeout_day character varying,
    serial_number character varying,
    relation_con_number text,
    loadtimestamp bigint,
    loadtime character varying
) DISTRIBUTED BY (id);

Step 2:
 truncate table test_unlogged

**Comment by paul-guo-** [comment]
On latest master with cassert enabled, it assert fails at this.

```
(gdb) bt
#0  0x00007f73e4b7f7a3 in select () at ../sysdeps/unix/syscall-template.S:81
#1  0x0000000000ca1a48 in pg_usleep (microsec=30000000) at pgsleep.c:56
#2  0x0000000000b37da9 in elog_debug_linger (edata=0x12a44e0 <errordata>) at elog.c:5290
#3  0x0000000000b2e3c4 in errfinish (dummy=0) at elog.c:676
#4  0x0000000000b2cb7c in ExceptionalCondition (conditionName=0xe7cc00 "!(reln->md_fd[forkNum] == ((void *)0))", errorType=0xe7cbbe "FailedAssertion", fileName=0xe7cbb9 "md.c", lineNumber=288) at assert.c:46
#5  0x00000000009b8ca9 in mdcreate (reln=0x2ac5548, forkNum=INIT_FORKNUM, isRedo=0 '\000') at md.c:288
#6  0x00000000009bbde0 in smgrcreate (reln=0x2ac5548, forknum=INIT_FORKNUM, isRedo=0 '\000') at smgr.c:355
#7  0x000000000060ab80 in heap_create_init_fork (rel=0x7f73e8caac98) at heap.c:1900
#8  0x0000000000725eff in ExecuteTruncate (stmt=0x298c128) at tablecmds.c:1844
#9  0x00000000009ca03c in standard_ProcessUtility (parsetree=0x298c128, queryString=0x298b5b8 "truncate table test_unlogged\n;", context=PROCESS_UTILITY_TOPLEVEL, params=0x0, dest=0x298c4b0, completionTag=0x7ffe14fd8970 "")
    at utility.c:622
#10 0x00000000009c99e5 in ProcessUtility (parsetree=0x298c128, queryString=0x298b5b8 "truncate table test_unlogged\n;", context=PROCESS_UTILITY_TOPLEVEL, params=0x0, dest=0x298c4b0, completionTag=0x7ffe14fd8970 "")
    at utility.c:373
```

**Comment by paul-guo-** [comment]
```
diff --git a/src/backend/commands/tablecmds.c b/src/backend/commands/tablecmds.c
index e73a236dda2..c2b0d67ff33 100644
--- a/src/backend/commands/tablecmds.c
+++ b/src/backend/commands/tablecmds.c
@@ -1840,8 +1840,8 @@ ExecuteTruncate(TruncateStmt *stmt)
            {
                Relation toast_rel = relation_open(toast_relid, AccessExclusiveLock);
                RelationSetNewRelfilenode(toast_rel, RecentXmin, minmulti);
-               if (rel->rd_rel->relpersistence == RELPERSISTENCE_UNLOGGED)
-                   heap_create_init_fork(rel);
+               if (toast_rel->rd_rel->relpersistence == RELPERSISTENCE_UNLOGGED)
+                   heap_create_init_fork(toast_rel);
                heap_close(toast_rel, NoLock);
            }
```
should be able to fix this. Thanks for reporting.
