### ISSUE TITLE
coredump while deleting from subpartitioned table

### ISSUE THREAD

**Issue by gamaro** [greenplum-db/gpdb#738]
When I issue a delete on a subpartitioned table on greenplum 4.3.8.1 I get a coredump on one of the database segments.

This can be reproduced the following way:
CREATE TABLE teste_subp
(
                time_client_key numeric(16,0) NOT NULL,
                ngin_service_key numeric NOT NULL,
                profile_key numeric NOT NULL
)
DISTRIBUTED BY (time_client_key)
PARTITION BY RANGE(time_client_key)
SUBPARTITION BY LIST (ngin_service_key)
SUBPARTITION TEMPLATE
( 
                SUBPARTITION Package5 VALUES (479534741),
                DEFAULT SUBPARTITION other_services
)  
(
                PARTITION p20151110 START (2015111000::numeric) END (2015111100::numeric) WITH (appendonly=false)
)
;

CREATE INDEX teste_subp_ndx0
  ON teste_subp
  (profile_key);

set optimizer=on;

gplum_test=# delete from teste_subp where profile_key = 99999999;
NOTICE:  Releasing segworker groups to finish aborting the transaction.
ERROR:  Error on receive from seg6 tcd-ngin-gpdb3:40002 pid=32514: server closed the connection unexpectedly
DETAIL:  
        This probably means the server terminated abnormally
        before or while processing the request.
ERROR:  could not temporarily connect to one or more segments (cdbgang.c:1654)

The table is empty and has 104 subpartitions. Here is the explain plan:
gplum_test=# explain delete from teste_subp where profile_key = 99999999;
##                                                       QUERY PLAN                                                      

Delete  (cost=0.00..0.97 rows=1 width=1)
   ->  Result  (cost=0.00..0.75 rows=1 width=450)
         ->  Partition Selector for teste_subp  (cost=0.00..0.75 rows=1 width=446)
               ->  Sequence  (cost=0.00..0.75 rows=1 width=442)
                     ->  Partition Selector for teste_subp (dynamic scan id: 1)  (cost=10.00..100.00 rows=13 width=4)
                           Partitions selected:  72 (out of 72)
                     ->  Dynamic Index Scan on teste_subp (dynamic scan id: 1)  (cost=0.00..0.75 rows=1 width=442)
                           Index Cond: profile_key = 99999999::numeric
Settings:  optimizer=on
Optimizer status: PQO version 1.629
(10 rows)

On the segment that generates the error i can see the following messages:
2016-05-10 12:25:09.755348 WEST,,,p32514,th0,,,2016-05-10 12:24:28 WEST,0,con32,cmd7,seg6,,,,,"PANIC","XX000","Unexpected internal error: Segment process received signal SIGSEGV",,,,,,,0,,,,"1    0x3cacc0f7e0 libpthread.so.0 <symbol not found> + 0xacc0f7e0
2    0x7b4c70 postgres ExecPartitionSelector + 0x1d0
3    0x75bc01 postgres ExecProcNode + 0x4b1
4    0x7aee48 postgres ExecSequence + 0x88
5    0x75bba7 postgres ExecProcNode + 0x457
6    0x7b4c05 postgres ExecPartitionSelector + 0x165
7    0x75bc01 postgres ExecProcNode + 0x4b1
8    0x78dda5 postgres ExecResult + 0x85
9    0x75bbdf postgres ExecProcNode + 0x48f
10   0x7b154c postgres ExecDML + 0x2c
11   0x75bb41 postgres ExecProcNode + 0x3f1
12   0x75108c postgres <symbol not found> + 0x75108c
13   0x751898 postgres ExecutorRun + 0x3a8
14   0x9a0044 postgres <symbol not found> + 0x9a0044
15   0x9a0f39 postgres <symbol not found> + 0x9a0f39
16   0x9a2735 postgres PortalRun + 0x515
"
2016-05-10 12:25:09.757566 WEST,,,p31221,th-2060015840,,,,0,,,seg-1,,,,,"LOG","00000","server process (PID 32514) was terminated by signal 11: Segmentation fault",,,,,,,0,,"postmaster.c",5876,
2016-05-10 12:25:09.757601 WEST,,,p31221,th-2060015840,,,,0,,,seg-1,,,,,"LOG","00000","terminating any other active server processes",,,,,,,0,,"postmaster.c",5563,
2016-05-10 12:25:09.760744 WEST,,,p32471,th-2060015840,,,,0,con13,,seg-1,,,,,"FATAL","57P01","terminating connection due to administrator command",,,,,,,0,,"postgres.c",3562,

**Comment by vraghavan78** [comment]
Thanks @gamaro we will take a look and get back shortly.

**Comment by vraghavan78** [comment]
```
vraghavan=# delete from teste_subp where profile_key = 99999999;
LOG:  statement: delete from teste_subp where profile_key = 99999999;
DELETE 0
```
