### ISSUE TITLE
psql: FATAL:  database is not accepting commands to avoid wraparound data loss in database "postgres"

### ISSUE THREAD

**Issue by jinxiaoxin** [greenplum-db/gpdb#7394]
When I execute any command
error：
psql: FATAL:  database is not accepting commands to avoid wraparound data loss in database "postgres"
HINT:  Shutdown Greenplum Database. Lower the xid_stop_limit GUC. Execute a full-database VACUUM in "postgres". Reset the xid_stop_limit GUC.

how to solve？

**Comment by berlin-ab** [comment]
Are you able to run the command `VACUUM` after connecting to the database named `postgres`

**Comment by gfphoenix78** [comment]
Will close this issue for no context, no response for a long time.
