### ISSUE TITLE
ubuntu 15.04, make cluster in gpdemo failed - Failed initdb(master)

### ISSUE THREAD

**Issue by robertmu** [greenplum-db/gpdb#74]
platform:ubuntu(32bit) 15.04 (Linux ubuntu 3.19.0-28-generic #30-Ubuntu SMP Mon Aug 31 15:52:10 UTC 2015 i686 i686 i686 GNU/Linux) 
gcc (Ubuntu 4.9.2-10ubuntu13) 4.9.2
./configure --enable-debug --enable-cassert

gpadmin@ubuntu:~/projects/gpdb_working/gpdb/gpAux/gpdemo$ make cluster
======================================================================
            ______  _____  ______  _______ _______  _____
           |  ____ |_____] |     \ |______ |  |  | |     |
           |_____| |       |_____/ |______ |  |  | |_____|

----------------------------------------------------------------------

  This is a demo of the Greenplum Database system.  We will create
  a cluster installation with master and 6 segment instances
  (3 primary & 3 mirror).

    GPHOME ................. : /usr/local/pgsql
    MASTER_DATA_DIRECTORY .. : /home/gpadmin/projects/gpdb_working/gpdb/gpAux/gpdemo/datadirs/qddir/demoDataDir-1

    MASTER PORT (PGPORT) ... : 15432
    SEGMENT PORTS .......... : 25432 25433 25434 25435 25436 25437 25438 25439 25440 25441 25442 25443

  NOTE(s):

    * The DB ports identified above must be available for use.
    * An environment file gpdemo-env.sh has been created for your use.

======================================================================

==========================================================================================
executing:
  /usr/local/pgsql/bin/gpinitsystem -a -c clusterConfigFile ""
==========================================================================================

20151111:10:03:56:002381 gpinitsystem:ubuntu:gpadmin-[INFO]:-Checking configuration parameters, please wait...
20151111:10:03:56:002381 gpinitsystem:ubuntu:gpadmin-[INFO]:-Reading Greenplum configuration file clusterConfigFile
20151111:10:03:56:002381 gpinitsystem:ubuntu:gpadmin-[INFO]:-Locale has not been set in clusterConfigFile, will set to default value
20151111:10:03:56:002381 gpinitsystem:ubuntu:gpadmin-[INFO]:-Locale set to en_US.utf8
20151111:10:03:57:002381 gpinitsystem:ubuntu:gpadmin-[INFO]:-No DATABASE_NAME set, will exit following template1 updates
20151111:10:03:57:002381 gpinitsystem:ubuntu:gpadmin-[INFO]:-MASTER_MAX_CONNECT not set, will set to default value 25
20151111:10:03:57:002381 gpinitsystem:ubuntu:gpadmin-[INFO]:-Detected a single host GPDB array build, reducing value of BATCH_DEFAULT from 60 to 4
20151111:10:03:57:002381 gpinitsystem:ubuntu:gpadmin-[INFO]:-Checking configuration parameters, Completed
20151111:10:03:57:002381 gpinitsystem:ubuntu:gpadmin-[INFO]:-Commencing multi-home checks, please wait...
.
20151111:10:03:57:002381 gpinitsystem:ubuntu:gpadmin-[INFO]:-Configuring build for standard array
20151111:10:03:57:002381 gpinitsystem:ubuntu:gpadmin-[INFO]:-Commencing multi-home checks, Completed
20151111:10:03:57:002381 gpinitsystem:ubuntu:gpadmin-[INFO]:-Building primary segment instance array, please wait...
...
20151111:10:03:58:002381 gpinitsystem:ubuntu:gpadmin-[INFO]:-Building group mirror array type , please wait...
...
20151111:10:03:59:002381 gpinitsystem:ubuntu:gpadmin-[INFO]:-Checking Master host
20151111:10:03:59:002381 gpinitsystem:ubuntu:gpadmin-[INFO]:-Checking new segment hosts, please wait...
......
20151111:10:04:01:002381 gpinitsystem:ubuntu:gpadmin-[INFO]:-Checking new segment hosts, Completed
20151111:10:04:01:002381 gpinitsystem:ubuntu:gpadmin-[INFO]:-Building the Master instance database, please wait...
20151111:10:04:09:gpinitsystem:ubuntu:gpadmin-[FATAL]:- Command /usr/local/pgsql/bin/initdb -E UNICODE -D /home/gpadmin/projects/gpdb_working/gpdb/gpAux/gpdemo/datadirs/qddir/demoDataDir-1 --locale=en_US.utf8        --max_connections=25 --shared_buffers=128000kB --is_filerep_mirrored=no --backend_output=/home/gpadmin/projects/gpdb_working/gpdb/gpAux/gpdemo/datadirs/qddir/demoDataDir-1.initdb failed with error status 1, see log file /home/gpadmin/gpAdminLogs/gpinitsystem_20151111.log for more detail Script Exiting!
========================================
gpinitsystem returned: 2
========================================

gpinitsystem_20151111.log:
20151111:10:04:01:002381 gpinitsystem:ubuntu:gpadmin-[INFO]:-Building the Master instance database, please wait...
20151111:10:04:01:002381 gpinitsystem:ubuntu:gpadmin-[INFO]:-Initializing Master Postgres instance /home/gpadmin/projects/gpdb_working/gpdb/gpAux/gpdemo/datadirs/qddir/demoDataDir-1
20151111:10:04:01:002381 gpinitsystem:ubuntu:gpadmin-[INFO]:-Commencing local /usr/local/pgsql/bin/initdb -E UNICODE -D /home/gpadmin/projects/gpdb_working/gpdb/gpAux/gpdemo/datadirs/qddir/demoDataDir-1 --locale=en_US.utf8        --max_connections=25 --shared_buffers=128000kB --is_filerep_mirrored=no --backend_output=/home/gpadmin/projects/gpdb_working/gpdb/gpAux/gpdemo/datadirs/qddir/demoDataDir-1.initdb
The files belonging to this database system will be owned by user "gpadmin".
This user must also own the server process.

The database cluster will be initialized with locale en_US.utf8.

creating directory /home/gpadmin/projects/gpdb_working/gpdb/gpAux/gpdemo/datadirs/qddir/demoDataDir-1 ... ok
creating subdirectories ... ok
selecting default max_connections ... initdb: error 35584 from: "/usr/local/pgsql/bin/postgres" --boot -x0 -F -c max_connections=25 -c shared_buffers=4000 -c max_fsm_pages=200000 < "/dev/null" > "/home/gpadmin/projects/gpdb_working/gpdb/gpAux/gpdemo/datadirs/qddir/demoDataDir-1.initdb" 2>&1
initdb: removing data directory "/home/gpadmin/projects/gpdb_working/gpdb/gpAux/gpdemo/datadirs/qddir/demoDataDir-1"
2015-11-11 02:04:02.026597 GMT,,,p7131,th-1219598592,,,,0,,,seg-1,,,,,"WARNING","01000","""fsync"": can not be set by the user and will be ignored.",,,,,,,,"set_config_option","guc.c",9622,
Segmentation fault (core dumped)
20151111:10:04:09:002381 gpinitsystem:ubuntu:gpadmin-[INFO]:-Start Function ERROR_EXIT
20151111:10:04:09:gpinitsystem:ubuntu:gpadmin-[FATAL]:- Command /usr/local/pgsql/bin/initdb -E UNICODE -D /home/gpadmin/projects/gpdb_working/gpdb/gpAux/gpdemo/datadirs/qddir/demoDataDir-1 --locale=en_US.utf8        --max_connections=25 --shared_buffers=128000kB --is_filerep_mirrored=no --backend_output=/home/gpadmin/projects/gpdb_working/gpdb/gpAux/gpdemo/datadirs/qddir/demoDataDir-1.initdb failed with error status 1, see log file /home/gpadmin/gpAdminLogs/gpinitsystem_20151111.log for more detail Script Exiting!

gdb postgres core
![gdb](https://cloud.githubusercontent.com/assets/14181034/11083580/b82074dc-886b-11e5-94ab-f6f08f9d39f0.jpg)

Did you ever see this on 32 bit linux?Seems like the CMPXCHG access illegal address

**Comment by robertmu** [comment]
It's the gcc -O3 cause this problem. 
GPDB default use gcc -O3 option to compile,make below assembly instruction retrieve incorrect value(from stack) that used by cmpxchg

        __asm__ __volatile__
                (
                "MOVL 0x8(%%ebp), %%edx                                                 \n\t"
                "MOVL 0xc(%%ebp), %%eax                                                 \n\t"
                "MOVL 0x10(%%ebp), %%ecx                                                \n\t"
                "LOCK CMPXCHG %%ecx, (%%edx)                    \n\t"
                "SETE %0                                                                \n\t"
                :"=g"(res)
                :
                :"%eax","%ecx","%edx"
                );
 
I'll send a pull request to fix this

**Comment by hlinnaka** [comment]
On 11/11/2015 09:58 AM, Robert Mu wrote:
> It's the gcc -O3 cause this problem.
> GPDB default use gcc -O3 option to compile,make below assembly instruction retrieve incorrect value(from stack) that used by cmpxchg
>
>          __asm__ __volatile__
>                  (
>                  "MOVL 0x8(%%ebp), %%edx                                                 \n\t"
>                  "MOVL 0xc(%%ebp), %%eax                                                 \n\t"
>                  "MOVL 0x10(%%ebp), %%ecx                                                \n\t"
>                  "LOCK CMPXCHG %%ecx, (%%edx)                    \n\t"
>                  "SETE %0                                                                \n\t"
>                  :"=g"(res)
>                  :
>                  :"%eax","%ecx","%edx"
>                  );

A-ha! I saw this earlier on a 32-bit VM, but I was trying to debug 
something else and forgot all about it.

> I'll send a pull request to fix this

Thanks! I think we should remove the gpdb-added atomic operations, and 
replace them with the atomic operation support from upstream. The 
upstream ones have been tested on a wide range of platforms, and we'd 
want to switch over to them eventually anyway, when we merge with later 
PostgreSQL releases.

- Heikki

**Comment by robertmu** [comment]
So,Should i fix this temporarily or just wait gpdb merge from upstream?

**Comment by hlinnaka** [comment]
On 11/11/2015 10:24 AM, Robert Mu wrote:
> So,Should i fix this temporarily or just wait gpdb merge from upstream?

The atomic operations were added in PostgreSQL 9.4 IIRC, so if we wait 
for the whole of PostgreSQL 9.4 to merged, it'll be a long wait. I think 
we need to backport just the atomic operations from 9.4 now, to get this 
fixed. Do you want to give that a shot? Or I can do it, it shouldn't 
take long.

- Heikki

**Comment by robertmu** [comment]
Of course,I'll do it

**Comment by robertmu** [comment]
@hlinnaka 
I can't find atomic operations in PostgreSQL 9.4 branch. It's in REL9_5_STABLE branch.
Should I backport atomic operations from REL9_5_STABLE branch?

**Comment by hlinnaka** [comment]
On 11/12/2015 05:51 AM, Robert Mu wrote:
> I can't find atomic operations in PostgreSQL 9.4 branch. It's in REL9_5_STABLE branch.
> Should I backport atomic operations from REL9_5_STABLE branch?

Ah yeah, take them from 9.5. I remembered wrongly that they were added 
in 9.4 already. Thanks!

- Heikki

**Comment by robertmu** [comment]
@hlinnaka 
Please review code,thanks

**Comment by davecramer** [comment]
I've seen lots of these mysterious segfaults as well.

Thanks!

Dave Cramer

**Comment by hlinnaka** [comment]
Pushed, thanks for the report and the fix!
