### ISSUE TITLE
could not use gpcopy on GP 4.3.X

### ISSUE THREAD

**Issue by zhangxin0112** [greenplum-db/gpdb#7444]
### Greenplum version or build
4.3.0.0 build 3
### OS version and uname -a
Centos 6 
### Expected behavior
Use gpcopy on GP 4.3.0.0 build 3
### Actual behavior
Can not use gpcopy on GP 4.3.0.0 build 3
### Step to reproduce the behavior
1. Deploy an old GP Cluster 4.3.0.0 build 3 ---- node10
2. Deploy an new  GP Cluster 5.18.0 ---- node11
3. node11# scp /usr/local/greenplum-db/bin/gpcopy gpadmin@node10:/usr/local/greenplum-db/bin/
4. node10# gpcopy --source-host node10 --source-port 5432 --source-user gpadmin --dest-host node11 --dest-port 5432 --dest-user gpadmin --full --drop --truncate-source-after --analyze  --validate count
5. Error msg: 
   20190412:16:27:50 gpcopy:gpadmin:node10:032307-[ERROR]:-Caught an error: GPDB version 4.3.0.0 build 3 is not supported. Please upgrade to GPDB 4.3.20.0 or later.

**Comment by BrianPivotal** [comment]
You need to use gpcopy beyond 4.3.26.0. Thanks.




Best Regards,
Brian

**Comment by zhangxin0112** [comment]
Ok. 
Thanks.
