### ISSUE TITLE
gpadmin-[WARNING]:-could not query segment 2

### ISSUE THREAD

**Issue by chenfengli1985** [greenplum-db/gpdb#7454]
i am install greenplum5.18 success ,but check status display down warings
gpadmin@sha-udb-10-24-XX-XX:~$ gpstate -e
20190415:14:18:31:051171 gpstate:sha-udb-10-24-CCC:gpadmin-[INFO]:-Starting gpstate with args: -e
20190415:14:18:31:051171 gpstate:sha-udb-10-24-CCC:gpadmin-[INFO]:-local Greenplum Version: 'postgres (Greenplum Database) 6.0.0-alpha.0+dev.16251.g1f58c17 build dev'
20190415:14:18:31:051171 gpstate:sha-udb-10-24-CCC:gpadmin-[INFO]:-master Greenplum Version: 'PostgreSQL 9.4.20 (Greenplum Database 6.0.0-alpha.0+dev.16251.g1f58c17 build dev) on x86_64-unknown-linux-gnu, compiled by gcc (Ubuntu 4.8.5-4ubuntu8~14.04.2) 4.8.5, 64-bit compiled on Apr 11 2019 08:12:59'
20190415:14:18:31:051171 gpstate:sha-udb-10-24-CCC:gpadmin-[INFO]:-Obtaining Segment details from master...
20190415:14:18:31:051171 gpstate:sha-udb-10-24-CCC:gpadmin-[INFO]:-Gathering data from segments...
.                                              CCC
20190415:14:18:33:051171 gpstate:sha-udb-10-24-CCC:gpadmin-[WARNING]:-could not query segment 2 (sha-udb-10-24-CCC.qq.com:40000)
20190415:14:18:33:051171 gpstate:sha-udb-10-24-CCC:gpadmin-[WARNING]:-could not query segment 3 (sha-udb-10-24-CCC.qq.com:40001)
20190415:14:18:33:051171 gpstate:sha-udb-10-24-CCC:gpadmin-[WARNING]:-could not query segment 4 (sha-udb-10-24-CCC.qq.com:40002)
20190415:14:18:33:051171 gpstate:sha-udb-10-24-CCC:gpadmin-[WARNING]:-could not query segment 5 (sha-udb-10-24-CCC.qq.com:40000)
20190415:14:18:33:051171 gpstate:sha-udb-10-24-CCC:gpadmin-[WARNING]:-could not query segment 6 (sha-udb-10-24-CCC.qq.com:40001)
20190415:14:18:33:051171 gpstate:sha-udb-10-24-CCC:gpadmin-[WARNING]:-could not query segment 7 (sha-udb-10-24-CCC.qq.com:40002)
20190415:14:18:33:051171 gpstate:sha-udb-10-24-CCC:gpadmin-[WARNING]:-could not query segment 8 (sha-udb-10-24-CCC.qq.com:40000)
20190415:14:18:33:051171 gpstate:sha-udb-10-24-CCC:gpadmin-[WARNING]:-could not query segment 9 (sha-udb-10-24-CCC.qq.com:40001)
20190415:14:18:33:051171 gpstate:sha-udb-10-24-CCC:gpadmin-[WARNING]:-could not query segment 10 (sha-udb-10-24-CCC.qq.com:40002)

**Comment by berlin-ab** [comment]
Would you describe how you installed GPDB? Also, what other steps have you done to ensure the cluster is up and running? What other log information do you have for cluster startup?

**Comment by hlinnaka** [comment]
Looks like the trail has gone cold on this, closing.
