### ISSUE TITLE
gpinitsystem failed with error "no route to host"

### ISSUE THREAD

**Issue by duj4** [greenplum-db/gpdb#747]
Hi, I was trying to deploy a 2-seg GP farm with mirror mode on, gpinitsystem failed and 1 seg failed to get up. 
From the log files, i could see that 
"socket.error: [Errno 113] No route to host" 
"20160512:14:38:51:018079 gpcreateseg.sh:dw-greenplum-1:gpadmin-[FATAL]:- Command export GPHOME=/opt/greenplum/greenplum-db-4.3.8.1/; . /opt/greenplum/greenplum-db-4.3.8.1//greenplum_path.sh; /opt/greenplum/greenplum-db-4.3.8.1//bin/lib/pysync.py -x pg_log -x postgresql.conf -x postmaster.pid /data/primary/gpseg1 \[sdw1\]:/data/mirror/gpseg1 on sdw2 failed with error status 1" 
I tried the scp manually between the directories and it worked. 
I worked on the RHEL 7.2 in the VMware workstation, bridged mode.
Then I turned off the mirror mode, everything looks good...

So is there something wrong on my config? (i have the log attached, please remove the ".txt" if you'd like to check it out)
[gpinitsystem_20160512.log.txt](https://github.com/greenplum-db/gpdb/files/260906/gpinitsystem_20160512.log.txt)

**Comment by asimrp** [comment]
Hi @duj4, apologies for not responding to your issue for so long.  I looked through the attached gpinitsystem output.  It may be possible that your configuration is incorrect.  But we can certainly enhance the error message reported by `pysync.py` to include IP address of the host to aid in debugging.  @jmcatamney, do you agree?

```
20160512:14:38:51:017911 gpcreateseg.sh:dw-greenplum-1:gpadmin-[INFO][0]:-Completed Update /data/mirror/gpseg0/postgresql.conf file
Killed by signal 1.
Traceback (most recent call last):
  File "/opt/greenplum/greenplum-db-4.3.8.1//bin/lib/pysync.py", line 669, in <module>
    sys.exit(LocalPysync(sys.argv, progressTimestamp=True).run())
  File "/opt/greenplum/greenplum-db-4.3.8.1//bin/lib/pysync.py", line 647, in run
    code = self.work()
  File "/opt/greenplum/greenplum-db-4.3.8.1//bin/lib/pysync.py", line 611, in work
    self.socket.connect(self.connectAddress)
  File "<string>", line 1, in connect
socket.error: [Errno 113] No route to host
20160512:14:38:51:017911 gpcreateseg.sh:dw-greenplum-1:gpadmin-[INFO][0]:-Completed Update /data/mirror/gpseg0/postgresql.conf file
20160512:14:38:51:018079 gpcreateseg.sh:dw-greenplum-1:gpadmin-[FATAL]:- Command export GPHOME=/opt/greenplum/greenplum-db-4.3.8.1/; . /opt/greenplum/greenplum-db-4.3.8.1//greenplum_path.sh; /opt/greenplum/greenplum-db-4.3.8.1//bin/lib/pysync.py -x pg_log -x postgresql.conf -x postmaster.pid /data/primary/gpseg1 \[sdw1\]:/data/mirror/gpseg1 on sdw2 failed with error status 1
20160512:14:38:51:018079 gpcreateseg.sh:dw-greenplum-1:gpadmin-[INFO]:-End Function RUN_COMMAND_REMOTE
20160512:14:38:51:017911 gpcreateseg.sh:dw-greenplum-1:gpadmin-[INFO]:-Start Function ED_PG_CONF
20160512:14:38:51:018079 gpcreateseg.sh:dw-greenplum-1:gpadmin-[FATAL][1]:-Failed remote copy of segment data directory from sdw2 to sdw1
```

@duj4 can you manually ssh/scp from sdw2 to sdw1?

**Comment by jiangxiluning** [comment]
did you disable firewalld service?
```shell
systemctl stop firewalld
systemctl disable firewalls
```

**Comment by ascherbaum-pivotal** [comment]
Is this issue still present?
