### ISSUE TITLE
[Greenplum JDBC Driver]This driver does not support the 'getNetworkTimeout' and 'setNetworkTimeout' methods.)

### ISSUE THREAD

**Issue by hhbbz** [greenplum-db/gpdb#7496]
### Greenplum version or build
5.10.2，my Greenplum JDBC Driver version also 5.10.2
### OS version and uname -a
Red Hat 4.8.5-28

### Expected behavior
dont shutdown the HikariPool when i use Greenplum JDBC Driver to reconnected
### Actual behavior
Occasionally throwing an error:

> HikariPool-2 - Driver does not support get/set network timeout for connections. ([Pivotal][Greenplum JDBC Driver]This driver does not support the 'getNetworkTimeout' and 'setNetworkTimeout' methods.)

### Step to reproduce the behavior
this is my connect-config
```java
            HikariDataSource dataSource = new HikariDataSource();
            JdbcTemplate jdbcTemplate = new JdbcTemplate();
            dataSource.setDriverClassName("com.pivotal.jdbc.GreenplumDriver");
            dataSource.setJdbcUrl(url);
            dataSource.setUsername(name);
            dataSource.setPassword(pwd);
            jdbcTemplate = new JdbcTemplate(this.dataSource);
```

**Comment by Eulerizeit** [comment]
Greenplum doesn't have a JDBC driver per say. You need to reach out to whoever is supporting your cluster or the JDBC driver developers.

**Comment by hhbbz** [comment]
> Greenplum doesn't have a JDBC driver per say. You need to reach out to whoever is supporting your cluster or the JDBC driver developers.

I was download the Greenplum JDBC driver in Official website，
https://network.pivotal.io/products/pivotal-gpdb/#/releases/338232/file_groups/1546
Doesn't that mean support for JDBC drivers?

**Comment by Eulerizeit** [comment]
We absolutely support JDBC drivers. Pivotal distributes what you
downloaded, please reach out to Pivotal support for help with that it isn't
a Greenplum product that we support in this repo.

-- Rob
