### ISSUE TITLE
Foreign table has relcache reference leaks with ORCA

### ISSUE THREAD

**Issue by adam8157** [greenplum-db/gpdb#7508]
### Expected behavior
No Warnings

### Actual behavior
WARNING:  relcache reference leak: relation "text_csv" not closed

### Step to reproduce the behavior
make install -C contrib/file_fdw/
make installcheck -C contrib/file_fdw/

A normal  `SELECT * FROM foreign_table` triggers this too. `optimizer=off` is good.

**Comment by berlin-ab** [comment]
Which version of Greenplum are you using? Would you please add the version label when you get a chance?

Also, If you could, would you check to see if the same problem exists in other major versions?

**Comment by adam8157** [comment]
@berlin-ab Checkout #7528, the latest master has that issue, 6X_STABLE probably also.

**Comment by vraghavan78** [comment]
@adam8157 thanks for reporting, please review PR-7595

**Comment by adam8157** [comment]
Cool, #7528 PR pipeline passed.
