### ISSUE TITLE
Greenplum server processes crashed while running regression suite

### ISSUE THREAD

**Issue by imshubhangi** [greenplum-db/gpdb#7512]
### Greenplum version or build
5.5 dev build

### OS version and uname -a
Linux ip-172-30-0-73.ec2.internal 3.10.0-327.10.1.el7.x86_64 #1 SMP Tue Feb 16 17:03:50 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

### Details
Five different Greenplum server processes crashed. 
`~]$ find    gpdb/gpAux/  -name "core*" | grep -v site
gpdb/gpAux/gpdemo/datadirs/dbfast1/demoDataDir0/core.22295
gpdb/gpAux/gpdemo/datadirs/dbfast1/demoDataDir0/core.31703
gpdb/gpAux/gpdemo/datadirs/dbfast1/demoDataDir0/core.31811
gpdb/gpAux/gpdemo/datadirs/dbfast2/demoDataDir1/core.22289
gpdb/gpAux/gpdemo/datadirs/dbfast3/demoDataDir2/core.22283`

`~]$ find    gpdb/gpAux/  -name "core*" | grep -v site | xargs file $1
gpdb/gpAux/gpdemo/datadirs/dbfast1/demoDataDir0/core.22295: ELF 64-bit LSB core file x86-64, version 1 (SYSV), SVR4-style, from 'postgres: 25432, checkpointer process'
gpdb/gpAux/gpdemo/datadirs/dbfast1/demoDataDir0/core.31703: ELF 64-bit LSB core file x86-64, version 1 (SYSV), SVR4-style, from '/usr/local/gpdb/bin/postgres -D /home/centos/gpdb/gpAux/gpdemo/datadirs/dbfast1'
gpdb/gpAux/gpdemo/datadirs/dbfast1/demoDataDir0/core.31811: ELF 64-bit LSB core file x86-64, version 1 (SYSV), SVR4-style, from '/usr/local/gpdb/bin/postgres -D /home/centos/gpdb/gpAux/gpdemo/datadirs/dbfast1'
gpdb/gpAux/gpdemo/datadirs/dbfast2/demoDataDir1/core.22289: ELF 64-bit LSB core file x86-64, version 1 (SYSV), SVR4-style, from 'postgres: 25433, checkpointer process'
gpdb/gpAux/gpdemo/datadirs/dbfast3/demoDataDir2/core.22283: ELF 64-bit LSB core file x86-64, version 1 (SYSV), SVR4-style, from 'postgres: 25434, checkpointer process'`

**Comment by imshubhangi** [comment]
` ~]$ gdb /usr/local/gpdb/bin/postgres gpdb/gpAux/gpdemo/datadirs/dbfast1/demoDataDir0/core.31703
...
Core was generated by `/usr/local/gpdb/bin/postgres -D /home/centos/gpdb/gpAux/gpdemo/datadirs/dbfast1'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000000000956570 in FaultInjector_InjectFaultNameIfSet.part.2 ()
Missing separate debuginfos, use: debuginfo-install bzip2-libs-1.0.6-13.el7.x86_64 libxml2-2.9.1-6.el7_2.3.x86_64 xerces-c-3.1.1-8.el7_2.x86_64 xz-libs-5.2.2-1.el7.x86_64
(gdb) bt
#0  0x0000000000956570 in FaultInjector_InjectFaultNameIfSet.part.2 ()
#1  0x00000000007b2b97 in ProcessStartupPacket ()
#2  0x00000000007b3a8a in ServerLoop ()
#3  0x00000000007b649a in PostmasterMain ()
#4  0x00000000004c6819 in main ()
(gdb)`

Unfortunately core files can not be provided.

**Comment by danielgustafsson** [comment]
This is caused by the faultinjector test framework which can induce a segfault into a running Greenplum backend to test how it behaves within a crash. This is expected behavior.
