### ISSUE TITLE
How does UPDATE work when update from many tuples

### ISSUE THREAD

**Issue by Dontpushme** [greenplum-db/gpdb#7513]
### Greenplum version or build
6X_STABLE
### OS version and uname -a
centos 7.3
### Expected behavior
I don't know an error maybe? it gets error when optimizer=on
### Actual behavior
update using the first tuple returned
### Step to reproduce the behavior
set optimizer=off;
drop table if exists t1;
create table t1 (i int, j int );
drop table if exists t2;
create table t2 (i int, j int );
insert into  t1 values (1,10);
insert  into t2 values (1,11),(1,12);
insert into t1 select * from t2 limit 1;
update t1 set j = t2.j from t2 where t1.i = t2.i ;
select * from t1;
reset optimizer;

In this case, it shows "1,11", but why? did the scan met tuple "1,12"?
what happens if the two (or more) tuples exist in different QE?

**Comment by berlin-ab** [comment]
Would you please post the error you see after running this with `set optimizer to on`?

**Comment by kainwen** [comment]
> Would you please post the error you see after running this with `set optimizer to on`?

@berlin-ab 
ORCA always generate split-update plan for any update on randomly | hash distributed tables.

So the error message is thrown here: https://github.com/greenplum-db/gpdb/blob/master/src/backend/executor/nodeModifyTable.c#L809

**Comment by d** [comment]
> In this case, it shows "1,11", but why? did the scan met tuple "1,12"?

Yes the executor has actually seen `(1,12)`, but the insertion will silently skip it because it has already updated `(1,10)` to `(1,11)`.

> what happens if the two (or more) tuples exist in different QE?
The update will probably increase the number of rows in the table -- IOW a wrong result. Do you want to try constructing such an example?

**Comment by d** [comment]
We appreciate your interest in Greenplum Database @Dontpushme, though this is not the right venue for discussions of this sort. Please move over to the [dev mailing list](https://groups.google.com/a/greenplum.org/forum/#!forum/gpdb-dev) for such discussions in the future.
