### ISSUE TITLE
GPFdist Erorr 'Segmentation Fault' when selecting from external table

### ISSUE THREAD

**Issue by VinnyPembe** [greenplum-db/gpdb#7524]
OS Version: CentOS 7.6 / Linux 3.10.0-957.10.1.el7.x86_64
Greenplum versions I've used to replicate issue: 5.18, 6 beta, & 7 beta
Compile command used:
`./configure --prefix=/usr/local/gpdb --with-perl --with-python --with-libxml --with-gssapi --with-includes=/usr/local/gpdb/include --with-libs=/usr/local/gpdb/lib --disable-orca`

I've installed a new server, and re-installed it many different ways, to try to remove this issue. Simply, I configure GPDB, initialise the database, and create a very simple, one column, table and external table. I can manually insert data into the table and select from it, etc. I create a file, start gpfdist with,
`gpfdist -d /home/gpadmin/test/ -p 8080 -l /home/gpadmin/greenplum/logs/gpfdist_log 2>&1 &`

and then try selecting from the external table, which results in the following error from gpfdist:
`[1]+  Segmentation fault      gpfdist -d /home/gpadmin/test -p 8080 -l /home/gpadmin/greenplum/logs/gpfdist_log 2>&1`

I did some painful work to get the following report from GDB:
`Core was generated by 'gpfdist -d /home/gpadmin/test -p 8080 -l /home/gpadmin/greenplum/logs/gpfdist_log'.
Program terminated with signal 11, Segmentation fault.
#0  0x00007f4f2c07bdff in ?? ()`

but I have no idea what this means, unfortunately.

Any help or assistance with this is appreciated, as I've scoured the internet and tried for days to solve this issue, by the simplest of things as ensuring packages are up to date, to removing GPORCA from the installation, and nothing has helped so far.

I can, just to note, install the Pivotal 5.18 equivalent version alongside the GitHub 5.18 version, on the same server, running at the same time, and GPFDist works for it, just not the GitHub version, so I'm very confident my network and operating system are fine, but what the issue is I have no idea.

Thank you.

**Comment by asimrp** [comment]
@VinnyPembe does `gpfdist` report anything on the console?  Note that you are starting `gpfdist` in the background.  Any console messages emitted by `gpfdist` may be intermixed with other commands run on the same shell.  Do you see anything in the log file specified as `-l` option in your `gpfdist` command line?

**Comment by pf-qiu** [comment]
Which version of libevent are you using? I think it only works with 1.4

**Comment by VinnyPembe** [comment]
Thank you both for a response.
@asimrp no, `gpfdist` does not report anything, sadly, as the log file is empty (and so is command line if I just run it on a seperate terminal). The error I posted above is the only message that is returned.

@pf-qiu I THINK I am using 2.2.0 as the below suggests (not sure how to check so this might be wrong):
`# ldconfig -p | grep event
libevent_pthreads.so.2.2.0 (libc6,x86-64) => /usr/local/lib/libevent_pthreads.so.2.2.0
libevent_pthreads.so (libc6,x86-64) => /usr/local/lib/libevent_pthreads.so
libevent_openssl.so.2.2.0 (libc6,x86-64) => /usr/local/lib/libevent_openssl.so.2.2.0
libevent_openssl.so (libc6,x86-64) => /usr/local/lib/libevent_openssl.so
libevent_extra.so.2.2.0 (libc6,x86-64) => /usr/local/lib/libevent_extra.so.2.2.0
libevent_extra.so (libc6,x86-64) => /usr/local/lib/libevent_extra.so
libevent_core.so.2.2.0 (libc6,x86-64) => /usr/local/lib/libevent_core.so.2.2.0
libevent_core.so (libc6,x86-64) => /usr/local/lib/libevent_core.so
libevent.so.2.2.0 (libc6,x86-64) => /usr/local/lib/libevent.so.2.2.0
libevent.so (libc6,x86-64) => /usr/local/lib/libevent.so`

I've just downloaded the 1.4.15 version from the GitHub releases for Libevent and will try a full system re-install now. I'll reply back as soon as I have done it to let you know if it works.

**Comment by VinnyPembe** [comment]
Ah ha! Finally! Installing libevent 1.4.15, instead of the latest (2.2.0), has solved my issue. Thank you for your assistance.

Would it not be worth putting some form of check on compiling GPDB whether or not the correct version of libevent is installed? It already checks for the correct version of GPORCA, so perhaps something similar would help others resolve such an issue in future.

**Comment by pf-qiu** [comment]
Good to hear that it resolves your problem.
One of my PR is indirectly related to your issue: https://github.com/greenplum-db/gpdb/pull/7514
I've encountered similar issue recently, but on Windows instead. I figured it out that libevent has changed some assumptions of its API.
If you patch gpfdist.c with the changes in that PR, you will be able to work with latest libevent(2.*).
