### ISSUE TITLE
Switch `libcurl4` flavors for Ubuntu 18.04

### ISSUE THREAD

**Issue by bradfordboyle** [greenplum-db/gpdb#7539]
It looks like our Ubuntu packages direct users to install `libcurl4-gnutls-dev` instead of `libcurl4-openssl-dev`:

- https://github.com/greenplum-db/gpdb/blob/4073a6ffe87a913a226daf7978c69786375859ab/README.ubuntu.bash#L18
- https://github.com/greenplum-db/gpdb/blob/a7a2a60ff101798e2c0d1d8050d1d864d039f3a5/concourse/server_pipeline/docker/Dockerfile#L31
- https://github.com/greenplum-db/gpdb/blob/e0004aa65c77894f88113dae37f04016df746881/src/tools/docker/ubuntu16/Dockerfile#L24

GPDB is compiled against OpenSSL and not GnuTLS. We should probably update required packages to use `libcurl4-openssl-dev`.

**Comment by d** [comment]
> GPDB is compiled against OpenSSL and not GnuTLS. We should probably update required packages to use `libcurl4-openssl-dev`.

When a program links against the GnuTLS-flavored `libcurl`, it dynamically links to both GnuTLS and libcurl. Note that there is only one set of API that's exposed here: the `libcurl` API. The fact that TLS is handled (in curl) through GnuTLS shouldn't be a concern for an application (gpfdist or PXF I'd assume), unless we started relying on undocumented behaviors that are specific to OpenSSL (behind the curl API)

**Comment by danielgustafsson** [comment]
The TLS API in libcurl (vtls) is constant and stable, but the TLS backend implementations have small differences in how they do things and what they support (only OpenSSL support the concept of Engines for example, and only 3 of the backends support PKCS#12 etc), so I wouldn't call them identical.

It's true that it's unlikely that using a different TLS backend would expose bugs or issues, but there is also no point in doing so when keeping them the same is easy enough to do as OpenSSL is the baseline.

**Comment by lij55** [comment]
I tested in on Ubuntu 22.04.
The build process will report following `pkg-config` error if there is no libcurl installed. 
```
configure:14061: checking for curl-config
configure:14092: result: no
configure:14142: error: Library requirements (curl) not met.
```
By `apt install libcurl-dev`, it shows that we need to explicit package name:
```
Package libcurl-dev is a virtual package provided by:
  libcurl4-openssl-dev 7.68.0-1ubuntu2.7
  libcurl4-nss-dev 7.68.0-1ubuntu2.7
  libcurl4-gnutls-dev 7.68.0-1ubuntu2.7
You should explicitly select one to install.
```
After `apt install libcurl4-openssl-dev`, I can build postgres successfully.
However,  it is linked to `libcurl-gnutls.so.4`
```
root@aea853a7a0bb:/gpdb/src/backend# ldd postgres  | grep curl 
	libcurl.so.4 => /lib/x86_64-linux-gnu/libcurl.so.4 (0x00007f9b90e05000)
	libcurl-gnutls.so.4 => /lib/x86_64-linux-gnu/libcurl-gnutls.so.4 (0x00007f9b9078d000)
```
By checking the library of postgres, it marked libcurl only instead of `libcurl-gnutls.so.4` or `libcurl4-openssl.xxx`
```
root@aea853a7a0bb:/gpdb/src/backend# readelf -d postgres 

Dynamic section at offset 0x12a6e40 contains 39 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libpthread.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libxerces-c-3.2.so]
 0x0000000000000001 (NEEDED)             Shared library: [libbz2.so.1.0]
 0x0000000000000001 (NEEDED)             Shared library: [librt.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libz.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libdl.so.2]
 0x0000000000000001 (NEEDED)             Shared library: [libcurl.so.4]
 0x0000000000000001 (NEEDED)             Shared library: [libzstd.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libstdc++.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libgcc_s.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x000000000000001d (RUNPATH)            Library runpath: [/usr/local/gpdb/lib]

```

The reason is that Greenplum/Postgres only depends on libcurl, no matter which underlying ssl libraries libcurl depends on. `libcurl4-gnutls-dev` and `libcurl4-openssl-dev` provides the same interface (ABI and API) and event the same implementation. Compiling Greenplum with any of them should be same. 
It will be totally OK if building with libcurl4-gnutls and linked with libcurl4-openssl, or vice versa. It is also why it is a virtual package.
