### ISSUE TITLE
unexpected permission denied error when creating schema

### ISSUE THREAD

**Issue by pengzhout** [greenplum-db/gpdb#7541]
### Greenplum version or build
latest master 

### Expected behavior
CREATE ROLE "current_user1";
CREATE SCHEMA newschema4 AUTHORIZATION "current_user1";
### Actual behavior
CREATE SCHEMA newschema4 AUTHORIZATION "current_user1";
ERROR:  permission denied for database gpadmin  (seg0 10.153.101.106:25432 pid=171526)

**Comment by pengzhout** [comment]
https://github.com/greenplum-db/gpdb/pull/7553 is for this.

**Comment by hlinnaka** [comment]
PR #7553 was pushed to master. Can this be closed?

**Comment by pengzhout** [comment]
Yes, close it.
