### ISSUE TITLE
ALTER USER ALL report an error

### ISSUE THREAD

**Issue by pengzhout** [greenplum-db/gpdb#7542]
### Greenplum version or build
latest master

### Expected behavior
 ALTER USER ALL SET application_name to 'SLAP'
### Actual behavior
ERROR:  ALTER without DATABASE or ROLE (pg_db_role_setting.c:237)

**Comment by pengzhout** [comment]
PR https://github.com/greenplum-db/gpdb/pull/7552 is for this.

**Comment by hlinnaka** [comment]
PR #7552 was merged, I believe we can close this.
