### ISSUE TITLE
Incorrect timezone conversion for Moscow

### ISSUE THREAD

**Issue by magi345** [greenplum-db/gpdb#7543]
In GPDB5, specific timezone abbrev is giving wrong result.
"MSK" is for "Europe/Moscow", but following statements are giving different result.
"Europe/Moscow" is correct, but "MSK" is always in UTC.
```
gpadmin=# SELECT CURRENT_TIMESTAMP AT TIME ZONE 'MSK';
          timezone
----------------------------
 2019-04-25 05:37:56.366521    <<<<<<< Wrong

gpadmin=# SELECT CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow';
          timezone
----------------------------
 2019-04-25 08:37:58.824073

gpadmin=# SELECT CURRENT_TIMESTAMP;
              now
-------------------------------
 2019-04-25 08:38:01.456155+03

gpadmin=# show timezone;
   TimeZone
---------------
 Europe/Moscow

gpadmin=# \! date
Thu Apr 25 08:38:45 MSK 2019
```
I verified with GPDB6 and PostgreSQL 11, the 'MSK' can give the correct result.
So maybe a gpdb 5 bug.

**Comment by magi345** [comment]
The workaround was to modify the $GPHOME/share/postgresql/timezonesets/Default file:
Change
```
MSK     Europe/Moscow  # Moscow Time
```
to
```
MSK     10800    #     (Europe/Moscow)
```

**Comment by tylarb** [comment]
Looks like this has been resolved. Closing
