### ISSUE TITLE
Vagrant VM - libffi-devel package needed

### ISSUE THREAD

**Issue by csylvester-pivotal** [greenplum-db/gpdb#756]
In the Vagant environment setup, Greenplum does not run correctly because of missing paramiko libraries. The libraries are not compiled during install because of a missing include file (ffi.h).
This file is available in the libffi-devel package. 

The following change corrects the problem:
File:                `gpdb-master/vagrant/centos/vagrant-setup.sh`
Add this line:  `sudo yum -y install libffi-devel`

**Comment by xinzweb** [comment]
@csylvester-pivotal would you please create a PR for the fix? Thanks a lot.

**Comment by danielgustafsson** [comment]
This dependency has been pushed to the Vagrantfiles, closing.
