### ISSUE TITLE
could not find array type for data type integer[]

### ISSUE THREAD

**Issue by pengzhout** [greenplum-db/gpdb#7562]
### Greenplum version or build
latest master

### Expected behavior
```
gpadmin=# select array_agg('{2}'::int[]) from generate_series(1,2);
 array_agg
-----------
 {{2},{2}}
(1 row)
```
### Actual behavior
gpadmin=# select array_agg('{2}'::int[]) from generate_series(1,2);
ERROR:  could not find array type for data type integer[]

**Comment by adam8157** [comment]
Checkout src/include/catalog/pg_type.h, INT4ARRAYOID has no valid `typarray` value.

Which version of Greenplum returns the expected result?

**Comment by melanieplageman** [comment]
Accepting arrays as input to `array_agg` is a feature not supported until Postgres 9.5 -- I think in this commit bac27394a1c69c20ec904729c593e59485c75c69

I'm assuming this is not considered a bug, so should I close this issue? @pengzhout

**Comment by d** [comment]
This is expected behavior / known limit of Postgres 9.4

In Postgres 9.5, this was enhanced in commit bac27394a1c where `array_agg` got an overload on array inputs.

**Comment by d** [comment]
oops @melanieplageman I closed it, sorry
