### ISSUE TITLE
Master pipelines differ in setup

### ISSUE THREAD

**Issue by danielgustafsson** [greenplum-db/gpdb#7569]
The `gpdb_master` and `gpdb_master_without_asserts` pipelines are configured differently wrt how failures are handled. `gpdb_master` exits early on error while `gpdb_master_without_asserts` keep going.

I don't have strong opinions on which strategy we should employ (both have pros and cons), but we should be consistent.

**Comment by kainwen** [comment]
I find now https://prod.ci.gpdb.pivotal.io/teams/main/pipelines/gpdb_master_without_asserts/jobs/icw_planner_icproxy_rhel8/builds/132

withoutassert still finish all when error happens.
