### ISSUE TITLE
Resource queue priority not working on segment. 

### ISSUE THREAD

**Issue by yew011** [greenplum-db/gpdb#7644]
### Greenplum version or build

Greenplum 5.10.2, (tag: 5.10.2)

### OS version and uname -a

```
[root:/etc/systemd/system]# uname -a
Linux hostname 4.9.76 #1-NixOS SMP Wed Jan 10 08:29:55 UTC 2018 x86_64 GNU/Linux
```

### autoconf options used ( config.status --config )

```
[root gpdb]# ./config.status --config
'--with-openssl' '--with-python' '--enable-orca' '--prefix=/usr/local/greenplum-db-5.10.2' 'CC=gcc' 'LDFLAGS=-L/usr/local/greenplum-db-5.10.2/lib' 'CPPFLAGS=-I/usr/local/greenplum-db-5.10.2/include
```

### Installation information ( pg_config )

```
bash-4.2$ gpconfig -s gp_resqueue_priority
Values on all segments are consistent
GUC          : gp_resqueue_priority
Master  value: on
Segment value: on
bash-4.2$ gpconfig -s gp_resqueue_priority_sweeper_interval
Values on all segments are consistent
GUC          : gp_resqueue_priority_sweeper_interval
Master  value: 1000
Segment value: 1000
bash-4.2$ gpconfig -s gp_resqueue_priority_cpucores_per_segment
Values on all segments are consistent
GUC          : gp_resqueue_priority_cpucores_per_segment
Master  value: 1
Segment value: 1
```

### Expected behavior

- Created two resource queues as follow:
```
CREATE RESOURCE QUEUE rsq_high WITH (ACTIVE_STATEMENTS=32, PRIORITY=HIGH);
CREATE RESOURCE QUEUE rsq_low WITH (ACTIVE_STATEMENTS=32, PRIORITY=LOW);
```

- Assign the resource queues to two roles respectively, (none of the roles have superuser privilege)

- Runs same expensive queries from a large distributed table (12 segments) using each role at the same time.

- Expect the role on *rsq_high* to finish much sooner than the other one as the `gp_resqueue_priority_cpucores_per_segment` is set to 1 on segment.

### Actual behavior

`top` cpu usage observation shows two queries using the same amount of CPU.
And both queries finish at the same time (turn on `\timing`).

### Possible fix

Not sure if this has been fixed already, but I dig into the source code and realize that the `queueId` for segment process is never set correctly...   I end up implementing this small change to fix the issue...
```
diff --git a/src/backend/postmaster/backoff.c b/src/backend/postmaster/backoff.c
index e9e9441..345c34f 100644
--- a/src/backend/postmaster/backoff.c
+++ b/src/backend/postmaster/backoff.c
@@ -46,6 +46,7 @@
 #include "cdb/cdbdisp_query.h"
 #include "cdb/cdbdispatchresult.h"
 #include "libpq-fe.h"
+#include "utils/resscheduler.h"
 #include <unistd.h>

 #include <signal.h>
@@ -1484,6 +1485,7 @@ ResourceQueueGetPriorityWeight(Oid queueId)
        ListCell   *le = NULL;
        int                     weight = BackoffDefaultWeight();

+       queueId = queueId ? queueId : MyQueueId;
        if (queueId == InvalidOid)
                return weight;

```

**Comment by d** [comment]
For what it's worth, we don't throttle the CPU for resource queues...

**Comment by d** [comment]
Have you tried Greenplum 5 with [resource groups](https://gpdb.docs.pivotal.io/5210/main/index.html)?
