### ISSUE TITLE
vacuum a external table  causes GP crash

### ISSUE THREAD

**Issue by zhbp366** [greenplum-db/gpdb#7659]
### Greenplum version or build
PostgreSQL 9.4.20 (Greenplum Database 6.0.0-beta.1 build dev) on x86_64-unknown-linux-gnu, compiled by gcc (GCC) 6.3.1
### OS version and uname -a
centos 7.5
### Actual behavior
When executing the sql:
```SQL
vacuum gp_toolkit.__gp_log_master_ext;
```
 we have the following error message:
```
WARNING:  skipping "__gp_log_master_ext" --- cannot vacuum non-tables or special system tables
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
connection to server was lost
```
### Step to reproduce the behavior
```SQL
vacuum gp_toolkit.__gp_log_master_ext
```

**Comment by adam8157** [comment]
Fixed.
