### ISSUE TITLE
missing metrics_collector.so file 

### ISSUE THREAD

**Issue by compasses** [greenplum-db/gpdb#7676]
### Greenplum version or build
 PostgreSQL 8.3.23 (Greenplum Database 5.18.0+dev.63.gadc1e81 build dev) on x86_64-pc-linux-gnu, compiled by GCC gcc (Ubuntu 5.4.0-6ubuntu1~16.04.
10) 5.4.0 20160609, 64-bit compiled on May 14 2019 08:48:47

### OS version and uname -a
Linux jet 4.15.0-47-generic #50~16.04.1-Ubuntu SMP Fri Mar 15 16:06:21 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

### Step to reproduce the behavior
configure --with-perl --with-python --with-libxml --enable-gpperfmon CFLAGS='-O0 -g' --prefix=/home/gp/install

after make & make install, during install the gpcc, raise the error:
**Could not detect [metrics_collector] in shared_preload_libraries
Please add it to enable GPCC metrics collection**

but I cannot find the metrics_collector so file in libdir, the contrib source don't have it also.
Thansks

**Comment by compasses** [comment]
@d could you kindly tell me the reason?

**Comment by jimmyyih** [comment]
@compasses, I believe this was closed because the metrics collector and GPCC are not open source.
