### ISSUE TITLE
gp_relation_node (2) has more entries than pg_aoseg (0) for relation xxxxxxxxx (aosegfiles.c:2226)

### ISSUE THREAD

**Issue by corama** [greenplum-db/gpdb#7694]
### Greenplum version or build
The GP version is 5.1.0
### OS version and uname -a
uname -a
Linux odeon003.segment.bja.greenplum 3.10.0-514.el7.x86_64 #1 SMP Tue Nov 22 16:42:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

cat /etc/redhat-release
CentOS Linux release 7.3.1611 (Core)

### Installation information ( pg_config )
pg_config
BINDIR = /opt/greenplum/greenplum/bin
DOCDIR = /opt/greenplum/greenplum/doc/postgresql
HTMLDIR = /opt/greenplum/greenplum/doc/postgresql
INCLUDEDIR = /opt/greenplum/greenplum/include
PKGINCLUDEDIR = /opt/greenplum/greenplum/include/postgresql
INCLUDEDIR-SERVER = /opt/greenplum/greenplum/include/postgresql/server
LIBDIR = /opt/greenplum/greenplum/lib
PKGLIBDIR = /opt/greenplum/greenplum/lib/postgresql
LOCALEDIR = /opt/greenplum/greenplum/share/locale
MANDIR = /opt/greenplum/greenplum/man
SHAREDIR = /opt/greenplum/greenplum/share/postgresql
SYSCONFDIR = /opt/greenplum/greenplum/etc/postgresql
PGXS = /opt/greenplum/greenplum/lib/postgresql/pgxs/src/makefiles/pgxs.mk
CC = /opt/gcc-6.2.0/bin/gcc -m64
CPPFLAGS = -D_GNU_SOURCE -I/opt/greenplum/greenplum/include
CFLAGS = -m64 -O3 -fargument-noalias-global -fno-omit-frame-pointer -g -std=gnu99 -Wall -Wmissing-prototypes -Wpointer-arith -Wendif-labels -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fno-aggressive-loop-optimizations -Wno-unused-but-set-variable -Wno-address -I/opt/greenplum/greenplum/include
CFLAGS_SL = -fpic
LDFLAGS = -Wl,--as-needed -Wl,-rpath,'/usr/local/greenplum-db-devel/lib',--enable-new-dtags -L/opt/greenplum/greenplum/lib
LDFLAGS_SL =
LIBS = -lpgport -lgpopt -lnaucrates -lgpdbcost -lgpos -lxerces-c -lxml2 -lpam -lrt -lkrb5 -lcom_err -lgssapi_krb5 -lcrypt -ldl -lm -lrt -L/opt/greenplum/greenplum/lib
VERSION = PostgreSQL 8.3.23

### Expected behavior
When use gpcrondump to backup the GP db, something wrong happens, and the error log like : 'p_relation_node (2) has more entries than pg_aoseg (0) for relation xxxxxxxxxx (aosegfiles.c:2226)'
Also with stack trace information:
Stack trace:
1    0x94f37b postgres errstart (elog.c:521)
2    0x9510f4 postgres elog_finish (elog.c:1462)
3    0x56af69 postgres <symbol not found> (aosegfiles.c:2223)
4    0x5660ec postgres appendonly_beginscan (appendonlyam.c:1797)
5    0x6dc361 postgres BeginScanAppendOnlyRelation (execAOScan.c:78)
6    0x6c6d85 postgres ExecTableScan (nodeTableScan.c:47)
7    0x69297a postgres ExecProcNode (execProcnode.c:1068)
8    0x6acb16 postgres ExecAgg (tuptable.h:157)
9    0x6928fa postgres ExecProcNode (execProcnode.c:1156)
10   0x6c2fb0 postgres ExecMotion (tuptable.h:157)
11   0x69294a postgres ExecProcNode (execProcnode.c:1176)
12   0x69025c postgres <symbol not found> (execMain.c:2811)
13   0x6907c0 postgres ExecutorRun (execMain.c:888)
14   0x82d5e9 postgres <symbol not found> (pquery.c:1152)
15   0x82f225 postgres PortalRun (pquery.c:975)
16   0x8273ec postgres <symbol not found> (discriminator 15)
17   0x82cacd postgres PostgresMain (postgres.c:5188)
18   0x7cb005 postgres <symbol not found> (postmaster.c:6384)
19   0x7cd7d2 postgres PostmasterMain (postmaster.c:1524)
20   0x4c7757 postgres main (main.c:206)
21   0x7f5bd5f86445 libc.so.6 __libc_start_main + 0xf5
22   0x4c7cac postgres <symbol not found> + 0x4c7cac

**Comment by asimrp** [comment]
@corama can you elaborate what "something wrong" means?  E.g. `gpcrondump` is interrupted somehow?  Or the database is restarted?

When this error happens, more details are emitted into the log file of the Greenplum segment which hit the error.  Could you please post those details here?  Look for `pg_aoseg segno:eof entries` string in the log file.

**Comment by corama** [comment]
The problem is that the error caused backup fail. Here are the logs which you need:


2019-04-27 00:32:26.383761 CST,"gpadmin","gpusername",p148453,th325031808,"[local]",,2019-04-27 00:30:07 CST,0,con10378,cmd10436,seg-1,,,,sx1,"LOG","00000","pg_aoseg segno:eof entries:",,,,,,"COPY ss.xxxxxxxxxxx (column_name list...) TO stdout IGNORE EXTERNAL PARTITIONS;",0,,"aosegfiles.c",2154,
2019-04-27 00:32:26.383842 CST,"gpadmin","gpusername",p148453,th325031808,"[local]",,2019-04-27 00:30:07 CST,0,con10378,cmd10436,seg-1,,,,sx1,"LOG","00000","gp_relation_node segno entries: 0 1",,,,,,"COPY ss.xxxxxxxxxxx (column_name list...) TO stdout IGNORE EXTERNAL PARTITIONS;",0,,"aosegfiles.c",2172,
2019-04-27 00:32:26.572974 CST,"gpadmin","gpusername",p148453,th325031808,"[local]",,2019-04-27 00:30:07 CST,0,con10378,cmd10436,seg-1,,,,sx1,"ERROR","XX000","gp_relation_node (2) has more entries than pg_aoseg (0) for relation xxxxxxxxxxx (aosegfiles.c:2226)",,,,,,"COPY ss.xxxxxxxxxxx (column_name list...) TO stdout IGNORE EXTERNAL PARTITIONS;",0,,"aosegfiles.c",2226,"Stack trace:
1    0x94f37b postgres errstart (elog.c:521)
2    0x9510f4 postgres elog_finish (elog.c:1462)
3    0x56af69 postgres <symbol not found> (aosegfiles.c:2223)
4    0x5660ec postgres appendonly_beginscan (appendonlyam.c:1797)
5    0x61b338 postgres <symbol not found> (copy.c:2616)
6    0x61c466 postgres DoCopyInternal (copy.c:1892)
7    0x61dac0 postgres DoCopy (discriminator 2)
8    0x83050d postgres ProcessUtility (utility.c:1134)
9    0x82d2c1 postgres <symbol not found> (pquery.c:1395)
10   0x82e13e postgres <symbol not found> (pquery.c:1478)
11   0x82f33c postgres PortalRun (pquery.c:1020)
12   0x829d56 postgres <symbol not found> (postgres.c:1817)
13   0x82bfcb postgres PostgresMain (postgres.c:5004)
14   0x7cb005 postgres <symbol not found> (postmaster.c:6384)
15   0x7cd7d2 postgres PostmasterMain (postmaster.c:1524)
16   0x4c7757 postgres main (main.c:206)
17   0x7fae0eaa4445 libc.so.6 __libc_start_main + 0xf5
18   0x4c7cac postgres <symbol not found> + 0x4c7cac
"


In the gpcrondump output file, also the same log recorded:

gpadmin-[INFO]:-20190516:00:32:22|gp_dump_agent-[ERROR]:-SQL command failed

gpadmin-[INFO]:-20190516:00:32:22|gp_dump_agent-[ERROR]:-Error message from server: ERROR:  gp_relation_node (2) has more entries than pg_aoseg (0) for relation xxxxxxxxxxxx (aosegfiles.c:2226)

gpadmin-[INFO]:-20190516:00:32:22|gp_dump_agent-[ERROR]:-The command was: COPY ss.xxxxxxxxxxxx (column_name list ....) TO stdout IGNORE EXTERNAL PARTITIONS;

gpadmin-[INFO]:-20190516:00:32:23|gp_dump_agent-[ERROR]:-*** aborted because of error: ERROR:  gp_relation_node (2) has more entries than pg_aoseg (0) for relation xxxxxxxxxxxx (aosegfiles.c:2226)

gpadmin-[INFO]:-

gpadmin-[INFO]:-20190516:00:32:23|gp_dump_agent-[ERROR]:-*** aborted because of error: ERROR:  gp_relation_node (2) has more entries than pg_aoseg (0) for relation xxxxxxxxxxxx (aosegfiles.c:2226)

gpadmin-[INFO]:-

gpadmin-[ERROR]:-Status file contents dumped to log file

**Comment by asimrp** [comment]
Can you confirm the following please?
1. Simple `select * from <table>;` is failing with the same error?
2. Did the segment go through `gprecoverseg -r` (rebalance) operation at some point in the past, after this table was created?

**Comment by corama** [comment]
1. Yes, issuing the SQL directly on the child table would fail with the same error.
2. Yes, rebalancing occurred for the segment host cannot be reached.

**Comment by asimrp** [comment]
Thank you for confirming @corama.  This is Greenplum 5.1.0.  That means you are very likely encountering the issue already fixed by https://github.com/greenplum-db/gpdb/commit/492803b652b8e7810703b8946cf3d7d7716f4f7f.  I would suggest trying the latest 5X_STABLE release and run your workload again.

After upgrading to latest 5X, the victim table must be dropped and restored from a backup, if you have one available.

**Comment by corama** [comment]
So many thanks. I will try to upgrade and test. ^^
