### ISSUE TITLE
Can't compile with libxerces-c-3.2 on Ubuntu 18.0.4

### ISSUE THREAD

**Issue by tanertas** [greenplum-db/gpdb#7698]
### Greenplum version or build
gpdb-6.0.0-beta.3

### OS version and uname -a
Ubuntu 18.0.4 LTS
Linux gpdb-03 4.15.0-50-generic #54-Ubuntu SMP Mon May 6 18:46:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

### autoconf options used ( config.status --config )
none

### Installation information ( pg_config )
not installed

### Expected behavior
gpdb will compile on Ubuntu 18.0.4 with libxerces-c3.2 installed

### Actual behavior
gpdb doesn't compile on Ubuntu 18.0.4 LTS if libxerces-c 3.2 is installed from package. But if I install libxerces-c 3.1.4 from source, gpdb compiles properly.

### Step to reproduce the behavior
cd gpdb-6.0.0-beta.3
./README.ubuntu.bash
cd depends
./configure
make

[gpdb-ubuntu-18.txt](https://github.com/greenplum-db/gpdb/files/3187649/gpdb-ubuntu-18.txt)

**Comment by d** [comment]
xerces 3.1 is a known dependency. closing as WONTFIX
