### ISSUE TITLE
pg_dump -i is deprecated, but there is no warning

### ISSUE THREAD

**Issue by ascherbaum-pivotal** [greenplum-db/gpdb#770]
The code for the -i option in pg_dump is deprecated:

https://github.com/greenplum-db/gpdb/blob/master/src/bin/pg_dump/pg_dump.c#L512

However there is no warning when this option is used. pg_dump keeps going as if nothing happened.

**Comment by ascherbaum-pivotal** [comment]
So we removed the documentation in #771, but we never decided what to do if someone uses this option.

The right thing to do is remove it, and just fail if it is used.

Ping @danielgustafsson

**Comment by danielgustafsson** [comment]
I agree with that, remove it from the code.

**Comment by hlinnaka** [comment]
The option was marked as deprecated in PostgreSQL in 8.4, so that it was a no-op. Just like it is now in GPDB. It was finally removed in 9.5. I think we can leave it as it is, until we merge the commit from 9.5 that finally removes it.

**Comment by hlinnaka** [comment]
I hear no objections, so closed.
