### ISSUE TITLE
psql command \dd is broken

### ISSUE THREAD

**Issue by BaiShaoqi** [greenplum-db/gpdb#7712]
### Greenplum version or build
latest master 730d31d5bf09ae327e2335eab11fd469a61098ef

### Expected behavior
```
         Object descriptions
 Schema | Name | Object | Description
--------+------+--------+-------------
(0 rows)
```
### Actual behavior
```
ERROR:  missing FROM-clause entry for table "o"
LINE 11:   AND pg_catalog.pg_operator_is_visible(o.oid)
                                                 ^
```
### Step to reproduce the behavior
```
-> psql  -d postgres --no-psqlrc
psql (9.4.20)
Type "help" for help.

postgres=# \dd
```

**Comment by asimrp** [comment]
Fixed in master by PR #7714 and back ported to 6X_STABLE as https://github.com/greenplum-db/gpdb/commit/321211d8168af993046ea7547cc9553f75b0f5f9
