### ISSUE TITLE
gprecoverseg -o ./recov shared memory error

### ISSUE THREAD

**Issue by 444728248** [greenplum-db/gpdb#7724]
log info
unable to clean up shared memory for stopped segments on host

**Comment by gaos1** [comment]
could you post more info about the issue, e.g.
1) what version?
2) master and segment logs or callstacks

**Comment by ashwinstar** [comment]
We don't have enough information to investigate this issue. Closing the same. If encountering the issue next time, please provide clear repro and information for the issue to help.
