### ISSUE TITLE
delete table by configuration error?

### ISSUE THREAD

**Issue by 444728248** [greenplum-db/gpdb#7728]
`Great gods`
My online environment deletes table structure

delete ： pg_class and pg_type 

Other system tables need to be deleted after operation

`I am not very familiar with the system table information, please God pointed out that if you delete the table structure, you need to delete the system configuration table.`

**Comment by danielgustafsson** [comment]
> On 21 May 2019, at 11:43, 444728248 <notifications@github.com> wrote:
> 
> Great gods
> My online environment deletes table structure
> 
> delete ： pg_class and pg_type
> 
> Other system tables need to be deleted after operation
> 
> I am not very familiar with the system table information, please God pointed out that if you delete the table structure, you need to delete the system configuration table.

It’s not entirely clear what you have done, or trying to achieve. In any case, you should never need to drop any catalog table and generally never need to manually delete from catalog tables either.

**Comment by 444728248** [comment]
Now my main table is broken and cannot be deleted. I delete records by deleting system table records. I delete records of pg_class and pg_type information, but I still can't create tables.

**Comment by hlinnaka** [comment]
I don't think this is a bug. If you delete entries in the system catalogs directly, bad things will happen, so don't do that. Closing.
