### ISSUE TITLE
ERROR:  operator 96 is not a member of opfamily 23 (lsyscache.c:160)

### ISSUE THREAD

**Issue by BaiShaoqi** [greenplum-db/gpdb#7742]
### Greenplum version or build
gpdb master latest, gporca  tag: v3.44.0

### Step to reproduce the behavior
```
postgres=# CREATE TABLE aa (a int, b int, c int, PRIMARY KEY (a, b));
CREATE TABLE
postgres=# INSERT INTO aa VALUES (1,1,1);
INSERT 0 1
postgres=# UPDATE aa SET c = 3 WHERE (a, b) = (1, 1);
ERROR:  operator 96 is not a member of opfamily 23 (lsyscache.c:160)
```
The error is not output in when `set optimizer=off`; suppose it is gporca releated.

**Comment by hlinnaka** [comment]
Works for me on latest 'master', with or without ORCA. Was this accidentally fixed?

**Comment by BaiShaoqi** [comment]
Right, seems orca team have fixed, no knowing which commit. closed
