### ISSUE TITLE
Question: Where is I can read about benefits of your own jdbc-driver?

### ISSUE THREAD

**Issue by Pryanic** [greenplum-db/gpdb#7752]
Hi all. 
What the difference between your own driver and postgre jdbc driver?

**Comment by ivannovick** [comment]
Which 2 drivers are you talking about?  Maybe you are referring to the not open source driver from Progress Software that is distributed by Pivotal.  Those differences would be discussed by contacting to Progress Software or Pivotal and not via OSS channels.  Sorry about that
