### ISSUE TITLE
only started greenplum in mode of  "gp_role=utility -M master"  and  can't gpstop  

### ISSUE THREAD

**Issue by liberalkk** [greenplum-db/gpdb#7768]
1.  only can start greenplum in mode of "gp_role=utility -M master" 
![image](https://user-images.githubusercontent.com/26476931/58309064-be256900-7e35-11e9-9ce8-9108cae0cbf0.png)

2.  can't gpstop
![image](https://user-images.githubusercontent.com/26476931/58308951-77377380-7e35-11e9-8826-1f79a7910d45.png)

and who could tell me  what is the meaning  of  'Database does not contain gp_fault_strategy entry' ? and how can i fix it ?
thxs~

**Comment by asimrp** [comment]
@liberalkk just out of curiosity, what are you using `gp_role=utility` for?

**Comment by liberalkk** [comment]
> @liberalkk just out of curiosity, what are you using `gp_role=utility` for?
check the log of gpinitsystem,i find the reason of using `gp_role=utility` maybe is that:
greenplum DB was not started in right way,and the pic just show the DB in master only mode.
![image](https://user-images.githubusercontent.com/26476931/58397310-ee157c00-8082-11e9-9432-0ddb8d1bee0c.png)
I also check /etc/hosts profile and find nothing wrong about hostfile .
Searched  stackover flow and googles still not fix the problem

**Comment by liberalkk** [comment]
> 1. only can start greenplum in mode of "gp_role=utility -M master"
>    ![image](https://user-images.githubusercontent.com/26476931/58309064-be256900-7e35-11e9-9ce8-9108cae0cbf0.png)
> 2. can't gpstop
>    ![image](https://user-images.githubusercontent.com/26476931/58308951-77377380-7e35-11e9-8826-1f79a7910d45.png)
> 
> and who could tell me what is the meaning of 'Database does not contain gp_fault_strategy entry' ? and how can i fix it ?
> thxs~

The problem is fixed.
There was a file named '.gphostcache'. you can find it by shell command "ll -al ~".
When fhe file was rm and DB can be start in the right way

**Comment by asimrp** [comment]
:+1: you found a solution yourself, thanks for sharing it @liberalkk!

**Comment by berlin-ab** [comment]
I also ran into this issue while setting up a cluster on Ubuntu 18.04. 

I found this in the `gpinitsystem` log:

```
psql: FATAL: semctl(152109057, 7, SETVAL, 0) failed: Invalid argument (pg_sema.c:151)
```

That led me to:

https://newbiedba.wordpress.com/2017/03/28/postgresql-9-6-on-rhel-7-2-fatal-semctlsetval-failed-invalid-argument/ 

and 

https://docs.oracle.com/cd/E52668_01/E67200/html/section-t51_kcn_f5.html

After setting `RemoveIPC=no` in `/etc/systemd/logind.conf` and rebooting the machine, `make cluster` started working.
