### ISSUE TITLE
Document requirements for installcheck-good

### ISSUE THREAD

**Issue by danielgustafsson** [greenplum-db/gpdb#777]
Some testsuites in installcheck-good depend on the build being set up with optional parameters such as `--with-python`. Document in the README.md file the full set of requirements for running installcheck-good.

**Comment by ivannovick** [comment]
@schubert @danielgustafsson do you want to keep this open?  Who can we assign it to?

**Comment by danielgustafsson** [comment]
I think we can close this one, it hasn't come up since and the proper solution is to remove the dependency on plpython in the tests anyways.
