### ISSUE TITLE
When the character type is used as a distribution key and a full match search is performed, all segment databases are searched instead of search only on the segment where the data is stored.

### ISSUE THREAD

**Issue by Melodyyy1016** [greenplum-db/gpdb#7779]
### Greenplum version or build
(Greenplum Database) 5.11.3

### OS version and uname -a
Centos7
Linux master 3.10.0-327.el7.x86_64 #1 SMP Thu Nov 19 22:10:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

### Installation information ( pg_config )
1master，3Physical node，6segment（2 segment per physical node）

### Expected behavior
When you want to use the character type distribution key to make a matching query, you only need to query the segment where the data is stored.Just like when matching queries with INT type distribution keys
![bbb](https://user-images.githubusercontent.com/51019386/58367755-2f881900-7f15-11e9-8bf0-f11d63212224.jpg)

### Actual behavior
When a matching query is made with a character-type distribution key, gpdb will query all the segments.
![aaa](https://user-images.githubusercontent.com/51019386/58367713-e768f680-7f14-11e9-93ea-816e372cf76e.jpg)

After I closed ORCA, the problem was solved.
![image](https://user-images.githubusercontent.com/51019386/58367768-652d0200-7f15-11e9-8a34-bf25f95d13fd.png)

**I suspect this problem is ORCA's bug！！！**

**Comment by melanieplageman** [comment]
Adding repro query here for convenience
```
drop table t1;
create table t1(a varchar, b int);
insert into t1 select i, i from generate_series(1,10)i;
set optimizer to on;
explain analyze select * from t1 where a = '5';
```

**Comment by chrishajas** [comment]
Orca now produces the good direct dispatch plan on the main branch:
```
test=# explain analyze select * from t1 where a = '5';
                                                        QUERY PLAN
--------------------------------------------------------------------------------------------------------------------------
 Gather Motion 1:1  (slice1; segments: 1)  (cost=0.00..431.00 rows=1 width=106) (actual time=0.140..0.141 rows=1 loops=1)
   ->  Seq Scan on t1  (cost=0.00..431.00 rows=1 width=106) (actual time=0.040..0.041 rows=1 loops=1)
         Filter: ((a)::text = '5'::text)
         Rows Removed by Filter: 2
 Optimizer: Pivotal Optimizer (GPORCA)
 Planning Time: 8.003 ms
   (slice0)    Executor memory: 17K bytes.
   (slice1)    Executor memory: 12K bytes (seg2).
 Memory used:  128000kB
 Execution Time: 0.901 ms
(10 rows)
```
