### ISSUE TITLE
gp_fault_injection does not work for gpdb extensions

### ISSUE THREAD

**Issue by HaozhouWang** [greenplum-db/gpdb#7788]
### Greenplum version or build
6X_STABLE & master
### Expected behavior

```
test=# SELECT gp_inject_fault('plcontainer_before_container_started', 'reset', 2);
NOTICE:  Success:  (seg0 127.0.0.1:25432 pid=21055)
 gp_inject_fault
-----------------
 t
(1 row)

```

### Actual behavior

```
test=# SELECT gp_inject_fault('plcontainer_before_container_started', 'reset', 2);
ERROR:  could not recognize fault name 'plcontainer_before_container_started'  (seg0 127.0.0.1:25432 pid=13485)
```

### Step to reproduce the behavior

After PR #7739  (https://github.com/greenplum-db/gpdb/pull/7739), the gp_fault_injection is not working for GPDB extensions by following code changes:

```
FaultInjectorType_e
FaultInjectorTypeStringToEnum(char* faultTypeString)
{
	FaultInjectorType_e	faultTypeEnum = FaultInjectorTypeMax;
	int	ii;
	
	for (ii=FaultInjectorTypeNotSpecified+1; ii < FaultInjectorTypeMax; ii++)
	{
		if (strcmp(FaultInjectorTypeEnumToString[ii], faultTypeString) == 0)
		{
			faultTypeEnum = ii;
			break;
		}
	}
	return faultTypeEnum;
}

FaultInjectorIdentifier_e
FaultInjectorIdentifierStringToEnum(char* faultName)
{
	FaultInjectorIdentifier_e	faultId = FaultInjectorIdMax;
	int	ii;
	
	for (ii=FaultInjectorIdNotSpecified+1; ii < FaultInjectorIdMax; ii++)
	{
		if (strcmp(FaultInjectorIdentifierEnumToString[ii], faultName) == 0)
		{
			faultId = ii;
			break;
		}
	}
	return faultId;
}
```
The `ii` is start from 1 instead of 0.

```
faultEntry.faultInjectorIdentifier = FaultInjectorIdentifierStringToEnum(faultName);
	if (faultEntry.faultInjectorIdentifier == FaultInjectorIdMax)
		ereport(ERROR,
				(errcode(ERRCODE_PROTOCOL_VIOLATION),
				 errmsg("could not recognize fault name '%s'", faultName)));

	faultEntry.faultInjectorType = FaultInjectorTypeStringToEnum(type);
	if (faultEntry.faultInjectorType == FaultInjectorTypeMax)
		ereport(ERROR,
				(errcode(ERRCODE_PROTOCOL_VIOLATION),
				 errmsg("could not recognize fault type '%s'", type)));
```
the if statments are changed from 
```
if (faultEntry.faultInjectorIdentifier == FaultInjectorIdNotSpecified)
            ereport(ERROR,
				(errcode(ERRCODE_PROTOCOL_VIOLATION),
				 errmsg("could not recognize fault name '%s'", faultName)));
if (faultEntry.faultInjectorType == FaultInjectorTypeMax || faultEntry.faultInjectorIdentifier == FaultInjectorIdNotSpecified)
        		ereport(ERROR,
				(errcode(ERRCODE_PROTOCOL_VIOLATION),
				 errmsg("could not recognize fault type '%s'", type)));
```

If we move back these changes, the gp_inject_fault is working as the previous version.

**Comment by asimrp** [comment]
In the plcontainer repo, can you please share how the fault `plcontainer_before_container_started` is defined?  E.g. how do `const char* FaultInjectorIdentifierEnumToString[]` and `typedef enum FaultInjectorIdentifier_e` look like?

**Comment by HaozhouWang** [comment]
No, we do not put our fault inject items into `FaultInjectorIdentifierEnumToString`  as plcontainer is an extension. We use the fault inject `string` based item instead of pre-defined in .h file. This allows us to put a `string` (e.g. `plcontainer_before_container_started`) into fault inject SHM hash table. When a fault_inject is triggered, it will search the hash table based on string match. 

For example, we do 

```
SELECT gp_inject_fault('plcontainer_before_container_started', 'reset', 2);
```
That registers the `plcontainer_before_container_started` into hash table.
So when we do `SIMPLE_FAULT_NAME_INJECTOR("plcontainer_before_container_started")` to trigger our fault. The fault_injector will search on the hash table to find the item with the name `plcontainer_before_container_started` and do its work.

This feature was added in PR #3249

**Comment by asimrp** [comment]
The commit 032b0a308cfb34c2cf8bf51cb2437b748aaf7dd0 added by PR #3249, in fact, fixed a bug in faultinjector.c.  Prior to this commit, `InjectFault()` would silently continue and add a fault to the shared memory hash table even if `faultName` was not found in the predefined enum `FaultInjectorIdentifierEnumToString`.  That is not right.

Apparently, `plcontainer` accidentally relied on this bug.  In order to suite `plcontainer` use case, I faultinjector.c needs to be able to assign fault IDs dynamically.

**Comment by asimrp** [comment]
> If we move back these changes, the gp_inject_fault is working as the previous version.

Moving back / reverting the changes in https://github.com/greenplum-db/gpdb/commit/032b0a308cfb34c2cf8bf51cb2437b748aaf7dd0 will be a regression.  Let's not do that.  A proper solution is to assign fault IDs from a dynamic range from `FaultInjectorIdMax` to some limit.

**Comment by HaozhouWang** [comment]
Thanks @asimrp. 

PL/Container fault_injector tests are not accidentally relied on this. This is a designed implementation (PR #3249 is designed among with this).  This is because an extension can not predefine an enum in the fault_injector, otherwise, we need to change the GPDB code. So it has to add a fault name into the hash table (the extension .so may not be loaded in that time), and the extension code can trigger that fault.

I agree using a dynamic way to register a fault ID into fault_injector. This is a good way to go.
A simple way is to add a set of special IDs for extensions such as `extension_fault_point_x`. I think this could be enough for extensions.
 
Do you have a plan to add a dynamic way/function for extension fault_injector feature?

**Comment by asimrp** [comment]
Ah, I see it now, after taking a close look at PR #3249.  Thank you for being patient.  I think the fault IDs we have today can be removed altogether.  The only advantage in defining all faults in one place, statically, is one can write comments describing each one.  If we are ok without this, I think we can remove the fault ID concept altogether and apply the idea in PR #3249 to all faults, not just those used by extensions.

**Comment by HaozhouWang** [comment]
Thank you very much! I'm +1 on this. Could I directly remove the fault ID concept by updating PR #7824 or using two separate PRs to do this?

**Comment by HaozhouWang** [comment]
Thanks @asimrp to fix this issue.
