### ISSUE TITLE
Assertion failure when INSERT with string - pg_verifymbstr

### ISSUE THREAD

**Issue by goopand** [greenplum-db/gpdb#7810]
### Greenplum version or build
PostgreSQL 8.3.23 (Greenplum Database 5.15.1 build dev) on x86_64-pc-linux-gnu, compiled by GCC gcc (GCC) 6.3.1 20170216 (Red Hat 6.3.1-3), 64-bit compiled on Dec 29 2018 16:47:59 (with assert checking)

### OS version and uname -a
CentOS Linux release 7.6.1810 (Core)
Linux gpdb01 3.10.0-862.el7.x86_64 #1 SMP Fri Apr 20 16:44:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

### autoconf options used ( config.status --config )
bash: config.status: command not found...

### Installation information ( pg_config )
BINDIR = /usr/local/gpdb/bin
DOCDIR = /usr/local/gpdb/doc/postgresql
HTMLDIR = /usr/local/gpdb/doc/postgresql
INCLUDEDIR = /usr/local/gpdb/include
PKGINCLUDEDIR = /usr/local/gpdb/include/postgresql
INCLUDEDIR-SERVER = /usr/local/gpdb/include/postgresql/server
LIBDIR = /usr/local/gpdb/lib
PKGLIBDIR = /usr/local/gpdb/lib/postgresql
LOCALEDIR = /usr/local/gpdb/share/locale
MANDIR = /usr/local/gpdb/share/man
SHAREDIR = /usr/local/gpdb/share/postgresql
SYSCONFDIR = /usr/local/gpdb/etc/postgresql
PGXS = /usr/local/gpdb/lib/postgresql/pgxs/src/makefiles/pgxs.mk
CC = gcc
CPPFLAGS = -D_GNU_SOURCE -I/usr/local/gpdb/include
CFLAGS = -O3 -std=gnu99 -Wall -Wmissing-prototypes -Wpointer-arith -Wendif-labels -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fno-aggressive-loop-optimizations -Wno-unused-but-set-variable -Wno-address -g -ggdb -I/usr/local/gpdb/include
CFLAGS_SL = -fpic
LDFLAGS = -Wl,--as-needed -Wl,-rpath,'/usr/local/gpdb/lib',--enable-new-dtags -L/usr/local/gpdb/lib
LDFLAGS_SL = 
LIBS = -lpgport -lgpopt -lnaucrates -lgpdbcost -lgpos -lxerces-c -lxml2 -lpam -lrt -lgssapi_krb5 -lcrypt -ldl -lm -L/usr/local/gpdb/lib
VERSION = PostgreSQL 8.3.23

### Expected behavior
We expect to insert some string data into a table successfully.

### Actual behavior
We were trying to insert some data into a table but found a fatal error as below:
2019-05-29 15:12:18.261558 CST,"dev_user","mydb",p32179,th-1168123776,"[local]",,2019-05-29 15:12:18 CST,0,con1900056,cmd3,seg-1,slice1,dx64,,sx1,"FATAL","XX000","Unexpected internal error (elog.c:227)","FailedAssertion(""!(pg_verifymbstr(*str, len, ((bool) 1)))"", File: ""elog.c"", Line: 227)","Process 32179 will wait for gp_debug_linger=120 seconds before termination.
Note that its locks and other resources will not be released until then.",,,," insert into source_data.data(col1,col2,col3,col4,col5,col6,col7,col8,col9,col10,col11,col12) values ('some data','some data','some data','2019-05-29','00:00:00','some data','',true,'some data','some data','4','1'),('some data','some data','some data','2019-05-29','00:00:00','some data','',true,'some data,0,,"elog.c",227,"Stack trace:
1    0x9cb650 postgres errstart (elog.c:521)
2    0x9c0e89 postgres ExceptionalCondition (assert.c:40)
3    0x9cbfbd postgres errmsg (elog.c:227)
4    0x89d6dd postgres <symbol not found> (discriminator 1)
5    0x8a33fb postgres PostgresMain (postgres.c:5146)
6    0x834baf postgres <symbol not found> (postmaster.c:6406)
7    0x83732a postgres PostmasterMain (postmaster.c:1533)
8    0x4cb96d postgres main (main.c:206)
9    0x7fbdb62643d5 libc.so.6 __libc_start_main + 0xf5
10   0x4cbecf postgres <symbol not found> + 0x4cbecf
"

After about 120 seconds all the connections to greenplum database are reset including connections from gpadmin user. Connections are reset with the following information:
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
The connection to the server was lost. Attempting reset: Succeeded.

### Step to reproduce the behavior
Just insert some data with some special characters (for example characters with '你好世界xE9xA2' shown in Notepad++) into a table and wait 2 minutes.

**Comment by goopand** [comment]
It doesn't look like an issue. Just reconfigure the source code without option '--enable-cassert' and it should work. Btw, '--enable-cassert' is not recommended in production environment.

**Comment by asimrp** [comment]
I tried with asserts enabled and insert as well select worked fine with the string ''你好世界xE9xA2'.

**Comment by goopand** [comment]
Refer to [this link](https://www.enterprisedb.com/edb-docs/d/postgresql/reference/manual/latest/install-procedure.html) for the '--enable-cassert' part.
