### ISSUE TITLE
The sub-transaction lock is not cleaned up as intended after release savepoint

### ISSUE THREAD

**Issue by constzl** [greenplum-db/gpdb#7819]
### Greenplum version or build
4.3.99
### OS version and uname -a
Linux centos7 3.10.0-957.12.1.el7.x86_64 #1 SMP Mon Apr 29 14:59:59 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
### autoconf options used ( config.status --config )
[const.zl@centos7 ~/workspace/greenplum]$ ./config.status
config.status: creating GNUmakefile
config.status: creating src/Makefile.global
config.status: creating src/include/pg_config.h
config.status: creating src/interfaces/ecpg/include/ecpg_config.h
config.status: src/interfaces/ecpg/include/ecpg_config.h is unchanged
config.status: linking src/backend/port/tas/dummy.s to src/backend/port/tas.s
config.status: linking src/backend/port/dynloader/linux.c to src/backend/port/dynloader.c
config.status: linking src/backend/port/sysv_sema.c to src/backend/port/pg_sema.c
config.status: linking src/backend/port/sysv_shmem.c to src/backend/port/pg_shmem.c
config.status: linking src/backend/port/unix_latch.c to src/backend/port/pg_latch.c
config.status: linking src/backend/port/dynloader/linux.h to src/include/dynloader.h
config.status: linking src/include/port/linux.h to src/include/pg_config_os.h
config.status: linking src/makefiles/Makefile.linux to src/Makefile.port

### Installation information ( pg_config )
BINDIR = /home/const.zl/workspace/app_orca/bin
DOCDIR = /home/const.zl/workspace/app_orca/doc/gpdb
HTMLDIR = /home/const.zl/workspace/app_orca/doc/gpdb
INCLUDEDIR = /home/const.zl/workspace/app_orca/include
PKGINCLUDEDIR = /home/const.zl/workspace/app_orca/include/gpdb
INCLUDEDIR-SERVER = /home/const.zl/workspace/app_orca/include/gpdb/server
LIBDIR = /home/const.zl/workspace/app_orca/lib
PKGLIBDIR = /home/const.zl/workspace/app_orca/lib/gpdb
LOCALEDIR = /home/const.zl/workspace/app_orca/share/locale
MANDIR = /home/const.zl/workspace/app_orca/share/man
SHAREDIR = /home/const.zl/workspace/app_orca/share/gpdb
SYSCONFDIR = /home/const.zl/workspace/app_orca/etc/gpdb
PGXS = /home/const.zl/workspace/app_orca/lib/gpdb/pgxs/src/makefiles/pgxs.mk
CC = gcc
CPPFLAGS = -D_GNU_SOURCE -I/home/const.zl/workspace/app_orca/include
CFLAGS = -O0 -std=gnu99 -Wall -Wmissing-prototypes -Wpointer-arith -Wendif-labels -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fno-aggressive-loop-optimizations -Wno-unused-but-set-variable -Wno-address -g -ggdb -I/home/const.zl/workspace/app_orca/include
CFLAGS_SL = -fpic
LDFLAGS = -Wl,--as-needed -Wl,-rpath,'/home/const.zl/workspace/app_orca/lib',--enable-new-dtags -L/home/const.zl/workspace/app_orca/lib
LDFLAGS_SL =
LIBS = -lpgport -lxml2 -lrt -lgssapi_krb5 -lmxml -laprutil-1 -lapr-1 -lcrypt -ldl -lm -L/home/const.zl/workspace/app_orca/lib
VERSION = PostgreSQL 8.2.15

### Expected behavior
Cleanup the lock of sub-transaction after release savepoint
### Actual behavior
The sub-transaction lock is always held until commit/rollback its parent's transaction
### Step to reproduce the behavior

GP 4.3 (with PG 8.2.15)
![image](https://user-images.githubusercontent.com/32921993/58604714-f9a5b480-82c7-11e9-8675-04e2ca759232.png)

VS
PG 8.2.15
![image](https://user-images.githubusercontent.com/32921993/58604787-42f60400-82c8-11e9-8118-58081bab355c.png)

**Comment by constzl** [comment]
I found something wrong with this code.

![image](https://user-images.githubusercontent.com/32921993/58604914-a849f500-82c8-11e9-9376-137ed5c2e68e.png)

It will lock twice if LockAcquire return LOCKACQUIRE_OK or LOCKACQUIRE_ALREADY_HELD. Locking twice leads to the counting of locks twice, so it never cleanup the sub-transaction lock by calling LockRelease because of its nLocks count > 0.

**Comment by Eulerizeit** [comment]
4.3.99 is more than 2 years old. Currently we are are on 5.19.  Could you see if this is still an issue in a somewhat newer codebase?

**Comment by constzl** [comment]
> 4.3.99 is more than 2 years old. Currently we are are on 5.19. Could you see if this is still an issue in a somewhat newer codebase?

I got this code from master branch of GP. see it's still possible to lock transactionid twice.
![image](https://user-images.githubusercontent.com/32921993/58692756-e37c1f00-83c1-11e9-9715-fd9d4d943a93.png)

**Comment by hlinnaka** [comment]
Yeah, that code is still there in GPDB master. It dates back to before Greenplum was open sourced, and there hasn't been any changes to it since.

@constzl, you're absolutely right, we're acquiring the lock twice, and fail to release it at subtransaction commit because of that. I don't think it causes any ill effects, though, except for taking space in the lock table. We should fix that.

**Comment by hlinnaka** [comment]
Opened https://github.com/greenplum-db/gpdb/pull/7929 to fix this. Thanks for the report!

**Comment by constzl** [comment]
> Yeah, that code is still there in GPDB master. It dates back to before Greenplum was open sourced, and there hasn't been any changes to it since.
> 
> @constzl, you're absolutely right, we're acquiring the lock twice, and fail to release it at subtransaction commit because of that. I don't think it causes any ill effects, though, except for taking space in the lock table. We should fix that.

Imagine that recurrence creates many subtransactions. What would happen if the transaction locks could not be released in a timely manner? There will eventually be no transaction locks available if let it go.

The pseudo code is as follows

```
BEGIN;
    LOOP SO MANY TIMES
        SAVEPOINT S1;
        RELEASE SAVEPOINT S1; -- What would happen if after a certain amount of sub-transaction and here never release transaction lock
   END LOOP
END;
```

**Comment by hlinnaka** [comment]
> > Yeah, that code is still there in GPDB master. It dates back to before Greenplum was open sourced, and there hasn't been any changes to it since.
> > @constzl, you're absolutely right, we're acquiring the lock twice, and fail to release it at subtransaction commit because of that. I don't think it causes any ill effects, though, except for taking space in the lock table. We should fix that.
> 
> Imagine that recurrence creates many subtransactions. What would happen if the transaction locks could not be released in a timely manner? There will eventually be no transaction locks available if let it go.

Right. That's what I meant with "except for taking space in the lock table".

I pushed PR #7929 to fix this, to master and 6X_STABLE branches. Thanks for the report!

**Comment by constzl** [comment]
> > > Yeah, that code is still there in GPDB master. It dates back to before Greenplum was open sourced, and there hasn't been any changes to it since.
> > > @constzl, you're absolutely right, we're acquiring the lock twice, and fail to release it at subtransaction commit because of that. I don't think it causes any ill effects, though, except for taking space in the lock table. We should fix that.
> > 
> > 
> > Imagine that recurrence creates many subtransactions. What would happen if the transaction locks could not be released in a timely manner? There will eventually be no transaction locks available if let it go.
> 
> Right. That's what I meant with "except for taking space in the lock table".
> 
> I pushed PR #7929 to fix this, to master and 6X_STABLE branches. Thanks for the report!

my pleasure
