### ISSUE TITLE
Not support ARM server?

### ISSUE THREAD

**Issue by laixiong** [greenplum-db/gpdb#7825]
We added hyperloglog plugin(https://github.com/citusdata/postgresql-hll) within greenplum-db-5.0.0 in x86_64 server.
But now We using ARM server,  when compile greenplum-db-5.16.0 , it success. bu when wen compile hyperloglog , it failed, error happend in file **postgres.h** , Could some one can resove this ?

### Greenplum version or build
5.16.0
### OS version and uname -a
4.11.0-44-e17a.aarch64
### autoconf options used ( config.status --config )
--with-perl --with-libxml --perfix=/usr/loca/gpdb-5.15.0 --with-apr-config=/usr/bin/apr-1-config --disable-gpcloud

**Comment by Eulerizeit** [comment]
Is the ask that we fix the CitusData HLL code to work with Greenplum on ARM?

**Comment by laixiong** [comment]
> Is the ask that we fix the CitusData HLL code to work with Greenplum on ARM? If it is our HLL code then you are linking the wrong thing. If it is the Citus code you need to talk to them.

nope, I think the error maybe in **postgres.h** of gpdb , because CitusData HLL code could compile success with postgresql source code in arm server .

**Comment by d** [comment]
Hi @laixiong

Thank you for your interest in Greenplum Database!

> We added hyperloglog plugin(https://github.com/citusdata/postgresql-hll) within greenplum-db-5.0.0 in x86_64 server.

Can you give us more context? Do you have a source repository published anywhere? Are you on AArch64? What compilation error did you see?

Also, are you aware of the users mailing list gpdb-users@greenplum.org? Your question may not fit well as a Github issue

Regards,
Jesse

**Comment by laixiong** [comment]
I am sorry for this issue, Now I recognized that I'm used the incorrect version of that extension, When I tried  the lower version , build success . (because the lastest version requires newer version of postgres.h.
So I close this issue.
