### ISSUE TITLE
Column `attrnums` missing when creating database 

### ISSUE THREAD

**Issue by akito803** [greenplum-db/gpdb#7844]
After I  created database by executed "create database gp_test" with gpadmin user,each time when connecting the database by using client "datagrip" will show the following error message:

select DP.localoid as table_id,
			DP.attrnums as distribution_keys
			from pg_catalog.gp_distribution_policy DP
			inner join pg_catalog.pg_class T on t.oid = DP.localoid
			where T.relnamespace = ?::oid
			and T.relkind = 'r'
			[42703] org.postgresql.util.PSQLException: ERROR: column dp.attrnums does not exist

Is this caused by the database template?

**Comment by paul-guo-** [comment]
What version is it?

Definition of gp_distribution_policy  is changed since GP 6.
```
psql (9.4.20)
Type "help" for help.

postgres=# \d gp_distribution_policy
Table "pg_catalog.gp_distribution_policy"
   Column    |    Type    | Modifiers
-------------+------------+-----------
 localoid    | oid        | not null
 policytype  | "char"     | not null
 numsegments | integer    | not null
 distkey     | int2vector | not null
 distclass   | oidvector  | not null
```

Assume you are using GP6+. According to the log, the query clause is wrong now. It is not a gpdb issue.

**Comment by akito803** [comment]
> 
> 
> What version is it?
> 
> Definition of gp_distribution_policy is changed since GP 6.
> 
> ```
> psql (9.4.20)
> Type "help" for help.
> 
> postgres=# \d gp_distribution_policy
> Table "pg_catalog.gp_distribution_policy"
>    Column    |    Type    | Modifiers
> -------------+------------+-----------
>  localoid    | oid        | not null
>  policytype  | "char"     | not null
>  numsegments | integer    | not null
>  distkey     | int2vector | not null
>  distclass   | oidvector  | not null
> ```
> 
> Assume you are using GP6+. According to the log, the query clause is wrong now. It is not a gpdb issue.

Hi
   It's 7.0.  Where can I get the 5+ binary installation package?

**Comment by akito803** [comment]
Should use 5+ release version
