### ISSUE TITLE
create table as with no data error

### ISSUE THREAD

**Issue by baobao0206** [greenplum-db/gpdb#7861]
### Greenplum version or build
master and 6X_STABLE

### Step to reproduce the behavior
```
create table t1 (a text);
create table t2 as select * from t1 with no data;
ERROR:  no pre-assigned OID for relation "pg_toast_16391" (oid_dispatch.c:699)  (seg1 127.0.0.1:25433 pid=23912) (oid_dispatch.c:699)
```

**Comment by baobao0206** [comment]
The issue fixed by pr: https://github.com/greenplum-db/gpdb/pull/7871

**Comment by hlinnaka** [comment]
PR #7871 was pushed to master. Shouldn't it be backported to 6X_STABLE, too?

**Comment by baobao0206** [comment]
> PR #7871 was pushed to master. Shouldn't it be backported to 6X_STABLE, too?

Yes, Have made a pr on 6X_STABLE.

**Comment by baobao0206** [comment]
The issue has been resolved by pr https://github.com/greenplum-db/gpdb/pull/7871 and https://github.com/greenplum-db/gpdb/pull/7879
