### ISSUE TITLE
Compiling failed with make -j8 after configuration of Greenplum on MacOS

### ISSUE THREAD

**Issue by sdyajian** [greenplum-db/gpdb#7882]
hi,

when i am installing GPDB（version 5.19.0） without ORCA and following the steps in,
https://github.com/greenplum-db/gpdb/blob/master/README.md

after configuring, i try to compile it and get the following errors,

plperl.c:475:2: error: use of undeclared identifier 'OP_PUSHRE'; did you mean
      'OP_PUSH'?
        PLPERL_SET_OPMASK(plperl_opmask);
        ^
./plperl_opmask.h:18:10: note: expanded from macro 'PLPERL_SET_OPMASK'
  opmask[OP_PUSHRE      ] = 0;  /* push regexp */ \
         ^
/usr/local/Cellar/perl/5.30.0/lib/perl5/5.30.0/darwin-thread-multi-2level/CORE/opnames.h:180:2: note: 
      'OP_PUSH' declared here
        OP_PUSH          = 163,
        ^
plperl.c:475:2: error: use of undeclared identifier 'OP_REACH'
        PLPERL_SET_OPMASK(plperl_opmask);
        ^
./plperl_opmask.h:223:10: note: expanded from macro 'PLPERL_SET_OPMASK'
  opmask[OP_REACH       ] = 0;  /* each on reference */ \
         ^
plperl.c:475:2: error: use of undeclared identifier 'OP_RKEYS'
./plperl_opmask.h:224:10: note: expanded from macro 'PLPERL_SET_OPMASK'
  opmask[OP_RKEYS       ] = 0;  /* keys on reference */ \
         ^
plperl.c:475:2: error: use of undeclared identifier 'OP_RVALUES'
./plperl_opmask.h:225:10: note: expanded from macro 'PLPERL_SET_OPMASK'
  opmask[OP_RVALUES     ] = 0;  /* values on reference */ \
         ^
plperl.c:1780:25: warning: expression which evaluates to zero treated as a null
      pointer constant of type 'void *' [-Wnon-literal-null-conversion]
        pl_error_context.arg = (Datum) 0;
                               ^~~~~~~~~
1 warning and 4 errors generated.
make[3]: *** [plperl.o] Error 1
make[2]: *** [all] Error 1
make[1]: *** [all] Error 2
make: *** [all] Error 2

how can i proceed?

best wishes,
yang

**Comment by asimrp** [comment]
@sdyajian I am able to compile HEAD of master as well as 6X_STABLE correctly using parallel make.  Can you double check if there are any local modifications in your repository?  What version are you trying to compile (branch@<commit_sha>)?

**Comment by sdyajian** [comment]
hi Asimrp,
i did no change on local repository.
The version of GPDB is 5.19.0 that i am trying to compile. 

1. download GPDB and install dependencies
2. configure build environment via,
./configure --disable-orca --with-perl --with-python --with-libxml --prefix=/usr/local/gpdb --disable-gpfdist
(--disable-gpfdist, reason for adding this option is because "error: apr-1-config is required for gpfdist, unable to find binary".)
3. Compiling via,
make -j8

best wishes,
Yang

**Comment by berlin-ab** [comment]
```
 2019-06-17 10:14:10 ⌚  Adams-MBP in ~/workspace/gpdb5
± |5X_STABLE ✓| → ./configure --disable-orca --with-perl --with-python --with-libxml --prefix=$HOME/some-five-installation --disable-gpfdist

 2019-06-17 10:14:21 ⌚  Adams-MBP in ~/workspace/gpdb5
± |backport-error-on-insert-segno-negative-one ✓| → cat VERSION
5.19.0+dev.38.g0cdf2a0666 build dev

± |5X_STABLE ✓| → make -j8 -s
config.status: creating src/interfaces/ecpg/include/ecpg_config.h
config.status: src/interfaces/ecpg/include/ecpg_config.h is unchanged
Greenplum INCLUDEDIR:    /Users/adamberlin/workspace/gpdb5/gpAux/greenplum-db-devel/include
Greenplum PKGINCLUDEDIR: /Users/adamberlin/workspace/gpdb5/gpAux/greenplum-db-devel/include/postgresql
Checking includes...
Include files are ok
gpcloud enabled
pxf enabled
Configuration not enabled for gpperfmon.
All of Greenplum Database successfully made. Ready to install.
```

**Comment by jchampio** [comment]
Just to be clear, if you remove `-j8`, does everything work? Or do you keep getting the same error?

> `error: use of undeclared identifier 'OP_PUSHRE'; did you mean
'OP_PUSH'?`

This error makes it seem like pl/Perl is being compiled against a different version of Perl than the one that generated `plperl_opmask.h`. Do you have multiple Perls installed? What is the `PERL` variable set to in your `src/Makefile.global`?

**Comment by sdyajian** [comment]
> Hi Yang,
> Here's my attempt to follow your steps:
> 
> ```
>  2019-06-17 10:14:10 ⌚  Adams-MBP in ~/workspace/gpdb5
> ± |5X_STABLE ✓| → ./configure --disable-orca --with-perl --with-python --with-libxml --prefix=$HOME/some-five-installation --disable-gpfdist
> 
>  2019-06-17 10:14:21 ⌚  Adams-MBP in ~/workspace/gpdb5
> ± |backport-error-on-insert-segno-negative-one ✓| → cat VERSION
> 5.19.0+dev.38.g0cdf2a0666 build dev
> 
> ± |5X_STABLE ✓| → make -j8 -s
> config.status: creating src/interfaces/ecpg/include/ecpg_config.h
> config.status: src/interfaces/ecpg/include/ecpg_config.h is unchanged
> Greenplum INCLUDEDIR:    /Users/adamberlin/workspace/gpdb5/gpAux/greenplum-db-devel/include
> Greenplum PKGINCLUDEDIR: /Users/adamberlin/workspace/gpdb5/gpAux/greenplum-db-devel/include/postgresql
> Checking includes...
> Include files are ok
> gpcloud enabled
> pxf enabled
> Configuration not enabled for gpperfmon.
> All of Greenplum Database successfully made. Ready to install.
> ```

**Comment by sdyajian** [comment]
hi @jchampio,

here is my PERL variable,
# Perl

ifneq (/usr/local/bin/perl,)
    # quoted to protect pathname with spaces
    PERL		= "/usr/local/bin/perl"
else
    PERL		= $(missing) perl
endif
perl_archlibexp		= /usr/local/Cellar/perl/5.30.0/lib/perl5/5.30.0/darwin-thread-multi-2level
perl_privlibexp		= /usr/local/Cellar/perl/5.30.0/lib/perl5/5.30.0
perl_useshrplib		= true
perl_embed_ldflags	=   -mmacosx-version-min=10.14 -fstack-protector-strong -L/usr/local/lib  -L/usr/local/Cellar/perl/5.30.0/lib/perl5/5.30.0/darwin-thread-multi-2level/CORE -lperl -lpthread -ldl -lm -lutil -lc


> Just to be clear, if you remove `-j8`, does everything work? Or do you keep getting the same error?
> 
> > `error: use of undeclared identifier 'OP_PUSHRE'; did you mean 'OP_PUSH'?`
> 
> This error makes it seem like pl/Perl is being compiled against a different version of Perl than the one that generated `plperl_opmask.h`. Do you have multiple Perls installed? What is the `PERL` variable set to in your `src/Makefile.global`?

**Comment by sdyajian** [comment]
hi @berlin-ab ,
thanks, and it produce the same error.
best wishes,
yang

**Comment by jchampio** [comment]
(I'm assuming this was closed by mistake, so I'm reopening.)

I wonder if you recently upgraded Perl to a slightly incompatible version? `5.30.0` has some changes that I'm having problems with on my machine as well. What happens if you run
```
$ rm src/pl/plperl/plperl_opmask.h
$ make -j8
```
from the repository root?

**Comment by sdyajian** [comment]
hi Jacob,

after running the provided commands, it fails with the output as below,

C02YC2NMJHD3:gpdb-5.19.0 i076014$ rm src/pl/plperl/plperl_opmask.h
C02YC2NMJHD3:gpdb-5.19.0 i076014$ make -j8
/Library/Developer/CommandLineTools/usr/bin/make -C src all
/Library/Developer/CommandLineTools/usr/bin/make -C port all
make[2]: Nothing to be done for `all'.
/Library/Developer/CommandLineTools/usr/bin/make -C timezone all
/Library/Developer/CommandLineTools/usr/bin/make -C ../../src/port all
make[3]: Nothing to be done for `all'.
/Library/Developer/CommandLineTools/usr/bin/make -C backend all
/Library/Developer/CommandLineTools/usr/bin/make -C ../../src/port all
make[3]: Nothing to be done for `all'.
/Library/Developer/CommandLineTools/usr/bin/make -C access all
/Library/Developer/CommandLineTools/usr/bin/make -C bootstrap all
/Library/Developer/CommandLineTools/usr/bin/make -C catalog all
/Library/Developer/CommandLineTools/usr/bin/make -C parser all
/Library/Developer/CommandLineTools/usr/bin/make -C commands all
/Library/Developer/CommandLineTools/usr/bin/make -C executor all
/Library/Developer/CommandLineTools/usr/bin/make -C fts all
/Library/Developer/CommandLineTools/usr/bin/make -C lib all
/Library/Developer/CommandLineTools/usr/bin/make -C common all
make[3]: Nothing to be done for `all'.
/Library/Developer/CommandLineTools/usr/bin/make -C libpq all
make[3]: Nothing to be done for `all'.
/Library/Developer/CommandLineTools/usr/bin/make -C main all
make[3]: Nothing to be done for `all'.
/Library/Developer/CommandLineTools/usr/bin/make -C gist all
make[3]: Nothing to be done for `all'.
/Library/Developer/CommandLineTools/usr/bin/make -C hash all
make[3]: Nothing to be done for `all'.
/Library/Developer/CommandLineTools/usr/bin/make -C nodes all
make[4]: Nothing to be done for `all'.
make[4]: Nothing to be done for `all'.
/Library/Developer/CommandLineTools/usr/bin/make -C heap all
/Library/Developer/CommandLineTools/usr/bin/make -C optimizer all
make[3]: Nothing to be done for `all'.
/Library/Developer/CommandLineTools/usr/bin/make -C port all
make[4]: Nothing to be done for `all'.
/Library/Developer/CommandLineTools/usr/bin/make -C index all
make[3]: Nothing to be done for `all'.
/Library/Developer/CommandLineTools/usr/bin/make -C postmaster all
make[3]: Nothing to be done for `all'.
/Library/Developer/CommandLineTools/usr/bin/make -C path all
/Library/Developer/CommandLineTools/usr/bin/make -C regex all
make[4]: Nothing to be done for `all'.
make[3]: Nothing to be done for `all'.
/Library/Developer/CommandLineTools/usr/bin/make -C nbtree all
make[3]: Nothing to be done for `all'.
/Library/Developer/CommandLineTools/usr/bin/make -C replication all
/Library/Developer/CommandLineTools/usr/bin/make -C plan all
/Library/Developer/CommandLineTools/usr/bin/make -C darwin all
make[4]: Nothing to be done for `all'.
/Library/Developer/CommandLineTools/usr/bin/make -C transam all
make[4]: Nothing to be done for `all'.
/Library/Developer/CommandLineTools/usr/bin/make -C prep all
make[3]: Nothing to be done for `all'.
/Library/Developer/CommandLineTools/usr/bin/make -C rewrite all
make[3]: Nothing to be done for `all'.
/Library/Developer/CommandLineTools/usr/bin/make -C external all
make[4]: Nothing to be done for `all'.
/Library/Developer/CommandLineTools/usr/bin/make -C util all
make[4]: Nothing to be done for `all'.
/Library/Developer/CommandLineTools/usr/bin/make -C gin all
make[3]: Nothing to be done for `all'.
/Library/Developer/CommandLineTools/usr/bin/make -C storage all
make[4]: Nothing to be done for `all'.
/Library/Developer/CommandLineTools/usr/bin/make -C bitmap all
make[4]: Nothing to be done for `all'.
make[4]: Nothing to be done for `all'.
make[4]: Nothing to be done for `all'.
/Library/Developer/CommandLineTools/usr/bin/make -C tcop all
make[3]: Nothing to be done for `all'.
/Library/Developer/CommandLineTools/usr/bin/make -C appendonly all
/Library/Developer/CommandLineTools/usr/bin/make -C tsearch all
make[4]: Nothing to be done for `all'.
/Library/Developer/CommandLineTools/usr/bin/make -C aocs all
/Library/Developer/CommandLineTools/usr/bin/make -C utils all
make[4]: Nothing to be done for `all'.
/Library/Developer/CommandLineTools/usr/bin/make -C ../../src/timezone all
/Library/Developer/CommandLineTools/usr/bin/make -C buffer all
make[4]: Nothing to be done for `all'.
/Library/Developer/CommandLineTools/usr/bin/make -C cdb all
make[4]: Nothing to be done for `all'.
/Library/Developer/CommandLineTools/usr/bin/make -C file all
make[3]: Nothing to be done for `all'.
/Library/Developer/CommandLineTools/usr/bin/make -C freespace all
make[4]: Nothing to be done for `all'.
make[3]: Nothing to be done for `all'.
/Library/Developer/CommandLineTools/usr/bin/make -C adt all
/Library/Developer/CommandLineTools/usr/bin/make -C ipc all
/Library/Developer/CommandLineTools/usr/bin/make -C cache all
/Library/Developer/CommandLineTools/usr/bin/make -C ../../src/port all
make[4]: Nothing to be done for `all'.
/Library/Developer/CommandLineTools/usr/bin/make -C large_object all
make[4]: Nothing to be done for `all'.
/Library/Developer/CommandLineTools/usr/bin/make -C lmgr all
/Library/Developer/CommandLineTools/usr/bin/make -C motion all
make[4]: Nothing to be done for `all'.
/Library/Developer/CommandLineTools/usr/bin/make -C datumstream all
make[4]: Nothing to be done for `all'.
/Library/Developer/CommandLineTools/usr/bin/make -C page all
make[4]: Nothing to be done for `all'.
make[4]: Nothing to be done for `all'.
/Library/Developer/CommandLineTools/usr/bin/make -C error all
/Library/Developer/CommandLineTools/usr/bin/make -C dispatcher all
make[4]: Nothing to be done for `all'.
/Library/Developer/CommandLineTools/usr/bin/make -C smgr all
make[4]: Nothing to be done for `all'.
/Library/Developer/CommandLineTools/usr/bin/make -C fmgr all
make[4]: Nothing to be done for `all'.
make[4]: Nothing to be done for `all'.
/Library/Developer/CommandLineTools/usr/bin/make -C hash all
make[4]: Nothing to be done for `all'.
/Library/Developer/CommandLineTools/usr/bin/make -C init all
make[4]: Nothing to be done for `all'.
/Library/Developer/CommandLineTools/usr/bin/make -C mb all
make[4]: Nothing to be done for `all'.
make[4]: Nothing to be done for `all'.
/Library/Developer/CommandLineTools/usr/bin/make -C misc all
make[4]: Nothing to be done for `all'.
/Library/Developer/CommandLineTools/usr/bin/make -C mmgr all
make[4]: Nothing to be done for `all'.
/Library/Developer/CommandLineTools/usr/bin/make -C resowner all
make[4]: Nothing to be done for `all'.
/Library/Developer/CommandLineTools/usr/bin/make -C resgroup all
/Library/Developer/CommandLineTools/usr/bin/make -C resscheduler all
make[4]: Nothing to be done for `all'.
/Library/Developer/CommandLineTools/usr/bin/make -C sort all
/Library/Developer/CommandLineTools/usr/bin/make -C time all
make[4]: Nothing to be done for `all'.
/Library/Developer/CommandLineTools/usr/bin/make -C gpmon all
/Library/Developer/CommandLineTools/usr/bin/make -C fstream all
make[4]: Nothing to be done for `all'.
make[4]: Nothing to be done for `all'.
/Library/Developer/CommandLineTools/usr/bin/make -C gp all
make[4]: Nothing to be done for `all'.
/Library/Developer/CommandLineTools/usr/bin/make -C workfile_manager all
make[4]: Nothing to be done for `all'.
/Library/Developer/CommandLineTools/usr/bin/make -C resource_manager all
/Library/Developer/CommandLineTools/usr/bin/make -C hyperloglog all
make[4]: Nothing to be done for `all'.
make[4]: Nothing to be done for `all'.
make[4]: Nothing to be done for `all'.
make[5]: Nothing to be done for `all'.
make[4]: Nothing to be done for `all'.
make[4]: Nothing to be done for `all'.
make[4]: Nothing to be done for `all'.
make[4]: Nothing to be done for `all'.
/Library/Developer/CommandLineTools/usr/bin/make -C backend/utils/mb/conversion_procs all
make[3]: Nothing to be done for `all'.
make[3]: Nothing to be done for `all'.
make[3]: Nothing to be done for `all'.
make[3]: Nothing to be done for `all'.
make[3]: Nothing to be done for `all'.
make[3]: Nothing to be done for `all'.
make[3]: Nothing to be done for `all'.
make[3]: Nothing to be done for `all'.
make[3]: Nothing to be done for `all'.
make[3]: Nothing to be done for `all'.
make[3]: Nothing to be done for `all'.
make[3]: Nothing to be done for `all'.
make[3]: Nothing to be done for `all'.
make[3]: Nothing to be done for `all'.
make[3]: Nothing to be done for `all'.
make[3]: Nothing to be done for `all'.
make[3]: Nothing to be done for `all'.
make[3]: Nothing to be done for `all'.
make[3]: Nothing to be done for `all'.
make[3]: Nothing to be done for `all'.
make[3]: Nothing to be done for `all'.
make[3]: Nothing to be done for `all'.
make[3]: Nothing to be done for `all'.
make[3]: Nothing to be done for `all'.
make[3]: Nothing to be done for `all'.
make[3]: Nothing to be done for `all'.
/Library/Developer/CommandLineTools/usr/bin/make -C backend/snowball all
make[2]: Nothing to be done for `all'.
/Library/Developer/CommandLineTools/usr/bin/make -C include all
(cd /Users/i076014/GPDB/gpdb-5.19.0/src/include/catalog/ && ./duplicate_oids) 
/Library/Developer/CommandLineTools/usr/bin/make -C interfaces all
make[3]: Nothing to be done for `all'.
/Library/Developer/CommandLineTools/usr/bin/make -C include all
cd ../../../.. && ./config.status src/interfaces/ecpg/include/ecpg_config.h
config.status: creating src/interfaces/ecpg/include/ecpg_config.h
config.status: src/interfaces/ecpg/include/ecpg_config.h is unchanged
/Library/Developer/CommandLineTools/usr/bin/make -C pgtypeslib all
make[4]: Nothing to be done for `all'.
/Library/Developer/CommandLineTools/usr/bin/make -C ecpglib all
/Library/Developer/CommandLineTools/usr/bin/make -C ../../../../src/interfaces/libpq all
/Library/Developer/CommandLineTools/usr/bin/make -C ../../../../src/interfaces/ecpg/pgtypeslib all
make[5]: Nothing to be done for `all'.
make[5]: Nothing to be done for `all'.
/Library/Developer/CommandLineTools/usr/bin/make -C compatlib all
make[4]: Nothing to be done for `all'.
/Library/Developer/CommandLineTools/usr/bin/make -C preproc all
/Library/Developer/CommandLineTools/usr/bin/make -C ../../../../src/port all
make[5]: Nothing to be done for `all'.
make[3]: Nothing to be done for `all'.
/Library/Developer/CommandLineTools/usr/bin/make -C bin all
/Library/Developer/CommandLineTools/usr/bin/make -C ../../../src/port all
make[4]: Nothing to be done for `all'.
make[3]: Nothing to be done for `all'.
/Library/Developer/CommandLineTools/usr/bin/make -C ../../../src/interfaces/libpq all
/Library/Developer/CommandLineTools/usr/bin/make -C ../../../src/port all
make[4]: Nothing to be done for `all'.
make[4]: Nothing to be done for `all'.
/Library/Developer/CommandLineTools/usr/bin/make -C ../../../src/interfaces/libpq all
/Library/Developer/CommandLineTools/usr/bin/make -C ../../../src/port all
make[4]: Nothing to be done for `all'.
make[4]: Nothing to be done for `all'.
/Library/Developer/CommandLineTools/usr/bin/make -C ../../../src/interfaces/libpq all
/Library/Developer/CommandLineTools/usr/bin/make -C ../../../src/port all
/Library/Developer/CommandLineTools/usr/bin/make -C cdb all
make[4]: Nothing to be done for `all'.
make[4]: Nothing to be done for `all'.
/Library/Developer/CommandLineTools/usr/bin/make -C ../../../../src/interfaces/libpq all
/Library/Developer/CommandLineTools/usr/bin/make -C ../../../../src/port all
make[5]: Nothing to be done for `all'.
make[5]: Nothing to be done for `all'.
/Library/Developer/CommandLineTools/usr/bin/make -C ../../../src/interfaces/libpq all
/Library/Developer/CommandLineTools/usr/bin/make -C ../../../src/port all
make[4]: Nothing to be done for `all'.
make[4]: Nothing to be done for `all'.
/Library/Developer/CommandLineTools/usr/bin/make -C ../../../src/interfaces/libpq all
/Library/Developer/CommandLineTools/usr/bin/make -C ../../../src/port all
make[4]: Nothing to be done for `all'.
make[4]: Nothing to be done for `all'.
/Library/Developer/CommandLineTools/usr/bin/make -C ../../../src/port all
make[4]: Nothing to be done for `all'.
/Library/Developer/CommandLineTools/usr/bin/make -C ../../../src/port all
make[4]: Nothing to be done for `all'.
/Library/Developer/CommandLineTools/usr/bin/make -C ../../../src/port all
make[4]: Nothing to be done for `all'.
/Library/Developer/CommandLineTools/usr/bin/make -C ../../../src/interfaces/libpq all
/Library/Developer/CommandLineTools/usr/bin/make -C ../../../src/port all
/Library/Developer/CommandLineTools/usr/bin/make -C ../../../src/backend/libpq ip.o
make[4]: `ip.o' is up to date.
make[4]: Nothing to be done for `all'.
make[4]: Nothing to be done for `all'.
/Library/Developer/CommandLineTools/usr/bin/make -C pl all
/Library/Developer/CommandLineTools/usr/bin/make -C src all
make[4]: Nothing to be done for `all'.
"/usr/local/bin/perl" plperl_opmask.pl plperl_opmask.h
gcc -O3 -std=gnu99  -Wall -Wmissing-prototypes -Wpointer-arith -Wendif-labels -Wformat-security -fno-strict-aliasing -fwrapv -Wno-address -Wno-unused-command-line-argument   -I. -I. -I../../../src/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/libxml2  -I/usr/local/Cellar/perl/5.30.0/lib/perl5/5.30.0/darwin-thread-multi-2level/CORE  -c -o plperl.o plperl.c
plperl.c:1780:25: warning: expression which evaluates to zero treated as a null
      pointer constant of type 'void *' [-Wnon-literal-null-conversion]
        pl_error_context.arg = (Datum) 0;
                               ^~~~~~~~~
1 warning generated.
gcc -O3 -std=gnu99  -Wall -Wmissing-prototypes -Wpointer-arith -Wendif-labels -Wformat-security -fno-strict-aliasing -fwrapv -Wno-address -Wno-unused-command-line-argument   -bundle -multiply_defined suppress  plperl.o SPI.o Util.o -bundle_loader ../../../src/backend/postgres -L/usr/local/lib -L/usr/local/Cellar/perl/5.30.0/lib/perl5/5.30.0/darwin-thread-multi-2level/CORE -L../../../src/port -L../../../src/port -L/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/lib -mmacosx-version-min=10.14 -fstack-protector-strong -lperl -lpthread -ldl -lm -lutil -lc  -o plperl.so
make[3]: Nothing to be done for `all'.
/Library/Developer/CommandLineTools/usr/bin/make -C makefiles all
make[2]: Nothing to be done for `all'.
/Library/Developer/CommandLineTools/usr/bin/make -C test/regress all
/Library/Developer/CommandLineTools/usr/bin/make -C ../../../src/port all
gcc -O3 -std=gnu99  -Wall -Wmissing-prototypes -Wpointer-arith -Wendif-labels -Wformat-security -fno-strict-aliasing -fwrapv -Wno-address -Wno-unused-command-line-argument   -I../../../src/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/libxml2  -I../../../src/port '-DHOST_TUPLE="x86_64-apple-darwin18.6.0"' '-DMAKEPROG="/Library/Developer/CommandLineTools/usr/bin/make"' '-DSHELLPROG="/bin/sh"' '-DDLSUFFIX=".so"' -c -o pg_regress.o pg_regress.c
gcc -O3 -std=gnu99  -Wall -Wmissing-prototypes -Wpointer-arith -Wendif-labels -Wformat-security -fno-strict-aliasing -fwrapv -Wno-address -Wno-unused-command-line-argument   -bundle -multiply_defined suppress  regress.o regress_gp.o partindex.o workfile_mgr_test.o -bundle_loader ../../../src/backend/postgres  -L../../../src/port -L../../../src/port -L/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/lib   -o regress.so
/Library/Developer/CommandLineTools/usr/bin/make -C ../../../contrib/spi refint.so autoinc.so
rm -rf ./testtablespace
./checkinc.py
make[3]: Nothing to be done for `all'.
mkdir ./testtablespace
/Library/Developer/CommandLineTools/usr/bin/make -C  hooktest
/Library/Developer/CommandLineTools/usr/bin/make -C  query_info_hook_test
make[3]: `refint.so' is up to date.
make[3]: `autoinc.so' is up to date.
gcc -O3 -std=gnu99  -Wall -Wmissing-prototypes -Wpointer-arith -Wendif-labels -Wformat-security -fno-strict-aliasing -fwrapv -Wno-address -Wno-unused-command-line-argument   -I. -I. -I../../../../src/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/libxml2   -c -o query_info_hook_test.o query_info_hook_test.c
gcc -O3 -std=gnu99  -Wall -Wmissing-prototypes -Wpointer-arith -Wendif-labels -Wformat-security -fno-strict-aliasing -fwrapv -Wno-address -Wno-unused-command-line-argument   -I. -I. -I../../../../src/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/libxml2   -c -o hook_test.o hook_test.c
Greenplum INCLUDEDIR:    /usr/local/gpdb/include
Greenplum PKGINCLUDEDIR: /usr/local/gpdb/include/postgresql
Checking includes...
gcc -O3 -std=gnu99  -Wall -Wmissing-prototypes -Wpointer-arith -Wendif-labels -Wformat-security -fno-strict-aliasing -fwrapv -Wno-address -Wno-unused-command-line-argument   -bundle -multiply_defined suppress  hook_test.o -bundle_loader ../../../../src/backend/postgres  -L../../../../src/port -L../../../../src/port -L/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/lib   -o test_hook.so
gcc -O3 -std=gnu99  -Wall -Wmissing-prototypes -Wpointer-arith -Wendif-labels -Wformat-security -fno-strict-aliasing -fwrapv -Wno-address -Wno-unused-command-line-argument   -bundle -multiply_defined suppress  query_info_hook_test.o -bundle_loader ../../../../src/backend/postgres  -L../../../../src/port -L../../../../src/port -L/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/lib   -o query_info_hook_test.so
  access/xlog_internal.h         includes missing file "time.h" 
  access/xlogdefs.h              includes missing file "fcntl.h" 
  c.h                            includes missing file "stdio.h" 
  c.h                            includes missing file "stdlib.h" 
  c.h                            includes missing file "string.h" 
  c.h                            includes missing file "strings.h" 
  c.h                            includes missing file "errno.h" 
  c.h                            includes missing file "fcntl.h" 
  c.h                            includes missing file "locale.h" 
  c.h                            includes missing file "unistd.h" 
  catalog/pg_control.h           includes missing file "time.h" 
  cdb/cdbfilerep.h               includes missing file "signal.h" 
  cdb/cdbgang.h                  includes missing file "pthread.h" 
  cdb/cdbicudpfaultinjection.h   includes missing file "poll.h" 
  cdb/cdbutil.h                  includes missing file "math.h" 
  getaddrinfo.h                  includes missing file "netdb.h" 
  libpq-int.h                    includes missing file "time.h" 
  libpq-int.h                    includes missing file "pthread.h" 
  libpq-int.h                    includes missing file "signal.h" 
  libpq/libpq-be.h               includes missing file "netinet/tcp.h" 
  libpq/libpq.h                  includes missing file "netinet/in.h" 
  libpq/pqcomm.h                 includes missing file "netdb.h" 
  libpq/pqcomm.h                 includes missing file "netinet/in.h" 
  libpq/pqsignal.h               includes missing file "signal.h" 
  port.h                         includes missing file "ctype.h" 
  port.h                         includes missing file "netdb.h" 
  port.h                         includes missing file "pwd.h" 
  port.h                         includes missing file "netinet/in.h" 
  port.h                         includes missing file "arpa/inet.h" 
  port/atomics.h                 includes missing file "limits.h" 
  port/win32.h                   includes missing file "signal.h" 
  port/win32.h                   includes missing file "errno.h" 
  port/win32_msvc/bzlib.h        includes missing file "stdio.h" 
  postmaster/syslogger.h         includes missing file "limits.h" 
  regex/regcustom.h              includes missing file "ctype.h" 
  regex/regcustom.h              includes missing file "limits.h" 
  regex/regcustom.h              includes missing file "wchar.h" 
  regex/regcustom.h              includes missing file "wctype.h" 
  regex/regguts.h                includes missing file "assert.h" 
  regex/regguts.h                includes missing file "limits.h" 
  replication/walsender.h        includes missing file "signal.h" 
  rusagestub.h                   includes missing file "limits.h" 
  snowball/libstemmer/header.h   includes missing file "limits.h" 
  storage/fd.h                   includes missing file "dirent.h" 
  storage/gp_compress.h          includes missing file "zlib.h" 
  storage/latch.h                includes missing file "signal.h" 
  storage/pg_sema.h              includes missing file "semaphore.h" 
  storage/pg_sema.h              includes missing file "semaphore.h" 
  tsearch/ts_locale.h            includes missing file "ctype.h" 
  tsearch/ts_locale.h            includes missing file "limits.h" 
  tsearch/ts_locale.h            includes missing file "wchar.h" 
  tsearch/ts_locale.h            includes missing file "wctype.h" 
  utils/date.h                   includes missing file "math.h" 
  utils/datetime.h               includes missing file "limits.h" 
  utils/datetime.h               includes missing file "math.h" 
  utils/elog.h                   includes missing file "setjmp.h" 
  utils/elog.h                   includes missing file "pthread.h" 
  utils/geo_decls.h              includes missing file "math.h" 
  utils/nabstime.h               includes missing file "limits.h" 
  utils/pg_locale.h              includes missing file "locale.h" 
  utils/string_wrapper.h         includes missing file "string.h" 
  utils/string_wrapper.h         includes missing file "errno.h" 
  utils/timestamp.h              includes missing file "math.h" 
  utils/timestamp.h              includes missing file "limits.h" 
  utils/varbit.h                 includes missing file "limits.h" 
  utils/zlib_wrapper.h           includes missing file "zlib.h" 
Include files... FAILED
make[2]: *** [includecheck] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [all] Error 2
make: *** [all] Error 2

**Comment by jchampio** [comment]
Okay, good. So the 5.30 environment was part of the problem, but now we're on to a new problem.

The above output indicates that `src/test/regress/checkinc.py` is failing. That script looks for header files in `/usr/include`, but your compilation lines indicate that you're using XCode 10, and XCode 10 [no longer installs headers into `/usr/include` by default](https://developer.apple.com/documentation/xcode_release_notes/xcode_10_release_notes#3035624). (Many developers here haven't jumped to XCode 10 yet due to other issues with High Sierra and beyond, so you may be blazing a trail here.) 

As a workaround, you might try to install the package listed in those linked instructions (`/Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg`) and see if that gets you any farther? Thanks for your patience and time in reporting these issues!

**Comment by sdyajian** [comment]
> Okay, good. So the 5.30 environment was part of the problem, but now we're on to a new problem.
> 
> The above output indicates that `src/test/regress/checkinc.py` is failing. That script looks for header files in `/usr/include`, but your compilation lines indicate that you're using XCode 10, and XCode 10 [no longer installs headers into `/usr/include` by default](https://developer.apple.com/documentation/xcode_release_notes/xcode_10_release_notes#3035624). (Many developers here haven't jumped to XCode 10 yet due to other issues with High Sierra and beyond, so you may be blazing a trail here.)
Hi Jacob,
thanks a lot.
that solves my problem, and I have built and installed GPDB successfully.

thanks.

best wishes,
yang 
> 
> As a workaround, you might try to install the package listed in those linked instructions (`/Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg`) and see if that gets you any farther? Thanks for your patience and time in reporting these issues!

**Comment by jchampio** [comment]
@sdyajian Great to hear! Thanks again for filing the issue.
