### ISSUE TITLE
Greenplum table growth very large（several hundred GB） because frequently delete rows and insert rows 

### ISSUE THREAD

**Issue by zengyongping** [greenplum-db/gpdb#7909]
### Greenplum version or build
PostgreSQL 8.3.23 (Greenplum Database 5.11.3 build commit:079ca994a1120ff7e46101163a29bb6ff2b0b14a) on x86_64-pc-linux-gnu, compiled by GCC gcc (GCC) 6.2.0, 64-bit compiled on Oct  9 2018 18:36:51
### OS version and uname -a
CentOS 7.2   x86_64

### Expected behavior
auto shrink table size ,like Hbase compact
### Actual behavior
table size growth larger ,well do create table <new_table> as select * from <old_table> ,then drop old_talbe,rename new_table to old_table name, the process is tedious,let me think Greenplum is a bad HTAP solution

**Comment by ashwinstar** [comment]
I don't think there are any plans to auto-shrink the tables. Please perform `vacuum full` to shrink the size of the table, as fits in your workload.
