### ISSUE TITLE
NOT IN query fails with "Unexpected internal error"

### ISSUE THREAD

**Issue by hlinnaka** [greenplum-db/gpdb#791]
postgres=# select * from gp_relation_node where persistent_tid not in (select ctid from gp_persistent_relation_node);
ERROR:  Unexpected internal error (nodeMergejoin.c:1685)

**Comment by vraghavan78** [comment]
Thanks @hlinnaka. Was able to reproduce this issue.

With Planner:
``
vraghavan=# explain select * from gp_relation_node where persistent_tid not in (select ctid from gp_persistent_relation_node);
ERROR:  Unexpected internal error (nodeMergejoin.c:1685)
``
With Orca:
``
set optimizer = on;
set optimizer_enable_master_only_queries = on;
vraghavan=# explain select * from gp_relation_node where persistent_tid not in (select ctid from gp_persistent_relation_node);
                                                      QUERY PLAN
-----------------------------------------------------------------------------------------------------------------------
 Table Scan on gp_relation_node  (cost=0.00..1324215.65 rows=77 width=30)
   Filter: (subplan)
   SubPlan 1
     ->  Result  (cost=0.00..431.13 rows=1 width=1)
           ->  Result  (cost=0.00..431.13 rows=1 width=1)
                 Filter: "ColRef_0042" = true
                 ->  Result  (cost=0.00..431.12 rows=1 width=1)
                       ->  Aggregate  (cost=0.00..431.12 rows=1 width=16)
                             ->  Result  (cost=0.00..431.12 rows=458 width=8)
                                   ->  Table Scan on gp_persistent_relation_node  (cost=0.00..431.09 rows=458 width=6)
 Settings:  optimizer=on
 Optimizer status: PQO version 1.633
(12 rows)
``

Will create an issue in the QP tracker.

**Comment by vraghavan78** [comment]
Resolved.
```
vraghavan=# explain select * from gp_relation_node where persistent_tid not in (select ctid from gp_persistent_relation_node);
                                           QUERY PLAN
-------------------------------------------------------------------------------------------------
 Nested Loop Left Anti Semi Join (Not-In)  (cost=66.70..15014.66 rows=12 width=30)
   Join Filter: gp_relation_node.persistent_tid = "NotIn_SUBQUERY".ctid
   ->  Seq Scan on gp_relation_node  (cost=0.00..3.46 rows=246 width=30)
         Filter: persistent_tid IS NOT NULL
   ->  Materialize  (cost=66.70..93.70 rows=900 width=6)
         ->  Subquery Scan "NotIn_SUBQUERY"  (cost=0.00..64.00 rows=2700 width=6)
               ->  Seq Scan on gp_persistent_relation_node  (cost=0.00..37.00 rows=2700 width=6)
 Optimizer status: legacy query optimizer
(8 rows)

vraghavan=#  select * from gp_relation_node where persistent_tid not in (select ctid from gp_persistent_relation_node);
 relfilenode_oid | segment_file_num | create_mirror_data_loss_tracking_session_num | persistent_tid | persistent_serial_num
-----------------+------------------+----------------------------------------------+----------------+-----------------------
(0 rows)
```
