### ISSUE TITLE
gppkg Behave tests do not appear to work on Ubuntu

### ISSUE THREAD

**Issue by dkrieger-pvtl** [greenplum-db/gpdb#7921]
We rewrote the sample.gppkg datafile for the Behave tests to work on Ubuntu.  This leads
to an inconsistent state where we can neither remove it nor reinstall it.

For context, we are enabling the Behave tests to run in our pipeline for Ubuntu18.04 and the existing gppkg tests failed(since we were installing an rpm). So we converted the rpm to a deb and rebuilt the sample.gppkg file.  But then we ran into the problem below.

### Greenplum version or build
GPDB-6 master

### OS version and uname -a
Ubuntu18.04

### Expected behavior
tests succeed

### Actual behavior
package system is in an inconsistent state...package says it is installed but then we cannot remove it.

### Step to reproduce the behavior
For the gppkg behave tests, the tests don't work with this file substituted in for the sample.gppkg file(centos).  We converted the rpm inside that file to a deb using `alien`.  To be explicit, over-write your sample.gppkg file for the behave test with this one:

https://github.com/slari-pivotal/gpdb/blob/ubuntu18__cli_pipeline_165299587/gpMgmt/test/behave/mgmt_utils/steps/data/sample.gppkg

### Details
```
gppkg --install test/behave/mgmt_utils/steps/data/sample.gppkg
20190612:22:37:54:016451 gppkg:mdw:gpadmin-[INFO]:-Starting gppkg with args: --install test/behave/mgmt_utils/steps/data/sample.gppkg
20190612:22:37:54:016451 gppkg:mdw:gpadmin-[INFO]:-Installing package sample.gppkg
20190612:22:37:54:016451 gppkg:mdw:gpadmin-[INFO]:-Validating deb installation cmdStr='fakeroot dpkg --dry-run --force-not-root --log=/dev/null --admindir=/usr/local/greenplum-db-devel/share/packages/database/deb --instdir=/usr/local/greenplum-db-devel -i /usr/local/greenplum-db-devel/.tmp/sample_0.0.1-1_amd64.deb'
20190612:22:37:54:016451 gppkg:mdw:gpadmin-[INFO]:-Check installation of package cmdStr='dpkg --force-not-root --log=/dev/null --admindir=/usr/local/greenplum-db-devel/share/packages/database/deb --instdir=/usr/local/greenplum-db-devel -l sample'
20190612:22:37:54:016451 gppkg:mdw:gpadmin-[CRITICAL]:-gppkg failed. (Reason='sample is already installed.') exiting...

gppkg -q --all
20190612:22:39:39:016540 gppkg:mdw:gpadmin-[INFO]:-Starting gppkg with args: -q --all
sample

gppkg --remove sample
20190612:22:40:08:016552 gppkg:mdw:gpadmin-[INFO]:-Starting gppkg with args: --remove sample
20190612:22:40:08:016552 gppkg:mdw:gpadmin-[INFO]:-Uninstalling package sample.gppkg
20190612:22:40:08:016552 gppkg:mdw:gpadmin-[CRITICAL]:-gppkg failed. (Reason='list index out of range') exiting...

gppkg --remove test/behave/mgmt_utils/steps/data/sample.gppkg
20190612:22:40:29:016565 gppkg:mdw:gpadmin-[INFO]:-Starting gppkg with args: --remove test/behave/mgmt_utils/steps/data/sample.gppkg
20190612:22:40:29:016565 gppkg:mdw:gpadmin-[ERROR]:-gppkg error: Package test/behave/mgmt_utils/steps/data/sample.gppkg has not been installed.
```

**Comment by gfphoenix78** [comment]
@dkrieger-pvtl sample.gppkg is now a binary file built for centos6 in the repo of gpdb. So, the file is not portable for ubuntu. For centos and ubuntu, gpdb should compile sample.gppkg before running behave test for gppkg. 
There is a bug in the command `gppkg`, that gppkg forces the file name to have at least 2 dashes ('-') when running `gppkg -q --all`. I'll check why it fails when installing.

**Comment by dkrieger-pvtl** [comment]
@gfphoenix78 Yes, the `sample.gppkg` in the master repo is built for centos6, but the one linked above(of the same name `sample.gppkg`) was rebuilt for ubuntu18.  We untar'd the centos6 one, used `alien` to convert the debian, and changed the os field from `rhel6` to `ubuntu18`, and re-tar'd it to create the one linked above.  So we expected it to work, or at least fail in a consistent way.

**Comment by gfphoenix78** [comment]
@dkrieger-pvtl 
* The name format of the internal deb file is assumed to be `<name>-<version>-<rel>.amd64.deb`
* Some part of behave tests about gppkg is required to use ccp, i.e. segment node and master node must have different GPHOME. Because there are some tests assuming that.

You may untar the sample.gppkg and run `mv sample*.deb sample-0.0.1-0.amd64.deb`, re-build sample.gppkg and do the behave test.

**Comment by dkrieger-pvtl** [comment]
https://github.com/greenplum-db/gpdb/pull/8067
https://github.com/greenplum-db/gpdb/pull/8066

resolve this.
