### ISSUE TITLE
\set VERBOSITY verbose is not working

### ISSUE THREAD

**Issue by BaiShaoqi** [greenplum-db/gpdb#7934]
### Greenplum version or build
latest master c30cd3ba99b46802e267f761aa616a1ba0879815
The problem is that presence of the fields ‘SCHEMA NAME’, ‘TABLE NAME’ and ‘CONSTRAINT NAME does not exist when 
### Expected behavior `\set VERBOSITY verbose`
```
postgres=# \set VERBOSITY verbose
postgres=# CREATE TABLE aa (a int PRIMARY KEY);
CREATE TABLE
postgres=# INSERT INTO aa VALUES (1);
INSERT 0 1
postgres=# INSERT INTO aa VALUES (1);
ERROR:  duplicate key value violates unique constraint "aa_pkey"
DETAIL:  Key (a)=(1) already exists.
STATEMENT:  INSERT INTO aa VALUES (1);
ERROR:  23505: duplicate key value violates unique constraint "aa_pkey"
DETAIL:  Key (a)=(1) already exists.
SCHEMA NAME:  public
TABLE NAME:  aa
CONSTRAINT NAME:  aa_pkey
LOCATION:  _bt_check_unique, nbtinsert.c:402
```
### Actual behavior
```
postgres=# \set VERBOSITY verbose
postgres=# CREATE TABLE aa (a int PRIMARY KEY);
CREATE TABLE
postgres=# INSERT INTO aa VALUES (1);
INSERT 0 1
postgres=# INSERT INTO aa VALUES (1);
ERROR:  23505: duplicate key value violates unique constraint "aa_pkey"  (seg1 127.0.0.1:25433 pid=24849)
DETAIL:  Key (a)=(1) already exists.
LOCATION:  _bt_check_unique, nbtinsert.c:500
```

**Comment by hlinnaka** [comment]
We seem to be missing the "errtableconstraint()" calls in the error messages in `_bt_ao_check_unique()` function. They were added in PostgreSQL 9.3 to the `_bt_check_unique()` function, but we have a copy-pasted version of that for AO tables in GPDB, `_bt_ao_check_unique()`, and we missed adding it there in the 9.3 merge.

**Comment by hlinnaka** [comment]
> We seem to be missing the "errtableconstraint()" calls in the error messages in `_bt_ao_check_unique()` function. They were added in PostgreSQL 9.3 to the `_bt_check_unique()` function, but we have a copy-pasted version of that for AO tables in GPDB, `_bt_ao_check_unique()`, and we missed adding it there in the 9.3 merge.

Looking at your fix, looks like that didn't cause this issue. But it seems like a separate issue we should fix, too. (I think you'll run into that one if you repeat the repro from this case with an AO table)

**Comment by BaiShaoqi** [comment]
> > We seem to be missing the "errtableconstraint()" calls in the error messages in `_bt_ao_check_unique()` function. They were added in PostgreSQL 9.3 to the `_bt_check_unique()` function, but we have a copy-pasted version of that for AO tables in GPDB, `_bt_ao_check_unique()`, and we missed adding it there in the 9.3 merge.
> 
> Looking at your fix, looks like that didn't cause this issue. But it seems like a separate issue we should fix, too. (I think you'll run into that one if you repeat the repro from this case with an AO table)

AO/CO table actually does not support uniq contraint, right?  according to https://github.com/greenplum-db/gpdb/blob/master/src/backend/commands/indexcmds.c#L671
Maybe the function `_bt_ao_check_unique` can be deleted ?

**Comment by hlinnaka** [comment]
On 26/07/2019 05:57, Shaoqi Bai wrote:
>         We seem to be missing the "errtableconstraint()" calls in the
>         error messages in |_bt_ao_check_unique()| function. They were
>         added in PostgreSQL 9.3 to the |_bt_check_unique()| function,
>         but we have a copy-pasted version of that for AO tables in GPDB,
>         |_bt_ao_check_unique()|, and we missed adding it there in the
>         9.3 merge.
> 
>     Looking at your fix, looks like that didn't cause this issue. But it
>     seems like a separate issue we should fix, too. (I think you'll run
>     into that one if you repeat the repro from this case with an AO table)
> 
> AO/CO table actually does not support uniq contraint, right? according 
> to 
> https://github.com/greenplum-db/gpdb/blob/master/src/backend/commands/indexcmds.c#L671
> Maybe the function |_bt_ao_check_unique| can be deleted ?

Oh, good point! Yeah, seems like _bt_ao_check_unique() is dead code 
then. +1 on removing it, and perhaps replace it with an elog(ERROR, 
"append-only tables do not support unique indexes") just to be sure we 
never get there.

- Heikki
