### ISSUE TITLE
unsupported frontend protocol 28675.0: server supports 1.0 to 3.0

### ISSUE THREAD

**Issue by BaiShaoqi** [greenplum-db/gpdb#7935]
### Greenplum version or build
latest master c30cd3ba99b46802e267f761aa616a1ba0879815

### Expected behavior
```
postgres=# select * from aa_foreign;
 a | b
---+---
 1 | 1
 1 | 2
 1 | 3
(3 rows)
```

### Actual behavior

Type command on  lastest master gpdb cluster
```
postgres=# select * from aa_foreign;
ERROR:  could not connect to server "postgres_server"
DETAIL:  FATAL:  unsupported frontend protocol 28675.0: server supports 1.0 to 3.0
```

### Step to reproduce the behavior

First create a 9_4_STABLE postgres instance

Then type following command on a  lastest master gpdb cluster
```
cd contrib/postgres_fdw/
make install
```
```
CREATE EXTENSION postgres_fdw;
CREATE SERVER postgres_server FOREIGN DATA WRAPPER postgres_fdw OPTIONS (host 'localhost', port '5432', dbname 'postgres');
CREATE USER MAPPING FOR PUBLIC SERVER postgres_server OPTIONS (password '');
CREATE FOREIGN TABLE aa_foreign (a int, b int) SERVER postgres_server OPTIONS (table_name 'aa');
```

**Comment by jimmyyih** [comment]
I think this is fixed in the 9.5 merge iteration branch... or at least @dgkimura and I played around with postgres_fdw and mostly everything worked.

**Comment by jchampio** [comment]
`28675.0` means we're sending the Greenplum internal protocol version instead of a standard Postgres version, right?

**Comment by d** [comment]
> `28675.0` means we're sending the Greenplum internal protocol version instead of a standard Postgres version, right?

Must be it, that's 0x7300. The frontend protocol normally should set protocol to 0x0300.

One way of fixing this might be to find a way to statically link libpq into Postgres FDW (and hide all those symbols :-S )
