### ISSUE TITLE
trigger failure

### ISSUE THREAD

**Issue by BaiShaoqi** [greenplum-db/gpdb#7938]
### Greenplum version or build
latest master c30cd3ba99b46802e267f761aa616a1ba0879815

### Expected behavior
```
postgres=# DELETE FROM users WHERE name = 'Shaoqi Bai';
DELETE 1
```

### Actual behavior
```
postgres=# DELETE FROM users WHERE name = 'Shaoqi Bai';
ERROR:  function cannot execute on a QE slice because it issues a non-SELECT statement  (seg1 127.0.0.1:25433 pid=66759)
CONTEXT:  SQL statement "DELETE FROM address WHERE address.id_user = OLD.id"
PL/pgSQL function delete_address() line 3 at SQL statement
```
### Step to reproduce the behavior
```
CREATE TABLE users (id int PRIMARY KEY, name varchar(256));

CREATE TABLE address (id_user int, address text);

INSERT INTO users VALUES (1, 'Shaoqi Bai');

INSERT INTO address VALUES (1, 'Home in Yinchuan, China');

CREATE FUNCTION delete_address() RETURNS TRIGGER AS $$
BEGIN
DELETE FROM address WHERE address.id_user = OLD.id;
RETURN OLD;
END $$ LANGUAGE 'plpgsql';

CREATE TRIGGER delete_user_address BEFORE DELETE ON users FOR EACH ROW EXECUTE PROCEDURE delete_address();
```

**Comment by paul-guo-** [comment]
Trigger is just partially (or not officially) supported on Greenplum. This is a known limitation.

**Comment by BaiShaoqi** [comment]
Heard about the trigger is partially supported ,  but the error message is not clear, if it is not supported in the case, should it be printed something like "trigger is paritilly supported, and not work at the condition"?
Or if Trigger function is not supported, the clause `CREATE FUNCTION RETURNS TRIGGER` should just be errored out at advance, so there won't be later trigger failure.

**Comment by berlin-ab** [comment]
@Eulerizeit Thoughts? I'm going to mark this as "do later".

**Comment by adam8157** [comment]
Trigger is not partially supported, it's not supported at all. It just partially works.

Leaving this opened forever doesn't make sense, gonna close it.
