### ISSUE TITLE
gpfdist failing with "SSL is not supported by this build" error, when trying to initialize gpfdist in windows.

### ISSUE THREAD

**Issue by akshay319** [greenplum-db/gpdb#7947]
### Expected behavior 
when trying to start gpfdist in SSL mode through command prompt. It should start the gpfdist process.
cmd syntax used:
"Location of gpfdist.exe" -d "Directory where external table will be created" -p "port number" -l "Log file location" -t "timeout" -m 32768 --ssl "certificate_path" -V

### Actual behavior
It's failing with SSL is not supported by this build error and process is not getting started.

### Step to reproduce the behavior
1) Open Command prompt
2) Try to start gpdfist in ssl mode by below commands
"Location of gpfdist.exe" -d "Directory where external table will be created" -p "port number" -l "Log file location" -t "timeout" -m 32768 --ssl "certificate_path" -V

it will fail with error. I have attached screenshot for reference.
![ssl_issue](https://user-images.githubusercontent.com/21255443/59688860-2b8da500-91fc-11e9-895d-c959bda00486.JPG)

**Comment by pf-qiu** [comment]
It's not supported on 5.

**Comment by akshay319** [comment]
@pf-qiu But according to Greenplum documentation, it's supported.

https://gpdb.docs.pivotal.io/5180/utility_guide/admin_utilities/gpfdist.html

Also, ssl issue is only observed on windows platform. Linux is working fine.

**Comment by pf-qiu** [comment]
It's not supported on Windows. We will update the documentation to mention it.

**Comment by akshay319** [comment]
Thanks for the update

**Comment by weinan003** [comment]
@akshay319 If no further hesitation
