### ISSUE TITLE
5X_STABLE won't build with Perl 5.30

### ISSUE THREAD

**Issue by jchampio** [greenplum-db/gpdb#7949]
### Greenplum version or build
5X_STABLE

### OS version and uname -a
macOS Sierra

### autoconf options used ( config.status --config )
`'--config-cache' '--enable-depend' '--enable-debug' '--disable-pxf' '--disable-cassert' '--with-python' '--prefix=/usr/local/gpdb5' '--with-perl' '--enable-gpperfmon' '--with-gssapi' '--enable-mapreduce' '--disable-gpcloud' '--enable-gpfdist' '--enable-tap-tests' '--enable-orca' '--with-openssl' 'CFLAGS=-g -O0' 'CPPFLAGS=-I/usr/local/opt/openssl/include' 'LDFLAGS=-L/usr/local/opt/openssl/lib'`

### Step to reproduce the behavior
```
$ perl --version

This is perl 5, version 30, subversion 0 (v5.30.0) built for darwin-thread-multi-2level
...

$ make -C src/interfaces/ecpg/preproc/
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C ../../../../src/port all
make[1]: Nothing to be done for `all'.
"/usr/local/bin/perl" ./parse.pl . < ../../../../src/backend/parser/gram.y > preproc.y
Assigning non-zero to $[ is no longer possible at ./parse.pl line 21.
make: *** [preproc.y] Error 255
make: *** Deleting file `preproc.y
```

It looks like 5X's `parse.pl` was backported from a future Postgres branch, but it hasn't been updated to track that branch, and it relies on some long-deprecated Perlisms that 5.30.0 seems to have finally dropped support for.

I'm wondering if #7882 is also due to the 5.30.0 update, but that symptom is different.

**Comment by kainwen** [comment]
Same as https://github.com/greenplum-db/gpdb/issues/8989

But since that issue contains some work-around. Keep that if someone meet the issue.

**Comment by l-wang** [comment]
I came across the same problem with perl v5.30.0 on Ubuntu 20.04.
```
perl --version
...
This is perl 5, version 30, subversion 0 (v5.30.0) built for x86_64-linux-gnu-thread-multi
...
```
```
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal
```
I worked around this by switching to an older version of perl (v5.22.4) using `perlbrew` and also removed the `--with-perl` configure option.
