### ISSUE TITLE
Question: Parsing of pg_exttable fmttype column

### ISSUE THREAD

**Issue by Pryanic** [greenplum-db/gpdb#7968]
Does you have default  mechanism for parsing fmttype column?

**Comment by adam8157** [comment]
Don't quite get your question.

src/include/catalog/pg_exttable.h
```
#define fmttype_is_custom(c) (c == 'b')
#define fmttype_is_text(c)   (c == 't')
#define fmttype_is_csv(c)    (c == 'c')
```

Feel free to reopen if the issue still exists.
