### ISSUE TITLE
KEY SHARE is unexpectedly blocking NO KEY UPDATE, SHARE, KEY SHARE

### ISSUE THREAD

**Issue by BaiShaoqi** [greenplum-db/gpdb#7983]
### Greenplum version or build
latest master  9fe24da

set optimizer to off;
### Expected behavior
all commands in session 2 should not be blocked
### Actual behavior
all commands in session 2 is blocked
### Step to reproduce the behavior
session 1
```
CREATE TABLE bb AS SELECT 1 AS b;
begin;
SELECT * FROM bb FOR key share;
```
session 2
```
SELECT * FROM bb FOR no key update;
SELECT * FROM bb FOR share;
SELECT * FROM bb FOR key share;
```

**Comment by kainwen** [comment]
If GDD is disabled, this is expected behavior. See the thread: https://groups.google.com/a/greenplum.org/forum/#!searchin/gpdb-dev/zlv%7Csort:date/gpdb-dev/q8Nro2iBHRU/78lk-k1_AQAJ

See the commit https://github.com/greenplum-db/gpdb/commit/6ebce73331773d7cf71cfd109d1d7617453c738e 

I close this. Feel free to reopen it if you have more questions.

**Comment by BaiShaoqi** [comment]
If this is expected behavior, but I did not found releated doc in the gpdb src.

**Comment by kainwen** [comment]
> @kainwen said this is expected behavior , but I failed to found releated doc in the gpdb src. Also,does it make sense to disable those lock mode in sql parsing, because the behavior is not right in these cases ?
> 
> @litzell @lisakowen do you know if there is any doc about those special lock mode behavior in gpdb ?
> when using select * from table for {LOCK} in gpdb, variable LOCK could be KEY SHARE, NO KEY UPDATE, SHARE, KEY SHARE, the behavior of these four lock is different from postgres. Is there any doc describe these differences from upstream.

http://gpdb.docs.pivotal.io/6-0Beta/ref_guide/sql_commands/SELECT.html

> If FOR UPDATE, FOR NO KEY UPDATE, FOR SHARE, or FOR KEY SHARE is specified, the SELECT statement locks the entire table against concurrent updates.

**Comment by litzell** [comment]
@BaiShaoqi We have a story in the docs tracker to update docs with information from https://github.com/greenplum-db/gpdb/commit/6ebce73331773d7cf71cfd109d1d7617453c738e and I've added this issue for additional input to the story.

**Comment by BaiShaoqi** [comment]
> @BaiShaoqi We have a story in the docs tracker to update docs with information from [6ebce73](https://github.com/greenplum-db/gpdb/commit/6ebce73331773d7cf71cfd109d1d7617453c738e) and I've added this issue for additional input to the story.

@litzell thanks for the info.
First, I do not want bring too much discussion on a closed issue,  so following are my not strong opions on this.
I do not know what should be updated in docs or if there should need some code work about these  locks:  ` KEY SHARE, NO KEY UPDATE, SHARE, KEY SHARE`, because right now these four locks all block each other, if all four locks  act  almost the `same`, why have fours locks, which does not make sense to me from first impression.

Althouth I have noted the doc has stated:

> If FOR UPDATE, FOR NO KEY UPDATE, FOR SHARE, or FOR KEY SHARE is specified, the SELECT statement locks the entire table against concurrent updates.
