### ISSUE TITLE
 Setting Parameters Error While encountering "-"

### ISSUE THREAD

**Issue by phan-pivotal** [greenplum-db/gpdb#8000]
### Greenplum version or build
'PostgreSQL 9.4.20 (Greenplum Database 6.0.0-beta.3 build commit:d2ebd40835e481a8724f4e3169c60cade3fed6d8) on x86_64-unknown-linux-gnu, compiled by gcc (GCC) 6.4.0, 64-bit compiled on May  8 2019 15:13:34'
### OS version and uname -a
CentOS 7.6 /
Linux localhost.localdomain 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
### Expected behavior
set 
### Actual behavior
syntax error
### Step to reproduce the behavior
1. install GP.
2. psql postgres
3.

postgres=# set optimizer=on;
SET
postgres=# SET LOCAL "request.header.user-agent" = 'curl/7.29.0';
WARNING:  SET LOCAL can only be used in transaction blocks
ERROR:  syntax error at or near "user"  (seg0 127.0.0.1:16000 pid=30595)
postgres=# set optimizer=off;
SET
postgres-# SET LOCAL "request.header.user-agent" = 'curl/7.29.0';
ERROR:  syntax error at or near "SET"
LINE 2: SET LOCAL "request.header.user-agent" = 'curl/7.29.0';

4. Contrasting PG 9.4 behaviors.
postgres=#  SET LOCAL "request.header.user-agent" = 'curl/7.29.0';
WARNING:  SET LOCAL can only be used in transaction blocks
SET

**Comment by pivotal-ning-yu** [comment]
Looks like you forgot to type the terminating `;` at end of the `SET optimizer=off` line.

**Comment by phan-pivotal** [comment]
Yes.  I lost some characters while pasting and already corrected them.
But the issue exists.

**Comment by adam8157** [comment]
The root cause is the command dispatched to segments has no quote characters.
```
(gdb) p debug_query_string
$1 = 0x27c8fa8 "SET LOCAL request.header.user-agent TO 'curl/7.29.0'"
```

**Comment by adam8157** [comment]
Fixed.
