### ISSUE TITLE
gpstart error: Catalog Versions are incompatible (between GPV6 Beta3 and Beta4)

### ISSUE THREAD

**Issue by phan-pivotal** [greenplum-db/gpdb#8040]
### Greenplum version or build
Greenplum Database) 6.0.0-beta.3
upgrade to 
Greenplum Database) 6.0.0-beta.4

### OS version and uname -a
CentOS 7.6
### Expected behavior
Catalog compatible between GP V5 and GP V6
Will the catalog incompatible influence the "catalog compatibility of GP V5 and V6"?
### Actual behavior
[gpadmin6@localhost ~]$ gpstart
20190701:14:32:56:010026 gpstart:localhost:gpadmin6-[INFO]:-Starting gpstart with args: 
20190701:14:32:56:010026 gpstart:localhost:gpadmin6-[INFO]:-Gathering information and validating the environment...
20190701:14:32:56:010026 gpstart:localhost:gpadmin6-[INFO]:-Greenplum Binary Version: 'postgres (Greenplum Database) 6.0.0-beta.3 build commit:d2ebd40835e481a8724f4e3169c60cade3fed6d8'
20190701:14:32:56:010026 gpstart:localhost:gpadmin6-[INFO]:-Greenplum Catalog Version: '301902051'
20190701:14:32:56:010026 gpstart:localhost:gpadmin6-[INFO]:-Starting Master instance in admin mode
20190701:14:32:56:010026 gpstart:localhost:gpadmin6-[INFO]:-Obtaining Greenplum Master catalog information
20190701:14:32:56:010026 gpstart:localhost:gpadmin6-[INFO]:-Obtaining Segment details from master...
20190701:14:32:56:010026 gpstart:localhost:gpadmin6-[INFO]:-Setting new master era
20190701:14:32:56:010026 gpstart:localhost:gpadmin6-[INFO]:-Master Started...
20190701:14:32:56:010026 gpstart:localhost:gpadmin6-[INFO]:-Shutting down master
20190701:14:32:57:010026 gpstart:localhost:gpadmin6-[INFO]:---------------------------
20190701:14:32:57:010026 gpstart:localhost:gpadmin6-[INFO]:-Master instance parameters
20190701:14:32:57:010026 gpstart:localhost:gpadmin6-[INFO]:---------------------------
20190701:14:32:57:010026 gpstart:localhost:gpadmin6-[INFO]:-Database                 = template1
20190701:14:32:57:010026 gpstart:localhost:gpadmin6-[INFO]:-Master Port              = 5432
20190701:14:32:57:010026 gpstart:localhost:gpadmin6-[INFO]:-Master directory         = /data1/gpadmin6/master/gpseg-1
20190701:14:32:57:010026 gpstart:localhost:gpadmin6-[INFO]:-Timeout                  = 600 seconds
20190701:14:32:57:010026 gpstart:localhost:gpadmin6-[INFO]:-Master standby           = Off 
20190701:14:32:57:010026 gpstart:localhost:gpadmin6-[INFO]:---------------------------------------
20190701:14:32:57:010026 gpstart:localhost:gpadmin6-[INFO]:-Segment instances that will be started
20190701:14:32:57:010026 gpstart:localhost:gpadmin6-[INFO]:---------------------------------------
20190701:14:32:57:010026 gpstart:localhost:gpadmin6-[INFO]:-   Host                    Datadir                          Port    Role
20190701:14:32:57:010026 gpstart:localhost:gpadmin6-[INFO]:-   localhost.localdomain   /data1/gpadmin6/primary/gpseg0   16000   Primary
20190701:14:32:57:010026 gpstart:localhost:gpadmin6-[INFO]:-   sdw                     /data1/gpadmin6/mirror/gpseg0    17000   Mirror

Continue with Greenplum instance startup Yy|Nn (default=N):

________________________________________________________-
[gpadmin6@localhost ~]$ gpstart
20190701:14:36:56:010326 gpstart:localhost:gpadmin6-[INFO]:-Starting gpstart with args: 
20190701:14:36:56:010326 gpstart:localhost:gpadmin6-[INFO]:-Gathering information and validating the environment...
20190701:14:36:56:010326 gpstart:localhost:gpadmin6-[INFO]:-Greenplum Binary Version: 'postgres (Greenplum Database) 6.0.0-beta.4 build commit:706e161e4b02b3fb967c8c689cb1c3f9de6d0f6a'
20190701:14:36:56:010326 gpstart:localhost:gpadmin6-[INFO]:-Greenplum Catalog Version: '301906041'
20190701:14:36:56:010326 gpstart:localhost:gpadmin6-[INFO]:-MASTER_DIRECTORY Catalog Version: '301902051'
20190701:14:36:56:010326 gpstart:localhost:gpadmin6-[INFO]:-Catalog Version of master directory incompatible with binaries
20190701:14:36:56:010326 gpstart:localhost:gpadmin6-[ERROR]:-gpstart error: Catalog Versions are incompatible

### Step to reproduce the behavior
1. install and initializing GP-V6-Beta3
2. replace binary of GP-V6-Beta3 to GP-V6-Beta4.
3. gpstart

**Comment by adam8157** [comment]
It's the expected behavior,

**Comment by phan-pivotal** [comment]
No permission to access.

**Comment by adam8157** [comment]
Yes, we have catalog changes in Greenplum 6 Beta
