### ISSUE TITLE
pg_export_snapshot() shows NOTICE:  One or more columns in the following table(s) do not have statistics

### ISSUE THREAD

**Issue by BaiShaoqi** [greenplum-db/gpdb#8058]
### Greenplum version or build
master 056125e0fa 
orca version : v3.53.0
orca enabled

### Step to reproduce the behavior

open two session with optimizer to on;

session 1
```SQL
create table jj(j int);
begin;
SELECT pg_export_snapshot();
 pg_export_snapshot
--------------------
 0000030B-1
(1 row)
```
session 2
```SQL
BEGIN TRANSACTION ISOLATION LEVEL REPEATABLE READ;
SET TRANSACTION SNAPSHOT '0000030B-1';
insert into jj values(1);
```
now back to session 1
```
select * from jj;
NOTICE:  One or more columns in the following table(s) do not have statistics: jj
HINT:  For non-partitioned tables, run analyze <table_name>(<column_list>). For partitioned tables, run analyze rootpartition <table_name>(<column_list>). See log for columns missing statistics.
 j
---
(0 rows)
```
while I was expecting 
```SQL
select * from jj;
 j
---
 1
(1 row)
```

The notice only comes when orca is enabled, so I suppose it belongs to orca.

**Comment by asimrp** [comment]
Hey @BaiShaoqi, thank you for the report :+1:  Please note that snapshot export/import functionality is not fully baked in Greenplum.  Greenplum must include distributed snapshot information in the exported snapshot and be able to import distributed snapshot as well, in order to properly support this feature.

Are you thinking of a use case for this feature in Greenplum?  If so, please do share your ideas!

**Comment by BaiShaoqi** [comment]
@asimrp I was not thinking about anything, I just run into this case when I verify your PR https://github.com/greenplum-db/gpdb/pull/8035
if greenplum-db merged postgre 9.5, there is a option for pg_dump that can be used like this `pg_dump --snapshot 0000030B-1` , if it can not be fully baked in Greenplum, I don't know if this option for pg_dump can be used.

**Comment by BaiShaoqi** [comment]
@asimrp another usage of snapshot export/import might be the following case, I don't know if it is worth a lot of work that in order to properly support this feature. 
the case is showing like following.
```
gpconfig -c wal_level -v logical
gpstop -r
cd contrib/test_decoding/
make install
```
```
-> PGOPTIONS='-c gp_session_role=utility'   psql "replication=database dbname=postgres"
psql (9.4.20)
Type "help" for help.

postgres=# CREATE_REPLICATION_SLOT foo3 LOGICAL test_decoding;
 slot_name | consistent_point | snapshot_name | output_plugin
-----------+------------------+---------------+---------------
 foo3      | 0/C385A38        | 00000318-1    | test_decoding
(1 row)
```
There is a `00000318-1` in the field snapshot_name in the output .
This maybe a useful feature that it is possible to get an image of the database when slot was created.
maybe useful for  cases like  the when database is not recoveryable, use pg_dump with the snapshot that when the slot is created, as long as database is recoverable when slot is created. because we can use pg_dump with snapshot like following.
`pg_dump --snapshot 00000318-1`

**Comment by ashwinstar** [comment]
I don't think `NOTICE:  One or more columns in the following table(s) do not have statistics: jj` has any connection with `pg_export_snapshot()` functionality. If the table is missing the stats ORCA complains/notices about that fact via this notice. Just analyze the table and this won't be seen. Nothing specific to fix under this GitHub issue.
