### ISSUE TITLE
crash when using two collations

### ISSUE THREAD

**Issue by BaiShaoqi** [greenplum-db/gpdb#8079]
### Greenplum version or build
master be00c3d2a6
crash both wih orca or without  orca.

### Expected behavior
No crash
### Actual behavior
NOTE : `select * from aa where chinese < (english collate "zh_HK.UTF-8");` only crashes after perform `select * from aa where chinese < english;` and it is not always crash, in my computer, it crashes like 70%. If it does not crash at first time, after following the step in `Step to reproduce the behavior`, always open an new session and type the following command.
```sql
select * from aa where chinese < english;
select * from aa where chinese < (english collate "zh_HK.UTF-8");
```
### Step to reproduce the behavior
```sql
-- 11 is the  oid of pg_catalog
-- load all the locale in system, so the "zh_HK.UTF-8" can be used
select  pg_import_system_collations(11);

create table aa(chinese  text collate "zh_HK.UTF-8", english text collate "en_US");

insert into aa values ('一', 'a');

select * from aa where chinese < english;
ERROR:  could not determine which collation to use for string comparison  (seg1 slice1 127.0.0.1:25433 pid=37174)
HINT:  Use the COLLATE clause to set the collation explicitly.

select * from aa where chinese < (english collate "zh_HK.UTF-8");
ERROR:  Error on receive from seg1 slice1 127.0.0.1:25433 pid=37174: server closed the connection unexpectedly
DETAIL:
	This probably means the server terminated abnormally
	before or while processing the request.
```

**Comment by weinan003** [comment]
The behavior is no different from upstream, at lease on pg11.

**Comment by weinan003** [comment]
If you do not have a further suggestion, I believe this issue should be closed

**Comment by BaiShaoqi** [comment]
I repeat the repro again and again, but did no see crash in latest master( 86288d29d1)
Did the repro in gpdb and pg11 also crash ?

**Comment by BaiShaoqi** [comment]
Since the repro can not be work in latest master, close the issue.
