### ISSUE TITLE
gpfdist merges two records when last record of file is missing linefeed and more files are needed to be processed

### ISSUE THREAD

**Issue by ddanese** [greenplum-db/gpdb#8122]
### Greenplum version or build
5.8.0

### OS version and uname -a
Linux hostname 3.10.0-957.12.1.el7.x86_64 #1 SMP Wed Mar 20 11:34:37 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

### autoconf options used ( config.status --config )
binary bundle provided from pivotal release

### Installation information ( pg_config )
BINDIR = /usr/local/greenplum-db-5.8.0/bin
DOCDIR = /usr/local/greenplum-db-5.8.0/doc/postgresql
HTMLDIR = /usr/local/greenplum-db-5.8.0/doc/postgresql
INCLUDEDIR = /usr/local/greenplum-db-5.8.0/include
PKGINCLUDEDIR = /usr/local/greenplum-db-5.8.0/include/postgresql
INCLUDEDIR-SERVER = /usr/local/greenplum-db-5.8.0/include/postgresql/server
LIBDIR = /usr/local/greenplum-db-5.8.0/lib
PKGLIBDIR = /usr/local/greenplum-db-5.8.0/lib/postgresql
LOCALEDIR = /usr/local/greenplum-db-5.8.0/share/locale
MANDIR = /usr/local/greenplum-db-5.8.0/man
SHAREDIR = /usr/local/greenplum-db-5.8.0/share/postgresql
SYSCONFDIR = /usr/local/greenplum-db-5.8.0/etc/postgresql
PGXS = /usr/local/greenplum-db-5.8.0/lib/postgresql/pgxs/src/makefiles/pgxs.mk
CC = gcc -m64
CPPFLAGS = -D_GNU_SOURCE -I/usr/local/greenplum-db-5.8.0/include
CFLAGS = -m64 -O3 -fargument-noalias-global -fno-omit-frame-pointer -g -std=gnu99 -Wall -Wmissing-prototypes -Wpointer-arith -Wendif-labels -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fno-aggressive-loop-optimizations -Wno-unused-but-set-variable -Wno-address -I/usr/local/greenplum-db-5.8.0/include
CFLAGS_SL = -fpic
LDFLAGS = -Wl,--as-needed -Wl,-rpath,'/usr/local/greenplum-db-devel/lib',--enable-new-dtags -L/usr/local/greenplum-db-5.8.0/lib
LDFLAGS_SL =
LIBS = -lpgport -lgpopt -lnaucrates -lgpdbcost -lgpos -lxerces-c -lxml2 -lpam -lrt -lkrb5 -lcom_err -lgssapi_krb5 -lcrypt -ldl -lm -lrt -L/usr/local/greenplum-db-5.8.0/lib
VERSION = PostgreSQL 8.3.23

### Expected behavior
when gpfdist finds an end of file, it should also end the record

### Actual behavior
gpfdist merges two records from two files into one.

### Step to reproduce the behavior
two files, named sequentially, first files last record missing linefeed (\n).
single gpfdist pointing to location
create external table
select from table
check error log

In my example I have two files with few hundred thousand records each.  last line of file 1 has no linefeed.
The record: 
SignalTest1,0,1562715064523
is the last record of the file
The record:
SignalTest2,0,1562715064918
is the first record of file 2

gpfdist returns: 
SignalTest1,0,1562715064523SignalTest2,0,1562715064918

**Comment by lij55** [comment]
gpfdist doesn't modify the content of file. It will decrease the loading performance. 
Please use the transform feature to work around it.

**Comment by lij55** [comment]
close it as it is not in current scope. The suggested work around for such issue is to use `transfrom` feature of gpfdist. the example transform scrits are:
```bash
#!/bin/bash
sed -e '$s/$/\n/' $@
```
