### ISSUE TITLE
pageinspect ERROR:  block number 0 is out of range for relation "bb"

### ISSUE THREAD

**Issue by BaiShaoqi** [greenplum-db/gpdb#8127]
### Greenplum version or build
master, 686874e9d32b9a406629d4b9f86d7c2a543a1195

### Expected behavior
no error at least
### Actual behavior
```sql
postgres=# SELECT * from heap_page_items(get_raw_page('bb', 0));
ERROR:  block number 0 is out of range for relation "bb"
```

### Step to reproduce the behavior
```sql
CREATE EXTENSION pageinspect;

CREATE TABLE bb AS SELECT 1 AS b;
```

**Comment by hlinnaka** [comment]
This isn't a bug. `pageinspect` is a low-level tool that returns raw page data. There is no data in the QD, hence it throws an error when you run it in the QD. If you connect to the segment that actually holds the data in utility mode, it'll work.

**Comment by gaos1** [comment]
@Eulerizeit @dyozie i suggest we add Heikki's comments to the doc page below so that users won't hit similar error.  right now we only guide users to refer to PostgreSQL document. 
https://gpdb.docs.pivotal.io/6-0/ref_guide/modules/pageinspect.html
