### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [greenplum-db/gpdb#8193]
I would like to point out that identifiers like “[`_PROC_H_`](https://github.com/greenplum-db/gpdb/blob/bfd1f46cdca853d72aade02ec97a447246f78ff0/src/include/storage/proc.h#L16 "Update candidate")” and “[`__S3_COMMON_HEADERS_H__`](https://github.com/greenplum-db/gpdb/blob/cb5d1db97b5fc7987a3e8139c085275037021378/gpcontrib/gpcloud/include/s3common_headers.h#L1 "Another update candidate")” [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by dgkimura** [comment]
Thanks for pointing that out.

However, I think there are a few hurdles:
1) proc.h is inherited from Postgres project, so it should be changed there first.
2) I think there is value in keeping consistent with Postgres style.  Unless that changes, I don't think we'd want to diverge GPDB specific code to accommodate other conventions.
3) GPDB project is first and foremost a C project, so some C++ conventions may not be applicable.

As such, until Postgres changes, I think it's unlikely we'd want to make these changes.

**Comment by dgkimura** [comment]
Closing for above reasons.

**Comment by elfring** [comment]
* Would you like to adjust bundled components?
* How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoiding undefined behaviour?")?
