### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [greenplum-db/gpdb#8194]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
- [reader_init](https://github.com/greenplum-db/gpdb/blob/c2edc32d3e0ca4a1aefe94262d02f60fc5be86ea/gpcontrib/gpcloud/src/gpreader.cpp#L112 "reader_init function")
- [writer_init](https://github.com/greenplum-db/gpdb/blob/8f8813d15cb1141a0dc8531fad4f19fdb7fa1e17/gpcontrib/gpcloud/src/gpwriter.cpp#L92 "writer_init function")

**Comment by danielgustafsson** [comment]
Would you like to propose a PR for these?

**Comment by d** [comment]
@elfring you're right, do you want to send a patch in?

**Comment by elfring** [comment]
How do you think about to [use a development tool like “clang-tidy” for corresponding source code adjustments](https://clang.llvm.org/extra/clang-tidy/checks/readability-delete-null-pointer.html "Deletion of unnecessary null pointer checks")?

**Comment by ashwinstar** [comment]
Sure @elfring we would be interested in clang-tidy as well along with tidying up the flagged code. Please go ahead to submit the PR for all the proposed.

**Comment by lij55** [comment]
thanks for reporting. we will fix them.
