### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [greenplum-db/gpdb#8195]
Would you like to add more error handling for return values from functions like the following?
- [calloc](https://pubs.opengroup.org/onlinepubs/9699919799/functions/calloc.html "Memory allocation") ⇒ [make_block_id](https://github.com/greenplum-db/gpdb/blob/99360f544ea55201afec791a36a733c7684156bc/src/backend/access/gin/test/ginpostinglist_test.c#L15)
- [pthread_mutex_init](https://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_mutex_init.html "Initialize a mutex.") ⇒ [S3KeyWriter constructor](https://github.com/greenplum-db/gpdb/blob/8f8813d15cb1141a0dc8531fad4f19fdb7fa1e17/gpcontrib/gpcloud/include/s3key_writer.h#L13)

**Comment by ashwinstar** [comment]
I am not sure I understand the ask here. Please can you send PR for the same and we can evaluate based on code change. Or if wish to discuss the same please initiate email thread on gpdb-dev@greenplum.org mailing list.

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Checking more return values") a bit more.
Would you like to detect every error situation as early as possible?
