### ISSUE TITLE
gpssh-exkeys ignore public keys with spaces in comment

### ISSUE THREAD

**Issue by Stolb27** [greenplum-db/gpdb#8201]
### Greenplum version or build
Greenplum Database 5.21.0

### OS version and uname -a
CentOS 7
Linux mdw 3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

### Expected behavior
Utility distribute any valid gpadmin openssh keys across cluster

### Actual behavior
Utility ignore public keys with spaces in comments

### Step to reproduce the behavior

1. Generate keys pair for gpadmin user with spaces in comment
`ssh-keygen -t rsa -f ~/.ssh/id_rsa -C "generated by script" -N ''`
2. Run on host1 `gpssh-exkeys -h host2`
3. Utility ignore such public keys and remove it from authorized_keys if already exists
Problem located in [addRemoteId](https://github.com/greenplum-db/gpdb/blob/3ce5a720eb775a120d201bdc42a154877fb81758/gpMgmt/bin/gpssh-exkeys#L446) function. Utility expect strictly 3 columns splitted by spaces. But comment may be absent.

**Comment by melanieplageman** [comment]
The code for `addRemoteId` is same on master as well--so, I think this is present across versions. @bharath1028 could you confirm if this behavior is in fact a bug?

**Comment by tylarb** [comment]
I'm expecting that this was an issue due to the paramiko library parsing, which had several issues. 

In master (Greenplum 7 target), paramiko is removed, and no parsing of the `id_rsa` file is done by Greenplum code - so I expect this issue is either resolved or no longer relevant.
