### ISSUE TITLE
truncate table stucked by  transaction without pid (process id)

### ISSUE THREAD

**Issue by chengshao1987** [greenplum-db/gpdb#8218]
Greenplum version or build
PostgreSQL 8.3.23 (Greenplum Database 5.11.0 build commit:6f447c24554134df0c1d473e63e0124e7ee6de6b) on x86_64-pc-linux-gnu, compiled by GCC gcc (GCC) 6.2.0, 64-bit compiled on Sep 12 2018 20:17:30

OS version and uname -a
Linux gpmaster 4.16.18-1.el6.x86_64 #1 SMP Fri Jul 20 21:46:55 CST 2018 x86_64 x86_64 x86_64 GNU/Linux

autoconf options used ( config.status --config )

Installation information ( pg_config )
default configuration

Expected behavior
truncate table command run correctly

Actual behavior
truncate table stuck by transaction without pid (process id)

Step to reproduce the behavior
I use HVR software to sync data from mysql to greenplum . And sometimes stucked when run truncate table command , every time when this occurred , I found table pg_locks  had a record (transaction without pid ) like this
![image](https://user-images.githubusercontent.com/29300172/61775869-5dfa7580-ae2c-11e9-88a3-c2126fdca01e.png)

I thought it was a prepared transaction and seacrhed the table pg_prepared_xacts, found no records in this table. After that I restart the Greenplum database ,and the record in pg_locks disappeared , and then I could ran truncate table command normally. 
I want to know if this is a bug or how can I remove the lock record without restart database system.

**Comment by asimrp** [comment]
@chengshao1987 next time this happens, please provide full output of `select * from pg_locks;`.  We are interested in rows having `granted` as false. These are the transactions waiting for a lock.  Knowing that will provide some clue to solve your problem.

**Comment by chengshao1987** [comment]
the attached Excel file contain the full output of pg_locks ，thank you
[pg_locks.xlsx](https://github.com/greenplum-db/gpdb/files/3426874/pg_locks.xlsx)

**Comment by asimrp** [comment]
Thank you @chengshao1987, here are the interesting rows from your lock table:
```
locktype | database | relation | page | tuple | virtualxid | transactionid | classid | objid | objsubid | virtualtransaction | pid | mode | granted | mppsessionid | mppiswriter | gp_segment_id
relation | 28555 | 32585807 |   |   |   |   |   |   |   | -0.0000000285277289810974 |   | RowExclusiveLock | t | 0 | f | 2
relation | 28555 | 32585807 |   |   |   |   |   |   |   | 10/774574 | 24831 | AccessExclusiveLock | f | 645566 | t | 2
```
Looks like your lock table is corrupted because these values look bogus: virtualtransaction = -0.0000000285277289810974, pid as NULL and mppsessionid = 0 for the first entry above.  And that's the holder of RowExclusiveLock on relation 32585807.  The second entry is a legitimate transaction that is waiting for AccessExclusiveLock held by the first ghost entry.

My suggestion is to upgrade to the latest 5X release and try again.  We have fixed one shared memory corruption issue in 5X that is not in 5.11.

**Comment by chengshao1987** [comment]
> Thank you @chengshao1987, here are the interesting rows from your lock table:
> 
> ```
> locktype | database | relation | page | tuple | virtualxid | transactionid | classid | objid | objsubid | virtualtransaction | pid | mode | granted | mppsessionid | mppiswriter | gp_segment_id
> relation | 28555 | 32585807 |   |   |   |   |   |   |   | -0.0000000285277289810974 |   | RowExclusiveLock | t | 0 | f | 2
> relation | 28555 | 32585807 |   |   |   |   |   |   |   | 10/774574 | 24831 | AccessExclusiveLock | f | 645566 | t | 2
> ```
> 
> Looks like your lock table is corrupted because these values look bogus: virtualtransaction = -0.0000000285277289810974, pid as NULL and mppsessionid = 0 for the first entry above. And that's the holder of RowExclusiveLock on relation 32585807. The second entry is a legitimate transaction that is waiting for AccessExclusiveLock held by the first ghost entry.
> 
> My suggestion is to upgrade to the latest 5X release and try again. We have fixed one shared memory corruption issue in 5X that is not in 5.11.

thank you , we will upgrade in the future and check it

**Comment by chengshao1987** [comment]
> Thank you @chengshao1987, here are the interesting rows from your lock table:
> 
> ```
> locktype | database | relation | page | tuple | virtualxid | transactionid | classid | objid | objsubid | virtualtransaction | pid | mode | granted | mppsessionid | mppiswriter | gp_segment_id
> relation | 28555 | 32585807 |   |   |   |   |   |   |   | -0.0000000285277289810974 |   | RowExclusiveLock | t | 0 | f | 2
> relation | 28555 | 32585807 |   |   |   |   |   |   |   | 10/774574 | 24831 | AccessExclusiveLock | f | 645566 | t | 2
> ```
> 
> Looks like your lock table is corrupted because these values look bogus: virtualtransaction = -0.0000000285277289810974, pid as NULL and mppsessionid = 0 for the first entry above. And that's the holder of RowExclusiveLock on relation 32585807. The second entry is a legitimate transaction that is waiting for AccessExclusiveLock held by the first ghost entry.
> 
> My suggestion is to upgrade to the latest 5X release and try again. We have fixed one shared memory corruption issue in 5X that is not in 5.11.

by the way，how can I remove these lock records (pid  as NULL) without restarting database system？
