### ISSUE TITLE
one TPC-H query error with "operator 37 is not a valid ordering operator"

### ISSUE THREAD

**Issue by gaos1** [greenplum-db/gpdb#8230]
### Greenplum version or build
PostgreSQL 9.4.20 (Greenplum Database 7.0.0-alpha.0+dev.552.g585e90b build dev)
### Expected behavior
Query can run successfully 

### Actual behavior
ERROR:  operator 37 is not a valid ordering operator (pathkeys.c:576)

### Step to reproduce the behavior
Run the following TPC-H query with legacy planner:
```
select
	s_acctbal,
	s_name,
	n_name,
	p_partkey,
	p_mfgr,
	s_address,
	s_phone,
	s_comment
from
	part,
	supplier,
	partsupp,
	nation,
	region
where
	p_partkey = ps_partkey
	and s_suppkey = ps_suppkey
	and p_size = 3
	and p_type like '%TIN'
	and s_nationkey = n_nationkey
	and n_regionkey = r_regionkey
	and r_name = 'ASIA'
	and ps_supplycost = (
		select
			min(ps_supplycost)
		from
			partsupp,
			supplier,
			nation,
			region
		where
			p_partkey = ps_partkey
			and s_suppkey = ps_suppkey
			and s_nationkey = n_nationkey
			and n_regionkey = r_regionkey
			and r_name = 'ASIA'
	)
order by
	s_acctbal desc,
	n_name,
	s_name,
	p_partkey
LIMIT 100;
```

**Comment by Eulerizeit** [comment]
Is there a schema and data that you could easily upload?

Rob

**Comment by gaos1** [comment]
i tested on both master and gp6 codebase, but cannot reproduce this error.  checked with the issue reporter, their cluster is destroyed. so close the issue for now.
