### ISSUE TITLE
I have a server(28 Cores, 128GB RAM，40TB disk space).How many greenplum segment instances should each server be assigned?

### ISSUE THREAD

**Issue by zhouhaihong** [greenplum-db/gpdb#8279]
I have a server(28 Cores, 128GB RAM，40TB disk space).
How many greenplum segment instances should each server be assigned?

**Comment by Eulerizeit** [comment]
This is not really an issue so getting a response here is not likely to happen. 

Please send this type of question to gpdb-users@greenplum.org.
