### ISSUE TITLE
Greenplum with Power BI

### ISSUE THREAD

**Issue by ghost** [greenplum-db/gpdb#8282]
Hi experts,

My organization decided to use Greenplum as BI platform, but I can't even find a connection in Power BI with Greenplum. Does anyone has such experience or best practice for that? Thanks.

Regards,
Yue

**Comment by danielgustafsson** [comment]
> On 31 Jul 2019, at 17:11, daniden <notifications@github.com> wrote:

> My organization decided to use Greenplum as BI platform, but I can't even find a connection in Power BI with Greenplum. Does anyone has such experience or best practice for that? Thanks.

I would recommend taking this question to the gpdb-users mailinglist: https://greenplum.org/community/

**Comment by sunnn** [comment]
@daniden did you try with postgresql odbc connection

**Comment by daniden** [comment]
Yes, I have tried it. The postgresql connector provided by Power BI can be used to connect GPDB. However it does not support the direct query mode in Power BI.
I could not find a roadmap that Power BI would support GPDB connector with direct query mode. Any news from your side? Thanks.



----------------------------

This message (including any attachments) contains confidential information intended for a specific individual and purpose, and is protected by law. If you are not the intended recipient, you should delete this message. Any disclosure, copying, or distribution of this message, or the taking of any action based on it, is strictly prohibited.

©2019 Deloitte Touche Tohmatsu in Hong Kong, Deloitte Touche Tohmatsu in Macau, and Deloitte Touche Tohmatsu Certified Public Accountants LLP in the Chinese Mainland. All rights reserved.

Deloitte refers to a Deloitte member firm, one of its related entities, or Deloitte Touche Tohmatsu Limited ("DTTL"). Each Deloitte member firm is a separate legal entity and a member of DTTL. DTTL does not provide services to clients. Please see www.deloitte.com/about to learn more.

[cid:image6b01ab.JPG@664a493d.40baae8b]
----------------------------

**Comment by ashwinstar** [comment]
Closing this very old issue. If requirement still exist please feel free to post here or best open discussion on gpdb-users mailing list.
