### ISSUE TITLE
createdb --template=postgres test ERROR

### ISSUE THREAD

**Issue by BaiShaoqi** [greenplum-db/gpdb#8289]
### Greenplum version or build
master 86288d29d1

### Expected behavior
should see no error.
This only fails when template is postgres, when it is template0, template1, or other user created database, it shows no error.
### Actual behavior
```
-> createdb --template=postgres test
createdb: database creation failed: ERROR:  source database "postgres" is being accessed by other users
DETAIL:  There is 1 other session using the database.
```

**Comment by ashwinstar** [comment]
This is failing because you must be having connection open to postgres database, as the error suggests. Close that connection and creation of db using "postgres" database should succeed.

**Comment by BaiShaoqi** [comment]
Open an session to check if see the if there is connection to postgres datatbase, there isn't
```
-> psql -d test1
psql (9.4.20)
Type "help" for help.

test1=# select * from pg_stat_activity  where datname = 'postgres';   
 datid | datname | pid | sess_id | usesysid | usename | application_name | client_addr | client_hostname | client_port | backend_start | xact_start | query_start | state_change | waiting | state | backend_xid | backend_xmin | query | waiting_reason | rsgid | rsgname | rsgqueueduration
-------+---------+-----+---------+----------+---------+------------------+-------------+-----------------+-------------+---------------+------------+-------------+--------------+---------+-------+-------------+--------------+-------+----------------+-------+---------+------------------
(0 rows)
```

**Comment by jimmyyih** [comment]
This is because the ftsprobe process and the seqserver process are instantiated with MyDatabaseId as postgres database.

In `fts.c:91` in GPDB 5X_STABLE:
```
static char *probeDatabase = "postgres";
```

In `seqserver.c:385` in GPDB 5X_STABLE:
```
static char *knownDatabase = "postgres";
```

Presumably, this is for access to relation cache.

**Comment by ashwinstar** [comment]
No plans to fix this for now, works this way as coded. Postgres database is used for most the internal operations in GPDB like FTS, Distributed Recovery Process, Utilities, Sequence Server, and such...
