### ISSUE TITLE
gp_segment_configuration does not reflect the current state of the cluster

### ISSUE THREAD

**Issue by kalensk** [greenplum-db/gpdb#8318]
gp_segment_configuration should be the single source of truth for the current state of the cluster which is critical since GPDB is a distributed system. For example, this can be very useful in debugging customer scenarios,  internal testing, as well as keeping cluster state consistent. 

For several scenarios, gp_segment_configuration does not seem to reflect the current state such as:
- double faults (primary and mirror going down)
- the last primary to go down when all other primaries have failed.
- when a primary goes down, the promoted mirror is shown as promoted _before_ the cluster can accept transactions (How might we want to show this other state as "promoting" or another field as "desired or expected state")

### Double Fault Reproduction:
- create a demo cluster
- stop a primary and associated mirror: 
`pg_ctl stop -w -t 60 -D /Users/kkrempely/workspace/gpdb7/gpAux/gpdemo/datadirs/dbfast1/demoDataDir0`
`pg_ctl stop -w -t 60 -D /Users/kkrempely/workspace/gpdb7/gpAux/gpdemo/datadirs/dbfast_mirror1/demoDataDir0`
- send an fts probe scan: `psql postgres -c "select gp_request_fts_probe_scan();"`
- expect both primary and mirror should be marked down in gp_segment_configuration, but the mirror is not
```
 dbid | content | role | preferred_role | mode | status | port  | hostname | address |                                      datadir
------+---------+------+----------------+------+--------+-------+----------+---------+------------------------------------------------------------------------------------
    1 |      -1 | p    | p              | n    | u      | 15432 | kalen    | kalen   | /Users/kkrempely/workspace/gpdb7/gpAux/gpdemo/datadirs/qddir/demoDataDir-1
    3 |       1 | p    | p              | s    | u      | 25433 | kalen    | kalen   | /Users/kkrempely/workspace/gpdb7/gpAux/gpdemo/datadirs/dbfast2/demoDataDir1
    6 |       1 | m    | m              | s    | u      | 25436 | kalen    | kalen   | /Users/kkrempely/workspace/gpdb7/gpAux/gpdemo/datadirs/dbfast_mirror2/demoDataDir1
    4 |       2 | p    | p              | s    | u      | 25434 | kalen    | kalen   | /Users/kkrempely/workspace/gpdb7/gpAux/gpdemo/datadirs/dbfast3/demoDataDir2
    7 |       2 | m    | m              | s    | u      | 25437 | kalen    | kalen   | /Users/kkrempely/workspace/gpdb7/gpAux/gpdemo/datadirs/dbfast_mirror3/demoDataDir2
    8 |      -1 | m    | m              | s    | u      | 16432 | kalen    | kalen   | /Users/kkrempely/workspace/gpdb7/gpAux/gpdemo/datadirs/standby
    2 |       0 | m    | p              | n    | d      | 25432 | kalen    | kalen   | /Users/kkrempely/workspace/gpdb7/gpAux/gpdemo/datadirs/dbfast1/demoDataDir0
    5 |       0 | p    | m              | n    | u      | 25435 | kalen    | kalen   | /Users/kkrempely/workspace/gpdb7/gpAux/gpdemo/datadirs/dbfast_mirror1/demoDataDir0
(8 rows)

```

### Greenplum version or build
 PostgreSQL 9.4.20 (Greenplum Database 7.0.0-alpha.0+dev.673.gdf7cef3bac build dev) on x86_64-apple-darwin17.5.0, compiled by Apple LLVM version 9.1.0 (clang-902.0.39.2), 64-bit compiled on Aug  5 2019 11:15:41 (with assert checking)

### OS version and uname -a
macOS High Sierra version 10.13.4
Darwin 17.5.0 Darwin Kernel Version 17.5.0: Mon Mar  5 22:24:32 PST 2018; root:xnu-4570.51.1~1/RELEASE_X86_64 x86_64

### autoconf options used ( config.status --config )
$ ./configure --prefix=/usr/local/gpdb7 --disable-orca --enable-depend --enable-debug --enable-cassert --disable-pxf --with-perl --with-python --with-libxml --with-gssapi CFLAGS=-O0 CXXFLAGS=-O0 --no-create --no-recursion

**Comment by asimrp** [comment]
Hey @kalensk, could you please elaborate on the usecase here?  Perhaps an example of a debugging scenario or internal testing scenario that will be simplified if `gp_segment_configuration` is updated as per your recommendation?

The way gp_segment_configuration is updated today is by design.  In the event of a double fault, the advantage of leaving the acting primary as `up` is apparent when we think about the workflow to recover from the double fault.  The current workflow is the cluster admin needs to bring the primary back up and the cluster starts function without further intervention.  If, instead, we choose to mark the acting primary as `down`, such that both, primary and mirror, are marked down, what do you think the workflow would be, when the primary is brought back up?  FTS would become more complex.  For a mirror-less cluster, FTS may need to start probing the primaries, where as today, it does not.

We need to determine the gains of keeping `gp_segment_configuration` up to date very clearly.  The complexity it brings is quite high, as I see it.

**Comment by asimrp** [comment]
To be clear, from a user's perspective, knowing that there is a double fault or, in a mirror-less cluster, that a primary is down, is valuable.  @liming01 made that point and I agree with it.  Shouldn't a user facing utility such as `gpstate` be able to provide the real-time, truthful cluster configuration details?

**Comment by Eulerizeit** [comment]
This isn't an issue, FTS is working as designed. This would be a useful conversation to have on the mailing list.

**Comment by jchampio** [comment]
@Eulerizeit The argument is not that there's a bug in FTS; the argument is that the design is insufficient for the functionality of the outer layers. Whether or not you and I agree with that argument, it's worth a conversation whether it's on the list or GitHub.

**Comment by kalensk** [comment]
> Shouldn't a user facing utility such as `gpstate` be able to provide the real-time, truthful cluster configuration details?

It makes more sense that as much information and logic be pushed into the server allowing the utilities to be simple wrappers around pg_utilities and the server. Thus, to me it makes much more sense to have gp_segment_configuration or the like be the source of truth of the current state of the cluster rather than gpstate.

**Comment by Eulerizeit** [comment]
On Wed, Aug 7, 2019, 11:39 PM Jacob Champion <notifications@github.com>
wrote:

> @Eulerizeit <https://github.com/Eulerizeit> The argument is not that
> there's a bug in FTS; the argument is that the design is insufficient for
> the functionality of the outer layers. Whether or not you and I agree with
> that argument, it's worth a conversation whether it's on the list or GitHub.
>

I'm totally in favor of a discussion, there is one happening on gpdb-dev
right now.

Rob
