### ISSUE TITLE
greenplum read and write separation

### ISSUE THREAD

**Issue by juaby** [greenplum-db/gpdb#8335]
how to config greenplum master and standby node read and write separation?

how to config greenplum segment pri and mirror node read and write separation?

**Comment by berlin-ab** [comment]
Hi @juaby. Thanks for posting your question.

You might have better odds at getting a thoughtful response by sending this to the Greenplum Users mailing list. 

See this site for more information on the mailing lists:
https://greenplum.org/mailing-lists/
