### ISSUE TITLE
hashagg for some UDAs OOMs

### ISSUE THREAD

**Issue by melanieplageman** [greenplum-db/gpdb#8339]
inspired by the [discussion](https://github.com/greenplum-db/gpdb/pull/8137#pullrequestreview-264701074)  on #8137 of its impact on UDAs 
@d and I created a minimal repro of this issue in [this](https://github.com/melanieplageman/gpdb/tree/make-it-leak) branch

We make two UDAs: `leaky_sum()` and `good_sum()`. We create a table and insert some data. Then, using these two aggregates, we demonstrate how all UDAs which would have pass-by-reference transvalues and a return type INTERNAL would potentially OOM.

For convenience, we stuck the UDAs in `pg_regress`.

You can see in the `make_it_leak` test [output file](https://github.com/melanieplageman/gpdb/blob/ef9247152c5fc9e8e77533a47e486f211d04d58f/src/test/regress/output/make_it_leak.source) that `leaky_sum()` OOMs.

More details on running the examples are in the commit message melanieplageman/gpdb@ef9247152c5

**Comment by adam8157** [comment]
Does PR https://github.com/greenplum-db/gpdb/pull/8280 help?

**Comment by melanieplageman** [comment]
So, I was trying to think how to let users know they should use `mpool_alloc` in their UDAs and checked the docs for `CREATE AGGREGATE` https://gpdb.docs.pivotal.io/5210/ref_guide/sql_commands/CREATE_AGGREGATE.html and, I'm just not sure it seems appropriate there. What should we do? @adam8157 @Eulerizeit

**Comment by melanieplageman** [comment]
Closing. refer to https://github.com/greenplum-db/gpdb/issues/8398
