### ISSUE TITLE
Faultinjector fails to emit a warning upon injecting a PANIC fault

### ISSUE THREAD

**Issue by asimrp** [greenplum-db/gpdb#8349]
### Greenplum version or build
master & 6X

### autoconf options used ( config.status --config )
`--enable-debug-extensions`

### Expected behavior
```SQL
create extension gp_inject_fault;
select gp_inject_fault('checkpoint', 'panic', dbid) from gp_segment_configuration
content=0 and role='p';
```
The above SQL command should emit a warning like this:
```
WARNING:  consider disabling FTS probes while injecting a panic.  (seg0 127.0.0.1:7002 pid=27680)
HINT:  Inject a 'skip' into the 'fts_probe' fault to disable FTS probing.
```

### Actual behavior
No warning is emitted.

This is because `_PG_init()` function of `gp_inject_fault` extension is executed by `create extension` command while loading the shared library that implements the extension.  The `gp_inject_fault()` UDF, however, creates a new libpq connection, creating a transient "fault handler" backend process to invoke `InjectFault()` function.  This process has the `warnings_list` global variable set to empty, so no warning is emitted.  See fbd0f091a21cc2d25b4c52e3182c9dc934ca0ce5 for more details.

**Comment by asimrp** [comment]
@berlin-ab FYI.

**Comment by berlin-ab** [comment]
@asimrp Do you think adding to shared memory for this is out of the question?

**Comment by ashwinstar** [comment]
No plans to fix this issue as not seen problem in CI related to this.
