### ISSUE TITLE
gphdfs run very long time and can't complete

### ISSUE THREAD

**Issue by weiyong-dba** [greenplum-db/gpdb#8373]
### Greenplum version or build
PostgreSQL 8.3.23 (Greenplum Database 5.12.0 build commit:6b542cd470174af5559a431318037521f4ad55a6) on x86_64-pc-linux-gnu, compiled by GCC gcc (GCC) 6.2.0, 64-bit compiled on Oct 17 2018 16:57:19
### OS version and uname -a
Linux 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

Hi, 
When i use gphdfs to load data from hadoop cluster, it run for very long time and can't complete. 
I have 4 segment on segment host, 3 segment is complete ,1 segment not complete and have not any error. 
The print of jstack show 1 thread is IN_NATIVE state, other thread is BLOCKED.
What's the problem? 

$jstack -F 2674
Attaching to process ID 2674, please wait...
Debugger attached successfully.
Server compiler detected.
JVM version is 25.66-b17
Deadlock Detection:

No deadlocks found.

Thread 3073: (state = BLOCKED)
 - java.lang.Thread.sleep(long) @bci=0 (Compiled frame; information may be imprecise)
 - org.apache.hadoop.hdfs.PeerCache.run() @bci=41, line=253 (Interpreted frame)
 - org.apache.hadoop.hdfs.PeerCache.access$000(org.apache.hadoop.hdfs.PeerCache) @bci=1, line=46 (Interpreted frame)
 - org.apache.hadoop.hdfs.PeerCache$1.run() @bci=4, line=124 (Interpreted frame)
 - java.lang.Thread.run() @bci=11, line=745 (Interpreted frame)

Thread 2843: (state = BLOCKED)
 - java.lang.Object.wait(long) @bci=0 (Compiled frame; information may be imprecise)
 - java.lang.ref.ReferenceQueue.remove(long) @bci=59, line=143 (Compiled frame)
 - java.lang.ref.ReferenceQueue.remove() @bci=2, line=164 (Compiled frame)
 - org.apache.hadoop.fs.FileSystem$Statistics$StatisticsDataReferenceCleaner.run() @bci=9, line=3806 (Interpreted frame)
 - java.lang.Thread.run() @bci=11, line=745 (Interpreted frame)

Thread 2770: (state = BLOCKED)

Thread 2762: (state = BLOCKED)
 - java.lang.Object.wait(long) @bci=0 (Compiled frame; information may be imprecise)
 - java.lang.ref.ReferenceQueue.remove(long) @bci=59, line=143 (Compiled frame)
 - java.lang.ref.ReferenceQueue.remove() @bci=2, line=164 (Compiled frame)
 - java.lang.ref.Finalizer$FinalizerThread.run() @bci=36, line=209 (Interpreted frame)

Thread 2760: (state = BLOCKED)
 - java.lang.Object.wait(long) @bci=0 (Compiled frame; information may be imprecise)
 - java.lang.Object.wait() @bci=2, line=502 (Interpreted frame)
 - java.lang.ref.Reference$ReferenceHandler.run() @bci=36, line=157 (Interpreted frame)

Thread 2676: (state = IN_NATIVE)
 - java.io.FileOutputStream.writeBytes(byte[], int, int, boolean) @bci=0 (Compiled frame; information may be imprecise)
 - java.io.FileOutputStream.write(byte[], int, int) @bci=8, line=326 (Compiled frame)
 - java.io.BufferedOutputStream.write(byte[], int, int) @bci=20, line=122 (Compiled frame)
 - java.io.PrintStream.write(byte[], int, int) @bci=16, line=480 (Compiled frame)
 - sun.nio.cs.StreamEncoder.writeBytes() @bci=120, line=221 (Compiled frame)
 - sun.nio.cs.StreamEncoder.implFlushBuffer() @bci=11, line=291 (Compiled frame)
 - sun.nio.cs.StreamEncoder.implFlush() @bci=1, line=295 (Interpreted frame)
 - sun.nio.cs.StreamEncoder.flush() @bci=12, line=141 (Interpreted frame)
 - java.io.OutputStreamWriter.flush() @bci=4, line=229 (Interpreted frame)
 - org.apache.log4j.helpers.QuietWriter.flush() @bci=4, line=59 (Interpreted frame)
 - org.apache.log4j.WriterAppender.subAppend(org.apache.log4j.spi.LoggingEvent) @bci=85, line=324 (Interpreted frame)
 - org.apache.log4j.WriterAppender.append(org.apache.log4j.spi.LoggingEvent) @bci=10, line=162 (Interpreted frame)
 - org.apache.log4j.AppenderSkeleton.doAppend(org.apache.log4j.spi.LoggingEvent) @bci=106, line=251 (Interpreted frame)
 - org.apache.log4j.helpers.AppenderAttachableImpl.appendLoopOnAppenders(org.apache.log4j.spi.LoggingEvent) @bci=41, line=66 (Interpreted frame)
 - org.apache.log4j.Category.callAppenders(org.apache.log4j.spi.LoggingEvent) @bci=26, line=206 (Interpreted frame)
 - org.apache.log4j.Category.forcedLog(java.lang.String, org.apache.log4j.Priority, java.lang.Object, java.lang.Throwable) @bci=14, line=391 (Compiled frame)
 - org.apache.log4j.Category.log(java.lang.String, org.apache.log4j.Priority, java.lang.Object, java.lang.Throwable) @bci=34, line=856 (Compiled frame)
 - org.slf4j.impl.Log4jLoggerAdapter.warn(java.lang.String, java.lang.Throwable) @bci=12, line=479 (Interpreted frame)
 - org.apache.hadoop.hdfs.client.impl.BlockReaderFactory.getRemoteBlockReaderFromTcp() @bci=148, line=771 (Compiled frame)
 - org.apache.hadoop.hdfs.client.impl.BlockReaderFactory.build() @bci=182, line=390 (Compiled frame)
 - org.apache.hadoop.hdfs.DFSInputStream.getBlockReader(org.apache.hadoop.hdfs.protocol.LocatedBlock, long, long, java.net.InetSocketAddress, org.apache.hadoop.fs.StorageType, org.apache.hadoop.hdfs.protocol.DatanodeInfo) @bci=183, line=644 (Compiled frame)
 - org.apache.hadoop.hdfs.DFSStripedInputStream.createBlockReader(org.apache.hadoop.hdfs.protocol.LocatedBlock, long, org.apache.hadoop.hdfs.protocol.LocatedBlock[], org.apache.hadoop.hdfs.StripeReader$BlockReaderInfo[], int) @bci=77, line=256 (Compiled frame)
 - org.apache.hadoop.hdfs.StripeReader.readChunk(org.apache.hadoop.hdfs.protocol.LocatedBlock, int) @bci=51, line=293 (Compiled frame)
 - org.apache.hadoop.hdfs.StripeReader.readStripe() @bci=47, line=323 (Compiled frame)
 - org.apache.hadoop.hdfs.DFSStripedInputStream.readOneStripe(org.apache.hadoop.hdfs.DFSUtilClient$CorruptedBlocks) @bci=185, line=318 (Compiled frame)
 - org.apache.hadoop.hdfs.DFSStripedInputStream.readWithStrategy(org.apache.hadoop.hdfs.ReaderStrategy) @bci=172, line=391 (Compiled frame)
 - org.apache.hadoop.hdfs.DFSInputStream.read(byte[], int, int) @bci=63, line=815 (Compiled frame)
 - java.io.DataInputStream.read(byte[], int, int) @bci=7, line=149 (Compiled frame)
 - org.apache.hadoop.mapreduce.lib.input.UncompressedSplitLineReader.fillBuffer(java.io.InputStream, byte[], boolean) @bci=46, line=62 (Compiled frame)
 - org.apache.hadoop.util.LineReader.readDefaultLine(org.apache.hadoop.io.Text, int, int) @bci=64, line=218 (Compiled frame)
 - org.apache.hadoop.util.LineReader.readLine(org.apache.hadoop.io.Text, int, int) @bci=19, line=176 (Compiled frame)
 - org.apache.hadoop.mapreduce.lib.input.UncompressedSplitLineReader.readLine(org.apache.hadoop.io.Text, int, int) @bci=31, line=94 (Compiled frame)
 - org.apache.hadoop.mapreduce.lib.input.LineRecordReader.skipUtfByteOrderMark() @bci=34, line=152 (Compiled frame)
 - org.apache.hadoop.mapreduce.lib.input.LineRecordReader.nextKeyValue() @bci=81, line=192 (Compiled frame)
 - com.emc.greenplum.gpdb.hdfsconnector.HDFSReader.readTextFormat() @bci=57, line=191 (Compiled frame)
 - com.emc.greenplum.gpdb.hdfsconnector.HDFSReader.doRead() @bci=19, line=159 (Interpreted frame)
 - com.emc.greenplum.gpdb.hdfsconnector.HDFSReader.main(java.lang.String[]) @bci=10, line=254 (Interpreted frame)

**Comment by frankgh** [comment]
@dbawy can you try using PXF instead https://gpdb.docs.pivotal.io/5120/pxf/instcfg_pxf.html ?
Let me know if that is an alternative

**Comment by adam8157** [comment]
It's been a long time without a response, closing this.
