### ISSUE TITLE
inconsistent documentation for CREATE INDEX CONCURRENTLY

### ISSUE THREAD

**Issue by dkrieger-pvtl** [greenplum-db/gpdb#8377]
When reading #8214, I noticed that we document that the user can use the `CONCURRENTLY` keyword to create an index that can later be attached to a table, but we later mention that Greenplum does not support this keyword.  Presumably, we do not want to frustrate a user with inconsistent documentation.  Perhaps a different example for use of `ALTER TABLE...ADD table_constraint_using_index`?  Or we actually support `CONCURRENTLY`?

We tell the user that they can use `CONCURRENTLY`(https://gpdb.docs.pivotal.io/6-0Beta/ref_guide/sql_commands/ALTER_TABLE.html):

```
Note: Adding a constraint using an existing index can be helpful
in situations where a new constraint needs to be added without
blocking table updates for a long time. To do that, create the
index using CREATE INDEX CONCURRENTLY, and then install it
as an official constraint using this syntax. See the example below.
```
Further, in that same page, we provide an example, which presumably can't possibly run due to the later documentation:
```
CREATE UNIQUE INDEX CONCURRENTLY dist_id_temp_idx ON distributors (dist_id);
ALTER TABLE distributors DROP CONSTRAINT distributors_pkey,
ADD CONSTRAINT distributors_pkey PRIMARY KEY USING INDEX dist_id_temp_idx;
```
But we then document that this mentioned use case cannot be used:
(https://gpdb.docs.pivotal.io/6-0Beta/ref_guide/sql_commands/CREATE_INDEX.html)

```
Greenplum Database does not support the concurrent creation of 
indexes (CONCURRENTLY keyword not supported).
```

**Comment by mkiyama** [comment]
Created a tracker story for this issue.

**Comment by mkiyama** [comment]
fixed See doc PR
https://github.com/greenplum-db/gpdb/pull/8409
