### ISSUE TITLE
gpcheckcloud does not check s3 correctly

### ISSUE THREAD

**Issue by umitanuki** [greenplum-db/gpdb#8382]
### Greenplum version or build
Greenplum Database 6.0.0-beta.6+dev.253.gfdecccf417 build dev

### Expected behavior
Using s3 readable external table, and following the document instruction, I set up AWS key in the config file. `gpcheckcloud -c "s3://... config=s3.conf"` runs fine saying 
```
Your configuration works well.
```

but actual `SELECT * FROM s3table` fails saying 

```
ERROR:  s3_import: could not read data: reader_transfer_data caught a S3LogicError exception: AWS returns error AccessDenied : Access Denied, Function: checkCompressionType, File: src/s3interface.cpp(386). (gpcloud.cpp:315)  (seg15 slice1 192.168.1.194:7015 pid=58927) (gpcloud.cpp:315)
```

Turned out the AWS policy did not have GetObject permission but the error was cryptic.

### Actual behavior
`gpcheckcloud -c` should report missing GetObject permission correctly.

**Comment by ivannovick** [comment]
@brianlugongyu can you help to triage this and find out the fix?

**Comment by lij55** [comment]
Thanks for reporting @umitanuki .
The error message printed by gpcheckcloud is from AWS RPC. "Access Denied" indicate insufficient permission so I think the error message is find enough. I will close this issue for now.
