### ISSUE TITLE
requested WAL segment 000000010000000000000025 has already been removed

### ISSUE THREAD

**Issue by wujunqing** [greenplum-db/gpdb#8388]
### Greenplum version or build
GPDB Version 5.4.1
### OS version and uname -a
Linux master_01 3.10.0-693.11.6.el7.x86_64 #1 SMP Thu Jan 4 01:06:37 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux 
### Installation information ( pg_config )
BINDIR = /data/local/greenplum-db-5.4.1/bin
DOCDIR = /data/local/greenplum-db-5.4.1/doc/postgresql
HTMLDIR = /data/local/greenplum-db-5.4.1/doc/postgresql
INCLUDEDIR = /data/local/greenplum-db-5.4.1/include
PKGINCLUDEDIR = /data/local/greenplum-db-5.4.1/include/postgresql
INCLUDEDIR-SERVER = /data/local/greenplum-db-5.4.1/include/postgresql/server
LIBDIR = /data/local/greenplum-db-5.4.1/lib
PKGLIBDIR = /data/local/greenplum-db-5.4.1/lib/postgresql
LOCALEDIR = /data/local/greenplum-db-5.4.1/share/locale
MANDIR = /data/local/greenplum-db-5.4.1/man
SHAREDIR = /data/local/greenplum-db-5.4.1/share/postgresql
SYSCONFDIR = /data/local/greenplum-db-5.4.1/etc/postgresql
PGXS = /data/local/greenplum-db-5.4.1/lib/postgresql/pgxs/src/makefiles/pgxs.mk
CC = gcc -m64
CPPFLAGS = -D_GNU_SOURCE -I/data/local/greenplum-db-5.4.1/include
CFLAGS = -m64 -O3 -fargument-noalias-global -fno-omit-frame-pointer -g -std=gnu99 -Wall -Wmissing-prototypes -Wpointer-arith -Wendif-labels -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fno-aggressive-loop-optimizations -Wno-unused-but-set-variable -Wno-address -I/data/local/greenplum-db-5.4.1/include
CFLAGS_SL = -fpic
LDFLAGS = -Wl,--as-needed -Wl,-rpath,'/usr/local/greenplum-db-devel/lib',--enable-new-dtags -L/data/local/greenplum-db-5.4.1/lib
LDFLAGS_SL = 
LIBS = -lpgport -lgpopt -lnaucrates -lgpdbcost -lgpos -lxerces-c -lxml2 -lpam -lrt -lkrb5 -lcom_err -lgssapi_krb5 -lcrypt -ldl -lm -lrt -L/data/local/greenplum-db-5.4.1/lib

### Step to reproduce the behavior
Please tell me the reason of this mistake . thanks 

gpdb log error info:

2019-08-15 11:48:52.512085 CST,"gpadmin",,p29333,th-1978067072,"10.62.2.99","6706",2019-08-15 11:48:52 CST,0,,,seg-1,,,,,"ERROR","58P01","requested WAL segment 000000010000000000000025 has already been removed",,,,,,,0,,"walsender.c",884,"Stack trace:
1    0x9561fb postgres errstart (elog.c:521)
2    0x7fc658 postgres XLogRead (walsender.c:881)
3    0x7fc7af postgres <symbol not found> (walsender.c:1056)
4    0x7fda22 postgres exec_replication_command (walsender.c:588)
5    0x832c47 postgres PostgresMain (postgres.c:5010)
6    0x7d1d75 postgres <symbol not found> (postmaster.c:6397)
7    0x7d454a postgres PostmasterMain (postmaster.c:1537)
8    0x4c88f7 postgres main (main.c:206)
9    0x7faf8564eb35 libc.so.6 __libc_start_main + 0xf5
10   0x4c8e4c postgres <symbol not found> + 0x4c8e4c
"

**Comment by ashwinstar** [comment]
I am not clear what is referred to as mistake here? WAL gets cleaned based on checkpoint and there is possibility WAL is cleaned from master before was streamed to standby. If that happens will get this error and need to recreate the standby.

For GPDB6 and further, we use replication slots to prevent this situation from happening. For GPDB5 can use `keep_wal_segments` GUC "Sets the number of WAL files held for standby servers." (with caution) to keep the wal around.

I am closing the issue as no further action on the same. Please feel free to post follow-up question if any.
