### ISSUE TITLE
docs: Greenplum Database does not support DISTINCT with multiple input expressions.

### ISSUE THREAD

**Issue by hlinnaka** [greenplum-db/gpdb#8422]
### Greenplum version or build
6

The documentation at https://github.com/greenplum-db/gpdb/blob/master/gpdb-doc/dita/admin_guide/query/topics/defining-queries.xml#L265 says:
> Greenplum Database does not support DISTINCT with multiple input expressions. 

That is not quite true. I think this refers to this limitation in GPDB 5:
```
postgres=# select string_agg(distinct g::text, ' ') from generate_series(1,10) g;
ERROR:  DISTINCT is supported only for single-argument aggregates
```
But it is supported in GPDB 6:
```
postgres=# select string_agg(distinct g::text, ' ') from generate_series(1,10) g;
      string_agg      
----------------------
 1 10 2 3 4 5 6 7 8 9
(1 row)
```
However, it's still not supported in window aggregates:
```
postgres=# select string_agg(distinct g::text, ' ') over (partition by (g)) from generate_series(1,10) g;
ERROR:  DISTINCT is supported only for single-argument window aggregates
```

**Comment by hlinnaka** [comment]
@mkiyama, spotted this while reviewing an unrelated docs PR. Assigned to you, feel free to assign to someone else if you're not the right person.

**Comment by mkiyama** [comment]
Thanks, I created a tracker story for this issue.
