### ISSUE TITLE
Failed rebalance cluster with "gprecoverseg -r"

### ISSUE THREAD

**Issue by leyxiaox** [greenplum-db/gpdb#8432]
### Greenplum version or build
postgres (Greenplum Database) 6.0.0-beta.7 build commit:0ea586b88e231d4f4e346c663b2eea7cbc5797a8
### OS version and uname -a
Linux mdw 3.10.0-693.el7.x86_64 #1 SMP Thu Jul 6 19:56:57 EDT 2017 x86_64 x86_64 x86_64 GNU/Linux
### Installation information ( pg_config )
BINDIR = /usr/local/greenplum-db-6.0.0-beta.7/bin
DOCDIR = /usr/local/greenplum-db-6.0.0-beta.7/share/doc/postgresql
HTMLDIR = /usr/local/greenplum-db-6.0.0-beta.7/share/doc/postgresql
INCLUDEDIR = /usr/local/greenplum-db-6.0.0-beta.7/include
PKGINCLUDEDIR = /usr/local/greenplum-db-6.0.0-beta.7/include/postgresql
INCLUDEDIR-SERVER = /usr/local/greenplum-db-6.0.0-beta.7/include/postgresql/server
LIBDIR = /usr/local/greenplum-db-6.0.0-beta.7/lib
PKGLIBDIR = /usr/local/greenplum-db-6.0.0-beta.7/lib/postgresql
LOCALEDIR = /usr/local/greenplum-db-6.0.0-beta.7/share/locale
MANDIR = /usr/local/greenplum-db-6.0.0-beta.7/man
SHAREDIR = /usr/local/greenplum-db-6.0.0-beta.7/share/postgresql
SYSCONFDIR = /usr/local/greenplum-db-6.0.0-beta.7/etc/postgresql
PGXS = /usr/local/greenplum-db-6.0.0-beta.7/lib/postgresql/pgxs/src/makefiles/pgxs.mk
CONFIGURE = '--with-quicklz' '--enable-tap-tests' '--enable-gpperfmon' '--with-gssapi' '--enable-mapreduce' '--enable-orafce' '--enable-orca' '--with-libxml' '--with-pgport=5432' '--with-libedit-preferred' '--with-perl' '--with-python' '--with-includes=/tmp/build/f8c7ee08/gpdb_src/gpAux/ext/rhel7_x86_64/include /tmp/build/f8c7ee08/gpdb_src/gpAux/ext/rhel7_x86_64/include/libxml2' '--with-libraries=/tmp/build/f8c7ee08/gpdb_src/gpAux/ext/rhel7_x86_64/lib' '--with-openssl' '--with-pam' '--with-ldap' '--prefix=/usr/local/greenplum-db-devel' '--mandir=/usr/local/greenplum-db-devel/man' 'CC=gcc -m64' 'CFLAGS=-m64 -O3 -fargument-noalias-global -fno-omit-frame-pointer -g'
CC = gcc -m64
CPPFLAGS = -D_GNU_SOURCE -I/usr/include/libxml2 -I/tmp/build/f8c7ee08/gpdb_src/gpAux/ext/rhel7_x86_64/include -I/usr/local/greenplum-db-6.0.0-beta.7/include
CFLAGS = -Wall -Wmissing-prototypes -Wpointer-arith -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fno-aggressive-loop-optimizations -Wno-unused-but-set-variable -Wno-address -m64 -O3 -fargument-noalias-global -fno-omit-frame-pointer -g -std=gnu99 -Werror=uninitialized -Werror=implicit-function-declaration -I/usr/local/greenplum-db-6.0.0-beta.7/include
CFLAGS_SL = -fPIC
LDFLAGS = -L/tmp/build/f8c7ee08/gpdb_src/gpAux/ext/rhel7_x86_64/lib -Wl,--as-needed -Wl,-rpath,'/usr/local/greenplum-db-devel/lib',--enable-new-dtags -L/usr/local/greenplum-db-6.0.0-beta.7/lib
LDFLAGS_EX = 
LDFLAGS_SL = 
LIBS = -lpgcommon -lpgport -lgpopt -lnaucrates -lgpdbcost -lgpos -lxerces-c -lxml2 -lpam -lrt -lyaml -lgssapi_krb5 -lquicklz -lzstd -lrt -lcrypt -ldl -lm -L/usr/local/greenplum-db-6.0.0-beta.7/lib
VERSION = PostgreSQL 9.4.23
### Expected behavior
Cluster returned to normal after  exectuted "gprecoverseg -r"
### Actual behavior
Incremental recovery failed for dbid *. You must use gprecoverseg -F to recover the segment.
### Step to reproduce the behavior
1. Begin with a normal cluster with mirror segments configured.
2. reboot one of segments host(assume host A).
3. All segments including primary and mirror in host A failed and cluster failedover.
4. Host A started.
5. execute "gprecoverseg -a" to bring failed instance to startup
6. some mirror in other hosts still "Acting as Primary" since the failure 
7. Rebalnce with "gprecoverseg -r"
"20190820:11:31:39:165315 gprecoverseg:mdw:gpadmin-[WARNING]:-Incremental recovery failed for dbid *. You must use gprecoverseg -F to recover the segment."
8. Incremental recovery failed, the only way for me is to do a Full recovery but it might cause performance problem if the data size is large.

BTW, I also can repro this issue in GP6.beta5 but it works fine in GP5, could you feel free help take an investigation, thanks.

**Comment by paul-guo-** [comment]
You could run `gprecover -rv` when running rebalancing to provide more logs also you could provide more pg logs of those failed primary/segment else it's hard to guess the reason.

**Comment by leyxiaox** [comment]
[gprecoversegrv.log](https://github.com/greenplum-db/gpdb/files/3518944/gprecoversegrv.log)
Thanks for the reply, attached gprecoversegrv.log for more investigating. 
BTW, Mentioned again , it can works well in GP5, but failed in GP6. could you help have a try to see if you can repro this issue.

**Comment by ashwinstar** [comment]
Looks like failed to connect to the current primary segment from old mirror based on logs, causing `pg_rewind` to fail, means incremental recovery to fail.

```
20190820:14:05:45:175138 gprecoverseg:mdw:gpadmin-[DEBUG]:-Running Command: [ -f /hdd/gpmirror/gpseg6/recovery.conf ] || PGOPTIONS="-c gp_session_role=utility" $GPHOME/bin/pg_rewind --write-recovery-conf --slot="internal_wal_replication_slot" --source-server="host=sdw2 port=6000 dbname=template1 application_name=__gprecoverseg_pg_rewind__" --target-pgdata=/hdd/gpmirror/gpseg6 --progress 2>&1
20190820:14:05:45:175138 gprecoverseg:mdw:gpadmin-[DEBUG]:-cmd had rc=1 completed=True halted=False
  stdout='
could not connect to server: FATAL:  no pg_hba.conf entry for host "10.10.99.4", user "gpadmin", database "template1", SSL off
Failure, exiting
'
  stderr=''
20190820:14:05:45:175138 gprecoverseg:mdw:gpadmin-[DEBUG]:-pg_rewind failed for target directory /hdd/gpmirror/gpseg6.
20190820:14:05:45:175138 gprecoverseg:mdw:gpadmin-[WARNING]:-Incremental recovery failed for dbid 20. You must use gprecoverseg -F to recover the segment.
```

**Comment by leyxiaox** [comment]
@ashwinstar Hi Ashwinstar, do you mean I should maually add the entry in pg_hba.conf?

**Comment by gaos1** [comment]
could you also upload your pg_hba.conf file on one segment?

**Comment by leyxiaox** [comment]
[pg_hba_conf.txt](https://github.com/greenplum-db/gpdb/files/3519771/pg_hba_conf.txt)
See attached.

**Comment by brianlugongyu** [comment]
@ashwinstar, should this item "host all gpadmin 10.10.99.4/32 trust" be added automatically instead of manually?

**Comment by ashwinstar** [comment]
>> @ashwinstar Hi Ashwinstar, do you mean I should manually add the entry in pg_hba.conf?

Nope. We need to investigate and code needs to be fixed. I didn't had cycles to look into this issue today. But seems like `pg_rewind` is not using the correct way to connect somewhere causing the failure. I am blindly guessing the single user mode start we do as part of `pg_rewind` which uses template1 database is the problem.

**Comment by berlin-ab** [comment]
Do the hosts have fixed IP addresses, or are they assigned dynamically?

**Comment by ashwinstar** [comment]
Thank you for reporting the issue. We (@d and I) are able to repro the issue locally. The setup essentially needs multi-host, we used 2 docker containers for the same. The issue stems from code not updating the `pg_hba.conf` file after performing `pg_basebackup` or `pg_rewind` when recreating the mirror. Didn't spend time looking into the fix today.

**Comment by ashwinstar** [comment]
Just to update PR https://github.com/greenplum-db/gpdb/pull/8517 fixes this issue (it's yet to be merged in master)

**Comment by bhuvnesh2703** [comment]
Fix Merged. Resolving the issue.
