### ISSUE TITLE
Mirrors fail to build during a gpinitsystem command.

### ISSUE THREAD

**Issue by KAdamsInCO** [greenplum-db/gpdb#8441]
### Greenplum version or build

GPDB 6, Beta 7

### OS version and uname -a

[gpadmin@mdw ~]$ uname -a
Linux mdw 3.10.0-957.27.2.el7.x86_64 #1 SMP Mon Jul 29 17:46:05 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

### Expected behavior

Run a gpinitsystem with mirrors enabled and mirror DB segments should be created as expected.

### Actual behavior

Ran a gpinitsystem to include mirrors, and the mirror build failed with a syntax error. The cluster came up with primaries only.

### Step to reproduce the behavior

gpinitsystem -c gpinitsystem_config -s smdw -a

20190820:17:54:53:002441 gpinitsystem:mdw:gpadmin-[INFO]:-Building primary segment instance array, please wait...
....
/usr/local/greenplum-db/./bin/gpinitsystem: line 1000: ((: MIRROR_REPLICATION_PORT_OFFSET=-: syntax error: operand expected (error token is "-")
20190820:17:54:54:002441 gpinitsystem:mdw:gpadmin-[INFO]:-Building group mirror array type , please wait...
./usr/local/greenplum-db/./bin/lib/gp_bash_functions.sh: line 585: 0+: syntax error: operand expected (error token is "+")

20190820:17:55:23:002441 gpinitsystem:mdw:gpadmin-[INFO]:-Completed restart of Greenplum instance in production mode
20190820:17:55:23:002441 gpinitsystem:mdw:gpadmin-[FATAL]:-Failed to complete failed to register mirror for contentid=  Script Exiting!

[gpadmin@mdw ~]$ psql
psql (9.4.23)
Type "help" for help.

gpadmin=# select * from gp_segment_configuration;
 dbid | content | role | preferred_role | mode | status | port | hostname | address |       datadir        
------+---------+------+----------------+------+--------+------+----------+---------+----------------------
    1 |      -1 | p    | p              | n    | u      | 5432 | mdw      | mdw     | /data/master/gpseg-1
    2 |       0 | p    | p              | n    | u      | 6000 | sdw1     | sdw1    | /data/primary/gpseg0
    3 |       1 | p    | p              | n    | u      | 6001 | sdw1     | sdw1    | /data/primary/gpseg1
    4 |       2 | p    | p              | n    | u      | 6000 | sdw2     | sdw2    | /data/primary/gpseg2
    5 |       3 | p    | p              | n    | u      | 6001 | sdw2     | sdw2    | /data/primary/gpseg3
(5 rows)

gpadmin=# select version();
                                                                                                   version                                                      
                                             
----------------------------------------------------------------------------------------------------------------------------------------------------------------
---------------------------------------------
 PostgreSQL 9.4.23 (Greenplum Database 6.0.0-beta.7 build commit:0ea586b88e231d4f4e346c663b2eea7cbc5797a8) on x86_64-unknown-linux-gnu, compiled by gcc (GCC) 6.
4.0, 64-bit compiled on Aug 14 2019 18:20:25
(1 row)

**Comment by KAdamsInCO** [comment]
[gpinitsystem_config.txt](https://github.com/greenplum-db/gpdb/files/3521972/gpinitsystem_config.txt)

**Comment by KAdamsInCO** [comment]
[gpadmin@mdw ~]$ gpssh -f seghosts 
=> ls -al /data
[sdw1] total 0
[sdw1] drwxr-xr-x   4 root    root     35 Aug 19 19:58 .
[sdw1] dr-xr-xr-x. 18 root    root    236 Aug 19 19:58 ..
[sdw1] drwxrwx---   2 gpadmin gpadmin   6 Aug 19 19:58 mirror
[sdw1] drwxrwx---   4 gpadmin gpadmin  34 Aug 20 17:55 primary
[sdw2] total 0
[sdw2] drwxr-xr-x   4 root    root     35 Aug 19 19:58 .
[sdw2] dr-xr-xr-x. 18 root    root    236 Aug 19 19:58 ..
[sdw2] drwxrwx---   2 gpadmin gpadmin   6 Aug 19 19:58 mirror
[sdw2] drwxrwx---   4 gpadmin gpadmin  34 Aug 20 17:55 primary

**Comment by KAdamsInCO** [comment]
[gpstop_20190820.log](https://github.com/greenplum-db/gpdb/files/3521998/gpstop_20190820.log)
[gpstart_20190820.log](https://github.com/greenplum-db/gpdb/files/3521999/gpstart_20190820.log)
[gpinitsystem_20190820.log](https://github.com/greenplum-db/gpdb/files/3522000/gpinitsystem_20190820.log)
[init_debug_output.txt](https://github.com/greenplum-db/gpdb/files/3522001/init_debug_output.txt)

**Comment by jchampio** [comment]
Thanks for finding this issue! It was masked in our testing by stale cluster configurations. PR to fix is up.

**Comment by jchampio** [comment]
Reopening for now; this is fixed in master but not the target version.

**Comment by jchampio** [comment]
@KAdamsInCO This is now fixed in 6X_STABLE, if you'd like to build and verify.

**Comment by KAdamsInCO** [comment]
Verified fixed. A gpinitsystem ran without any issues creating the mirror segments. This is in the GP 6.0.0 build.

Details below and attached.

Thanks,

Keaton

[init_config.txt](https://github.com/greenplum-db/gpdb/files/3580447/init_config.txt)
[test_db.txt](https://github.com/greenplum-db/gpdb/files/3580448/test_db.txt)


gpadmin=# select version();
                                                                                               version                                                                                                
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 PostgreSQL 9.4.24 (Greenplum Database 6.0.0 build commit:a2ff2fc318c327d702e66ab58ae4aff34c42296c) on x86_64-unknown-linux-gnu, compiled by gcc (GCC) 6.4.0, 64-bit compiled on Aug 28 2019 21:29:36
(1 row)

gpadmin=# select * from gp_segment_configuration order by hostname, role;
 dbid | content | role | preferred_role | mode | status | port | hostname | address |       datadir        
------+---------+------+----------------+------+--------+------+----------+---------+----------------------
    1 |      -1 | p    | p              | n    | u      | 5432 | mdw      | mdw     | /data/master/gpseg-1
    9 |       3 | m    | m              | s    | u      | 7001 | sdw1     | sdw1    | /data/mirror/gpseg3
    8 |       2 | m    | m              | s    | u      | 7000 | sdw1     | sdw1    | /data/mirror/gpseg2
    2 |       0 | p    | p              | s    | u      | 6000 | sdw1     | sdw1    | /data/primary/gpseg0
    3 |       1 | p    | p              | s    | u      | 6001 | sdw1     | sdw1    | /data/primary/gpseg1
    6 |       0 | m    | m              | s    | u      | 7000 | sdw2     | sdw2    | /data/mirror/gpseg0
    7 |       1 | m    | m              | s    | u      | 7001 | sdw2     | sdw2    | /data/mirror/gpseg1
    4 |       2 | p    | p              | s    | u      | 6000 | sdw2     | sdw2    | /data/primary/gpseg2
    5 |       3 | p    | p              | s    | u      | 6001 | sdw2     | sdw2    | /data/primary/gpseg3
   10 |      -1 | m    | m              | s    | u      | 5432 | smdw     | smdw    | /data/master/gpseg-1
(10 rows)

**Comment by ashwinstar** [comment]
Great thanks @KAdamsInCO for reporting and more importantly verifying it fixed now.
