### ISSUE TITLE
Recieved warning when running a gpdeletesystem when backup files did not exist.

### ISSUE THREAD

**Issue by KAdamsInCO** [greenplum-db/gpdb#8442]
### Greenplum version or build

GPDB 6, Beta 7

### OS version and uname -a

CentOS 7

[gpadmin@mdw ~]$ uname -a
Linux mdw 3.10.0-957.27.2.el7.x86_64 #1 SMP Mon Jul 29 17:46:05 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

### Expected behavior

Run a gpdeletesystem, and if backup files are not present, do not fail out the command with a warning about backup files.

### Actual behavior
For some reason, when I ran a gpdeletesystem against a newly initialized cluster, the command failed with an error that backup files existed, even though a backup had never been run.

### Step to reproduce the behavior
Initialize a new Greenplum 6, Beta 7 database.

[gpadmin@mdw ~]$ gpinitsystem -c gpinitsystem_config -s smdw -a

Then issue a gpdeletesystem command to remove it:

[gpadmin@mdw ~]$ export MASTER_DATA_DIRECTORY=/data/master/gpseg-1
[gpadmin@mdw ~]$ 
[gpadmin@mdw ~]$ gpdeletesystem
20190820:18:20:30:015086 gpdeletesystem:mdw:gpadmin-[INFO]:-Option -d or --master-data-directory not set. Checking environment variable MASTER_DATA_DIRECTORY
20190820:18:20:30:015086 gpdeletesystem:mdw:gpadmin-[INFO]:-Checking for database dump files...
20190820:18:20:30:015086 gpdeletesystem:mdw:gpadmin-[CRITICAL]:-Located possible database backup file on Master instance host
20190820:18:20:30:015086 gpdeletesystem:mdw:gpadmin-[CRITICAL]:-in directory /data/master/gpseg-1
20190820:18:20:30:015086 gpdeletesystem:mdw:gpadmin-[CRITICAL]:-To override database backup file checking use -f option
20190820:18:20:30:015086 gpdeletesystem:mdw:gpadmin-[CRITICAL]:-Backup files exist
20190820:18:20:30:015086 gpdeletesystem:mdw:gpadmin-[ERROR]:-Delete system failed
[gpadmin@mdw ~]$ 

The command requires overriding testing for backups with the -f option to work:

[gpadmin@mdw ~]$ gpdeletesystem -f
20190820:18:20:36:015092 gpdeletesystem:mdw:gpadmin-[INFO]:-Option -d or --master-data-directory not set. Checking environment variable MASTER_DATA_DIRECTORY
20190820:18:20:36:015092 gpdeletesystem:mdw:gpadmin-[INFO]:-Checking for database dump files...
20190820:18:20:37:015092 gpdeletesystem:mdw:gpadmin-[INFO]:-Getting segment information...
.
.
.
.
20190820:18:20:38:015092 gpdeletesystem:mdw:gpadmin-[WARNING]:-There are database dump files, these will be DELETED if you continue!
.
.
.
20190820:18:20:46:015092 gpdeletesystem:mdw:gpadmin-[INFO]:-Waiting for worker threads to complete...
20190820:18:20:47:015092 gpdeletesystem:mdw:gpadmin-[WARNING]:-Delete system completed but warnings were generated.

[gpdeletesystem_steps.txt](https://github.com/greenplum-db/gpdb/files/3522040/gpdeletesystem_steps.txt)

**Comment by KAdamsInCO** [comment]
[gpdeletesystem_20190820.log](https://github.com/greenplum-db/gpdb/files/3522046/gpdeletesystem_20190820.log)

**Comment by jchampio** [comment]
I think `gpsegconfig_dump` is probably throwing it.
