### ISSUE TITLE
Can't create a View with more than 1600 columns

### ISSUE THREAD

**Issue by jsanko9** [greenplum-db/gpdb#8468]
### Greenplum version or build

PostgreSQL 8.3.23 (Greenplum Database 5.17.0 build commit:fc9a9d4cad8dd4037b9bc07bf837c0b958726103) on x86_64-pc-linux-gnu, compiled by GCC gcc (GCC) 6.2.0, 64-bit compiled on Feb 13 2019 15:26:34

### OS version and uname -a
N/A
### autoconf options used ( config.status --config )
N/A
### Installation information ( pg_config )
N/A
### Expected behavior
As per this site: 
https://community.pivotal.io/s/article/FAQ--Pivotal-Greenplum-Limits
I should be able to create view with unlimited number of columns.
### Actual behavior
If >1600 columns
ERROR: tables can have at most 1600 columns
if >1664 columns 
ERROR: target lists can have at most 1664 entries

**Once again, I'm creating view, not a table**

### Step to reproduce the behavior
[view_column_test.txt](https://github.com/greenplum-db/gpdb/files/3530209/view_column_test.txt)

**Comment by gaos1** [comment]
per the doc, max column in a view is 1664.
