### ISSUE TITLE
External table column list limited to 1600

### ISSUE THREAD

**Issue by jsanko9** [greenplum-db/gpdb#8469]
### Greenplum version or build
PostgreSQL 8.3.23 (Greenplum Database 5.17.0 build commit:fc9a9d4cad8dd4037b9bc07bf837c0b958726103) on x86_64-pc-linux-gnu, compiled by GCC gcc (GCC) 6.2.0, 64-bit compiled on Feb 13 2019 15:26:34
### OS version and uname -a
N/A
### autoconf options used ( config.status --config )
N/A
### Installation information ( pg_config )
N/A
### Expected behavior
This issue is in relation to #8468. For machine learning use case we are trying to export directly into HDFS. We are facing issue with limited number of columns, which should not happen when converting to file of text type as these do not have same limitation.

Ideal state would be for us to be able prepare data segments in tables and then have them combined in analytical dataset view, that will be exported to HDFS to be used in Hive.

### Actual behavior
ERROR: tables can have at most 1600 columns

### Step to reproduce the behavior
[external_table_problem_example.txt](https://github.com/greenplum-db/gpdb/files/3530262/external_table_problem_example.txt)

**Comment by gaos1** [comment]
so your request is to support more than 1600 columns in external table?

**Comment by jsanko9** [comment]
Hey, yes and no.
This issue was raised in relation to #8468, which is now closed. (Documentation was corrected)

The idea _was_ to be able utilize unlimited size of view and then write to external table. This would allow us utilize GP infrastructure capacity instead of doing joins elsewhere.
As for external table/s, their support for more than 1600 would only be beneficial only if:
1 - It would be still fast to do join on them
2 - Select would be capable of more than 1664 columns.

Just support itself on external table would not help any use-case I have. 
We are trying to do machine-learning ready data export. As for import we would never encounter that large table normally, and for few more years to come.

Hope this clarifies

**Comment by adam8157** [comment]
The limit comes from PostgreSQL, and I don't see a plan extending it, from PG or GP. Close this.

**Comment by jsanko9** [comment]
> The limit comes from PostgreSQL, and I don't see a plan extending it, from PG or GP. Close this.

Hello Adam,
I of course understand that underlying storage for GreenPlum is based on Postgresql. However what I'm asking here is to allow bypassing this limit for **external tables**. This are for example stored in Parquet format or CSV which are not impacted by this limit.
So far it looks to me that select queries are only artificially limited as as its usually pointless to create such huge datasets if you can't store it. But this could be not that big of the problem for external tables.

Also I would like to appeal to sentiment of not considering this an important issue. GreenPlum heralds itself as a "big data" technology, for me that in todays world means supporting Machine Learning and AI Teams as well. Well, for us having a dataset 2k rows is not an uncommon thing, its actually quite advantageous and good practice to have large dataset and do training on it.  Thing is that, if we don't do it on GreenPlum we have to employ another 3rd party system that is not really even intended for such job. Joining on GreenPlum Cluster is simply way better and way more suited for this kind of job than doing it on separately.  Even in terms of investment it makes little sense as we have HUGE GP available (50+ Large Nodes), but we still can't use it for end-to-end "ML Feature Creation".

**Comment by kainwen** [comment]
> > The limit comes from PostgreSQL, and I don't see a plan extending it, from PG or GP. Close this.
> 
> Hello Adam,
> I of course understand that underlying storage for GreenPlum is based on Postgresql. However what I'm asking here is to allow bypassing this limit for **external tables**. This are for example stored in Parquet format or CSV which are not impacted by this limit.
> So far it looks to me that select queries are only artificially limited as as its usually pointless to create such huge datasets if you can't store it. But this could be not that big of the problem for external tables.
> 
> Also I would like to appeal to sentiment of not considering this an important issue. GreenPlum heralds itself as a "big data" technology, for me that in todays world means supporting Machine Learning and AI Teams as well. Well, for us having a dataset 2k rows is not an uncommon thing, its actually quite advantageous and good practice to have large dataset and do training on it. Thing is that, if we don't do it on GreenPlum we have to employ another 3rd party system that is not really even intended for such job. Joining on GreenPlum Cluster is simply way better and way more suited for this kind of job than doing it on separately. Even in terms of investment it makes little sense as we have HUGE GP available (50+ Large Nodes), but we still can't use it for end-to-end "ML Feature Creation".

Hi @jsanko9 

Can you describe a bit more of the computation model of your ML related jobs? Maybe we can come up with other methods to overcome it (like array type).

**Comment by jsanko9** [comment]
Hello @kainwen ,

We have base all data provided in GP trough ETLs, this is serving as Data warehouse and single point of truth.
On top this basic datasets we create logic based on ML models requirements, we clean data input, we create time based aggregations, impute missing values , etc. At the end we are left with a number of wide tables, usually separated by data domain. 

Now, in next step we would like to join them on common key, and export them to HDFS.

Since that is not possible, we have to export all tables separately and join them by other means ( currently in Hive ).
From Hive we either do training on Spark or scoring on VMs. After that's all done we load results back to GP.

We could be using array or json, there are 3 main problems with that:
- requires extra processing time
- logic needs to be implemented in all places and always be called when we do analytics
- in case of array we loose names of columns, in case of json data size is roughly double.

At the moment we have working solution as we join tables in spark, so we are not looking for a work-around. We want this to be done faster and with less extra steps and bit more control.

By allowing us to select more columns into external table this would solve our biggest pain point with dataset creation.

**Comment by asimrp** [comment]
Hey @jsanko9 I acknowledge the problems you've mentioned with using arrays.  Let me share a way to do it in SQL anyway, that I learned from coworkers: http://madlib.apache.org/docs/latest/group__grp__cols2vec.html and http://madlib.apache.org/docs/latest/group__grp__vec2cols.html

**Comment by jsanko9** [comment]
Thank you for suggestion @asimrp, this would work out quite nicely if we would be staying in GP or using MADlib ecosystem.

I'm really not trying to be difficult and if this change is too complex to implement, I will understand.

Once again, we are larger team that isn't using single approach in all cases, and at the end having "ready to use" dataset in hdfs would save us tons of effort.

@adam8157 mentioned that these limits are coming from PostgreSQL. which is limited by how data are stored, which is totally understandable, but should these limits be applied to external table too ? Supported external file formats don't care about how wide they are.

**Comment by adam8157** [comment]
@jsanko9 It's not like that, the `MaxTupleAttributeNumber` is limited by how data are transferred too, from a node to another. The codes don't guarantee a minimal tuple would not be transformed into a heap tuple either, which is the same structure as it stored.

Ref: https://github.com/postgres/postgres/blob/19ae53c92d5f5bdfb971d560a562e84c5f65c8b0/src/include/access/htup_details.h#L24

**Comment by jsanko9** [comment]
@adam8157 I see now. Thank you very much for explanation.
