### ISSUE TITLE
Wrong logging time in GPCC

### ISSUE THREAD

**Issue by wu623747113** [greenplum-db/gpdb#8525]
GP  version:    greenplum-db-5.21.2
GPCC  version:    greenplum-cc-web-4.7.0
Log times differ by 12 hours

**Comment by gaos1** [comment]
@funcode the issue is already fixed?

FYI, GPCC is not open sourced. so please feedback via support ticket.

**Comment by funcode** [comment]
@gaos1 Probably it is the same issue with https://github.com/greenplum-db/gpdb/issues/3574. But the fix was rolled back as far as I know.
