### ISSUE TITLE
support max_wal_size or min_wal_size in gpinitsystem

### ISSUE THREAD

**Issue by pengzhout** [greenplum-db/gpdb#8527]
checkpoint_segments has been replaced by max_wal_size and min_wal_size, GPDB used to allow users to specify checkpoint_segments in gpinitsystem, do we need to support max_wal_size or min_wal_size in gpinitsystem too?

**Comment by ashwinstar** [comment]
Given these are not strictly required parameters to be set during init, seems fine to not provide option. Like many other config options these can be configured post-init. Closing the feature request.
