### ISSUE TITLE
SKIP LOCKED does not working

### ISSUE THREAD

**Issue by BaiShaoqi** [greenplum-db/gpdb#8540]
### Greenplum version or build
master 6b79a578f04a1332cde96136ac0fd3541ed838c3

### Expected behavior
Second session
Not block, and gives result
```
SELECT * FROM aa WHERE a=1 FOR UPDATE SKIP LOCKED;
 a
---
(0 rows)
```

### Actual behavior
Second session
Blocked unexpectedly
```
SELECT * FROM aa WHERE a=1 FOR UPDATE SKIP LOCKED;
```

### Step to reproduce the behavior
First session
```
CREATE TABLE aa(a int);
INSERT INTO aa(a) SELECT a FROM generate_series(1, 100) a;
BEGIN;
SELECT a FROM aa WHERE a=1 FOR SHARE;
```
Second session
```
SELECT * FROM aa WHERE a=1 FOR UPDATE SKIP LOCKED;
```

**Comment by kainwen** [comment]
I believe if we enable GDD, this should work under planner.
