### ISSUE TITLE
COPY failure session held open, when it should have closed. 

### ISSUE THREAD

**Issue by mark-a-s** [greenplum-db/gpdb#8546]
apologies if this is rushed, but hopefully it's enough to reproduce the issue. 

### Greenplum version or build
6.0beta7
### OS version and uname -a
CentOS Linux release 7.6.1810 (Core) 
Linux server-dev-sloan-host-3orpzp.novalocal 3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

### Expected behavior
COPY or \COPY should stop as soon as an error is encountered if SEGMENT REJECT LIMIT isn't used. 

### Actual behavior
I've got a table 
create table web (jdoc jsonb); 
to load it for testing
bunzip2  -c web.bz2 | psql -h 192.168.16.236 -d marks_test -c "\COPY web FROM STDIN" 

I get an error in the master log about one of the records from the file being bad , however the psql session is held open and bunzip2 | psql never gets the error until you ctrl-c it. (unsure if you get the error at the end of the file being bunzip2'd it's large) . I think this breaks with previous behavior of greenplum that it doesn't immeditly cancel the copy 

### Step to reproduce the behavior

1. create table web (jdoc jsonb)

create a file with a lot of json (gigabytes) (each json doc as a single line) that has lots before and after a record that has json lint vaild escape for json that isn't valid for psql COPY escape .
e.g.

(pretty json)

{
	"attributes": {
		"seg.alert_enrolled_ind": "n",
		"seg.cfm_frd_ind": "n",
		"seg.cl_amt": "500",
		"seg.cpc_cd": "core",
		"seg.customer_tenure": "946",
		"seg.cyc_pdue_bkt_num": "0",
		"seg.daily_acct_bal": "-11",
		"seg.days_since_last_stmt": "9",
		"seg.days_until_pmt_due": "19"
	},
	"elements": [{
			"attributes": {
				"channel": "web"
			},
			"epochtime": 1396751037000,
			"originUuid": "c858674e-5caa-11e4-a891-3a717d64d23e",
			"sessionSource": "",
			"stateName": "web.entry"
		},
		{
			"attributes": {
				"channel": "web",
				"web.chat": "no chat evt",
				"web.evt_desc": "no evt",
				"web.lob_nm": "undefined",
				"web.non_pgvw_path_txt": ":",
				"web.page_actvy_ind": "page view",
				"web.page_nm": ":",
				"web.page_unifrm_rsrc_loc_txt": "https://secure.testdemo360.com/myaccount/banking/accountdetailcardtransactiondetail# trader bob\\'s #           &txncode=dwpos&pagetoken=9ntl2g3jdz4apjcbblt0jbbbsy6r44xn",
				"web.pgvw_seq_num": "000000010",
				"web.srch_rslts_cnt": "0",
				"web.srch_term_txt": "no search"
			},
			"epochtime": 1396751037000,
			"originUuid": "c858674e-5caa-11e4-a891-3a717d64d23e",
			"sessionSource": "",
			"stateName": "web.:"
		}
	],
	"key": "55ccc7e84bc1501b28a64bfd4111374b_29590365069976029224611687204376723662_4c6012dea886e513842204aa1b1fafe355ccc7e84bc1501b28a64bfd4111374b44",
	"layer": "web",
	"uuid": "43017f3d-beaa-11e9-9555-3e8958988269"
}

so this plus a few other million records you want to generate after it, and you should see that it won't close the connection as one would expect when copy'ing it in.

**Comment by sunnn** [comment]
@mark-a-s  can you try merging all the files into one big file and load into gp with \copy as we are doing that today in production and didn't see any failure s

**Comment by mark-a-s** [comment]
unsure what you mean by try merging all the files into one big file. 

it already is one big file, web.bz2. 

e.g. 
`bunzip2 -c web.bz2 | psql -h 192.168.16.236 -d marks_test -c "\COPY web FROM STDIN"`

**Comment by sunnn** [comment]
Ok then instead of bunzip could directly keep the file and see @mark-a-s

**Comment by ashwinstar** [comment]
I tried some cases with error data in file and COPY the same on latest master and 6X_STABLE. Seeing it to work fine, hence closing this issue. Please try latest 6X_STABLE.
