### ISSUE TITLE
Running `make check` fails with `psql: not found`

### ISSUE THREAD

**Issue by bradfordboyle** [greenplum-db/gpdb#8558]
### Greenplum version or build

6X_STABLE (commit: 0471e60ca37c8245ab96e00a0f5008539b6774af)

### OS version and uname -a

Ubuntu 18.04

### autoconf options used ( config.status --config )

```sh
$ config.status --config
'--disable-orca' '--disable-gpfdist' '--disable-gpcloud'
```

### Installation information ( pg_config )

N/A

### Expected behavior

`make check` passes

### Actual behavior

`make check` fails because it cannot find `psql`

### Step to reproduce the behavior

1. Launch a vanilla Ubuntu 18.04 environment (e.g., with Docker)

```sh
cd ~/workspace/gpdb
git checkout 6X_STABLE
docker run -it --rm -v $PWD:/tmp/build/gpdb -w /tmp/build/gpdb ubuntu:18.04 bash
```

2. Install dependencies

```sh
apt-get update

apt-get install -y --no-install-recommends \
    bison \
    build-essential \
    flex \
    libbz2-dev \
    libcurl4-openssl-dev \
    libreadline-dev \
    libzstd-dev \
    zlib1g-dev
```

3. Build and test

```sh
./configure --disable-orca --disable-gpfdist --disable-gpcloud
make -j
make check
```

Here is the output of `make check`

```
make -C  query_info_hook_test
make[2]: Entering directory '/tmp/build/gpdb/src/test/regress/query_info_hook_test'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/tmp/build/gpdb/src/test/regress/query_info_hook_test'
../../../src/test/regress/pg_regress --inputdir=. --temp-install=./tmp_check --top-builddir=../../..    --dlpath=. --init-file=./init_file  --schedule=./parallel_schedule   
sh: 1: psql: not found
...
sh: 1: psql: not found
============== creating temporary installation        ==============

pg_regress: installation failed
Examine /tmp/build/gpdb/src/test/regress/log/install.log for the reason.
Command was: "make" -C "../../.." DESTDIR="/tmp/build/gpdb/src/test/regress/./tmp_check/install" install > "/tmp/build/gpdb/src/test/regress/log/install.log" 2>&1
GNUmakefile:193: recipe for target 'check' failed
make[1]: *** [check] Error 2
make[1]: Leaving directory '/tmp/build/gpdb/src/test/regress'
GNUmakefile:135: recipe for target 'check' failed
make: *** [check] Error 2
```

**Comment by jimmyyih** [comment]
Are you looking for the unit tests (`make unittest-check`)?  Otherwise, you haven't run `make install` to set up your binary installation (to have psql in your $PATH) and a cluster hasn't been initialized (for psql to connect to).

**Comment by bradfordboyle** [comment]
What is the difference between `check` and `installcheck`?

**Comment by danielgustafsson** [comment]
> On 4 Sep 2019, at 22:36, Bradford Boyle <notifications@github.com> wrote:
> 
> What is the difference between check and installcheck?

“check" will bring up a temporary cluster, from a temporary installation of the
code, on non-conflicting ports and run tests against that.  It will work if
there is a cluster already running happily, as well as if not even the binaries
have been installed anywhere.

“installcheck” requires a running cluster on the standard ports with binaries
in PATH, and will run the tests against that cluster.

That being said, this is how it works in upstream.  “make check” doesn’t work
in Greenplum, not because it cant but because noone has written the code.

**Comment by bradfordboyle** [comment]
If I use upstream Postgres 9.4, I can run `make check` without installing first:

```
curl https://ftp.postgresql.org/pub/source/v9.4.24/postgresql-9.4.24.tar.bz2 | tar -xjf -
cd postgresql-9.4.24
./configure
make
make check
```

This suggest that there is an issue in GPDB's build system. I don't think this is a high-priority issue but it is something that we should look into understanding and try to fix.

**Comment by asimrp** [comment]
I agree @bradfordb-vmware, `make check` should work in Greenplum and we can use this issue to track it.  Interestingly, not all tests need complete demo-like cluster, just a single PostgreSQL instance and another instance as its mirror may suffice for some TAP tests.

**Comment by vkhashkovsky** [comment]
There is some little fixes: https://github.com/greenplum-db/gpdb/pull/10722
https://github.com/greenplum-db/gpdb/pull/10721
Review needed

**Comment by adam8157** [comment]
> If I use upstream Postgres 9.4, I can run `make check` without installing first:
> 
> ```
> curl https://ftp.postgresql.org/pub/source/v9.4.24/postgresql-9.4.24.tar.bz2 | tar -xjf -
> cd postgresql-9.4.24
> ./configure
> make
> make check
> ```
> 
> This suggest that there is an issue in GPDB's build system. I don't think this is a high-priority issue but it is something that we should look into understanding and try to fix.

Postgres has a temporary install before check.

```
check: temp-install
...
temp-install:
    ...
    $(MAKE) -C '$(top_builddir)' DESTDIR='$(abs_top_builddir)'/tmp_install install >'$(abs_top_builddir)'/tmp_install/log/install.log 2>&1
```

**Comment by adam8157** [comment]
Fixed by a modified version of https://github.com/greenplum-db/gpdb/pull/10722, closing.
