### ISSUE TITLE
gp6.0.0 gpinitsystem double "-S "

### ISSUE THREAD

**Issue by boazhh** [greenplum-db/gpdb#8579]
gpinitsystem --help
    -S, configure spread mirroring [default group]
    -S, standby_datadir [optional]
    so  $ gpinitsystem -c gpinitsystem_config -h hostfile_gpinitsystem -S not work

**Comment by danielgustafsson** [comment]
Thanks for the report! This was changed in commit 6fa3bce8e2498f8d330f1dabbe808db952db04 which turned the existing use of `-S` into `--mirror-mode`, please try that instead and see if it works. I've fixed this in commit a398b43724e in master, and it will be backported to Greenplum 6 as well.
