### ISSUE TITLE
Batch insert not work

### ISSUE THREAD

**Issue by degeorg** [greenplum-db/gpdb#8585]
### Greenplum version or build

> Greenplum Database 6.0.0 build commit:a2ff2fc318c327d702e66ab58ae4aff34c42296c

> DataDirect JDBC driver 5.1.4

### OS version and uname -a

> Linux baremetal 3.10.0-957.27.2.el7.x86_64 SMP Mon Jul 29 17:46:05 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

### Installation information ( pg_config )
1 Physical host. 1 master + 4 primary segment instances.
### Expected behavior
Working batch inserts
### Actual behavior
Batch inserts executed as single insert.
### Step to reproduce the behavior
```sql
create table test (val BIGINT) with (appendoptimized=true, orientation=column, compresstype=zstd, compresslevel=1) distributed by (val);
```

> openjdk version "1.8.0_222"

```java
Connection connection = DriverManager.getConnection(url, props);
connection.setAutoCommit(false);
String sql = "INSERT INTO test VALUES (?)";
PreparedStatement statement = connection.prepareStatement(sql);
int batchSize = 1000; 
Random random = new Random();
for (int i = 0; i < batchSize; i++) {
    long ts = random.nextLong();
    statement.setLong(1, ts);
    statement.addBatch();
}
statement.executeBatch();
connection.commit();
```
Wireshark show that for each new row driver create bind and execute postgres protocol instructions. Then server response with bind completion and command completion (Tag: INSERT 0 1) for each row.
If i use native postgres driver (42.2.5 version) it send only one bind and execute instructions with all values per executeBatch.

**Comment by Eulerizeit** [comment]
@ivannovick @kmacoskey FYI

**Comment by kainwen** [comment]
It seems tthat here are some difference between Datadirect jdbc driver and pg's driver. 

I have found another difference:  setBatchSize API seems only work under pg's driver, datadirect's driver will ignore this parameter and always send `max_row` as 0 when `exec_execute_message`

**Comment by kainwen** [comment]
And I think this issue should be opened for GPDB repo.

**Comment by asimrp** [comment]
If the batching of statements doesn't happen as expected in DataDirect JDBC driver but does happen in PostgreSQL JDBC driver, this doesn't seem like a Greenplum problem.  Should we close this issue then?

**Comment by degeorg** [comment]
With native postgres driver i get 3000-5000 rows per sec with batch size from 10000 to 100000. If this is expected result - ok, close issue. I also can't setup native driver for using binary format instead of text on select queries and this seriously impact performance. Max - 500000 rows per sec and with DataDirect driver i can get 1,8 - 2,5 mln rows per sec - this is big difference.
I assumed that normal performance with my setup must be 30000-50000 inserted rows per sec (with batches).

**Comment by kainwen** [comment]
> this is bi

Thanks for your reply. @degeorg 

Can you please open another issue on the performance problem. I will close this first.
