### ISSUE TITLE
 gpinitsystem standby master options don't have effect unless STANDBY_HOSTNAME is specified in cluster configuration file

### ISSUE THREAD

**Issue by ghost** [greenplum-db/gpdb#8593]
GP version: Greenplum 6.0.0 build commit:a2ff2fc318c327d702e66ab58ae4aff34c42296c
OS: Centos 7 minimal Linux 3.10.0-957.27.2.el7.x86_64 #1 SMP Mon Jul 29 17:46:05 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

When cluster is initialized with following command, cluster is initialized without standby master ( [INFO]:-Standby Master = Not Configured)

> gpinitsystem -c gpconfigs/gpinitsystem_config -h gpconfigs/hostfile_gpinitsystem -S -s smdw -P 5432 --standby_datadir=/dbdata/master

when following line is added in gpinitsystem_config, then cluster is initialized properly with standby master ([INFO]:-Standby Master = smdw)

> STANDBY_HOSTNAME=smdw

**Comment by dpandhi-git** [comment]
with CM team, cannot reproduce in 7x & 6x latest version
