### ISSUE TITLE
gpstart error: Catalog Versions are incompatible

### ISSUE THREAD

**Issue by luowencai** [greenplum-db/gpdb#8598]
greenplum-db-6.0.0-beta.7 upgrade to greenplum-db-6.0.0
already source /usr/local/greenplum-db-6.0.0/greenplum_path.sh
error:
20190910:11:27:05:060242 gpstart:server1:gpadmin-[ERROR]:-gpstart error: Catalog Versions are incompatible

**Comment by paul-guo-** [comment]
This is expected.

Refer https://gpdb.docs.pivotal.io/6-0/relnotes/gpdb-600-release-notes.html

```
Greenplum 6 does not support direct upgrades from Greenplum 4 or Greenplum 5 releases, or from earlier Greenplum 6 Beta releases. Perform a new install to use Greenplum 6.0.0.
```
