### ISSUE TITLE
Unable to run testing GP6 instance in docker

### ISSUE THREAD

**Issue by jsanko9** [greenplum-db/gpdb#8639]
### Greenplum version or build
pivotaldata/gpdb-dev:centos7
### OS version and uname -a
pivotaldata/gpdb-dev:centos7
### autoconf options used ( config.status --config )
default
### Expected behavior
To start up Greenplum
### Actual behavior
Error:
[FATAL]:-Failed to complete obtain psql count Master gp_segment_configuration  Script Exiting!

### Step to reproduce the behavior

Using this page as reference [link](https://github.com/greenplum-db/gpdb/tree/master/src/tools/docker).

git clone https://github.com/greenplum-db/gpdb.git greenplum

docker run -w /home/build/gpdb -v {local path to current folder}/greenplum/:/home/build/
gpdb:cached -it pivotaldata/gpdb-dev:ubuntu18 /bin/bash

./configure --enable-debug --with-perl --with-python --with-libxml --disable-orca --prefix=/usr/local/gpdb

make -j4

make install

sudo chown -R gpadmin:gpadmin /usr/local/gpdb

```
#Fix from https://github.com/greenplum-db/gpdb/issues/5797 issue using "eth0"
source /usr/local/gpdb/greenplum_path.sh
vi $GPHOME/bin/lib/gphostcachelookup.py
```

su gpadmin

source /usr/local/gpdb/greenplum_path.sh

make create-demo-cluster

**Comment by lavjain** [comment]
Just verified that the demo cluster is working:
```
docker run -w /home/gpadmin/workspace/gpdb -v ~/workspace/gpdb:/home/gpadmin/workspace/gpdb -it pivotaldata/gpdb-dev:centos7 /bin/bash
# run as root
/usr/sbin/sshd
mkdir -p /usr/local/gpdb
chown gpadmin:gpadmin /usr/local/gpdb
./configure --disable-orca --with-perl --with-python --with-libxml --prefix=/usr/local/gpdb --disable-gpcloud CFLAGS=-I/usr/local/include LDFLAGS=-L/usr/local/lib
make -j8
make install
su - gpadmin
# run as gpadmin
source /usr/local/gpdb/greenplum_path.sh
cd workspace/gpdb
make create-demo-cluster
.
.
.
========================================
gpinitsystem returned: 0
========================================

======================================================================
                           OPTIMIZER STATE
----------------------------------------------------------------------
  Optimizer state .. :  off
======================================================================

                                                                                                     version
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 PostgreSQL 9.6beta4 (Greenplum Database 7.0.0-alpha.0+dev.6782.gd62f227 build dev) on x86_64-unknown-linux-gnu, compiled by gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5), 64-bit compiled on Apr 24 2020 17:30:09
(1 row)

 optimizer
-----------
 off
(1 row)

            gp_opt_version
---------------------------------------
 Server has been compiled without ORCA
(1 row)

======================================================================
```

**Comment by lavjain** [comment]
* Verified that greenplum `6X_STABLE` branch also works
* Verified that greenplum build and create-demo-cluster using `pivotaldata/gpdb-dev:centos7`
