### ISSUE TITLE
Fix for motion hazard between subplan and outer rel in a join was incomplete

### ISSUE THREAD

**Issue by hlinnaka** [greenplum-db/gpdb#8677]
https://github.com/greenplum-db/gpdb/pull/7492 fixed a deadlock, if a join qual contains a SubPlan with a Motion. It fixed the deadlock by forcing any SubPlans in the join qual to be fully fetched, before reading the first tuple from the outer relation. To force the SubPlans to be fetched, it constructed a fake all-NULLs outer tuple, and evaluated the join qual with that. However, that method is not reliable. Consider this query:
```
select count(*) from t_inner right join t_outer on t_inner.c2=t_outer.c2
   and (t_inner.c1 is null or not exists (select 0 from t_subplan where t_subplan.c2=t_outer.c1));
```
This is the same query that the PR added to the regression suite in 'deadlock2.sql', but with the extra "t_inner.c1 is null or ..." clause. Because of that extra clause, evaluating the join qual with an all-NULLs tuple doesn't cause the subplan to be evaluated, because the "t_inner.c1 is null" condition is true and the qual evaluates to true without evaluating the subplan. So the query deadlocks.

**Comment by hlinnaka** [comment]
@pivotal-ning-yu, I was looking into this, because I noticed that the ShouldPrefetchJoinQual() is the only place where we use the estate->currentSliceIdInPlan field. I'd like to remove that field, because it seems pretty useless (prototype at https://github.com/hlinnaka/gpdb/tree/remove-unused-slice-id-tracking). I think ShouldPrefetchJoinQual() would work just as well (or poorly, given this bug :-) ) if it didn't check estate->currentSliceIdInPlan, it would just sometimes prefetch quals that it didn't necessarily need to.

**Comment by pivotal-ning-yu** [comment]
Nice catch, we'll work on this.  @gaos1

**Comment by pivotal-ning-yu** [comment]
To be honest, I can't recall why `ShouldPrefetchJoinQual() was implemented that way, that didn't do the real check.  So feel free to remove the `currentSliceIdInPlan` checking in that function, I'll check if we could add the real check later.

**Comment by kainwen** [comment]
Fix by https://github.com/greenplum-db/gpdb/commit/82dd4168c707956349082e40364976e5ce7e2136

Will consider backporting.

But for ORCA, I think we do not handle it correct.
