### ISSUE TITLE
Building on Ubuntu bionic: gpopt/translate/CMappingVarColId.o: undefined reference to symbol '_ZTIN11xercesc_3_117SAXParseExceptionE'

### ISSUE THREAD

**Issue by df7cb** [greenplum-db/gpdb#8693]
Having compiled and installed gp-xerces and gporca to /usr/local, building gpdb with orca fails:

### Greenplum version or build
master and 6X_STABLE as of 2019-09-23

### OS version and uname -a
Ubuntu bionic (18.04)

### autoconf options used ( config.status --config )
`./configure --with-perl --with-python --with-libxml --with-gssapi --prefix=/usr/local/gpdb`

### Actual behavior
```
make[3]: Leaving directory '/home/.../gpdb/gpdb/src/backend/gpopt'
g++ -Wall -Wmissing-prototypes -Wpointer-arith -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv
-fexcess-precision=standard -fno-aggressive-loop-optimizations -Wno-unused-but-set-variable -Wno-address -Wno-format-truncation -O3
-std=gnu99   -Werror=uninitialized -Werror=implicit-function-declaration -L../../src/port -L../../src/common   -Wl,--as-needed
-Wl,-rpath,'/usr/local/gpdb/lib',--enable-new-dtags  -Wl,-E access/common/heaptuple.o access/common/indextuple.o access/common/printtup.o
access/common/reloptions.o access/common/scankey.o access/common/tupconvert.o access/common/tupdesc.o access/common/bufmask.o
access/common/memtuple.o access/common/reloptions_gp.o access/gin/ginutil.o access/gin/gininsert.o access/gin/ginxlog.o ...
... gpopt/relcache/CMDProviderRelcache.o gpopt/utils/COptTasks.o gpopt/utils/CConstExprEvaluatorProxy.o gpopt/utils/funcs.o
gpopt/CGPOptimizer.o gpopt/gpdbwrappers.o ../../src/port/libpgport_srv.a ../../src/common/libpgcommon_srv.a -lgpopt -lnaucrates -lgpdbcost
-lgpos -lxerces-c -lbz2 -lxml2 -lrt -lgssapi_krb5 -lzstd -lz -lrt -lcrypt -ldl -lm -lcurl -lpthread -o postgres
/usr/bin/ld: gpopt/translate/CMappingVarColId.o: undefined reference to symbol '_ZTIN11xercesc_3_117SAXParseExceptionE'
//usr/local/lib/libxerces-c-3.1.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```

Switching from master to the 6X branch didn't change the error. Any idea what I did wrong?

**Comment by pivotal-ning-yu** [comment]
We should use the libxerces-c package from the system repo instead of the patched one.  So goto your local build dir of libxerces-c, run `make uninstall`, then `sudo apt install libxerces-c-dev`, then reconfigure & rebuild orca.

**Comment by bradfordboyle** [comment]
For the [open-source release of Greenplum Database](https://github.com/greenplum-db/gpdb/releases/tag/6.0.0), we do build & vendor gp-xerces on Ubuntu 18.04 [compile_gpdb_oss.bash](https://github.com/greenplum-db/greenplum-database-release/blob/917259ff2303262768dde1ff87482e94593589cc/concourse/scripts/compile_gpdb_oss.bash#L25-L32) which makes some assumptions about the set of packages available in the Docker CI image.

Note that `libxerces-c3` on Ubuntu 18.04 is 3.2.0 while `gp-xerces` is based on 3.1.2; gporca will not compile against 3.2.0 without patches. You can find a patch [here](https://github.com/greenplum-db/greenplum-database-release/blob/b45fa96080da50fdfd3b34d863003afcfe4c1ef8/packaging/gporca/debian/patches/fix-cxx-standard.patch-cxx).

**Comment by pivotal-ning-yu** [comment]
That's weird, I could compile orca against xerces 3.2 on my ubuntu 19.10 devel:

```sh
$ ldd ~/opt/orca/lib/libgpopt.so.3.72.0 | grep libxerces
        libxerces-c-3.2.so => /usr/lib/x86_64-linux-gnu/libxerces-c-3.2.so (0x00007f0c56b91000)

$ cat /etc/issue.net
Ubuntu Eoan Ermine (development branch)
```

**Comment by bradfordboyle** [comment]
Using the following `Dockerfile` to create a vanilla Ubuntu 18.04 build environment, I am able to

- build and install xerces-c 3.1.2 from source
- build and install GPORCA v3.72.0 from source
- build and install GPDB (master @ 0a12d83acaa55da531405251f7ef6194dafeb59f)

It is buried near the end of the Dockerfile, but this is running the same `./configure` invocation.

```dockerfile
FROM ubuntu:18.04

RUN apt-get -q=2 update && \
    apt-get -q=2 install \
        bison \
        build-essential \
        cmake \
        curl \
        flex \
        libapr1-dev \
        libbz2-dev \
        libcurl4-openssl-dev \
        libevent-dev \
        libkrb5-dev \
        libperl-dev \
        libreadline-dev \
        libssl-dev \
        libxml2-dev \
        libzstd-dev \
        python-dev \
        zlib1g-dev

WORKDIR /usr/local/src

RUN curl -LO http://archive.apache.org/dist/xerces/c/3/sources/xerces-c-3.1.2.tar.gz && \
    curl -LO https://github.com/greenplum-db/gporca/archive/v3.72.0.tar.gz && \
    tar -xzf xerces-c-3.1.2.tar.gz && \
    tar -xzf v3.72.0.tar.gz && \
    mkdir xerces_build gporca_build && \
    cd xerces_build && \
    ../xerces-c-3.1.2/configure --prefix=/usr/local && \
    make -j && \
    make install && \
    cd ../gporca_build && \
    cmake -D CMAKE_INSTALL_PREFIX=/usr/local ../gporca-3.72.0 && \
    make -j && \
    make install

COPY . /usr/local/src/gpdb

RUN cd gpdb && \
    ./configure \
        --with-perl \
        --with-python \
        --with-libxml \
        --with-gssapi \
        --prefix=/usr/local/gpdb && \
    make -j && \
    make install && \
    /usr/local/gpdb/bin/psql --version
```

If I build gp-xerces (from https://github.com/greenplum-db/gp-xerces), I am also able to compile GPDB successfully.

Can you confirm:

- gpdb commit SHA for master
- gpdb commit SHA for 6X_STABLE
- gporca version/commit SHA
- gp-xerces commit SHA
- gcc/g++ version

**Comment by d** [comment]
Hi Christoph (@df7cb )

> Switching from master to the 6X branch didn't change the error. Any idea what I did wrong?

I am thrilled that you're interested in Greenplum Database! I took a 3 second glance, and my uneducated guess is:

1. You compiled ORCA linking against xerces-c 3.1 (most likely gp-xerces, which is pretty much identical to Apache Xerces-C++ 3.1.1)
1. Somehow when configuring `gpdb`, you're test script is linking against xerces-c 3.2

So my questions for you are:

1. Can you confirm whether you have `libxerces-c-dev` package installed from apt?
1. If yes, then `-lxerces-c` is ambiguous: it really depends on the search order of the linker. To get to the bottom of that, you can tweak the final linking command to:

    ```
        g++ -Wl,--verbose -Wall -Wmissing-prototypes -Wpointer-arith -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fno-aggressive-loop-optimizations -Wno-unused-but-set-variable -Wno-address -Wno-format-truncation -O3 -std=gnu99   -Werror=uninitialized -Werror=implicit-function-declaration -L../../src/port -L../../src/common   -Wl,--as-needed -Wl,-rpath,'/usr/local/gpdb/lib',--enable-new-dtags  -Wl,-E access/common/heaptuple.o access/common/indextuple.o access/common/printtup.o access/common/reloptions.o access/common/scankey.o access/common/tupconvert.o access/common/tupdesc.o access/common/bufmask.o access/common/memtuple.o access/common/reloptions_gp.o access/gin/ginutil.o access/gin/gininsert.o access/gin/ginxlog.o ...  ... gpopt/relcache/CMDProviderRelcache.o gpopt/utils/COptTasks.o gpopt/utils/CConstExprEvaluatorProxy.o gpopt/utils/funcs.o gpopt/CGPOptimizer.o gpopt/gpdbwrappers.o ../../src/port/libpgport_srv.a ../../src/common/libpgcommon_srv.a -lgpopt -lnaucrates -lgpdbcost -lgpos -lxerces-c -lbz2 -lxml2 -lrt -lgssapi_krb5 -lzstd -lz -lrt -lcrypt -ldl -lm -lcurl -lpthread -o postgres
    ```
   which should hopefully tell us the exact search order for `-lxerces-c` when linking.

Cheers,
Jesse

**Comment by df7cb** [comment]
Unfortunately, I don't have access to that machine at the moment. I can check once the customer is getting back to us on this issue. If you think it's likely the reason that the system libxerces package is getting in the way, feel free to close this. Thanks!

**Comment by d** [comment]
> Unfortunately, I don't have access to that machine at the moment. I can check once the customer is getting back to us on this issue. If you think it's likely the reason that the system libxerces package is getting in the way, feel free to close this. Thanks!

Hopefully you can check it soon. After all, I can only guess, and you're the only one with the actual access to verify this.

**Comment by d** [comment]
> I can check once the customer is getting back to us on this issue

Wait a second, are you suggesting that you don't have a repeatable way of building Greenplum Database, and you're helping a customer compile her or his own Greenplum? That's nuts.

**Comment by df7cb** [comment]
I'd be using the Debian packages if there were any :)

**Comment by pivotal-ning-yu** [comment]
On Fri, Sep 27, 2019 at 6:29 PM Christoph Berg <notifications@github.com>
wrote:

> I'd be using the Debian packages if there were any :)
>
I guess https://launchpad.net/~greenplum/+archive/ubuntu/db is the official
PPA, but I'm not sure.

**Comment by df7cb** [comment]
I'll report back if the problem persists.
