### ISSUE TITLE
select always report fatal the database system is in recovery mode

### ISSUE THREAD

**Issue by githubylzhao** [greenplum-db/gpdb#8698]
### Greenplum version or build
5.8.0
### OS version and uname -a
Linux A01-R06-I30-53-7T3BT92.JCLOUD.COM 3.10.0-327.36.5.el7.x86_64

### Installation information ( pg_config )
gp_interconnect_type=udpifc
gp_connections_per_thread = 0
gp_segment_connect_timeout = 600s
gp_backup_directIO = off             
gp_backup_directIO_read_chunk_mb = 20
checkpoint_segments=8
max_connections=500
gp_vmem_protect_limit=8192
maintenance_work_mem=1GB
shared_buffers=1GB
effective_cache_size=1GB
work_mem=1GB
log_statement='ddl'
log_min_messages='fatal'
gp_resqueue_memory_policy = 'eager_free'
optimizer_analyze_root_partition = on
gp_autostats_mode=on_no_stats
gp_autostats_on_change_threshold=2147483647
log_autostats=off

### Step to reproduce the behavior
seg-1,slice1,dx20950057,,sx1,"LOG","00000","memory: Vmem,        -1, -1, 0, 1048576, 1048576, 0, 1048576
seg-1,slice1,dx20950057,,sx1,"LOG","00000","memory: Peak,        -2, -2, 0, 1179000, 1179000, 0, 1179000
seg-1,slice1,dx20950057,,sx1,"LOG","00000","memory: Root,        1, 1, 0, 0, 0, 0, 0
seg-1,slice1,dx20950057,,sx1,"LOG","00000","memory: Shared       Header, 2, 1, 0, 10400, 25354880, 25346400, 8480
seg-1,slice1,dx20950057,,sx1,"LOG","00000","memory: Rollov       er, 3, 1, 0, 1767328, 1140064, 0, 1140064
seg-1,slice1,dx20950057,,sx1,"LOG","00000","memory: MemAcc       , 4, 1, 0, 896, 896, 0, 896
seg-1,,dx20950285,,sx1,"LOG","00000","context: 1,        104104, 3672, 104104, 0, Timezones
seg-1,,dx20950285,,sx1,"LOG","00000","context: 1,        57344, 37544, 74792, 17448, Postmaster
seg-1,,dx20950285,,sx1,"LOG","00000","context: 1,        8192, 7352, 8192, 0, MemoryAccountMemoryContext
con5782786,cmd441,seg-1,,dx20950285,,sx1,       "LOG","00000","context: 1, 8192, 8056, 8192, 0, ErrorContext
"FATAL","57P03","the database        system is in recovery mode",,,,,,,0,,"postmaster.c",2939,

**Comment by asimrp** [comment]
@githubylzhao what is the SQL query that fails?  We need more details, may be there are additional messages before the ones you've posted in that master log file?  A database that was executing queries goes into recovery mode only in the event of a crash and a message with level PANIC is logged when this happens.  Do you see one or more PANIC messages in the log file?

Can you change `log_min_messages` GUC to `error` at least.  I see that it is currently set at `fatal`.

**Comment by d** [comment]
How did you compile Greenplum? We're not going to make changes to 5.8.0. Please try your query on the latest version of 5.x and report back
