### ISSUE TITLE
Is the greenplum 6.0 kernel version based on postgresssql 9.x

### ISSUE THREAD

**Issue by Bruce2jiang** [greenplum-db/gpdb#8726]
Is the greenplum 6.0 kernel version based on postgresssql 9.x

**Comment by kainwen** [comment]
> Is the greenplum 6.0 kernel version based on postgresssql 9.x

Yes. It is based on pg9.4.

I think such a question is not an issue. So close it.

Recommend to search on the Internet or ask op gpdb user mailing list.
