### ISSUE TITLE
gpinitsystem fails to set password for user names containing special characters

### ISSUE THREAD

**Issue by nickchu0804** [greenplum-db/gpdb#8749]
### Greenplum version or build
6X_STABLE
### OS version and uname -a
MacOS 10.14.3
Darwin US-143342MP.local 18.2.0 Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64 x86_64
### Expected behavior
No errors
### Actual behavior
From gpinitsystem log:

20191001:11:32:03:008353 gpinitsystem:US-143342MP:bruce.lee-[INFO]:-Start Function SET_GP_USER_PW
ERROR:  syntax error at or near "."
LINE 1: alter user bruce.lee password 'gparray';
### Step to reproduce the behavior
gpinitsystem with system USERNAME contains special characters like "bruce.lee"

**Comment by bharath1028** [comment]
Fixed in Master/6X/5X:
Master PR: https://github.com/greenplum-db/gpdb/pull/9705
6X Backport: https://github.com/greenplum-db/gpdb/pull/9745
5X Backport: https://github.com/greenplum-db/gpdb/pull/9751
