### ISSUE TITLE
Is there any way to install gpdb 6.0 via PPA?

### ISSUE THREAD

**Issue by tjlee** [greenplum-db/gpdb#8754]
There is only `greenplum-db | 6.0.0-ga-1` available on https://launchpad.net/~greenplum/+archive/ubuntu/db and I can't install it via `apt install -y greenplum-db-oss`

**Comment by Eulerizeit** [comment]
This question is probably more appropriate for gpdb-users@greenplum.org. 

I think there are options but I'm not sure how complete they are yet.
