### ISSUE TITLE
master and standby port in gp_segment_configuration not updated after config change&reboot

### ISSUE THREAD

**Issue by saaarenadataio** [greenplum-db/gpdb#8755]
### Greenplum version or build
 PostgreSQL 8.3.23 (Greenplum Database 5.21.2 build 5.21.2_arenadata6-409.el7) on x86_64-pc-linux-gnu, compiled by GCC gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36), 64-bit compiled on Aug 19 2019 12:31:28

### OS version and uname -a
CentOS Linux release 7.5.1804 (Core)
Linux gpm1 3.10.0-862.11.6.el7.x86_64 #1 SMP Tue Aug 14 21:49:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

### Installation information ( pg_config )
[pg_config.txt](https://github.com/greenplum-db/gpdb/files/3682018/pg_config.txt)

### Expected behavior
After port changed in postgresql.conf and system restarted - the same new port should appear in gp_segment_configuration

### Actual behavior
gp_segment_configuration contains old port value (and => Standby master can't start)

### Step to reproduce the behavior
1) Stop cluster (e.g. gpstop -aM fast)
2) Open postgresql.conf on Master and Standby, find  CONNECTIONS AND AUTHENTICATION section and set new port value, e.g. 5433
3) Start database (e.g. gpstart -a)

**Comment by gfphoenix78** [comment]
The port in gp_segment_configuration takes precedence over the port in postgresql.conf. `port` and `listen_addresses` are not allowed to change via gpconfig.
Users should not edit postgresql.conf manually. As far as I know, Greenplum doesn't support to change the port. If you really want to do that, you could follow the steps:
1. Stop the cluster
2. Update the port values in gp_segment_configuration in single mode: `postgres --single -D <master_data_directory>`
3. Change the port value in postgresql.conf to the same as that in gp_segment_configuration
4. Start the cluster.

Be careful in step 2.

**Comment by gaos1** [comment]
i think you also need to re-init standby. given the complexity and risk, I prefer to close this as not support feature for now.
