### ISSUE TITLE
[UDP interconnect]Does sender has actual handling when receiving a disordered ACK?

### ISSUE THREAD

**Issue by dreamedcheng** [greenplum-db/gpdb#8782]
### Greenplum version or build

Greenplum Database 6.0.0-beta.1+6cf975c5 build dev

I executed an insert select statement, but failed due to udp interconnect network timeout. The detailed error message is:

_interconnect encountered a network error, please check your network  (seg3 slice1 11.194.xxx.xxx:3021 pid=18812)
Failed to send packet (seq 2572) to 11.194.xx.xxx:38538 (pid 35662 cid 17) after 3592 retries in 3600 seconds._ 

I know this is a very old issue (seems remained unresolved on newest stable GP version...). My question here is : I checked the corresponding code and found that when a packet is reached out of order on receiver, the receiver will reply a disordered ACK. However, the sender seems do nothing in this case.  See function _handleAckForDisorderPkt_. Does anyone know something about it? Thanks in advance.

```
static bool
handleAckForDisorderPkt(ChunkTransportState *transportStates,
						ChunkTransportStateEntry *pEntry,
						MotionConn *conn,
						icpkthdr *pkt)
{
	ICBufferLink *link = NULL;
	ICBuffer   *buf = NULL;
	ICBufferLink *next = NULL;
	uint64		now = getCurrentTime();
	uint32	   *curLostPktSeq = 0;
	int			lostPktCnt = 0;
	static uint32 times = 0;
	static uint32 lastSeq = 0;
	bool		shouldSendBuffers = false;

	if (pkt->extraSeq != lastSeq)
	{
		lastSeq = pkt->extraSeq;
		times = 0;
		return false;
	}
	else
	{
		times++;
		if (times != 2)
			return false;
	}
......
}
```

**Comment by gaos1** [comment]
please send questions or discussion to gpdb-dev@greenplum.org. Thanks.
