### ISSUE TITLE
Unnecessary sort nodes in plan when involving DQA and grouping sets.

### ISSUE THREAD

**Issue by guofengrichard** [greenplum-db/gpdb#8797]
### Greenplum version or build
6X_STABLE

### Step to reproduce the behavior
```
create table a (i int, j int);

# explain (costs off) select i, j, count(distinct j) from a GROUP BY grouping sets((i), (j));
                            QUERY PLAN
------------------------------------------------------------------
 Append
   ->  GroupAggregate
         Group Key: share0_ref1.j, share0_ref1.i
         ->  Sort
               Sort Key: share0_ref1.j, share0_ref1.i
               ->  Gather Motion 3:1  (slice1; segments: 3)
                     Merge Key: share0_ref1.j, share0_ref1.i
                     ->  Sort
                           Sort Key: share0_ref1.j, share0_ref1.i
                           ->  Shared Scan (share slice:id 1:0)
                                 ->  Materialize
                                       ->  Seq Scan on a
   ->  GroupAggregate
         Group Key: share0_ref2.i, share0_ref2.j
         ->  Sort
               Sort Key: share0_ref2.i, share0_ref2.j
               ->  Gather Motion 3:1  (slice2; segments: 3)
                     Merge Key: share0_ref2.i, share0_ref2.j
                     ->  Sort
                           Sort Key: share0_ref2.i, share0_ref2.j
                           ->  Shared Scan (share slice:id 2:0)
 Optimizer: Postgres query optimizer
(22 rows)
```

Note that the sort nodes above the Gather Motion is unnecessary.

**Comment by guofengrichard** [comment]
The culprit is in `generate_list_subplans()`:
```
    for(group_no = 0; group_no < num_subplans; ++group_no)
    {
        /* GPDB_93_MERGE_FIXME: Check whether we could just use
         * context->current_pathkeys for the function's caller
         * since the list includes duplicates.
         */
        context->pathkeys = lappend(context->pathkeys,
                                    copyObject(context->current_pathkeys));
    }
```

We cannot just copy the pathkeys because `compare_pathkeys()` assumes the pathkeys are canonical so it performs the check by simple pointer comparison.

**Comment by asimrp** [comment]
And this issue doesn't exist in master because grouping sets support was brought in as part of PostgreSQL 9.5 merge?

**Comment by guofengrichard** [comment]
> And this issue doesn't exist in master because grouping sets support was brought in as part of PostgreSQL 9.5 merge?

Correct. We replaced GPDB's implementation of grouping sets with PostgreSQL's when merging 9.5.

**Comment by ashwinstar** [comment]
@kainwen thoughts if this issue needs to be addressed for 6X_STABLE? Given its not a problem in master branch, I feel can just close the same for now.

**Comment by kainwen** [comment]
> @kainwen thoughts if this issue needs to be addressed for 6X_STABLE? Given its not a problem in master branch, I feel can just close the same for now.

Sure. Will take a quick look at this and reply here.

**Comment by zxuejing** [comment]
master does not have the problem
The plan for master is as follows:
```
postgres=# explain verbose select i, j, count(distinct j) from a GROUP BY grouping sets((i), (j));
                                         QUERY PLAN                                         
--------------------------------------------------------------------------------------------
 GroupAggregate  (cost=2446.06..11819.56 rows=2000 width=16)
   Output: i, j, count(DISTINCT j)
   Group Key: a.i
   Sort Key: a.j
     Group Key: a.j
   ->  Gather Motion 3:1  (slice1; segments: 3)  (cost=2446.06..3665.81 rows=86100 width=8)
         Output: i, j
         Merge Key: i
         ->  Sort  (cost=2446.06..2517.81 rows=28700 width=8)
               Output: i, j
               Sort Key: a.i
               ->  Seq Scan on public.a  (cost=0.00..321.00 rows=28700 width=8)
                     Output: i, j
 Optimizer: Postgres query optimizer
(14 rows)
```

**Comment by zxuejing** [comment]
> for(group_no = 0; group_no < num_subplans; ++group_no)
>     {
>         /* GPDB_93_MERGE_FIXME: Check whether we could just use
>          * context->current_pathkeys for the function's caller
>          * since the list includes duplicates.
>          */
>         context->pathkeys = lappend(context->pathkeys,
>                                     copyObject(context->current_pathkeys));
>     }

yes, guofengrichard is right, here we copy context->current_pathkeys and assign it to context->pathkeys,
then the following codes use == to compare pathkey, the pointer is different so we add sort again. 
```
if (!pathkeys_contained_in(group_pathkeys,
									   pathkeys))
{
	subplan = (Plan *)
		make_sort_from_pathkeys(root, subplan, group_pathkeys,
								-1, false);
	mark_sort_locus(subplan);
}

```
