### ISSUE TITLE
[UDP interconnect] UDP interconnect timeout

### ISSUE THREAD

**Issue by dreamedcheng** [greenplum-db/gpdb#8811]
### Greenplum version or build
Greenplum Database 6.0.0-beta.1+6cf975c5 build dev

I executed a insert select, it threw a error:

interconnect encountered a network error, please check your network (seg3 slice1 11.194.xxx.xxx:3021 pid=18812)
Failed to send packet (seq 2572) to 11.194.xx.xxx:38538 (pid 35662 cid 17) after 3592 retries in 3600 seconds.

### Expected behavior
Execute correctly.

### Step to reproduce the behavior
Insert select produce the error in certain case, which I don't know clearly.

The stack is:
![image](https://user-images.githubusercontent.com/7367189/66633128-b62b6180-ec3c-11e9-8329-ec2cdf7fe9d3.png)
![image](https://user-images.githubusercontent.com/7367189/66633163-c4797d80-ec3c-11e9-823e-429aa56fa62a.png)

As we can see from the above screen shots ,  the unackQueue is empty and receivedAckSeq is equal to sentSeq. However, the capacity is 0 and consumedAck is also 0, this means that sender didn't receive any normal acks (may receive duplicate or disordered acks) with flag UDPIC_FLAGS_CAPACITY. 

Actually, the receiver has received all 4 packets under this case, but due to the parameter capacity wasn't updated correctly, it stunk in SendChunkUDPIFC's loop and finally triggered timeout error.

Correct me if I am wrong, thanks.

I have submitted a PR on this issue, see https://github.com/greenplum-db/gpdb/pull/8810

**Comment by pengzhout** [comment]
@gaos1

**Comment by dreamedcheng** [comment]
The error I encountered may produced by an old residual trx on segment that held a tuple lock, so new trx cannot consume the tuple packets to do insert.
