### ISSUE TITLE
there is no gpperfmon_install

### ISSUE THREAD

**Issue by eason0420** [greenplum-db/gpdb#8819]
### Greenplum version or build
greenplum-db-6.0.1

### OS version and uname -a
centos7

### Step to reproduce the behavior

i install gp with rpm,but there is no gpperfmon_install 

analyzedb   dropdb             gpaddmirrors        gpcheckresgroupimpl  gpfdist        gpload.py      gprecoverseg  gpssh-exkeys   gpsys1         pg_config       pg_isready      pg_rewind    psql
clusterdb   droplang           gpcheckcat          gpconfig             gpinitstandby  gpload.pyc     gpreload      gpssh_modules  initdb         pg_controldata  pg_receivexlog  pg_upgrade   reindexdb
createdb    dropuser           gpcheckcat_modules  gpconfig_modules     gpinitsystem   gplogfilter    gpscp         gpstart        lib            pg_ctl          pg_recvlogical  pg_xlogdump  stream
createlang  ecpg               gpcheckcloud        gpdeletesystem       gpload         gpmovemirrors  gpsd          gpstate        minirepro      pg_dump         pg_resetxlog    postgres     vacuumdb
createuser  gpactivatestandby  gpcheckperf         gpexpand             gpload.bat     gppkg          gpssh         gpstop         pg_basebackup  pg_dumpall      pg_restore      postmaster

**Comment by diarworld** [comment]
OSS version does not include gpperfmon. You need to create your own build with _--enable-gpperfmon_ key: https://github.com/greenplum-db/gpdb#building-gpdb-with-gpperfmon-enabled
