### ISSUE TITLE
reader_waits_for_lock isolation2 test is broken

### ISSUE THREAD

**Issue by hlinnaka** [greenplum-db/gpdb#8830]
I noticed that the test in `src/test/isolation2/reader_waits_for_lock.sql` test is broken. It gets the current session's session_id, and stores it in a table like this:
```
-- save session id
1: CREATE TABLE reader_waits_for_lock_table_sessionid(a, setting) AS SELECT 1, setting::int FROM pg_settings WHERE name = 'gp_session_id' distributed by (a);
```
Later, it uses this session_id from a utility connection like this:
```
-- all processes in the session 1 should be blocked
0U: select check_session_processes_are_blocked((SELECT setting FROM reader_waits_for_lock_table_sessionid));
```
That relies on the assumption that the single row created in the "save session id" step goes to the same segment that the utility connection runs in. But it doesn't. The row uses '1' as the distribution key, which hashes to segment 1, but the utility connection connects to segment 0:
```
isolation2test=# select gp_segment_id, * from reader_waits_for_lock_table_sessionid ;
 gp_segment_id | a | setting 
---------------+---+---------
             1 | 1 |     923
(1 row)

```
The test incorrectly passes, even though the test passed NULL to the helper function.

I tried fixing the test, but when you fix that issue, the test hangs. The helper function checks that all backends belonging to the session block on the lock, but that doesn't seem to be happening. I think that's because only some of the backends need to access the table. The query plan looks like this:
```
isolation2test=# explain SELECT t1.* FROM reader_waits_for_lock_table t1 INNER JOIN reader_waits_for_lock_table t2 ON t1.b = t2.b;
                                              QUERY PLAN                                              
------------------------------------------------------------------------------------------------------
 Gather Motion 3:1  (slice3; segments: 3)  (cost=1.04..2.11 rows=4 width=8)
   ->  Hash Join  (cost=1.04..2.11 rows=2 width=8)
         Hash Cond: (t1.b = t2.b)
         ->  Redistribute Motion 3:3  (slice1; segments: 3)  (cost=0.00..1.03 rows=1 width=8)
               Hash Key: t1.b
               ->  Seq Scan on reader_waits_for_lock_table t1  (cost=0.00..1.01 rows=1 width=8)
         ->  Hash  (cost=1.03..1.03 rows=1 width=4)
               ->  Redistribute Motion 3:3  (slice2; segments: 3)  (cost=0.00..1.03 rows=1 width=4)
                     Hash Key: t2.b
                     ->  Seq Scan on reader_waits_for_lock_table t2  (cost=0.00..1.01 rows=1 width=4)
 Optimizer: Postgres query optimizer
(11 rows)
```
Only slices 1 and 2 need to access the table. Slice 3 also runs on all segments, but it doesn't touch the table, hence it doesn't block.

**Comment by hlinnaka** [comment]
Ideas on how to fix this:

- Get rid of the 'reader_waits_for_lock_table_sessionid' table. instead, `set application_name=...` in the session, and identify the backends belonging to the test session based on pg_stat_activity.application_name. Alternatively, mark the 'reader_waits_for_lock_table_sessionid' table as replicated, or just insert a lot rows with different distribution key values to it, so that at least one row lands on the target segment.

- In the helper function, if there are no backends belonging to the target session, keep retrying. Perhaps check that there is exactly 2 such backends.

**Comment by ashwinstar** [comment]
Interesting, I thought @asimrp's PR https://github.com/greenplum-db/gpdb/pull/8827 was trying to fix this tests flakiness. Seems there is more to it and not just the issue in that PR.

**Comment by hlinnaka** [comment]
Oh, what a coincidence! I was looking at this because the test was failing on the 9.6 merge branch, and while trying to fix it there, I realized that it was broken to begin with.

**Comment by asimrp** [comment]
Yeah, quite a coincidence.  Setting an application name within the session of interest is a good idea.

**Comment by kainwen** [comment]
@asimrp 
Since this PR  https://github.com/greenplum-db/gpdb/pull/8851 has been merged.

Can we close this issue?

**Comment by asimrp** [comment]
Most certainly!
