### ISSUE TITLE
LATERAL JOIN returns error or segfault. 

### ISSUE THREAD

**Issue by mark-a-s** [greenplum-db/gpdb#8860]
### Greenplum version or build
 PostgreSQL 9.4.24 (Greenplum Database 6.0.1 build commit:053a66ae19cd7301ec8c8910ed85ec2c20ad60cc) on x86_64-unknown-linux-gnu, compiled by gcc (GCC) 6.4.0, 64-bit 
compiled on Oct 10 2019 15:27:29
### OS version and uname -a
Linux gpdb-sn.clickfox.net 3.10.0-957.27.2.el7.x86_64 #1 SMP Mon Jul 29 17:46:05 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
### autoconf options used ( config.status --config )
N/A ?
### Expected behavior
LATERAL JOINS should work and not cause a PANIC or segfault
### Actual behavior
INNER JOIN LATERAL, LEFT JOIN LATERAL and LEFT OUTER JOIN LATERAL return either an error 
`ERROR:  unexpected internal error (nodeMotion.c:173)
HINT:  Likely motion node is incorrectly squelched earlier`

OR a segfault
`ERROR:  Error on receive from seg0 slice1 127.0.0.1:6000 pid=19121: server closed the connection unexpectedly
DETAIL:  
	This probably means the server terminated abnormally
	before or while processing the request.`

### Step to reproduce the behavior

the fastest way to reproduce this:
```
create table mylog (myid int, log_date timestamptz ) ;
insert into mylog values (1,now()),(1,now()-'1 hour'::interval) ; 
insert into mylog values (2,now()),(2,now()-'2 hour'::interval) ; 
```

`SELECT ml1.myid, log_date as first_date, ml2.next_date FROM mylog ml1 INNER JOIN LATERAL (SELECT myid, log_date as next_date FROM mylog where myid = ml1.myid and log_date > ml1.log_date ORDER BY log_date ASC LIMIT 1) ml2 on true ; `

(ERROR happens here)
`ERROR:  unexpected internal error (nodeMotion.c:173)
HINT:  Likely motion node is incorrectly squelched earlier`
it seems like with AO or COLUMN orgineted tables it gets a PANIC which looks more like:

Using an AO column oriented, compressed zstd=2 table I get a segfault, this is not the example above but shows the PANIC/Segfault. 

```
2019-10-17 12:28:01.989550 EDT,,,p19137,th0,,,2019-10-17 12:28:01 EDT,0,con2341,cmd141,seg0,slice2,,,,"PANIC","XX000","Unexpected internal error: Segment process received signal SIGSEGV",,,,,,,0,,,,"1    0x7f78b81fa5f0 libpthread.so.0 <symbol not found> + 0xb81fa5f0
2    0x6cfc1e postgres <symbol not found> (execQual.c:2162)
3    0x6d52ae postgres ExecQual (execQual.c:6237)
4    0x6d5de3 postgres ExecScan (discriminator 1)
5    0x6c8488 postgres ExecProcNode (execProcnode.c:1001)
6    0x6f5e60 postgres ExecSort (tuptable.h:159)
7    0x6c8348 postgres ExecProcNode (execProcnode.c:1089)
8    0x6ebaa8 postgres ExecLimit (tuptable.h:159)
9    0x6c82d8 postgres ExecProcNode (execProcnode.c:1117)
10   0x706570 postgres ExecMotion (tuptable.h:159)
11   0x6c82c8 postgres ExecProcNode (execProcnode.c:1121)
12   0x6bf7f9 postgres <symbol not found> (tuptable.h:159)
13   0x6c0523 postgres standard_ExecutorRun (execMain.c:951)
14   0x88e2c7 postgres <symbol not found> (pquery.c:1150)
15   0x890271 postgres PortalRun (pquery.c:997)
16   0x88871e postgres <symbol not found> (postgres.c:1377)
17   0x88d23f postgres PostgresMain (postgres.c:5360)
"
2019-10-17 12:28:01.989682 EDT,,,p7474,th-1144866688,,,,0,,,seg0,,,,,"LOG","00000","server process (PID 19137) was terminated by signal 11: Segmentation fault","Failed process was running: SELECT s1.session_id, s2.next_session_id FROM session s1  INNER JOIN LATERAL (SELECT session_id as next_session_id FROM session s2 where s1.session_pos < s2.session_pos and s1.journey_id = s2.journey_id order by session_pos limit 1)  s2 ON TRUE WHERE journey_id = 'e565c517-95de-417a-af2b-0b6f8e17cd05' ;",,,,,,0,,"postmaster.c",3962,

```

**Comment by paul-guo-** [comment]
Lateral is not officially supported on Greenplum as the document says so far though some lateral query could run but some could not run and even panic as you encountered. If you check the lateral test cases like join.sql in the repo you will see some are commented out since they panic the database.

Closing this issue.

**Comment by mark-a-s** [comment]
any ways we can have the non-supported ones to fail gracefully and not segfault ?

**Comment by kainwen** [comment]
PR https://github.com/greenplum-db/gpdb/pull/9648 is to fix this in 6X.
