### ISSUE TITLE
Cannot execute ALTER EXTENSION UPDATE

### ISSUE THREAD

**Issue by hidva** [greenplum-db/gpdb#8862]
![image](https://user-images.githubusercontent.com/17427025/67065683-d65da200-f1a1-11e9-8223-78ea0b590b6e.png)

There are no special operations for GP in ExecAlterExtensionStmt(). Such as dispatching the modification of `extrelocatable` and `extversion` in the pg_extension tuple to segments, or, set global variable like creating_extension, CurrentExtensionObject in backend process in Gang created in ProcessUtility() so that findDependentObjects() in these backend can return correct results.

**Comment by gaos1** [comment]
as you find out the root cause, would you help to submit a PR?

**Comment by hidva** [comment]
ok

----------



--------------原始邮件--------------
发件人："Simon Gao "<notifications@github.com>;
发送时间：2019年10月18日(星期五) 晚上6:12
收件人："greenplum-db/gpdb" <gpdb@noreply.github.com>;
抄送："盏一 "<w@hidva.com>;"Author "<author@noreply.github.com>;
主题：Re: [greenplum-db/gpdb] Cannot execute ALTER EXTENSION UPDATE (#8862)
-----------------------------------

 
as you find out the root cause, would you help to submit a PR?
