### ISSUE TITLE
Address already in use (bind errno 98)

### ISSUE THREAD

**Issue by constzl** [greenplum-db/gpdb#8883]
### Greenplum version or build
4.3 & 6X_STABLE
### OS version and uname -a
Linux x86_64 GNU/Linux
### Actual behavior
```text
 LOG:  (58M01) Master unable to connect to seg2 xxxx:3176 with options : FATAL:  Interconnect Error: Could not set up tcp listener socket.
DETAIL:  Address already in use (bind errno 98)
```

**Comment by constzl** [comment]
I think this function **setupTCPListeningSocket** should set **SO_REUSEADDR** option with socket before "bind".

![image](https://user-images.githubusercontent.com/32921993/67284157-a565d000-f507-11e9-8426-b53442d52ca6.png)

**Comment by pivotal-ning-yu** [comment]
Is that mean that the port 3176 is already in use?  Can we find out who is it?

**Comment by asimrp** [comment]
Do we have the same problem in `setupUDPListeningSocket()`?

By the way, what exactly is the problem here?  Is it a transient problem, does the error stop occurring after some time?

**Comment by constzl** [comment]
> Do we have the same problem in `setupUDPListeningSocket()`?
> 
> By the way, what exactly is the problem here? Is it a transient problem, does the error stop occurring after some time?

It is a problem with probability.  See the function **StreamServerPort** to get more details.

```
Without the SO_REUSEADDR flag, a new postmaster can't be started
right away after a stop or crash, giving "address already in use"
error on TCP ports.
```

**Comment by constzl** [comment]
> Is that mean that the port 3176 is already in use? Can we find out who is it?

The socket with port 3176  is in TIME_WAIT state.

**Comment by asimrp** [comment]
I see, thank you for the details.  UDP connections won't suffer from this issue,  `setupUDPListeningSocket()` doesn't need any fix.  Am I right?

**Comment by constzl** [comment]
> I see, thank you for the details. UDP connections won't suffer from this issue, `setupUDPListeningSocket()` doesn't need any fix. Am I right?

yeah

**Comment by gfphoenix78** [comment]
> Do we have the same problem in `setupUDPListeningSocket()`?
> 
> By the way, what exactly is the problem here? Is it a transient problem, does the error stop occurring after some time?

Interconnect/UDP could be even worse. All sockets for interconnect/UDP are bound to `*:<port>` and the sockets for interconnect/TCP are bound to a unicast IP address. It means all sockets for interconnect/UDP share the same port space.

@constzl Could you show me the content in gp_segment_configuration?
`select dbid, hostname, address from gp_segment_configuration`
