### ISSUE TITLE
How to get tablespace of mirror segments in GP6?

### ISSUE THREAD

**Issue by magi345** [greenplum-db/gpdb#8903]
In GP6 the tablespace changed a lot from GP5.
In GP5 I'm able to view the locations of **both Primary and Mirror** by querying `SELECT * FROM pg_filespace_entry;`
```
 fsefsoid | fsedbid |             fselocation
----------+---------+--------------------------------------
  1158170 |       1 | /data/gpcc_data/master-newfs/gpseg-1
     3052 |       1 | /data/gpcc_data/master/gpseg-1
     3052 |       2 | /data/gpcc_data/primary/gpseg0
  1158170 |       2 | /storage3/primary/gpseg0
  1158170 |       3 | /storage3/primary/gpseg1
     3052 |       3 | /data/gpcc_data/primary/gpseg1
     3052 |       4 | /data/gpcc_data/primary/gpseg2
  1158170 |       4 | /storage3/primary/gpseg2
  1158170 |       5 | /storage3/primary/gpseg3
     3052 |       5 | /data/gpcc_data/primary/gpseg3
     3052 |       6 | /data/gpcc_data/primary/gpseg4
  1158170 |       6 | /storage3/primary/gpseg4
  1158170 |       7 | /storage3/primary/gpseg5
     3052 |       7 | /data/gpcc_data/primary/gpseg5
  1158170 |       8 | /storage3/primary/gpseg6
     3052 |       8 | /data/gpcc_data/primary/gpseg6
     3052 |       9 | /data/gpcc_data/primary/gpseg7
  1158170 |       9 | /storage3/primary/gpseg7
  1158170 |      10 | /storage3/primary/gpseg8
     3052 |      10 | /data/gpcc_data/primary/gpseg8
  1158170 |      11 | /storage3/mirror/gpseg0
     3052 |      11 | /data/gpcc_data/mirror/gpseg0
  1158170 |      12 | /storage3/mirror/gpseg1
     3052 |      12 | /data/gpcc_data/mirror/gpseg1
  1158170 |      13 | /storage3/mirror/gpseg2
     3052 |      13 | /data/gpcc_data/mirror/gpseg2
     3052 |      14 | /data/gpcc_data/mirror/gpseg3
  1158170 |      14 | /storage3/mirror/gpseg3
     3052 |      15 | /data/gpcc_data/mirror/gpseg4
  1158170 |      15 | /storage3/mirror/gpseg4
     3052 |      16 | /data/gpcc_data/mirror/gpseg5
  1158170 |      16 | /storage3/mirror/gpseg5
     3052 |      17 | /data/gpcc_data/mirror/gpseg6
  1158170 |      17 | /storage3/mirror/gpseg6
     3052 |      18 | /data/gpcc_data/mirror/gpseg7
  1158170 |      18 | /storage3/mirror/gpseg7
  1158170 |      19 | /storage3/mirror/gpseg8
     3052 |      19 | /data/gpcc_data/mirror/gpseg8
  1158170 |      20 | /data/gpcc_data/master-newfs/gpseg-1
     3052 |      20 | /data/gpcc_data/master/gpseg-1
```

But in GP6, according to [this doc](https://gpdb.docs.pivotal.io/6-0/admin_guide/ddl/ddl-tablespace.html), it is possible to view the locations of **only Primary segments** via gp_tablespace_location().
```
 gp_segment_id |        tblspc_loc
---------------+---------------------------
            -1 | /home/gpadmin/tablespace6
             0 | /home/gpadmin/tablespace6
             1 | /home/gpadmin/tablespace6
             2 | /home/gpadmin/tablespace6
             3 | /home/gpadmin/tablespace6
             4 | /home/gpadmin/tablespace6
             5 | /home/gpadmin/tablespace6
             6 | /home/gpadmin/tablespace6
             7 | /home/gpadmin/tablespace6
             8 | /home/gpadmin/tablespace6
```

Question:
Is there any way to view tablespace locations of **both Primary and Mirrors**, like in GP5?

**Comment by soumyadeep2007** [comment]
In GP6 we can no longer have mirror specific tablespace locations. The location value for a tablespace will have to be equal for the same primary-mirror pair.
Consider seg0's primary and mirror to be located on host1 and host2 respectively.
So we can no longer have this:
```
host1: /tmp/seg0/primary
host2: /tmp/seg0/mirror
```
Instead, we can have:
```
host1: /tmp/seg0
host2: /tmp/seg0
```

**Comment by magi345** [comment]
Thanks for the reply.
We are seeking a way for helping the user identify disk usage of GPDB.
It is clear that GP6 doesn't have a direct way to locate data-dir of mirror segments, so we will move on to other ways.
My question is clearly answered, so closing this issue.

**Comment by soumyadeep2007** [comment]
>It is clear that GP6 doesn't have a direct way to locate data-dir of mirror segments, so we will move on to other ways.

I think you meant tablespace dir instead of data-dir?

Anyway, it's not that there is no direct way, mirror's tablespace location = primary's tablespace location = contentId's tablespace location (that you can get from `gp_tablespace_location()`). So all you have to do is return the tablespace location that you get from the `gp_tablespace_location()` call as the mirror's tablespace location directory.

Hope this helps.

**Comment by magi345** [comment]
Thanks, it should works if the user never modified symlinks under `pg_tblspc`.
Also, we have another option to use an external program on each host to drill into `pg_tblspc` to locate those symlinks.

**Comment by soumyadeep2007** [comment]
> Thanks, it should works if the user never modified symlinks under `pg_tblspc`.
> Also, we have another option to use an external program on each host to drill into `pg_tblspc` to locate those symlinks.

True. gp_tablespace_location() would call pg_tablespace_location() which would do a readlink syscall to read the symlink target "pg_tblspc/<tsoid>". So if a user did update the symlink target on the master and any of the primaries, gp_tablespace_location() would suffice. However, since gp_tablespace_location is not executed on the mirrors, if a user changes the symlink target on the mirror, gp_tablespace_location would lie.

**Comment by phan-pivotal** [comment]
> In GP6 we can no longer have mirror specific tablespace locations. The location value for a tablespace will have to be equal for the same primary-mirror pair.
> Consider seg0's primary and mirror to be located on host1 and host2 respectively.
> So we can no longer have this:
> 
> ```
> host1: /tmp/seg0/primary
> host2: /tmp/seg0/mirror
> ```
> 
> Instead, we can have:
> 
> ```
> host1: /tmp/seg0
> host2: /tmp/seg0
> ```

Would you please explain the detailed reason of  "The location value for a tablespace will have to be equal for the same primary-mirror pair"?

**Comment by phan-pivotal** [comment]
Different tablespace location value supporting for the same primary-mirror pair is necessary for performance reason.

Justification:

1.Keep "each RAID group with a primary-mirror pair list have a symmetrical RAID group with the same primary-mirror list", would be idle for generating a symmetrical external storage flush task queue, which result in better SAS disk performance.

2.However this mean that for some contents, corresponding primary and mirror may be located in different path.
For example: the primary of content27 is located in "/data1", while the mirror of content27 has to be located in "/data2".

3. GP V6 still supporting customized mirror topology injection while initializing. And different design for tablespace feature would be a barrier for consistent UE, as well as a potential performance downgrade factor.


[topology .pdf](https://github.com/greenplum-db/gpdb/files/4924002/topology.pdf)
