### ISSUE TITLE
ERROR:  could not find hash function for type 1184 in operator family 2040 (cdbhash.c:438)

### ISSUE THREAD

**Issue by d** [greenplum-db/gpdb#8918]
### Greenplum version or build
Greeplum 6X_STABLE and master (commmit 4e850c90b114d707d83f79acc1e4349b9cf9f68f as of writing)

### Repro
DDL:
```sql
CREATE TABLE foo (a int, b timestamp) DISTRIBUTED BY (a, b);
CREATE TABLE bar (c int, d timestamp) DISTRIBUTED BY (c, d);

INSERT INTO foo SELECT i, timestamp '2016/11/06' + i * interval '1 day' FROM generate_series(1, 12) i;
INSERT INTO foo SELECT i, timestamp '2016/11/09' FROM generate_series(1, 12) i WHERE i <> 3;
INSERT INTO bar SELECT i, timestamp '2016/11/06' + i * interval '1 day' FROM generate_series(1, 12) i;

ANALYZE foo;
ANALYZE bar;

```

Query

```sql
EXPLAIN
SELECT a, b
FROM foo JOIN bar ON a = c AND b = timestamptz '2016/11/09';

```

The expected output should have 12 tuples. On 5X_STABLE we'll get wrong results (fewer than 12 output tuples).

Planner would complain that:

```
psql:/tmp/minimal-repro.sql:4: ERROR:  could not find hash function for type 1184 in operator family 2040 (cdbhash.c:438)
```

### Bonus
This might be a more illuminating example:

```sql
CREATE TEMP TABLE foo (a int, b real) DISTRIBUTED BY (a, b cdbhash_float4_ops);
CREATE TEMP TABLE bar (c int, d real) DISTRIBUTED BY (c, d cdbhash_float4_ops);

INSERT INTO foo SELECT i, i FROM generate_series(1, 12) i;
INSERT INTO foo SELECT i, 3 FROM generate_series(1, 12) i WHERE i <> 3;
INSERT INTO bar SELECT i, i FROM generate_series(1, 12) i;
CREATE TEMP TABLE whatif (e, f) AS SELECT a, b::float8 FROM foo DISTRIBUTED BY (e, f);

ANALYZE foo;
ANALYZE bar;

EXPLAIN
SELECT a, b
FROM foo JOIN bar ON a = c AND b = 3.0;
```

Again, the expected output should have 12 tuples. On master (as of commit 8223f3ab4e18), we error out with:

```
psql:sql.sql:16: ERROR:  could not find hash function for type 701 in operator family 7101 (cdbhash.c:439)

```

Interestingly, if we change the second join predicate to use a column comparison like `b=d` (with a corresponding change of the data type for column `d` to `timestamptz`), planner is able to produce a correct plan.

**Comment by hlinnaka** [comment]
I think there are two issues here at the code level:

1. cdbpathlocus_get_distkey_exprs() doesn't pay attention to the operator family, when it chooses the Expr to represent the distribution key. For example, if you have an equivalence class with two members, A and B, which are both present in the target list but have different datatypes, cdbpathlocus_get_distkey_exprs() should choose the expression that is hashable under the distribution key's hash operator family. Or more precisely, cdbpathlocus_get_distkey_exprs() should never choose an expression that is not hashable under the distkey's hash operator family.

I wonder if there are other queries where that might be a problem. I think we should do some testing, and try to find a case like that.

However, even after fixing that, this query still fails, but with a different error. In this case, none of the expressions in the targetlist are hashable using the distkey's operator family, so we fail to build the motion. The error happens earlier, which is good, but we shouldn't generate a CdbMotionPath that represents an impossible redistribute motion to begin with: 

2. cdbpath_create_motion_path() should not create an impossible motion like that. PR #8996 was a fix in that vein, but not quite right. The correct condition to check is that the constant is hashable under the distribution key's hash operator family.

I opened PR #9039 for a quick prototype to fix both issues. It's not quite ready to commit, though. Firstly, the test case from PR #8996 needs to be copied to it, as well as the other test scenario @d posted in the comments. Secondly, I think we should try to find a test case, where issue 1. would cause a problem, even when there are no constants involved. Thirdly, there's a FIXME in the PR; should fix that, and also find a test case for the scenario it describes.

**Comment by hlinnaka** [comment]
>     1. cdbpathlocus_get_distkey_exprs() doesn't pay attention to the operator family, when it chooses the Expr to represent the distribution key. For example, if you have an equivalence class with two members, A and B, which are both present in the target list but have different datatypes, cdbpathlocus_get_distkey_exprs() should choose the expression that is hashable under the distribution key's hash operator family. Or more precisely, cdbpathlocus_get_distkey_exprs() should never choose an expression that is not hashable under the distkey's hash operator family.
> 
> 
> I wonder if there are other queries where that might be a problem. I think we should do some testing, and try to find a case like that.

Found a test case for that:
```
CREATE TABLE gp_timestamp1 (a int, b timestamp, bb timestamptz) DISTRIBUTED BY (a, b);
CREATE TABLE gp_timestamp2 (c int, d timestamp, dd timestamptz) DISTRIBUTED BY (c, d);
INSERT INTO gp_timestamp1 SELECT i, timestamp '2016/11/06' + i * interval '1 day' FROM generate_series(1, 12) i;
INSERT INTO gp_timestamp1 SELECT i, timestamp '2016/11/09' FROM generate_series(1, 12) i;
INSERT INTO gp_timestamp2 SELECT i, timestamp '2016/11/06' + i * interval '1 day' FROM generate_series(1, 12) i;

SELECT a, b FROM gp_timestamp1 JOIN gp_timestamp2 ON a = c AND b = dd AND b = bb AND b = timestamp '2016/11/09';
```
Without fixing 1., the query fails with "ERROR:  could not find hash function for type 1184 in operator family 2040 (cdbhash.c:439)", even if issue 2. in cdbpath_create_motion_path() is fixed. In this query, gp_timestamp2 can be redistributed using column 'dd', so cdbpath_create_motion_path() is right to create such a Path. But the constant cannot be used as the hash key, even though it is in the same equivalence class as 'dd'.

**Comment by baobao0206** [comment]
We need to ensure that Var on both sides of the equal sign can generate equal hash values if the equal sign is true. So do we need pg_operaror.oprcanhash to be true?

**Comment by hlinnaka** [comment]
On 21/11/2019 07:32, Jinbao Chen wrote:
> We need to ensure that Var on both sides of the equal sign can generate 
> equal hash values if the equal sign is true. So do we need 
> pg_operaror.oprcanhash to be true?

No, we don't care about 'oprcanhash' as such. 'oprcanhash' is a 
denormalized or redundant field, it just means that the operator belongs 
to some hash operator family. We need to perform a more strict check; 
both datatypes need to have a hash function defined in the distribution 
key's hash operator family.

- Heikki

**Comment by hlinnaka** [comment]
Pushed to master, and opened a PR for 6X_STABLE (https://github.com/greenplum-db/gpdb/pull/9177).

I tried to backport it to 5X_STABLE too, but failed. The code is quite different on 5X_STABLE, we didn't use hash operator families for distribution keys there. We should fix this on 5X, too, but it needs some more thinking.

**Comment by hlinnaka** [comment]
Pushed to 6X_STABLE (commit 17c19c3fcd8e718518f287ec4ad76756020b060e).

5X_STABLE still needs a fix, but it requires more work.
