### ISSUE TITLE
gpcheck  utility  not  found in GP6 ,how to check instead of?

### ISSUE THREAD

**Issue by ailuhaosi** [greenplum-db/gpdb#8950]
gpcheck  utility  not  found in GP6 ,how to check instead of?

**Comment by tylarb** [comment]
gpcheck has been deprecated - we recommend you follow the installation guide [here](https://gpdb.docs.pivotal.io/6-9/install_guide/prep_os.html).

Some customers have success using ansible or puppet to validate and set values across a cluster.
