### ISSUE TITLE
[ORCA] Error in query plan for columns of type uuid

### ISSUE THREAD

**Issue by oSkrobuk** [greenplum-db/gpdb#8967]
### Greenplum version or build
PostgreSQL 8.3.23 (Greenplum Database 5.23.1)

### OS version and uname -a
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.1 LTS
Release  :        14.04
Codename:     trusty
Linux ******* 4.4.114-50 #1 SMP Fri Feb 2 10:53:13 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

### Installation information ( pg_config )
BINDIR = /usr/local/gpdb/bin
DOCDIR = /usr/local/gpdb/doc/postgresql
HTMLDIR = /usr/local/gpdb/doc/postgresql
INCLUDEDIR = /usr/local/gpdb/include
PKGINCLUDEDIR = /usr/local/gpdb/include/postgresql
INCLUDEDIR-SERVER = /usr/local/gpdb/include/postgresql/server
LIBDIR = /usr/local/gpdb/lib
PKGLIBDIR = /usr/local/gpdb/lib/postgresql
LOCALEDIR = /usr/local/gpdb/share/locale
MANDIR = /usr/local/gpdb/share/man
SHAREDIR = /usr/local/gpdb/share/postgresql
SYSCONFDIR = /usr/local/gpdb/etc/postgresql
PGXS = /usr/local/gpdb/lib/postgresql/pgxs/src/makefiles/pgxs.mk
CC = gcc
CPPFLAGS = -D_GNU_SOURCE -I/usr/local/gpdb/include
CFLAGS = -O3 -std=gnu99 -Wall -Wmissing-prototypes -Wpointer-arith -Wendif-labels -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fno-aggressive-loop-optimizations -Wno-unused-but-set-variable -Wno-address -I/usr/local/gpdb/include
CFLAGS_SL = -fpic
LDFLAGS = -Wl,--as-needed -Wl,-rpath,'/usr/local/gpdb/lib',--enable-new-dtags -L/usr/local/gpdb/lib
LDFLAGS_SL =
LIBS = -lpgport -lgpopt -lnaucrates -lgpdbcost -lgpos -lxerces-c -lxml2 -lrt -lcrypt -ldl -lm -L/usr/local/gpdb/lib
VERSION = PostgreSQL 8.3.23

### Expected behavior
The number of returned rows in the explain request will be correct

### Actual behavior
The number of rows in the query plan after the join is greatly overestimated

> Gather Motion 64:1  (slice1; segments: 64)  (cost=0.00..29776903.60 rows=400000400000 width=32)
>   ->  Hash Left Join  (cost=0.00..700874.53 rows=6250006250 width=32)
>         Hash Cond: f_t.id = s_t.id
>         ->  Table Scan on f_t  (cost=0.00..431.40 rows=15625 width=16)
>         ->  Hash  (cost=431.40..431.40 rows=15625 width=16)
>               ->  Table Scan on s_t  (cost=0.00..431.40 rows=15625 width=16)
> Optimizer status: PQO version 3.66.0

It works only when the optimizer is turned off.

> Gather Motion 64:1  (slice1; segments: 64)  (cost=23875.00..50250.00 rows=1000000 width=32)
>   ->  Hash Left Join  (cost=23875.00..50250.00 rows=15625 width=32)
>         Hash Cond: f.id = s.id
>         ->  Seq Scan on f_t f  (cost=0.00..11375.00 rows=15625 width=16)
>         ->  Hash  (cost=11375.00..11375.00 rows=15625 width=16)
>               ->  Seq Scan on s_t s  (cost=0.00..11375.00 rows=15625 width=16)
> Settings:  optimizer=off
> Optimizer status: legacy query optimizer

### Step to reproduce the behavior

> CREATE TEMPORARY TABLE f_t
> (
>   id UUID
> );
> CREATE TEMPORARY TABLE s_t
> (
>   id UUID
> );
> 
> INSERT INTO f_t
> SELECT md5(generate_series(1, 1000000)::VARCHAR)::UUID;
> INSERT INTO s_t
> SELECT md5(generate_series(1, 1000000)::VARCHAR)::UUID;
> 
> ANALYZE f_t;
> ANALYZE s_t;
> 
> EXPLAIN SELECT *
> FROM f_t f
>   LEFT JOIN s_t s
>     ON f.id = s.id;
> 
>

**Comment by sambitesh** [comment]
We have pushed fixes to cardinality estimation for `uuid` columns in PQO version 3.69.0.

Can you try this query with the latest version of gpdb 5?

**Comment by oSkrobuk** [comment]
> We have pushed fixes to cardinality estimation for `uuid` columns in PQO version 3.69.0.
> 
> Can you try this query with the latest version of gpdb 5?

Thank. I'll try tomorrow

**Comment by oSkrobuk** [comment]
> We have pushed fixes to cardinality estimation for `uuid` columns in PQO version 3.69.0.
> 
> Can you try this query with the latest version of gpdb 5?

Thank. It worked in ORCA 3.80.0
