### ISSUE TITLE
Incorrect results with a volatile

### ISSUE THREAD

**Issue by gfphoenix78** [greenplum-db/gpdb#8971]
### Greenplum version or build
6X or maybe master

This issue is similar to and inspired by #8590 
-- create test table with integers 1..100
create table integers (i int4);
insert into integers select generate_series(1, 100);

-- This order should be the same as 'order by i'
select * from integers order by random() * 10 + i;
### Expected behavior
the output integers should be ordered
### Actual behavior
out of order

This issue is general, there may be other places which random() is valid to appear.

**Comment by hlinnaka** [comment]
I think this works as designed. `random()` gets called once for each row, and the result is sorted to that order. It's different from #8590, where the volatile function got called multiple times.

**Comment by kainwen** [comment]
> I think this works as designed. `random()` gets called once for each row, and the result is sorted to that order. It's different from #8590, where the volatile function got called multiple times.

Yes. We have some discussion last Friday.

This should be different.

The expr in `order by` have to be in the target  list. However, limit only expected a Natural number.

The type and semantic is different.

**Comment by gfphoenix78** [comment]
Got it.
