### ISSUE TITLE
How do I view the changes in each version of greenplum-db?

### ISSUE THREAD

**Issue by byanjie** [greenplum-db/gpdb#8978]

**Comment by kainwen** [comment]
Please ask such questions in gpdb user mailing list, or you can just search on Google "GPDB change log", you may find some links 

https://gpdb.docs.pivotal.io/6-0/relnotes/gpdb-60-release-notes.html

**Comment by byanjie** [comment]
谢谢！！！

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Zhenghua Lyu <notifications@github.com>
发送时间: Sunday, November 3, 2019 10:41:37 PM
收件人: greenplum-db/gpdb <gpdb@noreply.github.com>
抄送: 包包大人 <byanjie@outlook.com>; Author <author@noreply.github.com>
主题: Re: [greenplum-db/gpdb] How do I view the changes in each version of greenplum-db? (#8978)


Please ask such questions in gpdb user mailing list, or you can just search on Google "GPDB change log", you may find some links

https://gpdb.docs.pivotal.io/6-0/relnotes/gpdb-60-release-notes.html

―
