### ISSUE TITLE
How to set up to enable greenplum-db to start automatically after the centos7 system is powered on?

### ISSUE THREAD

**Issue by byanjie** [greenplum-db/gpdb#8986]

**Comment by kainwen** [comment]
I believe it is linux admin issue. Not a Greenplum issue. So close it.

You can ask in gpdb user mailling list to see if any other guys have some specific exprience.

**Comment by byanjie** [comment]
I received your reply, thank you for your answer.

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Zhenghua Lyu <notifications@github.com>
发送时间: Tuesday, November 5, 2019 3:44:11 PM
收件人: greenplum-db/gpdb <gpdb@noreply.github.com>
抄送: 包包大人 <byanjie@outlook.com>; Author <author@noreply.github.com>
主题: Re: [greenplum-db/gpdb] How to set up to enable greenplum-db to start automatically after the centos7 system is powered on? (#8986)


I believe it is linux admin issue. Not a Greenplum issue. So close it.

You can ask in gpdb user mailling list to see if any other guys have some specific exprience.

―
