### ISSUE TITLE
gpdb 5 does not compile with perl 5.30 and later

### ISSUE THREAD

**Issue by remotefish** [greenplum-db/gpdb#8989]
```bash
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu Focal Fossa (development branch)"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

$ git show
commit 50015fed64d42bde57fb97396bd8e2aab5f2edae (upstream/5X_STABLE)
Author: Jason Vigil <jvigil@pivotal.io>
Date:   Thu Oct 31 11:30:56 2019 -0600

    Empty CDB Segment IP cache on disconnect

    After a disconnect, the same cdbgang will never attempt to re-resolve
    the hostname of a segment. If the segment IP changes, the cdbgang will
    never be able to reconnect (unless a new session is initiated). By
    emptying the segment IP cache, the cdbgang will lookup the new IP and be
    able to reconnect to the segment.

    Co-authored-by: Jason Vigil <jvigil@pivotal.io>
    Co-authored-by: Goutam Tadi <gtadi@pivotal.io>
    Co-authored-by: Karen Huddleston <khuddleston@pivotal.io>

$ perl -v
This is perl 5, version 30, subversion 0 (v5.30.0) built for x86_64-linux-gnu-thread-multi
(with 46 registered patches, see perl -V for more detail)

$ make
"/usr/bin/perl" ./parse.pl . < ../../../../src/backend/parser/gram.y > preproc.y
Assigning non-zero to $[ is no longer possible at ./parse.pl line 21.
make[4]: *** [Makefile:64: preproc.y] Error 255
make[4]: *** Deleting file 'preproc.y'
make[4]: Leaving directory '/home/u/src/gpdb.git/src/interfaces/ecpg/preproc'
```

According to [perl doc]:

> ### Assigning non-zero to $[ is fatal
> 
> This variable (and the corresponding array_base feature and arybase module) allowed changing the base for array and string indexing operations.
> 
> Setting this to a non-zero value has been deprecated since Perl 5.12 and throws a fatal error as of Perl 5.30.

Perl 5.30 is provided on ubuntu 20.04, that means gpdb 5 can't compile on ubuntu 20.04 .

[perl doc]: https://perldoc.pl/perldeprecation#Assigning-non-zero-to-$%5B-is-fatal

**Comment by pivotal-ning-yu** [comment]
A workaround is to use a previous version of perl:

```bash
$ sudo apt install libperl5.26

$ perl5.26-x86_64-linux-gnu -v
This is perl 5, version 26, subversion 1 (v5.26.1) built for x86_64-linux-gnu-thread-multi
(with 63 registered patches, see perl -V for more detail)

$ make PERL=perl5.26-x86_64-linux-gnu
```

**Comment by pivotal-ning-yu** [comment]
I searched a bit on the history of `parse.pl`, in postgres a `parse2.pl` was introduced in v9.1 with commit https://github.com/postgres/postgres/commit/32fce70564999a90d48a27c4279a8908e90f3ece, later `parse2.pl` replaced `parse.pl` in v9.2 with commit https://github.com/postgres/postgres/commit/030a2831a8df7829d606a873e28330ea2310fd64, so there is not a small patch that can be backported to replace the use of `$[`.  If we don't want to upgrade to `parse2.pl` in gpdb 5 then we need to replace `$[` with a modern equivalent.

**Comment by pivotal-ning-yu** [comment]
Updates to my previous workaround, besides `make PERL=perl5.26-x86_64-linux-gnu` we could also set it during `configure`:

```sh
$ PERL=perl5.26-x86_64-linux-gnu ./configure
$ make
```

**Comment by asimrp** [comment]
Thank you @pivotal-ning-yu for sharing the details, I am also facing the same problem.

Is `ecpg` used at all in 5X? If not, can we simply remove it from the code?

**Comment by pivotal-ning-yu** [comment]
> Thank you @pivotal-ning-yu for sharing the details, I am also facing the same problem.
> 
> Is `ecpg` used at all in 5X? If not, can we simply remove it from the code?

Good question, I don't even know what is ecpg, LOL.  With a bit of googling, I found it's very interesting, sth. like the PowerBuilder, allow SQL commands to be embedded into C programs.  I'm not sure if it is used by the built-in utilities and extensions, however if some users are using it, then removing it from 5X will cause problems.  In fact retiring any feature from a stable release would be a problem from my POV.  Consider that 5X is still not EOL, and we have a workaround, we'd better keep it.  What do you think?

However I think another option is to add a build time detection and only enable ecpg when an old perl is available, this must could save a developer several seconds of life.  I'm just not sure whether this kind of change is suitable for 5X.

**Comment by weinan003** [comment]
another walkaround, we can use [perlbrew](https://perlbrew.pl/), to quickly switch perl by version

**Comment by kainwen** [comment]
I think the above method is good workaround. So close this pr.
