### ISSUE TITLE
Mirrors take ~ 10 times longer than primaries to finish replay when loading data into append-optimized tables

### ISSUE THREAD

**Issue by asimrp** [greenplum-db/gpdb#9008]
@kapustor reported this issue on public slack channel: https://greenplum.slack.com/archives/C6TQ7D43E/p1573055686025800

### Greenplum version or build
6X and master

### Installation information
36 primary and 36 mirrors per host, with each host having 36 cores (72 with hyper threading).  4 such hosts, so 289 total segments including master

### Expected behavior
Replay lag is positive, but definitely not 10 times as much as a primary takes to load the same data.

### Actual behavior
With only three concurrent loading sessions, mirror replay takes 10 times longer - load finishes in 30 minutes but the mirror replay takes 5 hours (300 minutes) to complete.

### Step to reproduce the behavior
Create tales and load the staging tables:
```SQL
CREATE TABLE rnd_nocomp9_distrnd_ao_res1 (
rnd_1 int,
gen_1 int,
a_1 char,
b_1 char,
rnd_2 int,
gen_2 int,
a_2 char,
b_2 char
)
WITH (appendonly=true, orientation=column)
DISTRIBUTED BY (rnd_1);
drop table if exists rnd_nocomp9_distrnd_ao_res2;
CREATE TABLE rnd_nocomp9_distrnd_ao_res2 (
rnd_1 int,
gen_1 int,
a_1 char,
b_1 char,
rnd_2 int,
gen_2 int,
a_2 char,
b_2 char
)
WITH (appendonly=true, orientation=column)
DISTRIBUTED BY (rnd_1);
drop table if exists rnd_nocomp9_distrnd_ao_res3;
CREATE TABLE rnd_nocomp9_distrnd_ao_res3 (
rnd_1 int,
gen_1 int,
a_1 char,
b_1 char,
rnd_2 int,
gen_2 int,
a_2 char,
b_2 char
)
WITH (appendonly=true, orientation=column)
DISTRIBUTED BY (rnd_1);
drop table if exists rnd_nocomp9_distrnd_ao1;
CREATE TABLE rnd_nocomp9_distrnd_ao1 (
rnd int,
gen int,
a char,
b char
)
WITH (appendonly=true)
DISTRIBUTED BY (rnd);
drop table if exists rnd_nocomp9_distrnd_ao2;
CREATE TABLE rnd_nocomp9_distrnd_ao2 (
rnd int,
gen int,
a char,
b char
)
WITH (appendonly=true)
DISTRIBUTED BY (rnd);

insert into rnd_nocomp9_distrnd_ao1 select trunc(random()*1000)::int as rnd,
       generate_series as gen, substring(md5(random()::text), 1 ,1) as a,
       case when random() > 0.5 then 'A' else 'B' end as b from generate_series(1,2000000);

insert into rnd_nocomp9_distrnd_ao2 select trunc(random()*1000)::int as rnd,
       generate_series as gen, substring(md5(random()::text), 1 ,1) as a,
       case when random() > 0.5 then 'A' else 'B' end as b from generate_series(1,2000000);
```
Load the data by running three concurrent insert-into-select queries of the form:
```SQL
insert into rnd_nocomp9_distrnd_ao_res1
    select * from rnd_nocomp9_distrnd_ao1 a1 left join
    rnd_nocomp9_distrnd_ao2 a2 on a1.rnd=a2.rnd;
```

Data loading commands:
```SQL
nohup time psql -d adb -c 'insert into rnd_nocomp9_distrnd_ao_res1 select * from rnd_nocomp9_distrnd_ao1 a1 left join rnd_nocomp9_distrnd_ao2 a2 on a1.rnd=a2.rnd;' > /tmp/out_nocomp1.out 2>&1 &
nohup time psql -d adb -c 'insert into rnd_nocomp9_distrnd_ao_res2 select * from rnd_nocomp9_distrnd_ao1 a1 left join rnd_nocomp9_distrnd_ao2 a2 on a1.rnd=a2.rnd;' > /tmp/out_nocomp2.out 2>&1 &
nohup time psql -d adb -c 'insert into rnd_nocomp9_distrnd_ao_res3 select * from rnd_nocomp9_distrnd_ao1 a1 left join rnd_nocomp9_distrnd_ao2 a2 on a1.rnd=a2.rnd;' > /tmp/out_nocomp3.out 2>&1 &
```

**Comment by asimrp** [comment]
The following SQL can be used to monitor replication lag:
```SQL
select gp_segment_id, flush_location - replay_location as repl_lag
    from gp_stat_replication order by 1;
```

**Comment by asimrp** [comment]
On my demo cluster with `fsync=on`, I had to reduce the number of tuples in staging tables from 2 billion to 200,000 so that the insert finishes in reasonable time.  I ran a single insert session and the mirror replay finished in a few seconds after the bulk load (insert-into-select) finished.  I will try again with more concurrency.

In the meanwhile, let's look at the WAL generated by the bulk load.  The bulk load was split into APPENDONLY_INSERT records of length 65589 each.  And for every few APPENDONLY_INSERT records, hundreds of INPLACE update records of length 72 are written for `gp_fastsequence` table.

Open questions:
(1) Should we try to align length of APPENDONLY_INSERT records to a multiple of BLCKSZ, which is 32768?  I don't think this would help in concurrent loading situation but might be worth paying attention.
(2) Can the flood of INPLACE update records slow the replay down? Let's look at numbers.  In my experiment, for 880 APPENDONLY_INSERT records (~57Gb of I/O), I found 23820 INPLACE records.  That amounts to 23820 * 72 = 1,715,040 bytes of I/O.

**Comment by kapustor** [comment]
Hi @asimrp 
Joining 200k X 200k (with this type of data cardinality) will give you result of 40 millions of rows, and the rows are very small. This may be not enough to reproduce the issue, especially in on thread.
Is it possible to run the full test, even if it will run all night? You will get the result in IO charts.

**Comment by asimrp** [comment]
I increased one of the staging table's tuples to 2 billion and kept the other staging table at 200k tuples.  With three concurrent sessions and fsync=on, the loads finished in about 10 minutes and replay a few mins after.  However, I could see kernel_task and Sentinel One propping up every few seconds as over 50% CPU consuming processes.

Next steps: (1) try to reproduce / measure performance on a more isolated environment than my work laptop, such as a VM in cloud.  (2) try different values of blocksize parameter for append-optimized tables.

**Comment by ivannovick** [comment]
@brianlugongyu @gaos1 @asimrp how serious is this issue, do we know yet?

**Comment by asimrp** [comment]
Once we are able to reproduce this problem, more investigation will be possible easily.  It will be helpful if we get access to @kapustor 's environment (Simon has requested this on the slack channel).

**Comment by kapustor** [comment]
@asimrp @ivannovick dont you mind if I post final Slack message here?
"Strace on the mirror replay process confirmed that fsync is the most time consuming operation.  In addition, the replay process also does open, seek and close against the AO file for every AO WAL record replay..  The primary process, on the other hand, only opens and closes the file once during an insert command.  The timing reported in strace output also confirmed that fsync system call took 1000 times more time as compared with open and close.  Our plan is to work on avoiding fsync system call during AO WAL replay.  This can be achieved by leveraging checkpointer’s pendingOps table."

**Comment by asimrp** [comment]
Quick update: @paul-guo- and I are working on removing the need to `fsync` append-optimized data files during normal operation (primary) as well as WAL replay (mirror).  The idea is to leverage checkpointer's `pendingOps` hash table to register a fsync request at the next checkpoint for an append-optimized segment file, similar to how it works for heap.  And then only perform `write()` system call to append new data during normal operation as well as during replay.

**Comment by asimrp** [comment]
Fixed in PR https://github.com/greenplum-db/gpdb/pull/9201 and back ported to 6X_STABLE by PR https://github.com/greenplum-db/gpdb/pull/9237
