### ISSUE TITLE
6.1.0rpm call 'recoverseg -r' also let mirror down

### ISSUE THREAD

**Issue by usa1993** [greenplum-db/gpdb#9025]
### Greenplum version or build
6.1.0
###My problem
I install 6.1.0rpm Greenplum，when i use recoverseg -r to rebalance my cluster，it also show  me 'Incremental recovery failed,plesase use reoverseg -F......'，but is useful on version 5.X. So please let me know if my operation is wrong or what should i do to resolve this problem.
Thanks very much!

**Comment by paul-guo-** [comment]
incremental recovery is supported on gp6 but in some scenarios that can not work so you need to fall back to full recovery. You could check the pg_log on the failed segments to find why incremental recovery does not work.

**Comment by usa1993** [comment]
stdout='could not connect to server: FATAL: no pg_hba.conf entry for host "172.16.3.244", user "gpadmin", database "template1", SSL off Failure, exiting'
