### ISSUE TITLE
"SET TIME ZONE INTERVAL '01:00' HOUR TO MINUTE" report ERROR:  unrecognized node type

### ISSUE THREAD

**Issue by lide-reed** [greenplum-db/gpdb#9044]
### Greenplum version or build
VERSION = 'PostgreSQL 9.4.24 (Greenplum Database 6.0.0 build commit:a2ff2fc318c327d702e66ab58ae4aff34c42296c) on x86_64-unknown-linux-gnu, compiled by gcc (GCC) 6.4.0, 64-bit'
### OS version and uname -a
Linux ng8ec9d38-master-instance-9iuahm0v-2.novalocal 3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
### Expected behavior
Execute command in psql:
\# SET TIME ZONE INTERVAL '01:00' HOUR TO MINUTE;
SET
### Actual behavior
Execute command in psql:
\# SET TIME ZONE INTERVAL '01:00' HOUR TO MINUTE;
ERROR:  unrecognized node type: 910 (guc.c:7443)
### Step to reproduce the behavior
Execute command in psql:
\# SET TIME ZONE INTERVAL '01:00' HOUR TO MINUTE;

**Comment by soumyadeep2007** [comment]
Also broken on master. Not broken on 5x.

**Comment by soumyadeep2007** [comment]
Related:
On 5x and above, `SET timezone..` is not getting properly dispatched to segments (can be easily verified with a utility mode conn to segment -> `SHOW time zone;`).

**Comment by soumyadeep2007** [comment]
@lide-reed Thank you for reporting this! It has been fixed in 6X and master.
