### ISSUE TITLE
gprecoverseg -o ./recv -p sdw3 Error

### ISSUE THREAD

**Issue by star-hou** [greenplum-db/gpdb#9051]
### Greenplum version or build
Version 5.19
###
In my greenplum cluster, the segment (sdw1) is down, so i join in a new segment node.And then i use 
"gprecoverseg -o ./recv -p sdw3" to recover my fail segment node sdw1. But when i open the file "recv",  I see some information like that:
"sdw1:50000:/data1/mirror/gpseg16 sdw3:50000:80000/data1/recover1/gpseg16
sdw1:50001:/data1/mirror/gpseg16 sdw3:50001:80001/data1/recover1/gpseg16
sdw1:60001:/data1/mirror/gpseg16 sdw3:50002:80002/data1/recover1/gpseg16
sdw1:60001:/data1/mirror/gpseg16 sdw3:50003:80003/data1/recover1/gpseg16"
I think the information is wrong,because the port and replication_port is not same as before, what should i do?only modifiy it by myself?
And after do gprecoverseg -i with the recv file, my gpexpand also take a mistake like "gpexpand:gp-m:gpadmin-[ERROR]:-gpexpand failed: Port 50000 is used multiple times on host sdw5"

**Comment by asimrp** [comment]
@usa1993 what do you mean by "join in a new segment node"?  Did you add a brand new segment host with no existing data?  `gpexpand` is the tool used to incorporate such new nodes in the cluster.

**Comment by ashwinstar** [comment]
Using `gprecoverseg` one can move mirror to different host. I think that's essentially @usa1993 wished to perform.

It would be helpful, @usa1993, if you can post what was your `gp_segment_configuration` to understand what's existing configuration and what change you are attempting to make. Please can you explain "port and replication_port is not same as before" little more in detail to make the issue clear?

Also, if you can log separate issue for gpexpand you hinted above if facing same would be good.

**Comment by lij55** [comment]
closing this old issue without recent update.
