### ISSUE TITLE
Improper dispatch of SET TIME ZONE INTERVAL ... flavor.

### ISSUE THREAD

**Issue by soumyadeep2007** [greenplum-db/gpdb#9055]
### Greenplum version or build
4x, 5x, 6x and master. 
Note: For 6x and master, there is a related issue that manifests first (#9044). After fixing that like [here](https://github.com/soumyadeep2007/gpdb/commit/61778ad1e3cd24ba6666896683a274237117e56a), this issue manifests.

### Step to reproduce the behavior
(case A):
```
postgres=# set time zone interval '0 year 0 months 0 days 4 hours 30 minutes 6 seconds' HOUR TO MINUTE;
ERROR:  invalid value for parameter "TimeZone": "0 year 0 months 0 days 4 hours 30 minutes 6 seconds"  (seg2 127.0.0.1:7004 pid=39172)
```
(case B):
```
postgres=# set time zone interval '04:30:06' HOUR TO MINUTE;
ERROR:  time zone "04:30:06" appears to use leap seconds  (seg0 127.0.0.1:7002 pid=40711)
```
(case C): -- this succeeds luckily
```
postgres=# set time zone interval '04:30' HOUR TO MINUTE;
SET
```
### Expected behavior
Both of the cases above expect the time zone to be set to +4:30 (the seconds are to be ignored). 

And there can be many more cases depending on the many variants of the `SET TIME ZONE INTERVAL` syntax.

### RCA:
The issue is that we don't dispatch the SET TIME ZONE syntax properly (notice how the segments report the problem in both repros above). For the examples above, the string dispatched to the segments is missing the `INTERVAL` syntax:
(case A)  
```
(lldb) p buffer.data
(char *) $3 = 0x00007fdba6013848 "SET timezone TO '0 year 0 months 0 days 4 hours 30 minutes 6 seconds'"
```
(case B)
```
(lldb) p buffer.data
(char *) $1 = 0x00007fdb77000048 "SET timezone TO '04:30:06'"
```
(case C) -- this succeeds luckily
```
(lldb) p buffer.data
(char *) $1 = 0x00007fea7761089 "SET timezone TO '04:30'"
```
### Possible fix (working on it):
Special handling for the `timezone` GUC to allow for the special `SET` syntax. We should dispatch `SET timezone TO <value_set_on_QD>`.

**Comment by lij55** [comment]
It looks like this issue is fixed by #9056, #9149 and #9152
