### ISSUE TITLE
gpdb Segment fault with orca v3.82

### ISSUE THREAD

**Issue by templarzq** [greenplum-db/gpdb#9057]
### Greenplum version or build
master branch 

### OS version and uname -a
centos 7

gcc version 9.1.0

### autoconf options used ( config.status --config )
'--with-libraries=-L/greenplum/compile/deps/lib' '--with-includes=-L/greenplum/compile/deps/include' 'CFLAGS= -O3 -march=native' 'CXXFLAGS= -O3 -march=native' '--enable-orca' '--without-perl' '--without-python' '--with-libxml' '--without-gssapi' '--disable-pxf' '--with-zstd' '-with-openssl' '--without-libbz2' 'CC=/tools/cpp/bin/gcc' 'CXX=/tools/cpp/bin/g++'

### Installation information ( pg_config )
CONFIGURE = '--with-libraries=-L/greenplum/compile/deps/lib' '--with-includes=-L/greenplum/compile/deps/include' 'CFLAGS= -O3 -march=native' 'CXXFLAGS= -O3 -march=native' '--enable-orca' '--without-perl' '--without-python' '--with-libxml' '--without-gssapi' '--disable-pxf' '--with-zstd' '-with-openssl' '--without-libbz2' 'CC=/tools/cpp/bin/gcc' 'CXX=/tools/cpp/bin/g++'
CC = /tools/cpp/bin/gcc
CPPFLAGS = -DFRONTEND -D_GNU_SOURCE -I/usr/local/anaconda/include/libxml2
CFLAGS = -Wall -Wmissing-prototypes -Wpointer-arith -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-unused-but-set-variable -Werror=implicit-fallthrough=3 -Wno-format-truncation -Wno-stringop-truncation  -O3 -march=native -std=gnu99  -I/usr/local/anaconda/include -Werror=uninitialized -Werror=implicit-function-declaration
CFLAGS_SL = -fPIC
LDFLAGS = -L../../src/common -L/usr/local/anaconda/lib -Wl,--as-needed -Wl,-rpath,'/usr/local/gpdb/lib',--enable-new-dtags
LDFLAGS_EX =
LDFLAGS_SL =
LIBS = -lpgcommon -lpgport -Wl,--start-group -lgpopt -lnaucrates -Wl,--end-group -Wl,--start-group -lnaucrates -lgpopt -Wl,--end-group -lgpdbcost -lgpos -lxerces-c -lxml2 -lrt -lssl -lcrypto -lzstd -lz -lreadline -ltermcap -lrt -lcrypt -ldl -lm  -L/usr/local/anaconda/lib -lcurl
VERSION = PostgreSQL 9.6beta4

### Expected behavior

select version();

### Actual behavior

2019-11-18 17:08:54.652986 CST,,,p11982,th0,,,2019-11-18 17:08:48 CST,0,con6,cmd1,seg-1,,,,,"PANIC","XX000","Unexpected internal error: Master process received signal SIGSEGV",,,,,,,0,,,,"1    0xc13992 postgres StandardHandlerForSigillSigsegvSigbus_OnMainThread + 0x1b2
2    0x7ffac9178370 libpthread.so.0 <symbol not found> + 0xc9178370
3    0x7ffaadc96058 ??:0
"
2019-11-18 17:08:54.653161 CST,,,p11912,th-892360640,,,,0,,,seg-1,,,,,"LOG","00000","server process (PID 11982) was terminated by signal 11: Segmentation fault","Failed process was running: select version();",,,,,,0,,"postmaster.c",3979,
2019-11-18 17:08:54.653195 CST,,,p11912,th-892360640,,,,0,,,seg-1,,,,,"LOG","00000","terminating any other active server processes",,,,,,,0,,"postmaster.c",3707,

### Step to reproduce the behavior
compile orca v3.82
compile gpdb
gpinisystem
gpstart
psql
 select version();

**Comment by templarzq** [comment]
gporca test:

ctest -j8 --output-on-failure

25% tests passed, 120 tests failed out of 159

Total Test time (real) =   2.99 sec

37/159 Test  #37: gpos_test_CUnittestTest_1 .........................   Passed    0.05 sec
        Start  45: gporca_test_CTypeModifierTest
 38/159 Test  #38: gpos_test_CUnittestTest_2 .........................   Passed    0.05 sec
        Start  46: gporca_test_CIndexScanTest
 39/159 Test  #39: gpos_test_CUnittestTest_3 .........................   Passed    0.04 sec
        Start  47: gporca_test_CBitmapScanTest
 40/159 Test  #40: gporca_test_CSemiJoinTest .........................***Exception: SegFault  0.33 sec

        Start  48: gporca_test_CIndexApplyTest
 41/159 Test  #41: gporca_test_CAntiSemiJoinTest .....................***Exception: SegFault  0.29 sec

        Start  49: gporca_test_CDynamicIndexScanTest
 42/159 Test  #44: gporca_test_CLeftOuterIndexApplyTest ..............***Exception: SegFault  0.29 sec

        Start  50: gporca_test_CIndexScanOnLeafTest
 43/159 Test  #46: gporca_test_CIndexScanTest ........................***Exception: SegFault  0.29 sec

        Start  51: gporca_test_CStatsTest
 44/159 Test  #43: gporca_test_CLikeIDFTest ..........................***Exception: SegFault  0.31 sec

        Start  52: gporca_test_CICGMiscTest
 45/159 Test  #47: gporca_test_CBitmapScanTest .......................***Exception: SegFault  0.30 sec

        Start  53: gporca_test_CArrayCmpTest
 46/159 Test  #45: gporca_test_CTypeModifierTest .....................***Exception: SegFault  0.31 sec

        Start  54: gporca_test_CProjectTest
 47/159 Test  #42: gporca_test_CPredicateTest ........................***Exception: SegFault  0.31 sec

        Start  55: gporca_test_CPartTbl1Test
 48/159 Test  #48: gporca_test_CIndexApplyTest .......................***Exception: SegFault  0.06 sec

        Start  56: gporca_test_CPartTbl2Test
 49/159 Test  #49: gporca_test_CDynamicIndexScanTest .................***Exception: SegFault  0.06 sec

        Start  57: gporca_test_CPartTbl3Test
 50/159 Test  #51: gporca_test_CStatsTest ............................***Exception: SegFault  0.06 sec

        Start  58: gporca_test_CPartTbl4Test
 51/159 Test  #50: gporca_test_CIndexScanOnLeafTest ..................***Exception: SegFault  0.06 sec

        Start  59: gporca_test_CPartTbl5Test
 52/159 Test  #52: gporca_test_CICGMiscTest ..........................***Exception: SegFault  0.06 sec

        Start  60: gporca_test_CPartTbl6Test
 53/159 Test  #53: gporca_test_CArrayCmpTest .........................***Exception: SegFault  0.06 sec

        Start  61: gporca_test_CSetop1Test
 54/159 Test  #54: gporca_test_CProjectTest ..........................***Exception: SegFault  0.06 sec

**Comment by asimrp** [comment]
@templarzq I have seen `select version()` failure like this when Greenplum is run with binaries built from an unclean source repository.  Did you try cleaning up your source repository by running `make clean` or `git clean -xfdq .`?  Note that the `git` command will remove all files that are not version controlled from your source tree.

**Comment by templarzq** [comment]
there's no problem when i compile with gcc 7.1.0。so i suspect gcc 9.1.0 is uncompatible with gporca

**Comment by templarzq** [comment]
@asimrp

**Comment by asimrp** [comment]
We should try compiling gporca with GCC 9.1.0. I don't have time to install the compiler today, someone working actively on gporca knows already - @zellerh / @sambitesh?

**Comment by sambitesh** [comment]
We don't compile ORCA with gcc 9.1.0 today. We plan to do it in future though. Please compile using gcc 7.1.0 for now.

**Comment by d** [comment]
> gporca test:
> 
> ctest -j8 --output-on-failure
> 
> 25% tests passed, 120 tests failed out of 159
> 
> Total Test time (real) = 2.99 sec
> 
> 37/159 Test #37: gpos_test_CUnittestTest_1 ......................... Passed 0.05 sec
> Start 45: gporca_test_CTypeModifierTest
> 38/159 Test #38: gpos_test_CUnittestTest_2 ......................... Passed 0.05 sec
> Start 46: gporca_test_CIndexScanTest
> 39/159 Test #39: gpos_test_CUnittestTest_3 ......................... Passed 0.04 sec
> Start 47: gporca_test_CBitmapScanTest
> 40/159 Test #40: gporca_test_CSemiJoinTest .........................***Exception: SegFault 0.33 sec
> 
> ```
>     Start  48: gporca_test_CIndexApplyTest
> ```
> 
> 41/159 Test #41: gporca_test_CAntiSemiJoinTest .....................***Exception: SegFault 0.29 sec
> 
> ```
>     Start  49: gporca_test_CDynamicIndexScanTest
> ```
> 
> 42/159 Test #44: gporca_test_CLeftOuterIndexApplyTest ..............***Exception: SegFault 0.29 sec
> 
> ```
>     Start  50: gporca_test_CIndexScanOnLeafTest
> ```
> 
> 43/159 Test #46: gporca_test_CIndexScanTest ........................***Exception: SegFault 0.29 sec
> 
> ```
>     Start  51: gporca_test_CStatsTest
> ```
> 
> 44/159 Test #43: gporca_test_CLikeIDFTest ..........................***Exception: SegFault 0.31 sec
> 
> ```
>     Start  52: gporca_test_CICGMiscTest
> ```
> 
> 45/159 Test #47: gporca_test_CBitmapScanTest .......................***Exception: SegFault 0.30 sec
> 
> ```
>     Start  53: gporca_test_CArrayCmpTest
> ```
> 
> 46/159 Test #45: gporca_test_CTypeModifierTest .....................***Exception: SegFault 0.31 sec
> 
> ```
>     Start  54: gporca_test_CProjectTest
> ```
> 
> 47/159 Test #42: gporca_test_CPredicateTest ........................***Exception: SegFault 0.31 sec
> 
> ```
>     Start  55: gporca_test_CPartTbl1Test
> ```
> 
> 48/159 Test #48: gporca_test_CIndexApplyTest .......................***Exception: SegFault 0.06 sec
> 
> ```
>     Start  56: gporca_test_CPartTbl2Test
> ```
> 
> 49/159 Test #49: gporca_test_CDynamicIndexScanTest .................***Exception: SegFault 0.06 sec
> 
> ```
>     Start  57: gporca_test_CPartTbl3Test
> ```
> 
> 50/159 Test #51: gporca_test_CStatsTest ............................***Exception: SegFault 0.06 sec
> 
> ```
>     Start  58: gporca_test_CPartTbl4Test
> ```
> 
> 51/159 Test #50: gporca_test_CIndexScanOnLeafTest ..................***Exception: SegFault 0.06 sec
> 
> ```
>     Start  59: gporca_test_CPartTbl5Test
> ```
> 
> 52/159 Test #52: gporca_test_CICGMiscTest ..........................***Exception: SegFault 0.06 sec
> 
> ```
>     Start  60: gporca_test_CPartTbl6Test
> ```
> 
> 53/159 Test #53: gporca_test_CArrayCmpTest .........................***Exception: SegFault 0.06 sec
> 
> ```
>     Start  61: gporca_test_CSetop1Test
> ```
> 
> 54/159 Test #54: gporca_test_CProjectTest ..........................***Exception: SegFault 0.06 sec

Hi thank you for your interest in Greenplum Database! Are you still experiencing issue running tests for ORCA?

**Comment by adam8157** [comment]
It's been a year without responses, closing. Feel free to reopen it with more info.
