### ISSUE TITLE
gpexpand problem

### ISSUE THREAD

**Issue by student194** [greenplum-db/gpdb#9087]
### Greenplum version or build
5.19

When I execute gpexpeld -d  60:00:00 -D expbase , the program spends more than an hour redistributing a table. In the log of gexpand, I found the record of "Interconnect encountered a network error，please check  your network", but my network is connected. Can you give me some advice? Thank you very much!

**Comment by asimrp** [comment]
@zhangh43 do you have any thoughts on the interconnect error mentioned above?

**Comment by kainwen** [comment]
> ### Greenplum version or build
> 5.19
> 
> When I execute gpexpeld -d 60:00:00 -D expbase , the program spends more than an hour redistributing a table. In the log of gexpand, I found the record of "Interconnect encountered a network error，please check your network", but my network is connected. Can you give me some advice? Thank you very much!

Maybe you can first check the network config.

1. do you use TPC/UDP as interconnect?
2. If UDP, can you check that the UDF network acroos the new machines and old machines are OK.

**Comment by kainwen** [comment]
Long time no response. I feel strongly it is network issue. Close this.

Feel free to re-open if need-ed.
