### ISSUE TITLE
create external table with delimiter off option， return error.

### ISSUE THREAD

**Issue by xudagui** [greenplum-db/gpdb#9111]
### Greenplum version or build
Greenplum Database 6.0.1 & Greenplum Database 6.1.0
### OS version and uname -a
Linux master 4.18.0-80.4.2.el8_0.x86_64 #1 SMP Fri Jun 14 13:20:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
### Expected behavior
`CREATE EXTERNAL TABLE`
### Actual behavior
`ERROR:  COPY delimiter must be a single one-byte character`
### Step to reproduce the behavior
when create external table with delimiter off option, return `ERROR:  COPY delimiter must be a single one-byte character`;

SQL: ```create external table test_delimiter(data text) location('gpfdist://127.0.0.1/test_delimiter.txt') format 'text' (delimiter 'off');```

![image](https://user-images.githubusercontent.com/55196101/69491698-790ced00-0ed3-11ea-9f45-ed056adae83d.png)

LOG:  2019-11-24 06:21:37.013353 UTC,"gpadmin","ysda",p22194,th470934976,"[local]",,2019-11-24 05:15:30 UTC,0,con967,cmd17,seg-1,,dx875517,,sx1,"ERROR","0A000","COPY delimiter must be a single one-byte character",,,,,,"create external table test_delimiter(data text) location('gpfdist://127.0.0.1/test_delimiter.txt') format 'text' (delimiter 'off');",0,,"copy.c",1467,

it seems `/src/backend/commands/copy.c` at line 1464, hiven't consider the external table.

**Comment by adam8157** [comment]
Hi, @xudagui What's the use case, why do you need the delimiter off?

This could easily be fixed, it would be better supported if we know the use case.

**Comment by lij55** [comment]
This option is confirmed to be widly used by a lot of customers, expecially with custom formatter together.

**Comment by xudagui** [comment]
> Hi, @xudagui What's the use case, why do you need the delimiter off?
> 
> This could easily be fixed, it would be better supported if we know the use case.

Sometimes the data is not completely separated by specific delimiters, and the fields are also out of order. Some fields are missing, such as:
2019-11-26 01:10:23 status = zxcvb busyRate = zxcbn streamKey = xxxx
2019-11-26 01:10:24 status = zxcvb streamKey = xxxx

Need to treat it as a whole record, use substring (data from 'regexp') regular expression to intercept, just like:

select
   substring (data from '^ ([^ \ t] +) \ t') as create_time
   substring (data from 'status = ([^ \ t] +) (\ t | $)') as status
   substring (data from 'busyRate = ([^ \ t] +) (\ t | $)') as busyRate
   substring (data from 'speed = ([^ \ t] +) (\ t | $)') as speed
   substring (data from 'proxyId = ([^ \ t] +) (\ t | $)') as proxyId
   substring (data from 'proxyIp = ([^ \ t] +) (\ t | $)') as proxyIp
   substring (data from 'ver = ([^ \ t] +) (\ t | $)') as ver
   substring (data from 'recordTime = ([^ \ t] +) (\ t | $)') as recordTime
   substring (data from 'streamKey = ([^ \ t] +) (\ t | $)') as streamKey
from test_delimiter
