### ISSUE TITLE
"WARNING:  invalid attnum 4 for rangetable entry t (parse_relation.c:2974") when running some icg tests

### ISSUE THREAD

**Issue by paul-guo-** [greenplum-db/gpdb#9126]
### Greenplum version or build

gpdb master (Did not test gpdb6 and below)

with `-DOPTIMIZER_DEBUG` in CFLAGS

### Step to reproduce the behavior

Some icg tests fails with additional, this kind of warning output. Test opr_sanity is an example.

Did not look into the details so not sure if that is an exact bug but that cflag seems to work fine previously in my dev environment (I have been enabling it when debugging some planner issue).

**Comment by hlinnaka** [comment]
I'm not seeing these warnings now, so I guess it's been fixed. Closing.
