### ISSUE TITLE
ERROR:  invalid page in block 

### ISSUE THREAD

**Issue by bloodwolf2020** [greenplum-db/gpdb#9142]
test table struct
![图片](https://user-images.githubusercontent.com/46953147/69896223-b19b4380-1377-11ea-886d-60881983ccf6.png)

when i insert about 20, 000, 000 record in the test table; 

an error occur:
[SQL]select count(1)
from pss_satellite_search

WARNING:  page verification failed, calculated checksum 54504 but expected 5152  (seg4 slice1 192.168.25.12:30000 pid=4256)

[Err] ERROR:  invalid page in block 50453 of relation base/17234/16446  (seg4 slice1 192.168.25.12:30000 pid=4256)

![图片](https://user-images.githubusercontent.com/46953147/69896252-253d5080-1378-11ea-8643-affc0e80f5d9.png)

![图片](https://user-images.githubusercontent.com/46953147/69896246-0dfe6300-1378-11ea-98e7-dd00ba34bff3.png)

how can i process this error?

**Comment by xiong-gang** [comment]
It would be useful if you can upload the DDL and the corrupted data file of
this table.

**Comment by paul-guo-** [comment]
And what gpdb version?

**Comment by bloodwolf2020** [comment]
this problem is occured by disk, when i change the error segment to other server, this error is not occured.
