### ISSUE TITLE
Resource Group should support runaway mechanism too

### ISSUE THREAD

**Issue by zhangh43** [greenplum-db/gpdb#9155]
Resource queue mode support runaway mechanism, which will kill the top memory consuming session when system is in high memory usage. Details as belows.
1. RQ defines memory Redzone threshold e.g. 80% memory limit gpdb(i.e. gp_vmem_protect_limit).
2. During palloc and CHECK_FOR_INTERRUPTS(), it will check whether redzone is reached. If reached, then go through SessionStateArray and find the session whose memory usage is highest and mark that session with error out flag out in SessionStateArray.
3. Then in the same path, each session will check whether it's with error out flag, if yes, quit with elog error.

But Resource Group don't support runaway currently. It will result in all the sessions report OOM when memory are used up. Better to just kill the top consuming one in each group by supporting runaway mechanism.

**Comment by zhangh43** [comment]
Rough idea from @pivotal-ning-yu  and me:
Redzone in resource group is different from resource queue. It cannot just use the overall memory usage of a segment to determine whether it is in Redzone. For example, we have 3 groups: admin(10% memory limit), A(30% memory limit) and B(30% memory limit). And 30% for global shared memory(GSM) region. Support group A is very busy, running 50 concurrent queries(each query's memory usage is just 1%, but total memory usage is 50%); B is not busy, but running just single one memory consuming query(memory usage is 10%). In this case, the total segment memory usage is just 60%, it seems safe. But group A is not safe, it already used up its group local memory and GSM has only 10% memory left. We should treat this case as resource group A Redzone, and kill some sessions belong to group A. But even if query in group B is the most memory consuming one(single query 10%), it should not be killed which is required by the characteristic of memory isolation in resource group.

So one solution is to define resource group's redzone as follows. A resource group is not in Redzone if one of the following condition matches.
1. Resource group slot memory is not in Redzone.
2. Resource group local shared memory is not in Redzone.
3. Resource group's global shared memory is not in Redzone.

If a resource group is in Redzone, the mark one memory consuming session in this group as needed to error out and run the later runaway logic to kill that session.

**Comment by ivannovick** [comment]
+1 for the feature, it will be useful IMO

**Comment by zhangh43** [comment]
Issue fixed in #9245
