### ISSUE TITLE
GPEXPAND: Table regression.public.mvtest_tvvm failed to expand......

### ISSUE THREAD

**Issue by z17033** [greenplum-db/gpdb#9165]
### Greenplum version or build
PostgreSQL 9.6beta4 (Greenplum Database 7.0.0-alpha.0 build dev) on x86_64-unknown-linux-gnu, compiled by gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5), 64-bit compiled on Dec  3 2019 07:56:19

### OS version and uname -a
Linux node1.mpp.com 3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

### Actual behavior
When I run ‘gpexpand -B 4’，then the following error occurs.
```
20191203:07:57:44:005961 gpexpand:node1:gpadmin-[INFO]:-Expanding regression.public.mvtest_tvvm
20191203:07:57:44:005961 gpexpand:node1:gpadmin-[ERROR]:-Table regression.public.mvtest_tvvm failed to expand: error 'ERROR:  "mvtest_tvvm" is not a table
' in 'ALTER  TABLE ONLY public.mvtest_tvvm EXPAND TABLE'

_**note: mvtest_tvvm is a materialized view.**_
```

AND when I query the view named gpexpand.expansion_progress, then following error occurs even if the parameter enable_nestloop set to off.

```
postgres=# show optimizer;
 optimizer 
-----------
 on
(1 row)
postgres=# select * from gpexpand.expansion_progress ;
ERROR:  illegal rescan of motion node: invalid plan (nodeMotion.c:1605)  (entry db 10.121.66.120:5434 pid=1224) (nodeMotion.c:1605)
HINT:  Likely caused by bad NL-join, try setting enable_nestloop to off
```

### Step to reproduce the behavior
Run pg_regress
`./pg_regress --inputdir=. --bindir='/usr/local/seasql/bin/'    --dlpath=. --init-file=./init_file  --load-extension=gp_inject_fault --schedule=./parallel_schedule --schedule=./greenplum_schedule `

Run gpexpand 
`gpexpand -i gpexpand_inputfile_20191203073322`

Run gpexpand -B
`gpexpand -B 4`

**Comment by lij55** [comment]
Hi @z17033 ,

do you still have this issue on GP6 (6.20.0 by now)?

**Comment by lij55** [comment]
closing as missing information and no update for long time.
