### ISSUE TITLE
Error occurred while ending COPY

### ISSUE THREAD

**Issue by geekbosszhang** [greenplum-db/gpdb#9170]
### Greenplum version or build
server-rc-6.1.0+dev.90.gce8c47f-rhel7_x86_64.tar.gz
### OS version and uname -a
centos7
### Actual behavior
2019-12-04 09:25:03.909348 UTC,,,p11015,th0,,,2019-12-04 09:25:02 UTC,0,con9,cmd55,seg0,,,,,"PANIC","XX000","Unexpected internal error: Segment process received signal SIGSEGV",,,,,,,0,,,,"1    0x7f396f5715f0 libpthread.so.0 <symbol not found> + 0x6f5715f0
2    0x63a853 postgres <symbol not found> (copy.c:5520)
3    0x6404f4 postgres <symbol not found> (copy.c:3873)
4    0x644580 postgres DoCopy (copy.c:1131)
5    0x893f45 postgres standard_ProcessUtility (utility.c:636)
6    0x890551 postgres <symbol not found> (palloc.h:158)
7    0x89104e postgres <symbol not found> (pquery.c:1512)
8    0x892767 postgres PortalRun (pquery.c:1022)
9    0x88ac7e postgres <symbol not found> (postgres.c:1377)
10   0x88f8b9 postgres PostgresMain (postgres.c:5361)
"
2019-12-04 09:25:03.909547 UTC,,,p7776,th1929033856,,,,0,,,seg0,,,,,"LOG","00000","server process (PID 11015) was terminated by signal 11: Segmentation fault","Failed process was running:
        TRUNCATE gpmetrics.gpcc_disk_history;
        ALTER TABLE gpmetrics.gpcc_disk_history ADD DEFAULT PARTITION default_partition;
        COPY gpmetrics.gpcc_disk_history FROM '/tmp/build/8c86b158/gopath/src/gpcc/backend/bin/gpccws/tests/generator/tmpldata/totmp/gpcc_disk_history.csv' CSV HEADER;",,,,,,0,,"postmaster.c",3962,

### Step to reproduce the behavior
gpperfmon=# COPY gpmetrics.gpcc_disk_history FROM '/tmp/build/8c86b158/gopath/src/gpcc/backend/bin/gpccws/tests/generator/tmpldata/totmp/gpcc_disk_history.csv' CSV HEADER;
ERROR: MPP detected 3 segment failures, system is reconnected

gpperfmon=# \dS+ gpmetrics.gpcc_disk_history;
Append-Only Columnar Table "gpmetrics.gpcc_disk_history"
Column | Type | Modifiers | Storage | Stats target | Compression Type | Compression Level | Block Size | Description
-----------------+--------------------------------+-------------------------------+----------+--------------+------------------+-------------------+------------+-------------
ctime | timestamp(0) without time zone | not null default now() | plain | | rle_type | 2 | 32768 |
hostname | character varying(64) | not null | extended | | rle_type | 2 | 32768 |
filesystem | text | not null | extended | | rle_type | 2 | 32768 |
total_bytes | bigint | not null | plain | | rle_type | 2 | 32768 |
bytes_used | bigint | not null | plain | | rle_type | 2 | 32768 |
bytes_available | bigint | not null | plain | | rle_type | 2 | 32768 |
data_dirs | text[] | not null default '{}'::text[] | extended | | rle_type | 2 | 32768 |
Checksum: t
Child tables: gpmetrics.gpcc_disk_history_1_prt_1,
gpmetrics.gpcc_disk_history_1_prt_2,
gpmetrics.gpcc_disk_history_1_prt_default_partition
Distributed by: (ctime)
Partition by: (ctime)
Options: appendonly=true, orientation=column, compresstype=rle_type, compresslevel=2

[gpadmin@9507eb6b-72aa-43a7-764c-799f3df49142 totmp]$ head -n 2 /tmp/build/8c86b158/gopath/src/gpcc/backend/bin/gpccws/tests/generator/tmpldata/totmp/gpcc_disk_history.csv
ctime,hostname,filesystem,total_bytes,bytes_used,bytes_available,data_dirs
"2018-09-30 00:41:00","9507eb6b-72aa-43a7-764c-799f3df49142","/","189561409536","53324296190","136237113346","{/tmp/build/8c86b158/gpdb_src/gpAux/gpdemo/datadirs/qddir/demoDataDir-1,/tmp/build/8c86b158/gpdb_src/gpAux/gpdemo/datadirs/dbfast1/demoDataDir0,/tmp/build/8c86b158/gpdb_src/gpAux/gpdemo/datadirs/dbfast_mirror1/demoDataDir0,/tmp/build/8c86b158/gpdb_src/gpAux/gpdemo/datadirs/dbfast3/demoDataDir2,/tmp/build/8c86b158/gpdb_src/gpAux/gpdemo/datadirs/dbfast_mirror3/demoDataDir2,/tmp/build/8c86b158/gpdb_src/gpAux/gpdemo/datadirs/dbfast2/demoDataDir1,/tmp/build/8c86b158/gpdb_src/gpAux/gpdemo/datadirs/dbfast_mirror2/demoDataDir1,/tmp/build/8c86b158/gpdb_src/gpAux/gpdemo/datadirs/standby}"

**Comment by geekbosszhang** [comment]
gpperfmon=# COPY gpmetrics.gpcc_disk_history FROM '/tmp/build/8c86b158/gopath/src/gpcc/backend/bin/gpccws/tests/generator/tmpldata/totmp/gpcc_disk_history.csv' CSV HEADER;
ERROR:  MPP detected 3 segment failures, system is reconnected

gpperfmon=# \dS+ gpmetrics.gpcc_disk_history;
                                                           Append-Only Columnar Table "gpmetrics.gpcc_disk_history"
     Column      |              Type              |           Modifiers           | Storage  | Stats target | Compression Type | Compression Level | Block Size | Description
-----------------+--------------------------------+-------------------------------+----------+--------------+------------------+-------------------+------------+-------------
 ctime           | timestamp(0) without time zone | not null default now()        | plain    |              | rle_type         | 2                 | 32768      |
 hostname        | character varying(64)          | not null                      | extended |              | rle_type         | 2                 | 32768      |
 filesystem      | text                           | not null                      | extended |              | rle_type         | 2                 | 32768      |
 total_bytes     | bigint                         | not null                      | plain    |              | rle_type         | 2                 | 32768      |
 bytes_used      | bigint                         | not null                      | plain    |              | rle_type         | 2                 | 32768      |
 bytes_available | bigint                         | not null                      | plain    |              | rle_type         | 2                 | 32768      |
 data_dirs       | text[]                         | not null default '{}'::text[] | extended |              | rle_type         | 2                 | 32768      |
Checksum: t
Child tables: gpmetrics.gpcc_disk_history_1_prt_1,
              gpmetrics.gpcc_disk_history_1_prt_2,
              gpmetrics.gpcc_disk_history_1_prt_default_partition
Distributed by: (ctime)
Partition by: (ctime)
Options: appendonly=true, orientation=column, compresstype=rle_type, compresslevel=2

[gpadmin@9507eb6b-72aa-43a7-764c-799f3df49142 totmp]$ head -n 2 /tmp/build/8c86b158/gopath/src/gpcc/backend/bin/gpccws/tests/generator/tmpldata/totmp/gpcc_disk_history.csv
ctime,hostname,filesystem,total_bytes,bytes_used,bytes_available,data_dirs
"2018-09-30 00:41:00","9507eb6b-72aa-43a7-764c-799f3df49142","/","189561409536","53324296190","136237113346","{/tmp/build/8c86b158/gpdb_src/gpAux/gpdemo/datadirs/qddir/demoDataDir-1,/tmp/build/8c86b158/gpdb_src/gpAux/gpdemo/datadirs/dbfast1/demoDataDir0,/tmp/build/8c86b158/gpdb_src/gpAux/gpdemo/datadirs/dbfast_mirror1/demoDataDir0,/tmp/build/8c86b158/gpdb_src/gpAux/gpdemo/datadirs/dbfast3/demoDataDir2,/tmp/build/8c86b158/gpdb_src/gpAux/gpdemo/datadirs/dbfast_mirror3/demoDataDir2,/tmp/build/8c86b158/gpdb_src/gpAux/gpdemo/datadirs/dbfast2/demoDataDir1,/tmp/build/8c86b158/gpdb_src/gpAux/gpdemo/datadirs/dbfast_mirror2/demoDataDir1,/tmp/build/8c86b158/gpdb_src/gpAux/gpdemo/datadirs/standby}"

**Comment by magi345** [comment]
```
2 0x63a853 postgres (copy.c:5520)
3 0x6404f4 postgres (copy.c:3873)
```
Seems this issue is related to this recent commit https://github.com/greenplum-db/gpdb/commit/d3cca6d420a7046f73be100e6df9c017a436b287
@hlinnaka

**Comment by ashwinstar** [comment]
I reverted the commit for now, to unblock the release. We can investigate this issue and come back to commit this improvement later.
