### ISSUE TITLE
gpload merge data, always server closed the connection unexpectedly

### ISSUE THREAD

**Issue by deankwok** [greenplum-db/gpdb#9191]
### Greenplum version or build
6.0.1

### OS version and uname -a
centos 7

Linux deankwok.cn 3.10.0-1062.el7.x86_64 #1 SMP Wed Aug 7 18:08:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

### Expected behavior
I just create test table "user_info", create sql as shown below

``` sql
CREATE TABLE "public"."user_info" (
  "name" varchar(255) COLLATE "pg_catalog"."default",
  "id" int4,
  "id1" int4
)
;

alter table user_info set distributed randomly;
```
yml file content:

``` yml
VERSION: 1.0.0.1
DATABASE: dean
USER: gptest
HOST: 192.168.1.51
PORT: 5432
GPLOAD:
   INPUT:
    - SOURCE:
         LOCAL_HOSTNAME:
           - ping 192.168.1.239
         FILE:
           - /home/dkwok/Developer/test_data/gpload/user_info.csv
    - COLUMNS:
         - id:
         - id1:
         - name:
    - FORMAT: csv
    - DELIMITER: '|'
    - QUOTE: '"'
    - HEADER: FALSE
    - ENCODING: UTF8
    - ERROR_LIMIT: 0
   OUTPUT:
    - TABLE: user_info
    - MODE: merge
    - MATCH_COLUMNS:
         - id
    - UPDATE_COLUMNS:
         - id:
         - id1:
         - name
```

data csv content:

```csv
4|1|"alice"
2|2|"kwok"
```

Execute successfully whiche is expected result

### Actual behavior

Actually, occur error. as shown belown

```
[dkwok@deankwok gpload]$ gpload -f user_info.yml 
2019-12-06 10:13:57|INFO|gpload session started 2019-12-06 10:13:57
2019-12-06 10:13:57|INFO|setting schema 'public' for table 'user_info'
2019-12-06 10:13:57|INFO|started gpfdist -p 8000 -P 9000 -f "/home/dkwok/Developer/test_data/gpload/user_info.csv" -t 30
2019-12-06 10:14:25|ERROR|ERROR:  Error on receive from seg15 slice1 192.168.1.54:6003 pid=1094: server closed the connection unexpectedly
DETAIL:  
	This probably means the server terminated abnormally
	before or while processing the request.
 encountered while running INSERT INTO temp_staging_gpload_0f70c85e_17ce_11ea_93eb_000c29544e24 ("name","id","id1") SELECT "name","id","id1" FROM ext_gpload_0f70c85e_17ce_11ea_93eb_000c29544e24
2019-12-06 10:14:28|INFO|rows Inserted          = 0
2019-12-06 10:14:28|INFO|rows Updated           = 0
2019-12-06 10:14:28|INFO|data formatting errors = 0
2019-12-06 10:14:28|INFO|gpload failed
```

### Step to reproduce the behavior

1. create table by my sql script
2. make data by my csv content 
3. gpload -f data.yml by my yaml config

Thank you very much for any idea

**Comment by asimrp** [comment]
@deankwok can you open segment logs and post the error or a stack trace found there? Starting with the following string from the `gpload` output:
```
seg15 slice1 192.168.1.54:6003 pid=1094
```
Locate `seg15` data directory, the logs are found in `<seg15_data_dir>/pg_log/*.csv`.  You can:
1. grep the logs with the PID.  E.g.
```
cd <seg15_data_dir>
grep -il 'p1094,\|PID 1094' pg_log/*
```
2. Open the log file and post relevant details.

**Comment by lij55** [comment]
also the output of gpload with `-V` please. Thanks!

**Comment by deankwok** [comment]
The yml configuration was configured incorrectlly by my self, :(, for LOCAL_HOSTNAME, I typed a needless word 'ping'..., I will closed this issue. thank @asimrp and @lij55 for your reply.
