### ISSUE TITLE
no pre-assigned OID for pg_proc tuple for create function when reusing segdbDesc->segment_database_info->freelist

### ISSUE THREAD

**Issue by flashk1021** [greenplum-db/gpdb#9208]
### Greenplum version or build
6x_stable
### OS version and uname -a
Darwin Kernel Version 18.6.0
### autoconf options used ( config.status --config )
./configure --with-perl --with-python --with-libxml --with-gssapi --prefix=xxx --disable-gpfdist --disable-orca --enable-debug --disable-oss_ext CFLAGS=-O0 --no-create --no-recursion
### Installation information ( pg_config )
1x master + 3x segments
### Expected behavior
create function succeed
### Actual behavior
create function failed with 
ERROR:  no pre-assigned OID for pg_proc tuple "logging_sfunc_nonstrict7" (namespace:16385 keyOid1:0 keyOid2:0) (oid_dispatch.c:652)  (seg0 127.0.0.1:40000 pid=2806) (oid_dispatch.c:652)
### Step to reproduce the behavior
psql -d postgres -p 15432
psql (9.4.24)
Type "help" for help.

postgres=# drop schema singleseg;
DROP SCHEMA
postgres=# create schema singleseg;
CREATE SCHEMA
\q

-- reconnect to master
psql -d postgres -p 15432
psql (9.4.24)
Type "help" for help.

postgres=# set search_path=singleseg, public;
SET
postgres=# reset search_path;
RESET
postgres=# --show search_path;
postgres=# CREATE or replace FUNCTION logging_sfunc_nonstrict7(text, anyelement) RETURNS text AS
postgres-# $$ SELECT COALESCE($1, '') || '*' || quote_nullable($2) $$
postgres-# LANGUAGE SQL IMMUTABLE;
ERROR:  no pre-assigned OID for pg_proc tuple "logging_sfunc_nonstrict7" (namespace:16386 keyOid1:0 keyOid2:0) (oid_dispatch.c:652)  (seg0 127.0.0.1:40000 pid=10059) (oid_dispatch.c:652)

It is the issue of reusing previous segdbDesc->segment_database_info->freelist and it still contains search_path=singleseg,public carried from the first statement set search_path=singleseg, and then it gets reused at reset and create function statement.

**Comment by pengzhout** [comment]
This should be the same problem with https://github.com/greenplum-db/gpdb/issues/685.

**Comment by gfphoenix78** [comment]
Fixed in https://github.com/greenplum-db/gpdb/pull/12441

**Comment by gfphoenix78** [comment]
6X backport PR is https://github.com/greenplum-db/gpdb/pull/12480
