### ISSUE TITLE
psql session crashed when executing postgres_fdw.sql

### ISSUE THREAD

**Issue by aqktjcm** [greenplum-db/gpdb#9209]
### Greenplum version or build
PostgreSQL 9.6beta4 (Greenplum Database 7.0.0-alpha.0 build dev)

### OS version and uname -a
CentOS Linux release 7.5.1804 (Core)

### Expected behavior
execute postgres_fdw.sql and get expected output (gpdb\contrib\postgres_fdw\expected\postgres_fdw.output)

### Actual behavior
psql session crashed with info below:
postgres_fdw.sql:266: server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
postgres_fdw.sql:266: connection to server was lost

### Step to reproduce the behavior
psql -f postgres_fdw.sql
path of file postgres_fdw.sql: gpdb\contrib\postgres_fdw\sql\postgres_fdw.sql

**Comment by hlinnaka** [comment]
Thanks for the report! Opened PR #9222 to fix this.

I wonder why we haven't spotted this earlier, though? Seems that we are not running the `postgres_fdw` regression tests as part of installcheck-world. We should do something about that...
