### ISSUE TITLE
cache lookup failed for relation 225337 (lsyscache.c:3887)

### ISSUE THREAD

**Issue by superstarlpb** [greenplum-db/gpdb#9236]
I'm a greenplum beginner，This is a problem that bothers me 。I use the method of creating a different name table and replacing the table name to synchronize the latest data of the table，However, when I query this table again, I will report an error：ERROR: cache lookup failed for relation 225337 (lsyscache.c:3887)。
There is a solution to this problem when you re-establish a database connection,but,I would like to know how to refresh syscache，or some other way

**Comment by superstarlpb** [comment]
Greenplum's version is 4.3.7.2

**Comment by asimrp** [comment]
@superstarlpb GitHub issues are used only for Greenplum source code that is open to public (version 5.X and above).  Please contact Pivotal support for the version of Greenplum you are using or upgrade to a newer version to discuss things here.

**Comment by superstarlpb** [comment]
> @superstarlpb GitHub issues are used only for Greenplum source code that is open to public (version 5.X and above). Please contact Pivotal support for the version of Greenplum you are using or upgrade to a newer version to discuss things here.

Thank you very much, the version of Green Plum I am currently using is  4.3.7.2。
