### ISSUE TITLE
why we use gp_fastsequence?

### ISSUE THREAD

**Issue by LJoNe** [greenplum-db/gpdb#926]
In order to insert a tuple into an AO table, it seems that the code use gp_fastsequence to pre allocate 100 sequences. Is there any special point here? why do not use pg_aoseg table attribute 'tupcount' to set aoTupleId's rowNum? can anybody help me?

**Comment by ashwinstar** [comment]
Row number needs to be uniquely generated irrespective of committed / aborted inserts, for indexing to work correctly.

Incase insert aborts the tuple count will not be updated or visible in pg_aoseg. So, if tuple-count from pg_aoseg is used to generate row number, same row number as aborted insert will be assigned to next insert. This will break the index working for AO/CO. Row number is stored as TupleId in index and same is used to perform lookups to table. Currently, with fast sequence generated row numbers, its guaranteed to be unique irrespective of insert transaction aborts / commits as updates to fast sequence are frozen non-transactional. For aborted insert the block-directory lookup fails to find blocks corresponding to row numbers as block-directory. But if using tuplecount approach same row number as aborted tuple gets assigned to visible tuple, it will lead to incorrect lookups.

**Comment by LJoNe** [comment]
Got it， thank you!
