### ISSUE TITLE
how to remove segment and mirror not need

### ISSUE THREAD

**Issue by luowencai** [greenplum-db/gpdb#9278]
### greeplum 6.2.1

Hi，We have some segment and mirror don't need in greeplum 6.2.1，How to remove it safely and correctly.

**Comment by gaos1** [comment]
Greenplum doesn't support this feature yet. you need to setup a new cluster and then use gpcopy or similiar tool to transfer data to new cluster. new cluster can live on the same hardware as old one. could you also share why you want to remove some segments?

**Comment by luowencai** [comment]
Because while install new cluster, our guys init wrong seg on master service，and there some data there。luckly，the data size was small，and we use copy command to solve it。
