### ISSUE TITLE
Use of UDF with window functions results in incorrect results

### ISSUE THREAD

**Issue by zhbp366** [greenplum-db/gpdb#9297]
### Greenplum version or build
6.0.0
### OS version and uname -a
CentOs 7.5
### Expected behavior
the output next like this:
 select *,lead(a) over(order by a)   next from test_udf_win order by a;
  a  | next 
-----+------
   1 |    2
   2 |    3
   3 |    4
   4 |    5
   5 |    6
   6 |    7
   7 |    8
   8 |    9
   9 |   10
### Actual behavior
the output next  is null:
select *,getnext( a,a )    next from test_udf_win order by a;                                
  a  | next 
-----+------
   1 | 
   2 | 
   3 | 
   4 | 
   5 | 
   6 | 
   7 | 
   8 | 
   9 | 
  10 | 
### Step to reproduce the behavior
···
create table test_udf_win(a int);
insert into test_udf_win select generate_series(1,100);
CREATE FUNCTION  getnext( text,text ) RETURNS text  LANGUAGE SQL  AS $$SELECT  lead($1) over(order by $2)   ;$$; 
select *,getnext( a,a )    next from test_udf_win order by a; 
···

**Comment by hlinnaka** [comment]
That's working correctly. When you use the window function within the function, each invocation of the function will execute the query `SELECT lead($1) OVER (ORDER BY $2)` separately. The window function within the UDF can't "see" the outer query.
