### ISSUE TITLE
could not find pathkey item to sort

### ISSUE THREAD

**Issue by zhongyibill** [greenplum-db/gpdb#9320]
Greenplum version or build
PostgreSQL 9.6beta4 (Greenplum Database 7.0.0-alpha.0 build dev)
I run madlib forest_train test case. The command case issue.
NOTICE:  sql_compute_oob_error :
DETAIL:
            CREATE TABLE __madlib_temp_94602308_1577346866_49394706__ AS
            SELECT
                gid,
                avg(
                CASE WHEN dep = forest_prediction::integer
                    THEN 0.
                    ELSE 1.
                END) AS oob_error
            FROM
            (
                SELECT
                    gid,
                    dep,
                    madlib.mode(oob_prediction) AS forest_prediction
                FROM
                    __madlib_temp_85721913_1577346866_28018774__
                GROUP BY gid, id, dep
            ) prediction_subq
            GROUP BY gid
ERROR:  spiexceptions.InternalError: could not find pathkey item to sort (plpy_elog.c:150)

function prepare_sort_from_pathkeys throws this issue. By debuging the code, the tlist_member_ignore_relabel calling equal(node, tlexpr)  judge which node in targest.
the node->location is  -1 so that can't found node in targetlist.

**Comment by pivotal-ning-yu** [comment]
@weinan003 is this is the same issue fixed by https://github.com/greenplum-db/gpdb/pull/9314 ?

**Comment by weinan003** [comment]
> @weinan003 is this is the same issue fixed by #9314 ?

I do not have madlib addon to validate this issue.
But depends on the error message, this issue is trigger by two pre-requirements, one is using a plpython and in the pl function should using SPI do some further work.

It is highly suspicious to be the same issue as #9314.

**Comment by zhongyibill** [comment]
yes, It is caused by the same issue as  #9314.

**Comment by zhongyibill** [comment]
yes, It is caused by the same issue as  #9314.
