### ISSUE TITLE
Data update for AO tables with more than 200 columns will be slow. Is there a good solution to this phenomenon? 

### ISSUE THREAD

**Issue by wanglunwei** [greenplum-db/gpdb#9327]
Explanation: The table has 60 million data, and it takes 80 seconds to update a column in a data.

**Comment by ashwinstar** [comment]
> On Dec 28, 2019, at 6:27 PM, wanglunwei <notifications@github.com> wrote:
> 
> ﻿
> Explanation: The table has 60 million data, and it takes 80 seconds to update a column in a data.
> 

It’s hard to help just based on that info. Please at least provide how many segments in cluster. If possible repro with SQL commands. Also, stating slow compared to what would be good info to provide.

**Comment by wanglunwei** [comment]
4 machines ,9 segments ,56G memory
The table has 60 million data, update one data, the value of one column, time-consuming: 80 seconds

**Comment by d** [comment]
> 4 machines ,9 segments ,56G memory
> The table has 60 million data, update one data, the value of one column, time-consuming: 80 seconds

SQL or it didn't happen

**Comment by gaos1** [comment]
please paste your table DDL and the SQL statement that you are using to update it.
