### ISSUE TITLE
Error "no partition for partitioning key" for new partitions in table

### ISSUE THREAD

**Issue by oSkrobuk** [greenplum-db/gpdb#9345]
### Greenplum version or build
PostgreSQL 8.3.23 (Greenplum Database 5.23.1)

### OS version and uname -a
Distributor ID: Ubuntu
Description: Ubuntu 14.04.1 LTS
Release : 14.04
Codename: trusty
Linux ******* 4.4.114-50 #1 SMP Fri Feb 2 10:53:13 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

### Installation information ( pg_config )
BINDIR = /usr/local/gpdb/bin
DOCDIR = /usr/local/gpdb/doc/postgresql
HTMLDIR = /usr/local/gpdb/doc/postgresql
INCLUDEDIR = /usr/local/gpdb/include
PKGINCLUDEDIR = /usr/local/gpdb/include/postgresql
INCLUDEDIR-SERVER = /usr/local/gpdb/include/postgresql/server
LIBDIR = /usr/local/gpdb/lib
PKGLIBDIR = /usr/local/gpdb/lib/postgresql
LOCALEDIR = /usr/local/gpdb/share/locale
MANDIR = /usr/local/gpdb/share/man
SHAREDIR = /usr/local/gpdb/share/postgresql
SYSCONFDIR = /usr/local/gpdb/etc/postgresql
PGXS = /usr/local/gpdb/lib/postgresql/pgxs/src/makefiles/pgxs.mk
CC = gcc
CPPFLAGS = -D_GNU_SOURCE -I/usr/local/gpdb/include
CFLAGS = -O3 -std=gnu99 -Wall -Wmissing-prototypes -Wpointer-arith -Wendif-labels -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fno-aggressive-loop-optimizations -Wno-unused-but-set-variable -Wno-address -I/usr/local/gpdb/include
CFLAGS_SL = -fpic
LDFLAGS = -Wl,--as-needed -Wl,-rpath,'/usr/local/gpdb/lib',--enable-new-dtags -L/usr/local/gpdb/lib
LDFLAGS_SL =
LIBS = -lpgport -lgpopt -lnaucrates -lgpdbcost -lgpos -lxerces-c -lxml2 -lrt -lcrypt -ldl -lm -L/usr/local/gpdb/lib
VERSION = PostgreSQL 8.3.23

### Expected behavior
Inserting data into new partitions in the table should occur without errors

### Actual behavior
We have a large number of tables with partitions created in GP 5.03 version
```
CREATE TABLE table_name 
(
  id INT,
  dt DATE
) 
PARTITION BY RANGE(dt) ( START ('2012-01-01'::date) END ('2020-01-01'::date) EVERY ('1 mon'::interval));
```

Recently updated the version of GP 5.23.1

Added new partitions to the above tables using query `ALTER TABLE table_name ADD PARTITION "202001" START ('2020-01-01'::DATE) END ('2020-02-01'::DATE)`

When trying to insert data directly into the partition, we get an error: `no partition for partitioning key`
Query: `INSERT INTO table_name_1_prt_202001 (dt) VALUES ('2020-01-01')`

Such a request executing without error: `INSERT INTO table_name (dt) VALUES ('2020-01-01')`

We also get an error when we try to delete records from new partitions: `DELETE FROM table_name_1_prt_202001 WHERE 1=1`

The error does not depend on the optimizer

No errors in the new sections of the tables that were created in version 5.23.1

**Comment by xiong-gang** [comment]
Thanks for reporting it but I can't reproduce the issue locally with the same exact steps. 
Could you please upload the information in `pg_partitions` and `pg_partition_rule` of this table?

**Comment by oSkrobuk** [comment]
Sorry for not responding for a long time

pg_partitions:
> schemaname	tablename	partitionschemaname	partitiontablename	partitionname	parentpartitiontablename	parentpartitionname	partitiontype	partitionlevel	partitionrank	partitionposition	partitionlistvalues	partitionrangestart	partitionstartinclusive	partitionrangeend	partitionendinclusive	partitioneveryclause	partitionisdefault	partitionboundary	parenttablespace	partitiontablespace
schema_name	table_name	schema_name	table_name_1_prt_201909	201909			range	0	91	91	""	'2019-09-01'::date	true	'2019-10-01'::date	false	'1 mon'::interval	false	PARTITION "201909" START ('2019-09-01'::date) END ('2019-10-01'::date) EVERY ('1 mon'::interval) WITH (appendonly=true	compresslevel=4	orientation=column	compresstype=zlib)	pg_default	pg_default
schema_name	table_name	schema_name	table_name_1_prt_201910	201910			range	0	92	92	""	'2019-10-01'::date	true	'2019-11-01'::date	false	'1 mon'::interval	false	PARTITION "201910" START ('2019-10-01'::date) END ('2019-11-01'::date) EVERY ('1 mon'::interval) WITH (appendonly=true	compresslevel=4	orientation=column	compresstype=zlib)	pg_default	pg_default
schema_name	table_name	schema_name	table_name_1_prt_201911	201911			range	0	93	93	""	'2019-11-01'::date	true	'2019-12-01'::date	false	'1 mon'::interval	false	PARTITION "201911" START ('2019-11-01'::date) END ('2019-12-01'::date) EVERY ('1 mon'::interval) WITH (appendonly=true	compresslevel=4	orientation=column	compresstype=zlib)	pg_default	pg_default
schema_name	table_name	schema_name	table_name_1_prt_201912	201912			range	0	94	94	""	'2019-12-01'::date	true	'2020-01-01'::date	false	'1 mon'::interval	false	PARTITION "201912" START ('2019-12-01'::date) END ('2020-01-01'::date) EVERY ('1 mon'::interval) WITH (appendonly=true	compresslevel=4	orientation=column	compresstype=zlib)	pg_default	pg_default
schema_name	table_name	schema_name	table_name_1_prt_202001	202001			range	0	95	95	""	'2020-01-01'::date	true	'2020-02-01'::date	false	""	false	PARTITION "202001" START ('2020-01-01'::date) END ('2020-02-01'::date) WITH (appendonly=true	compresslevel=4	orientation=column	compresstype=zlib)	pg_default	pg_default
schema_name	table_name	schema_name	table_name_1_prt_202002	202002			range	0	96	96	""	'2020-02-01'::date	true	'2020-03-01'::date	false	""	false	PARTITION "202002" START ('2020-02-01'::date) END ('2020-03-01'::date) WITH (appendonly=true	compresslevel=4	orientation=column	compresstype=zlib)	pg_default	pg_default
schema_name	table_name	schema_name	table_name_1_prt_202003	202003			range	0	97	97	""	'2020-03-01'::date	true	'2020-04-01'::date	false	""	false	PARTITION "202003" START ('2020-03-01'::date) END ('2020-04-01'::date) WITH (appendonly=true	compresslevel=4	orientation=column	compresstype=zlib)	pg_default	pg_default
schema_name	table_name	schema_name	table_name_1_prt_202004	202004			range	0	98	98	""	'2020-04-01'::date	true	'2020-05-01'::date	false	""	false	PARTITION "202004" START ('2020-04-01'::date) END ('2020-05-01'::date) WITH (appendonly=true	compresslevel=4	orientation=column	compresstype=zlib)	pg_default	pg_default
schema_name	table_name	schema_name	table_name_1_prt_202005	202005			range	0	99	99	""	'2020-05-01'::date	true	'2020-06-01'::date	false	""	false	PARTITION "202005" START ('2020-05-01'::date) END ('2020-06-01'::date) WITH (appendonly=true	compresslevel=4	orientation=column	compresstype=zlib)	pg_default	pg_default

pg_partition_rule:
> paroid	parchildrelid	parparentrule	parname	parisdefault	parruleord	parrangestartincl	parrangeendincl	parrangestart	parrangeend	parrangeevery	parlistvalues	parreloptions	partemplatespace
2532876	2533946	0	201909	false	91	true	false	({CONST :consttype 1082 :consttypmod -1 :constlen 4 :constbyval true :constisnull false :constvalue 4 [ 15 28 0 0 0 0 0 0 ]})	({CONST :consttype 1082 :consttypmod -1 :constlen 4 :constbyval true :constisnull false :constvalue 4 [ 45 28 0 0 0 0 0 0 ]})	({CONST :consttype 1186 :consttypmod -1 :constlen 16 :constbyval false :constisnull false :constvalue 16 [ 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 ]})	<>		0
2532876	2533958	0	201910	false	92	true	false	({CONST :consttype 1082 :consttypmod -1 :constlen 4 :constbyval true :constisnull false :constvalue 4 [ 45 28 0 0 0 0 0 0 ]})	({CONST :consttype 1082 :consttypmod -1 :constlen 4 :constbyval true :constisnull false :constvalue 4 [ 76 28 0 0 0 0 0 0 ]})	({CONST :consttype 1186 :consttypmod -1 :constlen 16 :constbyval false :constisnull false :constvalue 16 [ 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 ]})	<>		0
2532876	2533970	0	201911	false	93	true	false	({CONST :consttype 1082 :consttypmod -1 :constlen 4 :constbyval true :constisnull false :constvalue 4 [ 76 28 0 0 0 0 0 0 ]})	({CONST :consttype 1082 :consttypmod -1 :constlen 4 :constbyval true :constisnull false :constvalue 4 [ 106 28 0 0 0 0 0 0 ]})	({CONST :consttype 1186 :consttypmod -1 :constlen 16 :constbyval false :constisnull false :constvalue 16 [ 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 ]})	<>		0
2532876	2533982	0	201912	false	94	true	false	({CONST :consttype 1082 :consttypmod -1 :constlen 4 :constbyval true :constisnull false :constvalue 4 [ 106 28 0 0 0 0 0 0 ]})	({CONST :consttype 1082 :consttypmod -1 :constlen 4 :constbyval true :constisnull false :constvalue 4 [ -119 28 0 0 0 0 0 0 ]})	({CONST :consttype 1186 :consttypmod -1 :constlen 16 :constbyval false :constisnull false :constvalue 16 [ 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 ]})	<>		0
2532876	12697300	0	202001	false	95	true	false	({CONST :consttype 1082 :consttypmod -1 :constlen 4 :constbyval true :constisnull false :constvalue 4 [ -119 28 0 0 0 0 0 0 ]})	({CONST :consttype 1082 :consttypmod -1 :constlen 4 :constbyval true :constisnull false :constvalue 4 [ -88 28 0 0 0 0 0 0 ]})	<>	<>		0
2532876	12611953	0	202002	false	96	true	false	({CONST :consttype 1082 :consttypmod -1 :constlen 4 :constbyval true :constisnull false :constvalue 4 [ -88 28 0 0 0 0 0 0 ]})	({CONST :consttype 1082 :consttypmod -1 :constlen 4 :constbyval true :constisnull false :constvalue 4 [ -59 28 0 0 0 0 0 0 ]})	<>	<>		0
2532876	12611965	0	202003	false	97	true	false	({CONST :consttype 1082 :consttypmod -1 :constlen 4 :constbyval true :constisnull false :constvalue 4 [ -59 28 0 0 0 0 0 0 ]})	({CONST :consttype 1082 :consttypmod -1 :constlen 4 :constbyval true :constisnull false :constvalue 4 [ -28 28 0 0 0 0 0 0 ]})	<>	<>		0
2532876	12611977	0	202004	false	98	true	false	({CONST :consttype 1082 :consttypmod -1 :constlen 4 :constbyval true :constisnull false :constvalue 4 [ -28 28 0 0 0 0 0 0 ]})	({CONST :consttype 1082 :consttypmod -1 :constlen 4 :constbyval true :constisnull false :constvalue 4 [ 2 29 0 0 0 0 0 0 ]})	<>	<>		0
2532876	12611989	0	202005	false	99	true	false	({CONST :consttype 1082 :consttypmod -1 :constlen 4 :constbyval true :constisnull false :constvalue 4 [ 2 29 0 0 0 0 0 0 ]})	({CONST :consttype 1082 :consttypmod -1 :constlen 4 :constbyval true :constisnull false :constvalue 4 [ 33 29 0 0 0 0 0 0 ]})	<>	<>		0

**Comment by xiong-gang** [comment]
Hi @oSkrobuk , the catalog table is correct, I frankly don't know what causes the error, it doesn't look like a issue of upgrade.

**Comment by oSkrobuk** [comment]
Thanks @xiong-gang
