### ISSUE TITLE
ERROR:  query plan with multiple segworker groups is not supported

### ISSUE THREAD

**Issue by aqktjcm** [greenplum-db/gpdb#9384]
### Greenplum version or build

`PostgreSQL 9.6beta4 (Greenplum Database 7.0.0-alpha.0 build dev)`

### OS version and uname -a
`CentOS Linux release 7.5.1804 (Core)
`

### Expected behavior
`sql statements in Step 2 below would be excuted collectly with proper results output.
`
### Actual behavior
With the optimizer turned on, error ocurs while excuting sql statements in Step 2 below. 
Error Message is:
```
ERROR:  query plan with multiple segworker groups is not supported
HINT:  likely caused by a function that reads or modifies data in a distributed table
CONTEXT:  SQL function "random_name" statement 1
```

However, when set optimizer to 'off', the sql statements run well.

### Step to reproduce the behavior

1. connect database with psql, create database 'test_db', set optimizer to 'on'
```
[gpadmin@node1 ~]$ psql
psql (9.6beta4)
Type "help" for help.
postgres=# create database testdb;
CREATE DATABASE
postgres=# \c testdb
You are now connected to database "testdb" as user "gpadmin".
testdb=# set optimizer=on;
SET
testdb=# show optimizer;
 optimizer
-----------
 on
(1 row)
```

2. execute sql statements below:
```
CREATE TABLE source_name(name TEXT) distributed replicated;
INSERT INTO source_name VALUES ('James');
INSERT INTO source_name VALUES ('Tim');

CREATE OR REPLACE FUNCTION random_name()
RETURNS TEXT AS $$
    SELECT name
    FROM source_name
    ORDER BY random() LIMIT 1;
$$
LANGUAGE SQL VOLATILE;

CREATE TABLE people ( name TEXT);
INSERT INTO people VALUES ('Jack');

select name,random_name() from people;
```
3. error ocurs with messages printed below:
```
testdb=# select name,random_name() from people;
ERROR:  query plan with multiple segworker groups is not supported
HINT:  likely caused by a function that reads or modifies data in a distributed table
CONTEXT:  SQL function "random_name" statement 1
```

**Comment by kainwen** [comment]
With `optimizer = off`, this runs correctly.

The orca's plan is:

```
gpadmin=# explain select name,random_name() from people;
                                     QUERY PLAN
------------------------------------------------------------------------------------
 Result  (cost=0.00..431.00 rows=1 width=16)
   ->  Gather Motion 3:1  (slice1; segments: 3)  (cost=0.00..431.00 rows=1 width=5)
         ->  Seq Scan on people  (cost=0.00..431.00 rows=1 width=5)
 Optimizer: Pivotal Optimizer (GPORCA) version 3.87.0
(4 rows)
```

**Comment by aqktjcm** [comment]
> With `optimizer = off`, this runs correctly.
> 
> The orca's plan is:
> 
> ```
> gpadmin=# explain select name,random_name() from people;
>                                      QUERY PLAN
> ------------------------------------------------------------------------------------
>  Result  (cost=0.00..431.00 rows=1 width=16)
>    ->  Gather Motion 3:1  (slice1; segments: 3)  (cost=0.00..431.00 rows=1 width=5)
>          ->  Seq Scan on people  (cost=0.00..431.00 rows=1 width=5)
>  Optimizer: Pivotal Optimizer (GPORCA) version 3.87.0
> (4 rows)
> ```
> 
> It seems the result plannode should be under gather motion.

yes, given that the table source_name has the attribute 'distributed replicated', function random_name() executed in segments is reasonable.

**Comment by lij55** [comment]
the issue is still in 6 (by 6.20.0) and master (by 71664c2aa).

**Comment by ThinkBlue1991** [comment]
gp version : PostgreSQL 12.12 (Greenplum Database 7.0.0+dev.99.g0428461 build dev) on x86_64-pc-linux-gnu, compiled by gcc (GCC) 7.3.1 20180303 (Red H
at 7.3.1-5), 64-bit compiled on Nov 14 2023 15:44:03 Bhuvnesh C.

```
# with t as (select name from people limit 1) select name,random_name() from t;
ERROR:  query plan with multiple segworker groups is not supported
HINT:  likely caused by a function that reads or modifies data in a distributed table
CONTEXT:  SQL function "random_name" statement 1
```
the issue is still in 7
