### ISSUE TITLE
Mismatch in serialization and deserialization functions for PartitionNode

### ISSUE THREAD

**Issue by fangzheng** [greenplum-db/gpdb#9390]
### Greenplum version or build
current master

### Expected behavior
For PartitionNode, there is only one function named "_outPartitionNode()" (defined in outfuncs.c) that serializes three fields of PartitionNode: part, default_part, and rules.

On the other hand, there are two _readPartitionNode() functions (one in readfuncs.c and the other in readfast.c) for deserializing PartitionNode. The one defined in readfuncs.c only deserializes two fields (part and rules) and omits default_part.

I am wondering if such mismatch would cause error in deserialization. For example, a PartitionNode instance is first serialized via nodeToString(), and then deserialized via stringToNode(). If so, it's probably better to have only one 
_readPartitionNode() function that matches _outPartitionNode().

**Comment by hlinnaka** [comment]
Good catch! The functions in readfuncs.c are used when nodes are serialized to disk, e.g. when an expression is used in a view. However, PartitionNodes cannot appear in any such context, so the _readPartitionNode() function in readfuncs.c is in fact dead code. If it was used, it would indeed throw an error.

I fixed this incidentally in commit 2a59afb8, but I didn't see your issue until now.

**Comment by ashwinstar** [comment]
On Mon, Jan 13, 2020 at 10:55 AM Heikki Linnakangas <
notifications@github.com> wrote:

> Good catch! The functions in readfuncs.c are used when nodes are
> serialized to disk, e.g. when an expression is used in a view. However,
> PartitionNodes cannot appear in any such context, so the
> _readPartitionNode() function in readfuncs.c is in fact dead code. If it
> was used, it would indeed throw an error.
>
> I fixed this incidentally in commit 2a59afb
> <https://github.com/greenplum-db/gpdb/commit/2a59afb899635331e438af6ea10384f16006480b>,
> but I didn't see your issue until now.
>
Do we need to do anything in back branches (6X_STABLE) for this?

>

**Comment by hlinnaka** [comment]
I guess we should fix it in back branches too, even though it's not a live bug.

Now that I look more closely, there's a similar mismatch in the _outPartitionRule() functions. I'll go fix that, and also backpatch.

**Comment by hlinnaka** [comment]
Ok, pushed patches to clean this up in 6X_STABLE and master.
