### ISSUE TITLE
现在遇到一个问题：复杂sql查询，做了offset，offset 180000 limit 10000 以前的查询很快能返回结果，但是offset 190000 以后就一直不返回结果

### ISSUE THREAD

**Issue by xueyilong** [greenplum-db/gpdb#941]

**Comment by danielgustafsson** [comment]
Hi @xueyilong, if possible please use English for issues/questions. Google translate returns this:

> When we encounter a problem: complex sql queries, do offset, offset 180000 limit 10000 previous query soon be able to return results, but has been offset 190000 after not return results

**Comment by xueyilong** [comment]
@danielgustafsson ,Thanks for reminding me, this is my first time to use it

**Comment by danielgustafsson** [comment]
Not a problem, can you show the query you are having problems with and more in detail what the problem is?

**Comment by xueyilong** [comment]
this is my query:

SELECT membership_id,brand_id,merchant_id,'2016-07-12' as trans_date,SUM(cash) cash,SUM(score) score,SUM(stored) stored,SUM(coupon) coupon,
       SUM(store_pay) store_pay,SUM(cash_income) cash_income,SUM(total_consume) total_consume,SUM(valid_consume) valid_consume,SUM(launch_number) launch_number,SUM(response_number) response_number , 
       (CASE WHEN SUM(couponcount)>0 THEN SUM(total_consume) ELSE 0 END )AS marketing_income,
       (CASE WHEN SUM(couponcount)>0 THEN SUM(cash)+SUM(stored) ELSE 0 END ) AS relative_income
FROM (SELECT * from (
                     SELECT tran.membership_id,merchant.brand_id,merchant.merchant_id,
                            SUM(case tran.trans_code when '0002' then tran.amount else 0 end)as cash,
                            SUM(case tran.trans_code when '1002' then tran.amount else 0 end)as score,
                            SUM(case tran.trans_code when '2002' then tran.amount else 0 end)as stored,
                            SUM( case tran.trans_code when '2001' then tran.amount when '2005' then tran.amount else 0 end)as store_pay,
                            SUM( case when tran.trans_code = '2001' then tran.amount when tran.trans_code = '0002' then tran.amount when tran.trans_code = '2005' and id = master_id then tran.amount else 0 end)as cash_income,
                            SUM(case when tran.trans_code = '3001' and tran.coupon_consume_quantity is not null then tran.amount*tran.coupon_consume_quantity  when tran.trans_code = '3005' and tran.coupon_consume_quantity is not null then tran.amount*tran.coupon_consume_quantity else 0 end)as coupon,
                            COUNT(CASE tran.trans_code WHEN '3001' THEN 1 WHEN '3005' THEN 1 ELSE NULL END) AS couponcount,
                            (SUM(case tran.trans_code when '0002' then tran.amount else 0 end)+
                            SUM(case tran.trans_code when '1002' then tran.amount else 0 end)+
                            SUM(case tran.trans_code when '2002' then tran.amount else 0 end)+
                            SUM(case when tran.trans_code = '3001' and tran.coupon_consume_quantity is not null then tran.amount*tran.coupon_consume_quantity  when tran.trans_code = '3005' and tran.coupon_consume_quantity is not null then tran.amount*tran.coupon_consume_quantity  else 0 end)
                            )AS total_consume,
                            (SUM(case tran.trans_code when '0002' then tran.amount else 0 end)+
                            SUM(case tran.trans_code when '2002' then tran.amount else 0 end)
                            )AS valid_consume ,
                            0 launch_number,0 response_number
                     FROM public.trans_water AS tran,trade.merchant merchant
                     WHERE tran.reversedflag = FALSE 
                           AND tran.revocationflag = FALSE
                           AND tran.trans_merchant = merchant.merchant_no
                           AND tran.trans_code in ('0002','1002','2002','3001','2001','2005','3005')
                           AND tran.trans_date >= '2016-07-12' 
                           AND tran.trans_date < '2016-07-13'
                           AND tran.membership_id <> 0
                     GROUP BY tran.membership_id,merchant.brand_id,merchant.merchant_id
                     )AS tmp                
                     UNION ALL
                     SELECT * FROM (SELECT tran2.membership_id,tran2.brand_id,tran2.merchant_id,0 cash,0 score,0 stored,0 coupon,0 store_pay,0 cash_income,0 couponcount,0 total_consume,0 valid_consume,sum(tran2.fqs) as launch_number,sum(tran2.xys) as response_number 
                                    FROM (SELECT tm.id membership_id,merchant1.brand_id,coupon.merchant_id,sum(send_quantity) fqs,0 xys 
                                          FROM public.v_coupon as coupon,trade.membership tm,trade.merchant merchant1,trade.merchant merchant2
                                          WHERE coupon.mobile = tm.mobile 
                                                and coupon.merchant_id = merchant1.merchant_id 
                                                and tm.merchant_id = merchant2.merchant_id 
                                                and merchant1.brand = merchant2.brand 
                                                and coupon.send_time >= '2016-07-12' 
                                                and coupon.send_time < '2016-07-13' 
                                          GROUP BY tm.id,coupon.merchant_id ,merchant1.brand_id
                                          UNION all
                                          SELECT tran1.membership_id,tran1.brand_id,tran1.merchant_id,0 fqs ,tran1.tr_count as xys 
                                          FROM (SELECT trans.membership_id,merchant.brand_id,merchant.merchant_id,SUM(trans.coupon_consume_quantity) AS tr_count 
                                                FROM public.trans_water as trans,trade.merchant merchant
                                                WHERE trans_code = '3001' 
                                                      and trans.trans_date >= '2016-07-12' 
                                                      and trans.trans_date < '2016-07-13' 
                                                      and trans.trans_merchant = merchant.merchant_no
                                                GROUP BY trans.membership_id,merchant.merchant_id ,merchant.brand_id
                                                )AS tran1 
                                           )AS tran2 
                                    GROUP BY tran2.membership_id,tran2.merchant_id ,tran2.brand_id
                     ) AS tmp2 
        ) AS tmp3 
GROUP BY tmp3.membership_id,tmp3.brand_id,tmp3.merchant_id 
ORDER BY tmp3.membership_id,tmp3.brand_id,tmp3.merchant_id
offset 190000 limit 10000;

**Comment by xueyilong** [comment]
when the query's offset less then 190000,the query can return the result faster,but when offset greater than 190000, the query can't return the result and it's always Execute

**Comment by hsyuan** [comment]
Can you provide the plan that is generated? Is ORCA turned on?
run `show optimizer;`

**Comment by ascherbaum-pivotal** [comment]
Any update on this issue, @xueyilong?

**Comment by ascherbaum-pivotal** [comment]
Closing, because one month without response. Please open another issue if this is still a problem. Please include the details requested by Daniel.
