### ISSUE TITLE
GP6 unrecognized path type when select

### ISSUE THREAD

**Issue by HugWenjiang** [greenplum-db/gpdb#9427]
### Greenplum version or build
GP 6.2.1
### OS version and uname -a
centos7.6

### Step to reproduce the behavior
CREATE TABLE "log_all_temp"."cost_log" (
  "dist_gather_id" int8 NOT NULL,
  "id" int8 NOT NULL,
  "update_time" timestamp(0) NOT NULL DEFAULT '2000-01-01 00:00:00'::timestamp without time zone,
  "original_time" timestamp(0) DEFAULT '2000-01-01 00:00:00'::timestamp without time zone,
  "gid" varchar(32) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
  "account" varchar(64) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
  "level" int8 DEFAULT (0)::bigint,
  "type" int8 DEFAULT (0)::bigint,
  "action" varchar(32) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
  "gold_coin_cost" int8 DEFAULT (0)::bigint,
  "gold_coin_left" int8 DEFAULT (0)::bigint,
  "gold_coin_gift_left" int8 DEFAULT (0)::bigint,
  "gold_coin_gift_cost" int8 DEFAULT (0)::bigint,
  "cur_state" int8 DEFAULT (0)::bigint,
  "uid" varchar(32) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
  "ip" varchar(32) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
  "mac" varchar(256) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
  "channel" varchar(32) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
  "para1" varchar(32) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
  "para2" varchar(32) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
  "para3" varchar(32) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
  "gs_memo" text COLLATE "pg_catalog"."default",
  "memo" text COLLATE "pg_catalog"."default",
  "data_date" int8 NOT NULL DEFAULT (0)::bigint,
  "record_time" timestamp(0) DEFAULT now(),
  "oaid" varchar(64) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
  CONSTRAINT "cost_log_pkey" PRIMARY KEY ("dist_gather_id", "update_time", "id", "data_date")
)
PARTITION BY RANGE(data_date) 
          (
		  PARTITION p20200114 START (20200114) END (20200115) exclusive, 
		  PARTITION p20200115 START (20200115) END (20200116) exclusive, 
          DEFAULT PARTITION default_part 
          )
;

CREATE TABLE "log_all"."cost_log" (
  "dist_gather_id" int8 NOT NULL,
  "id" int8 NOT NULL,
  "update_time" timestamp(0) NOT NULL DEFAULT '2000-01-01 00:00:00'::timestamp without time zone,
  "original_time" timestamp(0) DEFAULT '2000-01-01 00:00:00'::timestamp without time zone,
  "gid" varchar(32) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
  "account" varchar(64) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
  "level" int8 DEFAULT (0)::bigint,
  "type" int8 DEFAULT (0)::bigint,
  "action" varchar(32) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
  "gold_coin_cost" int8 DEFAULT (0)::bigint,
  "gold_coin_left" int8 DEFAULT (0)::bigint,
  "gold_coin_gift_left" int8 DEFAULT (0)::bigint,
  "gold_coin_gift_cost" int8 DEFAULT (0)::bigint,
  "cur_state" int8 DEFAULT (0)::bigint,
  "uid" varchar(32) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
  "ip" varchar(32) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
  "mac" varchar(256) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
  "channel" varchar(32) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
  "para1" varchar(32) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
  "para2" varchar(32) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
  "para3" varchar(32) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
  "gs_memo" text COLLATE "pg_catalog"."default",
  "memo" text COLLATE "pg_catalog"."default",
  "data_date" int8 NOT NULL DEFAULT (0)::bigint,
  "record_time" timestamp(0) DEFAULT now(),
  "oaid" varchar(64) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
  CONSTRAINT "cost_log3_pkey" PRIMARY KEY ("dist_gather_id", "update_time", "id", "data_date")
)
PARTITION BY RANGE(data_date) 
          (
		  PARTITION p202001 START (20200101) END (20200201) exclusive, 
		  PARTITION p202002 START (20200201) END (20200301) exclusive, 
          DEFAULT PARTITION default_part 
          )
;

---- insert some data into the tables;

The SQL：
select * from "log_all_temp"."cost_log" t1
where
t1.dist_gather_id=130834
and t1.update_time between  '2020-01-15 13:01:21' and '2020-01-15 13:52:21' 
and t1.data_date between to_char('2020-01-15 13:01:21'::timestamp(0),'YYYYMMDD')::int and to_char('2020-01-15 13:52:21'::timestamp(0),'YYYYMMDD')::int 
and
 not exists (select 1 from "log_all".cost_log t2 where t2.dist_gather_id=130834 and t2.update_time between  '2020-01-15 13:01:21' and '2020-01-15 13:52:21' and t2.data_date between to_char('2020-01-15 13:01:21'::timestamp(0),'YYYYMMDD')::int and to_char('2020-01-15 13:52:21'::timestamp(0),'YYYYMMDD')::int  and t1.data_date=t2.data_date   and t1.update_time=t2.update_time  and t1.id=t2.id)

ERROR：
select * from "log_all_temp"."cost_log" t1
where
t1.dist_gather_id=130834
and t1.update_time between  '2020-01-15 13:01:21' and '2020-01-15 13:52:21' 
and t1.data_date between to_char('2020-01-15 13:01:21'::timestamp(0),'YYYYMMDD')::int and to_char('2020-01-15 13:52:21'::timestamp(0),'YYYYMMDD')::int 
and
 not exists (select 1 from "log_all".cost_log t2 where t2.dist_gather_id=130834 and t2.update_time between  '2020-01-15 13:01:21' and '2020-01-15 13:52:21' and t2.data_date between to_char('2020-01-15 13:01:21'::timestamp(0),'YYYYMMDD')::int and to_char('2020-01-15 13:52:21'::timestamp(0),'YYYYMMDD')::int  and t1.data_date=t2.data_date   and t1.update_time=t2.update_time  and t1.id=t2.id)
> ERROR:  unrecognized path type: 106 (pathnode.c:216)
  
> 时间: 0.108s

**Comment by kainwen** [comment]
type 106 is merge_append.

I can reproduce this issue with the help of gdb:

break at the function create_merge_append_path
run the sql
use gdb to set the cost of the merge_append_path to a very small value
continue
We will hit this.

The RCA is that the function pathnode_walk_kids does not consider merge_append plannode.

Just add this field will fix the issue.

The hard part of the issue is how we can add a test case easily.

**Comment by kainwen** [comment]
Open a pr to fix this: https://github.com/greenplum-db/gpdb/pull/10483
