### ISSUE TITLE
uuid-ossp extension error

### ISSUE THREAD

**Issue by PauloVSReis** [greenplum-db/gpdb#9507]
When trying to install the extension in the database, I get the following error:

demo=# CREATE EXTENSION "uuid-ossp";
ERROR:  could not open extension control file "/opt/gpdb/share/postgresql/extension/uuid-ossp.control": No such file or directory

-------------------------------------------
Greenplum 5.16.0

**Comment by Eulerizeit** [comment]
UUID isn't supported for Greenplum. Most of the extension support that exists are extensions that can act on the segment in a way that is recognizable and actionable to the master. 

UUID would need to be coordinated by the master so the IDs are unique. This is not impossible but we have not done it yet. 

This might be an interesting problem to solve if you would like to contribute something.
