### ISSUE TITLE
Error of ACL when "CREATE PARTITION TABLE" after "ALTER DEFAULT PRIVILEGES"

### ISSUE THREAD

**Issue by meso4444** [greenplum-db/gpdb#9524]
### Greenplum version or build
6.3

### OS version and uname -a
CentOS 7 
3.10.0-693.el7.x86_64

### Step to reproduce the behavior

Step 1. ALTER DEFAULT PRIVILEGES

` 
ALTER DEFAULT PRIVILEGES FOR ROLE gpadmin IN SCHEMA public GRANT SELECT ON TABLES  TO user01
 `

Step 2. CREATE PARTITION TABLE

`
CREATE TABLE public.test_partition(
dt date
)
PARTITION BY RANGE (dt)
( START (date '2019-12-01') INCLUSIVE
END (date '2020-02-01') EXCLUSIVE
EVERY (INTERVAL '1 month') );
`

Then got an Error:
`ERROR: cannot copy ACL from parent, because there is an existing ACL (aclchk.c:2273)`

**Comment by LittleWuCoding** [comment]
I get this problem，too. 
Does any one can explain ? @flavorjones @paul-guo-  Need your Help~

**Comment by NEUPeter** [comment]
I get this problem，too.，need help，fellows

**Comment by kainwen** [comment]
Thanks for reporting this. Will take a look at it.

**Comment by kainwen** [comment]
GPDB 5 (with the kernel version 8.3) does not support the syntax `ALTER DEFAULT PRIVILEGES`.

6X and master have been fixed. So close this issue.

Feel free to discuss here for any further questions on this issue.
