### ISSUE TITLE
Function running on EntryDB cannot do dispatch

### ISSUE THREAD

**Issue by zhangh43** [greenplum-db/gpdb#9539]
### Greenplum version or build
GPDB master, 6X, 5X

### Actual behavior

create temp table t as select * from get_country();
ERROR:  function cannot execute on a QE slice because it issues a non-SELECT statement  (entry db 10.146.0.4:7000 pid=16593)
CONTEXT:  SQL statement "drop table if exists public.country"
PL/pgSQL function get_countryw() line 3 at SQL statement

### Step to reproduce the behavior
CREATE OR REPLACE FUNCTION get_country()
 RETURNS TABLE (
  country_id integer,
  country character varying(50)
  )

AS $$
  begin
  drop table if exists public.country;
  create table public.country( country_id integer,
    country character varying(50));
  insert into public.country
  (country_id, country)
  select 111,'INDIA'
  union all select 222,'CANADA'
  union all select 333,'USA' ;
  RETURN QUERY
  SELECT
  c.country_id,
  c.country
  FROM
  public.country c;
  end; $$
LANGUAGE 'plpgsql';

create temp table t as select * from get_country();

**Comment by zhangh43** [comment]
PR #9542 is trying to fix this issue.

**Comment by ivannovick** [comment]
love it

**Comment by zhangh43** [comment]
PR #9542 merged.
