### ISSUE TITLE
Failed to decrypt the data that encrypted with the OS command tool gpg

### ISSUE THREAD

**Issue by Honglei-Guo** [greenplum-db/gpdb#9572]
We encrypted some data with `gpg`(_gpg (GnuPG) 2.0.14, libgcrypt 1.4.5_) and imported it to a GPDB table successfully. But when we tried to decrypt it with function `pgp_pub_decrypt()`, an error occurred: **ERROR:  Not text data  (seg0 slice2 elcid-stg01.eng.pivotal.io:40000 pid=453)**

BTW, we armored the result by specifying the `-a` option when running `gpg`. And, we make sure the keys are correct. 

What could be wrong here?

**Comment by hlinnaka** [comment]
If the encrypted data is not pure ascii, you'll need to use `pgp_pub_decrypt_bytea()` instead. `pgp_pub_decrypt()` might also expect to see a pgrypto-specific header to identify the input as text, so even if the data contains just text, gpg might not create the header. The bottom line is, try `pgp_pub_decrypt_bytea()`.

**Comment by Honglei-Guo** [comment]
Thanks, @hlinnaka. `pgp_pub_decrypt_bytea()` does work. But it cannot correctly decrypt Chinese and Japanese. Could you give some suggestion for solving this issue, please?
![image](https://user-images.githubusercontent.com/50401451/74579804-6e488c80-4fd8-11ea-96e6-eca4712eecb4.png)

**Comment by hlinnaka** [comment]
On 15 February 2020 03:53:25 EET, Honglei Guo <notifications@github.com> wrote:
>Thanks, @hlinnaka. `pgp_pub_decrypt_bytea()` does work. But it cannot
>correctly decrypt Chinese and Japanese. Could you give some suggestion
>for solving this issue, please?

The result of pgp_pub_decrypt_bytea() is a bytea, that is, a binary string. You can use the convert_from() function to convert it to text.

- Heikki

**Comment by Honglei-Guo** [comment]
@hlinnaka, thank you very much!!!. It works. The final query:
```
select pg_catalog.convert_from(pgp_pub_decrypt_bytea(dearmor(b.name), dearmor(privatekey)), 'UTF8'::name)
from my_table AS b;
``` 

Thanks!
