### ISSUE TITLE
Memory in CdbPgResults.pg_results is calloc()-ed but not free()-ed after use

### ISSUE THREAD

**Issue by fangzheng** [greenplum-db/gpdb#9577]
### Greenplum version or build
6x_stable, master

In most cases, the CdbPgResults.pg_results array that is returned from various dispatch functions is not free()-ed after use.  A typical example can be found in cdbRelMaxSegSize() function (https://github.com/greenplum-db/gpdb/blob/master/src/backend/cdb/cdbrelsize.c#L36): After CdbPgResults.pg_results is consumed, only cdbdisp_clearCdbPgResults() is called, but that does not free the memory of CdbPgResults.pg_results array.

There are several other places like this. The only exception I found is in CdbDispatchDtxProtocolCommand(). The array is returned to its caller doDispatchDtxProtocolCommand() and gets free()-ed there.

Given that CdbPgResults.pg_results is allocated by cdbdisp_returnResults() via calloc(), failing to call free() would result in memory leak.

If this issue is confirmed, I would be happy to provide a pull request. Thanks.

**Comment by pengzhout** [comment]
That would be a problem, thanks to report it, a patch is welcomed,

**Comment by fangzheng** [comment]
Thanks for confirmation. I will submit a PR soon.

**Comment by d** [comment]
This is an issue indeed. I can't help but ask: why aren't we using `palloc0` and friends theee, but instead using `calloc`? The dispatcher struct doesn't really have a lifespan of "forever", unlike the memory for the GUC's...

**Comment by fangzheng** [comment]
Close this issue as PR#9583 has been merged into master.
