### ISSUE TITLE
"ERROR:  no partition for partitioning key" on INSERT

### ISSUE THREAD

**Issue by d** [greenplum-db/gpdb#9579]
### Greenplum version or build
7.0 alpha master branch (as of reporting, commit 684fe03275 )

### OS version and uname -a
Linux

### Step to reproduce the behavior
```sql
CREATE TABLE abuela_16 (a int, b int, c int)
DISTRIBUTED BY (a)
PARTITION BY range(b) (START(0) END(131072) EVERY(2))
;
INSERT INTO abuela_16 VALUES (42, 42, 42);
```

### Expected behavior
The `INSERT` succeeds and inserts one tuple into the 21st partition (0-based).

### Actual behavior
```
ERROR:  no partition for partitioning key
```

**Comment by lij55** [comment]
I run the original query in a less poewrful machin so I hit 'Canceling query because of high VMEM usage. Used: 7370MB, available 816MB, red zone: 7372MB (runaway_cleaner.c:200)' error with original error. 
It will success if I decrease the end number of partition range.
```sql
test=# CREATE TABLE abuela_16 (a int, b int, c int)
test-# DISTRIBUTED BY (a)
test-# PARTITION BY range(b) (START(0) END(100) EVERY(2))
test-# ;
CREATE TABLE
test=# INSERT INTO abuela_16 VALUES (42, 42, 42);
INSERT 0 1
test=# select * from abuela_16;
 a  | b  | c  
----+----+----
 42 | 42 | 42
(1 row)
test=# select * from abuela_16_1_prt_22;                                                                                                                                            
 a  | b  | c  
----+----+----
 42 | 42 | 42
(1 row)

```

so closing the issue.
