### ISSUE TITLE
Greenplum Failure of expand

### ISSUE THREAD

**Issue by wangxy0825** [greenplum-db/gpdb#9604]
### Greenplum version or build
Greenplum 5.1
### OS version and uname -a
CentOS Linux release 7.2.1511 (Core) 
### autoconf options used ( config.status --config )
gpexpand -i /home/gpadmin/onekey/gpexpand_inputfile_20200223_134656  -D ircs_du -S -V -v -n 1 -B 1 -t /u01/tmp
### Installation information ( pg_config )
4 servers ，28 segment  expand 2 servers
gpexpand -i /home/gpadmin/onekey/gpexpand_inputfile_20200223_134656  -D ircs_du -S -V -v -n 1 -B 1 -t /u01/tmp
### Expected behavior
expand success
### Actual behavior
20200221:22:16:41:042860 gpexpand:mdw:gpadmin-[DEBUG]:-[worker0] finished cmd: gpexpand remove segment template file on host: sdw05 cmdStr='GPSTART_INTERNAL_MASTER_ONLY=1 && ssh -o 'StrictHostKeyChecking no' sdw05 ". /usr/local/greenplum-db/./greenplum_path.sh; GPSTART_INTERNAL_MASTER_ONLY=1 && /bin/rm -f /u01/tmp/gpexpand_schema.tar"'  had result: cmd had rc=0 completed=True halted=False
  stdout=''
  stderr=''
20200221:22:16:41:042860 gpexpand:mdw:gpadmin-[DEBUG]:-[worker0] got cmd: /bin/rm -f /u01/tmp/gpexpand_schema.tar
20200221:22:16:42:042860 gpexpand:mdw:gpadmin-[DEBUG]:-[worker0] finished cmd: gpexpand remove segment template file on host: sdw06 cmdStr='GPSTART_INTERNAL_MASTER_ONLY=1 && ssh -o 'StrictHostKeyChecking no' sdw06 ". /usr/local/greenplum-db/./greenplum_path.sh; GPSTART_INTERNAL_MASTER_ONLY=1 && /bin/rm -f /u01/tmp/gpexpand_schema.tar"'  had result: cmd had rc=0 completed=True halted=False
  stdout=''
  stderr=''
20200221:22:16:42:042860 gpexpand:mdw:gpadmin-[DEBUG]:-Transitioning from UPDATE_OLD_SEGMENTS_STARTED to UPDATE_OLD_SEGMENTS_DONE
20200221:22:16:43:042860 gpexpand:mdw:gpadmin-[DEBUG]:-Transitioning from UPDATE_OLD_SEGMENTS_DONE to UPDATE_CATALOG_STARTED
20200221:22:16:43:042860 gpexpand:mdw:gpadmin-[INFO]:-Starting Greenplum Database in restricted mode
20200221:22:16:46:042860 gpexpand:mdw:gpadmin-[ERROR]:-gpexpand failed. exiting...
Traceback (most recent call last):
  File "/usr/local/greenplum-db/./bin/gpexpand", line 3154, in main
    _gp_expand.update_catalog()
  File "/usr/local/greenplum-db/./bin/gpexpand", line 1649, in update_catalog
    startCmd.run(validateAfter=True)
  File "/usr/local/greenplum-db/lib/python/gppylib/commands/base.py", line 694, in run
    self.validate()
  File "/usr/local/greenplum-db/lib/python/gppylib/commands/base.py", line 741, in validate
    raise ExecutionError("non-zero rc: %d" % self.results.rc, self)
ExecutionError: ExecutionError: 'non-zero rc: 2' occured.  Details: 'GPSTART_INTERNAL_MASTER_ONLY=1 && $GPHOME/bin/gpstart -a -R -v'  cmd had rc=2 completed=True halted=False
  stdout='20200221:22:16:43:046164 gpstart:mdw:gpadmin-[INFO]:-Starting gpstart with args: -a -R -v
20200221:22:16:43:046164 gpstart:mdw:gpadmin-[DEBUG]:-Setting level of parallelism to: 64
20200221:22:16:43:046164 gpstart:mdw:gpadmin-[INFO]:-Gathering information and validating the environment...
20200221:22:16:43:046164 gpstart:mdw:gpadmin-[DEBUG]:---Checking that current user can use GP binaries
20200221:22:16:43:046164 gpstart:mdw:gpadmin-[DEBUG]:-Obtaining master's port from master data directory
20200221:22:16:43:046164 gpstart:mdw:gpadmin-[DEBUG]:-Read from postgresql.conf port=5432
20200221:22:16:43:046164 gpstart:mdw:gpadmin-[DEBUG]:-Read from postgresql.conf max_connections=250
20200221:22:16:43:046164 gpstart:mdw:gpadmin-[INFO]:-Reading the gp_dbid file - /u01/data/master/gpseg-1/gp_dbid...
20200221:22:16:43:046164 gpstart:mdw:gpadmin-[DEBUG]:-Parsing : # Greenplum Database identifier for this master/segment. ...
20200221:22:16:43:046164 gpstart:mdw:gpadmin-[DEBUG]:-Parsing : # Do not change the contents of this file. ...
20200221:22:16:43:046164 gpstart:mdw:gpadmin-[DEBUG]:-Parsing : dbid = 1 ...
20200221:22:16:43:046164 gpstart:mdw:gpadmin-[INFO]:-Found match for dbid: 1.
20200221:22:16:43:046164 gpstart:mdw:gpadmin-[DEBUG]:-Parsing : standby_dbid = 58 ...
20200221:22:16:43:046164 gpstart:mdw:gpadmin-[INFO]:-Found match for standby_dbid: 58.
20200221:22:16:44:046164 gpstart:mdw:gpadmin-[INFO]:-Greenplum Binary Version: 'postgres (Greenplum Database) 5.1.0 build commit:529adcb13898f4d24d15ce5445f5698584dd5cff'
20200221:22:16:44:046164 gpstart:mdw:gpadmin-[INFO]:-Greenplum Catalog Version: '301705051'
20200221:22:16:44:046164 gpstart:mdw:gpadmin-[DEBUG]:-Check if Master is already running...
20200221:22:16:44:046164 gpstart:mdw:gpadmin-[INFO]:-Starting Master instance in admin mode
20200221:22:16:46:046164 gpstart:mdw:gpadmin-[INFO]:-Obtaining Greenplum Master catalog information
20200221:22:16:46:046164 gpstart:mdw:gpadmin-[INFO]:-Obtaining Segment details from master...
20200221:22:16:46:046164 gpstart:mdw:gpadmin-[DEBUG]:-Connecting to dbname='template1'
20200221:22:16:46:046164 gpstart:mdw:gpadmin-[ERROR]:-gpstart failed.  exiting...
Traceback (most recent call last):
  File "/usr/local/greenplum-db/lib/python/gppylib/mainUtils.py", line 271, in simple_main_locked
    exitCode = commandObject.run()
  File "/usr/local/greenplum-db/./bin/gpstart", line 120, in run
    self._startMaster()
  File "/usr/local/greenplum-db/./bin/gpstart", line 453, in _startMaster
    self.gparray = GpArray.initFromCatalog(self.dburl, utility=True)
  File "/usr/local/greenplum-db/lib/python/gppylib/gparray.py", line 1331, in initFromCatalog
    conn = dbconn.connect(dbURL, utility)
  File "/usr/local/greenplum-db/lib/python/gppylib/db/dbconn.py", line 205, in connect
    cnx  = pgdb._connect_(cstr, dbhost, dbport, dbopt, dbtty, dbuser, dbpasswd)
InternalError: could not connect to server: Connection refused
        Is the server running on host "localhost" (127.0.0.1) and accepting
        TCP/IP connections on port 5432?
 
'
  stderr=''
20200221:22:16:46:042860 gpexpand:mdw:gpadmin-[ERROR]:-Please run 'gpexpand -r -D ircs_du' to rollback to the original state.
20200221:22:16:46:042860 gpexpand:mdw:gpadmin-[INFO]:-Shutting down gpexpand...
20200221:22:16:46:042860 gpexpand:mdw:gpadmin-[DEBUG]:-WorkerPool haltWork()
20200221:22:16:46:042860 gpexpand:mdw:gpadmin-[DEBUG]:-[worker0] haltWork
20200221:22:16:46:042860 gpexpand:mdw:gpadmin-[DEBUG]:-[worker0] got a halt cmd
20200221:22:16:46:042860 gpexpand:mdw:gpadmin-[DEBUG]:-WorkerPool haltWork()
20200221:22:16:46:042860 gpexpand:mdw:gpadmin-[DEBUG]:-[worker0] haltWork

**Comment by kainwen** [comment]
Close it since no more info. Feel free to reopen it.
