### ISSUE TITLE
Wrong results for query with EXPR_SUBLINK

### ISSUE THREAD

**Issue by guofengrichard** [greenplum-db/gpdb#9615]
### Greenplum version or build
Master, but I believe it also exists in 6X and 5X.

### Step to reproduce the behavior
```
drop table if exists foo;
drop table if exists bar;

create table foo(a int, b int);
create table bar(a int, b int);

insert into foo select i, i from generate_series(1,2)i;
insert into bar select i, i from generate_series(1,2)i;

select * from foo where foo.a > (select avg(bar.a) from bar where foo.b + bar.a = bar.b);
```

### Expected behavior
```
 a | b
---+---
(0 rows)
```

### Actual behavior
```
 a | b
---+---
 2 | 2
(1 row)
```

**Comment by kainwen** [comment]
This has been fixed in master branch.

As mentioned in the issue, this may also be a bug in 5x and 6x. Should we backport and then close this?
