### ISSUE TITLE
problem with vm.overcommit_memory

### ISSUE THREAD

**Issue by LittleWuCoding** [greenplum-db/gpdb#9643]
### Greenplum version or build
Greenplum 6.1
### OS version and uname -a
rhel7

Hi, I come cross problem with Greenplum and other BigData tools in same machine.
the greenplum require the OS parameter vm.overcommit_memory to be 2 ,but that results in
other BigData tools (like redis) to frequent restart for shortage of mems, which works well with  
vm.overcommit_memory = 0.
So, what could I do to make them live in harmony? any suggestions would be helpful~

**Comment by paul-guo-** [comment]
Deploying two memory-intensive S/W on the same node does not look like a good idea. You could monitor the physical memory usage of redis if the physical memory requirement is high you need to increase the memory size, else maybe you could try adding a swap file to cheat kernel?

**Comment by LittleWuCoding** [comment]
Thanks for your reply.
Also I wondering if the OS parameter vm.overcommit_memory must be 2 with Greenplum?
It is OK to set it to 0 ? What's the danger？

**Comment by paul-guo-** [comment]
To my knowledge, setting to 2 is to avoid backend termination by SIGKILL due to lack of memory when accessing previously allocated memory. That kind of backend termination would cause the postgres instance restart and thus is not friendly in product environment.

**Comment by yuweisung** [comment]
vm.overcommit_memory=0 => Let Linux kernel decide whether or not refuse the
memory allocation requests (heuristic). Kernel rejects super large memory
allocation to avoid swap.  It is a bit safer than overcommit_memory=1.
But it will not stop "regular" memory allocations in forking. In the end,
swap activity will increase.
For test or development, I think this is fine assuming you really not worry
about data lost and the cost of data recovery is cheap.

**Comment by LittleWuCoding** [comment]
Thinks for your kindly explanation. @paul-guo- @yuweisung.
