### ISSUE TITLE
LWLock panic when canceling a query in resource queue's waiting queue

### ISSUE THREAD

**Issue by dreamedcheng** [greenplum-db/gpdb#9649]
This panic is likely to happen when the value of statement_timeout is equal to or close to deadlock_timeout.

### Greenplum version or build
6X_STABLE Greenplum Database 6.4.0+dev.56.gcd87c8e build dev

### Expected behavior
NO PANIC

### Actual behavior
![image](https://user-images.githubusercontent.com/7367189/75603126-9373e980-5b06-11ea-9543-55690ae40d9d.png)

### Step to reproduce the behavior

set deadlock_timeout = 1min;
alter resource queue pg_default with (active_statements = 1);

session 1:
psql -d postgres -U test_user -p 6000 -h 127.0.0.1 -c "select pg_sleep(1000)" &

session 2:
psql -d postgres -U test_user -p 6000 -h 127.0.0.1

Use gdb attach to attach to the process of session 2, then set breakpoint at ResLockWaitCancel(after LWLockAcquire(partitionLock, LW_EXCLUSIVE); and before releasing it). 

Back to session 2, issue query 'select pg_sleep(100)', and then press ‘ctrl+c’. we can see gdb is breaking at  'ResLockWaitCancel', enter 'p sleep(60)', then we can see the panic.

**Comment by jimmyyih** [comment]
This is fixed with https://github.com/greenplum-db/gpdb/commit/cf25bc0f0609afeedddcee2c5c1731cef2d648a8.  Thanks again for reporting the issue and creating the initial patch.
