### ISSUE TITLE
Query waiting on resqueue lock doesn't trigger Deadlock check

### ISSUE THREAD

**Issue by dreamedcheng** [greenplum-db/gpdb#9651]
### Greenplum version or build
Latest master

### Expected behavior
Trigger deadlock check when deadlock timer timeout.

### Step to reproduce the behavior
alter resource queue pg_default with (active_statements=1);

session 1:
select pg_sleep(1000);

open session 2, and gdb attach to session2, and set a breakpoint on 'CheckDeadLock'.

session 2: 
select pg_sleep(100);

**Comment by gaos1** [comment]
what is your expectation here? your example is not a real deadlock. deadlock means two or multiple sessions hold resources waited by one another, and cannot move forward at all and will wait forever. 

in your example, session 1 can execute and session2 will be waken up once session 1 is done. 

it seems you want to resolve deadlock involving both resource queue waiting and database object waiting, which is not considered in resource queue or local deadlock detector yet. if you want to avoid it, you can use resource group.

**Comment by dreamedcheng** [comment]
> what is your expectation here? your example is not a real deadlock. deadlock means two or multiple sessions hold resources waited by one another, and cannot move forward at all and will wait forever.
> 
> in your example, session 1 can execute and session2 will be waken up once session 1 is done.
> 
> it seems you want to resolve deadlock involving both resource queue waiting and database object waiting, which is not considered in resource queue or local deadlock detector yet. if you want to avoid it, you can use resource group.

Here, I don't mean to create a deadlock cycle, but want to say that when someone is waiting on a regular lock, the deadlock check timer will be set on, and when it reaches timeout, a deadlock check will be triggered to see if there is a deadlock cycle.  However, on master branch, waiting on resqueue lock will not trigger the deadlock check now.

**Comment by asimrp** [comment]
@dreamedcheng what goes wrong when the deadlock check is not triggered by a backend that is waiting on a lock of type "resource queue"?

A deadlock cannot go undetected as long as at least one participant in the deadlock cycle is waiting on a regular lock (not of "resource queue" type).  If I'm making sense, possibility of a deadlock is ruled out, then what is the problem?

**Comment by dreamedcheng** [comment]
@asimrp Considering the following situation(if a resource queue has active_statements = 1):  
T1: truncate table t;
gdb: attach session T1 then b auto_stats
T1: insert into t values (1);
T2: begin;
T2: analyze t;
gdb : c
T2: select * from t;

Without the fix, T1 and T2 will wait for each other forever, I can still reproduce the problem with latest master branch.

You can see that T1 wait for `ShareUpdateExclusiveLock` on t which was held by T2, while T2 wait for resqueue lock held by T1.
![image](https://user-images.githubusercontent.com/7367189/100738284-524f9380-3410-11eb-9629-ae8465bb8a69.png)

**Comment by asimrp** [comment]
@wuj21 @wenwangBJ this is a reproducible deadlock, worth taking a fresh look at.

**Comment by dreamedcheng** [comment]
Since resource queue is still the default resource manager, I strongly recommend to give a look at it.

PS: The steps to reproduce had been given in regression case added by PR https://github.com/greenplum-db/gpdb/pull/9652.

Thanks.

**Comment by jimmyyih** [comment]
Fixed with commit https://github.com/greenplum-db/gpdb/commit/b57bf4a2a3da9d7dc0fb21c69aea074d22e5098a.
