### ISSUE TITLE
Inefficiency in pg_lock_status()

### ISSUE THREAD

**Issue by fangzheng** [greenplum-db/gpdb#9654]
### Greenplum version or build
master, 6X_STABLE

`pg_lock_status()` function has a loop that iterates over all rows of all result sets returned by segment DBs. (https://github.com/greenplum-db/gpdb/blob/master/src/backend/utils/adt/lockfuncs.c#L486). The loop is based on `mystatus->currIdx` which counts the number of rows processed by the function so far.

Inside the while loop, there is another loop (https://github.com/greenplum-db/gpdb/blob/master/src/backend/utils/adt/lockfuncs.c#L507) that computes, from the value of `mystatus->currIdx`, which row of which result set is being processed. 

It seems that this part of the code could be made more efficient by keeping the two indices, `whichsrow` and `whichresultset` in `mystatus`. This way, we can eliminate this inner loop that iterates over the `mystatus-> segresults` array.
 
If this issue is confirmed, I'm happy to submit a pull request. Thanks.

**Comment by pivotal-ning-yu** [comment]
Nice catch.  It makes sense to save `whichrow` in `mystatus`, please go ahead to open a PR, thanks.

**Comment by fangzheng** [comment]
Thanks for confirmation. Will submit a PR soon.

**Comment by fangzheng** [comment]
Please see PR: https://github.com/greenplum-db/gpdb/pull/9683

**Comment by kainwen** [comment]
Fixed by https://github.com/greenplum-db/gpdb/pull/9683
