### ISSUE TITLE
 Greenplum won't start with optimizer_cost_model=experimental

### ISSUE THREAD

**Issue by baileygm** [greenplum-db/gpdb#9659]
Greenplum version - 5.25.0 on Ubuntu 16.04

Greenplum won't start if optimizer_cost_model=experimental is added to postgresql.conf

```2020-03-02 12:57:09.347571 GMT,,,p108,th-142051520,,,,0,,,seg-1,,,,,"FATAL","22023","invalid value for parameter ""optimizer_cost_model"": ""experimental""",,,,,,,,"set_config_option","guc.c",5076,```

**Comment by danielgustafsson** [comment]
`experimental` is not a valid value for `optimizer_cost_model` in Greenplum 5.x, it was introduced in Greenplum 6.x. Valid values are `legacy` and `calibrated`.

**Comment by baileygm** [comment]
@danielgustafsson - Thanks for the quick reply but it's in the release notes for 5.25.0 as a new feature

```Greenplum Database 5.25.0 includes these new Beta features:

    GPORCA introduces a new costing model for bitmap indexes. The new model is designed to choose faster, bitmap nested loop joins instead of hash joins. The new costing model is implemented as a Beta feature, and it is used as a default only if you enable it by setting the configuration parameter:

    set optimizer_cost_model = experimental

    The optimizer_cost_model parameter is required only during the Beta test period for this cost model. After further testing and validation, the new cost model will be enabled by default.
```

**Comment by danielgustafsson** [comment]
Indeed, you are right, I was going off a slightly too old tree and missed that.

**Comment by danielgustafsson** [comment]
I had a look at this and have posted a fix in PR9663, it still wont allow you to use gpconfig due to the nature of the GUC in question but it can be manually added to postgresql.conf. Thanks for reporting!

**Comment by chrishajas** [comment]
> I had a look at this and have posted a fix in PR9663, it still wont allow you to use gpconfig due to the nature of the GUC in question but it can be manually added to postgresql.conf. Thanks for reporting!

It can also be set with gpconfig by passing in the `--skipvalidation` flag:
`gpconfig -c optimizer_cost_model -v experimental --skipvalidation`.

**Comment by danielgustafsson** [comment]
Oh right, I had forgotten about the `--skipvalidation` parameter, thanks @chrishajas

**Comment by chrishajas** [comment]
Fix merged in https://github.com/greenplum-db/gpdb/commit/8546f824926e19570a785f825742f69e4902b4da, thanks for the report!
