### ISSUE TITLE
gpinitsystem failed

### ISSUE THREAD

**Issue by zhangshengdong** [greenplum-db/gpdb#9677]
### Greenplum version or build
6.2.1
### OS version and uname -a
Linux arpmdw 3.10.0-862.3.3.el7.x86_64 

I  execute follow commad:
[gpadmin@arpmdw gpdata]$ gpinitsystem -c gpinitsystem_config -s arpsdw3

get folow error log:

-----------------------------------log--------------------------------------------
20200304:10:14:20:009095 gpinitsystem:arpmdw:gpadmin-[FATAL]:-Some primary/mirror segment pairs were found to be not in sync Script Exiting!
-----------------------------------log---------------------------------------------

initial system fail.how to solve thie problem?

**Comment by asimrp** [comment]
@zhangshengdong we need more information to diagnose your problem.  Is it possible to find out which primary/mirror pairs are not in sync?  Once the victim segments are known, the primary and mirror logs (`<datadir>/pg_log/*.csv`) can be inspected to find any clues.

**Comment by zhangshengdong** [comment]
this problem that i solved。

find the log file 
cat /home/gpadmin/gpAdminLogs/gpinitsystem_20200304.log

and get  some information as  follows。

-------------------------log info ---------------------------------
2020-03-04 03:10:25.714894 GMT,,,p11333,th-349497216,,,,0,,,seg-10000,,,,,"FATAL","XX000","could not create semaphores: 设备上没有空间 (pg_sema.c:126)","Failed system call was semget(5432031, 17, 03600).","This error does *not* mean that you have run out of disk space.  It occurs when either the system limit for the maximum number of semaphore sets (SEMMNI), or the system wide maximum number of semaphores (SEMMNS), would be exceeded.  You need to raise the respective kernel parameter.  Alternatively, reduce PostgreSQL's consumption of semaphores by reducing its max_connections parameter.
-----------------------log info-----------------------------------------

modify kernel parameters  as follows:

[gpadmin@arpmdw gpconfigs]$ cat /proc/sys/kernel/sem
250     32000   100     128

[root@arpmdw ~]# vi /etc/sysctl.conf
---
kernel.sem = 5010 641280 5010 128
---

[root@arpmdw ~]# sysctl -p
fs.aio-max-nr = 1048576
fs.file-max = 6815744
kernel.shmall = 2147483648
kernel.shmmax = 68719476736
kernel.shmmni = 4096
kernel.sem = 5010 641280 5010 128
net.ipv4.ip_local_port_range = 9000 65500
net.core.rmem_default = 262144
net.core.rmem_max = 4194304
net.core.wmem_default = 262144
net.core.wmem_max = 1048586

and this issue is closed.

thanks for your answer.
