### ISSUE TITLE
The documentation for the COPY FROM command does not contain the FORCE_NULL parameter

### ISSUE THREAD

**Issue by sergushenkov** [greenplum-db/gpdb#9682]
PostgreSQL 9.4.24 (Greenplum Database 6.3.0 build commit:77aa1b6e4486adbaede9f5f2864a04fc3a512e93) on x86_64-unknown-linux-gnu, compiled by gcc (GCC) 6.4.0, 64-bit compiled on Jan 13 2020 22:04:43

The documentation for the COPY FROM command (https://gpdb.docs.pivotal.io/6-3/ref_guide/sql_commands/COPY.html) does not contain the FORCE_NULL parameter. But really is this parameter.

COPY test.outfittransferinoffice_buff FROM STDIN WITH (
     FORMAT csv,
     NULL 'None',
     FORCE_NULL (transfer_id, office_id, employee_id, dt, shipping_id, ttn_id, date_dt)
);

A request with FORCE_NULL correctly processes the string: 
"461360151", "686", "62288", "2019-03-01 00:43:27", "None", "None", "2019-03-01"
The same request without FORCE_NULL crashes with an INFO error - invalid input syntax for integer: "None" CONTEXT: COPY outfittransferinoffice_buff, line 5, column shipping_id: "None"

p.s.
CREATE TABLE test.outfittransferinoffice_buff (
    transfer_id int NULL,
    office_id int NULL,
    employee_id int NULL,
    dt timestamp NULL,
    shipping_id int NULL,
    ttn_id int NULL, 
    date_dt date NULL
);

**Comment by adam8157** [comment]
@lisakowen I see this is always in `doc/src/sgml/ref/copy.sgml`, but not in our online document, is it an issue?

**Comment by lij55** [comment]
doc updated so closing this issue: https://gpdb.docs.pivotal.io/6-20/ref_guide/sql_commands/COPY.html
