### ISSUE TITLE
Greenplum6.1 init error

### ISSUE THREAD

**Issue by star-hou** [greenplum-db/gpdb#9767]
### Greenplum version or build
v6.1

After init greenplum cluster, i saw log on segment nodes, there are some FATAL log in dir pg_log.

The content in mirror/gpsegX/pg_log like that:
2020-03-16 15:08:04.157088 CST,"gpadmin","template1",p6423,th-397125504,"192.168.1.154","40008",2020-03-16 15:08:04 CST,0,,,seg2,,,,,"FATAL","57M02","the database system is in recovery mode","last replayed record at 0/C3CA610- VERSION: PostgreSQL 9.4.24 (Greenplum Database 6.1.0 build commit:6788ca8c13b2bd6e8976ccffea07313cbab30560) on x86_64-unknown-linux-gnu, compiled by gcc (GCC) 6.4.0, 64-bit compiled on Nov 1 2019 22:06:07",,,,,,0,,"postmaster.c",2578

The log flush one or two per minute.

**Comment by asimrp** [comment]
@usa1993 can you run queries against the Greenplum cluster by connecting to master node?

**Comment by usa1993** [comment]
> @usa1993 can you run queries against the Greenplum cluster by connecting to master node?

Yes, it works normally, but this log seems to have some problems

**Comment by usa1993** [comment]
I have another question：when I execute gprecoverseg -i，two mirror segment nodes down，i saw the pg_log on failed nodes，the content like that：“message type: PROBE received dbid:8 doesn't match this segments configured dbid:9”，what this mean？

**Comment by asimrp** [comment]
@gfphoenix78 recently looked into the FATAL messages.  During Greenplum startup, `gpstart` utility needs to determine whether a segment has successfully initiated the startup.  The libpq interface used for this, `PQping()` (`pg_ctl -w`), results in a connection being made to a segment while it is starting up.  If `PQping()` request reaches too early, the segment log file will contain those FATAL messages.  They are benign, feel free to ignore them.

When we merge the latest PostgreSQL version into Greenplum, this message will go away, see this PostgresSQL commit: https://github.com/postgres/postgres/commit/f13ea95f9e473a43ee4e1baeb94daaf83535d37c

Now regarding the `received dbid doesn't match this segments configured dbid` problem.  It suggests manual modifications being made to `gp_segment_configuration` catalog table, do you know the table was modified, @usa1993?

**Comment by usa1993** [comment]
> @gfphoenix78 recently looked into the FATAL messages. During Greenplum startup, `gpstart` utility needs to determine whether a segment has successfully initiated the startup. The libpq interface used for this, `PQping()` (`pg_ctl -w`), results in a connection being made to a segment while it is starting up. If `PQping()` request reaches too early, the segment log file will contain those FATAL messages. They are benign, feel free to ignore them.
> 
> When we merge the latest PostgreSQL version into Greenplum, this message will go away, see this PostgresSQL commit: [postgres/postgres@f13ea95](https://github.com/postgres/postgres/commit/f13ea95f9e473a43ee4e1baeb94daaf83535d37c)
> 
> Now regarding the `received dbid doesn't match this segments configured dbid` problem. It suggests manual modifications being made to `gp_segment_configuration` catalog table, do you know the table was modified, @usa1993?

Yes, I manually modify the value of the hostname column. After I initialize, some values in the hostname column are my complete machine domain names, some are similar to sdwN. And values  are similar to sdwN in the address column. Therefore, I manually change all the values in the hostname to my complete domain name of the machine. My complete machine domain names are like "XXX-segment-host-N"

**Comment by usa1993** [comment]
Today, I found that the logs on my segment node <dir pg_log> have the following contents:

gpdb-2020-03-23_000000.csv:2:2020-03-23 09:44:06.311123 CST,"gpadmin","template1",p53492,th-109320064,"192.168.1.125","41604",2020-03-23 09:44:06 CST,0,,,seg3,,,,sx1,"FATAL","57P03","connections to primary segments are not allowed","This database instance is running as a primary segment in a Greenplum cluster and does not permit direct connections.","To force a connection anyway (dangerous!), use utility mode.",,,,,0,,"postinit.c",1150,

Could you inquire about the cause of this log？I saw the source code for version 6.1，the place
is different from 5.19.

`else if ((Gp_session_role == GP_ROLE_DISPATCH) && !IS_QUERY_DISPATCHER())
{
ereport(FATAL,
(errcode(ERRCODE_CANNOT_CONNECT_NOW),
errmsg("connections to primary segments are not allowed"),
errdetail("This database instance is running as a primary segment in a Greenplum cluster and does not permit direct connections."),
errhint("To force a connection anyway (dangerous!), use utility mode.")));
}`
and 
`define IS_QUERY_DISPATCHER() (GpIdentity.segindex == MASTER_CONTENT_ID)`
and
`MASTER_CONTENT_ID = -1`

So I have some doubts about the logic here, hope to get your answer.

First of all, thank you for your help

**Comment by gfphoenix78** [comment]
> CST,"gpadmin","template1",p53492,th-109320064,"192.168.1.125","41604",2020-03-23 09:44:06 CST,0,,,seg3,,,,sx1,"FATAL","57P03","connections to primary segments are not allowed","This database instance is running as a primary segment in a Greenplum cluster and does not permit direct connections.","To force a connection anyway (dangerous!), use utility mode.",,,,,0,,"postinit.c",1150,

You are not allowed to connect to the primary directly. But you can connect to the primary in utility mode and you should know what it means.

**Comment by usa1993** [comment]
> > @gfphoenix78 recently looked into the FATAL messages. During Greenplum startup, `gpstart` utility needs to determine whether a segment has successfully initiated the startup. The libpq interface used for this, `PQping()` (`pg_ctl -w`), results in a connection being made to a segment while it is starting up. If `PQping()` request reaches too early, the segment log file will contain those FATAL messages. They are benign, feel free to ignore them.
> > When we merge the latest PostgreSQL version into Greenplum, this message will go away, see this PostgresSQL commit: [postgres/postgres@f13ea95](https://github.com/postgres/postgres/commit/f13ea95f9e473a43ee4e1baeb94daaf83535d37c)
> > Now regarding the `received dbid doesn't match this segments configured dbid` problem. It suggests manual modifications being made to `gp_segment_configuration` catalog table, do you know the table was modified, @usa1993?
> 
> Yes, I manually modify the value of the hostname column. After I initialize, some values in the hostname column are my complete machine domain names, some are similar to sdwN. And values are similar to sdwN in the address column. Therefore, I manually change all the values in the hostname to my complete domain name of the machine. My complete machine domain names are like "XXX-segment-host-N"

Is my operation make the trouble?

**Comment by usa1993** [comment]
> > CST,"gpadmin","template1",p53492,th-109320064,"192.168.1.125","41604",2020-03-23 09:44:06 CST,0,,,seg3,,,,sx1,"FATAL","57P03","connections to primary segments are not allowed","This database instance is running as a primary segment in a Greenplum cluster and does not permit direct connections.","To force a connection anyway (dangerous!), use utility mode.",,,,,0,,"postinit.c",1150,
> 
> You are not allowed to connect to the primary directly. But you can connect to the primary in utility mode and you should know what it means.

Yes, I know, but I really want to know how it is generated. My master node is down, so I made an manual HA and then i saw these logs.

**Comment by asimrp** [comment]
Did you try using `gpactivatestandby` to bring up standby when master went down?  Was it not sufficient?

**Comment by usa1993** [comment]
> Did you try using `gpactivatestandby` to bring up standby when master went down? Was it not sufficient?

Yes, I did this operation, but there are some new problems. Please see the link:[https://github.com/greenplum-db/gpdb/issues/9837](url)

I saw the source code of gpinitstandby. In version 6.1, we used the largest dbid plus 1 as the new standby dbid instead of reading a gp_dbid file in version 5.19. So when I recover my segment node，it seems that one segment node use the dbid which is used by original master node(dbid:1), and then it report a dbid not match error.Then I looked at the original code of gprecoverseg, and I saw this code `peerForFailedSegmentDbId = peerForFailedSegment.getSegmentDbId()`. In the code,the variable ‘peerForFailedSegmentDbId’ is not used. And I think this variable maybe used for record failed segment dbid.
All of the above are my personal opinions. I don't know if they are correct. Can you help me to see the causes of this problem: `PROBE received dbid:4 doesn't match this segments configured dbid:5`
