### ISSUE TITLE
oracle_fdw cannot compile with GPDB 6

### ISSUE THREAD

**Issue by gaos1** [greenplum-db/gpdb#9805]
### Greenplum version or build
6.1
### Expected behavior
Oracle_fdw can work with Greenplum 6

### Actual behavior
```
oracle_fdw.c: In function ‘oracleGetForeignRelSize’:
oracle_fdw.c:893:3: error: too few arguments to function ‘clauselist_selectivity’
ntuples = ntuples * clauselist_selectivity(root, baserel->baserestrictinfo, 0, JOIN_INNER, NULL);
^
In file included from oracle_fdw.c:47:0:
/usr/local/greenplum-db-6.1.0/include/postgresql/server/optimizer/cost.h:225:20: note: declared here
extern Selectivity clauselist_selectivity(PlannerInfo *root,
^
oracle_fdw.c: In function ‘oracleIterateForeignScan’:
oracle_fdw.c:1480:31: error: ‘TupleTableSlot’ has no member named ‘tts_values’
convertTuple(fdw_state, slot->tts_values, slot->tts_isnull, false);
^
oracle_fdw.c:1480:49: error: ‘TupleTableSlot’ has no member named ‘tts_isnull’
convertTuple(fdw_state, slot->tts_values, slot->tts_isnull, false);
^
oracle_fdw.c: In function ‘oracleExecForeignInsert’:
oracle_fdw.c:2038:30: error: ‘TupleTableSlot’ has no member named ‘tts_values’
convertTuple(fdw_state, slot->tts_values, slot->tts_isnull, false);
^
oracle_fdw.c:2038:48: error: ‘TupleTableSlot’ has no member named ‘tts_isnull’
convertTuple(fdw_state, slot->tts_values, slot->tts_isnull, false);
^
oracle_fdw.c: In function ‘oracleExecForeignUpdate’:
oracle_fdw.c:2084:30: error: ‘TupleTableSlot’ has no member named ‘tts_values’
convertTuple(fdw_state, slot->tts_values, slot->tts_isnull, false);
^
oracle_fdw.c:2084:48: error: ‘TupleTableSlot’ has no member named ‘tts_isnull’
convertTuple(fdw_state, slot->tts_values, slot->tts_isnull, false);
^
oracle_fdw.c: In function ‘oracleExecForeignDelete’:
oracle_fdw.c:2130:30: error: ‘TupleTableSlot’ has no member named ‘tts_values’
convertTuple(fdw_state, slot->tts_values, slot->tts_isnull, false);
^
oracle_fdw.c:2130:48: error: ‘TupleTableSlot’ has no member named ‘tts_isnull’
convertTuple(fdw_state, slot->tts_values, slot->tts_isnull, false);
^
make: *** [oracle_fdw.o] Error 1
```

### Step to reproduce the behavior
```
git@github.com:laurenz/oracle_fdw.git
cd oracle_fdw
make
```
an old issue was opened to oracle_fdw project but closed with conclusion that Greenplum FDW internal API is not compatible with it. 
https://github.com/laurenz/oracle_fdw/issues/354

**Comment by adam8157** [comment]
I had a patch for this, could you please take a try?

[0001-Be-compatible-with-Greenplum-6X.patch.txt](https://github.com/greenplum-db/gpdb/files/4373425/0001-Be-compatible-with-Greenplum-6X.patch.txt)

I'm thinking of maintaining a sanity patched version https://github.com/adam8157/oracle_fdw_greenplum

**Comment by Eulerizeit** [comment]
I think we need to figure out what our expectations for an FDW are and then
test to make sure we meet those expectations. Currently I'm not sure how an
FDW would just work on Greenplum. I would imagine that it would just work
on master but then the data that is retrieved from the foreign server would
need to be distributed to the segments to be worked on.

Is there a generally understood flow we are expecting?

-- Rob

**Comment by adam8157** [comment]
Yes, by default the FDW only executes on the master node, our planner takes the locus as `CdbLocusType_Entry`.

ref: #5413

**Comment by gaos1** [comment]
Thx. it can compiled and installed.
