### ISSUE TITLE
ALTER DATABASE SET FROM CURRENT fails

### ISSUE THREAD

**Issue by reductionista** [greenplum-db/gpdb#9823]
### Greenplum version or build

PostgreSQL 9.4.24 (Greenplum Database 6.5.0 build commit:27520b0e901cefe748684c02e5155fb015cd5cc2) on x86_64-unknown-linux-gnu, c
ompiled by gcc (GCC) 6.4.0, 64-bit compiled on Mar 18 2020 23:07:19

### OS version and uname -a

CentOS release 6.10 (Final)

Linux 2.6.32-754.6.3.el6.x86_64 #1 SMP Tue Oct 9 17:27:49 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

### Expected behavior

Should set GUC at database level from current setting, as the help says:
\h ALTER DATABASE
ALTER DATABASE name SET configuration_parameter FROM CURRENT

### Actual behavior / steps to reproduce

It works if you explicitly set the GUC to a string.  Just can't set it from the current setting.
```
dl_perf# ALTER DATABASE dl_perf SET search_path = 'public';
ALTER DATABASE

dl_perf# \c
You are now connected to database "dl_perf" as user "gpadmin"

dl_perf# show search_path
 search_path
-------------
 public
(1 row)

dl_perf=# alter database dl_perf SET search_path FROM CURRENT;
ERROR:  syntax error at end of input  (seg0 10.XX.XX.XX:40000 pid=6831)
```

Same behavior for any GUC, not specific to `search_path`

**Comment by xiong-gang** [comment]
The information is not dispatched correctly, @gaos1 please add a story to fix this?
