### ISSUE TITLE
ERROR:  permission denied for sequence

### ISSUE THREAD

**Issue by l-wang** [greenplum-db/gpdb#9852]
### Greenplum version or build
All versions of Greenplum

### Expected behavior
Insert succeeding

### Actual behavior
Insert fails with the following ERROR:
ERROR:  permission denied for sequence

### Step to reproduce the behavior
```sql
CREATE USER regress_identity_user1;
CREATE TABLE itest8 (a serial, b text);
GRANT SELECT, INSERT ON itest8 TO regress_identity_user1;
SET ROLE regress_identity_user1;
INSERT INTO itest8 DEFAULT VALUES;
```

Context: this is exposed as part of upstream Postgres 12 merge. The repro comes from the new tests `identity` in upstream Postgres.

The function we are failing at is `nextval_internal()`, we have been always passing check_permissions as true from `nextval_qd()`.

**Comment by l-wang** [comment]
We fixed the problem in the merge branch, and decided to not fix it for stable versions for now. If we want to fix it in the future, we would need to pass a check_permissions argument to nextval_internal(), which is introduced in upstream postgres commit 3217327, and set the check_permissions to false in the caller nextval_qd().

**Comment by adam8157** [comment]
Closing based on the comment.
