### ISSUE TITLE
oracle_fdw error

### ISSUE THREAD

**Issue by Rumyuqiang** [greenplum-db/gpdb#9854]
### CENTOS 7.5

Dear sir,

I'm creating the oracle fdw after I droping my old oracle_fdw, I get the errors below:

postgres=# create extension oracle_fdw;
ERROR:  query plan with multiple segworker groups is not supported
HINT:  likely caused by a function that reads or modifies data in a distributed table

anyone who can help me? thank you!

**Comment by gaos1** [comment]
are you using this version, right?  https://github.com/adam8157/oracle_fdw_greenplum
cc @adam8157

**Comment by Rumyuqiang** [comment]
yes，it is！

**Comment by adam8157** [comment]
What if `set optimizer=off; create extension oracle_fdw;`?

**Comment by LittleWuCoding** [comment]
I got same ERROR when installing pljava.
```
postgres=# set optimizer=off;
SET
postgres=# create extension pljava;
ERROR:  query plan with multiple segworker groups is not supported
HINT:  likely caused by a function that reads or modifies data in a distributed table
postgres=# show optimizer;
 optimizer 
-----------
 off
(1 row)

postgres=# set optimizer=on;
SET
postgres=# create extension pljava;
ERROR:  query plan with multiple segworker groups is not supported
HINT:  likely caused by a function that reads or modifies data in a distributed table

```
@adam8157 set optimizer does not works~
Is there any solution to this issue?

**Comment by adam8157** [comment]
Have you installed the extension on every segment?

**Comment by adam8157** [comment]
It's probably because the Oracle library is not installed on every segment host.

The error "query plan with multiple segworker groups is not supported" is an issue of Greenplum error handling, it doesn't mean what it says...

Checkout the `oracle_fdw--1.2.sql` for example, run every query (replace MODULE_PATHNAME with oracle_fdw.so), then you should see the actual error.

**Comment by adam8157** [comment]
RCA: https://github.com/greenplum-db/gpdb/issues/10241

**Comment by adam8157** [comment]
RCA: https://github.com/greenplum-db/gpdb/issues/10241

**Comment by kainwen** [comment]
Fixed by https://github.com/greenplum-db/gpdb/commit/58628039c5369a520fc65adb87f0d29fd1203fd7 in master
and in 6x https://github.com/greenplum-db/gpdb/commit/4d185c05c8406cd38659a3aee952150c4cecb2b2
