### ISSUE TITLE
compressed data is corrupt error

### ISSUE THREAD

**Issue by lambgong** [greenplum-db/gpdb#9858]
### Greenplum version or build
5.23.0

### OS version and uname -a
centos 7.2

### autoconf options used ( config.status --config )
./config.status --config
'--with-perl' '--with-python' '--with-tcl' '--with-libxml' '--with-gssapi' '--with-openssl' '--enable-gpperfmon' '--enable-pxf' '--prefix=/home/gpadmincloud/install-5.23.0-1.0.0'

### Step to reproduce the behavior
table schema are as enclosed files : table_schema.txt

for query like this:
select count(distinct "account_id") from "insigths_age_gender" where "date_start" >= '2020-01-01' and "date_start" <= '2020-01-31' and "account_id" in ('1000284533662717') and "adset_id" in ('23844189311780154') group by "date_start"

will encountered an error at master:
2020-03-27 14:23:51.713349 CST,"cheetahgo_read","postgres",p6546,th-1328015296,"103.69.155.92","32491",2020
-03-27 14:23:49 CST,0,con3254488,cmd5,seg-1,,dx18254839,,sx1,"ERROR","XX000","compressed data is corrupt (pg_lzcompress.c:737)  (seg2 slice1 10.0.5.2:40002 pid=481) (cdbdisp.c:254)",,,,,,"select count(distinct ""account_id"") from ""insigths_age_gender"" where ""date_start"" >= '2020-01-01' and ""date_start"" <= '2020-01-31' and ""account_id"" in ('1000284533662717') and ""adset_id"" in ('23844189311780154') group by ""date_start""",0,,"cdbdisp.c",254,"Stack trace:
1    0x931056 postgres errstart + 0x1f6
2    0x9b378c postgres cdbdisp_finishCommand + 0x1ac
3    0x9b3982 postgres CdbDispatchHandleError + 0x172
4    0x69b3bb postgres mppExecutorCleanup + 0x6b
5    0x6848dd postgres ExecutorRun + 0x1ad
6    0x81c312 postgres <symbol not found> + 0x81c312
7    0x81dd41 postgres PortalRun + 0x191
8    0x817121 postgres <symbol not found> + 0x817121
9    0x81a172 postgres PostgresMain + 0xb12
10   0x7be336 postgres <symbol not found> + 0x7be336
11   0x7bfd22 postgres PostmasterMain + 0xc62
12   0x4cae4d postgres main + 0x39d
13   0x7f88acfcbb35 libc.so.6 __libc_start_main + 0xf5
14   0x4cb441 postgres <symbol not found> + 0x4cb441

on the segment, the error as follow:
1    0x931056 postgres errstart + 0x1f6
2    0x932b2b postgres elog_finish + 0xab
3    0x896a0b postgres <symbol not found> + 0x896a0b
4    0x4faf3d postgres varattrib_untoast_ptr_len + 0xcd
5    0xa006a4 postgres cdbhash + 0x714
6    0x6b80b8 postgres ExecMotion + 0x108
7    0x687201 postgres ExecProcNode + 0x4e1
8    0x684352 postgres <symbol not found> + 0x684352
9    0x684a2a postgres ExecutorRun + 0x2fa
10   0x81c312 postgres <symbol not found> + 0x81c312
11   0x81dd41 postgres PortalRun + 0x191
12   0x816315 postgres <symbol not found> + 0x816315
13   0x81b8a6 postgres PostgresMain + 0x2246
14   0x7be336 postgres <symbol not found> + 0x7be336
15   0x7bfd22 postgres PostmasterMain + 0xc62
16   0x4cae4d postgres main + 0x39d
17   0x7f5ee3057b35 libc.so.6 __libc_start_main + 0xf5
18   0x4cb441 postgres <symbol not found> + 0x4cb441

This error happen once in a while, you can't reproduce it.

[table_schema.txt](https://github.com/greenplum-db/gpdb/files/4414930/table_schema.txt)

**Comment by gaos1** [comment]
do you have mirror? can you failover to mirror and see if mirror is OK? is mirror data file md5 same or different from primary?

**Comment by adam8157** [comment]
Closing since we have no repro, it might be a real corruption.

Feel free to reopen with a repro or more info (the answers to these mirror questions could help to judge if it's a real disk corruption).
