### ISSUE TITLE
pg_statio views don't support external / appendoptimized tables

### ISSUE THREAD

**Issue by gaos1** [greenplum-db/gpdb#9861]
### Greenplum version or build
master 

### Actual behavior
As reported in https://groups.google.com/a/greenplum.org/forum/#!msg/gpdb-users/ncoUTMjbPKY/y-pjjvvRAwAJ, some of our system view pg_statio_* like pg_catalog.pg_statio_all_tables don't support external / appendoptimized tables.

We could also check all other pg_statio views:
pg_statio_all_indexes    
pg_statio_all_tables     
pg_statio_sys_sequences  
pg_statio_user_indexes   
pg_statio_user_tables
pg_statio_all_sequences  
pg_statio_sys_indexes    
pg_statio_sys_tables     
pg_statio_user_sequences

for pg_stat_* views, we actually don't gather them from segments and this PR will fix it. we can check if pg_statio views have similar problems. 
https://github.com/greenplum-db/gpdb/pull/9565

**Comment by lij55** [comment]
PR merged so closing this issue.
