### ISSUE TITLE
the relation between gp_vmem_protect_limit and postgres VIRT

### ISSUE THREAD

**Issue by GuoLiuFang** [greenplum-db/gpdb#987]
my cluster have 8 hosts include 1 active master , 1 standby master and 6 segment hosts.
Every segment host have 16 cores, so I have 8 primary segment on each segment host.
my gp_vmem_protect_limit = 8192MB
but why /usr/local/greenplum-db-4.3.8.1/bin/postgres VIRT only have 455m???
![Markdown](http://i4.piimg.com/1949/32787de47b463449.png)
this is the top command
![Markdown](http://i4.piimg.com/1949/c4113d9021153a20.png)

how can the /usr/local/greenplum-db-4.3.8.1/bin/postgres process access the virtual size to 8192MB?
any response is welcome.

**Comment by GuoLiuFang** [comment]
@bmomjian @tglsfdc @petere @scrappy

**Comment by eurekaka** [comment]
gp_vmem_protect_limit is the "virtual memory limit (in MB) of Greenplum memory protection", you can run complicated query to increase the VIRT of the postgres, once gp_vmem_protect_limit is hit, the query is expected to be canceled by reporting ERROR.

**Comment by GuoLiuFang** [comment]
@eurekaka . I have run a insert into query . and I get a error.. 
**ERROR:  Canceling query because of high VMEM usage. Used: 7375MB, available 814MB, red zone: 7372MB (runaway_cleaner.c:135)  (seg1 slice1 NY-GREENPLUM-12-13:40001 pid=30430) (cdbdisp.c:1326)**
But the VIRT of the postgres is still 455m...

**Comment by eurekaka** [comment]
Could you please check to make sure it is the working QD/QE postgres process who consumes 455m? because there are many "postgres" processes, for example, Postmaster is also a "postgres" process, and it is very stable in memory consumption because it does no substantial works.

Postmasters are like:
![687474703a2f2f69342e7069696d672e636f6d2f313934392f633431313364393032313135336132302e706e67](https://cloud.githubusercontent.com/assets/6261973/17169391/d98f56b8-5419-11e6-8495-d46a7f5479c2.png)

QD/QE processes are like:
![687474703a2f2f69342e7069696d672e636f6d2f313934392f633431313364393032313135336132302e706e67 1](https://cloud.githubusercontent.com/assets/6261973/17169451/130a2f94-541a-11e6-8e42-6c4ab54d068c.png)

**Comment by GuoLiuFang** [comment]
@eurekaka You are right. this is when I run a big job. the top comman show
![Markdown](http://i4.piimg.com/1949/838245d8bcac7abds.png)

about this ,I have two more question . First , when I run a small job. the VIRT RES is still LOW, It seems that consume memory only when I run big job. In result, My small query is very slow, take a lot of time ..Second , Why this postgres process always have a lowest cpu priority. this is led to like this 
![Markdown](http://i2.piimg.com/1949/8df4abe5d6a5efa9s.png)
when I run a job , my cpu nice time is very high. I think it is abnormal. How can I solve this two problems.

**Comment by eurekaka** [comment]
Hi,

1) What kind of "small job" you are running? how long will it take? Is there any concurrency? How is resource queue configured in the system?
2) In normal cases, high CPU utilization processes are supposed to have high nice value, thus other important processes will easily get CPU time if they need. From your graph, high CPU nice time means the CPU is mostly used by processes with high nice value, here the QD/QE processes. IMHO, I don't see any abnormality here.

**Comment by GuoLiuFang** [comment]
this is my sql `select tag,loader_version_short,province_id,operator_id, count(current_uuid), count(distinct current_uuid) from smart_v9_production.request_histories where record_time between '2016-06-13 00:00:00' and '2016-06-26 02:59:59' group by tag,loader_version_short,province_id,operator_id;`  about 103,178,367 records. It take about 117s. There is no concurrency.. this is my resource queue configuration and some server parameters.
![Markdown](http://i4.piimg.com/1949/794e3a28766cab05s.png)
![Markdown](http://i4.piimg.com/1949/ba2423ed90980597s.png)
My RAM=64G SWAP=20G master and standby master 24cpu cores; segment host 16cpu cores.
this is when I execute the "small job" one of the segment hosts show
![Markdown](http://i4.piimg.com/1949/cab6e95405259ba4s.png)
What I want to know is that why the memory usage is so low. and why the query takes so long. I have test this "small job" on InfiniDB which base on mysql MPP structure database system. It only take 17s... But when I look at the memory usage about 40G is used.. So I wonder to know how to speed up "small job query". The green highlight resource queue "Executive" is what I used to execute the small query. How can I speed up my query?Is there some thing I configured improperly? Thanks ahead.

**Comment by eurekaka** [comment]
Could you please paste the plan of your query? (since I am not sure of the data distribution of your table, so I cannot generate the plan locally). The statment_mem is configured to be 1GB, so each query can consume at most 1GB, that is to say, all the working processes for this query can consume additional(compared with idle state IIRC) 1GB on the fly in total. You can refer to the administration guide for a proper parameter for your system. http://gpdb.docs.pivotal.io/4380/admin_guide/admin_guide.html

**Comment by GuoLiuFang** [comment]
this is my Query Plan 
![Markdown](http://i1.piimg.com/1949/3d874fc8e4405742s.png)

> The statment_mem is configured to be 1GB, so each query can consume at most 1GB, that is to say, all the working processes for this query can consume additional(compared with idle state IIRC) 1GB on the fly in total.
Does it mean statment_mem per host . In other way, the total memory It consume is not 6*1G???(I have 6 segment host). And There is the question, How can I use as much memory as the whole cluster have ? I want this query execute as fast as it can.

**Comment by eurekaka** [comment]
* statment_mem is per host;
* the planner chooses group aggregate operator for aggregation, this explains the low memory consumption; if you want the query to be faster, you should check your data distribution and aggregation key and some GUCs such as enable_hashagg to make sure planner chooses hash strategy for aggregation, which would consume more memory respectively.

Also, GUCs such statement_mem, max_statment_mem should be adjusted as well I think.

**Comment by GuoLiuFang** [comment]
- enable_hashagg is on

- There is no concurrence, only me .use the Executive resource Queue.

- statement_mem is set to 2048MB, max_statment_mem is set to 8192MB.
I don't know why still Memory wanted 4G...this is the explain analyse for the query.
![Markdown](http://i4.piimg.com/1949/ab571959b9559951s.png)

**Comment by ascherbaum-pivotal** [comment]
Is this still an issue?

By the way, @GuoLiuFang, all the people you mentioned initially are members of the PostgreSQL project. But they almost certainly don't know the Greenplum memory management details.

**Comment by liruto** [comment]
After redistribution on _‘request_histories’_ and _‘current_uuid’_ columns, it occurs seriously data skew.  Disable optimization on distinct-qualified aggregates by _'set gp_enable_agg_distinct_pruning = off'_ and try again, can it help?

**Comment by Eulerizeit** [comment]
@GuoLiuFang given the age of this issue and the lack of response I'm going to close it. If you're still having issue please reopen.
