### ISSUE TITLE
When parallelizing plan tree, not transform ForeignScan make the result incorrect

### ISSUE THREAD

**Issue by haitaoy** [greenplum-db/gpdb#9872]
### Greenplum version or build
6X_STABLE

### Expected behavior
Transform the ForeignScan node to  Result-Material-Broadcast-ForeignScan.

### Actual behavior
https://github.com/greenplum-db/gpdb/blob/15fa2143015d14344cf36b6b52c9dfd3e8ff6db0/src/backend/cdb/cdbllize.c#L452-L454
Here, the ForeignScan may need to be added, otherwise when scanning the foreign table implemented via FDW，if FDW generates a distributed plan and one QE only scans parts of the table data, the final result would be incorrect as lacking of Broadcast node.
![image](https://user-images.githubusercontent.com/7891389/78338903-2e5c5980-75c6-11ea-83ef-ada9d2d8f024.png)

### Step to reproduce the behavior
This may need to implement one FDW foreign table, so...

**Comment by fanfuxiaoran** [comment]
What kind of fdw extension did you use?

**Comment by lij55** [comment]
Hi @haitaoy ,

could you please give more details about how to reproduce the issue with sql script? thanks!

**Comment by lij55** [comment]
closing this issue as no more information for long time.
