### ISSUE TITLE
psql \dm cannot find my materialized views, however `\d` lists them

### ISSUE THREAD

**Issue by mkiyama** [greenplum-db/gpdb#9876]
This issue was found when using Greenplum Database 6.4.0

See this thread
https://groups.google.com/a/greenplum.org/forum/#!topic/gpdb-users/pc0hjDCJuV4

**Comment by baobao0206** [comment]
This issue has been fixed by pr https://github.com/greenplum-db/gpdb/pull/10181 in gpdb6 and https://github.com/greenplum-db/gpdb/pull/10163 in master
