### ISSUE TITLE
gptransfer will transfer same-prefix tables with -f option

### ISSUE THREAD

**Issue by uglthinx** [greenplum-db/gpdb#9893]
### Greenplum version or build
GP5
### OS version and uname -a
centos7
### Step to reproduce the behavior
I executed gptransfer in two instance,  an error occurred during the process that caused some table transfers to fail, and the failed_transfer_tables_xxxx_xxxx.txt be generated. 
I viewed this file that show two tables "student" and "school" transmission failed, so I try to execute 

`gptransfer -f  failed_transfer_tables_xxxx_xxxx.txt -x --truncate --analyze \
--source-host=$masterHost --source-port=$masterPort --source-user=$sourceUser \
--source-map-file=/home/$sourceUser/gpconfigs/mapfile_gptransfer \
--dest-host=$destMasterHost --dest-port=$destMasterPort --dest-user=$destUser`

In the gptransfer log, I found that the tables with the same prefix "student_01" and "school_01" were retransmitted, but the two tables have been successfully transferred before. So I check the gptransfer code and find the function "_get_source_tables" , which to get tables from source instance, the relevant code is as follows:

`                        if (re.match(r'%s' % db_, database, re.L|re.U) and
                            re.match(r'%s' % schema_, schema, re.L|re.U) and
                            re.match(r'%s' % table_, table, re.L|re.U)):
                                if user_table not in seen:
                                    seen.add(user_table)
                                    source_tables.append(user_table)`

I change this code to

`if db_ == database and \
                            schema_ == schema and \
                            table_ == table :
                                if user_table not in seen:
                                    print "after match, table %s will be transferred." %(table)
                                    seen.add(user_table)
                                    source_tables.append(user_table)`

and the two tables "student_01" and "school_01" will not be retransmitted.

So I am curious why regular matching is used instead of "==". If this part of the code is modified, will it cause other bugs?

**Comment by lij55** [comment]
Hi @uglthinx ,

gptransfer is deprecated and could you try gpcopy?
