### ISSUE TITLE
Assertion failure: `"!(hashtable->nbuckets > spill_set->num_spill_files)"`

### ISSUE THREAD

**Issue by soumyadeep2007** [greenplum-db/gpdb#9902]
w/ @d 

### Greenplum version or build
master

### Expected behavior
The assertion failure does not occur.
### Actual behavior
```
psql:/tmp/denis_repro.sql:17: WARNING:  Any temporary tables for this session have been dropped because the gang was disconnected (session id = 40)
psql:/tmp/denis_repro.sql:17: ERROR:  Unexpected internal error (execHHashagg.c:1355)  (seg0 slice2 127.0.0.1:7002 pid=56035) (execHHashagg.c:1355)
DETAIL:  FailedAssertion("!(hashtable->nbuckets > spill_set->num_spill_files)", File: "execHHashagg.c", Line: 1355)
```

### Step to reproduce the behavior
```
CREATE TEMP TABLE foo(a int2, b xid, c char(4096) default 'hello');
INSERT INTO foo SELECT i, i::text::xid FROM generate_series(1, 4096) i;

ANALYZE foo;

SELECT $$
SELECT sum(a) FILTER (WHERE false)
FROM foo, generate_series(1, 2) bar(x)
GROUP BY b, c
$$ AS qry \gset

SET statement_mem = '2MB';

EXPLAIN VERBOSE
:qry;

EXPLAIN (COSTS OFF, ANALYZE, VERBOSE) :qry;
```

**Comment by soumyadeep2007** [comment]
We see the same failure on 6X as well with a slightly different repro:

```sql
CREATE TEMP TABLE foo (a int8, b int, c char(32768) DEFAULT 's');
INSERT INTO foo SELECT i, (i | 7) FROM generate_series(1, 1024) i;
ANALYZE foo;
SELECT $$
SELECT sum(a) FILTER (WHERE false), max(c)
FROM foo
GROUP BY b
$$ AS qry \gset
SELECT count(DISTINCT b) FROM foo;
EXPLAIN VERBOSE
:qry ;
SET statement_mem='1984kB';
/* EXPLAIN (COSTS OFF, ANALYZE) */
:qry ;
```

**Comment by soumyadeep2007** [comment]
The fix for this issue should be the same for 6X and master.

**Comment by d** [comment]
@soumyadeep2007 and I have a hunch that this assertion is wrong, as in, the number of buckets can be larger than, equal to, _and_ less than the number of branches (spill files)

**Comment by hlinnaka** [comment]
I dug into the old pre-opensourcing git repository for the history of this. Interestingly, this was fixed back in 2012:
```
commit b8409467fa4dfbabc18f0f7001cd9b15843cf28d
Date:   Tue May 15 07:54:39 2012 -0800

    Fixed wrong assert in HashAgg on nbuckets > nbatches. It is legal to have nbuckets == nbatches
    
    [JIRA: MPP-17036]
    
    [git-p4: depot-paths = "//cdb2/main/": change = 122737]

diff --git a/cdb-pg/src/backend/executor/execHHashagg.c b/cdb-pg/src/backend/executor/execHHashagg.c
index 7413117e0c..774907ffbd 100644
--- a/cdb-pg/src/backend/executor/execHHashagg.c
+++ b/cdb-pg/src/backend/executor/execHHashagg.c
@@ -1185,7 +1185,7 @@ spill_hash_table(AggState *aggstate)
 	/* Book keeping. */
 	hashtable->is_spilling = true;
 
-	Assert(hashtable->nbuckets > spill_set->num_spill_files);
+	Assert(hashtable->nbuckets >= spill_set->num_spill_files);
 
 	/*
 	 * Write each spill file. Write the last spill file first, since it will
```

But it got reverted some time later:
```
commit 842e04c7cee696c305b5df8a04270ea1e7142ce6
Date:   Thu Dec 20 22:52:04 2012 -0800

    This is a revert of //cdb2/main to branch point of 4.2.x (CL 100327)
    
    Eng team has decided to revert main to @100327 and then integrate changes
    from 4.2.x into main, in order to preserve linear history. The changes in
    main since 100327 are preserved in the history and if those changes are needed
    they need to be force integrated into feature branches and then integrated
    back to main.
    
    [git-p4: depot-paths = "//cdb2/main/": change = 147157]
```
The revert was a massive > 100000 million line diff. Looks like there was major confusion with the branch management, and this baby went with the bathwater.

The fix author wrote this analysis in the comments of MPP-17036:

> The assert that fails is wrong. 
> 
> The nbatches (which is equal to spill_set->num_spill_files) and nbuckets are set in execHHashAgg::calcHashAggTableSizes().
>
>    nbatches is always set to gp_hashagg_default_nbatches (which is usually set to 32 through a GUC)
>
>    nbuckets is first computed using entrysize and memquota, but if the computed value is too small, it is also set to gp_hashagg_default_batches
>
> Therefore, it is valid to have nbatches == nbuckets. 
>
> Also, the code in spill_hash_table works correctly for the case where nbatches == nbuckets. 
> 
> The fix is to change the assert from
>     Assert(hashtable->nbuckets > spill_set->num_spill_files);
> to
>     Assert(hashtable->nbuckets >= spill_set->num_spill_files);
>
> Fixed assertion in main. 

I haven't looked at the code in detail, but that analysis seems reasonable. I think we should make that change.

**Comment by hlinnaka** [comment]
> @soumyadeep2007 and I have a hunch that this assertion is wrong, as in, the number of buckets can be larger than, equal to, _and_ less than the number of branches (spill files)

Per that analysis on MPP-17036, I believe it cannot be less than at the moment, because calcHashAggTableSizes() does this:
```
	/*
	 * Always set nbuckets greater than gp_hashagg_default_nbatches since
	 * the spilling relies on this fact to choose which files to spill
	 * groups to.
	 * Note: gp_hashagg_default_nbatches must be a power of two
	 */
	nbuckets = Max(nbuckets, gp_hashagg_default_nbatches);
	buckets_mem = nbuckets * OVERHEAD_PER_BUCKET;
```
I'm not too familiar with the code, so I cannot verify if that comment is accurate. Or would everything actually work fine if nbuckets was smaller?

I think the best solution here is to trust the original analysis and those comments, and apply the original fix to change the assertion to `>=`.

**Comment by hlinnaka** [comment]
`calcHahAggTableSizes()` ensures that nbuckets is at least `gp_hashagg_default_nbatches`. And code elsewhere ensures that `num_spill_files` is never larger than `gp_hashagg_default_nbatches`. That's a bit more difficult to see, but I think that's true. `num_spill_files` is set in `createSpillSet()`, and the only caller to `createSpillSet()` passes `hashtable->hats.nbatches` as the argument. And all the places that set `hashtable->hats.nbatches` cap the value at `gp_hashagg_default_nbatches`.

That is, until someone decides to change gp_hashagg_default_nbatches on the fly, while the agg is running.... You could do that with a user-defined function in the query.

The long term plan is to replace this code with the hashagg spilling code from PostgreSQL v13. So I'd rather not do any big changes to this just for the backbranches.

**Comment by soumyadeep2007** [comment]
Yup, that is exactly what we had found. See: https://github.com/soumyadeep2007/gpdb/commit/5cfbf8160456fce889bae5ab1e586a96079610e2

**Comment by lij55** [comment]
it seems work on master and orca will rollback to postgres planner:

```sql
test=# EXPLAIN (COSTS OFF, ANALYZE, VERBOSE) :qry;
                                                            QUERY PLAN                                                             
-----------------------------------------------------------------------------------------------------------------------------------
 Gather Motion 2:1  (slice1; segments: 2) (actual time=403.162..786.337 rows=4096 loops=1)
   Output: (sum(foo.a) FILTER (WHERE false)), foo.b, foo.c
   ->  HashAggregate (actual time=402.962..688.692 rows=4096 loops=1)
         Output: sum(foo.a) FILTER (WHERE false), foo.b, foo.c
         Group Key: foo.b, foo.c
         Peak Memory Usage: 0 kB
         work_mem: 752kB  Segments: 2  Max: 712kB (segment 1)  Workfile: (1 spilling)
         ->  Redistribute Motion 2:2  (slice2; segments: 2) (actual time=0.574..245.232 rows=24576 loops=1)
               Output: foo.b, foo.c, foo.a
               Hash Key: foo.c
               ->  Nested Loop (actual time=0.074..41.953 rows=12468 loops=1)
                     Output: foo.b, foo.c, foo.a
                     ->  Function Scan on pg_catalog.generate_series bar (actual time=0.010..0.012 rows=2 loops=1)
                           Output: bar.x
                           Function Call: generate_series(1, 2)
                           work_mem: 33kB  Segments: 2  Max: 17kB (segment 0)
                     ->  Materialize (actual time=0.028..19.622 rows=6234 loops=2)
                           Output: foo.a, foo.b, foo.c
                           work_mem: 1171kB  Segments: 2  Max: 586kB (segment 0)  Workfile: (2 spilling)
                           Work_mem wanted: 49265K bytes avg, 49986K bytes max (seg1) to lessen workfile I/O affecting 2 workers.
                           ->  Seq Scan on pg_temp_290.foo (actual time=0.031..8.318 rows=6234 loops=1)
                                 Output: foo.a, foo.b, foo.c
 Planning Time: 0.932 ms
   (slice0)    Executor memory: 57K bytes.
   (slice1)    Executor memory: 387K bytes avg x 2 workers, 746K bytes max (seg1).  Work_mem: 712K bytes max.
 * (slice2)    Executor memory: 670K bytes avg x 2 workers, 670K bytes max (seg0).  Work_mem: 586K bytes max, 49986K bytes wanted.
 Memory used:  2048kB
 Memory wanted:  150356kB
 Optimizer: Postgres query optimizer
 Settings: optimizer=on
 Execution Time: 815.954 ms
(31 rows)
```

**Comment by lij55** [comment]
the result of this (https://github.com/greenplum-db/gpdb/issues/9902#issuecomment-613026896) sql on GP6 is strange but no assert failure any more. the result is attached.

closing this issue now
[issue_9902_result.txt](https://github.com/greenplum-db/gpdb/files/8388358/issue_9902_result.txt)
.
