### ISSUE TITLE
GP6.4   GPSS1.3.5  load json data error

### ISSUE THREAD

**Issue by liuzhliang** [greenplum-db/gpdb#9909]
GP版本6.4  GPSS版本1.3.5

导入kafka的json数据报错

20200413:16:19:18 gpss:etluser:gp_etl:030062-[DEBUG]:-rollback the batch 0 due to Failed to execute batch: pq: unsupported Unicode escape sequence  (seg3 slice1 10.100.19.2:6003 pid=15215)
20200413:16:19:18 gpss:etluser:gp_etl:030062-[ERROR]:-Job gpopdata_json failed: Failed to execute batch: pq: unsupported Unicode escape sequence  (seg3 slice1 10.100.19.2:6003 pid=15215)
20200413:16:19:18 gpss:etluser:gp_etl:030062-[ERROR]:-Failed to execute batch: pq: unsupported Unicode escape sequence  (seg3 slice1 10.100.19.2:6003 pid=15215)
Use following query to access the detailed error:
SELECT cmdtime, errmsg, COALESCE(rawdata, encode(rawbytes, 'escape')) AS rawdata
                FROM gp_read_error_log('"public"."gpkafkaloadext_73a8cfa767b441ae785d6a667c20b0c2"') WHERE cmdtime >= '2020-04-13 16:18:59.014502+08' AND cmdtime <= '2020-04-13 16:19:18.089793+08'

但是按照提示的sql到gp_read_error_log 查询 一条数据没有，目前没办法定位到错误数据 没办法修复 数据无法导入。

**Comment by Eulerizeit** [comment]
@lij55 is the PM for GPSS. 

Closing this issue here because gpss is a closed source component. Please reach out to support.
