### ISSUE TITLE
A problem of installation: command: gpinitsystem

### ISSUE THREAD

**Issue by WoodZzzzz** [greenplum-db/gpdb#9966]
#9164 # Greenplum version or build
greenplum-6.6.0-rhel6_x86_64.rpm
### OS version and uname -a
Linux 3.10.0-693.el7.x86_64  GNU/Linux
### Installation information ( pg_config )
SEG_PREFIX=gpseg
PORT_BASE=33000
declare -a DATA_DIRECTORY=(/home/gpdata/gp1 ..... /home/gpdata/gp4)
MASTER_HOSTNAME=10.***
MASTER_PORT=2345
MASTER_DIRECTORY=/home/gpdata/master
DATABASE_NAME=gpdb
MACHINE_LIST_FILE=/home/gpdata/all_segs
### Expected behavior
I hope I could install it sucessfully without inputting password in every step.
### Actual behavior
When I used 'gpinitsystem' to install greenplum. I needed to input the password of the current user at every step. So that I couldn't install it efficiently. 
### Step to reproduce the behavior
My English is poor. : ) Could you help me to fix this problem? Is this a problem with gp or with Linux OS ?

**Comment by kainwen** [comment]
I believe you need to use gpssh-exkeys to exchange ssh keys across the cluster.

Please refer to the doc https://gpdb.docs.pivotal.io/6-7/utility_guide/ref/gpssh-exkeys.html

**Comment by WoodZzzzz** [comment]
> I believe you need to use gpssh-exkeys to exchange ssh keys across the cluster.
> 
> Please refer to the doc https://gpdb.docs.pivotal.io/6-7/utility_guide/ref/gpssh-exkeys.html

Thanks for your reply at first. Here are still some questions: I am installing a stand-alone module. There are not any clusters in my environment. Should I still use 'gpssh-exkeys'?

**Comment by kainwen** [comment]
> > I believe you need to use gpssh-exkeys to exchange ssh keys across the cluster.
> > Please refer to the doc https://gpdb.docs.pivotal.io/6-7/utility_guide/ref/gpssh-exkeys.html
> 
> Thanks for your reply at first. Here are still some questions: I am installing a stand-alone module. There are not any clusters in my environment. Should I still use 'gpssh-exkeys'?

Even for one host gpdb, still need.

**Comment by WoodZzzzz** [comment]
Thanks a lot
