### ISSUE TITLE
CXXFLAGS is ignored by configure

### ISSUE THREAD

**Issue by d** [greenplum-db/gpdb#9980]
### Greenplum version or build
7.0.0 alpha / master branch (commit a7df6f9b7e5b as of writing)

### autoconf options used ( config.status --config )
./configure CXXFLAGS='-O0 -fno-omit-frame-pointer'

### Gripe
Our CXXFLAGS manipulation is fairly half assed. To wit, CXXFLAGS specified in the command line of `configure` is tossed away, unlike its brother CFLAGS. This makes it difficult for the user to take over C++ compilation tuning, say for example using `-O0` for faster build. To be fair, we used to _not do anything_ :tm:  prior to Oct 2016, so we've generally been on a positive trend.

**Comment by hlinnaka** [comment]
Starting with PostgreSQL v11, with the LLVM JIT compilation support, PostgreSQL's `configure` sets CXXFLAGS. We'll get those changes with the latest PostgreSQL merge, overriding the code we have now in GPDB's `configure.in`.

**Comment by d** [comment]
> Starting with PostgreSQL v11, with the LLVM JIT compilation support, PostgreSQL's `configure` sets CXXFLAGS. We'll get those changes with the latest PostgreSQL merge, overriding the code we have now in GPDB's `configure.in`.

With ORCA merged into the tree in 6X and master, we now have a stronger need for better handling `CXXFLAGS`. "Let's wait for the v12 merge to land" hardly serves us here. I've opened #9997 that addresses this issue with the following in mind:

1. It should minimize conflict with the v12 merge (heck I'll most likely be working on the merge)
1. It should be fairly straightforward to backpatch to 6.X

Would you take a quick look at that?
