### ISSUE TITLE
gpdb 6.7.0 gporca not support on arm64

### ISSUE THREAD

**Issue by ynqjwsm** [greenplum-db/gpdb#9994]
because of this x86 asm are not support

#define GPOS_ASMFP asm volatile ("movq %%rbp, %0" : "=g" (ulp));
#define GPOS_ASMSP asm volatile ("movq %%rsp, %0" : "=g" (ulp));

in

https://github.com/greenplum-db/gpdb/blob/1c8e9a99df3b3d5291c5f420fc3985541c0d60af/src/backend/gporca/libgpos/include/gpos/utils.h#L24

**Comment by ynqjwsm** [comment]
also at:

src/backend/utils/error/elog.c
196 | #define ASMFP asm volatile ("movq %%rbp, %0" : "=g" (ulp));

**Comment by Eulerizeit** [comment]
@vraghavan78 @asubramanya this issue was hit by @soumyadeep2007 and @d too on a project as well.

**Comment by hlinnaka** [comment]
This was fixed on master by commit 7c1891fb1a827542c0aa7a60e99e14086a6663ce. Closing. (I don't think there are plans to backport this)
